### ISSUE TITLE
Text does not fit in button Mobile View

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1002]
Admin 5.1.9

In the mobile view the following Text does not fit in the Button.

![Screenshot_20210620-201519_Gallery](https://user-images.githubusercontent.com/25422320/122684244-9798ae80-d204-11eb-8b26-137393b086a9.jpg)

![Screenshot_20210615-173123_Samsung Internet](https://user-images.githubusercontent.com/25422320/122684253-a8e1bb00-d204-11eb-8626-9ba0a87618a8.jpg)

**Comment by Feuer-sturm** [comment]
Admin 5.1.10

First screenshot "Slow connection": currently no possibility to trigger this
Second screenshot "Adapter Update" Is fixed. Text was removed, now to icons (v) and (x) are there :-)

**Comment by Apollon77** [comment]
Yes Admin 5.1.10 utransfers the data compressed, so rought twice as fast as before :-)
