### ISSUE TITLE
Settings for linkeddevices do not appear in new user interface/UI

### ISSUE THREAD

**Issue by tmycgn** [ioBroker/ioBroker.admin#1005]
When using the new user interface of the adapter, the settings of objects are no longer fully displayed. In my case the configuration of the adapter linkeddevices (https://github.com/Scrounger/ioBroker.linkeddevices) is completely missing. If I temporarily switch back to the old UI, they are displayed again.

![image](https://user-images.githubusercontent.com/82310796/123538953-83d6d600-d737-11eb-903f-8dea92eba2a1.png)

**Versions:**  
- Adapter Version: Admin 5.1.9
- Plattform: LINUX
- node.js: V12.22.1
- npm: 6.14.12
- js-controller: 3.3.14

**Comment by Apollon77** [comment]
Duplicate https://github.com/Scrounger/ioBroker.linkeddevices/issues/65 ... update of adapter needed
