### ISSUE TITLE
Benutzter RAM wird falsch dargestellt

### ISSUE THREAD

**Issue by Gosuwaldbear** [ioBroker/ioBroker.admin#1006]
In der "Hosts" Übersicht wird die benutzte CPU aber der freie RAM angezeigt.

**Comment by Apollon77** [comment]
Ja, da sist absicht so. Wer hat schon im Kopf wieviel RAM die Kiste hat? AM Ende ist für die Installation neuer bzw Betrieb von Adaptern der freie RAM viel wichtiger.
