### ISSUE TITLE
Adapter update windows shows to much information

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1009]
Admin 5.1.9

An update for [ValloxMV Adapter](https://github.com/hacki11/ioBroker.valloxmv) is available from 1.1.2 to 1.1.3
In the adapter update window the information for 1.2.0 is visible as well but 1.2.0 is not released yet (beta/stable)
![grafik](https://user-images.githubusercontent.com/25422320/124026009-7187c100-d9f1-11eb-98bb-736532f9789b.png)

In io-package.json with tag 1.1.3 the changelog until 1.1.3 is included
https://github.com/hacki11/ioBroker.valloxmv/blob/v1.1.3/io-package.json

Does Admin take the wrong io-package.json because changelog for 1.2.0 is shown?

In addition in adapter "Liesmich" (?) only a few changelog items are show but not the full changelog. Is this an admin or an adapter issue?
![grafik](https://user-images.githubusercontent.com/25422320/124027214-e7d8f300-d9f2-11eb-91fc-e361b5ff0a8d.png)

Discussion in iobroker forum: https://forum.iobroker.net/topic/34188/adapter-valloxmv-steuerung-lüftungsanlagen-der-fa-vallox/53

**Comment by Feuer-sturm** [comment]
Admin 5.1.10

Steps to reproduce
- Vallox Adapater 1.1.3 was installed
- Update Admin 5.1.9 to Admin 5.1.10
- Downgrade Vallox Adapter to 1.1.2
- Check update Information for Vallox Adapter


The first problem that informations were show for version 1.2.0 is fixed
![grafik](https://user-images.githubusercontent.com/25422320/125161756-661c5e80-e184-11eb-8b31-7dc4a1bccfe4.png)


The second problem "In addition in adapter "Liesmich" (?) only a few changelog items are show but not the full changelog. Is this an admin or an adapter issue?" is still there

**Comment by GermanBluefox** [comment]
It only shows, what is in package.json: https://github.com/hacki11/ioBroker.valloxmv/blob/master/io-package.json#L11

It does not parse readme

**Comment by Apollon77** [comment]
@GermanBluefox Yes and this is the issue ... if someone prepared on GitHub master a new version which was not yet released then Admin already shows  that changelog part. So Admin (or repo biuild scipt??) should filter out entries for news for versions higher then the "npm"/ "rstable" one

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 Was there a change with Admin 5.1.10? Because in my screenshot (https://github.com/ioBroker/ioBroker.admin/issues/1009#issuecomment-877623930) version 1.2.0 is not shown any more but is is available in https://github.com/hacki11/ioBroker.valloxmv/blob/master/io-package.json#L6

**Comment by GermanBluefox** [comment]
Please, close the issue.

**Comment by Feuer-sturm** [comment]
@GermanBluefox I will close the issue because main issue is fixed.

Can you please answer me if this is ad admin or an adapter issue? Behavior is there with Admin 5.1.11 as well.
"In addition in adapter "Liesmich" (?) only a few changelog items are show but not the full changelog. Is this an admin or an adapter issue?" https://github.com/ioBroker/ioBroker.admin/issues/1009#issue-934103496
