### ISSUE TITLE
Cannot delete object tree of mqtt

### ISSUE THREAD

**Issue by Easyrunner** [ioBroker/ioBroker.admin#1010]
It's not possible to delete the complete tree as in the picture shown.
It looks like that it grows and blocking more and more the system.

When I try to delete the tree starting at "0" I got the error message "Cannot delete object ERROR not exists"
![2021-07-01 08_56_00-objects - raspberrypi](https://user-images.githubusercontent.com/47195199/124083765-8c3c5300-da4e-11eb-827a-d1bf3ba9fa63.jpg)

**Comment by Apollon77** [comment]
Are these objects still there after reload in objects tab?

**Comment by Easyrunner** [comment]
Yes, after reload they are still existing.

**Comment by Easyrunner** [comment]
...and the mqtt adapter is stopped!

**Comment by Apollon77** [comment]
Can you try to open up to the last  node in that "tree" and show whats in there? because all these elements do not have a objects ... so there need to be one entry "at the end of the chain"

**Comment by Easyrunner** [comment]
Here it is
![2021-07-01 09_50_09-objects - raspberrypi](https://user-images.githubusercontent.com/47195199/124086970-da9f2100-da51-11eb-89a9-fee385b3dd67.jpg)

**Comment by Apollon77** [comment]
try to delete that one "last" entry in admin

**Comment by Easyrunner** [comment]
I started mqtt adapter and it was gone.
No more "0" tree.

Than I stopped mqtt and uploaded the object tree mdificated by JASON parser. After a while there came the "bad tree" again.
mqtt adapter was the whole time stopped!

**Comment by Easyrunner** [comment]
Maybe I'm not at the end of the tree, but I can't expand the tree, because the "Copy" sign comes.
How can I move the column width?
![2021-07-01 10_10_08-objects - raspberrypi](https://user-images.githubusercontent.com/47195199/124090298-ffe15e80-da54-11eb-8348-d518ea433aa1.jpg)

**Comment by Apollon77** [comment]
There are settings for the admin screen where you can set column widths

**Comment by Easyrunner** [comment]
I tested a lot and I could delete the tree (it just takes a while)

I cleaned the JSON table and upload again.
It looks good, but when I start mqtt it will create again a bad sign and after secound it starts to create this tree.
So I think it is an mqtt topic.

**Comment by Apollon77** [comment]
Please post JSON here

**Comment by Feuer-sturm** [comment]
@Easyrunner Is your issue still active?

**Comment by Feuer-sturm** [comment]
No feedback. Issue closed.
