### ISSUE TITLE
Reduce the size of tree views

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1014]
In comparison to Admin 4, all tree views (objects list, ID picker, etc.) are **HUGE** in Admin 5. Here's a comparison where you can see that the same space that was enough for 21 rows in Admin 4 now is just enough for 10 in Admin 5:
![index](https://user-images.githubusercontent.com/17641229/124605689-7b377b80-de6c-11eb-801d-4f15df53b449.jpg)

This is nice for mobile but if you are on a desktop PC, that greatly reduces the overview and leads to a lot of scrolling. I suggest:
* reducing some of the empty space, e.g. here (highlighted red):
![grafik](https://user-images.githubusercontent.com/17641229/124605730-82f72000-de6c-11eb-9482-2045fadbaeb6.png)
* reducing the size of the folder icons by 30-50%
* and reducing the space above, below and between the captions of each row

Here's a really quick and dirty mock up how that could look like - left = new vs. right = old:
![grafik](https://user-images.githubusercontent.com/17641229/124607425-21d04c00-de6e-11eb-8cc2-a9d8e9dcb6d6.png)
(of course that needs some fine-tuning - I'd keep the borders between rows)

**Comment by GermanBluefox** [comment]
Done, a bit narrower now.

**Comment by GermanBluefox** [comment]
please test 5.1.11

**Comment by AlCalzone** [comment]
Doesn't look like 5.1.11 was released

**Comment by Apollon77** [comment]
yes, build error https://github.com/ioBroker/ioBroker.admin/runs/3049822345?check_suite_focus=true#step:5:25

**Comment by AlCalzone** [comment]
Much better 👍🏻
