### ISSUE TITLE
Admin 5 - JSON Config - Repeated password fields are validated regardless of visibility

### ISSUE THREAD

**Issue by Excodibur** [ioBroker/ioBroker.admin#1015]
It seems like input fields of `type: "password"` when combined with `repeat: true` are always validated, even if they are _hidden_ or _disabled_.

For instance with https://github.com/ioBroker/ioBroker.influxdb/blob/2c6e673607293ed59cfdb011fbe6726424230053/admin/jsonConfig.json#L55-L59 the input field **Password** is only used for Influx 1 authentication, whereas for Influx 2 the field **Token** is used.

If the user on the config page would:

1. Select **DB Version** "Influx 1" and fill out only one **Password** field
2. Switch to **DB Version** "Influx 2" and fill out all (visible) fields as expected
3. Attempt to press **Save**

Step (3) would not be possible, as **Save** is still greyed out due to the now hidden/unused input fields of type "password" not being equal.

Is there a way to avoid this?

**Comment by GermanBluefox** [comment]
Please try 5.1.10

**Comment by Excodibur** [comment]
Thanks, with 5.1.10 the issue is gone now! Previously I was using 5.1.7.
