### ISSUE TITLE
getExtendableDevices does not work with Safari on iOS devices

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#1018]
getExtendableDevices() returns undefined on safari. Other browsers work fine. 

Bug was initially reported here https://forum.iobroker.net/post/624324

**Comment by sbormann** [comment]
@GermanBluefox can you help?

**Comment by GermanBluefox** [comment]
Which of 5500 messages is meant?
I could not find any calls of getExtendableDevices in Admin

**Comment by sbormann** [comment]
When opening the settings of iqontrol with safari the getExtandableDevices-Function in this line
https://github.com/sbormann/ioBroker.iqontrol/blob/53348762a67eda039af4ffffb1ffe2ac5148aaa6/admin/index_m.js#L2202
returns undefined.

**Comment by Apollon77** [comment]
So it is about getExtendableInstances and not *Devices???

**Comment by sbormann** [comment]
Oh sorry, my fault - of course you are right. It is getExtendableInstances!

**Comment by GermanBluefox** [comment]
> When opening the settings of iqontrol with safari the getExtandableDevices-Function in this line
> https://github.com/sbormann/ioBroker.iqontrol/blob/53348762a67eda039af4ffffb1ffe2ac5148aaa6/admin/index_m.js#L2202
> returns undefined.

It is not possible, as all 3 branches return Array: https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/public/js/adapter-settings.js#L1237

**Comment by sbormann** [comment]
Hab mir jetzt mal ein Macbook geliehen, hier das Ergebnis:
![image](https://user-images.githubusercontent.com/49171332/128251282-42a73c69-ce67-4507-b3a3-158d5d1664ce.jpeg)

Die aktuellen Safari Versionen sollten ja async unterstützen. An anderer Stelle klappt das auch. Denke, das liegt an anderer Stelle.

**Comment by Apollon77** [comment]
Debugge doch mal in die getExtendableInstances mit rein und schau was als Socket Antwort kommt

**Comment by sbormann** [comment]
Hatte Glück, konnte mir heute noch mal für länger ein MacBook ausleihen und habe den Fehler identifiziert. Ich hatte zwei mal die Variable result deklariert. Das hat Safari nicht vertragen - aber leider auch keine entsprechende Fehlermeldung ausgegeben. 

=> Also insgesamt KEIN Fehler von admin.

Danke für die Hilfe!
