### ISSUE TITLE
Error when showing history data

### ISSUE THREAD

**Issue by Moppedman** [ioBroker/ioBroker.admin#1019]
I updated admin adapter from 5.1.8 to 5.1.10

I observed the following issue:

I went to Objects and selected a data set were I record data in history. I wanted to review the latest data recorded by clicking the wheel at the very end of the marked line

![image](https://user-images.githubusercontent.com/85433777/125189803-3f206400-e23a-11eb-914d-1a1f74197f8b.png)

I got the following Error

![image](https://user-images.githubusercontent.com/85433777/125189735-ea7ce900-e239-11eb-9fc7-92a5c0ffcfdd.png)

When rolling back to 5.1.8 the issue disappeared again.

Moppedman

**Comment by GermanBluefox** [comment]
please test 5.1.11

**Comment by nelzon101** [comment]
![image](https://user-images.githubusercontent.com/34646672/125409995-bbdb4b80-e3bc-11eb-9507-ac385bcde71b.png)

same problem like moppedman.

V5.1.11

Gruß nelzon

**Comment by Moppedman** [comment]
Hi Blufox,

I updated admin to 5.1.12 and have no issues as before. Thanks for quick response & fix.

Moppedman
