### ISSUE TITLE
Falsches Changelog im stable

### ISSUE THREAD

**Issue by Wildbill-Z** [ioBroker/ioBroker.admin#1021]
Ich bin in iobroker auf dem stable-Zweig. Mir wurde für den Admin-Adapter das Update von 4.2.1 auf 4.2.2 angeboten. Ich klicke bei Updates immer auf Changelog um zu schauen, ob es etwas zu beachten gibt. Das Changelog wurde allerdings nur für die Latest-Version 5 angezeigt. Das Changelog für die 4er musste ich mir dann auf Github selbst suchen.
Da vermutlich die meisten Produktiv-Systeme auf stable laufen und man dort eher auf den Changelog achtet, um sich nichts abzuschiessen, wäre es sinnvoll, wenn dann auch dieser Changelog direkt angezeigt wird, auch, da viele mit stable vielleicht weniger Erfahrung mit Github haben.
Vielleicht lässt es sich ja auch einrichten, dass, abhängig von der installierten Version oder dem eingestellten Repo das jeweilige Changelog gezogen wird?!

Gruss, Jürgen

**Comment by GermanBluefox** [comment]
Ist fixed in admin5.

**Comment by Wildbill-Z** [comment]
Danke für die rasche Antwort. Gilt das dann grundsätzlich für alle Adapter oder muss jeder Adapter-Developer selbst dafür sorgen, dass ein korrektes Changelog angezeigt wird?
Kannst ja noch antworten, das Issue mache ich mal zu, ist ja gelöst.

Gruss, Jürgen
