### ISSUE TITLE
wenn ich über Edge auf Objekte gehe bekomme ich immer eine Fehlermeldung im Browser 

### ISSUE THREAD

**Issue by jayjay2601** [ioBroker/ioBroker.admin#1022]
index.js:18 iobroker.admin@5.1.9
instrument.ts:129 [2021-07-18T18:16:45.179Z] Try to connect
VM23:319 edge Translation started
translateInternal @ VM23:319
instrument.ts:129 [ADAPTERS] getAdapters
instrument.ts:129 [ADAPTERS] getAdaptersInfo
2instrument.ts:129 [ADAPTERS] Render
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.factoryResetFromSwitch
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.firmware
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.firmwareupdate
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.hostname
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.id
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.name
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.online
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.overtemperature
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.protocol
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.reboot
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.rssi
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.temperatureC
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.temperatureF
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.type
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.uptime
instrument.ts:129 + subscribe shelly.0.SHDM-1#D3EB5B#1.version
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.factoryResetFromSwitch
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.firmware
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.firmwareupdate
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.hostname
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.id
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.name
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.online
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.overtemperature
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.protocol
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.reboot
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.rssi
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.temperatureC
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.temperatureF
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.type
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.uptime
instrument.ts:129 > stateChange shelly.0.SHDM-1#D3EB5B#1.version
6instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Oi (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5491031)
    at jl (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5502843)
    at t.unstable_runWithPriority (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5529432)
    at Wa (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5445818)
    at Vl (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5500801)
    at ml (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5496887)
    at http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5446041
    at t.unstable_runWithPriority (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5529432)
    at Wa (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5445818)
    at Ga (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5445986)
    at Ua (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5445921)
    at hl (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5494031)
    at Object.enqueueForceUpdate (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5450246)
    at s.m.forceUpdate (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:5521030)
    at http://192.168.178.51:8081/static/js/2.dc013868.chunk.js:1:11300
    at r (http://192.168.178.51:8081/static/js/5.0b318a3b.chunk.js:2:6137066)
(anonymous) @ instrument.ts:129
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.factoryResetFromSwitch
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.firmware
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.firmwareupdate
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.hostname
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.id
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.name
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.online
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.overtemperature
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.protocol
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.reboot
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.rssi
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.temperatureC
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.temperatureF
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.type
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.uptime
instrument.ts:129 - unsubscribe shelly.0.SHDM-1#D3EB5B#1.version

**Comment by Apollon77** [comment]
Geht auch irgendetwas nicht oder geht alles?

**Comment by GermanBluefox** [comment]
Cache löschen?

Ich kann das nicht reproduzieren: 
![image](https://user-images.githubusercontent.com/4582016/126510159-cbfa1ad0-be25-431f-a3c0-447140f69034.png)

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
