### ISSUE TITLE
Admin 5.1.12 "Dauerladen" der GUI unter Chrome; in Firefox funktioniert die GUI tadellos.

### ISSUE THREAD

**Issue by MBeeken73** [ioBroker/ioBroker.admin#1023]
Hallo zusammen,
Admin 5.1.12 "Dauerladen" der GUI unter Chrome; in Firefox funktioniert die GUI tadellos.
Cache im Chrome schon gelöscht. Ist dieses "Problem" bekannt?

Gruß
Michael

**Comment by Apollon77** [comment]
Zeigt die Browser Konsole irgendeinen Fehler an?

**Comment by MBeeken73** [comment]
Hier mal ein Screenshot.

![Fehler](https://user-images.githubusercontent.com/48216471/126371165-8b38b3b2-3a12-40c3-a46a-b39653905598.JPG)

**Comment by MBeeken73** [comment]
Hier mal ein Screenshot.

![Fehler](https://user-images.githubusercontent.com/48216471/126371436-f2b6194e-8113-4ff2-8e4d-48e0bbaeabb5.JPG)

**Comment by GermanBluefox** [comment]
Geht auch ohne SSL?

**Comment by MBeeken73** [comment]
Der Virenscanner "funkt"dazwischen ...
Schalte ich den https Scanner aus, funktioniert es .... Beim Firefox ist diese Einstellung völlig egal, da funktioniert es immer.

![Screenshot 2021-07-21 195727](https://user-images.githubusercontent.com/48216471/126536995-92eb86fc-fa99-405c-808f-f9097698dc29.png)

**Comment by DuBass858** [comment]
The same situation happens only with ssl

**Comment by Apollon77** [comment]
Post output of "iobroker cert view" please ...

**Comment by DuBass858** [comment]
{
  "certificateFilename": null,
  "certificate": "-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----\r                                                                                                                                                             \n",
  "serialNumber": "0848fd3f7bc41adcbe",
  "signature": "sha256WithRSAEncryption",
  "keyLength": 2048,
  "issuer": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "7e4805a252caec3f7eeed95aba55c8417d8ad7a7"
  },
  "subject": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "raspberrypi",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "77790a0c1de11079759c543537d11e1b359ac5d1"
  },
  "dnsNames": [
    {
      "type": 2,
      "value": "raspberrypi"
    }
  ],
  "keyUsage": {
    "id": "2.5.29.15",
    "critical": true,
    "name": "keyUsage",
    "digitalSignature": true,
    "nonRepudiation": false,
    "keyEncipherment": true,
    "dataEncipherment": true,
    "keyAgreement": true,
    "keyCertSign": true,
    "cRLSign": true,
    "encipherOnly": true,
    "decipherOnly": true
  },
  "extKeyUsage": {
    "id": "2.5.29.37",
    "critical": false,
    "name": "extKeyUsage",
    "serverAuth": true,
    "clientAuth": true
  },
  "validityNotBefore": "2021-07-07T06:06:45.000Z",
  "validityNotAfter": "2022-07-07T06:06:45.000Z"
}

**Comment by Feuer-sturm** [comment]
@DuBass858 @MBeeken73 Is this issue still active? Please check with current admin 5.3.7

**Comment by DuBass858** [comment]
> @DuBass858 @MBeeken73 Is this issue still active? Please check with current admin 5.3.7

Now it works! 
Thank you!
