### ISSUE TITLE
Dauerladen unter Admin 5.1.12

### ISSUE THREAD

**Issue by BigBen667** [ioBroker/ioBroker.admin#1025]
Ich habe jetzt schon mehrmals eine Error in GUI Meldung bekommen. 

Nutze einen raspi 3 und wenn ich auf Info gehe fängt die GUI an zu laden und zeigt auch die Seite mit eventuellen Aktualisierungen an. Das Fenster "meine Adapter" wird nicht aktualisiert und scheint sich in Dauerschleife zu befinden. Oftmals hängt sich der iobroker nun auch auf. Ein Wechsel zu einem anderen Menüpunkt kann gut gehen ist jetzt aber auch mehrmals in obig genannter Meldung geendet.

Bei drücken von F12, wie in der GUI Meldung beschrieben, zeigt:

Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden.

Admin 5.12
Node js: 12.22.2
Js-version 3.3.14

**Comment by Apollon77** [comment]
Jetzt musst Du bitte nur noch sagen welche GUI Meldung DU meinst, Vllt ein screenshot? Sagt die Browser Konsole irgendwas?

**Comment by meicker** [comment]
@Apollon77 
Hi Ingo, ich habe glaube ich das gleiche Problem. Die Adapter werden nicht geladen. Das hat aber schon funktioniert und kam mE überraschend, es sei denn es hängt irgendwie mit Likeddevices zusammen was ich jetzt runtergeworfen habe weil es mir gestern ein ganz anderes Problem eingebrockt hatte ... Das sagt die Konsole beim laden :
<img width="2558" alt="grafik" src="https://user-images.githubusercontent.com/11345937/126223228-49ba7069-7254-4b61-bb30-21f1a1155039.png">

**Comment by meicker** [comment]
@BigBen667 
versuche mal bitte in den Einstellungen der Instanz vom Admin den Schalter 'Alte Benutzeroberfläche' zu aktivieren, dann zu speichern. Bei mir wurde dann der Adapter Inhalt wieder angezeigt. Danach kannst Du das wieder zurück setzen.

**Comment by BigBen667** [comment]
@Apollon77 

![Screenshot 2021-07-20 194332](https://user-images.githubusercontent.com/87669556/126371569-c561d741-0250-4978-8df1-6a508d95dad1.png)

Das ist die GUI Meldung im Firefox

![Screenshot 2021-07-20 194532](https://user-images.githubusercontent.com/87669556/126371677-a6576de9-aaea-416d-8b5b-ec021216537b.png)

Und das die Fehlermeldung bei Drücken von F12 in der Übersicht Debugger - Fehler

Hoffe diese Angaben sind für Euch Aussagefähig genug. Für mich sind das böhmische Dörfer! ;-)

**Comment by BigBen667** [comment]
@Apollon77 

Sorry muss mich hier erst etwas zurechtfinden. Screenshots s. unten

**Comment by BigBen667** [comment]
> 
> 
> @BigBen667
> versuche mal bitte in den Einstellungen der Instanz vom Admin den Schalter 'Alte Benutzeroberfläche' zu aktivieren, dann zu speichern. Bei mir wurde dann der Adapter Inhalt wieder angezeigt. Danach kannst Du das wieder zurück setzen.

@meicker 

Ja, das im Grundsatz geholfen! Mein System hat das Speichern und Schließen in der Admin Instanz aber auch erst wieder mit einem weiteren GUI Fehler quittiert. Ich füge auch hier mal die Screenshots mit bei:

![Screenshot 2021-07-20 195740](https://user-images.githubusercontent.com/87669556/126373566-d89feb06-9663-497d-9e10-ae3cb701b7a4.png)
![Screenshot 2021-07-20 195849](https://user-images.githubusercontent.com/87669556/126373587-f883cdc8-9a1b-40dc-8207-aeec328733d9.png)

![Screenshot 2021-07-20 200006](https://user-images.githubusercontent.com/87669556/126373608-b0bb5ee6-b798-40f0-a492-26d470150451.png)

**Comment by GermanBluefox** [comment]
Try 5.1.13

**Comment by BigBen667** [comment]
@GermanBluefox 

Nein, das Fenster "Meine Adapter" welches bei mir neuerdings "Fehler und Probleme" heißt bleibt in der Dauerladeschleife.

![Screenshot 2021-07-21 215800](https://user-images.githubusercontent.com/87669556/126552090-5efc248f-422a-4d0d-860b-1c0a081dfd2e.png)

**Comment by Apollon77** [comment]
AAaaaaghhhh ... das ist der Info Adapter und NICHT Admin!!

**Comment by BigBen667** [comment]
Sorry, da hab ich wohl nen Bock geschossen. 

Hier closen und im Info Adapter ein neues Issue aufmachen?

**Comment by Apollon77** [comment]
Das gibt es bei Info schon :-) Der ist gerade noch nicht kompatibel mit Admin5
