### ISSUE TITLE
Admin 4.2.2: Config page shows only html source code

### ISSUE THREAD

**Issue by KoMa1978** [ioBroker/ioBroker.admin#1026]
Hi all,

today I updated my iobroker install, which means, the admin adapter was updated from 4.2.1 to 4.2.2.

The config pages works fine if I connect directly to https://host:8081.
But if I connect to "hostname.net.internal" it does not work any more. I'm running a nginx reverse proxy on the same host that redirects traffic to https://hostname.net.internal to https://127.0.0.1:8081. This setup works fine since years, but with the update to 4.2.2 it stopped and the admin config page only shows html source code:
![example](https://user-images.githubusercontent.com/57285166/126314115-699b32a8-a82f-4737-8336-397ba4bd4199.jpg)

If seen some differences when inspecting the web page in Chrome:
REVERSE PROXY:
![nginx](https://user-images.githubusercontent.com/57285166/126314107-2d24c0f2-4499-488d-8479-850e4f1d8046.jpg)
DIRECTLY:
![direct](https://user-images.githubusercontent.com/57285166/126314112-cfa8a456-2039-4441-bc07-d103353e52af.jpg)

It makes no difference if I change the redirect in NGINX from 127.0.0.1 to the real ip. As soon as the traffic flows via the reverse proxy, this page is displayed as source. All other instances (info, web, daikin, homematic, ... config pages are working fine.

Any idea why this happens on the admin config page? Any idea how to troubleshoot?

Thanks a lot,
 KoMa 1978

**Comment by Apollon77** [comment]
Can you please check Admin 5 from latest? 

This will be the future and admin 4.2.2 is just a "legacy fix backport" and kind of the very very last version of the 4.x chain.
If you need to stay on 4.x please downgrade to Admin 4.2.1

**Comment by KoMa1978** [comment]
I tried downgrading to 4.2.1 and 4.1.2 as well but issue still occurs. I tried Chrome and Firefox.

Upgrading to 5.1.2 solved this issue.

**Comment by GermanBluefox** [comment]
> I tried downgrading to 4.2.1 and 4.1.2 as well but issue still occurs. I tried Chrome and Firefox.
> 
> Upgrading to 5.1.2 solved this issue.

There are must be an error message in browser console and I assume the content-type returned by nginx is not html/text, but plain/text...

**Comment by KoMa1978** [comment]
maybe but unlikely.

Why should this always happen on admin config but on no other tab?

NGINX config is pretty simple:

server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;

        ssl_certificate /etc/ssl/1.2.3.4.cer;
        ssl_certificate_key /etc/ssl/1.2.3.4.key;

        location / {
                proxy_pass https://127.0.0.1:8081/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Accept-Encoding "";
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout  2073600;
                proxy_http_version 1.1;        }
}

But since 5.1.2 is working and looks much better, I think we should not invest time in fixing this ;-)
