### ISSUE TITLE
Log-Level-Einstellung passt nicht

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#1027]
In den Basiseinstellungen habe ich bei "Standarteinstellungen für neue Instanzen"  "warn" eingetragen. Bei Neuinstallation eines Adapters wird allerdings die Logstufe "Info" übernommen. 

Node.js: 12.22.2
NPM: 6.14.13
Js-version: 3.3.14

**Comment by GermanBluefox** [comment]
Das sit Fehler für js-controller und nicht admin.
Aber ich habe jetzt noch mal getestet und konnte nicht reproduzieren.
