### ISSUE TITLE
Admin 5.1.12 column missing in Instances

### ISSUE THREAD

**Issue by KrX3D** [ioBroker/ioBroker.admin#1028]
Hello,

Admin v 5.1.12

when im in expert mode i cant see the Schedule and Restart columns in Instances, so i cant set a cron restart value,

when i set in admin to use the old gui i can see them.

**Comment by Apollon77** [comment]
In Admin 5 they are shown when you expand the instance entry in the list ... Click on it ...themn you see it

**Comment by KrX3D** [comment]
![image](https://user-images.githubusercontent.com/18599852/126324239-9a177248-718d-4ac3-95b9-496d560bd0cb.png)

Hello,

not sure where since i cant see them expanding the instance
