### ISSUE TITLE
Einheitliche, optimierte Ansichten

### ISSUE THREAD

**Issue by soef** [ioBroker/ioBroker.admin#103]
Hallo,

ich habe einmal begonnen die Ansichten im ioBroker.admin einheitlich zu gestalten. Bisher haben da viele Ansichten ein komplett unterschiedliches Aussehen. Es beginnt schon mit unterschiedlichen Tabellenheadern, unterschiedlichen Zeilenhöhen, Schriftgrößen, Buttongrößen usw. Ich habe einmal mit den Ansichten: Adapters, Instances und Objects begonnen. Für Objects habe ich eine zweite, Objects1 benannt. Diese kann nach Abschluss der Arbeiten aber zur Objects-Ansicht werden. Die Arbeit und Tests an diesen drei Ansichten sind noch nicht abgeschlossen. Ich glaube es ist aber schon ein guter Anfang.

Im Anhang einmal Screenshots der genannten drei Ansichten. Der Source ist auf github. Einen Pull request habe ich noch nicht gestellt, da noch nicht alles abgeschlossen ist.

Was hällst du oder ihr von dem Umbau?

Anmerkungen:

- Es sind sehr viele Kleinigkeiten und Details angepasst, bzw. erweitert worden.
- Auch wurden einige Dinge vereinfacht oder anders dargestellt.
- Ich habe die Lib collResizable vaon 1.5 auf Version 1.6 angehoben, da mit der Version einige Fehler behoben wurden.
    Z.B. die dynamische Größenanpassung der fancytree-Tabellen.
- Einheitliche Zeilenhöhe von derzeit 25px. Kann aber einfach einheitlich angepasst werden.Ich glaube 25px sind ein gutes Mittelmass der bisher verwendeten Höhen.   
- Randabstände und Ellipsis in Tabellen
- Icon-Größen angepasst, so dass auch sie nicht an den Spalten und Zeilenrändern kleben
- Sortierung der Adapter Liste.
- Icons für die unterschiedlichen Adaptergruppen wurden aus Übersichtsgründen entfernt
- Zu intensive Farben vermieden.
- mehr oder weniger einheitliche Spaltenüberschriften.
- Taste F2 in Objects-View zum umbenennen eines Objects eingefügt. Kann auch verwendet werden,
    wenn das Objekt zuvor noch keinen Namen hatte.
- Einheitliche Buttongröße und Sortierung über den Listen.
- Eigentlich könnte die Auswahl des Hosts auch weggelassen werden, wenn es nur den lokalen Host gibt.
    Ohne einen weiteren Host ist die Auswahl überflüssig, (müsste noch gemacht werden)
- Icon-Spalte in der Objects-View entfernt und das Icon in die Spalte Name aufgenommen.
- Aussehen der Tabs umgestaltet. Moderneres aussehen. Es sollte möglichst keine 3D Elemente mehr
verwendet werden. Ist nicht mehr zeitgemäß.
- vieles, vieles mehr.

PS.: Der source muss noch gesäubert werden, da noch sehr viele auskommentierte Stellen enthalten sind.

Gruß, soef

![objects](https://user-images.githubusercontent.com/7615985/32175578-aa196ae6-bd85-11e7-97ac-cc36e6c8e813.png)
![adapters](https://user-images.githubusercontent.com/7615985/32175579-aa38b0ae-bd85-11e7-93dc-6683ead430ae.png)
![instances](https://user-images.githubusercontent.com/7615985/32175580-aa589c34-bd85-11e7-8def-e065556d95e1.png)

**Comment by GermanBluefox** [comment]
Sieht sehr cool aus. Ich habe nur Angst, da ich auch daran arbeite, irgendwann wird es schwer zu mergen.
Wie weit bist du? Dann sollte es V2 sein. :)

**Comment by GermanBluefox** [comment]
Wenn wir schon über umstyen reden: so sieht meine Traumidee aus :)
![image](https://user-images.githubusercontent.com/4582016/32196794-1df18444-bdc2-11e7-92ba-4ee18b636b5d.png)

**Comment by GermanBluefox** [comment]
Weißt du vielleicht: Wie kann ich so was implementieren? Oder mir dabei helfen?
![image](https://user-images.githubusercontent.com/4582016/32197625-4242bffe-bdc5-11e7-9bc8-c7c595059c0c.png)

Das gleiche für Groups und Users.

**Comment by Apollon77** [comment]
Wäre ein super Fortschritt ... !!

**Comment by soef** [comment]
Hallo,
 
vorab: meine Hauptintension war ein einheitliches, konsequentes, modernes Aussehen des ioBroker.admins.
 
zu Deiner "Traumidee": An ein vertikales Menü links hatte ich auch schon gedacht. Ist eigentlich auch sehr verbreitet, wenn es bei Bedarf von links ausgefahren wird. Dauerhaft sichtbar nimmt es horizontal zu viel Platz in Anspruch. 

So ein Menü bedeutet aber auch einen Klick und eine Maus- oder Handbewegung mehr um eine andere View zu aktivieren. Bei der normalerweise geringen Anzahl auswählbaren View ist eigentlich das horizontale Menü besser geeignet. Bei Bedarf kann man noch Untermenüs schaffen.

Wenn du temporär meine github Version installierst, kannst du den Stand  sehen. Probiere es einfach einmal. Ich glaube es lohnt sich.

**Comment by GermanBluefox** [comment]
Es lohnt sich natürlich. :)
Sieht klasse aus:
![image](https://user-images.githubusercontent.com/4582016/32213921-8248ef30-be1d-11e7-8fbe-3fb4599c43d7.png)

**Comment by GermanBluefox** [comment]
Ich finde die Lämpchen tick zu klein..
Vielleicht so (1em)?
![image](https://user-images.githubusercontent.com/4582016/32271766-adfe9114-befb-11e7-881e-a6bf4220fa22.png)
War (0.55em):
![image](https://user-images.githubusercontent.com/4582016/32271784-bf2058c4-befb-11e7-956f-4e1d02e95c3d.png)

**Comment by Apollon77** [comment]
vllt "die mitte dazwischen? Das Icon des Adapters rechts daneben sollte größer sein finde ich persönlich ...

**Comment by soef** [comment]
Hab's mal angepasst...

**Comment by soef** [comment]
Oops, welchen Browser verwendest du? Der blaue Streifen unter dem aktiven Tab und der Dunkle unter dem rechten Pfeil sind eigentlich nicht richtig.

**Comment by GermanBluefox** [comment]
Chrome

**Comment by GermanBluefox** [comment]
>Hab's mal angepasst...
Super

**Comment by soef** [comment]
Hab' den States und Events Tab auch einmal angepasst.

Ich nutze auch hauptsächlich Chrome mit Windows 10. Welches OS nutzt du?

**Comment by GermanBluefox** [comment]
Windows 10.

Es ist wegen:
#tabs-ul li a{
    /*font-weight: normal !important;*/
    /*background-color: #efefef;*/
    height: fit-content;
    font-weight: normal !important;
    margin:0;
    /*padding: 4px 15px 0 15px;*/
}
Wenn ich das auf
height: 100%;
Dann gibt es keine Linie mehr. Diese Linie ist Hintergrund vom "li"
[image: Встроенное изображение 1]


2017-11-05 9:43 GMT+01:00 Soef <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Obwohl mit der Linie auch interessant aussieht. :)

**Comment by soef** [comment]
Stimmt, es sieht interessant aus. Aber eigentlich sollte der Hintergrund des aktiven Tabs mit der  Hintergrundfarbe der aktiven View übereinstimmen. Also gehört quasi der aktive Tab zur Fläche der aktiven View und sollte nicht durch den blauen Streifen unterbrochen werden..

Man könnet hingehen und die blaue Linie oberhalb des aktiven Tabs anordnen. Aber das sind Feinheiten die man später noch angehen kann.

Eine Frage zum admin-Adapter: Können wir eigentlich node.js 4.xx voraussetzen?

**Comment by GermanBluefox** [comment]
Wir haben offiziell alles unter 4 abgekündigt.

**Comment by soef** [comment]
Hallo, hab' ein paar weiter Views adaptiert. Vielleicht schaust du dir den aktuellen Stand einmal an und sagst mir deine Meinung.

**Comment by soef** [comment]
btw. ich weiß nicht, ob du es mitbekommen hast, ich habe die admin.css auf less umgestellt. Änderungen müssen also an der .less vorgenommen werden.

**Comment by GermanBluefox** [comment]
Es geht schon fast alles :)
Das hier weiß ich nicht woher das kommt:
![image](https://user-images.githubusercontent.com/4582016/32973643-ebb0d472-cbf8-11e7-8a78-e65561111ead.png)


Das die Hystory Knöpfe abgeschnitten sind.

**Comment by xmace** [comment]
Ich find die neue Optik sehr gut. Vielen Dank an euch beide!

Frage, über das iobroker.pro Admin panel sieht alles noch alt aus, liegt dann am cloud adapter, oder?

**Comment by Apollon77** [comment]
beta wird aktuell per cloud nicht augeliefert, von daher geht Cloud immer auf den "alten" admin
