### ISSUE TITLE
Install specific version of an adaper - Only last 7 versions available

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1030]
Admin 5.1.13

If a user wants to install a specific version of an adapter only the last 7 versions are shown.
I am not sure if it is a feature request or a bug.

ical Adapter:
![grafik](https://user-images.githubusercontent.com/25422320/126641076-3c3be3e3-823c-402f-b794-fdc5f339eca6.png)

My expectation was to see all available versions. Is there a reason for the restriction?

**Comment by Apollon77** [comment]
The adapter itself defined this how many entries are in the io-package news section ... We have no real way else to determine which are "good" or "bad" versions ...
