### ISSUE TITLE
Icon for "formula" is misleading

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1031]
**Describe the bug**  
The formula "icon" is currently the mathematical symbol for a sum (Σ). IMO this can be misleading because you're not supposed to enter a sum there, but rather a function or formula.

Using an icon similar to Excel would be more fitting:
![grafik](https://user-images.githubusercontent.com/17641229/126643246-0589c863-7538-4e6f-abb6-7d4b162a8433.png)

_(also posted this in https://github.com/ioBroker/ioBroker.devices/issues/85)_

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/126990256-f898915e-5282-47dd-a9f6-b589fe2ddc33.png)
in 5.1.15

**Comment by Feuer-sturm** [comment]
Admin 5.1.23

formular icon is available
![grafik](https://user-images.githubusercontent.com/25422320/128610276-790847ae-2037-4709-8baa-721d7600e377.png)
