### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.admin#1032]
Ich habe soeben die GUI-Error Meldung erhalten:
![gui](https://user-images.githubusercontent.com/73795309/126678055-d45eec7f-57b7-47c7-a664-1e34ca8b4276.JPG)

**Comment by Matt77CHE** [comment]
Node.js
    v12.22.3
NPM
    6.14.13
Admin
    5.1.13

**Comment by GermanBluefox** [comment]
Das ist nur css Warnung und konnte ignoriert werden
