### ISSUE TITLE
ADMIN 5: validator not working for input type checkbox

### ISSUE THREAD

**Issue by Excodibur** [ioBroker/ioBroker.admin#1035]
**Describe the bug**  
I would like to use a checkbox (which itself is dynamically displayed/hidden) to ensure users confirm a certain configuration change, before saving it. The only way I could think of, is to use the "validator" attribute, to disable the Save-button.

**Does not work:**
```
"retentionConfirm": {
            "type": "checkbox",
            "label": "Lower retention",
            "hidden": "data.retention >= originalData.retention",
            "disabled": "data.retention >= originalData.retention",
            "confirm": {
              "text": "Are your sure about lowering the retention? Past data exceeding the retention period will be lost.",
              "condition": "data.retentionConfirm && data.retentionConfirm != originalData.retentionConfirm",
              "title": "Please confirm",
              "type": "warning"
            },
            "validator": "data.retentionConfirm"
        },
```

**Works:**
```
        "test": {
            "newLine": true,
            "type": "text",
            "label": "Test",
            "validator": "data.test > 0",
            "sm": 12,
            "md": 8
          }
```

**Expected behavior** 
The _validator_-attribute should work for checkboxes as well. It defenitely works for text-inputs.

**Versions:**  
 - Adapter version: 5.1.14
 - JS-Controller version: 3.3.11
 - Node version: v14.15.5
 - Operating system: WSL Ubuntu

**Comment by GermanBluefox** [comment]
You can use:
```
"demoCheckbox": {
          "type": "checkbox",
          "label": "Demo checkbox",
          "confirm1": {
            "text": "Are you sure?",
            "condition": "data.demoCheckbox && data.demoCheckbox != originalData.demoCheckbox",
            "title": "Please confirm",
            "type": "warning"
          },
          "validator": "data.demoCheckbox",
          "validatorErrorText": "This should be true",
          "validatorNoSaveOnError": true
        },
```
from 5.1.15

**Comment by Excodibur** [comment]
Thanks for the change :-) , but I still have issues with _validatorNoSaveOnError_. For me in 5.1.15 the Save Button is still clickable, even though the _validationErrorText_ is shown. Is it working for you?

**Comment by GermanBluefox** [comment]
Yes. I could reproduce it. Wait

**Comment by GermanBluefox** [comment]
Please try Version 5.1.16

**Comment by Excodibur** [comment]
Thanks, this works now with 5.1.17, but related to the topic there is another issue: https://github.com/ioBroker/ioBroker.admin/issues/1048. Anyways this ticket can be closed I think.
