### ISSUE TITLE
Adapter lassen sich nicht mehr anwählen.

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.admin#1039]
Raspberry Pi 4, 8GB
ioBroker.admin 5.1.16
Node.js: v12.22.4
NPM: 6.14.6
js-controller
JS controller Installiert: 3.3.15
OS: linux
Beta (latest)

Der Fehler taucht auf wenn ich die Adapter aufrufen möchte. Kam jetzt mit admin 5.1.16 [
<img width="498" alt="F21C4B07-7E30-4889-8CF1-C3258B577F67" src="https://user-images.githubusercontent.com/59523523/127677211-ceaa06dc-e3e9-46ff-ac37-ab6ff3f95f87.png">
](url)

**Comment by LausiD** [comment]
TypeError: e.props.repository is undefined
    value Adapters.js:1350
    value Adapters.js:1302
    value Adapters.js:1613
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674
    promise callback*a/o.getAdaptersInfo Adapters.js:668
    value Adapters.js:325
    promise callback*value Adapters.js:325
    value Adapters.js:314
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    Xt React
    r helpers.ts:87
    _wrapEventTarget trycatch.ts:185
    I instrument.ts:559
    React 8
    e index.js:22
    1426 index.js:47
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.44b5e404.chunk.js:2
instrument.ts:129:35

​

**Comment by skvarel** [comment]
Hier der gleiche Fehler. Sobald ich den Adapter Tab öffne

![grafik](https://user-images.githubusercontent.com/1114419/127681177-76dab1ae-9c15-4128-82e4-46cccfe56430.png)

**Comment by Netfreak25** [comment]
Habe das gleiche Problem beim Adapter tab, aber einen anderen Fehler
<img width="902" alt="Bildschirmfoto 2021-07-30 um 18 33 33" src="https://user-images.githubusercontent.com/6755265/127683991-46fc2d98-5a65-4d1a-a3bd-bf8a114b5557.png">

**Comment by GermanBluefox** [comment]
> Raspberry Pi 4, 8GB
> ioBroker.admin 5.1.16
> Node.js: v12.22.4
> NPM: 6.14.6
> js-controller
> JS controller Installiert: 3.3.15
> OS: linux
> Beta (latest)
> 
> Der Fehler taucht auf wenn ich die Adapter aufrufen möchte. Kam jetzt mit admin 5.1.16 [ <img alt="F21C4B07-7E30-4889-8CF1-C3258B577F67" width="498" src="https://user-images.githubusercontent.com/59523523/127677211-ceaa06dc-e3e9-46ff-ac37-ab6ff3f95f87.png"> ](url)

Sieht so aus, als Kode sehr alt ist. Browser cache löschen?

**Comment by Voodoo2man** [comment]
Auch nach Update auf 5.1.17 gibt es massive Fehler im Adapter Tab.

**Comment by Feuer-sturm** [comment]
Admin 5.1.17
Browser Cache gelöscht nach Update

Sobald das Menü "Adapter" aufgerufen wird erscheint die Seite Error in GUI! mit folgendem Output in der Browser Console:  
![grafik](https://user-images.githubusercontent.com/25422320/127719307-0ccdfade-9458-479a-bf9d-fb66dd765f01.png)

**Comment by Alex0176** [comment]
Admin 5.1.17 hab gerade das Update eingespielt und habe exakt das gleiche Problem und Fehlermeldung wie Feuer-sturm

**Comment by skvarel** [comment]
Hier auch bei 5.17.7 besteht das Problem immer noch.

MAn kann den Tab nun zwar aufrufen, aber nichts weiter klicken.

Ein Umstellen auf die alte Ansicht hilt zumindest, um kein Downgrade machen zu müssen.

**Comment by GermanBluefox** [comment]
Fixed in 5.1.18
