### ISSUE TITLE
Einstellungsbutton für Datenpunkte ohne Funktion

### ISSUE THREAD

**Issue by Tan-DE** [ioBroker/ioBroker.admin#104]
In der aktuellsten Git Version lassen sich History und Mqtt-Client Einstellungen von Datenpunkten nicht über das Zahnrad Symbol (im Bereich Objekte) öffnen.

**Comment by GermanBluefox** [comment]
Danke, aber git ist für die Entwickler. Und momentan befindet sich die
Umbau in dem Zustand wo man die Version noch nicht benutzen kann. Als ob
man beim Auto den Akku zur Wartung abgegeben hat und sich dabei wundert,
dass Blinker nicht funktioniert.

15 нояб. 2017 г. 13:16 пользователь "Tan" <notifications@github.com>
написал:

**Comment by Tan-DE** [comment]
Ja, ich weiß. Sollte auch nur ne Info sein. PN wäre vielleicht besser gewesen, sorry!
