### ISSUE TITLE
Farbschema lässt sich nicht mehr ändern / Kein Dark Mode möglich

### ISSUE THREAD

**Issue by Azathoth88** [ioBroker/ioBroker.admin#1040]
Fällt zwar unter Kosmetik, möchte ich der Ordnung halber trotzdem melden:
Das Farbschema lässt sich seit Version  > 5.1.16 (?) nicht mehr ändern.

**Comment by asutpshnik** [comment]
The theme change button is not visible in version 5.1.17
![2021-07-31_02-11-21](https://user-images.githubusercontent.com/60661789/127720441-3cf0fee0-4f7f-4361-bf50-401624d48bc5.png)

**Comment by skvarel** [comment]
Bei der v5.1.17 leider immer noch so.

**Comment by GermanBluefox** [comment]
Fixed in 5.1.18
