### ISSUE TITLE
ioBroker Basic Settings switching to different tabs not possible

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1043]
Admin 5.1.17

Steps to reproduce:
- Open basic setting of ioBroker
- Try to select a different tab than the first one e.g. Repositories

Error: It is not possible to switch to a tab.

In the browser console is no output.

**Comment by GermanBluefox** [comment]
Fixed in 5.1.18

**Comment by skvarel** [comment]
Der Fehler ist mit der v5.1.18 behoben. Es läuft wieder alles :)
