### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by betonix70** [ioBroker/ioBroker.admin#1045]
**Describe the bug**  
bei der installation des aktuellen Admin Adapters.

TypeError: e.props.repository is undefined
    value Adapters.js:1350
    value Adapters.js:1302
    value Adapters.js:1613
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674
instrument.ts:129:35
    I instrument.ts:129
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1041
