### ISSUE TITLE
ADMIN 5: hidden checkbox not reseted

### ISSUE THREAD

**Issue by Excodibur** [ioBroker/ioBroker.admin#1048]
This issue is linked to https://github.com/ioBroker/ioBroker.admin/issues/1035. The fix provided there works, but the usage of the input type checkbox as a kind of confirmation-box turns out more complex. The following steps show the problem:

1. The user enters a lower rention and the checkbox is shown (hidden = false) as expected.
2. Only upon activating the checkbox the new configuration can be saved. So far so good.
3. When the user now tries to lower the retention again, the checkbox is made visible as before, but now it is already activated, since Admin somehow persisted the state from step (2). This of course defeats the purpose of the checkbox as confirmation-element, since it now will be confirmed by default.

I tried to work around this, by declaring the checkbox field as an adapter native config element via adding the following:

io-package.json:
```
"native": {
       ...
        "retentionConfirm": false,
       ...
```

adapter main.js:
```
//Reset retentionConfirm checkbox
    if (adapter.config.retentionConfirm) {
        adapter.log.debug("RentionConfirm box is reseted");
        adapter.extendForeignObject('system.adapter'+ adapter.namespace, {
            native: {
                retentionConfirm: false
            }
        });
    }
```

The idea is to reset the checkbox-field during adapter-restart when the previously changed configuration is read. This potentially has the downside of taking a while, until the adapter restart before the checkbox will be reset on the Admin config page.

Moreover, even though as part of the restart I could verify that the adapter-config is changed (System.Adapter.influxdb.0 shows the updated retentionConfirm-value), the adapter-configuration page where the confirmation-checkbox is show still displays it to be confirmed as before. Which, should not be the case.

**JSON Config defintion**  
JSONConfig definition of the checkbox (as in other ticket):
```
"retentionConfirm": {
          "type": "checkbox",
          "label": "Apply lower retention",
          "hidden": "(data.retention >= originalData.retention && originalData.retention != 0) || data.retention == 0",
          "disabled": "(data.retention >= originalData.retention && originalData.retention != 0) || data.retention == 0",
          "confirm": {
            "text": "Lowering the retention period should be considered with caution: Past data exceeding the retention period will be lost.",
            "condition": "data.retentionConfirm && data.retentionConfirm != originalData.retentionConfirm",
            "title": "Please confirm!",
            "type": "warning"
          }, 
          "validator": "data.retentionConfirm",
          "validatorErrorText": "Confirmation required.",
          "validatorNoSaveOnError" : true
        }
```
**Remark**
Even though we might get this workaround to work, I think it would be better if we could find an Admin5 solution (perhaps an additional flag in JSONConfig for the element) that allows this checkbox-approach (and the reset of it after saving the changes) to work without linking it to a adapter native config element and messing with it in the adapter-code. The confirmation-feature is meant to be a small helper for the user when changing config values in admin before updating the adapter, so putting logic to reset it into the adapter, fells wrong.

**Versions:**  
- Adapter version: 5.1.17
- JS-Controller version: 3.3.11
- Node version: v14.15.5
- Operating system: WSL Ubuntu

**Comment by GermanBluefox** [comment]
![admin2](https://user-images.githubusercontent.com/4582016/127744931-04b81b38-003d-4f70-a6fe-c5c7e2b6c09a.gif)

Like this?
So change JSON to:
```
"retentionConfirm": {
          "type": "checkbox",
          "label": "Apply lower retention",
          "hidden": "(data.retention >= originalData.retention && originalData.retention != 0) || data.retention == 0",
          "disabled": "(data.retention >= originalData.retention && originalData.retention != 0) || data.retention == 0",
          "confirm": {
            "text": "Lowering the retention period should be considered with caution: Past data exceeding the retention period will be lost.",
            "condition": "data.retentionConfirm && data.retentionConfirm != originalData.retentionConfirm",
            "title": "Please confirm!",
            "type": "warning"
          }, 
          "validator": "data.retentionConfirm",
          "validatorErrorText": "Confirmation required.",
          "validatorNoSaveOnError" : true,
          "doNotSave": true
        }
```
* Works with 5.1.19 (doNotSave added)

**Comment by Excodibur** [comment]
Thanks for the update! Works great now!
