### ISSUE TITLE
Verfügbare Adapter nicht werden nicht im INFO angezeigt

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#1049]
![grafik](https://user-images.githubusercontent.com/34395245/127735575-93bd161a-5cfe-4cda-ae66-48bb089ff18b.png)
![grafik](https://user-images.githubusercontent.com/34395245/127735581-1304a84a-1a3b-4705-9855-0c239d5a708e.png)

Versions:
    Info-Adapter: 1.9.7
    Admin-Adapter version: 5.1.17
    JS-Controller version: 3.3.15
    Node version: v12.22.4
    NPM Version: 6.14.14

**Comment by simatec** [comment]
Kann ich nicht bestätigen ... Admin 5.1.18
![image](https://user-images.githubusercontent.com/39792461/127736918-4e24ea2a-e373-4442-b173-a0f93f5294c1.png)

**Comment by guergen1** [comment]
Ich habe eine andere NPM und node.js-Version installiert; vielleicht liegt es daran!?

**Comment by GermanBluefox** [comment]
Erstens es ist ein Fehler für info. 
Zweitens, falls `Auch bestimmt Adpater-Versionen können nicht ausgewählt werden...`
Dann welche und was ist damit gemeint?

**Comment by Apollon77** [comment]
@guergen1 Und bitte nicht info Adapter und Admin verwechseln!!

**Comment by guergen1** [comment]
@GermanBluefox Stimmt, es ist ein Fehler des Info-.Adapters. In der 1.9.6 zeigt er die updatebaren Adapter noch an.

Zu "Auch bestimmt Adpater-Versionen können nicht ausgewählt werden...":
In der alten Oberfläche konnte man wählen, welche Adapterversion man installieren wollte, wenn man nach Fehlern sucht. Das ist in der V5 nicht mehr der Fall. 
Oder ist das Absicht, dass der Punkt herausgenommen wurde?
![grafik](https://user-images.githubusercontent.com/34395245/127762341-292d2388-0e85-4886-b6f0-ae72a324938f.png)
