### ISSUE TITLE
Adapter können nicht mehr Installiert werden

### ISSUE THREAD

**Issue by Peter1980FFM** [ioBroker/ioBroker.admin#1050]
Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on github
Without this information it is not possible to analyse the error.
It should looks like
index.js:18 iobroker.admin@5.1.17
instrument.ts:129 [2021-07-31T09:31:32.155Z] Try to connect
instrument.ts:129 [ADAPTERS] getAdapters
instrument.ts:129 [ADAPTERS] getAdaptersInfo
instrument.ts:129 [ADAPTERS] Render
instrument.ts:129 [ADAPTERS] vis-materialdesign
simple-api.png:1 GET http://192.168.122.11:8081/adapter/simple-api/simple-api.png 404 (Not Found)
Image (asynchron)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonym) @ Adapters.js:674
Promise.then (asynchron)
o.getAdaptersInfo @ Adapters.js:668
(anonym) @ Adapters.js:325
Promise.then (asynchron)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
Cross-Origin Read Blocking (CORB) hat eine ursprungsübergreifende Antwort https://github.com/hombach/ioBroker.kostal-piko-ba/blob/master/admin/picoba.png mit MIME-Typ text/html blockiert. Weitere Informationen finden Sie unter https://www.chromestatus.com/feature/5629709824032768.
Image (asynchron)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonym) @ Adapters.js:674
Promise.then (asynchron)
o.getAdaptersInfo @ Adapters.js:668
(anonym) @ Adapters.js:325
Promise.then (asynchron)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
Cross-Origin Read Blocking (CORB) hat eine ursprungsübergreifende Antwort https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/master/admin/dyson_logo.svg mit MIME-Typ text/html blockiert. Weitere Informationen finden Sie unter https://www.chromestatus.com/feature/5629709824032768.
Image (asynchron)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonym) @ Adapters.js:674
Promise.then (asynchron)
o.getAdaptersInfo @ Adapters.js:668
(anonym) @ Adapters.js:325
Promise.then (asynchron)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
Cross-Origin Read Blocking (CORB) hat eine ursprungsübergreifende Antwort https://github.com/Vertumnus/ioBroker.googleauth/blob/master/admin/logo-google.svg mit MIME-Typ text/html blockiert. Weitere Informationen finden Sie unter https://www.chromestatus.com/feature/5629709824032768.
Image (asynchron)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonym) @ Adapters.js:674
Promise.then (asynchron)
o.getAdaptersInfo @ Adapters.js:668
(anonym) @ Adapters.js:325
Promise.then (asynchron)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
Cross-Origin Read Blocking (CORB) hat eine ursprungsübergreifende Antwort https://github.com/Grizzelbee/ioBroker.mielecloudservice/blob/master/admin/mielecloudservice.svg mit MIME-Typ text/html blockiert. Weitere Informationen finden Sie unter https://www.chromestatus.com/feature/5629709824032768.
Image (asynchron)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonym) @ Adapters.js:674
Promise.then (asynchron)
o.getAdaptersInfo @ Adapters.js:668
(anonym) @ Adapters.js:325
Promise.then (asynchron)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
instrument.ts:129 TypeError: Cannot read property 'props' of undefined
    at AdapterTile.js:292
    at ro (react-dom.production.min.js:157)
    at No (react-dom.production.min.js:180)
    at Ui (react-dom.production.min.js:269)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at Ae (react-dom.production.min.js:292)
    at react-dom.production.min.js:50
    at xr (react-dom.production.min.js:105)
    at Qt (react-dom.production.min.js:75)
    at Jt (react-dom.production.min.js:74)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Xt (react-dom.production.min.js:73)
    at HTMLDivElement.r (helpers.ts:87)
(anonym) @ instrument.ts:129
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
Io @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
xr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Xt @ react-dom.production.min.js:73
r @ helpers.ts:87

**Comment by GermanBluefox** [comment]
Pleas use 5.1.18
