### ISSUE TITLE
ADMIN5: Object History returns additional rows for type boolean

### ISSUE THREAD

**Issue by Excodibur** [ioBroker/ioBroker.admin#1052]
**Describe the bug**  
Within Admin 5 the "History" view of for objects returns additional entries, if the state-object is of type boolean, see screenshot:

![image](https://user-images.githubusercontent.com/70700967/127736273-950f671a-9b0f-4d6b-9e1b-e982ae0c8a8b.png)

This only appears on Admin 5 (4 works fine) and only for boolean values (numbers are fine). The additional data was verified not to be provided by the influx-adapter, so I assume it is added somewhere in the Admin 5 code.

Please check it.

**Versions:**  
Adapter version: 5.1.17
JS-Controller version: 3.3.11
Node version: v14.15.5
Operating system: WSL Ubuntu

**Comment by GermanBluefox** [comment]
This is how it looks in history:
![image](https://user-images.githubusercontent.com/4582016/127745541-2254a655-dd7f-41ff-9d9e-c3d2afc56756.png)

No any additional entry. The table asks adapter 2 times: 
- First time to get the oldest and newest value to provide data for range selectors
- Second time to get selected interval data.

And exactly first time it asks from "2000-01-01T00:00:00.000Z" to Date.now(). 
The values with `null` will be ignored by first read, but "influxdb" returns `false` and not `null`

**Comment by Excodibur** [comment]
Ok I think I get your explanation how data is queried, but why (also in your screenshot) are those results (24.6.2021, and empty) part of the table and greyed out? Perhaps there is a purpose/reason to include them into the table, but why then only in Admin 5 and only for boolean values?

**Comment by GermanBluefox** [comment]
> Ok I think I get your explanation how data is queried, but why (also in your screenshot) are those results (24.6.2021, and empty) part of the table and greyed out? Perhaps there is a purpose/reason to include them into the table, but why then only in Admin 5 and only for boolean values?

It is new feature in Admin5 to detect the maximum range. It is not only for boolean. For all others too.

the Value on 24.6.2021 is empty, because on start and on stop of the instance the "null" values will be written into DB to mark the intervals where the instance was stopped.

**Comment by Excodibur** [comment]
Ok I understand.

Weirdly, after updating to Adminn 5.1.19 I don't see the grey entries anymore in the table. Is this maybe related to your changes on this line? https://github.com/ioBroker/ioBroker.admin/blob/9305806938b07c92718f934e1d6b2d6a30570300/src-rx/src/components/Object/ObjectHistoryData.js#L539

**Comment by GermanBluefox** [comment]
> Ok I understand.
> 
> Weirdly, after updating to Adminn 5.1.19 I don't see the grey entries anymore in the table. Is this maybe related to your changes on this line?
> 
> https://github.com/ioBroker/ioBroker.admin/blob/9305806938b07c92718f934e1d6b2d6a30570300/src-rx/src/components/Object/ObjectHistoryData.js#L539

Yes. I removed the line for 2000.1.1 as it not possible

**Comment by Excodibur** [comment]
Ok, sounds good. From my side we can close the issue. Thanks for your help and explanation!
