### ISSUE TITLE
Symbol to select dedicated Adapter Version not available

### ISSUE THREAD

**Issue by mirage-111** [ioBroker/ioBroker.admin#1053]
Using expert mode, it s usually possible to select previous Adapter Versions.
In Admin Adapter Version 5.1.18 the Version Symbol does not appear.

**To Reproduce**  
1. Go to Adapter
2. Click on Expert Mode
3. Scroll down to an installed Adapter
4. See that the Plus-Symbol for previous Version is missing 

https://forum.iobroker.net/topic/46656/adapter-version-nicht-mehr-wählbar

**Comment by GermanBluefox** [comment]
Foxed

**Comment by Feuer-sturm** [comment]
Admin 5.1.19

Issue is fixed. Icon is available
![grafik](https://user-images.githubusercontent.com/25422320/127773769-dae9eba2-b54d-4687-884e-fc551e2dcb8d.png)
