### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Fauli085** [ioBroker/ioBroker.admin#1054]
TypeError: e.props.repository is undefined
    value https://192.xxx.xxx.xx:8081/static/js/main.44b5e404.chunk.js:2
    value https://192..xxx.xxx.xx:8081/static/js/main.44b5e404.chunk.js:2
    value https://192..xxx.xxx.xx:8081/static/js/main.44b5e404.chunk.js:2
    Wo https://192..xxx.xxx.xx:80811/static/js/5.acc635a4.chunk.js:2
    Io https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Ui https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Cl https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    _l https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    El https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    ml https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Ga https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    unstable_runWithPriority https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Wa https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Ga https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    Ua https://192..xxx.xxx.xx:8081static/js/5.acc635a4.chunk.js:2
    hl https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    enqueueSetState https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    setState https://192..xxx.xxx.xx:8081/static/js/5.acc635a4.chunk.js:2
    value https://192..xxx.xxx.xx:8081/static/js/main.44b5e404.chunk.js:2
    getAdaptersInfo https://192..xxx.xxx.xx:8081/static/js/main.44b5e404.chunk.js:2

**Comment by Fauli085** [comment]
TypeError: e.props.repository is undefined
    value Adapters.js:1350
    value Adapters.js:1302
    value Adapters.js:1613
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674
    promise callback*a/o.getAdaptersInfo Adapters.js:668
    value Adapters.js:325
    promise callback*value Adapters.js:325
    value Adapters.js:314
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    Xt React
    r helpers.ts:87
    _wrapEventTarget trycatch.ts:185
    I instrument.ts:559
    React 8
    e index.js:22
    1426 index.js:47
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.44b5e404.chunk.js:2

**Comment by GermanBluefox** [comment]
Which version of admin? In 5.1.19 it should be fixed.

**Comment by Fauli085** [comment]
Thanks for the help. was due to the admin.
I have now 5.1.19 and there is no more error.

THANK YOU.

Sorry, my english is very bad  :)
