### ISSUE TITLE
Error in Adapter-GUI

### ISSUE THREAD

**Issue by juergenS09** [ioBroker/ioBroker.admin#1055]
Hallo zusammen,
ich bekomme bei dem Versuch die Adapter-Seite zu öffnen, folgenden Fehler:
GET http://192.xx.xx.xx:8081/adapter/socketio/socketio.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ai @ react-dom.production.min.js:208
Sl @ react-dom.production.min.js:251
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:600
(anonymous) @ Adapters.js:674
Promise.then (async)
o.getAdaptersInfo @ Adapters.js:668
(anonymous) @ Adapters.js:325
Promise.then (async)
value @ Adapters.js:325
value @ Adapters.js:314
fi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Vl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
instrument.ts:129 [ADAPTERS] Render
instrument.ts:129 TypeError: Cannot read property 'props' of undefined
    at AdapterTile.js:292
    at ro (react-dom.production.min.js:157)
    at No (react-dom.production.min.js:180)
    at Ui (react-dom.production.min.js:269)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at Ae (react-dom.production.min.js:292)
    at react-dom.production.min.js:50
    at xr (react-dom.production.min.js:105)
    at Qt (react-dom.production.min.js:75)
    at Jt (react-dom.production.min.js:74)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Xt (react-dom.production.min.js:73)
    at HTMLDivElement.r (helpers.ts:87)

Andere Seiten wie Instanzen, Objekte usw funktionieren tadelos.
Switche ich im admin auf "alte Benutzeroberfläche" funktioniert alles wie gehabt.
Admin Version ist bei mir derzeit 5.1.7

Grüße

Jürgen

**Comment by juergenS09** [comment]
Nachtrag:
Ich habe gesehen, dass es eine neuere Version gibt - 5.1.9
Ich habe versucht diese über die GUI direkt zu installieren, bekomme dann jedoch einen Fehler:
This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.

Also habe ich es über die Console via ssh versucht, was augenscheinlich auch funktioniert hatte. Jedoch kann ich nun die GUI garnicht mehr aufrufen, es erscheint immer dieser Fehler:
This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.

**Comment by Apollon77** [comment]
maybe try commandline

iobroker update
iobroker upgrade admin

**Comment by OXERY** [comment]
`iobroker update` and `iobroker upgrade` did the trick. Thanks @Apollon77
