### ISSUE TITLE
Hallo Leute, ich bin hier neu und erhalte beim IOBroker folegnde Fehlermeldung  beim Aufruf der Seite xxx.xxx.xxx.xxx:xxxx/#tab-adapters.  Sonst finktioniert eigentlich alles

### ISSUE THREAD

**Issue by Rolfsmart** [ioBroker/ioBroker.admin#1056]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
Hallo Admin Version hast du installiert?
Wenn mit der 5.1.19 der Fehler auftritt, bitte im Beschreibungsfeld mehr Details posten (Screenshots, Browser Console, Welche Schritte muss man machen, um den Fehler zu sehen)
