### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Rolfsmart** [ioBroker/ioBroker.admin#1057]
Hallo Leute, ich bin hier neu und erhalte beim IOBroker folgende Fehlermeldung  beim Aufruf der Seite xxx.xxx.xxx.xxx:xxxx/#tab-adapters.  alle anderen Seite in der GUi funktionieren  z.B. /#tab-intro.

Fehlermeldung:
TypeError: e.props.repository is undefined
    value Adapters.js:1350
    value Adapters.js:1302
    value Adapters.js:1613
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674
    promise callback*a/o.getAdaptersInfo Adapters.js:668
    value Adapters.js:325
instrument.ts:129:35
    I instrument.ts:129
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value Adapters.js:600
    getAdaptersInfo Adapters.js:674
    (Async: promise callback)
    getAdaptersInfo Adapters.js:668
    value Adapters.js:325

**Comment by GermanBluefox** [comment]
Bitte die Version 5.1.19 benutzen
