### ISSUE TITLE
faulty graphical Headline in 5.1.19

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#1060]
![admin_issue_5_1_19](https://user-images.githubusercontent.com/11257222/127897089-69998902-6ad9-4d8f-9ca0-41428c54a5f8.png)
The Line with the icons to administrate the page is partially hidden

**Comment by GermanBluefox** [comment]
Cannot reproduce

**Comment by Feuer-sturm** [comment]
@Homoran Is this issue still active or can we close it?

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
