### ISSUE TITLE
Admin 5.1.19 --> value "Ausgewählte Adapter" unclear or wrong

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#1061]
As example:

if i filter for adapters which can be updated i got "5 Ausgewählte Adapter"

![image](https://user-images.githubusercontent.com/33424168/127915553-52cbea21-e950-470b-90e1-b83dbc4c284d.png)

Where is this value coming from ? 
Shouldn`t it be "3" ?

**Comment by GermanBluefox** [comment]
Fixed in 5.1.22. This is a number of non-filtered out adapters.

**Comment by Feuer-sturm** [comment]
Admin 5.1.23

Number of adapter with updates fits to number "Ausgewählte Adapter" 

![grafik](https://user-images.githubusercontent.com/25422320/128569017-8b3545de-faf7-49c5-847e-2112339237f2.png)
