### ISSUE TITLE
Admin 5.1.21 Error after few seconds after login in new GUI

### ISSUE THREAD

**Issue by DerRonX** [ioBroker/ioBroker.admin#1062]
**Describe the bug**  
I just logged in after updating from 5.1.19 to 5.1.21. After several seconds this error appears. The selected tab doesnt matter. I cleared all cache and restarted ioBroker several times also.
Old GUI works fine.

**To Reproduce**  
1. Just Login New GUI
2. Wait several seconds

**Expected behavior**  

**Screenshots & Logfiles**  
![ErrorInGui](https://user-images.githubusercontent.com/6297638/127921219-b52b7abb-c936-4e69-b7d3-862a5d4957e2.PNG)

**Versions:**  
 - Adapter version: 5.1.21
 - JS-Controller version: 3.3.15
 - Node version: v12.22.4
 - Operating system: linux
- Browser: Chrome

**Comment by GermanBluefox** [comment]
Fixed in 5.1.22
