### ISSUE TITLE
Update GitHub/npm

### ISSUE THREAD

**Issue by beabel** [ioBroker/ioBroker.admin#1063]
**Describe the bug**  
Unter Info kam die Meldung Admin 5 im stabile.
Unter Adapter war jedoch keine neue Admin Version angezeigt.
Jetzt habe ich versucht mit der 🐱 den neuen zu installieren.
Beim Aufruf der Admin Seite kam dann diese Meldung:
This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.
OK, also per SSH dies ausgeführt:
cd /opt/iobroker/
npm Install iobroker.admin

Scheint es auch gemacht zu haben, jedoch steht auf der Admin Seite noch immer die Meldung:
This Adapter cannot......
Wie komme ich entw. Wieder auf die Seite ohne Meldung?
Oder wie bekomme ich den Admin Adapter zurück auf die 4'er Version?

**Comment by Apollon77** [comment]
Bitte Repository aktualisieren. In der Info Meldung stand auch ein Forum Link und dort immersten Satz steht "taucht jetzt heute Abend auf".

Ansonsten nach einem manuellen "Npm install" bitte ncoh ein "iobroker upload admin" machen dann sollte das passen
