### ISSUE TITLE
Admin 5.1.23 kein Button "Log herunterladen"

### ISSUE THREAD

**Issue by SliX185** [ioBroker/ioBroker.admin#1064]
Admin 5.1.23 fehlt in der "alten Benutzeroberfläche" im Reiter Log der Button "Log herunterladen"

![alte ansicht](https://user-images.githubusercontent.com/47434006/128557537-c1eae691-56aa-45e1-a273-20fe5727aba8.JPG)

Bei der neuen Ansicht gibts den Button

![neue](https://user-images.githubusercontent.com/47434006/128557552-e8a67ab3-029d-4376-ac54-e8cd2ca7f60d.JPG)

Es wär super, wenn wer das wieder gerade biegen könnte. Die neue Benutzeroberfläche ist leider nicht mein Fall.
Danke im Voraus.

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 3.3.15
 - Node version: 12.19.0

**Comment by Apollon77** [comment]
Nein, die Alte UI ist nur noch temporär da um im Notfall zurückwechseln zu können. Daher werden wir hier nichts mehr ändern.
