### ISSUE TITLE
Trennlinien zwischen Objekten

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.admin#1066]
Hallo Zusammen,
erstmal super Arbeit! Eine Sache stört mich aber beim Admin 5, die fehlenden Trennlinien. Ich glaube, das ist eine der Hauptursachen, dass Benutzer die neue UI als unübersichtlich empfinden.
Gerade wenn man Blocklys zusammenklickt und viele Objekte auswählt, sind machen es die fehlenden Trennlinien sehr unübersichtlich.
Keine Trennlinien in der aktuellen UI:
![Linien3](https://user-images.githubusercontent.com/18654629/128580809-14227143-ed17-491c-9005-6ee020668d27.JPG)

Wunderschöne Trennlinien in der alten UI: :) 
![Linien1](https://user-images.githubusercontent.com/18654629/128580844-cba7aec6-5203-4a87-bd7f-9adcc6ff0992.JPG)

![Linien2](https://user-images.githubusercontent.com/18654629/128580849-33d7efff-9336-451f-8c80-77bf711d5145.JPG)

**Comment by jolichter** [comment]
Hi, bin der gleichen Ansicht. Auch wenn vieles Gewöhnungssache ist, wäre eine Trennlinie übersichtlicher.

**Comment by GermanBluefox** [comment]
Just now only as option, but we will see. May be it will be enabled by default.
![image](https://user-images.githubusercontent.com/4582016/129067596-2fd39033-63c4-4e01-9345-50a4cc5d30db.png)

![image](https://user-images.githubusercontent.com/4582016/129067477-1b73c4a4-6533-45cd-85c8-3d14eca9c4af.png)

**Comment by Feuer-sturm** [comment]
Admin 5.1.24

@GermanBluefox 
Lines are implemented in 5.1.24
![grafik](https://user-images.githubusercontent.com/25422320/129492950-ce80e457-a98d-4048-a4de-5836c8c6e8cf.png)

**Comment by Feuer-sturm** [comment]
@Apollon77 @GermanBluefox Issue can be closed
