### ISSUE TITLE
Hilfeseiten der einzelnen Adaptern im ioBroker öffenen

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#107]
Es wäre cool, wenn die einzelnen Readme-Seiten direkt als Overlay in ioBroker erscheinen würden. Dafür gibt es eine JS Bibliothek, der Markdown in HTML umwandelt:

https://github.com/showdownjs/showdown

Habe es damals im Admin-Neo eingebaut:
https://github.com/ldittmar81/ioBroker.admin-neo/blob/1600165d0a889708fdb2c81f4a5e58c26e837f6d/www/neo-js/admin.js#L1496

Den Readme-Link bekommt man aus io-package:
https://github.com/ldittmar81/ioBroker.admin-neo/blob/master/README.md
muss aber noch entsprechend geändert werden, damit man daraus die Markdowns bekommt:
https://raw.githubusercontent.com/ldittmar81/ioBroker.admin-neo/master/README.md

Das wäre richtig cool! :sunglasses:

**Comment by ldittmar81** [comment]
It's done!

**Comment by GermanBluefox** [comment]
Cool 👍
