### ISSUE TITLE
Admin 5.1.23 Log: Error

### ISSUE THREAD

**Issue by jolichter** [ioBroker/ioBroker.admin#1070]
Hallo, bei jedem Login über das Webinterface habe ich eine Fehlermeldung im Log:

![Screenshot_20210807_170303](https://user-images.githubusercontent.com/1485851/128605286-ab8003d3-3f9f-4181-9df4-c7b76c67a00b.png)

Debug Logfile:
[iobroker.2021-08-07.log](https://github.com/ioBroker/ioBroker.admin/files/6949314/iobroker.2021-08-07.log)

Könnt Ihr die Ursache dafür finden? Oder benötigt mehr Infos?
Danke!

____________________
Admin: 5.1.23
Node.js: v12.22.4
NPM: 6.14.14

**Comment by Feuer-sturm** [comment]
Sieht nach diesem bereits existierenden issue 
https://github.com/ioBroker/ioBroker.admin/issues/1000
aus

**Comment by Apollon77** [comment]
@jolichter HTTPS?

**Comment by jolichter** [comment]
klar, immer HTTPS

**Comment by jolichter** [comment]
> Sieht nach diesem bereits existierenden issue
> #1000
> aus

Yepp, könnte sein. Jedoch erscheint bei mir "failed connection to socket.io" sehr selten (ist mir eben erst aufgefallen).

**Comment by jolichter** [comment]
Hi, wollte mal nachfragen ob das noch gefixt wird. Diese Log-Errors sind anscheinend nichts wichtiges und können ignoriert werden?

_____________
Admin: 5.1.25 | Node.js: v14.18.1 | NPM: 6.14.15

**Comment by jolichter** [comment]
Yes, the smart bot has a point and that is why I am closing it by my self ;-)
I guess the issue [#1000](https://github.com/ioBroker/ioBroker.admin/issues/1000) fits better.
