### ISSUE TITLE
Admin Error in Gui - Report

### ISSUE THREAD

**Issue by mandragora666** [ioBroker/ioBroker.admin#1073]
![image](https://user-images.githubusercontent.com/73381262/128628014-36e8583b-2f87-4b8d-9dee-4c01ff6d2742.png)

![image](https://user-images.githubusercontent.com/73381262/128628026-f5189fb0-f68f-49c8-9888-9d73fa3d7c90.png)

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1068
