### ISSUE TITLE
Open Node-Red via tab does not work any longer with https/secured

### ISSUE THREAD

**Issue by crocri** [ioBroker/ioBroker.admin#1074]
Hello!
Status line is shown as "https://iobroker.private:8081/#tab-node-red-0" => seems correct.
Direct open Node-Red in browser works with https!
Certificate is correct, all other tabs worked as expected. Same issue for Firefox, Chrome and MS Edge (chromium).

It seems admin module want to start node_red with ip address, not with name, so certificate verification failed.

Restore iobroker to admin version <5 works with https also for Node-Red tab.

Best regards
Crocri

**Comment by GermanBluefox** [comment]
Do you have a screenshot for me?

**Comment by crocri** [comment]
Screenshot? For certificates don't use ip address, use full qualified name (e.g. iobroker.local). Link shown is ok, but after klick on Node-Red tab ip is used, so certificate fails. Same in "Übersicht" for NODE-RED and other modules, for example FLOT. Never use IP in https mode.
Reproduce error: install certs, change to https, add Node-Red instance and change this to https too. Click on Node-Red tab = error.

**Comment by crocri** [comment]
Here a screenshot after click on node-Red tab:
![image](https://user-images.githubusercontent.com/55567276/129602816-39acff0a-0df9-4495-8c58-ab82a3b0218e.png)

**Comment by crocri** [comment]
Hi!
Tab is functioning now 👍 
One minor step is missing. Menu "Overiew" (Übersicht), Node-Red link is without https - but name and port is correct.

Best regards
Crocri
