### ISSUE TITLE
Objecttree Keyboard navigation not working since update to 5.x

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.admin#1076]
**Describe the bug**  
In version 4.x it was possible to traverse the object tree using the arrow keys on the keyboard within scripts and the main objects view. (up/down for switching the selected element as well as left/right to expand/collapse directories)

**To Reproduce**  
1. Go to the objects view
2. Select any object
3. Press the arrow keys
4. nothing happens

**Expected behavior**  
I would like the previous behaviour to be restored (navigating the objects tree with the arrow keys)

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 3.3.15
 - Node version: v12.22.4
 - Operating system: Ubuntu

**Additional context**  
Using Chrome browser

**Comment by disaster123** [comment]
+1 - one reason why i'm still using v4 admin
