### ISSUE TITLE
Error when opening page STANDARD ACL

### ISSUE THREAD

**Issue by Mag422** [ioBroker/ioBroker.admin#1077]
Error when opening page STANDARD ACL

**To Reproduce**  
1. Go to 'Übersticht'
2. Click on 'Systemeinstellungen'
3. Click on "Standard ACL"

**Expected behavior**  

![image](https://user-images.githubusercontent.com/88659972/128695405-ae76ff7d-81e9-4429-85ce-88183bbc03f6.png)
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 
 - JS-Controller version: 3.2.16
 - Node version: Node.js v12.22.1
 - Operating system: Synology

**Additional context**

**Comment by GermanBluefox** [comment]
Should be fixed in 5.1.24

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1068
