### ISSUE TITLE
Eingefärbte Datenpunkte in den Objekten bei Admin5

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#1078]
Mit neuer Admin Oberfläche(dunkles Design) wird der Pfad trashschedule.0.type so angezeigt, getestet mit Chrome und FF

![image](https://user-images.githubusercontent.com/41550245/128714180-89b6481c-9ce1-4e2a-bd64-c070bfd68820.png)

**Comment by Feuer-sturm** [comment]
In trashschedule instance it is possible to set a color for every type. If a color is selected here the text in the objects will be changed as well

![grafik](https://user-images.githubusercontent.com/25422320/128766628-c19f3042-a3c7-4d9c-966e-a5836d743f0e.png)

**Comment by crunchip77** [comment]
"This color code can be used to colorize the individual appointments in VIS".
What does this have to do with the object view in the admin then?

**Comment by klein0r** [comment]
@crunchip77 Thanks for the hin, I will update the description. But that's not the point in this issue 😄

**Comment by GermanBluefox** [comment]
It is automatic background for better contrast

**Comment by Feuer-sturm** [comment]
@GermanBluefox Diese Objekte sind auch farbig aber haben keinen weißen Hintergrund. Warum ist das Verhalten hier anders?
![grafik](https://user-images.githubusercontent.com/25422320/129085094-62a70760-7ab1-4869-8f61-b45e9e045c93.png)

**Comment by GermanBluefox** [comment]
Weil das sind die spezielle Objekte: system, adapter werden extra eingefärbt.

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 Da das Verhalten "Works as designed." ist, kann das Ticket auch geschlossen werden.

**Comment by Diginix** [comment]
Das im Darkmode Objekte grünen Schriftfarbe auf weißem Hintergrund haben ist "as designed"?

Auch Einstellungen div. Instanzen sind bei mir vollständig unlesbar.
![image](https://user-images.githubusercontent.com/39678667/153224565-3451fab3-38c0-43ac-9e61-3494bee92443.png)

Der weiße Hintergrund kommt auf jeden Fall aus der admin.css
![image](https://user-images.githubusercontent.com/39678667/153224971-dcb34db9-c04e-4d0c-b49f-c529ff9c56ff.png)

**Comment by Diginix** [comment]
Hm, weißer Adler auf weißem Grund = null Kontrast ;-)
Aber vllt liegt es auch an meinem Monitor. Imho ist eine größere weiße Fläche bei gewähltem dark theme einfach echt fieees.
Der Fehler bei Jarvis ist also die weiße Schriftfarbe in der adapter.css. Da jarvis2 keiner pflegt, muss ich es wohl lokal patchen.

**Comment by Diginix** [comment]
@klein0r Also der weiße Hintergrund bei der jarvis2 Instanz kommt auch aus der admin.css des jarvis Adapters.
Nachdem ich dort nun Zeile 14 auskommentiert habe, sieht es sauber aus. Das beißt sich mit deiner Aussage dass der weiße Hintergrund beim dark theme gewollt ist. Die weiße Schriftfarbe kommt nämlich vom Admin. Wie kann jemand weiße Schrift- und Hintergrundfarbe wollen?
Anyway: fixed for me
Musste schon einiges in jarvis2 fixen. Bringt aber nichts dafür noch ein Fork zu machen.

**Comment by klein0r** [comment]
@Diginix Hier (und im verlinkten Issue) ging es um die Darstellung in der Objekt-Ansicht. Was die Adapter in ihren iFrames machen steht auf einem anderen Blatt

**Comment by DcFamas** [comment]
Wäre es ggf. möglich dennoch das so anzupassen, dass der Text nur Grün erscheint und nicht der Hintergrund weiß eingefärbt wird? Das macht meiner Meinung nach den Dark Mode hinfällig,. Generell bricht es schon sehr das schöne Design.
