### ISSUE TITLE
Edited Objects are not correctly saved

### ISSUE THREAD

**Issue by Fontheweg** [ioBroker/ioBroker.admin#1079]
Since I updatet to Admin 5.1.23, it is not possible to edit Objects in RAW mode. For example:
![image](https://user-images.githubusercontent.com/77742610/128738767-96c0b14a-304d-4344-aaf3-1a65e057eb8e.png)
If I edit this to the following:
![image](https://user-images.githubusercontent.com/77742610/128738853-56a83c16-cf5c-4086-9372-b62ba6dc817a.png)
If I klick on save, the State is changed - but the ID is still the old one. On Admin 4.x a new State was created, so it was possible to "Copy/Paste" States easily. Now I have to create a new state step by step and afterwards I have to edit the RAW-Data to add more attributes.

I think that was a good option to quickedit states which I'm missing now. Sadly I damaged States, because there were overwritten not saved as newone.

**Comment by Apollon77** [comment]
That you cound change the _id property of an object was never intended and so it is no longer allowed in Admin5. Please create a new object and copy the object content if you like

**Comment by Fontheweg** [comment]
Sorry Apollo, you misunderstood.
Changing the ID was not renaming the Object, it creates a new on.

So if you want to have 5 States with the same Parameters. You could create one with all attibutes you want by clicki bunti.
Afterwards rename in the Rawdatas _id and name and save, and a new Object was created like a copy with a new name.

This is a much more functional flow as create each object by hand or creating an extra script to do this.

**Comment by Fontheweg** [comment]
Why did "you" delete the old function?
It was so practical. 

Edit the old State
Copy Rawdata
Create new State by wizzard
Put copied data

Is much more handling than

Edit the old state
Save

Is there an issue with this functionality?

**Comment by Apollon77** [comment]
Hm .. bit whats the difference to:
* Create 5 new sState objects with correct name - the mask for a new object is really slim
* Then edit one as wanted or use an existog - mainly the common part
* open each object and pst in there

Yes maybe some clicks more per needed object, but not that much of a difference or?

It ewas never a Feature in Admin4, it was more like a Flaw ... something not prevented. This can have that many internal sideeffects you can not imagine ...

**Comment by Fontheweg** [comment]
Okay,
thank you for your support. I'll try tomorrow. Seems like I just had to relearn an new way.
😏
