### ISSUE TITLE
Admin 5 - jsonConfig missing validation with item type "number" using min/max

### ISSUE THREAD

**Issue by bropat** [ioBroker/ioBroker.admin#1081]
**Describe the bug**  
During the development of the adapter I used jsonConfig for the admin configuration page. I noticed that when I create an item of the type "number" the min and max attributes are not automatically validated. 

Example:

```json
"eventDuration": {
    "type": "number",
    "min": 1,
    "max": 120,
    "label": "Time in seconds before event reset",
    "xs": 12,
    "sm": 12,
    "md": 4,
    "lg": 3
}
```

**To Reproduce**  
1. In the `jsonConfig.json` file create an item of the type "number" as follows:
    ```json
    "eventDuration": {
        "type": "number",
        "min": 1,
        "max": 120,
        "label": "Time in seconds before event reset",
        "xs": 12,
        "sm": 12,
        "md": 4,
        "lg": 3
    }
    ```
2. Deploy the Adapter with this config. and enter the value `0` manually for the above setting.
3. Save the settings
4. The settings were saved with the non-permitted value

**Expected behavior**  
I expect with the type "number" with specification of the attributes min/max that if the value is outside the specified range I cannot save the settings and am informed of this.

**Screenshots & Logfiles**  
None

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 3.3.14
 - Node version: 12.22.4
 - Operating system: Linux

**Additional context**  
None

**Comment by GermanBluefox** [comment]
Implemented in 5.1.24
![image](https://user-images.githubusercontent.com/4582016/129082482-b745f564-5754-4381-a333-a4f35527924b.png)
