### ISSUE TITLE
HTTP Post to sentry.iobroker.net even though sentry plugin disabled

### ISSUE THREAD

**Issue by thomas725** [ioBroker/ioBroker.admin#1082]
**Describe the bug**  
I can see HTTP Posts to https://sentry.iobroker.net/api/58/envelope/?sentry_key=012345&sentry_version=7 in my Firefox 90.0.2 Developer Tools network tab, even though I
* toggled all adapter instances sentry icons from green to gray
* set all `/system/adapter/.../0/plugins/sentry/enabled` to false (which aren't synchronized with the icons, though they probably should be?)
* ran `iobroker plugin disable sentry` & `iobroker restart` via ssh
* and cleared my browsers cache.

**To Reproduce**  
1. open the default admin.0 instance in your browser.

**Expected behavior**  
With the sentry plugin disabled, the browser should send no requests to sentry.iobroker.net.

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 4.0.0
 - Node version: v14.17.4
 - Operating system: Linux Mint 20.2, Kernel 5.11.0-25
 - NPM            : v6.14.14

**Additional context**  
https://forum.iobroker.net/topic/46921/meldungen-an-sentry-iobroker-net-deaktivieren

**Comment by GermanBluefox** [comment]
Please test 5.1.24

**Comment by thomas725** [comment]
I switched back to beta repository and refreshed the adapter list, but I don't see a version 5.1.24.
How can I test it? Should I install via github link https://github.com/ioBroker/ioBroker.admin ?

**Comment by GermanBluefox** [comment]
Javascript is another issue. Material, Scenes, ECharts, s7, modbus, and other React adapters still send the data to Sentry.
It will be fixed in the future.

5.1.24 is available in beta
