### ISSUE TITLE
"Standard ACL" Error in GUI

### ISSUE THREAD

**Issue by stenmic** [ioBroker/ioBroker.admin#1086]
In den Basiseinstellungen, der Reiter "Standard ACL" erzeugt sofort einen Error in GUI!

Ausgabe F12

TypeError: this.props.data.common.defaultNewAcl is undefined
    value ACLDialog.js:67
    value ACLDialog.js:72
    i ACLDialog.js:168
    value ACLDialog.js:163
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    onHashChanged App.js:938
    r helpers.ts:87
instrument.ts:129:35
    I instrument.ts:129
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    onHashChanged App.js:938
    r helpers.ts:87
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7. (Grund: CORS-Anfrage schlug fehl).

Ich habe iobroker neu auf Debian 10 installiert. Der Fehler kommt schon bei der Ersteinrichtung

**Comment by GermanBluefox** [comment]
Should be fixed in 5.1.24

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1068
