### ISSUE TITLE
Admin - Info zeigt Aktualisierungen nicht an

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#1088]
Wenn ich auf Info gehe, sagt er "Alle Adapter sind aktuell" aber man sieht, dass im Menupunkt "Adapter" Aktualisierungen anstehen. (In diesem Fall ist es ein Update vom web-server).

node.js 14.17.4, npm 6.14.4, admin 5.1.23
iobroker als multihost mit "Master"" auf intel NUC (proxmox container) und slave auf raspi 3b+.

![grafik](https://user-images.githubusercontent.com/45561610/129005641-bfc20880-079a-45b1-92ca-4e066e53b3ee.png)

**Comment by simatec** [comment]
Bitte ein Issue im info Adapter erstellen
