### ISSUE TITLE
Install adapter with option "From Github" fails when repo does not have a master branch

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#1089]
**Describe the bug**  
In expert mode its possible to install adapters from git, here you can use "From Github" which provides a dropdown or the custom URL.
When I try to install my adapters with "From Github" it always fails as my default branch is not named "master" but main.

But the admin try's to use the "master" Branch (which does not exist) and not my default "main" branch
This issue can be reproduced with all adapter part of DrozmotiX org

**To Reproduce**  
1. Activate expert mode
2. Install from custom URL
3. choose option from Github
4. Select an adapter part of the DrozmotiX Organisation (as all of the have their default branch called main)
5. See error in install log : 
```
$ iobroker url https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/tarball/master --host ioBroker
install DrozmotiX/ioBroker.coronavirus-statistics#master
NPM version: 6.14.14npm install DrozmotiX/ioBroker.coronavirus-statistics#master --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code 1
npm ERR! Command failed: git checkout master
npm ERR! error: pathspec 'master' did not match any file(s) known to git
```

**Expected behavior**  
Install command should always use the default branch (of no branche provided)

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 3.3.15
 - Node version: 14
 - Operating system: Ubuntu 20.04

**Comment by AlCalzone** [comment]
> Install command should always use the default branch (of no branche provided)

Solution: JS-Controller should simply invoke the command
```
iobroker url DrozmotiX/ioBroker.coronavirus-statistics --host ioBroker
```
and let `npm` deal with figuring out the default branch. As you can see below, the URL already gets normalized to the form `user/repo[#branch]`, but the incorrect branch is taken from the URL that is passed as the argument.

**Comment by GermanBluefox** [comment]
Please test 5.1.24

**Comment by DutchmanNL** [comment]
> Please test 5.1.24

fix confirmed, thank you !
