### ISSUE TITLE
JavaScript  Editor lässt sich nicht/sporadisch öffnen 

### ISSUE THREAD

**Issue by e-i-k-e** [ioBroker/ioBroker.admin#1091]
Hallo,

der JavaScript Editor (5.2.8) lässt sich nicht öffnen, ich sehe nur einen Dauerladebalken.
Sobald ich ein Downgrade des Adapters mache (z.B: auf 5.2.6) funktioniert es für eine gewisse zeit - dann habe ich wieder das selbe Problem. Wenn ich anschließend den Adapter wieder auf die aktuelle Version hochziehe, geht's auch für eine gewisse zeit. Das Problem ist Browserunabhängig.

Admin befindet sich auf Version 5.1.23.

![2](https://user-images.githubusercontent.com/83473829/129103092-2f200d25-87fb-490e-864a-abb4fe8a92ee.png)

Wenn es dann doch geht, sieht es so aus.
![1](https://user-images.githubusercontent.com/83473829/129103152-8eb4cb04-c66d-448d-872e-3d0d768e5993.JPG)

**Comment by DickenSerm** [comment]
Ich hab das selbe Problem mit dem Dauerladebalken bei Scripte. 

Mir ist allerdings aufgefallen, dass ich dieses Problem nur im Firefox (v91.0) hab in Chrome (v92.0.4515.131) funktioniert alles wunderbar.

**Comment by e-i-k-e** [comment]
Mit dem Admin 5.1.24 ich weiterhin die Probleme. 
![1](https://user-images.githubusercontent.com/83473829/129264075-dd7c38bd-79b3-4568-a28f-d18838877e15.JPG)

**Comment by Apollon77** [comment]
Can you pleas etry "iobroker upload javascript". Does it change something?

**Comment by e-i-k-e** [comment]
> Can you pleas etry "iobroker upload javascript". Does it change something?

Unfortunately no improvement.

**Comment by dg1lxs** [comment]
@e-i-k-e Siehst du die laufenden Instanzen unter "Instanzen" im ioBroker? Ich sehe auch keine Skripte mehr, aber ich sehe auch keine Instanzen mehr. Eventuell hängt das auch zusammen?
#1102

**Comment by e-i-k-e** [comment]
> @e-i-k-e Siehst du die laufenden Instanzen unter "Instanzen" im ioBroker? Ich sehe auch keine Skripte mehr, aber ich sehe auch keine Instanzen mehr. Eventuell hängt das auch zusammen?
> #1102

Das kann ich  bestätigen! Auch die laufenden Instanzen werden nur ab und zu angezeigt, ansonsten Dauerladebalken. 
Bei dem Zigbee Adapter direkt über die Admin Oberfläche ist es ebenso.
Ein Down-/Upgrade löst das Problem für einen Moment. 

Was mir auch aufgefallen ist, seit dem neuen Admin werden einem pro Start ja bestehende Probleme angezeigt. In meinem Fall mit der Backup Adapter. Das Icon davon wird nur dann  angezeigt, wenn ich auch den z.B. JavaScript Editor öffnen kann. Ansonsten wird mir an der Stelle das iobroker Icon angezeigt. 
Wie weit dies mit den anderen Problemen zusammen hängt.. Keine Ahnung 🤔😉

Zur Info: Ich verwende https, eine Umstellung auf http brachte keine Besserung.

**Comment by andiz81** [comment]
Der Link im Menü /#tab-javascript scheint nicht korrekt zu sein. Beim klick bleibt die Seite leer. 
![image](https://user-images.githubusercontent.com/817009/140301332-811bc445-697b-4640-85b8-0efa2bbf4ed1.png)

Ich habe 2 Instanzen installiert
![image](https://user-images.githubusercontent.com/817009/140301507-ce002e75-2b98-401a-898d-d9c02051f15b.png)

**Mein Workaround dafür ist dieser Link: (direkter Aufruf mit URL-Parameter)**
http://server:8081/adapter/javascript/tab.html?instance=1

**Comment by Apollon77** [comment]
WHat error console in browser shows in these cases?

**Comment by andiz81** [comment]
![image](https://user-images.githubusercontent.com/817009/140409964-f78c4fd2-e707-418a-9932-9d29d879a137.png)

**Comment by e-i-k-e** [comment]
Das Problem ist bei mir mittlerweile nicht mehr vorhanden.
Verwendete Versionen: Admin 5.2.3, javascript 5.2.21
