### ISSUE TITLE
Objects view column widths (auto: narrow value column/custom: column titles are off)

### ISSUE THREAD

**Issue by nooxnet** [ioBroker/ioBroker.admin#1097]
**Describe the bug**  
When I don't set individual column widths I get a very narrow "Value" column.
When I set individual widths the widths of the column titles do not match the widths of data columns.

**To Reproduce**  

Auto column width:
I have removed "Room" and "Function" column to have even more space on a 24" monitor. 80% of the screen width is "Id" and "Name". Date values, long numbers or strings longer then 15 characters are not fully visible in the values column.

Custom column width:
I'v set "ID", "Name", "Value" to 300 each.  Then the column titles do not match the columns any more. Additionally the widths are not arranged equally but the ID column is about 50% of the screen width.

**Expected behavior**  
I'm aware that this is surely not an easy task, but I assume this behavior can be improved.

**Screenshots & Logfiles**  
Auto:
![image](https://user-images.githubusercontent.com/16052584/129336165-25564e06-5262-48b1-a05c-6777a894d5de.png)

Width "300" for "ID", "Name" and "Value"
![image](https://user-images.githubusercontent.com/16052584/129336342-d0201e29-c566-4c51-9074-298eef225aa5.png)

Detail:
![image](https://user-images.githubusercontent.com/16052584/129336411-4e44192e-a628-4fb2-8ecc-6212817c71ac.png)

**Versions:**  
 - Adapter version: 5.1.23 and 5.1.24
 - JS-Controller version: 3.3.15
 - Node version: 12.22.4
 - Operating system: Raspbian
 - Browser: Chrome, Edge

**Additional context**  
I would also like to have an option for a smaller font size (and smaller line height) so I can see more data at once. This would also help to see more in the Values column

**Comment by Feuer-sturm** [comment]
@nooxnet Can you please double check your issue with current admin 5.3.7 if it still the same?

**Comment by nooxnet** [comment]
It seems like it's the same as I described it above. Don't know if the behavior has changed slightly.

But there is an additional column which looks like a Unix file access permission. The column header is "Settings". But in the column configurations dialog it's called "Buttons".

![image](https://user-images.githubusercontent.com/16052584/163072390-3edb08dc-5214-4e91-9df4-58ecf29bda9d.png)

![image](https://user-images.githubusercontent.com/16052584/163071985-7ec773ce-4188-40d6-b647-af2a576ae887.png)

**Comment by Feuer-sturm** [comment]
Admin 6.1.2
- The problem with the cloumn header is mentioned here as well: https://github.com/ioBroker/ioBroker.admin/issues/1321
- Your second issue "Buttons" in Popup menu vs "Settings" in the coloum is available in Admin 6.1.2 as well.

**Comment by Feuer-sturm** [comment]
@GermanBluefox I think we can close this issue because this feature was removed in Admin6
