### ISSUE TITLE
Nicht erlaubte Werte werden im Objekte-Explorer nicht abgelehnt

### ISSUE THREAD

**Issue by GitBaer** [ioBroker/ioBroker.admin#1099]
**Describe the bug**  
Wird in einem Number-Datenpunkt eine Einschränkung des zulässigen Wertebereiches vorgenommen ("min:" / "max:"), so werden nicht erlaubte Werte bei Eingabe im Objekte-Explorer nicht abgelehnt und dennoch gespeichert. Lediglich im Logfile erscheint eine Warnmeldung. Das Problem besteht unabhängig davon, ob der Expertenmodus aktiv ist oder nicht.

Das Problem dürfte verwandt sein mit diesem: https://github.com/ioBroker/ioBroker.admin/issues/1081

**To Reproduce**  
1. Neues Objekt vom Typ "Datenpunkt" unterhalb von 0_userdata.0 erstellen.
2. "Type" des Datenpunktes muss "number" sein.
3. "min" und "max"-Werte festlegen wie im nachfolgenden Beispiel:
>{
>   "common": {
>   "name": "TestA1",
>   "desc": "Manuell erzeugt",
>   "role": "state",
>   "type": "number",
>   "min": 0,
>   "max": 50,
>   "read": true,
>   "write": true,
>   "def": ""
>   },

4. Anschließend im Objekte-Explorer z.B. den Wert "60" eintragen. Die Eingabe wird nicht abgelehnt, obwohl sie außerhalb des defiierte Wertebereiches liegt. Im Protokoll des Admin-Adapters erscheint die Warnung: 
`State value to set for "0_userdata.0.TestA1" has value "60" greater than max "50"`

**Expected behavior**  
Bereits das Speichern eines nicht zulässigen Wertes sollte mit einer Fehlermeldung abgelehnt werden.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

![grafik](https://user-images.githubusercontent.com/49997071/129457522-a955a8ed-0fbc-4bab-9bde-c1b3fa289885.png)

![grafik](https://user-images.githubusercontent.com/49997071/129457529-043469d1-c83b-4230-acec-a48d443774de.png)

![grafik](https://user-images.githubusercontent.com/49997071/129457561-3ad0f90e-03bb-43cd-bc00-7ed3bab5ab00.png)

**Versions:**  
 - Adapter version: 5.1.24
 - JS-Controller version: 3.3.15
 - Node version: v14.17.4
 - Operating system: Debian 10

**Additional context**  
-

**Comment by Apollon77** [comment]
Hi,

was expert mode enabled? or not?

**Comment by GitBaer** [comment]
> Das Problem besteht unabhängig davon, ob der Expertenmodus aktiv ist oder nicht.

No, expert mode was not enabled.

I tried with enabled and disabled expert mode - problem is still the same.

Thank you.

**Comment by GitBaer** [comment]
@GermanBluefox sicher, dass das „enhancement“ und kein Bug ist? Im verlinkten Issue wurde der vergleichbare Sachverhalt als Bug eingestuft und zudem meine ich, dass das Verhalten früher bereits so war.

**Comment by Apollon77** [comment]
@GitBaer Das verlinkte Issue geht um was ganz anderes. Von daher hat das damit nichts zu tun.

Am Ende hat auch Admin4 noch nie min/max Werte geprüft und daher ist es ein Enhancement

**Comment by GitBaer** [comment]
@Apollon77 danke für Deine Antwort - ich dachte, dass dieses Verhalten vor einiger Zeit mal anders war und fühlte mich durch den Beitrag von Homoran (https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/292?_=1629043377092 - "Wenn ich da nichts verwechsle, wurde das früher "beschnitten". Da sollte IMHO jetzt nur 50 drin stehen") bestärkt.

Wie dem auch sei: wäre toll, wenn diese Prüfung eingefügt werden könnte, damit falsche Werte garnicht erst durch einen User ins System gebracht werden können ...
