### ISSUE TITLE
Instanzen: "Alle Elemente werden herausgefiltert" (angeblich) 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.admin#1102]
Seit dem Wechsel auf Admin 5.1.23 sehe ich gelegentlich keine Instanzen. 
Ich sehe dann nur den Hinweis "Alle Elemente werden herausgefiltert".

Bisher konnte ich es nur mobil feststellen (nutze den iobroker zu 95% mobil). Ein Wechsel von Desktop zur mobilen Ansicht oder anders rum löst das Problem immer.

Mobil kann ich vermutlich keinen ordentlichen Browser-Log erstellen..... 

Hier hat das Problem auch jemand am Desktop:
https://forum.iobroker.net/topic/47042/keine-instanzen-bei-admin-5-1-23?_=1628967139946

**Comment by GermanBluefox** [comment]
Es kann sein, dass irgendwelche Filters doch gesetzt sind. 
Ab nächster Version: 
![image](https://user-images.githubusercontent.com/4582016/129475621-ce0c0d09-f434-45f8-a511-8b3eec60d32e.png)

**Comment by meerkat82** [comment]
Hi, hier wie besprochen noch mein Auszug der Console
![1628978278786-0f6bdd14-8b1a-479e-b720-07a7c54b5bf9-image](https://user-images.githubusercontent.com/72659369/129480459-de298120-d21b-433e-8aea-647dc7f5cf63.png)

**Comment by ipod86** [comment]
Filter hatte ich keine gesetzt.
Kommt bei mir auch sporadisch.

Wenn es nochmal kommt, schicke ich ein Bild.

**Comment by Feuer-sturm** [comment]
Admin 5.1.25

In Admin 5.1.25 kann man auf den Text  "Alle Elemente herausgefilter" klicken, um den gesetzten Filter zu löschen
![grafik](https://user-images.githubusercontent.com/25422320/129570187-acb527ad-3b0c-4a13-bd80-f9bab5c9e2d9.png)

**Comment by meerkat82** [comment]
Hi @Bluefox,

ich habe das Problem mit meinen Instanzen immer noch. Wenn ich die Instanzen anhalte und neu starte, dann werden sie bis zum nächsten refreshen der Ansicht angezeigt und ab dann sind sie nicht mehr sichtbar. Ich habe das Log der Console nochmal beigefügt.
![image](https://user-images.githubusercontent.com/72659369/129621595-9eba3e31-020f-4c82-8c2e-32181ef8f81e.png)

**Comment by ipod86** [comment]
Gestern hatte ich es auch nochmal.
Hab allerdings nicht geschaut, ob ich noch wo drücken kann. Hab den Post von oben noch nicht gesehen gehabt. 

![Screenshot_20210816-084507_Chrome](https://user-images.githubusercontent.com/66136363/129668020-9c07f0ae-4ba6-43a0-aab1-6aac2fe18f0e.jpg)

**Comment by dg1lxs** [comment]
Hi,

Ich habe das Problem ja auch schon im Forum geschildert, aber hänge mich hier gerne noch mal an. Meine Konsole schaut auch sehr unauffällig aus:

<img width="1231" alt="Bildschirmfoto 2021-08-17 um 19 47 18" src="https://user-images.githubusercontent.com/77673186/129775781-db8c34b3-8200-48ba-b6a6-6cebc525a518.png">

Mich beruhigt es ein wenig, nicht alleine zu sein:-)

Viele Grüße,

Alexander

**Comment by Feuer-sturm** [comment]
@dg1lxs Dann wäre es ja bei dir auch ein Versuch in der 5.1.25 einmal auf den Text "Alle Elemte werden herausgefilter" zu klicken, um dann zu schauen ob wieder alle Instanzen sichtbar sind

**Comment by dg1lxs** [comment]
> @dg1lxs Dann wäre es ja bei dir auch ein Versuch in der 5.1.25 einmal auf den Text "Alle Elemte werden herausgefilter" zu klicken, um dann zu schauen ob wieder alle Instanzen sichtbar sind

Das funktioniert leider auch nicht. :-(
Mir ist übrigens gestern Abend noch aufgefallen, dass ich auch meine Skripte und die anderen Tabs von Adaptern nicht mehr aufrufen kann. Die Fehlermeldung in der Console ist (für Javascript, aber analog auch für "Kommandos" oder "Backup"
`Cannot find instance tab-javascript`
Die Skripte, backups, etc laufen aber. Nur das Webinterface funktioniert nicht.

<img width="536" alt="Bildschirmfoto 2021-08-18 um 07 57 24" src="https://user-images.githubusercontent.com/77673186/129845363-baeebb2e-1fb7-408f-a512-cc433a66e37d.png">

Ich habe dazu aber glaube ich schon ein issue oder eine Diskussion gesehen, evtl. hilft das den root-cause zu beheben.

Viele Grüße,

Alexander

**Comment by meerkat82** [comment]
HI @GermanBluefox ,
ich habe nun mal eine komplett neue ioBroker Installation durchgeführt. Gestern lief alles super und heute sind wieder alle Instanzen weg bzw. werden nicht mehr angezeigt. Mittlerweile ist es doch etwas nervig. Kannst du da bitte nochmal schauen. 

DANKE

**Comment by ipod86** [comment]
So, hatte es eben unter Chrome am Smartphone nochmal.

Auf  "Alle Elemte werden herausgefilter" kann nicht gedrückt werden. Ist kein Link oder Aktion hinterlegt.
Dieses Mal hat auch der Wechsel zwischen den Ansichten nichts gebracht und musste zu Firefox (auch mobil) wechseln.

**Comment by worksasdesigned** [comment]
Gleiches Problem. 
5.1.25

Auf den Link klicken hilft nichts
![image](https://user-images.githubusercontent.com/13118233/130359340-048f6933-6a42-4ca9-be54-fa26be0dd6e2.png)

**Comment by dg1lxs** [comment]
Hallo,
Ich bin inzwischen ein wenig am Verzweifeln. Mein iobroker ist aktuell durch diesen Bug nicht mehr konfigurierbar. Das "fixed" label an dem issue macht mich auch etwas nervös. Dadurch, dass ich (vermutlich durch das selbe Problem) auch nicht auf meine  Skripte zugreifen kann bin ich ziemlich im Blindflug.... Ich muss wohl versuchen noch mal aus dem Backup wiederherzustellen, aber es gibt ja auch Meldungen, dass das auch nicht funktioniert. Mir gehen die Ideen aus:-( Und mein Gefühl ist, dass das Problem noch nicht wirklich als potentieller Bug akzeptiert ist....

**Comment by worksasdesigned** [comment]
Das wird dir jetzt wenig helfen.
Ich habe meinen mehrfach neu gestartet (Strom getrennt, Sudo reboot, …)
Browser Cache gelöscht…
Sudo apt-get update


Irgendwann hat es wieder funktioniert- ohne etwas neues in iobroker zu installieren
Am 13. Sept. 2021, 08:45 +0200 schrieb dg1lxs ***@***.***>:

**Comment by Apollon77** [comment]
Also ja mal Browser cache inklusive local storage und so leeren (oder mal per inkognito modus) ... das sollte auf jeden Fall al sicherstellen das sich da nicht irgendwas verklemmt hat

**Comment by dg1lxs** [comment]
Ich habe schon zigfach den browser cache geleert, multiple devices mit vielen Browsern getestet, aber immer das selbe...  Auch mit und ohne reverse proxy macht keinen Unterschied. 
Vielleicht noch eine Kleinigkeit, evtl. hilft das: Manchmal nach dem Aufruf der Seite kommt diese Fehlermeldung:
<img width="975" alt="Bildschirmfoto 2021-09-13 um 09 45 42" src="https://user-images.githubusercontent.com/77673186/133071209-d3f1741f-afa3-4616-b9ac-3b38a7d16b95.png">
Ich bin direkt über gibt LAN verbunden, also sollte die Verbindung eigentlich nicht zu langsam sein:-) Kann es sein, dass der Admin Adapter noch andere Ports als 8081 verwendet?

**Comment by worksasdesigned** [comment]
Geh mal per ssh drauf und mach ein
Sudo apt-get update
Am 13. Sept. 2021, 12:53 +0200 schrieb dg1lxs ***@***.***>:

**Comment by dg1lxs** [comment]
auch wenn ich iobroker im docker image laufen habe habe ich das schon gemacht (Apt update und apt upgrade). beim nächsten pull des Images wird es wieder weg sein, aber es hat leider auch keinen Unterschied gemacht:-(

**Comment by Apollon77** [comment]
Anderer Port also 8081 nicht aber Websocket hat - keine AHnung ob das nichwichtig ist bei Dir? Falls ein Reverse Proxy genutzt wird muss man das ggf extra einstellen (siehe Readme vom Admin)

**Comment by meerkat82** [comment]
Hallo,
ich habe den Fehler ebenfalls immer noch. Mittlerweile macht es keinen Spaß mehr, mit dem ioBroker zu arbeiten, was ich extrem Schade finde. Ich möchte hier nochmals bitten, sich dem Thema anzunehmen, da es anscheinend laut Issues nicht das erste mal ist, dass die Instanzen nicht angezeigt werden.

**Comment by Apollon77** [comment]
Ok ich glaube hier werden verschiedenen Dinge in einem Issue gemischt ... also jeder der hier postet bitte sagen WAS GENAU nicht tut ... Kommt die "Langsame Verbindung" meldung? Kommen JavaScript Fehelr? Werden DInge ausgefilter? beim drüberscrollen sehe ich diese 3 Themen hier in einem Thread. Mega undurchsichtig!

Am liebsten würde ich den schliessen das Ihr bitte zielgerichtet mit Screenshots und ggf Fehlermeldungen neue Issues anlegt die NICHT dem TitelThema "Instanzen werden hrausgefiltert" entspricht!

**Comment by meerkat82** [comment]
Hallo @apollo77.
Ich habe immer noch das Problem, das alle Instanzen herausgefiltert werden. Ich kann keine einzige Instanz konfigurieren, bis ich sie deaktiviere und wieder starte, so wie es im Ursprung genannt wurde. Deaktivieren und starten geht auch nur über die console am Pi.
Die Instanzen werden dann auch nur so lange angezeigt, bis ich einmal auf einen anderen Menüpunkt in der admin Oberfläche klicke, danach sind sie nicht mehr zu sehen und ich muss ihn wieder deaktivieren und starten.

**Comment by meerkat82** [comment]
Hallo @Apollon77 7.
Ich habe immer noch das Problem, das alle Instanzen herausgefiltert werden. Ich kann keine einzige Instanz konfigurieren, bis ich sie deaktiviere und wieder starte, so wie es im Ursprung genannt wurde. Deaktivieren und starten geht auch nur über die console am Pi.
Die Instanzen werden dann auch nur so lange angezeigt, bis ich einmal auf einen anderen Menüpunkt in der admin Oberfläche klicke, danach sind sie nicht mehr zu sehen und ich muss ihn wieder deaktivieren und starten.

**Comment by Ilovegym66** [comment]
Hi, ich habe das Problem auch, dass der Filter alles filtert bei den Instanzen, obwohl nichts im Filter eingetragen ist.
Grundlegend ist hier für mich ebenso, warum man verschiedene Filterbuttons macht, in Javascript-Adapter siehts anders aus, beim Admin bei der Adapterliste ist der Filter auch anders designed. ( also der Button.. und bestimmt auch der Code hintendran).
Das ist erstens verwirrend und zweitens finde ich den Filter bei Instanzen ehrlich gesagt fehl am Platz.
Der oben genannte Effekt, dass keine Instanzen mehr angezeigt werden, tritt nach einiger Laufzeit des iobrokers bei mir auf, sowohl bei Chrom, Firefox als auch Safari. 
Ein komplettes refresh der Seite und leeren des Caches des Browsers bringt ab und zu abhilfe, ein Fenster im Privaten Modus dagegen immer.
Oft behelfe ich mir auch mit dem Kommando `iobroker set admin.0 --react false`  dann wird die Admin Instanz neu gestartet und danach sind oft die Instanzen wieder sichtbar. Der alte Modi funktioniert mit dem Kommando nicht mehr.
Alternativer Workaround ist immer noch das bearbeiten der Instanzen über die Cloud, das funktioniert einwandfrei.

Wenn ich mal wieder mehr Zeit habe, kann ich auch ein paar Debuglogs von der Webkonsole etc bringen, zur Zeit mehr den 14h Arbeitstag und da bleibt fürs Hobby erstmal nix übrig..

Vielleicht helfen ja die Workarounds ein paar..

**Comment by dg1lxs** [comment]
> Ok ich glaube hier werden verschiedenen Dinge in einem Issue gemischt ... also jeder der hier postet bitte sagen WAS GENAU nicht tut ... Kommt die "Langsame Verbindung" meldung? Kommen JavaScript Fehelr? Werden DInge ausgefilter? beim drüberscrollen sehe ich diese 3 Themen hier in einem Thread. Mega undurchsichtig!
> 

Hi,

Das Kernproblem ist, dass keine Instanzen angezeigt werden. Die anderen Themen sind potentiell zusammenhängende Hilfen bei der Fehlersuche.

**Comment by Apollon77** [comment]
Okm wenn keine Instanzen mehr angezeigt werden: Gibts einen Fehler ind er Javascriot Konsole im Browser? Wenn ja welchen? Ist das einer der Fehler von oben?

**Comment by dg1lxs** [comment]
> Okm wenn keine Instanzen mehr angezeigt werden: Gibts einen Fehler ind er Javascriot Konsole im Browser? Wenn ja welchen? Ist das einer der Fehler von oben?

Hi,

Meiner Meinung nach ist kein Fehler erkennbar: https://github.com/ioBroker/ioBroker.admin/issues/1102#issuecomment-900509889

**Comment by DannySotzny** [comment]
Habe hier das gleiche Problem seit dem Update. Gestern ging es mal .. und heute wieder nicht. Über den Websocket kommen die Daten rein.. aber er zeigt nie etwas an. In der WebConsole gibt es 0 Fehler
![image](https://user-images.githubusercontent.com/14806755/133428802-9b304eb5-b994-442d-a942-05be69818cb6.png)

**Comment by meerkat82** [comment]
Hi @Apollon77,
hier nochmal was die Console ausgibt, wenn ich auf Instanzen klicke
![image](https://user-images.githubusercontent.com/72659369/133491683-87a28955-651f-4dc7-8d5c-bc07e2c8f3fa.png)

**Comment by DannySotzny** [comment]
auch in der 5.1.25 gibt es den Fehler noch. Beim 1. Aufruf nach dem Update sah ich die Instanzen, dann habe ich Reload (Strg+R) gemacht und dann waren sie wieder weg... :-(

![image](https://user-images.githubusercontent.com/14806755/133511683-d4d9704e-97e6-4957-a340-d72320fa4756.png)

**Comment by Fredchenhh** [comment]
Moin zusammen, na da bin ich ja beruhigt das ich nicht der einzige bin. Ich habe das Problem auch seit dem Update. 

Wenn ich den iobroker aufrufe zeigt er mir manchmal auch an "langsame Verbindung erkannt" Dann kann ich das Timeout Intervall verlängern. Wenn ich dieses von 15 auf 30 stellen möchte, sagt er mir "Cannot getRepositoryCompact: getCompactRepository timeout". Zusätzlich ploppt auch manchmal  "getHostInfo timeout" auf. 

> [Log] iobroker.admin@5.1.23 (main.692229dc.chunk.js, line 2)
[Log] [2021-09-15T14:25:56.525Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Socket is not connected
[Error] Socket Error: UNKNOWN
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (main.692229dc.chunk.js:2:1099140)
	(anonyme Funktion) (main.692229dc.chunk.js:2:859565)
	forEach
	(anonyme Funktion) (socket.io.js:138)
[Log] [2021-09-16T07:24:11.337Z] Start reconnect 0 (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Socket is not connected
[Log] [2021-09-16T07:24:11.448Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Error] [2021-09-16T07:24:12.340Z] ws connection error: CLOSE_ABNORMAL
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Error] WebSocket connection to 'ws://192.168.178.3:8081/?sid=1631777051448&name=admin' failed: WebSocket is closed before the connection is established.
	(anonyme Funktion) (socket.io.js:341)
	(anonyme Funktion) (socket.io.js:130)
[Log] [2021-09-16T07:24:13.116Z] Start reconnect 1 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T07:24:13.119Z] Reconnect is already running 1 (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Can't assign requested address (x2)
[Error] [2021-09-16T07:24:13.130Z] ws connection error: CLOSE_ABNORMAL
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Log] [2021-09-16T07:24:13.130Z] Reconnect is already running 1 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T07:24:14.117Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Network is unreachable
[Log] [2021-09-16T07:24:14.155Z] Start reconnect 2 (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Network is unreachable
[Error] [2021-09-16T07:24:14.161Z] ws connection error: CLOSE_ABNORMAL
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Log] [2021-09-16T07:24:14.161Z] Reconnect is already running 2 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T07:24:16.156Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Network is down
[Log] [2021-09-16T07:24:16.158Z] Start reconnect 3 (5.42ef9396.chunk.js, line 2)
[Error] WebSocket network error: The operation couldn’t be completed. Network is down
[Error] [2021-09-16T07:24:16.159Z] ws connection error: CLOSE_ABNORMAL
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Log] [2021-09-16T07:24:16.159Z] Reconnect is already running 3 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T07:24:19.160Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Log] Repo updated! (5.42ef9396.chunk.js, line 2)
[Error] [2021-09-16T21:13:55.138Z] ws connection error: CLOSED_NO_STATUS
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Log] [2021-09-16T21:13:55.185Z] Start reconnect 0 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T21:13:55.206Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Error] [2021-09-16T21:15:41.492Z] ws connection error: CLOSED_NO_STATUS
	(anonyme Funktion) (5.42ef9396.chunk.js:2:6132564)
	(anonyme Funktion) (socket.io.js:128)
[Log] [2021-09-16T21:15:41.518Z] Start reconnect 0 (5.42ef9396.chunk.js, line 2)
[Log] [2021-09-16T21:15:41.539Z] Try to connect (5.42ef9396.chunk.js, line 2)
[Log] getInstances: 12 (5.42ef9396.chunk.js, line 2)
[Log] [ADAPTERS] getAdapters (5.42ef9396.chunk.js, line 2)
[Log] [ADAPTERS] getAdaptersInfo (5.42ef9396.chunk.js, line 2)
[Log] [ADAPTERS] Render (5.42ef9396.chunk.js, line 2)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (socketio.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (players.png, line 0)
[Log] [ADAPTERS] Render (5.42ef9396.chunk.js, line 2, x2)
[Error] Failed to load resource: the server responded with a status of 404 () (players.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (socketio.png, line 0)

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/51527408/133756293-3f0a1b02-4f06-4d41-8b62-83bdda31e184.png">

**Comment by dg1lxs** [comment]
Hi, ich habe mir nun den kompletten iobroker mit einem backup neu aufgesetzt. Das hat leider auch nichts gebracht :-( 
![Bildschirmfoto 2021-09-18 um 14 20 58](https://user-images.githubusercontent.com/77673186/133888628-691254da-c97a-4f49-bc81-b2a71c8c36ab.png)
Ich bin mit meinem Latein am Ende.

Mich irritiert ja immer noch das "Fixed" Attribut für das issue.... Ich kann seit einem Monat eigentlich nichts mehr machen und ich sehe keinen Ausweg. Der iobroker ist kein ganz unwichtiges Element in meiner Hausautomatisierung.... Aktuell läuft noch alles, aber sobald ich was ändern will habe ich keine Chance mehr :-( 

P.S.: Ja ich habe schon alle Caches geleert, neu gestartet und von vielen verschiedenen Browsern und Rechnern probiert. Direkt nach der Installation oder dem Update eines Adapters ist er manchmal für eine kurze Zeit in der "Instanzen-Übersicht" zu sehen und kann konfiguriert werden. Beim nächsten Re-Load ist wieder alles weg:-(

**Comment by dg1lxs** [comment]
Hi, 

Ich habe noch mal etwas weitergesucht und mir inspiriert von @DannySotzny die Socket-Daten angeschaut. Ich sehe keine getAdapters Nachricht wie er, aber dafür eine getCompactAdapters und getCompactInstances:
![Bildschirmfoto 2021-09-18 um 14 58 19](https://user-images.githubusercontent.com/77673186/133889662-05e691ab-fd23-4fec-809d-b5ade5597464.png)

Angezeigt wird aber keine Instanz.

Danach habe ich auf der Konsole mal einen Adapter gestopft und gestartet. Mit dem Start Commando sehe ich eine ObjectChange Nachricht (oder eigentlich 2). Danach wird der Adapter in der Übersicht automatisch ohne Reload der Seite in der Liste angezeigt. 
![Bildschirmfoto 2021-09-18 um 15 01 27](https://user-images.githubusercontent.com/77673186/133889717-b3ea3509-30d4-4648-81b8-e73cbfa73704.png)

Vielleicht hilft es. Wenn ich mehr Daten liefern soll, mache ich das sehr gerne!

Alexander

**Comment by Ilovegym66** [comment]
Hi, vom Backup zurück bringt in dem Fall nichts, da musst du schon ne ältere Admin Version einspielen.. irgendwann fing das mal an, mit dem blöden Filter.. von mir aus kann der da sowieso weg.. ich hab ja keine 100 Instanzen und wenn kann ich auch mal scrollen..

Wie geschrieben, notlösung ist per cloud drauf, oder ein `iobroker set admin.0 --react false`  hilft auch erstmal, er geht zwar nicht mehr auf das alte Gui aber man sieht die Instanzen wieder.

Mich wundert es, dass bei so vielen Usern auftritt, aber nicht bei den Entwicklern, oder sie wissen es und haben zur Zeit keine Lösung.. Genug Logfiles und Auszüge aus der Webconsole sind ja gepostet worden mit genug Fehlern drin..

100% kann ich es nachvollziehen, wenn der Expert Modus eingeschaltet ist.
Ist der aus, läuft der iobroker Admin länger, bis der Fehler auftritt.

Aber alles in allem sehr unbefriegend, gerade wenn man mal schnell was ändern möchte, und nicht in die Config vom Adapter kommt...

**Comment by dg1lxs** [comment]
Hi, als Workaround hat bei mir nun geholfen, dass ich den Admin Adapter nach ein paar Neustarts kurz bei den Instanzen gesehen habe. Dort konnte ich via GUI auf das Alte UI umstellen. Seit dem schaut es ganz gut aus (also ich mehr optisch, aber ich sehe alle Instanzen :-) ).
Aber eine tolle Lösung ist es natürlich nicht.

Alexander

**Comment by joerghohn** [comment]
Moin,
hatte das Problem eben auch, und das hat geholfen, danke @Ilovegym66 
Bei `iobroker set admin.0 --react false` kommt zwar eine Fehlermeldung `Adapter "admin.0" has no setting "react".`, aber danach funktioniert es bei mir wieder.

**Comment by zahnheinrich** [comment]
Hänge mich auch dran:

Ich kämpfe mit dem selben Problem.
Mein System: Docker auf Synology, Container mit buanet:latest repo, alle Adapter stable
Installation:
```
root@ServerRubensstr:/opt/iobroker# which nodejs node npm && nodejs -v && node -v && npm -v && sudo apt update && sudo apt update && ap
t policy nodejs
/usr/bin/nodejs
/usr/bin/node
/usr/bin/npm
v12.22.6
v12.22.6
6.14.15
OK:1 http://security.debian.org/debian-security buster/updates InRelease
OK:2 http://deb.debian.org/debian buster InRelease                                       
OK:3 http://deb.debian.org/debian buster-updates InRelease                               
OK:4 https://deb.nodesource.com/node_12.x buster InRelease                               
Paketlisten werden gelesen... Fertig                             
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
OK:1 http://deb.debian.org/debian buster InRelease
OK:2 http://deb.debian.org/debian buster-updates InRelease                               
OK:3 http://security.debian.org/debian-security buster/updates InRelease                 
OK:4 https://deb.nodesource.com/node_12.x buster InRelease                               
Paketlisten werden gelesen... Fertig                             
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
nodejs:
  Installiert:           12.22.6-deb-1nodesource1
  Installationskandidat: 12.22.6-deb-1nodesource1
  Versionstabelle:
 *** 12.22.6-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_12.x buster/main amd64 Packages
        100 /var/lib/dpkg/status
     10.24.0~dfsg-1~deb10u1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
```

 Herausgefunden habe ich nach mehrtägigen Anläufen:

Neuen Container ohne vorhandene Daten aufgesetzt: -> Funktion normal, keine Auffälligkeiten, Vorinstallierte Instanzen (Admin, Backitup) sichtbar im Instanzen TAB.

Anschliessend Datensicherung Backitup über Konsole eingespielt:
- alle Datenpunkte vorhanden
- Keine Instanz im Instanzen TAB sichtbar, nur Anzeige "Alle Elemente werden herausgefiltert".
- In der Konsole manuell gestartete Instanzen werden anschliessend im Instanzen-TAB normal angezeigt und sind bedienbar.
- Sobald ein forced refresh ausgeführt wird, sind alle Instanzen wieder unsichtbar, Azeige wieder "Alle Elemente werden herausgefiltert" 
- Alle Instanzen in der Konsole erneut gestartet -> Im Instanzen-TAB alles wieder normal sichtbar.
Öffne dann ein zweites Browserfenster und rufe den Instanzen-TAB auf: Keine Instanz sichtbar, Anzeige "Alle Elemente werden herausgefiltert"  

In der Entwicklerkonsole keine Fehler, aber mehrere Warnungen:
```
Utils.js:471 Please add to "system.adapter.javascript" common.adminUI={"config":"materialize","tab":"html"}
value @ Utils.js:471
Instances.js:444 getInstances: 4
3Utils.js:471 Please add to "system.adapter.javascript" common.adminUI={"config":"materialize","tab":"html"}
value @ Utils.js:471
Utils.js:471 Please add to "system.adapter.squeezeboxrpc" common.adminUI={"config":"materialize"}
value @ Utils.js:471
2Instances.js:444 getInstances: 2
Instances.js:444 getInstances: 6
Utils.js:471 Please add to "system.adapter.sonoff" common.adminUI={"config":"materialize"}
value @ Utils.js:471
Instances.js:444 getInstances: 2
```

Hoffe auf baldige Problemlösung

Edit: gleiches Verhalten in Chrome, FF, Opera

**Comment by phg2k** [comment]
Warum hier als Label immer noch "fixed" erscheint ist mir schleierhaft!!
Der Fehler ist doch recht heftig - wäre schön wenn er wirklich bald "gefixed" würde.

**Comment by tniercke** [comment]
+1

Der Tag "fixed" sollte wirklich entfernt werden.

Ich habe gerade auf 5.1.25 geupdated und habe das Problem auch.
War ein Update von 5.1.23 auf 5.1.25.
Bei der Version 5.1.23 war noch alles in Ordnung mit den Instanzen.

**Comment by tniercke** [comment]
@GermanBluefox GermanBluefox
needs remove tag "fixed"

**Comment by Wegatarus** [comment]
Hallo zusammen, 

bei mir ist eine neuer Effekt aufgetreten. von einem PC mit Firefox werden die Adapter nun nicht mehr angezeigt mit gleicher Meldung: "Alle Elemente werden herausgefiltert " Dafür sind aber die Instanzen sichtbar. 
Gleichzeitig über einen anderen Rechner mit Chrome sind es immer noch die Instanzen, die nicht angezeigt werden.
Also schön, wenn man mehrer Rechner hat.....
VG

**Comment by volkerrichert** [comment]
Ich habe das an einer anderen Stelle:

![image](https://user-images.githubusercontent.com/640914/141442887-8412a533-7fae-4f13-9174-cd5829d731d8.png)

die `newVersion` ist dabei leer. Leider kommt das dann immer wieder bis ich abbrechen klicke. Vermutlich hatte er Probleme die neue Version zu lesen. Aber dann sollte es besser keinen UpdateCheck geben

Volker

**Comment by Ilovegym66** [comment]
sollte mit Version 5.1.28 behoben sein, bei mir tritt seitdem der Fehler nicht mehr auf.

**Comment by volkerrichert** [comment]
ich habe die 5.1.28. Tritt also immer noch auf

**Comment by Bacaloni** [comment]
> Seit dem Wechsel auf Admin 5.1.23 sehe ich gelegentlich keine Instanzen. Ich sehe dann nur den Hinweis "Alle Elemente werden herausgefiltert".
> 
> Bisher konnte ich es nur mobil feststellen (nutze den iobroker zu 95% mobil). Ein Wechsel von Desktop zur mobilen Ansicht oder anders rum löst das Problem immer.
> 
> Mobil kann ich vermutlich keinen ordentlichen Browser-Log erstellen.....
> 
> Hier hat das Problem auch jemand am Desktop: https://forum.iobroker.net/topic/47042/keine-instanzen-bei-admin-5-1-23?_=1628967139946

Bei mir ist der Fehler nur im Google Chrome bei Firefox oder Edge besteht das Problem nicht

**Comment by Ilovegym66** [comment]
cache leeren hilft.

**Comment by Bacaloni** [comment]
> cache leeren hilft.

Danke

**Comment by romannknesch** [comment]
Kurz mal die Frage in die Runde ob hier noch dran gearbeitet wird. 

Ich weiß nicht ob das als Dauerlösung funktioniert bei jeder Sitzung den Cache löschen zu müssen...

Danke vorab und Frohes Fest!

**Comment by Ilovegym66** [comment]
Ja schon lange erledigt, einfach mal Update einspielen!

**Comment by romannknesch** [comment]
Merkwürdig, hat mir seit 5.1.25 keine neue stable version angeboten. Danke für den Tipp!

**Comment by Feuer-sturm** [comment]
Problem scheint mit den neueren Versionen nicht mehr aufzutreten. Ich mache das issue erstmal hier zu, wenn es doch weiterhin auftreten sollte kann das issue wieder geöffnet werden.
