### ISSUE TITLE
jsonConfig file upload

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#1103]
**Is your feature request related to a problem? Please describe.**
Need it for sayit, as there can be choosen announcment sounds that can be uploaded by the user.

**Describe the solution you'd like**
Implemantation like the picture upload would be nice.

**Describe alternatives you've considered**
There is no Alternative

Seems this feature is already planned, as written in the schema:

> !file - saves file (not image) as file of adapter.0 object
filename - name of file

**Comment by GermanBluefox** [comment]
Imlemented

**Comment by GermanBluefox** [comment]
See https://github.com/ioBroker/ioBroker.admin/issues/1535
