### ISSUE TITLE
After upgrade to Admin 5 - loading forever

### ISSUE THREAD

**Issue by DominikReber** [ioBroker/ioBroker.admin#1110]
Hallo zusammen

Habe auf Admin 5 geupdated
https://forum.iobroker.net/assets/uploads/files/1629105210640-5e27b877-dc05-4f22-ba6f-842f4bac21ec-image.png
Das wird jetzt seit 10 Minuten angezeigt.
Lade ich die Seite neu (cache gelöscht), kommt einfach nur:
https://forum.iobroker.net/assets/uploads/files/1629105258217-362b75dd-2e0f-493b-8785-e87fa6477ec0-image.png

iobroker status zeigt:
https://forum.iobroker.net/assets/uploads/files/1629105302648-6220c732-ee0e-4742-8abd-84ad6d60de6a-image.png

Irgendeine Idee?

Bin für jegliche Hilfe dankbar

Dominik

**Comment by Apollon77** [comment]
Bitte Browser ENtwicklertools ööffnen und schauen ob ein Fehler in der Browser-Konsole steht

**Comment by DominikReber** [comment]
Mach ich gleich.
Hab ein Downgrade auf 4.2.2 gemacht - das Problemlos funktioniert hat. Versuche es nochmals.

**Comment by DominikReber** [comment]
![image](https://user-images.githubusercontent.com/63448986/129541892-994f39d6-e29c-4eb3-be48-6d1b2d7ab9a1.png)
Neuinstallation hat jedenfalls schon mal keinen Fehler angezeigt aber mit gleichem Resultat. 
Schaue gerade in die Entwicklerkonsole

**Comment by DominikReber** [comment]
![image](https://user-images.githubusercontent.com/63448986/129542316-5269864a-fc70-4679-af1f-456098b77baa.png)

**Comment by Apollon77** [comment]
https??? und ne eigene Domain? Mit reverse proxy?  In Admin5 wird das hier wichtig ... https://github.com/ioBroker/ioBroker.admin#reverse-proxy ... beachtet?

**Comment by DominikReber** [comment]
Ja https, ne eigene Domain und reverse proxy. Ich weiss, würden viele nicht empfehlen, aber ich seh das risiko als überschaubar an. 

Ich werd das gleich anschauen. Bei Admin 4 gings noch, aber du schreibst ja, dass bei Admin 5 das wichtig ist. Da macht die Fehlermeldung auch Sinn.

**Comment by DominikReber** [comment]
Das wars, danke!

Aufm Synology Websockets im Reverse Proxy aktiviert und das hat geholfen.

**Comment by Apollon77** [comment]
Bei Admin4 hat die socket.io Library auf "Data polling" ugeschaltet wenn keine Websockets gingen - was aber immer wieder nachteile hat. Admin5 hat eine andere Websocket Lib und die macht das nicht mehr ... also ohne Websocket Support kommt nichts mehr durch

**Comment by DominikReber** [comment]
Danke für die Info. Admin 5 funktioniert soweit sehr stabil, danke!
