### ISSUE TITLE
adapter in different languages not found

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1111]
**Describe the bug**  
Adapter „Visualisierung“ will only be found if `visualis` is entered. It is not found if `visualisi` is entered.

**To Reproduce**  
1. Go to Admin, open Adapter
2. Enter `visualis` or `visualisi` in field `Nach Namen filtern`
3. Adapter is displayed / not displayed

**Expected behavior**  
Adapter are shown if german, english (and all other supported languages?) Adaptername is entered.

**Versions:**  
 - Adapter version: admin v5.1.23
 - JS-Controller version: v3.3.15
 - Node version: v12.22.5
 - Operating system: linux

**Additional context**  
see https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/299?_=1629133588666

**Comment by GermanBluefox** [comment]
Should work now:
![image](https://user-images.githubusercontent.com/4582016/173088732-8305fbc4-effd-4a0f-98ca-3aacc7b4cee0.png)

**Comment by ice987987** [comment]
I find the vis-adapter only with `visualis`
![FE832E5A-E398-4EC5-8677-DE2812EE63FD](https://user-images.githubusercontent.com/69053781/173176927-b895b06a-5369-44c8-8901-bf6dc4db7846.jpeg)
but not with `visualisi` (for visualisierung)
![43EA2F47-7BC6-4A71-BFC4-1334D7B462F7](https://user-images.githubusercontent.com/69053781/173176944-cc9d50e4-4e83-471e-ab81-e7d9cf2c39e1.jpeg)

**Comment by ice987987** [comment]
Works in v6.0.8. Thank you very much!
