### ISSUE TITLE
I can´t open iobroker via Safari on my iPhone

### ISSUE THREAD

**Issue by villamuc** [ioBroker/ioBroker.admin#1112]
Since i use the new admin v5.1.25 i can´t open iobroker via my safari on my iphone... but why? I get no error message the iobroker symbol only  rotates.
![image](https://user-images.githubusercontent.com/52203707/129616797-7952830d-4713-4516-8fe7-e6774f1d4f49.png)

**Comment by Apollon77** [comment]
Please show  "iobroke cert view" output

There is already an other issue about that ... it seems that safari on ios is very strange on self signed ssl certs!

**Comment by villamuc** [comment]
> Please show "iobroke cert view" output
> 
> There is already an other issue about that ... it seems that safari on ios is very strange on self signed ssl certs!

Where can i find the cert view do you mean:
![image](https://user-images.githubusercontent.com/52203707/129763164-1ac422de-b072-496b-8fd0-72a1f506ab49.png)

**Comment by Apollon77** [comment]
Login via ssh and execute that on your command line

**Comment by villamuc** [comment]
iobroker cert view
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "7e4805a252caec3f7eeed95aba55c8417d8ad7a7"
  },
  "subject": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "smarty",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "fd5f2ff233def6f2375109109347d0e24f585e04"
  },
  "dnsNames": [
    {
      "type": 2,
      "value": "smarty"
    }
  ],
  "keyUsage": {
    "id": "2.5.29.15",
    "critical": true,
    "name": "keyUsage",
    "digitalSignature": true,
    "nonRepudiation": false,
    "keyEncipherment": true,
    "dataEncipherment": true,
    "keyAgreement": true,
    "keyCertSign": true,
    "cRLSign": true,
    "encipherOnly": true,
    "decipherOnly": true
  },
  "extKeyUsage": {
    "id": "2.5.29.37",
    "critical": false,
    "name": "extKeyUsage",
    "serverAuth": true,
    "clientAuth": true
  },
  "validityNotBefore": "2021-02-12T20:14:36.000Z",
  "validityNotAfter": "2022-02-12T20:14:36.000Z"
}
{
  "certificateFilename": null,
  "certificate": "-----BEGIN CERTIFICATE-----\r\nMIIDejCCAmKgAwIBAgIJDr1pcvJrD4DbMA0GCSqGSIb3DQEBCwUAMD4xETAPBgNV\r\nBAMTCGlvYnJva2VyMRYwFAYDVQQKEw1pb0Jyb2tlciBHbWJIMREwDwYDVQQLEwhp\r\nb2Jyb2tlcjAeFw0yMTAyMTIyMDE0MzZaFw0yMjAyMTIyMDE0MzZaMDwxDzANBgNV\r\nBAMTBnNtYXJ0eTEWMBQGA1UEChXXXXXXXXXXXXXXXXXXXXXXXXX\r\n-----END CERTIFICATE-----\r\n",
  "serialNumber": "0ebd697XXXXXXXXdb",
  "signature": "sha256WithRSAEncryption",
  "keyLength": 2048,
  "issuer": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "7e4805a252caec3f7eeed95XXXXXXXX"
  },
  "subject": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "smarty",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "fd5f2ff233def6f2375109109XXXXX"
  },
  "dnsNames": [
    {
      "type": 2,
      "value": "smarty"
    }
  ],
  "keyUsage": {
    "id": "2.5.29.15",
    "critical": true,
    "name": "keyUsage",
    "digitalSignature": true,
    "nonRepudiation": false,
    "keyEncipherment": true,
    "dataEncipherment": true,
    "keyAgreement": true,
    "keyCertSign": true,
    "cRLSign": true,
    "encipherOnly": true,
    "decipherOnly": true
  },
  "extKeyUsage": {
    "id": "2.5.29.37",
    "critical": false,
    "name": "extKeyUsage",
    "serverAuth": true,
    "clientAuth": true
  },
  "validityNotBefore": "2021-02-12T20:14:36.000Z",
  "validityNotAfter": "2022-02-12T20:14:36.000Z"
}

**Comment by Apollon77** [comment]
have you tried to reset the caches? ("Verlauf und Websitedaten löschen")

**Comment by villamuc** [comment]
Yes but it doesnt work i have also tested Safari, opera, chrome and edge on the iphone but everytime the same

Von meinem iPhone gesendet

**Comment by ice987987** [comment]
This should now work with iOS15:

https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/432?_=1632320501207

**Comment by Feuer-sturm** [comment]
@villamuc Is this issue solved with iOS15?

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
