### ISSUE TITLE
Question: How to make meta folders appear in files-tab for non-experts

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#1113]
In files tab only
0_userdata and vis.x
are visible to non expert users.

How can i configure a meta folder (i.e. iqontrol.meta) to appear here? For now it is only visible in expert mode.

Thanks

**Comment by Apollon77** [comment]
Good question @GermanBluefox :-) Is admin limiting "meta.user" folders? I expected that only "meta" folders are not shown in "non-expert mode"

**Comment by Jey-Cee** [comment]
I am looking also for a soulution on this topic.

**Comment by Jey-Cee** [comment]
I have changed the filter, so all instance folder for adapters will be shown. 
This seems to be a good way to allow users show & upload files from adapters and do not need the file upload inside the adapter configuration. 

If this will be accepted i'll make a PR.

![image](https://user-images.githubusercontent.com/16007760/129964990-c793db4c-3ec1-401f-8f15-990a7a4b42cc.png)

**Comment by sbormann** [comment]
For iQontrol the iqontrol.meta should be accessible. I would prefer to have an option for that. Maybe native.filtabNonexpert? Analog to common.expert (which i think only affects objects-browser).
![image](https://user-images.githubusercontent.com/49171332/129986660-dcb5a6af-17a9-4c91-8605-78b97f066963.png)

**Comment by Apollon77** [comment]
Why not display all "meta.user"?? This should ist be for "non expert mode". expert kdoe then shows all "meta"

**Comment by GermanBluefox** [comment]
Behavior was changed in Admin6. Please retest

**Comment by sbormann** [comment]
Now i can see the folder, but upload is still noch allowed to non-expert users

**Comment by GermanBluefox** [comment]
PLease retry with Admin 6.0.4

**Comment by Feuer-sturm** [comment]
@sbormann Can you please check with current admin version?

**Comment by sbormann** [comment]
Works perfectly. Many thanks.
