### ISSUE TITLE
Encrypt / Decrypt using old encryption method in admin and can't read new aes

### ISSUE THREAD

**Issue by dbweb-ch** [ioBroker/ioBroker.admin#1116]
**Describe the bug**  
As discussed on discord: admin uses only the old encryption method to encrypt a value. js-controller does not have any issue with this as it understands the old encryption, but when you update a value with tools.encrypt, the admin isn't able to display it anymore as it can't decrypt the new AES-value.
seen in https://github.com/dbweb-ch/ioBroker.tesla-motors version 5.1.5

**To Reproduce**  
write a value in admin and set it as "encryptedNative". Admin will store it in the old format (value starts with "F\u0012A\u001e....").
Update the value in main.js using:
```
Adapter.getForeignObjectAsync
obj.native.value = tools.encrypt(secret, value)
Adapter.setForeignObjectAsync
```

this will store the value with the new encryption, starting with "$/aes-192".
Then try to read the value in admin
```
function load(settings, onChange){
    console.log(settings['value']); // Outputs binary / utf8 nonsense
}
```
**Expected behavior**  
admin should use new encryption in both ways.

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.15
 - Node version: 14.16.1
 - Operating system: ubuntu

**Additional context**  
check my code.
For main.js:
https://github.com/dbweb-ch/ioBroker.tesla-motors/blob/f15a091f929f6b87bef57e5eae025f03443b1426/main.js#L559
for index_m.html:
https://github.com/dbweb-ch/ioBroker.tesla-motors/blob/f15a091f929f6b87bef57e5eae025f03443b1426/admin/index_m.html#L72

**Comment by dbweb-ch** [comment]
seems that have been mentioned in https://github.com/ioBroker/ioBroker.admin/issues/598 but did not get into it.

**Comment by GermanBluefox** [comment]
Browser supports only aes-256-cbc. JS-Controller must be changed
