### ISSUE TITLE
Enhance new standard graphs-view for object values with enabled history

### ISSUE THREAD

**Issue by Pedder007** [ioBroker/ioBroker.admin#1118]
I very much like the new possibility to show graphs of the object values, captured by history:
![image](https://user-images.githubusercontent.com/44653371/129971864-0bed5ba7-f0bc-4a28-b7d4-d501f865191d.png)

I knew such valuable functionality already from my former Pimatic setup.

To increase the usability, I would like to suggest two things:
1. do not fill the graphs, only show simple lines (as prerequisite for 2.)
2. add the possibility to show more than one graph in a diagramm, to put values in context with others
The functionality extremly helps when evaluating depending functionalities, where maybe a value is set by reaching dedicated states of multiple other values (e. g. shutter sun-steering)

Thanks a lot in advance!

**Comment by Apollon77** [comment]
The admin display is limited to the one state slected.

Just use adapters like echarts (or the "Older flot") to create your own and custom charts

**Comment by Pedder007** [comment]
@Apollon77 thanks for your feedback and what a pity, that only one state can be selected.
But I will follow your hint regarding echarts, maybe the usage is more comfortable for some quick checks than the materialdesign charts I'm currently using.
