### ISSUE TITLE
14instrument.ts:129 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.     at Oi (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5514841)     at jl (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5526653)     at t.unstable_runWithPriority (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5553242)     at Wa (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5469628)     at Vl (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5524611)     at ml (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5520697)     at http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5469851     at t.unstable_runWithPriority (http://192.168.1.32:8081/static/js/5.42ef9396.chunk.js:2:5553242)     at

### ISSUE THREAD

**Issue by Elektrofix1** [ioBroker/ioBroker.admin#1123]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
Hallo @Elektrofix1, bitte deinen Fehler in das Beschreibungsfeld setzen und einen kurzen Titel wählen. Bitte ergänze auch Deine Admin Version und welche Aktionen man durchführen muss, um den Fehler zu sehen.
