### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DonLuigi1992** [ioBroker/ioBroker.admin#1124]
**Describe the bug**  
Error in GUI

**To Reproduce**  
1. Open JavaSkript Adapter
2. Click on "settings"
3. Click on "Standart ACL"

**Expected behavior**  
Open the tap "Standard ACL"

**Screenshots & Logfiles**  
TypeError: this.props.data.common.defaultNewAcl is undefined
    value http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    value http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    i http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    value http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    Wo http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Io http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ui http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Cl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    _l http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    El http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    ml http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ua http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    hl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    enqueueSetState http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    setState http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    onHashChanged http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    r http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    _wrapEventTarget http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    I http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    value http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    fi http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    jl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Vl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    ml http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ua http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    zl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    rs http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    render http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    e http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    1426 http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    u http://192.168.178.51:8081/#tab-javascript/system:1
    r http://192.168.178.51:8081/#tab-javascript/system:1
    t http://192.168.178.51:8081/#tab-javascript/system:1
    <anonymous> http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
5.42ef9396.chunk.js:2:6132559
    I http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    ii http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    payload http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    uc http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Io http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ui http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Cl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    _l http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    El http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    ml http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ua http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    hl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    enqueueSetState http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    setState http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    onHashChanged http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    r http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    (Async: EventListener.handleEvent)
    _wrapEventTarget http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    I http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    value http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    fi http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    jl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Vl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    ml http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    Ua http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    zl http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    rs http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    render http://192.168.178.51:8081/static/js/5.42ef9396.chunk.js:2
    e http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    1426 http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
    u http://192.168.178.51:8081/#tab-javascript/system:1
    r http://192.168.178.51:8081/#tab-javascript/system:1
    t http://192.168.178.51:8081/#tab-javascript/system:1
    <anonym> http://192.168.178.51:8081/static/js/main.692229dc.chunk.js:2
or

TypeError: this.props.data.common.defaultNewAcl is undefined
    value ACLDialog.js:67
    value ACLDialog.js:72
    i ACLDialog.js:168
    value ACLDialog.js:163
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    onHashChanged App.js:938
    r helpers.ts:87
    _wrapEventTarget trycatch.ts:185
    I instrument.ts:559
    value App.js:450
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    e index.js:22
    1426 index.js:72
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.692229dc.chunk.js:2
instrument.ts:129:35
    I instrument.ts:129
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    onHashChanged App.js:938
    r helpers.ts:87
    (Async: EventListener.handleEvent)
    _wrapEventTarget trycatch.ts:185
    I instrument.ts:559
    value App.js:450
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    e index.js:22
    1426 index.js:72
    u (index):1
    r (index):1
    t (index):1
    <anonym> main.692229dc.chunk.js:2

It switched by itself...

**Versions:**  
 - Adapter version: <5.2.8>
 - JS-Controller version: <3.3.15> 
 - Node version: <12.20.0> 
 - Operating system: <raspberrypi OS>

**Comment by fetzz-de** [comment]
**Describe the bug**
Error in GUI

**To Reproduce**
Steps to reproduce the behavior:
-     Click on "Systemeinstellungen"
-     Click on "Standart ACL"
-     See error

**Expected behavior**
Open the tap "Standard ACL"

**Screenshots & Logfiles**
Browser Firefox v.92.0b6
![grafik](https://user-images.githubusercontent.com/89337326/130349481-374f33ad-117f-4f4e-b615-4b0cc180ec7b.png)

Brwoser Chrome v.92.0.4515.159
![grafik](https://user-images.githubusercontent.com/89337326/130349468-7c304f19-b5b1-4d96-8589-3c71a277526c.png)

**Versions:**
    Adapter version: <5.2.8>
    Node version: <12.20.0>
    Operating system: linux arm debian 10.6
