### ISSUE TITLE
Feature request: mark new node.js version

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1125]
**Is your feature request related to a problem? Please describe.**
Since Info-Adapter is no longer installed while the Admin-Installation, there is no check if new node.js version available:
![](https://forum.iobroker.net/assets/uploads/files/1628764964360-fa031f5c-9299-446a-9b08-3766517949a9.jpeg)
or
![F4D3A145-C80E-43B7-963B-FC9EAD7BFD91](https://user-images.githubusercontent.com/69053781/130504640-78c1387c-6c97-467b-8be5-6ce9b876820f.jpeg)

**Describe the solution you'd like**
mark new node.js version if new version available like info-adapter:
![](https://forum.iobroker.net/assets/uploads/files/1628765003086-db163171-9cdb-4b49-8d7f-745a87bc9204.jpeg)

**Additional context**
https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/236?_=1629550676318

**Comment by GermanBluefox** [comment]
It was implemented like this:
![image](https://user-images.githubusercontent.com/4582016/173087759-8697d2d6-7b1c-4647-a79b-dd51c36e98c1.png)

**Comment by ice987987** [comment]
Works in v6.0.3. Thank you very much!
