### ISSUE TITLE
Font/icon size

### ISSUE THREAD

**Issue by algar42** [ioBroker/ioBroker.admin#1128]
Any chance to reduce fonts and icons size in React interface, especially in Objects tree view? Really, guys, it looks like it is created for people with disabilities. It is really difficult to use new UI in small screens and even on a big screen the most often thing you do in new UI is scroll-scroll-scroll back and forth. 
Pleeeeas create a theme with reduced elements size.

**Comment by Apollon77** [comment]
No, it is created for a compromise between PC and Tablet users

**Comment by algar42** [comment]
Compromise for Tablets? You are kidding :) 
Before I was able to use old UI on mobile phone. Yes, font was very small but usable. Did you ever try to open new UI on mobile phone? 
Please, take a look:
![image](https://user-images.githubusercontent.com/40002726/130359606-e221d8da-dad6-481d-8f4b-75540ec14329.png)
![image](https://user-images.githubusercontent.com/40002726/130359623-70e45067-53fc-495a-9de2-336cb571b376.png)

And compare with Old UI on the same mobile screen:
![image](https://user-images.githubusercontent.com/40002726/130359862-4fd8b759-2480-4c66-b536-ba2b376a8ef2.png)
Wow I can see all the columns, and still able to use interface.

Yes, new UI font size allows me to tap on correct row, but nothing else.. It is almost impossible to use this interface on mobile, and it is inconvenient on PC. TBH, it is not only my opinion. Everyone I personally know do not want to use React UI because its nightmare design.    
This compromise lead to only one thing - it looks ugly on both PC and Tablets. Sorry.. 

And, since we started this discussion, please check how the interface behave when you resize the browser window, e.g. in Objects Tab:
![image](https://user-images.githubusercontent.com/40002726/130360115-ca01b7c7-8b10-4b88-81e6-e20eb53fec75.png)
ID column has fixed length and it is very long. All other columns are being shifted in relation to header, and the narrower the window, the bigger the shift

**Comment by SliX185** [comment]
@Apollon77 
Maybe there could be an option for switching between mobile and desktop view? (media queries?!)
A smaller fontsize for desktop users would improve or bring back a lot of usabiltiy.

**Comment by Apollon77** [comment]
This is a topic for @GermanBluefox to answer :-)

> (Edit: I also would love, to have an option for "lines between columns")

This is implemented in the latest version of admin in latest and configurable

**Comment by SliX185** [comment]
> This is implemented in the latest version of admin in latest and configurable

5.1.25
Just have an option for lines in ROWS, wich is great, but not for CLOUMNS. Both as option would be great.

**Comment by GermanBluefox** [comment]
> Any chance to reduce fonts and icons size in React interface, especially in Objects tree view? Really, guys, it looks like it is created for people with disabilities. It is really difficult to use new UI in small screens and even on a big screen the most often thing you do in new UI is scroll-scroll-scroll back and forth. Pleeeeas create a theme with reduced elements size.

It is designed by professionals "material UI". I don't think that I can do it better.
