### ISSUE TITLE
Header on object tab with Chromium and Safari on MacOS

### ISSUE THREAD

**Issue by SabineTobi** [ioBroker/ioBroker.admin#1129]
**Describe the bug**  
Under MacOS the header line is not readable when using Chromium or Safari as Browser. With Firefox it is ok.

**Screenshots & Logfiles**  
Screenshots are here: https://forum.iobroker.net/post/667899

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.15
 - Node version: v12.22.2
 - Operating system: Server: Ubuntu 20.04
 - Desktop: MacOS BigSur 11.5.2

**Comment by Feuer-sturm** [comment]
@SabineTobi Is this issue still active?

**Comment by SabineTobi** [comment]
@Feuer-sturm it is ok now!
