### ISSUE TITLE
Change column width with mouse

### ISSUE THREAD

**Issue by SabineTobi** [ioBroker/ioBroker.admin#1130]
It would be useful if you could change the column width e.g. in the object tab with the mouse and not laboriously with the extra settings. With these settings it is also not clear which unit the values should have.

Es wäre praktisch, wenn man die Spaltenbreite z.B. im Objekt-Tab mit der Maus ändern könnte und nicht mühsam über die extra Einstellungen. Bei diesen Einstellungen ist auch nicht klar, welche Einheit die Werte haben sollten.

**Comment by GermanBluefox** [comment]
You can now change (not all) widths of columns
