### ISSUE TITLE
JSON Config Password input error

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.admin#1131]
Describe the bug
Input field for password disappears and it is not possible to enter a password. With copy paste of the password I get in the log of Synology that the user fails to login.
Thus, the password is also not stored correctly.

To Reproduce

Go to 'Adapter instance settings'
Click on 'Password input field'
Expected behavior
Entering a password

Versions:

Adapter version: v1.1.2
JS-Controller version: 3.3.15
Node version: v12.22.4
Operating system: Linux -> RP4

see here : https://github.com/iobroker-community-adapters/ioBroker.synology/issues/11

**Comment by MeisterTR** [comment]
something new?

**Comment by bropat** [comment]
I am also interested in the issue being solved.

**Comment by bropat** [comment]
@GermanBluefox 

Is there any news on this?

Here you can see the error:
![issue](https://user-images.githubusercontent.com/2305255/140605139-a7843035-2b09-4985-9852-24a362a9b052.gif)

**Comment by bropat** [comment]
Anybody there?

I think this is a very annoying bug...

**Comment by Apollon77** [comment]
Issue found!

In jsonconfig you NEED TO provide the property "repeat", ebven with a false value. If it is missing then this happens ... But so the workaround is known!

@GermanBluefox

**Comment by Apollon77** [comment]
@GermanBluefox a notset "repeat" shopuld be considered false
