### ISSUE TITLE
State Farbe unter Instanzen ist falsch

### ISSUE THREAD

**Issue by lindi200000** [ioBroker/ioBroker.admin#1133]
Hallo, 
im Admin 5.1.23 werden die farben von Instanzen falsch angezeigt, die ein schedule drin haben.
Aktuelle Farbe ist grau, was in meinen Augen  bedeutet, das dieser nicht funktionier.
![image](https://user-images.githubusercontent.com/16406425/130660898-6dd4a3c4-3022-4b95-9a1b-2099905c525c.png)
z.B. sollte der Corona Adapter grün sein, da er funktioniert, hier sieht es aber so aus, als währe er aus.

VG

**Comment by Apollon77** [comment]
Grau heisst in dem Fall "läuft nicht JETZT" und das ist korrekt weil er läuft ja nur zu den scheduled zeitpunkten. Er müsste gün vom Hintergrund her werden wenn er wirklich ausgeführt wird.

In dem Fall hast Du eine Fehlannahme was die Farbe angeht. "geht nicht" ist die Farbe vorn  grün/gelb/rot

**Comment by DutchmanNL** [comment]
> In dem Fall hast Du eine Fehlannahme was die Farbe angeht. "geht nicht" ist die Farbe vorn grün/gelb/rot

Ich stimme aber zu das es undeutlich ist für sheduled Adapter das es auszubalancierendem wäre die Instanz aus

**Comment by lindi200000** [comment]
> Grau heisst in dem Fall "läuft nicht JETZT" und das ist korrekt weil er läuft ja nur zu den scheduled zeitpunkten. Er müsste gün vom Hintergrund her werden wenn er wirklich ausgeführt wird.
> 
> In dem Fall hast Du eine Fehlannahme was die Farbe angeht. "geht nicht" ist die Farbe vorn grün/gelb/rot

Ok, das klingt einleuchtend, jedoch sieht es aktuell so aus, als würde der Adapter gar nicht gehen, das Grau verwirrt da einfach nur. Eine extra farbliche Kennzeichnung währe da nicht verkehrt.

**Comment by Feuer-sturm** [comment]
Aktuelles Verhalten mit Admin 5.3.1
Gelbe Uhr, und gauer Hintergrund wenn Instanz aktiv ist aber gerade nicht läuft. Wenn Instanz aktiv läuft, dann wird der Hintergrund Grün.

![Animation20](https://user-images.githubusercontent.com/25422320/155860103-dbb6ed3b-37b9-425c-ad6b-4a6609166acf.gif)

Die Orangene Uhr ist dann ja der Hinweis, dass die Instanz aktiv ist und gerade im Idle ist.
Wenn die Instanz ausgeschaltet ist, wird die Uhr grau.

![grafik](https://user-images.githubusercontent.com/25422320/155860311-a7787ab9-72bd-4f46-912a-93c45854f8c9.png)

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
