### ISSUE TITLE
Instance configuration - what should be there or not

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#1135]
While discussing which elements are needed for the new jsonConfig style, we should also make clear what is instance configuration and what not.
In general we can say they are only for instance purpose, not for devices if the instance handles more than one device.  
Here we can collect these things. 

- IP
- Port
- Serialport selection
- Username
- Password
- API Key
- Selection for other adapter instances to use with 
- Settings like "Use SSL certificate"

**Comment by Feuer-sturm** [comment]
@Jey-Cee @Apollon77 Is this topic still relevant?
