### ISSUE TITLE
Problem bei Namensänderungen mit Leerzeichen

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1139]
Wenn ich einen Objektnamen ändern möchte dann sind Leerzeichen unzulässig. Ich muss abschließen und editieren .. dann erst kann ich Leerzeichen zwischenfügen.

**Comment by FredF63** [comment]
Leerzeichen werden am Namensende nicht akzeptiert. Zwischendrin schon

**Comment by daniel-lo** [comment]
Mir ist es aufgefallen als ich den ganzen Text markiert hatte und komplett überschreiben wollte.
