### ISSUE TITLE
enum favorites können nicht gelöscht und umbenannt werden mit Admin 5.1.25

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#1141]
Ich habe in Admin 5.1.25 versucht enum favorites zu löschen oder umzubennen, beides funktioniert leider nicht,

![image](https://user-images.githubusercontent.com/33424168/131170916-219c77c1-7c8c-4bc8-8cc3-29adb87a92cb.png)

![image](https://user-images.githubusercontent.com/33424168/131170927-65bf961a-6c3c-4849-b75e-cd026134c1d2.png)

Falls weitere logs benötig werden oder ich etwas testen soll bitte melden.

**Comment by wendy2702** [comment]
Hi,

Maus welchem Grund auch immer stehen Sonderzeichen und Punkte im Namen der Favoriten welche jetzt wohl geprüft werden und das löschen/editieren verhindern.

Bitte eine Möglichkeit schaffen diese trotzdem löschen/editieren zu können.

**Comment by GermanBluefox** [comment]
You can use ObjectBrowser to delete enums:
![image](https://user-images.githubusercontent.com/4582016/172920090-2b7f2ce5-3c21-433a-82b4-3237649de3cd.png)
