### ISSUE TITLE
Feature request: enlarging the input field for json under "objekte"

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1142]
**Is your feature request related to a problem? Please describe.**
if a json as "objekt" is created, the input field is very small:

![image](https://user-images.githubusercontent.com/69053781/131223718-b1e04ab4-a886-4944-a89b-a4faf921eb36.png)

**Describe the solution you'd like**
please maximize the size of the input filed as big as possible

**Describe alternatives you've considered**
no alternatives, because it is not possible to change the size of this field.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172900369-7dc33adf-268c-412a-8fe0-e5f4987e8221.png)

**Comment by ice987987** [comment]
Works in v6.0.3. Thank you very much!
