### ISSUE TITLE
Missing "Different IDs for read and write" in translation.json

### ISSUE THREAD

**Issue by FredF63** [ioBroker/ioBroker.admin#1143]
![grafik](https://user-images.githubusercontent.com/43332106/131227414-9b45e97c-d31e-4bf0-af8b-2751e67ec92e.png)

**Comment by Feuer-sturm** [comment]
with admin 6.0.3 ok
![grafik](https://user-images.githubusercontent.com/25422320/173183324-58ce178d-ef56-4168-86c3-6fc2e36bc20e.png)
