### ISSUE TITLE
Admin lädt nicht (Ladeanimation)

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1144]
Der Admin präsentiert mir ganz häufig nur die Ladeanimation und erzählt was zu langsamer Verbindung:

Loading chunk 13 failed. (error: http://192.168.178.115:8081/static/js/13.7d21ae26.chunk.js)

u.e@http://192.168.178.115:8081/:1:2158function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}1426/zi<@http://192.168.178.115:8081/static/js/main.1892293b.chunk.js:2:1094433function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}V@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5551848function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Ui@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5542033function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Cl@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5528629function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}_l@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5528557function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}El@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5528418function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}ml@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5525384function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Ga/<@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5474763function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}t.unstable_runWithPriority@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5558154function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Wa@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5474540function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Ga@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5474710function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}Ua@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5474643function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}hl@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5522753function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}enqueueSetState@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5478661function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}m.prototype.setState@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5549665function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}t/<@http://192.168.178.115:8081/static/js/main.1892293b.chunk.js:2:1107018function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}u@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5562835function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}s/c._invoke</<@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5562624function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}w/</<@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:5563264function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}r@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:91852function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}i@http://192.168.178.115:8081/static/js/5.bde6ca2f.chunk.js:2:92056function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}

![admin ladefehler](https://user-images.githubusercontent.com/4311558/131240709-86372bdc-a726-4631-a3e2-e7bae09a5ddc.png)

**Comment by Apollon77** [comment]
Hm... and the iobroekr system itself is running?

Cannnot file bview "system" is normally a bigger issue withthe obejcts database.

So please stop iobroker, try to start again. if it does not with with this error you need to restore the objects db ... then you will find support in the forum (search for that error)

**Comment by daniel-lo** [comment]
Well this happens but somehow I always manage to get it up and runnint well again. For example now everything is fast and stable .. no errors no problems. I would expect big issues to be persistent and not intermittent.

**Comment by Apollon77** [comment]
@daniel-lo See my comments in the shelly tivcket ... your system is "Out fo control". Each error you report atm is subject to "imvalid because of that" ... sorry

**Comment by daniel-lo** [comment]
As mentioned in the other ticket .. I expected my logfile to be messy. Shutting down Proxmox without shutting down ioBroker first .. was the reason for your findings. Nothing surprising to me.

This report here is actually valid .. happens to be regularly.

**Comment by Apollon77** [comment]
Then I would like to see that while the system is running clean because as said "cannot find view" is a very hard error in the basic data structure and if this happens there is something more basic broken then admin!

**Comment by daniel-lo** [comment]
I will set my Admin to debug and will try to catch something the next days.

**Comment by daniel-lo** [comment]
wieder getötet:

[iobroker.2021-08-30.zip](https://github.com/ioBroker/ioBroker.admin/files/7075714/iobroker.2021-08-30.zip)

**Comment by Apollon77** [comment]
Also die "Job for iobroker.service cancelled" ist irgendwas von systemd ... hier ggf /var/log/syslog schauen

Ansosten: Was heisst "wieder getötet"? 

Ich sehe im Log um 11:19 einen Admin restart ... das warst du manuell und ist ok?

Ohne kontext und Zetangaben ist das mit dem Log a bissl schwierig zu erraten

Aber ja 11:37 sieht es so aus als ob das system wieder prozesse gekillt hätte. Was sagt /var/log/syslog zu demZeitpunkt? Bis 11:40:15 fährt alles runter und controller startet 11:40:19 neu. Ab 11:46 fängt es wieder an komisch zu werden und alles fleigt wieder auf die nase

**Comment by daniel-lo** [comment]
Das System ist mit dem neuen Admin sehr sensibel .. urplötzlich nur noch Ladeanimation. Manchmal bei Updates oder irgendwelchen trivialen Aktionen .. manchmal einfach so.

Syslog von gestern:

[syslog.2.gz](https://github.com/ioBroker/ioBroker.admin/files/7082234/syslog.2.gz)

**Comment by Apollon77** [comment]
Hat mit dem Admin nichts zu tun. Wäre mir neu und wärst der einzige.

Also das log ....

7:43:10 scheinbar spontaner reboot ... mitten im Startvorgang ... also ein Shutdown war vorher nicht im Log
selbes 8:01:09 und 8:21:36

Das erklärt einiges ... Ich sage du hast ein Hardware issue  oder Power issue

**Comment by daniel-lo** [comment]
Sowas wie spontaner reboot kann dadurch zustande kommen, dass ich reboot eingegeben habe als es einen Hänger gab.

**Comment by Apollon77** [comment]
wenn Du Reboot eingibst sollte an sich was im Log stehen das er das system sauber runterfährt. Das sieht eher nach "strom weg" reboot oder kernel panic ohne log aus

**Comment by daniel-lo** [comment]
neee .. nicht wirklich .. ich bin ja auch nicht der einzige mit Hängern .. diesen F12 Bildschirm hatten schon einige reported.
System mit altem Admin noch immer stabil.

**Comment by Apollon77** [comment]
@daniel-lo das ist ja alles ok, aber wenn bei Dir noch einige andere Fehler dabei sind die ihr Ursachen definitiv "woanders" haben ist das so eine sache ob nicht diese anderen Probleme Ursächlich sind.

Ein "Hängendes system" was nicht mehr reagiert und dann hart rebootet werden muss und das auch zu sehen in allen möglichen Logs das hat andere probleme als den Admin :-) Und die sollten zuerst weg sein. Da ist aber das GitHub issue hier das falsche weil ich kann dir nicht helfen - da wäre ein Forum Thread besser

**Comment by daniel-lo** [comment]
Sorry .. Missverständnis .. SSH geht immer .. ich spreche nur von hängendem ioBroker .. nichts anderem.

**Comment by Apollon77** [comment]
Wenn aber ein Rebotot nicht im syslog sichtbar ist dann ist da was im argen. Auch "ein hängender ioBroker" ist hier nicht zu sehen. ICh sage ja man muss genau schauen was bei deinem system passiert gerade.

**Comment by daniel-lo** [comment]
Puh .. ich wenn ich was finde was ich als Event mit einem Hänger verbinden kann .. poste ich es sofort. Werde demnächst mal wieder den neuen Admin einstellen .. mein Gefühlt sagt mir .. es hängt damit zusammen .. aber was sagen schon Gefühle ;-)

**Comment by Apollon77** [comment]
AM besten mach doch echt mal ein Forum Thread ... der Community Brain ist größer als meiner :-)

**Comment by daniel-lo** [comment]
Sag mal .. schaut das ok aus?
![grafik](https://user-images.githubusercontent.com/4311558/131891509-80616f1b-af6c-4e61-9412-cba863585333.png)

**Comment by Apollon77** [comment]
Also zwei Prozesse haben mega viel CPU ... frage ist welche das sind. Müsstest Du ggf in den system.adapter.X. states auch finden bzw system.host.X

**Comment by daniel-lo** [comment]
Leider kann ich genau dann nicht schauen, wenn das System hängt ... aktuell wieder runter auf unter max. 10% und läuft flüssig.

**Comment by daniel-lo** [comment]
Hab was gefunden:

ps -eo pcpu,pid,user,args | sort -k1 -r -n | head -10
,, show the top 10 cpu using threads, sorted numerically

Jetzt muss es nur wieder hängen .. mal schauen.

**Comment by daniel-lo** [comment]
Mir scheint es ist der Zigbee Adatper, der mein System manchmal zu stark belastet. Grad hab ich wieder die Situation, dass er zwischen 40 und 100% pendelt. Das ist mehr als der JS Adapter .. und mein System hängt.

Wollte testhalber den Adapter abschießen und schauen ob das System dann wieder gängig wird .. klappt aber nicht:

daniel@iobroker:/opt/iobroker$ iobroker stop zigbee.0
No connection to databases possible ...

**Comment by daniel-lo** [comment]
So schaut's übrigens aus .. wenn das System nicht beeinträchtigt ist:

![grafik](https://user-images.githubusercontent.com/4311558/132116676-0571c88a-c864-4f36-b636-d69429773169.png)

**Comment by Apollon77** [comment]
kannst ja mal versuchen wenn zigbee "viel zu tun hat" im Admin den loglevel auf debug zu setzen (ohne neustart!) ...dann log schauen

**Comment by daniel-lo** [comment]
kann ich gern machen .. aber meist geht dann nicht so viel

**Comment by Apollon77** [comment]
so oder so ... Forum ist besser für sowas als GitHub!

**Comment by daniel-lo** [comment]
Konnte mich mit dem neuen Forum nie anfreunden .. frage für gewöhnlich eher noch bei Facebook.
Hab aktuell auch noch wenig zu bieten.

**Comment by Apollon77** [comment]
Facebook ... hm ... naja nicht meins vor allem nicht für SUpport Themen.

Und FOrum hat nichts mit "Bieten" zu tun. Es ist aber ein gutes Medium wenn man Hilfe braucht von erfahrenen Usern der COmmunity
