### ISSUE TITLE
Status (!=) Zustand

### ISSUE THREAD

**Issue by softice24** [ioBroker/ioBroker.admin#1145]
Die Unterscheidung von "Status" und "Zustand" im Tooltip ist verwirrend. Die markierten Zeilen können entfernt werden.
Siehe: https://forum.iobroker.net/topic/46814/admin5-ich-kann-keine-objekte-mehr-manuell-anlegen/350?_=1630338561380
![grafik](https://user-images.githubusercontent.com/49113812/131368293-cd03b5e0-5ea4-4080-a023-37646a9f6c03.png)

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 6.0.4
