### ISSUE TITLE
Error in GUI!  Standart ACL

### ISSUE THREAD

**Issue by 69Teufel69** [ioBroker/ioBroker.admin#1147]
Gehe zu Systemeinstellungen 
Klicke auf Standart ACL

Siehe Fehler
Error in GUI!

instrument.ts:129 TypeError: Cannot read property 'object' of undefined
    at a.value (ACLDialog.js:67)
    at a.value (ACLDialog.js:72)
    at ACLDialog.js:168
    at Array.map (<anonymous>)
    at a.value (ACLDialog.js:163)
    at Wo (react-dom.production.min.js:187)
    at Io (react-dom.production.min.js:186)
    at Ui (react-dom.production.min.js:269)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at o.m.setState (react.production.min.js:12)
    at i.onHashChanged (App.js:938)
    at r (helpers.ts:87)

iobroker
Betriebssystem linux
Node.js v12.22.5
NPM 6.14.14
Installiert: 3.3.15
admin v5.1.23

das stand noch unter dem Fehler Bild

Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefinedfunction(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.value (http://192.xxx.xxx.xxx:8081/static/js/main.692229dc.chunk.js:2:1008221)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.value (http://192.168.xxx.xxx:8081/static/js/main.692229dc.chunk.js:2:1008360)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://192.xxx.xxx.xxx:8081/static/js/main.692229dc.chunk.js:2:1010416function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Array.map (<anonymous>)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at a.value (http://192.xxx.xxx.xxx:8081/static/js/main.692229dc.chunk.js:2:1010254)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Wo (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5496714)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Io (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5496511)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ui (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5537614)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Cl (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5523715)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at _l (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5523643)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at El (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5523506)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at ml (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5520472)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5469851function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5553242)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Wa (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5469628)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ga (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5469796)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ua (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5469731)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at hl (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5517841)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Object.enqueueSetState (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5473749)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at o.m.setState (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:5544753)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at i.onHashChanged (http://192.xxx.xxx.xxx:8081/static/js/main.692229dc.chunk.js:2:1098455)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at r (http://192.xxx.xxx.xxx:8081/static/js/5.42ef9396.chunk.js:2:6163749)

gruß oliver
ps ich bin geübter Anfänger :)

**Comment by Feuer-sturm** [comment]
@69Teufel69 Existiert das Problem bei dir noch mit Admin 5.3.1? Wenn nein, bitte das issue schließen.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
