### ISSUE TITLE
missing native part in object

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.admin#1148]
werden neue dp angelegt, wird im admin5 kein native{} teil im object angelegt - um z.b in iot ein smartdevice anzulegen, wird der aber benötigt - zumindest sagt das die fehlermeldung

im forum: https://forum.iobroker.net/post/672111

![Image 3](https://user-images.githubusercontent.com/18462890/131465624-8aaebb05-818f-4ed3-8339-7a7f43827b53.png)

**Comment by Apollon77** [comment]
@liv-in-sky Please also post the other screenshot with object because natve was there ... then it is more an iot issue?!

**Comment by liv-in-sky** [comment]
neuer dp zum test  - angelegt und auf switch geändert

`{
  "common": {
    "name": "dp-test-iot",
    "desc": "Manuell erzeugt",
    "role": "switch",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false
  },
  "type": "state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1630415857636,
  "_id": "0_userdata.0.CONTROL-OWN.AAATEST.dp-test-iot",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

dann im iot:

ganz schnell hintereinander diese fehlermeldungen


![Image 10](https://user-images.githubusercontent.com/18462890/131510473-119d9612-4c3a-4ab8-8268-a4f823edf995.png)


![Image 11](https://user-images.githubusercontent.com/18462890/131510487-3841020f-df3b-42fb-8e68-f6decc4776cb.png)

**Comment by Apollon77** [comment]
Geht es denn wenn du auf gleiche ebene wie common noch ein native:{} einfügst

**Comment by liv-in-sky** [comment]
wenn ich das native einfüge, geht es:
![Image 13](https://user-images.githubusercontent.com/18462890/131529079-ad39a74a-613c-431b-bfb3-f5381184b772.png)


aber noch eines: der dp sieht so aus nach dem gescheiterten versuch, und wird nicht in iot angezeigt - also der admin hat etwas daran geändert
![Image 12](https://user-images.githubusercontent.com/18462890/131529126-7bdc18b2-9b17-4034-911c-81a1d9329170.png)

**Comment by tehmilcho** [comment]
Hey ich hab das gleiche Problem gehabt und bin selbst dann auf diesen "Workaround" gekommen, ich find das echt unschön hoffe das man das mal fixen kann. 

Ich nutze sehr viele Userdata-Sachen damit meine "Regeln" funktionieren z.b. habe ich für jeden Raum ein Switch "Alexa Force RAUMNAME". Den packe ich dann mit in die Alexa-Gruppe von dem Raum als "Lampe" somit die dann mit geschaltet bei "Alexa Licht an" und meine Regeln die alle auf Bewegungsmelder und Anwesenheiten von Geräten basieren lassen dann das Licht an weil "Alexa Force" eingeschaltet ist.

**Comment by Schmakus** [comment]
Diese Frage kommt auch sehr oft in der Facebook-Gruppe. Bei einem eigenen Datenpunkt fehlt der "native:{}" Eintrag, welche vom IOT-Adapter vorausgesetzt wird. Entweder liegt das Problem am IOT oder am Admin?! Ein Hinzufügen des "native:{}" Eintrags schafft Abhilfe.

**Comment by GermanBluefox** [comment]
Fixed in 6.0.3

**Comment by tehmilcho** [comment]
Hello, 

sorry the delay ... 

Admin - 6.1.11 (1~)

Test Datapoint under Userdata:
```
{
  "common": {
    "name": "NativeJsonTest",
    "desc": "Manually created",
    "role": "state",
    "type": "boolean",
    "read": true,
    "write": true,
    "def": false,
    "custom": {
      "iot.0": {
        "smartName": {
          "en": "NativeJsonTest"
        }
      }
    }
  },
  "type": "state",
  "native": {},
  "_id": "0_userdata.0.Tests.NativeJsonTest",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1657269962042
}
```

Test Add to IOT Adapter:
![image](https://user-images.githubusercontent.com/22918349/177955107-42c9b702-092a-4b94-8d7e-e9117778c064.png)

So its all fine now :)
