### ISSUE TITLE
Selektion von Objekteigenschaften

### ISSUE THREAD

**Issue by softice24** [ioBroker/ioBroker.admin#1149]
Wenn unter Objekte eine Eigenschaft (z.B. Typ, Rolle, Zimmer, Funktion) selektiert wird, wird lediglich die unterste Ebene ausgeblendet. Erwarten würde man, dass nur Objekte mit der jeweiligen Eigenschaft angezeigt werden (wie auch unter der alten Benutzeroberfläche, oder wenn eine Eigenschaft geändert wird).
![grafik](https://user-images.githubusercontent.com/49113812/131476768-860de4c5-37b5-489e-abbf-a9c615a062e1.png)

**Comment by softice24** [comment]
Unfortuately not. With Admin 5.3.1 it even looks worse. Now i have more shapes of grey without anything being filtered.

**Comment by Feuer-sturm** [comment]
@softice24 Is it the same like this that it take a very long time from greyed out to filtered objects?

![Animation100](https://user-images.githubusercontent.com/25422320/156649360-33470a8c-048c-4f72-9837-4daf84f87489.gif)

**Comment by softice24** [comment]
Wouldnt be a problem if only performance was the issue. It just stays greyed out, no matter how long im waiting. Tested with Chrom, Firefox, Edge on Admin 5.3.1, js-controler 4.0.15, Node.js 16.14.0, Objects json, States redis. Please let me know if u need to know anything else. I wonder if I'm the only one with this problem.

**Comment by softice24** [comment]
Filtering works, performance is good, it should be possible to hide folders when filtering!

**Comment by Feuer-sturm** [comment]
@softice24  please open a new issue for your topic "hide folders when filtering!". This issue is fixed and can be closed.
