### ISSUE TITLE
No access with mobile Chrome and opera 

### ISSUE THREAD

**Issue by MubiTec** [ioBroker/ioBroker.admin#1150]
**Describe the bug**  
Most times I cannot reach via mobile Chrome and opera browser admin5 (5.1.25). In the case I can reach it it is very slow. 
I deleted all history data in browser but without any effect. 
On Chrome at laptop there is no problem. 
Is there an other possibility to delete cache like shift reload at the laptop?

**Comment by Apollon77** [comment]
>  Is there an other possibility to delete cache like shift reload at the laptop?

This highly depends on your mobile device and Google should be able to better help you, or? ;-)

**Comment by MubiTec** [comment]
So yesterday I cleared als history data including all cache. Then it works one time and accessing it a second time won't work.
Now I installed Firefox as anybody mentioned similar behavior and this browser works.
I cannot say why it do not work with Chrome and opera

**Comment by Feuer-sturm** [comment]
@MubiTec please check your problem with current admin version if it still exists.

**Comment by MubiTec** [comment]
Not really. Instances and objects works fine but scripts still do not load... 
![Screenshot_2022-03-01-05-39-43-05](https://user-images.githubusercontent.com/44448393/156105927-82ad6aa1-b372-4533-8f39-6d3a20087b3f.jpg)

**Comment by GermanBluefox** [comment]
Are you trying to reach admin via VPN?

**Comment by MubiTec** [comment]
No, without VPN.
I didn't try it for a long tinw, but as I saw your message, I tried it minutes ago and could say that know at the moment everything works fine, even the scripts
