### ISSUE TITLE
Error when Log In via web interface

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.admin#1151]
**Describe the bug**  
When I log in into ioBroker Webinterface I get the following error in Log.
Since the error seems to have no consequence at all it´s just something optical that should be corrected.
Before Update to the new GUI I didn´t have this issue.

**Expected behavior**  
No error

**Screenshots & Logfiles**  
`
<html>
<body>

admin.0 | 2021-09-01 12:36:35.350 | error | error
-- | -- | -- | --
admin.0 | 2021-09-01 12:36:35.332 | error | failed connection to socket.io from ::ffff:192.168.178.101:

</body>
</html>`

**Versions:**  
 - Adapter version: v5.1.25
 - JS-Controller version: 3.3.14
 - Node version: v12.22.2 
 - Operating system: Raspian

**Comment by Apollon77** [comment]
authentication enabled? Then duplicate to #1000

**Comment by Claus1985** [comment]
yes, authentication is enabled. Should I close this issue?
