### ISSUE TITLE
IObroker - Error in GUI - Users

### ISSUE THREAD

**Issue by Gut-Drauf** [ioBroker/ioBroker.admin#1154]
**Describe the bug**  

**To Reproduce**  
1. Go to 'menu'
2. Click on 'user'
3. 
4. See error in GUI

**Expected behavior**  
`
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.0.109:8081
iobroker.admin@5.1.23 main.692229dc.chunk.js:2:1133963
[2021-09-05T13:29:16.234Z] Try to connect 5.42ef9396.chunk.js:2:6132559
Translation for word "Enabled" in "de" was ignored: existing = "aktiviert", new = Aktiviert 5.42ef9396.chunk.js:2:6132559
Translation for word "users permissions" in "de" was ignored: existing = "Gruppen-Rechte", new = Benutzerberechtigungen 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:16.644Z] ws connection error: CLOSE_ABNORMAL 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:16.648Z] Start reconnect 0 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:16.648Z] Try to connect 5.42ef9396.chunk.js:2:6132559
Firefox kann keine Verbindung zu dem Server unter ws://192.168.0.109:8081/?sid=1630848616648&name=admin aufbauen. socket.io.js:91:21
[2021-09-05T13:30:19.132Z] Start reconnect 1 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:19.132Z] ws connection error: CLOSE_ABNORMAL 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:19.133Z] Reconnect is already running 1 5.42ef9396.chunk.js:2:6132559
[2021-09-05T13:30:20.144Z] Try to connect 5.42ef9396.chunk.js:2:6132559
Die Ressource von "http://192.168.0.109:8081/static/js/8.d988ca16.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
192.168.0.109:8081
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.0.109:8081/static/js/8.d988ca16.chunk.js". 192.168.0.109:8081:1:1
ChunkLoadError: Loading chunk 8 failed.
(error: http://192.168.0.109:8081/static/js/8.d988ca16.chunk.js)
    e http://192.168.0.109:8081/#tab-intro:1
    Di http://192.168.0.109:8081/static/js/main.692229dc.chunk.js:2
    V http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Ui http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Cl http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    _l http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    El http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    ml http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    unstable_runWithPriority http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Wa http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Ga http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Ua http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    ke http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    Yt http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
    r http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js:2
5.42ef9396.chunk.js:2:6132559
Die Ressource von "http://192.168.0.109:8081/static/js/0.3a1fcae0.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
192.168.0.109:8081
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.0.109:8081/static/js/0.3a1fcae0.chunk.js". 192.168.0.109:8081:1:1
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.0.109:8081/static/css/main.950070b4.chunk.css
Source-Map-Adresse: main.950070b4.chunk.css.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.0.109:8081/static/js/main.692229dc.chunk.js
Source-Map-Adresse: main.692229dc.chunk.js.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.0.109:8081/static/js/5.42ef9396.chunk.js
Source-Map-Adresse: 5.42ef9396.chunk.js.map
`

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - IObroker version: 5.1.23
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: Raspberry Pi 4

**Additional context**

**Comment by Feuer-sturm** [comment]
@Gut-Drauf please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
