### ISSUE TITLE
Feature Request: Add Custom CSS to Admin UI

### ISSUE THREAD

**Issue by workoutsevende** [ioBroker/ioBroker.admin#1156]
Dear ioBroker Team,

thanks for this nice looking Admin Panel we have since Version 5. Since some of us are able to write CSS Code, it would be nice if you could add a possibility to add some custom CSS to the admin UI in order to make some personal tweaks.

For a quick solution it might be an idea to add a section into the settings with a textbox to write some code which then will be included into the header section as CSS-File (or maybe directly using <style> Tags)

However I would love to hear if there could be any solution for this.

Thank you
Daniel

**Comment by AlCalzone** [comment]
There are browser plug-ins that let you do this on any page. Maybe that's a solution for you?

**Comment by GermanBluefox** [comment]
Very strange question, I would say...
What is a use-case?
