### ISSUE TITLE
Error in GUI; TypeError: Cannot read properties of undefiend (reading 'object')

### ISSUE THREAD

**Issue by BKhenloo** [ioBroker/ioBroker.admin#1157]
![image](https://user-images.githubusercontent.com/74878006/133195226-137b5675-3f3e-4e17-806c-bfae302c03ba.png)

**Comment by Feuer-sturm** [comment]
@BKhenloo please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
