### ISSUE TITLE
Problems with Safari Browser  

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.admin#1161]
**Describe the bug**  
Can not edit common of datapoint with Safari Browser 
No Adapter on Adapter-Tab ("Alle Elemente werden herausgefiltert")

**To Reproduce**  
With Firefox it's possible to edit the common and show the adapters

**Screenshots & Logfiles**  
<img width="775" alt="Bildschirmfoto 2021-09-15 um 11 51 37" src="https://user-images.githubusercontent.com/8231359/133412620-2da103fe-0521-4812-b7a8-ec292116d1f3.png">

**Versions:**  
 - Adapter version: 5.1.23
 - JS-Controller version: 3.3.15
 - Node version: v12.20.1
 - Operating system: Debian

**Additional context**

**Comment by Apollon77** [comment]
Pleas echeck the Browser Javascript error console. any error shown?

**Comment by Schmakus** [comment]
no errors in adapters tab. 
errors at editing datapoint, but only missing images. (screenshot)
<img width="1678" alt="Bildschirmfoto 2021-09-15 um 13 02 27" src="https://user-images.githubusercontent.com/8231359/133422143-43dd237f-3582-45f9-8930-4a878c3cb9a0.png">

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
