### ISSUE TITLE
Diagram: second half invisible

### ISSUE THREAD

**Issue by thomas725** [ioBroker/ioBroker.admin#1162]
**Describe the bug**  
Objects -> Settings -> Diagrams looks like this for me:
![image](https://user-images.githubusercontent.com/68635351/133432856-305d4c08-0391-4406-8e00-655e35ca76b7.png)
On mouse-over the data-dot and popup with value also shows for the invisible half of the diagram, so I guess it's only a GUI problem.

**Expected behavior**  
I'd expect the line and area to span the whole diagram, not just the first half.

**Versions:**  
 - Adapter version: Admin v5.1.25
 - JS-Controller version: 4.0.0
 - Node version: v14.17.6
 - Operating system: Linux Mint 20.2, Kernel 5.11.0-25

**Additional context**  
https://forum.iobroker.net/topic/46098/test-adapter-influxdb-2-0/175?_=1631619648144

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
