### ISSUE TITLE
Edge: error in iobroker.admin

### ISSUE THREAD

**Issue by marian-t-web-de** [ioBroker/ioBroker.admin#1164]
iobroker.admin crash, v.5.1.25

![image](https://user-images.githubusercontent.com/37208979/133679615-41b020f8-f461-461d-88fe-a37d8c3f7e39.png)

**Comment by Feuer-sturm** [comment]
@marian-t-web-de Bitte dein Problem mit Admin 5.3.1 nachtesten und wenn das Problem noch besteht kann das Ticket wieder geöffnet werden.
