### ISSUE TITLE
Unable to create adapter restart rule with individual interval

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#1168]
**Describe the bug**  
The cron-wizard only allows to create restart-rule "every minute". Every other scheduling will be ignored.

**To Reproduce**  
1. Go to 'Instances Tab'
2. Click on 'Expert-Mode'
3. Scroll down to any adapter
4. double click this adapter to expand it's additional settings
5. klick on the pencil beside the clock icon to open the restart cron wizard
6. select any scheduling you like - unless it's "every minute"
7. klick "OK"

**Expected behavior**  
Schedule a restart of this adapter in the selected interval (every day, ...)

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/5459426/134154876-164b1d51-5d4a-4fb1-95b0-6422c1aa9663.png)

![grafik](https://user-images.githubusercontent.com/5459426/134154997-5476afe9-574e-4373-8223-19461091f789.png)

**Versions:**  

Plattform    linux
Betriebssystem    Debian linux 10 Buster
Architektur    x64
Node.js    v12.22.5 (Es gibt eine neuere Version: v12.22.6)
NPM    6.14.14
Aktive Instanzen    29
location    /opt/iobroker/
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18

**Comment by Apollon77** [comment]
Ahhhhh ... but if you do that you also need to klick through "minute" and the other tags and set what you want there like "every day at 0 hour and 0 minute

**Comment by Grizzelbee** [comment]
Ah! Okay. Haven't thought that way. So - yes - I'm the issue. Thanks a lot for explanation.
Closed this as solved.
