### ISSUE TITLE
Admin 5: Clicking on instance settings toggles the extended options expander

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1169]
**Describe the bug**  
See video
![settings](https://user-images.githubusercontent.com/17641229/134158766-a08c38b3-05a2-4058-b6a4-e1df1901e0d3.gif)

**Expected behavior**  
The expander should not be toggled

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: v14.16.0
 - OS: Raspberry Pi OS (Buster)

**Additional context**

**Comment by Feuer-sturm** [comment]
is fixed with 6.0.3
