### ISSUE TITLE
Admin 5: Trying to copy information for a host toggles the expander

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1170]
**Describe the bug**  
See video
![hosts](https://user-images.githubusercontent.com/17641229/134159390-ddbcef24-4431-49a0-bc6e-827037de5403.gif)

**Expected behavior**  
The expander should not be toggled

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: v14.16.0
 - OS: Raspberry Pi OS (Buster)

**Additional context**

**Comment by Feuer-sturm** [comment]
ok with admin 6.0.3
