### ISSUE TITLE
iOS: Kein Login via Safari möglich, wenn Authentifizierung aktiviert

### ISSUE THREAD

**Issue by JayVee2** [ioBroker/ioBroker.admin#1173]
Wenn in iobroker.admin "Authentifizierung aktiviert" ist, dann ist kein Login möglich. Die Darstellung verharrt beim drehenden ioBroker Logo. Die Login-Seite erscheint nicht.
Getestet auf iPhone und iPad.

-jayvee

**Comment by Apollon77** [comment]
https? oder http?

**Comment by JayVee2** [comment]
> 
> 
> https? oder http? iOS 15? 14?

https, port 8081.
iOS 14.7.1

**Comment by Apollon77** [comment]
Peas epost output of "iobroker cert view"

**Comment by JayVee2** [comment]
> 
> 
> Peas epost output of "iobroker cert view"

`{
  "certificateFilename": null,
  "certificate": "-----BEGIN CERTIFICATE-----\r\nMIIDczCCAlugAwIBAgIICyQIlv2U1RYwDQYJKoZIhvcNAQELBQAwPjERMA8GA1UE\r\nAxMIaW9icm9rZXIxFjAUBgNVBAoTDWlvQnJva2VyIEdtYkgxETAPBgNVBAsTCGlv\r\nYnJva2VyMB4XDTIxMDgxMzEwNDYwMVoXDTIyMDgxMzEwNDYwMVowOTEMMAoGA1UE\r\nAxMDcGkzMRYwFAYDVQQKEw1pb0Jyb2tlciBHbWJIMREwDwYDVQQLEwhpb2Jyb2tl\r\ncjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALnEnrT2r9Lmdw4eUbOh\r\n14oMtsMH0SXntDxZzDDl5aGuceSTQ0zOdukXhzQnOcgvwGrSPHJ10mTCjPFYvTYO\r\ncwGmZkuhxhH/JynCZhGe76bRU4ubtj/r6UYeTKi64qr4JIL5yQrn61yrhf9zUgRU\r\n3Pe1gCMzmKzSzpGplNN+r0eeOfP6xY0hzD+eJ1leB8+odns7BWkdQOqof0KDBmUA\r\nV8rcs7gFCPIx35ht1g7SY4FRsfm/eBDBWmuOjGhWIMJ5GLTE9aaP9GNPb+updZhT\r\nj0FNwQTo0XT9bJOXBEhyXdwTMfG8dgAcLcfdSHzviAFgSjYj6M1N43Mcbro2ETOD\r\n+o0CAwEAAaN6MHgwDAYDVR0TAQH/BAIwADAPBgNVHQ8BAf8EBQMDB7+AMA4GA1Ud\r\nEQQHMAWCA3BpMzAdBgNVHQ4EFgQUURJw/R1W0/Oytr2P7SCKp4I7LUcwHQYDVR0l\r\nBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAkGA1UdIwQCMAAwDQYJKoZIhvcNAQEL\r\nBQADggEBAB4lvKcohqhooPwKR14Pmw92JLaOd04yyiVu1JLyo5i+ju3+MsQnnE+V\r\nyEi1Y7k7KdGeoKaPN48bwFnIsf2Hg4zKld+iibJAfdWnJ5Od8WGdMIpu0BsQvDzq\r\n3WPdU8N/Upm1BuBI6pRrBPvMs+vRCCtHjNF5kP5bYrmMM8JXpibYkfxQ1xpW96jQ\r\nE9MSDCJpZK+zxdAkWwb7/WfqMygRkS89t13n2ohw28lIad7asFJel7Xd+NDh7Kev\r\nXgqy76AGjOjQC+P2A/3YYvtMOKE0UXdBENSEzJ+COMIgtzHHyjP+pr9E2BdFRVXa\r\n+tdLEXtbtaGQAbP5y7QJg64muwS3Itk=\r\n-----END CERTIFICATE-----\r\n",
  "serialNumber": "0b240896fd94d516",
  "signature": "sha256WithRSAEncryption",
  "keyLength": 2048,
  "issuer": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "7e4805a252caec3f7eeed95aba55c8417d8ad7a7"
  },
  "subject": {
    "attributes": [
      {
        "type": "2.5.4.3",
        "value": "pi3",
        "valueTagClass": 19,
        "name": "commonName",
        "shortName": "CN"
      },
      {
        "type": "2.5.4.10",
        "value": "ioBroker GmbH",
        "valueTagClass": 19,
        "name": "organizationName",
        "shortName": "O"
      },
      {
        "type": "2.5.4.11",
        "value": "iobroker",
        "valueTagClass": 19,
        "name": "organizationalUnitName",
        "shortName": "OU"
      }
    ],
    "hash": "17801a9a18404ea00cda48944bac5223739520c2"
  },
  "dnsNames": [
    {
      "type": 2,
      "value": "pi3"
    }
  ],
  "keyUsage": {
    "id": "2.5.29.15",
    "critical": true,
    "name": "keyUsage",
    "digitalSignature": true,
    "nonRepudiation": false,
    "keyEncipherment": true,
    "dataEncipherment": true,
    "keyAgreement": true,
    "keyCertSign": true,
    "cRLSign": true,
    "encipherOnly": true,
    "decipherOnly": true
  },
  "extKeyUsage": {
    "id": "2.5.29.37",
    "critical": false,
    "name": "extKeyUsage",
    "serverAuth": true,
    "clientAuth": true
  },
  "validityNotBefore": "2021-08-13T10:46:01.000Z",
  "validityNotAfter": "2022-08-13T10:46:01.000Z"
}
`

**Comment by Apollon77** [comment]
Hm ... then strange ... no issues known so far with iOS 14 and such "New" certificates ...

**Comment by JayVee2** [comment]
> 
> 
> Same issue as #1112 ?

Yes.

**Comment by Feuer-sturm** [comment]
In this feed https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/436 there was the feedback that the problem is not there any more with iOS 15

**Comment by JayVee2** [comment]
I confirm: Problem solved with iOS 15.
