### ISSUE TITLE
Wizard doesn't save selected language

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1175]
**Describe the bug**  

**To Reproduce**  
1. Install ioBroker by using the install.sh script
2. Open the wizard
3. Select "Deutsch" in the second step

**Expected behavior**  
The UI should be German after completing the wizard - but the system language was empty (not even English).

**Screenshots & Logfiles**  

<img width="1951" alt="Screenshot 2021-10-01 at 15 18 40" src="https://user-images.githubusercontent.com/1959049/135626602-c365335c-5dc5-4656-96ba-9dc0b57673fc.png">

<img width="1945" alt="Screenshot 2021-10-01 at 15 19 01" src="https://user-images.githubusercontent.com/1959049/135626623-e33d60cc-7143-4da5-bac1-5ec9ad25f3f7.png">

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Raspbian Buster

**Comment by GermanBluefox** [comment]
Should be fixed in 5.1.26 (not yet released)

**Comment by Feuer-sturm** [comment]
Steps done during validating this issue:
- New ubuntu os
- Install iobroker by using current install script `curl -sLf https://iobroker.net/install.sh | bash -`
- iobroker with Admin 5.1.25 will be installed (stable version?!?)
- Language is not filled in settings
- Manual update from Admin 5.1.25 to 5.2.1 (Why is a newer version for manual update available? My expectation would be that the current stable version is installed by the installer)
- Language is not filled in settings

New test necessary if a newer Admin version than 5.1.25 is in stable available

**Comment by Apollon77** [comment]
The version thing comes from a missing update of the NPM stable tag when putting admin 5.2.1 into stable ... in fact we need 5.2.2 to get there I think

**Comment by Feuer-sturm** [comment]
New retest of issue:

- New ubuntu os
- Install iobroker by using current install script curl -sLf https://iobroker.net/install.sh | bash -
- iobroker with Admin 5.2.3 will be installed
- Language "German" was preselected in wizzard
- Check iobroker basic setting -> Language is not filled

**Comment by GermanBluefox** [comment]
I testes just now with 5.2.3 and the language was set...

**Comment by Feuer-sturm** [comment]
Issue is fixed.
Installed new iobroker with install script. Language "Deutsch" was preselected in wizard.
Check Admin setting: Language is set as well -> ok

@klein0r @Apollon77 Issue can be closed.

**Comment by Apollon77** [comment]
Tested te same and had the same result
