### ISSUE TITLE
Filter in objects tab is not working properly

### ISSUE THREAD

**Issue by eitch** [ioBroker/ioBroker.admin#1177]
**Describe the bug**  
The filter for name (and other fields) does not work intuitively in the objects tab. If i type a value in the name input field, then the filter greys out all nodes which don't fit the criteria. In some cases it is possible that the entering values actually filters the nodes, so that i only see the nodes which match the criteria.

The filtering out of the nodes isn't important, if the highlighted nodes would then be used in the "Edit custom config" action on the top right, but this is not the case, see the second screenshot.

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**
First screenshot:
![image](https://user-images.githubusercontent.com/245382/135989771-5fca3aad-332c-4176-af43-0f1b80746083.png)

Second screenshot showing that the editing is for 84 states, but my filter only highlights 13 nodes:
![image](https://user-images.githubusercontent.com/245382/135990629-59e3b25f-3bd3-46bf-b030-3172e1e8f036.png)

**Versions:**  
 - Adapter version: v5.1.25
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: docker container: buanet/iobroker:latest-v5

**Comment by Feuer-sturm** [comment]
@eitch Is this issue avaiable in different browsers? Which browser do you use?

Are there any errors in the "Browser Konsole" (Strg + Shit + i in Chrome e.g.)?

**Comment by eitch** [comment]
@Feuer-sturm on Firefox the websocket connection does not want to work. The TLS connection is a proxy to the non-TLS connection, which works on other browsers:

![image](https://user-images.githubusercontent.com/245382/136178242-853676ec-2568-4392-9c5c-f0b9bb04cf10.png)

It's weird, on a different computer, using Chrome and Chromium the search criteria leads to a greying out, then clicking on the refresh button on the top left leads to an actual filtering. After filtering i can then edit the custom config as expected.

In some situations it seems that this filtering does not work as intended. When it works, then it also seems to save the filter criteria when i switch tabs. When it doesn't, then it seems to not save the criteria.

I don't see any errors in the logs. I am also using https://webcatalog.io/webcatalog to access the installation, and there the situation is the same as with Chrome/Chromium, which is expected as these are Electron Apps using Chromium in the background.

I am using Chrome 92.0.4515.93 and Chromium 92.0.4515.159. WebCatalog Chromium is 93.x

**Comment by passuff** [comment]
Described a comparable issue here: https://forum.iobroker.net/topic/51850/filtern-im-objektbrowser-bug-oder-feature?_=1643279245209
Wenn ich nach einem Objekt filtere, werden mir zunächst alle anderen ausgegraut ebenfalls angezeigt:

![image](https://user-images.githubusercontent.com/39516113/151370915-68c12915-e526-4ff5-9d7f-8689b44f6199.png)

Erst wenn ich das die Einstellungen des Objektes verändere, werden die anderen Objekte ausgeblendet:
![image](https://user-images.githubusercontent.com/39516113/151370953-a4ba308e-5c18-48d9-9445-e7b7e46b063d.png)


Bug or Feature? 😉

**Comment by Feuer-sturm** [comment]
Not fixed yet

**Comment by GermanBluefox** [comment]
Fixed in Admin 6. Please verify

**Comment by Diginix** [comment]
Works for me with v6.0.1.
