### ISSUE TITLE
Old active repository in adapter list after default repository changed

### ISSUE THREAD

**Issue by macpo** [ioBroker/ioBroker.admin#1178]
**Describe the bug**  
In the adapter list the former selected default repository is displayed.

**To Reproduce**  
1. Open system settings
2. Change default repository
3. Click on 'Save and close'
4. Open/refresh adapter list
The banner with the active repository shows still the former selected default repository.

**Expected behavior**  
The current selected default repository shall be shown in the banner in the adapter list.

**Screenshots**  
![image](https://user-images.githubusercontent.com/17279799/136532885-899bb312-8e26-4dae-b958-3f2d244bb60f.png)

![image](https://user-images.githubusercontent.com/17279799/136532927-d54184f8-b1a0-48b9-83bc-3d381babe399.png)

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Debian on RaspPi

**Comment by GermanBluefox** [comment]
Should be fixed in 5.1.26 (not yet released)

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 @macpo Issue is fixed with admin 5.1.28
