### ISSUE TITLE
Adapter list - Colour for active repository too bright in dark mode

### ISSUE THREAD

**Issue by macpo** [ioBroker/ioBroker.admin#1179]
In the Adapter list the colour of the line for the active repository is yellow in dark mode, which is really bright. 
![image](https://user-images.githubusercontent.com/17279799/136553321-dcfdac72-4f52-4145-85dc-1bf255229a5b.png)

![image](https://user-images.githubusercontent.com/17279799/136552662-504266ae-9157-4466-af09-4ce1626802f6.png)

A lighter yellow will not be so loud.
![image](https://user-images.githubusercontent.com/17279799/136553295-f552b317-3efc-46ff-ad87-bccc14d0db44.png)

**Comment by GermanBluefox** [comment]
Changed to darker one in 5.1.26 (not yet released)
![image](https://user-images.githubusercontent.com/4582016/139540859-0f3313c7-64c6-4e01-8668-230271e6f516.png)

**Comment by Feuer-sturm** [comment]
Admin 5.1.28
Changed colour is available
![grafik](https://user-images.githubusercontent.com/25422320/141700001-3227b626-ae83-42ea-9087-65e36a4cce51.png)
