### ISSUE TITLE
Adapters are still shown with old version though updated

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.admin#1183]
**Describe the bug**  
Adapters are still shown with old version though updated.

**To Reproduce**  
Self-explanatory

**Expected behavior**  
After updating adapters they should have disappeared from the filtered list or at least show the update version and not the old version

**Screenshots & Logfiles**  
n.a.

**Versions:**  
 - Adapter version:5.1.25
 - JS-Controller version: <3.3.18> 
 - Node version: <v12.22.1> 
 - Operating system: <Debian under Proxmox VM>

**Additional context**  
n.a.

Examples:

<img width="1182" alt="grafik" src="https://user-images.githubusercontent.com/53481090/137278507-dca02259-05a6-4170-8660-15500b3c129c.png">

**Comment by Feuer-sturm** [comment]
@MichaelSchaaf999 Please check with Admin 5.3.1 if this issue is fixed on your side. On my system it looks ok.

**Comment by MichaelSchaaf999** [comment]
Thanks, Feuer-sturm, the issue seems to be fixed.
Appreciate your work.
