### ISSUE TITLE
"See on github" Button every Adapter ends in 404 Error

### ISSUE THREAD

**Issue by tehmilcho** [ioBroker/ioBroker.admin#1184]
**Describe the bug**  
The little button "See on github" by every Adapter "Readme" ends in a 404 Error from Github

**To Reproduce**  
1. Go to 'Apdapters'
2. Click on '?' by any Adapter
3. Scroll down to the end and click on "See on github"
4. See error - Website not found (404)

**Expected behavior**  
The Github Page of the Apdater should be opened

**Screenshots & Logfiles**  
N/A

**Versions:**  
 - Adapter version: 5.1.25 
 - JS-Controller version:  3.3.10  
 - Node version: V12.22.1 
 - Operating system: Ubuntu

**Comment by GermanBluefox** [comment]
Fixed in the next version 5.1.26 
Link is removed because is the same as "Open in new tab" Button

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 @tehmilcho 
Link "Siehe auf Github" is removed with admin 5.1.28
