### ISSUE TITLE
ioBroker.net License management

### ISSUE THREAD

**Issue by chefkoch009** [ioBroker/ioBroker.admin#1188]
I as an adapter developer want to have a central place/interface for licenses.
The user must enter email/password in the admin system settings and the licenses will be synchronized with the cloud.

After that the adapters can access the licenses via system.licenses object

**Comment by GermanBluefox** [comment]
IMplemented:
![image](https://user-images.githubusercontent.com/4582016/172903395-d2b6d23f-9e30-4237-82d9-8a13b149e234.png)
