### ISSUE TITLE
Iobroker asked me to report that

### ISSUE THREAD

**Issue by codingdave** [ioBroker/ioBroker.admin#1189]
Using chrome on Android 11. I was logged in and at ZigBee, then clicked somewhere else in the menu on the left. I do not know where I clicked exactly. Then I got this screen. Since I do not have a f12 key on my mobile device i want able to do the steps below.

Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on github
Without this information it is not possible to analyse the error.
It should looks like
error
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Loading chunk 11 failed. (error: https://192.168.178.36:8081/static/js/11.5d187238.chunk.js)
ChunkLoadError: Loading chunk 11 failed.function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}(error: https://192.168.178.36:8081/static/js/11.5d187238.chunk.js)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Function.u.e (https://192.168.178.36:8081/:1:3980)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at https://192.168.178.36:8081/static/js/main.1892293b.chunk.js:2:1095004function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at V (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5551848)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ui (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5542033)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Cl (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5528627)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at _l (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5528555)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at El (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5528418)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at ml (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5525384)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5474763function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (https://192.168.178.36:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)

**Comment by GermanBluefox** [comment]
Thank you for your report.
That could happen one time by update of admin
