### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by MaetthuK** [ioBroker/ioBroker.admin#1190]
*Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.1.195:8081
iobroker.admin@5.1.25 main.1892293b.chunk.js:2:1135948
[2021-10-28T15:28:24.578Z] Try to connect socket.io.js:59:41
Uncaught SyntaxError: illegal character U+0000
13.7d21ae26.chunk.js:1:29752
ChunkLoadError: Loading chunk 13 failed.
(missing: http://192.168.1.195:8081/static/js/13.7d21ae26.chunk.js)
    e http://192.168.1.195:8081/:1
    zi http://192.168.1.195:8081/static/js/main.1892293b.chunk.js:2
    V http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ui http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Cl http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    _l http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    El http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    ml http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    unstable_runWithPriority http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Wa http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ua http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    hl http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    enqueueSetState http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    setState http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    t http://192.168.1.195:8081/static/js/main.1892293b.chunk.js:2
    u http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    _invoke http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    w http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    r http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    i http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
5.bde6ca2f.chunk.js:2:5512353
    ii http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    payload http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    uc http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Io http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ui http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Cl http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    _l http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    El http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    ml http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    unstable_runWithPriority http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Wa http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ga http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    Ua http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    hl http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    enqueueSetState http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    setState http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js:2
    value http://192.168.1.195:8081/static/js/main.1892293b.chunk.js:2
Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 29755 of the JSON data
Ressourcen-Adresse: http://192.168.1.195:8081/static/js/main.1892293b.chunk.js
Source-Map-Adresse: main.1892293b.chunk.js.map

Source-Map-Fehler: Error: JSON.parse: bad control character in string literal at line 1 column 29754 of the JSON data
Ressourcen-Adresse: http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js
Source-Map-Adresse: 5.bde6ca2f.chunk.js.map

Source-Map-Fehler: Error: JSON.parse: unexpected character at line 1 column 29755 of the JSON data
Ressourcen-Adresse: http://192.168.1.195:8081/static/js/main.1892293b.chunk.js
Source-Map-Adresse: main.1892293b.chunk.js.map

Source-Map-Fehler: Error: JSON.parse: bad control character in string literal at line 1 column 29754 of the JSON data
Ressourcen-Adresse: http://192.168.1.195:8081/static/js/5.bde6ca2f.chunk.js
Source-Map-Adresse: 5.bde6ca2f.chunk.js.map

​

**Comment by GermanBluefox** [comment]
That could happen one time by update of admin
