### ISSUE TITLE
Error in Gui ChunkLoadError

### ISSUE THREAD

**Issue by Lantasch** [ioBroker/ioBroker.admin#1193]
Opening Objects tab, after changing Name Of a Shelly aktor in its web interface.

Every thing else funktions normal. 

iobroker.admin@5.1.25
socket.io.js:59 [2021-11-01T12:50:14.976Z] Try to connect
Instances.js:444 getInstances: 83
7.34479e94.chunk.js:2 Uncaught SyntaxError: Unexpected string
react-dom.production.min.js:216 ChunkLoadError: Loading chunk 7 failed.
(missing: http://192.168.178.34:8081/static/js/7.34479e94.chunk.js)
    at Function.u.e ((index):1)
    at App.js:73
    at V (react.production.min.js:18)
    at Ui (react-dom.production.min.js:269)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
Io @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
_l @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
:8081/#tab-objects:1 Uncaught (in promise) {}
:8081/#tab-objects:1 Uncaught (in promise) {}

**Comment by GermanBluefox** [comment]
this could happen if version updated.

**Comment by Lantasch** [comment]
ok, i don't know why or what happend, but i waited 6 hours and now it is functioning again.
