### ISSUE TITLE
Another Error in GUI

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.admin#1194]
**Describe the bug**  
Admin5 crashes sometimes

**To Reproduce**  
I found no rules or a way how to reproduce the error.

**Expected behavior**  
Admin5 will work without crashing

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/58858526/139686033-bbd10c74-a885-417d-bf4e-c0b1cf11e884.png)

![image](https://user-images.githubusercontent.com/58858526/139686953-ac76f44e-5c19-4b51-955d-17355c03e35c.png)

Loading chunk 12 failed. (error: http://iobrokerhost.fritz.box:8081/static/js/12.490971aa.chunk.js)

`
ChunkLoadError: Loading chunk 12 failed.function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}(error: http://iobrokerhost.fritz.box:8081/static/js/12.490971aa.chunk.js)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Function.u.e (http://iobrokerhost.fritz.box:8081/:1:3981)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://iobrokerhost.fritz.box:8081/static/js/main.1892293b.chunk.js:2:1094499function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at V (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5551848)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Ui (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5542033)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at Cl (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5528627)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at _l (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5528555)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at El (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5528418)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at ml (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5525384)function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5474763function(e,t){return Object(Me.jsxs)("div",{children:[e,Object(Me.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://iobrokerhost.fritz.box:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)
`

**Versions:**  
 - Adapter version: 5.1.25
 - JS-Controller version: 3.3.18
 - Node version: 14.18.1
 - Operating system: raspberry bullseye

**Additional context**  
---

**Comment by Feuer-sturm** [comment]
@mickym2 please check your problem with current admin version if it still exists.

**Comment by mickym2** [comment]
I am not able to reproduce an error which randomly occurs. I opened this issue - as it was recommended to do so. So I do not know if someone fix the error. Randomly I still get sometimes an Error in the GUI - but I restart the browser and it is fine. So if the developers think that the error is fixed or do not need this information - I am fine as well. So I close it from my side as I will not follow up this issue.
