### ISSUE TITLE
Error message when calling the objects

### ISSUE THREAD

**Issue by miklmoor76** [ioBroker/ioBroker.admin#1200]
Hello,
since a short time whenever I call the objects at the admin Console (:8081), an error message comes - and thus I can not see the values of the objects. Ask for further assistance...... Thank you.

1)I call up the following line via the Edge browser:
	"https://192.168.1.112:8081/#tab-intro"
2)Then I go to the objects on the left side...., and the error message comes.
	Missing image "Screenshot-tab-objects.png" in the attachment

**Expected behavior**	
Actually, the object list should come?!!

**Screenshots & Logfiles** 
	message "Fehler-Konsole-Text.txt" in the attachment
	picture "Fehler-Konsole-Bild.png" in the attachment

**Versions:**  
 - Adapter version:<ModBus, 3.4.14>
 - JS Controller Version: <3.2.16>
 - Node version: <node-version><v14.17.2>
 - Operating System:<Linux IOB 5.10.17-v7l+>
[Fehler-Konsole-Text.txt](https://github.com/ioBroker/ioBroker.admin/files/7531504/Fehler-Konsole-Text.txt)
![Fehler-Konsole-Bild](https://user-images.githubusercontent.com/93946091/141608398-946b78a2-d504-4997-8419-f4f7e9b95304.png)
![Screenshot-tab-objects](https://user-images.githubusercontent.com/93946091/141608408-1ebe3f36-5dca-496d-a49f-6694977473ad.png)

**Comment by Feuer-sturm** [comment]
@miklmoor76 please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
