### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by mmwulfsen** [ioBroker/ioBroker.admin#1203]
**Describe the bug**  

**To Reproduce**  
1. Go to #tab-adapters

**Expected behavior**  
after installing 
https://github.com/AttackStrawbery/ioBroker.sma-speedwire

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 3.3.18
 - Node version: 14.18.1 
 - Operating system: Raspbian 

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BAdapter%20to%20query%20values%20from%20sma%20devices%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (5.bde6ca2f.chunk.js:2)
    at 5.bde6ca2f.chunk.js:2
    at Ro (5.bde6ca2f.chunk.js:2)
    at Ui (5.bde6ca2f.chunk.js:2)
    at Cl (5.bde6ca2f.chunk.js:2)
    at _l (5.bde6ca2f.chunk.js:2)
    at El (5.bde6ca2f.chunk.js:2)
    at ml (5.bde6ca2f.chunk.js:2)
    at 5.bde6ca2f.chunk.js:2
    at t.unstable_runWithPriority (5.bde6ca2f.chunk.js:2)
ii @ react-dom.production.min.js:216

Failed to load resource: the server responded with a status of 404 ()

**Comment by Feuer-sturm** [comment]
@mmwulfsen please check your problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
