### ISSUE TITLE
switching colour-scheme reloads adapters admin-page

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#1205]
If you are editing an adapters setting in the adapters admin page (only non-react) and switch colour scheme, the page reloads. All changes are gone without saving.

**Comment by sbormann** [comment]
After the latest updates it seems to work now. Thank you.

**Comment by simatec** [comment]
@sbormann What updates did you do?  My test system is up-to-date and the settings are still lost after a reload.  I think that can only be fixed with an extension in admin

**Comment by sbormann** [comment]
I'm not shure which update made it work, but at the moment the problem is gone.
Admin 5.1.28
js-controller 3.3.19
NODE.JS: V14.18.1
NPM: 6.14.15
