### ISSUE TITLE
Zusammenfassung Bug Admin Oberfläche

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#1206]
nachdem hier mehrere Issus's erstellt wurden, mit scheinbar dem selben/ähnlichem Problem, Zwecks falscher Darstellung, nicht Aktualisierung, 404...
habe ich nochmal eine Zusammenfassung erstellt, siehe  https://forum.iobroker.net/post/704759

Adminversion 5.1.28
Web 3.4.13
socketio 3.1.5
Js-Controller  Version 3.3.18

**Comment by Feuer-sturm** [comment]
@crunchip77 Ist noch etwas von den Punkten die du im Forumsbeitrag genannt hattest offen? Wenn ja, dann sollten wir dazu einzelne Issues erstellen. Ansonsten kann dieses issue geschlossen werden.

**Comment by crunchip77** [comment]
Ja die Punkte  sind nach wie vor offen.

**Comment by GermanBluefox** [comment]
Please validate listed issues and create for EVERY problem one issue. It is hard to monitor and make a discussion for all of things. 
Thank you!

**Comment by crunchip77** [comment]
@GermanBluefox ok, I'll look at it the days and create an issue each if necessary
