### ISSUE TITLE
Habt ein Herz für ältere Menschen

### ISSUE THREAD

**Issue by ohle64** [ioBroker/ioBroker.admin#1208]
Hallo,
bitte mal bei der nächsten Änderung die /lib/web.js in Zeile 144 von white zu black ändern. Weiße Schrift auf Gelben Untergrund???
Nicht jeder hat noch so ein Sehvermögen ;-)
Gruß Frank

**Comment by ohle64** [comment]
ist scheinbar zu schwer zu ändern!

**Comment by Apollon77** [comment]
Wer sagt das?

**Comment by ohle64** [comment]
Vielen Dank! Es gibt noch Menschen mit Herz! Danke
