### ISSUE TITLE
Make Root URL Customizeable

### ISSUE THREAD

**Issue by alexpthe1** [ioBroker/ioBroker.admin#1209]
While setting up a ReverseProxy i have seen that some requests are (obviuosly) hardcoded to the root.
For Example:

/?sid=XXXXXXXX&name=admin from socket.io:91
/login?href=#tab-intro
It would be great to customize the root directory so these requests dont have to be re-written

**Comment by GermanBluefox** [comment]
It is implemented, that admin can run behind reverse proxy. But all other adapters (echart, eventlist, javascript, vis, material, ...) must be updated too..
