### ISSUE TITLE
jsonConfig sendTo jsonData -> allow to send whole io-pack.native

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#1211]
If someone wants to send the whole native, because user assumes what he sees is what he gets, no matter if he has saved the config, this will end up in receiving an `[object Object]` string. In Benchmark adapter I need to send more than 25 options (still ascending) which makes it pretty impractical to explicitly add every native attribute separate.

So it would be nice if I can send `"jsonData" : "${data}"`

**Comment by Feuer-sturm** [comment]
@foxriver76 Is this issue fixed and can be closed?
