### ISSUE TITLE
After update to admin - v5.1.29 - Webfrontend does not load

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.admin#1213]
Having updated admin to v5.1.29 the web gui does not load. 

**Versions:**  
 - Adapter version: 5.1.29
 - JS-Controller version: 3.3.20
 - Node version: v17.1.0
 - Operating system: Raspberry Bullseye
 - system.adapter.socketio                : socketio       - v3.1.5

**Additional context**  
Also see 
https://forum.iobroker.net/topic/49695/iobroker-startseite-nach-admin-update-nicht-mehr-erreichbar

Browser debug says: 
```
iobroker.admin@5.1.29
socket.io.js:59 [2021-11-25T15:04:56.757Z] Try to connect
socket.io.js:59 [2021-11-25T15:04:59.780Z] Authenticate timeout
App.js:268 Socket Error: Authenticate timeout
window.alert @ App.js:268
socket.io.js:59 [2021-11-25T15:04:59.782Z] Start reconnect 0
socket.io.js:59 [2021-11-25T15:04:59.784Z] Try to connect
socket.io.js:61 [2021-11-25T15:04:59.786Z] ws connection error: CLOSED_NO_STATUS
error @ socket.io.js:61
socket.io.js:341 WebSocket connection to 'ws://192.168.178.48:8081/?sid=1637852699784&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:341
socket.io.js:59 [2021-11-25T15:04:59.786Z] Start reconnect 1
socket.io.js:61 [2021-11-25T15:04:59.786Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
2socket.io.js:59 [2021-11-25T15:04:59.786Z] Reconnect is already running 1
socket.io.js:59 [2021-11-25T15:05:00.798Z] Try to connect
```

**Comment by BramTown** [comment]
same here
JS Controller v3.3.20
node v14.18.1
Debian Bullseye

**Comment by Grothesk242** [comment]
In the brower debug I find: 

``
iobroker.admin@5.1.29
socket.io.js:59 [2021-11-25T15:04:56.757Z] Try to connect
socket.io.js:59 [2021-11-25T15:04:59.780Z] Authenticate timeout
App.js:268 Socket Error: Authenticate timeout
window.alert @ App.js:268
socket.io.js:59 [2021-11-25T15:04:59.782Z] Start reconnect 0
socket.io.js:59 [2021-11-25T15:04:59.784Z] Try to connect
socket.io.js:61 [2021-11-25T15:04:59.786Z] ws connection error: CLOSED_NO_STATUS
error @ socket.io.js:61
socket.io.js:341 WebSocket connection to 'ws://192.168.178.48:8081/?sid=1637852699784&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:341
socket.io.js:59 [2021-11-25T15:04:59.786Z] Start reconnect 1
socket.io.js:61 [2021-11-25T15:04:59.786Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
2socket.io.js:59 [2021-11-25T15:04:59.786Z] Reconnect is already running 1
socket.io.js:59 [2021-11-25T15:05:00.798Z] Try to connect
``

**Comment by JogiBarbarski** [comment]
same here
ioBroker.admin 5.1.28
Node.js: v14.18.1
NPM: 6.14.15
js-controller
JS controller Installiert: 3.3.19

Loading chunk 1 failed. (error: http://192.168.188.31:8081/static/js/1.a058e567.chunk.js)

at mountIndeterminateComponent(react-dom-development.js:17811)
at beginWork(react-dom.development.js:19049)
at HTMLUnknownElement.callCallback(react-dom.development.js:3945)
at Object. invokeGuardedCallbackDev (react-dom.development.js:3994)
at invokeGuardedCallback(react-dom.development.js:4056)
at beginWork$1(react-dom.development.js:23964)
at performUnitOfWork(react-dom.development.js:22776)
at workLoopSync (react-dom-development. js:22707)
at renderRootSync(react-dom.development.js:22670)
at performSyncWorkOnRoot(react-dom.development.js:22293)
at react-dom.development.js:11327
at unstable runWithPriority (scheduler.development.js:468)
at runWithPriority$1(react-dom.development.js:11276)
at flushSyncCallbackQueueImpl(react-dom.development.js:11322)
at flushSyncCallbackQueue(react-dom.development.js:11309)
at discreteUpdates$1(react-dom.development.js:22420)
at discreteUpdates(react-dom.development.is:3756)
at dispatchDiscreteEvent (react-dom.development.is: 5889)
» The above error occurred in the «GitHubInstallDialog› component:
at GitHubInstallDialog (http: //localhost:3000/static/js/main-chunk.js:36864:3)
at div
at Grid (http://localhost:3000/static/js/vendors~main.chunk.js:73034:35)
at WithStyles (http: //localhost:3000/static/js/vendors-main.chunk.js:255639:31)
at div
at Paper (http: //localhost:3000/static/js/vendors~main.chunk.js:81079:23)
at
WithStyles(http://localhost:3000/static/is/vendors~main.chunk.is:255639:31)
at TabContainer (http:
/localhost:3000/static/i
/main-chunk.js:25179:1)
at
WithStyles (http:
endors~main.chunk.js:255639:31)

**Comment by Matt77CHE** [comment]
same happens to me

**Comment by Matt77CHE** [comment]
I can load Flot; Vis Edit; Vis - but not iobroker web gui

**Comment by dlehmann69iob** [comment]
same here

**Comment by Matt77CHE** [comment]
I made a downgrade following this : https://forum.iobroker.net/topic/49695/iobroker-startseite-nach-admin-update-nicht-mehr-erreichbar/10

**Comment by mk176** [comment]
same here
npm 6,14,15
node 14,18,.1
jscaontroller 3.3.20
running on Win10x64
after downgrade to 5.1.28 it worked again

**Comment by fuchs-1978** [comment]
Here the Dame, with downgrade all ist okay

**Comment by AlfredSch** [comment]
same here

os             : linux
node        : v12.22.7
NP           : v6.14.15
jscaontroller 3.3.20
after downgrade to 5.1.25 it worked again

**Comment by vepman** [comment]
same here.
Downgrade to 5.1.28 works.

**Comment by sjfm-design** [comment]
yesterday same problem.

**Comment by m0rph2k** [comment]
Update to 5.2.0 works

**Comment by sjfm-design** [comment]
yes, works! 5.2.0

**Comment by JogiBarbarski** [comment]
Danke für die schnelle Problemlösung 👍🏻
