### ISSUE TITLE
Admin 5 - remove js-controller 1.x to 2.x upgrade hint

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1216]
Maybe it's time to remove that hint for very old versions?

<img width="950" alt="Screenshot 2021-11-26 at 12 02 42" src="https://user-images.githubusercontent.com/1959049/143571275-b85ae875-39ee-4243-8ed3-9e520b35c6ac.png">

https://github.com/ioBroker/ioBroker.admin/blob/7be05c7171b9f599476c8849ebb1d9443f3b5379/src-rx/src/dialogs/JsControllerDialog.js#L194-L198

**Comment by GermanBluefox** [comment]
Changed to: `Für ein Update von js-controller lesen Sie bitte immer die Informationen unter`

**Comment by Feuer-sturm** [comment]
@GermanBluefox Why is there a need to have here in the code the instruction if the text of the dialog box for updating js-controller is this page https://github.com/ioBroker/ioBroker.docs/blob/master/admin/de/controller-upgrade.md?

**Comment by Feuer-sturm** [comment]
@GermanBluefox Is there a dependency to this issue? https://github.com/ioBroker/ioBroker.admin/issues/1311

**Comment by Feuer-sturm** [comment]
Admin 6.1.6
The text "Für ein Update von js-controller lesen Sie bitte immer die Informationen unter" is available in the dialog box
![grafik](https://user-images.githubusercontent.com/25422320/175999404-5e9a048d-8a39-4f0b-a944-6427e25eab6e.png)

This issue will be closed. In issue #1311  the discussion will be continued why not the current  updating js-controller page is used.
