### ISSUE TITLE
Probleme mit S7 Adapter

### ISSUE THREAD

**Issue by Chris160681** [ioBroker/ioBroker.admin#1218]
VM65:598 
        
       Encountered a node at with an invalid element index. There are 1 nodes at level 1 but got B11
error @ VM65:598
VM65:598 
        
       Encountered a node at with an invalid element index. There are 1 nodes at level 1 but got B12
error @ VM65:598
Instances.js:444 getInstances: 37
index.js:16 iobroker.s7@1.3.6 using theme "dark"
2.e9f9efb8.chunk.js:2 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

2.e9f9efb8.chunk.js:2 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
2.e9f9efb8.chunk.js:2 Help us to create open source project with reactJS!
2.e9f9efb8.chunk.js:2 See you :)
socket.io.js:59 [2021-11-29T08:50:33.737Z] Try to connect
Instances.js:444 getInstances: 1
Instances.js:444 getInstances: 569
ObjectBrowser.js:2301 + subscribe s7.0.info.connection
ObjectBrowser.js:2301 + subscribe s7.0.info.pdu
ObjectBrowser.js:2301 + subscribe s7.0.info.poll_time
ObjectBrowser.js:2150 > stateChange s7.0.info.connection
ObjectBrowser.js:2150 > stateChange s7.0.info.pdu
2ObjectBrowser.js:2150 > stateChange s7.0.info.poll_time
25.bde6ca2f.chunk.js:2 
        
       DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.removeChild (<anonymous>)
    at Oi (http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js:2:5519753)
    at jl (http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js:2:5531565)
    at t.unstable_runWithPriority (http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)
    at Wa (http://192.168.122.80:8081/static/js/5.bde6ca2f.chunk.js:2:5474540)
    at Vl (http://192.168.122.80:8081/static/js/5.bde6ca2f.chunk.js:2:5529523)
    at ml (http://192.168.122.80:8081/static/js/5.bde6ca2f.chunk.js:2:5525609)
    at http://192.168.122.80:8081/static/js/5.bde6ca2f.chunk.js:2:5474763
    at t.unstable_runWithPriority (http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js:2:5558154)
    at Wa (http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js:2:5474540)
ii @ 5.bde6ca2f.chunk.js:2
ObjectBrowser.js:1801 - unsubscribe s7.0.info.connection
ObjectBrowser.js:1801 - unsubscribe s7.0.info.pdu
ObjectBrowser.js:1801 - unsubscribe s7.0.info.poll_time
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.XXX.XXX.80:8081/static/js/5.bde6ca2f.chunk.js.map konnte nicht geladen werden: Laden wurde aufgrund eines Ladetimeouts abgebrochen.
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.XXX.XXX.80:8081/adapter/s7/static/js/2.e9f9efb8.chunk.js.map konnte nicht geladen werden: Laden wurde aufgrund eines Ladetimeouts abgebrochen.

Fehler kommt, beim öffnen der Objekte, nur bei Installiertem S7 Adapter

Iobroker löuft auf einer Synology NAS im Docker 

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@Chris160681 please check your Problem with current admin version if it still exists.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
