### ISSUE TITLE
Repositories again default and latest

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#1220]
**Describe the bug**  
Since Admin 5.2.x the names of the repositories in system settings are again named default and stable instead Stable and Beta.

**To Reproduce**  
1. Go to 'Admin'
2. Click on 'wrench'
3. Look at Standard repository

**Expected behavior**  
Show Stable and Beta as repository names.

**Screenshots & Logfiles**  
Admin 5.1.28
![image](https://user-images.githubusercontent.com/16007760/144140254-f7efcb0c-1575-4795-9ff6-c524b630546e.png)
Admin 5.2.1
![image](https://user-images.githubusercontent.com/16007760/144140360-100a5ff5-6fda-4574-baef-636d2fc84820.png)

**Versions:**  
 - Adapter version: 5.2.1
 - JS-Controller version: 3.3.21
 - Node version: 16.13.0
 - Operating system: ubuntu 18.04

**Additional context**  
Related to multi repo support?

**Comment by Rene5555** [comment]
Problem beim Eintragen weiterer Repositories: Ich habe es heute morgen mehrmals reproduzieren können, dass ich beim Eintragen und dem nachfolgenden speichern den Fehler "socket error: unknown" erhalte. Danach muss ich das Browserfenster neu starten und die Eingaben wiederholen. Dann gehts. Oder ist das Quatsch, weil das 'http://iobroker.live/repo/sources-dist.json' das gleiche ist, wie schon per Standard eingetragen. System: Buanet-Container: Node.js 14.18.2 und Admin 5.1.25

**Comment by Feuer-sturm** [comment]
New installation with install script (Admin 5.2.3)

With Admin 5.2.3 the names of the repository default / latest are still there.

Using name "default" for the stable repository will cause that the yellow hint will be shown if you open the adapter menu
![grafik](https://user-images.githubusercontent.com/25422320/151075463-1f0efdf4-4aba-4ccb-ae6f-75dac3826994.png)

If the name of the default repository is changed to "stable" there is no yellow hint. This is my expected behavior, that there is no yellow "warning" if I am using the stable repository.

**Comment by Apollon77** [comment]
maybe the translated texts are not used?

**Comment by Feuer-sturm** [comment]
Not fixed yet

**Comment by raschy** [comment]
Bin jetzt auf Admin 5.3.8.  Habe den 'Fehler' nicht mehr feststellen können. Kann geschlossen werden - Danke.

**Comment by Feuer-sturm** [comment]
Hast du auch einmal eine frische Installation mit Admin 5.3.8 gemacht? Bei einer Neuinstallation trat der Fehler auch auf.

**Comment by raschy** [comment]
@Feuer-sturm Ich hab gerade mit dem Image von Buanet:latest einen frischen ioB aufgesetzt. Aktuell beinhaltet dieses den Admin 5.3.1 mit Updatemöglichkeit auf 5.3.8. Dabei habe ich (auch zum wiederholten male) den Effekt, dass sich die 'Basiseinstellungen' nicht schließen lassen.

**Comment by Feuer-sturm** [comment]
Habe gerade einmal ein frisches System aufgesetzt und ioBroker mit Admin 5.3.8 installiert. Die Repositorys sind jetzt nach der Installation korrekt.

![grafik](https://user-images.githubusercontent.com/25422320/166000006-9c164504-11b7-429e-8067-4b4677b61eca.png)


@raschy Wenn sich die Basiseinstellungen (mit Admin 5.3.8) bei dir nicht sauber schließen lassen, wäre das ein eigenes Issue wert und hat mit diesem Thema nichts zu tun.
