### ISSUE TITLE
Multistate state does not return value

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.admin#1222]
If a multistate values are defined in a state

{
  "type": "state",
  "common": {
    "name": "BSH_Common_Root_ActiveProgram",
    "type": "string",
    "role": "indicator",
    "write": true,
    "read": true,
    "states": {
      "Dishcare.Dishwasher.Program.Auto1": "Auto 35-45°C",
      "Dishcare.Dishwasher.Program.Auto2": "Auto 45-65°C",
      "Dishcare.Dishwasher.Program.Auto3": "Auto 65-75°C",
      "Dishcare.Dishwasher.Program.Eco50": "Eco 50°C",
      "Dishcare.Dishwasher.Program.NightWash": "Leise 50°C",
      "Dishcare.Dishwasher.Program.Glas40": "Glas 40°C",
      "Dishcare.Dishwasher.Program.Quick45": "Schnell 45°C",
      "Dishcare.Dishwasher.Program.PreRinse": "Vorspülen"
    }
  },
  "native": {},
  "from": "system.adapter.homeconnect.0",
  "user": "system.user.admin",
  "ts": 1638279584925,
  "_id": "homeconnect.0.SIEMENS-SN778X16TE-68A40E00F63E.programs.active.BSH_Common_Root_ActiveProgram"
}

always the property name of the state and not the value is returned. 

So if state value is "Eco 50°C" - I want "Eco 50°C" as value returned and not  Dishcare.Dishwasher.Program.Eco50

**Comment by Apollon77** [comment]
Pleas provide more information what you expect where and how and how used?

1. "common.states" is officially defined ONLY for type number and not for strings
2. "common-states" is just there for visualizations to display more meaningful values to the user in UIs and have no role in set/getState at all!

**Comment by mickym2** [comment]
I know that this is for visualisiation. But I would expect that if I set the property of the multistate object, the value of this property is in the val and not the property name which I use to select the value. 

So it is perfect in admin5 itself - to select the value:

![image](https://user-images.githubusercontent.com/58858526/144682468-da6ed6fa-e9be-4924-8171-8758b2fe2064.png)

and I would expect that I would get those values back in JS or in NodeRed when I ask this multistate. 

Perfekt is - if I want to select with a simple value like on or off - and the value is the value of a property off/on in multistate:

Better example: 
I want to switch in multistate an off or on code:

    "states": {
      "on": "0x0011",
      "off": "0x0010"
    }

If I set the state via node-Red or JS to  "on" - the correct value 0x0011 is displayed in admin5.

So if I set the value to on - in admin the correct value 0X0011 is displayed and I expect that the value of this state is 0x0011.
![image](https://user-images.githubusercontent.com/58858526/144683848-a342b936-1b24-4e74-a656-3c740851e58f.png)

![image](https://user-images.githubusercontent.com/58858526/144684071-9d81f19b-3f8c-4d63-8573-7d6197cd8fac.png)


So I can select between this 2 values. 

![image](https://user-images.githubusercontent.com/58858526/144683737-899aba5a-3070-4b43-966f-a23e40778617.png)

If I do it the other way round - then I need to set value  - the translation is not consistent for me. 

I would expect that I can set the value to "off" and the state would have the value 0x0011. The it works for me perfectly

**Comment by Apollon77** [comment]
As described above tghis is working now as you expect it.

The real value is one thing ... the states array contains kind of an "alias to display instead of real value when user selects". But Written will be the "real value".

So in your in/off exmaple: if the neededvalues are the "number" ones 0x0011/0x0010 and their "meaning " are on/off then your definition needs to be the ther way around and you need to use the real values.

The "states display alternative value" is exactly that

**Comment by Feuer-sturm** [comment]
@mickym2 Please check the new Implementation and please close the issue if everything is fine.

**Comment by mickym2** [comment]
Nothing has been changed - but if it works as designed - i will not follow up further.
