### ISSUE TITLE
Login failure failed connection to socket.io from ::ffff:

### ISSUE THREAD

**Issue by meistermopper** [ioBroker/ioBroker.admin#1223]
Every login causes this message

<html><body>

admin.0 | 2021-12-02 09:26:56.752 | error | error
-- | -- | -- | --
admin.0 | 2021-12-02 09:26:56.752 | error | failed connection to socket.io from ::ffff:192.168.1.10:
admin.0 | 2021-12-02 09:26:56.648 | error | error
admin.0 | 2021-12-02 09:26:56.643 | error | failed connection to socket.io from ::ffff:192.168.1.10:

</body>
</html>

**Versions:**  
 - Adapter version: v5.1.25
 - JS-Controller version: v3.3.21
 - Node version:
 ```/usr/bin/nodejs
v14.18.2
/usr/bin/node
v14.18.2
/usr/bin/npm
6.14.15
nodejs:
  Installiert:           14.18.2-deb-1nodesource1
  Installationskandidat: 14.18.2-deb-1nodesource1
  Versionstabelle:
 *** 14.18.2-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_14.x bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     12.22.5~dfsg-2~11u1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages```
 - Operating system: Debian
 ```Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye```

**Comment by Stonelink77** [comment]
same Problem here with Debian Buster and a Pi4 and those mentionened Adapter, JS-Controller, and Node versions

`<html><body>


error
--
admin.0 | 2021-12-10 16:30:57.644 | error | failed connection to socket.io from ::ffff:192.168.2.202:


</body>
</html>`

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1000

**Comment by baerenwaldfreund** [comment]
Bei mir kommt der Fehler noch immer. Bin ich der Einzige?

**Comment by Feuer-sturm** [comment]
Das weiter referenzierte issue #1000 ist auch noch offen. Dieses issue wurde geschlossen, weil es doppelt ist.
