### ISSUE TITLE
Startproblem with Admin Adapter

### ISSUE THREAD

**Issue by Romawul** [ioBroker/ioBroker.admin#1224]
**Describe the bug**  

If I start the Adapter always the the adapter stops with the same results.  what can I do?
this problem ocured after I tried to update the adapter.

iobroker.admin@5.2.1
socket.io.js:59 [2021-12-04T10:33:48.480Z] Try to connect
socket.io.js:61 [2021-12-04T10:33:51.567Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:33:51.575Z] Start reconnect 0
socket.io.js:59 [2021-12-04T10:33:51.578Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614031578&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:33:51.589Z] Start reconnect 1
socket.io.js:61 [2021-12-04T10:33:51.590Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:33:51.590Z] Reconnect is already running 1
socket.io.js:59 [2021-12-04T10:33:52.590Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614032591&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:33:52.609Z] Start reconnect 2
socket.io.js:61 [2021-12-04T10:33:52.610Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:33:52.611Z] Reconnect is already running 2
socket.io.js:59 [2021-12-04T10:33:54.610Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614034610&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:33:54.617Z] Start reconnect 3
socket.io.js:61 [2021-12-04T10:33:54.618Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:33:54.619Z] Reconnect is already running 3
socket.io.js:59 [2021-12-04T10:33:57.621Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614037621&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:33:57.630Z] Start reconnect 4
socket.io.js:61 [2021-12-04T10:33:57.633Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:33:57.633Z] Reconnect is already running 4
socket.io.js:59 [2021-12-04T10:34:01.632Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614041633&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:34:01.643Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:01.644Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:34:01.644Z] Reconnect is already running 5
main.c7f54a06.chunk.js:2 Cannot getRepositoryCompact: timeout
main.c7f54a06.chunk.js:2 Cannot getInstalled: notConnectedError
window.alert @ main.c7f54a06.chunk.js:2
main.c7f54a06.chunk.js:2 Cannot read adapters: notConnectedError
window.alert @ main.c7f54a06.chunk.js:2
2main.c7f54a06.chunk.js:2 [ADAPTERS] Cannot compare "" and "3.2.16"
value @ main.c7f54a06.chunk.js:2
13.76eaf746.chunk.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
5.11c30091.chunk.js:2 Uncaught (in promise) notConnectedError
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
no-image.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
5.11c30091.chunk.js:2 ChunkLoadError: Loading chunk 13 failed.
(error: http://192.168.178.55:8081/static/js/13.76eaf746.chunk.js)
    at Function.u.e (192.168.178.55/:1)
    at main.c7f54a06.chunk.js:2
    at V (5.11c30091.chunk.js:2)
    at Zi (5.11c30091.chunk.js:2)
    at jl (5.11c30091.chunk.js:2)
    at Sl (5.11c30091.chunk.js:2)
    at Cl (5.11c30091.chunk.js:2)
    at zl (5.11c30091.chunk.js:2)
    at 5.11c30091.chunk.js:2
    at t.unstable_runWithPriority (5.11c30091.chunk.js:2)
ui @ 5.11c30091.chunk.js:2
browserError.png:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.c7f54a06.chunk.js:2 Cannot get logs: notConnectedError
window.alert @ main.c7f54a06.chunk.js:2
socket.io.js:59 [2021-12-04T10:34:06.644Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614046644&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:34:06.651Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:06.652Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:34:06.652Z] Reconnect is already running 5
:8081/#tab-intro:1 Uncaught (in promise) notConnectedError
200main.c7f54a06.chunk.js:2 notConnectedError
(anonymous) @ main.c7f54a06.chunk.js:2
socket.io.js:59 [2021-12-04T10:34:11.652Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614051652&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
socket.io.js:59 [2021-12-04T10:34:11.661Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:11.661Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.io.js:59 [2021-12-04T10:34:11.662Z] Reconnect is already running 5
socket.io.js:59 [2021-12-04T10:34:16.661Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614056662&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
(anonymous) @ socket.io.js:372
socket.io.js:59 [2021-12-04T10:34:16.677Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:16.678Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:128
socket.io.js:59 [2021-12-04T10:34:16.679Z] Reconnect is already running 5
DevTools failed to load source map: Could not load content for http://192.168.178.55:8081/lib/js/sparkline.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load source map: Could not load content for http://192.168.178.55:8081/static/js/5.11c30091.chunk.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load source map: Could not load content for http://192.168.178.55:8081/static/js/main.c7f54a06.chunk.js.map: Connection error: net::ERR_CONNECTION_REFUSED
socket.io.js:59 [2021-12-04T10:34:21.678Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614061679&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
(anonymous) @ socket.io.js:372
socket.io.js:59 [2021-12-04T10:34:21.686Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:21.687Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:128
socket.io.js:59 [2021-12-04T10:34:21.687Z] Reconnect is already running 5
socket.io.js:59 [2021-12-04T10:34:26.688Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614066690&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
(anonymous) @ socket.io.js:372
socket.io.js:59 [2021-12-04T10:34:26.704Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:26.705Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:128
socket.io.js:59 [2021-12-04T10:34:26.707Z] Reconnect is already running 5
socket.io.js:59 [2021-12-04T10:34:31.705Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614071706&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
(anonymous) @ socket.io.js:372
socket.io.js:59 [2021-12-04T10:34:31.719Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:31.720Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:128
socket.io.js:59 [2021-12-04T10:34:31.721Z] Reconnect is already running 5
socket.io.js:59 [2021-12-04T10:34:36.721Z] Try to connect
socket.io.js:91 WebSocket connection to 'ws://192.168.178.55:8081/?sid=1638614076723&name=admin' failed: 
SocketClient.connect @ socket.io.js:91
(anonymous) @ socket.io.js:372
socket.io.js:59 [2021-12-04T10:34:36.744Z] Start reconnect 5
socket.io.js:61 [2021-12-04T10:34:36.747Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:128
socket.io.js:59 [2021-12-04T10:34:36.748Z] Reconnect is already running 5
socket.io.js:59 [2021-12-04T10:34:41.746Z] Try to connect
**Describe the bug**

**Comment by GermanBluefox** [comment]
May be your system is overloaded?
