### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Walter-62** [ioBroker/ioBroker.admin#1226]
![grafik](https://user-images.githubusercontent.com/95735474/145157848-f807091c-4765-44f9-8c26-fed829208a00.png)

**Comment by Hedgehog61** [comment]
> ![grafik](https://user-images.githubusercontent.com/95735474/145157848-f807091c-4765-44f9-8c26-fed829208a00.png)

Hello, i think you can Fix the Problem by updating the Admin to Version 5.1.28 or higher. This is not a stable version, but it fixes the Problem.

**Comment by GermanBluefox** [comment]
Sorry. No debug data found. Can't do anything
