### ISSUE TITLE
Der Reiter Javascriptzeigt nichts an

### ISSUE THREAD

**Issue by EtzeSte13** [ioBroker/ioBroker.admin#1227]
**Describe the bug**  
Der Reiter JavaScript im Admin Adapter wird nicht angezeigt. Die gespeicherten Skripts laufen aber es gibt nur keine Möglichkeit diese zu editieren.

**To Reproduce**  
1. Ich weiß nicht wie ich das reprodizieren kann, ich würde es gerne weg haben. Bei mir ist es auf einmal gekommen. Ich habe ein Backup aufgespielt, dann ist es kurz gegangen und beim 2ten Versuch die Skipts zu laden zeigte sich der Fehler. 
2. genaue Daten sind in folgenden Thread zu sehen. 
3. https://forum.iobroker.net/topic/50112/der-skritpe-reiter-wird-nicht-mehr-angezeigt/15?_=1639050777754

Was habe ich bereits getan:

-) komplettes upgrade inkl js controller
-) Iobroker fixer laufen lassen
-) neu gestartet
-) Admin downgraden
-) JS-Adapter downgraden, deinstallieren und wieder neu installieren, auf einen Slave geschoben und wieder zurück.... mehr ist mir nicht mehr eingefallen.
-) folgende Installationsdaten:
Raspi 4 4GB als Master und 2 RasPi3B als slaves

**Expected behavior**  
Wäre schön wenn der Reiter wieder sichtbar wird

**Screenshots & Logfiles**  
Systemumfeld:
![grafik](https://user-images.githubusercontent.com/73318503/145610261-27db9951-eb8c-4a52-993b-857e6a555c4f.png)
Fehlerbild
![grafik](https://user-images.githubusercontent.com/73318503/145610716-9c71be07-455e-433d-b948-26c9ed085c98.png)
Konsole vom Firefox bei F12
![grafik](https://user-images.githubusercontent.com/73318503/145610499-0f876ed1-49c0-4358-8860-ca1d0019c5d3.png)
![grafik](https://user-images.githubusercontent.com/73318503/145610556-aa576e1f-9c32-41ee-b6d4-7605a3b84c9b.png)
![grafik](https://user-images.githubusercontent.com/73318503/145610576-6afa56da-f60c-42c9-90d2-d02470eb8d81.png)

**Versions:**  
Node.JS: V14.18.2
NPM: 6.14.15
Admin 5.1.25
JS-Adapter  5.2.13

**Comment by EtzeSte13** [comment]
Das Problem konnte in der Zwischenzeit durch einspielen eines noch älteren Backups behoben werden. Ursache konnte ich nicht herleiten. mfG Etze

**Comment by xnetworker** [comment]
Ich habe das gleiche Problem und kann nicht auf ein älteres Backup zurückgreifen, da ich alles neu installiert habe. 

Versions:
Node.JS: V14.18.1
NPM: 6.14.15
Admin 5.1.25
JS-Adapter 5.2.13

Fehlermeldung erhalte ich keine in der Konsole wenn ich auf Skripte klicke
