### ISSUE TITLE
Master / Slave wrong number of processes

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.admin#1229]
**Describe the bug**  
Slave / Master shows under Instances wrong number of processes.
For Master and Slave the same amount of processes are shown. Also under the Tab HOSTS !

**Expected behavior**  
It should show only the number of processes that is running on Master or Slave

**Versions:**  
 - Adapter version: admin 5.1.25
 - JS-Controller version: <js-controller-version>  3.3.21
 - Node version: <node-version> v14.18.1
 - Operating system: bullseye

**Comment by GermanBluefox** [comment]
Please test with 6.0.6

**Comment by Feuer-sturm** [comment]
@GermanBluefox Checked with Admin 6.1.2 but the problem is still the same. The number of processes does not change if I change the host.
