### ISSUE TITLE
Sprache bei Neuinstallation wird nicht übernommen

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#1230]
Wenn man ioBroker zum ersten Mal installiert, wird die ausgewählte Sprache nicht in den Einstellungen gespeichert. Wenn man die Einstellungen danach öffnet, ist das Feld immer leer. Wenn man es dann wieder ändert, dann leibt es gespeichert.
<img width="544" alt="Unbenannt" src="https://user-images.githubusercontent.com/9552828/146423029-9150a232-0237-43f1-94cd-6c7d9a8844be.PNG">
<img width="954" alt="Unbenannt2" src="https://user-images.githubusercontent.com/9552828/146423040-045d9c3b-0270-4f74-8db2-dc5a88f87f19.PNG">

**Comment by Feuer-sturm** [comment]
Issue ist identisch zu diesem hier https://github.com/ioBroker/ioBroker.admin/issues/1175
