### ISSUE TITLE
Allow deletion of custom data when deleting instances/adapters

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1233]
With js-controller 4.0  it is possible to delete the custom data of an instance when this instance is deleted (or the adapter). This is done by adding "--custom" to the CLI command.

Admin should check if an adapter uses Custom data and provide (if also controller support it - there is a feature flag) a checkbox (default unchecked) to also remove custom data when deleting the instance.

**Comment by Apollon77** [comment]
Feature flag see https://github.com/ioBroker/ioBroker.js-controller/commit/914239469d00114f47ff71d5b3fe2c04679c295d

**Comment by GermanBluefox** [comment]
Implemented in 5.2.4

**Comment by Apollon77** [comment]
related to #1707

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172638050-50f6c1d8-4989-4b7d-b72a-5de3e81fcbf5.png)
