### ISSUE TITLE
Fehler bei de Installation 

### ISSUE THREAD

**Issue by Patrick-Walther** [ioBroker/ioBroker.admin#1236]
Hallo,

Nach der  Installation auf einem Rpi 3 (Installations Befehle von der Iobroker Hompage) kommen folgende Fehlermeldungen.Siehe Bilder.
![Screenshot_2021-12-20-14-13-20-693_com android chrome](https://user-images.githubusercontent.com/76852173/146772836-1ccb4b21-83f0-497d-b578-0bb7ccb65339.jpg)
![Screenshot_2021-12-20-14-12-42-529_com android chrome](https://user-images.githubusercontent.com/76852173/146772852-53679cd3-6078-4614-bead-5c76616dc71c.jpg)

**Comment by vonCartman** [comment]
ich habe den gleichen problem.
Allerdings habe ich RPI  4er

**Comment by Yavieh** [comment]
Ich habe das gleiche Problem. 
Nutze Iobroker als Docker auf Unraid.

**Comment by Yavieh** [comment]
Okay ich habs gelöst. 
Ich habe in einem Docker image folgendes gemacht:
in opt/iobroker:
> iobroker stop
> npm update
> iobroker start

**Comment by sid684** [comment]
solve the problem for me. thx!

**Comment by GermanBluefox** [comment]
Sorry, I do not understand what is broken
