### ISSUE TITLE
Admin 5.2.x seems to have issues with js.controler 3.2?

### ISSUE THREAD

**Issue by llDarkSoull** [ioBroker/ioBroker.admin#1237]
After the installation of the latest admin i can't connect to the iobroker
Message:
Loading chunk 13 failed. (error: http://192.168.1.25:8081/static/js/13.76eaf746.chunk.js)
[failure.txt](https://github.com/ioBroker/ioBroker.admin/files/7747197/failure.txt)

**Comment by GRaptor** [comment]
Same here, same message (well, different server name ;-) )

**Comment by JensSuessmeyer** [comment]
Me too...

Firefox kann keine Verbindung zu dem Server unter ws://192.168.178.45:8081/?sid=1640072983909&name=admin aufbauen.

which is the corrct server name I am using.

**Comment by steinhuegel** [comment]
Selbes Problem auch auf meinem Raspi4 nach dem Admin Update.

**Comment by GRaptor** [comment]
Okay, found the issue (at least worked for me):

Checked by CLI the installed js-controller version:
`iobroker update` (fyi, doesn't really update anything, just shows the installed and the available versions)

For me, it showed for the js-controller:
`Controller "js-controller" : 3.3.21   , installed 3.2.16 [Updateable]`

so I updated the controller:
`iobroker stop
iobroker upgrade self`

now, everthing is back to normal :-)

Hope that helps!

**Comment by steinhuegel** [comment]
Perfect!

Controller "js-controller" : 3.3.21   , installed 3.2.16 [Updateable]
iobroker  upgrade self 

100% sucess

**Comment by Apollon77** [comment]
@GermanBluefox is Admin 5.2 requiring somehow js-controller 3.3? If yes we need to update the controller dep in Admin
