### ISSUE TITLE
Error when looking at chart of influxdb/history/sql stored history

### ISSUE THREAD

**Issue by latzi0710** [ioBroker/ioBroker.admin#1242]
when a chart of a datapoint, stored in influxdb, is chosen the following error occures:
`react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)`
The history of values can be displayed without any problem

**Versions:**  
 - Admin Adapter version: 5.2.2
 - JS-Controller version: 3.3.22
 - Influx Adapter version: 2.4.0
 - InfluxDB version: 2.1.1
 - Node version: 14.18.2
 - Operating system: Multihost, influxdb on slave debian v10; master raspberry4

**Comment by wojtzyk** [comment]
I have the same error, when a chart of a datapoint, stored in influxdb, is chosen:
react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)

Versions:
Admin Adapter version: 5.2.2
JS-Controller version: 3.3.22
Node version: 14.18.2
Operating system: Raspbian v11; raspberry pi 4

**Comment by DevYves89** [comment]
Same with my setup. When i access the diagram in a mqtt datapoint.


<img width="556" alt="Bildschirmfoto 2021-12-22 um 17 43 47" src="https://user-images.githubusercontent.com/46921238/147126857-973ca5fe-88ff-4666-9f1b-5b266cf5323d.png">

**Comment by micw421** [comment]
Same error with history adapter since I have upgraded iobroker today.
I cannot access the values or the chart.

**Comment by LPTR72** [comment]
![image](https://user-images.githubusercontent.com/96550014/147155382-254de4ec-e918-4069-8d78-d8b3f1249660.png)

Same for me if I try to open a History char.

Versions:
Admin Adapter version: 5.2.2
JS-Controller version: 3.3.22
Node version: 14.18.2
Raspbian bullseye; raspberry pi 4

**Comment by frendhomeio** [comment]
![image](https://user-images.githubusercontent.com/64314557/147207817-fe83175f-9aaf-4092-ac8f-ea27ec88610f.png)

**Comment by funky4t** [comment]
Same here, set up an alias, added it to influxdb, clicked on history diagram, error occurred. Now error occurs whenever I click on the config wheel of the dp. Not even values table is accessible anymore.

<img width="1438" alt="Bildschirmfoto 2021-12-23 um 13 16 26" src="https://user-images.githubusercontent.com/57875762/147240138-9e427f4e-fe56-4e43-892f-ef5bb76c511b.png">

Versions:
Admin Adapter version: 5.2.2
JS-Controller version: 3.3.22
Node version: v12.22.8
Ubuntu 20.4 als VM auf Proxmox NUC

**Comment by GermanBluefox** [comment]
Fixed in 5.2.3

**Comment by LPTR72** [comment]
Es funktioniert nach Update auf 5.2.3 wieder.

Vielen Dank and denjenigen (diejenigen), die es selbst über die Feiertage möglich gemacht haben!

**Comment by Feuer-sturm** [comment]
@Apollon77 I think you can close this issue.
