### ISSUE TITLE
Beim Versuch ein Diagramm von in sql.0 gespeicherten Daten aufzurufen

### ISSUE THREAD

**Issue by Linustrispoke** [ioBroker/ioBroker.admin#1244]
TypeError: o.getHours is not a function
    s ObjectChart.js:160
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 13
    e index.js:22
    1431 index.js:85
    f (index):1
    r (index):1
    t (index):1
    <anonymous> main.c7b7bd97.chunk.js:2

**Comment by Linustrispoke** [comment]
Jeder weitere Versuch endet immer wieder hier ....

**Comment by Linustrispoke** [comment]
Jeder weitere Versuch endet immer wieder in diesem Fehler

**Comment by HyperPollok** [comment]
Habe den selben Fehler wohl durch den History Adapter.
![image](https://user-images.githubusercontent.com/24475893/147257382-61d256d8-b34d-48ef-9838-514e16845769.png)

Ist reproduzierbar mit der Aktivierung der Historie auf einem Object 
![image](https://user-images.githubusercontent.com/24475893/147256593-66841e8a-d1bc-40ae-9934-4ef6f7bdeca8.png)

Nach dem zurücksetzen der Historie funktioniert der Object-Editor wieder.

TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)

![image](https://user-images.githubusercontent.com/24475893/147257755-ee056eaf-8934-4e4e-af8f-f6b1c2ce4a17.png)

**Comment by Apollon77** [comment]
duplicate #1242
