### ISSUE TITLE
Error in GUI 

### ISSUE THREAD

**Issue by RSScheible** [ioBroker/ioBroker.admin#1245]
Hi, 

the following bug appears since yesterday. For information: My host and the adapters are all on the latest versions.

I wanted to check the sql history of objects of my modbus adapter. The program terminates immediately with a message "error in GUI".  The same error happens with objects from other adapters (like knx) as well.  

I copied the text from the console here.  I hope that helps.

best regards 

Rolf-Stefan

iobroker.admin@5.2.2
socket.io.js:59 [2021-12-23T11:44:18.001Z] Try to connect
Instances.js:444 getInstances: 52
Instances.js:444 getInstances: 1
App.js:1406 Execute: del sql.0
Command.js:61 STARTED: del sql.0
9Command.js:128 cmdStdout
Instances.js:444 getInstances: 1
Command.js:128 cmdStdout
Command.js:91 timeout
Command.js:173 cmdExit
Command.js:174 189729331
Command.js:175 0
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:654 [ADAPTERS] getAdaptersInfo
3Adapters.js:1466 [ADAPTERS] Render
Adapters.js:447 [ADAPTERS] getAdapters
2Adapters.js:1466 [ADAPTERS] Render
Adapters.js:654 [ADAPTERS] getAdaptersInfo
2Adapters.js:1466 [ADAPTERS] Render
App.js:618 Repo updated!
6Adapters.js:1466 [ADAPTERS] Render
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:654 [ADAPTERS] getAdaptersInfo
5Adapters.js:1466 [ADAPTERS] Render
:8081/adapter/simple-api/simple-api.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/socketio/socketio.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
2Adapters.js:1466 [ADAPTERS] Render
App.js:1406 Execute: add sql auto --host raspberrypi 
Adapters.js:1466 [ADAPTERS] Render
Command.js:61 STARTED: add sql auto --host raspberrypi 
Adapters.js:1466 [ADAPTERS] Render
19Command.js:128 cmdStdout
2Adapters.js:1466 [ADAPTERS] Render
Command.js:173 cmdExit
Command.js:174 44665985
Command.js:175 0
2Adapters.js:1466 [ADAPTERS] Render
Command.js:91 timeout
Instances.js:444 getInstances: 6
index.js:116 Cannot find i18n for sql / 
(anonymous) @ index.js:116
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
App.js:271 Ok
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
index.js:116 Cannot find i18n for sql / 
(anonymous) @ index.js:116
i18n.js:106 Translate: DB settings
i18n.js:106 Translate: Default settings
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Write NULL values on start/stop boundaries
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
i18n.js:106 Translate: DB Type
i18n.js:106 Translate: File for sqlite
i18n.js:106 Translate: Input path with the file name.
i18n.js:106 Translate: requestInterval
i18n.js:106 Translate: Test connection
i18n.js:106 Translate: Reset DB
ObjectBrowser.js:2317 + subscribe 0_userdata.0.example_state
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Aktuelle_Temperatur_PS
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Max_Temperatur_PS
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Min_Temperatur_PS
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP61
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP62
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Max
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Min
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temperatur
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E61
ObjectBrowser.js:2317 + subscribe knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E62
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40001_Identification_Magicbyte
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40002_Modbus_Firmware
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40004_Hersteller
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40020_Modell
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40036_Seriennummer
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40052_Firmware
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40068_PV_Leistung
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40070_Batterie_Leistung
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40072_Hausverbrauch_Leistung
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40074_Netz_Leistung
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40076_Zusätzlicher_Einspeiser
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40082_Autarkie_Eigenverbrauch
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40083_Batterie_SOC
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40084_Emergency_Power_Status
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40085_EMS_Status
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40096_DC_String_1_Voltage
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40097_DC_String_2_Voltage
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40098_DC_String_3_Voltage
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40099_DC_String_1_Current
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40100_DC_String_2_Current
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40101_DC_String_3_Current
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40102_DC_String_1_Power
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40103_DC_String_2_Power
ObjectBrowser.js:2317 + subscribe modbus.0.holdingRegisters.40104_DC_String_3_Power
ObjectBrowser.js:2158 > stateChange 0_userdata.0.example_state
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Aktuelle_Temperatur_PS
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Max_Temperatur_PS
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Min_Temperatur_PS
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP61
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP62
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Max
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Min
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temperatur
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E61
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E62
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40001_Identification_Magicbyte
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40002_Modbus_Firmware
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40004_Hersteller
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40020_Modell
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40036_Seriennummer
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40052_Firmware
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40068_PV_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40070_Batterie_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40072_Hausverbrauch_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40074_Netz_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40076_Zusätzlicher_Einspeiser
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40082_Autarkie_Eigenverbrauch
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40083_Batterie_SOC
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40084_Emergency_Power_Status
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40085_EMS_Status
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40096_DC_String_1_Voltage
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40097_DC_String_2_Voltage
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40098_DC_String_3_Voltage
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40099_DC_String_1_Current
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40100_DC_String_2_Current
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40101_DC_String_3_Current
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40102_DC_String_1_Power
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40103_DC_String_2_Power
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40104_DC_String_3_Power
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40068_PV_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40072_Hausverbrauch_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40074_Netz_Leistung
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40076_Zusätzlicher_Einspeiser
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40097_DC_String_2_Voltage
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40099_DC_String_1_Current
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40100_DC_String_2_Current
ObjectBrowser.js:2158 > stateChange modbus.0.holdingRegisters.40103_DC_String_2_Power
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP62
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E62
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP61
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E61
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP62
ObjectBrowser.js:2158 > stateChange knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E62
react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
ui @ react-dom.production.min.js:216
ObjectBrowser.js:1809 - unsubscribe 0_userdata.0.example_state
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Aktuelle_Temperatur_PS
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Max_Temperatur_PS
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Pufferspeicher.Min_Temperatur_PS
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP61
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.Status_WP62
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Max
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temp_Min
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Status_Wärmepumpe.WP_Temperatur
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E61
ObjectBrowser.js:1809 - unsubscribe knx.0.PV_Anlage_und_Wärmepumpe_.Wärmepumpe.WP_E62
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40001_Identification_Magicbyte
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40002_Modbus_Firmware
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40004_Hersteller
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40020_Modell
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40036_Seriennummer
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40052_Firmware
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40068_PV_Leistung
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40070_Batterie_Leistung
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40072_Hausverbrauch_Leistung
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40074_Netz_Leistung
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40076_Zusätzlicher_Einspeiser
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40082_Autarkie_Eigenverbrauch
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40083_Batterie_SOC
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40084_Emergency_Power_Status
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40085_EMS_Status
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40096_DC_String_1_Voltage
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40097_DC_String_2_Voltage
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40098_DC_String_3_Voltage
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40099_DC_String_1_Current
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40100_DC_String_2_Current
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40101_DC_String_3_Current
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40102_DC_String_1_Power
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40103_DC_String_2_Power
ObjectBrowser.js:1809 - unsubscribe modbus.0.holdingRegisters.40104_DC_String_3_Power

**Comment by Apollon77** [comment]
duplicate #1242
