### ISSUE TITLE
Fehler in der GUI

### ISSUE THREAD

**Issue by 08041965** [ioBroker/ioBroker.admin#1247]
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (:8081/static/js/15.604fadf3.chunk.js:1)
    at zc (5.041e7077.chunk.js:2)
    at Uo (5.041e7077.chunk.js:2)
    at Zi (5.041e7077.chunk.js:2)
    at jl (5.041e7077.chunk.js:2)
    at Sl (5.041e7077.chunk.js:2)
    at Cl (5.041e7077.chunk.js:2)
    at zl (5.041e7077.chunk.js:2)
    at 5.041e7077.chunk.js:2
    at t.unstable_runWithPriority (5.041e7077.chunk.js:2)

der Sonoff Datenpunkt läst sich nicht bearbeiten

**Comment by ElRedef** [comment]
Hey,

selbes Thema seit dem Admin Update 5.2.2

Fehler kommt wenn mann auf den Zahnradkopf eines Datenpunktes drückt. 

![error_in_gui](https://user-images.githubusercontent.com/66745270/147269490-35c1c21d-c77f-4447-b7e1-486960ce0289.JPG)
![info](https://user-images.githubusercontent.com/66745270/147269626-d0ecbf75-76e2-4cda-8a90-6bc222ea2937.JPG)
.

**Comment by rimhaeuser** [comment]
Same by me. Rolling back to Admin-Version 5.2.1. and all is ok
js-controller Version is on 3.3.22
Error is only upcomming if the datapoint is stored in History (i use an extern mariadb)

**Comment by Apollon77** [comment]
duplicate #1242
