### ISSUE TITLE
Bug after Admin update

### ISSUE THREAD

**Issue by Erdnusschokolade** [ioBroker/ioBroker.admin#1249]
Found this bug after updating admin it appeared once i tried to open the Diagramm view of a state in History
`TypeError: o.getHours is not a function
    s ObjectChart.js:160
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value ObjectBrowser.js:1709
react-dom.production.min.js:216:199
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value ObjectBrowser.js:1709
`
![Unbenannt1](https://user-images.githubusercontent.com/96622762/147355287-36dad9fe-b350-48b1-a3c0-1d5b7241788e.png)
![Unbenannt](https://user-images.githubusercontent.com/96622762/147355289-f5572af1-53bb-4d32-8c1d-bb817714833d.png)

**Comment by GermanBluefox** [comment]
Please update to 5.2.3
