### ISSUE TITLE
Error in Gui

### ISSUE THREAD

**Issue by atoerschen** [ioBroker/ioBroker.admin#1250]
Hello all,

This error occurs in IOBROKER 5.2.2. when i try to click on the gear wheel icon under objects.

i don't know where this get.hours' is coming from? i was able to open the gear wheel a few days ago without problems

**To Reproduce**  
1. Go to 'objects.'
2. Click on 'gearwheel'

**Expected behavior**  
open the settings of influx.db /telegram for each specific object.

**Screenshots & Logfiles**  

react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
**Versions:**  
Standard repository : Stable (default)
 - Adapter version: <adapter-version>
 - JS-Controller version: <3.3.22> 
 - Node version: <v14.18.2> 
 - Operating system: <Linux raspberrypi 5.10.63-v7l>

**Additional context**  
i have also no influx-DB values in Grafana anymore before 23.12.2021 09:15, but i cannot check in Influx DB because the error above occurs.

Best regards,

Andreas Toerschen

**Comment by DominikReber** [comment]
Exactly the same happening to me on inflix.db/telegram since I updated to JS-Controller 3.3.22 and Iobroker 5.2.2.
![image](https://user-images.githubusercontent.com/63448986/147391416-305eaee0-63f9-4f05-beb0-7b23d010e188.png)

**Comment by EagleeyeKai** [comment]
I got also exactly the same problem like user "atoerschen":

<img width="812" alt="Bildschirmfoto 2021-12-26 um 00 12 49" src="https://user-images.githubusercontent.com/46163221/147395283-1494c559-76cd-4430-aa7f-e5ae8be8a8c2.png">

**Comment by Apollon77** [comment]
is already fixed in 5.2.3 (currently in beta)

**Comment by DominikReber** [comment]
Perfect, as it's currently impossible to deactivate/change influx as soon as it has been activated.

**Comment by GermanBluefox** [comment]
Please use 5.2.3
