### ISSUE TITLE
Error storing values in sql

### ISSUE THREAD

**Issue by RandyAndy1** [ioBroker/ioBroker.admin#1251]
I tried to create a new sql dataset in userdef. setting in objects. and the system crashed.
This is the error code generated in console:

TypeError: o.getHours is not a function
    s ObjectChart.js:160
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value ObjectBrowser.js:1709
    promise callback*value ObjectBrowser.js:1688
    value ObjectBrowser.js:1785
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    F scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    EventHandlerNonNull* scheduler.production.min.js:12
    f (index):1
    <anonymous> index.js:4
    f (index):1
    <anonymous> React
    f (index):1
    <anonymous> React
    f (index):1
    1431 main.c7b7bd97.chunk.js:2
    f (index):1
    r (index):1
    t (index):1
    <anonymous> main.c7b7bd97.chunk.js:2

**Comment by RandyAndy1** [comment]
Seems to be solved with the latest release from Dec. 25th

**Comment by Apollon77** [comment]
yes, solved by 5.2.3
