### ISSUE TITLE
Error in GUI o.getHours is not a function

### ISSUE THREAD

**Issue by Fiiti** [ioBroker/ioBroker.admin#1254]
**Describe the bug**  
Appears at click on the gear of the HM-rega Duty Cycle Object and then on the Diagram.
I am saving the DC into SQl Database and would look on a chart about it.

After this first error, it now appears directly if I click on the gear of the DC. I cannot see the dialog of the data store screen.
On other objects I get the data store screen.   

**Additional context**  
s@http://192.168.1.203:8081/static/js/15.604fadf3.chunk.js:1:54837function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}zc@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5611029function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Uo@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5630495function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Zi@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5674028function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}jl@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5660198function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Sl@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5660126function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Cl@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5659987function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}zl@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5656953function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Ka/<@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5606447function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}t.unstable_runWithPriority@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5689657function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Ga@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5606224function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Ka@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5606394function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Za@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5606327function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}ke@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5677494function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}Yt@http://192.168.1.203:8081/static/js/5.041e7077.chunk.js:2:5584947function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}

![image](https://user-images.githubusercontent.com/25975978/147406910-cc53a0a8-ae47-43d1-9ae5-2f1d09d86cd1.png)

**Comment by GermanBluefox** [comment]
Please use 5.2.3
