### ISSUE TITLE
Absturz beim Hinzufügen eines dritten Broadlink Adapters. Objektordner wird nicht angelegt

### ISSUE THREAD

**Issue by as38259** [ioBroker/ioBroker.admin#1259]
Hallo, 
ich benötige Hilfe da ich nicht weiter weiß und bedanke mich jetzt schonmal im Vorraus!

Es sind bereits lange 2 Broadlink im Einsatz und funktionieren ohne Probleme.
Jetzt wollte ich einen dritten Broadlink Mini installieren.

Nach Installation der Adapter wird KEIN Objektordner für die neue Instanz erstellt.
Der RM3 ist im Status mit dem Host verbunden. Lebenszeichen auch vorhanden.
Leider streikt dann Iobroker im Edge Browser nach ein paar Sekunden. (Im Firefox stürzt er nicht ab)

Zuerst dachte ich das es an der Broadlink RM Version liegt und hatte den zuerst erworbenen RM4 MINI
nach Misserfolg gegen einen RM3 Mini getauscht. Aber auch hier das gleiche Problem.
Habe beide verfügbaren Broadlink Adapter versucht. Nichts zu machen.

Kann mir jemand einen Tipp geben wie ich ohne großen Aufriss die Kuh vom Eis bekomme?

Gruß Andreas

Protokoll:

iobroker.admin@5.2.1
socket.io.js:59 [2021-12-30T22:34:57.277Z] Try to connect
VM8155:317 
        
       edge Translation started
translateInternal @ VM8155:317
translate @ VM8155:493
(anonym) @ VM8158:1
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.alive
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.compactMode
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.connected
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.cpu
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.cputime
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.eventLoopLag
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.inputCount
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.logLevel
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.memHeapTotal
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.memHeapUsed
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.memRss
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.outputCount
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.sigKill
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.2.uptime
ObjectBrowser.js:2317 + subscribe system.adapter.broadlink.upload
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.alive
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.compactMode
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.connected
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.cpu
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.cputime
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.eventLoopLag
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.inputCount
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.logLevel
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.memHeapTotal
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.memHeapUsed
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.memRss
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.outputCount
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.sigKill
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.2.uptime
ObjectBrowser.js:2158 > stateChange system.adapter.broadlink.upload

>>AB HIER ROT<<
**18react-dom.production.min.js:216 
        
       DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _i (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5653795)
    at Tl (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5665585)
    at t.unstable_runWithPriority (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5692108)
    at Ga (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5608675)
    at xl (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5663543)
    at zl (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5659629)
    at http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5608898
    at t.unstable_runWithPriority (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5692108)
    at Ga (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5608675)
    at Ka (http://192.168.178.113:8081/static/js/5.11c30091.chunk.js:2:5608843)**
  >>BIS HIER ROT<<   
    
    - unsubscribe system.adapter.broadlink.2.alive
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.compactMode
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.connected
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.cpu
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.cputime
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.eventLoopLag
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.inputCount
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.logLevel
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.memHeapTotal
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.memHeapUsed
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.memRss
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.outputCount
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.sigKill
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.2.uptime
ObjectBrowser.js:1809 - unsubscribe system.adapter.broadlink.upload

broadlink.2 | 22632 | 2021-12-30 23:25:35.135 | warnen | Keine IP-Adresse gefunden. Bitte in der Konfiguration einstellen.
-- | -- | -- | -- | --
host.iobroker-as |   | 2021-12-30 23:25:01.588 | fehler | instanzsystem.adapter.broadlink2.0 wurde auf anforderung der instanz selbst beendet und wird nicht neu gestartet, bevor der benutzer sie neu startet.

**Comment by Apollon77** [comment]
Ok, fangen wir doch hier an

> Nach Installation der Adapter wird KEIN Objektordner für die neue Instanz erstellt.

Wie ist der Adapter erstellt worden? Vom Github? hast du ggf manuell eine instanz erstellt?

**Comment by as38259** [comment]
Ganz normal unter Adapter den **Broadlink (RM3) Adapter** eine weitere Instans hinzugefügt und nach installation nur die IP des Gerätes eingetragen.
![1](https://user-images.githubusercontent.com/96891711/147819996-6a0735c9-d097-4142-aa1c-8107dfeec332.JPG)

![2](https://user-images.githubusercontent.com/96891711/147820086-9f36877b-e9b7-4fd5-a54e-ac271944a37c.JPG)

![3](https://user-images.githubusercontent.com/96891711/147820130-703443ad-b580-4e2f-a6c4-84fab138e5b3.JPG)

![4](https://user-images.githubusercontent.com/96891711/147820179-222a7180-7188-4ce9-81b1-61342f157c8c.JPG)



Systeminformationen

Plattform     linux
Betriebssystem     linux
Architektur     arm
CPUs  4
Geschwindigkeit  1200 MHz
Modell     ARMv7 Processor rev 4 (v7l)
RAM     926.08 MB
Node.js     v14.18.2
NPM     6.14.15
Datenträgergröße     14.54 GB
freier Festplattenspeicher 7.08 GB
Anzahl der Adapter     362
Aktive Instanzen     17

**Comment by as38259** [comment]
Wenn ich den Broadlink 2 Adapter von Github installiere wird mir keine Instanz angezeigt und ich bekomme folgenden Install Log:

![5](https://user-images.githubusercontent.com/96891711/147820954-bd9a5a1f-b4a6-4aab-80b2-85e265df1194.JPG)

**Comment by Apollon77** [comment]
Hm ... Erster vrsuch ist kein crash. Da gabs Warnungen beim install des Adapters weil bei einem andweren adapter die canvas Library genutzt wird und da wohl ein Debuan paket fehlt. Also irelevant hier

Zweites weist darauf hin das entweder kein "git" installiert ist oder irgendwas mit deiner nodejs installation nicht passt.

Bitte mal `iobroker fix` ausführen udn nochmal versuchen - aber wie gessagt der erste Befehl war ok!!

Neue instanz über das "+" unter "Adapter"

**Comment by as38259** [comment]
Hallo und frohes Neues!

"iobroker fix" durchgeführt.
Instanz neu installiert. ---> Keine Fehlermeldung... nur der Hinweis: "No IP-Address found. Please set in configuration"
 obwohl die IP das RM3 aber stimmt und sich auch anpingen lässt.
 
IP von bestehendem Broadlink parallel eingetragen. Objektordner wurde daraufhin erstellt.
Dann habe ich die IP wieder geändert und alles scheint ok. zu sein.

Werde später versuchen ob das Anlernen der Signale funktioniert und melde mich nochmal.

Erstmal dickes DANKESCHÖN!

**Comment by as38259** [comment]
THX! LÄUFT!
