### ISSUE TITLE
Reusability: move JsonConfigComponent to adapter-react

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.admin#1260]
**Is your feature request related to a problem? Please describe.**

When working on the new common "Device Manager" (a list of all devices within all supporting adapters), I wanted to reuse [JsonConfigComponent](https://github.com/ioBroker/ioBroker.admin/tree/master/src-rx/src/components/JsonConfigComponent). Unfortunately it is inside ioBroker.admin and it's also not really reusable because it needs a lot of parameters that are specific to the adapter configuration (or object commons).

**Describe the solution you'd like**
Ideally, JsonConfigComponent would be in adapter-react and could be used by any adapter in both JavaScript and Typescript (typings would be mandatory).

**Describe alternatives you've considered**
I copied the entire source code to my (test) project and got it mostly working, but that's not the way we should share code in ioBroker!

**Comment by GermanBluefox** [comment]
Done
