### ISSUE TITLE
Objektansicht Datenpunkt Einstellungen Zahnradfarbe blau statt grau

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.admin#1261]
Admin 5

In der Objektansicht lässt sich schwer der Unterschied erkennen ob bei einem Datenpunkt Einstellungen vorgenommen wurden (Zahnradfarbe blau statt grau). Könnte das nicht etwas Kontrastreicher gestaltet werden? zB Rot statt Blau

**Comment by Feuer-sturm** [comment]
Oder das Grün welches für den Expertenmodus schon verwendet wird, dann hätte man nicht noch eine weitere Farbe in der Oberfläche.

**Comment by GermanBluefox** [comment]
Changed in 6.0.1
