### ISSUE TITLE
ioBroker main page can not open.

### ISSUE THREAD

**Issue by oHero** [ioBroker/ioBroker.admin#1264]
**Describe the bug**  
ioBroker is crashed, after the trying to open it.

[2022-01-04T17:42:34.400Z] Try to connect socket.io.js:59:41
[2022-01-04T17:42:37.421Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32
[2022-01-04T17:42:37.421Z] Start reconnect 5 socket.io.js:59:41
Firefox kann keine Verbindung zu dem Server unter ws://192.168.178.34:8081/?sid=1641318154400&name=admin aufbauen. socket.io.js:91:21
[2022-01-04T17:42:37.422Z] Reconnect is already running 5 socket.io.js:59:41

**Comment by oHero** [comment]
[2022-01-04T18:41:00.728Z] ws connection error: CLOSE_GOING_AWAY socket.io.js:61:32
[2022-01-04T18:41:00.732Z] Start reconnect 0 socket.io.js:59:41
[2022-01-04T18:41:00.743Z] Try to connect socket.io.js:59:41
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.178.34:8081
iobroker.admin@5.2.1 index.js:18:8
[2022-01-04T18:41:01.421Z] Try to connect socket.io.js:59:41

**Comment by Feuer-sturm** [comment]
@oHero Is this issue still active?
Which adapter version do you use?

**Comment by oHero** [comment]
Dear @Feuer-sturm 
yes, the issue still active. i can not open the main page via webbrowser.

did you mean followed information:

pi@raspberrypi:/ $ iobroker info
Platform       : linux
os             : linux
Architecture   : arm
CPUs           : 4
Speed          : 900 MHz
Model          : ARMv7 Processor rev 5 (v7l)
RAM            : 872.3 MB
System uptime  : 00:08:32
Node.js        : v12.21.0
Disk size      : 29.0 GiB
Disk free      : 23.4 GiB
adapters count : 400
NPM            : v6.14.11

pi@raspberrypi:/ $ iobroker --version
3.2.16

thank you for the investigation and your time.

**Comment by Feuer-sturm** [comment]
@oHero The versions of your installed adapters can be read out with:
`iob list adapters`

In addition you can drop here the output of 
`iob list instances`
to see which instances are enabled

**Comment by oHero** [comment]
Dear @Feuer-sturm 
result of the `iob list adapters`:
system.adapter.admin                   : admin          - v5.2.1
system.adapter.daswetter               : daswetter      - v3.0.9
system.adapter.discovery               : discovery      - v2.7.3
system.adapter.email                   : email          - v1.0.10
system.adapter.ical                    : ical           - v1.11.4
system.adapter.info                    : info           - v1.9.8
system.adapter.javascript              : javascript     - v5.2.13
system.adapter.mqtt                    : mqtt           - v2.4.0
system.adapter.mqtt-client             : mqtt-client    - v1.4.0
system.adapter.node-red                : node-red       - v2.4.1
system.adapter.tankerkoenig            : tankerkoenig   - v2.1.1
system.adapter.trashschedule           : trashschedule  - v1.2.0
system.adapter.whatsapp-cmb            : whatsapp-cmb   - v0.1.6
system.adapter.wled                    : wled           - v0.6.3

and result of `iob list instances`:
+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: xxxx, bind: 0.0.0.0, run as: admin
+ system.adapter.discovery.0              : discovery             : raspberrypi                              -  enabled
+ system.adapter.email.0                  : email                 : raspberrypi                              -  enabled
  system.adapter.ical.0                   : ical                  : raspberrypi                              -  enabled
+ system.adapter.info.0                   : info                  : raspberrypi                              -  enabled
+ system.adapter.javascript.0             : javascript            : raspberrypi                              -  enabled
+ system.adapter.mqtt.0                   : mqtt                  : raspberrypi                              -  enabled, port: xxxx, bind: 0.0.0.0
+ system.adapter.node-red.0               : node-red              : raspberrypi                              -  enabled, port: xxxx, bind: 0.0.0.0
+ system.adapter.tankerkoenig.0           : tankerkoenig          : raspberrypi                              -  enabled
+ system.adapter.trashschedule.0          : trashschedule         : raspberrypi                              -  enabled
+ system.adapter.whatsapp-cmb.0           : whatsapp-cmb          : raspberrypi                              -  enabled
+ system.adapter.wled.0                   : wled                  : raspberrypi                              -  enabled

+ instance is alive

Thank you in advance

**Comment by Feuer-sturm** [comment]
@oHero There is no web adapter installed. You can install it with
`iob install web`

After this check with iob list instances once again if web adapter is enabled and the the output for system.adapter.admin.0 should look like this:
`+ system.adapter.admin.0                  : admin                 : ioBrokerTestsystem                       -  enabled, port: 8081, bind: 0.0.0.0, run as: admin`

**Comment by oHero** [comment]
Dear @Feuer-sturm 
after the installation of the web adapter, the error still exist. 
`+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: xxxx, bind: 0.0.0.0, run as: admin`

browser console shows: 
`[2022-03-01T08:22:05.707Z] Try to connect socket.io.js:59:41`
`[2022-03-01T08:22:08.719Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32`
`[2022-03-01T08:22:08.720Z] Start reconnect 5 socket.io.js:59:41
Firefox kann keine Verbindung zu dem Server unter ws://192.168.178.34:8081/?sid=1646122925707&name=admin aufbauen. socket.io.js:91:21
Die Verbindung zu ws://192.168.178.34:8081/?sid=1646122925707&name=admin wurde unterbrochen, während die Seite geladen wurde. socket.io.js:91:21`
`[2022-03-01T08:22:08.727Z] Reconnect is already running 5 socket.io.js:59:41`

Thank you in advance

**Comment by oHero** [comment]
Dear @Feuer-sturm 
after the installation of the web adapter, the error still exist. 
`+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: xxxx, bind: 0.0.0.0, run as: admin`

browser console shows: 
`[2022-03-01T08:22:05.707Z] Try to connect socket.io.js:59:41`
`[2022-03-01T08:22:08.719Z] No READY flag received in 3 seconds. Re-init socket.io.js:60:32`
`[2022-03-01T08:22:08.720Z] Start reconnect 5 socket.io.js:59:41
Firefox kann keine Verbindung zu dem Server unter ws://192.168.178.34:8081/?sid=1646122925707&name=admin aufbauen. socket.io.js:91:21
Die Verbindung zu ws://192.168.178.34:8081/?sid=1646122925707&name=admin wurde unterbrochen, während die Seite geladen wurde. socket.io.js:91:21`
`[2022-03-01T08:22:08.727Z] Reconnect is already running 5 socket.io.js:59:41`

Thank you in advance

**Comment by Feuer-sturm** [comment]
@oHero did you solve your problem?

**Comment by oHero** [comment]
Dear @Feuer-sturm 

no, i can not solve my problem. the issue still exist.

i see this info before get the error message:
![ioBroker Fehlermeldung](https://user-images.githubusercontent.com/22085853/156316812-06b011a7-5a48-4c7a-98d4-1ea9c2fd1142.png)

but i'm not sure, if that was the cause

Thank you in advance

**Comment by oHero** [comment]
Dear @Feuer-sturm 

Ok. i will create a topic in iobroker forum and post the link here. 

Thank you for your Suggestion and your Support.
