### ISSUE TITLE
white border on iobroker logo with gray color theme

### ISSUE THREAD

**Issue by TeNNo2k5** [ioBroker/ioBroker.admin#1268]
It's just a small thing but I'm a bit bothered by this white border on the iobroker logo, which is only displayed with the color theme gray.

![1](https://user-images.githubusercontent.com/33666714/148662371-0537ef3f-9d9e-4fd1-a234-debdaea3ce23.png)
I have unfortunately too little idea of Javascript to contribute appropriate code, but just as an example if I adjust with the devtools of my browser the div class MuiAvatar to jss39909 the logo is displayed without border as just in the Easy Admin Mode.

![2](https://user-images.githubusercontent.com/33666714/148662468-c52107f2-b098-4457-8a3f-2267c1c6028c.png)

Greetings
TeNNo2k5

PS: Maybe additionally as a small suggestion I would find it better to move the Easy Admin Mode into the right menu bar with its own logo/icon.
Because clicking on a logo/ is normally connected to return to the start page, and it happens to me sometimes that I automatically click on the iobroker logo. stupid muscle memory of me :)

**Comment by Feuer-sturm** [comment]
Admin 5.3.1
A little white boarder is still there and inside it is white
![grafik](https://user-images.githubusercontent.com/25422320/155899745-548bc90b-f158-4fb5-ab05-1b16f84bdea3.png)


With Easy Admin everything is fine:
![grafik](https://user-images.githubusercontent.com/25422320/155899786-2620e239-5641-4c4e-9246-a3f249e97b88.png)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172642065-6187ff3d-7b4d-4f61-a8ab-0d071097ea8c.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
This issue is not fixed with 6.0.1

![grafik](https://user-images.githubusercontent.com/25422320/172702380-1e62ded7-50cc-4668-81f5-fb91f3d7f074.png)

**Comment by Apollon77** [comment]
Maybe icon got cached by your browser?

**Comment by Feuer-sturm** [comment]
Same behavior after cleaning the cache.

**Comment by Diginix** [comment]
admin 6.0.2 in Google Chrome with zoom 400%
![image](https://user-images.githubusercontent.com/39678667/172779909-c8394894-8a11-4f35-aec4-5e047587e977.png)

**Comment by GermanBluefox** [comment]
> admin 6.0.2 in Google Chrome with zoom 400% ![image](https://user-images.githubusercontent.com/39678667/172779909-c8394894-8a11-4f35-aec4-5e047587e977.png)

I only removed the background. No size was changed and by me it looks OK
