### ISSUE TITLE
Verbindung zum Homematic IP Gateway, erstellt keinen Token

### ISSUE THREAD

**Issue by sysonic2** [ioBroker/ioBroker.admin#1269]
Liebe IoBroker,
Ich bitte euch um euren Blick und Rat, ich erhalte keine Verbindung,
ich möchte gerne den Adapter "HomeMatic IP Cloud-Zugriffspunkt" mit meinem AccessPoint verbinden und einen Token erstellen, erhalte aber leider keine Verbindung.
(PIN ist korrekt und accessPointSgtin ist definitiv korrekt)
Hat Jemand eine Idee?
Vielen Dank!

Dear IoBroker,
I ask you for your look and advice, I get no connection,
I would like to connect the "HomeMatic IP Cloud Access Point" adapter to my AccessPoint and create a token, but unfortunately I don't get a connection.
(PIN is correct and accessPointSgtin is definitely correct)
Does somebody has any idea?
Thanks very much!

![2022-01-08 22_30_08-Update js-controller und node js](https://user-images.githubusercontent.com/97381978/148689470-75ad0fab-730f-4fb2-a735-78d716134afa.png)
![2022-01-08 22_31_27-intro - raspberrypi](https://user-images.githubusercontent.com/97381978/148689472-d489934a-b936-4571-9be0-3b320c793ffa.png)
![2022-01-08 22_32_05-instances - raspberrypi](https://user-images.githubusercontent.com/97381978/148689474-0fbea23a-302a-4df4-aeaf-4e2810a3559b.png)
![2022-01-08 22_32_59-logs - raspberrypi](https://user-images.githubusercontent.com/97381978/148689475-2f663732-fe1e-4837-a421-e7af3163c03b.png)

**Comment by Apollon77** [comment]
Hi,

das issue muss wenn zum hmip adapter, aber faktisch scheint bei dir der adapter nicht korrekt installiert zu sein. Bitte neues issue im hmip repo anlegen und vor allem bitte die Fehlermeldung vollständig posten. Am besten nochmal adapterentfernen und neu installieren

**Comment by debian333** [comment]
Habe die HMIP installiert und kann den token nicht erstellen.Die Stgin Nummer habe ich angegeben aber die neue HMIP App hat keine möglichkeit die App Pin zu vergeben.Einzige Pin die vergeben werden kann ist die Admin Pin mit der kann der Token auch nicht erstellt werden.Gibt es möglichkeit ohne Pin den Token zu erstellen ?Ich habe HMIP mit dem Acess Point am laufen nicht CCU:

**Comment by debian333** [comment]
Und wo soll ich es Posten ?Bin neuling was Repo Git Hub etc betrifft.Sorry
