### ISSUE TITLE
Möglichkeit schaffen aktuell angemeldeten Benutzer zu wechseln

### ISSUE THREAD

**Issue by robdg80** [ioBroker/ioBroker.admin#127]
Bitte die Möglichkeit schaffen den aktuell angemeldeten benutzer zu wechseln.

Beispiel Ich ändere den default nutzer auf einen Nutzer der nicht in der Gruppe der Administratoren ist:
![2018-01-03_20h20_03](https://user-images.githubusercontent.com/12692680/34536061-62850c86-f0c4-11e7-963c-8506ac2cd42f.png)

Wie kann ich jetzt wieder im admin zu dem Benutzer admin wechseln, wenn Authentifikation deaktiviert ist?

Wer auch das Problem hat, um das weg zu bekommen siehe hier: http://forum.iobroker.net/viewtopic.php?f=8&t=10277

**Comment by Apollon77** [comment]
Ich denke dies ist Sicherheitstechnisch keine sinnvolle Idee! Dann müsste man einen automatischen Logout implementieren und auch sonst könnte ein Limitierter User sich so zum Admin machen.

Eine "Limitierte" Admin-Instanz macht nur Sinn wenn es eine "zweite Instanz" ist. Die erste sollte Immer Admin sein.

Oder verstehe ich irgendwas falsch?

**Comment by robdg80** [comment]
OK, so habe ich es noch nicht gesehen. Dann sollte vielleicht eine Warnung erscheinen, wenn man das versucht zu ändern.

**Comment by Apollon77** [comment]
Ein "Permission error" wird angezeigt, oder ?!

**Comment by GermanBluefox** [comment]
Einfach aufrufen:

iobroker set admin.0 --defaultUser admin

2018-01-03 22:50 GMT+01:00 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
Und das ist ok, weil "wer ssh zugriff auf den host hat kann eh alles"
