### ISSUE TITLE
File after deletion still visible

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1270]
**Describe the bug**  
After deletion of a file the file is still visible until a manual refresh is done.

**To Reproduce**  
1. Go to menu File
2. Delete one file
3. Check if file is still visible -> Yes -> :-(
4. Manual refresh is necessary to have the file not any more in the view

**Expected behavior**  
After deletion of the file the file is not visible any more

**Screenshots & Logfiles**  
![Animation19](https://user-images.githubusercontent.com/25422320/148696216-3cd6b04a-80cf-4851-9938-e1990fb99fef.gif)

**Versions:**  
 - Admin Adapter version: 5.2.3
 - JS-Controller version: 3.3.22
 - Node version: 14.18.1

**Comment by Feuer-sturm** [comment]
Not fixed yet

**Comment by GermanBluefox** [comment]
Please test 6.0.1

**Comment by Feuer-sturm** [comment]
Is fixed with 6.0.1
