### ISSUE TITLE
Generating of folder in channel not possible

### ISSUE THREAD

**Issue by klassisch** [ioBroker/ioBroker.admin#1272]
**Describe the bug**  
Data structure contains a channel with states under it.
A folder should be created under this channel. But was not possible
**To Reproduce**   
Data structure contains a channel called AllesZu:
![grafik](https://user-images.githubusercontent.com/35134055/148773348-fd2ab5ab-2b14-401c-b66b-987e5b0fa407.png)

![grafik](https://user-images.githubusercontent.com/35134055/148773471-47d90329-18fa-4347-819d-fa394f4adce9.png)

Generation of folder under the channel is not possible
![grafik](https://user-images.githubusercontent.com/35134055/148773953-12636e30-50f3-4b3c-b5d3-e7d8f6cf6b63.png)

![grafik](https://user-images.githubusercontent.com/35134055/148774147-1b378e1c-5e19-4a25-aec1-7ccc029988a3.png)

manual Conversion  to type "folder" solves the issue:
![grafik](https://user-images.githubusercontent.com/35134055/148774506-cab25126-e019-4c97-8e2f-c0d889c23c8e.png)

![grafik](https://user-images.githubusercontent.com/35134055/148774647-0839cd56-73e5-4e7b-8d5e-aebbad583c1b.png)

**Expected behavior**  
According https://forum.iobroker.net/post/738175 "folders are allowed under channels"

**Screenshots & Logfiles**  
see above
**Versions:**  
Admin: 5.2.3 
js 3.3.22
Plattform
    Windows
Betriebssystem
    win32
Architektur
    x64
CPUs
    4
Geschwindigkeit
    2496 MHz
Modell
    Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
RAM
    7.36 GB
System-Betriebszeit
    00:00:29
Node.js
    v14.18.2
Anzahl der Adapter
    362
Datenträgergröße
    166.52 GB
freier Festplattenspeicher
    103.52 GB
NPM
    v6.14.15
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

![grafik](https://user-images.githubusercontent.com/35134055/148775675-a9eba9c1-573b-4dc3-82ce-08e1032c17d7.png)

**Additional context**  
nothing to declare

**Comment by Apollon77** [comment]
We said that folder can be anywhere or? or do really channel need o be "the last level"?

**Comment by klassisch** [comment]
I am not sure, if I understood the question correctly. 
I am referring  to https://forum.iobroker.net/post/738175 "an sich sollten folders auch in channel erlaubt sein"
