### ISSUE TITLE
Error in GUI! Objekte

### ISSUE THREAD

**Issue by lobomau76** [ioBroker/ioBroker.admin#1273]
Ich kann "Objekte" plötzlich nicht öffnen im admin. Es kommt die "Error in GUI!" Meldung. Ich soll den Fehler hier posten:
js-controller: 3.3.22
admin: 5.2.3
Edit: Fehler kommt mit chrome Browser. Mit firefox läuft es.
Edit2: Fehler kommt auch mit firefox, nachdem ich in Objekte den Baum vom Denon Adapter öffne :-(

`react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'toString')
    at ObjectBrowser.js:1210:55
    at s.value (ObjectBrowser.js:3383:57)
    at s.value (ObjectBrowser.js:4067:34)
    at s.value (ObjectBrowser.js:4083:25)
    at ObjectBrowser.js:4128:45
    at Array.map (<anonymous>)
    at s.value (ObjectBrowser.js:4123:59)
    at ObjectBrowser.js:4115:45
    at Array.map (<anonymous>)
    at s.value (ObjectBrowser.js:4110:59)`

`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by lobomau76** [comment]
Problem taucht nur auf in neuer Admin Oberfläche.

**Comment by Feuer-sturm** [comment]
@lobomau76 Bitte einmal mit der aktuellen Admin Version 5.3.7 testen ob das Problem noch besteht.

**Comment by lobomau76** [comment]
Unter 5.3.7 bleibt das Problem mit dem tab Objekte unter google chrome browser. Habe auch einmal google chrome de- und wieder neu installiert. Eben auch nochmal mit firefox getestet... da ist nach 2-3 klicks unter Objekte schluss.

Das Problem ist aber nur mit neuer Benutzeroberfläche. Mit alter admin Benutzeroberfläche kein Problem.

**Comment by Apollon77** [comment]
Was sind denn diese "klicks"? Machst du da immer das gleiche? Wie immer gleichen Ordner aufklappen oder so? Ist da vllt ein Objekt kaputt?

**Comment by lobomau76** [comment]
Das Problem ist eventuell außerhalb von ioBroker zu finden. Auf dem Rechner bei der Arbeit habe ich keine Probleme.
Beide Rechner (Arbeit und Laptop zu Hause) haben Windows 10.
Bei der Arbeit gehe ich über admin.0 (https) und zu Hause über admin.1 (http neue Benutzeroberfläche) und admin.2 (http alte Benutzeroberfläche). Kann ich mal testen zu Hause was passiert wenn ich da über https gehe. Wahrscheinlich das hat nix damit zu tun.

**Comment by GermanBluefox** [comment]
Fixed in 5.4.8. Aber warum ist ack=null ???
https://github.com/ioBroker/ioBroker.admin/blob/a19915fdb2daa9c96ad189d16d824be06962123b/src-rx/src/components/ObjectBrowser.js#L1210

**Comment by lobomau76** [comment]
Ja, cool! Mit Admin 5.4.8 ist das Problem bei mir behoben.
ack=null sagt mir nichts
