### ISSUE TITLE
Trashshedule don't work

### ISSUE THREAD

**Issue by exmerci** [ioBroker/ioBroker.admin#1275]
**Describe the bug**  
Adapter does not work anymore. I reinstalled it, but it didn't help.

![image](https://user-images.githubusercontent.com/97529727/148954487-a5059c38-05fa-49f8-ac86-e707306026a0.png)

react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at d (react-dom.production.min.js:144)
    at v (react-dom.production.min.js:146)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at _l (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)

**Comment by Apollon77** [comment]
What exactly is not working anymore?

**Comment by exmerci** [comment]
I found the mistake. My Admin version is too old for the latest version
from trashschedule adapter. But what I not know is, why it is no more work,
if I install an older version of the trash adapter.
Before I did the update the trash adapter ran with the older Admin version
too.

Best Regards



Am Di., 11. Jan. 2022 um 17:18 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
But is this not  abetter question for the trashschedule adapter? The devfloper should be better able to tell you the reasons and also why he needs new admin but do not add this as a "dependency" to prevent adapter updates with too old admin versions
