### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by djordjy1907** [ioBroker/ioBroker.admin#1276]
Habe ein Fehler in der GUI.
Ich soll den hier Posten damit mir geholfen werden kann 
Es passiert wenn ich auf Einstellungen von  Trashshedule 1.41 gehe.
Hier ein Screenshot:

![Error GUI](https://user-images.githubusercontent.com/97546341/148992675-a17ef16e-a89d-4d8b-a790-5ba78431bf6c.JPG)

Hoffe es reicht so
Gruß

**Comment by lobomau76** [comment]
Wenn ich es richtig verstanden habe, ist das ein Beispiel-Screenshot. Man muss zusätzlich F12 tippen und da den Fehler raussuchen. Oder hast du das gemacht? Dann hättest du zufällig den selben Fehler wie im Screenshot.
Vielleicht es bei dir wie mir (habe gestern issue erstellt).
Kannst du mal testen, ob das auch mit altem Admin auftaucht? "benutze alte Benutzeroberfläche". Da habe ich dann kein Problem.

![image](https://user-images.githubusercontent.com/35029301/149124936-163fdd00-ec6f-437f-93d0-25b8bae538df.png)

**Comment by lobomau76** [comment]
@djordjy1907 bei mir kommt der Fehler übrigens nicht, wenn ich in die Einstellungen vom trashschedule gehe und dort rumklicke. Meine Probleme kommen wenn ich unter Objekte gehe.
Ich habe auch trashschedule 1.4.1.
Admin ist 5.2.3. und js-controller 3.3.22.

**Comment by djordjy1907** [comment]
@lobomau76 ich habe in der tat einen screenshot von dem Beispielbild angehängt.
Die Fehlermeldung tritt bei mir nur auf wenn ich in die Einstellungen von trashschedule 1.4.1 gehe, aber nicht wenn ich auf Admin gehe. Die Instance bliebt seit gestern nach dem Update auf 1.41 auf rot. 
Admin ist 5.1.25 und js-controller 3.3.22.
Habe versucht ein Admin Update auf 5.2.3 zu machen aber dann startet Admin nicht mehr und ich musste ein Backup einspielen.
Hier die Fehlermeldung von GUI

![Error Gui](https://user-images.githubusercontent.com/97546341/149196646-a8715b9d-6272-45dd-94e4-4270162b28c8.JPG)

**Comment by djordjy1907** [comment]
Habe den iobroker fix drüber laufen lassen.
jetzt ist der Fehler weg

**Comment by Apollon77** [comment]
Also iob fix kann damit an sich überhaupt nix zu tun haben :-)

**Comment by lobomau76** [comment]
> Also iob fix kann damit an sich überhaupt nix zu tun haben :-)

Schade. Hat auch bei meinem Problem issue 1275 nicht geholfen. Aber einen Versuch war es wert.

**Comment by GermanBluefox** [comment]
Sollte gefixt sein.
