### ISSUE TITLE
Can not add instances if dependencies for update are not met

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.admin#1277]
**Describe the bug**  
Installed is admin version 5.2.1 (yes, it is outdated). There is an update to 5.2.3 which currently can not be installed because js-controller dependency is not met. 
In this situation I can not add another admin instance (of the old version) but get the error message, that dependencies are not met. (this is on the same host the admin is currently installed).

I would expect that I can still add instances in  this situation.

**To Reproduce**  
1. Create situation where dependencies for an update are not met
2. Click on "add instance"
3. See error message instead of new instance being added

**Expected behavior**  
Add a new instance no matter what condition installed adapter is in.

**Screenshots & Logfiles**  
![Screenshot_2](https://user-images.githubusercontent.com/620860/149355181-f1bbfaf2-835f-47d6-92c1-0aa58bc66f97.png)

**Versions:**  
 - Adapter version: 5.2.1 (did not find another fitting example, sorry)
 - JS-Controller version: 3.3.21
 - Node version: 14.18.2
 - Operating system: Ubuntu

**Comment by GermanBluefox** [comment]
And why we need then conditions? The version could even do not start. Why you need a broken adapter?

**Comment by GermanBluefox** [comment]
> The installed adapter version (5.2.1) is not / was not broken. Only the update to 5.2.3 was not possible, because dependencies not met.
> 
> The question is: Why check dependencies for adapter version 5.2.3, when creating a new instance of adapter version 5.2.1.

Because admin does not have dependencies for all version. It has just for one in repository. 
It is technically hard to implement such a feature. Admin must download npm package unpack it and check io-package.... Use CLI for this very corner use-case

**Comment by Garfonso** [comment]
But the adapter (admin in this case) is already installed? So I don't get why a download from npm is necessary. But if it is too much effort to change, it's fine with me.
