### ISSUE TITLE
Connection over VPN produces websocket error

### ISSUE THREAD

**Issue by Mistaluna** [ioBroker/ioBroker.admin#1283]
**Describe the bug**  
I connect to iobroker over an IPSEC VPN connection. Some actions in iobroker, for exemple going to the Script pages produces an error at websocket.

**To Reproduce**  
1. Go to iobroker admin webinterface at port 8081
2. Click on Scripts
3. See error

**Expected behavior**  
The Scripts editor should load.

**Screenshots & Logfiles**  
`<html><body>

admin.0 | 2022-01-17 22:21:30.471 | info | starting. Version 5.2.3 in /opt/iobroker/node_modules/iobroker.admin, node: v17.3.1, js-controller: 3.3.22
-- | -- | -- | --
host.iobroker-1 | 2022-01-17 22:21:29.837 | info | instance system.adapter.admin.0 started with pid 691
host.iobroker-1 | 2022-01-17 22:20:59.817 | info | Restart adapter system.adapter.admin.0 because enabled
host.iobroker-1 | 2022-01-17 22:20:59.817 | error | instance system.adapter.admin.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker-1 | 2022-01-17 22:20:59.817 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/permessage-deflate.js:391:7
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/permessage-deflate.js:308:9
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:482:12
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught  by controller[0]:     at Receiver.startLoop  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:157:5)
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught by controller[0]:     at onwrite (node:internal/streams/writable:462:7)
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught by controller[0]:     at clearBuffer (node:internal/streams/writable:570:7)
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught by controller[0]:     at doWrite (node:internal/streams/writable:409:12)
host.iobroker-1 | 2022-01-17 22:20:59.816 | error | Caught  by controller[0]:     at Receiver._write  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:83:10)
host.iobroker-1 | 2022-01-17 22:20:59.815 | error | Caught  by controller[0]:     at Receiver.startLoop  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:136:22)
host.iobroker-1 | 2022-01-17 22:20:59.815 | error | Caught  by controller[0]:     at Receiver.getInfo  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:242:16)
host.iobroker-1 | 2022-01-17 22:20:59.814 | error | Caught by controller[0]: RangeError: Invalid WebSocket frame: FIN must be set
admin.0 | 2022-01-17 22:20:59.417 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
admin.0 | 2022-01-17 22:20:59.415 | info | terminating
admin.0 | 2022-01-17 22:20:59.414 | info | terminating http server on port 8081
admin.0 | 2022-01-17 22:20:59.395 | error | Exception-Code: WS_ERR_EXPECTED_FIN: Invalid WebSocket frame: FIN must be set
admin.0 | 2022-01-17 22:20:59.394 | error | RangeError:  Invalid WebSocket frame: FIN must be set    at Receiver.getInfo  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:242:16)     at Receiver.startLoop  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:136:22)     at Receiver._write  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:83:10)     at doWrite (node:internal/streams/writable:409:12)    at clearBuffer  (node:internal/streams/writable:570:7)    at onwrite  (node:internal/streams/writable:462:7)    at Receiver.startLoop  (/opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:157:5)     at  /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/receiver.js:482:12     at  /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/permessage-deflate.js:308:9     at  /opt/iobroker/node_modules/iobroker.admin/node_modules/ws/lib/permessage-deflate.js:391:7
admin.0 | 2022-01-17 22:20:59.391 | error | uncaught exception: Invalid WebSocket frame: FIN must be set

</body>
</html>`

![grafik](https://user-images.githubusercontent.com/85135468/149838679-6381a98e-a392-49c5-9dce-3a72ef2d15c0.png)

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 3.3.22
 - Node version: 17.3.1 also tried latest versions of 12.x, 14.x and 16.x
 - Operating system: Debian 11 Bullseye

**Comment by GermanBluefox** [comment]
I tried to catch this error in admin 5.3.0. Please check

**Comment by GermanBluefox** [comment]
> Doesn't work either correctly but beahvior changed.

Had you seen some errors in browser console?

**Comment by Feuer-sturm** [comment]
No additional feedback. Close issue.
@Mistaluna If there is still a problem with current admin please give additional information.
