### ISSUE TITLE
Drag & Drop does not work with Chromium

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#1285]
**Describe the bug**  
Drag & Drop does not work in enums and user managment. 

**To Reproduce**  
1. Go to 'Enumarations'
2. Drag any state you want from the right side 
3. Try to drop it on a enum on the left side
4. See that it was not added

**Expected behavior**  
State should appear wihtin the enum field.

**Versions:**  
 - Adapter version: 5.2.25 & 5.2.3
 - JS-Controller version: 3.3.22
 - Node version: 12.22.9
 - Operating system: Ubuntu
 - Browser: Chromium, Version 97.0.4692.71

**Additional context**  
Tested the same on Firefox and Chrome, there it works. 
No errors in Browser console.

**Comment by Apollon77** [comment]
What kind of "chromium" you use here? Or is it embedded in some application? Because what I know is thsi in such a case the application could control weather drag&drop is allowed/possible or not. And because Chrome also has Chromium inside it would be strange that it does not work when it works in Chrome

**Comment by Jey-Cee** [comment]
> What kind of "chromium" you use here?

I don't understand this question, because it is a browser as i have written in versions.

**Comment by Apollon77** [comment]
SO the stand alone Chromium build, ok got it. Background: Electron based projects have Chromium embedded and some other applications or even browsers base on it ... just wanted to be sure.

**Comment by GermanBluefox** [comment]
Cannot reproduce under Chrom:
![adminDrug](https://user-images.githubusercontent.com/4582016/153196229-f20e717f-16a7-4ebb-81e8-21fba6f0e098.gif)

**Comment by Apollon77** [comment]
Yes, it was reported for "Chromium" browser ... yes that really exists :-)) https://www.chromium.org/getting-involved/download-chromium/

**Comment by Jey-Cee** [comment]
Since Chromium version 98 it is working again. Looks like it was a bug of the browser.
