### ISSUE TITLE
I was asked to publish a request due to installtion of shelly adapter

### ISSUE THREAD

**Issue by misave** [ioBroker/ioBroker.admin#1286]
Hi all,
during the installation of the shelly adapter i got the browser message that there was a mistake and i was asked to publish an issue on github. For that i opened the exloter console and copied the given error message as following:

iobroker is running on buster on RPi 3, all adapters from stable repository, node and node.js are in 14.18.2 

iobroker.admin@5.2.3
socket.io.js:59 [2022-01-18T10:06:56.016Z] Try to connect
moma.png:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
Instances.js:444 getInstances: 61
:8081/lib/css/materialize.css:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/lib/js/jquery-3.2.1.min.js:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/css/adapter.css:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/js/adapter-settings.js:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
:8081/lib/js/materialize.js:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
​ [2022-01-18T10:07:18.250Z] Try to connect
:8081/lib/fonts/material.woff2:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
​ "Port:": {"en": "Port:", "de": "Port:", "ru": "Port:", "pt": "Port:", "nl": "Port:", "fr": "Port:", "es": "Port:", "pl": "Port:", "it": "Port:", "zh-cn": "Port:"},
​ "0 - At most once": {"en": "0 - At most once", "de": "0 - At most once", "ru": "0 - At most once", "pt": "0 - At most once", "nl": "0 - At most once", "fr": "0 - At most once", "es": "0 - At most once", "pl": "0 - At most once", "it": "0 - At most once", "zh-cn": "0 - At most once"},
​ "1 - At least once": {"en": "1 - At least once", "de": "1 - At least once", "ru": "1 - At least once", "pt": "1 - At least once", "nl": "1 - At least once", "fr": "1 - At least once", "es": "1 - At least once", "pl": "1 - At least once", "it": "1 - At least once", "zh-cn": "1 - At least once"},
​ "2 - Exactly once": {"en": "2 - Exactly once", "de": "2 - Exactly once", "ru": "2 - Exactly once", "pt": "2 - Exactly once", "nl": "2 - Exactly once", "fr": "2 - Exactly once", "es": "2 - Exactly once", "pl": "2 - Exactly once", "it": "2 - Exactly once", "zh-cn": "2 - Exactly once"},
​ "Default QoS:": {"en": "Default QoS:", "de": "Default QoS:", "ru": "Default QoS:", "pt": "Default QoS:", "nl": "Default QoS:", "fr": "Default QoS:", "es": "Default QoS:", "pl": "Default QoS:", "it": "Default QoS:", "zh-cn": "Default QoS:"},
​ "Blacklist": {"en": "Blacklist", "de": "Blacklist", "ru": "Blacklist", "pt": "Blacklist", "nl": "Blacklist", "fr": "Blacklist", "es": "Blacklist", "pl": "Blacklist", "it": "Blacklist", "zh-cn": "Blacklist"},
​ "Listen on all IPs": {"en": "Listen on all IPs", "de": "Listen on all IPs", "ru": "Listen on all IPs", "pt": "Listen on all IPs", "nl": "Listen on all IPs", "fr": "Listen on all IPs", "es": "Listen on all IPs", "pl": "Listen on all IPs", "it": "Listen on all IPs", "zh-cn": "Listen on all IPs"},
​ [2022-01-18T10:07:41.504Z] Try to connect
​ "Port:": {"en": "Port:", "de": "Port:", "ru": "Port:", "pt": "Port:", "nl": "Port:", "fr": "Port:", "es": "Port:", "pl": "Port:", "it": "Port:", "zh-cn": "Port:"},
​ "0 - At most once": {"en": "0 - At most once", "de": "0 - At most once", "ru": "0 - At most once", "pt": "0 - At most once", "nl": "0 - At most once", "fr": "0 - At most once", "es": "0 - At most once", "pl": "0 - At most once", "it": "0 - At most once", "zh-cn": "0 - At most once"},
​ "1 - At least once": {"en": "1 - At least once", "de": "1 - At least once", "ru": "1 - At least once", "pt": "1 - At least once", "nl": "1 - At least once", "fr": "1 - At least once", "es": "1 - At least once", "pl": "1 - At least once", "it": "1 - At least once", "zh-cn": "1 - At least once"},
​ "2 - Exactly once": {"en": "2 - Exactly once", "de": "2 - Exactly once", "ru": "2 - Exactly once", "pt": "2 - Exactly once", "nl": "2 - Exactly once", "fr": "2 - Exactly once", "es": "2 - Exactly once", "pl": "2 - Exactly once", "it": "2 - Exactly once", "zh-cn": "2 - Exactly once"},
​ "Default QoS:": {"en": "Default QoS:", "de": "Default QoS:", "ru": "Default QoS:", "pt": "Default QoS:", "nl": "Default QoS:", "fr": "Default QoS:", "es": "Default QoS:", "pl": "Default QoS:", "it": "Default QoS:", "zh-cn": "Default QoS:"},
​ "Blacklist": {"en": "Blacklist", "de": "Blacklist", "ru": "Blacklist", "pt": "Blacklist", "nl": "Blacklist", "fr": "Blacklist", "es": "Blacklist", "pl": "Blacklist", "it": "Blacklist", "zh-cn": "Blacklist"},
​ "Listen on all IPs": {"en": "Listen on all IPs", "de": "Listen on all IPs", "ru": "Listen on all IPs", "pt": "Listen on all IPs", "nl": "Listen on all IPs", "fr": "Listen on all IPs", "es": "Listen on all IPs", "pl": "Listen on all IPs", "it": "Listen on all IPs", "zh-cn": "Listen on all IPs"},
:8081/static/js/12.11af713b.chunk.js:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
react-dom.production.min.js:216 ChunkLoadError: Loading chunk 12 failed.
(error: http://192.168.2.25:8081/static/js/12.11af713b.chunk.js)
    at Function.u.e (192.168.2.25/:1:3981)
    at main.4ec45a8c.chunk.js:2:1086592
    at V (5.6300204f.chunk.js:2:5680544)
    at Zi (5.6300204f.chunk.js:2:5670728)
    at jl (5.6300204f.chunk.js:2:5657389)
    at Sl (5.6300204f.chunk.js:2:5657317)
    at Cl (5.6300204f.chunk.js:2:5657180)
    at zl (5.6300204f.chunk.js:2:5654146)
    at 5.6300204f.chunk.js:2:5603640
    at t.unstable_runWithPriority (5.6300204f.chunk.js:2:5686850)
ui @ react-dom.production.min.js:216

If you need more information, please let me know.
best regards 

Michael

**Comment by GermanBluefox** [comment]
Thank you for your reporting
This error could be fixed by cache cleaning.
