### ISSUE TITLE
Admin shows "non-npm version" for adapter installed from beta repo

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1287]
**Describe the bug**  
![grafik](https://user-images.githubusercontent.com/17641229/150004329-a971c9c0-de19-4f17-852e-78a6fe37d546.png)

**To Reproduce**  
Install adapter from beta repo

**Expected behavior**  
This is not a non-npm version :)

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: v5.2.3
 - JS-Controller version: 3.3.22
 - Node version: 14.18.3
 - Operating system: Debian Bullseye

**Additional context**

**Comment by AlCalzone** [comment]
`iobroker.influxdb@2.4.0`

**Comment by GermanBluefox** [comment]
> `iobroker.influxdb@2.4.0`

Exactly that means it was installed from npm

**Comment by Apollon77** [comment]
@GermanBluefox Yes this is NPM install but @AlCalzone says that his admin shows it as it would be an github install ... see first screen

**Comment by AlCalzone** [comment]
Yes exactly. I installed through the admin, with beta repository selected, but admin claims I **did not** install via npm.

**Comment by Feuer-sturm** [comment]
@AlCalzone can you please check with current admin version if this issue can be closed?
