### ISSUE TITLE
Error while trying to view the settings in object view adapter modbus.2 - setting value 'Momentanleistung= current power consumption'

### ISSUE THREAD

**Issue by 2000teddy** [ioBroker/ioBroker.admin#1288]
**Describe the bug**  

_Error while trying to view the settings in object view adapter modbus.2 - setting value 'Momentanleistung= current power consumption'_

**To Reproduce**  
2. Click on '...'

_> stateChange modbus.2.holdingRegisters.1.1790_Momentanleistung
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
react-dom.production.min.js:216 TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160:32)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
ui @ react-dom.production.min.js:216
ObjectBrowser.js:1809 - unsubscribe admin.0.info.connection_

**Expected behavior**  

_While clicking on the setting button, to open the setting window for storing values in history and influxdb_ 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

_pi@raspberrypi:~ $ iobroker -v
3.3.22

pi@raspberrypi:~ $ which nodejs node npm && nodejs -v && node -v && npm -v && sudo apt update && sudo apt update && apt policy nodejs
/usr/bin/nodejs
/usr/bin/node
/usr/bin/npm
v12.22.9
v12.22.9
8.3.1
Holen:1 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Holen:2 http://archive.raspberrypi.org/debian buster InRelease [32,6 kB]                                                                                                 
OK:3 https://deb.nodesource.com/node_12.x buster InRelease                                                                                                               
OK:4 https://repos.influxdata.com/debian buster InRelease                                             
Holen:5 http://archive.raspberrypi.org/debian buster/main armhf Packages [393 kB]
Es wurden 441 kB in 2 s geholt (286 kB/s).
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Aktualisierung für 2 Pakete verfügbar. Führen Sie »apt list --upgradable« aus, um sie anzuzeigen.
OK:1 http://archive.raspberrypi.org/debian buster InRelease
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                                                                                                      
OK:3 https://deb.nodesource.com/node_12.x buster InRelease                                                                                                          
OK:4 https://repos.influxdata.com/debian buster InRelease                                                                                  
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Aktualisierung für 2 Pakete verfügbar. Führen Sie »apt list --upgradable« aus, um sie anzuzeigen.
nodejs:
  Installiert:           12.22.9-deb-1nodesource1
  Installationskandidat: 12.22.9-deb-1nodesource1
  Versionstabelle:
 *** 12.22.9-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_12.x buster/main armhf Packages
        100 /var/lib/dpkg/status
     10.24.0~dfsg-1~deb10u1 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages_

**Additional context**

**Comment by Apollon77** [comment]
Update admin, see the pinned issue #1256
