### ISSUE TITLE
Adapterlist is not sorted by name

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.admin#1289]
The sorting looks off because it is by repo name and not by name

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1307684/150395705-bff316ff-2610-4367-8d44-df665ddbc04d.png">

**Comment by GermanBluefox** [comment]
Changed in 5.3.0
![image](https://user-images.githubusercontent.com/4582016/153194713-537cb12b-92e7-459b-a4bc-c7dbb31ddbc0.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox Here for example it does not look like it is sorted by name:
![grafik](https://user-images.githubusercontent.com/25422320/153486041-54986ffb-658c-4129-b479-1cc70d993f43.png)
