### ISSUE TITLE
Login not possible after restoring ioBroker files

### ISSUE THREAD

**Issue by RkcCorian** [ioBroker/ioBroker.admin#1290]
**Describe the bug**  

When I recover from a backup (Synology Hyper Backup - copy back my files) I have the following strange behaviour / trouble...
- ioBroker seems to start normally. I can access my VIS (JARVIS) normally and also scripts are working, I can e.g. also switch on lights, .... JARVIS also has a Adapter Widget where I see the status of the adapters, they are all running normally
- My trouble is... when I try to login to ioBroker (Admin) this is not possible. There is only a white page with the following errors in the console...
![image](https://user-images.githubusercontent.com/79741077/150552166-270fde88-f623-4bd7-856a-ffb9e6d4468d.png)

**To Reproduce**  
1. Synology Docker running ioBroker, data is stored outside the container in a folder on Synology NAS
2. Create an incremental Backup of the folder
3. Restore Backuped folder to another ioBroker Container folder (Beyond Compare tells both folders are equal)
4. Start Backuped ioBroker

Funny:
If i copy the files directly I do not have this problem

**Expected behavior**  

Login to Backuped ioBroker is possible in all cases

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

See above

**Versions:**  
 - Adapter version: 5.2.3
 - JS-Controller version: 3.3.22 
 - Node version: v14.18.3 
 - Operating system: Synolog Docker (buanet/iobroker:v6.0.0)

**Additional context**  

I did not had this issue in the past when tested my incremental backups. Any idea what might go wrong? Many thanks!!!!

**Comment by Apollon77** [comment]
Honestly? The official suppoted way for backups is  the "iobroker backup" command ... I have no idea what this kind of Synology Hyperbackup really does - especially when you might execte it when iobroker is running in parallel (?).

please try if an "iobroker upload all" fixes the issue, then it would mean that the metadata and adapterdata/iobroker storage run out of sync (whyever caused by your incremental backup).

**Comment by RkcCorian** [comment]
Many thanks for you response and time!
I tried "iobroker upload all" but it does not change anything. I mean ioBroker seems to work normal only the login is not coming.

Question from my side (to also improve my backup strategy 🙈)... "iobroker backup" is the same like using the backitup adapter?! If yes this is not fully working with me in the past. E.g. I had a high need for backups and rollbacks as I was supporting Zefau by testing and using several early development versions of JARVIS. When I was trying once to restore with BackitUp it was not working, at minimum with JARVIS. What was always working was to manually copy the files at the NAS from the ioBroker folder to another backup folder and in case of restore putting them back. Everything was then there also when I set up a new container. As the whole data copying is very inefficient I changed to use Synology Hyper Backup (its simply an app in the Synology Store) which was doing incremental backups of the files. This was also working till I had today the need to rollback. It was not working anymore. I thought that the incremental backup missed some files or some files are corrupted (btw. I always stopped the iobroker container before running the backup to avoid incosistent data) so I compared via Beyond Compare all files but there was no difference. I have totally no glue where the difference comes from, anyway... I had the luck that I had on a test iobroker container still the files which I was able to copy from there. A freshly created backup via Synology App was also working then.
-> I feel that Synology crashed something during incremental backup which I'm unable to find. I will look at this carefully in the next months
-> Appart from that I can retry to use BackitUp. To get excercise on this I will try to use a Backitup Backup with a fresh container
-> If "iobroker backup" is not the same like using Backitup please give me a hint to some docu how to use this 🙈

Many thanks!

**Comment by Apollon77** [comment]
I talk about the complete "low level general backup function" and this is the CLI command "iob backup" ... Yes backitup also uses this to backup the core data of iobroker but backitup also added several adapter specific backup stuff on top - so if you have issues with this open an issue in backitup please! I remember he did somethig special for Jarvis or such 

If upload all do not help try to reinstall admin adapter ... because the screenshot shows that the browser tries to load files that are not there :-)

**Comment by RkcCorian** [comment]
Moin @Apollon77 ! Now I managed also the official way of doing a Backup. Now the folder size has been reduced by 50%. It takes much more time to do this in this way. So in future I will have a mixture of both ways doing it. Many thanks again for the "trigger"! :-)
