### ISSUE TITLE
Admin crashes when repositories object can't be read

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#1291]
I believe this check is backwards. If `systemRepos` is undefined, the else branch gets executed and crashes
https://github.com/ioBroker/ioBroker.admin/blob/09063aec9d86312a793577482b7beee806fd3058/main.js#L327-L331

**Comment by GermanBluefox** [comment]
Fixed in 5.3.0

**Comment by Feuer-sturm** [comment]
@AlCalzone Can the issue be closed?

**Comment by AlCalzone** [comment]
Looks correct now, haven't tested though.
