### ISSUE TITLE
Instance titles gets overwritten on file upload

### ISSUE THREAD

**Issue by Bannsaenger** [ioBroker/ioBroker.admin#1292]
**Describe the bug**  
A instance title can be set via the admin gui. I use this to set a decription to a instance when there are 
more than one instances of an adapter.
On every file upload (iob upload ... oder install new version) the title gets overwritten back to the default title.

**To Reproduce**  
1. change the title of an instance e.g. backitup.0 to 123
2. iob upload backitup
3. the title is BackItUp again

**Expected behavior**  
When the instance title is changed by the user, there is a reason to set a user defined title
On file upload the user defined title has to be preserved.

**Versions:**  
 - Adapter version: 5.2.3
 - JS-Controller version: 3.3.22
 - Node version: 14.18.3
 - Operating system: ubuntu and windows

**Comment by Apollon77** [comment]
duplicate https://github.com/ioBroker/ioBroker.js-controller/issues/1448 and will be fixed in js-controller 4
