### ISSUE TITLE
Change static warning text for NPM install to dynamic text

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1294]
Admin 5.2.3

After discussion with @Apollon77 there is with Admin5 the new strategy to install the current beta version by using "NPM install" in Admin Adapter without changing the repository from stable to beta. 

Currently it is not possible to change the text below "Warnung" for the user because the static text github_warning is used and only the wording (NPM, github, URL) will change with %s 

![grafik](https://user-images.githubusercontent.com/25422320/151051778-b9139a9b-d0cb-4021-acee-cb2fc62b5441.png)

![grafik](https://user-images.githubusercontent.com/25422320/151051847-86a7de65-cfa6-4b24-a6e2-173aafb19b27.png)

Expectation:
It shall be possible to write a seperate text for the user if the tab "von NPM" is selected to give a different information to the user if he installs from npm

**Comment by GermanBluefox** [comment]
`npm_warning` was added in 5.3.0

**Comment by Apollon77** [comment]
Text in Weblate angepasst - I hope it is ok to only use one placeholder :-)
