### ISSUE TITLE
Rename get/setBinaryState methods to get/setForeignState

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1297]
In js-controller 4.0 we decided to cleanup an inconsistent naming with get/setBinaryState methods that work like get/setForeignBinaryState.

Please adjust the methods used to use the right "Foreign" wording and use js-controller 4.0 as dependency!

In js-controller 4.1 we plan to adjust the methods without Foreign to really behave that way!

**Comment by GermanBluefox** [comment]
Done in 5.3.0
