### ISSUE TITLE
Notifications severity ignored

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#1299]
No matter which of the supported severities is defined, admin will always show "Adapter warnings" as heading, however for "notify" and "info" it should not have a title like this and also not the yellow warning sign.

Furthermore, if the instance is a host `system.host.rpi` instead of an adapter instance `system.adapter.hm-rpc.0`, replace the word Adapter with the word host in the title.

**Comment by GermanBluefox** [comment]
The problem is, it could be combined warnings and to calculate the most worth state is comlex
