### ISSUE TITLE
Remove the "rebuild button" from a single adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1303]
... because is not working anymore

![IMAGE 2022-01-31 18:01:31](https://user-images.githubusercontent.com/11976694/151838715-ce705c69-1958-49df-813c-ec1f220f0362.jpg)

Relates https://github.com/ioBroker/ioBroker.js-controller/issues/1707

**Comment by GermanBluefox** [comment]
Done in 5.3.0
