### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by RayJayVaughn** [ioBroker/ioBroker.admin#1304]
**Describe the bug**  
The Webinterface of Iobroker could not be opened.

**To Reproduce**  
1. Go to IpAdress:8081
2. Click on Enter
3. See error "Error in GUI!"

**Expected behavior**  
Well, the GUI should be opened in a normal way.

**Screenshots & Logfiles**  

index.js:18 iobroker.admin@5.2.3
socket.io.js:59 [2022-02-01T15:21:29.372Z] Try to connect
:8081/static/js/13.f387ad79.chunk.js:1 Failed to load resource: net::ERR_CACHE_READ_FAILURE
react-dom.production.min.js:216 ChunkLoadError: Loading chunk 13 failed.
(error: http://192.168.2.131:8081/static/js/13.f387ad79.chunk.js)
    at Function.u.e (VM9:1:3981)
    at App.js:68:36
    at V (react.production.min.js:18:52)
    at Zi (react-dom.production.min.js:269:22)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

Loading chunk 13 failed. (error: http://192.168.2.131:8081/static/js/13.f387ad79.chunk.js)
ChunkLoadError: Loading chunk 13 failed.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}(error: http://192.168.2.131:8081/static/js/13.f387ad79.chunk.js)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Function.u.e (http://192.168.2.131:8081/:1:3981)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.2.131:8081/static/js/main.4ec45a8c.chunk.js:2:1086526function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at V (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5680544)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5670728)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5657389)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5657317)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5657180)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at zl (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5654146)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5603640function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.2.131:8081/static/js/5.6300204f.chunk.js:2:5686850)

**Versions:**  
PLATTFORM: LINUX
RAM: 3.7 GB
NODE.JS: V12.22.2
NPM: 6.14.13 

**Additional context**  
After Reloading everything seemed to be in order. But within the console tab there was:

:8081/adapter/deconz/deconz.png:1 GET http://192.168.2.131:8081/adapter/deconz/deconz.png net::ERR_CACHE_READ_FAILURE 304 (OK)

**Comment by GermanBluefox** [comment]
This is only temporary error and could be solved by the cache cleaning.

**Comment by ChristianHohman** [comment]
problem stays. Cache clearing in Browser?

**Comment by RayJayVaughn** [comment]
That is what finally made it work.....
