### ISSUE TITLE
Dark Theme. Button colors are low contrast

### ISSUE THREAD

**Issue by Makeitlviv** [ioBroker/ioBroker.admin#1308]
**Describe the bug**  
Regular buttons on the Dark theme are low contrasted. Used background #E0E0E0 and foreground #FFFFFF. There are too similar colors and it is not visible.
[https://i.imgur.com/aOqL9hI.png](https://i.imgur.com/aOqL9hI.png)

**To Reproduce**  
Admin driver 5.2.3 (stable)
1. Set the dark theme for admin'
2. Click on the 'Backup' point in the side panel (a similar problem with Alias Manager)
3. See button 'iobroker start backup' as background #E0E0E0 and foreground #FFFFFF.
4. Wait for 5-10 sec. Button 'iobroker start backup' has been self-updated to background #3399CC and foreground #FFFFFF. 

Case 2:
Admin driver 5.2.3 (stable)
1. Set the dark theme for admin'
2. Install Alias adapter
3. Click on the 'Alias-Manager' point in the side panel (a similar problem with Alias Manager)
4. Navigate to 'Manage Aliases'

The button 'New Alias' is low contrasted
[https://i.imgur.com/8afRmqJ.png](https://i.imgur.com/8afRmqJ.png)

**Expected behavior**  
The button should be more contrasted (like background #3399CC and foreground #FFFFFF)

**Screenshots & Logfiles**  
https://i.imgur.com/8afRmqJ.png
https://i.imgur.com/aOqL9hI.png

**Versions:**  
 - Adapter version: 5.2.3 stable
 - JS-Controller version: 3.3.22
 - Node version: 14.18.1
 - Operating system: Raspbian 11

**Additional context**

**Comment by GermanBluefox** [comment]
Requests are placed by according adapters:
- https://github.com/simatec/ioBroker.backitup/issues/614
- https://github.com/sbormann/ioBroker.alias-manager/issues/27
