### ISSUE TITLE
Dark Theme - red Text in dialog not readable if precondition is not fulfilled

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1310]
**Describe the bug**  
I just wanted to install an adapter and one precondition was not fulfilled. The information in the dialog is not readable:
![grafik](https://user-images.githubusercontent.com/25422320/152658362-c66df82d-7095-4938-9f7d-600970517cb4.png)

The is  how it looks like in the light mode
![grafik](https://user-images.githubusercontent.com/25422320/152658423-4edee9fc-ad84-47d0-9974-d1c066e47533.png)

**Expected behavior**  
The red colour of the text needs to be adapted to the dark mode

**Versions:**  
Admin 5.2.3

**Comment by GermanBluefox** [comment]
Fixed in 5.3.0

**Comment by Feuer-sturm** [comment]
Admin 5.3.0

With new admin it looks like this:
![grafik](https://user-images.githubusercontent.com/25422320/153483524-fb87508e-535b-468f-a8d0-42e26e610a62.png)


Issue is fixed
