### ISSUE TITLE
Enum translations not working in "Enums-Tab" for name and description

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1315]
**Describe the bug**  

- Name is not translated in enum tab
- description doesn't recognise translated objects

**Screenshots & Logfiles**  

<img width="836" alt="Screenshot 2022-02-11 at 10 16 36" src="https://user-images.githubusercontent.com/1959049/153565529-790055c5-be93-4f8b-bda6-63de4afdc617.png">

<img width="633" alt="Screenshot 2022-02-11 at 10 17 30" src="https://user-images.githubusercontent.com/1959049/153565770-1d7f393d-0139-46fd-932b-3fe88a386ed4.png">

**Versions:**  

 - Adapter version: 5.3.0
 - JS-Controller version: 4.0.5

**Additional context**  

Enum has translated name:

```json
{
  "_id": "enum.rooms",
  "common": {
    "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDI0IDI0IiB3aWR0aD0iMjRweCI+DQogICAgPHBhdGggZmlsbD0iY3VycmVudENvbG9yIiBkPSJNMTIgNS42OWw1IDQuNVYxOGgtMnYtNkg5djZIN3YtNy44MWw1LTQuNU0xMiAzTDIgMTJoM3Y4aDZ2LTZoMnY2aDZ2LThoM0wxMiAzeiIvPg0KPC9zdmc+",
    "name": {
      "en": "Rooms",
      "de": "Räume",
      "ru": "Комнаты",
      "pt": "Quartos",
      "nl": "Kamers",
      "fr": "Pièces",
      "it": "Camere",
      "es": "Habitaciones",
      "pl": "Pokoje",
      "zh-cn": "客房"
    },
    "desc": {
      "en": "List of the rooms",
      "de": "Liste der Räumen",
      "ru": "Список комнат",
      "pt": "Lista dos quartos",
      "nl": "Lijst met kamers",
      "fr": "Liste des chambres",
      "it": "Elenco delle stanze",
      "es": "Lista de las habitaciones",
      "pl": "Lista pokoi",
      "zh-cn": "房间清单"
    },
    "members": [],
    "dontDelete": true
  },
  "type": "enum",
  "acl": {
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "object": 1911
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1605876455777
}
```

**Comment by Feuer-sturm** [comment]
Admin 5.3.2

@GermanBluefox 
![grafik](https://user-images.githubusercontent.com/25422320/159065883-5a95ca60-ec3f-432a-82b0-05a188b08c28.png)
With new admin 5.3.2 the title is not translated correctly


Description is now corret:
![grafik](https://user-images.githubusercontent.com/25422320/159066106-b0998663-1462-4b2d-a15d-fe04c20bb959.png)
