### ISSUE TITLE
Show number of data points

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1318]
In Admin v4, the number of subordinate data points could be displayed via the expert view. With v5 that's probably gone.

**Comment by darkiop** [comment]
Find this very useful, especially in the process of creating an alias (before/after comparison with an old structure) and when cleaning up in general (reduce objects, recognize which adapter is currently responsible for a large number).

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1115
