### ISSUE TITLE
Optical fixes in v5 object view

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1319]
![grafik](https://user-images.githubusercontent.com/205119/153706867-cd817938-6d72-41ab-9d87-e9bb3b691dbd.png)

**Comment by GermanBluefox** [comment]
Colors are slightly changed in 5.3.2
![image](https://user-images.githubusercontent.com/4582016/155027601-44b1da3d-06b1-4858-9078-d720afa1675c.png)

**Comment by darkiop** [comment]
Thank you very much ;) my inner monk came through :D If I noticed anything else I would attach it to this issue.

**Comment by Apollon77** [comment]
>  I would attach it to this issue.

No, please create new tickets for the new topics because this one will be closed now :-)
