### ISSUE TITLE
Backup/Restore von Adapter Einstellungen

### ISSUE THREAD

**Issue by jensweigele** [ioBroker/ioBroker.admin#132]
Im Yahka-Repository gibt es einen Request, Einstellungen zu sichern/wiederherzustellen (https://github.com/jensweigele/ioBroker.yahka/issues/22).
Meiner Meinung nach sollte das in der Admin-Oberfläche implementiert werden.
Ich würde mir das auch mal anschauen und ggfls. einen Pull-Request einreichen. Die Frage ist, auf welcher Quellcode-Basis ich das umsetzen soll. 
Für mich sieht es so aus, als gäbe es gerade einen größeren Umbruch was Design/Libraries angeht!?

**Comment by GermanBluefox** [comment]
Momentan arbeiten wir an diesem Branch:
https://github.com/ioBroker/ioBroker.admin/tree/3.0.1

Auf "main" werden keine Pull Requests akzeptiert.

2018-01-05 11:48 GMT+01:00 jensweigele <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Admin3 ist jetzt master

**Comment by GermanBluefox** [comment]
@jensweigele  Irgendwas neues hier?

**Comment by GermanBluefox** [comment]
Done
