### ISSUE TITLE
The Growatt Adapter readme is no longer displayed

### ISSUE THREAD

**Issue by PLCHome** [ioBroker/ioBroker.admin#1320]
If the readme is to be displayed, an error message appears
DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('ioBroker@****.de') is not a valid name.

Url: <server>/#tab-adapters/readme/growatt

![image](https://user-images.githubusercontent.com/29116097/153842061-d842a92d-53d0-457b-b9ab-a0f334ca8880.png)

- Growatt verion 1.1.7 but redme from 1.1.3 is loaded
- Admin 5.3.0
- JS-Controller version: 4.0.8
- nodejs 14.19.0
- OS: raspian buster

I tried to fix the error by updating the readme and publishing your new adapter. Unfortunately the error is still there. What I don't understand either, the content of the loaded readme is still 1.1.3 and not the current 1.1.7

This is loaded:
![image](https://user-images.githubusercontent.com/29116097/153843528-1ca20f8f-29d8-4de3-952a-49e330eb7e3d.png)

![image](https://user-images.githubusercontent.com/29116097/153843746-f911a5e6-1a1e-483e-83cf-ba1fce0c023b.png)

![image](https://user-images.githubusercontent.com/29116097/153843678-cb7b254f-687f-4f2c-9b28-15fd03494317.png)

![image](https://user-images.githubusercontent.com/29116097/153843999-322ab67c-8fc2-432d-81a8-df847f97ec88.png)

This is on NPM and github:
![image](https://user-images.githubusercontent.com/29116097/153844293-032c34f0-5200-40c5-8262-bef87ae7dd4d.png)

![image](https://user-images.githubusercontent.com/29116097/153845031-3287360e-19ed-4013-8c36-4d36a254633b.png)

I tried to solve the problem. So the email has changed, but ioBroker is not interested in it since yesterday.

![image](https://user-images.githubusercontent.com/29116097/153844655-00a5c44d-557f-4029-95e0-138051134852.png)

What do I have to do so that the current version of the readme is displayed?

**Comment by Apollon77** [comment]
The MD File is read and parsed into HTML and this is then added as a new document. In the Readme.md there is <-email-> which is tried to add as html element which is not valid one ... SO the readme.d should be fixed to now include this invalid tag.

Github do not houd it because it simply uses html tags as is I assume

**Comment by PLCHome** [comment]
Thanks, but I corrected that with the tag and the e-mail, it was stored there by the adapter creator.
But why is the old file from version 1.1.3 still being loaded and not the current file from iobroker.net?

**Comment by PLCHome** [comment]
**What can I do to solve the problem?**
I have now done the following:

- Adjusted Read.me on Sunday
- unstable version with new Read.me released on Sunday
- stable version with new Read.me released on Monday

It still loads the broken file and not the repaired one
**What can I?**

**Comment by PLCHome** [comment]
@Apollon77 
I corrected and updated the readme nine days a ago at npm and github.
The broken 1.1.3 is always loaded. 
Could you please have a look and update the help on your servers.

![image](https://user-images.githubusercontent.com/29116097/155010945-2fc6da43-ff10-451d-ab02-c2ac11a6d175.png)

![image](https://user-images.githubusercontent.com/29116097/155011763-2e0febe7-f897-4396-87e3-427a61aa25ef.png)

**Comment by PLCHome** [comment]
@ldittmar81 

> @PLCHome the files are copied and translated on the ioBroker server every 3 days. Maybe you must to wait.

define again 3 days please

**Comment by PLCHome** [comment]
@Apollon77 @GermanBluefox 

Don't you have the possibility to repair the translated file?
Can't you load the latest readme or delete the old files from your server?
I fixed the "bug" 22 days ago now. Because I have bluefox as a collaborator at npm, I cannot revoke and delete the versions. I also doubt that this will change anything.

It's not about me that he processes the e-mail address! I would like the readme to be displayed again.

**Comment by PLCHome** [comment]
Now it works, thanks
