### ISSUE TITLE
Configure visible columns is broken

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#1321]
**Describe the bug**  
If I do this...

![image](https://user-images.githubusercontent.com/3794098/153875167-4b551267-955a-42ca-a134-adaa3d27690b.png)

I get this...

![image](https://user-images.githubusercontent.com/3794098/153875242-48c2074b-7bba-4bd7-9e40-79d6b80722d6.png)

But let's say I want to see 'Role' of each state, so I try this...

![image](https://user-images.githubusercontent.com/3794098/153875413-646e78bd-ed19-423c-a289-e33f5d532a23.png)

... which yields this...

![image](https://user-images.githubusercontent.com/3794098/153875483-4244df5b-8d7c-4dba-91d0-2e88fb80d073.png)

There are never any horizontal scrollbars so that's it.

Refreshing the page after changing these options does not change the outcome.

**To Reproduce**  
Mess with 'Configure visible columns' as described above.

**Expected behavior**  
The columns chosen should be shown.

**Screenshots & Logfiles**  
See above.

**Versions:**  
 - Adapter version: 5.2.3
 - JS-Controller version: 3.3.22
 - Node version: v12.22.5
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Comment by GermanBluefox** [comment]
You must set width of "name" to see "type". And so on

**Comment by raintonr** [comment]
OK. So this...

![image](https://user-images.githubusercontent.com/3794098/155026808-e8af3cdc-039e-4414-8974-94f69b398678.png)

... yields this...

![image](https://user-images.githubusercontent.com/3794098/155026865-3ff12a52-604c-4a5d-9b1b-3fe008be2c46.png)

... which I would still call broken.

Looks like 'ID' column is too wide but changing it's width to '100' does nothing.

**Comment by Feuer-sturm** [comment]
I can reprodce it with admin 5.3.7 as well
![grafik](https://user-images.githubusercontent.com/25422320/163057643-32f40532-20ef-4df2-bba6-de2c579e473a.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox I just checked this issue with Admin 6.1.2 

![grafik](https://user-images.githubusercontent.com/25422320/175386571-c5ce8b3d-3d1f-4f50-ad49-bf52998a3719.png)

![grafik](https://user-images.githubusercontent.com/25422320/175386495-d3dae7c9-376e-479f-bcbb-1ffd655e6508.png)
My expectation would be that the title is above the coloumn.

**Comment by Feuer-sturm** [comment]
@GermanBluefox I think we can close this issue because the feature was removed in Admin6
