### ISSUE TITLE
Instance namespace and id not passed to jsonCustom functions

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.admin#1323]
**Is your feature request related to a problem? Please describe.**
Migrating mqtt-client adapter to current ioBroker APIs I discovered that jsonCustom functions can not access the instance namespace or id.

**Describe the solution you'd like**
Functions inside **jsonCustoms** are already called with an **instanceObj**. However, it seems this object does not contain the instance id or any string the id could be derived from.
In **custom_m.html** instance id could be derived from **instanceObj._id**.
It would be nice to have **._id** (adapter namespace) aswell as **.instance** (adapter id) added to instanceObj

**Comment by GermanBluefox** [comment]
Do you have use case for that?

**Comment by GermanBluefox** [comment]
I added 
'_instance' - instance number
in 5.3.2

**Comment by Pmant** [comment]
> Do you have use case for that?

Yes, I stumbled accross this while working on modernizing mqtt-client adapter. When converting ioBroker ids to MQTT topics under adapters namespace it needs to remove adapters own namespace from ids. 
For now this is done with a regex but this potentially also removes namespaces of other mqtt-client instances. This is not a big issue but I was surprised instanceObj did not contain the actual instance number. 

Ty for the fix.

**Comment by Pmant** [comment]
Did not test but I think for using it in json**Custom**.json **_instance** needs to be added here aswell.
https://github.com/ioBroker/ioBroker.admin/blob/5ba62e76cabd73c88e5459db54eb22586cad3cd1/src-rx/src/components/JsonConfigComponent/ConfigGeneric.js#L310

**Comment by GermanBluefox** [comment]
Custom has whole instanceObj and this object should have `._id` in it.

**Comment by GermanBluefox** [comment]
I added _id to instanceObj: https://github.com/ioBroker/ioBroker.admin/commit/7ef0ebde5d1ea065edf4b9c6ea3141d3228af73b
