### ISSUE TITLE
Diverse kleine Fehler in den Host Base Settings

### ISSUE THREAD

**Issue by MarkBpunkt** [ioBroker/ioBroker.admin#1324]
In den Host Base Settings sind aus meiner Sicht ein paar kleine Fehler:

1. Ändert man in den Sektionen "Objects" oder "States" etwas an den Parametern "Size factor", "minimum size" etc., wird der Button "Save & Close" nicht aktiv. Man muss erst eine andere Option hin- und her ändern (z.B. "ignore read errors"), damit man speichern kann.

2. Man darf den "Auto-compress size factor" auf 1 ändern. Abgesehen davon, dass eine "1" hier keinen Sinn ergibt, startet danach ioBroker nicht mehr, bis man den Wert in der "iobroker.json" wieder auf >1 ändert.

3. Ändert man in der "Log"-Sektion den Parameter "Maximal size of one file", so wird dieser nach Speichern und erneut Öffnen nicht mehr angezeigt, wahrscheinlich, weil in der "iobroker.json" dann der Wert als String inkl. "MB" abgespeichert wird.

![grafik](https://user-images.githubusercontent.com/99531337/154857337-14ce77f0-8fff-49fb-94e8-2d80aa5f7dab.png)

![grafik](https://user-images.githubusercontent.com/99531337/154857312-4fa796fe-d66b-49bc-9572-d1d6ab8e5400.png)

Nötige Limits -> siehe Forum Links!!

Siehe auch:
https://forum.iobroker.net/post/765866
https://forum.iobroker.net/post/765875

ioBroker unter Docker (buanet Image)
js-controller  4.0.15
NPM    v6.14.16
Node.js    v14.19.0

**Comment by GermanBluefox** [comment]
Fixed in 5.3.1
