### ISSUE TITLE
jsonConfig - defaultFunc not working for table items

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1326]
**Describe the bug**  

When using jsonConfig.json an item could be assigned the attribute "defaultFunc" specifying a function to calculate an return a default value for an item. While this is working for normal items (i.e. text fields) it does not show any effect for items of a table (i.e. text fields in a table row).

I would expect that new table rows added using plus button are defaultted to the value returned by the defaultFunc function.

**To Reproduce**  

1. create a new using npx @iobroker/create-adapter
2. add json gui attribute to io-package.json
 ``` 		
"adminUI": {
 	"config": "json"
 },
```
3. create the following jsonConfig.json
```
{
    "i18n": true,
    "type": "tabs",
    "items": {
        "tab1": {
            "type": "panel",
            "label": "Tab 1",
            "items": {
                "myText": {
                    "type": "text",
                    "sm": 12,
                    "md": 6,
                    "lg": 6,
                    "label": "My Text",
                    "help": "my text help",
                    "defaultFunc": "return('abc')"
                },
                "myTable": {
                    "type": "table",
                    "sm": 12,
                    "md": 12,
                    "lg": 12,
                    "label": "My Table",
                    "items": [
                        {
                            "type": "checkbox",
                            "attr": "enabled",
                            "width": "10%",
                            "title": {
                                "en": "Table Chkbox"
                            },
                            "filter": false,
                            "sort": false,
                            "default": false
                        },
                        {
                            "type": "text",
                            "attr": "ip",
                            "width": "35%",
                            "title": {
                                "en": "Table Text"
                            },
                            "filter": true,
                            "sort": true,
                            "defaultFunc": "return( 'abc')"
                        }
                    ]
                }
            }
        }
    }
}
```
4.  create a new instance of adapter and open config page
5. The field "My Text" should be prepoluated with "abc" while adding new rows to table "My Table" will add all rows with empty field "Table Text"

**Expected behavior**  
I would expect that the filed "Table Text" is initialized to "abc" for new rows.

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: Admin 5.3.1
 - JS-Controller version: 3.3.22 - using dev-server
 - Node version: v14.19.0
 - Operating system: Windows 10

**Additional context**

**Comment by GermanBluefox** [comment]
![JsonConfig](https://user-images.githubusercontent.com/4582016/171840391-f251721b-06c5-48fa-887b-a6880e438434.gif)

![image](https://user-images.githubusercontent.com/4582016/171840425-94d2a6c8-49c3-4c3a-b440-ca90c82ddb21.png)

I added 2 new variables for tables: `arrayIndex` and `globalData`

In table mode the variable `data` represents only one line of table
