### ISSUE TITLE
Admin 2.x: Adapterliste lädt nicht mehr nach Update von Adaptern

### ISSUE THREAD

**Issue by robdg80** [ioBroker/ioBroker.admin#133]
Im Admin 2.x gibt es Probelm mit der Adapterliste
siehe auch [hier](https://github.com/ioBroker/ioBroker/issues/30) oder [hier](http://forum.iobroker.net/viewtopic.php?p=110633#p110633)

Es gibt eine Fehleranalyse vom Nutzer fsjoke  dazu:
http://forum.iobroker.net/viewtopic.php?p=110633#p110608

Das Problem wird dadurch verursacht, das einige Adapter (Flot 1.7.0, Chromecast 1.4.0, ...) aktualisiert wurden und damit eine andere Titel Eigenschaft bekommen:
> "title": {
>           "en": "Flot Charts",
>           "de": "Flot-Diagrammen",
>           "ru": "Графики c Flot",
>           "pt": "Flot Charts",
>           "nl": "Flot charts",
>           "fr": "Graphiques des Flot",
>           "it": "Grafici Flot",
>           "es": "Gráficos de Flot",
>           "pl": "Wykresy Flot"
>         }
> 
> Das versteht adminAdapter.js (in Zeile 665) nicht!
> Es glaubt dass title ein string (und kein Objekt) ist und wendet replace an.
> Das erzeugt einen Fehler welcher die ganze Prozedur die Adapter zu listen stoppt!

Das Problem tritt wahrscheinlich jetzt mit mehreren Adaptern auf, welche (vermutlich) auf Admin 3.x vorbereitet werden (Flot 1.7.0, chromecast, ...).

Es wäre schön, wenn entweder Admin 3x bald aktiv wird oder es noch einen Patch für Admin 2x gibt.

**Comment by GermanBluefox** [comment]
Sorry. Support of Admin2 closed.
