### ISSUE TITLE
#tab-users not working

### ISSUE THREAD

**Issue by KanzuTachiba** [ioBroker/ioBroker.admin#1331]
When I click on Users in Admin Panel, ioBroker crashes.

Screenshot of Error Page:
![image](https://user-images.githubusercontent.com/100464313/155836060-3e6b5af8-7e0c-4a01-9fa0-f931b5b004f6.png)

Browser-Console error text:
```
index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-02-26T08:00:31.001Z] Try to connect
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 getInstances: 3
instrument.ts:125 Translation for word "Enabled" in "de" was ignored: existing = "aktiviert", new = Aktiviert
(anonymous) @ instrument.ts:125
instrument.ts:125 Translation for word "users permissions" in "de" was ignored: existing = "Gruppen-Rechte", new = Benutzerberechtigungen
(anonymous) @ instrument.ts:125
socket.io.js:59 [2022-02-26T08:01:34.600Z] Try to connect
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
[DOM] Password field is not contained in a form: (More info: <URL>) 
translate.js:24 "Backitup": {"en": "Backitup", "de": "Backitup", "ru": "Backitup", "pt": "Backitup", "nl": "Backitup", "fr": "Backitup", "es": "Backitup", "pl": "Backitup", "it": "Backitup", "zh-cn": "Backitup"},
translate.js:24 "http": {"en": "http", "de": "http", "ru": "http", "pt": "http", "nl": "http", "fr": "http", "es": "http", "pl": "http", "it": "http", "zh-cn": "http"},
translate.js:24 "https": {"en": "https", "de": "https", "ru": "https", "pt": "https", "nl": "https", "fr": "https", "es": "https", "pl": "https", "it": "https", "zh-cn": "https"},
translate.js:24 "1.x": {"en": "1.x", "de": "1.x", "ru": "1.x", "pt": "1.x", "nl": "1.x", "fr": "1.x", "es": "1.x", "pl": "1.x", "it": "1.x", "zh-cn": "1.x"},
translate.js:24 "2.x": {"en": "2.x", "de": "2.x", "ru": "2.x", "pt": "2.x", "nl": "2.x", "fr": "2.x", "es": "2.x", "pl": "2.x", "it": "2.x", "zh-cn": "2.x"},
translate.js:24 "WhatsApp": {"en": "WhatsApp", "de": "WhatsApp", "ru": "WhatsApp", "pt": "WhatsApp", "nl": "WhatsApp", "fr": "WhatsApp", "es": "WhatsApp", "pl": "WhatsApp", "it": "WhatsApp", "zh-cn": "WhatsApp"},
translate.js:24 "URL": {"en": "URL", "de": "URL", "ru": "URL", "pt": "URL", "nl": "URL", "fr": "URL", "es": "URL", "pl": "URL", "it": "URL", "zh-cn": "URL"},
translate.js:24 "Access token: ": {"en": "Access token: ", "de": "Access token: ", "ru": "Access token: ", "pt": "Access token: ", "nl": "Access token: ", "fr": "Access token: ", "es": "Access token: ", "pl": "Access token: ", "it": "Access token: ", "zh-cn": "Access token: "},
translate.js:24 "Authorize this app by visiting this url: ": {"en": "Authorize this app by visiting this url: ", "de": "Authorize this app by visiting this url: ", "ru": "Authorize this app by visiting this url: ", "pt": "Authorize this app by visiting this url: ", "nl": "Authorize this app by visiting this url: ", "fr": "Authorize this app by visiting this url: ", "es": "Authorize this app by visiting this url: ", "pl": "Authorize this app by visiting this url: ", "it": "Authorize this app by visiting this url: ", "zh-cn": "Authorize this app by visiting this url: "},
translate.js:24 "Enter the code from that page here": {"en": "Enter the code from that page here", "de": "Enter the code from that page here", "ru": "Enter the code from that page here", "pt": "Enter the code from that page here", "nl": "Enter the code from that page here", "fr": "Enter the code from that page here", "es": "Enter the code from that page here", "pl": "Enter the code from that page here", "it": "Enter the code from that page here", "zh-cn": "Enter the code from that page here"},
translate.js:24 "http": {"en": "http", "de": "http", "ru": "http", "pt": "http", "nl": "http", "fr": "http", "es": "http", "pl": "http", "it": "http", "zh-cn": "http"},
translate.js:24 "https": {"en": "https", "de": "https", "ru": "https", "pt": "https", "nl": "https", "fr": "https", "es": "https", "pl": "https", "it": "https", "zh-cn": "https"},
translate.js:24 "1.x": {"en": "1.x", "de": "1.x", "ru": "1.x", "pt": "1.x", "nl": "1.x", "fr": "1.x", "es": "1.x", "pl": "1.x", "it": "1.x", "zh-cn": "1.x"},
translate.js:24 "2.x": {"en": "2.x", "de": "2.x", "ru": "2.x", "pt": "2.x", "nl": "2.x", "fr": "2.x", "es": "2.x", "pl": "2.x", "it": "2.x", "zh-cn": "2.x"},
instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.501acaca.chunk.js:2:5595786)
    at 6.501acaca.chunk.js:2:5600621
    at Po (6.501acaca.chunk.js:2:5611663)
    at Zi (6.501acaca.chunk.js:2:5657695)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at s.m.setState (6.501acaca.chunk.js:2:5664084)
    at 9.a078e0d6.chunk.js:1:27236
(anonymous) @ instrument.ts:125
instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.501acaca.chunk.js:2:5595786)
    at 6.501acaca.chunk.js:2:5600621
    at Po (6.501acaca.chunk.js:2:5611663)
    at Zi (6.501acaca.chunk.js:2:5657695)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at s.m.setState (6.501acaca.chunk.js:2:5664084)
    at 9.a078e0d6.chunk.js:1:27236
(anonymous) @ instrument.ts:125

```

**Versions:**  
 - Adapter version: 5.3.1
 - JS-Controller version: 4.0.15
 - Node version: 12.22.10
 - Operating system: Linux Debian11

**Comment by rjb752** [comment]
Got the same issue with the latest v6 Docker image (pushed 2 days ago) in a clean installation

**Comment by Lyxon1337** [comment]
same issue

docker container v6.1.0
Admin 5.3.1
JS-Controller 4.0.18
node.js 14.19.0
npm 6.14.16

![grafik](https://user-images.githubusercontent.com/91346264/157157797-0977bc70-aaa1-4cee-b3e1-7b177fa3ec7c.png)

**Comment by Lyxon1337** [comment]
same issue

docker container v6.1.0
build 2022-03-07T23:45:56+00:00
Admin 5.3.1
JS-Controller 4.0.19
node.js 14.19.0
npm 6.14.16

![grafik](https://user-images.githubusercontent.com/91346264/157228207-f45674dc-567a-47d6-9a72-4aa365ead4c4.png)

**Comment by Lyxon1337** [comment]
new test...

open older Backup and copy all data from /opt/... (with JS-Controller 3.3.22)
start this with the 6.1.0 from last test... works...
After this i only change the name "admin"

Than from Portainer:
  pkill -u iobroker
  iobroker update
  iobroker upgrade self
  iobroker fix
to update js-controller from 3.3.22 to 4.0.19...

After this... the user tabs works!

i don´t know why...

**Comment by Araktos255** [comment]
same error:

`Adapter    "admin"        : 5.3.1    , installed 5.3.1
Adapter    "backitup"     : 2.3.3    , installed 2.3.3
Adapter    "canbus"       : 1.3.0    , installed 1.3.0
Adapter    "discovery"    : 2.7.5    , installed 2.7.5
Controller "js-controller": 4.0.21   , installed 4.0.21`

`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    tt UsersList.js:331
    promise callback*2101/s/o.updateData UsersList.js:329
    value UsersList.js:297
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    F scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    EventHandlerNonNull* scheduler.production.min.js:12
    u (index):1
    <anonymous> index.js:4
    u (index):1
    <anonymous> React
    u (index):1
    <anonymous> React
    u (index):1
    1513 main.22a9d49c.chunk.js:2
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.22a9d49c.chunk.js:2
[instrument.ts:125:32](http://192.168.2.128:8081/src/instrument.ts)
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    tt UsersList.js:331
    promise callback*2101/s/o.updateData UsersList.js:329
    value UsersList.js:297
    React 3
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 2
    F scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    EventHandlerNonNull* scheduler.production.min.js:12
    u (index):1
    <anonymous> index.js:4
    u (index):1
    <anonymous> React
    u (index):1
    <anonymous> React
    u (index):1
    1513 main.22a9d49c.chunk.js:2
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.22a9d49c.chunk.js:2`

**Comment by klein0r** [comment]
I've tested several combinations using the ioBroker [dev-server](https://github.com/ioBroker/dev-server).

- Admin 5.3.1 + js-controller 3.3.22 ✔️
- Admin 5.3.1 + js-controller 4.0.10 🚫 
- Admin 5.3.1 + js-controller 4.0.5 🚫 
- Admin 5.3.1 + js-controller 4.0.3 🚫 
- Admin 5.3.1 + js-controller 4.0.1 - unable to install
- Admin 5.3.1 + js-controller 4.0.0 - unable to install

Bad news: The issue is somewhere between 3.3.22 and 4.0
But that is a very large diff. Every new installation in 4.x is affected right now.

**Comment by Apollon77** [comment]
Can you show how the pre-created admin-user and admin-group objects look like ... And also ..  is the error really showing like in first post in "GitHub install dialog"?

**Comment by klein0r** [comment]
The issue is in this line: So it is caused by groups:

https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/UsersList.js#L331

So I've compared group definitions of [3.3.22](https://github.com/ioBroker/ioBroker.js-controller/blob/v3.3.22/io-package.json#L347-L358) with [4.x](https://github.com/ioBroker/ioBroker.js-controller/blob/86efdc1c1093da68412c92208cca6592ccdb5416/packages/controller/io-package.json#L205-L216):

Old:

```json
                "description": {
                    "en": "Can do everything with System",
                    "de": "Darf alles mit dem System machen",
                    "ru": "Может делать все с помощью системы",
                    "pt": "Pode fazer tudo com o sistema",
                    "nl": "Kan alles doen met System",
                    "fr": "Peut tout faire avec le système",
                    "it": "Può fare tutto con il sistema",
                    "es": "Puede hacer todo con System",
                    "pl": "Potrafi zrobić wszystko dzięki Systemowi",
                    "zh-cn": "可以用系统做任何事情"
                },
```

New:

```json
        "desc": {
          "en": "Can do everything with System",
          "de": "Darf alles mit dem System machen",
          "ru": "Может делать все с помощью системы",
          "pt": "Pode fazer tudo com o sistema",
          "nl": "Kan alles doen met System",
          "fr": "Peut tout faire avec le système",
          "it": "Può fare tutto con il sistema",
          "es": "Puede hacer todo con System",
          "pl": "Potrafi zrobić wszystko dzięki Systemowi",
          "zh-cn": "可以用系统做任何事情"
        },
```

``description`` has been renamed to ``desc`` (which is the correct name for descriptions). But the admin is still using the ``common.description`` fields:

https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/GroupEditDialog.js#L182

This also explains, why an upgraded installation has no problem. The objects aren't recreated or updated in that case.

**Comment by Apollon77** [comment]
In fact admin subles over a fix because "common-description" was never defined and was thats why adjusted in js-controller 4 ... noone found before release that admin uses this :-( We will need to fix admin

**Comment by klein0r** [comment]
@Apollon77 Sorry, wrong issue. I don't know if it was related to his. Moved my comments to #1337

**Comment by Apollon77** [comment]
duplicate #1337
