### ISSUE TITLE
Unable to set letsencrypt infos in Dialog

### ISSUE THREAD

**Issue by effello** [ioBroker/ioBroker.admin#1332]
**Describe the bug**  
It is not possible to type in email, domain, and path 

**Versions:**  
 - Adapter version: 5.3.1
 - JS-Controller version:  3.3.22 
 - Operating system: rasp linux

**Additional context**  
![error](https://user-images.githubusercontent.com/8028591/155847519-7eae0f84-8487-40b0-8a40-7d888d968c26.png)

**Comment by bkomac** [comment]
Same here. It looks like an js error?! So not possible to set Iobroker to use Letsencrypt certs.

**Comment by Feuer-sturm** [comment]
@effello @bkomac Can you please check with current version if this issue can be closed?
