### ISSUE TITLE
[Suggestion] jsonConfig: change formatting of tables

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1334]
**Is your feature request related to a problem? Please describe.**
The apperance ofjsonConfig based tables is a little bit confusing. Ist not a big problem bute a question of usability.

If a table column has the attribute "filter" set to true, the header of the column is coloured in grey (in difference to black) and the header could be overwritten with some text used as filter. This is likely confusing to unexperienced user as its not very clear what this overwriting does. I first assumed it to be input to new rows. But most confusing is the fact that the column header is not alway visible.

**Describe the solution you'd like**
The header of the tablecolumns should always be visible und normal colour (black).
If filtering is enabled a second line below (or above) the header line should be visible to enter the filter data.
The sort icon would be ok side by side with the header text (just as it is).

**Describe alternatives you've considered**
I do not see a real alternative satisfying my wish to always should the column header even when filtering is set to true.
Inserting the filter data using pop up or so would be possible but I do not think that the effort to implement this would be worth.

Pleas discuss / evanuate the suggestion.

**Comment by Apollon77** [comment]
For filter: or add a filter icon right aligned in the table header field and when you click on it then a filter input field appears?!

**Comment by mcm1957** [comment]
> For filter: or add a filter icon right aligned in the table header field and when you click on it then a filter input field appears?!

Would be OK for mee too.
Its only confusing to override the table header. At last for me.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/170563581-49560ef7-52b3-4985-b8a0-de84d363c2dc.png)
