### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by Rennbahn** [ioBroker/ioBroker.admin#1335]
**Describe the bug**  

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    tt UsersList.js:331
instrument.ts:125:32

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@Rennbahn Which admin version did you use? What did you do to trigger the error?

**Comment by Rennbahn** [comment]
I'm completly new in this field. I just installed  iobroker 5.3.1 in proxmox with ubuntu 21.10
Bud

**Comment by Rennbahn** [comment]
I tried to discover what is behind of all items...
Bud

**Comment by Feuer-sturm** [comment]
You can just make a screenshot or write down the menu item on which you click before the error raise.

**Comment by opa75** [comment]
Ich bin Neuling und weiß nicht ob ich mit meiner Meldung hier richtig bin.
Unter Expertenmodus im Iobroker habe ich im Adapter Host die Einstellungen geöffnet. Beim Reiter Log öffnete sich ein Tab im Browser mit den Hinweis "Error in GUI"
Anbei der Ausdruck von GUI:
`index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-03-03T08:13:24.974Z] Try to connect
instrument.ts:125 [ADAPTERS] getAdapters
instrument.ts:125 [ADAPTERS] getAdaptersInfo
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 [ADAPTERS] vis-materialdesign
2instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 Execute: upgrade alias-manager@1.2.6
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 STARTED: upgrade alias-manager@1.2.6
instrument.ts:125 [ADAPTERS] Render
3instrument.ts:125 cmdStdout
instrument.ts:125 timeout
5instrument.ts:125 cmdStdout
instrument.ts:125 
        
       Please add to "system.adapter.alias-manager" common.adminUI={"config":"materialize","tab":"materialize"}
(anonym) @ instrument.ts:125
instrument.ts:125 [ADAPTERS] Render
22instrument.ts:125 cmdStdout
instrument.ts:125 
        
       Please add to "system.adapter.alias-manager" common.adminUI={"config":"materialize","tab":"materialize"}
(anonym) @ instrument.ts:125
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 [ADAPTERS] vis-materialdesign
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 [ADAPTERS] vis-materialdesign
instrument.ts:125 cmdExit
instrument.ts:125 145768071
instrument.ts:125 0
5instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 Execute: upgrade javascript@5.3.0
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 STARTED: upgrade javascript@5.3.0
instrument.ts:125 [ADAPTERS] Render
3instrument.ts:125 cmdStdout
instrument.ts:125 timeout
8instrument.ts:125 cmdStdout
instrument.ts:125 
        
       Please add to "system.adapter.javascript" common.adminUI={"config":"materialize","tab":"html"}
(anonym) @ instrument.ts:125
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 
        
       Please add to "system.adapter.javascript" common.adminUI={"config":"materialize","tab":"html"}
(anonym) @ instrument.ts:125
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 [ADAPTERS] vis-materialdesign
instrument.ts:125 [ADAPTERS] Render
instrument.ts:125 [ADAPTERS] vis-materialdesign
30instrument.ts:125 cmdStdout
instrument.ts:125 cmdExit
instrument.ts:125 16918596
instrument.ts:125 0
3instrument.ts:125 [ADAPTERS] Render
index.js:20 iobroker.javascript@5.3.0 using theme "colored"
Prompt.js:15 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Prompt.js:16 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
Prompt.js:17 Help us to create open source project with reactJS!
Prompt.js:18 See you :)
socket.io.js:59 [2022-03-03T08:23:24.245Z] Try to connect
instrument.ts:125 Detected custom blockly: pushover
instrument.ts:125 Detected custom blockly: iot
instrument.ts:125 Detected custom blockly: cloud
instrument.ts:125 Detected custom blockly: iqontrol
instrument.ts:125 Socket: true
instrument.ts:125 
        
       Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jl (react-dom.production.min.js:280:177)
    at react-dom.production.min.js:149:163
    at Po (react-dom.production.min.js:176:171)
    at Go (react-dom.production.min.js:187:274)
    at qo (react-dom.production.min.js:186:173)
    at Ki (react-dom.production.min.js:269:427)
    at Ll (react-dom.production.min.js:250:347)
    at Cl (react-dom.production.min.js:250:278)
    at jl (react-dom.production.min.js:250:138)
    at gl (react-dom.production.min.js:243:163)
    at vl (react-dom.production.min.js:237:175)
    at eu (react-dom.production.min.js:285:27)
    at react-dom.production.min.js:289:301
    at Ol (react-dom.production.min.js:244:244)
    at ou (react-dom.production.min.js:289:287)
    at Object.t.render (react-dom.production.min.js:296:69)
    at HTMLScriptElement.a.onload (App.js:351:26)
(anonym) @ instrument.ts:125
react-dom.production.min.js:260 
        
       Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Jl (react-dom.production.min.js:280:177)
    at react-dom.production.min.js:149:163
    at Po (react-dom.production.min.js:176:171)
    at Go (react-dom.production.min.js:187:274)
    at qo (react-dom.production.min.js:186:173)
    at Ki (react-dom.production.min.js:269:427)
    at Ll (react-dom.production.min.js:250:347)
    at Cl (react-dom.production.min.js:250:278)
    at jl (react-dom.production.min.js:250:138)
    at gl (react-dom.production.min.js:243:163)
    at vl (react-dom.production.min.js:237:175)
    at eu (react-dom.production.min.js:285:27)
    at react-dom.production.min.js:289:301
    at Ol (react-dom.production.min.js:244:244)
    at ou (react-dom.production.min.js:289:287)
    at Object.t.render (react-dom.production.min.js:296:69)
    at HTMLScriptElement.a.onload (App.js:351:26)
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 ()
sentry.iobroker.net/api/56/store/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 403 ()
3instrument.ts:125 
        
       Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
(anonym) @ instrument.ts:125
instrument.ts:125 + subscribe 0_userdata.0.Onlinestatus
instrument.ts:125 + subscribe 0_userdata.0.Sternzeichen
instrument.ts:125 + subscribe 0_userdata.0.example_state
instrument.ts:125 > stateChange 0_userdata.0.Onlinestatus
instrument.ts:125 > stateChange 0_userdata.0.Sternzeichen
instrument.ts:125 > stateChange 0_userdata.0.example_state
instrument.ts:125 - unsubscribe 0_userdata.0.Onlinestatus
instrument.ts:125 - unsubscribe 0_userdata.0.Sternzeichen
instrument.ts:125 - unsubscribe 0_userdata.0.example_state
3instrument.ts:125 
        
       Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
(anonym) @ instrument.ts:125
instrument.ts:125 + subscribe 0_userdata.0.Onlinestatus
instrument.ts:125 + subscribe 0_userdata.0.Sternzeichen
instrument.ts:125 + subscribe 0_userdata.0.example_state
instrument.ts:125 > stateChange 0_userdata.0.Onlinestatus
instrument.ts:125 > stateChange 0_userdata.0.Sternzeichen
instrument.ts:125 > stateChange 0_userdata.0.example_state
instrument.ts:125 + subscribe 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.lowBat
instrument.ts:125 + subscribe 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.windowOpen
instrument.ts:125 > stateChange 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.lowBat
instrument.ts:125 > stateChange 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.windowOpen
instrument.ts:125 - unsubscribe 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.windowOpen
instrument.ts:125 - unsubscribe 0_userdata.0.Magnetkontakt.EG_Flur.EG_Flur_Haustür.lowBat
instrument.ts:125 - unsubscribe 0_userdata.0.example_state
instrument.ts:125 - unsubscribe 0_userdata.0.Sternzeichen
instrument.ts:125 - unsubscribe 0_userdata.0.Onlinestatus
instrument.ts:125 + subscribe alias.0.Fenster.EG_KiZ_Fenster
instrument.ts:125 + subscribe alias.0.Fenster.EG_SZ_Fenster
instrument.ts:125 + subscribe alias.0.Fenster.OG-KiZ_Fenster
instrument.ts:125 + subscribe alias.0.Fenster.OG_Bad_Fenster
instrument.ts:125 + subscribe alias.0.Fenster.OG_FZ_Fenster
instrument.ts:125 + subscribe alias.0.Fenster.OG_SZ_Fenster_Bach
instrument.ts:125 + subscribe alias.0.Fenster.OG_SZ_Fenster_Carport
instrument.ts:125 > stateChange alias.0.Fenster.EG_KiZ_Fenster
instrument.ts:125 > stateChange alias.0.Fenster.EG_SZ_Fenster
instrument.ts:125 > stateChange alias.0.Fenster.OG-KiZ_Fenster
instrument.ts:125 > stateChange alias.0.Fenster.OG_Bad_Fenster
instrument.ts:125 > stateChange alias.0.Fenster.OG_FZ_Fenster
instrument.ts:125 > stateChange alias.0.Fenster.OG_SZ_Fenster_Bach
instrument.ts:125 > stateChange alias.0.Fenster.OG_SZ_Fenster_Carport
instrument.ts:125 - unsubscribe alias.0.Fenster.OG_SZ_Fenster_Carport
instrument.ts:125 - unsubscribe alias.0.Fenster.OG_SZ_Fenster_Bach
instrument.ts:125 - unsubscribe alias.0.Fenster.OG_FZ_Fenster
instrument.ts:125 - unsubscribe alias.0.Fenster.OG_Bad_Fenster
instrument.ts:125 - unsubscribe alias.0.Fenster.OG-KiZ_Fenster
instrument.ts:125 - unsubscribe alias.0.Fenster.EG_SZ_Fenster
instrument.ts:125 - unsubscribe alias.0.Fenster.EG_KiZ_Fenster
instrument.ts:125 + subscribe alias.0.Tür.EG_Flur_Haustür
instrument.ts:125 + subscribe alias.0.Tür.EG_WZ_Balkontür
instrument.ts:125 + subscribe alias.0.Tür.KG_Büro_Sonja_Tür
instrument.ts:125 + subscribe alias.0.Tür.KG_Heizraum_Tür
instrument.ts:125 + subscribe alias.0.Tür.OG_RZ_Terassentür
instrument.ts:125 + subscribe alias.0.Tür.OG_WZ_Balkontür
instrument.ts:125 > stateChange alias.0.Tür.EG_Flur_Haustür
instrument.ts:125 > stateChange alias.0.Tür.EG_WZ_Balkontür
instrument.ts:125 > stateChange alias.0.Tür.KG_Büro_Sonja_Tür
instrument.ts:125 > stateChange alias.0.Tür.KG_Heizraum_Tür
instrument.ts:125 > stateChange alias.0.Tür.OG_RZ_Terassentür
instrument.ts:125 > stateChange alias.0.Tür.OG_WZ_Balkontür
instrument.ts:125 - unsubscribe alias.0.Tür.OG_WZ_Balkontür
instrument.ts:125 - unsubscribe alias.0.Tür.OG_RZ_Terassentür
instrument.ts:125 - unsubscribe alias.0.Tür.KG_Heizraum_Tür
instrument.ts:125 - unsubscribe alias.0.Tür.KG_Büro_Sonja_Tür
instrument.ts:125 - unsubscribe alias.0.Tür.EG_WZ_Balkontür
instrument.ts:125 - unsubscribe alias.0.Tür.EG_Flur_Haustür
instrument.ts:125 + subscribe alias.0.windowOpen.ACTUAL
instrument.ts:125 > stateChange alias.0.windowOpen.ACTUAL
instrument.ts:125 + subscribe alias.0.on.SET
instrument.ts:125 > stateChange alias.0.on.SET
instrument.ts:125 - unsubscribe alias.0.on.SET
instrument.ts:125 - unsubscribe alias.0.windowOpen.ACTUAL
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 
        
       TypeError: Cannot read properties of null (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLBodyElement.a (helpers.ts:98:17)
(anonym) @ instrument.ts:125
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.1.140:8081/adapter/min-maps/vs/loader.js.map konnte nicht geladen werden: Fetch through target failed: Frame not found; Fallback: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.1.140:8081/adapter/min-maps/vs/editor/editor.main.js.map konnte nicht geladen werden: Fetch through target failed: Frame not found; Fallback: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.1.140:8081/adapter/javascript/plugins/popper.js.map konnte nicht geladen werden: Fetch through target failed: Frame not found; Fallback: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by Feuer-sturm** [comment]
@opa75 Ich hab dein issue #1349 kommentiert. Hier passt er nicht rein, weil dein Fehler ein anderer ist, als im ersten Beitrag gemeldet worden ist (nur nach außen sieht es auf den ersten Bick mit GUI Error gleich aus).

**Comment by Feuer-sturm** [comment]
@Rennbahn Please verify with Admin 5.3.2
