### ISSUE TITLE
click on user (Benutzer) becomes an error

### ISSUE THREAD

**Issue by JFi71** [ioBroker/ioBroker.admin#1336]
output from console:
iobroker.admin@5.3.1 index.js:18:8
[2022-02-28T06:10:42.272Z] Try to connect instrument.ts:125:32
[ADAPTERS] getAdapters instrument.ts:125:32
[ADAPTERS] getAdaptersInfo instrument.ts:125:32
[ADAPTERS] Render 2 instrument.ts:125:32

Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
        Ec
        _c
        Po
        Zi
        jl
        Sl
        Cl
        zl
        Ka
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        Ga
        Ka
        Za
        pl
        enqueueSetState
        setState
    tt UsersList.js:331
instrument.ts:125:32

**Comment by Feuer-sturm** [comment]
Looks like this issue https://github.com/ioBroker/ioBroker.admin/issues/1337
Issue stays open to give @GermanBluefox perhaps additional information

**Comment by Feuer-sturm** [comment]
duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
