### ISSUE TITLE
Crash when "Benutzer" is clicked

### ISSUE THREAD

**Issue by PatFrotHH** [ioBroker/ioBroker.admin#1337]
I've done a fresh install of iobroker with the "curl -sL https://iobroker.net/install.sh | bash -" script. At first on an Raspberry but later also with an VM at Proxmox. After installing i clicked on "Benutzer" and iobroker crashs with the following info:

```
Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like
![image](https://user-images.githubusercontent.com/100585150/155987322-430e4367-923b-404e-9363-a6b0c6269c20.png)
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ec (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5595786)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5600621function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Po (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5611663)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5657695)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5643113)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5643041)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5642904)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at zl (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5639870)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5589364function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5672574)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5589141)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5589309)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5589244)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5637247)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Object.enqueueSetState (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5593262)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at s.m.setState (http://192.168.76.66:8081/static/js/6.501acaca.chunk.js:2:5664084)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.76.66:8081/static/js/9.a078e0d6.chunk.js:1:27236
```
The error repeats every time and with every installation when i click on "Benutzer". 

I use chrome and the Error shown there is: 

`Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.501acaca.chunk.js:2:5595786)
    at 6.501acaca.chunk.js:2:5600621
    at Po (6.501acaca.chunk.js:2:5611663)
    at Zi (6.501acaca.chunk.js:2:5657695)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at s.m.setState (6.501acaca.chunk.js:2:5664084)
    at :8081/static/js/9.a078e0d6.chunk.js:1:27236`

**Comment by Feuer-sturm** [comment]
@GermanBluefox Please check as well the linked issues if there are additional information which will help you fixing the bug.

**Comment by xadox-1st** [comment]
Same problem for me on #1358

**Comment by Chiller2019** [comment]
Same Problem by "Info"-Adpater.

Any resolutions?

**Comment by mg-projects** [comment]
Bei mir stürzt es ebenfalls ab dies ist aber ein React Fehler der neuen Oberfläche denn wenn ich auf die alte Ansicht im Admin Adapter klicke funktioniert der Benutzertab ganz normal. 

Und die Fehlermeldung "Can not find adapter name" lässt darauf schließen das der Adapter Name nicht entsprechend aufgelöst werden kann. 

Habe aber auch nun keine Lust immer zwischen der alten und neuen Ansicht umzuschalten nur um meinen Elektromeister und 2 Arbeitskollegen einen Account einzurichten.

**Comment by Feuer-sturm** [comment]
@mg-projects du könntest ein downgrade vom admin auf 5.3.0 machen bis der Fehler gefixt wurde. Die ganzen Meldungen kamen ja erst mit admin 5.3.1

**Comment by mg-projects** [comment]
@Feuer-sturm  habe eben ein Downgrade auf 5.3.0 gemacht jedoch kommt der Fehler immer noch ich werde zu Testzwecken das ganze gleich mal local auf einer VM aufsetzen um zu sehen ab welcher Version das auftaucht.

**Comment by xadox-1st** [comment]
A test with js.controller version 4.0.21 could not solve the problem either.

**Comment by klein0r** [comment]
Siehe auch #1331 - ich habe mein duplicate issue #1372 schon wieder geschlossen.

- Bei mir passiert das nur bei Neuinstallationen (z.B. mit dem dev-server)
- Genau die gleichen Versionen laufen einwandfrei in meiner live-Installation (upgrade auf diese Version)

Ich glaube daher, dass es irgendwie mit dem Setup-Prozess im js-controller zusammenhängen muss. Eventuell wurden Benutzernamen oder Gruppennamen übersetzt?

> Objects are not valid as a React child (found: object with keys {en, de, ru, pt, nl, fr, it, es, pl, zh-cn}). If you meant to render a collection of children, use an array instead.

**Comment by GitBaer** [comment]
Selbes Problem bei mir (Neuinstallation ohne Backup am 14.03.20) unter Debian 11 (Node.js: v14.19.0 / NPM: 6.14.16).

**Comment by klein0r** [comment]
@Apollon77 Sorry, I've commented in the wrong issue 😄

I've tested several combinations using the ioBroker [dev-server](https://github.com/ioBroker/dev-server).

- Admin 5.3.1 + js-controller 3.3.22 ✔️
- Admin 5.3.1 + js-controller 4.0.10 🚫 
- Admin 5.3.1 + js-controller 4.0.5 🚫 
- Admin 5.3.1 + js-controller 4.0.3 🚫 
- Admin 5.3.1 + js-controller 4.0.1 - unable to install
- Admin 5.3.1 + js-controller 4.0.0 - unable to install

Bad news: The issue is somewhere between 3.3.22 and 4.0
But that is a very large diff. Every new installation in 4.x is affected right now.

The issue is in this line: So it is caused by groups:

https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/UsersList.js#L331

So I've compared group definitions of [3.3.22](https://github.com/ioBroker/ioBroker.js-controller/blob/v3.3.22/io-package.json#L347-L358) with [4.x](https://github.com/ioBroker/ioBroker.js-controller/blob/86efdc1c1093da68412c92208cca6592ccdb5416/packages/controller/io-package.json#L205-L216):

Old:

```json
                "description": {
                    "en": "Can do everything with System",
                    "de": "Darf alles mit dem System machen",
                    "ru": "Может делать все с помощью системы",
                    "pt": "Pode fazer tudo com o sistema",
                    "nl": "Kan alles doen met System",
                    "fr": "Peut tout faire avec le système",
                    "it": "Può fare tutto con il sistema",
                    "es": "Puede hacer todo con System",
                    "pl": "Potrafi zrobić wszystko dzięki Systemowi",
                    "zh-cn": "可以用系统做任何事情"
                },
```

New:

```json
        "desc": {
          "en": "Can do everything with System",
          "de": "Darf alles mit dem System machen",
          "ru": "Может делать все с помощью системы",
          "pt": "Pode fazer tudo com o sistema",
          "nl": "Kan alles doen met System",
          "fr": "Peut tout faire avec le système",
          "it": "Può fare tutto con il sistema",
          "es": "Puede hacer todo con System",
          "pl": "Potrafi zrobić wszystko dzięki Systemowi",
          "zh-cn": "可以用系统做任何事情"
        },
```

``description`` has been renamed to ``desc`` (which is the correct name for descriptions). But the admin is still using the ``common.description`` fields:

https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/GroupEditDialog.js#L182

This also explains, why an upgraded installation has no problem. The objects aren't recreated or updated in that case.

**Comment by Apollon77** [comment]
In fact admin stumbles over a fix because "common.description" was never defined and was thats why adjusted in js-controller 4 in the default obejcts ... noone found before release that admin uses this :-( We will need to fix admin

**Comment by Apollon77** [comment]
So in fact the workaround for now would be to use Admin - Objects with enabled expert mode and adjust the user.* objects and change common.desc to common.description.

In fact Admin now needs to support both to be backward compatible in future :-(

**Comment by Apollon77** [comment]
In fact also other places in Admin user management needs to be fixed like https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/UsersList.js#L236
or https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/GroupEditDialog.js#L182 or https://github.com/ioBroker/ioBroker.admin/blob/a209f9e5017950dc991032a2666b5e29d56de59d/src-rx/src/components/Users/GroupEditDialog.js#L230-L241 ...........

**Comment by klein0r** [comment]
> So in fact the workaround for now would be to use Admin - Objects with enabled expert mode and adjust the user.* objects

I've tested that. After changing "desc" to "description" everything works like expected...

**Comment by Apollon77** [comment]
At least good news seems that when searching in Admin for common.description only "User" area seems (!!) affected

**Comment by Feuer-sturm** [comment]
@PatFrotHH @xadox-1st @Chiller2019 @mg-projects @klein0r @GitBaer Please verify with Admin 5.3.2

**Comment by Chiller2019** [comment]
> 

Same Error with Admin 5.3.2

**Comment by Apollon77** [comment]
same error??? really? can you please post it?

**Comment by Chiller2019** [comment]
![image](https://user-images.githubusercontent.com/50303399/159074488-abd1522f-f846-4f5b-be49-bb4501313131.png)

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ec (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5612145)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5616980function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Po (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5628022)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5674054)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5659472)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5659400)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5659263)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at zl (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5656229)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5605723function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5688933)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5605500)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5605668)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5605603)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5653606)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Object.enqueueSetState (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5609621)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at s.m.setState (https://iobroker.homeserver:8081/static/js/6.071e06c3.chunk.js:2:5680443)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at https://iobroker.homeserver:8081/static/js/9.de33cfd8.chunk.js:1:27262

**Comment by Apollon77** [comment]
Und der Fehler kommt wenn Du auf "Benutzer" klickst????

**Comment by Chiller2019** [comment]
Jap, auch nur da.

**Comment by Feuer-sturm** [comment]
I can confirm that the issue is still there with admin 5.3.2
Steps to reproduce
- New installation of iobroker (admin 5.3.1)
- Enter menu "Benutzer" -> error
- Update admin to 5.3.2
- Refresh browser site
- Enter menu "Benutzer" -> error

Browser console:
![grafik](https://user-images.githubusercontent.com/25422320/159080920-356a08bb-5800-4411-a9c1-7fda119a3e3d.png)

**Comment by GitBaer** [comment]
Yes, "Benutzer" is still not accessible.

**Comment by xadox-1st** [comment]
Same for me with Admin v5.3.3, too.

**Comment by DanVanBurgh** [comment]
Ich habe auch den Fehler mit Admin v5.3.1 im Docker einer frischen Installation. Komme nicht auf Benutzer.

**Comment by Apollon77** [comment]
The workaround is describe her in this thread https://github.com/ioBroker/ioBroker.admin/issues/1337#issuecomment-1070516238

**Comment by Feuer-sturm** [comment]
@all Please verify with Admin 5.3.4

On my new installation and after updating to admin 5.3.4 the issue is fixed if I click on menu "Benutzer"

**Comment by MichaelUray** [comment]
> @ALL Please verify with Admin 5.3.4
I can confirm that the problem does not show up anymore with this new version.

**Comment by Feuer-sturm** [comment]
@Apollon77 I think you can unpin this issue.
