### ISSUE TITLE
Anzeige des Benutzernamens während der Ersteinrichtung im Passwortdialog

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.admin#1338]
Hallo, 

ich habe am Wochenende ein iobroker Testsystem aufgesetzt. 
Dabei habe ich zum ersten Mal den Setup wizard gesehen. Tolle Sache. 

Dort habe ich auch schon ein Passwort vergeben. 

Beim Login war ich kurz stutzig geworden, da ich einen Benutzernamen eingeben sollte und vorher keinen vergeben durfte. 
Mein erster Versuch mit "admin" war erfolgreich (wenn man schon was mit dem iobroker arbeitet, weiß man es ja). 

Als iobroker Anfänger wäre ich hier vermutlich gescheitert. 

Evtl macht es Sinn, bei Vergabe des Passworts einen Hinweis zum Benutzer anzuzeigen (oder ggf schon einen Anlsgezu können). 
Hier ist das Problem Aufgekommem
[https://forum.iobroker.net/topic/52959/loginname](https://forum.iobroker.net/topic/52959/loginname)

**Comment by Feuer-sturm** [comment]
@GermanBluefox I just made a new installation. The current dialog looks like this. A username (admin) is not shown.

![grafik](https://user-images.githubusercontent.com/25422320/172705109-a94813f6-0107-4350-b4e8-f3749fc1f9fd.png)

Should I see the same data than in your screenshot or do I have to wait for a new version of the installer?

**Comment by GermanBluefox** [comment]
> Should I see the same data than in your screenshot or do I have to wait for a new version of the installer?

Just wait

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Until today the admin user name is not shown with a new iob installation
