### ISSUE TITLE
iobroker

### ISSUE THREAD

**Issue by spreiter938** [ioBroker/ioBroker.admin#1340]
Error in GUI!
![grafik](https://user-images.githubusercontent.com/70776848/156135383-f240a99c-cfe9-4a6a-8fac-8c71491f7450.png)

**Comment by Feuer-sturm** [comment]
@spreiter938 your picture is just an example and not the real error.

Please post the error which is shown in the browser console and and additional information like the adapter Version and the steps to reproduce the error.

**Comment by Feuer-sturm** [comment]
No more feedback. Issue closed.
