### ISSUE TITLE
Sometimes added adapter doesn't show up in instance list

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/ioBroker.admin#1341]
**Describe the bug**  
Sometimes one needs to actually refresh the browser window to get newly added adapter instances in the instance list (just switching to a different "tab" (e.g. "Log") doesn't help.

**To Reproduce**  
Steps to reproduce the behavior: (Ich erlaube mir, das auf Deutsch zu schreiben, da ich das ganze bereits im Telegram geschrieben habe)
1. ich habe auf einem neu aufgesetzten Raspi ganz frisch ioBroker installiert (mit dem 1-Zeiler)
2. den Setup Assistenten durchmachen
3. Discovery abgebrochen 
4. den smartmeter Adapter aus der Adapter-Liste installiert
5. Ging alles einwandfrei, nur leider gab es keine Instanz von smartmeter in der Instanz-Liste. 
6. smartmeter adapter nochmals installiert 
7. nun habe ich "smartmeter.1" als einzige Instanz
8. Am Schluss habe ich ein komplettes Browser Refresh (Ctrl-Shift-R) gemacht und siehe da, der smartmeter.0 war da.

**Expected behavior**  
Adding an adapter should **always** show it in the list of instances (if an instance was created, of course).

**Versions:** 
- Admin 5.3.1
```
Platformoperating system:linux
Architecture:arm
CPUs:4
Speed:900 MHz
Model:ARMv7 Processor rev 3 (v7l)
RAM:7.7 GB
System uptime:00:23:02
Node.js:v14.19.0
time:1646131933446
timeOffset:-60
adapters count:400
NPM:6.14.16
Disk size:219.8 GB
Disk free:214.5 GB
Uptime:00:09:59
Active instances:4
Path:/opt/iobroker/
```

**Comment by Apollon77** [comment]
Seems to be refreshing issues again in current admin version!
@UncleSamSwiss still in current beta?

**Comment by UncleSamSwiss** [comment]
I can't reinstall everything on that RasPi right now, so I can't test it on my hardware for now.

**Comment by Feuer-sturm** [comment]
Ich habe gerade einen frischen ioBroker installiert mit Admin 5.3.8 (stable version). Hab dann mal zwei Adapter installiert (smartmeter, worx) und in beiden Fällen wurde auch die Instanz angelegt und war auch sofort sichtbar.

**Comment by GermanBluefox** [comment]
Dann markiere ich das als fixed

**Comment by Feuer-sturm** [comment]
Dann mach ich mal hier zu und wenn das Verhalten nochmal hochkommt mit der 6er Version gibt es ein neues Issue.
