### ISSUE TITLE
tab-users error

### ISSUE THREAD

**Issue by kwon66** [ioBroker/ioBroker.admin#1342]
index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-03-01T14:51:05.604Z] Try to connect
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.captureSession @ hub.ts:410
Gt @ sdk.ts:204
(anonym) @ sdk.ts:237
Ut @ sdk.ts:99
1513 @ index.js:63
u @ (Index):1
r @ (Index):1
t @ (Index):1
(anonym) @ main.22a9d49c.chunk.js:2
Entwicklertools konnten Quellzuordnung nicht laden: Inhalt für chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/scripts/content_scroll_mid_detection.map: HTTP-Fehler: Statuscode 404, net::ERR_UNKNOWN_URL_SCHEME konnte nicht geladen werden
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.endSession @ hub.ts:423
e.startSession @ hub.ts:456
Gt @ sdk.ts:203
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
6 weitere Frames anzeigen
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.captureSession @ hub.ts:410
Gt @ sdk.ts:204
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
5 weitere Frames anzeigen
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.endSession @ hub.ts:423
e.startSession @ hub.ts:456
Gt @ sdk.ts:203
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
6 weitere Frames anzeigen
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.captureSession @ hub.ts:410
Gt @ sdk.ts:204
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
5 weitere Frames anzeigen
instrument.ts:125 Translate: Favorites
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.endSession @ hub.ts:423
e.startSession @ hub.ts:456
Gt @ sdk.ts:203
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
6 weitere Frames anzeigen
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonym) @ fetch.ts:57
e @ syncpromise.ts:54
(anonym) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.captureSession @ hub.ts:410
Gt @ sdk.ts:204
(anonym) @ sdk.ts:243
Z @ instrument.ts:95
G.W.onpopstate @ instrument.ts:306
value @ Router.js:91
value @ App.js:1348
handleNavigation @ App.js:1719
onClick @ Drawer.js:577
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonym) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonym) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
5 weitere Frames anzeigen
2instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22

**Comment by Hans-JR** [comment]
When cklicking on the Tab "user" I get a "GUI" Error. This is on MS Edge and on Linux Mint.

System:
Raspi 3, NodeJS 14.19.0, Controller 4.0.15

`iobroker.admin@5.3.1
instrument.ts:125 [2022-03-01T18:18:52.613Z] Try to connect
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
2instrument.ts:125 
        
       Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.501acaca.chunk.js:2:5595786)
    at 6.501acaca.chunk.js:2:5600621
    at Po (6.501acaca.chunk.js:2:5611663)
    at Zi (6.501acaca.chunk.js:2:5657695)
    at jl (6.501acaca.chunk.js:2:5643113)
    at Sl (6.501acaca.chunk.js:2:5643041)
    at Cl (6.501acaca.chunk.js:2:5642904)
    at zl (6.501acaca.chunk.js:2:5639870)
    at 6.501acaca.chunk.js:2:5589364
    at t.unstable_runWithPriority (6.501acaca.chunk.js:2:5672574)
    at Ga (6.501acaca.chunk.js:2:5589141)
    at Ka (6.501acaca.chunk.js:2:5589309)
    at Za (6.501acaca.chunk.js:2:5589244)
    at pl (6.501acaca.chunk.js:2:5637247)
    at Object.enqueueSetState (6.501acaca.chunk.js:2:5593262)
    at s.m.setState (6.501acaca.chunk.js:2:5664084)
    at :8081/static/js/9.a078e0d6.chunk.js:1:27236`

**Comment by Feuer-sturm** [comment]
duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
