### ISSUE TITLE
With Tab "user"

### ISSUE THREAD

**Issue by spreiter938** [ioBroker/ioBroker.admin#1343]
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by Feuer-sturm** [comment]
duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
