### ISSUE TITLE
Time not displayed in readable format on Info tab

### ISSUE THREAD

**Issue by guthubps1304** [ioBroker/ioBroker.admin#1345]
**Describe the bug**  

**To Reproduce**  
1. Go to 'info tab in iobrokeqr
2. Check time + time offset in system info 

**Expected behavior**  
readable format of time + time offset

**Screenshots & Logfiles**  
See attached file

**Versions:**  
 - Adapter version: <5.3.1>
 - JS-Controller version: <4.0.15>
 - Node version: <14.18>
 - Operating system: <ubuntu server 20.04.4 LTS>

**Additional context**  
issue started after updating JS-Controller to version 4.x

![iobroker-sysinfo](https://user-images.githubusercontent.com/79707394/156314926-2baad5d0-2d56-47fa-9256-20881aaa3e4a.png)

**Comment by Diginix** [comment]
Duplicate https://github.com/iobroker-community-adapters/ioBroker.info/issues/411

**Comment by Apollon77** [comment]
The data come from js.controller and need to be converted by "the adapters that displays it" into a readable format ... so it is info when it is about the "info" tab and it is admin when we talk about an other place in te UI that comes from Admin

**Comment by ldittmar81** [comment]
It's a info issue and can be closed here.

**Comment by Diginix** [comment]
@guthubps1304 Just click thumbsup on my already existing issue: https://github.com/iobroker-community-adapters/ioBroker.info/issues/411

**Comment by guthubps1304** [comment]
closed and added thumb up on existing issue
