### ISSUE TITLE
error when opening log tab on Hosts page

### ISSUE THREAD

**Issue by guthubps1304** [ioBroker/ioBroker.admin#1346]
**Describe the bug**  
When going to the host tab and click basic host settings, then clicking the log tab an error page is diplayed.

**To Reproduce**  
1. Go to 'Hosts'
2. Click on 'Host Basic settings'
3. Click on 'Logs'

**Expected behavior**  
Display Log page

**Screenshots & Logfiles**  
See screenshots and log from chrome F12 page attached

Versions:

Adapter version: <5.3.1>
JS-Controller version: <4.0.15>
Node version: <14.18>
Operating system: <ubuntu server 20.04.4 LTS>

Additional context
issue started after updating JS-Controller to version 4.x

[iobroker-error-log.log](https://github.com/ioBroker/ioBroker.admin/files/8167597/iobroker-error-log.log)
![iobroker-error-log01](https://user-images.githubusercontent.com/79707394/156316465-d5d35d04-80b6-4631-a9c6-8cd0bff12c48.png)
![iobroker-error-log02](https://user-images.githubusercontent.com/79707394/156316468-e968b12e-590b-488e-a96e-c35d87ebb304.png)
![iobroker-error-log03](https://user-images.githubusercontent.com/79707394/156316483-9f5def99-2c21-496d-b916-c0cd53e71e25.png)

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1327
