### ISSUE TITLE
Versionsanzeige bei Adapter-Update fehlerhaft

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1348]
Updates von und zur gleichen Version:
![grafik](https://user-images.githubusercontent.com/4311558/156497552-b93fa5a9-8db4-460b-baae-b6f7882e1ff1.png)

Ist mir grad aufgefallen .. bei einem Update sollte sich doch die Versionsnummer ändern .. oder?
Oder könnte das am Beta-Repo liegen?

**Comment by daniel-lo** [comment]
Es ist so, dass beim untersten Eintrag die Versionsnummer gleichgesetzt wird, bevor das Update fertig und das Feld grün hinterlegt wird. Sonst passt es.

**Comment by klein0r** [comment]
Ich finde es generell verwirrend, dass die neue Version dann direkt links in der Liste eingetragen wird. Der Hintergrund wird ja grün - das reicht mir eigentlich als Info, dass ich wohl auf der neuen Version angekommen bin 😄 

``5.3.0 -> 5.3.0`` sieht dann z.B. komisch aus. Warum bleibt da nicht die Ausgangsversion stehen?
