### ISSUE TITLE
admin 5.3.1. Objects tab: Missing feature to copy the Name attribute of a datapoint to the clipboard

### ISSUE THREAD

**Issue by hsteinme** [ioBroker/ioBroker.admin#1350]
**Is your feature request related to a problem? Please describe.**
In the old interface the cursor could be set into the Name column of datapoint and its contents could be copied to the clipboard via Ctrl-C. This is not possible anymore in the new GUI.

**Describe the solution you'd like**
As already done in the ID and Value columns please offer a clipboard icon at the right side of the field to enable copying.

**Describe alternatives you've considered**
Clicking on the "edit object" pencil, marking the Name field, calling the context menue, selecting "copy" and afterwards pressing the escape button is a possible bypass, but not a "nice" one.

**Comment by GermanBluefox** [comment]
Fixed?

**Comment by Feuer-sturm** [comment]
At minimum with Admin 5.3.4 there is an icon in name cloum to copy the name of an object
![grafik](https://user-images.githubusercontent.com/25422320/163251568-f9bbfafb-e292-4b73-b7d5-daad8fceab49.png)

**Comment by hsteinme** [comment]
Just tested: Copy icon is offered in the name column - and it works.
