### ISSUE TITLE
Frontend crash on user tab

### ISSUE THREAD

**Issue by dkleber89** [ioBroker/ioBroker.admin#1354]
**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/31743141/156917567-f837f789-883b-4ecd-8545-915d37aec941.png)
![grafik](https://user-images.githubusercontent.com/31743141/156917607-52ac074a-ec6a-48c3-91c6-783f3ff10e3c.png)

**Versions:**  
 - Adapter version: Admin 5.3.1
 - JS-Controller version: 4.0.18
 - Node version: Docker Image from today -> 
![grafik](https://user-images.githubusercontent.com/31743141/156917680-b33fa549-f5c5-4910-8fea-7e2c5e89d7d7.png)
 - Operating system: Docker Image from today -> 
![grafik](https://user-images.githubusercontent.com/31743141/156917692-957dacad-f00e-4536-b991-16c499ee39dd.png)

**Additional context**  
On user tab click in menu

**Comment by Feuer-sturm** [comment]
@dkleber89 is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
