### ISSUE TITLE
Slow connection and no access to "einstellungen"

### ISSUE THREAD

**Issue by skatehouse** [ioBroker/ioBroker.admin#1356]
Hi....after updating ioBroker no connection to preferences and somehow the whole system seems to be slow.
Deleted browser cache, tried other browsers, even mobile ones. 

Pressing F12 after clicking preferences in admin menu:

```
iobroker.admin@5.3.1
instrument.ts:125 [2022-03-07T18:52:30.227Z] Try to connect
instrument.ts:125 Cannot getRepositoryCompact: timeout
5instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
2instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
instrument.ts:125 Translate: time
instrument.ts:125 Translate: timeOffset
4instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
instrument.ts:125 Cannot read settings: timeout
5instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
value @ Adapters.js:792
(anonymous) @ Drawer.js:211
value @ Drawer.js:210
value @ Drawer.js:197
mc @ react-dom.production.min.js:132
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ App.js:1314
onClose @ App.js:1763
(anonymous) @ Snackbar.js:134
(anonymous) @ useEventCallback.js:15
(anonymous) @ Snackbar.js:144
a @ helpers.ts:98
setTimeout (async)
(anonymous) @ trycatch.ts:121
(anonymous) @ Snackbar.js:143
(anonymous) @ useEventCallback.js:15
(anonymous) @ Snackbar.js:166
onMouseLeave @ Snackbar.js:183
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Sr @ react-dom.production.min.js:100
Vr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ae @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Xt @ react-dom.production.min.js:73
a @ helpers.ts:98
instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
value @ Adapters.js:792
(anonymous) @ Drawer.js:211
value @ Drawer.js:210
value @ Drawer.js:197
mc @ react-dom.production.min.js:132
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
instrument.ts:125 [ADAPTERS] Cannot compare "" and "4.0.18"
(anonymous) @ instrument.ts:125
value @ Adapters.js:792
(anonymous) @ Drawer.js:211
value @ Drawer.js:210
value @ Drawer.js:197
mc @ react-dom.production.min.js:132
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
n.onHashChanged @ App.js:940
a @ helpers.ts:98
hashchange (async)
value @ Router.js:91
onClose @ App.js:1293
(anonymous) @ SystemSettingsDialog.js:190
pc @ react-dom.production.min.js:131
gi @ react-dom.production.min.js:220
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
```

**Comment by Feuer-sturm** [comment]
@skatehouse is this a static problem or did it happen only once?

**Comment by skatehouse** [comment]
static problem - really don´t know how to fix that

**Comment by skatehouse** [comment]
`[Warning] 810 console messages are not shown.
[Warning] [ADAPTERS] Cannot compare "" and "1.4.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.6.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.2.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.1.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.0.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.1.6" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "5.3.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.4.12" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.6.4" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.2.1" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.12.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.16" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.4.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.4.1" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.2.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.6.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.3.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.13.1" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "5.3.8" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.0.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.11.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.1.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.3.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.3.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.3.20" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.2.9" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.7.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.0.10" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.8.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.1.13" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.2.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.0.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.2.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.10.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.6.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.0.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.1.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.9.18" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.11.4" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "5.2.21" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.0.4" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.4.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.6.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.2.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.1.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.0.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.1.6" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "5.3.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.4.12" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "2.6.4" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.2.1" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.12.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.16" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.4.5" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "3.4.1" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "4.2.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.2.2" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.6.3" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "1.3.0" (6.0126dbd0.chunk.js, line 2)
[Warning] [ADAPTERS] Cannot compare "" and "0.13.1" (6.0126dbd0.chunk.js, line 2)
> Ausgewähltes Element
< <div class="MuiSnackbarContent-message-4426">Cannot read settings: timeout</div>

**Comment by skatehouse** [comment]
changed the system from RPI to NUC. Maybe a corrupt SD?!
