### ISSUE TITLE
Error by clicking on Benutzer tab

### ISSUE THREAD

**Issue by xadox-1st** [ioBroker/ioBroker.admin#1358]
**Describe the bug**  
Fresh installation on a Proxxmox LXC:
https://www.iobroker.net/#de/documentation/install/proxmox.md

**To Reproduce**  
1. open iobroker
2. Click on "Benutzer"

![image](https://user-images.githubusercontent.com/13217841/157261799-85731be7-8382-4c7d-b43a-98b4a3787a2c.png)

**Versions:**  
nodejs: 14.19
npm: 6.14.16
Operating system: Ubuntu 20.04.4 LTS

**Comment by gr3yf0x2010** [comment]
i have the same problem on a fresh install in Docker (on synology nas) / on a Odroid XU4 with Ubuntu 20.04 

only on Windows the tab "Benutzer" (Users)  works

**Comment by Feuer-sturm** [comment]
Is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1337
