### ISSUE TITLE
Error in GUI ioBroker

### ISSUE THREAD

**Issue by PSchuZu** [ioBroker/ioBroker.admin#1364]
Go to ioBroker "Host" click on "Host-Basiseinstellungen", click on "Log".

index.js:18 iobroker.admin@5.3.1
socket.io.js:59 [2022-03-09T11:13:26.842Z] Try to connect
i18n.js:106 Translate: time
i18n.js:106 Translate: timeOffset
react-dom.production.min.js:216 TypeError: Cannot read properties of null (reading 'includes')
    at BaseSettingsLog.js:77:65
    at Array.forEach (<anonymous>)
    at new s (BaseSettingsLog.js:75:41)
    at zc (react-dom.production.min.js:135:172)
    at Uo (react-dom.production.min.js:181:146)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73

**Expected behavior**  
See the settings for the log

**Comment by Feuer-sturm** [comment]
Is duplicate to #1327
