### ISSUE TITLE
Multihost setup not working properly

### ISSUE THREAD

**Issue by xadox-1st** [ioBroker/ioBroker.admin#1367]
**Describe the bug**  
Setting up a Proxmox LXC Ubuntu or Debian master iobroker with _"iob multihost enable"_.
Setting up a Pi slave iobroker. Manuel with rapsbian or using the rpi image with _"iob multihost connect"_

**To Reproduce**  
1. Got to Adapters view
2. Switch to slave
3. "does not start any instances on this host" is logged
4. Force Refresh website
5. try installing Backitup Adapter. Adapter will be installed forever.

**Expected behavior**  
On my older setup with jscontroller below v4 this is working fine.

![image](https://user-images.githubusercontent.com/13217841/157658985-a6203080-ae40-47f8-9d83-54276356327f.png)

**Comment by Apollon77** [comment]
Ok, sorry I do not get the problem ... what exactly is your issue??

Is the issue that backit up can not be installed? So whats exactly the UI doing?

**Comment by xadox-1st** [comment]
I will try to describe better.
If I use the two iobroker without the multihost functionality separately, both work without problems.

But as soon as I use the PI as slave I have problems installing any adapter on the slave PI. The installation dialog is not finished and is not displayed after hours. Even if I hide this task in the background.

In previous version switching to a still empty slave did not lead to this error log entry. Since the Admin Adapter and the Discovery Adaper were also present on the slave.
But that should not be the core problem.
The problem is that I can't get the adapters installed on the slave without problems.

**Comment by Apollon77** [comment]
Please show more detaisl like a screenshot of full admin page, logfiles and and and

**Comment by xadox-1st** [comment]
I will try to deliver:
![image](https://user-images.githubusercontent.com/13217841/157723108-a2d7786b-b10a-4186-b031-81442be52273.png)

Adapters on Master
![image](https://user-images.githubusercontent.com/13217841/157723157-cf4a2848-0e37-4af4-a841-8b1c3a4a061e.png)

Switching between master and slave does not change view:
https://vimeo.com/686802669

Log:
[ioborker-pi.log](https://github.com/ioBroker/ioBroker.admin/files/8225850/ioborker-pi.log)
[iobroker-master.log](https://github.com/ioBroker/ioBroker.admin/files/8225866/iobroker-master.log)

**Comment by Apollon77** [comment]
For Admin: It seems that there is a "data refreshj issue" on host switch. Klick the reload button (the circle) after switching the host. I think there already is an issue fopr this

For the adapter install: Can you please execute the command in a shell 0n the slave?

`iobroker add lupusec`

for me it works

**Comment by xadox-1st** [comment]
> For Admin: It seems that there is a "data refreshj issue" on host switch. Klick the reload button (the circle) after switching the host. I think there already is an issue fopr this

you are right this works. So I seem to be affected by the bug as well.
Thank you for identifying the problem.

> For the adapter install: Can you please execute the command in a shell 0n the slave?
> `iobroker add lupusec`

For me I have the same problem from console, too. The task is running without an end:
![image](https://user-images.githubusercontent.com/13217841/157816326-e67416ae-19db-4b47-a97b-9a5f47c8c323.png)

**Comment by xadox-1st** [comment]
There seems to be a refresh problem in general. The adapters are installed but the dialog does not close. If one then Force Refreshed the adapters or also Instancen appear in the overview.

**Comment by Apollon77** [comment]
The EXEC without MULTI issue will be fixed in contrioller 4.0.20 soon (Beta today). maybe retry after that? It could easiely be connected

**Comment by Apollon77** [comment]
js.controller 4.0.21 is released in Beta ... Please try if now the install goes through

**Comment by xadox-1st** [comment]
I updated js.controller to 4.0.21:
The problem with the adapter installation has been solved. Thx for that fast fix.
The problem with missing autorefresh when switching between master and slave is still present.
The log entry "EXEC without MULTI" did not appear anymore.

**Comment by Apollon77** [comment]
Sure, the Admin iss ue is an admin issue :-)

formally the issue here is solved (hanging install) ... so maybe create a new issue for the refresh issue?
