### ISSUE TITLE
after update on 3.0.10: the adapter tab does not show any adapters

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.admin#137]
The 2.0.9 adapter still shows the adapters but 3.0.10 they disappear!

p.s.: the 3.0.10-adapter shows as version on upper right 3.0.1!

**Comment by frankjoke** [comment]
I need to add that new adapters (or  updated like I had when I downgraded vis to 1.0.4 because 1.0.10 is not working as  well) show up in the adapter list!

older ones (regardless if installed or not) do not show up!

**Comment by GermanBluefox** [comment]
I do not understand anything...

**Comment by GermanBluefox** [comment]
Closed because no comments
