### ISSUE TITLE
ERROR IN GUI

### ISSUE THREAD

**Issue by oggy79** [ioBroker/ioBroker.admin#1371]
[Log] Translate: timeOffset (6.501acaca.chunk.js, line 2)
[Error] TypeError: null is not an object (evaluating 'n.transport[t].maxSize.includes')
(anonyme Funktion) — BaseSettingsLog.js:77
forEach
s — BaseSettingsLog.js:75
zc — react-dom.production.min.js:135:178
Uo — react-dom.production.min.js:181:149
jl — react-dom.production.min.js:250:350
Sl — react-dom.production.min.js:250:281
Cl — react-dom.production.min.js:250:138
zl — react-dom.production.min.js:243:166
zl
(anonyme Funktion) — react-dom.production.min.js:123:115
(anonyme Funktion) — scheduler.production.min.js:18:343
Ka — react-dom.production.min.js:123
Za — react-dom.production.min.js:122:428
ke — react-dom.production.min.js:292:101
Yt — react-dom.production.min.js:73:355
Yt
a — helpers.ts:98

	(anonyme Funktion) (6.501acaca.chunk.js:2:6306641)
	ui (6.501acaca.chunk.js:2:5626907)
	(anonyme Funktion) (6.501acaca.chunk.js:2:5629167)
	fc (6.501acaca.chunk.js:2:5592193)
	Uo (6.501acaca.chunk.js:2:5614992)
	jl (6.501acaca.chunk.js:2:5643116)
	Sl (6.501acaca.chunk.js:2:5643044)
	Cl (6.501acaca.chunk.js:2:5642907)
	zl (6.501acaca.chunk.js:2:5639873)
	zl
	(anonyme Funktion) (6.501acaca.chunk.js:2:5589366)
	(anonyme Funktion) (6.501acaca.chunk.js:2:5672576)
	Ka (6.501acaca.chunk.js:2:5589312)
	Za (6.501acaca.chunk.js:2:5589247)
	ke (6.501acaca.chunk.js:2:5660414)
	Yt (6.501acaca.chunk.js:2:5567865)
	Yt
	a (6.501acaca.chunk.js:2:6337082)

**Comment by Feuer-sturm** [comment]
@oggy79 Please add the steps you did to trigger the error and which admin version is installed

**Comment by oggy79** [comment]
Admin Version 5.3.1

Host > Basicsettings (Tool-Symbol) > LOG

**Comment by Feuer-sturm** [comment]
@oggy79 Thanks. This issue is duplicate to #1327
