### ISSUE TITLE
A "german formatted date" (dd.mm.yyyy) is shown incorrect in Admin

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1373]
see https://github.com/iobroker-community-adapters/ioBroker.weatherunderground/issues/105#issuecomment-1065412198

State contains e.g. 11.3.2022 ... admin shows "3.11.2022" and jumps to invalid e.g. for 13.3.2022 ... because 3.13.2022 is invalid

**Comment by Feuer-sturm** [comment]
@crunchip77 Kannst du bitte einmal prüfen, ob das Problem mit Admin 5.3.2 gefixt ist?

**Comment by crunchip77** [comment]
@Feuer-sturm positive Rückmeldung, date funktioniert, sowie Log im Host funktioniert ebenfalls wieder
