### ISSUE TITLE
Error in GUI: Host-Basiseinstellungen -> Log

### ISSUE THREAD

**Issue by TbsBrggng** [ioBroker/ioBroker.admin#1374]
Admin 5.3.1:
Host -> Host-Basiseinstellungen -> Log ->

[Error] TypeError: undefined is not an object (evaluating 'n.transport[t].maxSize.includes')
	(anonyme Funktion) (6.501acaca.chunk.js:2:6306641)
	ui (6.501acaca.chunk.js:2:5626907)
	(anonyme Funktion) (6.501acaca.chunk.js:2:5629167)
	fc (6.501acaca.chunk.js:2:5592193)
	Uo (6.501acaca.chunk.js:2:5614992)
	jl (6.501acaca.chunk.js:2:5643116)
	Sl (6.501acaca.chunk.js:2:5643044)
	Cl (6.501acaca.chunk.js:2:5642907)
	zl (6.501acaca.chunk.js:2:5639873)
	zl
	(anonyme Funktion) (6.501acaca.chunk.js:2:5589366)
	(anonyme Funktion) (6.501acaca.chunk.js:2:5672576)
	Ka (6.501acaca.chunk.js:2:5589312)
	Za (6.501acaca.chunk.js:2:5589247)
	ke (6.501acaca.chunk.js:2:5660414)
	Yt (6.501acaca.chunk.js:2:5567865)
	Yt
	a (6.501acaca.chunk.js:2:6337082)

**Comment by Feuer-sturm** [comment]
Issue is duplicate to #1327
