### ISSUE TITLE
Fehler in der GUI! Wenn auf "Benutzer" im iobroker zugreifen möchte

### ISSUE THREAD

**Issue by Jens26bw** [ioBroker/ioBroker.admin#1376]
**Describe the bug**  
[192.168.178.57-1647270081783.log](https://github.com/ioBroker/ioBroker.admin/files/8246071/192.168.178.57-1647270081783.log)

**To Reproduce**  
1. Go to 'iobroker'
2. Click on 'benutzer'
3. See error

**Expected behavior**  
Hallo. Ich hoffe ich mache alles hier Richtig beim erstellen.
Ich öffne den iobroker, als Admin weil ich keine Benutzer anlegen kann.
Wenn ich auf den Reiter "Benutzer" klicke kommt sofort die Fehlermeldung.

**Screenshots & Logfiles**  
Logfile habe ich angehängt

**Versions:**  
 - Adapter version: ?
 - JS-Controller version: 4.0.21
 - Node version: ? v14.19.0   NPM? 6.14.16 ich kenne den unterschied leider nicht.
 - Operating system: linux

**Additional context**  
Ich bin sehr neu und verstehe nicht sehr viel davon.
Bitte haben sie Nachsicht mit mir. 
Ich hoffe ich habe alles Richtig ausgefüllt.

**Comment by GitBaer** [comment]
Problem ist bekannt, siehe https://github.com/ioBroker/ioBroker.admin/issues/1337

**Comment by Jens26bw** [comment]
Hallo. Vielen Dank. Jedoch kann ich keine Abhilfe finden.
Gibt es eine Abhilfe zu diesem Problem?

**Comment by Feuer-sturm** [comment]
@Jens26bw Eine Abhilfe kenne ich nicht. Stell diese Frage am besten im issue #1337  dann machen wir dieses issue zu, da es doppelt ist. Im Worst Case hilft nur ein Bugfix von @GermanBluefox
