### ISSUE TITLE
problem mit iobroker

### ISSUE THREAD

**Issue by Tomasz9691** [ioBroker/ioBroker.admin#1378]
ChunkLoadError: Loading chunk 14 failed.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}(error: http://192.168.178.103:8081/static/js/14.b28d85a4.chunk.js)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Function.u.e (http://192.168.178.103:8081/:1:3974)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.103:8081/static/js/main.22a9d49c.chunk.js:2:1113786function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at V (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5666268)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5656452)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5643113)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5643041)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5642904)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at zl (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5639870)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5589364function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5672574)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5589141)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5589309)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5589244)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5637247)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Object.enqueueSetState (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5593262)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at o.m.setState (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5664084)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.103:8081/static/js/main.22a9d49c.chunk.js:2:1126466function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at u (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5676516)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Generator._invoke (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5676304)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Generator.next (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:5676945)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at r (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:35792)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at i (http://192.168.178.103:8081/static/js/6.501acaca.chunk.js:2:35995)

**Comment by Feuer-sturm** [comment]
@Tomasz9691 Can you please provide some more details. Which admin version is installed, what did you do to trigger the error?
