### ISSUE TITLE
Verfügbare Version falsch dargestellt v5.3.1 (alte Oberfläche)

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1382]
Neue Oberfläche:
![image](https://user-images.githubusercontent.com/84818934/158657125-0f0b57b0-8217-45b7-8fca-cd973dca4ff3.png)

![image](https://user-images.githubusercontent.com/84818934/158657178-bd252e2b-66a7-473a-8ce9-2a6b950249a1.png)

Alte Oberfläche:
![image](https://user-images.githubusercontent.com/84818934/158657306-cfbd66ca-b878-4964-bc87-e66dd0bef660.png)

https://github.com/Zefau/ioBroker.jarvis/issues/1647

**Comment by Apollon77** [comment]
Yes, old Admin UI had this issue if Adapter news contained special non-escaped characters .. will not be fixed in Admin. Adapter can fix the news content
