### ISSUE TITLE
Farbgebung für Objectliste

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#1383]
![grafik](https://user-images.githubusercontent.com/6681528/158685127-1ada976d-88a4-41a8-a49e-08bb5708cab2.png)

ein standarisiertes Verfahren um offline/online Geräte anzuzeigen und diese performant im Admin anzuzeigen

**Comment by Apollon77** [comment]
Ok, so here the proposal after the talks in dev-meeting yesterday:
* We enhance the definition of device objects to allow
* common.statusStates as an object with two allowed boolean keys to contain stateIds
* common.statusStates.onlineId - stateId of the online/connected state of this device (true=connected=green, false=not-connected=red, null=no info=normal color (role: indicator.reachable)
* common.statusStates.errorId - stateId of the error state of this device (true=error, else=no-error) (role: indicator.maintenance.alarm)

If this is specified in the device object admin will colorize the device id as defined for online status and can also show error infos.
Also visualizations can use this additionally to the roles

**Comment by Feuer-sturm** [comment]
@arteck Can you verify this feature?

**Comment by arteck** [comment]
for zigbee is ok
![grafik](https://user-images.githubusercontent.com/6681528/168962890-7fcd799a-6e81-4b87-be52-6e3eb77b5a83.png)

**Comment by klein0r** [comment]
> for zigbee is ok

For larger columns / short names everything looks fine. The problem is, that the icons are placed in the same column as the name and overlay the text (same for all other icons, not just status icons). But maybe that is another issue and not related to this topic.

**Comment by GermanBluefox** [comment]
I have only one screen. How must I ALL THESE INFORMATION to squeeze into one line?
