### ISSUE TITLE
"value.time" with value null is shown as invalid date

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1387]
see https://github.com/ioBroker/ioBroker.dwd/issues/103#issuecomment-1072966795

if a role is "value.time" and the value is null Admin UI shows "invalid Date". 

This should also be checked for other roles that are converted to date for display please

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
With Admin 5.3.3 "Invalid Date" is still visible.
![grafik](https://user-images.githubusercontent.com/25422320/159184280-8e77e8a5-0004-4217-bfc3-003f5fdaa298.png)

@crunchip77 Do you see the same behavior?

**Comment by crunchip77** [comment]
@Feuer-sturm yes, invalid date, for warnings without message

**Comment by GermanBluefox** [comment]
> @Feuer-sturm yes, invalid date, for warnings without message

Will be fixed in the next version

**Comment by Feuer-sturm** [comment]
@GermanBluefox 

With Admin 5.3.4 there is still the same problem.
I deleted all objects of dwd and made a restart of the adapter.

dwd.0.warning.begin = Invalid Date
dwd.0.warning.end = Invalid Date

**Comment by Feuer-sturm** [comment]
Admin 5.3.7 
Issue is fixed :-)

![grafik](https://user-images.githubusercontent.com/25422320/163060028-cdf541bb-74a5-42aa-a269-dc8dfe03635f.png)
