### ISSUE TITLE
Common.states as array has unnecessary numbers

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#1388]
If common.states is an array, admin adds numbers in brackets  behind the actual values, but it has no further meaning and is just confusing

**Comment by Apollon77** [comment]
In fact admin always adds the real value in brackets ... also with arrays there are values :-)

**Comment by foxriver76** [comment]
Ok, I think I've had different expectations, when I proposed the array alternative vs the actual implementation. My thoughts were like: If I have a data structure like `['start', 'flight', 'land']` and I select one, admin should set the according string. Actually if I select `start` with the current impl I get 0.. okay then admin shows it correct, but impl is not what I would have expected. So still no real enum like data point is possible, while I still think this would be a strong feature

**Comment by Apollon77** [comment]
Aaahhhhhhhh ... in fact we still have "states" only defined for states of type number ... :-) So it can only be that right now.

Alternative is to decide that states also work for other datatypes and then define how it needs to work and implement this into all visus :-)

**Comment by foxriver76** [comment]
I would really appreciate to see this supported, because it is handful in many situations. ;-) but yes then ok it is a separate thing and an enhancement request.

**Comment by GermanBluefox** [comment]
You can achieve it with 
```
"states": {"start": "start", "flight": "flight", "land": "land"}
```

**Comment by foxriver76** [comment]
> You can achieve it with
> 
> ```
> "states": {"start": "start", "flight": "flight", "land": "land"}
> ```

Yes and I think this should be the default for array structures. I would not expect a mapping from like this https://github.com/foxriver76/ioBroker.denon/commit/6d50eb75c2ab4e7df19539ab122df76ce2954970#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aL2548

**Comment by Apollon77** [comment]
@GermanBluefox But then it would be still invalid according to state definition :-) I think we need to decide that topic in general

**Comment by GermanBluefox** [comment]
That means that we must threat it different for "number" and "string". 
- "number" the index of the word will be taken
- "string" the whole word will be taken.

Is it not too complex?

**Comment by foxriver76** [comment]
Imho I would keep the handling as it is for real objects, because multiple adapters are using string States even if not allowed and a change would break here.

However for array style just only use the entry do not add any index mapping for arrays and every use case should be possible from my pov

**Comment by Apollon77** [comment]
Yes iderally we just define that also "non number" types like string can use it :-) Maybe it also works for booleans :-)

**Comment by GermanBluefox** [comment]
I do not understand what do you offer.

**Comment by GermanBluefox** [comment]
@foxriver76 ?

**Comment by foxriver76** [comment]
If `common.states` is an array, offer an adjusted dropdown in admin, where only the exact values contained in the array can be selected, no index numbers behind it etc. If a value is selected, set exactly that value to the state, not the index of the value. So an `common.states: ['start', 'flight', 'land']` should be equal to `"states": {"start": "start", "flight": "flight", "land": "land"}`. And in the best case do not show the `start (start)` in admin, instead just show `start`.

**Comment by GermanBluefox** [comment]
Implemented
