### ISSUE TITLE
object name not editable

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1389]
admin 5.3.2
Just noticed that I cannot edit the object name in FF .. unless I edit the Raw-Data. I only see a copy to clipboard symbol .. but no wrench to edit the object name directly.

Maybe this has moved and I missed it.

**Comment by GermanBluefox** [comment]
I don't think that it was ever possible in admin5. 
I removed this feature in Admin5, as GUI was too overloaded.

**Comment by daniel-lo** [comment]
Thanks .. I can manage .. but it was quite nice :-)
