### ISSUE TITLE
Keine Aktivierung für History Adapter in Admin-Beta möglich

### ISSUE THREAD

**Issue by djalexz** [ioBroker/ioBroker.admin#139]
Im Admin-Beta ist die Aktivierung von History nicht möglich.
Nach Klick auf das Zahnrad eines Datenpunktes öffnet sich die Ansicht History.
Hier kann aber nicht aktiviert bzw. deaktiviert werden.
![image](https://user-images.githubusercontent.com/11389551/34665135-6667656c-f45f-11e7-9877-e1f26e6e7342.png)

**Comment by GermanBluefox** [comment]
History muss vom git sein.

8 янв. 2018 г. 10:33 пользователь "djalexz" <notifications@github.com>
написал:

**Comment by djalexz** [comment]
Hallo Bluefox,

danke dir für die schnelle Antwort.
Mit dem History Adapter gehts jetzt.
Allerdings mit dem SQL Adapter noch nicht.
Der ist vom Git.

Eventuell noch nicht angepasst?

**Comment by DutchmanNL** [comment]
SQL ist noch nicht angepasst

**Comment by djalexz** [comment]
Vielen Dank, dann übe ich mich in Geduld :-)
