### ISSUE TITLE
Invalid Date DWD Adapter

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#1393]
Hallo,

beim DWD Adapter ist die Anzeige falsch wenn wert null ist.

Plattform: Windows
RAM: 16 GB 
NODE.JS: V14.19.1
NPM: 6.14.16
JS Controller: 4.0.21
Admin: 5.3.3
DWD: 2.8.1 (2)

![Screenshot (4783)](https://user-images.githubusercontent.com/41079106/159446818-75e2be71-7b86-4797-a393-a47741fed362.png)

**Comment by Apollon77** [comment]
(SSorry ... I should have said that it is a known issue) :-))
