### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by thomashde** [ioBroker/ioBroker.admin#1397]
**Describe the bug**  
By browsing through the object list at the end this error occur:

sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
sparkline.js:17 Error: <path> attribute d: Expected number, "M4 NaN L 4 NaN L 12…".
u @ sparkline.js:17
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Thu%20Mar%2002%2010000%2000%3A00%3A00%20GMT%2B0100%20(Mitteleurop%C3%A4ische%20Normalzeit) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (6.10bc7fbf.chunk.js:2:5594586)
    at 6.10bc7fbf.chunk.js:2:5599421
    at Po (6.10bc7fbf.chunk.js:2:5610463)
    at Zi (6.10bc7fbf.chunk.js:2:5656495)
    at jl (6.10bc7fbf.chunk.js:2:5641913)
    at Sl (6.10bc7fbf.chunk.js:2:5641841)
    at Cl (6.10bc7fbf.chunk.js:2:5641704)
    at bl (6.10bc7fbf.chunk.js:2:5638670)
    at 6.10bc7fbf.chunk.js:2:5588164
    at t.unstable_runWithPriority (6.10bc7fbf.chunk.js:2:5671374)
    at Ga (6.10bc7fbf.chunk.js:2:5587941)
    at Ka (6.10bc7fbf.chunk.js:2:5588109)
    at Za (6.10bc7fbf.chunk.js:2:5588044)
    at pl (6.10bc7fbf.chunk.js:2:5636047)
    at Lo (6.10bc7fbf.chunk.js:2:5607697)
    at 6.10bc7fbf.chunk.js:2:342154
    at ye (6.10bc7fbf.chunk.js:2:1935353)
    at 6.10bc7fbf.chunk.js:2:1935711
    at a (6.10bc7fbf.chunk.js:2:6327193)
(anonymous) @ instrument.ts:124
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.batteryAvailableEnergy
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.batteryCapacity
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.batteryTS
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.batteryTemperature
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.chargeCancel
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.chargeEnable
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.charge_level
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.charging
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.chargingPower
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.charging_finished_at
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.gpsLatitude
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.gpsLongitude
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.plugged
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.preconNow
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.remaining_range
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.remaining_time
instrument.ts:124 - unsubscribe zoe2.0.VF1AG000666409219.totalMileage
DevTools failed to load source map: Could not load content for http://192.168.2.75:8081/adapter/info/lib/js/showdown.min.js.map: Fetch through target failed: Frame not found; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.2.75:8081/adapter/info/lib/js/chartist.min.js.map: Fetch through target failed: Frame not found; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.2.75:8081/adapter/info/lib/js/format-google-calendar.js.map: Fetch through target failed: Frame not found; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Feuer-sturm** [comment]
Hallo @thomashde which admin version  is in use? What did you do to trigger the error?

**Comment by thomashde** [comment]
Hello Feuer-sturm,
the Admin version I'm using is 5.3.3.

**Comment by Feuer-sturm** [comment]
@thomashde And What was the trigger of the error? Just open Objects menu and browsing there?

**Comment by thomashde** [comment]
I just opened object menue and scrolled down to the end.

**Comment by GermanBluefox** [comment]
> I just opened object menue and scrolled down to the end.

Which menu?

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1406
