### ISSUE TITLE
user error

### ISSUE THREAD

**Issue by TankiGHG** [ioBroker/ioBroker.admin#1399]
**Describe the error**
A clear and concise description of the error.
The error occurs when you go to the user view.

**Reproduce**
1. Go to 'dashboard'
2. Click on 'user'
3. See error

**Expected Behavior**
A clear and concise description of what you expected.

The user view
**Screenshots & Log Files**
If necessary, include screenshots and log files to explain your problem.
![Screenshot 2022-03-27 131450](https://user-images.githubusercontent.com/102466308/160278912-19dc4668-52e7-483f-877c-8c982dc343cc.png)

**Versions:**
 - Adapter version: <v5.3.1>
 - JS controller version: <6.14.16> 
 - Node version: < V12.22.11> 
 - Operating system: <rasberryos>

**Comment by Apollon77** [comment]
duplicate #1337
