### ISSUE TITLE
Datenpunkt für admin log

### ISSUE THREAD

**Issue by SebastianSchultz** [ioBroker/ioBroker.admin#140]
Ist es möglich für das Log des Admins einen eigenen Datenpunkt zu erstellen?
Dort muss ja nicht das komplette Log rein, aber evtl. die letzten 500 Zeilen z.B.

So könnte man das Log auch in der VIS anzeigen wenn man das möchte.

**Comment by GermanBluefox** [comment]
Log ist das, was sich sehr schnell und VIEL ändern kann. Aus performance gründen ist das nicht erwünscht.

**Comment by SebastianSchultz** [comment]
Wäre es denn evtl. möglich sonst nur die letzten x Einträge in einen Datenpunkt zu schreiben?

**Comment by Apollon77** [comment]
Egal ob ein oder mehrere Logeinträge Du willst die ganzen State-Updates nicht haben.

ich habe auf meiner Ideenliste die Idee einen "Log-Parser"-Adapter zu bauen wo man über Regeln ggf Trigger bauen kann oder sich bestimmte events rausfiltern kann (z.B. alle Fehler als Pushover schicken oder sowas) Mus mal schauen wie man das performancemäßig gut hinbekommt

**Comment by SebastianSchultz** [comment]
Hey Apollon,

wäre es - meiner Meinung nach - nicht sinniger, das irgendwie in den Admin zu integrieren?
Ich sehe persönlich hier die Gefahr, das es irgendwann "zu viele Adapter für jeden Kram" gibt, was evtl. neue Nutzer abschrecken könnte, oder?

**Comment by Apollon77** [comment]
Das Konzept von ioBroker ist genau dieses modulare Herangehen. Jeder Adapter hat eine Aufgabe. Admin ist für die Administrationsoberfläche da.
Für die wenigen Fälle wo man ggf was mit den Logs machen will wäre ein eigener Adapter sinnvoll.

**Comment by SebastianSchultz** [comment]
OK, war ja nur 'ne Idee :)
