### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by tomwolf1992** [ioBroker/ioBroker.admin#1402]
Honestly said I have no idea what I have done. I looked around to learn about menus and then this:

index.js:18 iobroker.admin@5.3.1
instrument.ts:125 [2022-03-27T23:17:59.111Z] Try to connect
fetch.ts:57          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
(anonymous) @ fetch.ts:57
e @ syncpromise.ts:54
(anonymous) @ fetch.ts:56
add @ promisebuffer.ts:49
t._sendRequest @ fetch.ts:54
e.sendSession @ base.ts:83
e.sendSession @ basebackend.ts:112
e._sendSession @ baseclient.ts:291
e.captureSession @ baseclient.ts:187
e._sendSessionUpdate @ hub.ts:475
e.captureSession @ hub.ts:410
Gt @ sdk.ts:204
(anonymous) @ sdk.ts:237
Ut @ sdk.ts:99
1513 @ index.js:63
u @ (index):1
r @ (index):1
t @ (index):1
(anonymous) @ main.22a9d49c.chunk.js:2
DevTools failed to load source map: Could not load content for chrome-extension://fajmnddnafkmfdeekbkjcpohhoodhgjj/vendor/libphonenumber-max.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
2instrument.ts:125 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ec (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Po (react-dom.production.min.js:176:171)
    at Zi (react-dom.production.min.js:271:134)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at zl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at UsersList.js:331:22
(anonymous) @ instrument.ts:125
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ UsersList.js:331
Promise.then (async)
o.updateData @ UsersList.js:329
(anonymous) @ UsersList.js:297
pc @ react-dom.production.min.js:131
gi @ react-dom.production.min.js:220
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
zl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
utils.ts:95          POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
Xe @ utils.ts:95
e._flushOutcomes @ base.ts:149
(anonymous) @ base.ts:66

**Comment by Feuer-sturm** [comment]
Did you click on menu User (Benutzer). If  yes it is duplicate to #1337 and fixed with Admin 5.3 4.

If no please try to provide more details.
