### ISSUE TITLE
Typo in german function "Kaffemaschine" (very cosmetic issue)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1404]
**Describe the bug**  
There's a typo at the german standard function "Kaffemaschine" is written with only one "e". Should read "Kaffeemaschine" 
 
**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/160660551-73faebad-0d58-422a-8fff-81b03a8b345b.png)

**Versions:**  
 - Adapter version: 5.3.4
 - Operating system: windows 10

**Comment by Feuer-sturm** [comment]
@Apollon77 Kann das über weblate korrigiert werden oder ist das im Admin fest hinterlegt?

**Comment by Feuer-sturm** [comment]
@Apollon77 wo werden diese Texte verwaltet? In weblate habe ich über die Suche nichts gefunden.

**Comment by mcm1957** [comment]
Can confirm that the fix is working. (dev-sever, admin 5.3.7)
Thanks McM
