### ISSUE TITLE
Hosts-Config-Log: Error in GUI!

### ISSUE THREAD

**Issue by UweLm** [ioBroker/ioBroker.admin#1405]
Good morning @all,

I've got an error (exception) by viewing the configuration in Hosts (LOG).
Enclosed a screenshot about this error.

- In ioBroker select "Hosts" in the left side menu
- Click on Config (wrench)
- Click on "LOG" in the upper menu band
- The following error will be displayed: 
![image](https://user-images.githubusercontent.com/78011774/160762481-881a63ff-f314-48ed-a1ce-bf9567811fef.png)

**Expected behavior**  
See the setup for Log

**Versions:**  
 - ioBroker version: 3.3.22
 - Node.js version: 5.2.21
 - Node version: v16.11.0
 - Operating system: Raspbian GNU/Linux 10 (buster)

Do you have any idea/hints how to avoid it?

KR Uwe

**Comment by Apollon77** [comment]
Node.js Version 5??? Das glaube ich irgendwie nicht. Denke du meinst eher den JavaScript Adapter.

generell fehlt die wichitgste Info: Welche Admin version? Bzw in der 5.3.4 sollte das gefixt sein

**Comment by UweLm** [comment]
Moin Ingo,

 

zunächst mal Danke für die schnelle Reaktion!

Du hast natürlich recht mit der Node.js version, es ist die v16.11.0.
Die Admin Version ist die 5.3.1:
- Verfügbare Version: 5.3.1

- Installierte Version: 5.3.1

 

Wenn das Problem in der 5.3.4 behoben ist installiere ich die, sobald sie zur Verfügung steht.

 

Besten Dank und einen angenehmen Tag.

 

Viele Grüße

 

Uwe


 
 

Gesendet: Mittwoch, 30. März 2022 um 08:47 Uhr
Von: "Ingo Fischer" ***@***.***>
An: "ioBroker/ioBroker.admin" ***@***.***>
Cc: "UweLm" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Hosts-Config-Log: Error in GUI! (Issue #1405)


 

Node.js Version 5??? Das glaube ich irgendwie nicht. Denke du meinst eher den JavaScript Adapter.

generell fehlt die wichitgste Info: Welche Admin version? Bzw in der 5.3.4 sollte das gefixt sein

**Comment by Feuer-sturm** [comment]
Hi, das Problem ist seit der 5.3.2 gefixt. Siehe auch #1327
