### ISSUE TITLE
Since Admin v5.3.2 Error in GUI hovering over certain dates in object tree

### ISSUE THREAD

**Issue by Black-Thunder** [ioBroker/ioBroker.admin#1406]
**Describe the bug**  
Since Admin v5.3.2 there seems to be a bug with states containing date values as string in a certain format. This leads to a crash of the admin GUI when trying to hover over the states values in the objects tab. Up until v5.3.1 everything works fine.

**To Reproduce**  

1. Create state like the following:
```
{
  "type": "state",
  "common": {
    "name": "Report end date (format: YYYY-MM-DD)",
    "type": "string",
    "role": "date",
    "read": true,
    "write": true,
    "desc": "Report data will be collected until this date"
  },
  "native": {},
  "from": "system.adapter.melcloud.0",
  "user": "system.user.admin",
  "ts": 1648837345537,
  "_id": "melcloud.0.devices.233097.reports.endDate",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

2. Set the value to "2021-10-01" ("YYYY-MM-DD") while leaving out the time portion (e.g. "T00:00:00")
3. Hovering in the objects tree over the value leads to the GUI crash:

`Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Wed%20Dec%2001%202021%2000%3A00%3A00%20GMT%2B0100%20(Mitteleurop%C3%A4ische%20Normalzeit) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Wed%20Dec%2001%202021%2000%3A00%3A00%20GMT%2B0100%20(Mitteleurop%C3%A4ische%20Normalzeit) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ec (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5593656)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5598491function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Po (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5609533)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Zi (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5655565)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at jl (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5640983)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Sl (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5640911)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Cl (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5640774)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at bl (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5637740)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5587234function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5670444)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5587011)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5587179)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5587114)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5635117)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Lo (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:5606767)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:342245function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at ye (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:1935220)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:1935578function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at a (http://192.168.150.26:8081/static/js/6.1cf1778f.chunk.js:2:6328631)`

**_React error message:_**

Error Decoder
In the minified production build of React, we avoid sending down full error messages in order to reduce the number of bytes sent over the wire.

We highly recommend using the development build locally when debugging your app since it tracks additional debug info and provides helpful warnings about potential problems in your apps, but if you encounter an exception while using the production build, this page will reassemble the original text of the error.

The full text of the error you just encountered is:

Objects are not valid as a React child (found: Wed Dec 01 2021 00:00:00 GMT+0100 (Mitteleuropäische Normalzeit)). If you meant to render a collection of children, use an array instead.

**Expected behavior**  
No crash when hovering over the value like in admin versions <= 5.3.1:

![image](https://user-images.githubusercontent.com/972581/161322765-e3f89d63-d5af-40a0-ab4e-4adedbf73ac1.png)

![image](https://user-images.githubusercontent.com/972581/161322696-5477cafc-2dee-409b-b97b-fc3b10651ee8.png)

**Additional context**  

As a workaround you can add the time portion at the end (e.g. "2021-10-01T00:00:00") which prevents the crash but this was not necessary with admin versions <= 5.3.1

**Versions:**  
 - Adapter version: 5.3.4
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: Raspberry Pi OS Lite 11 (bullseye)

**Comment by Black-Thunder** [comment]
Just tried v5.3.7 and the crash is now gone. 👍 

But now the date (especially the month) is displayed incorrectly, e.g. if you set it to "2022-03-31" it will be displayed as "2022.04.31".

![image](https://user-images.githubusercontent.com/972581/162714152-42093871-ca2f-4b50-aa6f-0cbb491615ed.png)

**Comment by Diginix** [comment]
I can confirm the date issue for objects type=string and role=date with admin 5.3.7.

**Comment by Black-Thunder** [comment]
Yes, if you use "DD.MM.YYYY" the date is displayed correctly (correct month).

Nevertheless, using "YYYY-MM-DD" shouldn't be displayed with the wrong month then (which is always MM+1) . At least it should be displayed as "Unknown Date" or something like that in the GUI if this is not a known/supported format.

**Comment by Diginix** [comment]
If the date value of the object isn't the format setup in global admin settings it should displayed as it is without trying it to convert. All is better that displaying a complete wrong value.

**Comment by GermanBluefox** [comment]
PLease test 5.4.8

**Comment by Diginix** [comment]
works for me with 5.4.8

**Comment by Black-Thunder** [comment]
Yes, I can confirm that with v5.4.8 the value is now displayed correctly without changing the format or value:

![image](https://user-images.githubusercontent.com/972581/167566081-5510b394-4e0c-419b-b82e-cdf86e46ec6a.png)

Thanks for the fix!
