### ISSUE TITLE
Irreführende Fehlermeldung bei Installation Homematic Adapter

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.admin#1408]
@Apollon77 empfahl mir hier ein issue zu öffnen:
![1648940195119-bf26ad16-1fca-40ba-83ac-897fb14ceaa6-image](https://user-images.githubusercontent.com/50423935/161436766-0b661bbb-2a7b-4178-9fde-45c864597f91.png)

Diese Fehlermeldung kommt, wenn man erstmalig den hm-rega Adapter installiert, wenn vorher nicht der hm-rpc installiert war.

Dass eine Abhängigkeit vorhanden ist, wusste ich am Anfang noch nicht, das sollte hier erwähnt werden.

**Comment by Apollon77** [comment]
@GermanBluefox I assume Admin stumbles over a "not specified version for hm-rpc" https://github.com/ioBroker/ioBroker.hm-rega/blob/master/io-package.json#L117 ... in this case it should simply tell about "the latest available for the chosen repo" - or sucmply state thet hm-rpc wil be added

**Comment by GermanBluefox** [comment]
Text geändert auf `Die neueste verfügbare Version von "%s" ist erforderlich, es ist jedoch nichts installiert. Bitte installieren Sie zuerst "%s" und versuchen Sie es dann erneut.`

**Comment by Feuer-sturm** [comment]
Neuer Text ist mit Admin 6.0.1 sichtbar. Übersetzung erfolgt über weblate (https://weblate.iobroker.net/translate/adapters/admin-web/de/?offset=1&q=latest+available+version&sort_by=-priority%2Cposition&checksum=#suggestions)

![grafik](https://user-images.githubusercontent.com/25422320/172706328-fc1bc576-18c8-415c-b5f4-fc1357657bca.png)
