### ISSUE TITLE
Error in GUI e.g OILFOX

### ISSUE THREAD

**Issue by GSV-Ha-Ma** [ioBroker/ioBroker.admin#1409]
**Describe the bug**  
Error in GUI e.g OILFOX

TypeError: can't convert undefined to object
    value ConfigPanel.js:124
    value ConfigPanel.js:262
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:148
    promise callback*1729/value/< index.js:144
    promise callback*value index.js:142
    n index.js:75
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    et JsonConfig.js:115
    promise callback*1927/n/et</< JsonConfig.js:113
    promise callback*1927/n/et< JsonConfig.js:110
    promise callback*n JsonConfig.js:109
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
        Ga
        Ka
        Za
        ke
        Yt
    a helpers.ts:98
    At trycatch.ts:227
    Z instrument.ts:536
    React 8
    e index.js:22
    1525 index.js:84
    u (index):1
    r (index):1
    t (index):1
    <anonymous> main.5451f6a7.chunk.js:2
instrument.ts:124:32
    Z instrument.ts:124
    React 10
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    value index.js:148
    (Async: promise callback)
    value index.js:144
    (Async: promise callback)
    value index.js:142
    n index.js:75
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    et JsonConfig.js:115
    (Async: promise callback)
    et JsonConfig.js:113
    (Async: promise callback)
    et JsonConfig.js:110
    (Async: promise callback)
    n JsonConfig.js:109
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    a helpers.ts:98
    (Async: EventListener.handleEvent)
    At trycatch.ts:227
    Z instrument.ts:536
    React 8
    e index.js:22
    1525 index.js:84
    u (index):1
    r (index):1
    t (index):1
    <anonym> main.5451f6a7.chunk.js:2

**Comment by Apollon77** [comment]
What exactly you did to see the error?

**Comment by Gunni666** [comment]
instrument.ts:124 
        
       TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.value (main.5451f6a7.chunk.js:2:1416095)
    at a.value (main.5451f6a7.chunk.js:2:1418847)
    at Go (6.1cf1778f.chunk.js:2:5614073)
    at Uo (6.1cf1778f.chunk.js:2:5613870)
    at Zi (6.1cf1778f.chunk.js:2:5654815)
    at jl (6.1cf1778f.chunk.js:2:5640983)
    at Sl (6.1cf1778f.chunk.js:2:5640911)
    at Cl (6.1cf1778f.chunk.js:2:5640774)
    at bl (6.1cf1778f.chunk.js:2:5637740)
    at 6.1cf1778f.chunk.js:2:5587234
    at t.unstable_runWithPriority (6.1cf1778f.chunk.js:2:5670444)
    at Ga (6.1cf1778f.chunk.js:2:5587011)
    at Ka (6.1cf1778f.chunk.js:2:5587179)
    at Za (6.1cf1778f.chunk.js:2:5587114)
    at pl (6.1cf1778f.chunk.js:2:5635117)
    at Object.enqueueSetState (6.1cf1778f.chunk.js:2:5591132)
    at n.m.setState (6.1cf1778f.chunk.js:2:5661954)
    at :8081/static/js/1.7dc4b47d.chunk.js:1:6094

**Comment by GSV-Ha-Ma** [comment]
with Chrome:

xxx.xxx.xxx.xxx:8081/#tab-instances/config/system.adapter.oilfox.0

Error:

instrument.ts:124 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.value (ConfigPanel.js:124:23)
    at a.value (ConfigPanel.js:262:31)
    at Go (react-dom.production.min.js:187:188)
    at Uo (react-dom.production.min.js:186:173)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at n.m.setState (react.production.min.js:12:369)
    at index.js:148:34

**Comment by Gunni666** [comment]
when calling the gui to enter username and password

**Comment by Gunni666** [comment]
only in build 4.1.1 not in 4.0.2

**Comment by GSV-Ha-Ma** [comment]
yes, it happened after the update aur 4.1.1, after downgrade to 4.0.2 the problem remains. All adapters are current - Beta (latest)

**Comment by xelarep** [comment]
I'll attach my report here as well: updated to OilFox 4.1.1 end got first error. Then I deinstalled OilFox and did a new install. I cannot access the Settings page (https://XXXXXXXX:8081/#tab-instances/config/system.adapter.oilfox.0) anymore. I get the following messages in the Chrome console:

`index.js:18 iobroker.admin@5.3.4
instrument.ts:124 [2022-04-09T08:35:42.538Z] Try to connect
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 [ADAPTERS] getAdapters
instrument.ts:124 [ADAPTERS] getAdaptersInfo
instrument.ts:124 [ADAPTERS] Render
socketio.png:1          GET https://morbo:8081/adapter/socketio/socketio.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ii @ react-dom.production.min.js:208
Ll @ react-dom.production.min.js:251
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:625
(anonym) @ Adapters.js:704
Promise.then (async)
o.getAdaptersInfo @ Adapters.js:697
(anonym) @ Adapters.js:327
Promise.then (async)
value @ Adapters.js:327
value @ Adapters.js:316
gi @ react-dom.production.min.js:219
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
(anonym) @ react-dom.production.min.js:244
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
ws.png:1          GET https://morbo:8081/adapter/ws/ws.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ii @ react-dom.production.min.js:208
Ll @ react-dom.production.min.js:251
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:625
(anonym) @ Adapters.js:704
Promise.then (async)
o.getAdaptersInfo @ Adapters.js:697
(anonym) @ Adapters.js:327
Promise.then (async)
value @ Adapters.js:327
value @ Adapters.js:316
gi @ react-dom.production.min.js:219
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
(anonym) @ react-dom.production.min.js:244
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1          GET https://raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png 404
Image (async)
y @ react-dom.production.min.js:23
ii @ react-dom.production.min.js:208
Ll @ react-dom.production.min.js:251
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
value @ Adapters.js:625
(anonym) @ Adapters.js:704
Promise.then (async)
o.getAdaptersInfo @ Adapters.js:697
(anonym) @ Adapters.js:327
Promise.then (async)
value @ Adapters.js:327
value @ Adapters.js:316
gi @ react-dom.production.min.js:219
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
(anonym) @ react-dom.production.min.js:244
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
instrument.ts:124 Translate: ra_Disconnected
instrument.ts:124 Translate: ra_Connected
socketio.png:1          GET https://morbo:8081/adapter/socketio/socketio.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ii @ react-dom.production.min.js:208
Ll @ react-dom.production.min.js:251
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonym) @ ObjectBrowser.js:1788
Promise.then (async)
value @ ObjectBrowser.js:1767
value @ ObjectBrowser.js:1864
gi @ react-dom.production.min.js:219
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
xl @ react-dom.production.min.js:252
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
Ae @ react-dom.production.min.js:292
(anonym) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
a @ helpers.ts:98
instrument.ts:124 Translate: ra_Disconnected
instrument.ts:124 Translate: ra_Connected
instrument.ts:124 getInstances: 13
instrument.ts:124 Translate: Edit schedule rule for %s
instrument.ts:124 Translate: Edit schedule rule for %s
instrument.ts:124 Translate: Edit schedule rule for %s
instrument.ts:124 Translate: Edit schedule rule for %s
instrument.ts:124 Translation for word "Main settings" in "de" was ignored: existing = "Allgemeine Einstellungen", new = Haupteinstellungen
(anonym) @ instrument.ts:124
(anonym) @ i18n.js:67
value @ i18n.js:62
(anonym) @ index.js:110
Promise.then (async)
(anonym) @ index.js:103
Promise.then (async)
value @ index.js:100
(anonym) @ JsonConfig.js:112
Promise.then (async)
(anonym) @ JsonConfig.js:110
Promise.then (async)
n @ JsonConfig.js:109
bc @ react-dom.production.min.js:135
Uo @ react-dom.production.min.js:181
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
instrument.ts:124 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at a.value (ConfigPanel.js:124:23)
    at a.value (ConfigPanel.js:262:31)
    at Go (react-dom.production.min.js:187:188)
    at Uo (react-dom.production.min.js:186:173)
    at Zi (react-dom.production.min.js:269:427)
    at jl (react-dom.production.min.js:250:347)
    at Sl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at pl (react-dom.production.min.js:237:203)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at s.m.setState (react.production.min.js:12:369)
    at index.js:148:34
(anonym) @ instrument.ts:124
ui @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
fc @ react-dom.production.min.js:130
Uo @ react-dom.production.min.js:184
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonym) @ index.js:148
Promise.then (async)
(anonym) @ index.js:144
Promise.then (async)
value @ index.js:142
s @ index.js:75
bc @ react-dom.production.min.js:135
Uo @ react-dom.production.min.js:181
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
pl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonym) @ JsonConfig.js:115
Promise.then (async)
(anonym) @ JsonConfig.js:113
Promise.then (async)
(anonym) @ JsonConfig.js:110
Promise.then (async)
n @ JsonConfig.js:109
bc @ react-dom.production.min.js:135
Uo @ react-dom.production.min.js:181
Zi @ react-dom.production.min.js:269
jl @ react-dom.production.min.js:250
Sl @ react-dom.production.min.js:250
Cl @ react-dom.production.min.js:250
bl @ react-dom.production.min.js:243
(anonym) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ga @ react-dom.production.min.js:122
Ka @ react-dom.production.min.js:123
Za @ react-dom.production.min.js:122
ke @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73
a @ helpers.ts:98
`

**Comment by GermanBluefox** [comment]
Please use latest oilfox version v4.1.2

**Comment by xelarep** [comment]
4.1.2 up and running - Thanks a lot!

**Comment by tukey42** [comment]
It works for me, too. Many thanks!
