### ISSUE TITLE
[v3] Creating a user also creates an object with empty _id and index

### ISSUE THREAD

**Issue by WolfspiritM** [ioBroker/ioBroker.admin#141]
It seems like creating a user in admin-beta (v3) also creates an object with an empty ID which breaks displaying Objects in v2 until it's manually removed from objects.json (it also has an empty index there, too: ","": {...}"
The objects looks like that:
```
{
  "common": {
    "name": "test4",
    "icon": "",
    "color": false,
    "desc": "",
    "enabled": true
  },
  "from": "system.adapter.admin-beta.0",
  "ts": 1515455118381,
  "_id": "",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```

"test4" was the user I created.

A correct system.user.test4 object is also created and according to the timestamp it's created prior to the wrong one.

The log also states:
```
admin-beta.0 | 2018-01-09 00:53:41.465 | error | change ID is empty: {"common":{"name":"test4","icon":"","color":false,"desc":"","enabled":true},"from":"system.adapter.admin-beta.0","ts":1515455118381,"_id":"","acl":{"object":1636,"owner":"system....
```

**Comment by GermanBluefox** [comment]
Thank you.

**Comment by GermanBluefox** [comment]
Fixed with https://github.com/ioBroker/ioBroker.admin/commit/1af05310a4e678c316adbc7881e759d1c0addc7a
