### ISSUE TITLE
[Feature] Use striked / crossed Sentry symbol if sentry is disabled

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1411]
You can disable sentry usage for an instance in expert mode. If you do so, the colour of the sentry symbol changes from green to grey. I did not really notice this change at the first glance.

I suggest to adapt the symbol to display a "Striked" or "Crossed Out" Sentry Symbol  if sentry is disabled. 

This change would improve the visibility for handicapped people too.

**Comment by GermanBluefox** [comment]
Like this?
![image](https://user-images.githubusercontent.com/4582016/162634308-10270f69-2574-44ce-8aaf-b78d2fa7e9ce.png)

**Comment by Apollon77** [comment]
OI would also have no problem with a red cross ... better visible (or just a red diagonal line)

**Comment by mcm1957** [comment]
Sorry for late answer. Yes, the crossed symbol is what I suggested. Red colored like Apollon77 suggested would be ok for me too, but I would leave this decision to kernel team as I cannot really decide whether a red cross might cause issues as some user might interpret this as an error.

Thanks for our effort

**Comment by Feuer-sturm** [comment]
How it could look like with red lines
![grafik](https://user-images.githubusercontent.com/25422320/163046484-006e903d-237c-42e3-8f61-4e3722ac2db7.png)

**Comment by Apollon77** [comment]
I would go for C ... B also ok

**Comment by mcm1957** [comment]
I would prefer C or A. Green/Red combination is somehow confusing.
But I would accept B too.

**Comment by Feuer-sturm** [comment]
I prefer C as well.

**Comment by Feuer-sturm** [comment]
@GermanBluefox Will the current icon stay or will you check how it will look like with a red line?

**Comment by GermanBluefox** [comment]
I think C is too colorful
