### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Andreas-W-S** [ioBroker/ioBroker.admin#1412]
**Describe the bug**  
Click --> instances - trash schedule - wrench
The Error in GUI page opens.
The system has been running for 8 months. Last activity: Update

**To Reproduce**  
1. Go to '...'instances - trash schedule 
2. Click on '...' wrench
3. See error

**Expected behavior**  
--> Page of settings for trash schedule opens 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <1.4.1>
 - JS-Controller version: <4.0.21> 
 - Node version: <12.22.7 
 - Operating system: <Debian GNU/Linux>

**Additional context**  

`index.js:18 iobroker.admin@5.1.25
socket.io.js:59 [2022-04-05T11:39:21.677Z] Try to connect
i18n.js:106 Translate: fileToJsonl
i18n.js:106 Translate: time
i18n.js:106 Translate: timeOffset
i18n.js:106 Translate: time
i18n.js:106 Translate: timeOffset
i18n.js:106 Translate: time
i18n.js:106 Translate: timeOffset
i18n.js:106 Translate: time
i18n.js:106 Translate: timeOffset
2i18n.js:106 Translate: fileToJsonl
Adapters.js:447 [ADAPTERS] getAdapters
Adapters.js:651 [ADAPTERS] getAdaptersInfo
Adapters.js:1443 [ADAPTERS] Render
:8081/adapter/ws/ws.png:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
Instances.js:444 getInstances: 5
Instances.js:444 getInstances: 2
i18n.js:106 Translate: Add row
i18n.js:106 Translate: Move down
i18n.js:106 Translate: Delete current row
i18n.js:106 Translate: Move up
i18n.js:106 Translate: Move down
i18n.js:106 Translate: Delete current row
i18n.js:106 Translate: Move up
i18n.js:106 Translate: Move down
i18n.js:106 Translate: Delete current row
i18n.js:106 Translate: Move up
i18n.js:106 Translate: Delete current row
4react-dom.production.min.js:216 
        
       Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140:47)
    at d (react-dom.production.min.js:144:29)
    at v (react-dom.production.min.js:146:132)
    at react-dom.production.min.js:150:224
    at Ro (react-dom.production.min.js:176:171)
    at Ui (react-dom.production.min.js:271:134)
    at Cl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
ii @ react-dom.production.min.js:216`
![iobroker_error 2022-04-05 141059](https://user-images.githubusercontent.com/55000989/161751058-be5e4e99-b66e-43b5-8c61-f10272f7335e.jpg)

**Comment by Feuer-sturm** [comment]
@Andreas-W-S Do you see the same error with stable Version of admin 5.3.4?

**Comment by GermanBluefox** [comment]
Fixed
