### ISSUE TITLE
JsonConfig encrypted field displays encrypted value after save

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/ioBroker.admin#1413]
**Describe the bug**  
Adapter with JsonConfig

Native filed in `io-package.json` defined in `protectedNative` and `encryptedNative`.
When a value is entered in JsonConfig for this field, this value is saved correctly encrypted in the adapter instance config.

Bug: When only "Save" is clicked, the displayed value for this field changes to the encrypted value. If the current config is saved again with the displayed encrypted value, the decrypted value is saved.
If you close the JsonConfig while the encrypted value is displayed and reopen it, the correct decrypted value is displayed. On save the encrypted value appears again.

**To Reproduce**  
1. Open adapter config for a adapter using JsonConfig with encrypted native field
2. Enter a value to the encrypted field
3. Click "Save" and not "Save and close"
4. See the encrypted value in the field and in the saved native config
5. Change any other field and click "Save" again
6. See the decrypted value in the field and in the saved native config

**Expected behavior**  
The field should always be saved encrypted and displayed decrypted.

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/24603271/161763723-0940e824-807c-420f-a429-33740112df22.png)

![grafik](https://user-images.githubusercontent.com/24603271/161763775-174b6f70-0ea9-4475-abfc-c12f08892d47.png)

**Versions:**  
 - Adapter version: admin 5.3.4
 - JS-Controller version: 4.0.21
 - Node version: 16.14.2
 - Operating system:
   - ioBroker Host: Debian buster
   - Client: Windows 10, Firefox 98.0.2

**Additional context**  
Example in [ioBroker.discord adapter](https://github.com/crycode-de/ioBroker.discord) (in development):
- [JsonConfig](https://github.com/crycode-de/ioBroker.discord/blob/4e5b64d66ec78325ee268f61c0acbd95f6ffc9df/admin/jsonConfig.json#L9-L20)
- [io-package.json](https://github.com/crycode-de/ioBroker.discord/blob/4e5b64d66ec78325ee268f61c0acbd95f6ffc9df/io-package.json#L90-L97)

**Comment by GermanBluefox** [comment]
Fixed in next admin version

**Comment by Feuer-sturm** [comment]
@crycode-de Can you please check your issue if it can be closed with new version 5.3.7?

**Comment by crycode-de** [comment]
Seams to be working correctly now in 5.3.7 👍
