### ISSUE TITLE
[jsonConfig] reordering table rows does not refresh select option fields

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1417]
**Describe the bug**  
Moving table rows does not correctly display select option fields.

**To Reproduce**  
Create a table using the following definition:

```
{
    "i18n": true,
    "type": "tabs",
    "items": {
        "devices": {
            "type": "panel",
            "label": "Devices",
            "items": {
                "ips": {
                    "type": "table",
                    "sm": 12,
                    "md": 12,
                    "lg": 12,
                    "label": "Devices",
                    "items": [
                        {
                            "type": "checkbox",
                            "attr": "enable",
                            "width": "10% ",
                            "title": "",
                            "filter": false,
                            "sort": false,
                            "default": true
                        },
                        {
                            "type": "number",
                            "min": 1,
                            "max": 999,
                            "step": 1,
                            "attr": "id",
                            "width": "10% ",
                            "title": "Id",
                            "filter": false,
                            "sort": true,
                            "default": ""
                        },
                        {
                            "type": "text",
                            "attr": "ip",
                            "width": "25% ",
                            "title": "IP Address",
                            "filter": false,
                            "sort": true,
                            "default": "0.0.0.0"
                        },
                        {
                            "type": "select",
                            "attr": "snmp-version",
                            "width": "10% ",
                            "title": "SNMP",
                            "options": [
                                { "label": "snmp v1", "value": 1}, 
                                { "label": "snmp v2", "value": 2},
                                { "label": "snmp v3", "value": 3}
                            ],
                            "filter": false,
                            "sort": true,
                            "default": "1"
                        },
                        {
                            "type": "text",
                            "attr": "community",
                            "width": "25% ",
                            "title": "community",
                            "filter": false,
                            "sort": true,
                            "default": "public"
                        }
                    ]
                }
            }
        }
    }
}
```

- add two rows of data like shown in screenshot 1
- use move row button to exchange the two rows
- you should see a picture like in screenshot 2

Note that all data is correctly exchanged except the two select option elements.

The real data seems to be exchanged anyway. If you save the config and refresh the screen the select option fields are show in exchanged order two.
 

**Screenshots & Logfiles**  
![Screenshot 1](https://user-images.githubusercontent.com/28575778/161996613-057820e9-8e77-44ba-a413-333c882805f0.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/28575778/161996661-c9482b25-1627-4b8c-b905-cc7f4fe70a04.jpg)

**Versions:**  
 - Adapter version: Admin 5.3.4
 - JS-Controller version: using dev-server, not sure how to get the info there
 - Node version: v14.19.1
 - Operating system: Raspian

**Comment by GermanBluefox** [comment]
Fixed in 5.3.7

**Comment by mcm1957** [comment]
Can confirm that fix is working as expected. (dev-server with admin 5.3.7)
Please let me know whether I should close the issue or this is done centrally during / after release of new versions. Don't know yet  what's the normal processing with ioBroker issues

**Comment by Feuer-sturm** [comment]
@mcm1957 If an issue is fixed and validated you can close it (or someone else will do it :-) )

**Comment by mcm1957** [comment]
Thanks for the info.
I did not want to close it as I did not know whether I confuse i.e. the collection of fixed issues for next stable release or something like this. Next time I will close own issiues if I can verify the solution and no one from core team closed it already.
