### ISSUE TITLE
Error: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by tonysteffen** [ioBroker/ioBroker.admin#1419]
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at _i (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5632131)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Tl (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5643921)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5670444)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5587011)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at xl (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5641879)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at bl (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5637965)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5587234function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5670444)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ga (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5587011)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Ka (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5587179)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Za (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5587114)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at pl (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5635117)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at Object.enqueueForceUpdate (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5591439)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at s.m.forceUpdate (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:5662041)function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at http://192.168.178.53:8081/static/js/3.e5852c98.chunk.js:1:12235function(e,t){return Object(ze.jsxs)("div",{children:[e,Object(ze.jsx)("br",{})]},t)}    at a (http://192.168.178.53:8081/static/js/6.1cf1778f.chunk.js:2:6328631)

**Comment by Feuer-sturm** [comment]
@tonysteffen which admin version is in use and what did you do to trigger the issue?

**Comment by tonysteffen** [comment]
Hallo. Admin-version v5.3.4.  Der Fehler tritt ohne erkennbaren Grund auf.

**Comment by Feuer-sturm** [comment]
Gehst du dabei in ein spezielles Menü? Instanzen, Objekte, ....?

**Comment by GermanBluefox** [comment]
Kann es sein, dass die Admin Version kurz vorher upgedatet wurde?

**Comment by tonysteffen** [comment]
Ich habe das komplette System vor kurzen neu aufgelegt

**Comment by Feuer-sturm** [comment]
Dann würde ich sagen, dass dieses issue geschlossen werden kann oder hast du noch etwas im log gesehen @GermanBluefox , so dass es sich lohnt das issue offen zu lassen?
