### ISSUE TITLE
[Feature Request] Allow the use of jsonc format in jsonConfig

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/ioBroker.admin#1424]
**Is your feature request related to a problem? Please describe.**
The jsonConfig and jsonCustom json files gets somewhat confusing if there are many entries.
Using the jsonc (JSON with comments) parser we could add comments to the json to allow some annotations.

**Describe the solution you'd like**
Use the [jsonc-parser](https://github.com/Microsoft/node-jsonc-parser) to parse `jsonConfig.json` and `jsonCustom.json`.

**Describe alternatives you've considered**
a) Just do a simple regexp replace to strip out some basic comments (may also remove false positives)
b) Use the normal json format without comments as currently supported.

**Additional context**
\---

**Comment by GermanBluefox** [comment]
Added support of JSON5 https://json5.org/
files must have names:
- jsonConfig.json5
- jsonCustom.json5

**Comment by GermanBluefox** [comment]
> @GermanBluefox Can ypou please also adjust the adapter checked to consider this and the testing lib?

Done

**Comment by mcm1957** [comment]
A hint for using json5 based jsonConfig.json:

As the adapter creator does not yet add json5 to the packaged files when creating a new adapter or when you are migrating an existing adapter, please ensure that json5 files are packaged (Check files section at package.json)

```"admin{,/!(src)/**}/!(tsconfig|tsconfig.*|.eslintrc).json"```  -->  ```"admin{,/!(src)/**}/!(tsconfig|tsconfig.*|.eslintrc).{json,json5}"```
