### ISSUE TITLE
Alias convert shows validation error in dialog (but works like expected)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1426]
**Describe the bug**  

Usage of functions in alias convert functions leads to error. e.g. *Cannot execute function: SyntaxError: JSON Parse error: Unexpected identifier "string"*

**To Reproduce**  

1. Create a new alias
2. Use functions like ``JSON.parse()`` in read
3. see error:

<img width="431" alt="Screenshot 2022-04-13 at 10 48 30" src="https://user-images.githubusercontent.com/1959049/163138473-1f2e4a1c-80fd-4dc1-b47c-d74c3e7af1e1.png">

**Expected behavior**  

JavaScript is validated correctly

**Versions:**  

 - Adapter version: 5.3.7

**Comment by Apollon77** [comment]
@klein0r Hmm ... I assume that this is the "function validator" that simply uses "string" as teststring as value...

What "role" the relevant object has?

**Comment by Apollon77** [comment]
In fact this wpuld be a "feature request in my eyes" to allow for states with roles like "json" or "object" (you would need to adjust your role) a json as test string.

a PR would need to adjust this here https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/Object/ObjectBrowserEditObject.js#L195-L240

**Comment by klein0r** [comment]
Okay, I thought the validation works with the current value of the alias state. Instead, it works just with a dummy value which depends on the data type:

https://github.com/ioBroker/ioBroker.admin/blob/b740603f48a8258141a2b431650aeae1884b77de/src-rx/src/components/Object/ObjectBrowserEditObject.js#L219-L225

This explains the error ``Unexpected identifier "string"``. I've had no idea where this "string" came from. 😄 In my example the validator executes this:

```javascript
JSON.parse('string').myAttr
```

So there are two options:

1. change role to "json" and add an example json (as you mentioned)
2. work with the "real" state value of the linked alias object

The first option has the problem, that nobody knows which attributes the JSON has and what data type they have. The validation will always fail.

```javascript
JSON.parse('{}').myAttr
```

is ``undefined``

**Comment by Apollon77** [comment]
Ok, then we might need a combination?
Use existing state value - if there is one !== null/not-set - else use a dummy value?
