### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by hartiman** [ioBroker/ioBroker.admin#1429]
BUG 
siehe Protokoll unten  (bin Anfänger !!)

********************************************************************************************************************
Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like
error
**************************************************************************************************************************

​

**Comment by Feuer-sturm** [comment]
Hallo @hartiman , welche Admin Version ist bei dir installiert? Was hast du gemacht, um den Fehler zu provozieren?

**Comment by hartiman** [comment]
Nach Major Update aloles wieder OK
