### ISSUE TITLE
Selected line in historical data is not readable in light mode of admin

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1430]
**Describe the bug**  
If light mode in admin is activated and historical data of a state is shown the values are hard to read if a line is selected

**To Reproduce**  
- Enable logging for an state
- open settings of this state
- switch to historical data and select an entry

**Expected behavior**  
Text of selected line is good to read, e.g. color of text switches to white or the background color the the selected line will be changed

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/163566592-aceee5ab-ae26-48a4-97e9-5d99db7600f6.png)

**Versions:**  
 - Adapter version: Admin 5.3.7
 - JS-Controller version: 4.0.21

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/170542330-8d22bcfc-983d-4ef2-b290-27e0b9890a9a.png)
