### ISSUE TITLE
failed connection to socket.io from ::ffff:172.16.3.22: (Adapter admin.0)

### ISSUE THREAD

**Issue by JuniperChris929** [ioBroker/ioBroker.admin#1436]
It's 2022 and I still get errors in my ioBroker when I'm coming from an IPv6 Address:
![logs](https://user-images.githubusercontent.com/50320773/164403718-b7e0a861-b547-4a38-af3b-1e4c4fb4f7fc.png)

Can someone look into this?
I thought the ioBroker is fully IPv6 "native" capable?

**Comment by Apollon77** [comment]
Are you sure this is about IPv6? Last assumptions are that it is from SSL usage - and in fact there should be an issue for this already

**Comment by Diginix** [comment]
Duplicate of #1000
