### ISSUE TITLE
5.3.8 - do not save Settings

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.admin#1438]
Admin 5.3.8
Host 4.0.21

ich ändere Einstellungen im Host unter Objekte und unter Zustände.
Beim Speichern und vor dem automatischen Neustart steht im Log eine Fehlermeldung

`2022-04-22 10:37:49.839 - error: host.Raspi-3BioB Cannot find "objects" in data`

Nach dem automatischen Neustart stehen die alten Werte wieder in den Einstellungen des Host. 

iobroker fix
läuft durch, löst aber das Problem nicht.

![111](https://user-images.githubusercontent.com/20645041/164707662-67df972a-72e4-46f6-b1e2-57eb4a97a236.png)
![222](https://user-images.githubusercontent.com/20645041/164707831-c839fcba-b506-4959-ae9e-3a9943ce0733.png)

**Comment by Herbert-Testmann** [comment]
ich hatte vermutet, dass der Abschnitt "objects" vielleicht in
/opt/iobroker/iobroker-data/iobroker.json
nicht vorhanden ist. Er ist aber dort.

`{
  "system": {
    "memoryLimitMB": 256,
    "hostname": ""
  },
  "network": {
    "IPv4": true,
    "IPv6": true,
    "bindAddress": null,
    "useSystemNpm": true
  },
  "objects": {
    "type": "jsonl",
    "typeComment": "Possible values: 'file' - [port 9001], redis - [port 6379], couch - [port 5984].",
    "host": "127.0.0.1",
    "port": 9001,
    "user": "",
    "pass": "",
    "noFileCache": false,
    "connectTimeout": 2000,
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    }
  },
  "states": {
    "type": "jsonl",
    "typeComment": "Possible values: 'file' - [port 9000], 'redis' - [port 6379].",
    "host": "127.0.0.1",
    "port": 9000,
    "options": {
      "auth_pass": null,
      "retry_max_delay": 5000
    }
  },
  "log": {
    "level": "info",
    "maxDays": 7,
    "noStdout": true,
    "transport": {
      "file1": {
        "type": "file",
        "enabled": true,
        "filename": "log/iobroker",
        "fileext": ".log",
        "maxsize": null,
        "maxFiles": null
      },
      "syslog1": {
        "type": "syslog",
        "enabled": true,
        "host": "192.168.1.114",
        "host_comment": "The host running syslogd, defaults to localhost.",
        "port": "514",
        "port_comment": "The port on the host that syslog is running on, defaults to syslogd's default port(514/UDP).",
        "protocol": "udp4",
        "protocol_comment": "The network protocol to log over (e.g. tcp4, udp4, unix, unix-connect, etc).",
        "path": "",
        "path_comment": "The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).",
        "facility_comment": "Syslog facility to use (Default: local0).",
        "localhost": "iobroker",
        "localhost_comment": "Host to indicate that log messages are coming from (Default: localhost).",
        "sysLogType_comment": "The type of the syslog protocol to use (Default: BSD).",
        "app_name_comment": "The name of the application (Default: process.title).",
        "eol_comment": "The end of line character to be added to the end of the message (Default: Message without modifications)."
      }
    }
  },`

**Comment by Apollon77** [comment]
Wenn Du per Admin Host Settings änderst dann generiert Admin ein neues iobroker.json und sendet das an den server ... in diesem ist dann scheinbar was kaputt und daher wird es gar nicht gespeichert

**Comment by Herbert-Testmann** [comment]
Jetzt können wir das Problem zwischen Admin und Server hin und her schieben, oder uns auf die gezielte Fehlersuche begeben ...

- in welcher Datei werden die Einstellungen gespeichert?
- welche Rechte sollte die Datei haben?
- kann ich die Datei löschen und wird diese dann bei einem "iobroker start"  neu (mit default Werten) angelegt?
- wo sind die möglichen Optionen, die in der Datei mit den Host Einstellungen drin stehen könnten beschrieben?

**Comment by Apollon77** [comment]
Liess bitte nochmal genau was ich geschrieben habe. Das issue ist das Admin ein scheinbar falsches iobroker.json erzeugt. also muss zuerst admin geprüft werden. Der Server bekommt das json und prüft es und meckert weil es falsch ist (weil der "object" Abschnitt fehlt und das ist der Fehler der geloggt wird.

**Comment by Apollon77** [comment]
Du kannst eheer mal Admin downgraden versuchen und schauen ob es damit tut ... die 5.3.8 ist glaube schon die Version mit dem Fix

**Comment by Herbert-Testmann** [comment]
> Du kannst eheer mal Admin downgraden versuchen und schauen ob es damit tut ... die 5.3.8 ist glaube schon die Version mit dem Fix

- in der Version 5.3.1  tritt der Fehler bei mir auch auf
- in der Version 5.2.3 sind als Parameter nur IP und Port einstellbar. Der Rest ist aus dem Admin heraus nicht einstellbar

Ich musste dann ein Backup zurück spielen
Admin und alle Adapter wurden auf dem aktuellen Stand neu geladen.
Der Fehler tritt trotzdem auf. Keine Einstellungen für den Host werden aus dem Admin heraus in iobroker.json geschrieben.

**Comment by Herbert-Testmann** [comment]
Test mit js-controller 4.0.23
`2022-04-28 07:52:26.387 - error: host.Raspi-3BioB Cannot find "objects" in data`

iobroker.json  wird nicht neu geschrieben

**Comment by Feuer-sturm** [comment]
@Herbert-Testmann Bitte einmal mit der aktuellen Admin Version 6.0.1 prüfen.
