### ISSUE TITLE
Custom Dialog: Autocomplete - event keypress and / or lostFocus

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#1442]
At the moment, change event of the autocomplete item only fired if you hit the enter key, that means that validator / default function will also only fired after hitting enter.
For a better user experience (quick filling) please implement a change listener for keypress and / or lostFocus event. This was possible in the old gui.

**Comment by GermanBluefox** [comment]
Please test In 5.5.0 or 6.0.0
