### ISSUE TITLE
iobroker - Error in GUI after power failure

### ISSUE THREAD

**Issue by smarthome-nerd** [ioBroker/ioBroker.admin#1443]
After a power failure the iobroker instance restartet automatically. By click on 'instance' the following error ist displayed:

![image](https://user-images.githubusercontent.com/80362490/165157611-95f4cda8-279a-483f-a82b-1eb43b725442.png)

![image](https://user-images.githubusercontent.com/80362490/165157773-3b70ffb0-078c-44d9-9ae1-7d635f263b0f.png)

Now it is not possible to open 'instances' and therefore also not the 'backitup' adapter/instance to backup files.

**Comment by Apollon77** [comment]
could it be that you have sony-bravia adapter ? Please update to latest version
