### ISSUE TITLE
TAB-Auswahl fehlt bei Direktaufruf http://192.168.178.XXX:8081/#tab-objects

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1444]
Ruft man im Browser die tab-objects-Seite direkt auf http://192.168.178.XX:8081/#tab-objects fehlt die TAB-Auswahl links:

![image](https://user-images.githubusercontent.com/84818934/165507416-7b4bdd08-ee19-416b-92d8-a20cc919b685.png)

![image](https://user-images.githubusercontent.com/84818934/165508131-99e1018a-6da1-4a98-bfd5-699307336e87.png)
![image](https://user-images.githubusercontent.com/84818934/165518770-21c43980-5e01-4d61-8cc8-fbca6aa81936.png)

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren. Gibt es anderen Fehler? in browser Konsole?

**Comment by mcuiobroker** [comment]
Jetzt gerade beim Wechseln auf den TAB objects:
![image](https://user-images.githubusercontent.com/84818934/167484241-f8a37cf4-c3f5-4de7-9af2-3b5ed44f77b9.png)
und
![image](https://user-images.githubusercontent.com/84818934/167484281-d831f28d-1596-417a-aed8-6d021104a5e5.png)
F12 DOM:
![image](https://user-images.githubusercontent.com/84818934/167484450-927b5127-854a-4b20-9080-5a08f5ec548c.png)

**Comment by GermanBluefox** [comment]
Deine Verbindung ist weg. 
Wie viele Objekte hast du?
Ist vielleicht dein System zu langsam?
Sieht man was in ioBroker log bezüglich admin? Z.B. Restart wegen irgendwas?

**Comment by mcuiobroker** [comment]
Hier mal als GIF
![Admin-WechselDebug-Info](https://user-images.githubusercontent.com/84818934/169994925-683e999e-0b08-4983-98f9-c84e982ea412.gif)

**Comment by crunchip77** [comment]
ich habe ebenfalls das Problem mit der Tab Leiste(seit admin5). Hin und wieder kommt es vor, das nach einem Browser refresh die Leiste verschwindet. Dabei ist es egal welcher Browser verwendet wird.
`iobroker.admin@5.4.9
instrument.ts:124 [2022-05-29T08:25:58.199Z] Try to connect
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 Stored version: , new version: 5.4.9
:8081/#tab-objects:1 Uncaught (in promise) timeout
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.iobroker.net/api/58/store/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 Cannot read notifications from "system.host.IoBroker": timeout`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/174192725-ac986dba-f4f6-4e7f-9816-52ae02073756.png)
![image](https://user-images.githubusercontent.com/84818934/174192755-630f3e47-7873-4e18-93e4-747a3be4e439.png)
