### ISSUE TITLE
Checkboxen löscht Textfeld 

### ISSUE THREAD

**Issue by AFPass** [ioBroker/ioBroker.admin#1446]
Aktiviere / Deaktiviere ich eine Checkbox werden Textfelder geleert.

https://github.com/Scrounger/ioBroker.linkeddevices/issues/79

**Comment by Apollon77** [comment]
@Scrounger More details needed please

**Comment by Scrounger** [comment]
Checkbox just set an option value to true or false. 

Example:
https://github.com/Scrounger/ioBroker.linkeddevices/blob/42bf1272025469c2981c287f7841748f05892ad6/admin/jsonCustom.json#L84

**Comment by Apollon77** [comment]
And which textfields get empty then?

**Comment by Scrounger** [comment]
> Aktiviere / Deaktiviere ich eine Checkbox "mergeSettingsOnRestart" oder "Aktiviert", wird das Feld "**prefix for id of linked object**" geleert.
