### ISSUE TITLE
make colum width in configuration dialog editable

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.admin#1449]
**Is your feature request related to a problem? Please describe.**
In configuration dialog column width is fixed and not everthing is visible

**Describe the solution you'd like**
Would be nice to change the width of the column.

**Describe alternatives you've considered**
Perhaps some kind of auto size is possible.

**Additional context**
In this case the width for the value is slightly above needed space ;-)
![image](https://user-images.githubusercontent.com/46641961/166903047-7dac4cd0-f0f0-4288-953c-ae102dbc0d05.png)

**Comment by GermanBluefox** [comment]
Implemented

**Comment by Feuer-sturm** [comment]
ok with Admin 6.0.4
