### ISSUE TITLE
v5.4.2: Datenpunkte können nicht gelöscht werden

### ISSUE THREAD

**Issue by Flipperbastler** [ioBroker/ioBroker.admin#1452]
Nach dem Update auf v5.4.2 lassen sich bei mir einzelne Datenpunkte unter "Objekte" mit dem Papierkorb-Symbol nicht mehr löschen. Die "Objekt(e) löschen <Adapter>"-Abfrage / "Wirklich sicher" / "Ganzen Objektbaum" zeigt ausser dem Verschwinden des Abfrage-Fensters kein Resultat. Der Datenpunktbaum existiert weiter.

![datenpunkt1](https://user-images.githubusercontent.com/63420578/167147362-45c34a62-9cbe-4aed-8c36-e78f7f6b2e66.jpg)

**Versions:**  
 - Adapter version: 5.4.2
 - JS-Controller version: 4.0.23
 - Node version: 14.19.2
 - Operating system: Raspberry Pi OS Lite (64-bit)

**Comment by daniel-lo** [comment]
Yep .. auch  bei 5.4.3 .. ich versuche grad die stationen im netatmo zu löschen .. geht nicht .. weder FF noch Edge

**Comment by crunchip77** [comment]
admin 5.4.4

Ganzer Objektbaum lässt sich zwar nicht löschen, aber einzelne Unterverzeichnisse

**Comment by MMeinhardt1** [comment]
admin 5.4.4

Das selbe Problem auch hier, Objekte einzeln löschen ist echt anstrengend. "puh"

**Comment by daniel-lo** [comment]
works for me .. thanks!

**Comment by Flipperbastler** [comment]
Vielen Dank für die schnelle Abhilfe!
