### ISSUE TITLE
Pfad ist nicht definiert -> ergänzen

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1453]
v5.4.2
![image](https://user-images.githubusercontent.com/84818934/167262894-6667f488-a854-4198-9984-4a98fcb79da5.png)
Bitte den Pfad, den es nicht gibt, ergänzen?

**Comment by Feuer-sturm** [comment]
@mcuiobroker Hast du noch weitere Informationen bei welchen Aktionen der Fehler kommt?

**Comment by mcuiobroker** [comment]
Aufgetreten ist der Fehler bei Aktualisierung von dem Instanzen-Tab oder Objekt-Tab. Ganz genau kann ich es nicht sagen.
Ich öffnen im Microsoft Edge immer 4 Tabs gleichzeitig mit einer Gruppe. 
```
<html>
<body>
<!--StartFragment-->

admin.0 | 2022-05-07 20:10:55.999 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
-- | -- | -- | --
admin.0 | 2022-05-07 20:10:46.185 | error | ReferenceError: path is not defined
jarvis.0 | 2022-05-07 20:10:38.094 | info | Client with IP 192.168.178.34 connected.
admin.0 | 2022-05-07 20:10:37.066 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-07 20:10:37.038 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-07 20:10:36.985 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-07 20:10:36.975 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-07 20:10:30.532 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin
admin.0 | 2022-05-07 20:10:30.510 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 javascript
admin.0 | 2022-05-07 20:10:30.499 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin
admin.0 | 2022-05-07 20:10:30.465 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin

<!--EndFragment-->
</body>
</html>
```
![image](https://user-images.githubusercontent.com/84818934/167266689-f2888667-820f-41cf-9afd-b41125956c25.png)
Man könnte es evtl eingrenzen, wenn man zum Connected den TAB z.B. objects schreiben könnte?

**Comment by GermanBluefox** [comment]
Fixed in the next version.

**Comment by mcuiobroker** [comment]
Ein Schritt weiter:
![image](https://user-images.githubusercontent.com/84818934/167308987-a6638122-1234-44c5-9386-434080faa484.png)
Was bedeutet das?

**Comment by GermanBluefox** [comment]
Please test 5.4.5

**Comment by mcuiobroker** [comment]
v5.4.7
Fehler taucht nicht mehr auf.
Thema im Log Connected TAB-Name ergänzen? Eigener Feature Request?

`Connected system.user.admin from ::ffff:192.168.178.34 admin objects`


admin.0 | 2022-05-10 02:41:59.032 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
-- | -- | -- | --
admin.0 | 2022-05-10 02:41:58.113 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin
admin.0 | 2022-05-10 02:41:41.527 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-10 02:41:40.930 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin

**Comment by Apollon77** [comment]
yes please extra issue
