### ISSUE TITLE
Versionsanzeige (installierte Version)  auch in der Instanz-Konfiguration

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1454]
Man hat schon die Versionsanzeige in den TAB Instanzen, wenn man auf die Instanz zum Adapter klickt.
Die User schauen nur öfter bei Nachfragen in die Konfig zum Adapter. Daher die Frage, ob es nicht auch dort sinnvoll wäre die Version anzeigen zu lassen.
![image](https://user-images.githubusercontent.com/84818934/167320168-f8473478-2e6f-4881-a61c-2b5506ebccca.png)

![image](https://user-images.githubusercontent.com/84818934/167320178-0be5975a-4ccc-4134-a8c3-ed715b8bdb62.png)
Direkt neben `Instanzeinstellungen: Adaptername.Instanz` - Version ?

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/168047456-cf27cac1-22c2-47f5-afbc-7515442639ed.png)

**Comment by mcuiobroker** [comment]
Passt mit v3.4.9. Danke.
