### ISSUE TITLE
instanzen sind falsch sortiert

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#1455]
![grafik](https://user-images.githubusercontent.com/6681528/167344057-fdd72b24-f395-4220-8e03-8299e6c5e32f.png)

mhine uns simpleapi kommen noch nach dem zwave..

**Comment by Diginix** [comment]
Mit admin 5.4.4 bei mir auch nicht alphabetisch:
![image](https://user-images.githubusercontent.com/39678667/167346474-18798fc1-e5cc-4fd6-863d-28b355e3480d.png)

**Comment by Flyor** [comment]
![image](https://user-images.githubusercontent.com/64526892/167483830-1b43a960-a762-45de-9359-840e6fb82dcc.png)
der mihome sitzt bei mir korrekt, aber der parser und der simple-api werden bei mir auch unterhalb von zigbee angezeigt (alphabetisch letzter Adapter).

**Comment by Diginix** [comment]
mihome ist ja auch was anderes als mihome-vacuum, aber sollte wohl für die Ursachenforschung keine Rolle spielen

**Comment by Feuer-sturm** [comment]
Das Thema ist vermutlich doppelt zu #1289

**Comment by Diginix** [comment]
Hier geht es um Instanzen und in #1289 um die Adapterliste. Ggf. hat beides dieselbe Ursache.

**Comment by Diginix** [comment]
Was ist denn beim mihome-vaccum Adapter oder parser, die demnach Extensions sind, anders als zB. beim mihome oder shelly Adapter?

**Comment by Apollon77** [comment]
mihome ist keine Extension

EIne Extension läuft "im Web Adapter" quasi und hat pot keinen eigenen Prozess

**Comment by Diginix** [comment]
Ja, mihome wird regulär sortiert, aber mihome-vacuum bei mir, wie oben zu sehen, eben nicht. Ich bezweifle aber dass mihome-vacuum der Definition Extension gerecht wird. Weder wird web verwendet noch gibt es keinen eigenen Prozess. Also wie nun? 😉
