### ISSUE TITLE
Im Log zum Connected-/ Disconnected-Eintrag auch den TAB-Namen hinzufügen

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1457]
`admin.0 | 2022-05-10 02:41:59.032 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34 admin objects`

`admin.0 | 2022-05-10 02:41:58.113 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin objects`

admin.0 | 2022-05-10 02:41:59.032 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
-- | -- | -- | --
admin.0 | 2022-05-10 02:41:58.113 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin
admin.0 | 2022-05-10 02:41:41.527 | info | ==> Connected system.user.admin from ::ffff:192.168.178.34
admin.0 | 2022-05-10 02:41:40.930 | info | <== Disconnect system.user.admin from ::ffff:192.168.178.34 admin

**Comment by Apollon77** [comment]
Was ist der "Tab name"?

**Comment by mcuiobroker** [comment]
Welcher TAB connected wurde:
![image](https://user-images.githubusercontent.com/84818934/167913496-fcaaab51-707f-4483-90d0-dd7014d5c79b.png)
oben als Beispiel `admin objects` mitangegeben.

**Comment by Apollon77** [comment]
Die Authentication ist komplett unabhängig vom aktuellen "tab" der angezeigt wird. die kommt vor allem ... Denke nicht das das sinn macht. Am End eist Admin eine "Singe page application" die alle tabs kann und alles findet nur im Browser in Javascript statt. das ist keine Klassische webseite.
