### ISSUE TITLE
socket.emit('getObjects' submits not all objects

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#1459]
Since one of the recent updates the call
``socket.emit('getObjects', function (err, _objs)`` does not deliver all objects, for example 
``system.adapter.admin`` is missing. I think it is because this object is of type 'adapter'?

Example: 
I use it here https://github.com/sbormann/ioBroker.iqontrol/blob/d4163271dfc8c69e66edcdbb2c1121041c77c1ec/admin/index_m.js#L2957
to fetch all ioBroker Objects.

And here i try to find out the version of admin adapter (which has now stoped working, because system.adapter.admin is missing):
https://github.com/sbormann/ioBroker.iqontrol/blob/d4163271dfc8c69e66edcdbb2c1121041c77c1ec/admin/index_m.js#L2916

Thank you

**Comment by sbormann** [comment]
Thanks for the fix, which works perfectly.

But i think i found another error of the same category:
``socket.emit('renameFile', adapter, oldPath, newPath, callback)`` leads to a crash of the admin-adapter.

**Comment by Apollon77** [comment]
@sbormann Can yopu please open a new issue? This one is closed and so most like invisible. AN please provide a log that shows the stack trace of the crash

**Comment by sbormann** [comment]
OK, here ist the new issue 
#1472 
Thanks
