### ISSUE TITLE
Objects-tab cannot be loaded (InternalError: too much recursion)

### ISSUE THREAD

**Issue by h1ob** [ioBroker/ioBroker.admin#1460]
Dear all,

when loading the objects-tab I get an reproducable GUI Error. I tried with Firefox 100.0 and Edge 101.0.1210.39.

All adapters and ioBroker are up to date.

System-Info:

> iobroker@iobrokerprod:~$ iob info
Platform       : linux
os             : linux
Architecture   : x64
CPUs           : 4
Speed          : 2111 MHz
Model          : Common KVM processor
RAM            : 4.8 GB
System uptime  : 01:22:52
Node.js        : v14.19.2
time           : 1652351887185
timeOffset     : -120
adapters count : 410
NPM            : v6.14.17
Disk size      : 31.4 GiB
Disk free      : 20.9 GiB

Error in the browser:

![1](https://user-images.githubusercontent.com/55213432/168053448-8bf14618-1d30-458b-b665-45f2f08c3972.jpg)
![2](https://user-images.githubusercontent.com/55213432/168053444-ed05fc71-3acc-4353-b758-56b252cf28f9.jpg)

**Comment by Feuer-sturm** [comment]
@h1ob which admin version do you use?

**Comment by h1ob** [comment]
@Feuer-sturm - I use 5.3.8

**Comment by GermanBluefox** [comment]
Please retest with next admin version: 5.4.10
