### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Sebastian-Bindler** [ioBroker/ioBroker.admin#1461]
Mir stürzt dauernd die GUI ab nach einem automatischen Update und ich soll das hier melden.

react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140:47)
    at react-dom.production.min.js:150:265
    at Ro (react-dom.production.min.js:176:171)
    at Ui (react-dom.production.min.js:271:134)
    at Cl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)

**Comment by Feuer-sturm** [comment]
@Sebastian-Bindler Welche Admin Version verwendest du?
Welche Schritte führst du aus / worauf hast du geklickt damit der Fehler kommt?

**Comment by Sebastian-Bindler** [comment]
Meine iObroker hat es irgendwie zerschossen, deswegen weiß ich die Admin Version nicht mehr. Es ist allerdings immer gekommen, als ich auf Benutzer gegangen bin.

Ich hatte einfach die neue Ui und musste ein Passwort vergeben, obwohl ich kein Update gemacht habe. Allerdings waren dann auch alle Adapter weg und mit Backitup konnte ich kein Backup mehr einspielen.

Das Ganze ging erst wieder, als ich alles neu installiert habe und jetzt ist das Problem auch weg. Würde jetzt mal fast sagen, da hat etwas mit der Installation nicht gestimmt, weil die viele verschiedene Probleme gemacht hat.

**Comment by Feuer-sturm** [comment]
Wenn der Fehler nicht mehr mit der aktuellen Installation auftritt würde ich sagen schließen wir das issue hier. Vielleicht hattest du noch eine ältere admin version drauf und hast diesen Bug gesehen #1337
