### ISSUE TITLE
Let's Encrypt ACME support

### ISSUE THREAD

**Issue by TimeToCode15** [ioBroker/ioBroker.admin#1462]
Hey :)
please add the Let's Encrypt ACME support to ioBroker if this is supported you did not need the validation over the webserver than you can validate the domain over a dns entry. 
![image](https://user-images.githubusercontent.com/105454780/168310849-3ef23a94-e41a-41c6-8ebd-51eb752a89c0.png)

Thanks :)

**Comment by Apollon77** [comment]
But this will only work manual, right? Unless we have interfaces to many DNS providers

**Comment by Apollon77** [comment]
Amnd please open this issue in js-controller. Thank you
