### ISSUE TITLE
==> Connected system.user.admin from ::ffff:xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by joergeli** [ioBroker/ioBroker.admin#1463]
Könnte man die log-Meldungen "**==> Connected system.user.admin from ::ffff:xxx.xxx.xxx.xxx**" , welche die  Admin-Version v5.4.9 ausgibt, entfernen, oder **zumindest einstellbar machen**, ob gewollt, oder nicht?
Müllt mir sonst unnötigerweise das Log voll.

**Comment by Apollon77** [comment]
Bitte einfach das Loglevel der Instanz ändern auf "warn" ... Dann sind diese info Logs weg.

**Comment by joergeli** [comment]
... so geht's natürlich auch.
