### ISSUE TITLE
alias creation with already existing name

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1466]
If a meta object exists at the highest level, then it is not possible to create an object with the same name under alias.0.*

![grafik](https://user-images.githubusercontent.com/205119/169036341-69e75642-f220-4e41-89ac-ac54885b3a3a.png)

**Comment by GermanBluefox** [comment]
Please retest with next admin version: 5.4.10

**Comment by Feuer-sturm** [comment]
On my system ok with Admin 6.0.2
