### ISSUE TITLE
[v3] Filter box is almost invisible

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#147]
![filter](https://user-images.githubusercontent.com/17641229/35480980-bf49da1e-041a-11e8-82a7-68b1a5f1ac28.PNG)

Also there's no text on the button next to it in the adapter tab.

**Comment by GermanBluefox** [comment]
Firefox?

**Comment by AlCalzone** [comment]
Yes, Firefox. Will test again with 3.1.3

**Comment by AlCalzone** [comment]
Still present in 3.1.4:
![unbenannt](https://user-images.githubusercontent.com/17641229/35483958-cf5de3ae-0448-11e8-85c7-a6911fbfb65d.PNG)
Now the button left to it is completely gone. The placeholder text "Filter" is too light IMO => #d1d1d1 on a #efefef background

**Comment by GermanBluefox** [comment]
Button should not be shown. And this is a valid behavior. 
Color of placeholder will be changed in 3.1.6

**Comment by GermanBluefox** [comment]
Please retest and close if fixed

**Comment by AlCalzone** [comment]
fixed
