### ISSUE TITLE
[JsonConfig] Static image src not working as documented (relative paths)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1470]
**Describe the bug**  

Created a jsonConfig with a static image - src is a relative path within ``/admin/`` as described here

https://github.com/ioBroker/ioBroker.admin/blob/8c4ff22f8ae839068a2b277a6f40b46d6a83b379/src-rx/src/components/JsonConfigComponent/SCHEMA.md?plain=1#L157-L159

```json
"_azimuthHelp": {
    "newLine": true,
    "type": "staticImage",
    "sm": 12,
    "md": 4,
    "lg": 4,
    "src": "img/Azimuth.png"
}
```

But the image is not displayed. This configuration is working:

```json
"_azimuthHelp": {
    "newLine": true,
    "type": "staticImage",
    "sm": 12,
    "md": 4,
    "lg": 4,
    "src": "adapter/pvforecast/img/Azimuth.png"
}
```

See

https://github.com/ioBroker/ioBroker.admin/blob/8c4ff22f8ae839068a2b277a6f40b46d6a83b379/src-rx/src/components/JsonConfigComponent/ConfigStaticImage.js#L13-L22

**Versions:**  
 - Adapter version: 5.4.9

**Comment by GermanBluefox** [comment]
Fix in next version. Please validate

**Comment by klein0r** [comment]
Thanks for updating the logic:

https://github.com/ioBroker/ioBroker.admin/blob/bf255fd1094145521e0179d2e718a883af7169f3/src-rx/src/components/JsonConfigComponent/ConfigStaticImage.js#L15-L18

Maybe you should also check for ``&& !src.startsWith('adapter/')``

**Comment by Feuer-sturm** [comment]
@klein0r Can we close this issue?
