### ISSUE TITLE
Adapter installation from git starts first after manually kill of "git ls-remote -h -t git://github.com/iobroker-community-adapters/..." process

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.admin#1471]
nodejs: 14.19.2
js-controller: 4.0.23
admin 5.4.9

If I choose GIT as source and select an adapter, I see over xx minutes this screen.
![image](https://user-images.githubusercontent.com/39678667/169796138-b5eefb2f-c971-472e-8465-413c73c2b3f3.png)

This happens since some days/weeks. In the past it was that fast as the normal adapter installation, which is still fast and takes at max some seconds, never above a minute.

In CLI I see these processes that won't finish:
```
node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js url iobroker-community-adapters/ioBroker.pvforecast --host iobroker --debug
git ls-remote -h -t git://github.com/iobroker-community-adapters/ioBroker.pvforecast.git
```
Happens with influxDB adapter and now with pvforecast.

### If I kill the process "git ls-remote", the installation first really starts with these running processes:
```
node /opt/iobroker/node_modules/iobroker.js-controller/iobroker.js url iobroker-community-adapters/ioBroker.pvforecast --host iobroker --debug
git clone --mirror -q https://github.com/iobroker-community-adapters/ioBroker.pvforecast.git /home/iobroker/.npm/_cacache/tmp/git-clone-70f56618/.git
/usr/lib/git-core/git-remote-https origin https://github.com/iobroker-community-adapters/ioBroker.pvforecast.git
```

And finally comes to a successfully end after some seconds:
![image](https://user-images.githubusercontent.com/39678667/169798314-2df4fd7c-0607-4893-b328-d87dad127aa1.png)

**Comment by Apollon77** [comment]
Thsi is an issue on npm 6.x ... should be fixed in npm 7 or 8 ... 

`git config --global url."https://".insteadOf git://`

could solve the issue also with npm 6 ... execute that in /opt/iobroker

**Comment by Apollon77** [comment]
Reason is a change by GitHub:
* https://github.com/npm/cli/issues/4896
* https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by Feuer-sturm** [comment]
> Thsi is an issue on npm 6.x ... should be fixed in npm 7 or 8 ...

With Nodejs: v16.15.1 and NPM: 8.11.0 adapter installations over github are fast as expected.
Since a few weeks nodejs 16 is recommended https://forum.iobroker.net/topic/55678/node-js-16-x-neue-empfehlung-f%C3%BCr-iobroker

@Apollon77 Can we close this issue or is there a reason to keep it open?
