### ISSUE TITLE
Im LOG Herkunft und Nachricht in eigene Spalten trennen

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1474]
![image](https://user-images.githubusercontent.com/84818934/170003614-d3235717-f49d-45b8-b860-7ae848c6ffe6.png)

```
javascript.0 | 2022-05-24 11:47:46.178 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen: Aktuelle Temperatur von SZ_VORNE hat sich geändert auf: 21.5 °C von 21 °C
javascript.0 | 2022-05-24 11:47:45.620 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen: Aktuelle Temperatur von WZ_LINKS hat sich geändert auf: 21 °C von 20.5 °C
```
Zusätzliche Spalte einführen Herkunft/Auslöser
```
Quelle       | Zeit                    |debug |  Herkunft / Auslöser                     | Nachricht
javascript.0 | 2022-05-24 11:47:46.178 | info | script.js.HAUS.HEIZUNG.Log_der_Änderungen| Aktuelle Temperatur von SZ_VORNE hat sich geändert auf: 21.5 °C von 21 °C
```

**Comment by Apollon77** [comment]
Hm ... Only the JavaScript adapter has such a structure, so makes that really sense to add new columns that are only used in such "rare cases"?
In the JavaScript UI you have logs per Script

**Comment by mcuiobroker** [comment]
Das macht Sinn, denn dann kann man die eigentlichen Nachrichten besser sofort erkennen.
Auch im javascript sollte man das trennen:
![image](https://user-images.githubusercontent.com/84818934/170018575-2092e564-1168-4ebd-afea-060f5ba591d7.png)
Es macht dort wenig Sinn dauernd anzuzeigen, dass die Meldung von dem Script kommt, welches man gerade ausführt. Um auch dort die Meldungen besser erkennen zu können, wäre es auch dort sinnvoll sie zu trennen.

**Comment by Apollon77** [comment]
Im Javascript zu oprtimieren ... d'acord ... please cfreate own issue for it ... in Admin I still do not see how this helps when 90%m of the logs are not from javascript
