### ISSUE TITLE
Sidebar is not updated automatically after deleting adapter

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1479]
**Describe the bug**  
- Sidebar is not updated automatically after deleting adapter (f. ex. BackitUp adapter).

**To Reproduce**  
- delete Adapter with entry in the sidebar.

**Expected behavior**  
- update sidebar after deleting adapter

**Screenshots & Logfiles**  
![Animation](https://user-images.githubusercontent.com/69053781/170467456-ad58744d-bfa8-4b33-a7de-705db6d393b4.gif)

**Versions:**  
 - Adapter version: admin v5.3.8
 - JS-Controller version: v4.0.23
 - Node version: v14.19.3
 - Operating system: docker / linux

**Comment by GermanBluefox** [comment]
Cannot reproduce

**Comment by ice987987** [comment]
This is a new, clean installation of ioBroker in a Docker Container (from Buanet). First thing which was done: deleting the two pre installed adapter "Gerätemanager" and BackItUp". The Icon of the BackItUp-Adapter in the left sidebar is not removed automatically, only after a manual refresh of the browser window.

**Comment by crunchip77** [comment]
> 

das liegt wohl daran wie du schon selbst festgestellt hast, am Browser(Cache)

**Comment by ice987987** [comment]
Works in v6.0.8. Thank you very much!
