### ISSUE TITLE
[v3] Header layout is broken

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#148]
The button breaks out of the header bar, see screenshot:
![header-layout](https://user-images.githubusercontent.com/17641229/35481007-4d6b98dc-041b-11e8-8fb4-88bc7f92c32c.PNG)

**Comment by GermanBluefox** [comment]
Fixed in 3.1.3

**Comment by AlCalzone** [comment]
Can confirm
