### ISSUE TITLE
ERROR IN GUI when opening permissions of object owned by a deleted user

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.admin#1482]
**Describe the bug**  
ERROR IN GUI when opening permissions of state owned by a deleted user

**To Reproduce**  
1. Create a new user
2. Create an object and change permissions in objects tab (owner = created user)
3. Delete the user
4. Try to change permissions again

**Expected behavior**  
Should be possible to access permissions settings without ERROR
...maybe iobroker should automatically change ownership of objects to admin when a user is deleted

**Screenshots & Logfiles**  
Message: ERROR IN GUI

Console Error Message:
```
6.0126dbd0.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'value')
    at is (15.948287e5.chunk.js:1:125499)
    at oo (6.0126dbd0.chunk.js:2:5620627)
    at $o (6.0126dbd0.chunk.js:2:5630194)
    at Zi (6.0126dbd0.chunk.js:2:5673918)
    at jl (6.0126dbd0.chunk.js:2:5660168)
    at Vl (6.0126dbd0.chunk.js:2:5660096)
    at Cl (6.0126dbd0.chunk.js:2:5659959)
    at bl (6.0126dbd0.chunk.js:2:5656925)
    at 6.0126dbd0.chunk.js:2:5606419
    at t.unstable_runWithPriority (6.0126dbd0.chunk.js:2:5689629)
    at Ga (6.0126dbd0.chunk.js:2:5606196)
    at Ka (6.0126dbd0.chunk.js:2:5606364)
    at Za (6.0126dbd0.chunk.js:2:5606299)
    at Pl (6.0126dbd0.chunk.js:2:5666063)
    at t.unstable_runWithPriority (6.0126dbd0.chunk.js:2:5689629)
    at Ga (6.0126dbd0.chunk.js:2:5606196)
    at Rl (6.0126dbd0.chunk.js:2:5665338)
    at Re (6.0126dbd0.chunk.js:2:5677623)
    at Yt (6.0126dbd0.chunk.js:2:5584888)
    at HTMLBodyElement.a (6.0126dbd0.chunk.js:2:6292702)
(anonymous) @ 6.0126dbd0.chunk.js:2
ui @ 6.0126dbd0.chunk.js:2
n.payload @ 6.0126dbd0.chunk.js:2
fc @ 6.0126dbd0.chunk.js:2
Uo @ 6.0126dbd0.chunk.js:2
Zi @ 6.0126dbd0.chunk.js:2
jl @ 6.0126dbd0.chunk.js:2
Vl @ 6.0126dbd0.chunk.js:2
Cl @ 6.0126dbd0.chunk.js:2
bl @ 6.0126dbd0.chunk.js:2
(anonymous) @ 6.0126dbd0.chunk.js:2
t.unstable_runWithPriority @ 6.0126dbd0.chunk.js:2
Ga @ 6.0126dbd0.chunk.js:2
Ka @ 6.0126dbd0.chunk.js:2
Za @ 6.0126dbd0.chunk.js:2
Pl @ 6.0126dbd0.chunk.js:2
t.unstable_runWithPriority @ 6.0126dbd0.chunk.js:2
Ga @ 6.0126dbd0.chunk.js:2
Rl @ 6.0126dbd0.chunk.js:2
Re @ 6.0126dbd0.chunk.js:2
Yt @ 6.0126dbd0.chunk.js:2
a @ 6.0126dbd0.chunk.js:2
```

**Versions:**  
 - main.0f2c8246.chunk.js:2 iobroker.admin@5.3.8

**Additional context**  
Workaround: Open settings of the object owned by a deleted user. Change object data "owner" manually to admin or other user. 

Regards,
André

**Comment by Feuer-sturm** [comment]
Issue is available with admin 5.4.9 as well.

**Comment by Feuer-sturm** [comment]
With Admin 6.0.1 it is now possible to enter the menu even the user who is the owner is deleted.

In Objectdaten of the state the old user is still included:
![grafik](https://user-images.githubusercontent.com/25422320/172711963-8c83e961-3b0e-4242-9c1f-614d41b0a243.png)

This is how it looks like if you enter the menu for the permissions:
![grafik](https://user-images.githubusercontent.com/25422320/172712176-85411d2b-86f4-49f2-a1ef-f12676d40b3a.png)

@GermanBluefox Is this how it should look like or should an existing user (e.g. admin) be the new owner?

**Comment by GermanBluefox** [comment]
> In Objectdaten of the state the old user is still included:

You must manually set new user.

**Comment by Feuer-sturm** [comment]
So it works as designed :-)
