### ISSUE TITLE
Every 2 Days I need to relogin and have Error in the protocol

### ISSUE THREAD

**Issue by aortmannm** [ioBroker/ioBroker.admin#1483]
Every 1-3 days I need to relogin, I use the admin user and have just http enabled right now because I thought it could be the self signed cert but this doesnt seems to be the issue.

I just have the Message Ërror" in protocol nothing else. The Cookie that I get after the login is valid for one month.

![image](https://user-images.githubusercontent.com/3414298/170872866-805f1765-a7aa-4bb1-a570-ee97afefaa44.png)

Versions is all stable right now
Admin: 5.3.8

**Comment by Feuer-sturm** [comment]
Is duplicate to [#1000](https://github.com/ioBroker/ioBroker.admin/issues/1000)
