### ISSUE TITLE
Admin 6 color issue in normal design

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.admin#1488]
Not a very good combination of green and blue, the adapter version is almost invisible
![image](https://user-images.githubusercontent.com/37106885/171922469-aa6c79aa-facd-4ced-ab00-5dcad3079c53.png)
in a gray theme is better, but then the dialog box looks foreign
![image](https://user-images.githubusercontent.com/37106885/171922692-73087101-5f14-43f9-a951-c5292f4f7d2b.png)
the "*" sign for editable objects is interesting, but it looks somehow strange, maybe it makes sense to select editable objects somehow differently? color or something else? At first I didn't understand what it was
![image](https://user-images.githubusercontent.com/37106885/171923437-b73a3a9f-75bb-46f9-b82d-5a23afab056f.png)

admin 6.0.0

**Comment by darkiop** [comment]
Alias create Modal is fixed on bottom = not a popup:

<img width="1895" alt="image" src="https://user-images.githubusercontent.com/205119/171924043-38fee41d-eae6-4c1e-8169-2dbe656ef621.png">

**Comment by Apollon77** [comment]
No collection ossues please!

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/171953272-fe51a029-4284-4885-a830-c327c616d13a.png)
text is not visible in HAM adapter in gray theme

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172329698-2c683251-8eba-4a52-9253-a423c385d760.png)

**Comment by GermanBluefox** [comment]
> the "*" sign for editable objects is interesting, but it looks somehow strange, maybe it makes sense to select editable objects somehow differently? color or something else?

I have no Idea how to mark writable (or may be non-writeable) states. Colors are already used for ack/quality
