### ISSUE TITLE
Admin 6.0 Dependencies check error

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.admin#1489]
**Describe the bug**  
After Updating to 6.0 adapter updates are no longer possible since the dependency check fails due to an error.
I have the newest version of js-controller installed (4.0.23) but update doesn´t work:

![image](https://user-images.githubusercontent.com/69499563/171923231-b3a591fe-c4af-4817-b727-0f324fe9a7f3.png)

Any idea what could be the problem?

**Comment by peer69** [comment]
Same here. In addition the update breaks SSL/TLS certificate support for iobroker.web which I cannot fix by rolling back the admin adapter.

> Cannot create web-server: Error: error:0909006C:PEM routines:get_name:no start line

**Comment by Apollon77** [comment]
@peer69 Please One issue for one issue!!

Additionally: Please see the Admin issue for certificates. Plesse edit a certificate and save again. Does it work then?

**Comment by Apollon77** [comment]
for the update check: duplicate #1490
