### ISSUE TITLE
Admin 6: Update dependency checks broken

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.admin#1490]
PLATTFORM: LINUX
BETRIEBSSYSTEM: LINUX
ARCHITEKTUR: X64
NODE.JS: V16.15.1
NPM: 8.11.0
AKTIVE INSTANZEN: 2

![image](https://user-images.githubusercontent.com/35106961/171924104-cc1e07b9-9bdf-4961-b5d3-45946bfbf8df.png)

![image](https://user-images.githubusercontent.com/35106961/171924163-9b70f74f-b70d-4da0-b4ce-56e42e209aaf.png)

**Comment by darkiop** [comment]
Nicht nur beim Update, auch beim Neu installieren:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/205119/171932511-d4105588-1d88-449f-944d-25f18c42ef50.png">

Frische Installation in nem Debian 11 LXC:
node v14.19.3
npm 6.14.17
admin 6.0

**Comment by amg666** [comment]
Dasselbe bei mir (Versuch eine 3. Instanz von tr-064 zu installieren):
![grafik](https://user-images.githubusercontent.com/45561610/172055937-9c8cbd20-ffb5-4720-aecd-13ffb684757b.png)

**Comment by arteck** [comment]
here also
![grafik](https://user-images.githubusercontent.com/6681528/172314853-9daa0bb0-8081-47e0-8490-b4d91bd20bd3.png)

**Comment by GermanBluefox** [comment]
Hm. semver 7.x is not compatible with vite... Fixed

**Comment by Apollon77** [comment]
ooohhh it is that semver browser topic? ...grrmppfff
