### ISSUE TITLE
Admin 6: Alias create Modal is fixed on bottom

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1491]
Alias create Modal is fixed on bottom = not a popup:

<img width="1807" alt="image" src="https://user-images.githubusercontent.com/205119/171924219-91ddfe06-00e4-4787-9dd1-9f530c482cd0.png">

_Originally posted by @darkiop in https://github.com/ioBroker/ioBroker.admin/issues/1488#issuecomment-1146245088_

**Comment by Feuer-sturm** [comment]
Looks ok with Admin 6.0.2
![grafik](https://user-images.githubusercontent.com/25422320/172930084-e8a41b07-9f29-4a9e-a648-6d4d2ba43ac1.png)
