### ISSUE TITLE
Admin 6: Theme Change Button is not aligned with the neighboring buttons

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1492]
Admin 6

<img width="152" alt="image" src="https://user-images.githubusercontent.com/205119/171954630-09142dc7-8f54-457c-9172-f989a5c67ebb.png">

--> shifted slightly up

Admin 5

<img width="150" alt="image" src="https://user-images.githubusercontent.com/205119/171954702-8c0565d9-303c-428b-aaad-c25c537e6620.png">

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172339285-3d0d9bb6-809b-42d1-8872-b4eb211fbf0e.png)

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 6.0.1
