### ISSUE TITLE
Admin 6 version number is not readable

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#1495]
**Describe the bug**  
Version number in instance configuration isn't visible on light theme if the instance is running, see screenshot.

**To Reproduce**  
1. Go to 'Instances tab'
2. Click on 'Wrench' at any running instance
3. See error

**Expected behavior**  
Readable Text.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/16007760/171993195-eb2209ea-5266-4754-a2aa-3d92443ef462.png)

**Versions:**  
 - Adapter version: 6.0.0
 - JS-Controller version: 4.0.15
 - Node version: 16.15.1
 - Operating system: Ubuntu 20.04
 - Chromium Browser: 102.0.5005.61 
 - Firefox: 100.0.2

**Additional context**  
None

**Comment by Apollon77** [comment]
ducplicate #1488
