### ISSUE TITLE
Admin 6.0 Adapter Installation from NPM/Git not possible

### ISSUE THREAD

**Issue by lobomau76** [ioBroker/ioBroker.admin#1497]
I cannot choose adapter for installation. List is empty:

![image](https://user-images.githubusercontent.com/35029301/171995844-19c8f31c-51cd-4443-a6bb-0c2bf93afd3c.png)

**Versions:**  
 - Adapter version: <6.0>
 - JS-Controller version: 4.0.23
 - Node version: 14.19.3
 - Operating system: linux debian

**Comment by Apollon77** [comment]
Please retry this tomorrow after an repo update... It seems that one repository file was invalid, maybe this was the reason?

**Comment by lobomau76** [comment]
I have just updated again to admin 6.0 (there is no > 6.0, right?) Or do I have to update admin over git?
There is no difference.

**Comment by Apollon77** [comment]
ok, then @GermanBluefox will check
