### ISSUE TITLE
Entdecken Sie alle möglichen Geräte leider nicht möglich

### ISSUE THREAD

**Issue by JogiBarbarski** [ioBroker/ioBroker.admin#1498]
Hallo und einen schönen guten Tag.
Entdecken Sie alle möglichen Geräte.
"Entdecken" drücken , um die Geräte in Ihrem Netzwerk zu finden (Vorher Netzwerk-Firewalls/Verkehrsanalyse-Systeme ausschalten !) oder "Weiter", um Geräte aus dem vorherigen Erkennungsprozess zu verwenden
Letzter Scan am 2022-06-04 13:56:59.715
Lookup devices - 97%
105 device(s) found
und dann steht das Programm und scant nicht weiter.

<img width="781" alt="FF127F8F-2B72-4893-9F75-8A0ED70C691F" src="https://user-images.githubusercontent.com/59523523/171998123-d8cff650-2c8f-47a3-ae4c-1f793b17873e.png">

Raspberry Pi 4, 8GB, 64Bit
Debian Bullseye
ioBroker.admin v6.0.0
Node.js: v14.19.3
NPM: 6.14.17
js-controller
JS controller Installiert: 4.0.23
OS: linux
Latest

**Comment by GermanBluefox** [comment]
Angezeigte Fehler hat mit Entdecken nichts zu tun.
Ich kann leider Fehler nicht reproduzieren:
![image](https://user-images.githubusercontent.com/4582016/172365773-aeca5475-8aea-4e8e-97fb-2f5d1183886c.png)

**Comment by JogiBarbarski** [comment]
Ok Danke, hab es eben nochmal versucht. Das kommt dabei raus.

Raspberry Pi 4, 8GB, 64Bit
Debian Bullseye
ioBroker.admin v6.0.0
Node.js: v14.19.3
NPM: 6.14.17
js-controller
JS controller Installiert: 4.0.23
OS: linux
Latest
auf SSD 1 TB

**Comment by GermanBluefox** [comment]
> Ok Danke, hab es eben nochmal versucht. Das kommt dabei raus. Raspberry Pi 4, 8GB, 64Bit Debian Bullseye ioBroker.admin v6.0.0 Node.js: v14.19.3 NPM: 6.14.17 js-controller JS controller Installiert: 4.0.23 OS: linux Latest auf SSD 1 TB
> […](#)
> Am 07.06.2022 um 13:11 schrieb Bluefox ***@***.***>: ﻿ Angezeigte Fehler hat mit Entdecken nichts zu tun. Ich kann leider Fehler nicht reproduzieren: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

Also. Geht es oder nicht?
