### ISSUE TITLE
Keine Adapter Updates mehr möglich

### ISSUE THREAD

**Issue by m0rph2k** [ioBroker/ioBroker.admin#1499]
Hi

Es lassen sich keine adapter mehr updaten er mein das die Dependencies nicht passen 
Aber JS-Controller ist auf 4.0.23 und admin auf 6.0

Bei Cloud adapter 1.11.5
Dependencies
admin (>=4.0.1): 6.0.0
js-controller (>=3.3.22): 4.0.23

Bei SQL adapter 2.1.1
Dependencies
js-controller (>=3.3.0): 4.0.23
node (>=10.0.0): 14.19.2

Bei Mqtt adapter 4.04
Dependencies
js-controller (>=3.0.0): 4.0.23
node (>=12.0.0): 14.19.2

**Comment by Feuer-sturm** [comment]
Duplicate to #1490
