### ISSUE TITLE
Make appearance of columns in object view fully configurable with mouse

### ISSUE THREAD

**Issue by mickym2** [ioBroker/ioBroker.admin#1500]
Similar to admin 4 - make the column width in object view again fully configurable with a mouse.
Most important:
1. Reseizing column width

Nice to have
2. Hide, Show
3. Rearrange columns order with drag and drop

**Comment by Feuer-sturm** [comment]
In #1130 geht es um das selbe Thema. Am besten dort einen Daumen hoch hinterlassen.

**Comment by mickym2** [comment]
Ja - das war zwar eher - aber wenn man schon an dem Thema arbeitet könnte man ja auch mal die anderen beiden Funktionen, die ich hier rein geschrieben habe evaluieren (rearrange, hide/show). Außerdem ist das andere Issue nun schon seit 9 Monaten offen und ich habe das extra im Rahmen der Version 6 nochmals geöffnet, weil ich gehofft hatte, dass man diese Funktion, die im Admin 4 ja vorhanden war, wieder implementiert hat. Ansonsten verteile ich meine Daumen gerne. ;)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Is it planned to implement this enhancement as well?

2. Hide, Show
3. Rearrange columns order with drag and drop

**Comment by Apollon77** [comment]
I assume not :-)

**Comment by mickym2** [comment]
So as the admin is in stable now - I had tested this version and even if it is great that configuration by mouse is possible - there are some issues which do not work:

On IOS devices iPad or iPhone you cannot change anything - so some columns are not visible at all

**Comment by SliX185** [comment]
@GermanBluefox 

> I assume not :-)

Darf man fragen warum das nicht umgesetzt wird? 
Hide/Show column mit rearrange wär doch super?!

Zudem noch die Frage, warum kann man nicht alle Spalten in der Breite anpassen? 
Gibts da nen logischen Grund? War ja früher auch mal möglich.

... und weil ich schon mal schreibe... 
Gibts nen Tipp wie man am Handy die Objekte halbwegs vernünftig anschauen kann, ohne Desktopwebsite?

Danke schonmal im voraus!

**Comment by Apollon77** [comment]
Ja, das wäre alles super ... ernst gemeint ... leider auch super viel Aufwand das selbst zu bauen (weil es genau solche flexiblen Komponenten im Web nur kommerziell gibt und der Umbau auch nicht ohne sind) ...ich fürchte es wird ein kompromiss werden

**Comment by SliX185** [comment]
Schade nur, dass ja im Admin v4 Objektbrowser noch alles super war... 
Seit Admin v5 sind die Objekte auf mobilen Geräte eigentlich überhaupt nicht nutzbar... Schonmal versucht auf dem Handy bei einer Homematic IP Gruppe was zu finden? Wenn man nicht gerade die ID auswendig kann, schlicht unmöglich... (Siehe Screenshot in Desktopwebsite view)
Admin v4 war zwar nicht auf mobile optimiert, aber zumindest nutzbar.
"Einfach" wieder die v4 Objekte in v6 integrieren? Das wäre für mich die Lösung aller Probleme ; )

Ihr macht echt einen Wahnsinns Job mit der ganzen Entwicklung!!! Aber der Objektbrowser ist seit v5 einfach nur sehr bescheiden.... milde ausgedrückt.

Guten Rutsch!

![Screenshot_20221228_212945_Chrome~3](https://user-images.githubusercontent.com/47434006/209868959-a3ad05bf-de32-4800-a4b7-57664d4d35fd.jpg)

**Comment by Apollon77** [comment]
v4 und v5 sind technisch keider komplett andere Basis ... und daher geht das nicht so einfach ...

**Comment by Feuer-sturm** [comment]
With admin 6.3.7 it is now possible to hide/show the coloums

![grafik](https://user-images.githubusercontent.com/25422320/224569602-e1ae412e-afc6-422d-ad68-c99225d5b306.png)

**Comment by wendy2702** [comment]
Would be still nice to be able to adjust the column width for all columns.

With 6.4.0 is's unfortenately still not possible

**Comment by Feuer-sturm** [comment]
I will close this issue and continue the last open question if all coloums can be resized in this issue https://github.com/ioBroker/ioBroker.admin/issues/1696
