### ISSUE TITLE
Admin 5/6: Files - no list-update after upload/delete

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1502]
**Describe the bug**  
If a file is uploaded or deleted via the "Files" function, then the list of files does not update automatically. Only after a reload of the page the result is visible.

**To Reproduce**  
1. Go to 'Files'
2. Upload and Delete Files

**Expected behavior**  
Automatic update of the file list

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/205119/172000324-a74013d5-6d0d-465a-8544-cd2824f370ae.png)

**Versions:**  
 - Adapter version: Admin 5 +6
 - JS-Controller version: 4.0.23

**Comment by Apollon77** [comment]
This will most likely stay that way until js.controlelr 4.1 ... let's see

**Comment by GermanBluefox** [comment]
Yes, this is js-controller 4.1 feature...
