### ISSUE TITLE
Admin 6: "Blue-Theme" - Settings Dialog: Tab Font from active Tab = background color

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1504]
**Describe the bug**  
Blue admin theme = active
The font color of the current tab corresponds to the background color.
Examples:
Systen Settings
js-controller Settings

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/205119/172000872-9f13afdb-ff3a-45fa-8b6e-d7957954be24.png)
![grafik](https://user-images.githubusercontent.com/205119/172000878-6a678610-ef88-4eee-bee2-f8d0ebc509af.png)

**Versions:**  
 - Adapter version: Admin 6

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172412166-ee308be3-e068-489a-bf8b-35494f913628.png)
