### ISSUE TITLE
Admin 6 - Spaltenbreite falsch, lesen der Objektnamen nicht mehr möglich, Layout zerschossen.

### ISSUE THREAD

**Issue by Frank1604** [ioBroker/ioBroker.admin#1507]
Wie im Titel beschrieben, seit Update auf Admin 6 nicht mehr benutzbar. Keine Möglichkeit gefunden die Spaltenbreite wieder herzustellen.

![grafik](https://user-images.githubusercontent.com/10420590/172070092-b7ec4515-5a5f-45ff-b90f-ad4d1ed3188b.png)

**Comment by Apollon77** [comment]
Hast Du ggf spaltenbreiten gesetzt (klick mal das icon mit den drei balken) die zu gross sind für die ID spalte und?

**Comment by Frank1604** [comment]
Guter Hinweis, danke. Mir war nicht bewusst, dass es diese Möglichkeit gibt. Aber gesetzt ist da nichts, alles steht auf Automatisch.

![grafik](https://user-images.githubusercontent.com/10420590/172071273-f7a1536b-234c-4241-92ac-679f16170ba2.png)

**Comment by Frank1604** [comment]
Firefox 101.0 64Bit.

Browserfensteraußengröße ist 1720 x 1039, Innenfenstergröße des Browesers beträgt 1708 x 948, Bildschirmauflösung ist 2560x1080.

Könnte es evtl daran liegen, dass die Berechnung der Spalten von der Bildschirmauflösung abhängig gemacht wird anstelle von der Browserfenstergröße?

**Comment by Frank1604** [comment]
Vielen Dank fürs fixen. Ich teste es sobald die neue Version bei mir verfügbar ist. Ich schaffe es irgendwie nicht das direkt von hier zu installieren.

**Comment by Frank1604** [comment]
Ok, Verzeihung. Der Tag war lang und ich vergesse schon die Basics.

**Comment by GermanBluefox** [comment]
> Ok, Verzeihung. Der Tag war lang und ich vergesse schon die Basics.
> 
> Habe die neue Version installiert. Wir nähern uns an, aber die erste Spalte ist immernoch viel zu groß. Wenn ich das Fenster nur ein bisschen kleiner mache geht es wieder nicht.
> 
> ![grafik](https://user-images.githubusercontent.com/10420590/172452859-9755035d-e8b3-46a0-b14b-acfa4e439449.png)

Ja, Frank und andere Leute sagen, dass lange IDs bei denen nicht sichtbar sind. Was soll ich tun?

**Comment by Frank1604** [comment]
Ich verstehe was du meinst, und ich wollte auch nicht unhöflich sein. Mir ist es eben nur aufgefallen, dass ich seit Admin 6 nicht mehr in der Lage bin die Namen der Objekte zu sehen. Seit Admin 5 geht es in der mobilen Ansicht schon nicht mehr, jetzt eben auch in der Desktop Ansicht.

**Comment by Frank1604** [comment]
Ich habe das jetzt versucht mit festen Spaltenbreiten hinzubekommen, jedoch habe ich das Gefühl, egal was ich da eintrage die Spalten machen was sie wollen.  In dem Beispiel hier ist sollte der Name deutlich breiter sein als die ID aber genau umgedreht ist es.
Irgendwas stimmt da nicht oder ich mache etwas falsch.

![grafik](https://user-images.githubusercontent.com/10420590/172538858-81a52d52-a07c-4e92-9686-66022a61bd90.png)
![grafik](https://user-images.githubusercontent.com/10420590/172538902-36894739-effa-4e20-a0d6-e9b23ace375e.png)

**Comment by Feuer-sturm** [comment]
@Frank1604 Hat sich dein Problem gebessert mit der aktuellen Admin Version 6.1.x? In der aktuellen Version gibt es jetzt auch die Möglichkeit bedingt die Spaltenbreite mit der Maus zu ändern.

**Comment by Frank1604** [comment]
Gebessert hat es sich tatsächlich, ich kann die Namen der Objekte wieder lesen. Vielen Dank schonmal dafür.
Allerdings ist die Funktion der Spaltengrößenanpassung noch nicht ganz optimal. Die Überschriften der Spalten sind völlig anders als die tatsächlichen Spalten. Ich hänge mal ein Bild an. Die Spalten stehen übrigens immernoch auf Automatisch.

Und ich habe immernoch das Gefühl, es hängt damit zusammen, dass mein Browserfenster nicht die volle Bildschirmbreite einnimmt. Ich habe einen extra breiten Bildschirm den ich zu 2/3 1/3 splitte.
Ziehe ich das Browserfenster auf volle Breite, passt alles.

![grafik](https://user-images.githubusercontent.com/10420590/175383394-424f7da5-c108-41f8-8126-3145a686f29b.png)
![grafik](https://user-images.githubusercontent.com/10420590/175383513-8897a061-ee1b-4510-a659-4cf70c9cf71a.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox I think we can close this issue because this feature was removed with Admin6
