### ISSUE TITLE
socket.emit('writeFile64' ist not working with admin v6

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#1508]
````
socket.emit('writeFile64', adapter, parts.join('/'), base64, function () {
			if (callback) callback(file.name);
		});
````
does nothing since update to admin v6, no error messages, the callback gets just not fired and the file not uploaded.

My complete code is this:
````
function uploadFile(file, path, callback) {
	if (typeof path == 'function') {
		callback = path;
		path = null;
	}
	var reader = new FileReader();
	reader.onload = function(e) { //Closure--> to capture the file information.
		path = (path ? path + "/" : "") + file.name;
		var parts = path.split('/');
		var adapter = parts[1];
		parts.splice(0, 2);
		var data = e.target.result;
		const base64 = btoa(new Uint8Array(data).reduce((data, byte) => data + String.fromCharCode(byte), ''));
		socket.emit('writeFile64', adapter, parts.join('/'), base64, function () {
			if (callback) callback(file.name);
		});
	};
	reader.readAsArrayBuffer(file);
}
````

---

...and by the way: Any chance to get the socket call 'writeDirAsZip' running? Maybe I'm doing it wrong, but since the beginning i did never get that command working. Here is my code:
````
function writeDirAsZip(path, base64Zip, callback) {
	var pathWithoutSlashNamespace = path.substring(namespace.length + 1)
	socket.emit('sendToHost', common.host, 'writeDirAsZip', {id: namespace, name: pathWithoutSlashNamespace, data: base64Zip}, function(data){
		callback(data.error || null, null);
	});
}
````

Thank you!

**Comment by GermanBluefox** [comment]
Cannot reproduce the bug with writeFile64:
![image](https://user-images.githubusercontent.com/4582016/172811063-68653d28-15a2-4918-88e6-4952456575f3.png)
![image](https://user-images.githubusercontent.com/4582016/172811197-cebc08a4-4914-4c97-9d8c-007f2293712d.png)

Can you give me an example of your `adapter` and `path` values?

**Comment by sbormann** [comment]
With the today's updates it works now. Thank you!
