### ISSUE TITLE
WORKAROUND! Admin 6.0.X can not be installed via Admin when Admin 6.0.0 is installed currently

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1509]
Admin 6.0.0 had a bug with dependency checks ´which can also be the reason that Admin 6.0.1 can not be installed via Admin.

Workaround is to use the commandline:

* iob update
* iob upgrade admin

**Comment by sysadmin0815** [comment]
hi, had the same issue as described from @Apollon77 .
Workaround "iob upgrade admin" worked for me. thanks!

**Comment by GermanBluefox** [comment]
You can use "info" adapter for it too

**Comment by Animizio** [comment]
this saved my iobroker and solved the update issue. thanks for this fix

**Comment by Feuer-sturm** [comment]
Admin 6.2.17 is stable. Issue closed.
