### ISSUE TITLE
Datenpunkt "admin" in jeder Instanz nur im Expertenmodus anzeigen

### ISSUE THREAD

**Issue by Siggi0904** [ioBroker/ioBroker.admin#1511]
Mit der Version 5 werden die Meta-Datenpunkte "admin" in jeder Instanz im Objektbaum angezeigt.

Wäre es möglich in Version 6 diese "admin" Datenpunkte nicht anzuzeigenn?

Danke.

**Comment by Apollon77** [comment]
Denke das macht sinn

**Comment by Siggi0904** [comment]
Okay. 

Was ist denn die Idee hinter dem Datenpunkt in jeder Instanz?
Und warum soll der nicht gelöscht werden?

**Comment by Apollon77** [comment]
Das ist ein meta Objekt was da sein muss ...Und wie gesagt ist das schon immer da ... aber ja ohne Expertenmodus sollte an es ausblenden

**Comment by Brainbug01** [comment]
Mit 6.0.2 sieht es gut aus, keine Admin Ordner mehr zu sehen.
