### ISSUE TITLE
UI for Adapter install by link not working correctly

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1513]
**Describe the bug**  
The icons and description text is broken if you want to install / update an adapater by npm/github/link

**To Reproduce**  
1. Go to menu "Installieren aus eigener URL"
2. Click on "npm", "github", "link"

**Expected behavior**  
Icons and text is show correctly

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/172699940-a0c7848c-587a-4d9e-9888-7bbd6fc9fc50.png)
![grafik](https://user-images.githubusercontent.com/25422320/172699975-a4f1056b-b0fb-4df7-a184-e6def8ff3039.png)
![grafik](https://user-images.githubusercontent.com/25422320/172700055-347949b7-ade3-4825-885f-d8257547c1ec.png)

**Versions:**  
 - Adapter version: Admin 6.0.1

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/172714240-bafdc40b-c0d9-4ef7-85f2-578285c68b54.png)
