### ISSUE TITLE
admin 6 - label of data type in object value edit dialog is not complete visible

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.admin#1515]
admin 6.0.2
google chrome 102

![image](https://user-images.githubusercontent.com/39678667/172835866-4cdda39d-9ff2-497f-b059-f62c48e5ce46.png)

**Comment by GermanBluefox** [comment]
Already fixed in 6.0.3

**Comment by Feuer-sturm** [comment]
is fixed with 6.0.3
