### ISSUE TITLE
Admin 6 lässt sich nicht installieren

### ISSUE THREAD

**Issue by Pissbirne** [ioBroker/ioBroker.admin#1516]
weder über Oberfläche noch über command line.

pi@raspberrypi:~ $ iob upgrade admin

This upgrade of "admin" will introduce the following changes:
==========================================================================
-> 6.0.2:
Many GUI fixes done

-> 6.0.1:
Many GUI fixes done

-> 6.0.0:
Breaking changes: no admin@v4(material) interface. Only react interface is possible.
Breaking changes: older browsers do not supported anymore.
Migration from material-ui to mui@v5
Many GUI fixes
Support of JSON5 for the config and custom files
Added run/stop buttons in instance settings dialog
Added support for the file change events
==========================================================================

BE CAREFUL: THIS IS A MAJOR UPGRADE, WHICH WILL MOST LIKELY INTRODUCE BREAKING CHANGES!
Would you like to upgrade admin from @5.4.9 to @6.0.2 now? [(y)es, (n)o]: y
Update admin from @5.4.9 to @6.0.2
host.raspberrypi Adapter "system.adapter.admin.0" is stopped.
NPM version: 8.5.5
Installing iobroker.admin@6.0.2... (System call)
host.raspberrypi Cannot install iobroker.admin@6.0.2: 217

**Comment by Apollon77** [comment]
Execute it via CLI please with "--debug" as additional parameter

**Comment by Pissbirne** [comment]
mit --debug folgendes:

Installing iobroker.admin@6.0.2... (System call)
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /opt/iobroker/node_modules/iobroker.admin
npm ERR! dest /opt/iobroker/node_modules/.iobroker.admin-TtUA2igk
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/iobroker.admin' -> '/opt/iobroker/node_modules/.iobroker.admin-TtUA2igk'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2022-06-09T12_40_38_798Z-debug-0.log
host.raspberrypi Cannot install iobroker.admin@6.0.2: 217

**Comment by Apollon77** [comment]
As my assumoption ... something Npm do not like in your npm tree ... foloow instructuions there and try again ....

Check if that directory he tells exists and if yes remove it

**Comment by Pissbirne** [comment]
nach rm /opt/iobroker/node_modules/.iobroker.admin-TtUA2igk -r

Update erfolgreich

Somit erledigt. Vielen Dank
