### ISSUE TITLE
Update auf V6.02 nicht möglich

### ISSUE THREAD

**Issue by kloppy1984** [ioBroker/ioBroker.admin#1517]
Er sagt ich brauch mindestens Version X.
Diese sind gegeben, er akzeptiert es aber nicht!

<img width="335" alt="image" src="https://user-images.githubusercontent.com/63321205/173009970-6056f5a2-398e-4414-8246-ac4ae622ddb6.png">

Hat jemand eine Idee?

**Comment by Apollon77** [comment]
Schau mal in dem oben angepinnten Issue :-))

https://github.com/ioBroker/ioBroker.admin/issues/1509
