### ISSUE TITLE
[v3] Cannot edit states when state value is null

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#152]
An example from the tradfri adapter:
![state-null](https://user-images.githubusercontent.com/17641229/35486746-c502d5f2-0472-11e8-81e0-0e589ede4e5a.PNG)
I set the state values for groups to `null` when the values of individual lightbulbs don't match. This results in the values to vanish from the objects grid.
In admin v2 I could click the empty cell and enter a new value for the group. In admin v3 this is not possible as there's nothing to click.

**Comment by Apollon77** [comment]
https://github.com/ioBroker/ioBroker.sayit/issues/28 seems to be duplicate

**Comment by GermanBluefox** [comment]
Fixed in 3.1.6

**Comment by AlCalzone** [comment]
fixed
