### ISSUE TITLE
Admin 6 : Verbunden mit Host kommt ständig bei jeden Adapter.

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#1520]
Verbunden mit Host kommt ständig bei jeden Adapter.

![Screenshot (4919)](https://user-images.githubusercontent.com/41079106/173178444-3926adcb-d7a4-4af8-94cf-2a1fcff639a0.png)

Plattform: Windows
NODE.JS: V14.19.3
NPM: 6.14.17
JS Controller: 4.0.23
Admin: 6.0.3

**Comment by PalmManiac** [comment]
Gerade als ich es gelesen habe, gleich mal nachgeschaut und es ist bei mir genauso. Wenn man mit der Maus über eine verbunden Instanz geht, kommt etwa jede Sekunde ein weiterer "Verbunden mit Host" dazu und hört nicht auf.

**Comment by Feuer-sturm** [comment]
is fixed with Admin 6.0.4
