### ISSUE TITLE
Admin 6: Alle Knoten zuklappen im Tab Objekte funktioniert nicht

### ISSUE THREAD

**Issue by Quarkmax** [ioBroker/ioBroker.admin#1521]
Hat man mehrere Objekt-Ordner geöffnet und will diese mit dem Button _Alle Knoten zuklappen_ schließen, werden diese geschlossen, aber nach einem Wechsel des Tabs in der linken Menueleiste und wieder zurück zum Objekte-Tab ist der Ordner wieder geöffnet, wo zuletzt der Focus auf einem Objekt lag. Setzt man vor dem Betätigen des Buttons den Focus auf den Root-Ordner einer aufgeklappten Instanz, dann funktionert es wie gewünscht
![objekte](https://user-images.githubusercontent.com/93822511/173180222-248d808d-9674-4a0f-92a3-9c2ed0939260.png)

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 6.0.4
