### ISSUE TITLE
Namensänderung eigener enum führt zu GUI error

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1523]
Benennt man eine eigene enum um, so kommt es zu einem Fehler.
Des weiteren tuchen manchmal ältere (schon gelöschte enums wieder in der Übersicht auf).

Hier ein Video zu dem Fehler

![enums-dev-janitza-gridvis-nb287-Google-Chrome-2022-06-11-22-12-53](https://user-images.githubusercontent.com/92173565/173230367-765a9160-d220-4be9-ac41-70e4a6087ace.gif)

**Versions:**  
 - Admin version: 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: docker linux (offizelles image von buanet)

**Comment by GermanBluefox** [comment]
Can you provide browser console messages after crash?

**Comment by GermanBluefox** [comment]
I cannot reproduce it with Admin6. Please re-validate

**Comment by BenAhrdt** [comment]
OK, i will check it in Admin 6 later. (when i have installed)

**Comment by Feuer-sturm** [comment]
@BenAhrdt Did you had already time to validate this issue with the current admin version?

**Comment by BenAhrdt** [comment]
Not yet,but i will check

**Comment by BenAhrdt** [comment]
@Feuer-sturm 
I checked it today… actualy i become no error
