### ISSUE TITLE
Admin-Übersicht -> GUI Error

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#1525]
When opening #tab-intro I receive a GUI Error
![grafik](https://user-images.githubusercontent.com/45561610/173338401-534fd9a4-6ba3-4df9-b34f-3195a952e52d.png)

Console log:
```
`TypeError: Invalid Version: undefined
    D semver.js:314
    Y semver.js:647
    t1 semver.js:683
    getHostDescription Intro.jsx:573
    getInstancesCards Intro.jsx:204
    getInstancesCards Intro.jsx:176
    render Intro.jsx:719
    React 8
    k scheduler.production.min.js:13
    nt scheduler.production.min.js:14
```
All other menus working fine (#tab-instances, #tab-objects etc)

​
admin 6.0.3, node.js 14.19.3
Proxmox Container/Debian10
Multihost with 1 PI as a slave`

**Comment by Feuer-sturm** [comment]
@amg666 please check with current version

**Comment by amg666** [comment]
@Feuer-sturm Works fine now with admin 6.0.8, but meanwhile I also switched to node.js 16.x.x and npm 8 x.x
