### ISSUE TITLE
JSON config einert tabele mit select verändet die reihenfolge eines value

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1527]
Ich speichere als Value ein json in einem elect, was wiederum in einer table liegt.

Dies sieht nach speichern so aus:
`{
      "onlineDevices": "{"id":28,"deviceName":"Hauptverteilung 1A / Basisgerät / Untermessungen","type":"JanitzaUMG801MeasurementGroup"}",
      "onlineValues": "{"value":"PowerActive","typeName":"Garage,Whirlpool,Lüfter II","type":"Input05","unit":"W","valueName":"Wirkleistung"}"
    }`

nach einiger Zeit (Habe noch nicht heraus gefunden wann es passiert).

sieht es so aus:

`{
      "onlineDevices": "{"id":28,"deviceName":"Hauptverteilung 1A / Basisgerät / Untermessungen","type":"JanitzaUMG801MeasurementGroup"}",
      "onlineValues": "{"type":"Input05","unit":"W","valueName":"Wirkleistung","typeName":"Garage,Whirlpool,"value":"PowerActive",Lüfter II"}"
    }`

Danach sieht die config dann so aus:
![image](https://user-images.githubusercontent.com/92173565/173619727-482acfb9-9aff-4e49-80ec-f6cebb15ccc5.png)

ich nehme mal an, dass die Reihenfolgenänderung ja bei einem json egal sein sollte, jedoch schreibt die config einen string in das native object.

![image](https://user-images.githubusercontent.com/92173565/173620013-1206adcd-043e-4c6b-9cef-6ed5f43286bc.png)

was mich vermuten lässt, dass es intern irgendwie al json behandelt wird, aber der eingetragene string dann nicht mehr passt und somit kein match zum lable vorhanden ist.
Kann das sein?

**Comment by GermanBluefox** [comment]
Wie sieht jsonconfig aus?

**Comment by BenAhrdt** [comment]
Hier ein Link zur config: [JSON-Config](https://github.com/BenAhrdt/ioBroker.janitza-gridvis/blob/main/admin/jsonConfig.json#:~:text=%7D%2C-,%22onlineDeviceTable%22%3A%7B,%7D,-%7D)

**Comment by GermanBluefox** [comment]
Admin behandelt die Values (onlineDevices, onlineValues) als string und kann eigentlich nicht die Reihenfolge da drehen.

**Comment by BenAhrdt** [comment]
Bezüglich der JSON Config.
Hier steht ja bei dem select: onlineValues das hier drin:
`"alsoDependsOn":[
                                "onlineDevices"
                            ]`
Bei Änderung von onlineDevices ruft er die message aber 3 mal auf, warum das?

**Comment by GermanBluefox** [comment]
> Bei Änderung von onlineDevices ruft er die message aber 3 mal auf, warum das?

Wegen update Zyklen... Also da kann ich nichts machen

**Comment by BenAhrdt** [comment]
OK, ist ja im grunde nicht schlimm, dachte nur er ruft das nur einmal bei Änderung auf und hatte mich gewundert.

**Comment by GermanBluefox** [comment]
Geht die Lösung?

**Comment by BenAhrdt** [comment]
Ja, es sieht so aus, als wäre das die Lösung gewesen.
Funktioniert bis jetzt.
