### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by SteveWi-291** [ioBroker/ioBroker.admin#1528]
**Describe the bug**  
Error in GUI!
Dieser Fehler erscheint wenn ich auf http://192.168.1.11:8081/#tab-intro gehe.

![image](https://user-images.githubusercontent.com/71070045/173634785-ba480838-e3b4-4a94-9752-b3f4ebe24ba4.png)
![image](https://user-images.githubusercontent.com/71070045/173634918-f23086df-89c9-440d-bdef-db44c80162e2.png)

`
TypeError: Invalid Version: undefined(p,z)=>A("div",{children:[p,e("br",{})]},z)    at new D (http://192.168.1.11:8081/assets/index.0b3adbb7.js:55:19942)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at Y (http://192.168.1.11:8081/assets/index.0b3adbb7.js:55:23981)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at Function.t1 [as gt] (http://192.168.1.11:8081/assets/index.0b3adbb7.js:55:24446)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at lt.getHostDescription (http://192.168.1.11:8081/assets/Intro.d792c253.js:1:26567)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at http://192.168.1.11:8081/assets/Intro.d792c253.js:1:20552(p,z)=>A("div",{children:[p,e("br",{})]},z)    at Array.map (<anonymous>)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at lt.getInstancesCards (http://192.168.1.11:8081/assets/Intro.d792c253.js:1:19878)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at lt.render (http://192.168.1.11:8081/assets/Intro.d792c253.js:2:904)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at mi (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:15558)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at uo (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:15355)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at wa (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:45195)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at va (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:39989)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at hf (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:39920)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at Hr (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:39780)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at Ei (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:36173)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at pa (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:24:35126)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at k (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:9:1580)(p,z)=>A("div",{children:[p,e("br",{})]},z)    at MessagePort.nt (http://192.168.1.11:8081/assets/__federation_shared_react-dom.js:9:1948)`

![image](https://user-images.githubusercontent.com/71070045/173635220-708ba623-ea26-4ca4-84d7-a5231291e884.png)

Wenn ich auf "http://192.168.1.11:8081/#tab-adapters" klicke, dann kommt keine Fehlermeldung!

Admin Adapter:    v6.0.3
Node.js:                v14.19.2 
NPM:                    v6.14.17

**Comment by GermanBluefox** [comment]
Fixed in 6.0.4

**Comment by Feuer-sturm** [comment]
@SteveWi-291 please check with current version
