### ISSUE TITLE
Objekt Verlaufsdaten Tabelle zerschossen

### ISSUE THREAD

**Issue by Diginix** [ioBroker/ioBroker.admin#1529]
Die Spalten, die nun in der Breite konfigurierbar sind, sind nicht mehr nebeneinander und lassen sich in dem Fall auch nicht mehr durch Skalieren in eine Reihe bringen. Es ist kein Spaltentrenner zum Anfassen und Verschieben vorhanden.

![image](https://user-images.githubusercontent.com/39678667/173753496-2f5fbc60-11e0-4ac1-a97e-b0821597632e.png)

Nur die erste Spalte lässt sich skalieren und damit verschiebt sich alles weitere aber auch.
![image](https://user-images.githubusercontent.com/39678667/173753800-2aae14c2-99bc-4305-97e5-fb8e2bef889d.png)

Es fehlt der horizontale Scrollbalken. Mit der mittleren Maustaste konnte ich nach rechts scrollen und so die Spalten wieder einfangen. Warum die über 1000 px breit waren, k.a. Hier wäre ein fit to max. Sichtbereich schön.

admin 6.0.4

**Comment by GermanBluefox** [comment]
Was passiert, wenn du double-click auf dem "Handle" machst?

**Comment by Diginix** [comment]
Du meinst den beweglichen Trenner?
![image](https://user-images.githubusercontent.com/39678667/173809337-5a636a56-1b18-4251-b019-aeebb06ce88a.png)

Da passiert gar nichts. 
Erst wenn ich den initial einzig sichtbaren Anfasser bewege und die Verlaufstabelle kurz verlasse und erneut öffne, dann sehe ich einen weiteren Spaltentrenner. Ein Doppelklick auf diesen korrigiert dann das komplette Tabellenlayout.
![image](https://user-images.githubusercontent.com/39678667/173809615-5c7bbadb-9bf4-4cdb-b34c-1f91a64ecf87.png)

**Comment by GermanBluefox** [comment]
Ist das Chrom oder Firefox? Ich kann das nicht reproduzieren.
Gibt es Fehler in der BrowserConsole?

**Comment by Diginix** [comment]
Bei dir sieht die Tabelle ja schon gut aus. Das Problem sind Verlaufsdaten von Objekten, die man mit admin 6.0.4 noch nie geöffnet hatte. Alle die ich bisher korrigiert habe, sehe auch weiterhin gut aus. Ich muss also immer neue Objekte suchen, bei denen das Layout noch zerschossen ist. K.a. ob es unterschiedliche Rollen, Datentypen oder oder sein müssen. Bei booleschen Werten finde ich auf die schnelle bei mir keine Layoutfehler mehr.

Ich nutze Chrome 102 und admin hat aktives SSL und Authentifizierung.
In der Console stehen nur Zeilen wie:
![image](https://user-images.githubusercontent.com/39678667/173825904-cda82355-86f8-4f41-8774-031967157739.png)

Also keine Fehler, auch nicht im Netzwerk.

**Comment by klein0r** [comment]
Habe auch nochmal getestet. Funktioniert alles bei mir mit:

- Safari Version 15.5 (17613.2.7.1.8)
- Firefox 101.0.1 (64-bit)
- Chrome Version 102.0.5005.115 (Official Build) (arm64)
- Microsoft Edge Version 102.0.1245.41 (Offizielles Build) (64-Bit)

**Comment by Diginix** [comment]
In Firefox 101 passt die Tabelle bei einem Objekt, wo es in Chrome 102 nicht stimmt. Dahingehend schonmal einzugrenzen.
In einem Chrome Gastfenster, also ohne Addons usw. passt die Darstellung auch ootb.
Demnach ist irgend ein Plugin in meinem Profil ursächlich. Ich recherchiere weiter.

**Comment by Diginix** [comment]
Clear vom local storage hat geholfen. Problem bestand aber an allen PCs an denen admin irgend wann mal geöffnet war.
Also muss da was historisch entstanden sein was beim Sprung zu admin 6.0.4 mit flexibler Spaltenbreite zu diesem Effekt führte.

**Comment by Diginix** [comment]
Leider ist das Problem an beiden PC, auf denen ich admin nutze, wieder vorhanden. Bei beiden Chrome wurde der local storage vor 2 Tagen geleert und iobroker zwischenzeitlich auch aus anderen Gründen neu gestartet.

![image](https://user-images.githubusercontent.com/39678667/174241825-53e184e2-7f6f-4827-9c1b-8e46ec781cce.png)

Workaround bleibt weiterhin der zweifache Wechsel zw. Verlaufsdaten und benutzerdefinierten Einstellungen wodurch dann 2 Handles im Tabellenkopf erscheinen und ein Doppelklick darauf die Tabelle korrigiert.
K.a. was ich hier noch weiter liefern könnte. Ich lasse es mal closed auch wenn nicht fixed.

**Comment by Apollon77** [comment]
Sounds not "fixed" ... lets see if someone else having issues or can reporoduce that.

@Diginix any repro steps you remember?

**Comment by Diginix** [comment]
Only updated admin 6.0.3 to 6.0.4 and opened the object details (gear icon) which goes directly to the history data table. Afaik it remembers the last used tab in this view. So if you exit it from the table, you will get back there the next time.
If you exit from custom settings and get back there and then switch by click to the history data, it could be different.
