### ISSUE TITLE
On opening admin do not display adapter list as starting page.

### ISSUE THREAD

**Issue by robdg80** [ioBroker/ioBroker.admin#153]
Hallo,

currently the adapter list is the default page which will be opend when admin is opend. Better will be the instance page or a little dashboard like ioBroker.info to have as starting page for admin.
When IOBroker is running the adapter page is needed rather rare. Then I'm more interested into current system state.

Maybe the startpage can be configurable in the admin settings.

Thanks

**Comment by GermanBluefox** [comment]
Started the implementation: 
![image](https://user-images.githubusercontent.com/4582016/37435376-62899958-27e3-11e8-873d-2e2469b9671e.png)
