### ISSUE TITLE
Admin 6: Selected history line is "invisible" after selection (white on white?)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1530]
**Describe the bug**  

When a table line is selected (for editing), the content disappears (while selected). See screenshot.

**Screenshots & Logfiles**  

<img width="1459" alt="Screenshot 2022-06-15 at 13 31 19" src="https://user-images.githubusercontent.com/1959049/173817625-94050af5-31fc-4de1-8474-d9943998df9c.png">

**Versions:**  

 - Adapter version: 6.0.4

**Comment by Feuer-sturm** [comment]
@klein0r Is this issue fixed with current admin version?

**Comment by klein0r** [comment]
Fixed (tested with v6.1.5)
