### ISSUE TITLE
Sentry icon wrong position

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1534]
**Describe the bug**  
Sentry icon is at wrong position and not in line with the other instances. On my systems it is only with fritzbox adapter.

**To Reproduce**  
Open instances and check icon position

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/174255155-3e03105c-3271-446f-b3be-9536c1216d64.png)

**Versions:**  
 - Adapter version: 6.0.4

**Comment by Frank795** [comment]
Habe ich auch so, allerdings schon beim Admin v5.4.9 
bei mir ist es der snmp Adapter.

![Sentry](https://user-images.githubusercontent.com/53878761/174468833-3f8a1f4b-e721-41ef-9f87-a7d3a6f5aaaa.PNG)

**Comment by foxriver76** [comment]
is this happening?

**Comment by foxriver76** [comment]
okay can replicate it with fritzbox

**Comment by foxriver76** [comment]
The positioning is wrong, if no `compact` attribute is provided.

**Comment by foxriver76** [comment]
fixed in next version
