### ISSUE TITLE
Add new "metafile" JSONComponent - select a file which has been uploaded via "Files" tab

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1535]
**Describe the solution you'd like**

Let's say a user wants to add an own iCal file which is stored locally (e.g. for ical-adapter). For that case,

- an adapter could provide a new meta object (like ``ical.0.calendarFiles`` of type ``type: 'meta'`` and ``common.type: 'meta.user'``
- The user can upload files to that storage (by using the "files" tab)

So far, everything works out of the box right now.

## Feature request

I need a new jsonComponent, which allows to select a file of a given state. Configuration could look like this:

```json
{
    "i18n": true,
    "type": "tabs",
    "items": {
        "_options": {
            "type": "panel",
            "label": "options",
            "items": {
                "iCalFile": {
                    "type": "metafile",
                    "objectId": "calendarFiles",
                    "globPattern": "**/*.ics"
                    "sm": 12,
                    "md": 6,
                    "lg": 6,
                    "label": "iCal file",
                    "help": "Choose a file"
                }
            }
        }
    }
}
```

or (for foreign meta objects):

```json
{
    "i18n": true,
    "type": "tabs",
    "items": {
        "_options": {
            "type": "panel",
            "label": "options",
            "items": {
                "iCalFile": {
                    "type": "metafile",
                    "foreignObjectId": "0_userdata.0",
                    "globPattern": "**/*.ics"
                    "sm": 12,
                    "md": 6,
                    "lg": 6,
                    "label": "iCal file",
                    "help": "Choose a file"
                }
            }
        }
    }
}
```

The config can just contain the file name afterwards and has to be loaded manually.

At the moment, the same procedure could be achieved with a "selectSendTo" and messagebox + readDir. But this is not working for scheduled adapters.

**Comment by GermanBluefox** [comment]
> ```json
> "objectId": "calendarFiles",
> ```

Does this will be mapped to `ical.X.calendarFiles`?

**Comment by klein0r** [comment]
Yes, or we need a placeholder like ``%INSTANCE%`` for ``foreignObjectId``

**Comment by Apollon77** [comment]
Placeholder better because else would not be possible to refer "generic adapter based meta places" so, e.g. when having "vis" itself as user meta object to have a place for all assets or such cases

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/174426048-4d15f484-2fc6-4c5d-91ca-57c867e6e7da.png)

**Comment by klein0r** [comment]
Thanks a lot! I will test it soon 🚀 
"upload" is a path relative to the meta storage, right?

**Comment by GermanBluefox** [comment]
> Thanks a lot! I will test it soon 🚀 "upload" is a path relative to the meta storage, right?

Example: If you to upload into `vis.0/main/` so: objectID is `vis.0`, upload is `main`
![image](https://user-images.githubusercontent.com/4582016/174484731-ba1e715a-246b-4f12-888f-89492360fc9c.png)

**Comment by klein0r** [comment]
Works perfectly ❤️
