### ISSUE TITLE
[Feature] Zugriff in Table select auf selects eine übergeordnerten Table

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1537]
Man kann ja innerhalb einer Table bspw. mit einem selectSendTo Daten der Konfigurationsvariablen außerhalb der Table senden.
Hat man nun eine Table innerhalb einer überlagerten Table, so kann man in der zweiten Table nicht mehr auf die Daten der ersten Table zugreifen.
Somit ist ein befüllen eines selectSendTo in der zweiten Table aufgrund der Auswahl des selects aus der 1. Table nicht möglich.
Könnte man hier eine Möglichkeit generieren, dass der das select im inneren Table auch auf das select das äußeren zugreifen kann?
es müsste ja wissen in welchem element es sich befindet, oder?

Hier eine schematische Darstellung, damit man es vielleicht besser versteht.
Die Pfeile sollen die Abhängigkeiten darstellen.

![image](https://user-images.githubusercontent.com/92173565/174296469-6d8dd648-1f78-4454-9b66-0113a3c9f308.png)

**Comment by GermanBluefox** [comment]
Wenn das hier nicht ausreichend ist,
![image](https://user-images.githubusercontent.com/4582016/174299728-d00f44b7-621e-4a39-921a-3e40ca8fa10f.png)

Finde ich dass man das Component lieber selbst schreiben sollte. Es wurde NIE dafür gedacht: Table in Table

**Comment by BenAhrdt** [comment]
@GermanBluefox 
Könnte man also mit dem Arrayindex und globalData auf die überlagerte table zugreifen?

**Comment by GermanBluefox** [comment]
> @GermanBluefox Könnte man also mit dem Arrayindex und globalData auf die überlagerte table zugreifen? Ich komme nämlich mit `${globalData.myValueInTheUpperTable}` nicht auf die Daten
> 
> Edit: Man müsste ja nur irgendwie wissen, was steht in den zeilenalementen des überlagerten table. Kommt man da über den index oder so ran?

Es nicht die Überlagerte Tabelle, sondern alle Daten und ja dadurch, dass du index von überlagerte Tabelle brauchst, kommst du nicht auf die gewünschte Daten

**Comment by GermanBluefox** [comment]
Bitte schreibe eigenen Component: https://github.com/ioBroker/ioBroker.admin-component-template
