### ISSUE TITLE
Admin 6: Adapter Warning Modal - black font color and background-color (Dark Theme)

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1538]
**Describe the bug**  
![grafik](https://user-images.githubusercontent.com/205119/174299945-65540355-32cb-4859-8c3b-a39bc48ecb1a.png)

See screenshot ;)

**Comment by GermanBluefox** [comment]
PLease retry with Admin 6.0.5

**Comment by darkiop** [comment]
fixed.
