### ISSUE TITLE
[Feature] Hinzufügen von Table Zeilen trotz filter

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1539]
Wenn man aktuell bspw. ein Table mit select hat und filtert auf dieses selct, dann verschwindet das "+" zum Hinzufügen von weiteren Table Einträgen.
Wäre es möglich, dass man trotzdem nun Werte hinzufügen kann?
Vielleicht müsste man dann im Filter abfragen, ob der Wert dem filter entspricht, oder leer ist.

Hintergrund:
Ich habe aktuell eine Table mit 2 selects.
Das 2. Select ist vom 1. abhängig.
Siehe auch issu: [#1537](https://github.com/ioBroker/ioBroker.admin/issues/1537)

Nun möchte der User gerne nach dem 1. Select filtern, jedoch dann trotzdem hinzufügen können um zu sehen was er bereits alles ausgewählt hat.

Ist dies Umsetzbar, oder zu viel aufwand?

User könnte auch natürlich x mal hinzufügen und immer das gleiche auswählen und dann filtern.

**Comment by GermanBluefox** [comment]
Problem ist, wenn User was hinzufügt und das sofort ausgefeilter wird, dann denkt der User, dass es nicht funktioniert, da keine Änderungen zu sehen sind. Ich könnte natürlich Flag hinzufügen, dass Addieren trotzt Filter möglich wäre. Aber deine Konstruktionen sehen sowieso zu kompliziert aus und ich empfehle eigene Komponente dafür zu schreiben

**Comment by GermanBluefox** [comment]
Added `allowAddByFilter` option

**Comment by BenAhrdt** [comment]
@GermanBluefox cool, was muss man updaten, damit man diese Funktion nutzen kann?

**Comment by GermanBluefox** [comment]
> @GermanBluefox cool, was muss man updaten, damit man diese Funktion nutzen kann?

Update to Admin 6.0.6

**Comment by BenAhrdt** [comment]
Ok, also wenn man es nutzen möchte in den dependencies Admin >=6.0.6 eintragen?

**Comment by Apollon77** [comment]
ja das auch

**Comment by Feuer-sturm** [comment]
@BenAhrdt Ist hier noch etwas offen oder kann das issue geschlossen werden?

**Comment by BenAhrdt** [comment]
@Feuer-sturm bin beruflich unterwegs und konnte es noch nicht testen.

**Comment by BenAhrdt** [comment]
ich habe es mit admin 6.2.0 getestet.... Keine Änderung zu vorher.

**Comment by GermanBluefox** [comment]
> ich habe es mit admin 6.2.0 getestet.... Keine Änderung zu vorher.

`allowAddByFilter: true` gesetzt?

**Comment by BenAhrdt** [comment]
Funktioniert.
Hatte es nur an der falschen Stelle positioniert.
