### ISSUE TITLE
Overrule system language per ioBroker.admin instance

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.admin#1542]
While I prefer to keep technical stuff in English, my "end-users" prefer to be addressed in their native tongue.

Currently, there is only a global language setting on the system level. For my end users, I must set this to THEIR language, but I cannot have the internal system run only in English.

It would be great if I could overrule the global language settings for the ioBroker.admin adapter so that I could run multiple languages from one ioBroker setup.

The same is obviously true for ioBroker.web, see https://github.com/ioBroker/ioBroker.web/issues/228.

**Comment by Apollon77** [comment]
So you mean an instance specific language setting for the Admin-UI or what exactly you mean?

Are you using iobroker in a commercial way or what are "end users" in your case?

**Comment by Apollon77** [comment]
That would also mean that The Admin UI need to also real it's own instance object to get the override because normally all is based on system.config

**Comment by jpawlowski** [comment]
> So you mean an instance specific language setting for the Admin-UI or what exactly you mean?

Yes. I don't know what works best, overruling in ioBroker.admin or ioBroker.web (ideally both should be possible) but I get that there are technical limitations of the existing language concept.

> Are you using iobroker in a commercial way or what are "end users" in your case?

I don't. End users are household members at home. It describes users who are not developing home automations as an admin, but are simply using them in a way that has been determined by the admin.

I usually refer to everyone as an end user if the person does not know anything about the system details but is a simple "Anwender" 🙃

**Comment by Feuer-sturm** [comment]
@jpawlowski Can you please verify this issue with current admin version?

**Comment by jpawlowski** [comment]
Apologies for late response... just wanted to say "thank you", seems to work as expected! <3
