### ISSUE TITLE
Admin 6.0.5 Menü Browsereinstellung/synchronisieren

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#1543]
Beim anwählen des Settings ist es nicht mehr möglich aus dem Menü zu kommen, Browser-Seite lässt sich nicht mehr bedienen. Abhilfe eines der beiden Optionen auszuwählen.
![image](https://user-images.githubusercontent.com/41550245/174548144-a726f481-31b8-487b-8f1f-a07e1a6508bb.png)

**Comment by Feuer-sturm** [comment]
Is fixed with 6.0.7
