### ISSUE TITLE
Used invalid characters: enum.rooms.basement,_cellar changed to enum.rooms.basement__cellar

### ISSUE THREAD

**Issue by boriswerner** [ioBroker/ioBroker.admin#1548]
**Describe the bug**  
When creating rooms from the standard selection, the log is showing the following warning when selecting the basement:
Used invalid characters: enum.rooms.basement,_cellar changed to enum.rooms.basement__cellar
The comma is too much and leads to doubled underscore

**To Reproduce**  
1. Go to 'enums'
2. Click on '+'
3. Click on default room 'Basement, Cellar'
4. See error in log

**Expected behavior**  
No warning and correct name enum.rooms.basement_cellar

**Screenshots & Logfiles**  
none

**Versions:**  
 - Adapter version: 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: V16.15.1
 - Operating system: RaspberryOS

**Additional context**  
Error is in src-rx/src/assets/rooms/list.json line 541 (as of today), the comma needs to be removed

**Comment by Apollon77** [comment]
Please try with Admin 6.1.x from latest/Beta

**Comment by Feuer-sturm** [comment]
Checked with Admin 6.1.5
I did the steps which are discribed in first post and there is still the warning in the log

`	Used invalid characters: enum.rooms.basement,_cellar changed to enum.rooms.basement__cellar`

**Comment by Feuer-sturm** [comment]
Admin 6.3.7

Created room enum.rooms.cellar and enum.rooms.basement and no errors in log file.

Issue closed.
