### ISSUE TITLE
The first entry of the day is missing in the log view. 

### ISSUE THREAD

**Issue by pk68-github** [ioBroker/ioBroker.admin#1549]
**Describe the bug**  
The first entry of the day is missing in the log view. 
Error occurs under admin V5.3.8 or V6.0.5.

**To Reproduce**  
View logs and compare with log file.

**Versions:**  
 - Adapter version: V5.3.8
 - JS-Controller version: V4.0.23
 - Node version: v14.19.3
 - Operating system: RaspberryOS

**Additional context**  
[Discussion in the iobroker forum:](https://forum.iobroker.net/topic/55700/erster-eintrag-im-log-wird-nicht-angezeigt)

**Comment by GermanBluefox** [comment]
It is fixed in js-controller
