### ISSUE TITLE
[v3] Cannot change loglevel of adapters

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#155]
This seems to be new in 3.1.5, as it worked on 3.1.4 yesterday (Firefox):
![dropdown](https://user-images.githubusercontent.com/17641229/35520652-ee193648-0517-11e8-8d27-07160f1dbab0.PNG)

**Comment by AlCalzone** [comment]
Found out why this is hidden
![dropdown](https://user-images.githubusercontent.com/17641229/35582259-9f29fb12-05ee-11e8-94bf-c1c01a419ee2.PNG)

it's never turned visible when selected

**Comment by GermanBluefox** [comment]
Fixed in 3.1.7

**Comment by AlCalzone** [comment]
fixed
