### ISSUE TITLE
Show Instance Value in Overwiew

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1550]
Which Instance is it?
![image](https://user-images.githubusercontent.com/84818934/175375564-2d79fe87-96b4-49ff-a038-7c0567532800.png)
Could you please add the instance Value (-> Instanz 0 ...)
Thank you.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/175487684-fd527a37-857c-4779-a803-6cc325018c7b.png)

**Comment by mcuiobroker** [comment]
Thanks.
