### ISSUE TITLE
select destination of a host during adapter installation has no effect

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1552]
**Describe the bug**  
If you want to select the destination of a host during adapter installation  this has no effect

**To Reproduce**  
1. Go to Adapter menu
2. Select one adapter to install
3. Try to switch the host to which the adapter shall be installed -> This selection has no effect

The adapter will be installed to the host which is currently selected (see red line in screenshot)

**Expected behavior**  
During install process it should be possible to select the available hosts to which the adapter shall be installed

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/175396599-0cbc2250-0631-443e-ac6e-856ff0a78968.png)

**Versions:**  
 - Adapter version: 6.1.4

**Comment by Feuer-sturm** [comment]
I just found this issue https://github.com/ioBroker/ioBroker.admin/issues/1153#issuecomment-1025997953
Is in linked comment from @Apollon77 the second bullet point still relevant and the dropdown can not work until this is implemented in js-controller?

> 2.) Independent what you choosee as server in the selection the command sent ALWAYS contains the host "which is selected on Admin adapter page "on top" ... so selection is simply unused
> 3.) js.controlle rneeds to detect that a command might not be for him and foward the command so the other host (see https://github.com/ioBroker/ioBroker.js-controller/issues/1716)

**Comment by Feuer-sturm** [comment]
@GermanBluefox I just checked with Admin 6.1.5 but I did not see a different behavior. What should be different from your point of view?

**Comment by GermanBluefox** [comment]
In 6.1.6 it should work

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 6.1.6
