### ISSUE TITLE
Admin won't open (instance is running)

### ISSUE THREAD

**Issue by Flyor** [ioBroker/ioBroker.admin#1553]
![photo5307512158680104664](https://user-images.githubusercontent.com/64526892/175422922-27b0c8ca-3c1a-424b-b382-ed93ca867519.jpg)

System told me to create issue with this text. 

Admin won't start, list instances says: running

VIS and rest of iobroker is running fine. 

Rep =  latest
Last thing i've done: 
Update all of the adapters, apt-get update && upgrade (weekly)
reboot the VM (Linux Server)

Already tried:
- downgrade admin to 5.3.8 by ssh - downgrade worked, but admin url tells me only a white screen (already deleted cache)

**Comment by tobasium** [comment]
Same error on my system after the last admin update.

![image](https://user-images.githubusercontent.com/23247891/175423598-1a795afb-8f70-4702-92f6-f3844ad835c3.png)

**Comment by tobasium** [comment]
ok hab eben gesehen es gibt ein update:

npm install iobroker.admin@6.1.4 --production

jetzt läuft alles wieder

**Comment by Feuer-sturm** [comment]
Yes your issue is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1551
The problem is know with Admin 6.1.2

**Comment by Feuer-sturm** [comment]
@Flyor Which commands did you use to downgrade your admin?
Perhaps you get a faster response in the forum to reactivate your system and get admin running.

**Comment by Flyor** [comment]
> @Flyor Which commands did you use to downgrade your admin? Perhaps you get a faster response in the forum to reactivate your system and get admin running.

cd /opt/iobroker
npm install iobroker.admin@stable --production
