### ISSUE TITLE
admin 6.1.4 Invalid request getRepository 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#1555]
little bug in 6.1.4

`host.iobroker | 2022-06-24 06:40:35.980 | error | Invalid request getRepository. "callback" or "from" is null`

when you switch from host to host on adapter list

https://user-images.githubusercontent.com/6681528/175465090-d3be0a94-c6cd-4a58-b244-abdb7910f1e4.mp4

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
This is how it looks like on my system (Admin 6.1.5). I get the same error message than @arteck 

![grafik](https://user-images.githubusercontent.com/25422320/175662318-3c877fcb-32d6-4b0d-847f-72563ef71bc1.png)

**Comment by GermanBluefox** [comment]
> This is how it looks like on my system (Admin 6.1.5). I get the same error message than @arteck

@Feuer-sturm Which version of js-controller do you use?

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
I made just a downgrade to admin 6.1.5 (with js-controller 4.0.23, which I justed in the past as well) but I am not able to reproduce the error in the log.

@arteck Are you able to reproduce the error?

**Comment by reutli** [comment]
Updated to Admin 6.2.20 today with exactly this issue in LOG. Any suggestions to resolve?


```
  | 2022-09-13 16:37:10.333 | error | Invalid request getRepository. "callback" or "from" is null
-- | -- | -- | --
```

**Comment by wendy2702** [comment]
Updated to 6.2.22 today and got this error:

`2022-09-22 12:34:52.787  - error: host.iobroker Invalid request getRepository. "callback" or "from" is null`

**Comment by daloki83** [comment]
Same error 
`2022-10-14 15:02:32.404 | error | Invalid request getRepository. "callback" or "from" is null`

But no idea how to provocate this. Switching from host to host on adapter list will not trigger this error message for me.

Sys:
Admin v6.2.22
Node.js v18.10.0
NPM v8.19.2
![Screenshot 2022-10-14 152247](https://user-images.githubusercontent.com/29686097/195857918-b35b0f46-2fe7-4f04-b7d1-aa9c75c0db32.png)

**Comment by andre-bu** [comment]
Hello, got the same error message in the LOG. I usually get the message when I call up the adapter list.

`host.ioBkoker202 | 2022-11-03 19:45:50.561 | error | Invalid request getRepository. "callback" or "from" is null`

Admin: 6.2.23
Node.js: v14.19.1
NPM: 6.14.16

**Comment by DrBing** [comment]
Here the same

`host.IO-Broker | 2022-11-21 08:15:44.523 | error | Invalid request getRepository. "callback" or "from" is null`

Admin: 6.2.23
Node.js: v16.18.1
NPM: 8.19.2
js-controller: 4.0.23

**Comment by dsignt** [comment]
Same error message here:

Admin: 6.3.5
Node.js: v16.19.0
NPM: 8.19.3
js-controller: 4.0.24

**Comment by pafade89** [comment]
Get this error very sporadically, but often when the adapter repository is updated manually via admin. (same as @andre-bu)

Admin: 6.3.5
Node.js: v16.18.1
NPM: 8.19.2
js-controller: 4.0.24

**Comment by Vumer4** [comment]
Here the same
`<html><body>


host.iobroker | 2023-04-04 13:38:46.613 | error | Invalid request getRepository. "callback" or "from" is null
-- | -- | -- | --



</body>
</html>`

Admin: 6.3.5
Node.js: v16.19.1 
NPM: 8.19.3
js-controller: 4.0.24

**Comment by DPO99** [comment]
Same Error here

<html>
<body>


host.iobroker | 2023-04-21 12:25:04.439 | error | Invalid request getRepository. "callback" or "from" is null
-- | -- | -- | --



</body>
</html>

Admin: 6.3.5
Node.js: v18.16.0
NPM: 9.5.1
js-controller: 4.0.24

**Comment by Feuer-sturm** [comment]
With admin 6.6.1 the error is a little bit different
```
host.ioBrokerTestsystem
	2023-07-20 21:21:00.504	error	Invalid request getRepository. "callback"(false) or "from"(true) is null
```
js-controller 5.0.8

**Comment by Suschibomber** [comment]
Same at my iobroker :(

**Comment by Michldigital** [comment]
Same here
Admin: 6.3.5
Node.js: v18.17.0
NPM: 9.6.7
js-controller 4.0.24

**Comment by kailausberg** [comment]
` host.vm-iobroker | 2023-08-27 13:54:05.156 | error | Invalid request getRepository. "callback"(false) or "from"(true) is null `

Admin: 6.8.3
Node.js: v18.17.1
NPM: 9.6.7
js-controller 5.0.12

**Comment by andiweli** [comment]
Same here.

Invalid request getRepository. "callback" or "from" is null

Admin 6.8.0
Node 18.17.1

**Comment by RedDaveNY** [comment]
Same message today: 

```
<html>
<body>
<!--StartFragment-->
Invalid request getRepository. "callback"(false) or "from"(true) is null
--


<!--EndFragment-->
</body>
</html>
```

IOBROKER
Plattform: linux
RAM: 7.8 GB
Admin: 6.12.0
Node.js: v18.18.2
NPM: 9.8.1
Java Script 7.1.6

**Comment by Seqway** [comment]
I have the same message at the moment - still no solution available ?

IoB

Plattform: linux
Admin: 6.12.0
Java Script 7.1.6
Node.js    v18.19.0
NPM    10.2.3

**Comment by tehmilcho** [comment]
Same issuse:

2024-01-29 10:57:49.390 | error | Invalid request getRepository. "callback"(false) or "from"(true) is null

Plattform: linux
Admin: 6.13.15
Java Script  dont know
Node.js v18.19.0
NPM 10.2.3

**Comment by jolichter** [comment]
Hi, I see the same problem very rarely, e.g. today 2024-03-07:
`host.manjaro-arm error Invalid request getRepository. "callback"(false) or "from"(true) is null`

It seems to be nothing important?

Plattform: linux manjaro
Architektur: arm64
Modell: Cortex-A72
RAM: 7.6 GB
Admin: 6.13.16
Node.js: v18.18.2
NPM: 10.2.5

**Comment by guitardoc** [comment]
Encountered the same issue:

`Invalid` request getRepository. "callback"(false) or "from"(true) is null`

admin: 6.13.16
node: 20.13.1
npm 10.5.2
js-controller: 8.3.1

**Comment by Feuer-sturm** [comment]
@guitardoc  @jolichter @tehmilcho @Seqway @arteck Is this issue still present with admin7?

**Comment by tehmilcho** [comment]
Hey,
I checked my logs and not found it in the moment, so it's fixed, I guess?

**Comment by jolichter** [comment]
Yes, it looks good and since admin7 I no longer get this error.
