### ISSUE TITLE
admin6.1.5 kein Update mehr per Gui möglich

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#1557]

**Comment by Feuer-sturm** [comment]
@crunchip77 Hast du noch ein paar mehr Details? :-)

Hab gerade mit Admin 6.1.5 versucht ein Downgrade von einem Adapter zu machen wo es dann keinen Fortschritt gab.

![grafik](https://user-images.githubusercontent.com/25422320/175659794-5aa90fec-4ef1-4eda-bce0-96eb701b536b.png)

Browser Console

```
Execute: upgrade daswetter@3.1.2 [instrument.ts:124:32](http://192.168.178.77:8081/static/node_modules/@sentry/src/instrument.ts)
STARTED: upgrade daswetter@3.1.2 [instrument.ts:124:32](http://192.168.178.77:8081/static/node_modules/@sentry/src/instrument.ts)
TypeError: E is undefined
    e1 tools.ts:16
    executor AdminConnection.ts:542
    x Connection.ts:914
    M0 1661.8e29f1de.chunk.js:1
    M0 1661.8e29f1de.chunk.js:1
    x Connection.ts:892
    request Connection.ts:892
    M0 1661.8e29f1de.chunk.js:1
    M0 1661.8e29f1de.chunk.js:1
    request Connection.ts:865
    request AdminConnection.ts:128
    cmdExec AdminConnection.ts:539
    executeCommand Command.jsx:93
    componentDidMount Command.jsx:62
    React 12
    executeCommand App.jsx:1648
    executeCommand App.jsx:1306
    update Adapters.jsx:822
    onClick Adapters.jsx:1924
    React 11
    C1 helpers.ts:99
```

**Comment by crunchip77** [comment]
Nur Ladebalken, weder im Log noch im Browserlog ist etwas zu sehen, bei einem Adapter update.
Per Konsole funktioniert ein Adapterupdate

**Comment by Feuer-sturm** [comment]
Beim Update von einem Adapter kommt das bei mir in der Browser Console

```
Execute: upgrade daswetter@3.1.3 [instrument.ts:124:32](http://192.168.178.77:8081/static/node_modules/@sentry/src/instrument.ts)
STARTED: upgrade daswetter@3.1.3 [instrument.ts:124:32](http://192.168.178.77:8081/static/node_modules/@sentry/src/instrument.ts)
TypeError: E is undefined
    e1 tools.ts:16
    executor AdminConnection.ts:542
    x Connection.ts:914
    M0 1661.8e29f1de.chunk.js:1
    M0 1661.8e29f1de.chunk.js:1
    x Connection.ts:892
    request Connection.ts:892
    M0 1661.8e29f1de.chunk.js:1
    M0 1661.8e29f1de.chunk.js:1
    request Connection.ts:865
    request AdminConnection.ts:128
    cmdExec AdminConnection.ts:539
    executeCommand Command.jsx:93
    componentDidMount Command.jsx:62
    React 12
    closeAdapterUpdateDialog Adapters.jsx:1013
    onUpdate Adapters.jsx:1885
    onClick AdapterUpdateDialog.jsx:518
    React 11
    C1 helpers.ts:99
    X5 trycatch.ts:227
    w2 instrument.ts:536
    React 14
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14
```

**Comment by BernhardLinz** [comment]
Also ich kann beisteuern das es bei dem 6.1.4 noch geht über die GUI, Update 6.1.5 habe ich noch nicht eingespielt

**Comment by sigi2345** [comment]
Dito:

![Screenshot (4982)](https://user-images.githubusercontent.com/41079106/175757068-46c7b745-b50f-4c74-a4c3-29730216dec9.png)

**Comment by fuchs-1978** [comment]
Bei mir mit 6.1.5 ist auch weder Update noch downgrade möglich.

**Comment by Brainbug01** [comment]
Der Workaround ist dann hier wieder beschrieben wie man das nächste Update macht:

https://github.com/ioBroker/ioBroker.admin/issues/1509

**Comment by Horgul123** [comment]
> Der Workaround ist dann hier wieder beschrieben wie man das nächste Update macht:
> 
> #1509

Das hilft aber nicht, wenn es keine neue Version gibt.
Ich kann mit der 6.1.5. auch keinen Adapter mehr aktualisieren :(
Nach downgrade auf 6.1.4 geht es wieder.
Wenn ich unter 6.1.5 ein Update versuche kommt noch ein (z.B.)
$ iobroker upgrade worx@1.6.6
aber mehr passiert nicht mehr

**Comment by Feuer-sturm** [comment]
@Horgul123 dann bleib doch auf der 6.1.4 und warte bis der fix da ist.  :-)

**Comment by Feuer-sturm** [comment]
With Admin 6.1.6 it is now possible to update the adapters over the UI :-)
Thanks @GermanBluefox
