### ISSUE TITLE
Icons moved/cut on small screens

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1558]
**Describe the bug**  
- Icons moved/cut on small screens (header too big/high)
- ioBroker-Icons same if left navigation bar is opened

**Expected behavior**  
- idea: remove sync-icon (two arrows in circle) in the header on small screens to get more space in width **OR** remove "logged in user" and admin-version in header if navigation is closed and show version only in left navigation (as currently is). Perhaps "logged in user" can also displayed in the left navigation.
- same ioBroker icon and icon arrangements if left navigation is opened or closed on (all/small) screens

**Screenshots & Logfiles**  
![A0D6C3C6-B4D7-4B49-B5E5-F56599BF3745](https://user-images.githubusercontent.com/69053781/175800342-54517ce3-9424-4325-b541-648d4da31264.jpeg)
![2E0FA9BE-D9FE-4820-B841-4112DE9284E0](https://user-images.githubusercontent.com/69053781/175800343-ec464e6b-ed22-434a-89cc-371daa43ecda.jpeg)

Furher the „update-progress-bar“ is no longer visible:
![DA86CF12-7E62-42BB-845D-DC78DD30861C](https://user-images.githubusercontent.com/69053781/175830781-9fe048ee-9100-48b7-ba11-6ced4f842ef4.jpeg)

**Versions:**  
 - Adapter version: admin v6.1.4
 - Operating system: iOS 15.5

**Comment by GermanBluefox** [comment]
What about this one?
![image](https://user-images.githubusercontent.com/4582016/175928134-63bbac23-a97f-4992-85bc-3ddf50ccf19a.png)

**Comment by Feuer-sturm** [comment]
Admin 6.1.7
## not ok
- if expert mode is disable the old design is still there
- if expert mode is disabled the progressbar is not visible
![grafik](https://user-images.githubusercontent.com/25422320/176433855-ddb6ece7-e82c-4a14-b265-13b06535f77d.png)


## ok
- Progressbar is visible if expert moded is activated
- optimized design is available if expert mode is activated
![grafik](https://user-images.githubusercontent.com/25422320/176433969-6633a7c0-5cf5-470d-9618-be2ca8d82cb1.png)

**Comment by GermanBluefox** [comment]
There are always limits. On the screen with 1 px width I cannot show any normal layout
![image](https://user-images.githubusercontent.com/4582016/176923462-026a7fd9-fccb-4672-be18-153d41e69708.png)

This is modern mobile phone:
![image](https://user-images.githubusercontent.com/4582016/176923510-65193c62-52f9-4afc-9681-039c0a5ece29.png)

**Comment by Feuer-sturm** [comment]
Hello @GermanBluefox 

I know that there are restrictions with the different resolutions. My expectation was that this design
![grafik](https://user-images.githubusercontent.com/25422320/176931737-f0ffc691-dd24-45bc-ac32-954e177d8aba.png)
is available if expert mode is enabled and disabled. If the design shall be different in both modes it is ok for me. From my point of view I like more the implementation if expert mode is enabled.

**Comment by ice987987** [comment]
From my point of view everything looks ok. This issue can be closed if there are no more other inputs from your side. Thank you very much!

![C3A389C0-6142-48A2-86EF-A9D5C051B1BA](https://user-images.githubusercontent.com/69053781/177005587-a0a9513c-362a-4405-a237-800ca02d5647.jpeg)
![AB2F7F2A-E55A-4BD4-B96C-13D71D394B20](https://user-images.githubusercontent.com/69053781/177005588-bc457eae-5ea9-41e9-b08f-4e25beb9114b.jpeg)

**Comment by Feuer-sturm** [comment]
For me Admin 6.1.9 is fine as well.
