### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by Snatch2001** [ioBroker/ioBroker.admin#156]
At the top right is the bottle version number. Currently with me 2.0.9
![11](https://user-images.githubusercontent.com/1833577/35535386-a9108d40-0543-11e8-9089-cc20e7588132.PNG)

**Comment by AlCalzone** [comment]
Is it possible you installed the beta version and not the full one?
Currently there are 2 versions in the adapter list under the name "Admin". One stops at 3.1.0 (beta) and one is at 3.1.5 (I think), which is the "full" version.

**Comment by GermanBluefox** [comment]
It is beta. Please install admin from latest
