### ISSUE TITLE
Icon for github installation will not be visible after page reload

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1566]
**Describe the bug**  
Icon for github installation will not be visible after page reload

**To Reproduce**  
1. Install adapter over github link
2. Check on installed adapter yellow github icon -> ok
3. Do Page Reload (F5)
4. Check on installed adapter yellow github icon -> not ok -> icon is not visible any more

**Expected behavior**  
Github installation icon will stay after page reload

**Screenshots & Logfiles**  
ok
![grafik](https://user-images.githubusercontent.com/25422320/176543464-7e440719-3244-4c86-8e9f-99c6f831da90.png)
![grafik](https://user-images.githubusercontent.com/25422320/176543543-6e765e20-8550-4f2c-98e3-08a5355f957e.png)

not ok
![grafik](https://user-images.githubusercontent.com/25422320/176543679-6c6e271b-91af-4ed3-81c0-1d99dedb6414.png)
![grafik](https://user-images.githubusercontent.com/25422320/176543793-dc66e8e7-73de-4994-a438-b9385bcc1f4b.png)

**Versions:**  
 - Adapter version: 6.1.7

**Comment by GermanBluefox** [comment]
> 4\. Check on installed adapter yellow github icon -> not ok -> icon is not visible any more



> **Describe the bug** Icon for github installation will not be visible after page reload
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install adapter over github link
> 2. Check on installed adapter yellow github icon -> ok
> 3. Do Page Reload (F5)
> 4. Check on installed adapter yellow github icon -> not ok -> icon is not visible any more
> 
> **Expected behavior** Github installation icon will stay after page reload
> 
> **Screenshots & Logfiles** ok ![grafik](https://user-images.githubusercontent.com/25422320/176543464-7e440719-3244-4c86-8e9f-99c6f831da90.png) ![grafik](https://user-images.githubusercontent.com/25422320/176543543-6e765e20-8550-4f2c-98e3-08a5355f957e.png)
> 
> not ok ![grafik](https://user-images.githubusercontent.com/25422320/176543679-6c6e271b-91af-4ed3-81c0-1d99dedb6414.png) ![grafik](https://user-images.githubusercontent.com/25422320/176543793-dc66e8e7-73de-4994-a438-b9385bcc1f4b.png)
> 
> **Versions:**
> 
> * Adapter version: 6.1.7

Can you provide which URL does admin try to load?
![image](https://user-images.githubusercontent.com/4582016/176924422-537e5d98-5bc0-49a0-8de6-3ea8b561e1d6.png)
![image](https://user-images.githubusercontent.com/4582016/176924422-537e5d98-5bc0-49a0-8de6-3ea8b561e1d6.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
I am not quite sure if this is the correct  snapshot what you requested.
I opened Adapter menu, opened Dev-Tools and searched for admin.png

![grafik](https://user-images.githubusercontent.com/25422320/176935379-dfed9ddf-ff57-466f-916a-7284a34aa0e0.png)

If you need something different please give me hint how I can find the information.

**Comment by GermanBluefox** [comment]
Of course I need the URl of daikin and not of admin

**Comment by Feuer-sturm** [comment]
Admin 6.1.7
@GermanBluefox 
![grafik](https://user-images.githubusercontent.com/25422320/176953278-93a91fb7-4bff-4823-9630-74bd0634fb53.png)

**Comment by Feuer-sturm** [comment]
Admin 6.1.9

@GermanBluefox I am sorry to tell that the issue is not fixed wit 6.1.9
![Animation1001](https://user-images.githubusercontent.com/25422320/177015105-8b0f38e2-1320-4e3b-8b3c-c2f977e371cf.gif)

**Comment by GermanBluefox** [comment]
Somehow you get the constellation,  that object `system.adapter.daikin.cloud` exists, but no files uploaded to `dakiin-cloud.admin`.
What happens if you write `iob u daikin-cloud` after installtion?
