### ISSUE TITLE
Datenpunkt für verfügbare Adapter- und Controller-Updates

### ISSUE THREAD

**Issue by SebastianSchultz** [ioBroker/ioBroker.admin#157]
Ich würde gern über VIS mit evtl. vorhandene Adapter- oder Controller-Updates anzeigen lassen (Anzahl würde mir reichen).
Vielleicht wäre sowas in Zukunft ein eigener Datenpunkt wert?

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/35556771-763869b4-05a3-11e8-8e3c-cd9d69b120c2.png)

**Comment by SebastianSchultz** [comment]
Wow, didn't seen that.
But for me this datapoints wil not be updated.

I have no adapter with updates:

![1](https://user-images.githubusercontent.com/12255583/35556978-11514a56-05a4-11e8-9870-e6c3219396bd.png)

And in the objects tab:

![2](https://user-images.githubusercontent.com/12255583/35556986-198a9cf4-05a4-11e8-94d5-966e5abef5ae.png)
