### ISSUE TITLE
[Admin 6] All schedule adapters show info "running as web extension"

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1576]
**Describe the bug**  

See screenshot for details. Visiable on all instances of schedule adapters.

**Screenshots & Logfiles**  

<img width="547" alt="Screenshot 2022-07-07 at 10 51 00" src="https://user-images.githubusercontent.com/1959049/177733119-149a8398-3fa5-4e18-adca-7e076fbfed4b.png">

**Versions:**  
 - Adapter version: 6.1.11

**Comment by Steff42** [comment]
Looks the same under Adapter Version 6.1.9

**Comment by Apollon77** [comment]
And 6.1.11 which is current beta?

**Comment by Steff42** [comment]
OK, i tried 6.1.11, but it looks the same

![image](https://user-images.githubusercontent.com/35137293/178111729-dca5ae8e-6ca1-4c78-879d-57a110a11193.png)

**Comment by klein0r** [comment]
@Apollon77 This issue was created with 6.1.11 😄

**Comment by Feuer-sturm** [comment]
Admin 6.1.12

With Admin 6.1.12 no information for schedule adapter is shown if you make a mouseover:
![grafik](https://user-images.githubusercontent.com/25422320/178572714-85267761-7fe6-4e1b-871d-b74ebaf58eff.png)

@GermanBluefox Should there be any information visible?

**Comment by GermanBluefox** [comment]
> @GermanBluefox Should there be any information visible?

Actually no. I have no Idea, what I can show there....
May be so?
![image](https://user-images.githubusercontent.com/4582016/178721662-3ea81ae1-dc5d-45e6-9d2a-3aa9add78d35.png)

**Comment by Feuer-sturm** [comment]
ok with Admin 6.2.0
