### ISSUE TITLE
[Admin 6] Invalid version of "admin". Installed "5.4.9", required ">=6.1.6"

### ISSUE THREAD

**Issue by patrickbs96** [ioBroker/ioBroker.admin#1577]
**Describe the bug**  
The current version of telegram isn't working anymore due to the check of the admin version number. I keep getting the error message above when trying to start the adapter even though I'm using version 6.1.11... 
I tried a fresh install in the hopes it might work then but unfortunately not...

**Versions:**  
 - Adapter version: <6.1.11>
 - JS-Controller version: <4.0.23>
 - Node version: <16.14.0>
 - Operating system: <linux>

**Comment by Feuer-sturm** [comment]
@Apollon77 is this a admin issue or telegram adapter?

**Comment by klein0r** [comment]
I think it is an admin issue, since the globalDependency in the telegram adapter is defined correctly:

https://github.com/iobroker-community-adapters/ioBroker.telegram/blob/e97865ea1220e9c2e3f81376a2d30ed44d6e008e/io-package.json#L150-L154

**Comment by klein0r** [comment]
@patrickbs96 Is it a multihost installation? Please ensure that all hosts satisfy the dependency requirement. If the admin is installed on a slave with a version older than 6.1.6 (in your case 5.4.9) the dependency is not fulfilled.

**Comment by patrickbs96** [comment]
@klein0r Yes it's a multihost installation. All adapters, admin and js-controller are up-to-date with latest repository.

Could there maybe be a location in my system where the admin version wasn't updated and that's the version which is being used for the dependency check?

**Comment by klein0r** [comment]
@patrickbs96 Double check if the admin adapter is not installed on your slave(s) or up to date

**Comment by Feuer-sturm** [comment]
@patrickbs96 I am trying to reproduce your problem on my multihost test system. Which telegram version is currently installed on your system and to which version do you want to upgrade?

**Comment by patrickbs96** [comment]
@Feuer-sturm I'm currently using *1.13.0* and everything works fine. After upgrading to version *1.14.1* the adapter won't start anymore due to the error message...

The telegram adapter is installed on the slave raspberrypi2

**Comment by Apollon77** [comment]
@patrickbs96 please try "iob upload admin" ... does it fix it?

**Comment by patrickbs96** [comment]
@Apollon77 I think there is something wrong with my slave. I just did the upload and when I now try to upgrade through the console I get the following error msg
```
pi@raspberrypi2:~ $ iob upgrade
Cannot check dependencies: Invalid version of "admin". Installed "5.4.9", required ">=6.1.6
```

I tried upgrading telegram through admin and then it allowed the upgrade but then fails while starting the adapter
```
2022-07-17 23:00:15.235  - error: host.raspberrypi2 startInstance system.adapter.telegram.0 Adapter dependency not fulfilled on any host: required adapter "admin" has wrong version. Installed "5.4.9", required ">=6.1.6"!
```

**Comment by Apollon77** [comment]
Make sure that all admin versions installed on all slaves were updated to 6.1.6+ Then it shopuld work

**Comment by patrickbs96** [comment]
@Apollon77 That was it 🤦🏻‍♂️ I had another slave connected which I hadn't been using in a while and there the version was still 5.4.9... Thanks for your help!!!
