### ISSUE TITLE
Make adapter changelog accessable in menu for multiple adapter update

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1579]
## Feature request

It would be great to have a button or a link to show the changelog  as a pop-up of a single adapter if you are in the menu for updating multiple adapters

Currently you need to quit this menu and check the different change logs before you can start the multiple adapter update

![grafik](https://user-images.githubusercontent.com/25422320/177850043-8a1fb331-4c0d-4dd4-aff2-4e0d1981442e.png)

**Comment by GermanBluefox** [comment]
IMplemented in 6.1.12
![image](https://user-images.githubusercontent.com/4582016/178526557-2a0f7631-6a50-4cb1-85f8-0f596b6265dc.png)

**Comment by Feuer-sturm** [comment]
ok with admin 6.1.12
