### ISSUE TITLE
globalData funktioniert in json config nicht.

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1580]
in einem Table möchte ich via globalData daten per message senden.
leider funktioniert es so nicht:
`"jsonData": "{\"adress\":\"${globalData.adress}\"}",`

hier wird globalData direkt als string empfangen

**Comment by BenAhrdt** [comment]
aktuell wird es gar nicht benutzt, da es ja nicht funktioniert.
Würde es gerne hier benutzen:
JsonConfig zeile 132:
[https://github.com/BenAhrdt/ioBroker.janitza-gridvis/blob/main/admin/jsonConfig.json](https://github.com/BenAhrdt/ioBroker.janitza-gridvis/blob/main/admin/jsonConfig.json)

**Comment by GermanBluefox** [comment]
Please try 6.1.12

**Comment by BenAhrdt** [comment]
Sieht aus, als würde es funktionieren.
Allerdings geht das selectsendTo nicht mehr.
Mache dazu ein issue auf.
