### ISSUE TITLE
Cannot update Admin update anymore

### ISSUE THREAD

**Issue by kuckuckmann** [ioBroker/ioBroker.admin#1583]
Hi,

I cannot update Admin adapter anmyore.
I am curretly having version 6.1.4. When I am trying over the GUI, the loading wheel runs endless without any change.

When I try iobroker upgrade admin command, I am always getting an error 217:

![grafik](https://user-images.githubusercontent.com/99131208/178062375-bf7b4782-19f0-400f-b90a-596ac97d1765.png)

With npm i iobroker.admin@6.1.11 --production it look slike that:

![grafik](https://user-images.githubusercontent.com/99131208/178062579-b622f2a5-14c3-421d-8cbb-994d498c28d4.png)

But no version change at all.

I need help on that please.

Thx ahead

**Comment by Apollon77** [comment]
Hi.

1.) On such errors start the "ipob upgrade "command with --debug to see the npm errors. pot run "iob fix"
2.) When upgrading using npm directly you need also to run "iob upload admin" afterwards (and I hope the command was executed in the right directly /opt/iobroker

**Comment by kuckuckmann** [comment]
Not really better:

![grafik](https://user-images.githubusercontent.com/99131208/178068107-16488064-0e19-4dab-8e0f-0de07b465b10.png)

**Comment by Apollon77** [comment]
Yes this seems to be an npm isssue ... check that "not empty I can not move a -> b" ... check if "b" exists and if yes delete it. try again

**Comment by kuckuckmann** [comment]
That was a success :)
Many thx for that hint.
