### ISSUE TITLE
[Admin 6] Downloading file from files tab adds ".js" to filename

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1584]
**Describe the bug**  

When downloading a file via the "files" tab in admin, ``.js`` is added to the filename. Example:

<img width="763" alt="Screenshot 2022-07-11 at 08 25 42" src="https://user-images.githubusercontent.com/1959049/178201732-e657b841-4834-460d-96a8-97e959ef52af.png">

Filename is ``yr.0.forecastHourly.0h.air_temperature.csv.js`` after download.

*Tested with Safari Version 15.5 (17613.2.7.1.8)*

**Versions:**  
 - Adapter version: 6.1.11

**Comment by GermanBluefox** [comment]
It is error in mui library. Now it will be sumulated

**Comment by klein0r** [comment]
Fixed, tested with 6.2.3
