### ISSUE TITLE
v6.1.11 Pausieren vom Log funktioniert nicht 

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#1585]
Wenn man die Pause-Taste drückt, läuft das Log trotzdem weiter.
Es wird immer 0 angezeigt.
![image](https://user-images.githubusercontent.com/84818934/178291926-5a6f832d-474b-434b-b583-a1815b584c98.png)

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren:
![admin](https://user-images.githubusercontent.com/4582016/178535515-8af451bf-634a-43c1-aa77-e242222a4eb5.gif)

**Comment by mcuiobroker** [comment]
Nach Neustart funktioniert es bei mir auch. Keine Ahnung woran es gelegen hat. Danke, Sorry für die Störung.
