### ISSUE TITLE
SelectSendTo nimmt keine Auswahlmehr an.

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1588]
die SelectSendTo nehmen keine Auswahl der Werte mehr an.
Wählt man einen Wert aus, so wird der nicht übernommen, sondern das Feld bleibt leer.

![instances-dev-janitza-gridvis-nb287-Google-Chrome-2022-07-14-12-42-51](https://user-images.githubusercontent.com/92173565/178965398-695b637e-f83b-4ff9-9e6d-eaee2ffd6ffc.gif)

@GermanBluefox Kann es sein, dass hier durch die 6.2.x vom admin dies verursacht wird?
Denn < 6.2.x funktioniert es noch.

**Comment by klein0r** [comment]
Ich habe das gleiche Problem mit Tabellen. Ich kann keinen einzigen Wert mehr ändern. Egal ob Text, Select, Checkbox, Color, ...

Muss ein Problem mit dem Tabellen-Widget sein. Siehe Issue #1589

**Comment by BenAhrdt** [comment]
@GermanBluefox Ich habe die 6.2.1 installiert.
Leider funktioniert es nicht => Keine Änderung.

**Comment by klein0r** [comment]
@BenAhrdt Mit 6.2.1 bestand das Problem ja auch noch. Bitte 6.2.2 testen

**Comment by BenAhrdt** [comment]
@klein0r Oh, sorry.
Mir wurde in der Beta nur die 6.2.1 angeboten, hatte gar nicht mehr drauf geachtet.

**Comment by klein0r** [comment]
> Sollte der noch erscheinen, oder muss der via github installiert werden?

Wird ganz normal über das Update verfügbar sein, wenn die Repositories neu gebaut werden. Über GitHub würde ich nie installieren (weil das dann nicht unbedingt dem 6.2.2 Stand entspricht, sondern dem letzten commit im master branch).

**Comment by Feuer-sturm** [comment]
@klein0r @BenAhrdt Can you please check with current admin version if this issue is fixed?

**Comment by BenAhrdt** [comment]
I can Check ist First After 15.08. (Holiday)

**Comment by Feuer-sturm** [comment]
@BenAhrdt May I ask, if you had already some time to check this issue?

**Comment by BenAhrdt** [comment]
Ist Looks like ist Is fixed
