### ISSUE TITLE
В версии admin 3.1.5 невозможно изменить некоторые опции..

### ISSUE THREAD

**Issue by Lstt2005** [ioBroker/ioBroker.admin#159]
![30-01-2018 110205](https://user-images.githubusercontent.com/6728198/35554447-c0ef8c72-05ac-11e8-9406-6a3fa3fd647b.jpg)
В свойствах объекта применительно к драйверу  mqtt-client невозможно изменить многие опции.....

**Comment by GermanBluefox** [comment]
mqtt-client must be updated. 
https://github.com/Pmant/ioBroker.mqtt-client/issues/5
