### ISSUE TITLE
[Admin 6] Strange redirect when logging in with incorrect credentials

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1590]
**Describe the bug**  

- Started @ ``/index.html?login&href=#tab-intro``
- Tried to log in with incorrect username / password
- Landed @ ``/index.html?login/index.html?login&error&href=#tab-intro``

Just seeing the loading spinner forver

**Versions:**  
 - Adapter version: 6.2.1

**Comment by GermanBluefox** [comment]
Fixed to `/index.html?login&error&href=#tab-instances`

**Comment by klein0r** [comment]
Tested with 6.2.3

Still redirected to ``/index.html?login/index.html?login&error&href=#tab-intro``

**Comment by Feuer-sturm** [comment]
@klein0r Can you please check with current admin version if this issue is fixed?

**Comment by klein0r** [comment]
Fixed (tested with v6.2.13)
