### ISSUE TITLE
Menu objects coloum "Einstellungen" is not visible in auto mode

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1591]
**Describe the bug**  
Coloum "Einstellungen" is not visible if "auto" mode is activated in setting "Spalten Konfigurieren"

**To Reproduce**  
1. Go to menu objects
2. Click on "Spalten Konfigurieren"
3. Activate option "auto" (all checkboxes are activated and greyed out)
4. Coloum "Einstellungen" is not visible 

**Expected behavior**  
Coloum "Einstellungen" is visible if option "Auto" is switched on. In Admin 6.1.11 coloum "Einstellungen" was visbile in "auto mode"

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/179366683-88c8cadf-5e0a-43e2-8d88-1625286eff72.png)

![grafik](https://user-images.githubusercontent.com/25422320/179366614-c7b523c9-eed8-4786-8b2e-a7f69dbd3f91.png)

**Versions:**  
 - Adapter version: Admin 6.2.1

**Comment by GermanBluefox** [comment]
I think I will deactivate this mode completely, as now users can adjust 2 most important columns.

**Comment by Feuer-sturm** [comment]
@GermanBluefox 

Admin 6.2.7

- Titel of  new popup is missing to configure coloums :x:
![grafik](https://user-images.githubusercontent.com/25422320/181597408-13bf8dc9-b288-4b06-8dde-56de6f28b364.png)

- If the side menu is enlarged the coloum "Einstellungen" is not vissible :x:
![grafik](https://user-images.githubusercontent.com/25422320/181597807-0bc827ab-ec8b-49c4-b1af-2fdf0a6cac40.png)

- You need to collapse the menu than the coloum is visible :heavy_check_mark:
![grafik](https://user-images.githubusercontent.com/25422320/181597877-4c171737-17ce-492f-8c8d-22e95f65f016.png)

**Comment by Feuer-sturm** [comment]
Admin 6.2.13

Titel of new popup is missing to configure coloums -> ok
If the side menu is enlarged the coloum "Einstellungen" is not vissible -> ok

**Comment by cavernerg** [comment]
> I think I will deactivate this mode completely, as now users can adjust 2 most important columns.

where is this feature?

**Comment by Apollon77** [comment]
What do you mean? Admin 6.2 has it
