### ISSUE TITLE
[Admin 6] devices und files Tab ohne Funktion

### ISSUE THREAD

**Issue by tobasium** [ioBroker/ioBroker.admin#1592]
Hallo Zusammen,

ich hab hier irgendwie das Problem das der Devices Tab bei mir nur die Sanduhr anzeigt. Habe hierzu im Forum nichts gefunden. Hat hier noch jemand das Problem? Bin och auf ein [github Fehler](https://github.com/ioBroker/ioBroker.devices/issues/115) der ähnlich ist aufmerksam geworden aber auch ohne Info.

Ebenfalls ist mir ist aufgefallen der Dateien Tab lädt auch nicht

Adapter version: 1.0.12
JS-Controller version: 4.0.23
Node version: v16.16.0
Operating system: Docker Buanet V7 / synology

![image](https://user-images.githubusercontent.com/23247891/179396569-684a2651-975b-4f4b-a6ee-dd547b9f5de8.png)

**Comment by GermanBluefox** [comment]
Cannot reproduce: 
![image](https://user-images.githubusercontent.com/4582016/179450966-e5397f73-ada8-4e54-aab7-3c629d8ab88e.png)

**Comment by tobasium** [comment]
Ich war mal so frei und habe beide Instanzen auf debug gestellt. Aber aus dem Log werde ich nicht schlau.
Glaub mein ganzer Iobroker gibt den Geist auf.

Neustes entdecktes Symptom: Gehe ich auf Objekte lädt es sich tot und dann erscheint Fehler: Cannot get instances: timeout

[iobroker log devices.txt](https://github.com/ioBroker/ioBroker.admin/files/9135605/iobroker.log.devices.txt)

**Comment by klein0r** [comment]
Ein ähnliches Verhalten hatte ich auch mal, als ich ein Objekt mit "falschen" Attributen (Tippfehler) angelegt hatte.

Ich glaube nicht, dass Dein ioBroker den Geist aufgibt. Ich denke es ist nur eine Kleinigkeit in der Objekt-Datenbank falsch, welche zu den Problemen führt.

Hast Du denn das Backup auf dem gleichen Host wiederhergestellt oder kommt das von einem anderen System (mit einem anderen Hostname)?

**Comment by tobasium** [comment]
Iobroker läuft im Docker. Probleme gab es schon davor, ich weiß nicht genau seid wann exakt Tage oder 2 Wochen vielleicht. Daher hab ich den Docker komplett neu erstellt und iobroker aus dem backup wieder hergestellt. Keine neuen Adapter nur Updates immer brav durchgeführt.

**Comment by klein0r** [comment]
Das Problem ist doch, dass Du die Objekt-Datenbank 1:1 wiederherstellst mit dem Backup Restore. Das heißt, dass auch ein kaputtes Objekt wieder hergestellt würde und das gleiche Problem verursachen würde (falls das das Problem ist).

**Comment by tobasium** [comment]
Da stellt sich die Frage wie würde ich da kaputte Objekt finden? Ich wöllte ungern bei mir komplett bei 0 anfangen. Hast du hier eine Idee? Hatte eigentlich auch keine neuen Objekte angelegt. Daher wüsste ich hier nicht einmal wo genau anfangen.

**Comment by klein0r** [comment]
Ich würde vorher nochmal ein ``iobroker upload all`` und ``iobroker host this`` im Container ausführen, bevor man da ewig sucht und es am Ende an etwas anderem lag.

**Comment by tobasium** [comment]
Also ich hab jetzt diese Meldung bekommen: 
A host with the name "iobroker" already exists!

Rest lief alles durch

**Comment by klein0r** [comment]
Und? Nach wie vor das gleiche Verhalten im Admin?

**Comment by tobasium** [comment]
Also es ist noch da:
Ich hab mal 2 Fotos hochgeladen wie das ganze aussieht:
![image](https://user-images.githubusercontent.com/23247891/179849929-cd754087-d612-4a0e-b65e-db2219879e4a.png)
![image](https://user-images.githubusercontent.com/23247891/179849948-48b242ae-cef9-4f7e-a34a-02d590c1ac92.png)

**Comment by Feuer-sturm** [comment]
@tobasium Welches genaue Fehlverhalten tritt bei dir noch auf? Ich kann es aus den Screenshots nicht ableiten?

**Comment by tobasium** [comment]
Hi,

der Device/Geräte Tab hat nicht mehr geladen. Ebenfalls der Objekte Tab hat sich regelmässig verabschiedet mit einer Sanduhr. Auch ein Backup einspielen brachte keinen Erfolg. Ich habe mir inzwischen iobroker neu aufgesetzt. War zwar etwas Arbeit aber jetzt geht alles. Irgendwann muss es das verspuhlt haben. Ich habe keine Ahnung wann.

**Comment by Feuer-sturm** [comment]
@tobasium Dann schließe ich das Ticket hier. Wenn das Problem doch noch einmal wieder hochkommen sollte erstell bitte ein neues issue.
