### ISSUE TITLE
[Admin 6] Fehlermeldung / Warnmeldung im Log

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.admin#1593]
Hi,

ich habe die folgenden Meldungen in Log,

admin.0 2022-07-19 15:52:45.339	warn	Cannot check node.js/npm version
admin.0 2022-07-19 15:52:45.325	warn	Cannot get current npm version: Cannot find npm version

Admin V6.2.3

Vielen Dank

**Comment by Apollon77** [comment]
Please create a forum tgread ... how nodejs and npm are installed (if you use nvm or such tools please skip that and install it globally). Else forum could help to verufy your installation

**Comment by MMeinhardt1** [comment]
Hi @Apollon77,
i have opened a thread last week but no one was able to solve the problem.
It is possible that this issue is from the admin adapter? Do you have any ideas?
All the updates of NodeJS i have installed with the guide in the forum (https://forum.iobroker.net/topic/44566/how-to-node-js-iobroker-richtig-updaten-2021-22-edition).

Many thanks
