### ISSUE TITLE
Admin 6.2.3 breaks Yahka Admin

### ISSUE THREAD

**Issue by krobipd** [ioBroker/ioBroker.admin#1594]
hey

die aktuelle admin 6.2.3 bricht die Adminoberfläche von Yahka.
wenn ich auf ein Gerät - in der Yahka Admin - klicke kommt rechts keine Info mehr.

mit 6.2.2 funktioniert alles wunderbar.

Node.js: v16.16.0
NPM: 8.14.0

<img width="1440" alt="Bildschirmfoto 2022-07-19 um 22 42 26" src="https://user-images.githubusercontent.com/27220902/179845298-a7a32719-cf68-46de-be2d-a8749a5d0853.png">
<img width="1440" alt="Bildschirmfoto 2022-07-19 um 22 45 54" src="https://user-images.githubusercontent.com/27220902/179845302-dddd4302-7ad2-47e9-9239-96977fcc0a3d.png">

**Comment by Apollon77** [comment]
Zeigt die JavaScipt Browser Konsole irgendeinen Fehler?

**Comment by krobipd** [comment]
hab jetzt im safari und firefox rumprobiert und geschaut aber in den Entwickler-werkzeugen keine Auffälligkeiten gesehen, außer das wohl manche Sachen nicht mehr so mega top sind beim yahka - aber diese Meldungen kommen bei beiden admin Versionen.

aber wenn du mir sagen kannst auf was ich achten soll oder so schau ich gerne nochmal. mal gucken wie oft man in welcher zeit die admin Version wechseln kann :-P

**Comment by krobipd** [comment]
fixed with 6.2.4
https://github.com/ioBroker/ioBroker.admin/releases/tag/v6.2.4
