### ISSUE TITLE
[Admin 6] JSON-Editor for json-States has strange Design

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1595]
**Describe the bug**  

When editing a state with role ``json``, the admin provides an editor window. At the moment it wastes some space.

**Screenshots & Logfiles**  

<img width="935" alt="Screenshot 2022-07-20 at 13 23 07" src="https://user-images.githubusercontent.com/1959049/179972535-1ec58160-43a2-4afb-833e-5231a2cd5b20.png">

**Versions:**  
 - Adapter version: 6.2.3

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/180010033-d0cb9d4c-76ed-4f24-81f5-c030be36f85b.png)

**Comment by klein0r** [comment]
Looks good in 6.2.4 ✅
