### ISSUE TITLE
Umleitung auf https (wenn benötigt) nach Setup-Assistent 

### ISSUE THREAD

**Issue by ipod86** [ioBroker/ioBroker.admin#1597]
Hallo,

habe heute nochmal meinen iobroker neu aufgesetzt.
Im Setup-Assistent habe ich SSL aktiviert.

Wenn man nach dem Assistent auf den Admin weitergeleitet wird, kommt man auf http anstatt https.

Ich kann mir vorstellen, dass da manche User die noch keine Berührungspunkte mit der Angelegenheit hatten nicht wissen wie sie nun aif den Admin kommen.

Praktisch wäre eine korrekte Weiterleitung entsprechend der Ssl-Einstellungen aus dem Assistenten.

**Comment by ipod86** [comment]
Evtl wäre im Admin oder am Ende des Assistent ein kleine Meldung mit der URL praktisch.
Ggf mit einem Button ein Lesezeichen anzulegen.

Sonst bekommt man ggf nicht mit, dass sich die URL geändert hat zu der, die man am Ende vom Setupskript gesehen hat.

**Comment by GermanBluefox** [comment]
Eigentlich es wird redirected: https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/dialogs/WizardDialog.jsx#L269
Und ich habe getestet, es geht. Was ich vermuten kann, dass es vielleicht 1 Sek timeout zu gering ist und admin startet in dieser Zeit noch nicht

**Comment by GermanBluefox** [comment]
Wenn du `system.config` Object `common.licenseConfirmed` auf `false` änderst, dann wird nach F5 dir wieder Wizard angeboten. Aber stelle erst admin auf nicht HTTPS um.
![image](https://user-images.githubusercontent.com/4582016/181297494-eaebe867-62c7-481a-abc0-92a61f856f36.png)

**Comment by ipod86** [comment]
Habs grad getestet.
Bin tatsächlich auf Ssl gekommen.

Der Admin war aber scheinbar noch nicht bereit. 
Nach einem reload ist er dann gekommen. 

![Screenshot_20220727-183335_Chrome](https://user-images.githubusercontent.com/66136363/181302766-2bc80b0f-1914-49e6-8263-ba8e149c8e4f.jpg)

**Comment by GermanBluefox** [comment]
> Habs grad getestet. Bin tatsächlich auf Ssl gekommen.
> 
> Der Admin war aber scheinbar noch nicht bereit. Nach einem reload ist er dann gekommen.
> 
> ![Screenshot_20220727-183335_Chrome](https://user-images.githubusercontent.com/66136363/181302766-2bc80b0f-1914-49e6-8263-ba8e149c8e4f.jpg)

Wie viel Sekunden dauert Restart von Admin auf Raspi4?
Dann verlängere ich die Wartezeit

**Comment by ipod86** [comment]
Kann ich das irgendwie genau messen?
Wenn ich unter Instanzen einfach auf Neustart drücke, dauert es ca 27sek bis der Ladekreis wieder verschwindet.

Im Log geht alles recht schnell:


admin
v5.3.8

admin.0

admin.0
2022-07-28 07:27:26.129	info	Repository received successfully.

admin.0
2022-07-28 07:27:14.148	info	Use link "https://localhost:8081" to configure.

admin.0
2022-07-28 07:27:14.148	info	https server listening on port 8081

admin.0
2022-07-28 07:27:12.664	info	received all objects

admin.0
2022-07-28 07:27:09.283	info	Request actual repository...

admin.0
2022-07-28 07:27:08.227	info	requesting all objects

admin.0
2022-07-28 07:27:08.225	info	requesting all states

admin.0
2022-07-28 07:27:08.097	info	starting. Version 5.3.8 in /opt/iobroker/node_modules/iobroker.admin, node: v16.16.0, js-controller: 4.0.23

admin.0
2022-07-28 07:27:00.857	info	Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason

admin.0
2022-07-28 07:27:00.855	info	terminating

admin.0
2022-07-28 07:27:00.854	info	terminating https server on port 8081

admin.0
2022-07-28 07:27:00.832	info	Got terminate signal TERMINATE_YOURSELF

**Comment by GermanBluefox** [comment]
Das reicht schon. 8 Sekunden. Danke

**Comment by GermanBluefox** [comment]
> Evtl wäre im Admin oder am Ende des Assistent ein kleine Meldung mit der URL praktisch. Ggf mit einem Button ein Lesezeichen anzulegen.
> 
> Sonst bekommt man ggf nicht mit, dass sich die URL geändert hat zu der, die man am Ende vom Setupskript gesehen hat.

Chrome erlaubt nicht die Bookmarks von JS zu setzten

**Comment by Feuer-sturm** [comment]
@ipod86 Can you please check with current admin version if this issue is fixed?

**Comment by ipod86** [comment]
In welcher Admin Version ist die Änderung?
Bin stable auf der 5.3.8.

Auf die 6er würde ich ungern schon gehen.

**Comment by Feuer-sturm** [comment]
@ipod86 Die Änderung kam mit der Admin Version 6.2.7

**Comment by ipod86** [comment]
Habe nur einen Produktiven iobroker.
Da würde ich gerne im stable bleiben.....

Versuche es am Wochenende mit meinem Backupsystem (2te ssd mit selber Installation, falls sich was zerschießt).

**Comment by Feuer-sturm** [comment]
@ipod86 Hattest du schon die Gelegenheit das issue nachzutesten?

**Comment by ipod86** [comment]
Bin noch am Admin 5.
Habe nur mein Produktivsystem.
Da würde ich ungerne auf den 6er gehen.

Kann ich die Änderung irgendwie im 5er Admin testen? 

Hab leider auch nur einen Rasparry hier.

**Comment by Feuer-sturm** [comment]
@ipod86 

> Kann ich die Änderung irgendwie im 5er Admin testen?

@ipod86 ich denke nicht. 

Ich kann in den nächsten Tagen einmal  versuchen,  das issue auf meinem Testsystem zu reproduzieren

**Comment by Feuer-sturm** [comment]
From my point of view redirection to https is working

@ipod86 If you agree we can close this issue.


Steps to reproduce:
- Fresh installation of iobroker with Admin 5.3.8
- Update Admin to latest beta version 6.2.14
- Change common.licenseConfirmed to false to enter wizzard once again
- Select SSL
- Finish setup wizzard

Check with Firefox Browser -> ok
Popup is shown for admin reload and after timeout admin will be accessed via https

![grafik](https://user-images.githubusercontent.com/25422320/185242187-9a6085cf-da35-4103-9262-a728250f14ea.png)

![grafik](https://user-images.githubusercontent.com/25422320/185242274-57d2d712-9497-44b2-bbcc-e300658da346.png)
