### ISSUE TITLE
decryption of encrypted fields in admin/adapter config fails

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#1598]
**Describe the bug**  

As figured out here: 
* https://github.com/Grizzelbee/ioBroker.mielecloudservice/issues/271

* when I enter something to an encrypted field NEWLY - it gets properly decrypted automatically in the backend
* when I open the config dialog again the encrypted fields aren't restored in clear text but show the string "[object promise]". When I change any field but an encrypted and save the config - the original content of the encrypted fields gets lost and the string "[object promise]" will be encrypted - and decrypted in the backend.

**To Reproduce**  
1. Go to any adapter config with an encrypted field (e.g. wireguard adapter - clear text field: Benutzer/User)
2. enter a new value to the encrypted field
3. save
4. reload the page to refresh all values (or exit and enter again)
5. edit any value but the encrypted field
6. save again
7. see that the encrypted field now has the value "[object promise]" - no matter what it has had before

**Expected behavior**  
Restore the clear text password on config page

**Screenshots & Logfiles**  
see the linked issue above

**Versions:**  
 - Adapter version: Admin 6.2.4 (at least affected since version 6.1.9)
 - JS-Controller version: 4.0.23
 - Node version: 14.17.0
 - Operating system: windows

**Additional context**  

related issues:
* https://github.com/ioBroker/ioBroker.admin/issues/1596
* https://github.com/Grizzelbee/ioBroker.wireguard/issues/36

**Comment by Feuer-sturm** [comment]
@Grizzelbee Can you please check with current admin version if this issue is fixed?

**Comment by Grizzelbee** [comment]
@Feuer-sturm 
Will do - as soon as I return from vacation.

**Comment by Grizzelbee** [comment]
Retested the issue and it's working again like in the older versions. ==> Fixed!
