### ISSUE TITLE
GUI Popup HttpError: runtime error @4:12

### ISSUE THREAD

**Issue by Rushmed** [ioBroker/ioBroker.admin#1601]
Hi.

When mouse hoovering over a DPs value which is logged by InfluxDB an set to boolean I get this popup:
![image](https://user-images.githubusercontent.com/59259796/180419078-5a252406-d0f9-427d-9cd0-cea3ea7ebf3f.png)
I am not able to change the value of the DP. As I close the popup an go to value it pops up again.

Also reported this behavoir [@influx adapter Git](https://github.com/ioBroker/ioBroker.influxdb/issues/281#issuecomment-1192358790)

**Comment by Apollon77** [comment]
@GermanBluefox We should ignore error messages coming back from the histpory adapter when it is about the "small chart in the object tab in admin"

**Comment by Feuer-sturm** [comment]
@Rushmed Can you please check with current admin version if this issue is fixed?

**Comment by Rushmed** [comment]
@Feuer-sturm Succssfully installed and tested  6.2.13. Thanks Sir!
