### ISSUE TITLE
[ADMIN 5 - jsonConfig] Config HELP icon leads to iobroker.net page with incorrect original link

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1602]
**Describe the bug**  
When clicking on the round HELP icon at the instance configuration page of an installation with german default the README.md page at iobroker.net is openend. (url: https://www.iobroker.net/#de/adapters/adapterref/iobroker.snmp/README.md)

This page has a banner telling that the text has been translated from english. Hoovering over the banner displays the hint "Zum Original gehen". But when clicking on this banner, an empty page is displayed. (url: https://www.iobroker.net/#en/undefined)

**To Reproduce**  
Klick at the help of an jsonConfig based adapter (i.e. snmp V2.0.0) and try to get the english original

**Expected behavior**  
I would expect to get the english original.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/180483277-634e59c6-dab3-47a8-b888-cccdaeed1da2.png)
![image](https://user-images.githubusercontent.com/28575778/180483343-f5b4d62e-cc16-4aa0-8667-fc292653e3f3.png)

**Versions:**  
 - snmp Adapter version: 2.0.0
 - Admin Adapter version: 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: v14.19.1
 - Operating system: Windows

**Comment by klein0r** [comment]
This is an issue for the https://github.com/ioBroker/ioBroker.docs repo

**Comment by foxriver76** [comment]
> (url: https://www.iobroker.net/#de/adapters/adapterref/iobroker.snmp/README.md)

if your ioBroker is configured for `de` this is as designed

And the issue to not get the english original if for docs repository.

**Comment by mcm1957** [comment]
I donit thinkbthat an incorrect link can be solved at doc.

See problem description:
This page has a banner telling that the text has been translated from english. Hoovering over the banner displays the hint "Zum Original gehen". But when clicking on this banner, an empty page is displayed. (url: https://www.iobroker.net/#en/undefined)

I do not have access to admin now but please check if clicking at banner works with current admin. I  can do later or next week if prefeted

**Comment by foxriver76** [comment]
It is for sure an issue in the docs from my pov. At least this is definetely not an admin issue, you can simply navigate independently of admin to https://www.iobroker.net/#de/adapters/adapterref/iobroker.snmp/README.md click on the banner and get the issue.

**Comment by mcm1957** [comment]
Ok I undrstand.
Thought admin provided the feamework including the tooltip. I was wrong.
