### ISSUE TITLE
jsonConfig: Editing of a text field has a bug

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.admin#1603]
**Describe the bug**  
if a text field is already filled an you klick at any position and want to insert text. the cursor jumps to the end of the text after one character.

**To Reproduce**  
for Example rssfeed Adapter 2.0.1 in the table field URL
or in the Admin-Dialog of the Admin Adapter in the Loading Background Tab in the Background color field (you have to dismiss the color select dialog)
and Admin-Adapter 6.2.3

**Expected behavior**  
not jumping to the end

**Screenshots & Logfiles**  
-

**Versions:**  
- Admin-Adapter 6.2.3
- js-controller 4.0.23
- node 18.6
- os windows 10
 
**Additional context**  
-

**Comment by Feuer-sturm** [comment]
@oweitman Can you please check with current admin version if this issue is fixed?

**Comment by oweitman** [comment]
tested with 6.2.13.
bug is fixed
