### ISSUE TITLE
When I log in to ioBroker i see an error "Error: "error""

### ISSUE THREAD

**Issue by Kopierwichtel** [ioBroker/ioBroker.admin#1606]
**Describe the bug**  
When I log in to ioBroker  i see an error "Error: "error"" in the logs reported by admin.

**To Reproduce**  
1. I created a new user Martin_A as part of the administrator group
2. Login to iobroker with the new user
3. Check the logs

**Expected behavior**  
no error is reported

**Screenshots & Logfiles**  
log with debug enabled, error at line 654:
[admin error.txt](https://github.com/ioBroker/ioBroker.admin/files/9175389/admin.error.txt)

**Versions:**  
 - Adapter version: 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: v14.19.0
 - Operating system: docker buanet

**Additional context**  
...

**Comment by Feuer-sturm** [comment]
@Kopierwichtel this error message is fixed with Admin 6


```
2022-07-24 10:13:19.139 - info: admin.0 (138) failed connection to socket.io from ::ffff:192.168.0.98:
2022-07-24 10:13:19.149 - error: admin.0 (138) Error: "error"
2022-07-24 10:13:45.907 - debug: admin.0 (138) successful connection to socket.io from ::ffff:192.168.0.98
```
