### ISSUE TITLE
jsonConfig: external loadable code

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.admin#1607]
https://github.com/ioBroker/ioBroker.admin/blob/bbcc2fb28ad21f2550a0bb558005d6c2a631aebc/src-rx/src/components/JsonConfigComponent/ConfigCustom.jsx#L97

do we really want this.
isnt this a security flaw?

all components that should be used in the admin dialog should be allready installed in the adapter

**Comment by GermanBluefox** [comment]
Interesting finding. I think, yes, it must be removed

**Comment by Feuer-sturm** [comment]
@oweitman  Can you please check with current admin version if this issue is fixed?
