### ISSUE TITLE
jsonConfig: Custom component - already finished example?

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.admin#1608]
ist the following file an already finished example for a custom component in the admin config dialog?
or is this an early fragment?
Is maybe there an example that it explains how to setup a custom react component?

https://github.com/ioBroker/ioBroker.admin/blob/bbcc2fb28ad21f2550a0bb558005d6c2a631aebc/admin/custom/customComponents.js#L1

**Comment by GermanBluefox** [comment]
It is finished component and it is used in production. You can find more examples here: https://github.com/ioBroker/ioBroker.admin-component-template
And here: https://github.com/iobroker-community-adapters/ioBroker.telegram/tree/master/src-admin
