### ISSUE TITLE
[jsonConfig] Add/change location  of "+" button for tables

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1611]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Currently the PLUS Button to add a new entry (new row) to a jsonConfig based table is located at top of the table. If the table is bigger it's necessary to scroll the table several times up and down to switch between pressing the plus button at the top of the table and entering the data at the lower end of the table.

Please consider moving the plus button to the end of the table or to add a second plus button at the lower end of the table to avoid scrolling up and down when adding several rows,

**Describe alternatives you've considered**
As an alternative it would be possible to fix the heading of the table and to scroll the table data only. This would have the benefit that the table headers would stay visible when scrolling but the effort to implemnt would be bigger. I'm not sure whether this would rectify the bigger cosing effort.

**Comment by GermanBluefox** [comment]
Added:
![image](https://user-images.githubusercontent.com/4582016/181294403-f47dc516-1aba-4e0b-8b95-62815e679095.png)

There is new parameter for table: showSecondAddAt: Number of lines from which the second add button at the bottom of the table will be shown. Default 5

**Comment by Feuer-sturm** [comment]
@mcm1957 Can you please check with current admin version if this issue is fixed?

**Comment by mcm1957** [comment]
sorry for the late reply. I did not receive a notifictio n (or missed it).

verified to work with admin v6.2.13 as expected
