### ISSUE TITLE
Display of changelog when using "install specific version" does not honor linebreaks

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1612]
**Describe the bug**  
When installing a newer version via Admin the releasenotes are displayed as expected:

![Releasenotes-1](https://user-images.githubusercontent.com/28575778/181281275-e6118c43-b8e6-4572-b03f-298f5ff6bbea.jpg)

But when I select the option "install special version" (Export mode on) the Releasenotes are all written into one long line - all linebreaks and formatting is lost making the text hard to read:

![Releasenotes-2](https://user-images.githubusercontent.com/28575778/181284059-62820e1b-b1e9-4761-b65a-f6f0b7f1ea05.jpg)

**Expected behavior**  
I would expect that at keast line breaks are honored. Colouring or bold attributes are nit required, but compressing the text into a single line makes it hard to read

**Versions:**  
 - Adapter version: Admin 5.3.8 / 6.2.4 
 - Operating system: windows 10

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/181297084-e33f48a8-5534-4142-8e81-417455659721.png)

**Comment by Feuer-sturm** [comment]
ok with Admin 6.2.7

**Comment by mcm1957** [comment]
I can confirm that ist working with latest 6.2.x
