### ISSUE TITLE
Display error of a dialog box in configuration dialog with 6.2.3 and 6.2.4

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#1613]
**Describe the bug**  
A dialog box in adapter fb-checkpresence has an doubled table header. see picture
With v6.2.1 and v6.2.2 all is ok. With v6.2.3 and v6.2.4 the error occours.
![image](https://user-images.githubusercontent.com/50245893/181494881-c953cd30-419b-4ee7-ad31-a07d922bf654.png)

**To Reproduce**  
1. Install adapter fb-checkpresence
2. Configure the adapter that it works and switch to family settings.
3. In the tab you has to cklick on "Add family members"
4. See error in the dialog box

**Expected behavior**  
As in the version 6.2.2

**Screenshots & Logfiles**  
see above

**Versions:**  
 - Adapter version: 6.2.3 and 6.2.4
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: Raspbian GNU/Linux 11 (bullseye)

**Additional context**  
Browser: Edge and Chrome

**Comment by Feuer-sturm** [comment]
@afuerhoff Can you please double check with Admin 6.2.6?

I just installed the adapter on my test system and this it how it looks like on my system
![grafik](https://user-images.githubusercontent.com/25422320/181606839-b5679d96-09d1-4e66-ba96-8902b6db82f7.png)

**Comment by afuerhoff** [comment]
With admin 6.2.6 the same problem as in your picture.

I have made some investigations in my adapter and I changed following in index_m.js: 
"$(id).append(dialogDevices);" to "$(id).html(dialogDevices);"
This solves the problem. But I am wondering why with v6.2.1 there is no problem.

**Comment by Feuer-sturm** [comment]
@afuerhoff Can this issue be closed because you have a new version of your adapter fb-checkpresence?

**Comment by afuerhoff** [comment]
It's ok for me that you close the topic.
But I don't know if this could be a problem of the admin adapter as I only had this problem with version greater than 6.2.3 of the admin adapter.

**Comment by Apollon77** [comment]
Was it retested with 5.2.10 or such from today?

**Comment by afuerhoff** [comment]
With admin 5.3.8 I have no problems.

**Comment by Apollon77** [comment]
hehe ... typo ... meanted 6.2.10

**Comment by afuerhoff** [comment]
With 6.2.10 the same error.

**Comment by afuerhoff** [comment]
With 6.2.11 also the same. But I think it could be a hidden error in my adapter.

**Comment by Feuer-sturm** [comment]
@afuerhoff I close this issue. If you find out that it is still an admin issue we can reopen this issue.
