### ISSUE TITLE
enabled checkbox "logo ausblenden" can not be disabled

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1617]
**Describe the bug**  
If the checkbox "Logo ausblenden" in submenu "login Hintergrund" of admin instance is enabled it is not possible to disable this checkbox by clicking once again.

**Expected behavior**  
Checkbox can be enabled / disabled by clicking

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/25422320/181750306-eeffca15-9267-49af-bd4f-1764c4f4a22d.png)

**Versions:**  
 - Adapter version: 6.2.8

**Comment by Feuer-sturm** [comment]
Same problem with submenu "loading background"

![grafik](https://user-images.githubusercontent.com/25422320/181751024-d6e9a137-fb77-4896-9ebd-5cd777376c56.png)

**Comment by Diginix** [comment]
After you have enable/disable "Hintergrundbild verwenden" you can disable "Logo ausblenden" ;-)

**Comment by Feuer-sturm** [comment]
ok with Admin 6.2.13
