### ISSUE TITLE
Error in GUI! Warning when trying to click on settings in object tab

### ISSUE THREAD

**Issue by PepaonDrugs** [ioBroker/ioBroker.admin#1621]
https://ibb.co/P5TRSgr
here ist the console error Log

**Comment by PepaonDrugs** [comment]
Upgrading the admin version helped sorry for waisting your time

**Comment by PepaonDrugs** [comment]
Neverminde still there

**Comment by Feuer-sturm** [comment]
Which admin version do you use? Please put logs here in comment field. 
I will not open unkown links.

Your title sounds like #1614
Please check.

**Comment by PepaonDrugs** [comment]
Using Version 6.2.10

Error Log:
- unsubscribe sonoff.0.5tromVerbrauch.Wifi_Channel instrument.ts:124 - unsubscribe sonoff.0.5tromVerbrauch.Wifi_Downtime instrument.ts:124 - unsubscribe sonoff.0.5tromVerbrauch.Wifi_LinkCount instrument.ts:124 - unsubscribe sonoff.0.5tromVerbrauch.Wifi_Mode instrument.ts:124 - unsubscribe sonoff.O.StromVerbrauch.Wifi_RSSI instrument.ts:124 - unsubscribe sonoff.O.StromVerbrauch.Wifi_SSId instrument.ts:124 - unsubscribe sonoff.O.StromVerbrauch.Wifi_Signal instrument.ts:124 - unsubscribe sonoff.0.5tromVerbrauch.alive instrument.ts:124 
• PTypeError: Cannot read properties of undefined (reading 'value') instrument.ts:124 at vn.renderItem (Configint,j1x12fil24) at vn.render (ConfigGeneric.jsx:514:39) at Wi (react-dom.production.min.js:204:189) 11111 at Rs (react-dom.production.min.js:203:149) at oa (react-dom.production.min.js:292:172) at ra (react-dom.production.min.js:280:389) at Jc (react-dom.production.min.js:280:320) at ml (react-dom.production.min.js:280:180) at iu (react-dom.production.min.js:271:88) at bs (react-dom.production.min.js:268:429) at Ln (scheduler.production.min.js:13:203) at MessagePort.Gn (scheduler.production.min. s:14:128)

**Comment by cburghardt** [comment]
Same error with zigbee device:

2instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by Feuer-sturm** [comment]
@cburghardt @PepaonDrugs What are the steps to trigger the error?

**Comment by cburghardt** [comment]
Sorry, forgot the version: 6.2.12
I clicked on the properties of a state in order to modify the influxdb settings. This error only happens with items that already have Influxdb settings activated.

**Comment by Feuer-sturm** [comment]
your issues are duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1615#issuecomment-1200093990
I will close this issue here.
