### ISSUE TITLE
"Cannot read property"-error by try to open the properties of an object

### ISSUE THREAD

**Issue by stmiko** [ioBroker/ioBroker.admin#1622]
admin 6.2.10
Google Chrome version Version 103.0.5060.134
same with MS Edge Version 103.0.1264.71
and Firefox 103.0 (64-Bit)

**Describe the bug** 
A Try to open the properties of an object.:
http://192.168.2.102:8081/index.html#tab-objects/customs/mqtt.0.wasserzaehler.main.value

then got the error

- unsubscribe 0_userdata.0.Verschiedenes.Sonnenschutz
instrument.ts:124 - unsubscribe 0_userdata.0.Verschiedenes.reportOpenWindowWashroom
instrument.ts:124 - unsubscribe 0_userdata.0.example_state
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.error
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.json
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.rate
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.raw
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.timestamp
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.main.value
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.connection
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.freeMem
instrument.ts:124 - unsubscribe mqtt.0.wasserzaehler.uptime
2instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
[Violation] Forced reflow while executing JavaScript took 35ms
instrument.ts:124 debounceTime => 0
instrument.ts:124 blockTime => 0
instrument.ts:124 ignoreBelowNumber => 
instrument.ts:124 disableSkippedValueLogging => false
instrument.ts:124 enableDebugLogs => false

This error can be reproduced.

**Comment by Diginix** [comment]
Same here with admin 6.2.10 and Chrome.

```
instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
instrument.ts:124 debounceTime => 0
instrument.ts:124 blockTime => 1000
instrument.ts:124 ignoreBelowNumber => 
instrument.ts:124 disableSkippedValueLogging => false
instrument.ts:124 customRetentionDuration => 365
instrument.ts:124 enableDebugLogs => false
```

**Comment by Feuer-sturm** [comment]
Issue is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1615#issuecomment-1200093990
