### ISSUE TITLE
JSON Config type: Instance; setting for 'all' instance is not working correctly

### ISSUE THREAD

**Issue by ciddi89** [ioBroker/ioBroker.admin#1623]
**Describe the bug**  
I'm using different types of messaging services in my Adapter. The user can choose the Instance of the messaging adapter. Like telegram, pushover etc.
If I use in the jsonConfig the type `instance` and set the config `all` -> 'true'  you can select `All` in the settings for the instance. But when you save it, the adapter breaks down and no message will be send. I logged the value of 'All' and it's only an '*'. I think maybe it's incorrect.

**To Reproduce**  
- Create a menu of type `instance`
- set `all` to true
- choose in the instance configuration `All` and try to get a message

**Expected behavior**  

**Screenshots & Logfiles**  
<img width="231" alt="Screenshot 2022-07-29 at 21 29 33" src="https://user-images.githubusercontent.com/66088020/181831295-0344d832-ddfc-405e-a506-8a6caa8a33af.png">

<img width="424" alt="Screenshot 2022-07-29 at 21 31 07" src="https://user-images.githubusercontent.com/66088020/181831338-4a894bae-8a60-4a19-867e-47b85f4b5eb4.png">

<img width="547" alt="Screenshot 2022-07-29 at 21 31 48" src="https://user-images.githubusercontent.com/66088020/181831375-3a3542f7-7c0a-4ef8-80e3-27e5ea7e1637.png">

**Versions:**  
 - Adapter version: Admin 5.3.8
 - JS-Controller version: 4.0.23
 - Node version: v16.15.1
 - Operating system: Debian

**Comment by Feuer-sturm** [comment]
@ciddi89 Can you please check the behavior with current Admin 6 (6.2.10) as well?

**Comment by ciddi89** [comment]
> @ciddi89 Can you please check the behavior with current Admin 6 (6.2.10) as well?

On my dev-server with admin 6.2.10 is the issue as well.

**Comment by GermanBluefox** [comment]
Works as designed:
![image](https://user-images.githubusercontent.com/4582016/182092603-e0b12ec1-5b5f-4bf9-ba3a-256c5e62f625.png)

**You must** in your code detect the "*" and in this case omit the instance. Just "telegram"

**Comment by ciddi89** [comment]
Oh sorry I guess I overlooked that. Thanks for your advice. I’ll try that.
