### ISSUE TITLE
column configuration in objects does not work

### ISSUE THREAD

**Issue by virgin09** [ioBroker/ioBroker.admin#1625]
**Describe the bug**  
as mentioned in title the column configuration in the objects section does not work properly. When passing with the mouse "ra_configute" is displayed. Two option only are shown when clicking "Ordner immer zuerst" and "Linien zwischen Zeilen anzeigen". No other options, i.e. Name, etc.

**To Reproduce**  
1. Go to "Objekte" in toolbar
2. Click on the Column symbol
4. See error directly

**Expected behavior**  
show all possible options like room, function, type, name etc

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: admin v6.2.11
 - JS-Controller version: <js-controller-version>  4.0.23
 - Node version: <node-version> Node.js:v16.16.0
 - Operating system: Linux

**Additional context*
<img width="960" alt="1659188028671-2022-07-30-1" src="https://user-images.githubusercontent.com/16071396/181920864-262bcc07-ba82-41f5-b265-1cbf7ef4beea.png">
*  
Add any other context ab
![1659189933040-unbenannt-2](https://user-images.githubusercontent.com/16071396/181920851-35325ae7-0923-486c-a087-f44ae15650f0.jpg)
out the problem here.
<img width="960" alt="2022-07-30 (2)" src="https://user-images.githubusercontent.com/16071396/181924253-850451fa-7740-42ca-8792-139c3a4027df.png">

Last screenshot shows how it should be. Did work in Version v6.1.11

See discussion here: https://forum.iobroker.net/topic/56806/ra_configure-fehler-im-admin/12

**Comment by Feuer-sturm** [comment]
Link to previous issue https://github.com/ioBroker/ioBroker.admin/issues/1591 with a similar topic

**Comment by GermanBluefox** [comment]
This feature was disabled

**Comment by elzershark** [comment]
> Diese Funktion wurde deaktiviert

hm.. das wäre nicht gut. wer vorher einige spalten ausgeblendet hatte, bekommt diese nie wieder.
Grad getestet.

**Comment by crunchip77** [comment]
@GermanBluefox  eine Frage, wie bekommt man denn nun die Spalten wieder brauchbar zu Gesicht, bzw kann sich die Werte in der mobilen Ansicht ansehen. Aktuell sieht es so aus mit v6.2.14 . Die gestrichelte Linie sehe ich zwar, kann diese aber nicht verschieben am Handy.
![12345](https://user-images.githubusercontent.com/41550245/183307478-f8dad0d1-f605-4102-a999-fc5de45e6d93.jpg)

**Comment by tetzlav** [comment]
The only way to see the value column is to switch to desktop mode...

**Comment by crunchip77** [comment]
@tetzlav my screen is in desktop mode

**Comment by GermanBluefox** [comment]
> > Diese Funktion wurde deaktiviert
> 
> hm.. das wäre nicht gut. wer vorher einige spalten ausgeblendet hatte, bekommt diese nie wieder. Grad getestet. (6.2.13)

This is fixed

**Comment by crocri** [comment]
Problem still exists in 6.2.19 - if I downgrade to 6.2.4 problem solved (and only with this old version).

No columns to configure:
![B48E0600-8752-436F-8C27-7BFF8D49A0B4](https://user-images.githubusercontent.com/55567276/187030572-f499f461-d4a0-4230-87e0-47928f6cc237.jpeg)

**Comment by Apollon77** [comment]
@GermanBluefox I think what users would like to get back is the option to hide/show columns ...

**Comment by crocri** [comment]
Yes, and set the width, because id is only shown on Safari/ios, no other columns reachable regardless of the used mode - e.g. Desktop.

**Comment by Apollon77** [comment]
For the width the question is if we get the "resize" option somehow also for mobile ... or we need an alternative :-(

**Comment by GermanBluefox** [comment]
> I think what users would like to get back is the option to hide/show columns ...

Early they wanted to remove this feature...

**Comment by tetzlav** [comment]
for me, i only want to have the value column back in mobile view...

**Comment by Apollon77** [comment]
> Earlier they wanted to remove this feature...

I think now ... the question was "now with option to resize in the UI directly do we need to specify the width anymore" ... and then kind of the "eanable/disable" feature eas removed with the other one :-) I think re-introducing the option to completely enable/disable columns helps some users

**Comment by virgin09** [comment]
For me it’s very important to search/ filter by (clear-) name instead by ID or role or room. Everything else is not convenient. So I kindly as to please make this feature work again. I do not necessarily need the option to define the width of the columns. As long as I can specify the elements that I need to search/ filter. Thanks

**Comment by Apollon77** [comment]
Right, setting comuln width should not be restored again ...

**Comment by rtwl21** [comment]
Please make it possible again that we can see values on mobile view.

**Comment by saeft2003** [comment]
Please make it possible again!

**Comment by peterfido** [comment]
Für Mal eben manuell z.b. einen Zählerstand zu korrigieren oder einen Wert zu triggern, ist es notwendig, dass man auch auf mobilen Geräten am die nötigen Spalten kommt. Ich hatte mir damals extra eine Maus fürs Tablet zugelegt, um die Spaltenbreiten anpassen zu können. So, wie es jetzt ist, ist es dafür absolut nicht geeignet.

**Comment by YosPoto** [comment]
Ich plädiere ebenfalls sehr für die Wiedereinführung einer Möglichkeit zur individuellen Anpassung der Spalten auf mobilen Endgeräten. Weder auf einem iPhone13 noch auf einem iPad lassen sich die Spaltenbreiten mit Firefox oder Safari in der mobile Sicht anpassen. Damit geht ein wesentlicher Teil der Nutzbarkeit verloren. Sehr schade.

**Comment by crocri** [comment]
Hi!
Without setting width, the Id consumes the whole Screen (my experience from version  6.2.4)

**Comment by Radla** [comment]
Da ich das Problem ebenfalls habe, würde ich gerne eine alte Version vom Broker instalieren oder ein downgrade machen.
Leider finde ich keinerlei Info dazu und im Installationsscript wurde ich auch nicht fündig. Kann mir da jemand weiterhelfen?

**Comment by stefh1970** [comment]
Das Problem besteht bei mir ebenfalls, da ich nur am Laptop arbeite, würde ich hier gerne die Spaltenbreite einstellen können.

**Comment by stony2k** [comment]
Same problem here. Can't resize the id column any further in my desktop (Chrome, 1920x1280). So I can't see the entitiy names.
![Bildschirm­foto 2022-11-05 um 10 57 44](https://user-images.githubusercontent.com/16526471/200114285-fc11f936-ac09-473a-aa4e-f9eab2f6263f.png)

**Comment by mango1402** [comment]
More or less the same problem...
I want to use my mobile to see (and modify) object values without switching browser to 'desktop mode'. Like it was possible with older Admin-versions....

**Comment by cavernerg** [comment]
Maybe object-tab got a bit lost in "Verschlimmbesserung"? I'd suggest to rollback to a more primitive solution and work from there ?

**Comment by Apollon77** [comment]
Interesting judgement .. based on which details? Based on which comparism ? With Admin 3? Sorry but please post constructive ideas, exact details of your issues, instead or such comments.

The main change is based on the fact that JQuery is outdated as hell and so we needed to upgrade the frontend library used ... but the issue here is that there are no comparable libraies that bring the featurset from before regarding columns, so anything would be needed to be developed anew ... You want to support?, PRs are welcome

**Comment by cavernerg** [comment]
Sorry Apollon , didn't want to hurt anyone or discredit the work done here.  It's no judgement , just my guess based on some observations about changes and issues regarding the tab. 
I don't know how to code (or at least just basics and I'm pretty sure you don't want my coding skills being involved here 😅). But as I work in requirements engineering I have some experience in how you can get lost trying to reach someone. But I'm not involved enough Here to finally decide, if this is the case. 

For now I can just say, that I read some complains (forum, Facebook, issues) about the objects tab and that those people complaining (including me 😅) had issues showing columns properly in desktop and mobile view.

**Comment by tommyMX** [comment]
Hi zusammen, also ich würde es auch gut finden wenn man for alle spalten die Breite verschieben kann aber so wie ich das überflogen habe war es mal User Wunsch dass nur zwei Spalten gehen ?

**Comment by tommyMX** [comment]
@GermanBluefox 
Ich habe gelesen dass es auf user wunsch deaktiviert wurde nur frage ich mich warum? Wenn unter Name mal ein längerer Text ist sieht man den dann ja leider nicht :-( Wäre auch dafür, dass es wieder geht :-)

**Comment by Apollon77** [comment]
Ohne jetzt ins Detail zu gehen: Zu beginn gab es nur die Option harte breiten in Pixel einzustellen. Das wurde entfernt als Bluefox die Option eingebaut hat die relevanten Spalten in der breote (mit der Maus) zu verschieben. Das ganze ist nur Problematisch auf Mobile.
In dem Zuge wurde ebenfalls entfernt das man spalten ganz ausblenden konnte und das soll jetzt erst einmal wieder rein kommen.

**Comment by Feuer-sturm** [comment]
With Admin 6.3.7 it is now possible  to configure which coloum shall be shown/hidden
![grafik](https://user-images.githubusercontent.com/25422320/224570526-e66c2340-3aa1-479a-9d08-530f150bd902.png)
