### ISSUE TITLE
Error in Gui 

### ISSUE THREAD

**Issue by Armin46** [ioBroker/ioBroker.admin#1626]
`Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.0.78:8081
iobroker.admin@6.2.11 bootstrap.jsx:19:8
[2022-07-30T20:49:57.826Z] Try to connect instrument.ts:124:32
Stored version: , new version: 6.2.11 instrument.ts:124:32
Connected: true instrument.ts:124:32
Translate: esphome instrument.ts:124:32
Translate: time instrument.ts:124:32
Translate: timeOffset instrument.ts:124:32
Translate: _nodeCurrent instrument.ts:124:32
Translate: _nodeNewest instrument.ts:124:32
Translate: _nodeNewestNext instrument.ts:124:32
Translate: _npmCurrent instrument.ts:124:32
Translate: _npmNewest instrument.ts:124:32
Translate: _npmNewestNext instrument.ts:124:32
[ADAPTERS] getAdapters instrument.ts:124:32
Translate: ra_Disconnected instrument.ts:124:32
Translate: ra_Connected instrument.ts:124:32
[ADAPTERS] getAdaptersInfo instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.1Pelletsack instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.2Pelletsack instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Benachrichtigung_gesendet instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Benachritigung_2_gesendet instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Durchschnittsverbrauch_Stunde instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Durchschnittsverbrauch_Tag instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Lüfter_Button_VIS instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.PelletStandLetzterVerbrauch instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Pellet_Säcke_im_Lager instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Pelletes_im_Tank instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Pelletverbrauch_bei_Füllung instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Säcke_eingefüllt instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Säcke_eingefüllt_Alt instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Säcke_verbraucht_2019/2020 instrument.ts:124:32
+ subscribe 0_userdata.0.Ofen.Verbrauch_seit_Beginn instrument.ts:124:32
+ subscribe 0_userdata.0.example_state instrument.ts:124:32
+ subscribe Test instrument.ts:124:32
Translate: ra_Configure instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.1Pelletsack instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.2Pelletsack instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Benachrichtigung_gesendet instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Benachritigung_2_gesendet instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Durchschnittsverbrauch_Stunde instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Durchschnittsverbrauch_Tag instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Lüfter_Button_VIS instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.PelletStandLetzterVerbrauch instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Pellet_Säcke_im_Lager instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Pelletes_im_Tank instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Pelletverbrauch_bei_Füllung instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Säcke_eingefüllt instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Säcke_eingefüllt_Alt instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Säcke_verbraucht_2019/2020 instrument.ts:124:32
> stateChange 0_userdata.0.Ofen.Verbrauch_seit_Beginn instrument.ts:124:32
> stateChange 0_userdata.0.example_state instrument.ts:124:32
> stateChange Test instrument.ts:124:32
> objectChange e3dc-rscp.0.PVI.PVI_0 instrument.ts:124:32
> objectChange e3dc-rscp.0.PVI.PVI_0.Phase_0 3 instrument.ts:124:32
> objectChange e3dc-rscp.0.PVI.PVI_0.Phase_1 3 instrument.ts:124:32
> objectChange e3dc-rscp.0.PVI.PVI_0.Phase_2 3 instrument.ts:124:32
> objectChange system.adapter.admin.0.guiSettings instrument.ts:124:32
Please add to "system.adapter.sourceanalytix" common.adminUI={"config":"materialize","custom":"json"} instrument.ts:124:32
> objectChange system.adapter.admin.0.guiSettings instrument.ts:124:32
Translation for word "Alias" in "ru" was ignored: existing = "Псевдоним", new = Имя instrument.ts:124:32
Translation for word "Alias" in "pt" was ignored: existing = "Pseudônimo", new = Alias instrument.ts:124:32
Translate: Day instrument.ts:124:32
Translate: Week instrument.ts:124:32
Translate: Month instrument.ts:124:32
Translate: Quarter instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.1Pelletsack instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.2Pelletsack instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Benachrichtigung_gesendet instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Benachritigung_2_gesendet instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Durchschnittsverbrauch_Stunde instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Durchschnittsverbrauch_Tag instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Lüfter_Button_VIS instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.PelletStandLetzterVerbrauch instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Pellet_Säcke_im_Lager instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Pelletes_im_Tank instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Pelletverbrauch_bei_Füllung instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Säcke_eingefüllt instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Säcke_eingefüllt_Alt instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Säcke_verbraucht_2019/2020 instrument.ts:124:32
- unsubscribe 0_userdata.0.Ofen.Verbrauch_seit_Beginn instrument.ts:124:32
- unsubscribe 0_userdata.0.example_state instrument.ts:124:32
- unsubscribe Test instrument.ts:124:32
TypeError: n is undefined
    componentDidMount ConfigNumber.jsx:43
    React 7
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14
    Webpack 18
instrument.ts:124:32
deviceResetLogicEnabled => true instrument.ts:124:32
threshold => 1 instrument.ts:124:32
`
TypeError: n is undefined
    componentDidMount ConfigNumber.jsx:43
    React 7
        Zs
        Gs
        Gs
        Xc
        bc
        $n
        bs
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
    41196 scheduler.production.min.js:14
    Webpack 18
        n
        72851
        n
        57799
        n
        73961
        n
        I
        t
        n
        24470
        n
        52898
        n
        promise callback*72063
        n
        <anonymous>
        <anonymous>
instrument.ts:124:32

**Comment by Feuer-sturm** [comment]
@Armin46 what did you do to trigger the error?

**Comment by Armin46** [comment]
Der Fehler tritt auf wenn ich die Benutzerdefinierten Einstellungen von Datenpunkten ändern will. Aber komischer weiße nur bei Datenpunkten bei denen der Source Analytix Adatper bereits aktiviert ist. 

Installiert ist Admin 6.2.11 Sourceanalytix 0.4.14 zustäzlich noch Statistics 2.2.0, Influxdb 3.1.7 und History 2.2.0

**Comment by Feuer-sturm** [comment]
@Armin46 Thanks. Your issue is duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1615#issuecomment-1200093990
I will close this issue here.
