### ISSUE TITLE
datapoints created via admin have no native

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#1627]
Create dp via objects tab
Then try to add it in iot adapter
iot won't add it because the datapoint is missing `native: {}`

**Comment by Feuer-sturm** [comment]
@foxriver76 which admin version do you use? Your issue sounds like this one #1148

**Comment by foxriver76** [comment]
Ops, yes sounds exactly the same and I am on stable so most likely fixed.
