### ISSUE TITLE
V 3.1+: 

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.admin#163]
If you switch adapter view to 'Adapter mit Aktualisierungen' and go to another admin tab and come back later, even in the next session, the display shows only  'Adapter mit Aktualisierungen'  but the button is not set to red, which means that you believe that there is no adapter displayed!

I raised already once an issue with no adapters displayed but found now that the 'Adapter mit Aktualisierungen'   is the reason!

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/192
