### ISSUE TITLE
Make the option `staticLink` more visible

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1634]
**Describe the bug**  
ioBroker JSON Config: Make the option `staticLink` more visible. Actually it has the same shape as `staticText` and it is not visible, that there is a link behind.

**Expected behavior**  
f. ex it make sense to change the color and underline the text, similar to:

`jsonConfig.json`
`"applicationKey": {
            "type": "password",
            "label": "applicationKey",
            "help": "applicationKeyHint",
},`

with `translations.json`:

`{
        "applicationKey": "Application key",
	"applicationKeyHint": "text text ' <a href='http://www.google.de' target='_blank'>google.ch</a>.",
}`

**Versions:**  
 - Adapter version: admin v6.2.12

**Comment by GermanBluefox** [comment]
Do you have screenshot, how it now looks like?

**Comment by ice987987** [comment]
`staticLink`:
![062E46B1-5427-42D1-867B-8704D8C6CB88](https://user-images.githubusercontent.com/69053781/182358372-d182432e-cfe0-4800-a314-b8b6e904b4d8.jpeg)

`help`:
![7C1A0666-753D-40D3-A448-5419B3CAAF9B](https://user-images.githubusercontent.com/69053781/182358571-9d5e1fc5-17bb-429c-a71f-cf002d0d16c9.jpeg)

**Comment by GermanBluefox** [comment]
Unfortunately this is not possible: `"applicationKeyHint": "text text ' <a href='http://www.google.de' target='_blank'>google.ch</a>."`, but color of the staticLink I changed.

**Comment by ice987987** [comment]
tested with admin v6.2.17

color is unchanged, fix is **not** effective:

![607C64A4-C46A-46FF-AAE5-FA62FD48751E](https://user-images.githubusercontent.com/69053781/186516851-cd3f455e-8928-45bc-b025-3a68b3b1f1f0.jpeg)

`        "_application_link": {
            "newLine": true,
            "type": "staticLink",
            "label": "application_link",
            "href": "https://www.blabla.com",
            "xs": 12,
            "sm": 12,
            "md": 8,
            "lg": 8
        }
`

**Comment by GermanBluefox** [comment]
Hm.. By me it works:
![image](https://user-images.githubusercontent.com/4582016/187023348-400ac7e9-daef-4a5b-889e-14ffd66f0ec8.png)

**Comment by ice987987** [comment]
Works in v6.2.18. Thank you very much!
