### ISSUE TITLE
"Error in GUI" bei Objekt-Abruf in History

### ISSUE THREAD

**Issue by rka-germany** [ioBroker/ioBroker.admin#1635]
Hallo zusammen,

beim Abruf von History-Daten über das Zahnrad (benutzerdefibierte Einstellungen) bekomme ich neuerdings einen "Error in GUI", 
dies passiert im Chrome-Browser und auch im Firefox und in MS Edge.
Das Ändern der History-Daten über "Objekt bearbeiten" geht ohne Fehler.

Versionen:
Operating system: Ubuntu 20.04.4 LTS (alles aktuell)
Node.js		       v14.20.0
NPM		       6.14.17
alle Adapter sind auf aktuellem Stand.
Admin 6.2.12

Bei der Suche habe ich gesehen, das der besagte Fehler schon in Error in GUI! #1614 behandelt wurde
und in Admin 6.2.7 gefixt sein sollte. Ist jetzt bei mir aber mit der Version 6.2.12 wieder aufgetreten.

Bitte seht mir nach wenn noch benötigte Infos fehlen sollten, es ist meine erste Bug-Meldung ;-)

------------------------------------------------------------------------------------------------------------------------------------

Die Meldungen in der Browser-Konsole:

3instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14

**Comment by Diginix** [comment]
@rka-germany ist erst mit 6.2.13 gefixt
Duplicate #1615

**Comment by rka-germany** [comment]
Vielen Dank für die Info!

**Comment by Feuer-sturm** [comment]
@rka-germany es besteht keine Abhängigkeit zum influx Adapter. Bitte einmal wie genannt mit der 6.2.13 nachtesten. Diese steht ab 14 Uhr im beta Repository zur Verfügung.

**Comment by rka-germany** [comment]
Hallo,

vielen Dank für die Hilfe und die Infos, mit dem neuen Admin hat der Abruf
der History dann funktioniert.

mit freundlichem Gruß
Rainer Kaufhold

-----------------------------------------
>     Rainer Kaufhold
>     Raiffeisenstr. 29
>     D-34270 Schauenburg
>     http://digitalfoto-welt.de
-----------------------------------------


Am Mo., 1. Aug. 2022 um 15:11 Uhr schrieb Feuer-sturm <
***@***.***>:
