### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Maschine20** [ioBroker/ioBroker.admin#1636]
**Describe the bug**  
I tried to open the website for the iobroker web admin.

I got this message:

Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like...

```
index.js:18 iobroker.admin@5.3.8
instrument.ts:124 [2022-08-02T11:47:10.797Z] Try to connect
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 Translate: esphome
instrument.ts:124 Double links: "vis.0" and "slideshow.0"
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 [2022-08-02T11:48:19.124Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:124
instrument.ts:124 [2022-08-02T11:48:19.200Z] Start reconnect 0
instrument.ts:124 [2022-08-02T11:48:19.210Z] Try to connect
instrument.ts:124 [2022-08-02T11:48:58.181Z] ws connection error: CLOSED_NO_STATUS
(anonymous) @ instrument.ts:124
instrument.ts:124 [2022-08-02T11:48:58.283Z] Start reconnect 0
instrument.ts:124 [2022-08-02T11:48:58.297Z] Try to connect
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:124 [2022-08-02T11:50:01.510Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ instrument.ts:124
instrument.ts:124 [2022-08-02T11:50:01.535Z] Start reconnect 0
instrument.ts:124 [2022-08-02T11:50:01.544Z] Try to connect
instrument.ts:124 ChunkLoadError: Loading chunk 13 failed.
(timeout: http://192.168.178.100:8081/static/js/13.d865fe46.chunk.js)
    at u.e (VM14:1:3973)
    at App.js:69:36
    at S (react.production.min.js:18:52)
    at Zi (react-dom.production.min.js:269:22)
    at jl (react-dom.production.min.js:250:347)
    at Vl (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
    at bl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at Ga (react-dom.production.min.js:122:325)
    at Ka (react-dom.production.min.js:123:61)
    at Za (react-dom.production.min.js:122:428)
    at ke (react-dom.production.min.js:292:101)
    at Yt (react-dom.production.min.js:73:352)
    at HTMLDivElement.a (trycatch.ts:99:17)
(anonymous) @ instrument.ts:124
sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

IOBROKER
PLATTFORM: LINUX
RAM: 3.8 GB
NODE.JS: V16.16.0
NPM: 8.11.0

**Comment by Feuer-sturm** [comment]
@Maschine20 Do you see the error by just opening ioBroker Admin Interface or if you switch to one of the menus like adaper, object, ....

**Comment by Maschine20** [comment]
I see it by opening ioBroker Admin Interface

**Comment by Manolo68** [comment]
Similar problem in my web admin.
Tried to open the configuration of cloud adapter, then got this message.
![Screenshot 2022-08-04 095512](https://user-images.githubusercontent.com/87265685/182794886-c70e7799-6272-44f1-a5d5-50c5e006e6b6.png)

It only happens by using the new user interface:
With the old interface everything works fine.

**Comment by Feuer-sturm** [comment]
@Manolo68 please open a new issue for your topic because I assume you have a different error than @Maschine20

**Comment by GermanBluefox** [comment]
> **Describe the bug** I tried to open the website for the iobroker web admin.
> 
> I got this message:
> 
> Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues) Without this information it is not possible to analyse the error. It should looks like...
> 
> ```
> index.js:18 iobroker.admin@5.3.8
> instrument.ts:124 [2022-08-02T11:47:10.797Z] Try to connect
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> instrument.ts:124 Translate: esphome
> instrument.ts:124 Double links: "vis.0" and "slideshow.0"
> instrument.ts:124 Translate: time
> instrument.ts:124 Translate: timeOffset
> instrument.ts:124 Translate: time
> instrument.ts:124 Translate: timeOffset
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> instrument.ts:124 [2022-08-02T11:48:19.124Z] ws connection error: CLOSE_ABNORMAL
> (anonymous) @ instrument.ts:124
> instrument.ts:124 [2022-08-02T11:48:19.200Z] Start reconnect 0
> instrument.ts:124 [2022-08-02T11:48:19.210Z] Try to connect
> instrument.ts:124 [2022-08-02T11:48:58.181Z] ws connection error: CLOSED_NO_STATUS
> (anonymous) @ instrument.ts:124
> instrument.ts:124 [2022-08-02T11:48:58.283Z] Start reconnect 0
> instrument.ts:124 [2022-08-02T11:48:58.297Z] Try to connect
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> instrument.ts:124 [2022-08-02T11:50:01.510Z] ws connection error: CLOSE_ABNORMAL
> (anonymous) @ instrument.ts:124
> instrument.ts:124 [2022-08-02T11:50:01.535Z] Start reconnect 0
> instrument.ts:124 [2022-08-02T11:50:01.544Z] Try to connect
> instrument.ts:124 ChunkLoadError: Loading chunk 13 failed.
> (timeout: http://192.168.178.100:8081/static/js/13.d865fe46.chunk.js)
>     at u.e (VM14:1:3973)
>     at App.js:69:36
>     at S (react.production.min.js:18:52)
>     at Zi (react-dom.production.min.js:269:22)
>     at jl (react-dom.production.min.js:250:347)
>     at Vl (react-dom.production.min.js:250:278)
>     at Cl (react-dom.production.min.js:250:138)
>     at bl (react-dom.production.min.js:243:163)
>     at react-dom.production.min.js:123:115
>     at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
>     at Ga (react-dom.production.min.js:122:325)
>     at Ka (react-dom.production.min.js:123:61)
>     at Za (react-dom.production.min.js:122:428)
>     at ke (react-dom.production.min.js:292:101)
>     at Yt (react-dom.production.min.js:73:352)
>     at HTMLDivElement.a (trycatch.ts:99:17)
> (anonymous) @ instrument.ts:124
> sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7:1          Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> ```
> 
> IOBROKER PLATTFORM: LINUX RAM: 3.8 GB NODE.JS: V16.16.0 NPM: 8.11.0

This could happen after admin update. Please reopen if happens again
