### ISSUE TITLE
[jsonConfig] unexpected / unequal font sizes (might be related to checkboxes only)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1637]
**Describe the bug**  
Labels are written wirth different fontsizes. See screenshot.
I would exoect that labels "Paketgröße" and "Kompatibilitätsmodus - Verwenden Sie die IP-Adresse für Status-IDs" are of equal size.
Most likely the labels for checkboxes are incorrect (too big).

**To Reproduce**  
Load the following jsonConfig.json and select tab "Options"
https://github.com/mcm1957/ioBroker.snmp/blob/a4c3cda888888a80499506af8d5a8b5279ef6272/admin/jsonConfig.json#L1

**Expected behavior**  
I would expect that all lables are of identical size.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/183261283-1d2162d7-c181-47a9-bb12-4c019c697f8f.png)

**Versions:**  
 - Adapter version: admin v6.2.13
 - JS-Controller version: 4.0.23
 - Node version: 14.19.1
 - Operating system: Windows 10

**Note**
The same issue exists with admin 5.x.x

**Comment by Apollon77** [comment]
But on the other side the size of the real value of "Paketgröße" (20) matches with the Checkbox ... and in fact for a checkbox the "Name" kid of is equivalent with the value liek the number, or?

**Comment by mcm1957** [comment]
Ok
So maybe the label of the numeric field should be larger. 

In my oppinion it looks inconsistent. But its only a matter of design. So i guess there ate devs around with more experience with such style guides

**Comment by GermanBluefox** [comment]
Everything works as designed.
![label](https://user-images.githubusercontent.com/4582016/185170941-c63c47d0-b21e-42bb-95d0-523ee376f533.gif)
It is original google material design
