### ISSUE TITLE
Web not showing https certificates/keys

### ISSUE THREAD

**Issue by KonnosPB** [ioBroker/ioBroker.admin#1638]
Hello,
I have a similar one to issue #1214, only this time it is not related to the Admin Adapter, but to the Web Adapter.
The self signed certificates have been inserted via drag and drop and also via file path and have the suffix Private and Public at the end.
![image](https://user-images.githubusercontent.com/38393288/183277749-24ef46ac-da07-49d8-b303-9a3a4946fc6f.png)
_I chose the identifiers defaultPrivate and defaultPublic as an experiment._

While you can select the certificates in the Admin Adapter, this is not possible in the Web Adapter.
![image](https://user-images.githubusercontent.com/38393288/183277761-7a84d725-71c7-415d-9fa5-9e5b9ee2e07c.png)
![image](https://user-images.githubusercontent.com/38393288/183277779-9f680f78-f41e-4e96-9436-e396e1aca3b0.png)

**Comment by KonnosPB** [comment]
Oh yes, I selected the Beta repository and not Stable.

**Comment by Feuer-sturm** [comment]
@KonnosPB is this an issue for admin 6 Adapter?

**Comment by KonnosPB** [comment]
Addition: 
A downgrade to 4.3.0 helped. Please check only version 5.2.4. I close the issue myself. Fortunately, I was able to solve my problem myself.

**Comment by KonnosPB** [comment]
@Feuer-sturm 
No, it was about the future 5.2.4 web adapter.

**Comment by Feuer-sturm** [comment]
Ok. If there is a need,please open a issue on Web Adapter
