### ISSUE TITLE
Consider changing text "Active repository is beta" to "WARNING: Active repository is beta. ..."

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1639]
Please consider changing the "Current rpository is beta" text to a version making it more clear that using the beta repository is risky.

Background:
See https://forum.iobroker.net/topic/55381/admin-6-0-neu-als-beta/279 and following disussion.
See https://forum.iobroker.net/topic/55381/admin-6-0-neu-als-beta/315

I would suggest to change the text within the yellow banner to

"WARNING: Current repository is beta, use at own risk!"
"WARNUNG: Aktives Repository ist "beta". Benutzung auf eigene Gefahr!"

or something similar just as the space allows. The yellow ribbon should be kept, one line of warnign should be enough.  In my oppinon it's not necessary to have a confirmatoon box.

**Comment by Apollon77** [comment]
I would support it

**Comment by Grizzelbee** [comment]
@Apollon77 , @mcm1957 
What about (maybe in addition) adding a kind of traffic light to the bar.
Green bar for the stable repo and yellow bar for latest. Just to better differentiate both environments and give users a quick suggestion where they are and what they are using.

**Comment by Apollon77** [comment]
which "bar" do you mean? There is the "bar" which is yellow for Beta or what do you mean?

**Comment by Grizzelbee** [comment]
This nice and funny yellow "bar" - which contains the environment text:
![grafik](https://user-images.githubusercontent.com/5459426/183380054-3745c6ae-c2f9-4b42-93ba-3647ae86fbd5.png)

**Comment by mcm1957** [comment]
> This nice and funny yellow "bar" - which contains the environment text: ![grafik](https://user-images.githubusercontent.com/5459426/183380054-3745c6ae-c2f9-4b42-93ba-3647ae86fbd5.png)
> 
> EDIT: But it seems to be gone in V6.2.14??

As far as I noticed the yellow banner only occures when BETA is selected. Whne using stable no banner at all is visible.
So my suggestion targets minimum effort by only changing the text.

-> stable - no banner, no text ... this is the current behavior.
-> beta   - yellow banner with new text including "Warning" ... banner is already present, only text need to be adapted.

**Comment by Grizzelbee** [comment]
@mcm1957 said:
> stable - no banner, no text ... this is the current behavior.

I need to disagree - my screenshot id no moc - it's really a screenshot. And I cant remeber having done such a setting.
Also possible is:

![grafik](https://user-images.githubusercontent.com/5459426/183398239-f74516e0-f6bc-44f8-aec3-cbacef356c00.png)


So in the end, only green and yellow aren't sufficient for my idea.
maybe:
* Green for stable
* yellow for latest
* red for any multiselect since it's not clear which repo to use.

**Comment by Feuer-sturm** [comment]
@Grizzelbee try changing your Name of your stable Repository to "stable". In this case you See no yellow banner. Perhaps your Installation is from a time where the Name was "stable (default)"

**Comment by Grizzelbee** [comment]
@Feuer-sturm 
Of course I can do that - but it would solve this issue only for me. Imagine how many installations are out there wich are pretty old and contain another text than "Stable"! I'm just the only one who stumbled over this open issue, made his thoughts and commented.

If my traffic light idea is a bad idea - Okay! Fine for me! I don't force anyone to like or code it.
But in that case please solve the "Stable (default)" issue (or any other text than "Stable") for each and every broker installation out there and replace any other text than "Stable" each time it gets changed. If there is a condition that requires and checks that text - make sure it's set! That's my opinion!
The idea was mainly to give users a warm and cozy feeling when they are on the green path (stable), beeing aware that they have to pay attention (yellow/beta) or they are in trouble (red/multiselect).

And even if anyone fixes the "Stable (default)" issue - the multiselect issue will be still active. 
Is anyone able to answer the question what repo is used when I select more than one? 
I'm aware it makes no sense - but it's not the only config ever that makes no sense and has been set anyways. And if only by accident.

**Comment by Feuer-sturm** [comment]
> Of course I can do that - but it would solve this issue only for me. Imagine how many installations are out there wich are pretty old and contain another text than "Stable"! I'm just the only one who stumbled over this open issue, made his thoughts and commented.
> 
> If my traffic light idea is a bad idea - Okay! Fine for me! I don't force anyone to like or code it. But in that case please solve the "Stable (default)" issue (or any other text than "Stable") for each and every broker installation out there and replace any other text than "Stable" each time it gets changed. If there is a condition that requires and checks that text - make sure it's set! That's my opinion!

I agree with you.. can you please open a new issue for this topic because it is easier to discuss, change and test it if it is not mixed up with a second issue.

**Comment by Feuer-sturm** [comment]
> And even if anyone fixes the "Stable (default)" issue - the multiselect issue will be still active.
> Is anyone able to answer the question what repo is used when I select more than one?
> I'm aware it makes no sense - but it's not the only config ever that makes no sense and has been set anyways. And if only by accident.

It is possible to add own custom Repositories e.g. for commercial adaptets for your customer. If I remember @GermanBluefox correctly the last Repository in the list has the highest priority.

**Comment by mcm1957** [comment]
I think this issue could / should be set on hold until issue #1644 is discussed / implemnted or rejected

**Comment by GermanBluefox** [comment]
I changed only the text

**Comment by Feuer-sturm** [comment]
Admin 6.1.16

New text is available
![grafik](https://user-images.githubusercontent.com/25422320/185501824-595ea0c8-4ae2-4ceb-8aa3-5c7654281cea.png)

I close this issue. Issue #1644 is in progress.
