### ISSUE TITLE
Consider adding a "reset" button to tab repositories

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1641]
I managed to override the url for stable repository at the repository configuration page. (That's my fault.)

**I suggest to add a RESET button to the repository configuration page to reconfigure / restore the standard repositories stable and latest with minimum effort.**

In my situation I could take a look at a second installation to copy the url data so the problem could be fixed without calling for help.

As an alternative protect the standard entries stable / latest from changes.

**Comment by Grizzelbee** [comment]
I think that it will be hardly possible to get such a reset button - even I like the idea.

From my point of view:
It requires to store all possible repos with their URLs somewhere - in Admin itself or even better in an external file. 
But if you do so: 
* Handling Community Repos is pretty easy - the URLs are already publicly known. So there is no special protection needed.
* How to handle company specific repos? 
     * Display them in each and every ioBroker installation (also community edition)? As a result any user will be able to activate them. Is any company happy with this? Is an additional protection needed for those repos so that only paying customers are able to access them?
     * Suppress them by a new edition-flag? Community-Edition, CompanyXY-Edition, ...  But even if you do this - the file and with it the URLs will be publicly accessable. So you end up pretty close to the first scenario.

**Comment by mcm1957** [comment]
Maybe I was not clearly describing the feature requst.

I suggests to add a button to reset the repos to *factory* defaults. Just like they are when installing  iobroker.

This would include removing any repo which was aded later. I do not see any problems as all reset to factory actions of any product will do exactly this - set the system or config to thst what was delivered originally.

Of course the repos would be hardcoded. But tgey are already hardcoded for installtion now. Optionally one coukd gardcode ONE Bootstrap url to get the rest values from.

And NO - I do not thing that the exact urls are widely know for typically users. The can be asked at forum or telegeam but thats not what a medium kniwledge user should be required to do.

**Comment by Grizzelbee** [comment]
> I suggests to add a button to reset the repos to factory defaults. Just like they are when installing iobroker.
This would include removing any repo which was aded later. I do not see any problems as all reset to factory actions of any product will do exactly this - set the system or config to thst what was delivered originally.

Okay. I didn't got that point. I thought of a separate button for each repo to only reset this special repo to default and keep any other untouched.

> And NO - I do not thing that the exact urls are widely know for typically users. The can be asked at forum or telegeam but thats not what a medium kniwledge user should be required to do.
And really check yourself. Could you write down the exact ulr for lastrst and stable without searching web or forum or ...? I cannot.

That's not what I intended - I thought about if company repos need some special (visibility/access) protection which the community repos don't need. The community repos are no secret - company repos may be one.

So your intended: "Reset community repos to default and delete any other - I'll reenter them" of course will work and will be possible to implement.

**Comment by Feuer-sturm** [comment]
Admin 6.2.16
Reset button is implented
![grafik](https://user-images.githubusercontent.com/25422320/185491418-0b8d9ed4-622b-49ca-be20-75c489e649d4.png)


Hint: The button will also remove manually added repositories.
