### ISSUE TITLE
Consider flagging the repos themself as stable/non-stable

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#1644]
**Is your feature request related to a problem? Please describe.**
It has been figured out here:
* https://github.com/ioBroker/ioBroker.admin/issues/1639
that the yellow ribbon/bar saying "You are currently using a BETA repo" relies on the word "Stable" to show up for non-stable repos or beeing supressed for stable ones.

There may exist many old installations like mine still using "Stable (default)" (an old standard text) and therefore showing in stable the text: "You are currently using Repo: Stable (default)" - which is not intended to show since it's special warning function for beta repos is broken in that case. To make it more complicated it's a freetext field and anyone is able to enter anything there - which also breaks the test for the text "Stable".

**Describe the solution you'd like**
In my opinion a solution would be to flag the repo-JSON files themself:

```
{
  "repotype":{
    "stable" : [true || false],
    "name" : ["ioBroker default stable repo" || "ioBroker default beta repo" || "Company XY specific stable repo" || "Company XY specific beta repo" || ...],
    "prio" : 1, [any number is possible; 1 is highest, rest follows in numeric order since it's intuitive]
    [maybe more]
}
  "accuweather": {
    "meta": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.accuweather/master/io-package.json",
    "icon": "https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.accuweather/master/admin/accuweather.png",
    "type": "weather",
    "version": "1.2.1"
  },
[...]
```

Doing that the free text field isn't needed anymore, any user has the same text at any given time (starting with a new admin version of course) and you don't need to rely on the word "Stable" since you have a true/false flag in the repo itself telling what kind of repo it is.
This works for any number of ioBroker Std-repos and customer specific repos as well. When using more flags - more stages are possible.
The prio field may give an organic sort order in config dialog making clear in which order repos are used by the system.
Every Company may get it's own prio range (ioBroker community 1-99, Company XY 100-199, Company YZ 200-299, ...) since adapters usually shouldn't exist in more than one repo (except stable/beta of course).

Additionally it gets possible to detect "senseless" combinations of repo selects since users are able to select as many repos as they like. Therefore it may happen that users select the "ioBroker default stable repo" AND the "ioBroker default beta repo". Which does no harm anymore due to the prio system (stable has 1, beta has 2 - in the worst case the user gets stable versions instead of beta) but it's senseless and you may display this in a RED ribbon/bar saying "You selected an invalid repo combination - please think about what you wanted to achieve and fix your selection!"

**Describe alternatives you've considered**
Automatically Replacing any text in the name field of repos back to "Stable", "Beta". 
This won't work since it's free text field and anyone is able to enter anything he likes.
In addition it's mandatory to change it back every time the user changes it - which makes a free text field senseless.

**Additional context**
This request is related to:
*  https://github.com/ioBroker/ioBroker.admin/issues/1639
* https://github.com/ioBroker/ioBroker.admin/issues/1641

**Comment by mcm1957** [comment]
This idea is the best solution in my oppinion too. So please consider a possible implementation.

The suggested change of the existint json (i.e. http://repo.iobroker.live/sources-dist-latest.json) seems to be impossible as currently the sources list simply contain a list of adapters. So adding "repotype" would possible break older versions of admin which try to list an adapter with such a name.

Any solution must be strictly compatible - older admins must work without any change and without any nonsense data or error.

So I can suggest the following:

a1) Check whether a second json exists which describes the repository, i.e. http://repo.iobroker.live/sources-dist-latest-info.json.
(append -info to the name of the dapater json). If this file exists, it could contain information about the quality of the repo and / or warning text. If the file does not exist, the repo should be considered unstabel. Older admins simply do not access the file and would not be affected.

a2) A variant for a could be that ioBroker provides exactly ONE repo info file for all internal and external repos. New admin could use it to display warnings / infos. Old admin version would simply ignore ist. This solution would require external repo providers to register at ioBroker to get the status of a trusted (stable) repository. This could be eventually an additional benefit
as ioBroker team could specifiy which repos are flagged as trusted.

b) The json data for any adapter already seem to contain an attribute "stable" - which seems to list the stable version. So a warning / info could be based on this. This would require no change at repo level but provide much less possibilities for foreign repos to provide information.

c) Change the context of the sources repo and provide the repos with a new name. This way the repo info could be integrated into one file. Due to ne naming older admins would not be affected. But on teh other side I think that existing installation would not migrate to new naming and hence not use the infomation feature. So c) would be a suboptimal solution.

**Comment by Grizzelbee** [comment]
> Any solution must be strictly compatible - older admins must work without any change and without any nonsense data or error.

I totally agree! 👍 
My idea will be compatible IF older Admins (maybe also the js-controller - I don't know where the repo handling is done) tests for the existence of any of the object members (meta, icon, type, ...) to accept an entry as an adapter - this will skip any invalid adapter entry - what the repotype/repoinfo entry will be. But I don't know if it's done. If not - I agree again - a sidecar file will be the best solution.

> a1) Check whether a second json exists which describes the repository, i.e. http://repo.iobroker.live/sources-dist-latest-info.json.
(append -info to the name of the dapater json). If this file exists, it could contain information about the quality of the repo and / or warning text. If the file does not exist, the repo should be considered unstabel. Older admins simply do not access the file and would not be affected.

I don't fully agree.
If a sidecar file is introduced, it should be mandatory for each repo - stable AND beta. So no considerations about the repotype are needed. The file tells clearly what kind of repo it is. This also applies if it can be inserted into the repo file itself. A repo shouldn't get considered as beta just because the sidecar file got lost by accicent. Additionally there can be a failover mechanism to just use the old/current style if the sidecar file/repoinfo entry isn't found just in case a repo provider missed to provide the file/entry. This won't require any change to older admins. If a single file for all repos will be possible it's also fine. I currently don't see any benefit in splitting the information into different files.

A first structure may be:
```
{
  "repoinfo":{
    "stable" : [true || false],
    "trusted": [true || false],
    "name" : ["Community Stable" || "Community Beta" || "Company XY Stable", ...]
    "desc" : ["ioBroker default stable repo" || "ioBroker default beta repo" || "Company XY specific stable repo" || "Company XY specific beta repo" || ...],
    "prio" : 1, [any number is possible; 1 is highest, rest follows in numeric order since it's intuitive]
    [maybe more]
}
```
Warnings (Yellow/Red) should be implented in admin and only rely on information taken from repoinfo (failsafe).

**Comment by Feuer-sturm** [comment]
Admin 6.1.16

@GermanBluefox I changed the name of the as stable marked repository but the yellow bar is still visible in adapter overview.

![grafik](https://user-images.githubusercontent.com/25422320/185501034-01134c99-fd82-46cf-bdb6-8d2d2888f958.png)

![grafik](https://user-images.githubusercontent.com/25422320/185500929-d299cade-aa22-429d-ba41-df562901839d.png)


My expectation is that the yellow bar is not visible if the repository is marked as stable

**Comment by Grizzelbee** [comment]
Similar here:
Stable repo isn't flagged as stable automatically:
![grafik](https://user-images.githubusercontent.com/5459426/185547075-aa9bf8e1-f750-448e-8de3-957c0da8923f.png)


And multi-select also shows the same message - making it still unclear in which order the repos will be used:
![grafik](https://user-images.githubusercontent.com/5459426/185547262-41b8a619-45cd-4a9f-9ba6-3bf7668e2d6b.png)

So - how is the detection done whether a repo is stable or not? -> Just realized that the "stable"-checkbox is checkable by the user. But the intention was to get the information curated and managed by the core dev team - just like the adapter list. So that the user can not and don't need to change it himself to protect him from messing it up.

**Comment by GermanBluefox** [comment]
> So that the user can not and don't need to change it himself to protect him from messing it up.

:(

**Comment by Grizzelbee** [comment]
@GermanBluefox wrote:
> To implement it it requires to change `js.controller` too, as `repoinfo` will be treated as adapter.

We've already been afraid of that point:

@mcm1957 wrote:
> Any solution must be strictly compatible - older admins must work without any change and without any nonsense data or error.

@Grizzelbee wrote:
> I totally agree! 👍
> My idea will be compatible IF older Admins (maybe also the js-controller - I don't know where the repo handling is done) [...]

This is the reason why we already thought about that sidecar file. But from my point of view, understanding and knowledge it will be the most sustainable, stable and future orientated solution. That's why I putted it to the discussion here. If it don't gets implemented or get's implemented in another way - fine for me. But at least let's talk about it and try to find a solution everybody is mostly happy with. I'm not here to annoy anyone - I just like to support as good as I can to make ioBroker better.

**Comment by Grizzelbee** [comment]
Tested V6.2.17 and looks pretty good to me. 👍 😀 
* Stable repo is detected automatically
* Yellow warning ribbon is only shown for beta repo - not for stable anymore and it's independant from repo name
* no multiselect possible: you can't select stable AND beta any longer at the same time

Thank you very much for implementing this!

Question:
Has the multiselect been removed for any combination of repos? Or does it only suppress stable/beta combinations of any kind (community/company repos)? 
I'm just thinking about whether it would be useful to have the ability of multiselects - e.g. to get adapters from stable where they are available in stable and get those adapters from beta which are (currently) not available in stable. May be pretty handy and useful in some environments/cases. But - just thinking loud.

**Comment by Feuer-sturm** [comment]
Admin 6.2.17

@Grizzelbee Multiselect is still possible:
Just create a new row with a new name and you can select this repo as well:
![grafik](https://user-images.githubusercontent.com/25422320/185712218-d7fe1e9e-69a2-4cff-9d0d-fc8f0530408e.png)


If you are in stable repository and need an adapter of beta repository this adapter can be installed in expert mode by using menu "Installieren aus eigener URL" -> npm

**Comment by Grizzelbee** [comment]
@Feuer-sturm wrote:
>@Grizzelbee Multiselect is still possible:
>Just create a new row with a new name and you can select this repo as well:

Funny. Haven't tried that. Need to think a while what opportunities this opens. 😉 

> If you are in stable repository and need an adapter of beta repository this adapter can be installed in expert mode by using menu "Installieren aus eigener URL" -> npm

I'm fully aware of this way, since I'm using it for years. I'm usually testing my own adapters in my prod environment for a while - especially when developing a new adapter. I just thought last night, that multiselecting may be a nice and handy way to achieve this. Especially for adapters that take very long to get to stable or - even worse - never go to stable. Since there are some!

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Grizzelbee 
From my point of view in this issue is no open topic or do you have a reason to keep this issue open?

@GermanBluefox 
What shall we do with this comment
https://github.com/ioBroker/ioBroker.admin/issues/1644#issuecomment-1220311504

> So that the user can not and don't need to change it himself to protect him from messing it up.
> 
> :(
> To implement it it requires to change js.controller too, as repoinfo will be treated as adapter.

Shall we create a new issue for this enhancement?

**Comment by Grizzelbee** [comment]
@Feuer-sturm wrote:
>@GermanBluefox @Grizzelbee
>From my point of view in this issue is no open topic or do you have a reason to keep this issue open?

The only reson for me to keep it open was to wait for @GermanBluefox answer. For me it's fine to close it.
