### ISSUE TITLE
Objekt Editor: Icon falscher pfad

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.admin#1647]
**Describe the bug**  
Icon am Objekt (mqtt.0.zigbee2mqtt.wz.Ventilator) konfiguriert:
"icon": "zigbee2mqtt/TS011F_plug_1.jpg"

In der Objekttabelle wird dies korrekt dargestellt mit:
src="./adapter/mqtt/zigbee2mqtt/TS011F_plug_1.jpg"

Im Editor auf dem Reiter Common wo man auch eigene Icons hochladen kann wird das Icon nicht dargestellt:
src="zigbee2mqtt/TS011F_plug_1.jpg"

Hier ist der Pfad falsch. Es fehlt ./adapter/mqtt/

**To Reproduce**  
- Icon in einen Unterordnet als Datei hochladen
- Icon mit pfad/datei konfigurieren

**Expected behavior**  
Das Icon sollte im Editor genauso wie in der Tabelle angezeigt werden.

**Screenshots & Logfiles**  
![editor](https://user-images.githubusercontent.com/1881217/184504216-54268f16-4d24-4881-a01a-213d54bf7478.png)
![json](https://user-images.githubusercontent.com/1881217/184504218-08675a6d-9d09-4601-865d-9738bf35c95f.png)
![list](https://user-images.githubusercontent.com/1881217/184504219-e15092b6-b2ab-410a-b117-8539264d1887.png)

**Versions:**  
 - Adapter version: 6.2.14

**Comment by Feuer-sturm** [comment]
@Eistee82 Can you please check with current admin version (6.2.16)?

**Comment by Eistee82** [comment]
![image](https://user-images.githubusercontent.com/1881217/185504383-11875558-9adb-4707-8422-1740ac246f32.png)


It is ok in 6.2.16. thx
