### ISSUE TITLE
Objekttabelle Überschriften und Spalten sind nicht untereinander

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.admin#1649]
**Describe the bug**  
Die Objekttabelle wird total verschoben dargestellt. Mit jedem unterordner sind die Spalten anders verschoben. Die Überschriften passen garnicht zu den Zeilen.

**Screenshots & Logfiles**  
![Objekttabelle](https://user-images.githubusercontent.com/1881217/184532046-adcb9766-baf5-4cf9-8048-77fb96fff9df.png)

**Versions:**  
 - Adapter version: 6.2.14

**Comment by Feuer-sturm** [comment]
@Eistee82 Das Problem hatte ich nach einem update auch einmal. Lösche mal bitte den Browser Cache und teste dann erneut.

**Comment by Eistee82** [comment]
Also selbst am Handy ist es.
![Screenshot_20220814-122806.png](https://user-images.githubusercontent.com/1881217/184532790-b390293c-bfcd-42a4-a902-779ec4484dda.png)

**Comment by Feuer-sturm** [comment]
@Eistee82 Hast du den Browser Cache mal gelöscht?

**Comment by Eistee82** [comment]
Ja frisch geleert. Neu eingeloggt. Selbes Problem. Es fällt stärker auf wenn das Fenster schmaler ist. Auf meinem 4k Bildschirm mit maximierten Fenster sieht es fast richtig aus. Mach ich das Fenster kleiner dann sieht man es stärker.

**Comment by GermanBluefox** [comment]
Das kann ich nicht fixen. Sorry.
Die Lösung ist Zoom oder breiter Bildschirm:
![image](https://user-images.githubusercontent.com/4582016/185173333-7e256545-9384-4ca8-9fc3-396af5bd581c.png)
