### ISSUE TITLE
Adapter tab-window empty when adapter restarts.

### ISSUE THREAD

**Issue by frankjoke** [ioBroker/ioBroker.admin#165]
I work on an adapter which uses an adapter tab (like Javascript) .
Since recent update (3.1.?) I get an empty tab when adapter saves config and restarts.

The reason is that the '.admin-sidemenu-body' get's empty when adapter restarts.

If I click on admin on another adapter-tab and back to my adapter it loads the element again correctly:
<div id="tab-statemachine" data-name="StateMachine" class="tab-custom admin-sidemenu-body-content" data-adapter="statemachine" data-instance="0" data-src="/adapter/statemachine/tab.html" style=""><iframe class="iframe-in-tab" style="border: 0; solid #FFF; display: block; left: 0; top: 0; width: 100%; height: 100%" src="/adapter/statemachine/tab.html"></iframe></div>

p.s.:  another question is how I can assign a tab icon to my adapter tab?

**Comment by GermanBluefox** [comment]
Please retest in 3.2.4
