### ISSUE TITLE
No dropdown for currency in installation wizzard

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1650]
Bug:
There is no dropdown field available for currency.

Expectation:
There is a dropwdown field with different values for currency

![grafik](https://user-images.githubusercontent.com/25422320/185239598-450d4eaa-fd23-4ec5-a492-cc39fda481f8.png)

Version:
Used installer on 17.08.2022

**Comment by GermanBluefox** [comment]
Work as designed. 
Hm. I think the user could use any Symbol for that. Which options should be visible for Currency?
EUR or €
USD or $
RUB or ₽
and so on.

**Comment by Apollon77** [comment]
simply make EUR default? then user maybe see that it's a textfield?

**Comment by Feuer-sturm** [comment]
@GermanBluefox Ok, then it is different to the settings of ioBroker
![grafik](https://user-images.githubusercontent.com/25422320/185373462-cdf5caed-9603-4749-8b30-adeafb7e7467.png)

Here you can select a curency. For me both ways are ok, but both fields should have the same functionality. If ioBroker can handle every symbol a text field would be the easiest soloutin.

**Comment by GermanBluefox** [comment]
I think, I should change it to autocomplete with possibility to enter any character into field

**Comment by Feuer-sturm** [comment]
ok with Admin 6.1.16
