### ISSUE TITLE
GUI nicht erreichbar

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1651]
Nach installation von Admin 6.2.16 ist mein ioBroker nicht mehr via GUI erreichbar.

Backup restored auf 6.2.14 .. alles ok.

**Comment by Apollon77** [comment]
Ok, und was fangen wir damit an? Steht was im Logh? Irgendein Fehler/Crash? Mal iobroker neu gestartet?

**Comment by daniel-lo** [comment]
Ja sorry .. wollte nur erstmal so nebenbei bescheid sagen. Wenn es für andere geht ist alles prima .. hab zwei restores hinter mir (also auch kein Log)

**Comment by Apollon77** [comment]
Ok, ich mache hier aber doch zu bis Du mehr Infos hast ... ohne die können wir nichts tun. bei vielen anderen tuts

Bitte bei sowas immer logs sichern

**Comment by daniel-lo** [comment]
@Apollon77

Admin aktualisiert .. wieder GUI nicht erreichbar .. dann

iobroker start admin

GUI dann erreichbar .. keine weiteren Probleme .. auch nicht nach einem Neustart.

Es scheint als würde (bei mir) der Admin ein Mal manuell gestartet werden müssen, damit der "sitzt" .. natürlich nur wenn die GUI nicht erreichbar ist .. was nicht jedes Mal der Fall ist.

**Comment by Apollon77** [comment]
Logfile?
