### ISSUE TITLE
error in admin 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#1652]
open admin side in chrome ..select first tab intro
wait a 15 min 
![grafik](https://user-images.githubusercontent.com/6681528/185581622-2bb90bcc-67bf-4b40-b98f-5812361c82df.png)

**Comment by GermanBluefox** [comment]
Browser console??

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/185583603-19f57ac0-5f4e-41b0-b63d-c3be73671044.png)

**Comment by GermanBluefox** [comment]
I cannot reproduce it. Anyone could?

**Comment by arteck** [comment]
login on ??

**Comment by GermanBluefox** [comment]
Ne

**Comment by Feuer-sturm** [comment]
@arteck which admin version do you use?  5.2.16?
