### ISSUE TITLE
GUI Problem Objekte

### ISSUE THREAD

**Issue by LastPerfectTobi** [ioBroker/ioBroker.admin#1653]
Am Smartphone ist die Spaltenansicht/Spaltenkonfiguration in Admin 6.x fehlerhaft. 

In Admin 5.x ließen sich Werte und Zustände von Datenpunkten sowohl im Hochformat als auch im Querformat bearbeiten. 
Auch die Spaltenkonfiguration war möglich. 

In Admin 6.x lässt sich nichts mehr konfigurieren, im Hochformat gibts nur eine Spalte mit dem Datenpunkt, rechts die weiteren Spalten mit Werte, Tasten usw.. fehlen. 
Im Querformat ist nach reload der Seite mehr sichtbar, aber fehlt trotzdem einiges, zudem ist der Text oben überlappt. 

Browser: Safari
Smartphone: IPhone mit iOS 15.6.1

![image](https://user-images.githubusercontent.com/75383507/185704049-d8f845c0-5b36-4ff2-8be0-ed13a35eadd7.jpeg)

![image](https://user-images.githubusercontent.com/75383507/185704062-41d782ae-6be7-4610-b5f8-c2d01ea1b84b.jpeg)

![image](https://user-images.githubusercontent.com/75383507/185704081-45c04d26-402a-4f83-9286-2e2196befcc3.jpeg)

**Comment by Feuer-sturm** [comment]
@LastPerfectTobi Dein issue ist doppelt zu https://github.com/ioBroker/ioBroker.admin/issues/1625#issuecomment-1207469745

Vorschlag: Wir schließen dieses issue hier und du hängst dich mit auf das verlinkte issue.

Die von dir erwähnte Spaltenkonfiguration wurde mit Admin 6.2.7 entfernt.
