### ISSUE TITLE
unable to read credentials on login page (autocomplete)

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#1654]
**Describe the bug**  
unable to read credentials on login page

**To Reproduce**  
1. Go to ioBroker login page https://192.168.1.xxx:8081/index.html?login
2. Enter credentials via „autocomplete“ (f.ex. 1Password)
4. See picture

**Expected behavior**  
color combination where credentals can be read

**Screenshots & Logfiles**
![949C84CE-8258-4083-A1D5-231AA5CD7940](https://user-images.githubusercontent.com/69053781/185706212-d5c46b02-2db9-4911-9277-d84a08b9a6a1.jpeg)

**Versions:**  
 - Adapter version: admin v6.2.17
 - iOS 15.6.1
 - Browser: Safari

**Comment by GermanBluefox** [comment]
Bei mir sieht das so aus:
![image](https://user-images.githubusercontent.com/4582016/186099654-ffb5eab2-c83f-49ed-9a14-aaac2b706da6.png)

**Comment by ice987987** [comment]
i can reproduce this on the iPad as well:


https://user-images.githubusercontent.com/69053781/186518005-059a1757-438b-4014-ab16-6b8f405ade51.MOV

**Comment by GermanBluefox** [comment]
So I can guess, it is feature of Password1 and I cannot change the background color of input field.

**Comment by ice987987** [comment]
thanks for your investigation. I'll close here, because it does not hurt that much.
