### ISSUE TITLE
[Admin 6] Alias value not visible after creation - reload required

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1655]
**Describe the bug**  

The value of an alias is not visible after configuration. Page reload is required.

**To Reproduce**  

1. Create a new state object of any data type. e.g. ``0_userdata.0.test``
2. Set a value for that state. e.g. ``true`` if boolean
3. Create an alias. e.g. ``alias.0.test``
4. Edit the alias object ``alias.0.test`` and configure the alias ID ``0_userdata.0.test``
5. Save the object
6. Admin shows value ``(null)`` instead of the current value

A page reload is required to see the current value of the alias state.

**Expected behavior**  

The value of the corresponding state should be visible instantly.

**Versions:**  
 - Adapter version: 6.2.17

**Comment by GermanBluefox** [comment]
This is known. And hard to fix.. I still have no Idea for that

**Comment by Apollon77** [comment]
Shold not be the idea to just trigger a manual "getState" after creating a new object? (can also be done in general but mostly respinse will be "null" ...

**Comment by klein0r** [comment]
Why is this hard to fix? Is there no "stateChange" event when the alias configuration changed?
Is this a js-controller issue?

**Comment by Apollon77** [comment]
js-controller do not trigger a stateChange on an alias object creation ... could also be an idea. But on the other hand Admin just needs to do a getState to get the value ... Because controller could have avery hard job to determine when to really send a "stateChange" ... else we could trigger too many strange updates

**Comment by klein0r** [comment]
> But on the other hand Admin just needs to do a getState to get the value

So admin just needs to execute ``getState`` after the object in ``alias.0`` has been modified?
Sounds like a simple solution 😄

**Comment by Feuer-sturm** [comment]
@klein0r Please check with current admin version

**Comment by klein0r** [comment]
Works perfectly. Tested with v6.2.21
