### ISSUE TITLE
Admin 6 , bei Objekte den Objektbaum begrenzen.

### ISSUE THREAD

**Issue by Glasfaser-io** [ioBroker/ioBroker.admin#1656]
Wie im ioBroker Thread herrausgefunden , war der Objektbaum zu viel geöffnet , so das der Admin / Browserverbindung zusammen gebrochen ist .

https://forum.iobroker.net/topic/57333/objekte-nicht-erreichbar-admin-instabil.

Wie von @Apollon77 angegeben 
**das der Button nie mehr alles aufklappen darf. Maximal einen baumbereich.**

**Comment by Apollon77** [comment]
@GermanBluefox Ich denke wir sollten die Anzahl der subscribe-ten States/OBjekte limitieren im Admin "Objekte" ... also ggf zählen und wenn >200 (oder sowas sinnvolles ... weiss nicht wo die grenze zwischen "könnte normal sein" und "system explodiert" ist) dann nicht weiter subscriben - ggf auch relevante subscribes wieder unsubscriben und in der UI eine Info-Leiste oben einblenden (oder dialog/Popup) mit einer Meldung ala "Too many datapoints shown. Live state data update disabled" anzeigen.

Vllt ists auch gar nicht "die maximale zahl" aber "zuviel state change durchsatz" ... wird der immer noch wie früher auf server seite begrenzt wenn zuviele state changes in zu kurzer zeit kamen?

**Comment by Glasfaser-io** [comment]
Erweiterung :

im Javascript Adapter ( Tab Oberfläche )  wird z.b bei Nutzung von Blockly , bei Auswahl der Objekte das Fenster zum auswählen der Objekte / Datenpunkte geöffnet .

Dort ist der gleiche Effekt **subscribes**  wenn zuviele Ordner geöffnet  wurden .

Wurde hier im Thread festgestellt : 
https://forum.iobroker.net/post/851330

**Comment by Feuer-sturm** [comment]
Admin 7.4.8
Über die Button im Menü Objekte sowie im Javascript Adapter bei dem Blockly Beispiel wird jetzt immer nur eine Einzelne Ebene (Ebene 1, Ebene 2, ...) iterativ aufgeklappt je häufiger man auf den Button klickt.
Aus meiner Sicht ist damit das Problem gelöst.

@Glasfaser-io fyi
