### ISSUE TITLE
Keine Verschiebe Option (Verschiebe Balken) für rechts und links in Javascript.

### ISSUE THREAD

**Issue by Menne01** [ioBroker/ioBroker.admin#1661]
Hallo,
man kann in Javascript ein größeres Blocklyscript nicht mehr nach rechts und links verschieben. Wo ist die Option geblieben?
Um jetzt ein Blockly zu bearbeiten, muss  man es extrems verkleinern, sodas man nichts mehr erkennen kann.

![grafik](https://user-images.githubusercontent.com/89869516/186737708-262128f8-f1f0-48be-99c2-03bdcefb08e3.png)

Ich gehe davon aus, das es am Admin liegt und nicht am Javascript Adapter.

Admin 6.2.18

Gruß

**Comment by GermanBluefox** [comment]
Nein. Das ist das Problem von Javascript: https://github.com/ioBroker/ioBroker.javascript/issues/1095 und die wurde in Javascript@6.0.1 gefixt. Allerdings die Version wurde nicht deployed. Aber das passiert gleich

**Comment by Menne01** [comment]
@GermanBluefox 
funzt wieder

Danke
