### ISSUE TITLE
Options in jsonConfig.json not working

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.admin#1667]
**Describe the bug**  
I use option "readonly" and "nodelete" in my jsonConfig.json as described here:

https://github.com/ioBroker/ioBroker.admin/blob/a19915fdb2daa9c96ad189d16d824be06962123b/src-rx/src/components/JsonConfigComponent/SCHEMA.md

It seems that these options does not work as described.

When using "nodelete" in a table, the elements for adding, deleting and sorting are still there.
When using "readonly" on a text field in a table, the element is still changeable.

**To Reproduce**  
Easiest way might be to use my attached jsonConfig.json

**Expected behavior**  
Using "readonly" : Text field is readonly, changes are not possible
Using "nodelete": There are no buttons in the table for adding, deleting or sorting

**Versions:**  
 - JS-Controller version: 4.0.23
 - Node version: v14.19.3
 - Operating system: Docker
 - Admin: 6.2.17

**jsonConfig.json:**
```
{
	"i18n": true,
	"type": "tabs",
	"items": {
		"_effects": {
			"type": "panel",
			"label": "STabEffects",
			"items": {
				"pnotification": {
					"type": "panel",
					"label": "SEffectNotification",
					"collapsable": true,
					"sm": 12,
					"md": 12,
					"lg": 12,
					"xs": 12,
					"items": {
						"notification": {
							"type": "table",
							"nodelete": true,
							"sm": 12,
							"md": 12,
							"lg": 12,
							"items": [
								{
									"type": "text",
									"attr": "type",
									"readonly": true
								},
								{
									"type": "color",
									"attr": "color",
									"label": "SColor"
								},
								{
									"type": "number",
									"attr": "brightLow",
									"label": "SBrightLow",
									"min": 1,
									"max": 100,
									"step": 1
								},
								{
									"type": "number",
									"attr": "brightHigh",
									"label": "SBrightHigh",
									"min": 1,
									"max": 100,
									"step": 1
								},
								{
									"type": "number",
									"attr": "pulse",
									"label": "SPulse",
									"min": 1,
									"max": 10,
									"step": 1
								}
							]
						}
					}
				}
			}
		}
	}
}
```

**Comment by GermanBluefox** [comment]
Please use `noDelete` and `readOnly` as described in https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/JsonConfigComponent/SCHEMA.md

`readOnly` flag is working only by `text`, `number`, `color` from version 6.2.20

**Comment by gaudes** [comment]
Thanks, 
case-sensitive was the problem :-)
Maybe you put in the documentation?
Thanks and regards,
Ralf
