### ISSUE TITLE
Warning "State "system.adapter.admin.0.guiSettings" has no existing object, this might lead to an error in future versions"

### ISSUE THREAD

**Issue by MaZchen** [ioBroker/ioBroker.admin#1668]
**Describe the bug**  
After update from 5.x to 6.2.17 I receive following warning in the log: "State "system.adapter.admin.0.guiSettings" has no existing object, this might lead to an error in future versions"

**Versions:**  
 - Adapter version: 6.2.17
 - JS-Controller version: 14.19.3
 - Node version: 14.20.0
 - Operating system: Debian 11

Not sure what triggered that..... What I did around the same time was switching on syncing of admin settings and changing the with of some columns in the object view.

**Comment by klassisch** [comment]
Ic can second this.
I have the feeling, that the message appears, when logging in to admin :8081.
`<html><body>


admin.0 | 2022-08-28 15:33:37.053 | warn | State "admin.0.info.connected" has no existing object, this might lead to an error in future versions
-- | -- | -- | --



</body>
</html>` 

Fresh base installation using the current windows installer (2022-08-27) but copying ioBroker-data from old installation.

`
Admin version 6.2.17

Plattform
    Windows
Betriebssystem
    win32
Architektur
    x64
CPUs
    4
Geschwindigkeit
    2295 MHz
Modell
    Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
RAM
    7.88 GB
System-Betriebszeit
    08:53:03
Node.js
    v16.15.1 (Es gibt eine neuere Version: v16.17.0)
time
    1661693819391
timeOffset
    -120
Anzahl der Adapter
    431
NPM
    8.11.0
Datenträgergröße
    463.61 GB
freier Festplattenspeicher
    335.69 GB
Betriebszeit
    08:52:48
Aktive Instanzen
    33
location
    C:\Users\admin\

js-controller version 4.0.23

`

**Comment by Feuer-sturm** [comment]
@MaZchen Please check with current admin version

**Comment by MaZchen** [comment]
Hi!Which Version? I’m currently on 6.2.20 Gesendet von Mail für Windows Von: Feuer-sturmGesendet: Mittwoch, 7. September 2022 20:36An: ioBroker/ioBroker.adminCc: MaZchen; MentionBetreff: Re: [ioBroker/ioBroker.admin] Warning "State "system.adapter.admin.0.guiSettings" has no existing object, this might lead to an error in future versions" (Issue ***@***.*** Please check with current admin version—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Feuer-sturm** [comment]
@MaZchen what is youre message? Did you validate this issue?

**Comment by MaZchen** [comment]
My message is that I am on the current latest available stable release 6.2.20. However I was not able to reproduce the message and I haven’t seen it since. Gesendet von Mail für Windows Von: Feuer-sturmGesendet: Freitag, 9. September 2022 18:07An: ioBroker/ioBroker.adminCc: MaZchen; MentionBetreff: Re: [ioBroker/ioBroker.admin] Warning "State "system.adapter.admin.0.guiSettings" has no existing object, this might lead to an error in future versions" (Issue ***@***.*** what is youre message? Did you validate this issue?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Feuer-sturm** [comment]
issue is fixed
tested with admin 6.2.22
