### ISSUE TITLE
UNIX timestamp

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.admin#1669]
Ist es möglich einen Datenpunkt in dem ein UNIX Timestamp steht im admin in lesbar anzuzeigen? Wenn ich die Rolle auf value.time stelle wird zwar ein datum Uhrzeit format angezeigt allerdings nicht das des unix timestamps der als number im Datenpunkt steht.

**Comment by Apollon77** [comment]
Hm .., also das tut eigentlich. was gernau wird denn angezeigt statt dem "Zeitpunkt des timestamps"? Bzw ... value.time ist Unix-Timestamp in Millisekunden!! Also nicht den Sekundenwert angeben! Das geht schieff. Ists vllt schon das?

**Comment by Eistee82** [comment]
Ja es ist in Sekunden. kann ich das denn automatisch umrechnen für die Darstellung? Oder geht das nur indem ich einen alias anlege?

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/187196169-6dd59ffa-506d-4ec6-a8a1-b2ce1e155131.png)

**Comment by Apollon77** [comment]
But honestly ... This is a "dirty" solution because now Admin Supports values aside the specificiation, but no other visualization or other adapter expects that there and will also not correctly show it ... I would rater revert this in admin (sorry) and @Eistee82 yes use an alias state to have a real state :-)

@GermanBluefox or we need to adjust the role definition or better introduce a new role for that ...

**Comment by Eistee82** [comment]
"unit": "s" or "unit": "ms"

**Comment by Apollon77** [comment]
@Eistee82 Yes on a pragmatic lever you are right ... but this would break/enhance the role definion and needs to be decided carefully, communicated to the developers, libraries like typedetector should be enhanced to support it and then several visualization adapters needs to be adjusted else the UIs will not show it ... Normally we discuss role adjustments in the develoepr community ...

**Comment by Eistee82** [comment]
So i need to ask why is the role changing the display of the value? with multistate the type field is changing the display. And all this is only visual in the ui and did not change the value. so i think the best is to have a type for timestamp and dont use number. so we can select that the ui should display a timestamp in ms or s like we did with multistate.

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 What is the next step with this issue? Is it fixed and can be closed or is a further discussion based on this comment https://github.com/ioBroker/ioBroker.admin/issues/1669#issuecomment-1230570120 necessary?
