### ISSUE TITLE
[v3] Layout of hosts tab is broken

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#167]
![hosts-1](https://user-images.githubusercontent.com/17641229/35731343-7f3d3462-0815-11e8-8d82-76951ddb8ccd.PNG)
and even worse when the window is smaller:
![hosts-2](https://user-images.githubusercontent.com/17641229/35731352-854d4356-0815-11e8-833c-e2cdf68271e1.PNG)

**Comment by AlCalzone** [comment]
Can confirm, looks good.

**Comment by AlCalzone** [comment]
Well I guess not entirely:
![hosts](https://user-images.githubusercontent.com/17641229/37171047-e2e9f420-230c-11e8-8c4d-b7bd1393ba0c.PNG)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/37435343-31b796ea-27e3-11e8-9e30-794bf32c9f4b.png)

**Comment by GermanBluefox** [comment]
Please reopen if still broken

**Comment by AlCalzone** [comment]
We'll see when there's an update ;)
