### ISSUE TITLE
Erro in GUI

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.admin#1670]
**Describe the bug**  
I don't know what triggert it but I was just redirected to the "Error in GUI" page when I clicked on Adapter.

After I reloaded the page the error was gone, it's been happening for a while now without warning sometimes when I click on adapters sometimes when I click on instances. But most of the time everything runs without problems.

**Versions:**  
 - Adapter version: <6.2.18>
 - JS-Controller version: <4.0.23>
 - Node version: <16.16.0>
 - Operating system: Windows 11

No AdBlocker or other stuff activ.
![Screenshot 2022-08-29 12 38 35](https://user-images.githubusercontent.com/111662370/187183216-036ce468-a8d2-4a17-87ee-23ec26e361f4.png)
![Screenshot 2022-08-29 12 28 26](https://user-images.githubusercontent.com/111662370/187181761-ecbeba20-d1e6-4820-8ce5-f703252eecaf.png)
![Screenshot 2022-08-29 12 15 20](https://user-images.githubusercontent.com/111662370/187181810-2c4e73ea-9495-40fe-9072-3f301d4d537d.png)
![Screenshot 2022-08-29 12 15 43](https://user-images.githubusercontent.com/111662370/187181795-1a5b2212-5fbb-48d1-b093-e314f0bee2e4.png)

**Comment by dekatWin** [comment]
After I reloaded the page the error was gone, it's been happening for a while now without warning sometimes when I click on Adapter sometimes when I click on Intances. But most of the time everything runs without problems.

**Comment by dekatWin** [comment]
thx.

**Comment by dekatWin** [comment]
Maybe I should wait with the closing until I can confirm that it doesn't happen anymore. (That's why I reopened it)

**Comment by Horgul123** [comment]
It's marked as fixed... But in which version? for me it exists in 6.2.19 and 6.2.17

**Comment by Horgul123** [comment]
Confirm Fix for 6.2.20
