### ISSUE TITLE
Protokoll, Log Default Settings?

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.admin#1673]
Das Protokoll speichert bei mir leider keine Werte, also die Log Größe ist immer 0B außer ich halten das Protokoll im Browser offen dann funktioniert es wie es soll, sobald ich aber das Fenster schließe sind alle Zeilen weg.
Das Problem hab ich jetzt schon ne weile, ich vermute es handelt sich um eine fehlerhafte erweiterte Einstellung unter Host aber leider bekomme ich das nicht selbst korrigiert.

Ich hatte bereits mehrfach versucht ein File log einzustellen doch jedesmal endete das mit einer defekten Admin Instanz, nach der Änderung lies sich die Weboberfläche nicht mehr erreichen und ich musste auf ein Backup zurück greifen um es wieder zum laufen zu bekommen.

Ist es möglich einen Default Reset der erweiterten Einstellungen durchzuführen ohne das ich den Rest komplett neu installieren muss.

Das sind mein Einstellungen:
![image](https://user-images.githubusercontent.com/111662370/187696741-3bbcc290-966c-4520-b021-de28db7c77e2.png)
![image](https://user-images.githubusercontent.com/111662370/187696884-2767eda5-7f28-4720-8665-168b0cfb9b95.png)
![image](https://user-images.githubusercontent.com/111662370/187183216-036ce468-a8d2-4a17-87ee-23ec26e361f4.png)

**Comment by dekatWin** [comment]
Übrigens mit dem Update von 6.2.18 auf 6.2.20 ist die Reaktionszeit der Oberfläche bei mir um gefühlte 90% gestiegen. 
Echt Klasse! Danke für das ständige Verbessern.

**Comment by Apollon77** [comment]
Weder file1 noch syslog1 hat den" aktiviert "haken ?! Ja dann gibts keine logs

**Comment by dekatWin** [comment]
Was genau sollte ich den nutzen ? Und was genau sollte ich da einstellen, ich hab bislang 5 mal verschiedene Einstellungen von File1 versucht jedesmal war der Admin Adapter danach nicht mehr Erreichbar, und nur ein Backup Rollback hatte noch geholfen.

**Comment by Apollon77** [comment]
Ok, scheinbar hast Du es geschafft das logging des default loggers "file1" zu deaktivieren.

Also gehen wir doch mal ganz low level ...

* iobroker beenden
* /opt/iobroker/iobroker-data/iobroker.json öffnen
* dort sektion "log" suchen und bei transport den "file1" und dort enabled auf true setzen (wie https://github.com/ioBroker/ioBroker.js-controller/blob/master/packages/controller/conf/iobroker-dist.json#L126)
Dann iobroker neu starten

Und ja wenn Du Host settings im Admin änderst wird der iobroker neu gestartet ... Also ist Admin dann (an sich kurz) mal nicht erreichbar. Was genau ggf dann bei dir passiert gäbe es im log zu finden :-)

**Comment by dekatWin** [comment]
Danke, werde das morgen gleich mal versuchen. Das mit dem Neustart ist mir auch klar, aber egal wie lange ich warte Admin war nicht mehr erreichbar, es hat auch kein manueller Neustart, des Admin Adapters, Iobroker oder bei Windows geholfen.

Zumindest weiß ich jetzt wie ich die Einstellung manuell rückgängig machen kann.

**Comment by dekatWin** [comment]
Hat funktioniert super, vielen dank für die Hilfe.
