### ISSUE TITLE
Some icons change and become corrupted when zooming in/out.

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.admin#1678]
**Describe the bug**  
Some icons change and become corrupted when you zoom out.

**To Reproduce**  
1. Open the Admin adapter in a Chrome browser
2. zoom in a lot.
3. zoom out a lot.

**Expected behavior**  
Some icons change, become corrupted

**Screenshots & Logfiles**  
![Screenshot 2022-09-01 22 22 50](https://user-images.githubusercontent.com/111662370/188005222-6acccc5d-7408-4850-b222-f72a47d8d02a.png)
![Screenshot 2022-09-01 22 22 35](https://user-images.githubusercontent.com/111662370/188005244-eff6493a-032d-433b-b3ce-b9d28a2c3b38.png)
![Screenshot 2022-09-01 22 22 18](https://user-images.githubusercontent.com/111662370/188005257-df367ccd-58c5-4898-bad0-d12cb3386f1e.png)

**Versions:**  
Google Chrome Browser Version 105.0.5195.24 
![image](https://user-images.githubusercontent.com/111662370/188004749-55b44b5f-bddc-4c54-9bf4-5b08b573bcdf.png)

**Comment by Apollon77** [comment]
Did you tried other browsers? This sounds more like a browser issue tio me?

**Comment by dekatWin** [comment]
you were right this is a chromebook related bug, neither on windows, android or apple devices the issues show up, no matter if firefox or chrome.

I have tried it on 3 Chromebooks and the problem appeared on all of them.
