### ISSUE TITLE
cannot read instances

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1680]
Admin shows cannot read instances sometimes, if i click on instances.

![image](https://user-images.githubusercontent.com/92173565/188153909-0fb075be-8286-41dc-a196-389ab9913d62.png)

in case that i refresh the page it works

**Comment by Apollon77** [comment]
WOuld be interesting what the browswer log konsole shown in these cases

**Comment by BenAhrdt** [comment]
I will Check this on sunday

**Comment by BenAhrdt** [comment]
Of course I couldn't reproduce it at the moment.
stay tuned

**Comment by BenAhrdt** [comment]
this is in the browser console:
![image](https://user-images.githubusercontent.com/92173565/188927302-63c3886d-b196-4eac-a5df-de152354b821.png)

**Comment by Apollon77** [comment]
Cleare mal alles, cache, cookies, vor allem local storage ... gehts danach wieder? vzw mal bitte admin adapter auf debug log und schauen ob er massig states subscribed

**Comment by BenAhrdt** [comment]
Mache ich mal. Was ich schon sagen kann, wenn man alles cleared, dann läufts wieder.

**Comment by Apollon77** [comment]
kann es sein das du im admin einfach seeehr viel unter "Objekte" aufgeklappt hast? Hatten wir letztens schon das zuviel subscribe traffic war

**Comment by BenAhrdt** [comment]
Ich habe einen großen Ordner aufgeklappt, aber der hat Unterordner und rein effektiv werden nur 5 States angezeigt.
Oder zählen die Unterordner dann mit?
Allerdings hatte ich das Problem auch schon mal, so meine ich zumindest, wenn ich nicht aus dem Untermenü Objekte kam.

**Comment by Feuer-sturm** [comment]
Issue seems not be relevant any more. If the problem still exists @BenAhrdt just add additional information and we can reopen the issue.

**Comment by BlackTigga** [comment]
Hallo, ich bekomme meine Instanzen nicht angezeigt. Es erscheinen hintereinander die Meldungen "Cannot read host information: Error: timeout" gefolgt von "Cannot read instances!"

https://github.com/user-attachments/assets/89bcd520-c197-40d9-85ec-6c4c2cdf0802

Das erhalte ich bei unterschiedlichen Computern.
Irgendwann später, am nächsten Tag oder so, funktioniert es dann mal wieder, und dann kommen irgendwann wieder diese Fehlermeldungen.

Besten Dank für jeglichen Support hierzu.

**Comment by mcm1957** [comment]
@BlackTigga 
Maybe you did not notice that this issue has been close a long time ago.
So if you want to report a new probelm, pleae open a new issue and fill in the requested information.
