### ISSUE TITLE
Spalten in den Ansicht Objekte

### ISSUE THREAD

**Issue by bambi-arch** [ioBroker/ioBroker.admin#1681]
Hallo,

ich kann leider keine Spalten mehr bei Objekte ein oder ausblenden. Die Spalte "Namen" wird nicht angezeigt. In der Vorversion konnte hier mehr ausgewählt werden und die größe verändert werden! Damit ist es fast unmöglich, mit den Objekten zu arbeiten! Browser Safari und Edge gleiche Problem!
![Bildschirmfoto 2022-09-04 um 15 04 17](https://user-images.githubusercontent.com/104907692/188314996-674cd881-925d-4996-821b-20cf5c53f379.png)

**Comment by Apollon77** [comment]
duploicate #1625
