### ISSUE TITLE
Can't open Objects Tab

### ISSUE THREAD

**Issue by JoJ123** [ioBroker/ioBroker.admin#1682]
**Describe the bug**  
When I open Objects Tab the GUI fails.

**To Reproduce**  
1. Go to Objects

**Expected behavior**  

**Screenshots & Logfiles**  

![image](https://user-images.githubusercontent.com/38938791/188442246-52e77516-97f9-420c-921a-c11cc46c2e97.png)

**Versions:**  
 - JS-Controller version: 4.0.23
 - Node version: Node.js: v16.17.0
 - Operating system: linux (docker)

**Comment by Apollon77** [comment]
Pleas etry "iob upload admin" and a hard browser reload ... fixed or still?

**Comment by JoJ123** [comment]
Hi @Apollon77,
command executed & Browser restarted & Reoaded with CTRL + F5
--> Still the same issue

**Comment by Apollon77** [comment]
Does an other browser work? Else which Admin version you use? You can also try to 
* cd /opt/iobroker
* npm i iobroker.admin@version        ... replace "version" by your version
* iob upload admin
* iob restart admin

Work then?

**Comment by JoJ123** [comment]
- Same error on Firefox
- The npm install said "Up To Date" and didn't reinstalled something I guess, after the restart still the same

**Comment by Apollon77** [comment]
And which version is it?

**Comment by JoJ123** [comment]
6.2.20

**Comment by JoJ123** [comment]
6.3.19 or 6.2.19?

**Comment by JoJ123** [comment]
6.2.19 is working, I will updae again to 6.2.20

**Comment by Apollon77** [comment]
hehe, sorry was typo ... But still strange that there was that file error ... maybe check your filesystem
