### ISSUE TITLE
Admin 6.2.21 (and maybe some before) call "load" twice for index_m

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1685]
We researched https://github.com/iobroker-community-adapters/ioBroker.tr-064/issues/405 and https://forum.iobroker.net/topic/57623/tr-064-adapter-komisches-verhalten/ and the results are

1.) "load()" is called twice! (when I see it right in log then one time before the new rypto lib is loaded and once afterwards
2.) When a message is sent via sendTo from index_m in fact TWO messages are sent out and so also two responses come back Logging wise only one sendTo is called

You can use tr-064 Github version that have some logging to verify this.

In fact Admin 5.x do not have this issue. In forum it was reported end of August, so I assume a 6.2.x version, but not yet tested it out

**Comment by djmarc75** [comment]
nachdem ich ab 6.0.3 jede Version getestet habe bin ich bei 6.2.3 auf den Fehler gestossen. Ab dieser Version werden die Einträge vierfach abgezeigt.

**Comment by Feuer-sturm** [comment]
@djmarc75 Please check with current admin version
