### ISSUE TITLE
Object state not accessible on cell phone

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#1688]
I cannot find out by myself how to get the object state on my cell phone .. is there a bug in the mobile gui (6.2.21)?

![grafik](https://user-images.githubusercontent.com/4311558/190325502-bcd17c48-1275-4c0b-b9c9-a1365f5fa3b3.png)

**Comment by Apollon77** [comment]
Try landscape or "desktop view" .. The space is very limited

**Comment by daniel-lo** [comment]
> Try landscape or "desktop view" .. The space is very limited

Landsacpe .. no difference .. don't see more.
Desktop-View didn't load when I tested.

I miss something like horizontal scrolling in that view .. I only have access to the tree itself.

**Comment by Feuer-sturm** [comment]
Issue is duplicate to #1625 
@daniel-lo please check there the discussion and participate.
