### ISSUE TITLE
Ansicht wechselt bei F5 auf "Kacheln" und ist allgemein recht träge

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.admin#1689]
**Describe the bug**  
Ansicht wechselt bei F5 auf "Kacheln" und ist allgemein recht träge
[https://forum.iobroker.net/topic/58040/admin-6-2-22-sehr-tr%C3%A4ge](url)

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/36501310/190845769-cd555ef8-02c6-4f6f-9071-880b080d5a28.png)

**Versions:**  
 - Adapter version: <6.2.22>
 - JS-Controller version: <4.0.23> 
 - Node version: <16.17.0> 
 - Operating system: <Bullseye>

**Comment by Rushmed** [comment]
Bei mir werden auch jedes Mal wenn ich wieder auf die Seite gehe die Kacheln eingestellt.

**Comment by ihavenonick** [comment]
Das Problem konnte eingegrenzt werden und liegt eindeutig an Version 6.2.22, tritt allerdings nur auf, wenn diese Option 
![image](https://user-images.githubusercontent.com/36501310/190889391-196206f0-ce5b-4669-babf-e0b5bdd164c0.png)aktiviert ist.
Hier kommt es dann auch zu der beschriebenen Trägheit, wenn man z.B. einfach von der Adapter Ansicht zu den Instanzen wechselt, oder beim Adapter Installieren das Log Fenster sich öffnen soll, was mit dieser aktiven Option doch recht lange dauert.

**Comment by Apollon77** [comment]
dduplicate #1690

**Comment by Apollon77** [comment]
But I leave open because more details

**Comment by Feuer-sturm** [comment]
@ihavenonick ich kann das Problem bei Admin 7.4.8 nicht mehr reproduzieren. Ich mache das Ticket erstmal zu. Wenn das Problem bei dir noch existiert bitte hier kurz schreiben, dann öffnen wir wieder das Ticket.
