### ISSUE TITLE
cannot set log levels of adapters

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#169]
in Version 3.1.5 it is not possible to set log levels of adapters
The corresponding menu is not displayed and the various levels are not selectable.
Tested with Chrome and Safari.

**Comment by GermanBluefox** [comment]
THere is a 3.1.11 and it is fixed for a long time ago.

**Comment by Marty56** [comment]
I have update to the Github version I guess it is 3.1.11.
And again receiving a almost blank screen when trying to open admin.

The screen says:

Cannot GET /

**Comment by elixier** [comment]
on my installation too

**Comment by Marty56** [comment]
I was able to "fix" the problem by

 sudo iobroker del admin
 sudo iobroker add admin
 sudo iobroker start admin

The version display after this fix is 3.1.11
