### ISSUE TITLE
Seitenleiste wird immer zurückgesetzt, wenn Sync aktiviert

### ISSUE THREAD

**Issue by Rushmed** [ioBroker/ioBroker.admin#1690]
Die Seitenleiste 
![image](https://user-images.githubusercontent.com/59259796/190872442-4a57a2ad-f8e0-47d1-877e-ed0c65c061ee.png)
des Web UI wird unabhängig von der Einstellung beim nächsten Starten des Browsers wieder zurückgesetzt auf:
![image](https://user-images.githubusercontent.com/59259796/190872453-e82ea1e1-a7e4-4d87-84bb-73a8d4c60938.png)

Früher blieb die fesgelegte Eistellung gespeichert.

Tritt seit Admin v6.2.22 und mindestens einer Satbleversion davor auf.

**Comment by Apollon77** [comment]
Wie sind deine Browsereinstellungen? ioBroker speichert die Settings im Browser Local Storage... ... wenn der von deinem browser zurückgesetzt wird sind die Settings auch weg? Bei mir passierts nicht.

**Comment by Feuer-sturm** [comment]
@Rushmed Hast du diese Option aktiv?
![grafik](https://user-images.githubusercontent.com/25422320/190873607-f6be3340-5225-4683-bb23-d4cfdde971c1.png)

Wenn ja, deaktivere diese bitte einmal, ist dann alles normal? In diesem issue #1689 wird mit aktiertem Sync beobachtet, dass die Adapterlist nach einem F5 Refresh auf die Kachelansicht zurückwechselt.

**Comment by Rushmed** [comment]
Jess, Synch war aktiviert. Nach Deaktivierung beleiben die Einstellunge für Seitenleiste und Adapteransicht erhalten.
Danke.

**Comment by Feuer-sturm** [comment]
Ich mach das issue mal wieder auf, damit @GermanBluefox sich das einmal ansehen kann ob das so gewollt ist. So wie ich es in dem anderen Ticket verstanden habe ist das Problem erst mit der Version 6.2.22 aufgetreten.

**Comment by Rushmed** [comment]
Achtung, wie im Eingangspost geschrieben bestand das Problem mindesten eine Stable vor  6.2.22 schon.

**Comment by Feuer-sturm** [comment]
Admin 6.10.4
Problem besteht auch weiterhin mit der aktuellen Admin Version
1. Sync Button aktivieren mit "Einstellungen dieses Browsers verwenden"
2. Menü einklappen
3. Admin Seite neu Laden mit F5
4. Menü ist wieder vollständig ausgeklappt -> nicht ok

**Comment by Feuer-sturm** [comment]
Admin 7.4.8
Seitenleiste bleibt eingeklappt, wenn ich diese Schritte https://github.com/ioBroker/ioBroker.admin/issues/1690#issuecomment-1745688512 wiederhole  -> ok

@Rushmed wenn das Problem bei dir noch aktiv ist, bitte kurz hier schreiben, dann öffnen wir wieder das Ticket.
