### ISSUE TITLE
v6.2.22 - color scheme changes on each login

### ISSUE THREAD

**Issue by kuckuckmann** [ioBroker/ioBroker.admin#1691]
**Describe the bug**  
Since the update to version 6.2.22 I have the behavior, that on each login attemp my dark color scheme is replaced to default white color scheme.

**To Reproduce**  
1. Close Browser with former opened ioBroker running
2. Wait for login timout time span
3. open Browser call iobroker and login

**Expected behavior**  
Former settings should not be changed by automativ logout

**Screenshots & Logfiles**  
Can not delivier now

**Versions:**  
 - Adapter version: 6.2.22
 - JS-Controller version: 4.0.23 
 - Node version: 18.5.0 
 - Operating system: Debian 11

**Additional context**  
Nothing to add

**Comment by Apollon77** [comment]
duplicate #1690
