### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by stevoboy** [ioBroker/ioBroker.admin#1692]
**Describe the bug**  
After installing this adaper via url it throws and Error "GUI error" when clicking on the adapter tab
https://github.com/Apollon77/iobroker.sma-speedwire

**To Reproduce**  
1. Go to adapter tab

**Expected behavior**  
Adapter tab should open

**Screenshots & Logfiles**  
```
instrument.ts:123 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BAdapter%20to%20query%20values%20from%20sma%20devices%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at Q (react-dom.production.min.js:162:372)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:123
raw.githubusercontent.com/instalator/ioBroker.vis-players/master/admin/players.png:1          Failed to load resource: the server responded with a status of 404 ()
```
**Versions:**  
 - Adapter version: 6.2.22
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: linux Synology

**Comment by corny359** [comment]
Hi,
seem I have a similar issue with the GUI:
`Loading chunk 217 failed. (error: http://piobroker.fritz.box:8081/static/js/217.022a0015.chunk.js)
@http://piobroker.fritz.box:8081/static/js/main.a9612c89.js:3:1020(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))@http://piobroker.fritz.box:8081/static/js/main.a9612c89.js:1:1300(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))reduce@[native code](Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))@http://piobroker.fritz.box:8081/static/js/main.a9612c89.js:1:1272(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))@http://piobroker.fritz.box:8081/static/js/5710.edd703fc.chunk.js:73:88195(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))G@http://piobroker.fritz.box:8081/static/js/9526.113dc042.chunk.js:9:3266(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))oa@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:44606(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))ra@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:39834(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))Jc@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:39765(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))ml@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:39624(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))ea@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:36764(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))ea@[native code](Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))hn@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:14:3268(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))@http://piobroker.fritz.box:8081/static/js/3961.a98ff7ab.chunk.js:16:34333`

It happens regularly but I didn't find a specific action that makes it occur.

**Comment by stevoboy** [comment]
It is solved. I tried with Microsoft Edge Browser - there it did not throw the error. Then I deleted the browser cache from Chrome. Now it all works again.
