### ISSUE TITLE
Respository URL verschwinden (Admin 6.2.22)

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.admin#1693]
Ich habe seit kurzem das Problem, dass mir keine Updates für adapter mehr angezeigt werden.
Dank der Hilfe in der Facebookgruppe konnte das jetzt eingegrenzt werden:
Rufe ich im Admin die Repositories aus, wird nichts angezeigt. Beim Zurücksetzen auf die Standartwerte werden Stable und Beta angezeigt und ich kann speichern. In der Konsole des Browsers sehe ich auch ein "Einstellungen gespeichert".
Rufe ich danach die Repositories wieder auf sind die Einträge wieder verschwunden.

nodejs 16.16.0
npm 8.11.0
admin 6.2.22 (vorher mit 6.2.20 gleiches Problem)
Debian 11

Irgendwelche Ideen? Es ging bin vor kurzem noch, kann aber nicht genau sagen ob es genau seit dem Update auf admin 6.2.20 nicht mehr ging oder später auftrat.
Admin habe ich via npm von 6.2.20 auf 6.2.22 aktualisiert.
iob fix ist auch gelaufen

**Comment by Horgul123** [comment]
Wo werden die URLs denn gespeichert? In einer Datei? Kann könnte ich da mal schauen was passiert....

**Comment by Horgul123** [comment]
Hab eben mal über die Console probiert, da kommt das
`oliver@iobrokervm:/opt/iobroker$ iobroker update
Error: Object "system.repositories" not found
`

**Comment by Apollon77** [comment]
Ok, wenn das passiert das ist das Objekt weg ... das sollte an sich NIE passieren!!

Versuch mal ein "iob setup first" ... wenn es danach wieder verschwindet dann ist was ganz komisch

**Comment by Horgul123** [comment]
Sieht gut aus!  Respositories sind da, überleben auch einen Neustart und das Umstellen von stable auf beta.
Vielen Dank erstmal!

Hast Du irgendeine Idee, was sowas verursachen könnte?
Mit den iob setup first erstellt er einfach alle Sachen neu?

**Comment by Apollon77** [comment]
ich denke nachträglich rauszufinden was er verursacht hat ist schwierig und man bräuchte logs ... voin daher, ja setup first legt das neu an

**Comment by Horgul123** [comment]
Ok :)  Vielen Dank nochmal... Und auch allgemein für einen einsatz für ioBroker!

**Comment by mcm1957** [comment]
Problem ist  bei anderem User nochmal aufgetreten.

https://forum.iobroker.net/topic/58458/nur-installierte-adapter-werden-angezeigt-bei-adapter/10

**Comment by Horgul123** [comment]
Muss das leider nochmal aufmachen. Heute waren die Repositories nach einem Neustart der VM wieder weg. Mit iob setup first waren sie wieder da.

**Comment by Apollon77** [comment]
Was hast du getan BEVOR sie weg waren?

**Comment by Horgul123** [comment]
Ich hatte ein Problem, dass mit die Platte vollgelaufen ist durch History Daten.  Hab dann IOB gestoppt, ein paar alte Sachen gelöscht und den Server durchgestartet.
Aufgefallen ist es mir, als ich jetzt auf InfluxDB umsteigen wollte und der Adapter nicht in der Liste war. 
Ich hab erst gestern oder vorgestern noch irgendwelche Adapter aktualisiert, das kann also noch nicht so lange weg gewesen sein.

**Comment by Apollon77** [comment]
Kann es dann sein das ggf vorher schon im Log Probleme wegen freien Plattenplatz waren und er ggf Daten gar nicht gespeichert hat? Daher würde ich das eher darauf schieben ;-)

**Comment by Horgul123** [comment]
Aber wieso waren dann die Respositories weg? Die sollten doch in den Einstellungen drin bleiben wenn man sie nicht rauslöscht....

**Comment by Apollon77** [comment]
Repositories sind am End enur ein Objekt ... wenn also Objekte nicht gespeichert werden können oder so dann fehlt das ggf auch

**Comment by Apollon77** [comment]
Ja, nein, vllt ... wenn sich das objekt wo die drin stehen ändert dann wird es neu geschrieben ...

**Comment by Horgul123** [comment]
hmmm.. ich beobachte das mal... Aber aus meiner Sicht sind die Quellen ja stabil. Aber klar: Wenn die durch den gleichen Wert überschrieben werden seh ich das nicht

**Comment by Apollon77** [comment]
Nochmal passiert?

**Comment by Horgul123** [comment]
> Nochmal passiert?

Nein. Seit längerem nicht mehr.
