### ISSUE TITLE
Admin 6.2.22 Column width cannot be set in the objects

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#1696]
At Objects Tab it's only possible to adjust the column width for ID and after function

**To Reproduce**  
1. Go to lates Admin Version 6.2.22
2. Click on Objects
3. Scroll down to try to modify the column width

**Expected behavior**  
Should be possible to adjust all columns

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/33424168/191930282-11c15f93-44bb-47d3-b6cc-0bdafd6a65b6.png)

**Versions:**  
 - Adapter version: Admin 6.2.22
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Bullseye

**Comment by Feuer-sturm** [comment]
@wendy2702 This is how @GermanBluefox designed it. Currently only the columns ID and value can be resized. @GermanBluefox needs to say if he plans to make the other coloums dynamic as well.

**Comment by wendy2702** [comment]
OK. But on small screens it would be usefull if you can change the size of all columns

**Comment by klassisch** [comment]
Confirmation: On several laptop screens there seems to be no possibility to view the very important column "name", V. 6.22.2
Reported also in https://forum.iobroker.net/post/865586 ff. Some users recommend to downgrade admin to 6.2.4.

**Comment by Linos88** [comment]
Hi, I can relate one to one there...

Admin V6.2.22
Desktop 24" = everything OK
Laptop 15" = column width cannot be changed and "name" is not visible
Smartphones = column width cannot be changed and nothing visible except " ID"

No zoom, no turning, no changing of the browser helps

**Comment by baennjer** [comment]
In addition to this I couldn't manage to change the width on a tablet by sliding over with finger, columns just don't react. 
On Windows Desktop with mouse no problem.

**Comment by nooxnet** [comment]
It's also quite strange with multi-monitor setup. I wondered why I cannot even see the title of the value column on my 24" monitor:

![image](https://user-images.githubusercontent.com/16052584/196027489-f7353765-15a2-47dc-a097-af6d6b6afc12.png)

But when I move the browser window to the 27" monitor I see the title of the value column:

![image](https://user-images.githubusercontent.com/16052584/196027563-907ae0cd-f76f-42f6-91c5-67354afc23b6.png)

Then I can resize it such that it is also visible on my smaller monitors.

I also cannot find the option to set the sizes and hide e.g. the function and room column.

**Comment by Radla** [comment]
On my iPad Air 4 iOS 15 with Safari i have no column "name".
Portrait or landscape doesnt matter:

![1BBBD290-4B02-4600-8EE9-5CE1925CFA19](https://user-images.githubusercontent.com/13787558/196520216-00df36f7-263f-4bc8-a276-73e15bc86bc5.jpeg)
![9B548B1E-5492-40C0-8DB8-D7541C44FA02](https://user-images.githubusercontent.com/13787558/196520227-cf0dc9a1-2b91-4718-a1a3-4f82e3292182.jpeg)

**Comment by baennjer** [comment]
Its hidden behind the dottet line left of the header "Raum"

**Comment by Radla** [comment]
But a doubleclick does not work and drag will also not work on a touchscreen.

**Comment by Radla** [comment]
I have just seen that there is already a post on this issue: https://github.com/ioBroker/ioBroker.admin/issues/1625

**Comment by Linos88** [comment]
After deleting the browser data (old laptop, no Full HD, Chrome), the column width can be adjusted and visible again. Smartphone (iOS) no improvement.

**Comment by Feuer-sturm** [comment]
With Admin 6.3.7 it is now possible to configure which coloum shall be shown/hidden
![grafik](https://user-images.githubusercontent.com/25422320/224570618-823a8a45-5ed9-45c2-84ce-ee7b2db1cf48.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox Do you plan to implement the feature that each coloum can be resized? (Took this questoin from this issue https://github.com/ioBroker/ioBroker.admin/issues/1500) to follow up the discussion in one issue
