### ISSUE TITLE
Every readme is no longer updated again

### ISSUE THREAD

**Issue by PLCHome** [ioBroker/ioBroker.admin#1697]
The readme will be displayed from April 2022:

1.1.1206.04.2022
- (PLCHome) api maintance

The changes from 08/10/2022 are not displayed in the admin interface of iobroker. 
This can be seen in the version history. Other changes to the readme are also not displayed:

1.2.1 (21.09.2022)
(PLCHome) Added an offset to numeric values. My inverter reset te total quantity by itself. Now the total quantity can be corrected.
1.1.19 (30.08.2022)
(PLCHome) HTML Header
1.1.17 (10.08.2022)
(PLCHome) JSON Loopkiller
1.1.16 (10.08.2022)
(PLCHome) https rejectUnauthorized false

**Comment by PLCHome** [comment]
![image](https://user-images.githubusercontent.com/29116097/194402410-2e6264fe-d8b8-4b9d-8ea6-556fbcbdeed5.png)
![image](https://user-images.githubusercontent.com/29116097/194402533-90b2ca7a-c813-4dc9-8dbc-e53b988c87e1.png)
The admin adapter's readme hasn't been updated since May either.

**Comment by GermanBluefox** [comment]
It is because of www.iobroker.net is on old state. And www.iobroker.net is on old state, because google translation costs too much and we do it much less frequent than before.
