### ISSUE TITLE
Admin 6.2.22 Cannot load jsonConfig of linkeddevices: Not exists

### ISSUE THREAD

**Issue by bjaesch912** [ioBroker/ioBroker.admin#1698]
Es können keine Objekte mit dem linkeddevices Adapter verknüpft werden.
Es erscheint der o.g. Fehler.
![inbound7661322874208930829](https://user-images.githubusercontent.com/56491470/192112898-d5289f61-5121-4cbe-9192-d7f9480c8adf.jpg)

**Comment by Apollon77** [comment]
SHould be working starting linkeddevcies 1.5.0 ... which version you have?
I assume an idirect duplicate of https://github.com/Scrounger/ioBroker.linkeddevices/issues/82
