### ISSUE TITLE
Admin 6.2.22 - font-color vis license at dark-mode

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1699]
**Describe the bug**  
![grafik](https://user-images.githubusercontent.com/205119/192130171-6f89123d-2910-42c8-9f67-a0638692acbc.png)

**Comment by GermanBluefox** [comment]
Fixed in 6.2.23

**Comment by Feuer-sturm** [comment]
@darkiop Please check with current admin version

**Comment by Feuer-sturm** [comment]
Issue is fixed. Tested with Admin 6.3.7
![grafik](https://user-images.githubusercontent.com/25422320/224569163-8fcffa3b-f3c0-4d1c-b40f-eb3cde1038df.png)
