### ISSUE TITLE
Outdated README information displayed (snmp adapter)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1700]
**Describe the bug**  
When clicking on the readme (Liesmich) Icon at the adapter tag an outdated README.md is displayed.

**To Reproduce**  
1. install current stable version of snmp
2. Click on "readme" icon
3. The README.md from v0.5.0 is displayed. Meantime v 2.1.8 is available at stable, v2.1.10 is available at github and latest

**Expected behavior**  
I would expect to see either the README.md matching the installed release or the newest README.md

**Versions:**  
 - Adapter version: admin 6.2.22
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - Operating system: Raspian

---

Adapter nsclient does not display any information. But this cpuld be caused by the fact that this adapter is installed via github and is not yet available via the repositories. Nevertheless it would be a nice feature if the infobutton would open the github README.md in those cases. The link to it should be available in io-config.json.

**Comment by Feuer-sturm** [comment]
Looks like is duplicate to #1697
