### ISSUE TITLE
Fehler in GUI! 

### ISSUE THREAD

**Issue by universum78** [ioBroker/ioBroker.admin#1702]
ich habe folgendes Problem:
instrument.ts:123 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

ioBroker ist aber auf der neusten version.

**Comment by Grothesk242** [comment]
Irgendwie etwas dürftig. Wo/wie zeigt sich der 'Fehler'?

**Comment by Glasfaser-io** [comment]
Da du einen Meldung "**instrument.ts:123** " angibst , hast du eventuell auch wie hier im ioBroker Thread Link gerade die gleichen Probleme :

https://forum.iobroker.net/topic/58249/skript-l%C3%B6schen-geht-nicht-permissionerror

**Comment by Feuer-sturm** [comment]
No further information from @universum78. Issue closed. If the issue is still relevant with current admin please add additional information.
