### ISSUE TITLE
Hostname when Multihost not shown in Desktop view on Adapter/Protokolle and such 

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#1705]
In Multihost environments the hostname is shown only on "Overview" in the header but not on Adapter or Protokolle ... This should be added again (for Desktop views).

It seems that on all pages where the name is choosable it is NOT shown ... and on the pages where host is not relevant it is shown

**Comment by Apollon77** [comment]
*ping* confuses users

**Comment by Apollon77** [comment]
Ok, the main issue is fixed, but the current solution is also still confusing because the currently choosen host is only shown on the pages where the host does not matter
![Bildschirmfoto 2023-07-12 um 08 38 06](https://github.com/ioBroker/ioBroker.admin/assets/11976694/4ae0e95e-e36a-4e87-8f73-3032bbd8c462)


vs
![Bildschirmfoto 2023-07-12 um 08 38 27](https://github.com/ioBroker/ioBroker.admin/assets/11976694/59bf2d30-f1bd-4548-941c-ba9ff39d659c)


So yes the "selection" is now correctl, but please also adjust the "hostname display". It can be stay grayed out on irrelevant pages (or can be removed) but added on the relevant pages :-)

**Comment by Feuer-sturm** [comment]
Admin 6.6.1

@foxriver76 Is there a reason why there is a border? My suggestion would be to remove the border. Other icons don't have an icon as well.

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25422320/7c1beaec-1952-4e61-b784-417d5d1c3651)


I would recommend to change the color of the text in the dark mode to white:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25422320/6c907df5-8f89-42e6-b654-849b8a0ab288)

**Comment by foxriver76** [comment]
Borderlands has been there in previous versions too from my knowledge. We can change the color in the next version

**Comment by Feuer-sturm** [comment]
@foxriver76 issue reopened to have an reminder for changing the color of the text and thinking about the border
