### ISSUE TITLE
Chunk Load Error

### ISSUE THREAD

**Issue by MPTrixi** [ioBroker/ioBroker.admin#1707]
Hi,

got a Error in GUI Message and that I shall post it here (it came up after installing the mihome-vacuum adapter, guess after install when it wanted to switch to the instance page):
Loading chunk 4191 failed. (error: https://192.168.1.112:8081/static/js/4191.3894ba77.chunk.js)

ChunkLoadError: Loading chunk 4191 failed.(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))(error: https://192.168.1.112:8081/static/js/4191.3894ba77.chunk.js)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at n.f.j (https://192.168.1.112:8081/static/js/main.a9612c89.js:3:1011)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at https://192.168.1.112:8081/static/js/main.a9612c89.js:1:1300(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at Array.reduce (<anonymous>)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at n.e (https://192.168.1.112:8081/static/js/main.a9612c89.js:1:1266)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at https://192.168.1.112:8081/static/js/5710.edd703fc.chunk.js:73:88049(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at G (https://192.168.1.112:8081/static/js/9526.113dc042.chunk.js:9:3265)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at oa (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:44605)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at ra (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:39832)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at Jc (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:39763)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at ml (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:39622)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at ea (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:36762)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at hn (https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:14:3267)(Y,ae)=>r().createElement("div",{key:ae},Y,r().createElement("br",null))    at https://192.168.1.112:8081/static/js/3961.a98ff7ab.chunk.js:16:34331
![image](https://user-images.githubusercontent.com/56068880/192756380-54b6d585-1903-4fe4-b5f5-3e5d09d490e4.png)
![image](https://user-images.githubusercontent.com/56068880/192756424-e998bd18-ac53-4249-98e6-09b9ab84107c.png)

**Comment by Feuer-sturm** [comment]
@MPTrixi which admin version is installed? What did you do to trigger the issue?

**Comment by foxriver76** [comment]
not enough information to identify the error
