### ISSUE TITLE
viele Fehler/Hinweise im Log seit V6.2.22

### ISSUE THREAD

**Issue by CBRocker** [ioBroker/ioBroker.admin#1709]
Hallo,
seit Update von V5.x auf V6.2.22 bekomme ich immer viele Hinweise/Fehler im Log.
Das war mit V5.x nicht so. Siehe Bild. 
Node.js v16.17.0, NPM 8.15.0,

Muß/kann ich was dagegen machen?

Der Hinweis fullybrowser UpdateDeviceError kommt schon länger, das ist mal zu vernachlässigen.

Ansonsten kann ich den Entwicklern nicht genug danken für so ein geniales Projekt. ioBroker, VIS usw. macht so viel Spaß,
gut, übersichtlich, logisch aufgebaut. Und ich hatte noch nie ernsthafte Probleme/Fehler.
DANKE :-)

![iobroker](https://user-images.githubusercontent.com/96444759/193308401-9a65c4be-5217-479d-b888-628afe14f8c3.jpg)

**Comment by Feuer-sturm** [comment]
Hallo @CBRocker , die Infos vom roomba Adapter müssen im Adapter selber gefixt werden. Dort wird mit falschen Datentypen gearbeitet. Es gibt beim roomba Adapter auch schon ein entsprechendes issue https://github.com/iobroker-community-adapters/ioBroker.roomba/issues/104
Dort kannst du dich mit deinem Log dranhängen, wenn dort noch nicht alle Datenpunkte aufgelistet sind, welche die Info Einträge triggern.

Um die Warnungen vom Roomba Adapter analysieren zu können, stelle den Roomba Adapter wie gefordert auf das Debug Log Level und erstelle dann ein issue beim Roomba Adapter.

Fehler sehe ich keine in deinem Log Ausschnitt :-)

Der Admin Adapter hat hier keinen Einfluss auf deine gemeldeten. Probleme.
