### ISSUE TITLE
[v3] client-side subscriptions only work when objects tab is open

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#171]
In my adapter configuration I use the following code to watch 4 states:
```ts
socket.emit("subscribeStates", namespace + ".info.*");
socket.on("stateChange", (id: string, state: ioBroker.State) => { ... });
```
The states I'm trying to watch are called "info.apiVersion", "info.requiresPairing", "info.paired". When the objects tab is open in another window, I get updates for those 3 states and "info.connection". When the objects tab is *not* open, I only get updates for "info.connection".

Also I get updates for a lot of foreign states like "system.adapter.xxx.0.yyy" although I never actively subscribed to them.

**Comment by GermanBluefox** [comment]
Try

socket.emit("subscribe", namespace + ".info.*");



2018-02-03 14:17 GMT+01:00 AlCalzone <notifications@github.com>:

**Comment by AlCalzone** [comment]
That works, thanks. 
For some reason I always get updates for `system.adapter.cloud.0.alive` and similar states. Is that how it's supposed to be?

**Comment by AlCalzone** [comment]
Another thing: Am I supposed to unsubscribe again when closing the config dialog? Where would I put that code?

**Comment by GermanBluefox** [comment]
$(window).on("beforeunload", function() { 
    socket.emit('unsubscribe', 'blabla');
    return null; 
})
