### ISSUE TITLE
Fehler in GUI!

### ISSUE THREAD

**Issue by pasmei46** [ioBroker/ioBroker.admin#1730]
Seit längerer Zeit kommt nach der Anmeldung zum Teil immer wieder die Meldung: Fehler in GUI!
![image](https://user-images.githubusercontent.com/114834204/193428136-6b0e42b3-cd21-4a1a-aa62-527e68bc3689.png)

Den JS Controller kann ich auch nicht auf die Version 4.0.x updaten. 
Hat diese Meldung einen Zusammenhang?

Vielen Dank für die Unterstützung

**Comment by Apollon77** [comment]
> Den JS Controller kann ich auch nicht auf die Version 4.0.x updaten.
Hat diese Meldung einen Zusammenhang?

Da du nicht sagst wegen welchem Fehler der controller nicht aktualisiert werden kann ist das nicht zu sagen.

**Comment by SteSch81** [comment]
Hallo zusammen, ich habe erst angefangen mit dem iobroker zu arbeiten. Gestern habe ich den sonoff adapter zum laufen gebracht aber wenn ich in objects gehen möchte, bringt er mir diesen Fehler! 
![Fehler in GUI](https://user-images.githubusercontent.com/115268398/194594920-a21b5c96-2675-48cf-b88f-6c2cefcd376e.PNG)

Was läuft falsch?

Vielen Dank!

**Comment by Apollon77** [comment]
Kommt nur der Fehler im Browser-Log oder geht auch irgendetwas nicht?

**Comment by SteSch81** [comment]
Die Objekte lassen sich nicht mehr öffnen. Bei jedem Versuch, kommt die Fehlermeldung. Wenn ich den sonoff adapter lösche, funktioniert wieder alles.

**Comment by SteSch81** [comment]
Hallo nochmal @Apollon77 
Ich habe jetzt auf den Shelly Adapter wechseln wollen, leider kommt der gleiche Fehler wie bei dem Sonoff Adapter. Fehler in der GUI. Ich kann die Objekte nicht mehr öffnen. Erst wenn der Adapter gelöscht ist, funktioniert wieder alles.

![Fehler in GUI_2](https://user-images.githubusercontent.com/115268398/197764662-e2d70d68-f311-4c04-9ae0-e7ed17d94d58.PNG)


Wäre super wenn mir jemand weiterhelfen könnte. Vielen Dank!

**Comment by Feuer-sturm** [comment]
Dieses issue wurde hier #1785 auch schon gemeldet

**Comment by Feuer-sturm** [comment]
@pasmei46 @SteSch81 Bitte einmal Browser Cache leeren und prüfen ob nach einem neu laden der Seite der Fehler weiterhin auftritt.
