### ISSUE TITLE
Inconsistent German ACL translations

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1732]
<img width="202" alt="Screenshot 2022-10-04 at 11 39 28" src="https://user-images.githubusercontent.com/1959049/193788495-a3228170-d8ce-412f-866b-3b2dc89f2806.png">

```
Besitzergruppe: administrator
Besitzer Benutzer: admin
Besitzer kann Objekt lesen,0x400
Besitzer kann Objekt schreiben,0x200
Gruppe kann Objekt lesen,0x40
Gruppe kann Objekt schreiben,0x20
Jeder kann Objekt lesen,0x4
Jeder kann ein Objekt schreiben,0x2
Besitzer kann Zustand lesen,0x400
Besitzer kann Zustand schreiben,0x200
Gruppe kann Status lesen,0x40
Gruppe kann Status schreiben,0x20
Jeder kann Zustand lesen,0x4
Jeder kann Zustand schreiben,0x2
```

- Jeder kann **ein** Objekt schreiben,0x2 - remove "ein"
- Gruppe kann **Status** lesen,0x40 - rename to "Zustand"
- Gruppe kann **Status** schreiben,0x20 - rename to "Zustand"

**Comment by Apollon77** [comment]
Thank you, adjusted in Weblate
