### ISSUE TITLE
Add package-lock.json

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1733]
To avoid issues like https://github.com/ioBroker/ioBroker.javascript/issues/1151 where some people have older dependencies as others and issues are hard to reproduce

> This file is intended to be committed into source repositories, and serves various purposes:

> Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.

**Comment by Apollon77** [comment]
@klein0r This would help anything because the package lock will not be used on npm installation ... it just helps for ci testing and dependency security analysis

**Comment by klein0r** [comment]
Damn, of course 😭
