### ISSUE TITLE
Skript löschen geht nicht - permissionError

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.admin#1734]
**Describe the bug**  
Beim löschen eines Scrip kommt der Fehler "permissionError". Das Script/Blockly kann nichtgelöscht werden.

**To Reproduce**  
1. neues Script/Blockly erstellen
2. Neues Script/Blockly löschen

**Versions:**  
 - Adapter version: 6.2.22
 - JS-Controller version: 4.0.23
 -  - Node version: 16.17.1
 - Operating system: linux Raspberry 4

<img width="617" alt="Bildschirmfoto 2022-10-04 um 19 09 02" src="https://user-images.githubusercontent.com/4241968/193882909-d45c073b-7007-4f44-9a0e-270bd2cc4500.png">

**Comment by Feuer-sturm** [comment]
@bergjet Die Analyse läuft gerade und wird im issue https://github.com/ioBroker/ioBroker.javascript/issues/1151 verfolgt.
