### ISSUE TITLE
[permission handling] Admin crashes when file permissions are changed

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1738]
**To Reproduce**  

1. Login as admin user
2. Go to tab "Files"
3. Upload a new file to "Userdata"
4. Open file permissions and remove "read" for "everyone"
5. save

```
t is not a function. (In 't()', 't' is an instance of Promise)
```

**Versions:**  
 - Adapter version: 6.2.22
 - JS-Controller version: 4.0.23

**Comment by Feuer-sturm** [comment]
admin 7.4.8
I can not reproduce the error with current admin7 version.
@klein0r If this issue is still active, please comment and we will reopen the issue.
