### ISSUE TITLE
History Settings Dialog crashes

### ISSUE THREAD

**Issue by gregx77** [ioBroker/ioBroker.admin#1739]
**Describe the bug**  
Clicking on "Objects > Setting" opens  (SQL) History settings for some milliseconds but crashes with "Error in GUI!"

**To Reproduce**  
1. Go to 'Objects' 
![image](https://user-images.githubusercontent.com/70832546/194249766-8c1abcf6-e45f-48a5-8b25-ce80a1d856d7.png)

2. Click on 'Settings'
3. See error:
![image](https://user-images.githubusercontent.com/70832546/194250086-b869091f-52b1-4e0f-ad5e-63afd29a441c.png)

**Expected behavior**  
History Settings Dialog opens.

**Versions:**  
 - iobroker.admin@6.2.12
 - sql@2.2.0
 - JS-Controller version: 4.0.23
 - Node version: v16.17.1
 - Operating system: OMV6 / docker: buanet/iobroker:latest-v7 (2022-10-04)

**Additional context**  
The State Settings are:
{
  "common": {
    "name": "Z1 Zählerstand WP/Haus Netz",
    "read": true,
    "write": true,
    "type": "number",
    "def": 0,
    "custom": {
      "sql.0": {
        "enabled": true,
        "storageType": "",
        "counter": false,
        "aliasId": "",
        "changesOnly": true,
        "debounce": 1000,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "retention": 0
      }
    },
    "role": "state"
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1664598697626,
  "_id": "0_userdata.0.Haus.Stromzaehler.history.SML_Z1_1_8_0_Total_Pin",
  "acl": {
    "object": 1638,
    "state": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by gregx77** [comment]
I had to downgrade, because of deletion or renaming of states and js-scripts was not possible with current version.

**Comment by Feuer-sturm** [comment]
@gregx77 The issue with the problem of deletion is known. Here is the issue https://github.com/ioBroker/ioBroker.javascript/issues/1151#issuecomment-1266834194 and the current status.

I will close this issue because your issue is based on an old admin version. The current admin version does not have this issue.
