### ISSUE TITLE
Keine Typenauswahl im Cloud.Adapter (Admin V 3.1.10)

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.admin#174]
Hallo, 
Ich kann bei einem erstellten Smart Gerät im Cloud Adapter keine Typenauswahl anwählen. unter (Admin V 3.1.10)

Unter Admin Version 2.0.9 funktionierte es noch.

L.G.

**Comment by AlCalzone** [comment]
Sollte mit https://github.com/ioBroker/ioBroker.cloud/pull/62 gefixt sein. Keine Ahnung welche Cloud-Version das wird/ist.
