### ISSUE TITLE
нет отступов

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#175]
![image](https://user-images.githubusercontent.com/11523624/35778019-b58ec9b4-09ea-11e8-92f4-336bce8f1362.png)
нет отступов

**Comment by GermanBluefox** [comment]
3.2.1
![image](https://user-images.githubusercontent.com/4582016/36903185-46a939b0-1e2d-11e8-902b-72b2d69273c4.png)

**Comment by instalator** [comment]
![image](https://user-images.githubusercontent.com/11523624/36981303-667afe24-20bf-11e8-950c-fd068ca0ef35.png)

**Comment by GermanBluefox** [comment]
Browser?

**Comment by instalator** [comment]
chrome Версия 64.0.3282.186 (Официальная сборка), (64 бит)

**Comment by GermanBluefox** [comment]
Please retest after browsercache purging.
