### ISSUE TITLE
Error in GUI by touching history adapter

### ISSUE THREAD

**Issue by Hakemann** [ioBroker/ioBroker.admin#1756]
**Describe the bug**  
By pressing the tool button of the history adapter the error occures
![image](https://user-images.githubusercontent.com/115536105/195038853-9844f420-2076-4a02-bd06-6e5e663d9b0a.png)

**To Reproduce**  
It can be reproduced allways as above descibed. It also happens by adding a state to the history.

**Expected behavior**  
I want to enter the settings or to add an state 

**Screenshots & Logfiles**  
Translate: DB settings      instrument.ts:124 
TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at ea (react-dom.production.min.js:273:439)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:124

**Versions:**  
 - Adapter version: 2.2.0
 - JS-Controller version: 4.0.23
 - Node version: 16.17.1
 - Operating system: Debian on Raspberry Pi 4
 

**Additional context**  
Restarting the iobroker or removing and installation of the history adapter does not help.

**Comment by Hakemann** [comment]
![image](https://user-images.githubusercontent.com/115536105/195045218-9f226319-f4cf-43b5-a1aa-0eab3063660d.png)

**Comment by Feuer-sturm** [comment]
@Hakemann Which admin version do you use?

**Comment by Hakemann** [comment]
Ich nutze aktuell 6.2.12. Habe gestern morgen von 6.2.22 ein downgrad vorgenommen wegen der Problematik mit dem Löschen von eigenen Objekten und Skripten.
Hiernach trat der Fehler auf.

**Comment by Feuer-sturm** [comment]
Bei mir tritt der Fehler mit der 6.2.22 nicht auf. 
Bitte Fehler nur auf Basis der aktuellen Admin Version einstellen. Seit der 6.2.12 wurde ja schon einiges wieder gefixt
