### ISSUE TITLE
0.userdata.0  Objekte nicht löschbar

### ISSUE THREAD

**Issue by vaaarg** [ioBroker/ioBroker.admin#1757]
0.userdata.0  Objekte nicht löschbar

Sämtliche Versuche das Example State oder neu angelegte Objekte zu löschen wird mit einem "Permission Error" quittiert.

Bullyeye auf raspi. alles aktuell mit nodejs16 admin 6222

**Comment by Feuer-sturm** [comment]
Sounds like this issue https://github.com/ioBroker/ioBroker.javascript/issues/1151

**Comment by Feuer-sturm** [comment]
@vaaarg please check with 6.2.23.

**Comment by vaaarg** [comment]
> @vaaarg please check with 6.2.23.

thank you works
