### ISSUE TITLE
Browser refresh on #tab-adapters always resets admin settings

### ISSUE THREAD

**Issue by jens-maus** [ioBroker/ioBroker.admin#1758]
**Describe the bug**  
Starting with a few iobroker.admin versions back, I noticed that when I access my ioBroker instance, some user configurable admin interface settings / filters are somehow always set to their default values and not saved anymore. So something in the cookie / status / filter management might have changed some versions back which hinders iobroker.admin to load these user settings, e.g. in the adapter tab view, upon web page refresh.

See here: 

![Oct-12-2022 18-33-03](https://user-images.githubusercontent.com/5887769/195398896-58a9e718-dd3f-442f-b3cc-27e5d372ed1d.gif)

**To Reproduce**  
1. Access iobroker instance via http and port 8081
2. Go to #tab-adapters 
3. select some filter settings like "only installed adapters" or another listing type
4. note that when switching from another admin subpage back to the tab-adapters subpage these filter settings are reserved
5. make sure to open a new browser tab or press refresh and note that the tab-adapters listing is reset to its default values again rather than to the previously selected filter settings like this was done until some ioBroker.admin versions before.

**Expected behavior**  
The filter/settings state should be preserved as it was in previous versions of ioBroker.admin.

**Screenshots & Logfiles**  
See uploaded gif screencast above

**Versions:**  
 - Adapter version: 6.2.23
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: Ubuntu 22.04 LTS

**Additional context**  
n/a

**Comment by Feuer-sturm** [comment]
admin 7.4.8
I can not reproduce this issue anymore with admin 7. I will close the issue.

@jens-maus If you can still reproduce the issue, please comment and we will reopen this issue.
