### ISSUE TITLE
Admin UI - Input field truncated at role edit modal

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1759]
**Describe the bug**  
See
![grafik](https://user-images.githubusercontent.com/205119/195970481-d7a8760a-7471-4cdd-bffb-b449780604b2.png)

Admin v6.2.23

**To Reproduce**  
Click on a value in the Role column to open the modal.

**Comment by foxriver76** [comment]
Cannot replicate so I think it has been fixed in the meantime, maybe you can check @darkiop
