### ISSUE TITLE
Feature request: Double Click on Object-Line to open Edit-Modal

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#1762]
**Describe the solution you'd like**
Open the editor for objects with a double click.

**Describe alternatives you've considered**
Click on the pencial.

**Comment by Apollon77** [comment]
Edit modal? for the object propoerties? Or for the value of the object?

You see it could be two options ... so what to open? ;-)

**Comment by darkiop** [comment]
hi ingo, normally i always attach a screenshot. here i forgot...
i meant the object properties.

![grafik](https://user-images.githubusercontent.com/205119/195993405-714493c2-80dd-4194-9bbb-536fc10aa270.png)

From my point of view, they make the most sense.

But perhaps both would also be possible?

* double click -> object properties
* CTRL + double click -> value edit :)

**Comment by Apollon77** [comment]
I would when turn around because from my knowledge users more often use admin to set values then to change object properties, so "set value" should be easier reachable? ;-)

**Comment by darkiop** [comment]
Also an idea. Maybe you could also work with direct keyboard shortcuts: 'E' for Edit and then the double click for Value-Edit?

**Comment by foxriver76** [comment]
We now have the right click context menu with all options.
