### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by marsmaennchen** [ioBroker/ioBroker.admin#1763]
When i try to change the userdefined settings for the Influx Datastorage: 

![error01](https://user-images.githubusercontent.com/33393715/196018599-fdb884a1-945f-4b19-a51f-6b004ba46279.PNG)

An Error occures with the instruction to create an issue and to copy a part of the log from the console of the browser.

`instrument.ts:124 TypeError: Cannot read properties of undefined (reading 'toString')
    at et.componentDidMount (ConfigNumber.jsx:43:40)
    at Zs (react-dom.production.min.js:261:217)
    at Gs (react-dom.production.min.js:260:446)
    at Gs (react-dom.production.min.js:260:343)
    at Xc (react-dom.production.min.js:259:431)
    at bc (react-dom.production.min.js:283:96)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
ea @ react-dom.production.min.js:273
hn @ react-dom.production.min.js:127
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:270
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
`

**Comment by Apollon77** [comment]
WHich admin version is used?

**Comment by marsmaennchen** [comment]
I went down to 6.2.12 (permission denied issue)

**Comment by Apollon77** [comment]
Then please use 6.2.23 from Beta which has fixed the permission issue and check if then this issue still happens

**Comment by marsmaennchen** [comment]
thanks, i try. i give you feedback soon.

**Comment by marsmaennchen** [comment]
Perfect... now my admin is broken, not reachable anymore:
`This adapter cannot be installed directly from GitHub.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.
`

**Comment by marsmaennchen** [comment]
Ok, i downgraded again to 6.2.12. I wait for the stable version to update it from the Admin adapter.Thanks

**Comment by Apollon77** [comment]
Noone told you to update from Github ... The Beta version is available using Admin - Adapters -Expertmode - CUstom Install - "Install from npm" tab

**Comment by marsmaennchen** [comment]
ok, but now i´m waiting since 30 min.
Whats now? Does it really takes so long? :
`$ iobroker url iobroker.admin --host achbot --debug

install iobroker.admin

NPM version: 8.15.0

Installing iobroker.admin... (System call)

up to date in 11s170 packages are looking for funding run `npm fund` for details

upload [51] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png

upload [50] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/customComponents.js custom/customComponents.js application/javascript

upload [40] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/i18n/ru.json custom/i18n/ru.json application/json

upload [30] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js application/javascript

upload [20] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js application/javascript

upload [19] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map application/json

upload [18] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js application/javascript

upload [17] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map application/json

upload [16] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js application/javascript

upload [15] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map application/json

upload [14] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js application/javascript

upload [13] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map application/json

upload [12] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js application/javascript

upload [11] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map application/json

upload [10] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [9] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [8] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/es/translations.json i18n/es/translations.json application/json

upload [7] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [6] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/it/translations.json i18n/it/translations.json application/json

upload [5] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pl/translations.json i18n/pl/translations.json application/json

upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/ru/translations.json i18n/ru/translations.json application/json

upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json

upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json5 jsonConfig.json5 application/json5

Update "system.adapter.admin.0"`

**Comment by Apollon77** [comment]
Was successfull, does it work now?

**Comment by marsmaennchen** [comment]
No, after 45min i pushed the refresh Button (Browser) and the Version of
Adapter is the same. Im waiting for the stable..

Ingo Fischer ***@***.***> schrieb am Mo., 17. Okt. 2022,
11:55:

**Comment by marsmaennchen** [comment]
Update:
Now i updated the Adapter (with the standart updatebutton in Admin)
and everything works again.
Thanks for your help and patience!
