### ISSUE TITLE
Readme wird nicht angezeigt

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1765]
Bei meinen Adaptern wird weder über das Fragezeichen in der Adapterübersicht, noch über das Fragezeichen der Konfiguration die Readme Datei angezeigt.
Es erscheint entweder dies hier:
![image](https://user-images.githubusercontent.com/92173565/196466204-29cc6490-0165-4784-9a0d-1a2852abba22.png)

Oder das:
![image](https://user-images.githubusercontent.com/92173565/196466261-e9fb0ba2-fdca-4ee4-a1e3-ba4dc9029e44.png)

**Comment by Feuer-sturm** [comment]
@BenAhrdt welche Adapter hast du bis jetzt identifiziert und welche Admin Version verwendest du?

**Comment by BenAhrdt** [comment]
Es betrifft komischerweise ALLE meine Adapter. (War schon immer so unabhängig der Admin Version…. Aber aktuell 6.2.22)

**Comment by Feuer-sturm** [comment]
@BenAhrdt Ich hab es gerade mal bei mir bei den folgenden Adapter ausprobiert, wo es keine Probleme gibt:
- admin
- backitup
- rainbird
- daswetter
- influxdb
- dwd
- simple-api
- visfacnyswitch

Stichprobenartig habe ich bei weitere Adapter bei mir auf das Fragezeichen geklickt aber ich hab das Problem erstmal bei meiner Admin 6.2.22 und diversen Adapter nicht.

Taucht das Problem bei dir auch beim admin, backitup, info Adapter auf? Die sind ja in der Regel standarmäßig installiert. Bist du bei der Adapterübersicht in der Kachel oder Listenansicht?

Gibt es Fehlermeldungen in der Browserkonsole?

**Comment by Feuer-sturm** [comment]
Dann poste doch bitte einmal hier die Namen der Adapter, damit Bluefox einen Anhaltspunkt hat.
Betrifft es Adapter die nur direkt von github und nicht über das beta/stable repository installiert wurden?

**Comment by Feuer-sturm** [comment]
I am not quite sure if this issue is a bug or a feature. See also #1703

**Comment by BenAhrdt** [comment]
Ok, but There Is a normal readme

**Comment by BenAhrdt** [comment]
So what is about this?

**Comment by Feuer-sturm** [comment]
Issue is tagged and is pending  until a developer has some free time :-)

**Comment by BenAhrdt** [comment]
OK, sorry i had i sleep attack.
Im not realy there :-)

**Comment by BenAhrdt** [comment]
Its woking

**Comment by BenAhrdt** [comment]
Was wird denn hier angezeigt:
![image](https://user-images.githubusercontent.com/92173565/202910428-a3b02924-22d1-4678-823b-4e14c4bddeff.png)

denn das her ist es scheinbar nicht:
![image](https://user-images.githubusercontent.com/92173565/202910474-70ac7141-59fe-40f4-b901-71f1368a55e7.png)

**Comment by foxriver76** [comment]
Docs are correctly linked for a while now for the reported adapters, will close this one. Regarding texts etc check https://github.com/ioBroker/ioBroker.docs
