### ISSUE TITLE
Missing icon placeholder in object edit dialog

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1767]
**Describe the bug**  

The "default image" (when no icon is defined) is missing.

Generated HTML is ``<img src="adapter/0_userdata/" class="iob310" alt="icon">``. Which is obviously not a valid image path.

**To Reproduce** 

1. Edit an object
2. Click on '+ Icon'
3. See missing image

**Screenshots & Logfiles**  

<img width="1235" alt="Screenshot 2022-10-25 at 08 37 39" src="https://user-images.githubusercontent.com/1959049/197700509-577261a7-7861-41a5-ae05-b0c6f482de98.png">

**Versions:**  
 - Adapter version: 6.2.23

**Comment by foxriver76** [comment]
Will be fixed in next version, however instead of a default, we are showing the correct upload mask, for "no file present yet"

![Bildschirmfoto vom 2023-07-15 11-52-52](https://github.com/ioBroker/ioBroker.admin/assets/25484431/4e6b02e0-2572-4de2-8ab3-09bb42b18a21)
