### ISSUE TITLE
unable to upgrade from 6.2.22 to 6.2.23 

### ISSUE THREAD

**Issue by olli0815** [ioBroker/ioBroker.admin#1769]
hey,
I updates my (2) slaves to admin 6.2.23 successfully (even if these instances are paused..) - everything works fine. 
But my master can't be upgraded properly - I can't find any errors. 
Installer is running through - result is that the instance is still 22 instead of 23.

`host.DaIOBroker Adapter "system.adapter.admin.0" is stopped.
NPM version: 8.19.2
Installing iobroker.admin@6.2.23... (System call)
upload [51] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png
upload [50] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/customComponents.js custom/customComponents.js application/javascript
upload [40] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/i18n/ru.json custom/i18n/ru.json application/json
upload [30] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js application/javascript
upload [20] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js application/javascript
upload [19] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map application/json
upload [18] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js application/javascript
upload [17] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map application/json
upload [16] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js application/javascript
upload [15] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map application/json
upload [14] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js application/javascript
upload [13] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map application/json
upload [12] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js application/javascript
upload [11] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map application/json
upload [10] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [9] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [8] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [7] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [6] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [5] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json5 jsonConfig.json5 application/json5
host.DaIOBroker Adapter "system.adapter.admin.0" is started` 

as mentioned without any changes to the system - where can I look at?

Node.js: v16.18.0
NPM: v8.19.2

[2022-10-26T08_48_08_808Z-debug-0.log](https://github.com/ioBroker/ioBroker.admin/files/9867813/2022-10-26T08_48_08_808Z-debug-0.log)

**Comment by Apollon77** [comment]
Please try "iob fix" and try again. Does it help?

**Comment by olli0815** [comment]
no it doesn't. 
I attached the complete npm - hope that helps.
I couldn't interpret the latest entries with error code 1

**Comment by Apollon77** [comment]
In fact npm has some issues with open_zwave ... this more feelds like the old zwave adapter ... so maybe try to update this one

**Comment by olli0815** [comment]
I already did - i use zwave 2 for years. 
But has not been a problem so fare - obviously.

second: It seems so that I could update any adapter on the host.

**Comment by olli0815** [comment]
okay, my monthly retention backup works fine ..

based on 
Node.js: v14.20.0
NPM: 6.14.17

so obviously individual node / npm issue in my config here..
Thanks for support

**Comment by olli0815** [comment]
..auch wenn ich jetzt plötzlich die beiden Slave-Admin-Adapter wieder in der Übersicht in der version 22 angezeigt bekomme.., die hatte ich ja nun bereits auf den hosts auf 23 upgedated..

Auch nachdem ich die Instanzen neu gestartet bzw. die hosts neu gebootet wurden..
