### ISSUE TITLE
Иконки не отражают своей сути, я думаю вообще можно оставить одну тогловую и иконку заменить на стрелку например

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#177]
![image](https://user-images.githubusercontent.com/11523624/35778026-ed8c6bdc-09ea-11e8-81de-f99278889600.png)

**Comment by GermanBluefox** [comment]
According to google materialize:
![image](https://user-images.githubusercontent.com/4582016/35809545-5196e460-0a89-11e8-9836-6ad467cd68a5.png)
If you find better icons here: http://next.materializecss.com/icons.html
Welcome.

**Comment by salambelgord** [comment]
![icon-](https://user-images.githubusercontent.com/27768450/35917172-cc0e77a2-0c15-11e8-8cdd-b67992790d36.png)
![icon](https://user-images.githubusercontent.com/27768450/35917174-ce71641e-0c15-11e8-94e6-4992241de827.png)

**Comment by instalator** [comment]
arrow_drop_down OR arrow_drop_down_circle
При свернутом списке поворачивть на 90 градусов.
И сделать не две кнопки а одну toggle

**Comment by GermanBluefox** [comment]
Toggle will not suit, because I can expand or collapse the tree with partially expanded/collapsed branches.

**Comment by instalator** [comment]
Ok
