### ISSUE TITLE
Multiple browser sessions are no longer possible

### ISSUE THREAD

**Issue by MosizZ** [ioBroker/ioBroker.admin#1771]
since updating to Node.jsv16.18.0/NPM8.19.2 I can no longer open multiple browser tabs in ioBroker. More precisely. Opening and logging in works, only the session of the "older" tab is ended a short time later. the behavior can be reproduced independently of the browser and operating system.

**Versions:**  
 - Adapter version: v6.2.23
 - JS-Controller version: v4.0.23
 - Node version: v16.18.0
 - Operating system: buster /Client Windows10/11 MacOS Ventura

**Comment by Feuer-sturm** [comment]
@MosizZ I just tried to reproduce your issue.

It seems not to be a general issue.
I can open in two seperate my iobroker Testsystem and I am able to work in both windows of firefox.

![grafik](https://user-images.githubusercontent.com/25422320/198897279-b487beed-f96b-4c8a-bd68-e886f7bcf88a.png)

Does it work on your system if you active this sync feature between browsers?
![grafik](https://user-images.githubusercontent.com/25422320/198897406-4ea72b4b-322a-484b-a6ab-aad6dcc131a7.png)


Version:s 
Adapter version: v6.2.23
JS-Controller version: v4.0.23
Node version: v16.18.0
npm: 8.19.2
OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.4.195-1-pve x86_64), Client Windows10 Firefox

**Comment by crunchip77** [comment]
klappt bei mir auch nicht, sobald ich eine 2te Browserseite öffne, läuft diese in einen timeout, die 1te Seite lässt sich ab diesen Zeitpunkt auch nicht mehr bedienen.

Manchmal kommt der admin von alleine wieder und manchmal muss ich per Konsole einen admin restart ausführen. Im log selbst ist kein Fehler oder Warnung diesbezüglich zu sehen. Sobald ich mehr Info habe, reiche ich diese nach.
