### ISSUE TITLE
Кнопка перезапустить обозначает выключить/включить

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#178]
![image](https://user-images.githubusercontent.com/11523624/35778033-f7d141c6-09ea-11e8-96c0-671420b45519.png)

**Comment by GermanBluefox** [comment]
Fixed in 3.2.1
![image](https://user-images.githubusercontent.com/4582016/36903219-60b83784-1e2d-11e8-995d-5c2b1a9eb4ff.png)
