### ISSUE TITLE
Fehler in GUI

### ISSUE THREAD

**Issue by GerdNi** [ioBroker/ioBroker.admin#1784]
Wenn ich in der GUI den Tab Adapters öffne bekomme ich diese nicht angezeigt.
Statt dessen kommt die Nachricht ich möge doch zur Fehleranalyse den Inhalt der Konsole hier hereinkopieren.
Es funktioniert alles wie es soll außer das die Adapter nicht angezeigt werden.

iobroker.admin@6.2.17
instrument.ts:123 [2022-11-01T10:56:07.331Z] Try to connect
instrument.ts:123 Stored version: , new version: 6.2.17
instrument.ts:123 Connected: true
5instrument.ts:123 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ instrument.ts:123
instrument.ts:123 Double links: "flot.0/flot/edit.html" and "flot.0"
instrument.ts:123 Double links: "material.0/material/index.html" and "material.0"
instrument.ts:123 Double links: "mobile.0/mobile/index.html" and "mobile.0"
instrument.ts:123 Double links: "vis.0/vis/edit.html" and "vis.0"
instrument.ts:123 Translate: Link
instrument.ts:123 Translate: time
instrument.ts:123 Translate: timeOffset
instrument.ts:123 Translate: _nodeCurrent
instrument.ts:123 Translate: _nodeNewest
instrument.ts:123 Translate: _nodeNewestNext
instrument.ts:123 Translate: _npmCurrent
instrument.ts:123 Translate: _npmNewest
instrument.ts:123 Translate: _npmNewestNext
7instrument.ts:123 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ instrument.ts:123
instrument.ts:123 Double links: "flot.0/flot/edit.html" and "flot.0"
instrument.ts:123 Double links: "material.0/material/index.html" and "material.0"
instrument.ts:123 Double links: "mobile.0/mobile/index.html" and "mobile.0"
instrument.ts:123 Double links: "vis.0/vis/edit.html" and "vis.0"
2instrument.ts:123 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ instrument.ts:123
instrument.ts:123 [ADAPTERS] getAdapters
instrument.ts:123 [ADAPTERS] Cannot compare "" and "4.0.23"
(anonym) @ instrument.ts:123
instrument.ts:123 [ADAPTERS] getAdaptersInfo
instrument.ts:123 TypeError: Cannot read properties of undefined (reading 'beta')
    at Adapters.jsx:1744:38
    at Array.map (<anonymous>)
    at Zs.render (Adapters.jsx:1743:70)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonym) @ instrument.ts:123

**Comment by Feuer-sturm** [comment]
@GerdNi Bitte einmal die aktuelle admin version 6.2.23 installieren und damit prüfen.

**Comment by GerdNi** [comment]
@Feuer-sturm Ich konnte nicht upgraden da auch das Repro zerschossen war.
Ich habe ein Backup eingespielt und alle Adapter auf den neuesten Stand gebracht.
Es läuft wieder alles wie es soll, auch der neue Admin :-)
