### ISSUE TITLE
Cannot find npm version - docker

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.admin#1789]
Current version: 6.2.23
Since Admin 6 I get the following message in the log: Cannot get current npm version: Cannot find npm version

The npm version is actually shown correctly in the overview tab (for all nodes). I have a master-slave setup, the master runs on docker.
The following command executes correctly in the shell:
npm --version --location=global

**Comment by Feuer-sturm** [comment]
@cburghardt Can you please post a log ? Which adapter sends your message? Which event triggers the message?

**Comment by cburghardt** [comment]
The message is generated by the admin adapter. It appears every day the same time which means it is triggered from the repository update.

![Bildschirmfoto 2022-11-07 um 19 47 38](https://user-images.githubusercontent.com/839480/200390509-92c4a82e-b815-4e0f-b61b-f9f17bf71fe7.png)
