### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Lapi2000** [ioBroker/ioBroker.admin#1793]
![image](https://user-images.githubusercontent.com/84219740/201461988-3cfc7e83-4786-4b3b-af06-a5ebfcea64b8.png)

![image](https://user-images.githubusercontent.com/84219740/201462016-4b1685fb-38da-4a81-bbca-c5dfdd1e22d3.png)

![image](https://user-images.githubusercontent.com/84219740/201462201-43631921-3d12-4a34-913d-ed05bc2b3b78.png)

Die Console finde ich unter Safari nicht. Aber ein Fehlertext steht unten in Rot.

undefined is not an object (evaluating 'n.toString')
componentDidMount@http://192.168.151.29:8081/static/js/5710.c7a2bbf1.chunk.js:74:106750($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Zs@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:31790($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Gs@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:31546($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Gs@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:31443($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Xc@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:31088($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))bc@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:40967($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))$n@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:40318($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))bs@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:16:35807($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))bs@[native code]($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Ln@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:24:1615($,te)=>r().createElement("div",{key:te},$,r().createElement("br",null))Gn@http://192.168.151.29:8081/static/js/3961.a98ff7ab.chunk.js:24:2009

Unter Windows / chrome
![image](https://user-images.githubusercontent.com/84219740/201462398-6e6a0888-0673-4364-951b-c9400a3df8d3.png)

**Versions:**  
 - Adapter version: <6.2.12>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

![image](https://user-images.githubusercontent.com/84219740/201462131-8197a646-b131-4d48-b981-62e56f70e954.png)

**Additional context**  
Ich hatte auch mal den neusten Adminadapter installiert, brachte aber nur probleme. Nach Recherche wieder auf den 6.2.12 zurückgegangen.

**Comment by Feuer-sturm** [comment]
It is not helpful to create issue based on old admin version. 
Please post in iobroker forum to solve your problem with the stable Version 6 2.23.

If this issue is available in the latent admin version as well we can reopen it.

**Comment by Lapi2000** [comment]
Wie ich bereits geschrieben hatte, bekam ich Probleme mit dem neuen Adminadapter. Und da ich nicht der Einzige war mit diesen Problemen bin ich vor längerer Zeit wieder zurück auf den jetztigen Stand. Dieser hat auch bis vor ein paar Tagen sehr gut funktioniert. Wusste nicht, dass man keine Probleme mit älterne Ständen posten darf! Sorry. Ist ja quasi so als wenn man mit einem älteren Auto in die Werkstatt fahren würde und die einen rausschmeissen würden. Aber Regeln sind Regeln. Danke trotzdem.
