### ISSUE TITLE
Multihost Systems:  which Adapter is installed on which Host?

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#1794]
Hello,
I use iobroker with Multihost ( 5 Clients on different Nodes as LXC), this is running very well, thank you for all work!

My problem is everythime, I want to see on which host is which adapter installed in the Adapters-Tab, this is only shown in the Instances-Tab, so if I need to update an Adapter, I have to change to Instances, look, wich Host is it, than change to Adapters, change the Host, and than I can update.

I know now you said, why can't switch on the Favorite, but than I see only the Adapters on one Host, not on all Hosts :-)
Even I'm in the cli, I can't see a list which Adapter is installed on which host, only all Adapters..

I think it's a nice feature for next Admin / js-controller update.. thanks in advance!
Best regards,
Bernd

**Comment by Apollon77** [comment]
hm.... The adapters tab always shows the adapters and installation status and updates available that match to the host selected on top of the page. And yes "instances "shows which instance runs where.

So should be all there

**Comment by Apollon77** [comment]
@Ilovegym66 ?

**Comment by Ilovegym66** [comment]
Yes can closed :-)
