### ISSUE TITLE
[JSON Config / Feature] add attribute "unique" to table elements

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1801]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would need a new attribute "unique" for table elements specifying that the value stored in a table element is unique over all rows of the table.

This can already be implemented using a validator function. But this is errorprone and I think that uniqueness of table elements is a feature required more than once (at least if the element should be used as any kind of id).

**Comment by klein0r** [comment]
My workaround for unique table entries (field `name` in table should be unique):

```
"validator": "globalData.customApps.filter(app => app.name === data.name).length === 1",
```

**Comment by mcm1957** [comment]
> My workaround for unique table entries (field `name` in table should be unique):
> 
> ```
> "validator": "globalData.customApps.filter(app => app.name === data.name).length === 1",
> ```

Thanks - a good and short solution. I had loops until now :-(
