### ISSUE TITLE
[JSON Config / Feature] support functions stored in script file for default, validator, ...

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1802]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Json config supports js functions at several locations, i.e. as defaultfunction or as validatorfunction. But due to limitations of json these functions must be written as one-liners making them hard to read and write.

Please check whether json confoig could be extended to
-) load a (single?) file containing js functions. It would be sufficient to name it hardcoded jsonConfig.js i.e.
-) let the user enter the name of the function as parameter to the config object and call the function contained in the file

This would allow to write the functions in a readbale way even if they are longer then 2 or 3 words.

**Describe alternatives you've considered**

**Additional context**

**Comment by GermanBluefox** [comment]
You can create a custom json config components and use them in jsonConfig.
Check https://github.com/ioBroker/ioBroker.admin-component-template and this https://github.com/ioBroker/ioBroker.admin-component-easy-access

**Comment by mcm1957** [comment]
I do not see how to use a custom component to use for providing a function to an exsiting component. As an example I would like to write some validation function (which is not a two word expression) to use with a text field. I do not want (and cannot due to ma lack in gui knowledge) programm a complete new grafic component.

Either I do not understand how to use custom components or this solution seems to be too complicated as a simple way to store js functions external to config.json.
