### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by laolaxyz** [ioBroker/ioBroker.admin#1805]
got an error /error in GUI) in Firefox with the request to file an issue in Gihub...

Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. [192.168.1.4:8081](http://192.168.1.4:8081/?#tab-objects)
iobroker.admin@5.3.8 [main.0f2c8246.chunk.js:2:1154757](http://192.168.1.4:8081/static/js/main.0f2c8246.chunk.js)
[2022-11-24T09:16:42.731Z] Try to connect [6.0126dbd0.chunk.js:2:6258764](http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js)
Cannot getRepositoryCompact: timeout [6.0126dbd0.chunk.js:2:6258764](http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js)
[ADAPTERS] Cannot compare "" and "4.0.23" 4 [6.0126dbd0.chunk.js:2:6258764](http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js)
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.1.4:8081/static/js/2.52dbc996.chunk.js". [192.168.1.4:8081:1:1](http://192.168.1.4:8081/?#tab-objects)
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.1.4:8081/static/js/8.1f7b3a0d.chunk.js". [192.168.1.4:8081:1:1](http://192.168.1.4:8081/?#tab-objects)
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.1.4:8081/static/js/3.87af30ac.chunk.js". [192.168.1.4:8081:1:1](http://192.168.1.4:8081/?#tab-objects)
Laden fehlgeschlagen für das <script> mit der Quelle "http://192.168.1.4:8081/static/js/15.948287e5.chunk.js". [192.168.1.4:8081:1:1](http://192.168.1.4:8081/?#tab-objects)
ChunkLoadError: Loading chunk 2 failed.
(error: http://192.168.1.4:8081/static/js/2.52dbc996.chunk.js)
    e http://192.168.1.4:8081/?#tab-objects:1
    Ri http://192.168.1.4:8081/static/js/main.0f2c8246.chunk.js:2
    S http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Zi http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    jl http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Vl http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Cl http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    bl http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Ka http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    unstable_runWithPriority http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Ga http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Ka http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    Za http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    pl http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    enqueueSetState http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    setState http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    t http://192.168.1.4:8081/static/js/main.0f2c8246.chunk.js:2
    u http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    _invoke http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    w http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    r http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
    i http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js:2
[6.0126dbd0.chunk.js:2:6258764](http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js)
Die Ressource von "http://192.168.1.4:8081/static/js/2.52dbc996.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
[192.168.1.4:8081](http://192.168.1.4:8081/?#tab-objects)
Die Ressource von "http://192.168.1.4:8081/static/js/8.1f7b3a0d.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
[192.168.1.4:8081](http://192.168.1.4:8081/?#tab-objects)
Die Ressource von "http://192.168.1.4:8081/static/js/3.87af30ac.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
[192.168.1.4:8081](http://192.168.1.4:8081/?#tab-objects)
Die Ressource von "http://192.168.1.4:8081/static/js/15.948287e5.chunk.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
[192.168.1.4:8081](http://192.168.1.4:8081/?#tab-objects)
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.1.4:8081/static/js/main.0f2c8246.chunk.js
Source-Map-Adresse: main.0f2c8246.chunk.js.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.1.4:8081/static/js/6.0126dbd0.chunk.js
Source-Map-Adresse: 6.0126dbd0.chunk.js.map

​

**Comment by Feuer-sturm** [comment]
@laolaxyz which admin version do you use? What did you do to trigger the error?

**Comment by laolaxyz** [comment]
Admin version 6.2.4. As I tried t refresh the tab where the objects has been shown before. After closing oft he firefox browser everything worked normal. I didn’t see the failure again.

 

Von: Feuer-sturm ***@***.***> 
Gesendet: Donnerstag, 24. November 2022 18:20
An: ioBroker/ioBroker.admin ***@***.***>
Cc: laolaxyz ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI (Issue #1805)

 

@laolaxyz <https://github.com/laolaxyz>  which admin version do you use? What did you do to trigger the error?

**Comment by Feuer-sturm** [comment]
@laolaxyz Please update to Admin 6.2.23 (current stable version). I will close this issue. If you have still problems please open a new issue with logs based on current admin version.
