### ISSUE TITLE
Fehler in der GUI

### ISSUE THREAD

**Issue by Chrischaaan1** [ioBroker/ioBroker.admin#1808]
Gehe ich im ioBroker auf die Objekte kommt immer folgendes Bild
liegt dies eventuell an den shelly´s mit denen ich den Raspi verknüpft habe?

![image](https://user-images.githubusercontent.com/119163040/204131659-10842495-5b8f-44cc-8246-6cbd87b52ed0.png)

**Comment by Feuer-sturm** [comment]
@Chrischaaan1 Verwendetst du den Edge Browser mit aktivierter Übersetzung?

Könnte doppelt zu #1785 sein

**Comment by Feuer-sturm** [comment]
no feedback from @Chrischaaan1. Issue closed
