### ISSUE TITLE
Не могу найти где сменить аватарку

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#181]
![image](https://user-images.githubusercontent.com/11523624/35778048-103e0c94-09eb-11e8-8ef7-987f97be9dab.png)

**Comment by GermanBluefox** [comment]
It is not the bug.
![image](https://user-images.githubusercontent.com/4582016/35809673-b90b8920-0a89-11e8-8d68-43f1dda60b17.png)
