### ISSUE TITLE
[JSON Config] Json Editor not working

### ISSUE THREAD

**Issue by ciddi89** [ioBroker/ioBroker.admin#1810]
**Describe the bug**  
According to the documentation it is possible to add an json editor. But nothing happens. Maybe I forgot something or I'm expecting something different?

**To Reproduce**  
Add the type `json` to json config

**Expected behavior**  
I'm expecting an editor where the user can add own JSON Data.

**Screenshots & Logfiles**  
<img width="291" alt="Screenshot 2022-11-27 at 22 42 08" src="https://user-images.githubusercontent.com/66088020/204161633-1fa203cf-de12-4e6f-aefb-27662718896c.png">

<img width="1561" alt="Screenshot 2022-11-27 at 22 42 22" src="https://user-images.githubusercontent.com/66088020/204161685-b6a11f31-e9a2-43d1-a121-310d013becee.png">

**Versions:**  
 - Adapter version: v6.2.23
 - JS-Controller version: v4.0.23
 - Node version: v16.13.2
 - Operating system: dev-server on MacOs

**Additional context**

**Comment by foxriver76** [comment]
have you tested it in `jsonconfig-demo` @mcm1957 by any chance? Iam currently mainly using `jsonconfig-demo` to fix the existing bugs in json config, so if it is in there let me know, would be a great help.

**Comment by foxriver76** [comment]
fixed in https://github.com/ioBroker/ioBroker.admin/commit/c5455a73190f4509c3dc2559d11175dcd9e2efc6

please note, that there was a bug in docs, the component needs to be of type `jsonEditor`
