### ISSUE TITLE
Verkettetes SSL Zertifikat kann nicht ausgewählt werden

### ISSUE THREAD

**Issue by DerT94** [ioBroker/ioBroker.admin#1811]
Ich wollte eben meine komplette Zertifikatskette in der Admin Oberfläche angeben.
Dabei ist mir aufgefallen, dass ich keine Möglichkeit habe das verkettete Zertifikat auszuwählen.
Unter der Liste der verketteten Zertifikate wird mir nur mein Öffentliches Zertifikat vorgeschlagen
![image](https://user-images.githubusercontent.com/58786605/204378791-cad2d711-dc46-4ab1-80fd-60cd3a86ce66.png)

![image](https://user-images.githubusercontent.com/58786605/204378759-bbe09070-9bc1-4933-804c-1b71751fcec5.png)

**Comment by foxriver76** [comment]
Hm this is as designed, and the GUI states this

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/721680f8-7324-4c54-a6ac-5550602b3517)


and also shows the detected type below

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/a19b0d0f-2d06-4a8a-b738-62319ca9b78b)
