### ISSUE TITLE
Не сквозная сортировка обьектов

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#182]
![image](https://user-images.githubusercontent.com/11523624/35778050-1dad39a4-09eb-11e8-9547-840bf168fe3e.png)

**Comment by GermanBluefox** [comment]
Folders A-Z
Objects A-Z
Objects a-z
Like in Windows Explorer
![image](https://user-images.githubusercontent.com/4582016/35809789-f5563678-0a89-11e8-9bba-2b211c7a3f54.png)
