### ISSUE TITLE
Problem when switch to Logs

### ISSUE THREAD

**Issue by stilicrafter** [ioBroker/ioBroker.admin#1824]
**Describe the bug**  
Switch from the info to log tag ( http://raspberrypi4:8081/#tab-logs )  

**To Reproduce**  
1. Go to 'info
2. Click on 'Logs'
Cant be reproduced after close and reopen

**Expected behavior**  
Open LogPage

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/22886797/205743884-aaa7b5e1-7476-4ba3-90cf-0c43d8fd0440.png)

**Versions:**  
 - JS-Controller version: <js-controller-version> 
 - iobroker -v
    4.0.23

 - Node version: <node-version> 
 - node -v
    v16.16.0

 - Operating system: Raspberry Pi (Raspian)

**Additional context**  
After reboot error is gone

![image](https://user-images.githubusercontent.com/22886797/205744258-9ce64ae5-f8e5-48de-84a1-48c85847ce0d.png)
![image](https://user-images.githubusercontent.com/22886797/205744284-c85e5357-5048-497e-89df-f6a5ce800f4a.png)

![image](https://user-images.githubusercontent.com/22886797/205744353-66abdb07-bcf1-4058-98b7-4a2d96c7b6cf.png)
![image](https://user-images.githubusercontent.com/22886797/205744367-c1173e9c-fe39-418a-8524-61e9979b08e4.png)

**Comment by Feuer-sturm** [comment]
@stilicrafter Which admin version do you use?

**Comment by stilicrafter** [comment]
I ll try to update to the newest version. If problem persists, i ll let you know

**Comment by Feuer-sturm** [comment]
No feedback from @stilicrafter . Issue closed. If it is still relevant, please write a comment here.
