### ISSUE TITLE
[bug] when newly created adapter with tab resists the tab content is not displayed

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.admin#1825]
**Describe the bug**  
If I use the `adapter creator` to create an adapter with tab, nothing is displayed under tab except `Cannot GET /tab.html` Screenshot no.1, although all files are there. In the io-package.json everything is entered as it should Screenshot no.2.
If I now add `"materializeTab": true,` the tab is displayed with the content.
I have made `"materializeTab": true,` out for testing, and it still worked, but after a reinstallation of the adapter without `"materializeTab": true,` it does not work again.

**Screenshots & Logfiles**  
No.1
![image](https://user-images.githubusercontent.com/32600934/205862846-00674b4c-0542-420d-ba19-173a594232db.png)
No.2 
![image](https://user-images.githubusercontent.com/32600934/205863401-126dd3aa-c458-438c-9503-41507a833f7a.png)

**Versions:**  
 - Adapter version: <6.2.23>
 - JS-Controller version: 4.0.23
 - Node version: 16.17.0
 - Operating system: windows (dev-server and test system Linux)

**Comment by Jey-Cee** [comment]
Problem is still there with 6.4.3
