### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by Andronid** [ioBroker/ioBroker.admin#1827]
ChunkLoadError: Loading chunk 3212 failed.
(timeout: http://192.168.178.32:8081/static/js/3212.3a2d2d09.chunk.js)
    j http://192.168.178.32:8081/static/js/main.a2ac1a91.js:3
    e http://192.168.178.32:8081/static/js/main.a2ac1a91.js:1
    e http://192.168.178.32:8081/static/js/main.a2ac1a91.js:1
    ec http://192.168.178.32:8081/static/js/5710.f3fdf624.chunk.js:73
    G http://192.168.178.32:8081/static/js/9526.113dc042.chunk.js:9
    oa http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16
    ra http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16
    Jc http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16
    ml http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16
    ea http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16
    hn http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:14
    ye http://192.168.178.32:8081/static/js/3961.a98ff7ab.chunk.js:16

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@Andronid Which admin version is in use? What did you do to trigger the issue?

**Comment by Andronid** [comment]
V. 6.2.23

**Comment by Andronid** [comment]
Ich habe nochmals alles installiert, aber es lassen sich die Adapter nicht aktualisieren. Es kommt eine Fehlermeldung mit code 25. Langsam verliere ich die Gedult mit dem iobroker

**Comment by Feuer-sturm** [comment]
Issue geschlossen, da es keine weiteren Infos von @Andronid gab. Wenn das issue weiterhin relevant ist, schreib bitte hier einen kurzen Kommentar, dann mache ich das Issue wieder auf.
