### ISSUE TITLE
admin 6.3.2 object icons are gone or in folder 0

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#1829]
![grafik](https://user-images.githubusercontent.com/6681528/207520322-5877bbfe-7190-4fb5-9277-45abf7af2da8.png)

![grafik](https://user-images.githubusercontent.com/6681528/207520337-2ff9d8b5-cc4c-455b-ac91-cd93c8cdffbd.png)

![grafik](https://user-images.githubusercontent.com/6681528/207520352-227c09e5-6d91-46f4-9097-e53b00224dbc.png)

**Comment by Jey-Cee** [comment]
The source path of the icon is  missing "/adapter/adapterName/".
This is only happen on adapter objects with type "meta".
