### ISSUE TITLE
[JSONConfig] selectSendTo with parameter "multiple" not working correctly

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.admin#1830]
**Describe the bug**  
If I define a `selectSendTo` as `multiple` and I choose more than one option, then after saving only the first option is shown and accepted.

Code:
![Xnip2022-12-13_20-45-31](https://user-images.githubusercontent.com/8231359/207602050-dfc503c3-ef9c-492f-8eb8-126fc50b78f0.jpg)

Choice:
![Xnip2022-12-13_20-45-46](https://user-images.githubusercontent.com/8231359/207602241-eee24eea-a4e4-4220-8bd0-d935c7781db1.jpg)

After saving:
![Xnip2022-12-13_20-46-03](https://user-images.githubusercontent.com/8231359/207602314-74ce7720-fbca-48d8-9c8d-e551fc17890e.jpg)

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
Options should be saved as array

**Versions:**  
 - dev-server
 - Adapter version: 6.2.23
 - JS-Controller version: <js-controller-version> 
 - Node version: v18.12.1
 - Operating system: macOS

**Additional context**

**Comment by Schmakus** [comment]
is it being worked on?

**Comment by Schmakus** [comment]
@foxriver76 do you have any ideas?

**Comment by foxriver76** [comment]
I can look into it

**Comment by foxriver76** [comment]
@Schmakus do you have a adapter which is using it? Would make it easier for me to test.

**Comment by Schmakus** [comment]
https://github.com/Schmakus/ioBroker.lightcontrol

Branch: v1.0.0

**Comment by foxriver76** [comment]
thanks

**Comment by foxriver76** [comment]
fyi: not the problem but this function is not valid https://github.com/Schmakus/ioBroker.lightcontrol/blob/a1e3bb0e4d784561dd636d5d26eb4c3cb129a803/admin/jsonCustom.json#L182 @Schmakus

**Comment by foxriver76** [comment]
It seems like Custom Components are currently not able to save array data. 

Unfortunately it is not that easy to trace down to the origin, I get it saving the array data, but then whenever I save with `enabled: true` some other mechanism is overriding the object with `enabled: false`.

**Comment by foxriver76** [comment]
Okay, its the adapter itself who is deactivating the custom settings, so on admin side everything works

```
 [ buildStateDetailsArray ] Light group "Wohnzimmer,Bongzimmer" was deleted by the user in the instance settings! LightControl settings will be deactivated for this StateID: 0_userdata.0.Neuer_Zustandsdfasf)
 ```

fixed in https://github.com/ioBroker/ioBroker.admin/commit/65ba53dec9811a5543152f14080a71e144fccd46

**Comment by Schmakus** [comment]
@foxriver76 ok, you mean, LightControl do that itself? will check the method. Usually, the adapter should deactivate the custom settings only the user delete the group in instance settings?!

**Comment by foxriver76** [comment]
You still need a new admin version for the multiple support. But the issue which I was investigating afterwards was just due to the light control logic

**Comment by foxriver76** [comment]
It can be that I was not using this adapter in anyway it should be used so probably it is not a problem in real environments, just used the box to test if selection is saved and this works now with the next admin version
