### ISSUE TITLE
Color of states with role 'button'

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.admin#1832]
A state got a definition like:
```
"_id": "update",
  "type": "state",
  "common": {
    "role": "button",
    "name": "Manually trigger an update",
    "type": "boolean",
    "read": false,
    "write": true,
    "def": false
  },
```

The role `button` is easy to use for trigger something manually, but after first use the button gets a deep red color which might lead misunderstandings because this means `true` w/o `ack`. A button is only `true` when it is pushed, else it is `false`.

Please consider to not coloring the button or change its behavior to get a light red color after use.

**Comment by Apollon77** [comment]
My proposal is to leabv the color grey ... so also no light red or such

**Comment by mcm1957** [comment]
@Apollon77 
As discussed shortly at telegramm channel  the button does NOT fall back to flse typically. 

As farcas I understood theres no rule that the adapter should reset it to false. Vis could do it. Admin does not reset the button too 

So when used at admin object interface th2 button typically dtays at value tru with ack false.

For further discussion I suggest using telegram or an new topic at forum if prferred.

**Comment by Apollon77** [comment]
@mcm1957 No, noone should reset it to "false" ... but yes all as discussed. It is not easy. Formally "read=false" means that there is no meaningfil value and a value has no meaning ... so best Admin ignores the value and ack and just shows a "grey Button icon" (when not expert mode)
