### ISSUE TITLE
adapter problem

### ISSUE THREAD

**Issue by Redfighter181** [ioBroker/ioBroker.admin#1833]
**Describe the bug**
I can't install and update adapters.
**To Reproduce**
1. Click on System Preferences -> Repositories Enter:
beta | http://download.iobroker.net/sources-dist-latest.json
2. Click on save and close
3. Click on Adapters
4. See error:
TypeError: Cannot read properties of undefined (reading 'beta')
at Adapters.jsx:1744:38
at Array.map (<anonymous>)
at Zs.render (Adapters.jsx:1743:70)
at Wi (react-dom.production.min.js:204:189)
at Rs (react-dom.production.min.js:203:149)
at oa (react-dom.production.min.js:292:172)
at ra (react-dom.production.min.js:280:389)
at Jc (react-dom.production.min.js:280:320)
at ml (react-dom.production.min.js:280:180)
at iu (react-dom.production.min.js:271:88)
at bs (react-dom.production.min.js:268:429)
at Ln (scheduler.production.min.js:13:203)
at MessagePort.Gn (scheduler.production.min.js:14:128)

5. Click on System Preferences - Repositories
6. List is gone
____________________

1. Click on System Preferences -> Repositories Enter:
stable | http://download.iobroker.net/sources-dist.json
2. Click on Save and close
3. Click on Adapters
4. Only installed adapters are shown and no available updates.
5. Click on System Preferences - Repositories
6. List is gone

**Screenshots & Log Files**
![Unbenannt4](https://user-images.githubusercontent.com/70227047/207897947-e8f03482-6788-4985-88e9-cc49674379ca.PNG)

![Unbenannt5](https://user-images.githubusercontent.com/70227047/207899105-f4cb324d-dc02-4caa-8992-23e5d8679d04.PNG)

![Unbenannt1](https://user-images.githubusercontent.com/70227047/207898201-758b6ece-48db-4249-8ab4-8156c3bdccc5.PNG)

![Unbenannt](https://user-images.githubusercontent.com/70227047/207898179-10541873-c8e8-4c95-a2f1-e378f790a162.PNG)

![Unbenannt2](https://user-images.githubusercontent.com/70227047/207898238-20419aca-8f9c-4950-bb76-3b853e9cbef1.PNG)

**Versions:**
  - Adapter version: admin.0 v 6.2.17
  - JS controller version: 4.0.23
  - Node version: 12.22.12
  - Operating system: Raspbian

**Comment by Grothesk242** [comment]
Adapter version: admin.0 v 6.2.17
Node version: 12.22.12
both versions are more than aged. Upgrade to supported versions first.

**Comment by Feuer-sturm** [comment]
@Grothesk242 please Update to admin 6.2.23
And npm 16 is currently recommended

**Comment by Redfighter181** [comment]
I have now
node: 16.18.1
npm: 8.19.2

Then I wanted to update iobroker:
pi@ibroker:/opt/iobroker $ sudo iobroker stop
pi@ibroker:/opt/iobroker $ sudo iobroker update
Error: Object "system.repositories" not found

I also ran the "ioBroker installation fixer" and got an error:
![Unbenannt](https://user-images.githubusercontent.com/70227047/207984528-bb1b1cf5-d249-40e0-aad1-d79d4c6f4668.PNG)

**Comment by Feuer-sturm** [comment]
@Redfighter181 the fastet war to solve your problem is creating a topic in ioBroker forum. There are a lot of users who can support you.

**Comment by Apollon77** [comment]
Additionally this is no topic for Admin ... but in fact I adjusted the jsonl fixer to handle this case. Please try "iob fix" again - would be good to see the output afterwards please (from Step #3 is enough)

**Comment by Redfighter181** [comment]
> Additionally this is no topic for Admin ... but in fact I adjusted the jsonl fixer to handle this case. Please try "iob fix" again - would be good to see the output afterwards please (from Step #3 is enough)

Step 3 causes problems. The original problem still persists:
![Unbenannt](https://user-images.githubusercontent.com/70227047/208113986-cfe95082-b105-4432-b21e-1b9165f10947.PNG)

**Comment by Apollon77** [comment]
Ok seems not my day today ... another try please

**Comment by Redfighter181** [comment]
> Ok scheint heute nicht mein Tag zu sein ... versuchen Sie es bitte noch einmal

No problem, I do as often as you want.
![Unbenannt](https://user-images.githubusercontent.com/70227047/208138330-ae29369b-3046-4b2a-abc6-df2da8fa3433.PNG)

**Comment by Apollon77** [comment]
But then we are through ... worked and fixed the DB file

**Comment by Redfighter181** [comment]
But I still have my (Error: Object "system.repositories" not found) problem.
Maybe someone else has an idea, otherwise I'll try the ioBroker forum.
Thanks

**Comment by Apollon77** [comment]
Then please try "iob setup first" and then update repository in Admin  on Adapter tab with the "arrows in circle" button

**Comment by Apollon77** [comment]
But one thing: Maybe do a Filesystem check (and backup) ... if the jsonl file got corrupted then it is sdcard/filesystem or you had a bad crash

**Comment by mcm1957** [comment]
@Apollon77 
Not quite sure but I think this issue could be closed.
