### ISSUE TITLE
[6.3.2] Update to version 6.3.2 kills the admin instance at all

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.admin#1837]
HI, my current production environment looks like this:

iobroker docker with latest docker image 7.2.0. Standard installation, no tweaking or extra tricks.
Adapters installed:

- system.adapter.admin                   : admin          - v6.2.23                                                                                                 
- system.adapter.alias-manager           : alias-manager  - v1.2.4                                                                                                  
- system.adapter.backitup                : backitup       - v2.5.9                                                                                                  
- system.adapter.bosch-ebike             : bosch-ebike    - v0.0.3                                                                                                  
- system.adapter.comfoair                : comfoair       - v1.1.5                                                                                                  
- system.adapter.device-watcher          : device-watcher - v2.0.3                                                                                                  
- system.adapter.discovery               : discovery      - v3.1.0                                                                                                  
- system.adapter.echarts                 : echarts        - v1.0.12                                                                                                 
- system.adapter.feiertage               : feiertage      - v1.1.0                                                                                                  
- system.adapter.history                 : history        - v2.2.0                                                                                                  
- system.adapter.hs100                   : hs100          - v2.1.2                                                                                                  
- system.adapter.icons-material-png      : icons-material-png - v0.1.0                                                                                              
- system.adapter.icons-mfd-png           : icons-mfd-png  - v1.1.0                                                                                                  
- system.adapter.influxdb                : influxdb       - v3.1.8                                                                                                  
- system.adapter.info                    : info           - v1.9.19                                                                                                 
- system.adapter.iqontrol                : iqontrol       - v2.0.0                                                                                                  
- system.adapter.javascript              : javascript     - v6.0.3                                                                                                  
- system.adapter.openknx                 : openknx        - v0.2.5                                                                                                  
- system.adapter.ping                    : ping           - v1.5.3                                                                                                  
- system.adapter.scenes                  : scenes         - v2.3.9                                                                                                  
- system.adapter.schoolfree              : schoolfree     - v1.0.1                                                                                                  
- system.adapter.simple-api              : simple-api     - v2.7.0                                                                                                  
- system.adapter.socketio                : socketio       - v4.2.0                                                                                                  
- system.adapter.tesla-motors            : tesla-motors   - v1.3.1                                                                                                  
- system.adapter.tr-064                  : tr-064         - v4.2.16                                                                                                 
- system.adapter.vis                     : vis            - v1.4.15                                                                                                 
- system.adapter.web                     : web            - v4.3.0                                                                                                  

When updating the admin to v6.3.2, the iobroker istance becomes unapproachable. Can't connect anymore via web interface. When restarting the container, start fails with the log "no admin found" or something like this. admin v6.3.3 not tested.

I tested a fresh installation of iobroker with image v7.2.0 which comes with admin v6.2.23 as well. An update of the admin to 6.3.2 works without an issues then. So the issue seem to be (a) a regression with another adapter or (b) an problem with the existing data from the production environment.

Before I go the hard way of testing all extended adapter combinations, I wonder if there is some troubleshooting advice for narrowing down the problem to its root a bit more quicker (and easier).

So happy to get your advice.

- Breisgauer

**Comment by Apollon77** [comment]
Please provide logs ... 6-3-2 is used by throusands of users already ...

**Comment by Breisgauer** [comment]
```
took a moment to figure out how to find the logs without having UI running. Here we go

2022-12-17 23:53:32.100  - [32minfo[39m: host.iobroker-tst iobroker upgrade admin@6.3.3
2022-12-17 23:53:33.530  - [32minfo[39m: host.iobroker-tst iobroker Update admin from @6.2.23 to @6.3.3
2022-12-17 23:53:33.543  - [32minfo[39m: host.iobroker-tst iobroker host.iobroker-tst Adapter "system.adapter.admin.0" is stopped.
2022-12-17 23:53:33.556  - [32minfo[39m: admin.0 (576) Adapter is disabled => stop
2022-12-17 23:53:33.571  - [32minfo[39m: admin.0 (576) terminating http server on port 8081
2022-12-17 23:53:33.587  - [32minfo[39m: host.iobroker-tst "system.adapter.admin.0" disabled
2022-12-17 23:53:33.589  - [32minfo[39m: host.iobroker-tst stopInstance system.adapter.admin.0 (force=false, process=true)
2022-12-17 23:53:33.606  - [32minfo[39m: admin.0 (576) terminating
2022-12-17 23:53:33.607  - [32minfo[39m: admin.0 (576) Terminated (NO_ERROR): Without reason
2022-12-17 23:53:33.608  - [32minfo[39m: admin.0 (576) Got terminate signal TERMINATE_YOURSELF
2022-12-17 23:53:33.631  - [32minfo[39m: host.iobroker-tst stopInstance system.adapter.admin.0 send kill signal
2022-12-17 23:53:34.275  - [32minfo[39m: host.iobroker-tst instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
2022-12-17 23:53:34.276  - [32minfo[39m: host.iobroker-tst iobroker NPM version: 8.19.2Installing iobroker.admin@6.3.3... (System call)
2022-12-17 23:53:38.380  - [31merror[39m: host.iobroker-tst iobroker host.iobroker-tst Cannot install iobroker.admin@6.3.3: 217
2022-12-17 23:53:39.403  - [32minfo[39m: host.iobroker-tst iobroker exit 25

```
Tried to restart the docker instance which fails. The log from the start phase:
![log](https://user-images.githubusercontent.com/40452508/208269173-ece0c53b-7b74-4a45-8ada-d9e7b5009729.JPG)

**Comment by Apollon77** [comment]
error 217 ... something is with your npm tree ... try to run "iob upgrade admin --debug"

**Comment by Breisgauer** [comment]
done:

![image](https://user-images.githubusercontent.com/40452508/208318363-96bca92b-3b24-4f70-857f-2dcdb8a74d3d.png)

npn log:
```

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@8.19.2
2 info using node@v16.18.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 7ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 16ms
10 timing config:load:file:/opt/iobroker/.npmrc Completed in 2ms
11 timing config:load:user Completed in 3ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:validate Completed in 1ms
15 timing config:load:credentials Completed in 1ms
16 timing config:load:setEnvs Completed in 2ms
17 timing config:load Completed in 38ms
18 timing npm:load:configload Completed in 39ms
19 timing npm:load:mkdirpcache Completed in 2ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install iobroker.admin@6.3.3
22 verbose argv "install" "--save-exact" "iobroker.admin@6.3.3"
23 timing npm:load:setTitle Completed in 2ms
24 timing config:load:flatten Completed in 6ms
25 timing npm:load:display Completed in 8ms
26 verbose logfile logs-max:10 dir:/opt/iobroker/.npm/_logs
27 verbose logfile /opt/iobroker/.npm/_logs/2022-12-18T20_40_49_085Z-debug-0.log
28 timing npm:load:logFile Completed in 10ms
29 timing npm:load:timers Completed in 1ms
30 timing npm:load:configScope Completed in 0ms
31 timing npm:load Completed in 63ms
32 timing arborist:ctor Completed in 2ms
33 silly logfile start cleaning logs, removing 4 files
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 1009ms
36 timing idealTree:userRequests Completed in 8ms
37 silly idealTree buildDeps
38 silly fetch manifest iobroker.admin@6.3.3
39 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/iobroker.js-controller
40 http fetch GET 200 https://registry.npmjs.org/iobroker.admin 1397ms (cache updated)
41 silly placeDep ROOT iobroker.admin@6.3.3 REPLACE for: iobroker.inst@3.0.0 want: 6.3.3
42 silly fetch manifest @iobroker/socket-classes@^1.0.2
43 silly fetch manifest axios@^1.2.1
44 silly fetch manifest semver@^7.3.8
45 silly fetch manifest ws@^8.11.0
46 http fetch GET 200 https://registry.npmjs.org/@iobroker%2fsocket-classes 202ms (cache updated)
47 http fetch GET 200 https://registry.npmjs.org/semver 205ms (cache updated)
48 http fetch GET 200 https://registry.npmjs.org/ws 212ms (cache revalidated)
49 http fetch GET 200 https://registry.npmjs.org/axios 218ms (cache revalidated)
50 timing idealTree:#root Completed in 1659ms
51 silly fetch manifest bufferutil@^4.0.1
52 http fetch GET 200 https://registry.npmjs.org/bufferutil 42ms (cache revalidated)
53 silly fetch manifest utf-8-validate@^5.0.2
54 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 45ms (cache revalidated)
55 silly placeDep ROOT @iobroker/socket-classes@1.0.2 OK for: iobroker.admin@6.3.3 want: ^1.0.2
56 silly placeDep node_modules/iobroker.admin axios@1.2.1 OK for: iobroker.admin@6.3.3 want: ^1.2.1
57 silly placeDep ROOT semver@7.3.8 REPLACE for: iobroker.admin@6.3.3 want: ^7.3.8
58 silly placeDep node_modules/iobroker.admin ws@8.11.0 OK for: iobroker.admin@6.3.3 want: ^8.11.0
59 silly fetch manifest passport@^0.6.0
60 silly fetch manifest axios@^0.27.2
61 silly fetch manifest form-data@^4.0.0
62 http fetch GET 200 https://registry.npmjs.org/passport 54ms (cache revalidated)
63 http fetch GET 200 https://registry.npmjs.org/form-data 55ms (cache revalidated)
64 timing idealTree:node_modules/iobroker.admin Completed in 178ms
65 silly placeDep node_modules/@iobroker/socket-classes axios@0.27.2 OK for: @iobroker/socket-classes@1.0.2 want: ^0.27.2
66 silly placeDep node_modules/@iobroker/socket-classes passport@0.6.0 OK for: @iobroker/socket-classes@1.0.2 want: ^0.6.0
67 timing idealTree:node_modules/@iobroker/socket-classes Completed in 6ms
68 timing idealTree:node_modules/semver Completed in 1ms
69 silly placeDep node_modules/@iobroker/socket-classes form-data@4.0.0 OK for: axios@0.27.2 want: ^4.0.0
70 timing idealTree:node_modules/@iobroker/socket-classes/node_modules/axios Completed in 4ms
71 timing idealTree:node_modules/@iobroker/socket-classes/node_modules/form-data Completed in 0ms
72 timing idealTree:node_modules/@iobroker/socket-classes/node_modules/passport Completed in 1ms
73 silly placeDep node_modules/iobroker.admin form-data@4.0.0 OK for: axios@1.2.1 want: ^4.0.0
74 timing idealTree:node_modules/iobroker.admin/node_modules/axios Completed in 3ms
75 timing idealTree:node_modules/iobroker.admin/node_modules/form-data Completed in 0ms
76 timing idealTree:node_modules/iobroker.admin/node_modules/ws Completed in 0ms
77 timing idealTree:buildDeps Completed in 1856ms
78 timing idealTree:fixDepFlags Completed in 15ms
79 timing idealTree Completed in 2908ms
80 timing reify:loadTrees Completed in 2911ms
81 timing reify:diffTrees Completed in 38ms
82 silly reify mark retired [ '/opt/iobroker/node_modules/iobroker.admin' ]
83 silly reify mark retired [
83 silly reify   '/opt/iobroker/node_modules/semver',
83 silly reify   '/opt/iobroker/node_modules/.bin/semver'
83 silly reify ]
84 silly reify mark retired [ '/opt/iobroker/node_modules/@iobroker/socket-classes' ]
85 silly reify moves {
85 silly reify   '/opt/iobroker/node_modules/iobroker.admin': '/opt/iobroker/node_modules/.iobroker.admin-TtUA2igk',
85 silly reify   '/opt/iobroker/node_modules/semver': '/opt/iobroker/node_modules/.semver-n8m5lQuN',
85 silly reify   '/opt/iobroker/node_modules/.bin/semver': '/opt/iobroker/node_modules/.bin/.semver-LPDaIsIH',
85 silly reify   '/opt/iobroker/node_modules/@iobroker/socket-classes': '/opt/iobroker/node_modules/@iobroker/.socket-classes-bdAChYMK'
85 silly reify }
86 timing reify:rollback:retireShallow Completed in 3ms
87 timing command:install Completed in 2977ms
88 verbose stack Error: ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/iobroker.admin' -> '/opt/iobroker/node_modules/.iobroker.admin-TtUA2igk'
89 verbose cwd /opt/iobroker
90 verbose Linux 4.4.180+
91 verbose node v16.18.1
92 verbose npm  v8.19.2
93 error code ENOTEMPTY
94 error syscall rename
95 error path /opt/iobroker/node_modules/iobroker.admin
96 error dest /opt/iobroker/node_modules/.iobroker.admin-TtUA2igk
97 error errno -39
98 error ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/iobroker.admin' -> '/opt/iobroker/node_modules/.iobroker.admin-TtUA2igk'
99 verbose exit -39
100 timing npm Completed in 3331ms
101 verbose unfinished npm timer reify 1671396049436
102 verbose unfinished npm timer reify:retireShallow 1671396052394
103 verbose code -39
104 error A complete log of this run can be found in:
104 error     /opt/iobroker/.npm/_logs/2022-12-18T20_40_49_085Z-debug-0.log
```
restart of the iobroker container fails with error:

![image](https://user-images.githubusercontent.com/40452508/208318763-08b60dc8-8a76-4cd2-93e4-896a0ca0d0bf.png)

**Comment by Apollon77** [comment]
Please see https://forum.iobroker.net/topic/57337/fehler-25-oder-217-bei-adapter-install-update-mit-npm8
