### ISSUE TITLE
Hosts: Warnung der freie Speicherplatz auf der Festplatte ist niedrig scheint falsch zu sein

### ISSUE THREAD

**Issue by Eistee82** [ioBroker/ioBroker.admin#1838]
Fehlermeldung scheint falsch zu sein wenn 17GB freier Festplattenspeicher angezeigt werden.

![iobspeicher](https://user-images.githubusercontent.com/1881217/207978269-074e8eed-c35f-4b87-84d2-257c87d4b09c.png)

```
root@iobroker:~# df -h
Filesystem                  Size  Used Avail Use% Mounted on
fasttank/subvol-905-disk-0   32G   16G   17G  48% /
none                        492K  4.0K  488K   1% /dev
udev                         47G     0   47G   0% /dev/ttyACM0
tmpfs                        63G     0   63G   0% /dev/shm
tmpfs                        26G  104K   26G   1% /run
tmpfs                       5.0M     0  5.0M   0% /run/lock
```

**Comment by foxriver76** [comment]
Es kann edge cases geben, diese werden in der nächjsten Version gefixt sein. Grundsätzlich wird allerdings das Limit angezogen, dass der User in `system.host.<hostname>.diskWarning` konfiguriert hat. Evtl hast du da auch etwas unpassendes drin stehen?

**Comment by Eistee82** [comment]
Wo finde ich das?
system.host.<hostname>.diskWarning

**Comment by foxriver76** [comment]
Ist ein State unter Objekte wenn du Expertenmodus an hast.

**Comment by Eistee82** [comment]
Sieht ok aus oder? Die Warnung bekomme ich dennoch.
![image](https://github.com/ioBroker/ioBroker.admin/assets/1881217/0d60f7d5-5f8a-4b6c-8091-42652124ab40)

**Comment by mcm1957** [comment]
Ähmm
Wenn ich die description des Stats diskWarning richtig lese, gibt dieser State den Schwellwert an der UNTERSCHRITTEN werden muss um den Alarm auszulösen. Und weniger als 90% FREI hast du ja ...

Trag mal 20%, 10% oder so ein ...

**Comment by Eistee82** [comment]
Hab da meines Wissens aber nie was verändert. Mit 10% wird keine Warnung mehr angezeigt.

**Comment by foxriver76** [comment]
Ist genau wie Martin sagt
