### ISSUE TITLE
missing values colomn on mobile browser 

### ISSUE THREAD

**Issue by rtwl21** [ioBroker/ioBroker.admin#1839]
I really miss the values colomn on my mobile phone in the object tab. do you see any chance to bring them back?

(Desktop Mode is not an option for me (my device) because of the small font or have to swipe left-right-left-right when zooming in)

**Comment by Feuer-sturm** [comment]
Duplicate to #1625

**Comment by rtwl21** [comment]
In 1625 geht es doch um den Browser am PC. Jedoch hat es nichts, oder nur bedingt mit dem mobilen Browser zu tun, oder?

**Comment by Feuer-sturm** [comment]
@rtwl21 Hi, in dem issue #1625 geht es um beide Ansichten. Am PC aber auch auf dem mobilen Endgerät. Du findest dort mehrere Beiträge, wo sich einige User aucch eine andere Bedienung auf dem Handy wünschen. Häng dich am besten an das issue mit dran, bzw. Daumen bei den entsprechenden Beiträgen nach oben, welche für dich wichtig sind.
