### ISSUE TITLE
Admin 6.3.5 - cannot find npm version

### ISSUE THREAD

**Issue by Siggi0904** [ioBroker/ioBroker.admin#1845]
Hallo,

auch mit der neuen Version 6.3.5 tritt der Fehler mit der Erkennung der NPM-Version weiterhin auf.

Aus dem heutigen log:
`admin.0 | 2022-12-24 12:41:07.420 | warn | Cannot get current npm version: Cannot find npm version`

Könnte man die Warnmeldung erweitern, dass angezeigt wird, ob es ein Netzwerk-Problem bzw. nicht erreichbare Server war?

**Comment by Diginix** [comment]
Was heißt denn weiterhin? Gab es dazu schon ein issue welches auch geschlossen wurde.
6.3.5 hat nur ein Fix für die nodejs Versionserkennung: #1834
Die Warnung in deinem Log ist aber was anderes.

**Comment by Siggi0904** [comment]
Okay, ich dachte das wär das Gleiche.

Ich habe nicht verfolgt, seit welcher Version das aufgetreten ist.
Aber ich würd' vermuten mit der 6.3.4 oder der Aktualisierung von node.js auf Version 16.

Ich kann es aber nicht genau sagen.

Aus welchem Check wird denn die Warnung generiert?
Dann kann man das ggf. nachvollziehen. Falls die Warnung erweitert wird, könnte man es auch dort sehen.

**Comment by Feuer-sturm** [comment]
@Siggi0904 welche nodejs und npm Version hast du installiert?

**Comment by Siggi0904** [comment]
NPM: 8.19.2
Node.js: 16.18.1

letztes stable

**Comment by foxriver76** [comment]
Passiert das noch @Siggi0904?

**Comment by Siggi0904** [comment]
Hi, ja einmal täglich.
Kann man im code sehen, dass die Abfrage einmal täglich erfolgt?

Kann ich sehen welcher Befehl ausgeführt wird, um diesen auf der console zu testen?

**Comment by Siggi0904** [comment]
Nein, läuft in einer VM auf Proxmox.
Falls der Fix funktioniert, wär das super.

Gilt der Fix auch für die npm 6.6.0 vom Admin Adapter?
Denn diese Version sollte ja auch zeitnah ins Stable gehen.

Der Aufruf auf der cmd funktioniert aber:

`mario@iobroker:~$ npm --version --location=global
 
9.5.1

mario@iobroker:~$
`
