### ISSUE TITLE
Add type timePicker to jsonConfig

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#1846]
**Is your feature request related to a problem? Please describe.**
In the adapter solarviewdatareader I used a timepicker for configuration. In the new jsonConfig environment I cannot found
a timepicker. Please add. 

**Describe the solution you'd like**
Timepicker behaviour as in the solarviewdatareader adapter.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by foxriver76** [comment]
IT is existing https://github.com/mcm1957/ioBroker.jsonconfig-demo/blob/7995b12f33a161383078ace186c11e74b867d9af/admin/jsonConfig.json5#L651
