### ISSUE TITLE
[JSON Config] scheme failure: Property alsoDependsOn is not allowed. (autocompleteSendTo)

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.admin#1847]
**Describe the bug**  

Ich habe ein Problem mit customConfig. Ich möchte in Abhängigkeit eines anderen Feldes ein autocompleteSendTo ausführen. Problem ist, dass zu Beginn das DropDown „group“ noch leer ist. Somit habe ich ein undefined. Wie integriere ich ein alsoDependsOn richtig? Quasi, wenn ich im DropDown [group] einen Wert auswähle, dass ein weiteres onMessage für description ausgeführt wird?

**To Reproduce**  
2. Click on '...'

**Expected behavior**  
Nach Auswahl eines Wertes im Drop-down, ein erneutes SendTo eines anderen Feldes. 

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/8231359/209870429-b9ccf3bf-5245-4ba4-9b17-eaf675bd64ae.jpeg)

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Schmakus** [comment]
is it being worked on?

**Comment by Schmakus** [comment]
@foxriver76 Maybe, you have a solution for that? say if it is an usage error or enhancement or bug?

**Comment by foxriver76** [comment]
before I look deep into it, can you please try if this works

```
		"description": {
			"type": "autocompleteSendTo",
			"command": "LightName",
                        "alsoDependsOn": ["group"],
			"jsonData": "{\"LightGroups\": ${JSON.stringify(data.group)}}",
			"freeSolo": true,
			"label": "Name of the Light",
			"help": "e.g. FloorSpots, Spotlights, Wallpanel, ...",
			"sm": 3,
			"md": 3,
			"lg": 3,
			"hidden": "data.type === 'sensor'"
		},
```

**Comment by Schmakus** [comment]
> "alsoDependsOn": ["group"],

It works! but scheme failure: ```Property alsoDependsOn is not allowed.```

**Comment by foxriver76** [comment]
should be fixed
