### ISSUE TITLE
Admin 6.3.5 Adapter baut massiv States auf

### ISSUE THREAD

**Issue by weindler** [ioBroker/ioBroker.admin#1848]
Nach der folgenden Fehlermeldung bin ich auf die Suche gegangen.

`<html><body>

admin.0 | 2022-12-29 14:43:03.806 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)
-- | -- | -- | --

</body>
</html>`

Nach 10 Minuten mit der Version 6.3.5 erscheint die obige Fehlermeldung, die States gehen über 3400
![admin 6 3 5](https://user-images.githubusercontent.com/41335851/209964439-cb2a6f04-0b14-4792-8dcf-2bedea28e2d0.jpg)

Nach 10 Minuten in der Version 6.3.4 erscheint die obrige Fehlermeldung nicht die states stehen bei ca. 154

![admin 6 3 4](https://user-images.githubusercontent.com/41335851/209964532-d192b297-adf0-448d-91bc-4950ca79ff6d.jpg)

Update auf 6.3.5 erfolgte von mir vor 2 Tagen und genau da gingen die INfo Meldungen zu den unsubscribes states los.

Mehr Infos zu meinem Problem findet man auch hier

[https://forum.iobroker.net/topic/61486/admin-6-3-5-unsubscribe-from-all-states/35?_=1672322153332](url)

**Comment by Steff42** [comment]
Hmm....,
.... kann ich nicht bestätigen:

![image](https://user-images.githubusercontent.com/35137293/210101544-f4e7cef7-2770-49fe-8b4e-e36828b703b1.png)

Node: V16.16.0 / NPM V8.11.0
JSC V4.0.24 / JSE V6.1.4

**Comment by Diginix** [comment]
Bei mir auch alles ruhig mit 6.3.5 und ca. 70 Javascripten. Die Ursache scheint also woanders zu liegen.

**Comment by Feuer-sturm** [comment]
User hat sein System neu aufgesetzt https://forum.iobroker.net/topic/61486/admin-6-3-5-unsubscribe-from-all-states/45 und seitdem ist wohl alles i.O.
Issue geschlossen.
