### ISSUE TITLE
Pulldown für "Bestimmte Version installieren" an "komischer Stelle"

### ISSUE THREAD

**Issue by eumats** [ioBroker/ioBroker.admin#185]
Pulldown für "Bestimmte Version installieren" an "komischer Stelle" (siehe Anhang).

Getestet mit Firefox und Safari

![admin](https://user-images.githubusercontent.com/32279788/35779475-ea279218-09cd-11e8-99dc-f4be6dba9e7b.jpg)

**Comment by Apollon77** [comment]
Welche Admin Version hast du genutzt?
Log sollte wenn ich recht entsinne gefixt sein. Am besten bitte auch nur ein issue pro Fehler/problem

**Comment by eumats** [comment]
3.1.11. gekommen bin ich von 2.0.11

Das aufsplitten werde machen.

**Comment by eumats** [comment]
Issue mit 2 Einträgen aufgeteilt in #185 und #188

**Comment by GermanBluefox** [comment]
Fixed in 3.2.1
