### ISSUE TITLE
Fehler in der GUI! - Immer bei Klick auf Objekte ....

### ISSUE THREAD

**Issue by Jokl46** [ioBroker/ioBroker.admin#1850]
Um den Fehler zu reproduzieren muss ich im iobroker einfach auf den Button "Objekte" klicken.

![image](https://user-images.githubusercontent.com/121661658/210045949-46fe5cb4-547c-4801-bde7-3956b4b3800b.png)

**Comment by Feuer-sturm** [comment]
@Jokl46 welche Admin Version hast du installiert? 
Welchen Browser verwendest du?

**Comment by Feuer-sturm** [comment]
@Jokl46 falls du denn Edge Browser verwendest mit aktivierter Übersetzung, dann ist es diese Problem https://github.com/ioBroker/ioBroker.admin/issues/1785
In dem Fall hilft nur die Übersetzung abzuschalten

**Comment by Jokl46** [comment]
Vielen Dank an alle!!!! Also mit Firefox kommt der Fehler schon mal nicht. Auch wenn ich wie beschrieben die automatische Übersetzung ausschalte funktioniert auf den ersten Blick alles..... Danke und euch allen einen guten Rutsch!

**Comment by Feuer-sturm** [comment]
Danke für die Rückmeldung und ich wünsche dir auch einen guten Rutsch

**Comment by Apollon77** [comment]
@Jokl46 Im anderen browser mal cache und local szorage gelöscht? Das resettet alle settings
