### ISSUE TITLE
History Data Point Viewer messes up shown data 

### ISSUE THREAD

**Issue by lxffm** [ioBroker/ioBroker.admin#1860]
**Describe the bug**  
Sometimes if you want to view the recorded data in a data point, the table is shown messed up. (see Screenshot) 
<img width="1227" alt="Screenshot 2023-01-01 at 16 07 44" src="https://user-images.githubusercontent.com/3496522/210175646-d0f0891a-97e7-4d8c-a9cc-592a7c212b03.png">

**To Reproduce**  
1. Go to a datapoint which has recorded history data
2. Find a time setting which is reproducing the error (not clear pattern found yet)

**Expected behavior**  
The table is intact showing the correct data

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.2.4
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: linux (RasPi)

**Additional context**  
Maybe it's related to my data so I exported you the data. The time setting "last 12 months" lead to the issue, whereas "this year" which only contains one day, shows the table correct.

[power consumption last day.csv](https://github.com/ioBroker/ioBroker.history/files/10328985/power.consumption.last.day.csv)

**Comment by lxffm** [comment]
@Apollon77 Admin Version is 6.3.5 but I can observe this behavior for a couple of versions already. 
I exported the data from the screen being shown.

Also other datapoints are suffering from this issue.
First I thought it might be related to the long floats in my energy consumption datapoints. But I also found the issue in some sensor data from homematic were it only stores a couple of minutes. 

screens attached
<img width="1220" alt="Screenshot 2023-01-01 at 18 03 36" src="https://user-images.githubusercontent.com/3496522/210179113-d30aaa15-5b23-4325-8a0e-d19c10c74a70.png">
<img width="1222" alt="Screenshot 2023-01-01 at 18 05 32" src="https://user-images.githubusercontent.com/3496522/210179117-f54aa2be-5c24-487e-b509-2a02878d8caa.png">

**Comment by lxffm** [comment]
Seems like it's writing the first value into the table header somehow.

**Comment by ScumbagSteve** [comment]
> I know a very similar behavior, which occurs whenever you use more than one history instance. If you start with an instance in the view that contains no data and then switch to an instance with data, the columns are shifted. 

I can confirm this bug and also the reproduction steps, @Marc-Berg has mentioned.
Would be good to get a fix for it, the bug is around for quite a while already.

**Comment by foxriver76** [comment]
will be fixed in the next version of admin
