### ISSUE TITLE
History data viewer is not loading data until time period is been changed

### ISSUE THREAD

**Issue by lxffm** [ioBroker/ioBroker.admin#1861]
**Describe the bug**  
If you open the history data point viewer in continously keeps loading without showing any data, unless you change the time period (relative). After that change it will load the data properly. If you close the viewer and reopen the viewer again, the error happens again on any given time period you have left the viewer last time.

**To Reproduce**  
1. Go to any datapoint with history recordings and open the history data viewer
2. See error, not loading any data

**Expected behavior**  
Data shall be shown for the given time period

**Screenshots & Logfiles**  
Please see the video for error visualization

https://user-images.githubusercontent.com/3496522/210176304-951f4dff-4c51-4719-ab50-9b3e3ee6c2ae.mp4

**Versions:**  
 - Adapter version: 2.2.4
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: linux (RasPi)

**Additional context**

**Comment by foxriver76** [comment]
it should be fixed in 6.6.1
