### ISSUE TITLE
Admin zeigt manchmal error in GUI, wenn man auf "Instnzen" klickt

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1862]
Admin V6.3.5
Beim klicken auf Instanzen erscheint dieses Fenster:
![image](https://user-images.githubusercontent.com/92173565/210245881-2f70efe6-f91c-46b0-b86a-b0a290b66fde.png)

Erst ein chache löschen des Browsers lädt die Seite neu.

**Comment by BenAhrdt** [comment]
![image](https://user-images.githubusercontent.com/92173565/212134214-9fb155d4-5dc1-4cf6-b064-00b2c081093b.png)

**Comment by Feuer-sturm** [comment]
@BenAhrdt kannst du bitte noch diese Frage beantworten:
Verwendest du zufälligerweise den Edge Browser mit aktivierter Übersetzung?

Gibt es nur warnungen oder auch rote Fehler?

**Comment by BenAhrdt** [comment]
@Feuer-sturm Nein. Benutze Chrome und übersetze NIE etwas.
Soweit ich gesehen habe hab es nur Warnungen. Kann das nächste mal noch die console exportieren.

**Comment by foxriver76** [comment]
Error log is missing, unfortunately, this cannot be resolved without
