### ISSUE TITLE
Admin 6.3.5 "From npm" in expert mode not working correctly

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#1863]
**To Reproduce**  

1. Enable expert mode
2. Go to tab adapters
3. Click on octocat
4. Choose tab "from npm"

**Issues**

- Filter is not working
- When choosing an item, input box contains `[object Object]` instead of adapter name

**Screenshots & Logfiles**  

<img width="1034" alt="Screenshot 2023-01-05 at 13 57 51" src="https://user-images.githubusercontent.com/1959049/210785475-016479e4-4e21-4cbd-ba80-0da088188133.png">

**Versions:**  

- Adapter version: 6.3.5

**Comment by Diginix** [comment]
Dropdown works for me:
![image](https://user-images.githubusercontent.com/39678667/210793377-61bbc1b0-1da5-4429-b130-da8a6988ce00.png)

But doesn't tried to install something this way with admin 6.3.5

**Comment by Apollon77** [comment]
@klein0r Please try to update the repo

**Comment by klein0r** [comment]
@Apollon77 Same result - tested on 2 different installations and @Diginix confirmed the issue

**Comment by Apollon77** [comment]
hhmmm ... lametric do not have a title field ... not that we have an admin bug here that it not using titleLang[locale] but titlelang as fallback?

**Comment by Diginix** [comment]
[object Object] is shown no matter which adapter I select in dropdown.

click on admin
![image](https://user-images.githubusercontent.com/39678667/210948753-29381056-3647-4e8f-a2ad-be9b235c44d5.png)
leads to this:
![image](https://user-images.githubusercontent.com/39678667/210948798-52eed11c-0628-4c90-8529-02d42cfdb632.png)

**Comment by crunchip77** [comment]
can I confirm [object Object]

**Comment by Feuer-sturm** [comment]
With Admin 6.3.6 I had today the same issue. After updating to admin 6.3.7 the issue is fixed on my system. 
@klein0r or @Diginix can you please double check?

**Comment by klein0r** [comment]
Fixed (tested with 6.3.7)
