### ISSUE TITLE
Fehler in der GUI! immer beim öffnen von Objekte

### ISSUE THREAD

**Issue by Steve1907** [ioBroker/ioBroker.admin#1867]
Immer wenn ich die objekte öffne erscheint folgende fehlermeldung.

Fehler beim Ausführen von 'removeChild' auf 'Knoten': Der zu entfernende Knoten ist kein untergeordnetes Element dieses Knotens.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ks (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:26162)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27463)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:30653)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27920)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Xs (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27725)(X,se)=>r().createElement("div",{key:se},X,r().createElement("br",null))    at Ie (http://192.168.178.48:8081/static/js/3961.a98ff7ab.chunk.js:16:27612)

**Comment by Feuer-sturm** [comment]
@Steve1907 verwendest du den Edge Browser mit aktivierter Übersetzung? Wenn ja ist der Fehler bekannt. Hier hilft nur die automatische Übersetzung auszuschalten

**Comment by Steve1907** [comment]
Ja verwende ich, danke für die Hilfe damit ist mein Problem gelöst!
