### ISSUE TITLE
Slave not in the selection list for instance installation

### ISSUE THREAD

**Issue by tugsi** [ioBroker/ioBroker.admin#1869]
Added a new slave, it also appears in the host list and on the header in the web interface, but when I want to install an instance, I only have my master and the old slave in the selection list.

[https://forum.iobroker.net/topic/62114/slave-nicht-in-in-der-auswahlliste-bei-instanzinstallation](https://forum.iobroker.net/topic/62114/slave-nicht-in-in-der-auswahlliste-bei-instanzinstallation)

**Expected behavior**  
Also available as a selection in the instance installation.

**Screenshots & Logfiles**  
<img width="468" alt="instanz1" src="https://user-images.githubusercontent.com/18611753/212617343-3790e659-5ca9-4824-a076-6d94643f0720.png">
<img width="329" alt="instanz2" src="https://user-images.githubusercontent.com/18611753/212617345-839894ec-a2b7-42c4-b283-1f2f6ad5b8fa.png">

**Versions:**  
 - Adapter version: v6.3.5
 - JS-Controller version: 4.0.24
 - Node version:  v14.21.1 (Master), 16.19.0 (Slave)
 - Operating system: Linux

**Comment by Feuer-sturm** [comment]
@tugsi  can you please verify with admin 6.4.3 if your issue is fixed

**Comment by tugsi** [comment]
Yes is fixed on my system. Installed and tested. Thanks
