### ISSUE TITLE
Reverse scrolling of log file 

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.admin#1870]
It is more than annoying to read log files from bottom to the top when c&p from #tab-logs 
I don't know how you usually read text in western languages, but I usually start top left and read downwards... 

Please reverse the output.

**Comment by Apollon77** [comment]
ist is way more convenient for the normal users and so you make sure that you see the most current logs directly at first (without having the need to tell the UP that you start "at the undefined bottom"

**Comment by Grothesk242** [comment]
But longer messages that span over several lines are totally akward to read 'upside down'. 
You always have to check the timestamps for the direction that you have to read a log. The log read directly out ouf the file system is in chronological order, the admin one is reversed. Very confusing.

**Comment by Grothesk242** [comment]
I really don't know if it is convenient to have the adapter terminate and in the next lines it starts... :-) 

```
host.chet | 2023-01-23 22:36:03.270 | info | instance system.adapter.iceroad.0 terminated with code 0 (NO_ERROR)
iceroad.0 | 2023-01-23 22:36:02.719 | info | Terminated (NO_ERROR): Without reason
iceroad.0 | 2023-01-23 22:36:01.936 | info | starting. Version 1.1.3 in /opt/iobroker/node_modules/iobroker.iceroad, node: v16.19.0, js-controller: 4.0.24
host.chet | 2023-01-23 22:36:00.070 | info | instance system.adapter.iceroad.0 started with pid 526605
```

**Comment by Grothesk242** [comment]
LGTM
Is the chronological order the new default?

**Comment by GermanBluefox** [comment]
> LGTM Is the chronological order the new default?

No. The default is still "newest on the top"
