### ISSUE TITLE
Deprecate Let's Encrypt/certificate configuration + add ability to edit certificate collections

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#1871]
Dependant on https://github.com/ioBroker/ioBroker.js-controller/issues/2099.

**Comment by Feuer-sturm** [comment]
@raintonr  please provide additional information to your issue

**Comment by Apollon77** [comment]
@Feuer-sturm Topic is known by core team... so ok that way for now, but yes needs to be detailed

**Comment by raintonr** [comment]
Don't worry - PR is coming :smile:

**Comment by raintonr** [comment]
See https://github.com/ioBroker/webserver for certificate manager API.

**Comment by raintonr** [comment]
Thinking more about the need to edit certificate collections.

If a user doesn't want to use self signed certificates  (already editable on the admin page) and they don't want to use ACME (nothing required for that here anyway) then... erm... that has to be a ridiculously unlikely edge case. For those people I would say we should just explain that they can go to the advanced object editor and edit the certificates object directly. Saves maintaining a UI :smile:

**Comment by foxriver76** [comment]
As @GermanBluefox added the fixed label.. is it fully implemented from your point of view @raintonr?

**Comment by raintonr** [comment]
> As @GermanBluefox added the fixed label.. is it fully implemented from your point of view @raintonr?

No. There are still unnecessary options from what I can see. We discussed this on Telegram:

> If an adapter uses the new web module, it should not ask user to select certificates as the web module does that automatically. Maybe the user should be shown a note in the config settings explaining this (next to the single checkbox for HTTPS). It would be super useful if there could be some common config settings/text/whatever that could be re-used by all adapters that want, but that sounds like a core feature request.
> If an adapter uses the old mechanism... well... old way is unchanged but should be removed eventually.

**Comment by raintonr** [comment]
![image](https://github.com/ioBroker/ioBroker.admin/assets/3794098/882e07e3-9d23-4dc9-980f-fdd3a01cb88e)

**Comment by foxriver76** [comment]
Thanks, so this is the same issue as https://github.com/ioBroker/ioBroker.admin/issues/1962? 

Before removing it, I want to ensure, that everything works as expected. There is one open issue https://github.com/ioBroker/ioBroker.admin/issues/1977, I guess this is because of user misunderstanding. 

> If an adapter uses the new web module, it should not ask user to select certificates as the web module does that automatically. Maybe the user should be shown a note in the config settings explaining this (next to the single checkbox for HTTPS). It would be super useful if there could be some common config settings/text/whatever that could be re-used by all adapters that want, but that sounds like a core feature request.
If an adapter uses the old mechanism... well... old way is unchanged but should be removed eventually.

As you are deepest in this topic, could you provide me a explaining text, then I can replace the current config dropdowns with a note.

**Comment by mcm1957** [comment]
Just a side note - not sure if relevant here.
iobroker-coummunity-adapters/iobroker.acme is not yet available at stable. If using this adapter is suggested to more users, dont forget to add it to stable.
If this comment is unrelated - please simply ignore it

**Comment by foxriver76** [comment]
> Just a side note - not sure if relevant here. iobroker-coummunity-adapters/iobroker.acme is not yet available at stable. If using this adapter is suggested to more users, dont forget to add it to stable. If this comment is unrelated - please simply ignore it

It has a controller v5 dependency, so latest is okay, but should not forget to add it to stable before controller v5 goes stable. As it is a brand new adapter, we can also add it to stable right now already, if  @raintonr gives the go.

**Comment by raintonr** [comment]
> It has a controller v5 dependency

Actually, no. ACME runs on v4.

It looks stable to me. Some wording isn't what I'd prefer but maybe that's just me.

**Comment by mcm1957** [comment]
Iso whats ghe result?
If you feel ist stable you can simply add it to stable. At iobroker.dev it should wirk with one click
As an alternative add a remark at the corresponding issue at acme adapter and i can do it as soon as i have time

**Comment by foxriver76** [comment]
> > It has a controller v5 dependency
> 
> Actually, no. ACME runs on v4.

Perfect, however, the v0.0.2 on npm has a dependency 
```
    "dependencies": [
      {
        "js-controller": ">=5.0.0-alpha"
      }
```
So maybe publish the current content from GH to npm before going to stable
