### ISSUE TITLE
Admin updatet repository merfach

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1872]
Hallo, der Admin (V6.3.5) hat heute alleine mehrfach das Repository geupdaten (Es versucht).
![image](https://user-images.githubusercontent.com/92173565/214780643-2230c0d1-1db3-4f6a-8ec8-cc77454775ed.png)

**Comment by Apollon77** [comment]
Was ist als Frequenz fürs update eingestellt? Welche Admin version? Mehr logs? Detaaaiillllllllsssssss ....

**Comment by BenAhrdt** [comment]
Normal auf Täglich. Ich habe nichts verstellt.
Sorry log eben aus Versehen gelöscht.
Wo finde ich denn nochmal die Einstellung des Zyklus? Habe gerade vergeblich gesucht.

**Comment by Feuer-sturm** [comment]
@BenAhrdt 
Die Einstellung findest du unter Instanzen -> Admin
![grafik](https://user-images.githubusercontent.com/25422320/227737576-d96aa10a-3992-43c5-99f9-dfff063df809.png)

Ist das issue von deiner Seite aus noch aktuell?

**Comment by BenAhrdt** [comment]
Nein kam jetzt nicht mehr vor.
