### ISSUE TITLE
Cannot install iobroker.admin@6.3.6

### ISSUE THREAD

**Issue by dekatWin** [ioBroker/ioBroker.admin#1875]
**Describe the bug**  
Installing iobroker.admin@6.3.6... (System call)
host.Mini-Pc(ioB) Cannot install iobroker.admin@6.3.6: 4294963214

**To Reproduce**  
Try  installing the Update on Windows via Admin or cmd....

**Expected behavior**  
Cannot install iobroker.admin@6.3.6: 4294963214

**Versions:**  
 - Adapter version: <6.3.5>
 - JS-Controller version: <4.0.24>
 - Node version: <18.12.1>
 - npm <8.19.2>
 - Operating system: <Win 11>

**Additional context** 
Since a complete Windows restart didn't work either, I used some --force and was able to install it in the end.

At the moment everything is working normally, but I keep getting a warning that a slow connection has been detected and I can't do anything except click Cancel in the warning window. 

There is no slow connection, the mini-PC is connected to a router with WLAN 802.11ax, which is connected to the Internet via fibre optics at 500 Mbps.

**Comment by dekatWin** [comment]
small Update,  The Iobroker admin is now completely frozen. I can no longer reload the page, but other Iobroker adapter interfaces such as Node Red are still working fine. 

I get the browser error message: "ERR_CONNECTION_TIMED_OUT" when I try to reload the admin page. 
I am now trying to roll back and to restore an earlier backup.

**Comment by Apollon77** [comment]
try updating via CLI and add --debug ... then youz see whsat NPM really outputs

**Comment by dekatWin** [comment]
Here is the debug cli output:

`This upgrade of "admin" will introduce the following changes:
==========================================================================
-> 6.3.6:
Allowed the edit of log level in the configuration tab
==========================================================================

Would you like to upgrade admin from @6.3.5 to @6.3.6 now? [(y)es, (n)o]: y
Update admin from @6.3.5 to @6.3.6
npm WARN config dev Please use --include=dev instead.
npm WARN config dev Please use --include=dev instead.
NPM version: 8.19.2
Installing iobroker.admin@6.3.6... (System call)
npm WARN config dev Please use --include=dev instead.
npm WARN config dev Please use --include=dev instead.
npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Program Files\iobroker\ioB\node_modules\iobroker.info
npm ERR! dest C:\Program Files\iobroker\ioB\node_modules\.iobroker.info-jASK6mdT
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Program Files\iobroker\ioB\node_modules\iobroker.info' -> 'C:\Program Files\iobroker\ioB\node_modules\.iobroker.info-jASK6mdT'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mini-Pc\AppData\Local\npm-cache\_logs\2023-02-01T11_28_34_354Z-debug-0.log
host.Mini-Pc(ioB) Cannot install iobroker.admin@6.3.6: 4294963214

**Comment by Apollon77** [comment]
EBUSY is a windows thingy ... stop the adapter please and do the update then. sometimes windows seems to lock files and then npm can not update them

**Comment by dekatWin** [comment]
thx, it worked. 

I was able to install admin 6.3.6 without force after stopping iobroker.
But unfortunately now i have 2 perm problems.

1. At the first start of admin I always get the slow connection warning, which accepts no input except abort.

2. Now I can't update, uninstall or install anything via Admin.

**Comment by dekatWin** [comment]
Ok, I have solved the EBUSY problem.

1. delete the "package-lock.json" file from the IoBroker folder.
2. Clear the npm cache, I used the command "npm cache clean --force".

After that I was able to upgrade, install and uninstall adapters via admin as usual.
Thanks for your help, the EBusy hint helped me a lot.

The problem with the slow connection warning still remains, I can click on all the other buttons, but the warning only disappears briefly for 1 second and then reappears immediately, so to make it disappear permanently I have no choice but to click on Cancel.

**Comment by dekatWin** [comment]
Thanks, just the slow connection warning issue is still there, it doesn't really bother me but before the admin upgrade I didn't have this problem. Gone try my luck on the iobroker forum, its problebe a just a windows think again.

**Comment by Apollon77** [comment]
"Slow connection" info mainly means that the js.controller process is somehow overloaded ot the CPU is utilized a lot

**Comment by dekatWin** [comment]
Then it should be an overload warning and not a slow connection warning, that's a bit misleading.

This is my average load:
![image](https://user-images.githubusercontent.com/111662370/216323193-67926472-7b41-4f55-a3ef-16f2131e0472.png)

Usually just before the first slow connection warning, this error message appears in the bottom left corner:
![Screenshot 2023-02-02 13 17 13](https://user-images.githubusercontent.com/111662370/216323771-984da060-29e9-4daa-8ac4-c6e639c104b5.png)



As you can see something doesn't fit here, in the meantime I have tried all sorts of things and have now successfully narrowed down the reason, I don't understand why, but I am 100% sure that the Slow Connections warning is triggered as soon as no CMD window is active in the foreground. If I manually open the CMD window and leave it open, the warning disappears permanently, if I don't leave a CMD window open, the Slow Connections warnings start again after about 15 min. 

My guess:
Probably since the last update, Windows 11 starts to throttle the services or iobroker after about 15 min, without an active window in the background. The CPU load remains low, so Windows will probably somehow affect the read and write speed. 

My workaround for this:
I now simply leave an iobroker cmd window in the foreground via a batch as soon as Windows starts, which works quite well.

**Comment by Apollon77** [comment]
In fact "overload" is the most common reasoin for the message but there could be also others, so thats why it is called as it is.

It would be cool if you could create your infos as Thread in the forum that also other users with WIndows 11 maybe can check that or say something to it if they have the same issues.
Thank you!
