### ISSUE TITLE
Fehler bei getRespository

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1877]
Heute tauchte diese Meldung auf:

Admin: V6.3.5

`<html>
<body>

host.buanet-iobroker1 | 2023-02-01 09:07:00.043 | error | Invalid request getRepository. "callback" or "from" is null
-- | -- | -- | --

</body>
</html>`

**Comment by Feuer-sturm** [comment]
Is duplicate to #1555
