### ISSUE TITLE
Fensterinhalte werden nicht automatisch aktualisiert (z.B. Log Fenster, Skripte)

### ISSUE THREAD

**Issue by eumats** [ioBroker/ioBroker.admin#188]
Die Informationen in einigen Fenstern werden nicht automatisch aktualisiert. Dies tritt sowohl im Log Fenster als auch im Skripte Fenster auf. Ändert man z.B. im Skripte Fenster ein globales Skript, so werde die Inhalte nicht automatisch geladen. Das Fenster bleibt grau.
Getestet mit Firefox und Safari.

V3.1.11. Gekommen bin ich von 2.0.11

**Comment by GermanBluefox** [comment]
Wurde admin auch neu gestartet?

2018-02-05 5:08 GMT+01:00 eumats <notifications@github.com>:

**Comment by eumats** [comment]
Sowohl admin als auch den gesamten Raspi...

**Comment by AlCalzone** [comment]
Hatte das gleiche Problem mit dem Skripte-Log vor Version 3.1.6. Installation von 3.1.6 und Neustart hat das Problem behoben.

Dann ging es eine Weile, gestern ist der Log wieder leer geblieben (v3.1.10). Nach Neustart ging es dann wieder.

**Comment by eumats** [comment]
Bei mir funktioniert die LOG-Aktualisierung nun. Warum? Keine Ahnung...

Das mit dem leeren Skripte Fenster bei Aktualisierung von globalen Skripten ist dafür unverändert...
