### ISSUE TITLE
Admin meldet für einen Alias ein Error

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1880]
Der Admin hat gerade diesen Fehler für 40 Objekt gebracht:

`<html>
<body>

admin.0 | 2023-02-13 11:49:46.714 | error | Alias subscription error. Please check your alias definitions: sourceId=operating-hours.0.Heizungsbrenner.operatingHours.timestring_d_h_m_s, sourceObj={"type":"state","common":{"name":"timestring_d_h_m_s","type":"string","role":"value","read":true,"write":false,"unit":"d:h:m:s","def":""},"native":{},"from":"system.adapter.operating-hours.0","user":"system.user.admin","ts":1676099085318,"_id":"operating-hours.0.Heizungsbrenner.operatingHours.timestring_d_h_m_s","acl":{"object":1636,"state":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}
-- | -- | -- | --

</body>
</html>`

Danach war wieder alles ok. Und genau diese states haben auch funktioniert.

**Comment by Diginix** [comment]
Gehört hier hin:
https://github.com/ioBroker/ioBroker.js-controller/issues/1406
