### ISSUE TITLE
Error in GUI (files)

### ISSUE THREAD

**Issue by UweLm** [ioBroker/ioBroker.admin#1882]
**Describe the bug**  
Open 

**To Reproduce**  
1. Go to 'files'
2. Click on '---' of any directory
3. The dialog 'Zugriffsteuerungsliste...' (access control list...) will be displayed
4. Click "Abort" (or anywhere else)
5. Crash (see screenshot)

**Expected behavior**  
Dialog  'Zugriffsteuerungsliste...' (access control list...) should disappear and the list of subdirs/files shall be displayed

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/78011774/218798756-487630bd-c2a9-4c3c-bbff-b4d3b3e82255.png)
![image](https://user-images.githubusercontent.com/78011774/218796625-f96cecd4-2c20-4960-8308-b058856cda02.png)

**Versions:**  
 - Adapter version: 6.3.5 Admin
 - JS-Controller version: <4.0.24> 
 - Node version: <16.11.0> 
 - Operating system: <Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l>

**Additional context**

**Comment by Feuer-sturm** [comment]
is fixed with admin 6.4.3

**Comment by UweLm** [comment]
Thank you for the quick solution!
Have a nice weekend.
