### ISSUE TITLE
Fehler mit GUI

### ISSUE THREAD

**Issue by AustrianSteve** [ioBroker/ioBroker.admin#1885]
Hallo zusammen!
Ich bin ganz neu hier und hoffe hier jetzt nicht gleich negative auf zu fallen.

Habe einen Fehler in der GUI
![Fehler](https://user-images.githubusercontent.com/126331167/221416252-5389555f-3541-4239-88c5-f4c632b736ff.jpg)

Hier ein paar Daten aus dem System:

Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 3
Geschwindigkeit: 2399 MHz
Modell: Intel(R) Atom(TM) CPU C2538 @ 2.40GHz
RAM: 4.8 GB
System-Betriebszeit: 1 T. 00:06:08
Node.js: v16.19.1
time: 1677421294264
timeOffset: --
Adapter-Anzahl: 468
NPM: 8.19.3
Datenträgergröße: 47.9 GB
Freier Festplattenspeicher: 40.0 GB
Betriebszeit: 1 T. 00:05:14
Aktive Instanzen: 10
Pfad: /opt/iobroker/
aktiv:

Denke der Fehler hat mit dem Adapter fritzbox dect zu tun, da es wieder weg ist, wenn ich diesen entferne. Würde diesen aber gerne verwenden und vielleicht kann mir jemand helfen.

Adapter:
fritzbox dect
Version: 2.2.6

Danke für Eure Hilfe

Liebe Grüße Steve

**Comment by Apollon77** [comment]
Ich glaube der Fehler kommt weil Du die Webseite von ioBroker "automatisch übersetzen lässt". Buitte solche auto translate Tools deaktivieren
