### ISSUE TITLE
"Kommando-Ausführung": Toggle-Button weniger/mehr hat keine Funktion

### ISSUE THREAD

**Issue by eumats** [ioBroker/ioBroker.admin#189]
Unter Safari funktioniert der Toggle-Button weniger/mehr bei "Kommando-Ausführung" nicht. Man kann nicht zwischen mehr und weniger hin- und herschauten.

V3.1.12

**Comment by AlCalzone** [comment]
Bin ich auch schon drauf hereingefallen. Der Button sieht aus als wäre er zu betätigen, tatsächlich musst du aber auf die Labels "mehr" und "weniger" klicken. 
Mmn sollte auch ein Klick auf den Toggle-Button funktionieren.

**Comment by GermanBluefox** [comment]
Please retest with 3.2.4
