### ISSUE TITLE
6.3.7: Liesmich wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.admin#1894]
In der 6.3.7 geht beim klicken auf das ? neben dem Adapter die Liesmich-Seite nicht mehr auf.
![image](https://user-images.githubusercontent.com/11984960/224836111-71a1f054-e1be-48d0-b62d-5a0a0c1f2e0f.png)

Es kommt folgende Fehlermeldung.

![image](https://user-images.githubusercontent.com/11984960/224835762-538281d4-b896-4407-a3f2-551f566ea79d.png)

Beim Rückrüsten auf die 6.36 geht wieder alles.

**Comment by MarkBpunkt** [comment]
Lässt sich so zuverlässig reproduzieren:

**Comment by mcm1957** [comment]
Siehe auch https://forum.iobroker.net/topic/64061/typeerror-can-t-convert-undefined-to-object

**Comment by Feuer-sturm** [comment]
Is fixed with 6.4.1
