### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by mueller-esch** [ioBroker/ioBroker.admin#1898]
iobroker.admin@6.3.5
instrument.ts:124 [2023-03-18T15:02:22.387Z] Try to connect
:8081/#tab-intro:1 Unchecked runtime.lastError: The message port closed before a response was received.
instrument.ts:124 Stored version: , new version: 6.3.5
instrument.ts:124 Connected: true
instrument.ts:124 Translate: Link
instrument.ts:124 Translate: time
instrument.ts:124 Translate: timeOffset
instrument.ts:124 Translate: _nodeCurrent
instrument.ts:124 Translate: _nodeNewest
instrument.ts:124 Translate: _nodeNewestNext
instrument.ts:124 Translate: _npmCurrent
instrument.ts:124 Translate: _npmNewest
instrument.ts:124 Translate: _npmNewestNext
 iobroker.javascript@6.1.4 using theme "colored"
 
██╗ ██████╗ ██████╗ ██████╗  ██████╗ ██╗  ██╗███████╗██████╗ 
██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗██║ ██╔╝██╔════╝██╔══██╗
██║██║   ██║██████╔╝██████╔╝██║   ██║█████╔╝ █████╗  ██████╔╝
██║██║   ██║██╔══██╗██╔══██╗██║   ██║██╔═██╗ ██╔══╝  ██╔══██╗
██║╚██████╔╝██████╔╝██║  ██║╚██████╔╝██║  ██╗███████╗██║  ██║
╚═╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

 Nice to see you here! :) Join our dev community here https://github.com/ioBroker/ioBroker or here https://github.com/iobroker-community-adapters
 Help us to create open source project with reactJS!
 See you :)
 [2023-03-18T15:02:28.350Z] Try to connect
:8081/adapter/javascript/vs/editor/editor.main.nls.de.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
 Loading "vs/editor/editor.main.nls.de" failed
_ @ :8081/adapter/javascript/vs/loader.js:6
 Error: [object Event]
_ @ :8081/adapter/javascript/vs/loader.js:6
 Here are the modules that depend on it:
_ @ :8081/adapter/javascript/vs/loader.js:6
 ===anonymous2===
_ @ :8081/adapter/javascript/vs/loader.js:6
:8081/adapter/javascript/tab.html?newReact=true&react=colored:1 Unchecked runtime.lastError: The message port closed before a response was received.
sentry.iobroker.net/api/56/envelope/?sentry_key=504499a725eb4898930d3b9e9da95740&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.19.0:1          Failed to load resource: the server responded with a status of 403 ()
 Detected custom blockly: email
 Detected custom blockly: iqontrol
 Detected custom blockly: pushover
7 Detected an editable field that was not serializable. Please define SERIALIZABLE property as true on all editable custom fields. Proceeding with serialization.
(anonymous) @ :8081/adapter/javasc…424922d.chunk.js:61
2948.1bd4fcc1.chunk.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
7397.796d0586.chunk.js:1          Failed to load resource: net::ERR_CACHE_READ_FAILURE
instrument.ts:124 ChunkLoadError: Loading chunk 2948 failed.
(error: http://192.168.52.133:8081/static/js/2948.1bd4fcc1.chunk.js)
    at n.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at n.e (ensure chunk:5:56)
    at App.jsx:81:36
    at G (react.production.min.js:18:161)
    at oa (react-dom.production.min.js:291:300)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at ea (react-dom.production.min.js:273:245)
    at hn (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

Plattform: linux
RAM: 5.8 GB
Node.js: v16.17.0(16.19.1)
NPM: 8.18.0(8.19.3)

**Comment by Feuer-sturm** [comment]
@mueller-esch Hi, what did you do to trigger the error?

**Comment by mueller-esch** [comment]
I only opened the instances site
