### ISSUE TITLE
Skript Änderungen gehen beim Tabwechsel verloren (Admin 3.1.12)

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.admin#190]
Admin 3.1.12

In Admin 2 konnte während des Editieren mal eben in den Tab Objekte wechseln, um etwas nachzusehen.
Wenn man dann auf Skripte zurück ging, blieben die Änderungen erhalten und man konnte weiter editieren.

In Admin 3 sind alle Änderungen verloren.
Eine Warnung beim Tabwechsel, dass nicht gespeichert wurde erfolgt nicht.

**Comment by eumats** [comment]
Das Verhalten kann ich bestätigen. Das ist bei mir auch so...

V3.1.12

**Comment by roe19xx** [comment]
Das Verhalten tritt auch beim Admin Adapter 3.2.3 (Javascript Adapter 3.6.4) auf.

**Comment by GermanBluefox** [comment]
Bin selbst in das Problem rein gelaufen. :(
In 3.4.3 Admin sollte es gefixt sein.
Leider javascript muss auch upgedatet werden (es gibt aber nur git version)

**Comment by Apollon77** [comment]
Weche JS Version wäre das? Muss die dann zusammen mit Admin in Stable oder im Notfall ok wenn nicht?
