### ISSUE TITLE
State "admin.0.system.adapter.admin.0.logging" has no existing object

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#1907]
**Describe the bug**  
Warning in log file for State "admin.0.system.adapter.admin.0.logging" has no existing object

**To Reproduce**  
1. Update to js-controller 5
2. Start ioBroker

**Expected behavior**  
No error in the log :-)

**Screenshots & Logfiles**  
```
admin.0
	2023-03-30 20:27:07.044	warn	State "admin.0.system.adapter.admin.0.logging" has no existing object, this might lead to an error in future versions

```
**Versions:**  
 - Adapter version: admin 6.4.2
 - JS-Controller version:  5.0.1-alpha.0-20230330-e0b409fe)
 - Node version: v18.15.0

**Comment by Apollon77** [comment]
Mainly js-controller issue !! WIll be fixed in next alpha
