### ISSUE TITLE
Licensing of vis2 not possible bug

### ISSUE THREAD

**Issue by programmcs** [ioBroker/ioBroker.admin#1909]
**Describe the bug**  
Licensing of vis2 not possible

**To Reproduce**  
1. i copy the licence key in the licence key field
2. Click Check licence
3. the Error is coming

**Expected behavior**  
that the product is licensed

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
![image](https://user-images.githubusercontent.com/55063928/229343741-ad45fb8d-7698-4484-9cf3-601307407b82.png)

**Versions:**  
 - Adapter version: 2.0.23
 - JS-Controller version: 4.0.24 
 - Node version: 18.15.0 
 - Operating system: that the product is licensed

**Additional context**

**Comment by Feuer-sturm** [comment]
@programmcs Which Admin version do you use?

**Comment by programmcs** [comment]
i haved the version 6.3.5 now i have updated to 6.4.3 

now I also have an error, but now the error is a little further different

![image](https://user-images.githubusercontent.com/55063928/229372989-63daf9c4-ec13-4ca3-8343-73620b9690e5.png)
