### ISSUE TITLE
Zeien in den Objekten werden nicht korrekt dargestellt

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#1915]
Seit der 6.3.5 werden bei mir die Zeilen wie bspw. "Name" nicht mehr korrekt / gar nicht dargestellt.
Auf der rechten Bildschirmseite dagegen ist jede Menge platz.
![image](https://user-images.githubusercontent.com/92173565/231200101-a7602bae-4e1f-4487-80a3-bf22aa612c3e.png)

**Comment by BenAhrdt** [comment]
@mcm1957 ja ich meinte Spalten.
Aber ich kann die Spalte nicht ziehen,
das ist es ja.

**Comment by mcm1957** [comment]
Oben im Header die gepunktete Linie sollte ziehbar sein. Die nicht gepunkteten sind "fix"
Wenn das nicht geht - OK, dann weiß ich auch nichts dazu

**Comment by Feuer-sturm** [comment]
@BenAhrdt welche Auflösung verwendest du? Ist die Darstellung von einem Tablet oder PC/Notebook?

**Comment by BenAhrdt** [comment]
@Feuer-sturm Ich verwende 1920 x 1200 (schon ewig)
@mcm1957 Am PC und am Laptop. Kann nichts verschieben, neben Type die gestrichelte Linie nur 5mm nach links. Das wars.
Das war auf einmal nach dem letzten Admin Update so.

**Comment by Feuer-sturm** [comment]
@BenAhrdt schau dir bitte einmal die Lösungsversuche in diesem thread an https://forum.iobroker.net/post/959182

Ich vermute, dass du im forum zu einer schnelleren Lösung kommst. Du kannst dich dort ja an die Diskussion mit dran hängen und wenn es für den admin eine Problem Beschreibung/nährte Hinweise gibt packen wir sie hier rein.

**Comment by klein0r** [comment]
Am besten mal den local storage für die Domain/IP im Browser löschen (nein, damit meine ich nicht die Cookies).

**Comment by BenAhrdt** [comment]
@klein0r Danke. Das war es.
