### ISSUE TITLE
[jsonConfig] option useSystemName does not work with element coordinates

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1919]
coordinates always displays system coordinates option, useSystemName:false or omitting does not change anything

```
                "coordinates1Txt": {
                    "type":"staticText",
                    "text": "COORDINATES displays coordinates (divider: #)",
                    "newLine": true
                },
                "coordinates1": {
                    "type":"coordinates",
                    "divider":"#",
                    "newLine": true
                },
                "coordinates2Txt": {
                    "type":"staticText",
                    "text": "COORDINATES displays coordinates (with autoInit)",
                    "newLine": true
                },
                "coordinates2": {
                    "type":"coordinates",
                    "autoInit":true,
                    "useSystemName":false,
                    "newLine": true
                },
```

![Screenshot 2023-04-15 202035](https://user-images.githubusercontent.com/28575778/232246829-82246d7c-501f-48dc-bfe8-f81b554a99f6.jpg)

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

**Comment by foxriver76** [comment]
From my understanding (from reading the code), `useSystemName` is intended to render an additional checkbox, where the user can click `use system settings`
If this checkbox is chcked, the Coordinate control should be greyed out (disabled) and the UI automatically updates to the system configured coordinates, whenever rendered.

Can you maybe uncomment https://github.com/mcm1957/ioBroker.jsonconfig-demo/blob/d81aec4c2c7e8f44927aa7220a9739e36a98a288/admin/jsonConfig.json5#L343, then we can check this.

**Comment by mcm1957** [comment]
I think its faster and easier for you if you cann modify the repo directly.
Ive sent an invite. Feel free to change whatever seems useful for prectical use at real adapters.

If you not not want to do this, please let me know, I'll do the changes / test as soon as possible
