### ISSUE TITLE
Adapterliste und Filter Probleme Admin3

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#192]
1.) Wenn man die Adapterliste gefilter hat (z.B. "Nur welche mit Updates zeigen") und dann den Host bei Multihost wechselt passiert nichts. Erst nach entfernen des filters passiert der Reload
2.) Wenn man Filter setzt und dann Admin verlässt ist beim nächsten Besuch der Filter wieder da, aber der Button ist nicht farbig markiert

**Comment by GermanBluefox** [comment]
PLease retest 3.2.4

**Comment by Apollon77** [comment]
Sorry, aber da geht etwas ganz gehörig komisch:

...Multihost und Admin 3.3.3 … das umschalten der hosts geht nicht mehr bekomme immer eine leere seite

sobald ich host ändere wird seite in der navigation dektiviert (bzw „Übersicht“ aktiviert aber nichts engezeigt). Wenn ich dann wieder adapter klickt bekomme ich alles angezeigt für den master egal was oben für ein Host ausgewhlt ist

aaahh … wenn ich dann filter umschalte kommen die anzeigen für den korrekten Host

**Comment by GermanBluefox** [comment]
Close?

**Comment by Apollon77** [comment]
No, see #220 and https://github.com/ioBroker/ioBroker.admin/issues/216#issuecomment-373905096 ... think all refers to the same topic

**Comment by GermanBluefox** [comment]
Please retest with 3.3.8

**Comment by Apollon77** [comment]
verified
