### ISSUE TITLE
[jsonConfig] elements datePicker and timePicker do not store default values unless those values are edited/changed

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1923]
jsonConfig elements DATEPICKER and TIMEPICKER show current date / time as default when gui is opened the first time. BUT those information is not stored automatically. You need to change the date or edit the time so that the dat.xxx elements get filled and the infomation is stpored at config.

Thats the same missing update as describe at issue https://github.com/ioBroker/ioBroker.admin/issues/1920

In addition datpicker stores a string including a time and timepicker stores a string including a date.
That's at least surprising. Is there any option available to limit the string to the information displayes at the picker?

Please let me know, if a screenrecoder is needed or my description is sufficient.

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

Note: demo config is stored at repository mcm1957/ioBroker.jsonconfig-demo

![image](https://user-images.githubusercontent.com/28575778/232333555-b1ee8f13-3d1f-4a94-b590-9df91f9ce87b.png)

![image](https://user-images.githubusercontent.com/28575778/232333596-20512150-bcca-4b57-b894-9470b4e40ca5.png)

**Comment by foxriver76** [comment]
other question is, should they really have a preselected default if the underlying value is undefined? I think, then strange issues happen, when someone saves config and without touching anything has changed the date to today for example. I would try to keep the input empty or show a placeholder when the underlying value is non existing yet. Thoughts  @mcm1957?

**Comment by mcm1957** [comment]
see https://github.com/ioBroker/ioBroker.admin/issues/2319

**Comment by mcm1957** [comment]
> other question is, should they really have a preselected default if the underlying value is undefined? I think, then strange issues happen, when someone saves config and without touching anything has changed the date to today for example. I would try to keep the input empty or show a placeholder when the underlying value is non existing yet. Thoughts @mcm1957?

Sorry for late answer.
In my oppinion it would be ok to show nothing as default too. Using the default function it should be possible to set the current date / time as default is desired by adapter. The only thing I would rquire is that every value shown must be saved too :-)
