### ISSUE TITLE
[jsonConfig] element json does not work at all (no editor displayed)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1925]
jsonConfig element json (json editor) does not work at all. I do not see any place to edit json data nor a buttoen to launch the editor.
The element jsonEditor displays the specified label - but nothing else. 

Source extract:
```
                // json - json editor
                "jsonHdr": {
                    "type": "header",
                    "text": "JSON",
                    "size": 2
                },
                "jsonTxt": {
                    "type":"staticText",
                    "text": "configure json data",
                    "newLine": true
                },
                "json": {
                    "type": "json",
                    "label": "json data",
                    "delimiter":";",
                    "newLine": true
                },
                "jsonVal": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.json}",
                    "sm":8,
                    "md":8,
                    "lg":8,
                    "xs":8
                },
```

Scrrenshot:

![image](https://user-images.githubusercontent.com/28575778/232472041-6c0704f4-4f75-446a-8ee8-a9af75cf4a3e.png)

NO error is visible at browser console

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

Note: demo config is stored at repository mcm1957/ioBroker.jsonconfig-demo

**Comment by foxriver76** [comment]
Okay, the first problem, is that the component should be named `jsonEditor` and not `json`

**Comment by mcm1957** [comment]
Sorry for the mistake

**Comment by mcm1957** [comment]
Maybe some sort of warning for unknown Objects should be discussed.
Although this would be a feature for incorrect admin requirements primary.

**Comment by mcm1957** [comment]
Ok, I could have checked the sources.  But I did not have the idea that this could be the problem.
Please feel free to adapt repo. You should have an invite. So you can close or further investige this issue with minimum additional effort.

**Comment by foxriver76** [comment]
closed by https://github.com/ioBroker/ioBroker.admin/pull/1980
