### ISSUE TITLE
[jsonConfig] hideOnlyControl attribute does not work at text element 

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1929]
When setting attribute hídeOnlyControl the space occupied should be kept.
The following example shows a text element which is hidden. The following elemnt (a pattern element) shifts to the left, the space previously occupied by the text inpu field is not kept blank as expected:

![image](https://user-images.githubusercontent.com/28575778/232535993-3eb75a75-abf8-4920-aa82-1a29abde2add.png)

![image](https://user-images.githubusercontent.com/28575778/232536117-e51eeb1f-6b9b-4db9-b6d8-d58ca36b006e.png)

Sourceextract: 
```
                // text - Text component
                "textHdr": {
                    "type": "header",
                    "text": "TEXT",
                    "size": 2
                },
                "text1Txt": {
                    "type":"staticText",
                    "text": "standard textfield for datat input",
                    "newLine": true
                },
                "text1": {
                    "type":"text",
                    "label":"Textinput",
                    "newLine": true
                },
                "text1Val": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.text1}"
                },
                "text2Txt": {
                    "type":"staticText",
                    "text": "textfields can be disabled and hidden",
                    "newLine": true
                },
                "text2c": {
                    "type":"checkbox",
                    "label":"click to enable",
                    "newLine": true
                },
                "text2": {
                    "type":"text",
                    "label":"Textinput",
                    "disabled":"!!data.text2c"
                },
                "text2Val": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.text2}"
                },
                "text3c": {
                    "type":"checkbox",
                    "label":"click to hide",
                    "newLine": true
                },
                "text3": {
                    "type":"text",
                    "label":"Textinput",
                    "hidden":"data.text3c",
                    "hideOnlyControl":true
                },
                "text3Val": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.text3}"
                },
                "text4Txt": {
                    "type":"staticText",
                    "text": "Textfields can be readonly",
                    "newLine": true
                },
                 "text4c": {
                    "type":"checkbox",
                    "label":"click to remove writeprotect",
                    "newLine": true
                },
                "text4": {
                    "type":"text",
                    "label":"Textinput",
                    "readOnly":true,
                    "default":"some default text"
                },
                "text4Val": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.text4}"
                },
                "text5Txt": {
                    "type":"staticText",
                    "text": "Multiline textfields are possible too (here 3 to 7 rows)",
                    "newLine": true
                },
                "text5": {
                    "type":"text",
                    "label":"Textinput",
                    "minRows":3,
                    "maxRows":7
                },
                "text5Val": {
                    "type":"pattern",
                    "pattern":"stored value is ${data.text3}"
                }
```
No error is visible at browser console

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

Note: demo config is stored at repository mcm1957/ioBroker.jsonconfig-demo

 Note2: Did not (yet) test if hideOnlyControl works woth other elements

**Comment by foxriver76** [comment]
Not sure if this is as designed or a bug tbh. Haven't looked deeper into it but I guess if disabled, the whole disabled component is not rendered and not hidden with css. Thus, the space will never be occupied.

**Comment by mcm1957** [comment]
If the space is not kept, this option is ruther useless :-)
You can hide a control using "hidden". So if the space is not kept regardless of setting "hideOnlyControl" I do not know whtas the purpose of this option

**Comment by foxriver76** [comment]
Makes sense, yes. Then it seems like some has to define the actual space

https://github.com/ioBroker/ioBroker.admin/blob/654399e865127a38b6ff34dcbf42cdaa5818454b/src/src/components/JsonConfigComponent/ConfigPanel.jsx#L233-L240

maybe @GermanBluefox can say how it is supposed to work. Then we can change the documentation or the code accordingly.

**Comment by mcm1957** [comment]
Well, if the elemnt is not hidden the space is calculated somehow anyway. The label occupies space depending on context and the text field seems to have some predefioned space. Isn't possible to use this calculation for hidden element too?

But  I do not have any knowlege on react otherwise I would have provided a PR anyway. 

And THANKS fro processing those json issues !

**Comment by GermanBluefox** [comment]
The space is calculated depends on sm, lg, md, xl... Nothing of it is used in your jsonConfig.
Please provide the valid width and you will be happy
