### ISSUE TITLE
Keine Scrollbalken im Firefox und Designartefakte im IE

### ISSUE THREAD

**Issue by MiJo112** [ioBroker/ioBroker.admin#193]
Im Firefox (58.0.1) lässt sich nicht im eingebetten Bugtracker und Liesmich runtersrollen.
Im IE11 sind noch starke Designartefakte vorhanden.
Admin Version: 3.1.12
![grafik](https://user-images.githubusercontent.com/35043404/36039865-0eb0b782-0dc4-11e8-9d1c-5cddec0536f6.png)
![grafik](https://user-images.githubusercontent.com/35043404/36039815-e93176fe-0dc3-11e8-9dc9-cc9fcba395a2.png)

**Comment by GermanBluefox** [comment]
BItte 2 issues daraus machen:
V3.2.1 IE: 
![image](https://user-images.githubusercontent.com/4582016/36904362-cae19c7e-1e30-11e8-8311-1c345f312fbf.png)

**Comment by GermanBluefox** [comment]
Scrollbar is fixed in 3.2.1
