### ISSUE TITLE
Inkonsistencies when creating objects at admin interface in expert mode

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1930]
a) When creating a state using expert mode, the follwoing pop up is shown:

![image](https://user-images.githubusercontent.com/28575778/232543171-4a97a624-f395-475a-966f-66ee6fee1b9c.png)

At this pop up states aer named datapoints. For consistency the text should be changes to states in my oppinion. OR the rule to name states states a(and in german Zustände) should be changed to datapoints (de:Datenpunkte). 

I can accept both variants, but we should try to be consistent.

b) Its not possible to add a ste object directly at instance level:

![image](https://user-images.githubusercontent.com/28575778/232543820-cf7c2745-b172-420d-81d3-df027652f01c.png)

I do not see a reason why this is blocked.

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

**Comment by foxriver76** [comment]
`a` agree

For `b` is it now allowed to create states under arbitrary instances again @GermanBluefox  @Apollon77? I would expect that you can neither create a state in scenario `a` nor `b`. I thought we only had exceptions for `javascript`, `0_userdata` and `mqtt` (maybe?)? However, it could be that I am not up-to-date ;-)

**Comment by Apollon77** [comment]
I thunk there was such a whitelist already somewhen ... and yes javascript 0_uderdata.0 and mqtt were in when I remember ...
