### ISSUE TITLE
[jsonConfig / Feature] related to element setState

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1931]
a) jsonConfig element setState requires a full id (including adaptername and instance). It would be very useful if at least the instance could be configure by %INSTANCE% or by some other way specifying the own instance

b) the val attribute uses the value specified. It would be useful to add a valFunc attribute so that setState can be used to set a state with a vlaue contained in some other configuration elelemnt, i.e. a text or number field.

c) docu (schema.md) should be extended to clearly state that a full id is required. (I could do this., but I'll prefer to wait until a) is reviewed and decided what will be implemented (or not) 

admin 6.4.3
js-controller 4.0.24
running inside dev-server on node 16.17.0

Note: demo config is stored at repository mcm1957/ioBroker.jsonconfig-demo

**Comment by GermanBluefox** [comment]
a) done
b) 
![image](https://github.com/ioBroker/ioBroker.admin/assets/4582016/b32f38ad-2ac3-4aee-ba1e-5a8a02ab674b)

c) done

**Comment by mcm1957** [comment]
thanks
