### ISSUE TITLE
Fehler in GUI

### ISSUE THREAD

**Issue by taifun11** [ioBroker/ioBroker.admin#1937]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Feuer-sturm** [comment]
@taifun11 do you use automatic translation of the website e.g. with the Edge Browser? 
If yes, please deactivate this Feature.

**Comment by BenAhrdt** [comment]
Hier auch ein screenshot.

![image](https://user-images.githubusercontent.com/92173565/234939686-95c8d8f2-4980-4da1-8ba3-7bb5d69cebad.png)

**Comment by Feuer-sturm** [comment]
@BenAhrdt woraus schließt du, dass ihr beide den gleichen Fehler habt? Die angezeigten Fehler sind zumindest unterschiedlich. 
Wenn es ein anderer Fehler ist, bitte ein eigenes issue mit den entsprechenden Details und nicht nur mit einem Screenshot erstellen.

**Comment by taifun11** [comment]
Es war die automatische Übersetzung von Edge
