### ISSUE TITLE
Admin Version 3.1.11 kein Zugriff auf Grafik Tab

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#194]
Ich habe den History Adapter und Flot Adapter installiert.
Wenn ich History aktiviert habe und sehe ich, dass die Tabelle gefüllt wird.

Der "Grafik" Tab ist leider ausgegraut und kann nicht bedient werden.

**Comment by GermanBluefox** [comment]
Ist flot enabled?

**Comment by Marty56** [comment]
Yes, I have flot instantiated. In Tab "instances" flot appears but configuration is greyed out.

**Comment by GermanBluefox** [comment]
I asked about "enabled".
Is your instance active (runs)? Screenshot of instances tab?

2 мар. 2018 г. 6:18 пользователь "Marty56" <notifications@github.com>
написал:

**Comment by Marty56** [comment]
![bildschirmfoto 2018-03-02 um 10 06 45](https://user-images.githubusercontent.com/8623789/36891484-1bf1bcf4-1e02-11e8-950e-b73a3209896d.png)
![bildschirmfoto 2018-03-02 um 10 06 59](https://user-images.githubusercontent.com/8623789/36891485-1c161432-1e02-11e8-84f7-2bf292b75fbd.png)

**Comment by GermanBluefox** [comment]
iobroker list instance

 ?


Am 02.03.2018 10:11 schrieb "Marty56" <notifications@github.com>:

**Comment by Marty56** [comment]
Es scheint, dass flot disabled ist.

system.adapter.email.0                 : email       -  enabled
system.adapter.fakeroku.0              : fakeroku    -  enabled
system.adapter.feiertage.0             : feiertage   -  enabled
system.adapter.flot.0                  : flot        - disabled
system.adapter.harmony.0               : harmony     -  enabled
system.adapter.history.0               : history     -  enabled
system.adapter.hm-rega.0               : hm-rega     -  enabled
system.adapter.hm-rpc.0                : hm-rpc      -  enabled, port: 0

**Comment by Marty56** [comment]
Die Anleitung: 
How to use

install "web"-adapter and create one instance if not installed.
Select in settings of "web"-adapter the instance of installed "socket.io"-instance.
install "flot"-adapter and call

verstehe ich leider nicht.
Aber wenn das der Grund ist, dann können wir den Issue schließen. Vielleicht muss ich im Forum suchen.

**Comment by GermanBluefox** [comment]
iobroker start flot.0

2018-03-02 14:17 GMT+01:00 Marty56 <notifications@github.com>:
