### ISSUE TITLE
Admin does not use let's encrypt certificate collection from acme

### ISSUE THREAD

**Issue by dklinger** [ioBroker/ioBroker.admin#1940]
**Describe the bug**  
Not sure if it is live yet or not. But the certificate process via ioBroker.acme seems not work yet. I can aquire the certificates via acme adapter and also select it in the Admin adapter. But when opening admin instance, it's showing me a certificate error and, when checking the certificate, it's shown a self-signed one, created by ioBroker.

**To Reproduce**  
1. Configure acme adapater to retrieve certificates
2. Select collection in Admin adapter
3. Try to open Admin instance

**Expected behavior**  
Admin page opening with the certificate which was aquired by acme adapter.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/2249766/234256548-61e8c2b9-c1e8-4db0-9771-710f139dbd5a.png)
![image](https://user-images.githubusercontent.com/2249766/234255801-7a878b2d-ebbd-46b7-849f-1ed5183050d8.png)
![image](https://user-images.githubusercontent.com/2249766/234256669-d14167f5-b82d-438c-9603-67149afbe56a.png)
![image](https://user-images.githubusercontent.com/2249766/234256932-49b9ab69-3fe7-4d0a-81fc-d32be10c7d77.png)

**Versions:**  
 - Adapter version: 6.4.3
 - JS-Controller version: 4.0.24
 - Node version: v18.16.0
 - Operating system: docker - buanet

**Comment by dklinger** [comment]
Darn - that's good to know :D
Thanks!

**Comment by peterbaumert** [comment]
I have js-controller 5.0.6 and have the same issue.

```2023-07-03 20:40:04.832  - error: admin.0 (1394527) Cannot configure secure web server, because no certificates found: , ,```

**Comment by dklinger** [comment]
I am now on below verions and it is still loading the ioBroker GmbH certificate.

Adapter version: 6.10.1
JS-Controller version: 5.0.12
Node version: v18.17.1
Operating system: docker - buanet

**Comment by dklinger** [comment]
I have setup 2 collections and ACME shows status "OK" for both. I have tried selecting both of them in the Admin adapter, with fallback certificates set to none.

**Comment by mcm1957** [comment]
@foxriver76 
Could you üplease check / comment if this is still a problem?
The issue was created at april - several new release of admin / web and js-controller are out in the meantime.

**Comment by dklinger** [comment]
@foxriver76 
Yes, I checked 1-2 weeks ago after I've updated to the v5 JS controller. It still did not work. Let me gather a few details and update the thread.

**Comment by dklinger** [comment]
@foxriver76 
Admin is still always providing the ioBroker-cert:
![image](https://github.com/ioBroker/ioBroker.admin/assets/2249766/0e058f96-106c-4756-b2ed-7c5eeae57f20)

**Comment by mcm1957** [comment]
siehe auch:
https://forum.iobroker.net/topic/68286/acme-letsencrypt-zertifikate-auch-f%C3%BCr-web-adapter/5

Wobei es divergierende Aussagen gibt ob das hilft oder nicht

**Comment by dklinger** [comment]
Nope, hilft leider nicht.

**Comment by aSilentSniper** [comment]
Es hilft nichts weder im Admin noch im Web bekomme ich die ACME certs zum laufen auch nach lesen aller tips hier.

**Comment by peterbaumert** [comment]
Ja geht bei mir auch nicht. Mein issue wurde leider geschlossen.

**Comment by TA2k** [comment]
Auch bei mir war die einzige Lösung revert

admin auf v6.7.0
web auf v5.5.3

Dann geht alles normal ohne acme und update der certificate

**Comment by aSilentSniper** [comment]
Naja das kann ja keine lösung sein was sagen die Entwickler dazu?

**Comment by mcm1957** [comment]
> Naja das kann ja keine lösung sein was sagen die Entwickler dazu?
@Apollon77 @foxriver76

**Comment by aSilentSniper** [comment]
Schade das seit einem Monat da nichts zu gesagt wird

**Comment by mcm1957** [comment]
@Apollon77 @foxriver76 @bluefox

**Comment by foxriver76** [comment]
Unfortunately I have no touching point with this functionality currently. We had a fix one month ago https://github.com/ioBroker/webserver/commit/2355c345b5a7a08f842319fd130e2d823ca3e68b but this is already included in the current admin. So if someone which has a setup with public domain could look into this, would be much appreciated.

**Comment by dklinger** [comment]
Works with latest version of acme adapter (0.1.2).
