### ISSUE TITLE
[jsonConfig / Feature] possibility to cause refreh after sendTo

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#1943]
Please consider adding a possibility to issue an automatic REFRESH (Broser reload) auf the config screens after returning from "sendTo".

Usage:
The sendTo code inside an adapter could possibly modify some data, i.e. rewrite the configuration data. This will be visible at the instance gui only after a Browser Refresh / Reload. So it would be a nice feature if this reload could be triggered after returning from the sendTo if it is i.e. configured as an option to the element or is requested by a special flag within the return data.

**Comment by foxriver76** [comment]
Technically possible of course, however I am not sure about this workflow, the adapter would only change relevant data when it restarts (modifiying the instance object). Normally the workflow is, send stuff to backend -> backend answers -> display updated data in GUI and only modify the settings if `save` is pressed.

**Comment by mcm1957** [comment]
One use I thought about would be
- open configuration
- use sendTo to request some major task to be done by adapter code, i.e. updating the configuration by loading and merging some template data (or lets call it to import and merge configuration data which is not available as plain import provided as standard)
- the adapter code could do its task and rewrite configuration. Of course this would restart the adapter - but not the config UI session.
- now the user has to press reload to see the new data. This could be done automatically.

Yes, this could be done by some custom configuration - but the effort to implement this is significant and unuseable for developers not knowing react while using jsonConfig is streat ahead.

As an alternative the possibility to return much more complex data by the sendTo* functions could be an option which would allow to modifiy the complete configuration, i.e. adding elements to tables (incl. multiple tables) etc. Currently returned data can only be used to fill a single element. This approch would better match the "change config only at store pressed" cocept but for sure require much more effort to implement.

Background:
I'm searching a way to implement loading templates functionality to the snmp adapter. The template would contain oids and names etc. The data must be loaded into one (or ev. 2) tables. This import must not completely replace existing data and should not override existing entries. So the standard import is not useable for this (except by using export - starting external tool to merge -import approach)
