### ISSUE TITLE
Error opening instance config

### ISSUE THREAD

**Issue by Waldmensch1** [ioBroker/ioBroker.admin#1945]
**Describe the bug**  
iobroker.admin@5.1.25
socket.io.js:59 [2023-05-11T16:06:03.664Z] Try to connect
Instances.js:444 getInstances: 755
i18n.js:106 Translate: Add row
i18n.js:106 Translate: Delete current row
7react-dom.production.min.js:216 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%2C%20pl%2C%20zh-cn%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140:47)
    at d (react-dom.production.min.js:144:29)
    at v (react-dom.production.min.js:146:132)
    at react-dom.production.min.js:150:224
    at Ro (react-dom.production.min.js:176:171)
    at Ui (react-dom.production.min.js:271:134)
    at Cl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at El (react-dom.production.min.js:250:138)
    at ml (react-dom.production.min.js:243:163)
i

**To Reproduce**  
1. Open iCal config page

**Expected behavior**  
configpage of iCal plugin should open

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.admin/assets/57328533/be2e55e0-c906-4891-9039-d4bc01a10206)
![image](https://github.com/ioBroker/ioBroker.admin/assets/57328533/27a158ec-acbd-40b2-9900-0cc3f213c6ff)

**Versions:**  
 - Adapter version: iCal 1.13.2
 - JS-Controller version: 3.3.19
 - Node version: v14.18.1
 - Operating system: Ubuntu on odroid

**Additional context**

**Comment by Waldmensch1** [comment]
Looks that this Adapter need a newer Admin Version but this was not shown in dependencies while Adapter upgrade. Downgrading Adapter solved the issue

**Comment by Diginix** [comment]
ical 1.13.2 works fine here with admin v6 and JS-Controller v4. 
You should probably update your system than downgrading an adapter.

**Comment by mcm1957** [comment]
> ical 1.13.2 works fine here with admin v6 and JS-Controller v4.
> You should probably update your system than downgrading an adapter.

That might be a recommandation. BUT ical should check its prerequists adn require usaeable versions of admin / js-controller / ...

**Comment by Diginix** [comment]
Your JS-Controller is since 4 months obsolete and v4 is stable since then. Maybe your old controller does not support such checks. Not all is done by the adapter irself.

**Comment by mcm1957** [comment]
Current rquirements of ical adapter:

                "js-controller": ">=2.0.0"
                "admin": ">=5.3.2"

**Comment by Diginix** [comment]
And @Waldmensch1 uses admin 5.1.25.

**Comment by mcm1957** [comment]
OK - just seen ...
So the requirement of admin is not fulfilled. 

Don't know where this check should trigger and prohibit an installation or output a warning at least.

**Comment by Waldmensch1** [comment]
> OK - just seen ... So the requirement of admin is not fulfilled.
> 
> Don't know where this check should trigger and prohibit an installation or output a warning at least.

Update is shown in green for iCal, that's why I trusted installation is safe
![image](https://github.com/ioBroker/ioBroker.admin/assets/57328533/1f37e47a-ad4f-409f-a663-3ee08aa522a9)

Other Adapters show their dependencies and appear in red.
![image](https://github.com/ioBroker/ioBroker.admin/assets/57328533/91baceb8-9af8-45e0-ad69-a05f413d8619)

if dependency checks are done, they should be correct, isn't it? I don't know how an auto-update would react
