### ISSUE TITLE
System settings: Tab Let's Encrypt: Read more link not clickable

### ISSUE THREAD

**Issue by josefglatz** [ioBroker/ioBroker.admin#1949]
Looks like the frontend HTML/CSS markup needs a small fix.

The following link shown in the screenshot is not clickable:
![image](https://github.com/ioBroker/ioBroker/assets/2861556/2def2779-fffc-46b3-99ed-be38381bc5c2)

The reason seems like is the overlapping <div/> which overlops the info text above:

![image](https://github.com/ioBroker/ioBroker/assets/2861556/15c59204-4f62-4bdc-8f32-876bff4ccf26)

**Comment by Apollon77** [comment]
I moved it into the correct repo. Thank you for reporting
