### ISSUE TITLE
"Install a specific version" in List Mode

### ISSUE THREAD

**Issue by vdemidov** [ioBroker/ioBroker.admin#195]
In List Mode of  Adapters view. If you enable Expert mode and press button "Install a specific version" of any adapter, popup window with list of versions will open in wrong position and with very big font size.
![admin_install_adaper_version](https://user-images.githubusercontent.com/922943/36140416-e541eb8a-10a9-11e8-872d-892d57a9c459.png)

**Comment by eumats** [comment]
See also #185

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/185
