### ISSUE TITLE
Upgrade  6.4.4 --> 6.5.3  nicht möglich

### ISSUE THREAD

**Issue by Harry-58** [ioBroker/ioBroker.admin#1950]
Der Upgrade des Adapters ist nicht möglich.

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/56926733/4b60f209-7507-4c76-868d-dfc0790af110)

Im Log stehen keine Fehlermeldungen.
Auch der Update über die Oberfläche ist nicht möglich.

 - Adapter version: 6.4.4 --> 6.5.3
 - JS-Controller version:  4.0.24
 - Node version: v18.16.0
 - Operating system:   Raspbian (Linux) Pi4

Alle Adapter und System auf aktuellem Updatestand.

**Comment by Apollon77** [comment]
Bitte mit --debug aufrufen und je nach Fehlerdetails dann reagieren

**Comment by Harry-58** [comment]
Die Ursache waren Probleme beim rename
npm ERR! ENOTEMPTY: directory not empty, rename '/opt/iobroker/node_modules/unix-dgram' -> '/opt/iobroker/node_modules/.unix-dgram-n2LIi0YN'

Nicht nur diese Datei, sondern dutzende weitere. 
Nach dem löschen aller ging der Update.

**Comment by Apollon77** [comment]
Ja, ist ein npm issue
