### ISSUE TITLE
Admin 6.5.3 -- weiße Seite

### ISSUE THREAD

**Issue by Negalein** [ioBroker/ioBroker.admin#1952]
Seit Admin 6.5.3 komm ich nicht mehr auf die Oberfläche.
Es bleibt bei einer weißen Seite.

In der Browserkonsole kommt dieser Fehler.
Getestet mit Chrome & Edge.
Mit FF keine Probleme!

```
chrome-extension://njgehaondchbmjmajphnhlojfnbfokng/js/contentScripts/dom.js:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
bootstrap.jsx:19 iobroker.admin@6.5.3
sdk.ts:121 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at propertyIsEnumerable (<anonymous>)
    at Object.Qr (sdk.ts:121:1)
    at 52898 (bootstrap.jsx:68:5)
    at Function.n (bootstrap:19:32)
```

**Comment by RP70DP** [comment]
Gestern ging es bei mir noch mit FF. Heute selbe Meldung mit FF.

**Comment by peer69** [comment]
+1

**Comment by Diginix** [comment]
same here
Browser refresh solves it until next blank screen.

**Comment by Megawaldi** [comment]
Same here

**Comment by Narolakk** [comment]
+1

**Comment by dekatWin** [comment]
Ich bin auch von dem Bug betroffen, es hat vielleicht mit der Anzeige zu tun, wenn ich einen Bildschirm an mein Windows 10 Nuc anschließe, verschwindet die weiße Seite, doch wenn ich versuche nur über das Admin Web Panel darauf zuzugreifen, ohne angeschlossenen Bildschirm erhalte ich nur die weiße Seite.

**Comment by j1s2e3** [comment]
Same here. I get a white page instead of the login dialog. But only with Firefox. Chrome still works.

I'm using latest Ubuntu 22.04 LTS.
Firefox version 113.0.2 (snap)
Chrome  version 113.0.5672.126

Here is the error message from firefox:
![ff](https://github.com/ioBroker/ioBroker.admin/assets/92024911/236e9a09-eab5-4752-88e1-945cd4efaca5)

**Comment by GermanBluefox** [comment]
Can someone reproduce this error with opened developer console? So I can see the exactly place, where error occurs.

**Comment by Marc-Berg** [comment]
This is the content of the console when the error occurs

`22:23:24.585 [2023-05-30T20:23:24.585Z] ws connection error: CLOSE_GOING_AWAY 3651.2439ca53.chunk.js:16:171
    xt http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:16
    error http://debian11.fritz.box:8081/lib/js/socket.io.js:68
    onclose http://debian11.fritz.box:8081/lib/js/socket.io.js:177
    (Async: EventHandlerNonNull)
    connect http://debian11.fritz.box:8081/lib/js/socket.io.js:173
    connect http://debian11.fritz.box:8081/lib/js/socket.io.js:43
    startSocket http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:594
    Yn http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:1
    Yn http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:1
    startSocket http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:594
    C http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:594
    (Async: promise callback)
    C http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:594
    $ http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:594
    componentDidMount http://debian11.fritz.box:8081/static/js/3589.df119534.chunk.js:73
    Zs http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    Gs http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    Xc http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    bc http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    $n http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    bs http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    Ln http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:24
    Gn http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:24
    (Async: EventHandlerNonNull)
    41196 http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:24
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    72851 http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:24
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    57799 http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:9
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    73961 http://debian11.fritz.box:8081/static/js/3961.36e663dd.chunk.js:16
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    I http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    e http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:2
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    24470 http://debian11.fritz.box:8081/static/js/3651.2439ca53.chunk.js:463
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    52898 http://debian11.fritz.box:8081/static/js/3589.df119534.chunk.js:1
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    (Async: promise callback)
    72063 http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    n http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:1
    <anonym> http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:4
    <anonym> http://debian11.fritz.box:8081/static/js/main.1df2f32f.js:4
22:23:24.589 [2023-05-30T20:23:24.590Z] Start reconnect 0 3651.2439ca53.chunk.js:16:171
22:23:24.719 [2023-05-30T20:23:24.719Z] Try to connect 3651.2439ca53.chunk.js:16:171
22:23:24.957 Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.53.0. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).
22:23:25.009 Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. debian11.fritz.box:8081
22:23:26.138 iobroker.admin@6.5.3 bootstrap.jsx:19:8
22:23:26.145 Uncaught (in promise) TypeError: can't convert undefined to object
    Qr sdk.ts:121
    52898 bootstrap.jsx:68
    Webpack 5
sdk.ts:121
    Qr sdk.ts:121
    52898 bootstrap.jsx:68
    Webpack 5
`

**Comment by Negalein** [comment]
> Can someone reproduce this error with opened developer console? So I can see the exactly place, where error occurs.

mehr kommt bei Chrome nicht

```
chrome-extension://njgehaondchbmjmajphnhlojfnbfokng/js/contentScripts/dom.js:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
bootstrap.jsx:19 iobroker.admin@6.5.3
sdk.ts:121 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at propertyIsEnumerable (<anonymous>)
    at Object.Qr (sdk.ts:121:1)
    at 52898 (bootstrap.jsx:68:5)
    at Function.n (bootstrap:19:32)
```

**Comment by dekatWin** [comment]
Meinst du die ganze Konsole?
![image](https://github.com/ioBroker/ioBroker.admin/assets/111662370/46b692cc-7d29-48b4-881b-53e7fa825bc0)

**Comment by dekatWin** [comment]
Hier mal das ganze Chrome Dev Board, zu dem Bug:
![Screenshot 2023-05-31 02 13 59](https://github.com/ioBroker/ioBroker.admin/assets/111662370/1f8c2995-56ea-42d5-9f56-dde59cb44ec0)

**Comment by syberx** [comment]
Auch seit Tagen das Problem das Admin nicht mehr richtig will.. bekomme diese Meldung :
```
caught (in promise) TypeError: Cannot convert undefined or null to object
    at propertyIsEnumerable (<anonymous>)
    at Object.Qr (sdk.ts:121:1)
    at 52898 (bootstrap.jsx:68:5)
    at Function.n (bootstrap:19:32)
Qr @ sdk.ts:121
52898 @ bootstrap.jsx:68
n @ bootstrap:19
Promise.then (async)
72063 @ index.jsx:1
n @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ main.1df2f32f.js:4
```

**Comment by ticaki** [comment]
Mac Mini M1 Safari 16.5

```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'Bn(ie({},B),{stackParser:R2(B.stackParser||Da),integrations:Z2(B),transport:B.transport||(Nt()?di:vi)})')
	propertyIsEnumerable (3651.2439ca53.chunk.js:19:23620)
	Qr (3651.2439ca53.chunk.js:19:23620)
	52898 (3589.df119534.chunk.js:74:11325)
	n (main.1df2f32f.js:1:318)
	n
```

mehfaches Kicken auf Reload sorgt am und an für ein fehlerfreies Laden

**Comment by Bulls91** [comment]
habe das gleiche Problem mit Safari auch in der heute veröffentlichten Admin 6.5.4

Der Fehler besteht auch auf den iOS Geräten

**Comment by GermanBluefox** [comment]
Ich habe versucht einen Work-Around in 6.5.4 einzubauen. Aber warum das so ist, weiß ich nicht.

**Comment by Bulls91** [comment]
kann ich bestätigen mit 6.5.5 läuft alles wieder einwandfrei

**Comment by Narolakk** [comment]
Leider immer noch das gleiche Problem.

![image](https://github.com/ioBroker/ioBroker.admin/assets/48066111/76800388-97cd-408c-ad32-b2bb96200ace)

**Comment by Negalein** [comment]
mit 6.5.5 läuft es derzeit wieder fehlerfrei

**Comment by ticaki** [comment]
Bei mir läuft es anderes. Gerade eben hatte ich X autoreloads der Seite bis ich mich einloggen konnte.

**Comment by dekatWin** [comment]
Chrome, Windows 10, Admin v6.5.5
Das Problem besteht bei mir in anderer Form immer noch:
(Aber die weiße Seite stört mich jetzt kaum noch.)

1. Man sieht die weiße Seite für ca. 1-2 Sekunden.
2. Animation des Ladebalkens für ca. 1-2 Sek.
3. Für ca. 5 Sekunden wird wieder eine weiße Seite angezeigt.
4. Login-Panel erscheint.
5. Nach dem Login erscheint für ca. 1 sec. wieder eine weiße Seite.
6. Gefolgt von der Ladebalken Kreis Animation für ca. 1 Sek.
7. Danach ist bei jedem Seiten Reload für ca. 1-2 Sek. erneut ne weiße Seite zu sehen.
8. Wie immer gefolgt von einer Ladebalken Kreis Animation für ca. 1-2 sek.

**Comment by ticaki** [comment]
Zusätzliche Infos:
Admin 6.5.5

Hat das gerade wiede,r jedoch hat er trotz 40+ Reloads nicht die Iobrokerseite angezeigt. Der Prozess io.admin.0 hat 60% der CPU Leistung belegt (Raspberry 4). Neustart von Safari hat das Problem behoben.

**Comment by dekatWin** [comment]
Hier mal der neue Auto Reload Bug auf Video:
[untitled.webm](https://github.com/ioBroker/ioBroker.admin/assets/111662370/a0d2f17f-5e1c-40fe-8569-551a7fad4d6e)

**Comment by GermanBluefox** [comment]
Es scheint jetzt klarer zu sein. Von heute auf morgen hat angefangen craco-esbuild modul Probleme zu machen. Nicht nur bei admin. Ich habe jetzt Plugin deaktiviert und es scheint in 6.5.6 zu funktionieren.

**Comment by dekatWin** [comment]
- Die weiße Seite vor dem login Panel ist noch da, aber nur noch sehr kurz, ca. 1 Sekunde.
- Der Mehrfach-Auto-Reload-Bug scheint behoben zu sein.
thanks for fixing it.

**Comment by Feuer-sturm** [comment]
@Negalein Tritt das problem bei dir noch mit der aktuellen Admin Version 5.6.7 auf? Bei mir ist das Problem mit der aktuellen Version nicht mehr aufgetreten.
Wenn es bei dir i.O. ist, bitte issue schließen.

**Comment by Negalein** [comment]
> Wenn es bei dir i.O. ist, bitte issue schließen.

Ja, läuft wieder.
Hab es noch wegen @dekatWin offen gelassen.
Da er sich nicht mehr gemeldet hat, denke ich läufts bei ihm mit 6.5.7 auch wieder.
