### ISSUE TITLE
6.5.3  scripts export - file not found 404

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#1953]
System: iobroker latest, admin 6.5.3, js-controller 5.01, javascript Adapter 7.0.3, Node 18.16.0, NPM 9.5.1, Debian Bullseye, Syno VM.

Function "export all scripts" in javascript-adapter is not working any more, the file is not found, tested with chrome and firefox:
![image](https://github.com/ioBroker/ioBroker.admin/assets/36229898/5278d71f-46de-434d-a03e-1b0c1243acad)

**Comment by GermanBluefox** [comment]
This behavior is indeirect fixed. When this PR will be merged it will work again: https://github.com/ioBroker/ioBroker.js-controller/pull/2278

**Comment by Ilovegym66** [comment]
Hi, small state update with js-controller 5.0.2 beta, and Admin 6.5.7, the error is not fixed.. 
A backup is not possible in the moment... can I something do to fix it temporary ???

`ilovegym@iobrokerS2:/opt/iobroker$ iob backup
Parsing error on getStates("io.system.host.iobrokerS2.zip.2023-06-12-scripts.zip"), returning "null" for "PK
���Vcommon/PK
���V|DK*  common/_dir.json{
  "_id": "script.js.common",
  "common": {
    "name": "common"
  },
  "type": "channel",
  "native": {},
  "from": "system.host.iobrokerS2.cli",
  "ts": 1686580182521,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}PK
���Vcommon/Alarme/PK
���V�s�wKKcommon/Alarme/_dir.json{
  "common": {
    "name": "Alarme",
    "expert": true
  },
  "type": "channel",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1669360385573,
  "_id": "script.js.common.Alarme",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}PK
`

**Comment by Ilovegym66** [comment]
update: 
With js-controller 5.0.3 the backup is working now again:
`
ilovegym@iobrokerS2:/opt/iobroker$ iob backup
host.iobrokerS2 93302 states saved
host.iobrokerS2 113031 objects saved
Backup created: /opt/iobroker/backups/2023_06_14-09_36_10_backupiobroker.tar.gz
This backup can only be restored with js-controller version up from 4.1
ilovegym@iobrokerS2:/opt/iobroker$

`

Export of the scripts with javascript 7.1.0 and js-controller 5.0.3 and Admin 6.5.8 are not working, file not found.
![image](https://github.com/ioBroker/ioBroker.admin/assets/36229898/b58d5cea-c5db-4869-93a1-a46550929361)

**Comment by GermanBluefox** [comment]
Fixed with javascript 7.1.1

**Comment by Diginix** [comment]
Doesn't work for me with JS 7.1.1 and Controller 4.0.24 and nodejs 16.
