### ISSUE TITLE
better sorting for variables

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.admin#1955]
Hi,
not a problem, but sometimes confusing:

NOW variables are sorted by number, not respecting the magnitude (count of digits in a number)
eg:
1000 ...
120 ...
14 ...

in FUTURE better sorting like this:
14 ...
120 ...
1000 ...

Thank You for looking into this!

By the way: thin about inserting a level for "programs" and "variables", as variables are use often in history database 

cu
Harvey

**Comment by Apollon77** [comment]
Hi, what exactly you mean? Admin Adapter is General iobroker admin ui and on that level there are no variables or such. Please maybe show a screenshot on what exactly you mean.

**Comment by mcm1957** [comment]
Ok, you refer to sorting of **State Ids**. 

State Ids are defined as text strings. So sorting will occure based an text a nd not based on numeric value. Whether a special handling for numeric only states should (and can) be implemented must be discussed. But keep in mind that states with ids X10, X100, ... will be sorted textual in any case. Ans sorting for adapter having both - pure numeric and testual ids would add extra effort.

**Comment by Apollon77** [comment]
yes state ids are text and so sorted as text. it is not posible to detect that really and honestly ... that is very error prone, I close this request.
