### ISSUE TITLE
Remove HTTP certificate options. All that is required is one 'Use HTTPS' option.

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#1962]
As discussed in dev forum, the new ACME collections mechanism does not need the user to choose a certificate. If the user wants HTTPS, they simply have to choose a single boolean option to state that - the new webserver mecahnism will then automatically choose to use an ACME certificate for the target domain if available, and if not will fall back to self signed.

This not only applies to admin, but in fact all adapters that want to fire up a webserver, but, erm... is there an elegant way to do that?

**Comment by Apollon77** [comment]
It we also need this on web and the other adapters where we originally have letsencryp in or!! Or where you can select ssl CERTs?

**Comment by raintonr** [comment]
> But we also need this on web and the other adapters where we originally have letsencryp in or!! Or where you can select ssl CERTs?

It should not be necessary to select certs when using new web module. That is the point.

**Comment by raintonr** [comment]
Still there in 6.10.1 (see #2122). What happened?
