### ISSUE TITLE
BUG. In expert mode, install a specific version

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#197]
![122](https://user-images.githubusercontent.com/11523624/36157166-cbc6caa6-110b-11e8-8943-8a92a6b54a78.gif)

**Comment by vdemidov** [comment]
Duplicate of my issue https://github.com/ioBroker/ioBroker.admin/issues/195

**Comment by eumats** [comment]
#185

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/195
