### ISSUE TITLE
[jsonConfig / Feature] related to element ip

### ISSUE THREAD

**Issue by pdbjjens** [ioBroker/ioBroker.admin#1971]
**Is your feature request related to a problem? Please describe.**
Currently the jsonConfig control element "ip" supports filtering the available ip addresses of the host for "onlyIP4" and "onlyIP6"
In some cases it is neccessary to filter out  internal IPs  if the network interface is a loopback  (e.g. 127.0.0.1) or similar internal interface that is not remotely accessible and thus should not be offered to the user for selection.

**Describe the solution you'd like**
A new confiuration option should be added to the [JsonConfigComponent](https://github.com/ioBroker/ioBroker.admin/tree/master/src/src/components/JsonConfigComponent) /ConfigIP.jsx and in SCHEMA.md

`ip - bind address

listenOnAllPorts - add 0.0.0.0 to option
onlyIp4 - show only IP4 addresses
onlyIp6 - show only IP6 addresses
noInternal - do not show internal IP addresses
`
This directly maps to the os.networkInterfaces() internal property:

**internal** (boolean): true if the network interface is a loopback or similar interface that is not remotely accessible; otherwise false

**Describe alternatives you've considered**
If the user is able to select internal interface IPs, this needs to be caught by the adapter and an error message will have to issued, which might confuse the user. It would be much better if the user would not be able to select the internal interfaces in the first place.

**Additional context**
It should be quite simple and having hardly any side-effects to add the confiuration option "noInternal" to ConfigIP.jsx

              if (!this.props.schema.listenOnAllPorts) {
                    ips = ips.filter(item => item.address !== '0.0.0.0' && item.address !== '::');
                }
                if (this.props.schema.onlyIp4) {
                    ips = ips.filter(item => item.family === 'ipv4');
                } else
                if (this.props.schema.onlyIp6) {
                    ips = ips.filter(item => item.family === 'ipv6');
                }
                if (this.props.schema.noInternal) {
                    ips = ips.filter(item => item.internal === false);
                }

**Comment by GermanBluefox** [comment]
Very good described Issue. Thank you!
