### ISSUE TITLE
Admin 3 installed with "stable / default" repository

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.admin#198]
If a user comes with a "fresh" Raspberry with a Stretch-Image and installs ioBroker via the normal rpm-commands, the there will be a very interesting combination:
- The repositories are ok
- The current repo is "stable"
- But the user will get admin v3 installed - it is only available in repo "latest", not in "stable/default"

See attached screenshots.
![image_01](https://user-images.githubusercontent.com/18639287/36345389-998c6782-1429-11e8-80c2-b251d0f476d9.png)
![image_02](https://user-images.githubusercontent.com/18639287/36345390-99a7ee9e-1429-11e8-921a-875a6cae1789.png)

Greetings,
Eric

**Comment by Apollon77** [comment]
The current dependency from js-controller is to install an Admin with ">=2.0.9" ... I fear that this also includes 3.x releases ... 
@GermanBluefox change dependecy in js-controller? but we would need to release an update then ...

**Comment by GermanBluefox** [comment]
It is because of https://github.com/ioBroker/ioBroker/blob/master/lib/setup.js#L437.
There must be explicit version: `npmInstall('iobroker.admin@2.0.9', ....`

**Comment by GermanBluefox** [comment]
And the same for js-controller and discovery

**Comment by Apollon77** [comment]
fixed in iobroker 1.1.1 and js-controller 1.2.6 (upcoming)
