### ISSUE TITLE
VIS2 Licence cannot be checked

### ISSUE THREAD

**Issue by AxelG-DE** [ioBroker/ioBroker.admin#1995]
**Describe the bug**  
I went to iobroker.net, converted my VIS.0 license to Vis-2 with new UIDD and pasted it into the adapter. Then clicked on "Check license" and I get an error

**To Reproduce**  
see above

**Expected behavior**  
License accepted and adapter working

**Screenshots & Logfiles**  
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/49004103/32809a32-727f-4a9b-ae1a-047ea02e3cb0)

and I get:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/49004103/e3d43073-c78a-449c-bce9-08c211abf1b8)
2nd try:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/49004103/8e317723-b42b-46c1-9284-ae333d89786f)

Indeed here the real link (from the second try:
https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BCountry%2C%20Name%2C%20FirmName%2C%20AddressLine1%2C%20AddressLine2%2C%20ZIP%2C%20City%7

The link gives then:
`Objects are not valid as a React child (found: object with keys {Country, Name, FirmName, AddressLine1, AddressLine2, ZIP, City). If you meant to render a collection of children, use an array instead.`

**Versions:**  
 - Adapter version: 2.1.4
 - JS-Controller version: 4.0.24
 - Node version: 16.20.1 (EDIT: now 18.17.0)
 - Operating system: Linux Gentoo

**Additional context**  
I also tried to pause the VIS.0 to no avail.
Tried "License Manager" (before and after converting the license) to no avail

**Comment by AxelG-DE** [comment]
I am surprised, the link in the error-page guided me to iobroker.admin but not to iobroker.vis

Feel free to move, if possible at all....

**Comment by AxelG-DE** [comment]
I have updated node.js to 18.17.0 but still same result

**Comment by foxriver76** [comment]
which version of admin do you use? It could be fixed with `6.6.1`

**Comment by AxelG-DE** [comment]
@foxriver76 admin is 6.3.5, which is the latest in the stable branch, as far as I can see. You recommend me to go to beta here. I hope that comes with no risks

**Comment by AxelG-DE** [comment]
without updating yet, I just switched the repo and it gives me 6.4.3. as the latest beta...

**Comment by AxelG-DE** [comment]
@foxriver76 
you added the fixed label, but how can I appreciate the fix? I tried to verify my license and still get the same bug. :face_in_clouds:

**Comment by foxriver76** [comment]
Not yet in stable

**Comment by AxelG-DE** [comment]
I upgraded admin to 6.4.3 and now I get: 

```
TypeError: n[h] is undefined
    renderMessageDialog ConfigCheckLicense.jsx:93
    renderMessageDialog ConfigCheckLicense.jsx:84
    renderMessageDialog ConfigCheckLicense.jsx:78
    renderItem ConfigCheckLicense.jsx:476
    render ConfigGeneric.jsx:541
    React 8
    Ln scheduler.production.min.js:13
    Gn scheduler.production.min.js:14
```

A bit frustrating, that it seems I am the only one cannot make VIS2 running. What am I missing?

**Comment by foxriver76** [comment]
6.4.3 does not have the fixes, if important click on the icon for expert mode and then on adapters tab on the cat and then install admin from npm.

**Comment by AxelG-DE** [comment]
besides expert mode, I am afraid I should have switched beta repo? I switched back to stable in between... -because it installs for ages already, seems to stuck
