### ISSUE TITLE
Switching to 'Adapters' showing Error 'Cannot get adapters info: TypeError: Attempted to assign to readonly property.'

### ISSUE THREAD

**Issue by pixelchrome** [ioBroker/ioBroker.admin#1997]
**Describe the bug**  
When I switch in the WubUI in 'Adapters' the Error 'Cannot get adapters info: TypeError: Attempted to assign to readonly property.' is shown

**To Reproduce**  
1. Open the WebUI
2. Click on 'Adapter'
3. See error  'Cannot get adapters info: TypeError: Attempted to assign to readonly property.' and Adapters are not being loaded

**Expected behavior**  
Adapter should be shown.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: 4.0.23
 - Node version: v16.20.1
 - Operating system: docker - Host is Ubuntu 22.04

**Additional context**  
<img width="592" alt="Screenshot 2023-07-23 at 16 11 51" src="https://github.com/ioBroker/ioBroker.admin/assets/10322584/e57180e8-8c5c-456b-81a8-c4942d4b348f">

iobroker info
Platform       : docker
os             : linux
Architecture   : x64
CPUs           : 12
Speed          : 1883 MHz
Model          : AMD Ryzen 5 PRO 4650GE with Radeon Graphics
RAM            : 62.2 GB 
System uptime  : 2d. 21:00:02
Node.js        : v16.20.1
time           : 1690121644653
timeOffset     : -120
adapters count : 1210
NPM            : v8.19.4
Disk size      : 100.0 GiB
Disk free      : 17.8 GiB

**Comment by foxriver76** [comment]
I cannot replicate this with 6.6.1 and the version of admin is missing in your ticket.

**Comment by pixelchrome** [comment]
Any idea how to troubleshoot this behavior?

**Comment by mcm1957** [comment]
What about starting by specifying the involved admin release as foxriver asked at last posting?

**Comment by pixelchrome** [comment]
I can't tell you why... but I can see the 'adapters' again. Is it possible that there are some dns blocklists out there that prevent the loading of the adapters (that is the only thing I've changed)
