### ISSUE TITLE
change "label" attribute within jsonConfig.json to i18n multi-language

### ISSUE THREAD

**Issue by walburgf** [ioBroker/ioBroker.admin#2001]
**Is your feature request related to a problem? Please describe.**
The "label" attribute of the "staticText" and "staticLink" definition within jsonConfig.json are defined as multi-language text (i18n):

- staticText - static text like description
    label - multi-language text
    text - same as label

The "label" attribute of the "select" definition and some others are not defined as multi-language text. Translations can only be applied within the select definition.

- select
       options - [{label: {en: "option 1"}, value: 1}, ...]

**Describe the solution you'd like**
Please change all "label" attributes to be multi-language text.

**Describe alternatives you've considered**
n/a

**Additional context**
This makes implementation of multi-language much easier and consistent.

**Comment by mcm1957** [comment]
Did you try it?
As far as I remember ALL labels are translated when using i18n environment.

Feel free to check with mcm1957/iobroker.jsonConfig-demo adapter.

**Comment by walburgf** [comment]
I tested it again and detected an error in my implementation ....
So it's working....
Thank you fpr the spport !
