### ISSUE TITLE
Erster Log nach "dauerhaft von der Disk löschen", wird nicht aufgeführt

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2002]
Wenn man die logs löscht, so wird der erste Log nach dieser Aktion nicht im Logfenster angezeigt.

![logs-buanet-iobroker_8_0_1-Google-Chrome-2023-07-27-12-02-04 (1)](https://github.com/ioBroker/ioBroker.admin/assets/92173565/32b42e3d-99b3-447d-8dbf-6bbd85b580d2)

**Comment by Feuer-sturm** [comment]
@BenAhrdt taucht der Eintrag den im logfile auf wenn du es herunterlädst?

**Comment by BenAhrdt** [comment]
@Feuer-sturm ich habe geahnt dass diese Frage kommt. Komme allerdings aktuell nicht dran.

**Comment by foxriver76** [comment]
Admin Version? Ich habe das mal versucht nachzustellen, allerdings läuft es bei mir korrekt.

**Comment by foxriver76** [comment]
Ah laut Video 6.3.6? Dann villt nochmal probieren mit 6.6.X

**Comment by BenAhrdt** [comment]
@foxriver76 bei mir sehe man ch selbst mit dem Beta repo nur die 6.5.6

**Comment by foxriver76** [comment]
Mittlerweile ist ja 6.8.0 stable, damit dieses Problem reproduzierbar?

**Comment by Feuer-sturm** [comment]
@BenAhrdt tritt das Problem noch mit der aktuellen stable version (6.10.1) auf oder kann das issue geschlossen werden?

**Comment by Feuer-sturm** [comment]
Can not reproduce it with admin 7.4.8
@BenAhrdt I close this issue. If it is still present with current admin, please comment here and we will reopen the issue.

**Comment by BenAhrdt** [comment]
> Can not reproduce it with admin 7.4.8 @BenAhrdt I close this issue. If it is still present with current admin, please comment here and we will reopen the issue.

it looks like it is ok.

**Comment by Feuer-sturm** [comment]
Thanks @BenAhrdt
