### ISSUE TITLE
Adapter "Liesmich" wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Gosuwaldbear** [ioBroker/ioBroker.admin#2003]
Bei den Adaptern können die Infos nicht mehr angezeigt werden:

<img width="306" alt="Bildschirmfoto 2023-07-28 um 14 24 27" src="https://github.com/ioBroker/ioBroker.admin/assets/35446177/90ffc2c6-4cc3-4109-853c-b8b5a1694f6e">

Fehler:
TypeError: null is not an object (evaluating 'this.state.text')
value — AdapterInfoDialog.jsx:194
Po — react-dom.production.min.js:204:189
ks — react-dom.production.min.js:280:392
ys — react-dom.production.min.js:280:323
vs — react-dom.production.min.js:280:180
us — react-dom.production.min.js:271:91
as — react-dom.production.min.js:268:432
as
S — scheduler.production.min.js:13:205
T — scheduler.production.min.js:14:128

 - Adapter version: admin 6.6.4
 - JS-Controller version: 5.0.9
 - Node version: v18.17.0
 - Operating system: macOS 13.5
 - Safari 16.6
 - Chrome 115.0.5790.114
 - NPM: 9.6.7

**Comment by foxriver76** [comment]
fixed in next version by https://github.com/ioBroker/ioBroker.admin/commit/65ba53dec9811a5543152f14080a71e144fccd46
