### ISSUE TITLE
Error in GUI Admin 6.6.4 / MQTT

### ISSUE THREAD

**Issue by Bernd9000** [ioBroker/ioBroker.admin#2008]
**Describe the bug**  
Error in GUI when opening instance settings of mqtt adapter.

**Screenshots & Logfiles** 

![Unbenannt](https://github.com/ioBroker/ioBroker.admin/assets/77005685/962d9bf3-603e-4e30-91ff-f6209d7dca27)

TypeError: undefined has no properties
    value ChipInput.jsx:573
    React 8
        Po
        No
        Ei
        ks
        ys
        vs
        us
        as
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    36813 scheduler.production.min.js:14
    Webpack 18
        t
        45296
        t
        34463
        t
        54164
        t
        I
        e
        t
        1250
        t
        16677
        t
        promise callback*77569
        t
        <anonymous>
        <anonymous>
instrument.ts:132
TypeError: undefined has no properties
    value ChipInput.jsx:573
    React 8
        Po
        No
        Ei
        ks
        ys
        vs
        us
        as
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
    36813 scheduler.production.min.js:14
    Webpack 18
        t
        45296
        t
        34463
        t
        54164
        t
        I
        e
        t
        1250
        t
        16677
        t
        promise callback*77569
        t
        <anonymous>
        <anonymous>
instrument.ts:132

​

**Versions:**  
 - Adapter version: <6.6.4>
 - JS-Controller version: <5.0.10>
 - Node version: <18.17.0>
 - Operating system: <Windows 11>

**Comment by Feuer-sturm** [comment]
Duplicate with #2006
