### ISSUE TITLE
Error in GUI! Adapter Helpsite

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2012]
**Describe the bug**  
Error in GUI!
Beim Anklicken des Fragezeichens in Adapter - 3 Punkte - Fragezeichen bekomme ich diesen Fehler 

**To Reproduce**  
Dieser kommt bei mir auch nach einem Reload, reboot/restart iobroker/system hab ich noch nicht ausgeführt.

**Expected behavior**  
Die Hilfeseite soll angezeigt werden.

**Screenshots & Logfiles**  

```
[Error] Failed to load resource: the server responded with a status of 404 () (fakeroku.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (rssfeed.png, line 0)

[Error] TypeError: null is not an object (evaluating 'this.state.text')
value — AdapterInfoDialog.jsx:194
Po — react-dom.production.min.js:204:189
ks — react-dom.production.min.js:280:392
ys — react-dom.production.min.js:280:323
vs — react-dom.production.min.js:280:180
us — react-dom.production.min.js:271:91
ss — react-dom.production.min.js:273:303
ss
Hl — react-dom.production.min.js:127:105
(anonyme Funktion) — react-dom.production.min.js:267:273

	(anonyme Funktion) (6488.4f805dd7.chunk.js:2:115438)
	fo (4164.29c179b8.chunk.js:2:71896)
	(anonyme Funktion) (4164.29c179b8.chunk.js:2:72413)
	Ua (4164.29c179b8.chunk.js:2:53538)
	wi (4164.29c179b8.chunk.js:2:101355)
	ki (4164.29c179b8.chunk.js:2:100923)
	bi (4164.29c179b8.chunk.js:2:100459)
	(anonyme Funktion) (4164.29c179b8.chunk.js:2:112296)
	Ss (4164.29c179b8.chunk.js:2:112809)
	ss (4164.29c179b8.chunk.js:2:106530)
	ss
	Hl (4164.29c179b8.chunk.js:2:46922)
	(anonyme Funktion) (4164.29c179b8.chunk.js:2:103925)
```
**Versions:**  
Node.js: v18.17.0
NPM: 9.6.7
js-controller: 5.0.10
admin: v6.6.4

Client:
Mac mini Apple M1
System: 13.4.1 (22F82)
Safari: Version 16.5.1 (18615.2.9.11.7)

**Comment by bicmac** [comment]
same here for me. If i try to open the help for admin Adapter i get the same error.
here the output from Browser Console:

`[ADAPTERS] admin
github.com/iobroker-community-adapters/ioBroker.fakeroku/master/admin/fakeroku.png:1     Failed to load resource: the server responded with a status of 404 ()
raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png:1     Failed to load resource: the server responded with a status of 404 ()
instrument.ts:132 TypeError: Cannot read properties of null (reading 'text')
    at a.value (AdapterInfoDialog.jsx:194:25)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:132`

Versions:
Node.js: v16.19.0
NPM: 8.19.3
JS-Controller: 4.0.24
Admin V6.6.4

Client:
MACbook Pro Apple M1
MCOS 13.3.1
Google Chrome : Version 115.0.5790.114 (Offizieller Build) (arm64)
Safarie: Version 16.4 (18615.1.26.110.1)

**Comment by Feuer-sturm** [comment]
Is duplicate to #2003
