### ISSUE TITLE
cannot open configuration page of mqtt-adapter

### ISSUE THREAD

**Issue by gitMatthias** [ioBroker/ioBroker.admin#2016]
**Describe the bug**  
Error page is shown, when I try to open the configuration page of the mqtt-adapter

**To Reproduce**  
1. Go to 'Instanzen'
2. Click on 'Einstellungen' of mqtt-adapter
3. See error

**Expected behavior**  
Open configuration page of mqtt-adapter

**Screenshots & Logfiles**  
see attached file
![image](https://github.com/ioBroker/ioBroker.admin/assets/64424483/d7f2f1c2-4b25-43fb-b220-8acb1bd850c3)

**Versions:**  
 - Adapter version: 4.1.1
 - JS-Controller version: 5.0.11
 - Node version: v18.17.0
 - Operating system: debian bullseye
[mqtt.log](https://github.com/ioBroker/ioBroker.admin/files/12213403/mqtt.log)

**Comment by Feuer-sturm** [comment]
Duplicate to #2006
