### ISSUE TITLE
[BUG] Admin v3.2.0 (Win) ungültiger Pfad zur Log-Datei

### ISSUE THREAD

**Issue by Rantanplan01** [ioBroker/ioBroker.admin#202]
Folgender Pfad wird im Log als Fehler ausgegeben.
`error | Cannot check file: C:\ioBroker\log/iobroker.2018-02-10.log`

**Comment by GermanBluefox** [comment]
Weil diese Datei aus irgendeinem Grund vom Windows geblockt ist. Hat nichts mit admin zu tun.
