### ISSUE TITLE
HIstory Adapter macht Probleme nach Update auf Beta Admin

### ISSUE THREAD

**Issue by Dragon0501** [ioBroker/ioBroker.admin#2025]
Der History Adapter flutet den Log mit Fehlermeldungen für ganz viele Datenpunkte.

`

 
--
history.0 | 2023-08-01 21:50:57.773 | error | Cannot store file /opt/iobroker/node_modules/iobroker-data/history/20230801/history.nut.0.output.voltage.json: Error: ENOENT: no such file or directory, mkdir '/opt/iobroker/node_modules/iobroker-data/history/20230801

`

Es werden alle Datenpunkte aufgeführt, dies ist nur eine beispielhafte Fehlermeldung.

**Comment by Feuer-sturm** [comment]
@Dragon0501 bitte die Version vom admin Adapter und history Adapter ergänzen

**Comment by Dragon0501** [comment]
Die Meldungen treten regelmäßig auf.
History Adapter ist die 2.2.4
Der Admin ist die 6.6.5
Der Fehler war aber bei der Vorgängerversion des Admin der gleiche

**Comment by foxriver76** [comment]
Die Meldung kommt aber vom history Adapter und der Pfad ist definitiv nicht korrekt bitte issue da anlegen

**Comment by Dragon0501** [comment]
Oki

**Comment by foxriver76** [comment]
Und falls man im history Adapter einen Pfad angeben kann checke den mal der sollte auf keinen Fall nach node_modules führen das müsste alles eine Ebene tiefer das es passt aber kann sein dass auch history da noch einen Bug hat.

**Comment by mcm1957** [comment]
Man kann der Speicherort angeben
https://github.com/ioBroker/ioBroker.history/blob/master/docs/de/README.md

**Comment by Dragon0501** [comment]
Ich habe ja aber bis auf ein Adapter Update nichts gemacht. Wieso funktionierte es vorher und jetzt nicht mehr?

**Comment by Dragon0501** [comment]
es scheint als fehle dem Adapter nach dem update ein Recht um die Ordner zu erstellen.

**Comment by Dragon0501** [comment]
Oder es wird ein falscher Standardpfad verwendet nach dem Update.

**Comment by Feuer-sturm** [comment]
@Dragon0501 hast du schon einmal 
Iob fix
aufgerufen?

**Comment by Dragon0501** [comment]
Ja habe ich.

Das Ding ist ja wenn der Pfad in den geschrieben werden soll nicht ok ist scheint es ein Problem des History Adapters mit dem Standardpfad zu geben...

**Comment by Dragon0501** [comment]
A: das stimmt. issue eröffnet.
B: garnichts, da ich immer den Standardpfad verwendet habe. Dieser scheint aber nicht mehr zu stimmen...
C: ja ich habe wohl auch den js aktualisiert, warum?

**Comment by Feuer-sturm** [comment]
@Dragon0501 verlink bitte mal das andere issue hier, dann schließen wir hier das issue und die Diskussion geht im anderen issue weiter

**Comment by Dragon0501** [comment]
[Issue beim History Adapter](https://github.com/ioBroker/ioBroker.history/issues/267)

**Comment by mcm1957** [comment]
Ad c)
Weil es einerseits immer wichtig ist zuvsagenvwas sich potenziell geändert hat. Ich hab nur admin aktualisiert ist was anderes als ich gab sdmin, node und js-conztoller aktualisiert.

Und weil js-controller 5 einiges verändert hat und ev Zugriffe in "verbotene" Bereiche nun anders vehandelt. Hab aber die Details nicht im Kopf.

**Comment by Apollon77** [comment]
Also ja komisch ... welche Pfad ist denn bei history angegeben? Aber ja vllt besserr in einem history issue zu diskutieren
