### ISSUE TITLE
Dont active save button

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#203]
![image](https://user-images.githubusercontent.com/11523624/36626392-919110b0-1964-11e8-97e4-1ee3e92d9492.png)

**Comment by GermanBluefox** [comment]
You did not change anything.
If yes, what?

**Comment by instalator** [comment]
TYPE

**Comment by GermanBluefox** [comment]
Fixed in 3.2.3 (not yet published)

**Comment by GermanBluefox** [comment]
Please retest

**Comment by instalator** [comment]
fixed
