### ISSUE TITLE
fakeroku.png not found on github when trying to check vis-2 license

### ISSUE THREAD

**Issue by Frickeldave** [ioBroker/ioBroker.admin#2030]
**Describe the bug**  
In the vis-2 adapter i try to check the license (without license manager). When clicking on the check-license button i get the message showed in the screenshot.

**To Reproduce**  
1. Go to 'Settings of VIS-2 adapter'
2. Add UUID and license
3. Click on Check license

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.admin/assets/34135598/4e88c7fd-10a6-44bc-b606-05f0c31fea51)

**Versions:**  
 - Adapter version: vis-2 2.1.5
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: docker iamge v8.0.1

**Comment by Feuer-sturm** [comment]
@Frickeldave which admin version do you use?

**Comment by foxriver76** [comment]
is most likely already fixed, if not please reopen
