### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by zeroneverload** [ioBroker/ioBroker.admin#2039]
**Describe the bug**  

**To Reproduce**  
1. Go to Host
2. Click on update
3. Click on Update in Popupwindow

**Expected behavior**  
Erropage will load

**Screenshots & Logfiles**  
2instrument.ts:132 [ADAPTERS] admin
toolbarContentscript.js:113 {"message":"A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received"}
raw.githubusercontent.com/oweitman/ioBroker.rssfeed/main/admin/rssfeed.png:1     Failed to load resource: the server responded with a status of 404 ()
github.com/iobroker-community-adapters/ioBroker.fakeroku/master/admin/fakeroku.png:1     Failed to load resource: the server responded with a status of 404 ()
instrument.ts:132 Translate: time
instrument.ts:132 Translate: timeOffset
instrument.ts:132 TypeError: e.startsWith is not a function
    at g (tools.ts:16:12)
    at n.value (AdminConnection.ts:479:10)
    at JsControllerDialog.jsx:158:38
    at li (react-dom.production.min.js:244:332)
    at xs (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:283:409
    at Ss (react-dom.production.min.js:281:398)
    at ss (react-dom.production.min.js:273:439)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonym) @ instrument.ts:132

**Versions:**  

 - JS-Controller version: <js-controller-version 4.0.23> 
Plattform: docker
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 1711 MHz
Modell: Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
RAM: 15.3 GB
System-Betriebszeit: 26 T. 14:41:14
Node.js: v16.19.0
time: 1691482861515
Adapter-Anzahl: 578
NPM: 8.19.3
Datenträgergröße: 40.0 GB
Freier Festplattenspeicher: 29.9 GB
Betriebszeit: 6 T. 12:40:03
Aktive Instanzen: 36

**Comment by Feuer-sturm** [comment]
@zeroneverload please check with admin 6.7.1
Issue should be fixed in this Version 
Related issue: #2033

**Comment by foxriver76** [comment]
should be fixed in 6.7.2

**Comment by zeroneverload** [comment]
Error is now fixed in admin 6.7.2. 

Case Closed

THX for the replies
