### ISSUE TITLE
Scrollbar is missing

### ISSUE THREAD

**Issue by AndyUM61** [ioBroker/ioBroker.admin#204]
The scrollbar in objects is missing.
System: Windows
Browser: Chrome

Greetings Andy

**Comment by Apollon77** [comment]
Which version of admin?

**Comment by AndyUM61** [comment]
V. 3.2.1

**Comment by AndyUM61** [comment]
Darf man hier eigentlich auch Deutsch schreiben?
Ich mach das einfach mal;)...

Also noch einmal bzgl. Scrollbar.
Im Bereich "Objekte" sind so einige "komische" Verhaltensweisen.
Wenn ich kein Objekt ausgeklappt habe, dann ist der eine Scrollbar vorhanden.
Klappe ich ein Objekt aus, verschwindet er.
Klappe ich dann wieder ein, wird ein Teil des soeben ausgeklappten Teils nach einer kurzen Verzögerung wieder ausgeklappt.

Ich hoffe sehr, ihr wisst was ich mit "ausklappen" und "einklappen" meine.
(Der kleine weiße/schwarze Pfeil links von der ID)

**Comment by GermanBluefox** [comment]
Ein screenshot kostet 1000 Worte. Ich habe nichts verstanden.

**Comment by AndyUM61** [comment]
Ja, sorry, es ist nicht so leicht das zu beschreiben.
Mit einem Screenshot ist es leider auch nicht getan, da die Scrollbar mal da ist und mal nicht.

**Comment by none007** [comment]
Hallo Zusammen,

ich habe ebenfalls das Problem mit der nicht vorhandenen Scrollbar im Objekt-Bereich. In allen anderen Bereichen ist die Scollbar vorhanden und funktioniert. 
Bei mir fehlt allerdings nur die Scrollbar im Objektbereich. Kein komisches Verhalten beim auf-  und zuklappen der Object-Instanzen und Geräte.

Admin 3.2.1 und Chrome-Browser
VG
Marco

**Comment by GermanBluefox** [comment]
Was ist mit 3.2.4?

**Comment by AndyUM61** [comment]
Bei mir ist alles Bestens mit der 3.2.4
