### ISSUE TITLE
admin 6.6.4 cannot create datapoints in 0_userdate.o anymore

### ISSUE THREAD

**Issue by AxelG-DE** [ioBroker/ioBroker.admin#2040]
**Describe the bug**  
What ever I try, I cannot create folders or datapoints or whatsoever in 0_userdate.0 even not in expert-mode
After clicking on "add" or German "Hinzufügen" nothing happens...

**To Reproduce**  
1. Go to Objects
2. Click on '+'
3. After fill in , click on "add" (Hinzufügen) 

**Expected behavior**  
Datapoint to be created

**Versions:**  
 - Adapter version: <6.6.4>
 - JS-Controller version: <4.0.24>
 - Node version: <18.17.0> 
 - Operating system: <Raspbian 11>

**Comment by foxriver76** [comment]
Use 6.7.0

**Comment by AxelG-DE** [comment]
TNX for your always super swift reply. 
6.7.1 came via npm and did the trick
