### ISSUE TITLE
Admin (6.newest) should require node 16 as engine (instead of node 12) to avoid npm6/adapter-core 3.x.x errors

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2044]
The actual admin release should require NODE 16.

As admin now uses adapter-core 3.x.x which is know to fail when installed with npm 6 (node 14) its not optimal if ioBroker.admin has an engine node>=12 entry.

https://github.com/ioBroker/ioBroker.admin/blob/389567e543e97f163479021e35e18b39f62124fb/package.json#L12

**Comment by mcm1957** [comment]
see PR https://github.com/ioBroker/ioBroker.admin/pull/2045

Feel free to merge or comment / change

**Comment by foxriver76** [comment]
was fixed during webserver upgrade PR
