### ISSUE TITLE
Optimierung für Mobile Endgeräte

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.admin#205]
Ich verwende ioBroker größtenteils auf meinem Smartphone oder Tablet. Beides sind Android Geräte mit dem aktuellen Chrome Browser.
Einige Tabellen oder Steuerelement werden nicht richtig bzw. nicht am richtigen Ort angezeigt.
Es wäre daher schön, wenn die Admin Oberfläche ein wenig für Mobile Endgeräte angepasst bzw. optimiert würde.

Wenn ich dazu komme, hänge ich heute Nachmittag noch ein paar Screenshots hier an, um das genauer zu dokumentieren.

**Comment by dontobi** [comment]
![Screenshot #1](https://i.imgur.com/LN16SXA.jpg)
Auf dem Bild sieht man, dass der Button zum hinzufügen eines Benutzers und oben der Text "Gruppen" nicht in der selben Zeile sind.

![Screenshot #2](https://i.imgur.com/jG5L1CB.jpg)
Der Button Download ist eine Zeile unter den restlichen Steuerelementen.

![Screenshot #3](https://i.imgur.com/jekozHm.jpg)
Die beiden Steuerelemente sind untereinander statt nebeneinander.

![Screenshot #4](https://i.imgur.com/vM5jGYN.jpg)
Die Steuerelemente und das Setzen der Filter ist ebenfalls unter einander. Außerdem werden die Spalten der Tabelle nicht richtig angezeigt.

**Comment by GermanBluefox** [comment]
Please test 3.2.2

**Comment by dontobi** [comment]
Mit Version 3.2.2 sind alle Fehler behoben, bis auf den mit den Tabellenspalten auf der Adapterseite. Die Spalten werden immer noch nicht richtig angezeigt.

**Comment by dontobi** [comment]
Ich weiß nicht ob es durch ein fehlerhaftes Update kam oder ob es ein Bug ist, aber die Anzeige in Prozent auf der Instanzen Seite ist verbugt.

**Comment by GermanBluefox** [comment]
Das ist RAM nutzung dürch ioBroker. Es gibt aber hunderte andere Prozesse.

**Comment by GermanBluefox** [comment]
>bis auf den mit den Tabellenspalten auf der Adapterseite. 
Screenshot?

**Comment by dontobi** [comment]
![Screenshot #5](https://i.imgur.com/rK1e8Qb.jpg)
Alles ist nun gefixt, aber die Anzeige des Speicherverbrauchs ist bei mir immernoch fehlerhaft.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/209
