### ISSUE TITLE
Adapter kann nicht gestartet werden, wenn über Dateipfad installiert

### ISSUE THREAD

**Issue by Mittelblut9** [ioBroker/ioBroker.admin#2050]
**Describe the bug**  
Wenn ich versuche einen Adapter, der per Dateipfad in den Admin eingefügt wurde, zu starten bricht dieser direkt ab mit dem Fehler `CANNOT_FIND_ADAPTER_DIR`.

**To Reproduce**  
1. Adapter herunterladen
2. Dateipfad unter "Den Adapter von URL installieren oder aktualisieren" einfügen
3. "Installieren" drücken
4. Instanz hinzufügen
5. Versuchen den Adapter zu starten

**Expected behavior**  
Der Adapter startet und führt den vorgegeben Code aus.

**Screenshots & Logfiles**  
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/67608550/cbee053c-0355-4245-bb45-0a3dc4127d03)

**Versions:**  
 - Adapter version: ??
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: Windows

**Additional context**  
Der benutze Adaper ist der WIP Fork vom Apple Find My Adapter https://github.com/Mittelblut9/ioBroker.apple-find-me
Per GitHub URL funktionert alles einwandfrei.

**Comment by GermanBluefox** [comment]
This is js-controller error.
Please check if the adapter could be found under: `/opt/iobroker/node_modules/iobroker.apple-find-me/...`

**Comment by foxriver76** [comment]
Was this working with local Paths at some Point?

**Comment by foxriver76** [comment]
And can you show which path was pasted in the install dialog + logs of the installation

**Comment by Mittelblut9** [comment]
It works with `npm pack`. 

A small notice at the input would be nice instead of just "File Path" (german: Dateipfad). 👍

**Comment by foxriver76** [comment]
I totally agree, we will adapt the texts
