### ISSUE TITLE
Unable to close "upgrade js-controller" dialog

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2052]
**Describe the bug**  

<img width="1713" alt="Screenshot 2023-08-18 at 20 03 56" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/2505938f-caa1-4438-b35c-df397ddf8c73">

**To Reproduce**  
1. Go to hosts
2. Click on the new version
3. Click "show" button
4. Try to close the dialog

**Versions:**  
 - Adapter version: 6.8.3

**Additional context**  

Browser console:

```
[Error] Invalid hostId: "false" with type boolean
	(anonymous function) (7853.5366b11e.chunk.js:2:283634)
	(anonymous function) (6655.c7a9c74e.chunk.js:1:46909)
	li (4164.29c179b8.chunk.js:2:93782)
	xs (4164.29c179b8.chunk.js:2:114010)
	(anonymous function) (4164.29c179b8.chunk.js:2:112745)
	Ss (4164.29c179b8.chunk.js:2:112809)
	ss (4164.29c179b8.chunk.js:2:106530)
	ss
	Hl (4164.29c179b8.chunk.js:2:46922)
	(anonymous function) (4164.29c179b8.chunk.js:2:103925)
```

**Comment by foxriver76** [comment]
I am currently unable to reproduce this. With adapter version `6.8.3` you mean `6.8.2`?

**Comment by foxriver76** [comment]
hm okay probably 6.8.3 this ones weird 
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/d33fbc71-f0d9-4d91-8f62-1d603a538b8c)

**Comment by foxriver76** [comment]
Okay, I have tagged 6.8.3 as latest now. Will try to repro again.

**Comment by klein0r** [comment]
With 6.9.0 the behaviour changed - now the dialog doesn't open anymore

![iob](https://github.com/ioBroker/ioBroker.admin/assets/1959049/e87ecf96-3cc4-4b4f-b48e-192e4e33da86)

**Comment by foxriver76** [comment]
I am still not able to reproduce this.

**Comment by foxriver76** [comment]
Ah okay, probably only happens, when no UI upgrade is supported.
