### ISSUE TITLE
Files: Creation of folders not possible

### ISSUE THREAD

**Issue by Rookiestyle** [ioBroker/ioBroker.admin#2053]
**Describe the bug**  
I'm unable to create folders inside 0.userdata_0 or vis.0

**To Reproduce**  
1. Go to 'Files'
2. Click on 'Userdata'
3. Click 'Create folder'
5. See error

**Expected behavior**  
ioBroker asks for foldername and creates folder

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.admin/assets/36454520/6d017b91-2ffb-49c5-bcd9-df5073c21b1d)

![image](https://github.com/ioBroker/ioBroker.admin/assets/36454520/554ce924-27e2-4eca-8641-0bfde494a169)

**Versions:**  
 - Adapter version: 6.8.3
 - JS-Controller version: 5.0.12
 - Node version: v18.17.1
 - Operating system: Raspbian GNU/Linux bullseye 6.1.21-v8+

**Comment by foxriver76** [comment]
will be fixed by https://github.com/ioBroker/adapter-react-v5/pull/162
