### ISSUE TITLE
Always use english as defautl for releasenotes during adapter installation / upgrade

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2064]
Currently releasnotes ar seem to be displayed using the language configured as default and used for adapter configuration guis.

As the non english (man some english) text is horrible bad, theres been a discussion to display releasenoted during adapter installion per default in english always. Other languages should be displayed only when a user request the other language explicitly during the installation. (This can already be done using the globe symbol)

So please consider / discuss to use ALWAYS ENGLISH for releasenotes unless the user selects another langue for this single installation.

relates: https://t.me/ioBroker_development/30560 and some around

**Comment by foxriver76** [comment]
hm in a short test this is exactly the case for me, system language is `de` but release notes of adapter are displayed in `en` until I click on the translate world icon.

If you enabled the translation, it will stay active for your session, also for other adapters, this could be the only thing we could change.

**Comment by mcm1957** [comment]
Ok, I'm definitly sure that I did NOT change any language settings during this session. Would be ok if it stays enable for a complete session. But I just upgraded node - so I'm ruther sure that no session could be kept.

But I just now rebooted my laptop. I'll try to do an install and lokk for the language.

**Comment by mcm1957** [comment]
Your are completly right.
The brand new session has the desired behavior.

Could it be that this has become available with admin 6.8.x ? The system is running at stable so admin has been upgraded just now to 6.8.x and was running the "previous" stable admin but not the bunch of latest only admins? The german text has been displayed during update of  adapters including admin befor node update.

SORRY for the wrong issue.
Lets close here
