### ISSUE TITLE
Error in sendmail with 2 attachments

### ISSUE THREAD

**Issue by d1nd141** [ioBroker/ioBroker.admin#207]
Adding 2 attachments (using the Text field) looks like:
         attachments:[
            {path: '/tmp/garage1.jpg', cid: "file1"}
            {path: '/tmp/garage2.jpg', cid: "file2"}
          ]
in the source. This gives an error.
Copy the entire script and add as new Javascript, then change to:
         attachments:[
            {path: '/tmp/garage1.jpg', cid: "file1"},
            {path: '/tmp/garage2.jpg', cid: "file2"}
          ]
is OK. Save the script. You will be asked to convert to Blocky.
After converting, you will have an error again:

javascript.0 | 2018-03-04 08:00:28.881 | error | at Object.createScript (vm.js:80:10)
-- | -- | -- | --
javascript.0 | 2018-03-04 08:00:28.881 | error | SyntaxError: Unexpected token {
javascript.0 | 2018-03-04 08:00:28.881 | error | ^
javascript.0 | 2018-03-04 08:00:28.880 | error | {path: '/tmp/garage2.jpg', cid: "file2"}
javascript.0 | 2018-03-04 08:00:28.880 | error | at script.js.common.Garagentor:25
javascript.0 | 2018-03-04 08:00:28.880 | error | script.js.common.Garagentor compile failed:

**Comment by GermanBluefox** [comment]
What does admin have common with email send???? Where is the logic?
>You will be asked to convert to Blocky.

Is impossible. So I don't understand what you do.
Please create issue for ioBroker.email and test new verison.
