### ISSUE TITLE
Error in Gui! beim Anlegen eines neuen Ordners

### ISSUE THREAD

**Issue by daestx** [ioBroker/ioBroker.admin#2070]
Wenn ich unter Dateien ein neues Verzeichnis anlegen möchte erfolgt die Ausgabe: Error in Gui!

![image](https://github.com/ioBroker/ioBroker.admin/assets/93374366/a815a48b-a6d4-41a8-9964-9dd99cc54a9f)

**Versions:**  
 - IObroker: 4.0.24
 - Operating system: Raspi mit Linux

**Comment by foxriver76** [comment]
Admin adapter version?

**Comment by daestx** [comment]
Adim Adapter: 6.8.0

**Comment by foxriver76** [comment]
Siehe changelog 6.9.0 ist bereit gefixt
