### ISSUE TITLE
Not possible to save adapter admin config: admin >= 6.9.0 

### ISSUE THREAD

**Issue by daolis** [ioBroker/ioBroker.admin#2073]
Not possible to save the adapter admin config.
No reaction when clicking on `Save` or `Save and close`

**To Reproduce**  
First i saw it when testing an adapter with dev-server with admin 6.9.1

1. Checkout https://github.com/daolis/ioBroker.sun2000-modbus
2. Setup the dev-server and run it
3. Try to save the adapter config

**Expected behavior**  
Config should be saved

**Versions:**  
 - Admin version: 6.8.3 works
 - Admin version: 6.9.0 or later -> nope

**Comment by daolis** [comment]
@GermanBluefox, @foxriver76 JFYI, as the commits between 6.8.3 and 6.9.0 are from you... ;-)
https://github.com/ioBroker/ioBroker.admin/compare/v6.8.3...v6.9.0

**Comment by Apollon77** [comment]
Any error in the javascript console in the browser?

**Comment by foxriver76** [comment]
I will try to reproduce with dev-server, normal installation with current admin 6.9.1 as well as current github version works fine for me.

**Comment by foxriver76** [comment]
okay can reproduce it

**Comment by foxriver76** [comment]
we should of course prevent the crash case in the future. However, there is basically an inconsistency in the adapter code.

Default port is a number https://github.com/daolis/ioBroker.sun2000-modbus/blob/a43d95d764685934183121948e53af0b45fe4f55/io-package.json#L123 jsonConfig states it is text. So as long as you do not change the port, it tries to trim the number value (calling `.trim` on type `number` -> crash)

**Comment by daolis** [comment]
Ahh, thanks @foxriver76. Will fix it in the adapter.
