### ISSUE TITLE
Influxdb Einstellungen in Instanz lässt sich nicht ändern/speichern

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#2076]
In der Influx Instanz sind Änderungen nicht möglich, (wollte die Entprellzeit in den Standardeinstellungen anpassen)
Beim speichern erscheint folgende Meldung im Browserlog
`JsonConfig.jsx:436 Uncaught (in promise) TypeError: t[e].trim is not a function
    at n.value (JsonConfig.jsx:436:45)
    at n.value (JsonConfig.jsx:428:30)
    at n.value (JsonConfig.jsx:426:30)
    at n.<anonymous> (JsonConfig.jsx:477:18)
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:128:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:22:9)
value @ JsonConfig.jsx:436
value @ JsonConfig.jsx:428
value @ JsonConfig.jsx:426
(anonymous) @ JsonConfig.jsx:477
d @ regeneratorRuntime.js:44
(anonymous) @ regeneratorRuntime.js:128
(anonymous) @ regeneratorRuntime.js:69
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Promise.then (async)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(anonymous) @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:19
(anonymous) @ JsonConfig.jsx:518
onSave @ JsonConfig.jsx:576
onClick @ SaveCloseButtons.js:84
Re @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cs @ react-dom.production.min.js:274
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
o @ helpers.ts:98`

Admin 6.9.1
Js-controller 5.0.12
InfluxDB 3.2.0

**Comment by foxriver76** [comment]
6.9.2 released
