### ISSUE TITLE
Update des js-controllers schlägt fehl.

### ISSUE THREAD

**Issue by raschy** [ioBroker/ioBroker.admin#2077]
Mein Vorhaben war, in einem dev-server den js-controller auf die derzeit aktuelle Version 5.0.12 anzuheben. Installiert hatte ich den dev-server in einer proxmox-lxc unter debian 12, mit node 20.4.0/npm 9.8.0. Die laufende Version vom js-controller ist die 5.0.7 mit admin 6.9.1.
Im Host wird die Möglichkeit des Updates auf 5.0.12 angeboten, 
In dem erschienenen Dialogfeld wird nach kurzer Zeit "SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON" angezeigt.
Dem ConsolenLog konnte ich folgendes entnehmen:
2023-08-27 15:22:00.049  - debug: host.dev-raschytest-dev-node20 Incoming Host message upgradeController
2023-08-27 15:22:00.050  - info: host.dev-raschytest-dev-node20 Controller will upgrade itself to version 5.0.12

Aktuell sind meinerseits keine Tests mehr möglich, da ich anschließend noch versucht habe, manuell mit "npm install iobroker.js-controller@5.0.12" upzudaten. Seither beim start "Error: Couldn't start js-controller".

**Comment by foxriver76** [comment]
in controller 5.0.7 war ui upgrade kaputt siehe controller beta thread
