### ISSUE TITLE
Filter box in adapter list is in a weird position

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#208]
See screenshot:
![unbenannt](https://user-images.githubusercontent.com/17641229/36949301-a36afc32-1fe6-11e8-9790-8c36f8a862df.PNG)

Admin v3.2.2

**Comment by GermanBluefox** [comment]
Why it should be there? Filter is planned to be as on screenshot.

**Comment by AlCalzone** [comment]
If you say so. 
IMO, it looks really lost over there. I didn't see it at first because it has low contrast, too. 
And it's a lot further left for the other tabs with the same box.

**Comment by GermanBluefox** [comment]
Changed in 3.2.4

**Comment by AlCalzone** [comment]
Hmm, not really better. The position still looks pretty random and now its hidden on small screens:
![unbenannt](https://user-images.githubusercontent.com/17641229/37171195-5d21fd3c-230d-11e8-9eee-2ff3d0d14eb1.PNG)
On my phone I cannot see it at all.

I think putting all the controls in a single column and floating them to the left would be better here. Maybe some space between the controls and the filter box, like 1 or 2 `rem`.

**Comment by AlCalzone** [comment]
And I have to disagree again, sorry

This is fine:
![1](https://user-images.githubusercontent.com/17641229/37553500-b1931078-29c9-11e8-95a7-cd477a298112.PNG)

But when I make the window 2px smaller, it vanishes entirely, although there is a lot of space:
![2](https://user-images.githubusercontent.com/17641229/37553504-be149164-29c9-11e8-9827-daaf7673f96b.PNG)

**Comment by GermanBluefox** [comment]
Please retest with 3.4.3

**Comment by AlCalzone** [comment]
It does a few weird jumps when resizing the window, but it stays more or less in the same position. It only vanishes on very very narrow screens, when the list below it isn't readable anymore.

**Comment by AlCalzone** [comment]
I'd consider this fixed
