### ISSUE TITLE
Error by set value in object browser (dev-server)

### ISSUE THREAD

**Issue by Schmakus** [ioBroker/ioBroker.admin#2081]
**Describe the bug**  
by clicking on value of an state, the following message appears:

![Xnip2023-08-29_14-15-19](https://github.com/ioBroker/ioBroker.admin/assets/8231359/5010729e-db61-4617-b3f7-66896bd1f1a2)

![Xnip2023-08-29_14-17-17](https://github.com/ioBroker/ioBroker.admin/assets/8231359/5d20cb96-3be9-445d-ab57-2154d1f350fa)

This error appears after I want to create an object. The object will be created, but with warnings!

`
lightcontrol.0 | 2023-08-29 14:07:23.451 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
lightcontrol.0 | 2023-08-29 14:07:23.451 | warn | Object lightcontrol.0.Wohnzimmer.adaptiveCt.adaptiveCtMode is invalid: obj.common.type has an invalid value (state) but has to be one of number, string, boolean, array, object, mixed, file, json
lightcontrol.0 | 2023-08-29 14:07:23.450 | debug | setObject Wohnzimmer.adaptiveCt.adaptiveCtMode (type=state) property common.name missing, using id as name
lightcontrol.0 | 2023-08-29 14:07:23.450 | warn | setObject Wohnzimmer.adaptiveCt.adaptiveCtMode (type=state) property common.role missing!
`

Here the source of common:
`
"adaptiveCt.adaptiveCtMode": {
   type: "state",
   common: {
	read: true,
	write: true,
	name: {
		en: "Mode for Adaptive Colortemperature",
		de: "Modus für adaptive Farbtemperatur",
		ru: "Режим для адаптации Colortemperature",
		pt: "Modo de temperatura adaptativa da cor",
		nl: "Mode voor Adaptieve Colortemperatuur",
		fr: "Mode pour la couleur adaptative",
		it: "Modalità per colori adattivi",
		es: "Mode for Adaptive Colortemperature",
		pl: "Przewodnik adaptacyjny",
		uk: "Режим адаптивної кольорової температури",
		"zh-cn": "A. 资格认证",
	},
	type: "string",
	role: "switch.mode",
	def: "solar",
	states: {
		linear: "Linear",
		solar: "Solar",
		solarInterpolated: "Solar Interpolated",
		timedInterpolated: "StartYourDay Interpolated",
		timed: "StartYourDay",
	},
},
native: {},
},
`

**Versions:**  
 - Adapter version: 6.9.1
 - JS-Controller version: 5.0.12
 - Node version: 18.12.1
 - Operating system: macOS

**Additional context**

**Comment by foxriver76** [comment]
I have no idea how to replicate, at  the beginning it is about clicking on a state then about creating an object. How is the object created? What kind of state it is you are clicking on, the raw object could help.

**Comment by Schmakus** [comment]
The failure was produced by myself. I set a object with an common in a common. After that, the error occurs. 

![image](https://github.com/ioBroker/ioBroker.admin/assets/8231359/bb85f3e4-b59d-4dcf-a268-b842ba1b4555)

**Comment by foxriver76** [comment]
Please no screenshots in the future, copy paste helps more ;-)

**Comment by darkman242** [comment]
I have the same problem with changing objects. But it does not affect all objects (for me the unifi-protect objects).

![image](https://github.com/ioBroker/ioBroker.admin/assets/46793576/4f25540d-cfb3-4db8-9f11-db449a806478)

`{
  "type": "state",
  "common": {
    "name": "recordingMode",
    "type": "string",
    "read": true,
    "write": true,
    "states": {
      "always": "always",
      "never": "never",
      "detections": "detections"
    },
    "alias": {
      "id": "unifi-protect.0.cameras.64f069b30393f403e4003a32.recordingSettings.mode"
    },
    "desc": "per Script erstellt"
  },
  "native": {},
  "from": "system.adapter.javascript.1",
  "user": "system.user.admin",
  "ts": 1693502068758,
  "_id": "alias.0.IPCams.Terrasse_rechts.recordingMode",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`
