### ISSUE TITLE
Widgetübersicht + View laden nicht

### ISSUE THREAD

**Issue by LortusX** [ioBroker/ioBroker.admin#2082]
Aufgrund diverser Anfängerfehler wollte ich meinen inzwischen knapp drei Jahre alten ioBroker neu aufsetzen. (via Promox auf einem NUC) In diesem Kontext war es der Plan die neue Visualisierung sinnvollerweise direkt auf Basis der vis-2 (Version 2.2.2) zu erstellen.

Beim Öffnen des Editors läuft sowohl oberhalb der Widgetübersicht als auch oberhalb der View ein blauer Balken durch - die jeweiligen Fenster bleiben aber auch nach längerem Warten leer. [siehe GIF] Selbes gilt beim Aufrufen der Vis = am oberen Rand des Bildes läuft ein blauer Balken durch, das Fenster bleibt aber leer.
![](https://github.com/ioBroker/ioBroker.admin/assets/57331280/ea399687-b476-421b-b78f-148c6515c9dc)

Die Instanz (2er-Lizenz; Lizenz "OK") selber ist grün.
Die gleiche Problematik bzw. eine entsprechende Lösung habe ich bisher nirgendwo finden können. (Da sich Ladeprobleme teilweise auf den web-Adapter beziehen, habe ich diesen ebenfalls entsprechend angepasst. [siehe Screenshot])
![](https://github.com/ioBroker/ioBroker.admin/assets/57331280/344bf662-6bf2-4487-bdcb-c4a3683c5290)

bisher erfolglos getestet:
- mehrfaches deinstallieren und neu installieren (auch via Konsole)
- zusätzlichen Account für neuen Lizenzschlüssel angelegt

Versionen:
 - Adapter version: 2.2.2
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: debian

Instanzen:
+ system.adapter.admin.0                  : admin                 : iobroker                                 -  enabled, port: 8081, bind: 0.0.0.0 (SSL), run as: admin
+ system.adapter.alarm.0                  : alarm                 : iobroker                                 -  enabled
+ system.adapter.alexa2.0                 : alexa2                : iobroker                                 -  enabled
+ system.adapter.backitup.0               : backitup              : iobroker                                 -  enabled
+ system.adapter.deconz.0                 : deconz                : iobroker                                 -  enabled, port: 80
+ system.adapter.discovery.0              : discovery             : iobroker                                 -  enabled
  system.adapter.dwd.0                    : dwd                   : iobroker                                 -  enabled
+ system.adapter.fritzdect.0              : fritzdect             : iobroker                                 -  enabled
+ system.adapter.homeconnect.0            : homeconnect           : iobroker                                 -  enabled
+ system.adapter.hs100.0                  : hs100                 : iobroker                                 -  enabled
+ system.adapter.hue-extended.0           : hue-extended          : iobroker                                 -  enabled
  system.adapter.ical.0                   : ical                  : iobroker                                 -  enabled
  system.adapter.iot.0                    : iot                   : iobroker                                 - disabled
+ system.adapter.javascript.0             : javascript            : iobroker                                 -  enabled
  system.adapter.mihome-vacuum.0          : mihome-vacuum         : iobroker                                 - disabled, port: 54321
  system.adapter.mqtt.0                   : mqtt                  : iobroker                                 - disabled, port: 1883, bind: 0.0.0.0
+ system.adapter.nina.0                   : nina                  : iobroker                                 -  enabled
  system.adapter.nuki.0                   : nuki                  : iobroker                                 - disabled
  system.adapter.ring.0                   : ring                  : iobroker                                 - disabled
+ system.adapter.shelly.0                 : shelly                : iobroker                                 -  enabled, port: 1893, bind: 0.0.0.0
+ system.adapter.socketio.0               : socketio              : iobroker                                 -  enabled, port: 8084, bind: 0.0.0.0, run as: admin
+ system.adapter.sonoff.0                 : sonoff                : iobroker                                 -  enabled, port: 1883, bind: 0.0.0.0
+ system.adapter.sql.0                    : sql                   : iobroker                                 -  enabled
+ system.adapter.telegram.0               : telegram              : iobroker                                 -  enabled, port: 8443, bind: 0.0.0.0
+ system.adapter.text2command.0           : text2command          : iobroker                                 -  enabled
+ system.adapter.tr-064.0                 : tr-064                : iobroker                                 -  enabled
+ system.adapter.vis-2.0                  : vis-2                 : iobroker                                 -  enabled
+ system.adapter.web.0                    : web                   : iobroker                                 -  enabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.worx.0                   : worx                  : iobroker                                 -  enabled
  system.adapter.yr.0                     : yr                    : iobroker                                 -  enabled

**Comment by mcm1957** [comment]
Are you sure that thisvissue relates to admin. Sounds more like a vis-2 problem

https://github.com/ioBroker/ioBroker.vis-2

**Comment by LortusX** [comment]
You are of course absolutely right. I found the following issue (https://github.com/ioBroker/ioBroker.vis/issues/642) when I was looking for a solution and then I also posted it here without looking closely enough. I'll try it again in the right place.

**Comment by LortusX** [comment]
Falls Bedarf bestehen sollte, geht es hier weiter: https://github.com/ioBroker/ioBroker.vis-2/issues/75
