### ISSUE TITLE
Amount of Free Memory is displayed wrong

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#209]
![free_memory](https://user-images.githubusercontent.com/33424168/37048115-38943cba-216d-11e8-847f-37a82a0007ab.png)

**Comment by Homoran** [comment]
At first startup it's still ok, but after the first change it's getting weird

**Comment by GermanBluefox** [comment]
Fixed in 3.2.4

**Comment by wendy2702** [comment]
Gelöst in 3.3.0
