### ISSUE TITLE
jsonConfig: check schema is correct and show warning on page/console if not

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#2095]
I recently created a `jsonConfig.json` file with `items: {...}` nested too deep. This resulted in a blank page with no error.

Ideally admin page should show an error like, *"Invalid jsonConfig - please contact adapter developer"* or something either on the page or browser console.

**Comment by foxriver76** [comment]
Nicest thing would be to fire the whole config against our schema, but I think the schema is not a 100 % up to date currently.
