### ISSUE TITLE
jsonConfig port '0' cannot be changed by typing

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#2097]
Version 6.8.0
node: v16.20.2
js-controller: 5.0.8

When using jsonConfig element such as...

```json
"port": {
  "label": "Listen port",
  "min": 1,
  "max": 65565,
  ...
},
```

... and the default port is undefined (ie. zero) then the field is rendered as expected (label, field with zero value) but... entering that field and trying to type a numeric value does not work:

- Whatever number is entered: eg. '8' yields '08' - is very quickly automatically changed back to zero.
- This can be overcome by moving the cursor in front of the initial zero and typing: eg. '8' now yields '80' which is not changed and the number can be edited as required.

While this bug can be worked around it's an annoying user experience.

**Comment by foxriver76** [comment]
I guess we are talking about using `type: port`, as the element type is missing in the example.

**Comment by raintonr** [comment]
> I guess we are talking about using `type: port`, as the element type is missing in the example.

Yes. Maybe I should have included that line :clown_face:
