### ISSUE TITLE
Incorrect date time displayed at object browser

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2102]
**Describe the bug**  
DATES stored as string are displayed with wrong information

**To Reproduce**  
1. create a state with type STRING and role DATE
2. store the value "08.09.2023"
3. admin object browser displays "Wed Aug 09 2023 00:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)"

**Expected behavior**  
The correct date should be displayed

**Screenshots & Logfiles**  
You may check adapter weatherunderground
Sometimes (depending on values) the string "invalid Date" is displyed too (see issue https://github.com/iobroker-community-adapters/ioBroker.weatherunderground/issues/191)

**Versions:**  
 - Adapter version: 6.9.2 (works as expected with 6.4.4)
 - JS-Controller version: 4.0.24
 - Node version: v18.16.0
 - Operating system: Windows 11

**Additional context**  
NOTE: The used string format "dd.mm.yyyy" is not officially supported by js. So this format does N OT meet the spezifications for role "date". For me it would be OK to close the issue with "correct the adapter" too. But it should be considered that maybe more than one or two aapters are effected.

**Comment by mcm1957** [comment]
Writing the date text using correct javascript format (yyyy-mm-dd) solved the problem for weatherunderground.

@foxriver76 
In my oppinion we could close here - there are enough other tasks to do. But I will leave the decision to core devs, so I only leave this note.

**Comment by foxriver76** [comment]
At least there was a bug, because we wanted to show the original string if `Invalid Date` cases happen
