### ISSUE TITLE
Seit dem vorletzten Upgrade keine Namen mehr möglich in der ID Zeile.

### ISSUE THREAD

**Issue by Menne01** [ioBroker/ioBroker.admin#2103]
Hallo GermanBluFox,
IOB ist im letzten Beta Stand.
Folgendes Problem....

Es werden bei ID keine Namen mehr angezeigt, wenn man bei gedrückter Maustaste nach links zieht in der Sitzung.

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/89869516/4f1b7f73-2613-430a-87e3-eb0adcbc3844)

Grüße

Dirk

**Comment by Feuer-sturm** [comment]
@Menne01 welche Admin Version nutzt du? Welche Auflösung verwendest du? Hast du schon einmal den Browser Cache gelöscht? Tritt das Problem auch in einem anderen Browser bei dir auf?

**Comment by Menne01** [comment]
Moin,
Asche auf mein Haupt. Gestern noch ganz vergessen, das Issue wieder zu schließen. Es ist Firefox. Hatte gestern noch ein Fehler in Octoprint. Dort wurde die eingebettete Cam nicht mehr angezeigt. Gewechselt auf Edge. Namen und Cam wieder i.O.
