### ISSUE TITLE
After installing the latest admin adapter version i can't connect to the ui anymore (HomeAssistant)

### ISSUE THREAD

**Issue by Presl1983** [ioBroker/ioBroker.admin#2107]
Describe the bug
After installing the latest admin adapter (from 4.2.1 -> 6.8.0) version i can't connect to the ui anymore (HomeAssistant)

To Reproduce
image
i need to update because of mqtt broker

Expected behavior
should be up and running after the update

Versions:

Adapter version: 4.2.1
JS-Controller version: latest update
Operating system: Home Assistant

**Comment by Apollon77** [comment]
What is in the logs? What exactly means "can not connect anymore"?

**Comment by Presl1983** [comment]
i'm not able to connect to the ui anymore :(.
i dont know how to get the logs from the iobroker in HomeAssistant :/

![image](https://github.com/ioBroker/ioBroker.admin/assets/142180290/4b8c2d08-8296-480d-94fb-188f5ff3ad93)
![image](https://github.com/ioBroker/ioBroker.admin/assets/142180290/22df0ef1-362c-4f18-a4c8-41c3a3e500ec)

**Comment by mcm1957** [comment]
According to thie script output you are using node 12 (!).

Minimum required node version is node 16 which is epl too already. Recommended node version is node 18.

Most  new adapter releases require node 16 / npm 7 minimum and normally enforce this during installation as npm 6 does not install 

You should upgrade your system to current node versions (node 18).

As you seem to use some container please check your container sources for an up to date version

**Comment by Apollon77** [comment]
@mcm1957 Not totally right, because just now js.controller 4 is still stable, so should be nodejs 12 ... but backit up might reuqire 14 ... so yes updating nodejs is in any case an yidea ... the current docker container should have that ...
@buanet ... any idea?

**Comment by Presl1983** [comment]
Thanks ... i found the eval command to do that in home assistant:
![image](https://github.com/ioBroker/ioBroker.admin/assets/142180290/6d23f8e7-52b4-4ba9-9a00-9106701c9626)

**Comment by Apollon77** [comment]
@Presl1983 in fact this command is deprecated ... it gets a bit more complicated in the future, but ioBroker will provide help soon with new CLI commands

**Comment by mcm1957** [comment]
Please note that this issue relates to an installation inside  homassistant addon based on buanet container 5.1.0.

This release is pretty outdated. And updating inside container us no good option. In addition this homeassistant addon uses a parched startup script. No clue whther it is compatible with js-controller 5 in sny way.

Thus has been discussed at forum in detail. In my oppinion thsis issue can beclosed.

@apollon77
