### ISSUE TITLE
Error when using Info-Button in Overview-Tab since js-controller 5.0.12

### ISSUE THREAD

**Issue by ThomasK1966** [ioBroker/ioBroker.admin#2113]
**Describe the bug**  
Since I have updated the js-controller to version 5.0.12, there is an error, if I use the "Info-Button" on Overview-Tab.

![image](https://github.com/ioBroker/ioBroker.admin/assets/66748020/ce88f630-c9d1-4566-95a8-74aceed9f6d2)

Error from Browser-Console (screeshot):

![image](https://github.com/ioBroker/ioBroker.admin/assets/66748020/c93e39f6-4195-490c-93cd-f7b1b0f57f29)

Log from Browser-Console (Save as...):
`bootstrap.jsx:20 iobroker.admin@6.8.0
instrument.ts:132 [2023-09-17T09:14:25.638Z] Try to connect
instrument.ts:132 Stored version: , new version: 6.8.0
instrument.ts:132 Connected: true
instrument.ts:132 Double links: "eventlist.0/eventlist/index.html" and "eventlist.0"
instrument.ts:132 Double links: "flot.0/flot/edit.html" and "flot.0"
instrument.ts:132 Double links: "vis.0/vis/edit.html" and "vis.0"
instrument.ts:132 Translate: Link
instrument.ts:132 Translate: time
instrument.ts:132 Translate: timeOffset
instrument.ts:132 Translate: dockerInformation
instrument.ts:132 Translate: _nodeCurrent
instrument.ts:132 Translate: _nodeNewest
instrument.ts:132 Translate: _nodeNewestNext
instrument.ts:132 Translate: _npmCurrent
instrument.ts:132 Translate: _npmNewest
instrument.ts:132 Translate: _npmNewestNext
instrument.ts:132 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (react-dom.production.min.js:152:60)
    at d (react-dom.production.min.js:156:186)
    at h (react-dom.production.min.js:158:331)
    at e (react-dom.production.min.js:162:334)
    at wo (react-dom.production.min.js:192:308)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273
(anonymous) @ instrument.ts:132
fo @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
Ua @ react-dom.production.min.js:144
wi @ react-dom.production.min.js:261
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
Ss @ react-dom.production.min.js:281
ss @ react-dom.production.min.js:273
Hl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
`

From the Error Decoder:

![image](https://github.com/ioBroker/ioBroker.admin/assets/66748020/3ac1d39f-55df-4f50-8ea3-df41ddf07bae)

**To Reproduce**  
1. Go to 'Overview-Tab'
2. Click on 'Info-Button'
3. See error

**Versions:**  
![image](https://github.com/ioBroker/ioBroker.admin/assets/66748020/e3d47a8f-b06a-49d6-a565-c26dc31ff24e)

All adapters are up to date.

**Additional context**  
I don't know if the bug only occurs within a Docker environment.

**Comment by foxriver76** [comment]
Version of admin adapter?

**Comment by ThomasK1966** [comment]
> Version of admin adapter?
6.8.0

**Comment by foxriver76** [comment]
6.10.1 will be stable the next days and should fix this problem

**Comment by ThomasK1966** [comment]
Hi @foxriver76 
I have updated my admin to version 6.10.1 (from beta-repo) and the error is the same. So 6.10.1 don't fix the problem.
I can't reopen this issue.  I hope you read it anyway.

**Comment by foxriver76** [comment]
Please try 6.10.2

**Comment by ThomasK1966** [comment]
Hi @foxriver76,

the error is fixed with 6.10.2 :-)

Thank you!
