### ISSUE TITLE
Error in GUI! - click on "JSON" state

### ISSUE THREAD

**Issue by Stefan592** [ioBroker/ioBroker.admin#2118]
**Describe the bug**  
I try to open an in the paste defined mqtt topic as json. In the paste it works fine, after update to admin 6.9 it brokes.

**To Reproduce**  
1. Go to json state in objects
2. Click on state
3. See error

**Expected behavior**  
No error :) 
State as object

**Screenshots & Logfiles**  
![image](https://github.com/ioBroker/ioBroker.admin/assets/14180760/33975c4a-8519-48ba-b52e-9d4e0e0c76d0)
![image](https://github.com/ioBroker/ioBroker.admin/assets/14180760/d13fff20-c82c-4052-8e79-2f376a35565a)
![image](https://github.com/ioBroker/ioBroker.admin/assets/14180760/87afcc51-f456-4ea2-8d4d-ee8683904622)

**Versions:**  
 - Adapter version: Admin 6.9.2
 - JS-Controller version: 5.0.11
 - Node version: 16.20.2
 - Operating system: Buanet Docker

**Comment by foxriver76** [comment]
hm why `6.9.2`? `6.10.1` is stable, please post the error from this version if it still occurs.

**Comment by foxriver76** [comment]
And yes, the object is missing the required property `common.role` and the crash should be fixed, please reopen if occurs with `6.10.1`
