### ISSUE TITLE
Admin 6.10.1: Entering decimal values into datapoints is some kind of 'fuzzy'

### ISSUE THREAD

**Issue by DEV2DEV-DE** [ioBroker/ioBroker.admin#2119]
If I try to enter a decimal value into a number object, the decimal point is ignored in the first attempt.
When I enter the value without the point and then move the cursor to the position and insert the point, it works.
It also works directly when entering a comma as the german decimal character according the current country settings.

System-Language: German
Datapoint:
```
{
  "common": {
    "name": "Ansagetext",
    "desc": "Manuell erzeugt",
    "type": "number",
    "read": true,
    "write": true,
    "def": 0
  },
  "type": "state",
  "native": {},
  "_id": "0_userdata.0.Test.differenz",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1695204700483
}
```

**Comment by foxriver76** [comment]
Using Chrome? I can reproduce it with Chrome, in Firefox it works as expected.

**Comment by DEV2DEV-DE** [comment]
Chrome and Edge. I will try with Firefox later.

**Comment by DEV2DEV-DE** [comment]
I can confirm: No Problem with Firefox.
Please close this issue if not adapter related but a browser problem.

**Comment by foxriver76** [comment]
I hope we can fix it in the adapter. Will probably affect many users, and I don't think the behavior will change from Chrome side

**Comment by raschy** [comment]
In Firefox you can write a value like '47,011' by entering a comma. This is not possible in Edge and Chrome.

**Comment by Wildbill-Z** [comment]
Same problem with Safari on iPad and with macOS.

**Comment by foxriver76** [comment]
Behavior has changed with the latest version. All valid number input should now be accepted.

**Comment by Wildbill-Z** [comment]
With latest version you mean [6.11.0](https://github.com/ioBroker/ioBroker.admin/blob/master/README.md#6110-2023-10-19) ? Any idea, when this one will become stable?

**Comment by foxriver76** [comment]
Indeed, no idea currently. Will take some weeks I guess.

**Comment by Wildbill-Z** [comment]
OK, no problem. I‘ll update just admin with latest and switch repo back to stable immediately. It is a kind of annoying bug…

**Comment by raschy** [comment]
Entries with commas are possible again without chin-ups. Thank you.
