### ISSUE TITLE
Error when clicking info button in intro tag

### ISSUE THREAD

**Issue by mibr85** [ioBroker/ioBroker.admin#2125]
**Describe the bug**  
i have a completly new ioBroker installation on Docker.
when i click in the intro tab on the smal info button i get an GUI ERROR.
it happen again and agaiun

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/56867583/74d3ba16-bbe5-45cc-b856-ea89e2e23f3c)

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/56867583/585137f7-e79e-4b0e-98de-3e3ecc312e6d)

F12 > Consol:
`Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. [192.168.100.140:8081](http://192.168.100.140:8081/#tab-intro)
iobroker.admin@6.10.1 [bootstrap.jsx:20:8](http://192.168.100.140:8081/static/js/bootstrap.jsx)
[2023-09-24T09:47:01.474Z] Try to connect [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Stored version: , new version: 6.10.1 [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Connected: true [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: Link [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: time [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: timeOffset [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: dockerInformation [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _nodeCurrent [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _nodeNewest [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _nodeNewestNext [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _npmCurrent [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _npmNewest [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Translate: _npmNewestNext [instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 13
        Ka
        d
        h
        e
        wo
        Ei
        ks
        ys
        vs
        us
        ss
        Hl
        ls
[instrument.ts:144](http://192.168.100.140:8081/static/node_modules/@sentry/src/instrument.ts)
    je instrument.ts:144
    React 11
        fo
        callback
        Ua
        wi
        ki
        bi
        Ss
        Ss
        ss
        Hl
        ls

1

​`

**Versions:**  
     Plattform: docker
    RAM: 3.8 GB
    Node.js: v18.17.1(18.18.0)
    NPM: 9.6.7(9.8.1)
host 5.0.12

**Additional context**

**Comment by Feuer-sturm** [comment]
Duplicate with #2113
