### ISSUE TITLE
Admin 6.10.3: Cannot parse json5 config for each adapter using jsonconfig

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/ioBroker.admin#2129]
**Describe the bug**  
With Admin 6.10.3 on my test installation I can't open any instance config for adapters using jsonconfig.
The part of the website normally containing the config stays empty and an error "[JsonConfig] Cannot parse json5 config!" is shown.

**To Reproduce**  
1. Update Admin to 6.10.3
2. Open any adapter instance config of an adapter using jsonconfig
3. See error

**Expected behavior**  
Adapter instance config renders.

**Screenshots & Logfiles**  

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24603271/f2b1f926-9dd0-4ef4-b783-aaef9763fa9c)

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24603271/3db4e5e0-30e9-411d-8cf8-a43d121060b8)

Browser console output:

```
[JsonConfig] Cannot parse json5 config! [instrument.ts:144]
SyntaxError: JSON5: invalid end of input at 1:1
    gu index.js:1456
    du index.js:1405
    start index.js:1189
    ru index.js:376
    value JsonConfig.tsx:435
    promise callback*value JsonConfig.tsx:410
    B JsonConfig.tsx:237
    promise callback*n JsonConfig.tsx:237
    React 13
    onHashChanged App.jsx:1398
    o helpers.ts:98
[instrument.ts:144]
```

**Versions:**  
 - Adapter version: 6.10.3
 - JS-Controller version: 5.0.12
 - Node version: 20.5.1
 - Operating system: Ubuntu 22.04

**Comment by mcm1957** [comment]
@foxriver76 
I think the jsonConfig-demo is using json5 if you need a test environment.

**Comment by foxriver76** [comment]
Its not necessarily json5, in my test installation I can only reproduce it with Discord adapter so far.

**Comment by ticaki** [comment]
This is a admin .3 problem not a testing enviroment. Same Problem on production systems with my Alpha Adapter reported. With version .2 every thing works as excepted. https://forum.iobroker.net/post/1050448

**Comment by Diginix** [comment]
I have the same issue with simpe-api adapter v2.7.2.

**Comment by foxriver76** [comment]
Is fixed with 6.10.4

**Comment by andreaskoerber** [comment]
I have the same problem with admin adapter 6.17.14 since yesterday.

**Comment by mcm1957** [comment]
> I have the same problem with admin adapter 6.17.14 since yesterday.

I auggest to open a NEW issue as this issue is closed since sep 2023.

And pleae provide more Information.
Ja-controller?
Opening ui of which Adapter? 
...
