### ISSUE TITLE
Admin 3.2.4 Host reload button is not working

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#213]
Hi,

the reload button at Host "tab" is not working. To get the view updated you need to move to another view and go back.

![admin_3 2 4_reload](https://user-images.githubusercontent.com/33424168/37210874-7447622a-23aa-11e8-9d0f-d8836407eb5a.jpg)

**Comment by GermanBluefox** [comment]
Fixed in 3.3.0

**Comment by wendy2702** [comment]
Thanks!
