### ISSUE TITLE
[JsonConfig] Cannot parse json5 config! with some adapters

### ISSUE THREAD

**Issue by Grothesk242** [ioBroker/ioBroker.admin#2130]
With some adapter/instances the message
[JsonConfig] Cannot parse json5 config!
appears when trying to enter the Settings Page. Page stays empty then.  
Adapters affected: 

    awtrix-light
    cloud
    opendtu
    followthesun
    govee-app

There may be more, didn't check them all. 

**Versions:**  
 - Adapter version: 6.10.3
 - JS-Controller version: 5.0.12
 - Node version: 18.18.0
 - Operating system: Debian Linux

**Comment by Grothesk242** [comment]
Regression. Going back to admin 6.10.2 everything works as expected.

**Comment by Diginix** [comment]
Duplicate #2129

**Comment by Grothesk242** [comment]
Oh, sorry. Did not check enough for previous entries.
