### ISSUE TITLE
Show migration suggestion by objects count > 15000

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.admin#2132]
If File/JsonL Database has more than 15000 objects, show suggestion message about migration to redis

**Comment by foxriver76** [comment]
Could be realized by the news logic, if we allow to check for db and number of objects, would be in general nice in some other scenarios.

**Comment by foxriver76** [comment]
done with https://github.com/ioBroker/ioBroker.docs/pull/451
