### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by H0Krab** [ioBroker/ioBroker.admin#2138]
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
    
    Was muss ich nun machen?

**Comment by Psychi1** [comment]
Hello,

here to:

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 17
        Ka
        d
        h
        e
        wo
        Ei
        ks
        ys
        vs
        us
        ss
        Hl
        ls
        ls
        rs
        enqueueSetState
        setState
    value IntroCard.jsx:291
    onClick IntroCard.jsx:413
    React 11
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
    o helpers.ts:98
instrument.ts:144
    je instrument.ts:144
    React 15
        fo
        callback
        Ua
        wi
        ki
        bi
        Ss
        Ss
        ss
        Hl
        ls
        (Async: VoidFunction)
    ls
        rs
        enqueueSetState
        setState
    value IntroCard.jsx:291
    onClick IntroCard.jsx:413
    React 11
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
    o helpers.ts:98
```

**Comment by Feuer-sturm** [comment]
@H0Krab
Bitte ergänze welche Admin Version bei dir installiert hast und was du genau gemacht hast, um den Fehler zu provozieren. 

 @Psychi1 
Deine Fehlermeldung sieht nicht identisch zu der im ersten Beitrag aus. Bitte erstelle ein eigenes issue und ergänze bitte ebenfalls deine Admin version und was du gemacht hast, um den fehler zu provozieren.

**Comment by Psychi1** [comment]
Done, Issue #2140

**Comment by H0Krab** [comment]
Hi @Feuer-sturm,
guter Hinweis, ich hatte die Admin Version 6.3 und habe nun auf 6.10.1 geupdatet. 
Neustart und alles wie gewohnt. Der Fehler scheint nun weg zu sein.
