### ISSUE TITLE
Description at PopUp Window after Admin modification is not clear!

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#214]
If you read this it means that you want to discard your changes.

![admin_popup](https://user-images.githubusercontent.com/33424168/37211031-ece2a64a-23aa-11e8-8683-1ace3b7ebdfc.jpg)

Better would be:

Einige Daten sind nicht gespeichert!
Speichern = OK
Verwerfen = Abbrechen

**Comment by GermanBluefox** [comment]
Bitte die Frage so formulieren, dass man immer noch OK und Abbrechen antworten kann.

OK muss aber heißen => wir gehen weiter und speichern nichts
Abbrechen => wir bleiben und haben die Möglichkeit noch zu speichern.

**Comment by wendy2702** [comment]
Wieso muss OK heißen wir speichern nichts!? Aktuell ist es doch so das nachdem ich etwas editiert habe dieses Fenster kommt und die Änderungen übernommen werden wenn ich "OK" drücke.

Text im PopUp dann vielleicht so:

Bitte bestätigen:
Einige Daten sind nicht gespeichert! 
Zum Speichern bitte OK drücken.
Zum Verwerfen bitte Abbrechen drücken.

**Comment by GermanBluefox** [comment]
Ich sehe kein Vorschlag. Bitte wenn noch aktuell, dann wieder aufmachen.

**Comment by wendy2702** [comment]
Verstehe ich nicht.

Hatte im ersten und vorletzten Post jeweils einen Vorschlag gemacht.

**Comment by robdg80** [comment]
Das ist wirklich nicht eindeutig.
Einfach dazuzuschreiben, wie OK und wie Abbrechen wirkt ist doch eine gute Lösung:

"Einige Daten sind nicht gespeichert!
Mit OK Änderungen verwerfen und ohne Speichern weiter.
Zum Speichern bitte Abbrechen drücken."

Damit sind dass dann nicht 30 Zeilen Code ändern, sondern nur 3. ;)

**Comment by wendy2702** [comment]
@GermanBluefox : Warum so aggressiv?

Ich hatte lediglich einen Vorschlag zur Verbesserung des "TEXTES" gemacht und glaube nicht das es 30 Zeilen Code Änderung erfordert wie auch @robdg80 geschrieben hat.

Unabhängig davon das ich den "Text" nicht eindeutig finde scheint der Button "OK" oder "Abbrechen" zumindest bei mir keine Wirkung zu haben. ADMIN 3.3.5, JS 1.3.0 Google Chrome

Beispiel:

Ich will den Verwahrungsort von "latest" auf "default" umstellen. Drücke in Admin 3.3.5 auf das Schraubenschlüssel Symbol und wähle im dropdown Menu "default", dann drücke ich auf Speichern und es öffnet sich das neue Popup während im hintergrund scheinbar die Änderung übernommen wird. 
Zu erkennen ist das daran das sich die Anzahl der Adapter für die es ein Update gibt ändert. 
Ich kann dann im PopUp drücken was ich will aber der geänderte Verwahrungsort bleibt auf "default" und wechselt nicht wieder zurück nach "latest"... was ich bei "verwerfen" erwarten würde.

Ist das so verständlich beschrieben?
