### ISSUE TITLE
Error in GUI! - diffent error message

### ISSUE THREAD

**Issue by Psychi1** [ioBroker/ioBroker.admin#2140]
**Describe the bug**  
An Error Message appears after clicking "Info" 

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35874716/c7316c31-3114-4fd0-9cc4-3858768a40e3)

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 17
        Ka
        d
        h
        e
        wo
        Ei
        ks
        ys
        vs
        us
        ss
        Hl
        ls
        ls
        rs
        enqueueSetState
        setState
    value IntroCard.jsx:291
    onClick IntroCard.jsx:413
    React 11
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
    o helpers.ts:98
instrument.ts:144
    je instrument.ts:144
    React 15
        fo
        callback
        Ua
        wi
        ki
        bi
        Ss
        Ss
        ss
        Hl
        ls
        (Async: VoidFunction)
    ls
        rs
        enqueueSetState
        setState
    value IntroCard.jsx:291
    onClick IntroCard.jsx:413
    React 11
        Re
        Be
        Ir
        Ir
        Ur
        Qr
        cs
        Le
        Qr
        qn
        $n
    o helpers.ts:98
```

**To Reproduce**  
1. Open IoBroker Admin Panel
2. Click on 'Info' in the upper right corner (s. picture at 'Describe the bug'-section)
3. The error appears

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35874716/56c85e25-ae22-49ac-95df-181e227fedb0)

**Expected behavior**  
No Error Message :-)

**Screenshots & Logfiles**  

see prior sections

**Versions:**  
 - Adapter version: 6.10.1
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1 (from Admin Panel)
 - Operating system: docker / https://hub.docker.com/r/buanet/iobroker

**Comment by Feuer-sturm** [comment]
duplicate to https://github.com/ioBroker/ioBroker.admin/issues/2113
issue is fixed with admin 6.10.2
