### ISSUE TITLE
Update of node.js from admin

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.admin#2149]
I as a user, want to update my node.js from admin interface, like js-controller

**Comment by mcm1957** [comment]
Check ev node-fix script from thomas brown at forum.

**Comment by foxriver76** [comment]
according to https://github.com/ioBroker/ioBroker/commit/152ce8d4d05309c4a29c031fef1eefcc9af29bb3 we would simply need to exec `iob nodejs-update`

**Comment by Apollon77** [comment]
The update script is mainly for major updates!

see also:
* https://github.com/ioBroker/ioBroker.js-controller/issues/2488
* https://github.com/ioBroker/ioBroker.js-controller/issues/2490
* https://github.com/ioBroker/ioBroker.js-controller/issues/2490

**Comment by foxriver76** [comment]
This is now implemented as beta feature with admin and controller v6. Will currently only upgrade to the newest available version in configured sources
