### ISSUE TITLE
Versionen Nummern von Adapter Updates werden nicht angehoben

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#2153]
Bei mir standen heute insgesamt 8 Adapter Updates (Latest) zur Verfügung (auch auf Admin 6.10.8)

Die Updates wurden via Admin scheinbar ausgeführt (Logging sah jedenfalls gut aus), jedoch wurde bei keinem der Adapter die Versionsnummer angehoben. 

Ich habe das gleiche dann nochmal via Konsole versucht, mit dem selben Ergebnis. Auffällig dabei war, das immer die NPM Version 8.14.0 angegeben wurde, obwohl in  der Admin Info Kachel NPM auf 9.6.7 steht .

Die Frage ist - stimmt nur die Versionsnummer nicht, oder wurden die Update tatsächlich nicht installiert.

Admin 6.10.6

Plattform Windows
Betriebssystem win32
Architektur x64
CPUs 4
Geschwindigkeit 1995 MHz
Modell Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM 7.93 GB
System-Betriebszeit
13 T. 14:19:53
Node.js v18.17.0 (Es gibt eine neuere Version: v18.18.2)
time 1697264008659
timeOffset -120
NPM 9.6.7
Anzahl der Adapter 590

**Comment by Feuer-sturm** [comment]
@JBSullivan poste doch mal hier die Langfassung von
`iob diag`
Dort werden ja auch die Adapterversionen, nodejs und npm versionen aufgelistet

**Comment by JBSullivan** [comment]
Den Befehl scheint es bei einer ioB Windows Installation nicht zu geben. Ich bekomme da nur die "Hilfe" Liste mit den zulässigen Befehlen.

**Comment by Feuer-sturm** [comment]
@JBSullivan du kannst einmal vorher ein
`iob fix` 
aufrufen, das ist der Weg wie iob diag nachgeladen wird. 
Kann dir aber auch nicht mit Garantie gerade sagen,  ob es unter Windows funktioniert.

**Comment by JBSullivan** [comment]
Also `iob fix` und somit `iob diag` scheint unter einer Win Installation nicht möglich zu sein. Daher kann ich leider mit keinen weiteren Daten "on Block" dienen.

![image](https://github.com/ioBroker/ioBroker.admin/assets/44617472/c45cbff0-9cbd-4547-8c09-641eb890bf48)

**Comment by JBSullivan** [comment]
So, ich habe das ganze jetzt nochmal über den Windows Installer 2.2.2 gemacht, welcher ja auch einen `iob fix` an Board hat und welcher gleichzeitig die Node & Npm Version auf den aktuellen Stand anpasst.

Auch hier hat der `iob fix` nicht funktioniert. Allerdings war das anheben, der Node Version erfolgreich, was dann wiederum dazu führte, das die oben angesprochenen Adapter Updates mit anschließender Versions Anhebung nun wieder funktioniert.

Aktuelle Version ist nun wie folgt und damit funktionieren die Adapter Updates wieder.

Plattform Windows
Betriebssystem win32
Architektur x64
CPUs 4
Geschwindigkeit 1995 MHz
Modell Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
RAM 7.93 GB
System-Betriebszeit 14 T. 18:59:40
Node.js v18.18.2
time 1697367011204
timeOffset -120
NPM 9.8.1
Anzahl der Adapter 590
Datenträgergröße 118.09 GB
freier Festplattenspeicher 35.88 GB
Aktive Instanzen 50
Pfad C:\ioBroker\GLT\
Betriebszeit 00:08:04
Hostname GLT


![image](https://github.com/ioBroker/ioBroker.admin/assets/44617472/f1283884-9c9c-4610-a45d-96ee77549f2c)

![image](https://github.com/ioBroker/ioBroker.admin/assets/44617472/8f8bd53e-ef72-4058-86db-dbf2f051c97e)

``

**Comment by Feuer-sturm** [comment]
@JBSullivan Bei Windows Installationen bin ich raus.
Wenn ich deinen letzten Beitrag richtig verstanden habe, dann läuft dein System wieder richtig. Es klingt für mich nicht nach einem Admin issue.
Ansonsten im Forum bein entsprechenden Windows Installer Beitrag mal dranhängen.

**Comment by Gaspode69** [comment]
Da war wohl irgendwas mit deiner Node.js Installation verbogen. Aus irgendeinem Grund wollte Windows einen Script Aufruf im Installer- bzw. Fixer-Script nicht in der Node Umgebung, sondern im [Windows Script Host](https://de.wikipedia.org/wiki/Windows_Script_Host) ausführen. Ich nehme an, die Aktualisierung der Node Version hat die Node.js Installation wieder gerade gebogen.

**Comment by foxriver76** [comment]
Nothing we can do here in admin

with current controller 5.0.17 these errors should no longe the hidden
