### ISSUE TITLE
Feature: Links to Forum / Github Issues at adapter tile

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2157]
**Is your feature request related to a problem? Please describe.**
Sometimes user ask questions at issues and sometimes user at forum ask how to create a issue

**Describe the solution you'd like**
I suggest to add links at admin Adapter tile 
- to forum with some text like 'Ask for support at forum ...'
- to issue page of github with some text like 'Creat problem reports and Feature requests here...'0

**Describe alternatives you've considered**
none except individaul support at issues / forum

**Additional context**
I consider this issue as a discussion base. If it has already discossed and dismissed, please feel free to close without much feedback!

**Comment by foxriver76** [comment]
We have the link for the issue tracker, but not for forum, also froum threads could change with versioning as far as I know or also be closed to various reasons. And of course only helpful for German community.

**Comment by mcm1957** [comment]
I would suggest to link to forum or forum area in general ... NOT to a specific topic.

Although it could be a good idea to have a fixed link topic per adapter which contains a link to the actual thread. But this would require a discussion at forum first
