### ISSUE TITLE
Cannot enter a negative number in objects->state->value

### ISSUE THREAD

**Issue by 1N4148** [ioBroker/ioBroker.admin#2159]
**Describe the bug**  
Since Admin 6.10.1 I cannot enter anymore a negative number in Objects->State->Value

**To Reproduce**  
1. Go to Objects
2. Click on a numerical state
3. Input box for state opens
4. Try to type in a negative number. As soon you hit '-' the number will be 0

**Expected behavior**  
In Admin 6.8.0 it works like expected, you can enter a negative number

**Versions:**  
 - Adapter version: 6.10.1
 - JS-Controller version: 5.0.12
 - Node version: 18.16.1
 - Operating system: Debian Bullseye x64

**Comment by Feuer-sturm** [comment]
@1N4148 
Is your adapter version `Adapter version: 6.8.0` correct?

I can reproduce your issue if I tried to start with an "-" befor entering a number.
Workaround which works on my system: First enter the number, go to the beginning and the write the "-"


Tested with Admin 6.10.8

**Comment by 1N4148** [comment]
@Feuer-sturm 

No, adapter version is 6.10.1, thanks for the hint. 

In 6.10.1 it works with your workaround
In 6.8.0 no workaround was required

So, probably something has been changed in the dialog box?
