### ISSUE TITLE
Overview tab missing in navigation

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#216]
The new overview tab is opened by default in v3.3.0, but it is not visible in the navigation by default:
![unbenannt](https://user-images.githubusercontent.com/17641229/37259700-f6cc6f98-2589-11e8-9c1c-c44b5931ec19.PNG)

**Comment by AlCalzone** [comment]
Not sure if that's related, but now it looks like this for me:
![unbenannt](https://user-images.githubusercontent.com/17641229/37553477-5cc8a83c-29c9-11e8-8af2-59d35026cbcd.PNG)

**Comment by GermanBluefox** [comment]
Fixed in 3.3.4
