### ISSUE TITLE
Darstellung im Darkmode

### ISSUE THREAD

**Issue by Boronsbruder** [ioBroker/ioBroker.admin#2160]
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/a72d0160-d8b6-4ea2-8616-3a707c9f8444)
Im Darkmode ist die Darstellung der hervorgehobenen Punkte extrem  schlecht lesbar.
Könnte man da was ändern?

Getestet in Chrome und Firefox im Admin v6.10.1

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/fdbda513-e7ce-4701-a021-d146436d79c9)
Ach ja und vielleicht die farbliche Hervorhebung wie in den hellen Themen übernehmen

**Comment by Feuer-sturm** [comment]
@Boronsbruder Hi, kommen für Screenshots aus dem Info Adapter oder wo kommen die Screenshots genau her?

**Comment by Boronsbruder** [comment]
Ja sind aus dem Info-Adapter:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/2d9e22b5-0840-4f3f-ab3f-4bf1d83c9e03)

**Comment by Feuer-sturm** [comment]
@foxriver76 @Apollon77 Is this an issue for admin or for https://github.com/iobroker-community-adapters/ioBroker.info repository? If for info repository please move issue because I don't have the access rights

**Comment by foxriver76** [comment]
I think info adapter.

**Comment by Feuer-sturm** [comment]
@mcm1957 @foxriver76 can you move the issue please to info adapter?

**Comment by foxriver76** [comment]
Maybe @Apollon77 can, it seems like I have no permission for Info adapter repo

**Comment by mcm1957** [comment]
@foxriver76 
You are member of community adapters
BUT a transfer is not possible. From github help:
```Note: You can only transfer issues between repositories owned by the same user or organization account.```

**Comment by mcm1957** [comment]
@Boronsbruder 
Please reopen tha issue at 
https://github.com/iobroker-community-adapters/ioBroker.info/issues
and close here

Thanks

**Comment by Apollon77** [comment]
Ican also not move it ... best is to recreate it

**Comment by mcm1957** [comment]
> Ican also not move it ... best is to recreate it

It's impossible as github docu states (see note above). community is another owner than iobroker. One canot move between owners.

**Comment by Boronsbruder** [comment]
Moved -> https://github.com/iobroker-community-adapters/ioBroker.info/issues/645#issue-1959579190
