### ISSUE TITLE
Cannot update news: TypeError: newNews.forEach is not a function

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.admin#2163]
**Describe the bug**  
Found this today in the log
`admin.0 | error | Cannot update news: TypeError: newNews.forEach is not a function`

**To Reproduce**  
In this point in time I was not in the admin tool and no specific job was running.

**Expected behavior**  
No error :-)

**Versions:**  
 - Adapter version: 6.10.4
 - JS-Controller version: 5.0.12
 - Node version: 18.18.2
 - Operating system: Linux Ubuntu 18.04

**Comment by maheshchandra10** [comment]
Let me see if I can work on this issue please.
