### ISSUE TITLE
Falsche Anzeige der Installierten Instanzen

### ISSUE THREAD

**Issue by vauvau07** [ioBroker/ioBroker.admin#217]
<img width="856" alt="admin 3 3 1" src="https://user-images.githubusercontent.com/34857880/37278915-8265a83a-25e9-11e8-9590-ab7f7b5aafa9.PNG">

**Comment by GermanBluefox** [comment]
Please test

**Comment by DutchmanNL** [comment]
fix confirmed in 3.3.9

**Comment by vauvau07** [comment]
die Anzeige ist jetzt in Ordnung. 
Danke

**Comment by vauvau07** [comment]
Die Anzeige ist jetzt in Ortnung
Danke
