### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by mfelber63** [ioBroker/ioBroker.admin#2172]
When clicking on 'iobroker' -> 'overview' -> 'info' I get "Error in GUI!" and in the console following error message.
------------------------------------------------------------------------------------------------------------------------------------------------
5966.a0d97006.chunk.js:2 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ka (4164.29c179b8.chunk.js:2:56521)
    at d (4164.29c179b8.chunk.js:2:58289)
    at h (4164.29c179b8.chunk.js:2:59436)
    at e (4164.29c179b8.chunk.js:2:61497)
    at wo (4164.29c179b8.chunk.js:2:73213)
    at Ei (4164.29c179b8.chunk.js:2:122139)
    at ks (4164.29c179b8.chunk.js:2:109418)
    at ys (4164.29c179b8.chunk.js:2:109346)
    at vs (4164.29c179b8.chunk.js:2:109209)
    at us (4164.29c179b8.chunk.js:2:105989)
    at ss (4164.29c179b8.chunk.js:2:106380)
    at Hl (4164.29c179b8.chunk.js:2:46920)
    at 4164.29c179b8.chunk.js:2:103922
(anonym) @ 5966.a0d97006.chunk.js:2
fo @ 4164.29c179b8.chunk.js:2

a.componentDidCatch.t.callback @ 4164.29c179b8.chunk.js:2
Ua @ 4164.29c179b8.chunk.js:2
wi @ 4164.29c179b8.chunk.js:2
ki @ 4164.29c179b8.chunk.js:2
bi @ 4164.29c179b8.chunk.js:2
(anonym) @ 4164.29c179b8.chunk.js:2
Ss @ 4164.29c179b8.chunk.js:2
ss @ 4164.29c179b8.chunk.js:2
Hl @ 4164.29c179b8.chunk.js:2
(anonym) @ 4164.29c179b8.chunk.js:2
------------------------------------------------------------------------------------------------------------------------------------------------
Plattform     docker
Betriebssystem     linux
Architektur     x64
CPUs     8
Geschwindigkeit     652 MHz
Modell     11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
RAM     31 GB
System-Betriebszeit     39 T. 04:38:29
Node.js     v18.17.1 (Es gibt eine neuere Version: v18.18.2)
time     1698069288219
timeOffset     -120
NPM     9.6.7
Anzahl der Adapter     505
dockerInformation      [object Object]
Datenträgergröße     456.89 GB
freier Festplattenspeicher     430.32 GB
Aktive Instanzen     27
Pfad     /opt/iobroker/
Betriebszeit     16:31:43
Hostname     XXXXX

**Comment by Feuer-sturm** [comment]
@mfelber63 sounds like it is duplicate to #2113 
Please verify with admin version >= 6.10.2
