### ISSUE TITLE
admin has an invalid jsonConfig: 

### ISSUE THREAD

**Issue by Brainbug01** [ioBroker/ioBroker.admin#2184]
v6.12.1

```
[{
"instancePath":"/items/reverseProxyTab/items/reverseProxy/items/1",
"schemaPath":"#/patternProperties/%5E.%2B/allOf/22/then/properties/items/items/allOf/31/then/allOf/1/additionalProperties",
"keyword":"additionalProperties",
"params":{"additionalProperty":"width"},
"message":"must NOT have additional properties"
},{
"instancePath":"/items/reverseProxyTab",
"schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if",
"keyword":"if",
"params":{"failingKeyword":"then"},
"message":"must match \"then\" schema"
}]
```

**Comment by GermanBluefox** [comment]
When this error message shown? By which jsonConfig file?

**Comment by Brainbug01** [comment]
Ich öffne den admin Reiter "Allgemeine Einstellungen"

**Comment by mcm1957** [comment]
Thanks

```
admin has an invalid jsonConfig:
```
was missing at the first posting. So its the admin adapter causing the warning

**Comment by mcm1957** [comment]
Yes, but admin raises this warning for invalid jsonConfigs of other adapters too. The adapter is identified by the mentioned text, the raising adapter at log is alwys admin. So the topic was not clear.
Thanks for fast feedback - will be checked. Warning should not have any negative effect on your system.

**Comment by Brainbug01** [comment]
Offtopic sorry dafür.

Ich habe jetzt beim device-watcher, netatmo, octoprint, operating-hours, ping, sayit, shelly und trashschedule ein Ticket eröffnet. Hoffe doch das es so richtig ist.

**Comment by mcm1957** [comment]
> Offtopic, sorry dafür.
> 
> Ich habe jetzt beim device-watcher, netatmo, octoprint, operating-hours, ping, sayit, shelly und trashschedule ein Ticket eröffnet mit den jeweiligen Meldungen. Hoffe doch das es so richtig ist.

ja passt schon

**Comment by mcm1957** [comment]
@foxriver76 
Hab die oben angeführten Adapter Issues gescannt und soweit notwindig / sinnvoll ein react v5 issue erstellt.

**Comment by foxriver76** [comment]
Ja Admin war leider etwas schneller stabvle als vermutet, wir wollten die issues erst mal im schema abhandeln. Dieses wird auch im schema angepasst werden.

**Comment by foxriver76** [comment]
fixed in schema
