### ISSUE TITLE
[jsonConfig] language field is empty when selecting system language ("system": true)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2185]
**Describe the bug**  

1. Go to instance settings of `admin.0`
2. Select "system language"
3. Field is empty

<img width="218" alt="Screenshot 2023-10-30 at 13 34 17" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/34efbda7-cddf-4696-8024-730278fa9bdb">

Saved value in `system.adapter.admin.0` is `"language": "",` (which is correct afaik). But the added value is `_`:

https://github.com/ioBroker/ioBroker.admin/blob/8982e59a79b533bbf7a129d4ba1071216cb705a2/src/src/components/JsonConfigComponent/ConfigLanguage.jsx#L76

But: The saved value is `''` when selected value is `_`:

https://github.com/ioBroker/ioBroker.admin/blob/dedc74a9d0337f68b395aad2cca41d13239c8b55/src/src/components/JsonConfigComponent/ConfigLanguage.jsx#L98

----

e.g. in admin:

https://github.com/ioBroker/ioBroker.admin/blob/8982e59a79b533bbf7a129d4ba1071216cb705a2/admin/jsonConfig.json5#L124-L132

**Versions:**  
 - Adapter version: 6.12.1
 - JS-Controller version: 5.0.12

**Comment by foxriver76** [comment]
Thanks for the report. I am unsure if I already get it correctly.

Do you mean the empty dropdown should save `_` to the config? Or vice versa - it does this but you would expect it to save just an empty string? Or did I get it completely wrong?

**Comment by klein0r** [comment]
Everything is working, except displaying "System language" in the Dropdown field after selection.

**Comment by foxriver76** [comment]
Thanks, I will check that
