### ISSUE TITLE
scroll bar not visible at adapter Info page i.e. for Sayit Adapter

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#219]
Hi,

it's not possible to scroll at the adapter info page. Tested with Google Chrome

![no_scroll](https://user-images.githubusercontent.com/33424168/37408880-548b7678-279d-11e8-9ab7-a34e3052a90a.jpg)

Admin 3.3.1
JS 1.2.7

**Comment by GermanBluefox** [comment]
Can you try 3.3.4?
![image](https://user-images.githubusercontent.com/4582016/37411569-62d170ec-27a3-11e8-8166-902f0415a06e.png)
When it published..

**Comment by wendy2702** [comment]
Yes for sure.

As soon as new version is available i will retest.

**Comment by wendy2702** [comment]
Hi,

any news about 3.3.4? Is it available via Github already?

For some reason i can't update/install Admin via "octocat" Button at Version 3.3.3 because Admin is not listed:

![admin_missing_github](https://user-images.githubusercontent.com/33424168/37716040-d416c1ba-2d1d-11e8-94d5-85a696a2f246.jpg)

**Comment by wendy2702** [comment]
Today i tried to update Admin from 3.3.3 to 3.3.4 using procedure provided by AlCalzone

https://forum.iobroker.net/viewtopic.php?f=22&t=12776#p135679

After doing the upgrade admin adapter can be startet but at Browser i get this message:

``This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.``

Any advice on how to upgrade for testing?

**Comment by wendy2702** [comment]
Just managed to install Admin 3.3.4 but scrollbar is still missing. Tried to delete cache, forced-reload without sucess.

![sayit_no_scrollbar](https://user-images.githubusercontent.com/33424168/37825102-07aa5196-2e8f-11e8-9258-7bb9085763d3.jpg)
![sayit_no_scrollbar1](https://user-images.githubusercontent.com/33424168/37825114-0c54f08e-2e8f-11e8-95b1-a909bfea9175.jpg)


Tried also with other Adapters.

**Comment by wendy2702** [comment]
With Admin 3.3.5 still no scrollbar visible:

![738aa5dc-b22f-462a-a447-3e153fd3f78c](https://user-images.githubusercontent.com/33424168/37952475-24d7f5d4-31a0-11e8-87cf-373c16e901fa.png)
