### ISSUE TITLE
[jsonConfig.json] autocompleteSendTo Increase the amount of data

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2190]
**Is your feature request related to a problem? Please describe.**
In meinem Adapter habe ich eine Liste mit 10000 Orten, von diesen werden ca. 700 angezeigt und der Nutzer muß hin und herklicken damit ein neuer Sendto ausgelöst wird und er eine kleiner Liste bekommt. Das führt dazu das Tester behaupten Orte wären nicht da und ich ihn an die Hand gehen muß.

**Describe the solution you'd like**
Erhöhung der möglichen Arrayeinträge im callback() auf über 10000

**Comment by foxriver76** [comment]
I don't think that there is a hard limit of `700`, it would help providing a reproduceable example or linking the affected adapter so someone could reproduce this.

**Comment by ticaki** [comment]
Ich habe das jetzt nochmal neu gemacht, allen code rausgeworfen, der irgendwelche Probleme auffangen soll und es funktioniert wie erhofft. Entschuldige für den falschen Report, hätte das vor dem Issue machen sollen.
