### ISSUE TITLE
jsonUI not recognizing more than 1 value when returned as native:{} in message handler in main.js

### ISSUE THREAD

**Issue by foxthefox** [ioBroker/ioBroker.admin#2196]
**Describe the bug**  
When using the native option to return values from the message handler in main.js only 1 item is taken over into the config page of the adapter. I am returning 4 values and 3 of them are not taken over to the configuration.

**To Reproduce**  
1. define 4 values in io-packege.json and jsonUiconfig.json
2. create function that corresponds to the sendTo message from adapter config page
3. put 4 values with same identifier as object in the object native:{} as returned message
4. check the 4 values to be identical with the ones return from message handler in main.js

**Expected behavior**  
When 4 values are inside the returned message as native:{}, I am expecting all of them recognized and processed in the adapter configuration page.

**Screenshots & Logfiles**  
initial setup values:
![Bildschirmfoto 2023-11-01 um 13 56 14](https://github.com/ioBroker/ioBroker.admin/assets/16841643/8d17dc43-922a-48d2-8ea9-db2d2af970b8)

after returned message:
![Bildschirmfoto 2023-11-01 um 13 56 31](https://github.com/ioBroker/ioBroker.admin/assets/16841643/0380247a-c750-4bb1-8094-ece9d42a45dc)

**Versions:**  
 - Adapter version: 6.12.0
 - JS-Controller version: 5.0.12
 - Operating system: linux on proxmox

**Additional context**  
I have 4 values in the config page to be set by returning them from a function in sendTo.

in jsonUIconfig I have:
```
		"mqttUserId": {
			"type": "text",
			"label": "mqtt userId",
			"newLine": false
		},
		"mqttUserName": {
			"type": "text",
			"label": "mqtt user name",
			"newLine": false
		},
		"mqttPwd": {
			"type": "text",
			"label": "mqtt pwd",
			"newLine": true
		},
		"mqttClientId": {
			"type": "text",
			"label": "mqtt pwd",
			"newLine": false
		},
//this is the button to toggle the function and get 4 values in return
		"_create": {
			"type": "sendTo",
			"label": "Create Login Data",
			"command": "create",
			"variant": "outlined",
			"useNative": true,
			"jsonData": "{\"user\": \"${data.mqttUserName}\", \"pass\": \"${data.mqttPwd}\"}}"
		}
```

and in the message portion I have 
```
// the placeholder for the function
	const resultFromFunction = {
		native: {
			mqttUserId: '1232445564356',
			mqttUserName: 'login.User',
			mqttPwd: 'login.Password',
			mqttClientId: 'login.clientID'
		}
	};
	this.sendTo(obj.from, obj.command, resultFromFunction, obj.callback);
```

after returning the message only the last value is modified in the config page of the adapter.
If I reduce it to one value, it is running OK.

**Comment by foxthefox** [comment]
After installation of 6.12.2 it seems still not working. Is there something what has to be done after installation?

**Comment by foxriver76** [comment]
no, then needs further investigation from our side

**Comment by foxriver76** [comment]
Do you have the code somewhere on GitHub so I can easily reproduce?

**Comment by foxriver76** [comment]
thanks a lot, found the problem - will be fixed in next version. However, some info for you: 

the last `}` at https://github.com/foxthefox/ioBroker.greensolar-battery/blob/dffb2f8b82e298226a28ffce13c8b0d580b0dd11/admin/jsonConfig.json#L78 is wrong


at https://github.com/foxthefox/ioBroker.greensolar-battery/blob/dffb2f8b82e298226a28ffce13c8b0d580b0dd11/main.js#L179-L182

you need to remove the `data.` prefix.

**Comment by foxthefox** [comment]
Thank you very much for the patch.
Thank you also for your comments, especially the }. The data. was one of my last attempts to get it working, I tried a lot :-)

**Comment by foxthefox** [comment]
Its working perfectly now. :-)
