### ISSUE TITLE
[jsonConfig] type": "accordion", "noDelete": true not work as excepted.

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2197]
**Describe the bug**  
Trotz `noDelete = true` ist ein funktionierender Löschknopf vorhanden (bei Tabellen das selbe wenn ich mich recht entsinne)

**Expected behavior**  
Kein löschen möglich.

**Screenshots & Logfiles**  
```
                    "type": "accordion",
                    "noDelete": true,                
```
<img width="714" alt="Bildschirmfoto 2023-11-01 um 15 25 14" src="https://github.com/ioBroker/ioBroker.admin/assets/59184294/b3e3dd59-b63b-48bb-b820-b2ec33c1e557">

**Versions:**  
 - Adapter version: v6.12.1

**Comment by foxriver76** [comment]
@klein0r fyi: afair you have provided the component. If you want to have a look yourself, let me know.

**Comment by klein0r** [comment]
@foxriver76 I'll check that
