### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by muellcy** [ioBroker/ioBroker.admin#2198]
**Describe the bug**  
"Error in GUI" Page will be display after clicking on "hosts.
Happens after update to js version5.x

**To Reproduce**  
1. Click on " hosts" or on "hosts" and "admin"

**Screenshots & Logfiles**  

<img width="565" alt="2023-11-01 16_04_43-hosts - 80ca9d8a2083" src="https://github.com/ioBroker/ioBroker.admin/assets/54805849/1a5e790a-c74d-403e-9095-147410e56fad">

**Versions:**  
 - Adapter version: latest
 - JS-Controller version: <5.0.12> 
 - Node version: <v18.18.2> 
 - Admin Version: <6.3.5>
 - Operating system: <Synology DMS 7.2-64650 Unix>

**Additional context**  
Admin Console is not working anymore

**Comment by Feuer-sturm** [comment]
@muellcy please update to stable admin version 6.12.0. If this issue is still there we can reopen the issue.
