### ISSUE TITLE
Admin 3.1.12: Not possible to switch host 

### ISSUE THREAD

**Issue by Goersch** [ioBroker/ioBroker.admin#220]
Using an iPad , it is not possible to change the host with the „host“ button. The drop down list opens, but selecting a host doesn‘t change the actual host.

It would be nice to get an overview of used/free mem of the hosts within the host overview.

**Comment by wendy2702** [comment]
This problem exist at Admin 3.3.5 as well. Using IPad Air 2 with Chrome Browser:

![a1751b75-5095-40c4-99d5-381590057f05](https://user-images.githubusercontent.com/33424168/37952354-c8744f22-319f-11e8-97f8-179a0b8295db.png)

**Comment by Goersch** [comment]
Yesterday I changed my setup from „files“ to „redis“ and now it works. Of course, I don‘t know if there is a relation, but that is what I observed (l am still on 3.1.12).

It looks even like using redis uses appr. 200kB less RAM (which is a lot on Raspis) but I will have to observe this.

**Comment by Apollon77** [comment]
> It looks even like using redis uses appr. 200Mb less RAM (which is a lot on Raspis) but I will have to observe this.

This can be, BUT the memonry needs to be used by the additional Redis process, or !?

**Comment by Goersch** [comment]
Well, while reading your answer I recognized myself that I didn‘t stop redis when switching from redis to files.

Anyway, since I switched back to redis the log function within the script page works again and everything seems to be faster (just a feeling).

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/228
