### ISSUE TITLE
[jsonConfig] "type" = "autocompleteSendTo" property "freesolo": false not work as excepted.

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2200]
**Describe the bug**  
`freeSolo - Set freeSolo to true, so the textbox can contain any arbitrary value. `
 ```
                            "type": "autocompleteSendTo",
                            "freeSolo": false,
```
Ich verstehe die definition so, das der Nutzer bei false keinen eigenen Namen vorgeben kann. Jedoch wird ihm aktuell seine Eingabe zur Auswahl angeboten.

EDIT: gleiches Verhalten wenn freesolo weg gelassen wird oder true ist.

**Expected behavior**  
Seine eigene Eingabe sollte nicht als Auswahlmöglichkeit angeboten werden

**Screenshots & Logfiles**  
<img width="606" alt="Bildschirmfoto 2023-11-02 um 09 23 14" src="https://github.com/ioBroker/ioBroker.admin/assets/59184294/df930e5e-d388-4cbe-8280-dce2d2a80320">

**Versions:**  
 - Adapter version: v6.12.0

**Comment by foxriver76** [comment]
Intended behavior is: https://mui.com/material-ui/react-autocomplete/

Without freeSolo, you should not be able to select free text, with free solo it should be able. 
I see, that this is not the current behavior for autocomplete components.
