### ISSUE TITLE
Fehlerhafte Schemawarnung

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2201]
Beim Öffnen der Adapterconfig erscheint folgende Warnung:

`janitza-gridvis has an invalid jsonConfig: [{"instancePath":"/items/mainTab/items/projectname","schemaPath":"#/patternProperties/%5E.%2B/allOf/2/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"alsoDependsOn"},"message":"must NOT have additional properties"},{"instancePath":"/items/mainTab","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

Dies ist ein selectSendTo, welches mit dem alsoDependsOn funktioniert und dieses auch benötigt (Für die Anwendung)
Hier ist denke ich etwas in der Prüfung des Schemas / der Doku falsch.

**Comment by mcm1957** [comment]
Schema Probleme in Zukunft bitte in https://github.com/ioBroker/adapter-react-v5 loggen.
Und bitte einen LINK auf das entsprechende jsonConfig File mitposten - Foxriver erspart sich dann Sucharbeit.

**Comment by mcm1957** [comment]
Nachtrag:
Was soll bei einem selectSendTo passieren wenn sich einer der anderen Werte ändert? alsoDependsOn macht ja nur einen Sinn, wenn die Componente sich ändert wenn sich ein alsoDependsOn Wert ändert - also z.B. bei sendTo. selectSendTo erfordert doch explizit dass der User das select ausführt ... 

Aber ok - ev versteh ich da was falsch. Werten wir auf Feedback von Foxriver76

**Comment by foxriver76** [comment]
Ja es ist möglich: https://github.com/ioBroker/ioBroker.admin/blob/46d494bd0f6996766e0062588334bf4459910677/src/src/components/JsonConfigComponent/ConfigSelectSendTo.jsx#L105

Ich vermute, dass die anderen Werte auch ausgefüllt sein müssen für das sendTo, habe jetzt allerdings nicht genau rein geschaut

**Comment by mcm1957** [comment]
Ok, dann fehlt es definitiv auch in der DOCU.

Aber die Funktion würd mich auch interessieren. Normalerweise ist selectSendTo mit einer DropDown Auswahl verbunden. Wenn ich nun ein ANDERES Elemnt ändere wird ein neuer Callback ausgeführt. Da ich da auf einem snderen Feld stehe kann ich nichts auswählen. Was steht dann nach dem Callback im Auswahlfeld ? Irgendwie wirkt das komisch ...

**Comment by foxriver76** [comment]
added to schema at https://github.com/ioBroker/adapter-react-v5/pull/227

**Comment by foxriver76** [comment]
ja funktion wie bei allen sendTo varianten mit alsoDependsOn: `  - `alsoDependsOn` - by change of which attributes, the command must be resent`

Sprich wenn sich eines der Fehler im Array ändert wird sendTo erneut ausgeführt.

**Comment by mcm1957** [comment]
Und mit welcher Auswirkung !?
Bei testSenTo wird das Textfeld mit neuem Inhalt befüllt - ok
Aber bei selectSendTo müßte ja dann der User aus der Auswahlliste die das selectSendTo reourniert was auswählen. Nur der Cursor steht zu dem Zeitpunkt gar nicht dort ...

**Comment by mcm1957** [comment]
Na ja - die Frage wäre ob jedesmal wenn man dass Feld anklickt um etwas auszuwählen ein sendTo geschickt wird oder die Liste der auswählbaren Daten lokal geached wird. Wenn sie gecached werden, dann macht ein alsoDendsOn einen Sinn. Wenn eh bei jedem neuen Auswhalzugriff ein selectSendTo abgesetzut wird, dann machen zwischenzeiotlich Callouts eigentloich keinen Sinn - außer ein Adapter lebt von "Nebenwirkungen" des callouts. Weil den ausgewählten Wert kann der selectSendTo ja (hoffentlich) nicht direkt verändern.

**Comment by BenAhrdt** [comment]
@mcm1957 @foxriver76 
Ich habe das issue hier platziert, da foxriver mir das geschrieben hatte.
Die Funktion ist die:
Es gibt ip, Port und Projektname.
Wenn mit dem selectsendto das Prokekt ausgewählt wird, wird eine Anfrage an eine api gesendet.
Wenn nun bsp. Der Port geändert wird, so wird mittels alsoDependsTo erneut das selectsendTo ausgeführt (es wird ip und Port mit gesendet)
Es erkennt, dann bspw. Andere Projekte, oder keine Verbindung und verändert das Dropdown-Menü.

**Comment by foxriver76** [comment]
Falls du das meinst, bezog sich auf das nicht funktionierende Filter add https://github.com/ioBroker/adapter-react-v5/issues/225#issuecomment-1790265011 Schema meckerei ist Adapter react und nicht funktionieren von json Config ist Admin. Sorry aktuell etwas verstreut

**Comment by BenAhrdt** [comment]
Ok. Stimmt.
Aber hoffe es ist rüber gekommen, dass das sendTo dich das alsoDependsOn gefüllt / neu gefüllt wird
