### ISSUE TITLE
Node.removeChild: The node to be removed is not a child of this node 

### ISSUE THREAD

**Issue by ReneMuell** [ioBroker/ioBroker.admin#2205]
Ich bekomme die folgende Fehlermeldung:

Node.removeChild: The node to be removed is not a child of this node

**Comment by Feuer-sturm** [comment]
@ReneMuell Bitte ergänzen weitere Details: welche Admin Version ist installiert, was machst du, um den Fehler zu provozieren, Log Auszug der Konsole (F12) wenn der fehler auftritt

**Comment by ReneMuell** [comment]
Der Fehler tritt immer auf, wenn ich auf "Systemeinstellungen" (Schraubenschlüssel) drücke. -> Fehler in GUI
![2](https://github.com/ioBroker/ioBroker.admin/assets/149803600/2e5017ab-0bce-41e2-b771-b3b5c78e83ed)

**Comment by Feuer-sturm** [comment]
@ReneMuell und welche Admin Version hast du installiert?
Folge bitte acuh der Anweisung, drücke F12 und kopiere die Fehler aus dem Tab Konsole hier in dein issue

**Comment by ReneMuell** [comment]
1. Fehler:
TypeError: e.NSSS is undefined NSSSDarkModeCS.js:1:24703
    <anonym> moz-extension://c5bbbec6-4dc9-4c73-a46a-7e2460fd6ca4/content/scripts/NSSSDarkModeCS.js:1
    <anonym> moz-extension://c5bbbec6-4dc9-4c73-a46a-7e2460fd6ca4/content/scripts/NSSSDarkModeCS.js:1
    inject resource://gre/modules/ExtensionContent.sys.mjs:581
    AsyncFunctionNext self-hosted:852

2. Fehler 
3.DOMException: Node.removeChild: The node to be removed is not a child of this node
    React 100
instrument.ts:144
    Fe instrument.ts:144
    React 13
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
![1](https://github.com/ioBroker/ioBroker.admin/assets/149803600/dec64332-89aa-4b73-b70f-9347170c26d9)
![2](https://github.com/ioBroker/ioBroker.admin/assets/149803600/f7236b97-5b39-4c17-9238-5cfa1a418224)

**Comment by Feuer-sturm** [comment]
@ReneMuell Verwendest du eine automatische Übersetzung deiner Webseiten? Wenn ja bitte die automatische Übersetzung abschalten.

**Comment by Apollon77** [comment]
Remove child hatte Bluefox mal gesagt meistens wenn admin aktualisiert wurde aber nicht neu geladen im Browser ... Also Reload tut gut?

**Comment by ReneMuell** [comment]
Da ich ja erst neu mit iobroker angefangen habe, habe ich einfach neu installiert und die automatische Webseitenübersetzung ausgeschaltet. Bis jetzt läuft wieder alles soweit (TR-04; Shelly und fritzbox dect).

**Comment by Feuer-sturm** [comment]
@ReneMuell OK, dann schließe ich das issue hier erstmal. Wenn das Problem wieder Auftritt, können wir es wieder öffnen.
