### ISSUE TITLE
[jsonConfig] textInputSendTo, capability to send text fields by messaging

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#2207]
**Is your feature request related to a problem? Please describe.**
JSON config support different sendTo capabilities, for text items we are currently able to request an value (readOnly) from the backend and show in admin.

We miss the option to have a text field as input to send its content to the backend.

**Describe the solution you'd like**
I would like to have an option in JSON config to have an text-field I provide information which can be submitted by sendTo to the backend without saving its contents to the instance object.

**Describe alternatives you've considered**
We tried all possible combinations (with support of our dev telegram group) to find a proper solution to handle the use-case:

- Text field as input
- Not saved in instance object
- Send its content to the backend

Unfortunately we were unable to succeed

**Additional context**
This kind of input fields can be very useful to communicate with the backed, in situation as WLED, ESPHome or SourceAnalytix data to connect devices must be send to the backend which should not be stored in instance object

**Comment by mcm1957** [comment]
Creating a text field which is not stored in config ispossible using attribute  ```"doNotSave": true,```
The content of a text field can be sent to backend by pressing a button is already posssible. See https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/blob/1952b7a7a8eb2fded9fb5e857412ca4415a69f1d/admin/jsonConfig.json#L31

Do you mean to create a Component which sends the data to the backend when the text filed is left? Or after entereing every character? Or something completly others?

**Comment by DutchmanNL** [comment]
> Creating a text field which is not stored in config is possible using attribute `"doNotSave": true,`
> The content of a text field can be sent to backend by pressing a button is already posssible. See https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/blob/1952b7a7a8eb2fded9fb5e857412ca4415a69f1d/admin/jsonConfig.json#L31

Interesting, I tried to adopt the code but its not working.

I created a text field as input:

```
				"deviceInput-IP": {
					"type": "text",
					"xs": 3,
					"sm": 3,
					"md": 3,
					"lg": 3,
					"label": "Select existing device or Enter IP of new device",
					"tooltip": "TypeFilter"
				},
```

in addition a button with send to and linking, like in the example, to data.XXX attribute
But the message coming does not contain content of the text input field, message result:

```
{
  "command": "getStationId",
  "message": {
    "username": "${data.deviceInput-IP}",
    "password": "${deviceInput-apiCredentials}"
  },
  "from": "system.adapter.admin.0",
  "callback": {
    "message": {
      "username": "${data.deviceInput-IP}",
      "password": "${deviceInput-apiCredentials}"
    },
    "id": 395,
    "ack": false,
    "time": 1699283148423
  },
  "_id": 1897755
}
```

As you see, I get ```"username": "${data.deviceInput-IP}",``` instead of the value containing in deviceInput-IP

> Do you mean to create a Component which sends the data to the backend when the text filed is left? Or after entereing every character? Or something completly others?

No I am basically more than happy if we can use a button to submit the text of an input field

**Comment by DutchmanNL** [comment]
ok, it looks like this setup works with an text-box (which is nice) but not for autocomplete.
When using autocomplete as input I get just the string back and not the value

**Comment by mcm1957** [comment]
> ok, it looks like this setup works with an text-box (which is nice) but not for autocomplete. When using autocomplete as input I get just the string back and not the value

Might be an error ...

**Comment by DutchmanNL** [comment]
> > ok, it looks like this setup works with an text-box (which is nice) but not for autocomplete. When using autocomplete as input I get just the string back and not the value
> 
> Might be an error ...

I will double check with my code and if that's the case raise a new issue to address that part.
But in generic, thank you @mcm1957 (again :P) you feedback solved my problem :)

**Comment by DutchmanNL** [comment]
working configuration example, also with autocompleteSelectSendTo (you must ensure your array entry does not have any - in their naming:

```
"deviceList": {
			"type": "panel",
			"label": "Ignore List",
			"items": {
				"deviceIP": {
					"newLine": true,
					"type": "autocompleteSendTo",
					"command": "getDeviceIPs",
					"jsonData": "{ \"service\": \"${data.deviceInputIP}\" }",
					"xs": 3,
					"sm": 3,
					"md": 3,
					"lg": 3,
					"label": "Select existing device or Enter IP of new device",
					"tooltip": "TypeFilter"
				},
				"encryptionKey": {
					"type": "password",
					"label": "Encryption Key",
					"doNotSave": true,
					"hidden": "!_alive",
					"default": "",
					"tooltip": "ttCloudPassword",
					"help": "hlpCloudPassword"
				},
				"apiPassword": {
					"type": "password",
					"label": "API password (legacy",
					"doNotSave": true,
					"hidden": "!_alive",
					"default": "",
					"tooltip": "ttCloudPassword",
					"help": "hlpCloudPassword"
				},
				"_addUpdateDevice": {
					"type": "sendTo",
					"label": "lblGetStationId",
					"variant": "outlined",
					"showProcess": true,
					"command": "_addUpdateDevice",
					"jsonData": "{ \"ip\": \"${data.deviceIP}\", \"encryptionKey\": \"${data.encryptionKey}\", \"apiPassword\": \"${data.apiPassword}\" }",
					"useNative": true,
					"disabled": "data.deviceIP===''",
					"hidden": "!_alive",
					"tooltip": "ttGetStationId",
					"help": "hlpGetStationId"
				}
			}
		}
```

**Comment by mcm1957** [comment]
@DutchmanNL 
If a '-' at any normally valid position causes this functionality to fail, this should be logged as an issue in my opinion.
Id are allowed to contain a minus sign. But not sure what you mean with  'array entry does not have any - in their naming:'

**Comment by DutchmanNL** [comment]
> @DutchmanNL If a '-' at any normally valid position causes this functionality to fail, this should be logged as an issue in my opinion. Id are allowed to contain a minus sign. But not sure what you mean with 'array entry does not have any - in their naming:'

I will finish my current part and cool down of all Invest stuff, clean all up and try to reproduce. If reproducible indeed an issue should be made and I will take care of it
