### ISSUE TITLE
[JSON-Config] Add capability for showProcess to return OK of failed

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#2208]
**Is your feature request related to a problem? Please describe.**
Functionality "showProcess" is available in JSON-Config, as example this helps to identify if an request is pending or executed/confirmed by backend

I didn't find any documentation about OK/Not-OK feedback, currently when replying with an empty message you always get:

![2023-11-06 19 11 29](https://github.com/ioBroker/ioBroker.admin/assets/7318445/2d0999c6-454e-47c6-898b-ebab9a43bfd7)

Which can be misleading

**Describe the solution you'd like**
I would like to habe the possibility to response to the message:

Like

```
response: {"result" : "ok", "response" : "OK"}
```

or when it fails

```
response: {"result" : "failed", "response" : "Provided data has an incorrect Device Name"
```

**Describe alternatives you've considered**
I don't see an alternative for this option to have proper feedback in Admin UI without using custom components or react

**Comment by mcm1957** [comment]
sendTo has this functionality.

see https://github.com/mcm1957/ioBroker.jsonconfig-demo/blob/4989dd8cb05e97a41d94fb7b00476ae96202f803/admin/jsonConfig.json5#L1238

**Comment by DutchmanNL** [comment]
> sendTo has this functionality.
> 
> see https://github.com/mcm1957/ioBroker.jsonconfig-demo/blob/4989dd8cb05e97a41d94fb7b00476ae96202f803/admin/jsonConfig.json5#L1238
> 
> Although its not su optimal that OK and error are formatted complely different

your are referring to an select, not select sendTo were the OK/FAIL message would come from the backend but will give it a try and provide feedback.
I was not able to find that by documentation

**Comment by DutchmanNL** [comment]
> Although its not su optimal that OK and error are formatted complely different

tried but no, its not possible to add these attributes to an sendTo type like:

```
				"addUpdateDevice": {
					"type": "sendTo",
					"command": "addUpdatedevice",
					"jsonData": "{ \"deviceIP\": \"${data.deviceInput-IP}\"}",
					"label": "Add or Update device",
					"tooltip": "restoreDefaultToolTip",
					"useNative": true,
					"newLine": true,
					"xs": 2,
					"sm": 2,
					"md": 2,
					"lg": 2
				},
```

![Screenshot 2023-11-06 at 20 29 17](https://github.com/ioBroker/ioBroker.admin/assets/7318445/e2892e67-5f84-48ea-8a5a-039b91c51463)

**Comment by mcm1957** [comment]
The select is used to fill different intpu to the sendTo. The sendTo is triggered by the button. The following code shows error or ok return:
https://github.com/mcm1957/ioBroker.jsonconfig-demo/blob/4989dd8cb05e97a41d94fb7b00476ae96202f803/main.js#L165

**Comment by DutchmanNL** [comment]
> The sendTo is triggered by the button. The following code shows error or ok return:

lovely thank you! Will give it a try and provide feedback

**Comment by DutchmanNL** [comment]
@mcm1957 confirmed, thank you providing this example !
