### ISSUE TITLE
Fehler beim öffen der Objekte unter "0_Userdata...

### ISSUE THREAD

**Issue by Danisun07** [ioBroker/ioBroker.admin#2209]
DOMException: Node.removeChild: The node to be removed is not a child of this node
    React 100
instrument.ts:144
    Fe instrument.ts:144
    React 13
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14

**Comment by Apollon77** [comment]
Maybe YOu updated admin? Try to reload .. happens again then?

**Comment by Danisun07** [comment]
Yes, I reloaded “Admin” or installed an older instance. Unfortunately, this didn't fix the error either. My current version is 6.10.5
Possible version: 6.12.0;

**Comment by Feuer-sturm** [comment]
Please verify with current stable version
