### ISSUE TITLE
adminUI.tab is changed to 'html' when materializeTab isn't true

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2210]
**Describe the bug**  

Defined a new tab like this:

```json
    "adminUI": {
      "config": "none",
      "tab": "materialize"
    },
```

Generated message:

`Please modify "${obj._id.replace(/\.\d+$/, '')}" common.adminUI=html`

because default is `html` if `common.materializeTab` is not defined

https://github.com/ioBroker/ioBroker.admin/blob/dedc74a9d0337f68b395aad2cca41d13239c8b55/src/src/Utils.tsx#L498-L509

----

Workaround:

```json
    "materializeTab": true,
    "adminUI": {
      "config": "none",
      "tab": "materialize"
    },
```

**Versions:**  
 - Adapter version: 6.12.2

**Comment by klein0r** [comment]
Maybe this is an issue in the adapter-creator when creating a new adapter with custom react tab:

https://github.com/ioBroker/create-adapter/blob/dc0c265ebbbb74844011a8439d5c565ebe235217/templates/io-package.json.ts#L118C48-L118C48

At the moment a `tab_m.html` is created and `common.adminUI.tab: "materialize"` instead of `tab.html` and `common.adminUI.tab: "html"`

**Comment by foxriver76** [comment]
`materialize` and `html` are valid values, so from my point of view admin should not replace a valid value
