### ISSUE TITLE
Error in GUI!

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.admin#2214]
JS - 5.0.16
sayit - 3.0.5
http://192.168.10.116:8081/#tab-instances/config/system.adapter.sayit.0

iobroker.admin@6.12.2
instrument.ts:145 [2023-11-12T11:39:46.007Z] Try to connect
instrument.ts:145 Stored version: , new version: 6.12.2
instrument.ts:145 Connected: true
instrument.ts:145 system.adapter.admin.0
instrument.ts:145 system.adapter.alarm.0
instrument.ts:145 system.adapter.backitup.0
instrument.ts:145 system.adapter.devices.0
instrument.ts:145 system.adapter.echarts.0
instrument.ts:145 system.adapter.history.0
instrument.ts:145 system.adapter.info.0
instrument.ts:145 system.adapter.iot.0
instrument.ts:145 system.adapter.javascript.0
instrument.ts:145 system.adapter.lovelace.0
instrument.ts:145 system.adapter.material.0
instrument.ts:145 system.adapter.megadd2.0
instrument.ts:145 system.adapter.megadd2.1
instrument.ts:145 system.adapter.megadd2.2
instrument.ts:145 system.adapter.megadd2.3
instrument.ts:145 system.adapter.megadd2.4
instrument.ts:145 system.adapter.megadd2.5
instrument.ts:145 system.adapter.megadd2.6
instrument.ts:145 system.adapter.megadd2.7
instrument.ts:145 system.adapter.megadd2.8
instrument.ts:145 system.adapter.megadd2.9
instrument.ts:145 system.adapter.mpd.0
instrument.ts:145 system.adapter.mqtt.0
instrument.ts:145 system.adapter.opi.0
instrument.ts:145 system.adapter.ping.0
instrument.ts:145 system.adapter.rickshaw.0
instrument.ts:145 system.adapter.rpi2.0
instrument.ts:145 system.adapter.sayit.0
instrument.ts:145 system.adapter.sonoff.0
instrument.ts:145 system.adapter.telegram.0
instrument.ts:145 system.adapter.vis.0
instrument.ts:145 system.adapter.web.0
instrument.ts:145 system.adapter.yahka.0
instrument.ts:145 system.adapter.zigbee.0
instrument.ts:145 getInstances: 198
instrument.ts:145 fetch http://192.168.10.116:8081/validate_config/sayit
instrument.ts:145 Translation for word "All" in "ru" was ignored: existing = "все", new = Все
(анонимная) @ instrument.ts:145
(анонимная) @ i18n.js:106
value @ i18n.js:102
(анонимная) @ index.jsx:87
f @ regeneratorRuntime.js:45
(анонимная) @ regeneratorRuntime.js:133
(анонимная) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(анонимная) @ asyncToGenerator.js:27
(анонимная) @ asyncToGenerator.js:19
(анонимная) @ index.jsx:101
(анонимная) @ JsonConfig.tsx:241
Объект Promise.then (асинхронный)
(анонимная) @ JsonConfig.tsx:238
Объект Promise.then (асинхронный)
n @ JsonConfig.tsx:237
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:145 Translation for word "File" in "ru" was ignored: existing = "Файл", new = файл
(анонимная) @ instrument.ts:145
(анонимная) @ i18n.js:106
value @ i18n.js:102
(анонимная) @ index.jsx:87
f @ regeneratorRuntime.js:45
(анонимная) @ regeneratorRuntime.js:133
(анонимная) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(анонимная) @ asyncToGenerator.js:27
(анонимная) @ asyncToGenerator.js:19
(анонимная) @ index.jsx:101
(анонимная) @ JsonConfig.tsx:241
Объект Promise.then (асинхронный)
(анонимная) @ JsonConfig.tsx:238
Объект Promise.then (асинхронный)
n @ JsonConfig.tsx:237
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:145 Translation for word "Type" in "ru" was ignored: existing = "Тип", new = Вывод звука
(анонимная) @ instrument.ts:145
(анонимная) @ i18n.js:106
value @ i18n.js:102
(анонимная) @ index.jsx:87
f @ regeneratorRuntime.js:45
(анонимная) @ regeneratorRuntime.js:133
(анонимная) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(анонимная) @ asyncToGenerator.js:27
(анонимная) @ asyncToGenerator.js:19
(анонимная) @ index.jsx:101
(анонимная) @ JsonConfig.tsx:241
Объект Promise.then (асинхронный)
(анонимная) @ JsonConfig.tsx:238
Объект Promise.then (асинхронный)
n @ JsonConfig.tsx:237
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:145 Translation for word "error" in "ru" was ignored: existing = "ошибки", new = ошибка
(анонимная) @ instrument.ts:145
(анонимная) @ i18n.js:106
value @ i18n.js:102
(анонимная) @ index.jsx:87
f @ regeneratorRuntime.js:45
(анонимная) @ regeneratorRuntime.js:133
(анонимная) @ regeneratorRuntime.js:74
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
Объект Promise.then (асинхронный)
r @ asyncToGenerator.js:12
s @ asyncToGenerator.js:22
(анонимная) @ asyncToGenerator.js:27
(анонимная) @ asyncToGenerator.js:19
(анонимная) @ index.jsx:101
(анонимная) @ JsonConfig.tsx:241
Объект Promise.then (асинхронный)
(анонимная) @ JsonConfig.tsx:238
Объект Promise.then (асинхронный)
n @ JsonConfig.tsx:237
Wa @ react-dom.production.min.js:147
No @ react-dom.production.min.js:198
Ei @ react-dom.production.min.js:292
ks @ react-dom.production.min.js:280
ys @ react-dom.production.min.js:280
vs @ react-dom.production.min.js:280
as @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
instrument.ts:145 Translate: Test
instrument.ts:145 TypeError: Cannot read properties of undefined (reading 'label')
    at ConfigFileSelector.jsx:393:45
    at Array.map (<anonymous>)
    at a.value (ConfigFileSelector.jsx:391:36)
    at a.value (ConfigGeneric.tsx:907:35)
    at Po (react-dom.production.min.js:204:189)
    at No (react-dom.production.min.js:203:149)
    at Ei (react-dom.production.min.js:292:172)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at us (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(анонимная) @ instrument.ts:145
fo @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
Ua @ react-dom.production.min.js:144
wi @ react-dom.production.min.js:261
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
(анонимная) @ react-dom.production.min.js:283
Ss @ react-dom.production.min.js:281
as @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14

**Comment by foxriver76** [comment]
Some context would be really great.
