### ISSUE TITLE
[enhancement]: Freely writable comment field for the instance tab.

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.admin#2218]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

If you have multiple instances of the same adapter, it's not immediately clear what the advantage is.

### Description

In my case, I use Gotify with multiple instances to have several push channels that I can configure individually. Through a comments field, I could now name each instance and describe exactly what I use it for, without having to go into the configuration each time.
Example for the comments field, see screenshot.

![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/d4bc8b6b-e1fb-41ba-85aa-679bdaa17dbd)

**Comment by foxriver76** [comment]
Behind the instance name on hover there is a tool icon where you can adapt the name.

**Comment by pafade89** [comment]
I hadn't discovered the feature until now, and I think it's great =) Thank you very much for your help @foxriver76
