### ISSUE TITLE
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#2223]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Update Versuch von 6.12.2 auf 6.12.3 liefert den oben genannten Fehler und wird nicht ausgeführt.

### To Reproduce

Update über das Admin Adapter Menü angestoßen. Nach der timeout Zeit kommt dann die oben genannte Fehlermeldung. Auch ein Admin Update via Aufruf aus der Info Kachel heraus bringt ebenfalls keinen Erfolg. Auch hier wird das Admin Update nicht durchgeführt - allerdings ohne weitere Fehlermeldung. 

Nächster Versuch via Konsole liefert das nachfolgende Log, was eigentlich suggeriert, das der Admin 6.12.3 installiert ist. Nach Neustart von ioB und Kontrolle des Admin wird dort aber immer noch 6.12.2 angezeigt.

### Expected behavior

Ich erwarte ein Adapter Update

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/44617472/da18ccba-e1e6-48a8-ad93-ba403284927e)

`This upgrade of "admin" will introduce the following changes:
==========================================================================
-> 6.12.3:
fixed problem that disabled checkbox is still clickable
no longer replace valid `common.adminUI.tab` values of adapters
fixed `freeSolo` option for autocomplete components
fixed issue with jsonConfig `sendTo` with `native` option when returning multiple properties
fixed empty dropdown selection after selecting `system language` in JsonConfig
==========================================================================

Would you like to upgrade admin from @6.12.2 to @6.12.3 now? [(y)es, (n)o]: y
Update admin from @6.12.2 to @6.12.3
host.GLT Adapter "system.adapter.admin.0" is stopped.
NPM version: 9.8.1
Installing iobroker.admin@6.12.3... (System call)
upload [52] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/admin.png admin.png image/png
upload [50] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/customComponents.js.map custom/customComponents.js.map application/json
upload [40] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/i18n/zh-cn.json custom/i18n/zh-cn.json application/json
upload [30] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js.map custom/static/js/node_modules_prop-types_index_js.512eddf9.chunk.js.map application/json
upload [20] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map custom/static/js/vendors-node_modules_mui_material_Accordion_index_js-node_modules_mui_material_AccordionDetai-57e02d.0886b730.chunk.js.map application/json
upload [19] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js application/javascript
upload [18] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map custom/static/js/vendors-node_modules_mui_material_index_js.40e01f69.chunk.js.map application/json
upload [17] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js application/javascript
upload [16] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_index_js-node_modules_mui_utils_esm_capitalize_js-node_module-19fe07.82575832.chunk.js.map application/json
upload [15] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js application/javascript
upload [14] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map custom/static/js/vendors-node_modules_mui_styles_withStyles_withStyles_js.6d998ff2.chunk.js.map application/json
upload [13] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js application/javascript
upload [12] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map custom/static/js/vendors-node_modules_react-dom_index_js.51544235.chunk.js.map application/json
upload [11] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [10] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [9] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [8] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [7] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [6] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [5] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [4] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [3] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [2] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/uk/translations.json i18n/uk/translations.json application/json
upload [1] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [0] admin.admin C:/iobroker/GLT/node_modules/iobroker.admin/admin/jsonConfig.json5 jsonConfig.json5 application/json5
host.GLT Adapter "system.adapter.admin.0" is started`

### Adapter version

6.12.2

### js-controller version

5.0.16

### Node version

9.8.1

### Operating system

Windows

**Comment by foxriver76** [comment]
Probier mal bitte ob da mehr Log kommt auf der Konsole mit `iob upgrade admin --debug`

**Comment by JBSullivan** [comment]
Da wart ihr mit der 6.12.4 schneller als ich den Debug ausführen konnte. Offensichtlich wurde der Fehler gefixt, denn die 6.12.4 ist ohne Probleme durchgelaufen. Issue kann also geschlossen werden.
