### ISSUE TITLE
[bug]: jsonConfig.json - autocompleteSendTo 

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2229]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Der obere Type zeigt bei einer Liste von 10.000 Ortsnnamen folgendes Verhalten:

`Köln` und `Köln ` ergibt:

<img width="428" alt="Bildschirmfoto 2023-11-19 um 16 52 11" src="https://github.com/ioBroker/ioBroker.admin/assets/59184294/22ed545e-db1c-4847-a4d6-d3887eb9f447">

gebe ich nun noch ein leerzeichen hinzu `Köln  ` wird `no option` angezeigt, weil es gibt keinen Eintrag mit Köln + 2 Leerzeichen. Lösche ich nun das letzten Leerzeichen so das wieder `Köln ` da steht sieht es so aus:

<img width="422" alt="Bildschirmfoto 2023-11-19 um 16 54 42" src="https://github.com/ioBroker/ioBroker.admin/assets/59184294/7894162d-7090-4eda-8ed9-ea02ba30ffd6">

gibt 2 Einträge die sich auf Köln beziehen.

### To Reproduce

siehe oben

### Expected behavior

Es sollte sofort die richtige Auswahl angezeigt werden.

### Screenshots & Logfiles

siehe oben

### Adapter version

v6.12.4

### js-controller version

5.0.16

### Node version

18.18.2

### Operating system

debian

**Comment by foxriver76** [comment]
Can you send me a link to the adapter, will make it easier for me to reproduce it.

**Comment by ticaki** [comment]
https://github.com/ticaki/ioBroker.weather-warnings

**Comment by foxriver76** [comment]
Not yet sure what causes this, of course your automplete options are freaking huge. However, it also complains a lot of duplicate entries, also does not make sense for users to have two times `Köln (Stadt/NW)`, because no one know which to select.

**Comment by foxriver76** [comment]
Okay, this seems to be already the problem:

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/919d850a-f347-4a6a-b50e-66e973e419bd)
https://stackoverflow.com/questions/75209557/material-ui-autocomplete-showing-wrong-searched-value-some-extra-invalid-result

Then needs to be fixed on your side. Please reopen if this not solve the problem.
