### ISSUE TITLE
flooded by "martian source" on my PC's dmesg and log files

### ISSUE THREAD

**Issue by AxelG-DE** [ioBroker/ioBroker.admin#2230]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

There is a chance I am mistaken, hence I have elminated that [bug:] at the beginning of the title...

My internet router (AVM Fritz!box) runs on the standard IP address 192.168.178.1

The iobroker runs on a raspberryPi at 192.168.178.119:8081

Then I have a PC with three NIC. eno1 is within 192.168.178.0/24 and enp5s0f0 has a different subnet 192.168.5.0/24 as well as enp5s0f1 has yet another subnet.

All eth-cables go to a managed switch, which does not use v-lan yet (so everyone can shout to everyone)

I run my iobroker already since ~2years.

Starting with October 23rd 19:33:08 my logs getting flodded with this messages:
```
Nov 19 17:07:27 brain kernel: IPv4: martian source 192.168.178.76 from 192.168.178.119, on dev enp5s0f0
Nov 19 17:07:27 brain kernel: ll header: 00000000: ff ff ff ff ff ff e4 5f 01 35 b1 d5 08 06
Nov 19 17:07:28 brain kernel: IPv4: martian source 192.168.178.72 from 192.168.178.119, on dev enp5s0f0
Nov 19 17:07:28 brain kernel: ll header: 00000000: ff ff ff ff ff ff e4 5f 01 35 b1 d5 08 06
Nov 19 17:07:28 brain kernel: IPv4: martian source 192.168.178.73 from 192.168.178.119, on dev enp5s0f0
Nov 19 17:07:28 brain kernel: ll header: 00000000: ff ff ff ff ff ff e4 5f 01 35 b1 d5 08 06
```
(it actually broadcasts for several IPs but not those, which are actually in use)

so there is 192.168.178.0/24 shouting on 192.168.5.0/24, which shouldn't be there and it makes my logs eligible. 

When I check my logs before 23rd Oct. there is no such behaviour (logrotate will soon eliminate those old logs)

When I stop iobroker on the raspi, that behaviour is also gone.

Analysing with wireshark does not bring me much further because it sets the NIC to promiscous mode (but I make sure promiscous mode is off, after checking)

I have the smell, on 23rd Oct. I updated the iob-admin adapter. For my main machines I am using Gentoo, so for the RaspbianOS, I do not know how to check, by when an update has taken place. Sorry for beeing boon her.

### To Reproduce

please see above

### Expected behavior

no martian source messages on a subnet which is not the one, where iobroker belongs to

### Screenshots & Logfiles

n/a 

### Adapter version

6.12.0

### js-controller version

5.0.16

### Node version

v18.17.1

### Operating system

RaspbianOS

**Comment by foxriver76** [comment]
You could stop only admin adapter to check if it is really admin.

**Comment by AxelG-DE** [comment]
@foxriver76 before I reply to your proposal: 
- I have stopped all adapters one by one first (I think even admin, this I forgot) and the martians kept going
- with your comment I tried particularly admin.0 again from GUI but also from shell and I have to admit, the martians keep going

Even worse :-( I did test in the past and "iob stop" made those martian source disappear. Today I tried again and they get slower but not stopping. Now I am totally lost.

I understand, this issue will be closed as not apply, but where could I ask now. Google didn't bring me further :-(

Why it bothers me? dmesg and syslog are almost useless to me now as they are flooded

**Comment by foxriver76** [comment]
I could imagine, that maybe Thomas Braun would be interested looking into it with you in the Forum. Maybe create a thread at https://forum.iobroker.net/ and tag him there.

**Comment by AxelG-DE** [comment]
thank you very much!

I close here as (up to now :-P ) does not apply

**Comment by AxelG-DE** [comment]
Ladies and gentlemen, I still need help..

I am continuously analysing with 
- wireshark (telling me there is an ARP flood on my raspi)
- while ! ss -p state syn-sent | grep 192.168.178.76; do sleep .1; done
- - giving me `tcp   0      1      192.168.178.119:60454 192.168.178.76:9090` (which says nothing to me)
- when issueing iob stop, that behaviour persists, but when typing `systemctl stop iobroker.service`, then the ARP flood stops.

I will ask in the forum again, first attempt wasn't successful yet...
Any recommendations?
