### ISSUE TITLE
[JSONconfig] : file & fileSelector not working, admin crash 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#2236]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I would like to implement file view/upload for ESPHome to allow upload/download of YAML files present in a folder

https://github.com/ioBroker/ioBroker.admin/blob/master/src/src/components/JsonConfigComponent/SCHEMA.md

Config examples have been used, but as soon I add an item filed with fileSelector or file the page is not loading anymore

example:
```
		"getDataFiles" : {
			"type": "fileSelector"
		}
```

admin error

![Screenshot 2023-11-23 at 15 49 56](https://github.com/ioBroker/ioBroker.admin/assets/7318445/89eb8f29-81e5-422c-91e9-f2f4d3215f61)

### To Reproduce

1) implement JSON-Config in an adapter
2) add an item as file or fileSelector

### Expected behavior

capability for file upload/browsing should be possible by using JSON-config

### Screenshots & Logfiles

see above

### Adapter version

6.12.4

### js-controller version

5.0.16

### Node version

18.3

### Operating system

Docker image, dev server, native Linux installation

**Comment by DutchmanNL** [comment]
possibly already part of https://github.com/ioBroker/ioBroker.admin/pull/2235, will check as soon as available

**Comment by foxriver76** [comment]
`fileSelector` should be fixed and `file` is probably crashing when the attribute has no default value. I prepared a PR to fix the latter case too.

**Comment by DutchmanNL** [comment]
thank you @foxriver76, appreciated :)
