### ISSUE TITLE
[bug]: Error in GUI! when displaying update instructions for host

### ISSUE THREAD

**Issue by joluxer** [ioBroker/ioBroker.admin#2237]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Got the "Error in GUI!" screen, when displaying the instructions, how to update the js-controller.

### To Reproduce

1. went to the tab "hosts" because of the notification symbol there
2. got the display for updating the js-controller to V5.0.16, hit that button
3. got the modal displaying the changelog, hit the button for displaying the instructions
4. for the fraction of an second there was some page or modal displayed, then the error screen appeared

### Expected behavior

Getting instructions displayed, how to update the js-controller.

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/22770260/f35da6d5-3c50-44ed-8423-5244782e0ea6)

### Adapter version

admin v6.12.0

### js-controller version

5.0.12

### Node version

v18.17.1

### Operating system

Debian GNU/Linux 11 (bullseye)

### Additional context

Followed the instructions for displaing things in the browser console, here is the screen shot:

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/22770260/c0f96c6c-07cb-41be-b8b5-f25e8cfa4e59)

**Comment by foxriver76** [comment]
Is this the log when you reproduced the error while the console was already opened? Else please try to do so, else it is very unlikely to reproduce it for us.

**Comment by joluxer** [comment]
Yes, the shown console log was already open, when I began to reproduce the error, as in the description for error reproduction stated.

**Comment by foxriver76** [comment]
And the error is reproduceable? Can you show the menu and the button on a screenshot which produces the issue.

**Comment by joluxer** [comment]
The error is reliably reproducable by opening the hosts tab, klicking the button in the "available" column and hitting the for displaing the instructions (mouse cursor is shown on the button for the next step on both images):

![Bildschirmfoto_2023-12-02_12-09-45](https://github.com/ioBroker/ioBroker.admin/assets/22770260/fb4a0651-5033-4b82-bc38-b1c7054680c2)

![Bildschirmfoto_2023-12-02_12-10-06](https://github.com/ioBroker/ioBroker.admin/assets/22770260/fe0759ae-4317-4ed9-87a8-34b066481689)

The next screen is already the big screen "Error in the GUI".

**Comment by foxriver76** [comment]
Unfortunately I cannot replicate this and the logged error is not very helpful.

**Comment by joluxer** [comment]
The problem is still reproducible here, so how can I help? How can I create a more helpful debug output? 

I'm not in a rush, to perform the update, so we can take some more days, to find out something. 

(I could go through the CLI upgrade steps, according to [this forum post](https://forum.iobroker.net/topic/69920/iobroker-im-docker-updaten-wie), this worked out last time, half a year ago, but then the problem might vanish and hide something deeper...)
