### ISSUE TITLE
[bug]: Error in GUI

### ISSUE THREAD

**Issue by Tykuryu** [ioBroker/ioBroker.admin#2238]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Just opened it and got this Error the moment i klick on something other than tha main page.

### To Reproduce

opened iobroker.admin
click on a link.(instantzen, Protokoll)

### Expected behavior

to open the link without error

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/101496896/7ac150fb-307c-47e6-8d83-6d5527d8170d)

### Adapter version

v6.12.0

### js-controller version

5.0.16

### Node version

v18.17.1

### Operating system

Ubuntu on raspberry

**Comment by foxriver76** [comment]
So you are opening admin over ioBroker Pro or what?

**Comment by foxriver76** [comment]
Sorry without information I cannot do anything here.
