### ISSUE TITLE
[bug]:  Column with / header mismatch at object panel

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2248]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When using custom column - specified by adminColumn config in io.package - the header and the data at object view tab do not match at all:

 For example see 
- header role and data for roles
- -address- relates to adminColumn named address but is shown somehere below rooms

Further the header is destroyed (overridden) - see right upper end of headers:

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/23c91748-a6e4-43f9-a05d-e0e0ded84d78)

Releated io-pacakge.json (work in progress)
https://github.com/daolis/ioBroker.sun2000-modbus/blob/bef1ac1388cf1f0893abd48f820bd38a703d4912/io-package.json#L82

### To Reproduce

see problem description

### Expected behavior

correct display

### Screenshots & Logfiles

see problem description

### Adapter version

6.10.1 and 6.12.1

### js-controller version

5.0.12

### Node version

v18.18.2

### Operating system

Win 11

**Comment by Feuer-sturm** [comment]
@mcm1957 can you please check if this issue is still relevant with admin7?

**Comment by mcm1957** [comment]
Problem fixed.
