### ISSUE TITLE
[bug]: [jsonConfig.json] default dont work for keys start with _

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2252]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Komponentenkeys die mit einem _ anfangen, ignorieren das property `default`

Getestet mit Type: checkbox, text, number

Weiß nicht ob das ein Schemafehler ist, weils dort nicht verboten ist, oder ein Adminbug weils da nicht geht.

### To Reproduce

s.o

### Expected behavior

s.o.

### Screenshots & Logfiles

```
                                                     _interviewCompleted2: {
								type: "checkbox",
								label: `Interview completed`,
								default: true,
								disabled: 'true',
								newLine: true,
							},
```

### Adapter version

v6.12.8

### js-controller version

latest

### Node version

18.19.0

### Operating system

linux

**Comment by mcm1957** [comment]
Please add dedicated numeric versions.
Latest is not sufficient,
Could be current latest or stable.
And is aother version as soon as some new versionnist published.

**Comment by ticaki** [comment]
I dont think that the version gives any additional information - latest ist latest and not stable. Anyway i add it.

**Comment by foxriver76** [comment]
> I dont think that the version gives any additional information - latest ist latest and not stable. Anyway i add it.

Yes, but what @mcm1957 means, if someone takes care of the issue in like 3 months, it is more effort to find out which version it was at this timepoint than to simply write it down.

**Comment by foxriver76** [comment]
Here are filtering takes place removing attributes starting with `_` in general https://github.com/ioBroker/ioBroker.admin/blob/756fe3dda775ff54cfaffa0a407dbb5fa2523bf4/src/src/components/JsonConfigComponent/index.jsx#L144

Need to check back why.
