### ISSUE TITLE
[bug]: Node.JS version detection is faulty

### ISSUE THREAD

**Issue by Sgt-Nukem** [ioBroker/ioBroker.admin#2255]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Node.JS **v18.18.2** is detected as a *newer* version than **v18.19.0** (c.f. screenshot below)

### To Reproduce

1. Have Node.JS v18.19.0 installed
2. Open the 'Info' tab on the admin page
3. See the faulty version detection in the 'System information' box

### Expected behavior

Let the box say "No newer version available"

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/4144388/bc1de6d7-d4b7-4088-b435-df014a4d0b94)

### Adapter version

6.12.0

### js-controller version

5.0.16

### Node version

v18.19.0

### Operating system

Raspbian GNU/Linux 10 (buster)

**Comment by foxriver76** [comment]
From which page is the screenshot above?

**Comment by foxriver76** [comment]
ah yes you state info tab which is most likely the info adapter, admin has nothing to do with it despite from displaying what is provided. 

See https://github.com/iobroker-community-adapters/ioBroker.info/issues/52
