### ISSUE TITLE
elemente im accordion hängen an ihrem label[bug]: 

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2270]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In dem JSON config element "accordion" hängen gewisse elemente wie bspw. "select", "ObjectId" uns eventuell noch mehr direkt an ihrem label und somit generell höher wie bspw. das element "text" .
Ein Beispiel, habe ich in die Screenshots gepackt. 

Ps. zusätzlich wird bei "text" und bei "ObjectId" nicht die in den i18n hinterlegte Übersetzung angezogen, sondern nur der "attr" name

### To Reproduce

here my jsonconfig:
```
{
	"i18n": true,
	"type": "panel",
    "items":{
        "informationHeader": {
            "newLine": true,
            "type": "header",
            "text": "mainInformations",
            "size": 3
        },
        "Information1":{
            "newLine":true,
            "type": "staticText",
            "label": "mainInformationText"
        },
        "configurationHeader": {
            "newLine": true,
            "type": "header",
            "text": "configuration",
            "size": 3
        },
        "statesAccordion":{
            "type":"accordion",
            "sm":12,
            "allowAddByFilter": true,
            "items":[
                {
                    "type": "text",
                    "attr": "name",
                    "label": "name",
                    "tooltip": "nameTooltip"
                },
                {
                    "type": "objectId",
                    "title": "state id",
                    "attr": "id",
                    "tooltip": "idTooltip",
                    "sm":4
                },
                {
                    "type": "select",
                    "attr": "type",
                    "options": [
                        {"label":"avg","value":"avg"},
                        {"label":"avgArray","value":"avgArray"}],
                    "default": "avgArray",
                    "label": "calculationType",
                    "tooltip": "typeTooltip",
                    "sm": 1
                },
                {
                    "attr": "refreshRate",
                    "type": "select",
                    "options": [
                    {"label":"1 s","value":1},
                    {"label":"2 s","value":2},
                    {"label":"3 s","value":3},
                    {"label":"4 s","value":4},
                    {"label":"5 s","value":5},
                    {"label":"6 s","value":6},
                    {"label":"7 s","value":7},
                    {"label":"8 s","value":8},
                    {"label":"9 s","value":9},
                    {"label":"10 s","value":10},
                    {"label":"20 s","value":20},
                    {"label":"30 s","value":30},
                    {"label":"40 s","value":40},
                    {"label":"50 s","value":50},
                    {"label":"60 s","value":60}],
                    "default": 2,
                    "label": "refreshRate",
                    "tooltip": "refreshRateTooltip",
                    "sm": 1
                },
                {
                    "newLine": true,
                    "type": "select",
                    "attr":"smoothtime",
                    "options": [
                    {"label":"unsmoothed","value":0},
                    {"label":"1 s","value":1},
                    {"label":"2 s","value":2},
                    {"label":"3 s","value":3},
                    {"label":"4 s","value":4},
                    {"label":"5 s","value":5},
                    {"label":"6 s","value":6},
                    {"label":"7 s","value":7},
                    {"label":"8 s","value":8},
                    {"label":"9 s","value":9},
                    {"label":"10 s","value":10},
                    {"label":"20 s","value":20},
                    {"label":"30 s","value":30},
                    {"label":"1 min","value":60},
                    {"label":"2 min","value":120},
                    {"label":"3 min","value":180},
                    {"label":"4 min","value":240},
                    {"label":"5 min","value":300},
                    {"label":"6 min","value":360},
                    {"label":"7 min","value":420},
                    {"label":"8 min","value":480},
                    {"label":"9 min","value":540},
                    {"label":"10 min","value":600},
                    {"label":"11 min","value":660},
                    {"label":"12 min","value":720},
                    {"label":"13 min","value":780},
                    {"label":"14 min","value":840},
                    {"label":"15 min","value":900},
                    {"label":"30 min","value":1800},
                    {"label":"45 min","value":2700},
                    {"label":"60 min","value":3600}],
                    "default":300,
                    "label": "smoothtime",
                    "tooltip": "smoothtimeTooltip"
                },
                {
                    "newLine": true,
                    "type": "select",
                    "attr":"smoothtimeNegative",
                    "options": [
                    {"label":"unsmoothed","value":0},
                    {"label":"1 s","value":1},
                    {"label":"2 s","value":2},
                    {"label":"3 s","value":3},
                    {"label":"4 s","value":4},
                    {"label":"5 s","value":5},
                    {"label":"6 s","value":6},
                    {"label":"7 s","value":7},
                    {"label":"8 s","value":8},
                    {"label":"9 s","value":9},
                    {"label":"10 s","value":10},
                    {"label":"20 s","value":20},
                    {"label":"30 s","value":30},
                    {"label":"1 min","value":60},
                    {"label":"2 min","value":120},
                    {"label":"3 min","value":180},
                    {"label":"4 min","value":240},
                    {"label":"5 min","value":300},
                    {"label":"6 min","value":360},
                    {"label":"7 min","value":420},
                    {"label":"8 min","value":480},
                    {"label":"9 min","value":540},
                    {"label":"10 min","value":600},
                    {"label":"11 min","value":660},
                    {"label":"12 min","value":720},
                    {"label":"13 min","value":780},
                    {"label":"14 min","value":840},
                    {"label":"15 min","value":900},
                    {"label":"30 min","value":1800},
                    {"label":"45 min","value":2700},
                    {"label":"60 min","value":3600}],
                    "default":300,
                    "label": "smoothtimeNegative",
                    "tooltip": "smoothtimeNegativeTooltip",
                    "hidden": "data.smoothtimePositive !== -1"
                }
            ]
        }
	}
}
```

### Expected behavior

Die Elemente sollten gleich hoch platziert sein und einen passenden Abstand von deren label

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/92173565/59eeb16a-363a-4b5d-bcb3-e1f61dd3adb9)

### Adapter version

6.12.9

### js-controller version

5.0.17

### Node version

18.15.0

### Operating system

dev-server

**Comment by foxriver76** [comment]
@klein0r fyi

**Comment by klein0r** [comment]
Muss ich mir anschauen warum das nicht klappt. Am Ende werden die Elemente im Accordion genauso hinzugefügt wie in einer Tabelle z.B. auch. Eventuell überschneiden sich da irgendwelche Klassen.

@foxriver76 Wie bekomme ich mit der neuen Ordner-Struktur einen dev-server aufgesetzt?!

> Ps. zusätzlich wird bei "text" und bei "ObjectId" nicht die in den i18n hinterlegte Übersetzung angezogen, sondern nur der "attr" name

Das hat aber nichts mit dem Accordion zu tun. Deine Definition funktioniert auch so nicht:

```json
"id": {
            "type": "objectId",
            "title": "state id",
            "tooltip": "idTooltip",
            "sm": 4
        },
```

Wenn Du das gegen das Schema vergleichst, dann siehst Du auch dass es `"title"` nicht gibt. Nur `"label"`.

**Comment by foxriver76** [comment]
`npm run start` im Root folder bei laufendem Admin wie vorher sollte es gehen

**Comment by BenAhrdt** [comment]
@klein0r 
ich hatte oben noch eine alte Version gepostet, sorry.
Ich habe schon das label drin. trotzdem geht nicht:
`{
                    "type": "objectId",
                    "label": "id",
                    "attr": "id",
                    "tooltip": "idTooltip",
                    "default": "",
                    "sm":5
                },`

**Comment by BenAhrdt** [comment]
Des weiteren erscheint nun auch diese Meldung im Log. (Bis gestern erschien die nicht)

`smoothed has an invalid jsonConfig: [{"instancePath":"/items/statesAccordion/type","schemaPath":"#/definitions/componentType/enum","keyword":"enum","params":{"allowedValues":["alive","autocomplete","cron","fileSelector","text","textSendTo","number","port","color","checkbox","chips","header","slider","ip","user","room","func","select","icon","image","panel","password","file","sendTo","staticText","custom","pattern","table","instance","language","setState","certificate","certificates","staticImage","staticLink","divider","objectId","selectSendTo","autocompleteSendTo","checkLicense","uuid"]},"message":"must be equal to one of the allowed values"}]`

**Comment by mcm1957** [comment]
- Schema Fehler gehören in adapter-react-v5
- Fehler bekannt: https://github.com/ioBroker/adapter-react-v5/issues/1950

**Comment by klein0r** [comment]
@foxriver76 Mh, ich kann den aktuellen Admin nicht bauen (nodejs 20). Gerade frisch ausgecheckt.

<img width="1242" alt="Screenshot 2023-12-22 at 20 25 49" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/f80eeba3-8ca8-48e6-9436-5ee0ef549926">

**Comment by foxriver76** [comment]
Mit den steps geht nicht? https://github.com/ioBroker/ioBroker.admin/blob/master/DEVELOPER.md#development

**Comment by klein0r** [comment]
Fehlerhafte Darstellung liegt an

https://github.com/ioBroker/ioBroker.admin/blob/d32ff8edea9e234b55e5e3c1aa0f94940fb49bde/packages/jsonConfig/src/JsonConfigComponent/ConfigSelect.jsx#L23-L27

Wenn ich die Zeilen entferne, siehts ganz gut aus. Die Frage ist, für welchen Fall die da sind. Aus a5aebbbf6d10d151704059cd6c9fc8067f65960e

**Comment by foxriver76** [comment]
Und im root reicht json config ein mal in richtigen deps. Ist sowieso nur ein Meta Paket. Pfade gerne korrigieren. Alles noch relativ frisch ;-)

**Comment by foxriver76** [comment]
> Fehlerhafte Darstellung liegt an
> 
> https://github.com/ioBroker/ioBroker.admin/blob/d32ff8edea9e234b55e5e3c1aa0f94940fb49bde/packages/jsonConfig/src/JsonConfigComponent/ConfigSelect.jsx#L23-L27
> 
> Wenn ich die Zeilen entferne, siehts ganz gut aus. Die Frage ist, für welchen Fall die da sind. Aus [a5aebbb](https://github.com/ioBroker/ioBroker.admin/commit/a5aebbbf6d10d151704059cd6c9fc8067f65960e)

Ich frage mal BF

**Comment by GermanBluefox** [comment]
> Fehlerhafte Darstellung liegt an
> 
> https://github.com/ioBroker/ioBroker.admin/blob/d32ff8edea9e234b55e5e3c1aa0f94940fb49bde/packages/jsonConfig/src/JsonConfigComponent/ConfigSelect.jsx#L23-L27
> 
> Wenn ich die Zeilen entferne, siehts ganz gut aus. Die Frage ist, für welchen Fall die da sind. Aus [a5aebbb](https://github.com/ioBroker/ioBroker.admin/commit/a5aebbbf6d10d151704059cd6c9fc8067f65960e)

Diese margin ist dafür da, damit in einer Tabelle Select in einer Rehe mit anderen TextField, Checkboxen steht.
Aus irgenwelchem Grund verwendet Accordion arrayIndex hier https://github.com/ioBroker/ioBroker.admin/blob/d32ff8edea9e234b55e5e3c1aa0f94940fb49bde/packages/jsonConfig/src/JsonConfigComponent/ConfigAccordion.jsx#L87

**Comment by klein0r** [comment]
> Aus irgenwelchem Grund verwendet Accordion arrayIndex hier

Das Accordion habe ich auf Basis der Tabellen zusammengebaut (war ja meine erste React-Component). Also gerne alles hinterfragen was dort enthalten ist 😄

**Comment by misanorot** [comment]
> > Aus irgenwelchem Grund verwendet Accordion arrayIndex hier
> 
> Das Accordion habe ich auf Basis der Table-Component zusammengebaut (war ja meine erste React-Component). Also gerne alles hinterfragen was dort enthalten ist 😄

Hallo,

dann frag ich mal... :-)

Ist es möglich, jede Zeile zu bezeichnen? Ohne Bezeichnung wäre das nicht wirklich optimal.
![WhatsApp Bild 2024-01-11 um 17 41 34_252b09ea](https://github.com/ioBroker/ioBroker.admin/assets/23728622/44a23793-af8d-40e6-80e5-dbaab6d6f0e9)

**Comment by klein0r** [comment]
@misanorot You can specify which attribute / value in each accordion should be used for the title:

https://github.com/klein0r/ioBroker.awtrix-light/blob/a7fa2acb6b2cd58d1fc14b00207131f787e54bbe/admin/jsonConfig.json#L181

**Comment by misanorot** [comment]
> @misanorot You can specify which attribute / value in each accordion should be used for the title:
> 
> https://github.com/klein0r/ioBroker.awtrix-light/blob/a7fa2acb6b2cd58d1fc14b00207131f787e54bbe/admin/jsonConfig.json#L181

Danke! Ich hatte zwar den Code so, hatte aber nicht vernommen, dass titleAttr eine Variable beinhaltet die dann beschrieben werden muss. Jetzt ist es natürlich logisch. Im übrigen finde ich die Umsetzung mit dem Accordion sehr gut.

**Comment by BenAhrdt** [comment]
@klein0r Ist es möglich dort auch etwas eintragbar zu machen, wie bspw. bei "hidden"?
Oder eventuell ein string wie:
${name}: ${type}
... etc?

**Comment by klein0r** [comment]
@BenAhrdt Aktuell nicht, müsstest einen PR für erstellen, welcher das alles berücksichtig. Eventuell über ein zweites Attribut

`titleTemplate: "${data.name}: ${data.type}"`
