### ISSUE TITLE
[bug]: Does not load the admin configuration of adapter installed from github custom.

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2275]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin 6.13.2 & 6.13.3 läd nicht die Admin-Konfiguration von Adapter die über die benutzerdefinierte Github installation installiert sind.

Hab das auch mit neu installieren versucht(6.13.2), da gehts auch nicht. Screenshot ist von einem schon installierten Adapter. Betrifft beide Adapter die ich aktuell von Github installiert habe:

https://github.com/DrozmotiX/ioBroker.esphome
https://github.com/ticaki/ioBroker.espresense

EDIT: Mit 6.12.9 funktioniert es wie es soll.

Dieses Problem wurde bestätigt von:
@raschy

### To Reproduce

Rufe die Konfigurationseite von einem Adapter auf der per benutzerdefiniertem Github install installiert wurde.

### Expected behavior

Die Konfiguration sollte geladen werden

### Screenshots & Logfiles

<img width="434" alt="Bildschirmfoto 2023-12-22 um 12 53 41" src="https://github.com/ioBroker/ioBroker.admin/assets/59184294/6a9c7e44-3573-414f-83b2-d1a9d8370325">

### Adapter version

6.13.2 & 6.13.3

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

Debian bookworm

**Comment by mcm1957** [comment]
Did you do an upload after installation?

**Comment by ticaki** [comment]
Wie geschrieben, ist das Adapter schon installiert - und ein upload ändert nichts. Mit 6.12.9 funktioniert es wie es soll.

**Comment by sansonifabio** [comment]
... diese Problem mit dem Admin kann ich auch bestätigen. Die Adapter Info seit lädt nicht zum Beispiel beim eusec Adapter und auch Admin Adapter bei anderen Adaptern fehlen dann auch einträge. Mein System ist auf dem neusten Stand. Bin mit Admim wieder zurück auf die 6.12.0 und alles funktioniert wieder.

**Comment by ohle64** [comment]
bei mir das gleiche Problem mit influxdb - normale Installation (Admin) läst sich nicht öffnen -> leere seite mit Laufbalken oben, mehr kommt nicht. Bin zurück auf 6.12.7 -> alles wieder ok.

**Comment by foxriver76** [comment]
Was most likely also due to missing crypto-js please retest with 6.13.5

**Comment by sansonifabio** [comment]
@foxriver76 I thank you very much for your endless work.
I just tested it and it works correctly, all adapter information and settings are back.

@foxriver76 ich danke dir ganz herzlich für deine unendliche Arbeit. 
Habe es gerade getestet und es läuft korrekt alle Adapter Infos und Einmstellungn sind wieder da.
