### ISSUE TITLE
[bug]: Missing CryptoJS Since Admin 6.13.3

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.admin#2276]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

User reports he receive the error
`
[JsonConfig] Cannot set object: TypeError: window.CryptoJS is undefined
`
With Admin 6.13.3

It is working with Admin  6.12.9 
https://forum.iobroker.net/post/1098325

### To Reproduce

Install Adapter with crypto state try to save instance settings

### Expected behavior

No error

### Screenshots & Logfiles

`
[JsonConfig] Cannot set object: TypeError: window.CryptoJS is undefined
`

### Adapter version

6.13.3

### js-controller version

5.0.17

### Node version

18

### Operating system

Linux

**Comment by klein0r** [comment]
Same here:

```
URL: http://10.10.9.10:8081/lib/js/crypto-js/crypto-js.js
Status: 404 Not Found
```

Duplicate `.js` file extension in request url
