### ISSUE TITLE
[bug]: Admin >= v6.13.5 causes Firefox with NoScript Add-In to show a blank page

### ISSUE THREAD

**Issue by RP70DP** [ioBroker/ioBroker.admin#2285]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Firefox with active NoScript Add-In throws the following error:
`Uncaught (in promise) InternalError: too much recursion`

### To Reproduce

Install NoScript Add-In in Firefox.

### Expected behavior

Show the Admin in the right way.

### Screenshots & Logfiles

`Uncaught (in promise) InternalError: too much recursion`

### Adapter version

>= 6.13.5

### js-controller version

5.0.17

### Node version

18.17.1

### Operating system

Windows 10

### Additional context

https://forum.iobroker.net/topic/71286/admin-6-13-5-keine-gui-unter-firefox?_=1703537463543

**Comment by Gaspode69** [comment]
Additional hint:
Error messages "Uncaught (in promise) InternalError: too much recursion" occurs also with disabled NoScript addon, but Admin page is displayed.
These error messages do not occur when using Chrome.

**Comment by Feuer-sturm** [comment]
In parallel an issue for noscript was created as well https://github.com/hackademix/noscript/issues/333

**Comment by Schorsch99** [comment]
Additional info:
I have the same issue, but independent of the browser used: when NoScript is activated in either Firefox or Chromium, only a blank Admin page appears. When the Add-In is deactivated in either browser, both show the page correctly.
A test with Edge (without NoScript) also produces a normal page.

Admin Adapter version
6.13.15

js-controller version
5.0.17

Node version
18.19.0

Operating systems
Kubuntu / Windows 10 / Windows 11

Browsers
Firefox / Chromium

**Comment by Schorsch99** [comment]
Same issue here also with newer versions of the Admin adapter and Node.js:

Adapter version
6.13.15

js-controller version
5.0.17

Node version
18.19.0

Operating system
Kubuntu / Windows 11

**Comment by RP70DP** [comment]
Seems Admin v6.13.16 fixed the problem.

**Comment by Schorsch99** [comment]
6.13.16 works for me too :-)

**Comment by RP70DP** [comment]
I'm sorry, but Scripts-Tab don't work.

**Comment by Schorsch99** [comment]
You mean this one:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/27017311/45a1695a-b385-4b54-a12c-ed7f416b9db2)

**Comment by RP70DP** [comment]
Yes, but after many reloads suddenly it works. I'm confused...

**Comment by RP70DP** [comment]
I can't reproduce the not working Scripts-Tab. Please close again.
