### ISSUE TITLE
[bug]: Konfiguration meldet Error in GUI[bug]: #2280

### ISSUE THREAD

**Issue by Suedtschech1** [ioBroker/ioBroker.admin#2288]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Error in GUI

### To Reproduce

1. Go To ioBroker 
2.  Objekt List

### Expected behavior

1310.8a1c4a0c.chunk.js:2 ChunkLoadError: Loading chunk 6875 failed.
(missing: http://192.168.1.31:8081/static/js/6875.e99ef546.chunk.js)
    at t.f.j (main.56eaa755.js:1:13504)
    at main.56eaa755.js:1:1285
    at Array.reduce (<anonymous>)
    at t.e (main.56eaa755.js:1:1250)
    at 7136.2908cc23.chunk.js:2:238300
    at P (2791.8afe157f.chunk.js:2:3351)
    at Ei (4164.29c179b8.chunk.js:2:120786)
    at ks (4164.29c179b8.chunk.js:2:109418)
    at ys (4164.29c179b8.chunk.js:2:109346)
    at vs (4164.29c179b8.chunk.js:2:109209)
    at ss (4164.29c179b8.chunk.js:2:106325)
    at Hl (4164.29c179b8.chunk.js:2:46920)
    at 4164.29c179b8.chunk.js:2:103922

### Screenshots & Logfiles

![2023-12-27 19_11_54-Window](https://github.com/ioBroker/ioBroker.admin/assets/155011582/ff4e737f-edb8-4d98-adaa-a78a406403a2)

### Adapter version

6.12.0

### js-controller version

5.0.17

### Node version

16.19.0

### Operating system

linux

### Additional context

No response

**Comment by foxriver76** [comment]
Bitte den Fehler reproduzieren mit geöffneter Konsole (f12) wie es im  Screenshot steht. Das aktuelle log bringt uns leider keinen Hinweis auf den Fehler

**Comment by Suedtschech1** [comment]
iobroker.admin@6.12.0
1310.8a1c4a0c.chunk.js:2 [2023-12-31T14:56:50.802Z] Try to connect
1310.8a1c4a0c.chunk.js:2 Stored version: , new version: 6.12.0
1310.8a1c4a0c.chunk.js:2 Connected: true
windhager.png:1 
        
        
       GET http://192.168.1.31:8081/adapter/iobroker.windhager/windhager.png 404 (Not Found)
Image (async)
wi @ 4164.29c179b8.chunk.js:2
ki @ 4164.29c179b8.chunk.js:2
bi @ 4164.29c179b8.chunk.js:2
(anonym) @ 4164.29c179b8.chunk.js:2
Ss @ 4164.29c179b8.chunk.js:2
as @ 4164.29c179b8.chunk.js:2
S @ 4164.29c179b8.chunk.js:2
T @ 4164.29c179b8.chunk.js:2
1310.8a1c4a0c.chunk.js:2 Translate: Link
1310.8a1c4a0c.chunk.js:2 Translate: time
1310.8a1c4a0c.chunk.js:2 Translate: timeOffset
1310.8a1c4a0c.chunk.js:2 Translate: _nodeCurrent
1310.8a1c4a0c.chunk.js:2 Translate: _nodeNewest
1310.8a1c4a0c.chunk.js:2 Translate: _nodeNewestNext
1310.8a1c4a0c.chunk.js:2 Translate: _npmCurrent
1310.8a1c4a0c.chunk.js:2 Translate: _npmNewest
1310.8a1c4a0c.chunk.js:2 Translate: _npmNewestNext
6875.e99ef546.chunk.js:1 Uncaught SyntaxError: Invalid or unexpected token (at 6875.e99ef546.chunk.js:1:1)
1310.8a1c4a0c.chunk.js:2 ChunkLoadError: Loading chunk 6875 failed.
(missing: http://192.168.1.31:8081/static/js/6875.e99ef546.chunk.js)
    at t.f.j (main.56eaa755.js:1:13504)
    at main.56eaa755.js:1:1285
    at Array.reduce (<anonymous>)
    at t.e (main.56eaa755.js:1:1250)
    at 7136.2908cc23.chunk.js:2:238300
    at P (2791.8afe157f.chunk.js:2:3351)
    at Ei (4164.29c179b8.chunk.js:2:120786)
    at ks (4164.29c179b8.chunk.js:2:109418)
    at ys (4164.29c179b8.chunk.js:2:109346)
    at vs (4164.29c179b8.chunk.js:2:109209)
    at ss (4164.29c179b8.chunk.js:2:106325)
    at Hl (4164.29c179b8.chunk.js:2:46920)

**Comment by Suedtschech1** [comment]
Ich hoffe jetzt ist alles dabei was ihr braucht. 
Guten Rutsch

**Comment by GCP007** [comment]
habe ähnliches Problem - möglicher Weise gleiche Ursache: "**Error in GUI**"

02.01.2023: **System vollständig aktuell** (Raspberry-Linux ohne Desktop, ioBroker, alle Adapter)

### mit F12 zyklisch immer dieselben Meldungen:

[2024-01-02T22:43:55.878Z] Reconnect is already running 5
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:00.890Z] Try to connect
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:03.894Z] No READY flag received in 3 seconds. Re-init
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
warn @ socket.io.js:67
(anonym) @ socket.io.js:148
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
socket.io.js:396 WebSocket connection to 'ws://192.168.231.20:8081/?sid=1704235440892&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:396
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient.connect @ socket.io.js:146
(anonym) @ socket.io.js:428
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
setTimeout (async)
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
SocketClient._reconnect @ socket.io.js:423
SocketClient.close @ socket.io.js:410
(anonym) @ socket.io.js:149
o @ 1310.8a1c4a0c.chunk.js:sourcemap:2
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:03.903Z] Start reconnect 5
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:03.903Z] Reconnect is already running 5
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:03.903Z] ws connection error: CLOSE_ABNORMAL
(anonym) @ 1310.8a1c4a0c.chunk.js:sourcemap:2
error @ socket.io.js:68
socket.onclose @ socket.io.js:177
1310.8a1c4a0c.chunk.js:sourcemap:2 [2024-01-02T22:44:03.903Z] Reconnect is already running 5

Fehler tritt binnen 1...5 Tagen auf, fängt sich gelegentlich nach 1...3 h während der Zeiten ist das System weder über VIS, Admin noch SSH erreichbar. MySQL wird während Störung nicht bedient (Datenlücken). Regelmäßig hilft nur noch Hardreset.

**Comment by Feuer-sturm** [comment]
@Suedtschech1 please check with admin 7.1.5
if this issue is still there please create a new issue.
