### ISSUE TITLE
[bug]:  Changing the default columns in the object tab on smartphones

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2292]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Im Standardautomodus wird in der Objektübersicht auf Smartphones nur die Objekt-ID angezeigt. Das wird so nicht erwartet und auch viele der "Pro" Nutzer wissen nicht wie man das umstellt. 

Damit ist die Objektansicht wohl für sehr viele Nutzer auf dem Smartphone nutzlos.

### To Reproduce

Objektansicht öffnen und angucken :)

### Expected behavior

ID und Wert sollten per Default angezeigt werden. Abgesehen von von den guten Vorschlägen die in Telegram kamen lässt sich das hoffentlich schnell umsetzen.

### Screenshots & Logfiles

geklaut von seb :)
![IMAGE 2023-12-29 00:32:34](https://github.com/ioBroker/ioBroker.admin/assets/59184294/b5d02628-ff49-4ca9-9663-be87de0ee978)

### Adapter version

6.13.11

### js-controller version

5.0.17

### Node version

18.19.0

### Operating system

debian bookworm

**Comment by Feuer-sturm** [comment]
admin 7.4.8
With current admin this it how it looks like
![grafik](https://github.com/user-attachments/assets/095ad5be-76f4-4905-9628-b9ce813de03a)

ObjectID and value are now visibile on mobilephone
Issue closed

@ticaki fyi
