### ISSUE TITLE
[bug]: I get the hint to switch to redis, although I have few objects

### ISSUE THREAD

**Issue by DcFamas** [ioBroker/ioBroker.admin#2294]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hello everyone,
I get this message although I have less than 30000 objects in ioBroker. 

I have installed my instance in a Synology VMM with 4GB Ram, 4 cores and 64GB hard drive space. I only have one master and no slave. Here is the extract from iob diag:

### Screenshots & Logfiles

![1703961470277-a79b18a7-dac0-4763-becf-9d6231a3daba-grafik](https://github.com/ioBroker/ioBroker.admin/assets/35306967/edac9aff-68be-42ce-a778-b242b313654d)

======================= SUMMARY =======================
                        v.2023-10-10
   Static hostname: ioBroker
         Icon name: computer-vm
           Chassis: vm
    Virtualization: microsoft
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-26-amd64
      Architecture: x86-64

Installation:           microsoft
Kernel:                 x86_64
Userland:               amd64
Timezone:               Europe/Berlin (CET, +0100)
User-ID:                1000
X-Server:               false
Boot Target:            multi-user.target

Pending OS-Updates:     0
Pending iob updates:    0

Nodejs-Installation:    /usr/bin/nodejs         v18.19.0
                        /usr/bin/node           v18.19.0
                        /usr/bin/npm            10.2.3
                        /usr/bin/npx            10.2.3
                        /usr/bin/corepack       0.22.0

Recommended versions are nodejs 18.19.0 and npm 10.2.3
Your nodejs installation is correct

MEMORY:
               total        used        free      shared  buff/cache   available
Mem:            3.9G        2.4G        805M        0.0K        729M        1.3G
Swap:           974M          0B        974M
Total:          4.9G        2.4G        1.8G

Active iob-Instances:   29
Active repo(s): stable

ioBroker Core:          js-controller           5.0.17
                        admin                   6.12.0

ioBroker Status:        iobroker is running on this host.

Objects type: jsonl
States  type: jsonl

Status admin and web instance:
+ system.adapter.admin.0                  : admin                 : ioBroker                                 -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.web.0                    : web                   : ioBroker                                 -  enabled, port: 8082, bind: 0.0.0.0, run as: admin

Objects:                9314
States:                 7456

Size of iob-Database:

25M     /opt/iobroker/iobroker-data/objects.jsonl
8.3M    /opt/iobroker/iobroker-data/objects.json.migrated
8.3M    /opt/iobroker/iobroker-data/objects.json.bak.migrated
8.3M    /opt/iobroker/iobroker-data/states.jsonl
1020K   /opt/iobroker/iobroker-data/states.json.migrated
1020K   /opt/iobroker/iobroker-data/states.json.bak.migrated
0       /opt/iobroker/iobroker-data/states.json.broken

=================== END OF SUMMARY ====================

**Comment by foxriver76** [comment]
I just re-checked the code and the check looks good. Can it be that you had more objects for a short time? I think once the notification is generated it will stay until you click don't show anymore.

**Comment by DcFamas** [comment]
Hey Max,
this could be possible. I had installed the Homeassistant Adapter which loads a few states and objects. When everything is fine, I'm good to close the incident. :)

Best regards and happy new year

**Comment by mcm1957** [comment]
I got the message too (inside INFO Adapter) at production system (Pi4)

I'm quite sure that I never had such a number of states. Sorry - I confirmed the message already.
If theres any way to reset the confirmation I can aid in diagnose for sure. Please contact me if I can help

**Comment by Apollon77** [comment]
inof adapter is deprecated and most likely can not check the new rule for number of objects

**Comment by Feuer-sturm** [comment]
Issue closed because it currently does not look like an issue for admin adapter.

@DcFamas did you receive the notification from admin adapter or info adapter (which is deprecated)? If you still have problems with notification from admin adapter to switch to redis we can reopen the issue.
