### ISSUE TITLE
Kein Scrollen möglich in "Aufzählungen" und "Benutzer"

### ISSUE THREAD

**Issue by ktrolp** [ioBroker/ioBroker.admin#230]
Im Reiter "Aufzählungen" und "Benuter" ist unter Firefox (Mac) kein Scrollen möglich. Es erscheint keine Scrollbar.

**Comment by Reelfan** [comment]
unter WIndows (Firefox) dito, was hilft ist

#tab-enums .tree-table-body {
    overflow: hidden;
auf der entsprechenden Seite zu deaktivieren
