### ISSUE TITLE
[bug]:  "[ADAPTERS] {"rating":{"title":"No rating or too few data"}}"

### ISSUE THREAD

**Issue by Kystim** [ioBroker/ioBroker.admin#2309]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Without any changes I can't open my Adapter page anymore. When I navigate to "Adapters" the Tab freezes and the Error `"[ADAPTERS] {"rating":{"title":"No rating or too few data"}}"` is logged multiple thousand times a second. After a while (10 Sec?) another entry is logged uncountable often aswell `"{className: "MuiCardMedia-root iob130 css-padqbj', role: 'img', src: undefined, children: undefined}"`

<img width="1439" alt="image" src="https://github.com/ioBroker/ioBroker.admin/assets/13536402/9c30504f-afaf-4747-8571-b483b1496aff">

### To Reproduce

1. Go to `http://<iorboker>/#tab-adapters`
2. Adapter Page opens with loading bar 
3. 🥶

### Expected behavior

Adapter Page should load

### Screenshots & Logfiles

<img width="1439" alt="image" src="https://github.com/ioBroker/ioBroker.admin/assets/13536402/9c30504f-afaf-4747-8571-b483b1496aff">

<img width="1433" alt="Screenshot 2024-01-07 at 22 37 00" src="https://github.com/ioBroker/ioBroker.admin/assets/13536402/c9fb0ad6-5383-43d2-bf61-2381d85fc4aa">

### Adapter version

~6.12.3~ 6.13.15

### js-controller version

~4.0.24~ 5.0.17

### Node version

18.19.0

### Operating system

Docker (buanet/iobroker:latest)

**Comment by Leonhard-87** [comment]
I'm experiencing the exact same issue. Clean, first time install, same versions.

**Comment by morpeuse** [comment]
I have the same issue with three ioBroker instance. One of them are a Clean install.

**Comment by foxriver76** [comment]
Are the logs really from a version `6.13.15`? The line numbers seem to be from an older version.

**Comment by morpeuse** [comment]
> I have the same issue with three ioBroker instance. One of them are a Clean install.

now its working and I don't have change anything.

**Comment by foxriver76** [comment]
I think, the repository had an invalid entry  maybe empty object for a short time to whatever reasons, which lead to this behavior.

**Comment by Kystim** [comment]
> > I have the same issue with three ioBroker instance. One of them are a Clean install.
> 
> now its working and I don't have change anything.

Same here
