### ISSUE TITLE
mehrere Datenpunkte zeitgleich bearbeiten für History

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.admin#231]
in der Liste der Objekte filtere ich mehrere Datenpunkte
Mit dem "Schraubenschlüssel" Icon rechts oben kann ich alle gefilterten Kanäle gleichzeitig bearbeiten.
Die Kanäle sind in dem Moment unterschiedlich eingestellt. Manche aktiviert, manche nicht.

"Entprellzeit" wird mit dem neuen Wert nur bei Kanälen übernommen, die bereits Aktiviert sind.
Der Haken bei "Aktiviert" und "Änderungen aufzeichnen" lässt sich nicht setzen.

sql 1.7.3
admin 3.3.5

![screenshot 2018-03-29 11 47 21](https://user-images.githubusercontent.com/20645041/38093098-3d3547f0-336a-11e8-9f1d-d00f360b0085.png)

**Comment by Homoran** [comment]
das gleiche gilt für History (und vermutlich für mqtt-client)

**Comment by GermanBluefox** [comment]
Please retest

**Comment by DutchmanNL** [comment]
I had the same issue, confirmed now working at version 3.3.9 thank you !

**Comment by Herbert-Testmann** [comment]
works with 3.3.9
