### ISSUE TITLE
[bug]: username not removed in the changelog

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2314]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Some usernames are not removed in the changelog. Looks like this is the case when the name contains special characters (see screenshot)

### To Reproduce

Update an adapter

### Expected behavior

Removed username

### Screenshots & Logfiles

<img width="824" alt="Screenshot 2024-01-14 at 11 40 52" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/0f8893e8-ec5b-451a-bb2f-e6798e20e316">

### Adapter version

6.13.15

### js-controller version

5.0.17

### Node version

20.x

### Operating system

Debian 12 lxc

**Comment by mcm1957** [comment]
@klein0r 

I'm not sure if this is really an admin issue.

Normally the username is not included in news contained in io-package.json. I've checked several adapters and theres only the text inside iopacakge.jsoen. I guess admin only displays whatever is included in io-package.json.

iobroker.dasWetter ahs (rene) included in io-package.json. As rg-engeneering seems to use the releasescript this could be a issue of the release-script. But maybe rg-engeneering uses some other method to fill io-package at all. 

Could you double check when time allows?
I'll check the release-scritp when I create a releas next time

**Comment by klein0r** [comment]
@mcm1957 You're right - the release script removes the author names.

https://github.com/AlCalzone/release-script/blob/111e796532a1d6410e4e61662d98fd6ac7c01faa/packages/plugin-iobroker/src/tools.ts#L17
