### ISSUE TITLE
[enhancement]: timePicker in jsonConfig nicht wirklich anwendbar

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#2319]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Der timePicker ist nicht in der Dokumentation beschrieben. Daher weiß ich nicht, ob es noch zusätzliche Konfigurationsparameter gibt. Aus meiner Sicht fehlt das 24h Format.  Es kann auch nicht jede Minute eingestellt werden. 
Das wäre evtl. auch mit der jetzigen Auswahlmöglichkeit viel Platzbedarf. Bei meiner jetzigen Lösung geht es aber.
Rückgabe String sollte konfigurierbar sein. Ich benötige z.B. nur "hh:mm". 
Ein timePicker sollte nur einen Zeitstring zurückgeben, da das Datum ja nicht ausgewählt wird.

 

### Description

Bisherige Lösung:
![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/c6ad9b7f-14a1-4035-8ebe-6312cfc5f5dd)

Bisherige Initialisierung:
![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/485b9775-0080-4bb1-9f39-e38194c7468a)

jsonConfig: Alter Wert aus der Config ist gespeichert, wird aber nicht angezeigt, da Formate nicht zusammenpassen.
![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/9eb97742-e676-4878-be9b-22d4ef79a99c)

Nach Eingabe eines Wertes: 
![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/befeff3c-1674-4eb6-9f25-cfea94ffc932)

**Comment by mcm1957** [comment]
see https://github.com/ioBroker/ioBroker.admin/issues/1923 too

**Comment by afuerhoff** [comment]
@mcm1957: Zum Teil ist das sicher so. Man kann sich ja auch auf keine Doku beziehen, da sie nicht existent ist.
Ich habe hier aber noch weitere Features aufgeführt.

**Comment by mcm1957** [comment]
@afuerhoff 
(inoffizielle Antwort - bin kein Kernel/Admin Entwickler)

a) 24h EINGABE via Text ist ohne Probleme möglich, grafische Auswahl ist auch aus meiner Sicht nicht optimal. Welche Möglichkeiten der react mui-x-timepicker hier bietet wäre zu klären

b) Die Components timePicker und datePicker scheinen keinen componentspezifischen Optionen anzubieten wenn ich den Source richtig gelesen habe.

c) Die Dokumentation dürfte irgendwann verloren gegangen sein. Ich habe ein Issue erstellt:
https://github.com/ioBroker/ioBroker.admin/issues/2320
