### ISSUE TITLE
[enhancement]: Allow "free text" input for npm installation (expert mode)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2325]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

If you want to install an adapter from npm (which is not listed in the current repository - e.g. "stable"), it is not possible to define a free text value.

e.g. `vedirect` to install https://www.npmjs.com/package/iobroker.vedirect

At the moment it is required to execute the command manually via ssh

💲 `iobroker url iobroker.vedirect@latest`

### Description

Allow free input for the text field (and not just values of the adapter list):

<img width="2037" alt="Screenshot 2024-01-22 at 09 18 17" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/b2822259-885c-4e08-affc-35cd35344d14">

**Comment by mcm1957** [comment]
Free text should include the possibility to specify a version or a version-tag (latest, next) too

**Comment by klein0r** [comment]
@mcm1957 Nice idea, maybe a second input should be added to specify the version (with default "latest")

**Comment by mcm1957** [comment]
I think 'vedirect@1.2.3' or 'vedirect@next' would be sufficient and less effort to implement.

Users who do not understand that syntax should most likely install stable release only ...

But of course a second field would be fine too. In this case a drop down with allows selction of existing tags at npm would be the top solution but free text would solve 99% of demand.

**Comment by klein0r** [comment]
> Default - to be defined

The current default is already "latest" when you install an adapter via npm

**Comment by Jey-Cee** [comment]
This is already possible in the User defined tab. Just enter npm command like on the CLI. 
I use this now for years in this way.
