### ISSUE TITLE
[bug]: Admin user with just read permissions do not load admin

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#2329]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Create a user like this (ok a group with sch a user)

![2024-01-25 08 55 00](https://github.com/ioBroker/ioBroker.admin/assets/11976694/a39576c7-7052-4487-9efe-7725d26e65d7)

Then configure admin to sart with this user.

Result is starpage of admin with "permissionDenied" error and nothing more

Example https://admin.iobroker.click/

### To Reproduce

see above

### Expected behavior

see above

### Screenshots & Logfiles

see above

### Adapter version

6.13.15

### js-controller version

5.0.17

### Node version

18

### Operating system

Ubuntu 22.04

**Comment by foxriver76** [comment]
According to console on iobroker.click the issue should be somewhere here

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/95780a07-7f36-4d49-8f15-600444bfdd22)

https://github.com/ioBroker/ioBroker.admin/blob/bc2c0d4c547bbc8b4daefa2b95cc42c1288adb23/packages/admin/src/src/App.jsx#L1013

Locally I was not able to reproduce it.

**Comment by Apollon77** [comment]
maybe that setState ?

**Comment by foxriver76** [comment]
It is a bit confusing when coming from ioBroker. But the `this.setState` is setting a react state^

**Comment by foxriver76** [comment]
I assume it is one of these commands, I will try with the provided backup of click https://github.com/ioBroker/ioBroker.admin/blob/bc2c0d4c547bbc8b4daefa2b95cc42c1288adb23/packages/admin/src/src/App.jsx#L946-L949

**Comment by Apollon77** [comment]
Good luck and thank you!
