### ISSUE TITLE
Onboarding "Nodejs 10" (before 24.04.2018)

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#233]
The Admin UI shows an Info box if no LTS version 4/5/8 is used.

In a first run we need to enhance that to also support nodejs 10 because it will be the next LTS starting 24.4.18.

Question: Only Admin3 or also an Admin2 change? :-)

Nodejs 4 should still be in as allowed for now, we should remove this later

**Comment by GermanBluefox** [comment]
Admin 3.3.6 akzeptiert node alles über node 8 (erstmal)

**Comment by Apollon77** [comment]
I still would show a message at node 9 because node 9 will not really be maintained after 10 is released ... but ok then we need to remember that later to remove 9
