### ISSUE TITLE
[bug]: Problem with dark mode

### ISSUE THREAD

**Issue by MaaG-dA** [ioBroker/ioBroker.admin#2333]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

There is an inaccuracy in the display change when switching to dark mode.
Not all icons that are drawn in the "light" mode, e.g. black, change to light when the "dark" mode is turned on. They still remain dark (black) - which makes them invisible (or almost invisible).
An example in the attached graphics.

### To Reproduce

Just switch to dark mode

### Expected behavior

fix it ?

### Screenshots & Logfiles

"Normal" color mode:
![dark1](https://github.com/ioBroker/ioBroker.admin/assets/87951504/f3a1a5ee-35d2-48b5-8ec6-549f5d181ede)
And "dark mode":
![dark2](https://github.com/ioBroker/ioBroker.admin/assets/87951504/9e2789bf-cccb-4cc1-8d08-6fb0a7e2e0f5)

### Adapter version

6.12.0

### js-controller version

n/a

### Node version

n/a

### Operating system

Debian 12

**Comment by Feuer-sturm** [comment]
admin 7.4.8
![grafik](https://github.com/user-attachments/assets/a80ad9f1-1d5f-4f28-b6cd-71b037e4cf43)
