### ISSUE TITLE
Better Dialog for "Deleting Instances"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#234]
In Dialog when deleting an instance only 

"Sind sie sicher?"

... should be changed to:
"Instanz mobile.0 wird gelöscht. Sind Sie sicher?"

Migrated from Trello (Image there): https://trello.com/c/n6upow2H

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/38466221-41788d2c-3b26-11e8-9749-72eeb5f9e4a1.png)

**Comment by Apollon77** [comment]
Perfect , then close.
