### ISSUE TITLE
[bug]: [JSONCONFIG]  No value for language type if set to system language

### ISSUE THREAD

**Issue by ciddi89** [ioBroker/ioBroker.admin#2352]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In JSON Config, for the type 'language' there is an option to choose the system language. But the option doesn't have any value. But it should contains the value from the system.config

### To Reproduce

Add in JSON Config a new type with:
```
userSelectedLanguage: {
        type: 'language',
        system: true,
	label: 'Language',
},
```

### Expected behavior

It should contain the value from the system.config for selected system language.

### Screenshots & Logfiles

not necessary. It is a blank value.

### Adapter version

6.13.16

### js-controller version

5.0.19

### Node version

v21.6.1

### Operating system

debian

**Comment by foxriver76** [comment]
No, it should not. Else, the user would select "system language" and it would be pinned down to the system language at time of selecting, however it actually means: change with the system language. 

So adapter needs to determine the system language at runtime if this is desired. If you just want hardcoded values do not set system true.
