### ISSUE TITLE
Log Level js-controller konfigurierbar machen

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.admin#236]
Wunsch:

Im Log werden die Adapter regelmäßig angezeigt, die mit CRON aufgerufen werden.
Hier wäre es wünschenswert, auch den Loglevel vom js-controller unter host einstellen zu können, z.B. auf Stufe "warn".

`

host.iobrokerng2 | 2018-04-08 08:25:11.816 | info | instance system.adapter.ical.0 terminated with code 0 (OK)
-- | -- | -- | --
host.iobrokerng2 | 2018-04-08 08:25:11.362 | info | instance system.adapter.dwd.0 terminated with code 0 (OK)
host.iobrokerng2 | 2018-04-08 08:25:00.026 | info | instance system.adapter.ical.0 started with pid 12022
host.iobrokerng2 | 2018-04-08 08:25:00.012 | info | instance system.adapter.dwd.0 started with pid 12015
host.iobrokerng2 | 2018-04-08 08:20:11.886 | info | instance system.adapter.ical.0 terminated with code 0 (OK)
host.iobrokerng2 | 2018-04-08 08:20:11.455 | info | instance system.adapter.dwd.0 terminated with code 0 (OK)
host.iobrokerng2 | 2018-04-08 08:20:00.040 | info | instance system.adapter.dwd.0 started with pid 11741
host.iobrokerng2 | 2018-04-08 08:20:00.016 | info | instance system.adapter.ical.0 started with pid 11733

`

**Comment by GermanBluefox** [comment]
To change the log level of js.controller, the whole iobroker must be restarted, what is not supported now.

You can set the log level here https://github.com/ioBroker/ioBroker.js-controller/blob/master/conf/iobroker-dist.json#L61
