### ISSUE TITLE
[enhancement]: extra tab for non host specific notifications

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#2363]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

Admin currently shows notifications which are from the `system` scope in the hosts tab of admin. 

All other notifications are currently ignored and users can only get them via https://github.com/foxriver76/ioBroker.notification-manager

### Description

Admin should have e.g. a tab, which hints to new notifications or/and should hint to notification manager adapter for managing notifications.

**Comment by Apollon77** [comment]
I agree!

If we introduce a new notification scope "admin" then we know all these and should show them by default.

All "other" notifications could be shown "collapsed" by default, but possible to being displayed/expanded/enabled

**Comment by foxriver76** [comment]
Basically implemented in https://github.com/ioBroker/ioBroker.admin/pull/2381

With maybe upcoming UX/UI rework.
