### ISSUE TITLE
[bug]: "Alle Adapter aktualisieren" zeigt nicht alle updatebaren Adapter

### ISSUE THREAD

**Issue by Boronsbruder** [ioBroker/ioBroker.admin#2367]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

3 Adapter könnten upgedatet werden.
Mit alle Adapter updaten werden nur 2 angezeigt.

### To Reproduce

Im Admin -> Adapter -> Alle Adapter Aktualisieren

### Expected behavior

Sollten nicht alle 3 Adapter aufgeführt werden?

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/dda12f56-41a8-4860-a4b7-40fec7165beb)
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/7c3e9d52-db53-4d5e-baca-17a714288669)

### Adapter version

Admin v6.13.16

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

**Comment by foxriver76** [comment]
Korrekt, wenn wichtige Benachrichtigungen für dieses Update existieren wird dieses Update nicht im Update All Dialog angezeigt. Selbiges gilt für admin selbst.
