### ISSUE TITLE
[bug]: Error in GUI! on #tab-hosts after restoring in a clean iobroker container

### ISSUE THREAD

**Issue by sohlt** [ioBroker/ioBroker.admin#2370]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hi guys,

IOBroker asked me to upload this issue. ;-) 

After restoring by maintenance script OR by GUI I get anytime the same issue. 

Before I backuped the old iobroker host I updated it to the latest version (5.0.17) inside the container (synology hosted) 

### To Reproduce

1. go to hosts (#tab-hosts)
2.  hover with the mouse into the windows it happen.
3. reload page
4. happen anytime on the #tab-hosts

### Expected behavior

By hovering to restart I expect to get the chance to go to. 

### Screenshots & Logfiles

bootstrap.jsx:19 iobroker.admin@6.3.5
bootstrap.jsx:68 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0 net::ERR_BLOCKED_BY_CLIENT
tt @ fetch.ts:35
I1 @ base.ts:75
It @ promisebuffer.ts:49
Nt @ base.ts:90
_sendEnvelope @ baseclient.ts:739
sendSession @ baseclient.ts:314
captureSession @ baseclient.ts:205
_sendSessionUpdate @ hub.ts:461
captureSession @ hub.ts:387
mr @ sdk.ts:252
z2 @ sdk.ts:281
qa @ sdk.ts:128
52898 @ bootstrap.jsx:68
n @ bootstrap:19
Promise.then (async)
72063 @ index.jsx:1
n @ bootstrap:19
(anonymous) @ startup:4
(anonymous) @ main.f92f1824.js:4
Show 12 more frames
Show less
socket.io.js:66 [2024-02-16T18:09:50.929Z] Try to connect
App.jsx:713 Stored version: , new version: 6.3.5
HostsWorker.jsx:13 Connected: true
Hosts.jsx:236 Translate: time
Hosts.jsx:236 Translate: timeOffset
Hosts.jsx:236 Translate: dockerInformation
Hosts.jsx:236 Translate: You cannot delete host, when it is alive
Hosts.jsx:236 Translate: Copy
instrument.ts:124 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisDocker%2C%20isOfficial%2C%20officialVersion%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Zr (react-dom.production.min.js:152:60)
    at h (react-dom.production.min.js:156:186)
    at S (react-dom.production.min.js:158:331)
    at Q (react-dom.production.min.js:162:334)
    at ae (react-dom.production.min.js:192:308)
    at oa (react-dom.production.min.js:294:9)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at bs (react-dom.production.min.js:268:429)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)
(anonymous) @ instrument.ts:124
Hi @ react-dom.production.min.js:189
i.componentDidCatch.t.callback @ react-dom.production.min.js:190
Yo @ react-dom.production.min.js:144
Zs @ react-dom.production.min.js:261
Gs @ react-dom.production.min.js:260
Xc @ react-dom.production.min.js:259
bc @ react-dom.production.min.js:283
$n @ react-dom.production.min.js:281
bs @ react-dom.production.min.js:269
Ln @ scheduler.production.min.js:13
Gn @ scheduler.production.min.js:14
Show 12 more frames
Show less
client.ts:138 
        
        
       POST https://sentry.iobroker.net/api/58/envelope/?sentry_key=43643152dab3481db69950ba866ee9d6&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.0 net::ERR_BLOCKED_BY_CLIENT
_flushOutcomes @ client.ts:138
(anonymous) @ client.ts:60
Show 2 more frames
Show less

### Adapter version

5.0.17

### js-controller version

5.0.17

### Node version

v18.19.0

### Operating system

Docker version 24.0.5, build ced0996

### Additional context

![image](https://github.com/ioBroker/ioBroker.admin/assets/74131869/c67c6a31-0a85-4b38-9cae-1f30830f2987)

**Comment by foxriver76** [comment]
Adapter Version 5.0.17? I think this is an old admin version with a current controller version.
