### ISSUE TITLE
[enhancement]: Change icon of "free" adpaters (licenseInformation)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2375]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

The current "TextIcon" is too prominent in my opinion.
Maybe the icon should be removed completely for free apdaters?

### Description

<img width="875" alt="Screenshot 2024-02-20 at 09 48 15" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/748d81e4-d870-47ae-8f32-ac5ffde36e76">

**Comment by klein0r** [comment]
- Current Icon: https://mui.com/material-ui/material-icons/?query=text&selected=TextSnippet
- Suggestion: Use https://mui.com/material-ui/material-icons/?query=MonetizationOn&selected=MonetizationOn in different colors (red, yellow, green) and remove it completely for free adapters

**Comment by mcm1957** [comment]
Small note (not really releated to payment symbol)

The columns should be aligned, so if an adapter does not specify i.e. cloud usage, the other symbols should NOT be move to the left.

**Comment by foxriver76** [comment]
Not sure if it is good to rely just on colors for UX, especially for people which might be not able to distinguish colors well. But yes, I am also not a 100 % happy. We basically have 4 categories -> `free` (ok we can get rid of icon if free), `limited`(balance icon - e.g. iot you can do 20 requests per day, else pay), `paid` (MonetizationOn icon - only with paid license), `commercial` (BusinessCenter icon - free but pay for commercial use). If you have better idea for icon let me know, but as stated just color is not optimal from my pov.

**Comment by pafade89** [comment]
Additionally, it should be mentioned that the icons are not visually sorted nicely, so it always looks quite chaotic.

![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/ac90ebf3-9299-487a-a4a8-8401c19eafaf)

**Comment by klein0r** [comment]
> but as stated just color is not optimal from my pov.

I agree. But: explaining everything with a bunch of different icons is also not that easy (and I was confused what the "letter" icon means).

**Comment by mcm1957** [comment]
I agree with klein0r

I do not see a big problem with colours - except for free adapters which I simply would display without a symbol (or a placeholder minus). If someone has problems detecting colours he/she should be able to trigger an associated tooltip with an explanation.

In my oppinion this icon should primary signal "Attention, this adapter requires or might require a payment" as opposite that the adapter is free for all. I do NOT think that anyone will associate multiple icons - especially as they are only used at very few adapters - with different commercial aspects.

So I would suggest

free - no symbol
paid - $ symbol, even if only paid for commercial purposes, ebentually using different colours and a tooltip in any case

Most adapters requiring payment for commercial purposes will require a license for private use too - kits only prced cheeper (= 0€). So handling for users is nearly identical.

**Comment by foxriver76** [comment]
> If someone has problems detecting colours he/she should be able to trigger an associated tooltip with an explanation.

not on mobile

**Comment by foxriver76** [comment]
please check with 6.14.1 as soon as released
