### ISSUE TITLE
[bug]: No LICENSE information with older admin

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2378]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Adapters SHELLY and NOT-TOOLS already migrated and use common.licenseInformation 
Those adapter do not display any license information with current stable admin (6.13.16)

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/5d516e26-d665-4db7-958b-b43c30725978)

### To Reproduce

Install current stable admin (6.13.16)
select lates repository
see screenshot attached above

### Expected behavior

Older admin should display license information as usual.

### Screenshots & Logfiles

see description

### Adapter version

6.13.16

### js-controller version

5.0.19

### Node version

v18.19.1

### Operating system

raspian

**Comment by mcm1957** [comment]
Additional information

After updating admin to 6.14.1 still no license information is visible. 6.14.1 IS installed at the alignment of icons is no OK

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/2a4bda02-688f-4b6e-a239-fd036ee88176)

**Comment by mcm1957** [comment]
OK next info:

Problem seesm to be the repository script
https://repo.iobroker.live/sources-dist-latest.json

Does NOT contain a license or licenseInformation object (at least I die not find it - reading this big file is a little bit difficult)

**Comment by foxriver76** [comment]
the latest repo now seems to be build correctly.

**Comment by mcm1957** [comment]
Will have to check .json and source io-packages.json. Something still seems to be wrong.

- shelly seems to be OK now
- net-tools is still missing license text and $ indicator

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/b6c69f06-dc9e-4f16-8d52-2c99d77f2394)

admin 6.14.1
latest repository
manual refreh triggered (search for updates button clicked)

**Comment by foxriver76** [comment]
not a repo issue with net-tools https://github.com/Jey-Cee/ioBroker.net-tools/issues/32

**Comment by mcm1957** [comment]
OK, and sorry - did not check this one.
Thanks for Issue @net-tools

**Comment by mcm1957** [comment]
Additional question:

There was no correction commit at repo iobroker.repositories.

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/a704970d-d32a-4cfc-90f8-feae48284f9a)

Where was the code fixed?
Will the scripts at iobroker.repository be adapted or are they outdated?
We should clearify whgich scripts are executed and where they are maintained. 
(O - its OT here, but consider this as a reminder to clearify with BF)

**Comment by foxriver76** [comment]
As mentioned in telegram, BF noticed later on, that the code in repositories is not the one executed as he first thought. So we could delete the stuff in repositories and add to readme that it is build on AWS instead. As far as I understood, it is not worth the effort currently to migrate it to GH, however, at least the full core team has now access to the code.

**Comment by foxriver76** [comment]
I think this should be fixed at repo level

**Comment by mcm1957** [comment]
Yes, 
feel free to close
Otherwise I will test as soon as tesing PR has been released by Dominiy so that adapetrs with ne Information can be released

**Comment by mcm1957** [comment]
Problem seesm to be fixed after update of effeted adapters.

So we can close here
