### ISSUE TITLE
Objekte - fehlende Übersetzung

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.admin#238]
Leider ist der Text der markierter Auswahlfelder nicht auf Deutsch übersetzt. Vielleicht eine Kleinigkeit für das nächste Update.

![unbenannt](https://user-images.githubusercontent.com/38273154/38597372-93766a08-3d57-11e8-996b-1cbe017eeff3.png)

**Comment by GermanBluefox** [comment]
Fixed in next version
