### ISSUE TITLE
[bug]: update js-controlle brings error

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2382]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

today i update the js-controller from 5.0.18 to5 .0.19.

this message comes up.

![image](https://github.com/ioBroker/ioBroker.js-controller/assets/92173565/d29ac874-4665-4338-9ead-d46c82c57bdb)

i hope everything works. after i click close the js-controller is up to 5.0.19

**Comment by foxriver76** [comment]
one question here: are you running multihost?

**Comment by BenAhrdt** [comment]
no. No multihost.
Just one in docker container

**Comment by mcm1957** [comment]
@Apollon77 
Did you close this issue intentionally?
As far as I see there is no solution / reason logged until now.

**Comment by Apollon77** [comment]
sorry ...

**Comment by foxriver76** [comment]
In the near future we will have some additional console logging, because without it is hard to say if ip is correct and what the response actually was. https://github.com/ioBroker/ioBroker.admin/pull/2386

**Comment by foxriver76** [comment]
should be fixed with 7.0.22 and above
