### ISSUE TITLE
[enhancement]: Uniform links to the adapter documentation

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#2383]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

different links to the adapter documentation

### Description

As discussed in the dev meeting, I think it would be great if the links to the adapter documentation in the "Adapter" tab and in the instance itself pointed to the same documentation.

It was also suggested that the system language should be used to check whether there is a doc in the repo for the system language and then link directly to it

**Comment by foxriver76** [comment]
Which exactly do you mean?

I have noticed that 

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/39b90b50-c4cb-4362-bd4c-2e0cd391975e)

and 

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25484431/aa972f7f-4c4a-4dd4-9275-e559b2fbc9f4)


both lead to readme.

**Comment by foxriver76** [comment]
Okay it seems like the following is the case currently: 

At instance level: 
Adapters written in jsonConfig have a link to the docs automatically instead of readme, like `https://www.iobroker.net/#${lang}/adapters/adapterref/iobroker.${this.props.adapter}/README.md`

Adapters without jsonConfig simply have a link to readme

At adapters tab level:
All have a link to readme

So the goal would be to always direct users to the docs I guess.

**Comment by simatec** [comment]
> So the goal would be to always direct users to the docs I guess.

Yes, that would be the goal... In the end, we would have to check whether there is a docs in the repo and which languages are available.

1. if the system language selected in iobroker is available, it should be displayed directly.
2. if only English documentation is available, this should be displayed.
3. if no docs are available and only a readme is available, this should be displayed.

The whole thing is then identical in the two places from your screenshots.

This is roughly what we discussed in the dev meeting

**Comment by foxriver76** [comment]
The docs seems to be translated automatically in `'en', 'de', 'ru', 'zh-cn'`. I can only speak for german, but it does not look too bad (as it is done via Google translate not like LibreTranslate like for news), e.g. https://www.iobroker.net/#de/adapters/adapterref/iobroker.benchmark/README.md there are some flaws, which seem to be mainly by wrongly parsing texts to translator. However, in general I could imagine that a german speaker prefers the translated one over an english one. 

But if it was the final outcome from meeting, we can also follow the proposed approach.

**Comment by simatec** [comment]
I would think it would be very cool to take the actual docs from the developers and not automatically translate them here.
I think that would also honor the work of the developers, since they take the trouble to make docs available in several languages

**Comment by simatec** [comment]
Very cool... many thanks for the implementation

**Comment by foxriver76** [comment]
Please check if the behavior fits with 6.15.0 (as soon as available -seems github has problems with actions again)

**Comment by simatec** [comment]
Looks very good... All links now refer to the documentation of iobroker.net.
Now we just have to get the documentation there up to date or keep it up to date and fix a few bugs with the display.

I will add a few points for the next dev meeting.
