### ISSUE TITLE
Fehlerhafte Darstellung in Adapterübersicht "Visualisation"

### ISSUE THREAD

**Issue by winterson0** [ioBroker/ioBroker.admin#239]
Die Darstellung des Adapters "Visualisation" im  Reiters "Installieren" ist fehlerhaft. 
Siehe Bild.

![iobroker_fehler](https://user-images.githubusercontent.com/38296136/38635498-ccda9b7a-3dc5-11e8-84af-d37cab35e7bb.jpg)

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren.
Was sieht man in Source?
![image](https://user-images.githubusercontent.com/4582016/38690162-be091d20-3e7d-11e8-94ed-a3a4d39a8cfb.png)

**Comment by winterson0** [comment]
Langt das so?
![iobroker_fehler_untersuchen](https://user-images.githubusercontent.com/38296136/38690667-f2c79dc4-3e7e-11e8-8667-3b7d5f9a731e.jpg)

**Comment by GermanBluefox** [comment]
Please expand all 3 buttons:
![image](https://user-images.githubusercontent.com/4582016/38700893-c6411e2e-3e9c-11e8-91fa-06e1f93b124a.png)

**Comment by winterson0** [comment]
Here with expand buttons
![iobroker_fehler_expand](https://user-images.githubusercontent.com/38296136/38704805-c1e3c24a-3ea7-11e8-87a7-724175b2279b.jpg)

**Comment by GermanBluefox** [comment]
Bei mir sieht es so aus. Ich vermute, du hast Title vom Adapter Geändert
und ">" am Ende eingetippt.


2018-04-12 23:18 GMT+02:00 winterson0 <notifications@github.com>:

**Comment by winterson0** [comment]
Also ich habe jetzt mal auf "Experten-Ansicht" umgeschaltet. Hier wird es richtig dargestellt. Nach zurück stellen auf "Normalsicht" war es jetzt hier auch wieder ok.
Keine Ahnung warum???
