### ISSUE TITLE
[bug]: [JSON-CONFIG] Array data is not saved in the CustomConfig

### ISSUE THREAD

**Issue by Xenon-s** [ioBroker/ioBroker.admin#2392]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I assemble my jsonCustom via selectSendTo. The data comes in like this : [{"label": "1", "value":1709366561874},{"label": "2", "value":1709366563037}]

If I now have multiple true, the select is set up correctly, but not written to the object native. No error is displayed, it is simply not saved.
If I remove the "multiple", everything is saved correctly.
If you create the same function and configuration in the jsonCustom, everything works

### To Reproduce

1. create a Telegram user in the instance, for example 
2. select the user on an object for the custom config
3. save and close
4. open the config again, no data has been saved in select

### Expected behavior

Please fix the error.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/65488191/73cc793e-9a58-43c7-bd23-a526da6d554c)
![image](https://github.com/ioBroker/ioBroker.admin/assets/65488191/bca65aab-082d-4a0d-a10d-00e62c347e42)
![image](https://github.com/ioBroker/ioBroker.admin/assets/65488191/26c158d9-e550-45d3-afd1-bf623eb37f69)

### Adapter version

6.15.0

### js-controller version

5.0.19

### Node version

18.19.1

### Operating system

ubuntu 22.04

**Comment by Xenon-s** [comment]
repo:
https://github.com/Xenon-s/ioBroker.device-reminder

**Comment by Xenon-s** [comment]
[Update] It works with the stable version of Admin 6.13.16

![image](https://github.com/ioBroker/ioBroker.admin/assets/65488191/b8ade765-c681-4d54-8db0-964992f164d5)

**Comment by foxriver76** [comment]
The cause is https://github.com/ioBroker/ioBroker.admin/commit/5013fbf301e516c72f20ebf3b1f250fcd38cf946 because of https://github.com/ioBroker/ioBroker.admin/issues/2359 

Needs some further adaption
