### ISSUE TITLE
Anzeige des freien Diskspeichers auf Info Tab

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.admin#240]
Aktuell wird da ja z.b. schon der freie RAM, CPU etc. angezeigt. Jetzt dazu noch die SD Karten Werte wäre top!

**Comment by GermanBluefox** [comment]
Ist implementiert. Dazu braucht man aber js-controller vom git.

**Comment by JackWolfskin42** [comment]
Habe erst auf Admin 3.4.3 aktualisiert und dann noch js-controller 1.50 von github über custom install, restartet und läuft :-)

Vielleicht könnte man aber die Werte noch etwas verbessern ?
Aktuell wird von iobroker gemeldet:
Disk size    3883851776
Disk free    790757376

Erwartet hätte ich eher Werte wie vom DF Befehl:
/opt/iobroker$ df -h /root

Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/root       3,7G    2,9G  **576M**   84% /

Also am besten in GB oder MB, aber vor allem ist der in iobroker als free gemeldete Wert zu hoch, evtl. rechnet das die Ramdisk mit, wobei das wäre dann eher ~1000MB frei?

**Comment by GermanBluefox** [comment]
Es ist komisch warum die Werte nicht umgerechnet werden. Bei mir sieht es so aus:
![image](https://user-images.githubusercontent.com/4582016/40052755-0bac8cc6-583f-11e8-988b-3b4dba8e78f4.png)

Es wird tatsächlich "df -B 1024 /" Befehl benutzt.
```
                    // Filesystem            1K-blocks    Used Available Use% Mounted on
                    // /dev/mapper/vg00-lv01 162544556 9966192 145767152   7% /
```
Und dann 162544556 als Disk size genommen, und 145767152 als Free.

**Comment by JackWolfskin42** [comment]
Sehr komisch, bei mir kommt da auch folgendes raus:
/opt/iobroker$ df -B 1024 /

Dateisystem    1K-Blöcke Benutzt Verfügbar Verw% Eingehängt auf
/dev/root        3792824 3021712    587808   84% /
/opt/iobroker$

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren.
Was ist bei @Apollon77, @BuZZy1337 , @AlCalzone ?

**Comment by AlCalzone** [comment]
Prüfe ich heute Abend.

**Comment by BuZZy1337** [comment]
@GermanBluefox Hab gerade JS Controller von Git installiert und Admin auf 3.4.7 aus der Repo..

Bei mir sieht es so aus:
![image](https://user-images.githubusercontent.com/6979405/41893476-28485d12-791c-11e8-92bc-70cd6d3522c3.png)

The calculation is wrong here:
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/tools.js#L957
```javascript
return callback && callback(error, {'Disk size': parseInt(parts[1]) * 1024, 'Disk free': parseInt(parts[3]) * 1024});
```

----
Maybe we should just use `df -h /` ?
Then we dont have to do any calculations..
```root@ioBroker:/opt/iobroker/node_modules/iobroker.js-controller# df -h /
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sda1        14G    4,0G  8,8G   32% /
```

**Comment by GermanBluefox** [comment]
Auf russisch sind Gb => Гб und das ist der Grund

вт, 26 июн. 2018 г., 9:41 BuZZy1337 <notifications@github.com>:
