### ISSUE TITLE
[bug]: Deleting Object causes Exception

### ISSUE THREAD

**Issue by tops4u** [ioBroker/ioBroker.admin#2402]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When trying to delete Objects or a Folder in the browser (Safari 17.3.1 /  Firefox 123.0 on MacOS 14.3.1) an exception occurs

### To Reproduce

Open the Objects and delete any object or folder

### Expected behavior

Selected object is deleted

### Screenshots & Logfiles

Error Code:
Rs@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:116947(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)e@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:61060(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)wo@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:73210(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)Ei@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:122136(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ks@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:109415(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ys@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:109343(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)vs@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:109206(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)us@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:105986(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ss@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:106377(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)Hl@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:46916(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)@http://nas:8081/static/js/5096.3d7275da.chunk.js:2:103919

From JS Console:
<img width="750" alt="image" src="https://github.com/ioBroker/ioBroker.admin/assets/6877067/5efe986b-3c72-48ec-b0e1-583350460998">

### Adapter version

admin 6.3.5

### js-controller version

5.0.19

### Node version

18.18.2

### Operating system

Linux (Docker on Synology)

**Comment by beandi** [comment]
fixed in 6.15.1
see https://github.com/ioBroker/ioBroker.admin/issues/2396 and https://github.com/ioBroker/ioBroker.admin/issues/2393

**Comment by foxriver76** [comment]
> admin 6.3.5

is neither stable nor latest, please do not open issues with in between version
