### ISSUE TITLE
[bug]: GUI crashed

### ISSUE THREAD

**Issue by dexic79** [ioBroker/ioBroker.admin#2406]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Error in GUI!
Please open the browser console (F12), copy error text from there and create the issue on [github](https://github.com/ioBroker/ioBroker.admin/issues)
Without this information it is not possible to analyse the error.
It should looks like
error
If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
```
Loading chunk 8917 failed. (error: http://192.168.178.64:8081/static/js/8917.cd25ddbb.chunk.js)

t.f.j@http://192.168.178.64:8081/static/js/main.22705a8c.js:1:11752(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)t.e/<@http://192.168.178.64:8081/static/js/main.22705a8c.js:1:1118(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)t.e@http://192.168.178.64:8081/static/js/main.22705a8c.js:1:1096(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)85392/qa<@http://192.168.178.64:8081/static/js/6518.bdbf8c40.chunk.js:2:217277(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)P@http://192.168.178.64:8081/static/js/3617.303c042a.chunk.js:2:3345(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)Ei@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:120780(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ks@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:109414(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ys@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:109342(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)vs@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:109203(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)ss@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:106321(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)Hl@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:46914(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)15009/ls/<@http://192.168.178.64:8081/static/js/2882.4644449f.chunk.js:2:103916(e,t)=>(0,f.jsxs)("div",{children:[e,(0,f.jsx)("br",{})]},t)
```
### To Reproduce

I have only wanted to switch from Objects to Instances

### Expected behavior

Should move on

### Screenshots & Logfiles

See in description

### Adapter version

up to date

### js-controller version

5.0.19

### Node version

v18.19.0

### Operating system

Linux (Raspberry Pi 4)

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden
