### ISSUE TITLE
[bug]: Alias convert shows validation error in dialog for mixed type

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2408]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

<img width="524" alt="Screenshot 2024-03-11 at 16 00 11" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/3195e22e-42b0-4b28-8da1-6f58b74a5644">

### To Reproduce

- Create a new state with type `mixed`
- Create an alias to write that state
- Use a custom write function

### Expected behavior

Mixed should accept all values and should not be validated

### Screenshots & Logfiles

see above

### Adapter version

v6.15.2

### js-controller version

5.0.19

### Node version

20.x

### Operating system

debian 12

**Comment by klein0r** [comment]
Avoid type comparison if `finalType` is `mixed`

https://github.com/ioBroker/ioBroker.admin/blob/4f901d24c663dfeef52f4de8e35ddd9fad7e8b14/packages/admin/src/src/components/Object/ObjectBrowserEditObject.tsx#L569

**Comment by Feuer-sturm** [comment]
@klein0r can you please check if this issue can be closed?
