### ISSUE TITLE
[bug]: get rid of instance.common.disableDateReporting

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#2409]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Use the plugin state instead to deactivate sentry plugin - lol ;-)

See https://github.com/ioBroker/ioBroker.js-controller/pull/2638#issuecomment-2002490554 and the whole discussion

### To Reproduce

On instances tab in expert mode disable/enable sentry via icon, it uses the self defined flag instead of the true plugin state

### Expected behavior

Use `${this.instanceId}.plugins.sentry.enabled` state instead of increasing object size by redundant property

### Screenshots & Logfiles

 No

### Adapter version

6.15.2

### js-controller version

5

### Node version

16

### Operating system

linux

**Comment by Feuer-sturm** [comment]
@foxriver76 can this issue be closed?
