### ISSUE TITLE
Hilfe Button bei Instanzen hinzufügen

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.admin#241]
"Hilfe" gibts zwar beim Adapter aber nicht ihren Instanzen, wo man die Hilfe oft eher braucht. Am besten wäre es statt den oft kombinierten Readme's zur Installation und "Anleitung" getrennte Dokument zu machen. Aber für den Anfang wäre es imho schon nett den Readme Link auch in den Instanzen mitaufzunehmen.

**Comment by GermanBluefox** [comment]
Die Hilfe ist in dem Konfigurationsdialog vorhanden:
![image](https://user-images.githubusercontent.com/4582016/39143966-aa88c5ba-472f-11e8-8f16-470ef2ad317b.png)

**Comment by GermanBluefox** [comment]
Das ist tatsächlich Admin3
