### ISSUE TITLE
[bug]: Error when clicking on update

### ISSUE THREAD

**Issue by kuch3n** [ioBroker/ioBroker.admin#2410]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Update fails with error message

version: 6.7.2
version admin: 6.7.2 -> 6.13.6
reproducable: always

clicking on system settings doesn't work either, maybe my installation is just foobar

### To Reproduce

1. go to main page
2. click on system settings in top bar

### Expected behavior

 start update

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/977721/d57706f5-9131-463f-b625-0a12cdbd06b7)

### Adapter version

6.7.2

### js-controller version

4.0.24

### Node version

v18.19.0

### Operating system

Ubuntu/Docker

**Comment by mcm1957** [comment]
Thanks for reposting a problem.

Please updateyour system

js-controller 4.x.x is outdated, - current stable veresion is 5.0.19
admin 6.7.2 is outdated - current stable version is 6.13.16

**Comment by kuch3n** [comment]
> Thanks for reposting a problem.
> 
> Please consider updateing your system
> 
> js-controller 4.x.x is outdated, - current stable version is 5.0.19 admin 6.7.2 is outdated - current stable version is 6.13.16

Just updated via console, but clicking on "systemsettings" still gives an error:

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/977721/f620daa1-7403-4a9f-8489-1515b37ac6a4)

**Comment by mcm1957** [comment]
Updated js-controller and admin?
Please state actual versions

**Comment by kuch3n** [comment]
> Updated js-controller and admin? Please state actual versions

js-controller: 5.0.19 (via iobroker -v)
admin: 6.13.16 (via web)

**Comment by mattreim** [comment]
"iob rebuild" and "iob fix" is your friend

**Comment by kuch3n** [comment]
it was the Proton Pass extension for Firefox, not a problem with iobroker or it's installation. Anyway, thanks for the quick support (:
