### ISSUE TITLE
[bug]: timePicker Attribut timeSteps in jsonConfig hat keine Wirkung

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#2414]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Mit folgender Konfiguration ändert sich die Einstellung für timeSteps nicht (siehe Bild). Es bleibt bei der Default Einstellung.
            "format": "HH:mm",
            "returnFormat": "HH:mm:ss",
            "views": ["hours", "minutes"],
            "timeSteps": {"hours": 1, "minutes": 1},

Außerdem scheint tooltip nicht im Schema enthalten zu sein. siehe 2. Bild

### To Reproduce

-

### Expected behavior

Timestep Einstellung für Minuten in 1 Minuten Schritten.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/26dfe974-5151-424b-879b-7b238c17c21d)

![image](https://github.com/ioBroker/ioBroker.admin/assets/50245893/d4dbbec1-3256-47c6-bf96-7b83ace5d0f7)

### Adapter version

6.15.2

### js-controller version

5.0.19

### Node version

18.20.0

### Operating system

Debian 12 - Proxmox

### Additional context

-

**Comment by Feuer-sturm** [comment]
@afuerhoff please check with admin 6.17.13

**Comment by afuerhoff** [comment]
Funktioniert mit 6.17.13.
Danke
