### ISSUE TITLE
Objekt Bezeichner hinzufügen

### ISSUE THREAD

**Issue by JackWolfskin42** [ioBroker/ioBroker.admin#242]
Instanzen  können zwar mit einem Titel benamst werden , aber ihre Objekte nicht! Dadurch können Objekte unterschiedlicher Instanzen gleichen Adapters kaum unterschieden werden (nur der Nummer nach). Dazu muss man immer erstmal wieder unter Instanzen nachgucken was das überhaupt ist. Vielleicht wäre es möglich den Instanz Titel  entweder mit in die Object ID zu packen oder zusätzlich bei den Objekten als Spalte anzuzeigen?

**Comment by DutchmanNL** [comment]
Währe das nicht doppelt ich begreife Sinnlicht ganz?
Ich finde es nur unübersichtlicher wen da noch ne Spalte mit Instanz dazu käme das würde der Übersicht nicht gerade zu gute kommen.
Und wen man das nur im Experten Modus macht trifft man nur User die es ohnehin bereits durch den Namen .x begreifen sollten

**Comment by GermanBluefox** [comment]
This is technically almost impossible. We should rewrite the core to allow
that.

ср, 11 апр. 2018 г., 23:28 Dutchman <notifications@github.com>:

**Comment by JackWolfskin42** [comment]
Ich wollte eigentlich gar keinen so großen Aufwand triggern ;)
 
Wird der Instanz Titel aktuell eigentlich für irgendwas verwendet?
![instant title](https://user-images.githubusercontent.com/38285253/38662679-64b7babc-3e35-11e8-9fdc-130b0d34914c.JPG)

Könnte man als Workaround den Objekt Namen manuell editieren?
![objekte](https://user-images.githubusercontent.com/38285253/38662737-8ba78d6e-3e35-11e8-8b90-d7e11d024f80.JPG)
Ups, das geht ja bereits - hätte wetten können das das vor kurzem noch nicht ging - never mind - reicht mir :-)

**Comment by GermanBluefox** [comment]
Close?

чт, 12 апр. 2018 г., 9:43 JackWolfskin42 <notifications@github.com>:

**Comment by JackWolfskin42** [comment]
Leider doch keine Lösung: Es kann nur der Name vom system.adapter.xyz vom Typ instance geändert werden, aber nicht der Name der Objekte selber :-(
Aktuell funktionieren aber mein modbus Instanzen gar nicht mehr. Entweder ist mit beim admin Update was schief gelaufen oder man sollte nicht an den Instance Namen rumspielen ;-)

**Comment by GermanBluefox** [comment]
Also ich werde definitiv "renamer" von ObjektIDs nicht implementieren.
