### ISSUE TITLE
[bug]: Admin crashes if state infoUpdates is invalid

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2422]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If the contents of info.updates.Json is not parseable, abdmin seems to crash.

Link to code:
https://github.com/ioBroker/ioBroker.admin/blob/836eba9df14c2b4f72367e34f7db5df099c64d9a/packages/admin/main.js#L514C24-L514C40

Discussion at Forum:
https://forum.iobroker.net/topic/73873/iobroker-admin-startet-nicht-mehr/5

### To Reproduce

see discussion at forum.

I assume (but not tested ) that writing any nonsens into state info.jsonUpdate should cause the problem

### Expected behavior

a) Admin should ignore invalid data at this state
b) Admin should of course not crash
c) If an error is logged it should be useable without look into the code :-)

### Screenshots & Logfiles

see Forum
https://forum.iobroker.net/topic/73873/iobroker-admin-startet-nicht-mehr/5

### Adapter version

6.13.16

### js-controller version

5.0.19

### Node version

18.20.0

### Operating system

Debian GNU/Linux 11 (bullseye)

**Comment by Feuer-sturm** [comment]
Asked in forum thread if someone can test this issue
