### ISSUE TITLE
[enhancement]: Add Warning when changing customConfig for all states at once

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2423]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

At the Objects Tab one can edit the custom Config for ALL existing states when selecting the wrench symbol. This can be destructive as this might put a undesired and high load onto the system.

### Description

I would suggest to either reove the possibility to change all states with one click completly or at least add a Warning "Are you sure that you want to change all xxxx States?" or something similar

**Comment by GermanBluefox** [comment]
![image](https://github.com/ioBroker/ioBroker.admin/assets/4582016/42dad2fd-0eaa-4bb6-9a25-085ec04d115c)

**Comment by Feuer-sturm** [comment]
@mcm1957  please check with current beta version 6.17.13 if this issue can be closed

**Comment by mcm1957** [comment]
Warning is OK

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/d87660cc-f765-4fa5-a332-6b565df61eed)
