### ISSUE TITLE
[bug]: Some dialogs aren't centered anymore

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#2425]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

e.g. Adapter update dialogs

### To Reproduce

1. Go to adapters
2. Filter for adapter with updates
3. See dialog

### Expected behavior

Centered window / dialog

### Screenshots & Logfiles

<img width="1616" alt="Screenshot 2024-04-09 at 12 11 53" src="https://github.com/ioBroker/ioBroker.admin/assets/1959049/24bae88d-f216-43db-b605-48f6a24f9255">

### Adapter version

v6.17.2

### js-controller version

5.0.19

### Node version

20.x

### Operating system

Debian 12

**Comment by Feuer-sturm** [comment]
@klein0r  please check with current beta version 6.17.13 if this issue can be closed
