### ISSUE TITLE
[bug]: npm adapter installation is broken

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.admin#2426]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Installing the latest npm version of an adapter via the npm tab hasn't been functioning since version v6.17.0. The window simply closes afterwards.

### To Reproduce

1. Go to adapter
2. Click on githubs octocat
3. Choose npm tab
4. install admin adapter

### Expected behavior

install adapter

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/aa10cb17-5254-45b9-ab46-5e7d3dc0b453)

### Adapter version

Since 6.17.0

### js-controller version

5.0.19

### Node version

18.20.1

### Operating system

Debian

**Comment by pafade89** [comment]
Unfortunately, nothing is written here so that I can send you something. Here is the problem as a video. As I said, everything worked fine before v6.17.0.


https://github.com/ioBroker/ioBroker.admin/assets/113902279/117f4e0a-2607-4f45-92ae-3ba57828dd7e

Once the 'Install' button is clicked, the window simply closes.

**Comment by mcm1957** [comment]
Thanks.

**Comment by dimaiv7** [comment]
Bei mir auch. 
"von Github" und "Benutzerdefiniert" funktionieren auch nicht.
Egal welches Browser, PC, Stadt, Land.....
Keine Log Einträge.
