### ISSUE TITLE
[bug]: jsonConfig schema errors where they shouldnt be

### ISSUE THREAD

**Issue by sestriel** [ioBroker/ioBroker.admin#2429]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

jsonConfig.json: When using the "password" type as an item inside an table, the properties "attr" and "title" are treated as not allowed and produce following error in logs

### To Reproduce

Use type "password" inside table:
```json
"presetTopics": {
            "type": "table",
            "sm": 12,
            "items": [
                {
                    "type": "text",
                    "attr": "presetTopicName",
                    "title": "presetTopicName"
                },
                {
                    "type": "select",
                    "attr": "presetTopicAuth",
                    "title": "presetTopicAuth",
                    "options": [
                        {
                            "label": "presetTopicAuthNone",
                            "value": 0
                        },
                        {
                            "label": "presetTopicAuthUser",
                            "value": 1
                        },
                        {
                            "label": "presetTopicAuthToken",
                            "value": 2
                        }
                    ]
                },
                {
                    "type": "text",
                    "attr": "presetTopicUsername",
                    "title": "presetTopicUsername"
                },
                {
                    "type": "password",
                    "attr": "presetTopicPassword", // <= Property attr is not allowed
                    "title": "presetTopicPassword", // <= Property title is not allowed
                    "visible": true,
                    "style": {}
                },
                {
                    "type": "password",
                    "attr": "presetTopicAccessToken", // <= Property attr is not allowed
                    "title": "presetTopicAccessToken", // <= Property title is not allowed
                    "visible": true,
                    "style": {}
                }
            ]
        },
```

### Expected behavior

self-saying.. these properties should work or do i miss something?

### Screenshots & Logfiles

XYZ has an invalid jsonConfig: [{"instancePath":"/items/presetTopics/items/4","schemaPath":"#/definitions/passwordProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"title"},"message":"must NOT have additional properties"},{"instancePath":"/items/presetTopics","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/23/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match \"else\" schema"}]

### Adapter version

6.17.3

### js-controller version

5.0.19

### Node version

18.18.0

### Operating system

Linux

**Comment by mcm1957** [comment]
Known problem - see https://github.com/ioBroker/adapter-react-v5/issues/292

Will be handled there.

Please report error at checking schema at repository iobroker/adapter-react-v5 (https://github.com/ioBroker/adapter-react-v5/issues).

Can be closed here in my oppinion.
