### ISSUE TITLE
Admin 3.3.9 not possible to change Host with Chrome/Safari at IPAD Air 2 (IOS 11.3)

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#243]
Can‘t select another Host at IPAD (IOS11.3) with Chrome or Safari Browser.

Select Window opens but it‘s not possible to select another Host.

![3653647c-e577-46e3-ac18-61cd83925135](https://user-images.githubusercontent.com/33424168/38748367-2286f6e8-3f4e-11e8-9cc7-4271ff35d95c.png)

**Comment by GermanBluefox** [comment]
Please retest with 3.4.2

**Comment by wendy2702** [comment]
Solved with 3.4.2
