### ISSUE TITLE
[bug]: Sometimes wrong ts-value with comma in the state

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#2430]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When I set the state with a javascript program the ts-value is displayed wrong in the value column.
![image](https://github.com/ioBroker/ioBroker.admin/assets/84818934/a9428f76-620d-4014-a7a8-d52f5a118fa5)

The value which is displayed in the log from the program is right.
```
script.js.ENTWICKLUNG.awattar: 1712867043000
```

### To Reproduce

https://forum.iobroker.net/topic/73946/javascript-adapter-8-0-0/28

Program
```
let url = 'https://api.awattar.de/v1/marketdata';
getData(url);
function getData(url){
    // Daten ab der aktuellen Stunde
    const axios = require('axios');
    axios.get(url)
    .then(function (response) {
        //console.log(response);
        if( response.status === 200){
            // setState(awJsonDP,JSON.stringify(response.data.data), true);
            let dateTS = new Date(response.headers.date).getTime();
            let date   = formatDate(dateTS,'DD.MM.YYYY hh:mm:ss')
            // console.log(new Date(date).getTime());
            console.log(dateTS)
            // console.log(date);
            setStateAsync(awUpdateTimeTSDP,dateTS,true);
            setStateAsync(awUpdateTimeDP,date,true);
            // data -> hours
            // setDataToHours(response.data.data);
            // cheapestHours(response.data.data);
        }
    })
    .catch(function (error) {
        console.log(error);
    })
    .finally(function () {
        // always executed
    });
 
}
 
```

### Expected behavior

Display right value

### Screenshots & Logfiles

Object data
![image](https://github.com/ioBroker/ioBroker.admin/assets/84818934/9628d894-f05e-4241-b400-4c40a33d65a3)

### Adapter version

6.17.3

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

debian as lxc on proxmox

**Comment by Feuer-sturm** [comment]
@mcuiobroker please check with current beta version 6.17.13 if this issue can be closed

**Comment by mcuiobroker** [comment]
Thanks. Its ok.
