### ISSUE TITLE
[enhancement]: Make details at host tab more prominent

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2431]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

It took a long time to detect that after clicking at the host name at tab host the detail infomation is displayed:

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/b08516f6-e82b-48ec-be84-c2068e953a6c)

I assume that many user do not even kow that they can get infos this way

### Description

I would suggest 

- to make it more clearly that there is a possibility to expand the display by clicking at the host name
or
- to expand the display per default

Exapnding per default should be OK as most users will have one or two hosts which will fit on the screen easily (up to three should be OK without scrolling) Eventually only the first host (master host) could be expandid.

**Comment by Apollon77** [comment]
Maybe a "arrow right" when closed and arrow down when extended would also be an idea? SO as it it usually done with extendable/collapsable elements?

**Comment by Feuer-sturm** [comment]
admin 6.17.13 link is implemented -> ok

@GermanBluefox Do you plan to implement @Apollon77 suggestion?

**Comment by foxriver76** [comment]
I would also say the suggestion by Apollon is more preferable, the blinking is a bit lets call it fancy^
