### ISSUE TITLE
Objekt Baumstruktur wird nicht mehr aktualisiert

### ISSUE THREAD

**Issue by Norb1204** [ioBroker/ioBroker.admin#2432]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ab der Version 6.17.x wird die Objekt Baumstruktur nicht mehr aktualisiert.

### To Reproduce

Wenn ich z.B. ein Verzeichnis oder Datenpunkt erzeuge im Stammordner für Benutzerobjekte via JavaScript, werden diese nicht in Objekte angezeigt. Erst wenn ich den Browser aktualisiere werden diese angezeigt.
Beim löschen von Datenpunkten oder Verzeichnisse im Objekt Fenster das gleiche, sie werden nicht mehr aktualisiert.
Mit der Version 6.15.2 funktioniert das noch.

### Expected behavior

Aktualisierung

### Screenshots & Logfiles

nicht notwendig

### Adapter version

6.17.x

### js-controller version

5.0.19

### Node version

v18.20.1

### Operating system

Pi 4

**Comment by mattreim** [comment]
Ich habe das gleiche Aktualisierungsproblem.

**Comment by AlfredSch** [comment]
Bei mir funktionier die Aktualisierung auch nicht mehr, muss Seite neu aufrufen um die Änderung zu sehen.

**Comment by Norb1204** [comment]
mit der neuen Version 6.17.5 sieht das gut aus bei mir, kann das einer bestätigen?
