### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by ceebo2022** [ioBroker/ioBroker.admin#2434]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

console.ts:40 ChunkLoadError: Loading chunk 9525 failed.
(error: http://172.16.0.10:8081/static/js/9525.2aa39fb4.chunk.js)
    at t.f.j (jsonp chunk loading:27:18)
    at ensure chunk:6:25
    at Array.reduce (<anonymous>)
    at t.e (ensure chunk:5:56)
    at App.jsx:91:34
    at P (react.production.min.js:18:161)
    at Ei (react-dom.production.min.js:291:292)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at ss (react-dom.production.min.js:273:245)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:267:273

### To Reproduce

Load Website

### Expected behavior

Website will be shown correctly

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/110699657/2166369f-50f8-43f4-b8a0-5225abb3fef8)

### Adapter version

Admin: 6.13.16

### js-controller version

18.20.2

### Node version

10.5.0

### Operating system

Ubuntu on Intel Atom Board

**Comment by GermanBluefox** [comment]
at least in 6.17.6 fixed

**Comment by Feuer-sturm** [comment]
@ceebo2022 Can you please check with 6.17.6?

**Comment by ceebo2022** [comment]
@Feuer-sturm I will do, when I'm back at home. ;)

**Comment by fL4sH3r** [comment]
@GermanBluefox : I have the same Problem "ERROR in GUI"  with version 6.17.6.
![image](https://github.com/ioBroker/ioBroker.admin/assets/97987283/369e010d-7e96-48ce-8cbe-9a5d301886be)

**Comment by Feuer-sturm** [comment]
@fL4sH3r what did you do to trigger the issue?

**Comment by fL4sH3r** [comment]
> @fL4sH3r what did you do to trigger the issue?

I wanted to change the value of a data point.

**Comment by GermanBluefox** [comment]
duplicate to https://github.com/ioBroker/ioBroker.admin/issues/2443
