### ISSUE TITLE
[bug]: Typ Error failed to execute

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#2437]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim aktualisieren vom Admin kommt immer die im Screenshot ersichtliche Meldung.
Das Update läuft aber dann durch.

### To Reproduce

Run Update vom Admin

### Expected behavior

Meldung entfernen

### Screenshots & Logfiles

![Screenshot (669)](https://github.com/ioBroker/ioBroker.admin/assets/41079106/48d07f18-788c-4600-b052-a0614147711a)
![Screenshot (667)](https://github.com/ioBroker/ioBroker.admin/assets/41079106/c30458c1-c606-45eb-a3f3-7a8a159cfd95)

https://forum.iobroker.net/topic/74073/fehlermeldung-beim-update-vom-admin?_=1713533150814

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

Windows

**Comment by raschy** [comment]
Mercy for this.

**Comment by mcm1957** [comment]
Obige Fehlermeldung kam beim Update 6.17.6 aud 6.17.7 ausgelöst via Admin UI Tab Adapters

**Comment by Feuer-sturm** [comment]
@sigi2345 please check with current admin v6.17.13 if this issue can be closed
