### ISSUE TITLE
[bug]: "states": {...} werden nicht angezeigt

### ISSUE THREAD

**Issue by Dirk-Peter-md** [ioBroker/ioBroker.admin#2439]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ab der Version des Admin 6.17.5 werden unter Objekte die states: nicht mehr angezeigt.
`{
  "type": "state",
  "common": {
    "role": "state",
    "name": "FixDay => start on a fixed day",
    "type": "number",
    "min": 0,
    "max": 7,
    "states": {
      "0": "Sun",
      "1": "Mon",
      "2": "Tue",
      "3": "Wed",
      "4": "Thur",
      "5": "Fri",
      "6": "Sat",
      "7": "off"
    },
    "read": true,
    "write": false,
    "def": 7
  },
  "native": {},
  "from": "system.adapter.sprinklecontrol.0",
  "user": "system.user.admin",
  "ts": 1685880510907,
  "_id": "sprinklecontrol.0.sprinkle.FixDay.actualSoilMoisture",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

![Screenshot 2024-04-19 184457](https://github.com/ioBroker/ioBroker.admin/assets/52133172/b2d5fd2a-56e2-4465-b2f3-727b4cddb3f7)

Bisher sah es immer so aus:

![Screenshot 2024-04-19 185129](https://github.com/ioBroker/ioBroker.admin/assets/52133172/c1affd09-3570-4d04-9993-1e8b95415420)

### To Reproduce

Anzeige unter Objekte

### Expected behavior

states sollten angezeigt werden

### Screenshots & Logfiles

![Screenshot 2024-04-19 184457](https://github.com/ioBroker/ioBroker.admin/assets/52133172/3ed7d7a7-2f93-41a1-ac7a-dd5453ba9cc1)

### Adapter version

sprinklecontrol 0.2..13

### js-controller version

5.0.19

### Node version

v18.17.1

### Operating system

pve mit Ubuntu 20.04.6 LTS (GNU/Linux 6.5.11-8-pve x86_64)

**Comment by Diginix** [comment]
Kann ich bestätigen. `common.states {}` wird nicht mehr ausgewertet.

**Comment by Apollon77** [comment]
Which Admin version?

**Comment by Diginix** [comment]
Steht in beiden Kommentaren ;)
6.17.5 und 6.17.6
Kann aber auch schon davor sein. Mir ist es erst durch das Issue hier aufgefallen.

**Comment by Dirk-Peter-md** [comment]
ab 6.17.5 ist der Fehler erst aufgetreten

**Comment by Feuer-sturm** [comment]
@Dirk-Peter-md @Diginix please check with current beta version v6.17.13

**Comment by Dirk-Peter-md** [comment]
### states werden jetzt mit der Version v6.17.13 korrekt angezeigt
![Screenshot 2024-05-24 173112](https://github.com/ioBroker/ioBroker.admin/assets/52133172/8a7e1f17-f29b-4895-9cd2-2198ff31dee0)
