### ISSUE TITLE
[bug]: Name wird in der Objektstruktur verdeckt

### ISSUE THREAD

**Issue by mattreim** [ioBroker/ioBroker.admin#2440]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Hallo,
in der Objektstruktur wird der Name verdeckt. Erst mit einem Zoomfaktor kleiner 100% wird er wieder sichtbar.

### To Reproduce

1. ioBroker starten
2. Objekte selektieren -> Ergebnis

### Expected behavior

Name sichtbar bei Standard-Zoomfaktor

### Screenshots & Logfiles

Zoom: 100%
![iob_Objektstruktur_100%](https://github.com/ioBroker/ioBroker.admin/assets/80219712/21422744-5921-42d2-86ae-205c1559e240)

Zoom: 90%
![iob_Objektstruktur_90%](https://github.com/ioBroker/ioBroker.admin/assets/80219712/7f1d1f45-7fea-4d06-a09c-2a3185598884)

### Adapter version

7.2.6

### js-controller version

7.0.1

### Node version

20.18.0

### Operating system

Armbian Bookworm

### Additional context

Browser: Google Chrome v130.0.6723.70

Bildschirmauflösung:
![Bildschirmauflösung](https://github.com/ioBroker/ioBroker.admin/assets/80219712/581385ed-9066-40e9-90ef-99c03cdce07b)

**Comment by Apollon77** [comment]
Did you tried to change the column size? I just assume that tis is the automatic sizing based on the available width of the window

**Comment by mattreim** [comment]
It always resets itself after a restart.
