### ISSUE TITLE
Using passwords with double quote (") causes trouble while configuring adapters

### ISSUE THREAD

**Issue by mxgross** [ioBroker/ioBroker.admin#2441]
Hi and thanks for all your work here!

It seems like the jsonConfig from ioBroker does not handle passwords with double quotes (and maybe other special chars) well.

During configuring of the Dyson adapter I had an issue but the lead me to the ioBroker projekt: See [https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/259](https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/259)

It is ja TypeScript/JavaScript error that appears in Chrome Webdeveloper Console after I want to save my user credentials for an adapter:
`console.ts:40 Cannot parse json data: { "email": "mymail@xyz.com", "password": "<MyPwContains|;,^=">" , "country": "DE", "locale": "undefined"}`
For less technical people not looking in the web console of their browser, the login inside the (Dyson) adapter just won't work without seeing why.

Solution ideas: Either handle the password field different, so that any special char is handled right
Or: Bring these kind of messages to the frontend so that a user has a chance to see that he should select a different password for his (cloud)service, before any ioBroker adapter can access it.

Thanks

**Comment by Apollon77** [comment]
@mxgross With exactly which action this error happens?

Because when it happens with a sendTothen it might be an issue there liek https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/master/admin/jsonConfig.json#L151 (also @Grizzelbee) but yes the question is (@foxriver76  @GermanBluefox ) how the adapter dev should/can escape such sendTo Strings correct when they coukd contain relevant special chars correctly?

**Comment by mcm1957** [comment]
Please report versions involved

admin
js-controller
dysonairpurifyer
node

A quick check with jsonConfig-demo looks like everything is working normally

**Comment by mcm1957** [comment]
@Apollon77 

As far as I checked jsonConfig of dysonairouirifier it constructs a json to be used for sendTo. Within this json it uses the password text as entered by the user. So a " within the password causes an invalid json to be created.

 "jsonData": "{ \"email\": \"${data.email}\", \"password\": \"${data.Password}\" , \"country\": \"${data.country}\", \"locale\": \"${data.locale}\"}",

https://github.com/Grizzelbee/ioBroker.dysonairpurifier/blob/8b05bf05824d8d952c8e6fb690764c7a92c11183/admin/jsonConfig.json#L151

I would NOT consider this an issue auf admin adapter.

**Comment by Apollon77** [comment]
> I would NOT consider this an issue auf admin adapter.

it is ... and when a more generic one with the jsonconfig "sendto json strings" ... the values are included as is ... but they might need to be escaped in jsondata else they give such errors

**Comment by mcm1957** [comment]
Youre right. The json defined at jsonConfig is built inside admin code based on definition and varaibale content and not ad adapter code level. So there is the possibility to escape special characters within varaibles there. In addition the opposit direction (sending data from adpater code to config ui varaibles) must be unescaped too.

**Comment by Feuer-sturm** [comment]
@mxgross please check with current beta version
