### ISSUE TITLE
OS information on "Hosts" page incorrect

### ISSUE THREAD

**Issue by werner256** [ioBroker/ioBroker.admin#245]
![unbenannt](https://user-images.githubusercontent.com/36113944/38794568-d306be32-4155-11e8-84f7-de0c5aeff308.PNG)
Shows "win32" but in fact is win64.

**Comment by Apollon77** [comment]
In nodejs windows is always win32, the architecture could be used to decide between x86 and x64, so basically "as desdigned" :-)

**Comment by werner256** [comment]
Not sure if I understand this correctly (in fact, I don't). Actually, there are installers for both x86 and x64 versions of node.js (whatever the difference may be) and it gave me some troubles as a accidently installed the 32-bit version on my 64-bit windows (node.js installed just fine and without warning, but the node.js apps refused to run as service).

**Comment by GermanBluefox** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/4582016/39143827-43c7db4a-472f-11e8-9bfc-06e76339bd78.png)
