### ISSUE TITLE
[bug]: Notifications unreadable due to colour issue

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2451]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

The notification test is written in white on grey background. 
See screenshot

### To Reproduce

1. Use notificationmanger to register a notification (Memory Warning in my case)
2. Display the notification at admin 
3. See result provided as screenshot

### Expected behavior

Readable test :-)

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/259b59c2-eb25-4c39-af94-01e9626c06a3)

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

v18.20.2

### Operating system

win32

**Comment by Feuer-sturm** [comment]
@mcm1957 please check with current version v6.17.13

**Comment by mcm1957** [comment]
is OK now

![image](https://github.com/ioBroker/ioBroker.admin/assets/28575778/68c0796f-3236-4a34-b8da-1c904fa6bfb2)
