### ISSUE TITLE
Darstellungsfehler in benutzerdefinierten Einstellungen

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#2456]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

nach dem admin update keine konfiguration mehr möglich in den benutzerdefinierten Einstellungen(Zahnrad)

### To Reproduce

.

### Expected behavior

konfigurierbar

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/41550245/3449f7cb-b6ca-4a3f-b340-2a48e67419e8)

### Adapter version

6.17.8

### js-controller version

5.0.19

### Node version

18.20.2

### Operating system

docker image 9.1.2

**Comment by GermanBluefox** [comment]
@mcm1957 , @Feuer-sturm und andere: Kann jemand das reproduzieren?

**Comment by crunchip77** [comment]
Nachtrag
mit v6.17.7 selbe Fehler
mit v6.17.6 funktioniert alles

**Comment by mcm1957** [comment]
> @mcm1957 , @Feuer-sturm und andere: Kann jemand das reproduzieren?

Bug ist bei mir reproduzierbar.

Mit 6.17.7 passiet beim Anklicken von Aktiviert nichts
Mit 6.17.6 kommen die Einstallungen.
Zum Test ha ich den History Adapter verwendet.

**Comment by crunchip77** [comment]
funktioniert mit v6.17.11 wieder
