### ISSUE TITLE
[bug]: Error in GUI! - Tab-Backup

### ISSUE THREAD

**Issue by jkret1966** [ioBroker/ioBroker.admin#2457]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

vermutlich nach dem Update des Adapters BackItUp auf Version 2.11.0 funktioniert der Tab Backup nicht mehr und es kommt die Meldung Error in GUI!
Danach habe ich die Node-Version auf 18.20.2 und js-controll auf 5.0.19 aktualisiert, aber der Fehler bleibt.

### To Reproduce

http://192.168.xxx.yy:8081/#tab-backitup-0
![image](https://github.com/ioBroker/ioBroker.admin/assets/57103858/c668f7ce-4ad8-4a90-a578-7b43646ec786)

### Expected behavior

Fehlerursache??

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/57103858/8333f633-bcb3-4be7-822e-4a78e18c7bde);
![image](https://github.com/ioBroker/ioBroker.admin/assets/57103858/175ab42a-a0d3-4548-97e9-20d0be216340);
![image](https://github.com/ioBroker/ioBroker.admin/assets/57103858/ae26b4ff-9dc2-4001-8ed5-6f5e2b29980b);

### Adapter version

2.11.0

### js-controller version

5.0.19

### Node version

 v18.20.2

### Operating system

linux

**Comment by mcm1957** [comment]
Looks like duplicate of https://github.com/ioBroker/ioBroker.admin/issues/2455
