### ISSUE TITLE
Adapter versions show "npm error"

### ISSUE THREAD

**Issue by werner256** [ioBroker/ioBroker.admin#246]
When repository is set to "online", all Adapters on "Adapters" page show "npm error" as installed version. When I change repository to "latest", version numbers are displayed.
online="https://raw.githubusercontent.com/ioBroker/ioBroker.repositories/master/sources-dist.json"
latest="http://download.iobroker.net/sources-dist-latest.json"
Are the repository-links maintained automatically?
![unbenannt2](https://user-images.githubusercontent.com/36113944/38795012-373f267c-4157-11e8-9f9e-c76d428bcf13.PNG)

**Comment by GermanBluefox** [comment]
It can happen, if you use online.
Your system has problem with stable connect to npm. Please use latest or
default if problem stays.

пн, 16 апр. 2018 г., 9:21 Werner Schieber <notifications@github.com>:

**Comment by werner256** [comment]
Thanks a lot for your answer. I will ignore the problem and stay with "latest".
