### ISSUE TITLE
[bug]: Error in Gui!

### ISSUE THREAD

**Issue by Norb1204** [ioBroker/ioBroker.admin#2460]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin Gui Crash when i try to open value
<img width="528" alt="image" src="https://github.com/ioBroker/ioBroker.admin/assets/132662785/09e84fe6-e8d2-47e3-b013-f883915fd61d">

### To Reproduce

ka

### Expected behavior

 ka

### Screenshots & Logfiles

<img width="1245" alt="image" src="https://github.com/ioBroker/ioBroker.admin/assets/132662785/779ef471-c7bb-47e5-ac33-7a3073ce85dc">

Log
error: admin.0 (763) Cannot find view "system" for search "instance" : Connection is closed.

### Adapter version

6.17.7

### js-controller version

 5.0.19

### Node version

v18.20.2

### Operating system

debian 10, same in debian 12

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/2443
