### ISSUE TITLE
allow text fields in jsonConfig without "X" at the end - similar to materialize [enhancement]: 

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.admin#2464]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

While changing from materialize to jsonConfig all text input fields have an "X" at the end. 
Compared to materialize this is not looking nice:

### Description

Please add an attribute to jsonConfig for text-fields to avoid the "X" entry.

### Additional context

jsonConfig:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/36480251/81b7af2c-e867-4e4e-ac32-64b7d570065a)

materialize:
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/36480251/3e1b94ea-7893-4ff8-a367-7cf47d2073ff)

**Comment by mcm1957** [comment]
Maybe the default should be adjusted too
Or the size / appearance of the 'x' should be adjusted.

In general one feature of jsonConfig is that UI is displayed somehow constistent over mutliple adapters. Too much variants will eventually disturb this goal and result in questins "Clear button missing".

I confirm, that the X is not optimal at black design. But I think we should check what style guide we want.

(In addtion I wonder why the numeric fields seem to be text fields ...)

**Comment by tp1de** [comment]
> (In addtion I wonder why the numeric fields seem to be text fields ...)

These fields are hex numbers not decimal and can contain letters as well.

**Comment by tp1de** [comment]
> you can use `noClearButton` as true to hide the clear button from 6.17.13

Thanks a lot. I will finally test when 6.17.13 is released.
With version 12 it is already working (adapter config dialog) but with warnings about invalid jsonConfig within log.

**Comment by tp1de** [comment]
Even with 6.17.3 the warning message within log exists: _ems-esp has an invalid jsonConfig_

**Comment by tp1de** [comment]
And I would recommend to set noClearButton as default without adding this attribute explicitly.

**Comment by mcm1957** [comment]
> Even with 6.17.13 the warning message within log exists:
> 
> `ems-esp has an invalid jsonConfig: [{"instancePath":"/items/tab-ems-esp/items/ems_modulation","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"noClearButton"},"message":"must NOT have additional properties"},{"instancePath":"/items/tab-ems-esp/items/ems_modulation","schemaPath":"#/patternProperties/%5E.%2B/allOf/21/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/tab-ems-esp","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

The new attribute seems to be missing from schema.
Please open a Issue here:
https://github.com/ioBroker/adapter-react-v5/issues/new?assignees=foxriver76&labels=schema+%3Abook%3A&projects=&template=schema.yml&title=%5BjsonConfig%5D%3A+
