### ISSUE TITLE
[bug]: Don´t remember instance name

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.admin#2465]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

After installing an adapter update via the npm tab of the admin ui, the custom instance name field in the instance tab is reseted. As a result, the assignment that was entered is missing after an update.

### To Reproduce

1. creat multipel instances of an adapter
2. update via npm tab of admin ui an adapter with multipel Instances
3. check instance name of the instance tab of admin ui

### Expected behavior

Remember self created name of instance.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/e129b168-0a5f-42ea-a33d-a20d0f4fe42c)

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.20.1

### Operating system

Debbian

**Comment by mcm1957** [comment]
Looks like this issue: https://github.com/ioBroker/ioBroker.js-controller/issues/2604
If correct, this will be fixed with js-controller 6

**Comment by pafade89** [comment]
Oh sorry, yes that is correct. I only looked at the issues in admin.

Thank you =)

**Comment by mcm1957** [comment]
No problem. You cannot scan the whole Internet for duplicates. :-)
I'm happe if 2 identical issues are not listed with a difference of 2 numbers ...

And I just rememberd this issue so I wanted to link them if they are really identical but I did not have time to investigate in detail.
