### ISSUE TITLE
[bug]: Editieren von Alias mit Konvertierungsfunktionen crasht GUI

### ISSUE THREAD

**Issue by m-s-b** [ioBroker/ioBroker.admin#2468]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn mit Admin > 6.17.6 ein Alias angelegt wird funktioniert das weiterhin korrekt. Sobald eine Konvertierungsfunktion genutzt wird lässt sich der Alias nicht mehr editieren da die GUI crasht. Die getestete Konvertierungsfunktion " val / 100" funktioniert mit Downgrade auf Admin 6.17.6 wieder fehlerfrei.

### To Reproduce

1. Alias anlegen / bearbeiten
2. Konvertierung eintragen
3. Erneutes bearbeiten nach speichern crasht GUI

### Expected behavior

Wäre schön wenn Alias-Datenpunkte mit Konvertierung wieder editierbar wären ;-)

### Screenshots & Logfiles

`Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': 
The script at 'https://192.168.10.15:8081/static/js/worker-json.js' failed to load.

TypeError: Cannot read properties of undefined (reading 'common')
    at rt.checkFunction (ObjectBrowserEditObject.tsx:554:105)
    at new rt (ObjectBrowserEditObject.tsx:498:29)
    at ao (react-dom.production.min.js:184:172)
    at zo (react-dom.production.min.js:197:97)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at is (react-dom.production.min.js:272:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273`

### Adapter version

6.17.12

### js-controller version

5.0.19

### Node version

18.20.3

### Operating system

debian 12

**Comment by Diginix** [comment]
Same here with admin 6.17.11
```
bootstrap.jsx:18 iobroker.admin@6.17.11
console.ts:40 [2024-05-23T06:53:59.440Z] Try to connect
:8081/#tab-logs:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
console.ts:40 Stored version: , new version: 6.17.11
console.ts:40 Connected: true
:8081/#tab-objects:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
console.ts:40 + subscribe alias.0.Pixel_Clocks.awtrix_1_power
console.ts:40 + subscribe alias.0.Pixel_Clocks.awtrix_2_power
console.ts:40 + subscribe alias.0.Pixel_Clocks.awtrix_3_power
console.ts:40 + subscribe alias.0.example_state
console.ts:40 + subscribe alias.0.test_number
console.ts:40 > stateChange alias.0.Pixel_Clocks.awtrix_1_power
console.ts:40 > stateChange alias.0.Pixel_Clocks.awtrix_2_power
console.ts:40 > stateChange alias.0.Pixel_Clocks.awtrix_3_power
console.ts:40 > stateChange alias.0.example_state
console.ts:40 > stateChange alias.0.test_number
:8081/#tab-objects:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
ObjectBrowser.tsx:2967 - unsubscribe alias.0.Pixel_Clocks.awtrix_1_power
ObjectBrowser.tsx:2967 - unsubscribe alias.0.Pixel_Clocks.awtrix_2_power
ObjectBrowser.tsx:2967 - unsubscribe alias.0.Pixel_Clocks.awtrix_3_power
ObjectBrowser.tsx:2967 - unsubscribe alias.0.example_state
ObjectBrowser.tsx:2967 - unsubscribe alias.0.test_number
console.ts:40 TypeError: Cannot read properties of undefined (reading 'common')
    at rt.checkFunction (ObjectBrowserEditObject.tsx:555:82)
    at new rt (ObjectBrowserEditObject.tsx:499:30)
    at ao (react-dom.production.min.js:184:172)
    at zo (react-dom.production.min.js:197:97)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at is (react-dom.production.min.js:272:300)
    at Hl (react-dom.production.min.js:127:105)
    at react-dom.production.min.js:266:273
(anonymous) @ console.ts:40
co @ react-dom.production.min.js:188
a.componentDidCatch.t.callback @ react-dom.production.min.js:189
Wa @ react-dom.production.min.js:156
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
yi @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
ws @ react-dom.production.min.js:280
is @ react-dom.production.min.js:272
Hl @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:266
Show 12 more frames
Show less
```

**Comment by Diginix** [comment]
works with 6.17.13

**Comment by m-s-b** [comment]
@GermanBluefox 
Danke, geht wieder.
