### ISSUE TITLE
[enhancement]: improve json validation within jsonConfig

### ISSUE THREAD

**Issue by tp1de** [ioBroker/ioBroker.admin#2470]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

I do have fields within adapter config dialog which requires input to be valid json data:
![image](https://github.com/ioBroker/ioBroker.admin/assets/36480251/6ebc18bb-9a3d-415c-b1b5-2171b90c5a1a)

When item-type is defined as "text", input is displayed in config dialog.
When item-type is defined as "jsonEditor" the input is not displayed, just in the pop-up window when button is pressed.

In both case there is no validation for formally right json content. ("valid json")

### Description

When using "type": "jsonEditor" 

- the content should be displayed (like on type text)
- an "edit" button should open an  editing window
- on closing this editing window a formal check for valid json should take place

**Comment by foxriver76** [comment]
Should now be possible with `validateJson` option, see https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md
