### ISSUE TITLE
[bug]: lastChange show time without 0 lower than 10

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.admin#2474]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

![image](https://github.com/ioBroker/ioBroker.admin/assets/84818934/bfdbd5d2-232f-4323-b9a9-2f5b9f912b47)
if time here minutes lower than 10 -> only shows 2 and not 02.

### To Reproduce

Mouseover the Object Value.

### Expected behavior

Instead of showing 2 -> 02

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/84818934/a84fb609-9bf0-48c6-ac88-99e3f0f38a00)

### Adapter version

6.17.14

### js-controller version

5.0.19

### Node version

20.14.0

### Operating system

lxc Proxmox debian

**Comment by Feuer-sturm** [comment]
@mcuiobroker please check with current beta version

**Comment by mcuiobroker** [comment]
v7.0.7
![image](https://github.com/ioBroker/ioBroker.admin/assets/84818934/2abcdc4b-8014-4bd1-abb3-4283d49693ad)
It's ok. Thanks.
