### ISSUE TITLE
[bug]: Button overlay in "Betriebssystem-Paket-Updates verfügbar"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#2477]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If multiple OS updates are available the button for confirming is at the wrong position:

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25422320/5533493c-309a-44a1-90ea-014e46799496)
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25422320/ec9012dc-49bc-4b9a-9311-31c549963f89)

### To Reproduce

OS needs multiple updates e.g. 10 packages
Check "Betriebssystem-Paket-Updates verfügbar" in host menu

### Expected behavior

Button is under the text and the text is shown correct

### Screenshots & Logfiles

see above

### Adapter version

6.17.14

### js-controller version

6.0.1

### Node version

18.20.3

### Operating system

ubuntu

**Comment by GermanBluefox** [comment]
Please retest it with 7.0.2

**Comment by Feuer-sturm** [comment]
is ok with admin 7.0.7

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/25422320/7888680b-90bd-4fc7-a86c-a265adc6f422)
