### ISSUE TITLE
Unable to accept license without accepting collection of statistics

### ISSUE THREAD

**Issue by SkyLined** [ioBroker/ioBroker.admin#2483]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Background:
While going through "Initial ioBroker setup" after installing, Step 2 involves accepting the license agreement. There is a checkbox at the top of that page that asks if you agree to the collection of anonymous statistics and automatically reporting crashes (see https://github.com/ioBroker/ioBroker.admin/blob/master/packages/admin/src/src/components/Wizard/WizardLicenseTab.jsx#L176). This checkbox must be checked to enable the "AGREE" button.

There are multiple problems with this:
* This checkbox is not related to the license agreement, so it should not be on this page and should certainly not prevent you from accepting the license agreement.
* There is no information about what information is collected, how it is processed and stored, and who has access to this information. The user cannot make an informed decision.
* The page mentions that you can disable this later in settings but doesn't say if statistics or crash reports are send before you get to those settings to disable it again.
* If people are allowed to disable it, they should not be forced to enable it first
* Forcing people to enable this is, IMHO, not ethical.

### To Reproduce

* Install ioBroker
* Goto http://<localhost>:8081
* Go to step 2
* Attempt to accept the license agreement without accepting the collection of usage statistics and crash reports.

### Expected behavior

Allow people to use ioBroker without ever sending usage statistics or crash reports.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/1959110/de1c843e-b944-4d93-8dfd-d09fd5b26665)
* Notice text next to checkbox is red, indicating the box must be checked.
* Notice the text for the checkbox has nothing to do with the license agreement
* Notice the "AGREE" button is greyed out, indicating it cannot be clicked until the box is checked.

### Adapter version

N/A

### js-controller version

N/A

### Node version

N/A

### Operating system

N/A

**Comment by Apollon77** [comment]
Basically you are right - "ethical" might be the wrong word here. The other side is that you install a complete home automation system here for free - there it should be ok to at least share the installation information to us, even if you disable all reporting later on. For now we decided that we want to have it that way. So we decided that crash and statistics reporting is an "opt out" mechanism and not "opt in".

On the page in the settings where you can disable it the information about which data is reported and such is contained

**Comment by GermanBluefox** [comment]
This statistics is critically important for the project development. So it is enabled. But I added the option to show the sent statistics
![image](https://github.com/ioBroker/ioBroker.admin/assets/4582016/a61195db-11d2-4eeb-bc48-42af5574619c)

![image](https://github.com/ioBroker/ioBroker.admin/assets/4582016/42496c52-9de7-42f1-86c7-0952323d6b2b)

**Comment by SkyLined** [comment]
Privacy and control over what the software on your own systems is allowed to do is critically important, statistics is nice to have. I'm sure you do not need 100% of people to report them.

It's a shame that this is your view on privacy: I will not use it or participate in development any further.
