### ISSUE TITLE
[bug]: Bad wording in setup wizard prevents informed decision making

### ISSUE THREAD

**Issue by SkyLined** [ioBroker/ioBroker.admin#2484]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In step 4 of the Initial ioBroker setup, there is a checkbox for "Authentication in Admin" with the text
> Activate the check of password in admin if you plan to access your ioBroker is not in "Demilitarized Zone"
This sentence is not welformed English and does not explain what you are being asked to decide. This prevents the user from making a well informed decision.

### To Reproduce

1. Install ioBroker
2. Goto http://<ip address>:8081
3. Go through steps 1-3
4. At step 4, read the text and try to understand it.

### Expected behavior

I expected a clear and concise description of what happens if I check the checkbox vs what happens if I do not check it.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/1959110/390e4f40-d6ae-4789-a42f-8042ff5ce465)

### Adapter version

N/A

### js-controller version

N/A

### Node version

N/A

### Operating system

N/A

**Comment by mcm1957** [comment]
@SkyLined 
I would suggest to provide a suggestion of the text you would expect.

**Comment by SkyLined** [comment]
I would if I had any clue as to what this means. I looked at `en`, `de` and `nl` version and all of them are equally cryptic to me. Since I cannot understand what this does at all, I am unable to submit a patch or offer a suggestion.

**Comment by SkyLined** [comment]
I am new to the project, so I do not know what this setting is used for. If somebody can tell me where this setting is used in the code, I might be able to figure it out from that code and offer a better explanation.

**Comment by mcm1957** [comment]
'authentication in admin' configures wether you must login to use the admin page or (if not checked) no user/password is required. Login is recommended if your installation is reachable from internet - which is generel not recommended (always use ioBroker cloud or an vpn tunnel).

**Comment by SkyLined** [comment]
@mcm1957 Thanks, that makes it much clearer. I've tried to capture what you've said in a patch. Let me know what you think.
