### ISSUE TITLE
[enhancement]: Input option for number of decimal places for type Number

### ISSUE THREAD

**Issue by RALFISBORN** [ioBroker/ioBroker.admin#2488]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

In my search, I have not currently found a way to specify a fixed number of decimal places for a UserData variable of type Number.

### Description

Ideally, an additional field would be desirable for COMMON in order to enter the input there (similar to MIN, MAX, STEP, etc.).

Alternatively in the OBJECT DATA

**Comment by mcm1957** [comment]
What do you mean with UserData variable?

Do you refer to
- displaying a state value at object view in admin ?
- specify an input field in admin UI using jsonConfig ?
- some other place displaying / allowing to enter a numeric value?

**Comment by RALFISBORN** [comment]
I would like to be able to define the decimal places at the following position:
![image](https://github.com/ioBroker/ioBroker.admin/assets/47441243/05bd24f8-b48f-43db-b4f0-6a5d6b22eeda)

Without additional scripts

**Comment by foxriver76** [comment]
This is something which you would specify in a displaying adapter like vis or vis 2 you can specify this per widget, IMHO in Admin this does not make sense.

**Comment by RALFISBORN** [comment]
This is a pity, because the use case is required in every visualisation option (e.g. VIS, Lovelace) and must be explicitly adapted there each time.

**Comment by GermanBluefox** [comment]
You can create an alias with formula: `Math.round(val * 100) / 100` to round the value
