### ISSUE TITLE
[bug]: In v7.0.1 React components for jsonConfig are not loaded

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#2496]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

With the update to admin 7.0.1, the React components are no longer loaded in the Backitup config.
There is no error log in the console.

### To Reproduce

1. Got to Backitup Config. All configuration options that contain React components are not displayed

### Expected behavior

Display all components

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/39792461/f5a934f8-a6ec-448b-8e81-a8d1efb0cf3e)

### Adapter version

7.0.1

### js-controller version

6.0.1

### Node version

20.14.0

### Operating system

Ubuntu 22.04

**Comment by mcm1957** [comment]
If this error is caused by the a little bit cryptic changelog
```
7.0.1 (2024-06-10)
(bluefox) Because of the breaking change in GUI components, the GUI was updated. Users will see no difference, but developers should check their packages.
...
```
we have a problem. Its not possible that all adapters using react are updated withon a short period.

**Comment by simatec** [comment]
@mcm1957 I think in the case of Backitup, @GermanBluefox has insight. We are currently working together on the switch to react

**Comment by Tronje-the-Falconer** [comment]
I have also a Problem with the js-controller.
I can't install any new adaptor with the admin frontend. I get the error:

"Latest available version of "js-controller" is required, but nothing installed. Please install first "js-controller" and then retry."

Installing an adaptor with console is no Problem

**Comment by mcm1957** [comment]
@Tronje-the-Falconer 
I think this is a seperate issue...

@simatec 
I know - but the error sounds like a genral error. And the releasenotes for admin 7 are cryptic. I do not understand what developers should check whne admin reads: `Because of the breaking change in GUI components, the GUI was updated. Users will see no difference, but developers should check their packages.`

**Comment by GermanBluefox** [comment]
Please retest with 7.0.2

**Comment by simatec** [comment]
With v7.0.2 is OK 👌
