### ISSUE TITLE
[bug]: Telegram: Section missed

### ISSUE THREAD

**Issue by raschy** [ioBroker/ioBroker.admin#2500]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In the Telegram adapter, the information on 'Authenticated users' and the corresponding settings are missing in the instance settings on the 'Messages' page in the lower section.

### To Reproduce

In the adapter settings, page 2

### Expected behavior

look at screenshot.

### Screenshots & Logfiles

![Telegram_Nutzer](https://github.com/ioBroker/ioBroker.admin/assets/75622810/1bc3aec9-2358-4272-840a-43bc7ee5eb9b)

### Adapter version

Admin 7.0.1, Telegram 3.4.0/ 3.4.1

### js-controller version

6.0.4

### Node version

20.14.0

### Operating system

Linux

**Comment by klein0r** [comment]
Related to #2496

**Comment by raschy** [comment]
Yes, seems to be similar with this error. I will wait for a correction - until then continue with Admin 6.x.x

**Comment by GermanBluefox** [comment]
Duplicate
