### ISSUE TITLE
[bug]: Object Explorer can not be opened

### ISSUE THREAD

**Issue by Zefau** [ioBroker/ioBroker.admin#2503]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

>  TypeError: l is undefined
    getObjectName Utils.tsx:156
    onAfterSelect ObjectBrowser.tsx:3028
    loadAllObjects ObjectBrowser.tsx:2975
    expandAllSelected ObjectBrowser.tsx:3011
    loadAllObjects ObjectBrowser.tsx:2975
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14

### To Reproduce

Opening the object explorer fails. Before ioBroker can show any objects the error is thrown.

PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:2900 MHz
Modell:Intel(R) N100
RAM:14 GB
System-Betriebszeit:44 T. 22:32:03
Node.js:v18.20.3
time:1718432644769
timeOffset:-120
NPM:10.8.1
Adapter-Anzahl:624
Datenträgergröße:49.0 GB
Freier Festplattenspeicher:24.8 GB
Aktive Instanzen:34
Pfad:/opt/iobroker/
Betriebszeit:11:58:26
aktiv:true
_nodeCurrent:18.20.3
_nodeNewest:18.20.3
_nodeNewestNext:18.20.3
_npmCurrent:10.8.1
_npmNewest:10.7.0
_npmNewestNext:10.7.0

### Expected behavior

Object Explorer to show

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/14368811/f4edaa1a-4fa1-41a6-866c-2ad401ef3db4)

### Adapter version

v7.0.1

### js-controller version

v6.0.4

### Node version

v18.20.3

### Operating system

Linux

**Comment by Dreistein19** [comment]
same here

**Comment by Dreistein19** [comment]
Same Here

**Comment by Dreistein19** [comment]
`
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.19.17:8081
iobroker.admin@7.0.1 bootstrap.tsx:25:8
[2024-06-17T18:03:18.735Z] Try to connect console.ts:40:19
Cannot override navigator.credentials:  TypeError: undefined is not a non-null object
    <anonymous> moz-extension://3927ca12-d5a8-4896-93c6-f1dc21ba1cb4/content/passkeys.js:201
    <anonymous> moz-extension://3927ca12-d5a8-4896-93c6-f1dc21ba1cb4/content/passkeys.js:210
console.ts:40:19
Stored version: , new version: 7.0.1 console.ts:40:19
Connected: true console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.batteryAutonomy console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.batteryAvailableEnergy console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.batteryCapacity console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.batteryLevel console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.chargingRemainingTime console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.chargingStatus console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.plugStatus console.ts:40:19
+ subscribe renault.0.VF1AG000765757892.battery-status.timestamp console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.batteryAutonomy console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.batteryAvailableEnergy console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.batteryCapacity console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.batteryLevel console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.chargingRemainingTime console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.chargingStatus console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.plugStatus console.ts:40:19
- unsubscribe renault.0.VF1AG000765757892.battery-status.timestamp console.ts:40:19
TypeError: l is undefined
    getObjectName Utils.tsx:156
    onAfterSelect ObjectBrowser.tsx:3028
    loadAllObjects ObjectBrowser.tsx:2975
    expandAllSelected ObjectBrowser.tsx:3011
    loadAllObjects ObjectBrowser.tsx:2975
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.batteryAutonomy console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.batteryAvailableEnergy console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.batteryCapacity console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.batteryLevel console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.chargingRemainingTime console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.chargingStatus console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.plugStatus console.ts:40:19
> stateChange renault.0.VF1AG000765757892.battery-status.timestamp console.ts:40:19


`

**Comment by GermanBluefox** [comment]
Fixed in 7.0.2

**Comment by Feuer-sturm** [comment]
@Zefau  @Dreistein19 please check with current beta version

**Comment by Zefau** [comment]
Works for me
