### ISSUE TITLE
Admin 3.3.9 Dropdown-Menü for „Installation from GIT“ not working at IPAD

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#251]
The dropdown menu for „Installation from GIT“ is not working. I‘m not able to scroll down at IPAD using SAFARI/CHROME. As soon as i try to scroll down —> the dropdown window will be closed.

![81c6b067-7140-4d75-b32b-0404aaa660b3](https://user-images.githubusercontent.com/33424168/39147442-e10eafaa-4739-11e8-81ee-dff8ca844240.png)

**Comment by BuZZy1337** [comment]
Fixed with PR https://github.com/ioBroker/ioBroker.admin/pull/262 :relaxed:

**Comment by GermanBluefox** [comment]
Please retest with 3.4.2

**Comment by wendy2702** [comment]
Problem is solved with 3.4.2
