### ISSUE TITLE
[bug]: Setting the restart times

### ISSUE THREAD

**Issue by raschy** [ioBroker/ioBroker.admin#2512]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When setting the restart times of an adapter, the following selection is offered in the "Weekdays" tab: sc_every_dow. sc_everyN_do and sc_specific_dow.
I assume that the German translation has not yet been completed here (and also in the following selection dialog).

### To Reproduce

Setting the restart times for any adapter.

### Expected behavior

German texts throughout

### Screenshots & Logfiles

![issue_Admin_Cron-Telegram](https://github.com/ioBroker/ioBroker.admin/assets/75622810/33413269-25ed-4af5-bebc-edf39fa8def4)

### Adapter version

v6.16.14

### js-controller version

6.0.5

### Node version

20.15.0

### Operating system

Linux

**Comment by Feuer-sturm** [comment]
@raschy please check with current beta version

**Comment by raschy** [comment]
With Admin 7.0.6 and 7.0.7 this is in the correct language.
