### ISSUE TITLE
[bug]: installation of vis-2 widgets from github doesn't work

### ISSUE THREAD

**Issue by oweitman** [ioBroker/ioBroker.admin#2513]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I don't know if admin or js-controller is the right place to create the issue.

no build process is started and the build files are usually not included in github.
they are then missing and cannot be uploaded to vis-2 so that the widgets are available there

### To Reproduce

installation of iobroker.vis-2-widgets-rssfeed, for example
open vis-2 editor
widgets are not available

### Expected behavior

widgets should be available

### Screenshots & Logfiles

no logfiles

### Adapter version

vis-2 v2.9.64

### js-controller version

v6.13.15

### Node version

v18.17.1

### Operating system

linux/docker

**Comment by oweitman** [comment]
no this is not the right adapter.
not working https://github.com/oweitman/iobroker.vis-2-widgets-rssfeed 
working https://www.npmjs.com/package/iobroker.vis-2-widgets-rssfeed?activeTab=readme
atm not available via beta

**Comment by mcm1957** [comment]
Maybe I'm wrong - but either ALL files required for an installation must be present at github if an installation from github should work. Otherwise a dev could decide to build all or some files during deploy step and provide those files only at npm package. In the later case attribiute common.nogit must be set to true.

@oweitman Which build step do you expect to be started during installation?

@Apollon77 
Please let me know if I'm complezly incorrect. I hiold back stable release of rssfeed until its know whther some adaptions at adapter are required or a js-controller bug exists. (amdin should not be involved anyway as i.e. Installations via cli should behave identical to installs using admin )

**Comment by mcm1957** [comment]
> no this is not the right adapter. the mentioned rssfeed 2.9.7 contains the logic and the vis-1 widgets
> 
> this is the right adapter not working https://github.com/oweitman/iobroker.vis-2-widgets-rssfeed working https://www.npmjs.com/package/iobroker.vis-2-widgets-rssfeed?activeTab=readme atm not available via beta

Ok my fault - so its not relevant fpr rssfeed of course

**Comment by oweitman** [comment]
> Maybe I'm wrong - but either ALL files required for an installation must be present at github if an installation from github should work. Otherwise a dev could decide to build all or some files during deploy step and provide those files only at npm package. In the later case attribiute common.nogit must be set to true.

for the react/typscript related developments, only the source files are included on github. the preparation of the source files into corresponding executable JavaScript files is then done via the ts transpiler or the basic process for react.

this build process is initiated via "npm run build".

the result is then created via npm pack/npm publish (previous process) or via the release script (via github), a package is created and uploaded to npm.

i.e. the build files are included in the npm package and can be installed in iobroker as normal.

it doesn't work just using the button to install directly from github.

this is currently only an edge case, of course, but with increasing development of vis-2 widgets or individual react admins, this will become difficult with (I call it integration testing), as you have to publish an npm package first in each case.

my vis-2 widgets can be run locally and I have tested them extensively, but I wanted to test the installation directly from github, but it didn't work because files were missing.

installation via npm works. but as I said, this means that versions that shouldn't actually be public end up on npm.

> 
> @oweitman Which build step do you expect to be started during installation?
> 
> @Apollon77 Please let me know if I'm complezly incorrect.

the PR for rssfeed has nothing to do directly with the vis-2-widget-rssfeed adapter.
if that is OK for you, please merge

**Comment by mcm1957** [comment]
OK now looked at vis-2 adapter

package.json references the main file 
  "main": "widgets/vis-2-widgets-rssfeed/customWidgets.js",

As this file is not checked in intogithub an github installtion will not work. I'm not aware that npm will start any builds on its own.

The file is store at npm packge as test-and.release workflow contains the reuired build commands.

So either you must perform the build locally and check the files into github (and removed the build from workflow) OR you must set common.nogit to true as this adapter does not allow github installations.

Other vis-2 adapters have choosen to set nogit:true.

In my oppinion this is the intended behavior of npm.

**Comment by mcm1957** [comment]
> for the react/typscript related developments, only the source files are included on github. the preparation of the source files into corresponding executable JavaScript files is then done via the ts transpiler or the basic process for react.
> 
> this build process is initiated via "npm run build".
> 

Its a decision of the developer. Some do the build during npm run release and store them at github. In this case a github installation is possible. Others decide to run npm run build during test-and-release workflow and provide the files at npm only.
In the later case common.nogit must be set to true and no github based installation is possible.

> it doesn't work just using the button to install directly from github.

Thats normal if the build files (compiled files) are not created by npm run release and stored at github. Neitehr admin nor js-controller will trigger a build.

> this is currently only an edge case, of course, but with increasing development of vis-2 widgets or individual react admins, this will become difficult with (I call it integration testing), as you have to publish an npm package first in each case.

No  - you can run npm run build locally too.

> my vis-2 widgets can be run locally and I have tested them extensively, but I wanted to test the installation directly from github, but it didn't work because files were missing.

See above - if the files are not present at github a github installation is not possible.

You can build files locally using npm run build and install from local directory too as far as I know.

**Comment by oweitman** [comment]
no tag is currently created and no package is created via the release script. I am currently doing this manually from the computer because the test fails for reasons that are still unknown. locally it is due to timing errors in the tests; on github it is because the widgets are also not available in the editor.

I still have to research this separately though. the available know-how on this from me and from others is very limited (see also reaction to vis-2 question in discord)

no idea if the "install from github" button only targets tags. it used to work without the existence of a tag.

**Comment by oweitman** [comment]
how do I do the "no git" tag?

**Comment by mcm1957** [comment]
> no tag is currently created and no package is created via the release script. I am currently doing this manually from the computer because the test fails for reasons that are still unknown. locally it is due to timing errors in the tests; on github it is because the widgets are also not available in the editor.

releasenotes plugin is missing. Not sure wther this could cause the problem.  Otherwise releasescript config looks good. Any errors during npm run release?

> I still have to research this separately though. the available know-how on this from me and from others is very limited (see also reaction to vis-2 question in discord)

I did not see ANY questions at telegram developer channels. So either you use a special discord channel not used by other adapter developers or discord coupling is broken. A package is not created at as long as tests fail - this is the desired behaviour.

> no idea if the "install from github" button only targets tags. it used to work without the existence of a tag.
No - install from github button tries to install from github which is a basic functionality of npm. But of course this requires all files to be present at github.

The nogit attribute blocks github installs for adapter which cannot be installed from github. tis is the case for your vis-2 widgets (like with  other vios-2 widgets)-.

**Comment by mcm1957** [comment]
> how do I do the "no git" tag?

see io-package.json schema: https://github.com/ioBroker/ioBroker.js-controller/blob/0e88061f58602a0f3652062055d0f66e6d85d705/schemas/io-package.json#L1258

Anyway: 
I suggest to switch discussion to telegram developer channel

**Comment by oweitman** [comment]
Solution is to tag with no-git 
that nobody can install a tag release from GitHub

**Comment by Apollon77** [comment]
@oweitman In fact most of the adapters that have build parts commit then also into GitHub so that GitHub installs are possible ... else you should use tghe no-git flag ... correct. Including the build files is kind of convenience for the users and party dev depending how he does "alpha testing" :-)
