### ISSUE TITLE
[bug]: Icons are broken

### ISSUE THREAD

**Issue by pafade89** [ioBroker/ioBroker.admin#2514]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Since version 6.13.16, the icons are missing in the left admin UI menu and for almost all objects.

### To Reproduce

Check the sidebar menu and the objects.

### Expected behavior

Icons are available.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/91e8d796-19cb-493f-880d-a17d256d5108)
![image](https://github.com/ioBroker/ioBroker.admin/assets/113902279/9289afe4-0eb7-4a99-b9b3-382b41702aac)

### Adapter version

7.0.2

### js-controller version

5.0.19

### Node version

20.14.0

### Operating system

Debian

**Comment by GermanBluefox** [comment]
Could it be, that you installed the adapter from git directly?

**Comment by pafade89** [comment]
Hi @GermanBluefox , 
when trying to retrieve the icons, I always receive the following message: "Token unauthorized (404)".

I tried again a day later, and now it’s working.
