### ISSUE TITLE
[bug]: Loginscreen

### ISSUE THREAD

**Issue by Bulls91** [ioBroker/ioBroker.admin#2516]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If you want to Login to IOBroker you got this Screen:

![image](https://github.com/ioBroker/ioBroker.admin/assets/92435210/8f3085fe-3060-484b-89ff-73425f05449c)

It's not possible to Login. Tested with Safari and Chrome.

This Problem exists since Admin **Version 7.0.2**

### To Reproduce

Try to login 

### Expected behavior

its not possible to login because, the boxes where you have to typ in your credentials are hidden.

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/92435210/0ab4b185-eea8-447a-b5a1-d9703d21ed98)

### Adapter version

7.0.2

### js-controller version

6.0.5

### Node version

18.20.3

### Operating system

Debian

**Comment by kago76** [comment]
Same behavior here.
Tested with Chrome, Firefox and Brave. (current versions)

**Comment by arteck** [comment]
![Unbenannt](https://github.com/ioBroker/ioBroker.admin/assets/6681528/f8e555ba-0489-42e5-b490-9fb6c996f156)

js-controller version
5.0.19

Node version
v20.14.0

**Comment by diamand2k22** [comment]
same here....

![image](https://github.com/ioBroker/ioBroker.admin/assets/119601644/6a76f5d7-07cc-409a-8cf4-317fd48c85be)

js-controller version
6.0.5

Node version
v20.15.0

**Comment by sammie76-2** [comment]
Same here. Is there a way to log in with this bug?

**Comment by Menne01** [comment]
Nach dem npm Ugrade auf 7.0.6 wieder normales Verhalten.
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/89869516/3f7d921b-65ba-4761-89de-4d770f5f859c)
