### ISSUE TITLE
[bug]: Admin (7.02) merkt sich nicht mehr die Einstellungen von Farbthema und Log-Level 

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.admin#2517]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin (7.02) merkt sich nicht mehr die Einstellungen von Farbthema und Log-Level 
Standard Farbthema ist immer weiss nach Browser Reload , egal was man vorher eingestellt hat.
Standard Log-Level im Protokoll ist immer Debug nach Browser Reload , egal was man vorher eingestellt hat.

### To Reproduce

.

### Expected behavior

Speichern des zuletzt eingestellten Wertes.

### Screenshots & Logfiles

.

### Adapter version

7.02

### js-controller version

6.05

### Node version

20.5.1

### Operating system

debian

**Comment by Diginix** [comment]
Loglevel (warn) as well as theme (dark) remains as set for me after browser reload.
admin 7.0.2
js-controller 6.0.5
nodejs 20.15.0

**Comment by SurfGargano** [comment]
Hängt wohl mit Synchronisierung der Admin Browser zusammen. Wenn ich die ausschalte, merkt er sich die Einstellungen.
Sobald ich 'Einstellung dieses Browsers' oder 'Einstellung anderer Browser' verwende, nimmt er immer White-Mode und Debug-Level

**Comment by Diginix** [comment]
Stimmt, wenn ich die aktiviere bleibt der Loglevel Debug, aber Theme bleibt das gewählte. Mein System ist aber global dark. Vllt nutzt der Admin das ja als Quelle.

**Comment by Feuer-sturm** [comment]
@SurfGargano @Diginix please check with current beta version

**Comment by Diginix** [comment]
works fine with 7.0.7

**Comment by SurfGargano** [comment]
works as espected now
