### ISSUE TITLE
[bug]: after installing an adapter from GIT, or doing an "upload" for an adapter, all action-icons (buttons) remain greyed-out (inactive)

### ISSUE THREAD

**Issue by jlegen** [ioBroker/ioBroker.admin#2518]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

after installation from GIT (or doing an "upload" of adapter files) using the icon-buttons on the right, all those icon-buttons are set to inactive (greyed out) afterwards. 
Gets re-activated when some screen update is triggered (changing section, checking for adapter updates, toggle filter etc.)

### To Reproduce

- chose "install from GIT", "upload adapter files" (probably aynthing on the actions on the right might trigger this)
- do anything (install)

### Expected behavior

action-icons should stay active...

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24507951/e8f191de-f1ca-47e7-a520-f82e17a5f6f4)

### Adapter version

7.0.2

### js-controller version

5.x

### Node version

18.x

### Operating system

Alma8

**Comment by GermanBluefox** [comment]
Are you installing admin adapter from git or any other?

**Comment by jlegen** [comment]
...no, just updated using the regular update procedure in "adapters" section... (= "official" 7.0.2)
Was using firefox here...

**Comment by GermanBluefox** [comment]
Corrected in 7.0.16
