### ISSUE TITLE
[bug]: badge for"errors" in protocol view is off

### ISSUE THREAD

**Issue by jlegen** [ioBroker/ioBroker.admin#2519]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

 badge for"errors" in protocol view is off (latest Firefox)

### To Reproduce

enter protocol view, check badge on error filter toggle

### Expected behavior

showing error number

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24507951/038679dd-7ddf-4639-9f37-98c739e6ccc5)

### Adapter version

7.0.2

### js-controller version

5.x

### Node version

18.x

### Operating system

Alma8

**Comment by Feuer-sturm** [comment]
@jlegen please check with current beta version

**Comment by jlegen** [comment]
looks good now! :-)
