### ISSUE TITLE
Drag and Drop funktioniert nicht in Tab Aufzählungen

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#252]
Habe versucht mit Safari, Firefox und Chrome mit Drag and Drop States zu einer Gruppe hinzuzufügen.
Einmal hat es funktioniert. Ansonsten nicht.
Mir ist nicht klar, warum es einmal funktioniert hat.

PS: es scheint relativ unzuverlässig in der Listenansicht zu funktionieren.

**Comment by GermanBluefox** [comment]
Ist das Problem in beiden Ansichten (Listenansicht, Panelansicht) reproduzierbar?
Browser? Apple/Windows/ Linux?

**Comment by Marty56** [comment]
Ich habe es nur unter MacOS getestet.
In der Panelansicht geht es überhaupt nicht, in der Listenansicht mehr schlecht als recht.
Browser hatte ich oben schon angegeben.

**Comment by Apollon77** [comment]
Bug? Enhancemenst?

**Comment by JackWolfskin42** [comment]
Unter Windows/Chrome das gleiche Verhalten - einmal gehts , dann nicht mehr ...

**Comment by GermanBluefox** [comment]
> Unter Windows/Chrome das gleiche Verhalten - einmal gehts , dann nicht mehr ...

3.4.4 ??

**Comment by GermanBluefox** [comment]
Please test with 3.4.4

**Comment by JackWolfskin42** [comment]
Ja,, der Fehler tritt bei mir unter 3.4.4 auf

**Comment by GermanBluefox** [comment]
With Firefox I could reproduce

**Comment by GermanBluefox** [comment]
PLease retest with 3.5.0

**Comment by Marty56** [comment]
Ich kann leider nicht testen, weil ich nicht zuhause bin. Sorry

**Comment by Jey-Cee** [comment]
Bug ist noch da. Manche Objekte liesen sich nicht hinzufügen ein reload des Admin im Bowser hat abhilfe geschaffen.
Ubuntu, Chromium, Admin 3.5.0

**Comment by Jey-Cee** [comment]
Neue Hinweise: 
- 'Phantom' Objekte  lassen sich nicht hinzufügen, gemeint sind Objekte die ohne Attribute als Parent Obejekte angelegt werden. 
- Objekte der Untersten ebene (adapter.0) lassen sich auch dann nicht hinzufügen auch wenn sie einen Typ haben, Beispiel Xbox Adapter

**Comment by wendy2702** [comment]
@Jey-Cee : Ist der Bug noch da?
