### ISSUE TITLE
[bug]:  Anmeldefenster ist defekt unter 7.02

### ISSUE THREAD

**Issue by XxJooO** [ioBroker/ioBroker.admin#2520]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Fehler 1. 
In den Hinweisen zur V 7.02 steht extra drin, dass die GUI der ioBroker Oberfläche sich nicht ändert. Das Anmeldefenster ist bei mir allerdings perdu. Ich nutze den aktuellsten Chrome unter LMDE 6.
Ich kann mich nur noch anmelden, da mein Bitwarden glücklicherweise die unsichtbaren Felder ausfüllt.

Fehler 2.
Am Unterrand des nach der Anmeldung erscheinenden Fenster entsteht plötzlich eine Leiste, diese muss ich nach rechts ziehen, um den rechten Rand vollständig zu sehen. Die Übersicht steht immer auf 80%. Somit ist das also kein Problem des Platzes.

### To Reproduce

Alles nach dem Aufruf von ioBroker im Browser  sofort zu sehen

### Expected behavior

Beschrieben ist, dass keine Änderung dre GUI zu erkennen sei...

### Screenshots & Logfiles

Fehler 1.
![image](https://github.com/ioBroker/ioBroker.admin/assets/47712364/9894d064-7411-4b64-aa72-3dfbbf9d3a71)

Fehler 2.
![image](https://github.com/ioBroker/ioBroker.admin/assets/47712364/4431e129-9041-42ed-a15f-5ab588bd3f34)

### Adapter version

7.02

### js-controller version

6.0.5-alpha -0-20240616-xxx

### Node version

18.20.3

### Operating system

Linux LMDE 6

**Comment by Feuer-sturm** [comment]
There is already a fix for issue #2516 in admin 7.0.3
issue closed

**Comment by mcm1957** [comment]
When will 7.0.3 be published?

**Comment by Feuer-sturm** [comment]
@mcm1957 I don't know :) I only see that here is a commit for 7.0.3 https://github.com/ioBroker/ioBroker.admin/commits/master/

**Comment by mcm1957** [comment]
But tests failed ...
https://github.com/ioBroker/ioBroker.admin/actions/runs/9665547608
