### ISSUE TITLE
Problem bei Namensauflsösung

### ISSUE THREAD

**Issue by ManfredHi** [ioBroker/ioBroker.admin#2523]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Seit der Version 6.17.14 habe ich das Problem, dass Icons nicht mehr richtig angezeigt werden.
Ich verwende die TLD .internal. Könnte es sein, dass diese dann als TLD .in aufgelöst wird?
Verwende ich bei mir den Aufruf direkt über die IP-Adresse sind alle Icons vorhanden.

### To Reproduce

https://forum.iobroker.net/topic/75487/admin-v6-17-14-fehlende-icons/25

### Expected behavior

-

### Screenshots & Logfiles

https://forum.iobroker.net/topic/75487/admin-v6-17-14-fehlende-icons/25

### Adapter version

v6.17.14

### js-controller version

 5.0.19

### Node version

v20.15.0

### Operating system

Debian 11

**Comment by mcm1957** [comment]
Some additonal Info:

The assumtion that intern is truncated to in is incorrect for sure.
The file are tried to read from remote-files.iobrober.in :-). This fails due to a missing token ...

More info at forum https://forum.iobroker.net/topic/75487/admin-v6-17-14-fehlende-icons/20
