### ISSUE TITLE
Darstellungsfehler in mobiler Hochformat-Ansicht 

### ISSUE THREAD

**Issue by LastPerfectTobi** [ioBroker/ioBroker.admin#2525]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei Instanzen fehlt in der Hochformat-Ansicht auf dem Handy die grüne/rote Adapterstatus-Anzeige. 

Im Log sind die Schriftgrößen unterschiedlich. 

Iphone 11 im Safari Browser
Siehe Bilder
![IMG_6351](https://github.com/ioBroker/ioBroker.admin/assets/75383507/d6c2a565-d576-4bb1-a48d-c74b91dbaf1a)
![IMG_6350](https://github.com/ioBroker/ioBroker.admin/assets/75383507/61a3100b-832b-4a42-8e7f-93f262d3e23c)

### To Reproduce

Ansicht Instanzen oder Protokoll öffnen

### Expected behavior

Bei den Instanzen der Indikator sichtbar. 

In der Log-Übersicht gleiche Schriftgrößen

### Adapter version

7.0.6

### js-controller version

6

### Node version

20.15.0

### Operating system

Raspian

**Comment by Feuer-sturm** [comment]
@LastPerfectTobi Bitte einmal mit der aktuellen Beta Version >= 7.0.9 testen

**Comment by LastPerfectTobi** [comment]
> @LastPerfectTobi Bitte einmal mit der aktuellen Beta Version >= 7.0.9 testen

Mit 7.0.9 keine Auffälligkeiten bei Instanzen und Log mehr, nur die Buttons für z.B. Settings (Schraubenschlüssel) sind leider nicht mehr in der ersten Ebene. Aber das soll wahrscheinlich so sein. 

Punkt hier kann aber geschlossen werden.
