### ISSUE TITLE
[bug]: null values in jsonConfig breaks adapter config page

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/ioBroker.admin#2527]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If an adapter has a `null` value in it's `jsonConfig.json` the adapter config page will not load since admin 6.17.0.

Example config:
https://github.com/crycode-de/ioBroker.ds18b20/blob/48e5683ae2c6605e462fe05fb032fd2883656341/admin/jsonConfig.json#L82-L93

Related issue: https://github.com/crycode-de/ioBroker.ds18b20/issues/117

Related forum thread: https://forum.iobroker.net/topic/75516/jsonconfig-cannot-parse-json5-config

### To Reproduce

1. Use Admin >= 6.17.0
2. Open Config page of ds18b20 Adapter
3. See the Message `[JsonConfig] Cannot parse json5 config!` and `TypeError: t is null` in console.

### Expected behavior

Adapter config loads loads correctly.

### Screenshots & Logfiles

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24603271/1b7e4cd9-f8ab-4c07-a9ef-d215db175e25)

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/24603271/1185fa95-aca2-42a1-922a-f44482c4e914)

### Adapter version

6.17.14

### js-controller version

5.0.12

### Node version

18.19.0

### Operating system

Ubuntu 22.04 in Proxmox LXC

### Additional context

I've traced the issue down to the `scanForIncludes` function, where the value of a key is checked to be typeof object and the function is called recursively:
https://github.com/ioBroker/ioBroker.admin/blob/3d6414b79bcff87c9d19cbca0ccbd110244b9f70/packages/jsonConfig/src/JsonConfig.tsx#L404-L406

Sadly `typeof null` is also `'object'`. So for a null value the function gets called again and crashed on the first check where `json` will be null.
https://github.com/ioBroker/ioBroker.admin/blob/3d6414b79bcff87c9d19cbca0ccbd110244b9f70/packages/jsonConfig/src/JsonConfig.tsx#L392

A possible solution will be to change
```ts
if (typeof json[keys[k]] === 'object') {
```
to
```ts
if (typeof json[keys[k]] === 'object' && json[keys[k]] !== null) {
```

**Comment by Feuer-sturm** [comment]
@crycode-de Please check with current beta version

**Comment by crycode-de** [comment]
@Feuer-sturm Seems to be fine in v7.0.11 👍️
