### ISSUE TITLE
Umbenennen von Gruppe in Aufzählung fehlerhaft

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#253]
Gibt man einer Gruppe, die schon Elemente beinhaltet, einen neuen Namen, dann werden alle Elemente hochgestuft und die umbenannte Gruppe ist leer.

Als ich die automatisch angelegte Gruppe "functions" in "Funktionen" umbenannt habe, hat das Mobile UI nur noch einen leeren Bildschirm angezeigt hat.

**Comment by BuZZy1337** [comment]
Was hast du geändert?
Name oder ID der Gruppe?

**Comment by Marty56** [comment]
Ich habe den Namen der Gruppe geändert. Daraufhin hat ioBroker selber die ID geändert. Das Ganze habe ich abgespeichert.

**Comment by GermanBluefox** [comment]
Please retest with 3.4.2

**Comment by Marty56** [comment]
danke für das Update. Noch eine Frage bevor ich es ausprobiere.
Funktioniert mitterweile das Update normal über die Instalation mit Weboberfläche und GitHub oder muss ich eine Sequenz über die Kommandozeile eingeben?

Hintergrund: Ich hatte damit in der Vergangenheit ziemliche Probleme bei Update von Admin über das WebUi

**Comment by BuZZy1337** [comment]
Das Update von Admin über die Weboberfläche hat bei mir immer funktioniert.. Du darfst nur nicht "von GitHub" installieren auswählen.

**Comment by Marty56** [comment]
I have installed version 3.4.2 but do not see a big improvement.
Some items can be added via drag and drop. Some can not.
In my case the item "Heizungspumpe" cannot be added whatever I do.
![bild](https://user-images.githubusercontent.com/8623789/39818566-7aca4cd0-53a1-11e8-8ba1-74f579cef38c.JPG)

**Comment by GermanBluefox** [comment]
Hm...... This issue about renaming. Why Drag&drop???

**Comment by Marty56** [comment]
Oh sorry. I replied having the biggest problem of the UI in my mind. Will test the rename feature soon.
