### ISSUE TITLE
IoBroker Oberfläche->Kategorien [bug]: Error in GUI bei Browser Safari oder Firefox

### ISSUE THREAD

**Issue by Reimann-Family** [ioBroker/ioBroker.admin#2530]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn ich den Reiter Kategorien in der Oberfläche wähle wird eine Error angezeigt: 
Hier die Analyse-Daten aus dem Browser-Fenster:

### To Reproduce

1. Gehe zum Reiter Kategorien
2. --> Erro GUI

### Expected behavior

Anzeige des Fensters Kategorien.

### Screenshots & Logfiles

<img width="1681" alt="Bildschirmfoto 2024-06-29 um 20 24 36" src="https://github.com/ioBroker/ioBroker.admin/assets/54028057/d1456444-2f16-49d6-a615-e82ff7ed5a6b">

### Adapter version

v6.17.14

### js-controller version

5.0.19

### Node version

Node.js: v20.15.0

### Operating system

Linux Raspberry 4

**Comment by astrokpz** [comment]
Identisches Problem bei mir unter - Chrome Version 126.0.6478.127 (Offizieller Build) (64-Bit)

TypeError: Cannot read properties of undefined (reading 'desc')
    at y.render (EnumBlock.tsx:405:37)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

**Comment by dolomiti70** [comment]
Gleiches Problem bei mir sowohl mit Vivaldi 6.7.3329.39 (Stable channel) (64-Bit) (Chrome 124.0.6367.243) als auch unter FF 127.0.2
Admin: 6.17.14, js-controller: 5.0.19, Node.js: 20.15.0
```
Connected: true
console.ts:40 TypeError: Cannot read properties of undefined (reading 'desc')
    at y.render (EnumBlock.tsx:405:37)
    at No (react-dom.production.min.js:203:189)
    at zo (react-dom.production.min.js:202:149)
    at xi (react-dom.production.min.js:291:172)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

**Comment by HackyPaddy** [comment]
Hier auch gleiches Problem mit v6.17.14 unter Safari.

Fixed? Wie bekomme ich den Fix, damit es wieder klappt?!

**Comment by Feuer-sturm** [comment]
@HackyPaddy Entweder du wartest bist die aktuelle admin 7.x Version ins stable repository kommt oder du installierst dir die aktuelle Beta Version vom Admin Adapter . Achtung bei der Version 7.x gab es größere Anpassunge im Code, die auch noch Bugs mit sich bringen kann (Beta Versionen werden nicht für Produktivsysteme empfohlen).

**Comment by Feuer-sturm** [comment]
@Reimann-Family Bitte einmal mit der aktuellen Beta Version >= 7.0.9 testen ob das issue gefixt ist.

**Comment by Reimann-Family** [comment]
Hallo Zusammen,
Ich habe gerade auf die Admin V7.0.9 ß-Version aktualisiert. Damit konnte ich nun die Funktion „Kategorien“ aufrufen. 
￼

Die Objekte in Kategorien kommen im wesentlichen aus meinem HomeMatic-Adapter, der die Objekte (Räume, Gewerke, etc. bereitstellt). Vielleicht hat der das Problem verursacht? 
Ich hatte auch beobachtet, das manchmal der Bug auch mit der alten Version nicht erscheint. Es ist also ein stochastischer Bug, der nicht immer auftritt. Jedenfalls scheint es erst mal mit der ß_version zu klappen. Ich beobachte das mal 2-3 Tage und melde mich nochmals.

Vielen Dank erst mal für den Tipp.




Wilfried Reimann 
Consulting QC         

mailTo: ***@***.*** ***@***.***>
mobile: +49.176.10557642
LinkedIN: https://www.linkedin.com/in/wilfriedreimann/

**Comment by Reimann-Family** [comment]
Hallo Zusammen,
Ich habe jetzt die neue Version [Admin V7.0.9 ß-Version] jetzt 2 Tage laufen lassen. 
Der Fehler ist nicht mehr aufgetreten! Ich lasse jetzt die ß-Version laufen.

Vielen Dank für die schnelle Behebung des Fehlers!

LG Wilfried

Wilfried Reimann 
Consulting QC         

mailTo: ***@***.*** ***@***.***>
mobile: +49.176.10557642
LinkedIN: https://www.linkedin.com/in/wilfriedreimann/

> Anfang der weitergeleiteten Nachricht:
> 
> Von: Familie Reimann ***@***.***>
> Betreff: Aw: [ioBroker/ioBroker.admin] IoBroker Oberfläche->Kategorien [bug]: Error in GUI bei Browser Safari oder Firefox (Issue #2530)
> Datum: 2. Juli 2024 um 21:25:51 MESZ
> An: "ioBroker/ioBroker.admin" ***@***.***>
> Kopie: "ioBroker/ioBroker.admin" ***@***.***>, Mention ***@***.***>
> 
> Hallo Zusammen,
> Ich habe gerade auf die Admin V7.0.9 ß-Version aktualisiert. Damit konnte ich nun die Funktion „Kategorien“ aufrufen. 
￼

**Comment by dolomiti70** [comment]
Auf meinem Testsystem funktioniert es mit 7.0.11. Es hat dort aber auch unter 7.0.7 funktioniert. 
Nachteil ist, dass das in der 6.xx.xx nicht mehr gefixt wird. Ich installiere sehr ungerne Adapter aus dem Beta-Zweig in meinem Produktivsystem.
Dann muss ich wohl oder über warten bis Admin 7 stable wird damit ich meine Kategorien ändern/anpassen kann.

VG
