### ISSUE TITLE
Installation not possible

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.admin#2532]
Unfortunately I can't install the adapter in iobroker:

![image](https://github.com/ioBroker/ioBroker.lovelace/assets/39516113/fe27688f-7cea-4b15-91ee-62d8700ce9cf)

License agreement doesn't load. Clicking accept just closes the box but nothing happens.
Installing manually from github doesn't work too.  No instance shows up after install.

**Comment by passuff** [comment]
You're right. Working wit admin v6.17.14

**Comment by GermanBluefox** [comment]
Please retest with 7.0.9
