### ISSUE TITLE
Adapter XYZ has an invalid jsonConfig [bug]: 

### ISSUE THREAD

**Issue by AlRo75** [ioBroker/ioBroker.admin#2537]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei diversen Adaptern bekomme ich die Meldung 

`netatmo has an invalid jsonConfig: [{"instancePath":"/items/_authenticate","schemaPath":"#/definitions/sendToProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"window"},"message":"must NOT have additional properties"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match \"else\" schema"}]`

wie hier z.B. bei Netatmo oder Imap.

`imap has an invalid jsonConfig: [{"instancePath":"/items/tab1/items/max_mb_telegram","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"adapter"},"message":"must NOT have additional properties"},{"instancePath":"/items/tab1/items/max_mb_telegram","schemaPath":"#/patternProperties/%5E.%2B/allOf/21/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/tab1","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

### To Reproduce

Das ganze kann reproduziert werden. In den Instanzen bei dem Adapter einfach die Einstellungen öffnen und wieder schließen (reicht schon).

### Expected behavior

kein Fehler

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/103645905/757e3ac2-42f1-48f9-a817-e1b91eee613f)

### Adapter version

6.13.16

### js-controller version

5.0.19

### Node version

18.20.3 / 10.7.0

### Operating system

Ubuntu 22.04 LTS

**Comment by mcm1957** [comment]
Dies ist KEIN Fehler des Admin Adapters sondern ein Fehler in der json Config des Adapters XYZ (oder ev Ein Fehler im Prüfschema).

Bitte bei jeweiligen Adapter ein Issue mit der Fehlermeldung des betroffenen Adapters öffnen.

**Comment by Apollon77** [comment]
... unless it's a jsonschema issue :-)

**Comment by mcm1957** [comment]
> ... unless it's a jsonschema issue :-)

I noted " oder ev ein Fehler im Prüfschema" 

Attribute "adapter"  at imap is definitly an adapter error.

And IF its an eror at schema ist no admin issue either but should / must be Registern at react-v5. 

Sp I suggest to close here an create issues at the effected adapters.

**Comment by GermanBluefox** [comment]
Fixed
