### ISSUE TITLE
[bug]: jsonconfig schema misses "window" attribute for sendTo

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#2538]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

admin.0 | 2024-07-05 17:03:08.874 |
warn |
daikin-cloud has an invalid jsonConfig: [{"instancePath":"/items/_authenticate","schemaPath":"#/definitions/sendToProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"window"},"message":"must NOT have additional properties"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match "else" schema"}]

### To Reproduce

e.g. netatmo, daikin.cloud that uses the admin based oauth flow

### Expected behavior

no error

### Screenshots & Logfiles

n/a

### Adapter version

current

### js-controller version

irrelevant

### Node version

irrelevant

### Operating system

irrelevant

**Comment by mcm1957** [comment]
Please create sich issurs at repo react-v5.

**Comment by mcm1957** [comment]
created https://github.com/ioBroker/adapter-react-v5/issues/355.

Think this issue could be closed
