### ISSUE TITLE
[enhancement]: CURRENT_MAX_MAJOR_NODEJS should be managed externally

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2539]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

CURRENT_MAX_MAJOR_NODEJS and CURRENT_MAX_MAJOR_NPM is hardcoded at admin source. So setting a new recommended node version a new admin release is required. 

### Description

CURRENT_MAX_MAJOR_NODEJS is hardcoded here:
https://github.com/ioBroker/ioBroker.admin/blob/aaf857fd467d543025c1920fd8c757a373aa299d/packages/admin/src/main.ts#L36

Node 20 has been added at admin 7.x.x. As this constant is used fro recommended node version at vis (info Adapter replacements) users of older Admin (Admin 6 is still stable) see still node 18 to be recommended. In addition update_node already updates to node 10 (which is OK) - but users are irritated by the fact that the system is updated to node 20 while the info (state object, vis) still recommends node 18..

### Additional context

Theras already a file containing the recommended node version:
https://github.com/ioBroker/ioBroker/blob/master/versions.json

Maybe either admin could read and use this file from github or the news system (or the reposytem) could include the information and deliver it to admin.

**Comment by Feuer-sturm** [comment]
@mcm1957 can we close this issue?

**Comment by mcm1957** [comment]
looks Ok
