### ISSUE TITLE
Blauer Balken erscheint beim aktualisieren der Objekte

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.admin#254]
Habe gerade festgestellt, wenn man unter Objekte den Button " Baum neu erstellen " betätig, dass ein blauer Balken in der Mitte in höhe der Spalte "Typ" erscheint.

**Comment by BuZZy1337** [comment]
Es erscheint ganz kurz ein (bei mir) grauer bereich, der verschwindet aber nach 1 Sekunde wieder.
Meinst du das?
Oder bleibt der "blaue Balken" bei dir dauerhaft im Bild?

**Comment by GermanBluefox** [comment]
Danke. Das ist "wait" Fenster mit falsche Höhe. Muss fixen.

чт, 26 апр. 2018 г., 11:47 BuZZy1337 <notifications@github.com>:

**Comment by quorle** [comment]
Stimmt, der Balken ist so grau/blau, aber wenn man weiter nach unten sieht, sieht man den "wait" kreisel.

Super Bluefox, ihr seit die besten und immer fix ;)

**Comment by BuZZy1337** [comment]
Fixed by Bluefox with commit https://github.com/ioBroker/ioBroker.admin/commit/b99f02a67a71eb8715b75b8688181493c5c609c1
:relaxed: 

![image](https://user-images.githubusercontent.com/6979405/39321701-0fd15694-4988-11e8-8b52-436b2bb739e1.png)
