### ISSUE TITLE
[bug]: CURRENT_MAX_ MAJOR_NPM = 8 seems to be outdated

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2540]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

const CURRENT_MAX_ MAJOR_NPM = 8;
seems to be outdated at
https://github.com/ioBroker/ioBroker.admin/blob/aaf857fd467d543025c1920fd8c757a373aa299d/packages/admin/src/main.ts#L37

As far as I know some npm 10 release is realted to node 20.

### To Reproduce

check source

### Expected behavior

using the correct recommended NPM version (or to remove this info all together as npm should ALWAYS be installed by node installer - so the information about newer npm versions might confuse users while the npm version info itself does not provide much help.

### Screenshots & Logfiles

n/a

### Adapter version

7.x.x

### js-controller version

n/a

### Node version

n/a

### Operating system

n/a

**Comment by Feuer-sturm** [comment]
@mcm1957 can we close this issue?

**Comment by mcm1957** [comment]
looks Ok
