### ISSUE TITLE
[bug]:  Falsche Anzeige wenn man einen automatischen Adapter neustart konfiguriert

### ISSUE THREAD

**Issue by JackDaniel007** [ioBroker/ioBroker.admin#2546]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

es wird zb. Jede Minute von undefined Stunde angezeigt

### To Reproduce

einfach einen automatischen neustart bei einem adapter einrichten

### Expected behavior

eine korrekte anzeige

### Screenshots & Logfiles

![image](https://github.com/ioBroker/ioBroker.admin/assets/2413204/eaafcb46-0e04-47cf-a4f3-26f98cd5ea5f)

### Adapter version

7.0.12

### js-controller version

6.0.6

### Node version

20

### Operating system

linux

**Comment by GermanBluefox** [comment]
Fixed in next version
![image](https://github.com/user-attachments/assets/b45be81f-31d6-4068-b791-f7324e088fa1)

![image](https://github.com/user-attachments/assets/5cce7d2a-1a1b-43c6-b7b4-51913f96bebd)

**Comment by JackDaniel007** [comment]
thx

**Comment by JackDaniel007** [comment]
passt wieder :)
![image](https://github.com/user-attachments/assets/f1a30950-b1d2-470c-ad8c-71e36db0699f)
