### ISSUE TITLE
[bug]: Device Manager Tab: Instance action won't be rendered if using an unknown icon

### ISSUE THREAD

**Issue by MiSchroe** [ioBroker/ioBroker.admin#2551]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

If i use an icon in an instance action of the dm-utils, that is probably not known, the whole action won't be displayed on my device manager tab.

### To Reproduce

1. Add a tab for the device manager to your jsonConfig.json of your adapter:
```json
"DeviceManager-tab": {
	"type": "panel",
	"label": "DeviceManager-tab-label",
	"items": {
		"DeviceManager": {
			"type": "deviceManager",
			"sm": 12,
			"style": {
				"width": "100%",
				"height": "100%",
				"overflow": "hidden"
			}
		}
	},
	"style": {
		"width": "100%",
		"height": "100%",
		"overflow": "hidden"
	},
	"innerStyle": {
		"width": "100%",
		"height": "100%",
		"overflow": "hidden"
	}
}
```
2. Add an action in the getInstanceInfo method of the DeviceManagement class with the following content:
```typescript
{
	id: "addGroup",
	icon: "fas fa-users",
	title: "",
	description: "Create a new group",
},
```
3. Run the adapter and go to the instance settings to your device management tab. There is no Button for the addGroup action.
4. Change the icon to "fas fa-search".
5. Now, the action will be displayed.

### Expected behavior

Instead of removing the action in total at least a text button with the ID or a broken link button should be displayed.

### Screenshots & Logfiles

n/a

### Adapter version

6.17.14

### js-controller version

6.0.6

### Node version

18.19.0

### Operating system

docker v9.1.1 linux

**Comment by GermanBluefox** [comment]
Icon with question mark will be displayed

**Comment by foxriver76** [comment]
fixed by https://github.com/ioBroker/ioBroker.admin/pull/2567
