### ISSUE TITLE
bei awtrix V1.2.1 linker Text nicht mehr sichtbar

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.admin#2555]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

vgl. issue in awtrix.
Lt. Matthias soll es ein admin Problem sein.

https://github.com/klein0r/ioBroker.awtrix-light/issues/144

### To Reproduce

x

### Expected behavior

x

### Screenshots & Logfiles

x

### Adapter version

7.0.13

### js-controller version

5.0.19

### Node version

20.15.0

### Operating system

proxmox

**Comment by GermanBluefox** [comment]
Fixed in 7.0.18
