### ISSUE TITLE
[bug]: Kann keine Instanzen anlegen

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.admin#2556]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn ich bei einem Adapter (z.B. Open KNX oder Jäger design Widgets) eine Instanz anlegen will (diese haben noch keine Instanzen) und auf das "+" drücke passiert nichts. 
Getestet mit allen Admin Versionen 7.0.13 aufwärts

### To Reproduce

Adapter auswählen und über "+" eine neue Instanz anlegen

### Expected behavior

Instanz wird angelegt

### Screenshots & Logfiles

Kein Eintrag im Debug Log

### Adapter version

7.0.17

### js-controller version

6.0.8

### Node version

20.15.1

### Operating system

Dedian

**Comment by Horgul123** [comment]
Nachtrag:
Eine OpenKNX instanz konnte ich über die Console problemlos anlegen.

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren. Kann jemand das bestätigen?

**Comment by Horgul123** [comment]
@GermanBluefox Hängt vielleicht mit diesem Problem zusammen: https://github.com/ioBroker/ioBroker.admin/issues/2557

**Comment by mcm1957** [comment]
I suggest to check
https://github.com/ioBroker/ioBroker.admin?tab=readme-ov-file#7018-2024-07-22

**Comment by Horgul123** [comment]
@mcm1957 Thanks for the hint!  Will check as soon as it's available in the beta repository

**Comment by Bernd9000** [comment]
Adapter version 7.0.18

Funktioniert noch nicht.
Alle Adapter, bei denen man die Lizenz bestätigen muß, funktioniert es nicht.
Die Fenster "Eine neue Instanz wird hinzugefügt" und "Befehl ausführen" erscheinen nicht.

**Comment by Horgul123** [comment]
Bestätigt: 7.0.18 geht z.B. beim OpenKNX Adpater nicht um eine weitere Instanz anzulegen

**Comment by Bernd9000** [comment]
Hab mal ein Test mit Admin Adapter 6.0.14 gemacht und versucht beim echarts und web Adapter eine Instanz hinzuzufügen:

Bei "echarts" kommt folgende Fehlermeldung:
host.Server(SmartHome) error: this adapter does not allow multiple instances
ERROR: Process exited with code 19

Bei web Adapter funktioniert es wieder.

**Comment by mcm1957** [comment]
> Bei "echarts" kommt folgende Fehlermeldung: host.Server(SmartHome) error: this adapter does not allow multiple instances ERROR: Process exited with code 19
> 

Die Fehlermeldung sagt genau das was dort steht. Von echarts kann es nur eine Instanz am System geben. Das ist kein Fehler.

**Comment by Bernd9000** [comment]
> Die Fehlermeldung sagt genau das was dort steht. Von echarts kann es nur eine Instanz am System geben. Das ist kein Fehler.
Ja, wußte es nicht mehr genau.
Danke für den Hinweis.

**Comment by Bernd9000** [comment]
Admin 7.0.19
Lizenz beim web Adapter kann nicht bestätigt werden.
Schaltfläche ist ausgegraut, keine Scrollbalken.

![Unbenannt](https://github.com/user-attachments/assets/fb025030-27b7-4d73-bff4-30bd5a09a752)

**Comment by Horgul123** [comment]
Mit Adapter 7.0.19 für mich gefixt

**Comment by GermanBluefox** [comment]
> Admin 7.0.19 Lizenz beim web Adapter kann nicht bestätigt werden. Schaltfläche ist ausgegraut, keine Scrollbalken. Browser Cache wurde gelöscht, test mit Firefox, Chrome, Edge.
> 
> ![Unbenannt](https://private-user-images.githubusercontent.com/77005685/351223189-fb025030-27b7-4d73-bff4-30bd5a09a752.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk2OTMsIm5iZiI6MTcyMTg3OTM5MywicGF0aCI6Ii83NzAwNTY4NS8zNTEyMjMxODktZmIwMjUwMzAtMjdiNy00ZDczLWJmZjQtMzBiZDVhMDlhNzUyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZmFhN2I1NjczOWVkN2RmYTUzMGNlYjg4ZmVjODZkMzVjN2FlZjJhNDc5MzEwZDg1OGFiMTk0MTZjM2JmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OO8ptwl9v9uSutTi_SEV1Ot253uQzl1AxL2u07ywnEs)
> 
> In der Browser Console habe ich folgenden Fehler, weiß nicht wie lange das schon ist:
> 
> ![Unbenannt2](https://private-user-images.githubusercontent.com/77005685/351225596-66362c75-787a-4942-ba3a-edb25c3e353b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4Nzk2OTMsIm5iZiI6MTcyMTg3OTM5MywicGF0aCI6Ii83NzAwNTY4NS8zNTEyMjU1OTYtNjYzNjJjNzUtNzg3YS00OTQyLWJhM2EtZWRiMjVjM2UzNTNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAzNDk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMTc4M2VkMGY2YWY5Zjk5MDdiNDdhMTkxM2NhNzhmMzNlYmM1ODY3ZGI4ODQwMzE3ZTQ1ODgwYmZjNzY0OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JhNdeZrJLV3iXOd5LzQhbvjc3ipShTGgX7DCXR5Nx8E)
> 
> Adapter version 7.0.19 js-controller version 6.0.9 Node version 20.15.1 Operating system Windows

Welche Adapter ist das? MIT sollte eigentlich nicht bestätigt werden

**Comment by Bernd9000** [comment]
>
> Welche Adapter ist das? MIT sollte eigentlich nicht bestätigt werden

Es handelt sich um den "web" Adater ( web-Server )

![1](https://github.com/user-attachments/assets/3d4bb3a0-b045-44e2-b8c6-c0ed755e4ec7)

**Comment by mcm1957** [comment]
io-package.json of adapter ioBroker.web contains an invalid licenseInformation object.
See PR https://github.com/ioBroker/ioBroker.web/pull/450 for a fix

**Comment by Bernd9000** [comment]
Mit Admin 7.0.21 funktioniert es wieder.
Dann kann hier dicht.

**Comment by foxriver76** [comment]
I cannot replicate this it works like a charme tested in Firefox

**Comment by Feuer-sturm** [comment]
@JoergGiencke does your problem with hue adapter (acepting the licence) still exist?
I just tested it to add a new instance with hue in admin 7.4.1 and I had no problems.
