### ISSUE TITLE
Anzeige aktiver Tab in Titel

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#256]
Bei der Arbeit mit iobroker sind oft mehrere Tabs geöffnet (Log, Objekte, Skripte, ...).
Es wäre nützlich für die Übersicht, wenn im Seitentitel der Name des aktiven Tabs angezeigt wird.

**Comment by BuZZy1337** [comment]
Implementiert mit #260 
( https://github.com/ioBroker/ioBroker.admin/pull/260#issuecomment-385404200 )

**Comment by BuZZy1337** [comment]
@Apollon77 this is done and can be closed. :relaxed:

**Comment by darkiop** [comment]
Vielen Dank für die schnelle Realisierung!!
