### ISSUE TITLE
[bug]: backitup has an invalid jsonConfig

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#2560]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Since admin does not yet recognise the Shema, the following warning appears when opening the Backitup config.

`backitup has an invalid jsonConfig: [{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/then/required","keyword":"required","params":{"missingProperty":"items"},"message":"must have required property 'items'"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

### To Reproduce

After open the Backitup Config, the warning is visible in The Log

### Expected behavior

 no warning

### Screenshots & Logfiles

`backitup has an invalid jsonConfig: [{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/then/required","keyword":"required","params":{"missingProperty":"items"},"message":"must have required property 'items'"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

### Adapter version

7.0.16

### js-controller version

6.0.8

### Node version

20.14.0

### Operating system

Ubuntu 22.04

**Comment by mcm1957** [comment]
@simatec 
This is NOT an admin issue. Its a problem of the checking schema.
Please close here an open a issue at react-v5 (https://github.com/ioBroker/adapter-react-v5/issues)

**Comment by GermanBluefox** [comment]
Should be fixed by https://github.com/ioBroker/adapter-react-v5/pull/360

**Comment by simatec** [comment]
@GermanBluefox Many thanks for your efforts and the fix

**Comment by jolichter** [comment]
Hello, I also updated the BackItUp adapter from version 2.11.0 to 3.0.16 today.

The backup works, but I am receiving a similar warning after opening the BackItUp Config. The warning is visible in the log:
`backitup has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"tabsStyle"},"message":"must NOT have additional properties"}]`

Does this concern the same issue, or should I open a new bug report?

Adapter: 7.0.22
js-controller: 6.0.9
Node: 20.11.1
NPM: 10.4.0
OS: Manjaro ARM Linux aarch64
Kernel: 6.6.33-2-MANJARO-RPI4

Thanks!
