### ISSUE TITLE
Darstellungsfehler Datenpunkt in mobiler Ansicht

### ISSUE THREAD

**Issue by LastPerfectTobi** [ioBroker/ioBroker.admin#2569]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In der mobilen Ansicht ist beim Wert eines Datenpunktes das Kopieren-Symbol überlagert, so dass ein Bearbeiten des Werts oft nicht möglich ist. 

![IMG_6658](https://github.com/user-attachments/assets/5aaac49c-d139-45c6-9c97-994a897200a1)

### To Reproduce

Objekte - Datenpunkte aufklappen - Wert bearbeiten

### Expected behavior

Kopierensymbol an einer anderen Stelle

### Screenshots & Logfiles

Siehe angehängter Screenshot

### Adapter version

7.0.19

### js-controller version

6.0.9

### Node version

20.15.1

### Operating system

Raspbian

**Comment by GermanBluefox** [comment]
What the browser is that? I cannot reproduce it in Chrome/FF

**Comment by LastPerfectTobi** [comment]
> What the browser is that? I cannot reproduce it in Chrome/FF

Safari on iPhone/iOS. 
With iOS17.x and the latest iOS18.x the same like described here.

**Comment by LastPerfectTobi** [comment]
Fixed with 7.0.23

![image](https://github.com/user-attachments/assets/a70571a7-e991-44aa-85a7-332a0e4a11be)

**Comment by GermanBluefox** [comment]
> Fixed with 7.0.23
> 
> ![image](https://private-user-images.githubusercontent.com/75383507/355194665-a70571a7-e991-44aa-85a7-332a0e4a11be.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTEwNTMsIm5iZiI6MTcyMzU1MDc1MywicGF0aCI6Ii83NTM4MzUwNy8zNTUxOTQ2NjUtYTcwNTcxYTctZTk5MS00NGFhLTg1YTctMzMyYTBlNGExMWJlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxMjA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzkxMWZjNmJiZGQxNTJmODZlMmJkZTFjNjNhOWNlMjAzNGU4ZmMxMzc0YzFiODEzY2JkMWE3MjljNjE2MmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EanBs7lvCa0BUzHAdpbSA9oDTGqmAnJBwoty5_N7uzo)

But I still do not understand, what the icon is that....

**Comment by LastPerfectTobi** [comment]
No its not possible because I can not connect a mouse to my smartphone and on desktop browser it looks not the same. 

When I click on symbol in red circle its the same like I click on symbol in blue circle. 
So I think this in red may be not needed?!
It copies both time the same value of this datapoint. 

![image](https://github.com/user-attachments/assets/2da79471-cc89-49fd-b431-b1779d86eb94)

**Comment by LastPerfectTobi** [comment]
In Admin 7.0.24 the icon is removed. 
All works fine.
