### ISSUE TITLE
Objekte - Button Einstellungen überlagert Text "Anzahl der Objekte"

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.admin#257]
in derObjektansicht ist die Anzahl der Objelte dazu gekommen. Der Button für "Einstellungen"  verdeckt den Text

admin 3.4.0
Chrome

![screenshot 2018-04-28 07 00 28](https://user-images.githubusercontent.com/20645041/39392214-710c90ba-4ab2-11e8-9f19-c6dc593aa5f6.png)

**Comment by BuZZy1337** [comment]
Fixed with #262 
With enabled History:
![image](https://user-images.githubusercontent.com/6979405/39587734-80ede820-4efa-11e8-9b20-e9ffb86745cb.png)

Without enabled History:
![image](https://user-images.githubusercontent.com/6979405/39587774-9acc53ee-4efa-11e8-9c7f-88b8c65a278b.png)

**Comment by Herbert-Testmann** [comment]
Test, OK
