### ISSUE TITLE
[bug]: Problem mit admin-Adapter >= v6.17.7

### ISSUE THREAD

**Issue by joergeli** [ioBroker/ioBroker.admin#2572]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Ab Admin v6.17.7 werden in der Instanz-Ansicht keine Einzelverbindungen, d.h. welche Geräte verbunden sind. bei z.B. mqtt-, oder sonoff-Adapter mehr angezeigt. Es wird nur noch "Verbunden mit Gerät oder Dienst" angezeigt, was m.E. eine rel. dürftige Information ist.
Mit Admin-Adapter <= v6.17.6 werden alle verbundenen Gräte z.B. beim mqtt-Adapter aufgelistet.

Nähere Erläuterungen siehe:
[https://forum.iobroker.net/topic/76085/problem-mit-admin-adapter-v6-17-6](url) 

### To Reproduce

Getestet mit admin-Adapter v6.17.6 und admin-Adapter >= v6.17.7
Ab v6.17.7 tritt das Problem auf.

### Expected behavior

Möglichst wieder die gewohnte Anzeige auch in neueren Versionen wieder anzeigen.

### Screenshots & Logfiles

Instanz-Anzeige mqtt-Adapter mit admin-Adapter **bis v6.17.6**:
![Aufzaehlungen mqtt](https://github.com/user-attachments/assets/55be9c9a-25a7-4088-af76-e6d32db7eb5d)

Instanz-Anzeige mqtt-Adapter mit admin-Adapter **ab v6.17.7**:
![leer mqtt](https://github.com/user-attachments/assets/ab69d3c7-501a-4b9a-a8ad-4f352e98408d)

### Adapter version

>= v6.17.7

### js-controller version

5.0.19

### Node version

v20.16.0

### Operating system

Bookworm

### Additional context

Bitte auch die nähere Erläuterungen im ioBroker-forum ansehen:
[https://forum.iobroker.net/topic/76085/problem-mit-admin-adapter-v6-17-6](url)

**Comment by mcm1957** [comment]
Admin wertet anscheinend ab Version x.x.x den State info.connected nur mehr als boolean aus. Bei den meisten neuen Adaptern ist info.connected common.type=boolean.

**Typischer Standardadapter:**
common.type: boolen
common.role: indicator.connected
```
{
  "_id": "shelly.0.info.connection",
  "type": "state",
  "common": {
    "role": "indicator.connected",
    "name": "If listening for Shelly packets",
    "type": "boolean",
    "read": true,
    "write": false,
    "def": false
  },
  "native": {},
  "from": "system.adapter.shelly.0",
  "user": "system.user.admin",
  "ts": 1721374613956,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Display: (admin 6.13.16)
![image](https://github.com/user-attachments/assets/bdf40eab-eaa3-4ecf-8bf9-950427d4260d)

**Adapter mit Devicelisting:**
common.type: string
common.role: info.clients
```
{
  "_id": "mqtt.0.info.connection",
  "type": "state",
  "common": {
    "role": "info.clients",
    "name": {
      "en": "List of connected clients",
      "de": "Liste der verbundenen Clients",
      "ru": "Список подключенных клиентов",
      "it": "Elenco dei client connessi",
      "es": "Lista de clientes conectados",
      "pt": "Lista de clientes conectados",
      "nl": "Lijst van verbonden clients",
      "fr": "Liste des clients connectés",
      "pl": "Lista podłączonych klientów",
      "uk": "Список підключених клієнтів",
      "zh-cn": "已连接客户端的列表"
    },
    "type": "string",
    "read": true,
    "write": false,
    "def": ""
  },
  "native": {},
  "from": "system.adapter.mqtt.0",
  "user": "system.user.admin",
  "ts": 1721072977648,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Display: (admin 6.13.16)
![image](https://github.com/user-attachments/assets/c5552ad4-b4e3-47d8-bd82-847037275f17)


Die Role info.clients gibts übrigends nicht in der Spec ..

**Comment by joergeli** [comment]
Ich glaube, ich habe die Erklarung mit meinem Halbwissen verstanden.
Was heißt es im Endeffekt - wird der Status Quo jetzt so belassen?
Soll keine Kritik sein, ich möchte es halt nur wissen.

**Comment by mcm1957** [comment]
Nach derzeitigem Wissenstand liegt keine geplante Änderung vor. Es dürfte sich um ein Versehen bei einer Anpassung handeln. Wahrscheinlich wird die Anzeige wie von 6.17.7 wieder hergestellt - allerdings sicher erst mit Admin 7.x.x. Da bisher nur 3 Adapter gefunden wurden die das Feature "Testanzeige" benutzen ist es bisher nicht aufgefallen.

Bekannte Adapetr sind bisher mqtt, sonof und hikvision-alarmserver. Solltest du weitere kennen, bitte um Info.

**Comment by joergeli** [comment]
Mir fällt noch der PAW-Adapter (Sprachausgabe) ein.

**Comment by joergeli** [comment]
Problem with Devicelistings (as described avove) occurs again with Admin-Adapter v7.6.14
