### ISSUE TITLE
[bug]: HTML in Logansicht wird geparst

### ISSUE THREAD

**Issue by cuddlyclara** [ioBroker/ioBroker.admin#2573]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Wenn man unter "Protokolle" den "LOG HERUNTERLADEN" Button verwendet, wird in den Log Nachrichten eventuell enthaltener HTML Code geparst. Dabei können sogar Java Skripte ausgeführt werden.

### To Reproduce

Man kann über ein Java Skript beispielsweise folgendes Skript erstellen und ausführen:

```javascript
console.info("<script>fetch('https://httpbin.org/html').then(response => response.text()).then(data => {document.getElementsByTagName('body')[0].innerHTML = data;}).catch(error => {document.getElementsByTagName('body')[0].innerHTML = 'Error: ' + error;});</script>");
```

Das Skript ruft beispielhaften HTML Code ab (nur um zu demonstrieren, dass man auch externe Quellen erreichen kann) und ersetzte den Dokument Body mit dem abgerufenen HTML Code. Dies hat zur Folge, dass man beim Aufrufen der Logansicht über den Button "LOG HERUNTERLADEN" kein Log mehr sieht, sondern nur noch das grade abgerufene HTML.

### Expected behavior

Der HTML Code in den Log Nachrichten sollte nicht geparst werden. Die speziellen HTML Zeichen sollten bei der Ausgabe z.B. mit HTML Entities ersetzt werden.

### Screenshots & Logfiles

.

### Adapter version

v6.17.14

### js-controller version

5.0.19

### Node version

v20.16.0

### Operating system

Debian 12.6 bookworm

**Comment by foxriver76** [comment]
It seems like the commit is not in any PR or even on master branch yet @GermanBluefox
