### ISSUE TITLE
[bug] jsonEditor in json config schema fehlerhaft: 

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/ioBroker.admin#2574]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Bei Verwendung des jsonEditor Objekts in der json config, wird dieser als nicht gültig angezeigt:

### To Reproduce

jsonEditor in einer json config verwenden

### Expected behavior

warnung herausnehmen / Schema anpassen

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/b0d3539e-ee2f-4ffe-b369-d0ec7439cc00)

### Adapter version

6.17.6

### js-controller version

5.0.19

### Node version

18.15.0

### Operating system

windows

**Comment by mcm1957** [comment]
THIS IS NO ADMIN BUG

a) Errors at checking Schema shoul dbe reported at repo react-v5 (as I wrote at telegramm)
b) Error has been reported before https://github.com/ioBroker/adapter-react-v5/issues/194
c) Error has been fixed already - although PR is not yet merged / delivered https://github.com/ioBroker/adapter-react-v5/pull/360

So I suggest to close here (@feuer-sturm)
