### ISSUE TITLE
[bug]: update Admin 7.0.23 error TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#2600]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Error is show during update admin from 7.0.22 to 7.0.23
After page refresh admin version 7.0.23 is shown, admin is installed in version 7.0.23
Output iob list adapters
│ 0       │ 'system.adapter.admin'                       │ 'admin'                       │ '7.0.23'       │ 'none'         │

### To Reproduce

Update Admin from 7.0.22 to 7.0.23

### Expected behavior

no error

### Screenshots & Logfiles

![grafik](https://github.com/user-attachments/assets/9f40fdd1-52c0-4fd1-9f21-6582efbabc42)

### Adapter version

7.0.22

### js-controller version

6.0.9

### Node version

Node.js: v20.16.0

### Operating system

ubuntu

**Comment by GermanBluefox** [comment]
@foxriver76 I think, that update was finished before the first request was done.

**Comment by foxriver76** [comment]
ah that could be another explanation, then we would need to check on first request if we already have been updated lol

**Comment by Feuer-sturm** [comment]
issue is fixed
