### ISSUE TITLE
[enhancement]: show min and max values on input

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#2601]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

The user can not know the min or max value of an number, as it is only shown in the object, which is only visible in Expert (or God) Mode.

### Description

Instead opening the object to see the min and max value it would be better to show it on the input (see screenshot) modal. 
![image](https://github.com/user-attachments/assets/4b6d3d66-7053-4faf-bc83-d439320951c0)
![iob_number_input](https://github.com/user-attachments/assets/e1bf7be5-73d5-4dc0-acc1-4afea8aade69)
![image](https://github.com/user-attachments/assets/e90545e7-ed62-4ee8-9113-e7cefa2a8a45)

**Comment by Feuer-sturm** [comment]
@Jey-Cee please chek if this issue can be closed
