### ISSUE TITLE
[bug]: Backitup has an invalid jsonConfig (tabsStyle)

### ISSUE THREAD

**Issue by jolichter** [ioBroker/ioBroker.admin#2602]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

Hello, yesterday I updated the Backitup adapter from version 2.11.0 to 3.0.16.

The backup works, but I am receiving a similar warning like issue [2560 ](https://github.com/ioBroker/ioBroker.admin/issues/2560)after opening the backitup config. The warning is visible in the log:
`backitup has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"tabsStyle"},"message":"must NOT have additional properties"}]`

There seems to be an additional property ("tabsStyle") that should not be included in the configuration.

Does this concern the same issue [2560](https://github.com/ioBroker/ioBroker.admin/issues/2560)? If so, please accept my apologies.

### To Reproduce

After open the backitup config, the warning is visible in the log.

### Expected behavior

no warning

### Screenshots & Logfiles

`backitup has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"tabsStyle"},"message":"must NOT have additional properties"}]`

### Adapter version

7.0.22

### js-controller version

6.0.9

### Node version

20.11.1

### Operating system

Manjaro ARM Linux aarch64 (6.6.33-2-MANJARO-RPI4)

**Comment by GermanBluefox** [comment]
Fixed with https://github.com/ioBroker/adapter-react-v5/pull/390

**Comment by simatec** [comment]
Is done and can be closed

**Comment by jolichter** [comment]
Thanks a lot!
