### ISSUE TITLE
[bug]: "tabsStyle" not documented at jsonConfig/SCHEMA.md

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2605]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Attribute "tabsStyle" is missing at jsonConfig schema doku
https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md#possible-control-types

Used at:
https://github.com/simatec/ioBroker.backitup/blob/e04e4ba226bff29d6a31bcadc2a6d2c395b70244/admin/jsonConfig.json5#L4

### To Reproduce

n/a

### Expected behavior

Docmentation is complete

### Screenshots & Logfiles

n/a

### Adapter version

n/a

### js-controller version

n/a

### Node version

n/a

### Operating system

n/a

### Additional context

related checking schema issue
https://github.com/ioBroker/adapter-react-v5/issues/389

**Comment by simatec** [comment]
is done...
