### ISSUE TITLE
[bug]: Linebreaks at info.connected text is missing

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2608]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

As no effected user seems to like to create a issue, I'll do it :-(

Admin v7.0.23 restors the possibility to display text (i.e. System names) at state info.connected.

But there seems to be a problem with linebreaks. It seems that linebreks are only inserted at '-' signs, but not at i.e. comma, underscores and other useefaul places.

See screenshots below.

### To Reproduce

see https://forum.iobroker.net/topic/76085/gel%C3%B6st-problem-mit-admin-adapter-v6-17-6/6

### Expected behavior

linebreaks beeing added as needed

### Screenshots & Logfiles

![1722887233284-instmqtt](https://github.com/user-attachments/assets/73b15bf2-0d98-498b-bfe0-d3596522dcaa)
![1722946397387-mqtt-verbindungen](https://github.com/user-attachments/assets/ca7e8b36-979e-462d-8e7c-3ce74a5463be)

### Adapter version

6.17.6

### js-controller version

n/a

### Node version

n/a

### Operating system

n/a

### Additional context

see discussion at forum https://forum.iobroker.net/topic/76085/gel%C3%B6st-problem-mit-admin-adapter-v6-17-6/6

**Comment by GermanBluefox** [comment]
Fixed by update of mqtt adapter

**Comment by Feuer-sturm** [comment]
@mcm1957 please check if this issue can be closed

**Comment by mcm1957** [comment]
Hab im Forum nachgefragt:
https://forum.iobroker.net/topic/76085/gel%C3%B6st-problem-mit-admin-adapter-v6-17-6/7

**Comment by mcm1957** [comment]
According to forum this is fixed.
https://forum.iobroker.net/topic/76085/gel%C3%B6st-problem-mit-admin-adapter-v6-17-6/16

Issue can be closed.
