### ISSUE TITLE
Admin3: Custom-Tab "Tabelle" und "Grafik" Tabs haben keine Scrollbars und unterer Teil abgeschnitten/überlagert

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#261]
Admin 3.4.0

<img width="1497" alt="bildschirmfoto 2018-04-30 um 22 44 12" src="https://user-images.githubusercontent.com/11976694/39449385-2d88a91a-4cc8-11e8-9c5d-603a4039a963.png">
<img width="1495" alt="bildschirmfoto 2018-04-30 um 22 44 19" src="https://user-images.githubusercontent.com/11976694/39449386-2db57044-4cc8-11e8-9d3c-ef5ca729a808.png">

**Comment by BuZZy1337** [comment]
Ich kann die Fehler nicht reproduzieren..
Scrollbar in der Tabelle ist vorhanden

![image](https://user-images.githubusercontent.com/6979405/39547969-6b61fb6e-4e59-11e8-9629-861a00cdfc15.png)

und die Grafik wird an die Bildschirmgröße angepasst (10" Netbook :disappointed: :smile: )
![image](https://user-images.githubusercontent.com/6979405/39547924-5029f022-4e59-11e8-82df-ff3a937b4a7f.png)

**Comment by Apollon77** [comment]
zusatzinfo: firefix tut nicht bei mir, chrome tut

**Comment by BuZZy1337** [comment]
Fixed with #262 

![image](https://user-images.githubusercontent.com/6979405/39582779-f77006ce-4eee-11e8-984e-6755dcac86f3.png)

![image](https://user-images.githubusercontent.com/6979405/39582792-feb46c5e-4eee-11e8-82d7-57e689e9fb69.png)

**Comment by GermanBluefox** [comment]
Please retest with 3.4.2
