### ISSUE TITLE
[bug]: Farbthema Steuerung

### ISSUE THREAD

**Issue by AlRo75** [ioBroker/ioBroker.admin#2610]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Im ioBroker kann das Farbthema geändert werden. Auch für Skripte gibt es die Möglichkeit das Farbthema zu ändern. Allerdings steuert die eine Einstellung auch die andere. Ich kann also für ioBroker nicht hell und für Skripte gleichzeitig dunkel einstellen.

### To Reproduce

Farbe einstellen iobroker
andere Farbe für Skripte einstellen
Reload der Seite

### Expected behavior

Gentrennte Auswahl

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/578600ad-7715-454f-9cec-f63443254e45)

![image](https://github.com/user-attachments/assets/75a3ee46-2e25-4ba8-aba6-a213e0688127)

### Adapter version

7.0.22

### js-controller version

6.0.9

### Node version

18.20.4

### Operating system

Ubuntu 22.04.3 LTS

**Comment by GermanBluefox** [comment]
Es ist so gedacht, dass Theme für alle GUIs umgestellt wird.

**Comment by AlRo75** [comment]
Dann sollte die Möglichkeit der Umstellung aus dem Skript entfernt werden, damit es nicht zu Irritationen kommt.
