### ISSUE TITLE
[bug]: Update-Warnungen öffnen sich bei jedem Reload erneut

### ISSUE THREAD

**Issue by Standarduser** [ioBroker/ioBroker.admin#2622]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Das Fenster, das auf neue Updates von Betriebssystempaketen hinweist, öffnet sich jedes Mal, wenn man die Admin-Seite öffnet, oder neu lädt, obwohl diese Meldung bereits bestätigt wurde.

<img width="1024" alt="Bildschirmfoto 2024-08-15 um 12 30 19" src="https://github.com/user-attachments/assets/8189083c-9bda-45a9-a14c-50469d2da73a">

### To Reproduce

1. Bestätigen & Schließen klicken
2. Seite neu laden

### Expected behavior

Das Fenster sollte geschlossen bleiben, bis ein weiteres, bisher nicht angezeigtes Update, hinzukommt.
Alternativ sollte es möglich sein, das automatische Öffnen dieses Fensters generell zu unterbinden (bevorzugte Lösung).

### Screenshots & Logfiles

Siehe oben.

### Adapter version

7.0.22

### js-controller version

6.0.9

### Node version

20.16.0

### Operating system

Ubuntu 22.04 LTS

**Comment by mcm1957** [comment]
Looks like this PR https://github.com/ioBroker/ioBroker.js-controller/pull/2865 addresses the problem already.

**Comment by foxriver76** [comment]
This specific Situation is also fixed in the newest admin version
