### ISSUE TITLE
[enhancement]: Switch for easy operation for beginners in the objects

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#2629]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

user-friendliness

### Description

To make ioBroker even more beginner-friendly, I would like to suggest making all true/false objects similar to the button objects, so that the user has a simple switch instead of `true/false`.
This would make the application much clearer for beginners.

In expert mode, `true/false` would then be displayed again instead of the switch and you would have the popup for operation.

If devices or objects are not operable but only readable, the switch could be greyed out.

I am of the opinion that it would improve user-friendliness, clarity and usability

### Additional context

Here is an example as a photomontage

![Objects](https://github.com/user-attachments/assets/d191c7c3-0453-451b-9f1f-dc4140acaf00)

**Comment by Feuer-sturm** [comment]
issue is implemented
