### ISSUE TITLE
[bug]: Admin > Files > User Files: Cannot read folder 0_userdata.0: Not exists

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#2634]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

In the "Files" area, after clicking on "User Files", an error message appears saying that the folder cannot be opened.

The browser log is a bit more detailed and says the folder does not exist.

Creating the folder manually (/opt/iobroker/iobroker-data/files/0_userdata.0) solves the problem.

### To Reproduce

Admin -> Files and click on User Files

### Expected behavior

The folder should be created during installation.

### Screenshots & Logfiles

Message in Admin>Files: 
![image](https://github.com/user-attachments/assets/15b91ae4-c5f0-47da-8e12-bc8f248d9dde)

Browser Log:
![image](https://github.com/user-attachments/assets/72de8349-29d7-4d7f-9559-21e20c30ad55)

No special log with admin at log level debug.

Manual creation of the folder solve the issue:
![image](https://github.com/user-attachments/assets/2d973206-2e7a-46f5-a361-042c49d53310)

### Adapter version

7.0.23

### js-controller version

6.0.9

### Node version

latest docker-container (buanet)

### Operating system

latest docker-container (buanet)

### Additional context

detected on my main system (LXC) and retested with a fresh docker container

**Comment by Feuer-sturm** [comment]
@darkiop please check if the issue is fixed

**Comment by darkiop** [comment]
sorry the delayed answer. today i did the test on fresh installation (lxc, ubuntu 24.04., stable repo).

the issue is still valid:

<img width="617" alt="image" src="https://github.com/user-attachments/assets/2b9dc3ce-76f2-4437-86d7-0fe9cc93d736">

**Comment by Feuer-sturm** [comment]
@GermanBluefox Were there any additional code updates for this issue?
@darkiop can you please double check  with current beta version (>= 7.2.6)

**Comment by darkiop** [comment]
Sure, new tests:

buanet/iobroker:latest (=Admin 7.1.5 after installation) -> issue exists

After update to Admin 7.2.6 the mentioned error message is not displayed and the directory /opt/iobroker/iobroker-data/files/0_userdata.0 still does not exist. after uploading a file, the directory is created. = issue solved.

tomorrow i can run a test within a vm or lxc

**Comment by darkiop** [comment]
tested positiv with fresh debian 12 and ubuntu 24.04. VMs. admin 7.2.6 solves the issue.
