### ISSUE TITLE
[enhancement]: Show if aliases are linked in objects tree

### ISSUE THREAD

**Issue by guitardoc** [ioBroker/ioBroker.admin#2639]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

No relating problem I could find.

### Description

When having to substitute a certain device, you have to scroll through the list of their objects and click on each of them in order to find if the object is linked to an alias and bind them to the new device. Maybe it is possible to show in the objects tree which alias is linked to a specific object, if any?

**Comment by GermanBluefox** [comment]
Just to think on the implementation strategy: How many aliases do you have?

**Comment by guitardoc** [comment]
About a hundred…

**Comment by Feuer-sturm** [comment]
@guitardoc  please check with current beta version (>= 7.2.6)

**Comment by guitardoc** [comment]
This works fine, thank you very much!
