### ISSUE TITLE
No scrollbar for Object selection at Blockly

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#264]
With Admin 3.4.x it's not possible to scroll for Object selection at Blockly:

![blockly_objekt auswahl](https://user-images.githubusercontent.com/33424168/39617335-9ee1adfa-4f7f-11e8-8ffc-9e3f1eb3e9bf.jpg)

Thread at iobroker Forum:

https://forum.iobroker.net/viewtopic.php?f=22&t=13865&p=147574#p147574

**Comment by BuZZy1337** [comment]
Issue only occurs when an entry is expanded..

I am investigating that issue..

**Comment by BuZZy1337** [comment]
Fixed with #265 

![image](https://user-images.githubusercontent.com/6979405/39627797-4bf3c4f2-4fa7-11e8-90f9-f5060151829b.png)
