### ISSUE TITLE
[bug]: Übersichtsseite: keine Anzeige der IP Adressen

### ISSUE THREAD

**Issue by frank-thegreat** [ioBroker/ioBroker.admin#2655]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Auf der Übersichtsseite werden mir in den Kacheln nur noch die Ports aber keine vorangestellten IP-Adressen mehr angezeigt.
Ab der Admin Version 7.0.18 tritt der Bug auf. Bis Version 7.0.17 passt es.

### To Reproduce

Intro-Übersicht-Kacheln (GUI)

### Expected behavior

Admin Version 7.0.17
![grafik](https://github.com/user-attachments/assets/8ad6fa5d-c402-4226-bd1b-b1a1af605710)

### Screenshots & Logfiles

Admin Version 7.0.18
![1725726891079-e52be9fe-8686-470e-828b-159fa4fef288-grafik](https://github.com/user-attachments/assets/c55121cf-2e35-44e0-b2f8-f40f211555a4)

### Adapter version

7.0.18

### js-controller version

6.0.11

### Node version

20.17.0

### Operating system

Linux

**Comment by Feuer-sturm** [comment]
@frank-thegreat Kannst du mal bitte schauen, ob mit Admin v7.2.0 das Problem bei dir noch besteht? Bei mir werden die Links korrekt angezeigt.

**Comment by frank-thegreat** [comment]
Hallo, hab heute mal den Admin 7.2.0 draufgeprügelt. Das hat auf jeden Fall was gebracht...siehe Screen.

![Admin 7 2 0](https://github.com/user-attachments/assets/235dcd9a-d7b4-415d-a9a3-e42ec0248e9d)

Die Kacheln werden jetzt wieder korrekt mit IP und Port angezeigt.

Ich hab jetzt zwar ein paar "Doppelgänger" drin, also einmal die Kachel mit passendem Link und einmal die gleiche Kachel nur mit dem Port, bei welcher nix passiert.
Kann ich aber mit leben, weil man die ja einfach ausblenden kann.
Von daher kann der Fall geschlossen werden.

Nochmal vielen Dank für eure Bemühungen.
