### ISSUE TITLE
[bug]: [jsonconfig] can delete table item despite "readOnly: true"

### ISSUE THREAD

**Issue by git-kick** [ioBroker/ioBroker.admin#2656]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Having a table with a text item defined as readOnly, there is still an "X" in the GUI which deletes the item's content. Then, I can store the changes, i.e. I changed a readOnly item.

### To Reproduce

1. iobroker url https://github.com/mcm4iob/ioBroker.jsonconfig-demo
2. iobroker add jsonconfig-demo
3. open jsonconfig-demo admin
4. go to tab "Tables"
5. press "X" right from text "Example 1"
6. save & close
7. open again and see that text "Example 1" is gone; i.e. it was deleted from the "Initialized table with fixed data"

### Expected behavior

1. No "X" should be displayed at readOnly items.
2. After modifying a readOnly item, storing chages should be inhibited.

### Screenshots & Logfiles

![grafik](https://github.com/user-attachments/assets/8360319d-f619-44e8-a6d6-1a9846c824e2)

### Adapter version

7.0.23

### js-controller version

6.0.11

### Node version

v20.17.0

### Operating system

Ubuntu 24.04 LTS

**Comment by Feuer-sturm** [comment]
@git-kick please check if the issue can be closed

**Comment by git-kick** [comment]
fix confirmed (7.1.5)
