### ISSUE TITLE
[bug]: planned instance restart calculates wrong cron pattern

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.admin#2666]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When I want to plan an adapter restart every 6 hours admin is calculating the following pattern: * */6 * * *
This actually restarts the adapter every 6 hours but all minutes within that hour

I would have expected the following pattern: 0 */6 * * *

### To Reproduce

1. Go to Instances
2. select an adapter and click on "automatisch neu starten" (the pen next to it)
3. select "Stunden"
4. select alle N Stunden
5. Key in 6 hours

now the generated pattern is * */6 * * *

### Expected behavior

I would have expected: 0 */6 * * *

### Screenshots & Logfiles

no logfile as this is a logic error

### Adapter version

7.1.0

### js-controller version

6.0.11

### Node version

20.17.0

### Operating system

Bookworm latest

**Comment by Apollon77** [comment]
But description is clear or?  "but all minutes within that hour" ... Problem is ... yes we could set automatically 0 as minute or such when you select an hour but also this might be wrong and unexpected.

I would more think about a clear warning and question on safe for restart schedule to ask "hey you really want every minute"?

**Comment by looxer01** [comment]
description is clear but for me at least it does not make much sense.
when I select "bestimmte Stunden", I would not expect every minute of the selected hour.
The cases where this is what a user might want may be real rare.

**Comment by GermanBluefox** [comment]
I have read the error message 2 times. Am I understand right, you forgot to set the minutes and wondering, that you system restarts every minute?

**Comment by GermanBluefox** [comment]
![image](https://github.com/user-attachments/assets/594c97ed-6d4c-4272-be32-96847369a796)

**Comment by looxer01** [comment]
sorry, it was really difficult to see how the pattern creation cross time categories.
I believe, it's clear now with the new warning. 
thank you
