### ISSUE TITLE
Filter box in adapter list not visible at IPAD

### ISSUE THREAD

**Issue by wendy2702** [ioBroker/ioBroker.admin#267]
Hi,

Using IPAD AIR 2 with IOS 11.3 and Chrome/Safari the Filter box is not visible:

![a29035dc-720e-42a7-9030-88b9407b6e3f](https://user-images.githubusercontent.com/33424168/39747094-98f66856-52ac-11e8-82b6-52a3c969275b.png)

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/208
