### ISSUE TITLE
& Zeichen wird nicht korrekt behandelt

### ISSUE THREAD

**Issue by twonky4** [ioBroker/ioBroker.admin#268]
Ich habe das Problem im iobroker.spotify-premium Adapter. Dort steht in einem State eine URL mit mehreren Parametern, die der User kopieren muss. Leider wird in der admin v3.4.1 - v3.4.3 ein einfaches `&` in `&amp;` umgewandelt. Dies ist der Fall beim kopieren und beim öffnen des Edit-Fensters. Im admin v3.4.0 war das noch nicht der Fall.

Listen Anzeige und echter Inhalt: ![display](https://user-images.githubusercontent.com/3495103/40100754-68f9b1a0-58e5-11e8-9d2f-cc3f71cba0d0.png)

Edit Fenster: ![edit](https://user-images.githubusercontent.com/3495103/40100755-69141a0e-58e5-11e8-8b4a-b3c954de0c26.png)

**Comment by BuZZy1337** [comment]
Der Screenshot ist aber nicht aus einer Installation mit Admin 3??
Das ist noch Admin 2.x?

**Comment by BuZZy1337** [comment]
Es geht wohl darum, dass der User eine URL manuell kopieren muss.. 

Vielleicht sollten wir in  `src/lib/js/selectID.js` so ändern:
https://github.com/BuZZy1337/ioBroker.admin/commit/3a2e497af9eab7c6c3244bb7bfcd92305963abe2

Was meinst du @GermanBluefox?

**Comment by GermanBluefox** [comment]
Ja. Man muss es ändern

ср, 16 мая 2018 г., 9:30 BuZZy1337 <notifications@github.com>:

**Comment by twonky4** [comment]
Existiert immer noch in v3.4.4 & v3.4.5.

**Comment by GermanBluefox** [comment]
Fixed in 3.4.6

**Comment by twonky4** [comment]
confirmed.
