### ISSUE TITLE
[bug]: Edit Alias (and others) are nnot available with expert mode off 

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2682]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When using the object editor with 'expert mode = OFF' some entries are not visible at right click menu. While some should be hidden, it's not clear why

- Edit Alias

is hidden / disabled. Creation ob alias should be available to all users in my oppinion

### To Reproduce

Use rihght click on any state object with expert mode on and/or off

### Expected behavior

I would expect that a user can always edit the alias config, ie. add a new alias.

### Screenshots & Logfiles

Expert Mode OFF:
![image](https://github.com/user-attachments/assets/5fa24920-8ffa-4d4f-bcc8-4ba0f8496dd6)

Expert Mode ON:
![image](https://github.com/user-attachments/assets/571e7705-f420-4308-a275-c49b4f3c50ec)

### Adapter version

7.1.0

### js-controller version

6.0.5

### Node version

20.15.0

### Operating system

windows 10

### Additional context

CPU: 0,21 %
RAM: 84 %
Betriebszeit: 16h
Verfügbar: 6.0.11
Installiert: 6.0.5
Ereignisse: ⇥8 / ↦12
Plattform: Windows
Betriebssystem: win32
Architektur: x64
CPUs: 8
Geschwindigkeit: 1996 MHz
Modell: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx  
RAM: 5.8 GB
System-Betriebszeit: 16:50:26
Node.js: v20.15.0
time: 1726753226131
timeOffset: -120
NPM: 10.7.0
Adapter-Anzahl: 630
Datenträgergröße: 221.6 GB
Freier Festplattenspeicher: 36.5 GB
Aktive Instanzen: 8
Pfad: C:\ioBroker\
Betriebszeit: 16:50:05
aktiv: true
_nodeCurrent: 20.15.0
_nodeNewest: 20.17.0
_nodeNewestNext: 20.17.0
_npmCurrent: 10.7.0
_npmNewest: 10.7.0
_npmNewestNext: 10.8.2

**Comment by GermanBluefox** [comment]
Weil das die Expert Einstellungen sind

**Comment by mcm1957** [comment]
Ok, ja das ist schon klar.

Dann sind m.E. die Experteinstellungen in diesem Punkt nicht optimal da ein User ja Aliasse anlegen können soll aber wir doch nicht jedem User zu Einrichten eines Adapters in den Expertmode schicken wollen / sollen. Oder?

**Comment by Apollon77** [comment]
@GermanBluefox Ich stimme zu. Wenn jeder user Aliase alegen kann sollte er auch editieren können

**Comment by mcm1957** [comment]
Der Dialog dient zum Editieren UND anlegen. Derzeit kann man ohne expertmode via Rechtklick auf einen state  keinen Alias anlegen ... oder ich habs nicht gesehn.

**Comment by Feuer-sturm** [comment]
@mcm1957  please check with current beta version (>= 7.2.6)

**Comment by Feuer-sturm** [comment]
admin 7.4.8
Alias bearbeiten is now visible with deactivated expert mode
![grafik](https://github.com/user-attachments/assets/933f832c-daaf-435f-a2dc-e2c051660a5e)
