### ISSUE TITLE
Keine Host-Basiseinstellungen mit admin v7.1.11

### ISSUE THREAD

**Issue by mrjeschke** [ioBroker/ioBroker.admin#2683]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Beim Aufruf der HostBasiseinstellungen mit Admin v7.1.11 kommt nur ein (fast) leeres Fenster.
Getestet auf 3 Systemen. Debian 12 / Nodejs 20
Auch verschiedene Browser probiert.
Browser-Console zeigt keinen Fehler.
Nach downgrade auf Admin v7.1.10 funktioniert es wieder.

### To Reproduce

1. In Seiteleiste auf Host
2.  im Expertenmodus den Schraubenschlüssel anklicken

### Expected behavior

Das Fenster sollte etwas anzeigen.

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/4fd7c2e1-ba51-4818-81e3-e36b07f808b1)

### Adapter version

V7.1.11

### js-controller version

6.0.11

### Node version

20.17.0

### Operating system

Debian Bookworm

**Comment by mrjeschke** [comment]
Nein, absolut nichts.
![image](https://github.com/user-attachments/assets/6eb8f42f-3d1a-4e2c-8343-297f66888180)

**Comment by mcm1957** [comment]
Ich gehe davon aus dass Admin 7.1.1 gemeint ist und nicht 7.1.11

**Comment by mcm1957** [comment]
Kann das Fehlverhalten auch bestätigen.
Admin 7.1.1

**Comment by foxriver76** [comment]
Ich brauche das Log, bitte zu erst F12 Konsole öffnen und dann die Einstellungen öffnen, dann bekommen wir hoffentlich aussagekräftigeres Log. Ich kann den Fehler mit 7.1.11 nicht nachstellen.
