### ISSUE TITLE
[bug]: WARNUNG: Aktuelles Repository ist "Offizielles stabiles Repository". Benutzung auf eigene Gefahr!

### ISSUE THREAD

**Issue by raldi01** [ioBroker/ioBroker.admin#2689]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I have updated today to admin 7.1.2 . Since the update i get the warning as discribed. Is this really wanted?

### To Reproduce

Click on the adapters tab and the warning appears.

### Expected behavior

This should give no warning.

### Screenshots & Logfiles

![grafik](https://github.com/user-attachments/assets/1e79c6fe-f7de-46c0-bc9e-df919d182308)

### Adapter version

7.1.2

### js-controller version

6.0.11

### Node version

20.17.0

### Operating system

Debian 12 bookworm on an Proxmox VM

**Comment by raldi01** [comment]
These are my settings for the repos.
![grafik](https://github.com/user-attachments/assets/c29e4628-a955-4160-81b9-543a7af0445f)

**Comment by foxriver76** [comment]
I cannot reproduce it, can you show the raw of the `system.repositories` object please

**Comment by foxriver76** [comment]
Yep on this datapoint, please click on the Pen icon and go to tab raw, copy paste the content here as text please.

**Comment by raldi01** [comment]
On my site the message disappiert after updating to admin 7.1.3.
It is not possible to paste the RAW. It is to long. The message here is: There was a problem saving your comment. Your comment is too long (maximum is 65536 characters). Please try again.

**Comment by foxriver76** [comment]
This part would be helpful

```
 "native": {
    "repositories": {
      "stable": {
        "link": "http://download.iobroker.net/sources-dist.json",
        "json": {
          "_repoInfo": {
            "stable": true,
            "name": {
              "en": "Official stable repository",
              "de": "Offizielles stabiles Repository",
              "ru": "Официальный стабильный репозиторий",
              "pt": "Repositório estável oficial",
              "nl": "Officiële stabiliteit",
              "fr": "Dépôt stable officiel",
              "it": "Repository stabile ufficiale",
              "es": "Repositorio estable oficial",
              "pl": "Repozytorium",
              "zh-cn": "A. 正式稳定存放处"
            },
            "repoTime": "2024-09-24T02:57:07.508Z",
            "recommendedVersions": {
              "nodeJsAccepted": [
                16,
                18,
                20
              ],
              "nodeJsRecommended": 20,
              "npmRecommended": 10
            }
          },
``

**Comment by klein0r** [comment]
If you don't know how to access the object definition, you can share the results of

```
sudo apt install jq
iobroker object get system.repositories | jq | head -n 50
```

**Comment by udondan** [comment]
Got the same warning since 7.1.2, also with 7.1.5.

In my repo config I have http://repo.iobroker.live/sources-dist.json as active repository. I have never touched this myself, so it must currently or previously have been the default. In the screenshot above, though, I see http://download.iobroker.net/sources-dist.json

Which of the URLs should be used?

I updated the value to the one from the screenshot but the warning is still present.

```
$ iobroker object get system.repositories | jq | head -n 50
{
  "_id": "system.repositories",
  "type": "config",
  "common": {
    "name": {
      "en": "System repositories",
      "de": "System-Repositorys",
      "ru": "Системные репозитории",
      "pt": "Repositórios do sistema",
      "nl": "Systeemrepository's",
      "fr": "Référentiels système",
      "it": "Repository di sistema",
      "es": "Repositorios del sistema",
      "pl": "Repozytoria systemowe",
      "zh-cn": "系统资料库"
    },
    "dontDelete": true
  },
  "native": {
    "repositories": {
      "Stable (default)": {
        "link": "https://download.iobroker.net/sources-dist.json",
        "json": {
          "_repoInfo": {
            "stable": true,
            "name": {
              "en": "Official stable repository",
              "de": "Offizielles stabiles Repository",
              "ru": "Официальный стабильный репозиторий",
              "pt": "Repositório estável oficial",
              "nl": "Officiële stabiliteit",
              "fr": "Dépôt stable officiel",
              "it": "Repository stabile ufficiale",
              "es": "Repositorio estable oficial",
              "pl": "Repozytorium",
              "zh-cn": "A. 正式稳定存放处"
            },
            "repoTime": "2024-09-27T02:57:37.613Z",
            "recommendedVersions": {
              "nodeJsAccepted": [
                16,
                18,
                20
              ],
              "nodeJsRecommended": 20,
              "npmRecommended": 10
            }
          },
          "accuweather": {
            "name": "accuweather",
```

**Comment by foxriver76** [comment]
`http://download.iobroker.net/sources-dist.json` is the correct one, but both have `_repoInfo.stable = true` which should not display the warning. 

Can you show a screenshot of the warning + the tab on which it occurs? Host and Adapters?

**Comment by foxriver76** [comment]
Can you show from the `system.config` object the `common.activeRepo` attribute, this is currently my last idea to look into. From code it seems that it checks if one repo does not have the `_repoInfo.stable = true` and name does not start with `stable`, so maybe there is a dead repository somehow.

**Comment by klein0r** [comment]
default configuration

> "repositories": {
>       "stable": {
>         "link": "http://download.iobroker.net/sources-dist.json",

@udondan configuration

> "repositories": {
>       "Stable (default)": {
>         "link": "https://download.iobroker.net/sources-dist.json",

Maybe the admin checks for the key instead of the stable flag?

**Comment by foxriver76** [comment]
Ah it's still a string for you, I can reproduce it now. Thanks

**Comment by foxriver76** [comment]
> default configuration
> 
> > "repositories": {
> > "stable": {
> > "link": "http://download.iobroker.net/sources-dist.json",
> 
> @udondan configuration
> 
> > "repositories": {
> > "Stable (default)": {
> > "link": "https://download.iobroker.net/sources-dist.json",
> 
> Maybe the admin checks for the key instead of the stable flag?
> 
> https://github.com/ioBroker/ioBroker.admin/blob/84e927d82c935da0398f7d4a834af5874c59ad5c/packages/admin/src-admin/src/tabs/Adapters.tsx#L1911

Yep, one line below the string case was inverted. I also changed these double negations for the array, they are hard to read imo^^

**Comment by udondan** [comment]
Awesome, thank you @foxriver76!

**Comment by matze-pe** [comment]
Ich habe den Admin Adapter 7.1.5, die Meldung "Aktuelles Repository ist "Offizielles stabiles Repository". Benutzung auf eigene Gefahr!" erhalte ich wieterhin, die Ausgabe ergibt bei mir nur das "stable" anstatt "stable (default)".

`iobroker object get system.config | jq .common.activeRepo
"stable"
`

`iob repo list
┌─────────┬──────────┬─────────────────────────────────────────────────────────┬                                                                                                                                                                                                                                             ──────────────┐
│ (index) │ name     │ url                                                     │                                                                                                                                                                                                                                              auto upgrade │
├─────────┼──────────┼─────────────────────────────────────────────────────────┼                                                                                                                                                                                                                                             ──────────────┤
│ 0       │ 'stable' │ 'http://download.iobroker.net/sources-dist.json'        │                                                                                                                                                                                                                                              false        │
│ 1       │ 'beta'   │ 'http://download.iobroker.net/sources-dist-latest.json' │                                                                                                                                                                                                                                              false        │
└─────────┴──────────┴─────────────────────────────────────────────────────────┴                                                                                                                                                                                                                                             ──────────────┘

Active repo(s): stable
Upgrade policy: none
`

Hat jemand einen Tipp für mich?
