### ISSUE TITLE
[bug]: no Admin icon on http://iobrokerIP:8082

### ISSUE THREAD

**Issue by Herbert-Testmann** [ioBroker/ioBroker.admin#2694]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

no picture for Admin on web site http://192.168.xxx.xxx:8082 since 7.1
MacOS Chrome and Safari
Admin 7.1.2
browser cache cleared

### To Reproduce

open http://iobrokerIP:8082

### Expected behavior

.

### Screenshots & Logfiles

<img width="1071" alt="Bildschirmfoto 2024-09-21 um 08 50 03" src="https://github.com/user-attachments/assets/dcfbc4d7-a417-44c8-911a-42681b0cfa4b">

### Adapter version

7.1.2

### js-controller version

6.0.11

### Node version

20.17.0

### Operating system

linux ubuntu 24.04.1

**Comment by foxriver76** [comment]
will be fixed with web adapter version 6.3.1

**Comment by Herbert-Testmann** [comment]
web server 6.3.1 works
