### ISSUE TITLE
[bug]: Admin settings don't open 

### ISSUE THREAD

**Issue by Michel83** [ioBroker/ioBroker.admin#2696]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When you open the Web interface Show the admin screen a error message.
When i want to open the settings i became a timeout 

### To Reproduce

Start the iobroker web interface 

### Expected behavior

Not a big problem, but I can't change settings

### Screenshots & Logfiles

![Screenshot_20240922_133749_Samsung Internet](https://github.com/user-attachments/assets/9a911c17-c33e-4cb8-a11a-8c85399edd89)

### Adapter version

7.1.3

### js-controller version

Newest stable

### Node version

Newest stable

### Operating system

Raspberry Pi

**Comment by GermanBluefox** [comment]
https://www.iobroker.net/#de/documentation/faq/_040_contibution.md?fehlerindergrafischeoberflchemelden

**Comment by GermanBluefox** [comment]
Sorry I can't do anything without debug info
