### ISSUE TITLE
[bug]: error in GUI after Admin update

### ISSUE THREAD

**Issue by thomasklein1975** [ioBroker/ioBroker.admin#2700]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Erroro GUI Screen is shown

### To Reproduce

1) open http://IP:Port/#tab-adapters
2) have a look at display :-)

### Expected behavior

Overview of adapters will be shown

### Screenshots & Logfiles

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

va@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:49950
e@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:54965
ko@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:73156
xi@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:122082
bs@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:109363
vs@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:109291
gs@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:109152
as@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:105932
ls@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:104483
S@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:131249
T@http://192.168.0.20:8081/static/js/5096.3a6e8bdb.chunk.js:2:131782

![admin_update_bug_gui_1](https://github.com/user-attachments/assets/561094ec-c1ca-452f-8501-97db0daaa88f)

### Adapter version

v7.1.2

### js-controller version

6.0.11

### Node version

v18.0.0

### Operating system

debian

**Comment by MPTrixi** [comment]
same issue since updated to 7.1.2

**Comment by GermanBluefox** [comment]
Please test 7.1.3

**Comment by thomasklein1975** [comment]
@GermanBluefox ok, how can i only update this adapter without overview page of adapters? is it in stable or beta repo?

**Comment by foxriver76** [comment]
7.1.5 should be stable now

**Comment by thomasklein1975** [comment]
updated to 7.1.5 and seems to be fixed.

thx for fast support/update!
