### ISSUE TITLE
[bug]: error when opening files

### ISSUE THREAD

**Issue by averlon** [ioBroker/ioBroker.admin#2709]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I have created a directory and uploaded files into this directory.

Now, when opening the files view this error occurs.

### To Reproduce

1. open files view
2. create new directory under zigbee.admin
3. upload image files to new directory
4. logout
5. login again
6. open files view in Thumbnail-view (list view works)
7. error - reproducable

### Expected behavior

show files view

### Screenshots & Logfiles

`iobroker.admin@7.0.25 [bootstrap.tsx:22:8](http://s42240io:8081/static/js/bootstrap.tsx)
[2024-09-28T08:21:04.860Z] Try to connect [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Stored version: , new version: 7.1.5 [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Connected: true [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: Link [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: time [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: timeOffset [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _nodeCurrent [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _nodeNewest [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _nodeNewestNext [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _npmCurrent [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _npmNewest [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Translate: _npmNewestNext [console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
[console.ts:40:19](http://s42240io:8081/node_modules/@sentry/utils/src/instrument/console.ts)
    He console.ts:40
    React 9
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14

​`

### Adapter version

7.1.5

### js-controller version

??

### Node version

18.19.1

### Operating system

Ubuntu 24.04.1 LTS

### Additional context

Adapter zigbee

**Comment by mcm1957** [comment]
- Please correct your version information. Admin 8.0.25 does not exist. You seem to use 7.0.25.
- Please check with up to date admin (7.1.5)

**Comment by mcm1957** [comment]
Which admin version did you use to log the errors of your last post ?

**Comment by GermanBluefox** [comment]
Please test the 7.2.0

**Comment by mcm1957** [comment]
Why do you want to install from git ???
please install from repository or eventually from npm.

**Comment by mcm1957** [comment]
'iob url iobroker.admin@7.2.2'

installs 7.2.2 from npm

But please see Issues logged against 7.2.1 and 7.2.2 before installing those versions

**Comment by GermanBluefox** [comment]
Please test 7.2.6

**Comment by vowill** [comment]
Same here with admin 7.15 - it works fine with with 7.2.6
