### ISSUE TITLE
[bug]: Error in GUI

### ISSUE THREAD

**Issue by 4foobar** [ioBroker/ioBroker.admin#2710]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

opening iobroker GUI is throwing an error

### To Reproduce

opening iobroker main GUI for logs
http://192.168.178.30:8081/#tab-logs

### Expected behavior

opening iobroker GUI

### Screenshots & Logfiles

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.178.30:8081
iobroker.admin@7.0.23 7669.72a3d01c.chunk.js:1:1706488
[2024-09-28T09:32:49.402Z] Try to connect 3957.af86c9f9.chunk.js:2:243182
Stored version: , new version: 7.1.2 3957.af86c9f9.chunk.js:2:243182
Connected: true 3957.af86c9f9.chunk.js:2:243182
Loading failed for the <script> with source “http://192.168.178.30:8081/static/js/6552.8a972966.chunk.js”. 192.168.178.30:8081:1:1
ChunkLoadError: Loading chunk 6552 failed.
(error: http://192.168.178.30:8081/static/js/6552.8a972966.chunk.js)
    j main.148da242.js:1
    e main.148da242.js:1
    e main.148da242.js:1
    Ba 7669.72a3d01c.chunk.js:1
    P React
    xi 5096.802dcc19.chunk.js:2
    bs 5096.802dcc19.chunk.js:2
    vs 5096.802dcc19.chunk.js:2
    gs 5096.802dcc19.chunk.js:2
    ls 5096.802dcc19.chunk.js:2
    S 5096.802dcc19.chunk.js:2
    T 5096.802dcc19.chunk.js:2
3957.af86c9f9.chunk.js:2:243182
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.30:8081/static/css/7669.90353861.chunk.css
Source-Map-Adresse: 7669.90353861.chunk.css.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.30:8081/static/js/7669.72a3d01c.chunk.js
Source-Map-Adresse: 7669.72a3d01c.chunk.js.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.30:8081/static/js/3957.af86c9f9.chunk.js
Source-Map-Adresse: 3957.af86c9f9.chunk.js.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.30:8081/static/js/main.148da242.js
Source-Map-Adresse: main.148da242.js.map
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.30:8081/static/js/5096.802dcc19.chunk.js
Source-Map-Adresse: 5096.802dcc19.chunk.js.map

### Adapter version

7.1.2

### js-controller version

6.0.11

### Node version

19.9.0

### Operating system

Raspbian GNU/Linux 10 (buster)

### Additional context

![image](https://github.com/user-attachments/assets/a74e3e0d-9e51-432f-9abe-f477450510ea)

**Comment by foxriver76** [comment]
Please use stable version 7.1.5

**Comment by foxriver76** [comment]
If admin is not accessible at all you can do it with cli `ìob upgrade admin`

**Comment by 4foobar** [comment]
thanks - done and working!
