### ISSUE TITLE
[bug]: device manager JSONConfig bad color scheme

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#2714]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

On the device card the name/title ins't readable, see scrennshot.

### To Reproduce

Open the device tab on net-tools or hm-rpc configuration.

### Expected behavior

Background color or text color should be brighter.

### Screenshots & Logfiles

![grafik](https://github.com/user-attachments/assets/953b671a-df2c-49f2-92ae-6f0c61aa6213)

### Adapter version

7.1.5

### js-controller version

6.0.11

### Node version

v20.12.2

### Operating system

Ubuntu 22.04

**Comment by Feuer-sturm** [comment]
@Jey-Cee  please check with current beta version (>= 7.2.6)

**Comment by Jey-Cee** [comment]
Better. thank you for fixing.
