### ISSUE TITLE
[bug]: Deselecting all weekdays in a cron expression (simple view) crashes the GUI

### ISSUE THREAD

**Issue by MiSchroe** [ioBroker/ioBroker.admin#2727]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When deselecting all weekdays in a the simple dialog for a cron expression the GUI crashes.

### To Reproduce

1. Open the settings dialog of an adapter that has a cron field, e.g. klf200 adapter.
2. Click '...' to open the dialog.
3. Choose Simple dialog.
4. Uncheck all weekdays.
5. After unchecking the last weekday the GUI crashes.

### Expected behavior

The GUI shouldn't crash. Probably it should either display a message to the user that this is an invalid cron expression or disable the checkbox if there is only one left (whichever is easier to implement).

### Screenshots & Logfiles

```
console.ts:40 Error: Expression has only 4 parts. At least 5 parts are required.
(anonymous)	@	console.ts:40
co	@	react-dom.production.min.js:188
a.componentDidCatch.t.callback	@	react-dom.production.min.js:189
Wa	@	react-dom.production.min.js:156
ki	@	react-dom.production.min.js:260
bi	@	react-dom.production.min.js:259
yi	@	react-dom.production.min.js:258
(anonymous)	@	react-dom.production.min.js:282
ws	@	react-dom.production.min.js:280
is	@	react-dom.production.min.js:272
Hl	@	react-dom.production.min.js:127
cs	@	react-dom.production.min.js:273
Le	@	react-dom.production.min.js:52
Qr	@	react-dom.production.min.js:109
qn	@	react-dom.production.min.js:74
$n	@	react-dom.production.min.js:73
r	@	helpers.ts:98
```

### Adapter version

7.1.5

### js-controller version

5.0.19

### Node version

20.17.0

### Operating system

docker (official image - v10.0.0)

**Comment by Feuer-sturm** [comment]
@MiSchroe  please check with current beta version (>= 7.2.6)

**Comment by MiSchroe** [comment]
It works partially:
1. Deselecting all weekdays should disable the OK button, because it doesn't make sense.
2. After deselecting all weekdays and clicking OK, an invalid CRON expression is stored in the field. After clicking on the ellipsis button (...) the GUI crashes again.

Further testing shows that the GUI crashes whenever I type in an invalid expression into the CRON field and click on the ellipsis button. It would be nice to have at least a basic regex test on the cron field, e.g. `((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})`

**Comment by Feuer-sturm** [comment]
@MiSchroe I can reproduce your described behavior.
This is the GUI error after your step 2

```
Error: DOW part contains invalid values: 'NaN,NaN' [console.ts:40:19](http://192.168.178.140:8081/node_modules/@sentry/utils/src/instrument/console.ts)
    me console.ts:40
    React 11
```

@GermanBluefox fyi

**Comment by Feuer-sturm** [comment]
admin 7.4.8

With current beta admin version the gui does not crash anymore of no weekday is selected. I could not reproduce the issue any more.
Issue will be closed.

@MiSchroe If you still can reproduce the issue, please comment it here and we can reopen it.
