### ISSUE TITLE
[bug]: JSONConfig hat seid Admin v7.1.0 Darstellungsfehler

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#2728]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Eingefügte Bilder werden nicht mehr richtig skaliert und es wird nach jedem Header ein NewLine ausgeführt - unabhängig von der Konfiguration.

### To Reproduce

Öffne Konfigurationsdialog meiner Adapter z.B. dysonAirPurifier, MieleCloudService, Robonect mit Admin >= 7.1.0

### Expected behavior

Darstellung der Konfig wie bis incl. Admin v7.0.25

### Screenshots & Logfiles

Soll-Zustand (Also Istzustand mit Admin <= 7.0.25):
![image](https://github.com/user-attachments/assets/db2a5257-0fc6-48d8-8598-341753465c8d)
![image](https://github.com/user-attachments/assets/a53b55ce-cc7d-45f5-8adc-2b893fa2a50d)
![image](https://github.com/user-attachments/assets/61e2ee58-8945-43f0-8c33-c0e96dd719de)

Ist-Zustand mit Admin >= 7.1.0
![image](https://github.com/user-attachments/assets/ef2f351c-01d3-40cd-84c9-1fc6653a368e)
![image](https://github.com/user-attachments/assets/86b19212-3179-42e1-a837-c90d2e5bae56)
![image](https://github.com/user-attachments/assets/877e616d-3d61-4a0a-bb37-f89f30fa38aa)

### Adapter version

unabhängig von der Version

### js-controller version

6.0.11

### Node version

20..17.0, 22.9.0

### Operating system

Linux, Windows

**Comment by mcm1957** [comment]
Are you srue that this is not only caused by width attributes (sm, lg, ..) and screen resolution.

Anyway I do not think that placing 2 Headers side by side and contrcuting some sort of tables this way is a good idea as there always will be small screens which will (and should) insert a line break in between. But this must be eventually discussed.

**Comment by GermanBluefox** [comment]
I reverted the behavior on big screens back and applied it only on screens < 600. But your layout is wrong.
You may not rely that fields will be rendered on the same line. Please use tabs or panels for that

**Comment by Grizzelbee** [comment]
@GermanBluefox , @mcm1957 

Okay - you're right I'm going to fix my jsconConfigs.

BUT ... What about the images (Donate-Button in my case)?
They get also suddenly streched since 7.1.0 and there is no (documented) possibility to keep the original size - which makes them looking really ugly.

![image](https://github.com/user-attachments/assets/0c7a092a-3d77-4e1a-8bde-761f19ff9d5d)

**Comment by GermanBluefox** [comment]
> BUT ... What about the images (Donate-Button in my case)?
> They get also suddenly streched since 7.1.0 and there is no (documented) possibility to keep the original size - which makes them looking really ugly.

First: you didn't define any width of the button, so the width is 12 (full width)
Second: you can define
```
"style": {
    "maxWidth": 150
}
```
Style is available for every type of control

**Comment by Feuer-sturm** [comment]
@Grizzelbee is this issue fixed and can be closed?
