### ISSUE TITLE
[enhancement]: Show symbol for upgrade configuration at adapter page

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2731]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

no - just a suggestion - LOW PRIOR

### Description

I suggest to show the configured upgrade policy by using different icons or colours:

![image](https://github.com/user-attachments/assets/3a4f87d8-863d-4cfd-a24b-5c462e001755)

Currently a ^ is always displayed independent of selected upgrade policy. Eventually ^p / ^n / ^m could be created ?

In tile mode the info is only visible after switchung to second tile by using 3dot klick. At tile there would be definitly enogh place to show the info at main tile etoo.

**Comment by GermanBluefox** [comment]
It is rather simple request, but required some code changes

**Comment by mcm1957** [comment]
OK, I cannot determine the effort. I would classify it as nice to have. If effort is to high - feel free to close or keep it open untile time allows.

**Comment by Feuer-sturm** [comment]
@mcm1957  please check with current beta version (>= 7.2.6)
