### ISSUE TITLE
[bug]: Cannot add instance .0 (by selecting 0 explicitly)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2732]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

It's not possible to add instance .0 in expert mode even if instance 0 does not exist. Instead of adding ionstance 0 the display immidiatly returns and displays auto.

### To Reproduce

- Add instance 1 to any adapter
-  delete intance 0 of the adapter
- enable expert mode
- try to add instance 0 using admin UI

### Expected behavior

instance 0 should be added like any other not existing instance

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/7486ffde-88ea-4ac3-a001-5141806fb971)

### Adapter version

7.2.0

### js-controller version

6.0.5

### Node version

20.15.0

### Operating system

win 10

**Comment by Feuer-sturm** [comment]
@mcm1957 please check with current beta version

**Comment by Feuer-sturm** [comment]
is working with admin 7.4.1
