### ISSUE TITLE
Addresses with "/" are truncated

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.admin#274]
KNX-Addresses with "/" are truncated

**Comment by Apollon77** [comment]
Is this a KNX issue or an Admin issue? WHen KNX then please close here and open in KNX Adapter Repository.
If Admin please provide more information!

**Comment by obodeldog** [comment]
Not only with character "/", also problems with "-". Maybe all similar character

**Comment by GermanBluefox** [comment]
Fixed in 3.4.4
