### ISSUE TITLE
[bug]: Version 7.2.2

### ISSUE THREAD

**Issue by Brandy-f1** [ioBroker/ioBroker.admin#2740]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Admin.0 bleib nach Eingabe der Logindaten in der Schleife mit dem IOBroker Symbol hängen und zeigt die Configseite nicht an.

Admin.1 ohne https angelegt. Dann komme ich wieder auf die Configseite.

Auszug aus dem Log ist im Scrrenshot zu finden.

Wenn noch Infos benötigt werden, bitte melden.

### To Reproduce

Admin.0 bleib nach Eingabe der Logindaten in der Schleife mit dem IOBroker Symbol hängen und zeigt die Configseite nicht an.

### Expected behavior

Öffnen der Configseite von IOB

### Screenshots & Logfiles

![Fehler Admin o](https://github.com/user-attachments/assets/eb6cdf3e-1326-42f3-b258-992aa6c5bd9b)

### Adapter version

7.2.2

### js-controller version

7.0.0

### Node version

v20.18.0

### Operating system

bookwoorm on raspberry pi

**Comment by Apollon77** [comment]
duplicate #2737
