### ISSUE TITLE
[bug]: Latest available version of "%s" is required, but nothing installed. Please install first "%s" and then retry.

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2744]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

When trying to install adapter flexcharts the following message is displyed:

Latest available version of "%s" is required, but nothing installed. Please install first "%s" and then retry.

Reason for the message is obviously that adapter web is not installed.

![image](https://github.com/user-attachments/assets/b85efd8e-e6fc-4105-abc2-c1dc40e42729)

### To Reproduce

1. ensure that adapter flexcharts AND adpter web is **NOT** installed
2. try to install adapter flexcharts (available at latest repo)

### Expected behavior

Either web should be installed automatically OR a message containing the required adapter (instead of %s) should be displayed.

### Screenshots & Logfiles

ADDITIONAL INFO:

The problem was reported from user using admin 7.1.5.

A)  I used my test system with admin 7.2.2 installed and deinstalled web. After this I tried to install flexcharts and flexcharts installed withpout any error and installed web automatically. Log see below.

B) I downgraded admin to 7.1.5 and deinstalled web. Then I tried to install felxcharts. The above message was displayed.

C) I updated admin to 7.2.2 (again) and tried to install flexcharts The above message was displayed. Note that this is almaost the same situation as A) with te small difference that web was deinstalled before Adnin 7.2.2 was installed while at C) web was deinstalled first and then admin was updated. 

D) to make thinks more confusing: I tried to install vis-2 (with admin 7.2.2 installed and web not installed.) This time the above message was displayed BUT with test "web" instead if %s.

Have no Idea what going on there.

![image](https://github.com/user-attachments/assets/ce1a1e7a-6c18-45f1-82f6-81671332ca4c)

![image](https://github.com/user-attachments/assets/838723eb-d1d5-40e4-a714-9ad85936907c)

 
![image](https://github.com/user-attachments/assets/bded78f3-4678-4748-b978-0964adeb76a1)

### Adapter version

7.1.5 / 7.2.2

### js-controller version

6.0.5

### Node version

20.15.0

### Operating system

win 11

**Comment by GermanBluefox** [comment]
https://github.com/MyHomeMyData/ioBroker.flexcharts/issues/36

**Comment by mcm1957** [comment]
Thanks

@GermanBluefox 
@foxriver76 
@Apollon77 

But in my oppinion either the implementation or the schema is incorrect:

Schema states:
```
        "dependencies": {
          "description": "Array like [{\"js-controller\": \">=2.0.0\"}] that describes which ioBroker modules are required for this adapter on the same host",
          "type": "array",
          "items": {
            "type": [
              "object",
              "string"
            ]
          }
        },
```

io-package.jsosn states:
```
    "dependencies": [
      {
        "js-controller": ">=5.0.19",
        "web": ">=2.0.0"
      }
    ],
```

If I'm correct this is an array containg one object. Its not prohibited that more than one item is contained in the object and its not unusual for objects to have this. In addition whats the use of an object which is allowed to contain exactly one item only?

If someone can explain please do. 
In addtion I would suggest to improve the schema or code as this situation cannot be detected by standard dev,.

**Comment by mcm1957** [comment]
In addtion one more question:
Is an empty dependency a problem? Otherwise I personally would prefer to add it / keep it at io-pacakge.json to indicate the availability and some sort of standard ordering within io-package.
