### ISSUE TITLE
admin.0 aktualisiert Eintrag unter dem Reiter Objekte admin.0.info.UpdatesList und UpdatesNumber  nach erfolgreichem Update nicht

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.admin#275]
Hallo, UpdatesList und UpdatesNumber unter Objekte wird nach erfolgreichem Update nicht zurück gesetzt. Die Adapterupdate info, also die Anzahl der zur Verfügung stehenden Updates unter dem Reiter Adapter jedoch schon.

**Comment by BuZZy1337** [comment]
Kann ich bestätigen..
Restart der Admin-Instance setzt die Werte zurück auf 0..

**Comment by BuZZy1337** [comment]
Ist bei mir jetzt verschwunden und die Werte sind korrekt.
Wird wohl immer automatisch aktualisiert wenn ioBroker nach Updates in der Repo sucht.

**Comment by smartboart** [comment]
Ja habe ein button in vis mit ner exec funktion über javascript welches iobroker update ausführt...danach ist es wieder zurück gesetzt..

**Comment by GermanBluefox** [comment]
Du muss eine von dieser Meldungen im log sehen :
'Repository cannot be read'
'No repository source configured'

**Comment by GermanBluefox** [comment]
>updatesList und UpdatesNumber unter Objekte wird nach erfolgreichem Update

Wo machst du Update? Im Admin über Button? Beim Start von Admin? Über CLI und "iobroker update"?

**Comment by smartboart** [comment]
Hallo, 
habe es die ganze Zeit über die admin Oberfläche im Browser gemacht, sobald mir unter dem Reiter Adapter die verfügbaren Updates angezeigt wurden. Anschließend in der admin Weboberfläsche unter dem Reiter Adpater auf Adapter mit Updates selektiert und das Update dann über den entsprechenden Button durchgeführt...Da meine Updates ja automatisch angezeigt werden und auch ohne probleme durchgeführt werden. ist der Zugriff auf die repository source mit sicherheit konfiguriert. Der kleine Schönheitdfehler besteht nur darin, das die Updateslist nicht direkt nach dem Update zurück gesetzt werden. Wie oben Buzzy1337ebenfalls geschrieben hat, aktualisiert sich das dann wohl auch  nach einenr Zeit X von selbst....Oder eben auch nachdem man einfach nochmal die exec iobroker update manuell startet...
Das ist mir nur aufgefallen, da ich mir die Updateinfos in Vis anzeigen lasse und auch nun die Updates über Vis mittels script  durchführe. Ist kein risen Ding aber für meine Info view unschön, da die Anzeige eben dann nicht gleich nach dem Update aktualisiert...

**Comment by GermanBluefox** [comment]
Nach dem Update sollte sich auch nicht aktualisieren.
Update cli Befehl führt js-controller aus. Die states sind im admin.x drin.


чт, 14 июн. 2018 г., 14:39 smartboart <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Fixed in js-controller 1.5.0

**Comment by olderbag** [comment]
Eingangspost:

> Hallo, UpdatesList und UpdatesNumber unter Objekte wird nach erfolgreichem Update nicht zurück gesetzt. Die Adapterupdate info, also die Anzahl der zur Verfügung stehenden Updates unter dem Reiter Adapter jedoch schon.

Post vom 26 Jun 2018:

> Fixed in js-controller 1.5.0

Was dazwischen steht verstehe ich nicht. Bei mir besteht das Problem jedenfalls nach wie vor mit js-controller 1.5.7

**Comment by olderbag** [comment]
Sieht der Entwickler hier Kommentare noch, wenn der Issue auf fixed steht?

In meinen Augen (zumindest in meiner Installation (js-controller 1.5.12) besteht das Problem noch.

**Comment by wendy2702** [comment]
Hi,

Wir sind mittlerweile bei JS-Controller 2.x oder im latest bei 3.x.

Habt ihr das Problem noch?

**Comment by smartboart** [comment]
ja, das Problem ist noch da...
siehe Bilder 
vor update 
![vor update](https://user-images.githubusercontent.com/38385805/80514790-49ca4280-8981-11ea-8017-e1afc7a84ffd.JPG)
nach Update

![nach update](https://user-images.githubusercontent.com/38385805/80514813-5058ba00-8981-11ea-9304-eec076315ee7.JPG)

**Comment by smartboart** [comment]
ioBroker-Rock

    Typ: js-controller
    Titel: JS controller
    OS: linux
    Verfügbar: 3.0.20
    Installiert: 3.0.20

**Comment by wendy2702** [comment]
> oh sehe gerade , dass es nach ein bißchen vergangener Zeit nun stimmt...

Kannst du noch kurz testen und dann wenn es geht hier bitte schließen oder kann ich jetzt schließen und du machst bei bedarf ein neues Issue auf?

**Comment by smartboart** [comment]
ich teste beim nächsten update und mache dann zu...Danke...

**Comment by Apollon77** [comment]
Gestern erst getestet. Nach update wird es nicht aktualisiert. Wenn man Adapter reloaded dann wird es aktualisiert

**Comment by olderbag** [comment]
Kann ich bestätigen. Ich werde nach dem nächsten Update mal bewusst lange warten, bis ich den Admin neu starte.

**Comment by smartboart** [comment]
ok, also es besteht immer noch das ÖProblem...Auch nach längerem Warten.
Updates List und Updates Number werden nach update der Adapter nicht zurück gesetzt. siehe Bild, welches 10 min nach Update der beiden Adapter durchgeführt wurde.

![Unbenannt](https://user-images.githubusercontent.com/38385805/80633472-22df3f80-8a59-11ea-9efc-5873ae4cc76c.JPG)

**Comment by Apollon77** [comment]
Maybe it works to listen for object changes on system.adapter.name from type "adapter" because they are updated on an adapter update only. and if a change happened update these data

**Comment by GermanBluefox** [comment]
Should be fixed in 5.0.27

**Comment by Feuer-sturm** [comment]
Admin 5.0.30
js-controller 3.3.10

Issue is fixed from my point of view.

Steps to reproduce
- No adapter updates available 
- Check objects in admin.0 -> ok
- Make downgrade for one adapter (worx)
- Check objects in admin.0 -> ok (admin.0.info.updatesNumber = 1, admin.0.info.updatesList = worx)
- Make update of worx adapter to current version
- Check objects in admin.0 -> ok (admin.0.info.updatesNumber = 0, admin.0.info.updatesList = "")
