### ISSUE TITLE
[bug]: Admin 7.2.4 Restart loop and Darkmode 

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#2756]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Nach einen Update von 7.2.2 zu 7.2.4 habe ich einen Restart loop und der Darkmode geht nicht mehr

### To Reproduce

Update Admin auf 7.2.4

### Expected behavior

No loop and Darkmode ok

### Screenshots & Logfiles

![Screenshot (989)](https://github.com/user-attachments/assets/90d81f31-683c-4c31-9f29-6c9d539cc32e)
![Screenshot (990)](https://github.com/user-attachments/assets/61c5d3de-c7c7-4266-a93f-d371a99c5cd6)

`admin.0
2024-10-09 07:26:32.688	info	==> Connected system.user.admin from ::1

admin.0
2024-10-09 07:26:32.017	info	<== Disconnect system.user.admin from ::1 admin

admin.0
2024-10-09 07:26:31.955	warn	REAUTHENTICATE!

admin.0
2024-10-09 07:25:31.942	info	==> Connected system.user.admin from ::1

admin.0
2024-10-09 07:25:30.950	info	<== Disconnect system.user.admin from ::1 admin

admin.0
2024-10-09 07:25:30.878	warn	REAUTHENTICATE!`

### Adapter version

7.2.4

### js-controller version

7.0.0

### Node version

20.18.0

### Operating system

Windows

**Comment by crunchip77** [comment]
Kann ich ebenfalls bestätigen mit js-controller v6, Nodejs v20 und Docker v10

**Comment by tmaul1968** [comment]
I can confirm this issue (restart loop, and dark mode as well)

**Comment by Nunmalfix** [comment]
I have the same issues.

**Comment by dlehmann69iob** [comment]
kann ich ebenfalls bestätigen. Fehler kommt aber ohne zutun des Nutzers. Folgende Meldung im Log. 

`admin.0 | 2024-10-09 09:28:55.479 | warn | REAUTHENTICATE!
-- | -- | -- | --
admin.0 | 2024-10-09 09:27:54.018 | warn | REAUTHENTICATE!
admin.0 | 2024-10-09 09:26:52.482 | warn | REAUTHENTICATE!
admin.0 | 2024-10-09 09:25:50.591 | warn | REAUTHENTICATE!
admin.0 | 2024-10-09 09:24:48.054 | warn | REAUTHENTICATE!`

Es wird kurz die Maske zur Passworteingabe gezeigt und dann wieder das bisherige Fenster. Ein Passwort habe ich nicht vergeben.

**Comment by vepman** [comment]
Habe `REAUTHENTICATE!`auch.
ein ` iobroker set admin.0 --auth false` hat nicht geholfen.

**Comment by dlehmann69iob** [comment]
> kann ich ebenfalls bestätigen. Fehler kommt aber ohne zutun des Nutzers. Folgende Meldung im Log.
> 
> `admin.0	2024-10-09 09:28:55.479	warn	REAUTHENTICATE!
> admin.0	2024-10-09 09:27:54.018	warn	REAUTHENTICATE!
> admin.0	2024-10-09 09:26:52.482	warn	REAUTHENTICATE!
> admin.0	2024-10-09 09:25:50.591	warn	REAUTHENTICATE!
> admin.0	2024-10-09 09:24:48.054	warn	REAUTHENTICATE!`
> Es wird kurz die Maske zur Passworteingabe gezeigt und dann wieder die Übersichtsseite. Ein Passwort habe ich nicht vergeben.

Ich darf mich präzisieren. Der Loop mit REAUTHENTICATE! kommt nur, solange man iobroker im Browser offen hat. Der Fehler tritt nicht auf, wenn man nicht auf iobroker zugreift.

**Comment by Kampfratte** [comment]
Bei mir auch Reauthenticate Loop und Darkmode.

**Comment by skvarel** [comment]
Ja, hier auch.

Admin: v7.2.4
js-controller: v7.0.0
Node-JS: v18.x.x

**Comment by CommanderXXL** [comment]
Leider ebenfalls bei mir. Version 7.2.4 und Node: 20.18 js-controller: 7.0.0
Restart passiert auch ohne irgendwelches zutun. Z.B. in der Adapter Liste ohne Interaktion und plötzlich restart

**Comment by Grothesk242** [comment]
Betrifft auch meine eCharts. Die setzen eigentlich auf den DarkMode auf, sind natürlich jetzt auch hell. 
Durch den reAuth stürzt das aber offenbar irgendwann ganz ab und ich sehe nur noch eine weiße Seite im Browser.

**Comment by Moormerlander** [comment]
Hier ebenfalls. Irgendwas in der GUI konfigurieren oder Scripte bearbeiten/erstellen ist so leider nicht mehr möglich weil der Refresh alle paar Sekunden stattfindet. :-(

**Comment by AlfredSch** [comment]
Leider ebenfalls bei mir. Version 7.2.4 und Node: 20.18 js-controller: 7.0.0
Restart passiert auch ohne irgendwelches zutun. Z.B. in der Adapter Liste ohne Interaktion und plötzlich restart

**Comment by dlehmann69iob** [comment]
Bei einem Fernzugriff über iobroker.pro tritt der Fehler nicht auf, da dort ein anderer Stand des admin genutzt wird

**Comment by Apollon77** [comment]
Admin im Latest ist auf 7.2.0 zurückgerollt

**Comment by ankaibb** [comment]
Bin wieder auf die 7.2 zurück - alles läuft normal - warte bis Fehler behoben

**Comment by mattreim** [comment]
Darkmode works again with 7.2.5 but the REAUTHENTICATE issue is still there.

**Comment by Jey-Cee** [comment]
Since i have enabled the authentication for admin the REAUTHENTICATION is gone.

**Comment by sigi2345** [comment]
> Darkmode works again with 7.2.5 but the REAUTHENTICATE issue is still there.

Dito

**Comment by Diginix** [comment]
reauth see here: https://github.com/ioBroker/ioBroker.admin/issues/2737#issuecomment-2406504145

**Comment by Diginix** [comment]
With admin 7.2.5 I have no restart loop or other issue in dark mode.

**Comment by AlfredSch** [comment]
Nach dem Update auf die Version 7.2.5  ist das verhalten  immer noch das selbe.
Nach paar Secunden restart des Gui's !

PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:3698 MHz
Modell:Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
RAM:5.8 GB
Node.js:v20.18.0
NPM:10.8.2

**Comment by Apollon77** [comment]
lets move all infos to #2737
