### ISSUE TITLE
[typo]: Automatic repository update is not allowed more than once a hour

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.admin#2757]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

<html>
<body>

Automatic repository update is not allowed more than once a hour
--

</body>
</html>

should be

<html>
<body>

Automatic repository update is not allowed more than once an hour
--

</body>
</html>

### To Reproduce

.

### Expected behavior

.

### Screenshots & Logfiles

.

### Adapter version

7.1.5

### js-controller version

.

### Node version

.

### Operating system

.

**Comment by mcm1957** [comment]
fixed with https://github.com/ioBroker/ioBroker.admin/pull/2758
