### ISSUE TITLE
[bug]: REAUTHENTICATE!

### ISSUE THREAD

**Issue by aski71** [ioBroker/ioBroker.admin#2762]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Seit dem Update auf admin 7.2.4 wird mein Logfile so alle halbe Minute mit "REAUTHENTICATE!" zugekleistert.
Authentisierung ist bei mir abgeschaltet.

### To Reproduce

siehe oben

### Expected behavior

Funktionsfähigkeit ohne Authentisierung ohne Fehlermeldung.

### Screenshots & Logfiles

2024-10-11 09:40:49.160	warn	REAUTHENTICATE!  

### Adapter version

7.2.4

### js-controller version

7.0.0

### Node version

20.17.0

### Operating system

Ubuntu  5.15.0-122-generic #132-Ubuntu

**Comment by Apollon77** [comment]
duplicate #2737
