### ISSUE TITLE
Kollektives Ändern der Einstellungen für history nicht mehr möglich

### ISSUE THREAD

**Issue by Church2** [ioBroker/ioBroker.admin#277]
![bildschirmfoto 2018-06-10 um 12 58 25](https://user-images.githubusercontent.com/39483049/41200939-3785e54e-6cae-11e8-9487-a752953e1287.jpg)

Kollektives Ändern der Einstellungen für history der gefilterten Objekte (z.B. über Dropdown oben rechts) nicht mehr möglich.

**Comment by Apollon77** [comment]
Welche Admin Version?

**Comment by Church2** [comment]
Sorry, Version ist 3.4.4!

**Comment by BuZZy1337** [comment]
Den Bug kann ich bestätigen.

**Comment by GermanBluefox** [comment]
Gefunden. Abends wird es gefixt.

**Comment by GermanBluefox** [comment]
Fixed in 3.4.5
