### ISSUE TITLE
[bug]: Rewrite of html code for zigbee adapter admin interface breaks zigbee adapter configuration interface

### ISSUE THREAD

**Issue by asgothian** [ioBroker/ioBroker.admin#2774]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

WIth the admin 7.1.5, the zigbee adapter configuration and tab display looks identical.
With the admin 7.2.6 or newer (tested with current GitHub version too), the display of the tab has not changed, but the display of the header for the adapter configuration has changed.
Inspection of the code has shown that a modification from the provided html code, which lists `class="col"` to `class="col S12"` is the cause of this change. Manual edit of the html code in the browser confirms this

Additional information provided in screenshots and log files

### To Reproduce

1. ensure that at least admin 7.2.6 is installed
2. ensure that the zigbee Adapter 1.10.3 or greater is installed. Note: Zigbee Hardware is not required to see the effect - it occurs on a stopped adapter as well as a started one.
3. Open the adapter configuration interface
4. open the Zigbee Tab
5. Compare the differences (should be obvious)

Note - I spent over 3 hrs trying to modify the index_m.html to render as the tab does - with no success. As this error blocks the ability to configure the zigbee adapter, it is a breaking change for the zigbee Adapter. I am aware that the underlying issue may live in the zigbee adapter configuration, but my knowledge of materialise is insufficient to actually pinpoint / fix it.

### Expected behavior

- Identical behaviour when displaying tab and configuration interface when identical html styles are used
- Rendering of the configuration interface header just as the tab header is rendered today

### Screenshots & Logfiles

Screenshot of tab interface (and config interface on Admin 7.1.5)

<img width="1072" alt="Screenshot 2024-10-18 at 03 20 17" src="https://github.com/user-attachments/assets/fb4c61ea-32fe-4cfc-bd19-deeca504ef30">

Screenshot of config interface (identical zigbee adapter code) on Admin 7.2.6
<img width="1077" alt="Screenshot 2024-10-18 at 03 20 40" src="https://github.com/user-attachments/assets/94bf622d-c932-4b7d-96a3-4e1cacf7148d">

Code as present in the zigbee Adapter index_m.html:
```
            <div class="nav-wrapper">
                <div class="col">
                    <img src="zigbee.png" class="zlogo left" height="64px"/>
                </div>
                <div class="col">
                    <h5 class="translate center-align">Zigbee adapter</h5>
                </div>

```
Screenshot of website inspector on Admin 7.2.6 / current GitHub version)
<img width="485" alt="Screenshot 2024-10-18 at 03 21 29" src="https://github.com/user-attachments/assets/f474f7d1-b88d-44e9-9689-6718771c12ce">

### Adapter version

7.2.6 or newer

### js-controller version

verified with 5.0.19 and 7.0.0

### Node version

18.18.2 or newer

### Operating system

various

**Comment by Apollon77** [comment]
@simatec Maybe you have an idea and could support here

@asgothian We are currently optimize Admin and the adapter configs to be more responsive. this might have caused thus

**Comment by simatec** [comment]
> Code as present in the zigbee Adapter index_m.html:
> 
> ```
>             <div class="nav-wrapper">
>                 <div class="col">
>                     <img src="zigbee.png" class="zlogo left" height="64px"/>
>                 </div>
>                 <div class="col">
>                     <h5 class="translate center-align">Zigbee adapter</h5>
>                 </div>
> ```

In the index_m.html the definitions of the resolutions for different Dsiplay sizes are partially missing.

The admin is currently trying to automatically adapt the responsive for small screens such as smartphones.

In the Zigbee adapter, however, some additional adjustments are necessary in the html and css.
There was also an issue from the bot
I recommend the following changes for the special div:

```
             <div class="nav-wrapper">
                 <div class="col s12 m12 l12">
                     <img src="zigbee.png" class="zlogo left" height="64px"/>
                 </div>
                 <div class="col s12 m12 l12">
                     <h5 class="translate center-align">Zigbee adapter</h5>
                 </div>
 ```

**Comment by asgothian** [comment]
Perfect, thanks a lot for the help with that.

**Comment by mcm1957** [comment]
> > Code as present in the zigbee Adapter index_m.html:
> > ```
> >             <div class="nav-wrapper">
> >                 <div class="col">
> >                     <img src="zigbee.png" class="zlogo left" height="64px"/>
> >                 </div>
> >                 <div class="col">
> >                     <h5 class="translate center-align">Zigbee adapter</h5>
> >                 </div>
> > ```
> 
> In the index_m.html the definitions of the resolutions for different Dsiplay sizes are partially missing.
> 
> The admin is currently trying to automatically adapt the responsive for small screens such as smartphones.
> 
> In the Zigbee adapter, however, some additional adjustments are necessary in the html and css. There was also an issue from the bot I recommend the following changes for the special div:
> 
> ```
>              <div class="nav-wrapper">
>                  <div class="col s12 m1 l1">
>                      <img src="zigbee.png" class="zlogo left" height="64px"/>
>                  </div>
>                  <div class="col s12 m4 l4">
>                      <h5 class="translate center-align">Zigbee adapter</h5>
>                  </div>
> ```

@simatec 
@arteck

Did you create a issue at zigbee adapter?
Or an PR ?

**Comment by asgothian** [comment]
I made a PR and merged it earlier today. Should be fixed to what @simatec suggested
