### ISSUE TITLE
[bug]: Darstellungsfehler Admin 7.2.6

### ISSUE THREAD

**Issue by Knoddel** [ioBroker/ioBroker.admin#2775]
### No existing issues.

- [ ] There is no existing issue for my problem.

### Describe the bug

Ich habe ein Darstellungsproblem mit dem Zigbee Adapter das mit Admin 7.2.6 zusammenhängt. Wenn ich links in der Leiste Zigbee anklicke ist die Darstellung okay, aber wenn ich über Instanzen und dann beim Zigbee Adapter auf den Schlüssel klicke ist die Darstellung nicht okay.
Mit Admin 7.2.0 ist alles okay.

### To Reproduce

1.	Klick links auf Zigbee (Ansicht okay)
2.	Klick links auf Instanzen
3.	Geht zu Zigbee
4.	Klick auf Schlüssel (Ansicht nicht okay)

### Expected behavior

Richtige Ansicht

### Screenshots & Logfiles

![Leiste links](https://github.com/user-attachments/assets/30a78af0-4a65-4a46-96eb-409214cc474c)
![Schlüssel](https://github.com/user-attachments/assets/0d13ce5c-2563-4ff5-b657-0b2a1abfe856)

### Adapter version

7.2.6

### js-controller version

7.0.0

### Node version

20.18.0

### Operating system

Debian 12 bookworm

**Comment by mcm1957** [comment]
Most likely a duplicate of https://github.com/ioBroker/ioBroker.admin/issues/2774

Must be and is fixed at ZIGBEE adapter
