### ISSUE TITLE
[bug]: JSONConfig we need for password field an eye

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#2776]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

![grafik](https://github.com/user-attachments/assets/bff9165c-c957-4750-87d3-8bc78b9f7a14)

we need an eye for psw in one line

### Adapter version

7.2.6

### js-controller version

7.0

### Node version

20

### Operating system

linux

**Comment by klein0r** [comment]
`visible: true` should work

https://github.com/ioBroker/ioBroker.admin/blob/620c68a361a27a72c11d4d3acb28ac7dee69f1b8/packages/jsonConfig/SCHEMA.md?plain=1#L175-L183

**Comment by arteck** [comment]
nope

look here

https://github.com/arteck/ioBroker.zigbee2mqtt/blob/cebf7e3ba4a384f9e2abae4914ad324f807fc72b/admin/jsonConfig.json#L116

and screenshot

**Comment by arteck** [comment]
nope 
![grafik](https://github.com/user-attachments/assets/ee8c0bd8-abca-457b-9d74-bfe4b031c4d7)
