### ISSUE TITLE
Scrolling in "edit objects" dialog is broken

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#278]
See screenshot, I cannot scroll down to the lowest item in the dialog on all pages, as that is hidden by the "save/cancel" bar.

![unbenannt](https://user-images.githubusercontent.com/17641229/41225796-f5a59bac-6d6f-11e8-9048-ede37ff7c93c.PNG)

**Comment by BuZZy1337** [comment]
With Chrome everything is working as expected..
Which browser are you using?

![image](https://user-images.githubusercontent.com/6979405/41229210-6dcb9f0e-6d7b-11e8-9f62-8d23e775ec06.png)

**Comment by AlCalzone** [comment]
I use Firefox. Admin 3 had several similar issues/inconsistencies between FF and Chrome at the beginning, so I think this is related.

**Comment by BuZZy1337** [comment]
Okay, PR #279 is ready for this issue. :relaxed:
