### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by todonica** [ioBroker/ioBroker.admin#2782]
### No existing issues.

- [ ] There is no existing issue for my problem.

### Describe the bug

try to enter the **file** pages im main menu

### To Reproduce

1. goto files-page link
2. error occurs

### Expected behavior

open the files page

### Screenshots & Logfiles

Logfile console:
iobroker.admin@7.0.25
console.ts:40 [2024-10-28T13:35:11.626Z] Try to connect
console.ts:40 Stored version: , new version: 7.1.5
console.ts:40 Connected: true
console.ts:40 Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ye (react-dom.production.min.js:50:341)
    at Ko (react-dom.production.min.js:229:311)
    at ks (react-dom.production.min.js:280:85)
    at bs (react-dom.production.min.js:279:450)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ console.ts:40
Show 1 more frame
Show lessUnderstand this errorAI
6:8081/#tab-files:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this errorAI
:8081/#tab-files:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this errorAI
![chrome_IJTdARhXby](https://github.com/user-attachments/assets/cb25d508-c8c6-4316-9f24-69fcc48ab19c)

### Adapter version

v7.1.5

### js-controller version

6.0.9

### Node version

v20.16.0

### Operating system

 Windows Betriebssystem: win32 Architektur: x64

**Comment by Feuer-sturm** [comment]
duplicate to #2791
