### ISSUE TITLE
[bug]: error tab files

### ISSUE THREAD

**Issue by jvfle** [ioBroker/ioBroker.admin#2791]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

bootstrap.tsx:22 iobroker.admin@7.0.25
console.ts:40 [2024-10-30T18:46:12.316Z] Try to connect
console.ts:40 Stored version: , new version: 7.1.5
console.ts:40 Connected: true
console.ts:40 system.adapter.accuweather.0
console.ts:40 system.adapter.admin.0
console.ts:40 system.adapter.backitup.0
console.ts:40 system.adapter.daswetter.0
console.ts:40 system.adapter.discovery.0
console.ts:40 system.adapter.dwd.0
console.ts:40 system.adapter.energiefluss-erweitert.0
console.ts:40 system.adapter.icons-addictive-flavour-png.0
console.ts:40 system.adapter.icons-material-png.0
console.ts:40 system.adapter.icons-mfd-svg.0
console.ts:40 system.adapter.icons-open-icon-library-png.0
console.ts:40 system.adapter.modbus.0
console.ts:40 system.adapter.mqtt.0
console.ts:40 system.adapter.node-red.0
console.ts:40 system.adapter.pollenflug.0
console.ts:40 system.adapter.vis.0
console.ts:40 system.adapter.vis-2.0
console.ts:40 system.adapter.vis-2-widgets-gauges.0
console.ts:40 system.adapter.vis-icontwo.0
console.ts:40 system.adapter.vis-inventwo.0
console.ts:40 system.adapter.vis-jqui-mfd.0
console.ts:40 system.adapter.vis-materialdesign.0
console.ts:40 system.adapter.vis-plumb.0
console.ts:40 system.adapter.vis-rgraph.0
console.ts:40 system.adapter.vis-timeandweather.0
console.ts:40 system.adapter.weather-warnings.0
console.ts:40 system.adapter.weatherunderground.0
console.ts:40 system.adapter.web.0
console.ts:40 getInstances: 99
12console.ts:40 Width: lg
console.ts:40  Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ye (react-dom.production.min.js:50:341)
    at Ko (react-dom.production.min.js:229:311)
    at ks (react-dom.production.min.js:280:85)
    at bs (react-dom.production.min.js:279:450)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonym) @ console.ts:40
1 weiteren Frame anzeigen
Weniger anzeigen
console.ts:40  [2024-10-30T18:57:33.934Z] ws connection error: CLOSED_NO_STATUS
(anonym) @ console.ts:40
1 weiteren Frame anzeigen
Weniger anzeigen
console.ts:40 [2024-10-30T18:57:33.941Z] Start reconnect 0
console.ts:40 [2024-10-30T18:57:33.944Z] Try to connect
console.ts:40 Stored version: 7.1.5, new version: 7.1.5

### To Reproduce

1. go to iobroker-vis and click  Übersicht/Dateien then occurs the mistake and I can not working. The windows freeze and reboot.

### Expected behavior

I don't know. 

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/b72c7895-091d-4897-a08c-cdbae2a44746)
![image](https://github.com/user-attachments/assets/311f36ad-dd71-4ce4-9bd6-30350be95466)

### Adapter version

7.1.5

### js-controller version

6.0.9 ??

### Node version

Node.js 22.9.0 (x64) 

### Operating system

Windows 11

### Additional context

PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:1601 MHz
Modell:Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz
RAM:7.7 GB
System-Betriebszeit:540 T. 18:13:10
Node.js:v22.6.0
time:1730316469836
timeOffset:-60
NPM:10.8.2
Adapter-Anzahl:545
Datenträgergröße:25019.4 GB
Freier Festplattenspeicher:7652.4 GB
Aktive Instanzen:12
Pfad:/opt/iobroker/
Betriebszeit:7 T. 00:16:44
aktiv:true
_nodeCurrent:22.6.0
_nodeNewest:22.11.0
_nodeNewestNext:20.18.0
_npmCurrent:10.8.2
_npmNewest:10.8.2
_npmNewestNext:10.8.2

**Comment by Feuer-sturm** [comment]
duplicate to #2648 -> is fixed with admin >=7.2.6

**Comment by jvfle** [comment]
Bug described #2791 is solved. Update to admin version 7.2.6 solved the issue.
Thanks jvfle

**Comment by jvfle** [comment]
Problem is solved. I closed tue issue.Thank you very much for fast helping. With regards 
-------- Ursprüngliche Nachricht --------Von: Feuer-sturm ***@***.***> Datum: 31.10.24  21:17  (GMT+01:00) An: "ioBroker/ioBroker.admin" ***@***.***> Cc: jvfle ***@***.***>, Author ***@***.***> Betreff: Re: [ioBroker/ioBroker.admin] [bug]: error tab files (Issue #2791) 
duplicate to #2648 -> is fixed with admin >=7.2.6
