### ISSUE TITLE
SSL-Zertifikate nicht gefunden / SSL certificates not found

### ISSUE THREAD

**Issue by Leseratte10** [ioBroker/ioBroker.admin#280]
Wenn ich in den Einstellungen das gesamte Zertifikat, die Chain und den Key reinkopiere, werden mir die drei Dinge korrekt in den admin.0 und web.0-Einstellungen angeboten. 

Gebe ich nur einen Dateipfad an (weil ich die Keys nicht im Iobroker speichern möchte, und weil sich die ständig ändern und ich die dann extern über einen Cronjob aktualisiere), werden alle drei Einträge unter "publicKey" angeboten und keins unter "Chain" und "Private key", so lässt sich dann nichts abspeichern. Lässt sich das ändern, dass man Keys im Dateisystem auch nutzen kann und die nicht im IObroker gespeichert werden müssen?

Vielen Dank!

---

When I copy the whole certificate and key into the table in the settings, I can correctly select all of them in the admin.0 and web.0 settings. 

However when I only enter a file path, all three files are displayed as "public key" and I can't select a private key and chain. Can this be fixed so I can use keys inside the file system and don't have to store them inside the IObroker?

Thanks a lot!

**Comment by GermanBluefox** [comment]
Version?

**Comment by GermanBluefox** [comment]
dann probiere 3.4.6 aus

**Comment by GermanBluefox** [comment]
?

**Comment by Leseratte10** [comment]
Sorry, hatte noch keine Gelegenheit zu testen. Mit 3.4.6 werden jetzt alle drei Einträge an allen drei Stellen angezeigt und HTTPS funktioniert jetzt, vielen Dank.
