### ISSUE TITLE
[enhancement]: Scaling of Object Edit Modal

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#2814]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

The editing modal does not scale with high resolutions. It becomes long and narrow. A percentage adjustment to the width and height of the viewport would be better.

### Description

Vivaldi / Chrome / Edge
![image](https://github.com/user-attachments/assets/6f33e5be-4e32-430c-b2c8-25a6e0cbe513)

Firefox
![image](https://github.com/user-attachments/assets/adf91f60-ffa6-4afa-a59d-d34a4aa866c1)

**Comment by GermanBluefox** [comment]
Changed to 
![image](https://github.com/user-attachments/assets/eb028dc9-375d-445e-b5e5-f49bc5fa00b1)

**Comment by Feuer-sturm** [comment]
@darkiop please check with current beta version

**Comment by darkiop** [comment]
GM @Feuer-sturm: With admin v7.4.8 still the same (firefox, chrome):
![image](https://github.com/user-attachments/assets/7b9496ba-a5b8-4296-a89b-d9a6b682044d)

**Comment by Feuer-sturm** [comment]
@darkiop please check with admin >= 7.4.9

**Comment by darkiop** [comment]
Fixed
