### ISSUE TITLE
[enhancement]: Expert Mode - titlebar alignment

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#2815]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

In the title bar of the ioBroker with activated Expert Mode, the ioBroker logo (and instance name) is slightly offset to the top and the logo would also fit better into the Ui if the background of the logo were transparent (not white).

### Description

![image](https://github.com/user-attachments/assets/dfd343d5-bf16-40f9-a3f1-67019bd2b65d)

**Comment by GermanBluefox** [comment]
> In the title bar of the ioBroker with activated Expert Mode, the ioBroker logo (and instance name) is slightly offset to the top

You are right

> and the logo would also fit better into the Ui if the background of the logo were transparent (not white).
This done if the icon content is similar to admin background, (e.g. gray). In this case it will not be visible.

**Comment by Feuer-sturm** [comment]
admin 7.4.8
from my point of view it is fixed
![grafik](https://github.com/user-attachments/assets/73f9f897-a3b1-4cd2-bc79-06bf5034bca3)

@darkiop please double check. If not ok, we can reopen the issue.

**Comment by darkiop** [comment]
looks good, can remain closed ;)
