### ISSUE TITLE
[bug]: Error in GUI when trying opening "files" - Fehler beim Öffnen von "Dateien" 

### ISSUE THREAD

**Issue by thebilberry** [ioBroker/ioBroker.admin#2819]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Firefox Console log (xxx.xxx.xxx.xxx = placeholder for my internal IP):
`Could not process news: 34400/request/l</o<@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:161997
r@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:228834
setTimeout handler*78990/tn/<@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:240686
34400/request/l<@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:161959
request@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:161875
request@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:174283
getDiagData@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:180172
44321/Qa/this.onNews@http://xxx.xxx.xxx.xxx:8081/static/js/4684.31dece60.chunk.js:1:1666111
async*subscribeState@http://xxx.xxx.xxx.xxx:8081/static/js/5056.9247882b.chunk.js:2:157645
async*44321/componentDidMount/onReady/</<@http://xxx.xxx.xxx.xxx:8081/static/js/4684.31dece60.chunk.js:1:1679277
[console.ts:40:19](http://xxx.xxx.xxx.xxx:8081/node_modules/@sentry/utils/src/instrument/console.ts)
    He console.ts:40
    onNews App.tsx:1654
    subscribeState Connection.ts:694
    onReady App.tsx:1230`
and
`Error: Minified React error #62; visit https://reactjs.org/docs/error-decoder.html?invariant=62 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 8
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14
[console.ts:40:19](http://xxx.xxx.xxx.xxx:8081/node_modules/@sentry/utils/src/instrument/console.ts)
    He console.ts:40
    React 9
    S scheduler.production.min.js:13
    T scheduler.production.min.js:14`

### To Reproduce

click on "files" in Admin menu (klick auf "Dateien")
![Auswahl_003](https://github.com/user-attachments/assets/c9926e7d-6742-409c-88d4-73d2e67ff7bb)

after clicking the initial view appears with a counter in the left upper corner:
![Auswahl_002](https://github.com/user-attachments/assets/d03bbcc9-24bc-474d-b225-3d37efe2e66e)
and after a few seconds...
![error](https://github.com/user-attachments/assets/49194c2e-0ebd-485d-a2d9-68938709364b)

### Expected behavior

View the files-screen
(like example here) 
![viewFiles](https://github.com/user-attachments/assets/7ada55f9-47b6-4017-b8b2-3511a038ae60)

### Screenshots & Logfiles

please see above

### Adapter version

7.1.5

### js-controller version

6.0.11

### Node version

20.18.0

### Operating system

Ubuntu 22.04.5 LTS

**Comment by Feuer-sturm** [comment]
@thebilberry duplicate to https://github.com/ioBroker/ioBroker.admin/issues/2648 -> is fixed with admin >=7.2.6
