### ISSUE TITLE
Beim Tab Wechsel wird immer oberste Zeile angezeigt

### ISSUE THREAD

**Issue by lobomau76** [ioBroker/ioBroker.admin#282]
Beim Wechsel zwischen Tabs, z.B. Objekte und Scripte, wird jedesmal das oberste Objekt angezeigt und nicht die Stelle die ich vorher auf hatte. Also, wenn man ein Script aufmacht, wo man weiter runterscrollen muss, weg- und wieder zurückgeht, ist man wieder ganz oben und muss wieder die Stelle finden, wo man vorher war. Das war beim alten Admin nicht so.

Getestet mit ioBroker auf Ubuntu mit node 8.11.3 (auch 6.x.x) und npm 6.1.0 (auch 4.x.x).
Browser: Chrome und Firefox.

**Comment by GermanBluefox** [comment]
Ist aber im neuen so.
Die Seiten werden nach Verlassen gelöscht.

чт, 21 июн. 2018 г., 10:53 lobomau76 <notifications@github.com>:

**Comment by Apollon77** [comment]
Werden die Seiten auch gelöscht wenn man nur die "Konfig" (Custom oder Objektkonfig als beispiel) aufruf? Da lande ich unter "Objekte" auch immer wieder oben. nervt wenn man mehrere Objekte bearbeiten will ... man muss immer schauen wo man gerade war

**Comment by GermanBluefox** [comment]
Objects, Instances, Adapters, Intro saves the position now in 3.4.7

**Comment by Apollon77** [comment]
Cool!! Thank you
