### ISSUE TITLE
[bug]: Allow negative values in "Ignore values smaller than" field

### ISSUE THREAD

**Issue by slimline33** [ioBroker/ioBroker.admin#2826]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

I encountered an issue where the Admin Adapter does not allow entering negative values (e.g., -20) in the "Ignore values smaller than" field. Attempting to do so results in an error message. It seems possible to enter these thresholds directly into the object properties, but I am not sure if this workaround works as expected.

### To Reproduce

click on the settings button in objects and type a negative number e.g. -10 in the field.

### Expected behavior

The Admin Adapter offers the feature to ignore values smaller or larger than a defined threshold. However, it does not support negative thresholds.

### Screenshots & Logfiles

![image](https://github.com/user-attachments/assets/71a26418-385d-4595-b0e0-f7b10d54daa9)

![image](https://github.com/user-attachments/assets/6bcef1a3-b061-46b9-bb6a-a99184e91cfa)

![image](https://github.com/user-attachments/assets/b4c22902-d03e-4b34-89a5-56d13a07c810)

### Adapter version

v7.1.5

### js-controller version

6.0.11

### Node version

v18.20.5

### Operating system

debian

### Additional context

**Use Case:**
I use Aqara temperature sensors, which occasionally log unrealistic values like -100°C into InfluxDB. These extreme values disrupt my Grafana dashboards, and I have to manually delete them from the database to restore proper visualization.

Please enable support for entering negative values in the "Ignore values smaller than" field through the Admin Adapter UI. This would save the need to preprocess data using scripts and provide a more user-friendly solution for filtering unrealistic sensor values.

Thank you for considering this improvement!

**Comment by mcm1957** [comment]
Most likely this issue is not related to admin biut to influx-db.

**Comment by slimline33** [comment]
You're right. This doesn't belong here. I'll close this issue and move it to the InfluxDB Adapter instead!
