### ISSUE TITLE
Neue Filter in Instanz Ansicht

### ISSUE THREAD

**Issue by darkiop** [ioBroker/ioBroker.admin#283]
Weitere Filter in der Instanz Übersicht wären hilfreich, wie z.B.:

- gestartet, gestoppt
- Nach Status (Host / Lebenszeichen)
- Nach Mode (daemon, scheduled, ...)

Würde die Arbeit mit der Instanzübersicht flexibler machen.

Grüße, Thorsten

**Comment by GermanBluefox** [comment]
"gestartet, gestoppt" ist implementiert

**Comment by GermanBluefox** [comment]
Done

**Comment by Feuer-sturm** [comment]
Admin 5.0.18

Filter für Instanzen ist verfügbar:
![grafik](https://user-images.githubusercontent.com/25422320/117514868-2fb04080-af95-11eb-9691-f51edb7728d3.png)
