### ISSUE TITLE
[enhancement]: Mark stable release in install modal

### ISSUE THREAD

**Issue by ThomasPohl** [ioBroker/ioBroker.admin#2833]
### No existing issues.

- [X] There is no existing issue for my request.

### Related problems

No related problem

### Description

When selecting a specific version of an adapter for installation, it would be highly beneficial if the current stable version was clearly labeled.

This would allow users testing the latest versions to easily identify changes introduced since the last stable release. It would also simplify determining whether an issue is specific to the latest version or already present in the stable release.

### Additional context

This feature would only be relevant if a user is using the latest repository and has enabled expert mode.

**Comment by GermanBluefox** [comment]
It will be only possible if stable repository selected in the configuration

**Comment by mcuiobroker** [comment]
@GermanBluefox You only have to read both Json (stable and latest)?
Or not? Only 200ms.
![image](https://github.com/user-attachments/assets/19d747c4-96c9-4b15-bce5-9a5afc557636)

**Comment by Feuer-sturm** [comment]
is implemented in admin 7.4.8
![grafik](https://github.com/user-attachments/assets/d75c7a4d-d988-4ebb-8cb6-13f84a5a50b5)

**Comment by Feuer-sturm** [comment]
@GermanBluefox I would recommend to use the word "stable" instead of "stabil" in german.

**Comment by Feuer-sturm** [comment]
fixed with 7.4.9
