### ISSUE TITLE
[bug]: Incorrect wording at adapter panel - "There is 123 more"

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.admin#2834]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

![image](https://github.com/user-attachments/assets/af5d782e-038b-4668-8f92-acde571e0edf)

Should read: "There **ARE** ..."

### To Reproduce

Look at adapter panel

### Expected behavior

Test should be "There are xxx more"

### Screenshots & Logfiles

see description

### Adapter version

6.2.6

### js-controller version

5.0.19

### Node version

18

### Operating system

raspian

**Comment by Feuer-sturm** [comment]
admin 7.4.8
Issue is fixed
![grafik](https://github.com/user-attachments/assets/d852071e-3ba4-4960-86f0-7a125a1d0f65)
