### ISSUE TITLE
Export of objects in csv

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#284]
Currently we are able to export objects in JSON format and also use this export as import file.
It would be quite useful if the export option could be extended to CSV format which allows to extract all objects related data (or bij filtering only the shown data) into a CSV file.

Reason : For several administrative actions its useful to have a CSV like output which can be viewed in other applications (like Excel).

Use Case : configuration of Graphana graphs, based on influxDB only the serial number is shown as selectable item and not the name of the device itself. The CSV output would help to find the proper objects needed to build graphs.

Currently I handle this by javascripting but would prefer a out of the box button for that.

**Comment by GermanBluefox** [comment]
Can you provide the Screenshot of excel to catch your idea? Actually I
can't imagine how to export native part in csv

пн, 25 июн. 2018 г., 12:29 Dutchman <notifications@github.com>:

**Comment by GermanBluefox** [comment]
@DutchmanNL ?

**Comment by wendy2702** [comment]
@DutchmanNL : is this still open? 
If yes please provide the requested file. 
If no, please close the issue.

**Comment by DutchmanNL** [comment]
> Can you provide the Screenshot of excel to catch your idea? Actually I

so waiting so long for my answer, I think my first issue explanation did not cover the use case correctly so lets elaborate : 

Use Case : I want to have an easy way to export alle states points there value into states in an CSV or excel format.

Purpose is not to have the whole structure including object information in the export, but an easy way to have the state and value.

Hope this explanation makes more sense

**Comment by GermanBluefox** [comment]
So do you want a table like:
```
ID ; Value; ack
system.id; 5; true
```

**Comment by Apollon77** [comment]
From my point of view also it is the question of purpose.
Exporting OBJECTS (means the object definition) or exporting the state values as Csv??

**Comment by GermanBluefox** [comment]
I will close the issue, as it is not clear what is required
