### ISSUE TITLE
[Feature Request] Add warning to "install from github" dialog

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#285]
A lot of users seem to carelessly install adapters from github and then ask on the forums why stuff isn't working...

Since it is very possible that the github versions are broken in some way, I'd like to see a BIG FAT WARNING in this dialog. Some examples:
* WARNING: Don't install from github unless asked to by a developer or if you are 100% sure what you are doing!
* WARNING: Adapters on GitHub may not work like they should. Only install them if you are participating in a test!
* WARNING: Adapters on GitHub are still under development and may not work. Unless you are participating in a test, please wait for an official release!

**Comment by BuZZy1337** [comment]
Good idea.. Go for it! :relaxed:

**Comment by Hypnos3** [comment]
Idea, also add a link to the doku, where it is explained how to install old version. (maybe http://www.iobroker.net/docu/?page_id=5379)

**Comment by klein0r** [comment]
@GermanBluefox Please close this issue, since the feature has been added to 4.0.5
