### ISSUE TITLE
[bug]: Chinesisch funktioniert nicht.

### ISSUE THREAD

**Issue by ticaki** [ioBroker/ioBroker.admin#2854]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Chinesisch wird nicht angezeigt wenn es in den Systemeinstellungen ausgewählt wird.

zh-ch ist entweder falsch oder der translator macht den Fehler.

die Bezeichnung für chinesisch ist zh-cn

Mit zh-cn finde ich 5.5M Codezeilen, zh-ch nur 103k - duckduckgo findet bei letzterem auch nicht wirklich was mit Sprache

Aufzug aus: https://de.wikipedia.org/wiki/Chinesischsprachige_Wikipedia#Traditionelle_und_vereinfachte_Schrift

> Ursprünglich gab es daher zwei chinesischsprachige Wikipedia-Versionen unter den Sprachkürzeln „zh“ (oder „zh-cn“) für die vereinfachte Schrift und „zh-tw“ für die traditionellen Langzeichen.

Da ioBroker seit bis zu 3 Jahren(lt. git blame) kein chinesisch uberstüzt, sollte man das vielleicht in den News erwähnen. 

### To Reproduce

Sprache umstellen

### Expected behavior

soll angezeigt werden :)

### Screenshots & Logfiles

Der Fehler
https://github.com/ioBroker/ioBroker.admin/blob/000ac03a48b960b3e55a2ef5ca82eb4e1de09ab2/packages/jsonConfig/src/JsonConfigComponent/ConfigLanguage.tsx#L52

Ein Übersetzungsverzeichnis
https://github.com/foxriver76/ioBroker.notification-manager/tree/main/admin/src/i18n

### Adapter version

7.4.3

### js-controller version

7.0.5

### Node version

20.18.1

### Operating system

debian bookworm

**Comment by mcm1957** [comment]
Additional remark
Some language names are starting with an lowercase letter while most start with an uppercase char. Please check if this is due to language specifics or on error (i.e. français, русский)

**Comment by GermanBluefox** [comment]
@ticaki You are absolutely right. It was an error

**Comment by Feuer-sturm** [comment]
admin 7.4.8 it is now possible to switch to chinese language
