### ISSUE TITLE
Konfiguration wird nicht geschlossen

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.admin#286]
Hallo.
Admin 3.4.7, wenn ich dort eine Einstellung ändere und dann den Button "SPEICHERN und SCHLIESSEN" wähle, wird das Konfigurations Fenster nicht geschlossen. Wähle ich danach nur "SCHLIESSEN" erhalte ich Fehlermeldung "Bitte Bestätigen"
![grafik](https://user-images.githubusercontent.com/17329042/42036387-a05e86d0-7ae5-11e8-95b4-90f134af2496.png)

**Comment by WLAN-Kabel** [comment]
Bitte kommentieren oder wiedereröffnen, falls das Problem noch nicht behoben ist.
