### ISSUE TITLE
REDIS Error bei 'iobroker status'

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.admin#287]
'iobroker status' führt zu einer Fehlermeldung. Siehe https://forum.iobroker.net/viewtopic.php?f=22&t=13998&p=158808#p158808

Getestet mit js-controller 1.4.2 und admin 3.4.7 auf meinem Testsystem (Debian in Hyper-V, REDIS aktiviert)
Auffällig: ich hatte zuvor ein Restore von meinem RASPI zurückgespielt.
Ob sich der Fehler auch ohne zuvor eingespieltes Backup reproduzieren lässt, habe ich nicht getestet.

**Comment by GermanBluefox** [comment]
Das ist js-controller issue and was fixed in 1.5.0
