### ISSUE TITLE
3.4.7: 'open web page for adapater' fails for vis.0 and Microsoft Edge

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.admin#289]
ioBroker.admin -> Instances -> visu.0 -> 'open web page for adapater' funktioniert mit Microsoft Edge nicht mehr. Mit anderen Adaptern geht es (getestet für web.0, flot.o, admin.0). Mit Google Chrome funktioniert auch vis.0

**Comment by WLAN-Kabel** [comment]
Bitte kommentieren oder wiedereröffnen, falls das Problem noch nicht behoben ist.
