### ISSUE TITLE
Autologout auf 0

### ISSUE THREAD

**Issue by UweRP** [ioBroker/ioBroker.admin#290]
Wird der automatische Logout auf 0 (NULL) gesetzt ist ein Login nicht mehr möglich.
Dachte damit wird der automatische Logout deaktiviert, ist aber leider nicht so.
Habe mich jetzt ausgesperrt...

**Comment by GermanBluefox** [comment]
iobroker set admin.0 --ttl 3600

пн, 2 июл. 2018 г. в 8:52, Uwe <notifications@github.com>:

**Comment by UweRP** [comment]
Danke! Das hat geholfen :-)
