### ISSUE TITLE
Raum/Licht Zuordnung nicht erreichbar

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#291]
die letzten Datenelemente in der Tabelle sind schwer zu erreichen
![grafik](https://user-images.githubusercontent.com/6681528/42407539-eda7c304-81be-11e8-87e4-b72cfec03f00.png)

**Comment by GermanBluefox** [comment]
Fixed in 3.5.0

**Comment by foxriver76** [comment]
Then it should be closed.
