### ISSUE TITLE
Inaccuracy in russian localization

### ISSUE THREAD

**Issue by kostett** [ioBroker/ioBroker.admin#292]
Swapped point and comma definitions in module settings at initial setup
![photo_2018-07-09_12-16-02](https://user-images.githubusercontent.com/3895729/42441982-27c1eb78-8372-11e8-848c-54c2890237ad.jpg)

**Comment by GermanBluefox** [comment]
Are you sure, that we a speaking about admin?
![image](https://user-images.githubusercontent.com/4582016/42787341-58580810-895a-11e8-8cdf-aa2d2a85b7dc.png)

**Comment by kostett** [comment]
Maybe not, cause this inaccuracy shown in initial setup

**Comment by GermanBluefox** [comment]
Is it on the system settings dialog?
