### ISSUE TITLE
Instanzen sortieren

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.admin#293]
Wäre es möglich in den Instanzen eine Sortiermöglichkeit einzubauen?
Ähnlich der Adapterseite.

Grund:

Die Instanzenseite ist recht unübersichtlich wenn mehrere installiert sind. 
Ich möchte dann gerne beispielsweise die Icons zusammenfassen und ausblenden.
Ebenso die installierten aber inaktiven Instanzen.

**Comment by DutchmanNL** [comment]
Reden wir über Sortierung oder Gruppierung die Instanzen ähnlich zu Adapter Übersicht?

Könnte mir Gruppierung auf Kategorie oder auch zB aktief/inaktiv vorstellen

**Comment by Chaot1** [comment]
Ja, auch eine Gruppierung wäre für mich vorstellbar. 
Zumindest irgendeine Lösung die das Ganze etwas übersichtlicher machen sollte.

**Comment by wendy2702** [comment]
@Chaot1 ist das noch aktuell?

**Comment by Chaot1** [comment]
@wendy2702  Ja, zumindest sehe ich bisher keine Sortiermöglichkeit um z.B. nach aktiven Instanzen zu sortieren.

**Comment by wendy2702** [comment]
OK. Danke für die schnelle Antwort.

**Comment by Feuer-sturm** [comment]
@GermanBluefox Is this issue duplicate to https://github.com/ioBroker/ioBroker.admin/issues/283?
