### ISSUE TITLE
Cannot install adapter via Admin-GUI

### ISSUE THREAD

**Issue by derchirurg** [ioBroker/ioBroker.admin#294]
I'm trying to install an adapter per Web-GUI and getting the following error:

```
$ ./iobroker add daswetter 
npm install iobroker.daswetter --production --prefix "/opt/iobroker" (System call)
Killed
ERROR: host.iobroker Cannot install iobroker.daswetter: 137
ERROR: process exited with code 25
```
Any idea?

**Comment by GermanBluefox** [comment]
Have you seen my suggestion/question here? 
https://github.com/ioBroker/ioBroker/issues/59

**Comment by derchirurg** [comment]
Sorry, I found the issue.
I'm using Docker as virtualization and I didn't give enough RAM.
