### ISSUE TITLE
log doesn't scroll automatically

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#295]
In my latest installation on Odroid C2 with armbian, the log won't scroll automatically. I have to refresh manually.

Nodejs 8.11.3
npm 6.2.0
iobroker 1.2.3
admin 3.4.8

**Comment by GermanBluefox** [comment]
Only one opened page is supported. Are you sure, that only on admin page is
opened?

вт, 17 июл. 2018 г. в 19:29, Homoran <notifications@github.com>:

**Comment by GermanBluefox** [comment]
Are you sure that only one browser tab was opened

**Comment by GermanBluefox** [comment]
Must be fixed now with 3.5.9
