### ISSUE TITLE
Colorize output in log tab and installation logs

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#298]
Previously we could colorize the output in the log window by using html in the log messages, but that feature was removed. It would be cool if there was a way to colorize stuff like on the command line.

I think a good way would be to automatically replace the shell commands for colorized text (like the ones generated with https://www.npmjs.com/package/colors) with html `<span>`s that are colorized in the same way.

Some examples:
```
'abc\u001b[31mdef\u001b[39mghi'
becomes:
'abc<span style="color: red">def</span>ghi'

'\u001b[31mabc\u001b[34mdef\u001b[31m\u001b[39m'
becomes
'<span style="color: red">abc</span><span style="color: blue">def</span>'

// open tags should be closed at the end
'\u001b[31mabc\u001b[34mdef'
becomes
'<span style="color: red">abc<span style="color: blue">def'
and with tag closing:
'<span style="color: red">abc<span style="color: blue">def</span></span>'
```

In consequence this could also be used to colorize the raw output from npm installs in the log included in the installation window for adapters.

**Comment by wendy2702** [comment]
@AlCalzone : is this still open?

**Comment by AlCalzone** [comment]
Admin log text is still black and white, so yeah 😅

**Comment by wendy2702** [comment]
I did not use the log tab at Admin 😬 That’s why i ask.

**Comment by AlCalzone** [comment]
The how do you see if something is wrong?

**Comment by wendy2702** [comment]
Always using Putty :-)

**Comment by GermanBluefox** [comment]
Logs now supports ansi codes:
![image](https://user-images.githubusercontent.com/4582016/119272708-91181680-bc07-11eb-850e-626452ccd22a.png)

**Comment by AlCalzone** [comment]
YEAH! 👍🏻
