### ISSUE TITLE
Don't display installation-/update-buttons if (npm) reqirements are not given

### ISSUE THREAD

**Issue by Stabilostick** [ioBroker/ioBroker.admin#299]
We know that some problems occure using specific versions of npm. Till now the npm version is checked and a warning appears (somewhere deeply hidden from the customers) in the log. The installation of an additional adapter _might_ be working. But sometimes the installation of the whole ioBroker system gets corrupt. 

Why do we offer the install- or update-buttons, when we know something can go horribly wrong using them? Just disable the buttons and instead show a big button "install prerequisites" with "npm install npm@version"-logic behind it on the ioBroker main admin page! So we can be shure, the correct npm-version is used. 

Additional: Download the prohibit list dynamically from iobroker.net, so we can immediatly react to new findings.

**Comment by wendy2702** [comment]
@Stabilostick : is this still open?

**Comment by Apollon77** [comment]
I would close ... we only had one problem with npm versions ... hopefull ythey never break that way again
