### ISSUE TITLE
button.* weden nicht als Button angezeigt

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.admin#300]
Moin, 
 _**button.***_ weden nicht als Button angezeigt

![nvidia geforce overlay-25 07 2018_22_53_27](https://user-images.githubusercontent.com/32074970/43227008-c36037f4-905d-11e8-8a53-f501c461a84a.png)

**Comment by Apollon77** [comment]
Und ja: read: false, type: boolean 

Verified.

**Comment by GermanBluefox** [comment]
Welcher Adapter ist das? Wie sieht common vom Objekt aus?

чт, 26 июл. 2018 г., 0:45 Ingo Fischer <notifications@github.com>:

**Comment by Matten-Matten** [comment]
Folgender Adapter ist das:

https://github.com/Apollon77/ioBroker.alexa2


`
{
  "from": "system.adapter.alexa2.0",
  "ts": 1532555790303,
  "common": {
    "name": "controlPause",
    "type": "boolean",
    "role": "button.pause",
    "read": false,
    "write": true,
    "def": false
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "alexa2.0.Echo-Devices.G090L90971470A7T.Player.controlPause",
  "type": "state"
}

`

**Comment by GermanBluefox** [comment]
Fixed in 3.5.0

**Comment by Kaskadeur111** [comment]
Admin Version 3.6.4 -> Problem besteht (nach wie vor?/wieder?)
Buttons werden nicht als klickbare Symbole angezeigt

Nachtrag: Gerade festgestellt, dass im Expertenmodus true/false und im nicht Expertenmodus der Button angezeigt wird.

Jetzt die Frage, ob das so gedacht ist, könnte mir vorstellen JA.

**Comment by Apollon77** [comment]
Ja das ist so gedachr , da der Expertenmodus das flexible setzen des State Wertes generell erlaubt - auch für Buttons.
