### ISSUE TITLE
Schriftfarbe, -größe, Hintergrundfarbe

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker.admin#301]
Die  graue Schrift auf grauem Hintergrund ist nur sehr schwer lesbar und die  Schrift außerdem im Verhältnis zu den Eingabefeldern zu klein. Betrifft die gesamte Oberfläche des aktuellen ioBroker (Einstellungen bei den Instanzen und Objekten). Alle Eingabemasken haben einen hellgrauen Hintergrund und die Beschreibungstexte bei den Eingabefeldern sind ebenfalls grau (nur etwas dunkler) und außerdem vom Schriftgrad wesentlich kleiner wie der Font in den Eingabefeldern.

**Comment by mhandschuher** [comment]
![cr_oberflache](https://user-images.githubusercontent.com/40818158/43358261-ec89009c-928e-11e8-829e-838f1cc5e6f7.JPG)

**Comment by Apollon77** [comment]
Danke!!

**Comment by thorsten26** [comment]
Die Objektauflistung der Stammknoten ist immer noch grau auf grau (mehr oder weniger)
Seit über 2 Jahren?

**Comment by DcFamas** [comment]
Das stört mich tatsächlich auch. Wäre es möglich die Farbe zu ändern? Gerade wenn ein wenig die Sonne scheint lässt sich einfach nichts erkennen.

**Comment by GermanBluefox** [comment]
in Admin5 gibt es 4 Farbthemen
