### ISSUE TITLE
Allow copy&paste in install-/update dialogue

### ISSUE THREAD

**Issue by mhandschuher** [ioBroker/ioBroker.admin#302]
Currently it is not possible to mark and export displayed messages (especially errors and warnings) within the install-/update dialogue box which makes it difficult to track those messages (except via screenshot).

In addition, the "extended display" should be marked by default as well as the "close when done" should not be set by default.

**Comment by GermanBluefox** [comment]
Done in 3.5.0

**Comment by mhandschuher** [comment]
Thx!
