### ISSUE TITLE
Add flat or floor to enums

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#308]
For Installations with more than one flat/floor it would be nice to have this enum as standard.
Also it would be nice to see this (and other) enums in the object tab.

**Comment by Jey-Cee** [comment]
#365

**Comment by wendy2702** [comment]
@Jey-Cee : do we need to keep this open?

**Comment by Jey-Cee** [comment]
If no one is interested in implementing this, than not.

**Comment by wendy2702** [comment]
Hi,

I will put enhancement label to this issue. Developers should check.

**Comment by Ilovegym66** [comment]
I'm no one :-)
