### ISSUE TITLE
kein Log mehr sichtbar!?

### ISSUE THREAD

**Issue by Matten-Matten** [ioBroker/ioBroker.admin#309]
seit dem update auf ioBroker.admin 3.5.2 hab ich kein log mehr

![nvidia geforce overlay-17 08 2018_23_45_51](https://user-images.githubusercontent.com/32074970/44290206-e7e2ab80-a277-11e8-897c-12b98fdcdf57.png)

**Comment by Ilovegym66** [comment]
sorry, looks not fixed, now with 3.5.3 here the same.. no logs..
NPM4.6.1 Node 8.11.4

**Comment by GermanBluefox** [comment]
iobroker u admin
gemacht?

**Comment by Ilovegym66** [comment]
ja, hab komplett neu installiert, wollte ich sowieso. Lag wohl an verwurschteln npm-node installationen. 
Läuft jetzt einwandfrei, Admin 3.5.3, alles auf latest, NPM 6.4 und Node 8.11.4 
Issue can closed now :-)
