### ISSUE TITLE
Number of events is over 200...

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#310]
Hi,
seit Admin 3.5.3 folgendes dauernd im Log:
`

admin.0 | 2018-08-20 13:44:12.786 | info | Subscribe on all states again
-- | -- | -- | --
admin.0 | 2018-08-20 13:43:11.854 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)
admin.0 | 2018-08-20 13:42:57.751 | info | Subscribe on all states again
admin.0 | 2018-08-20 13:41:56.815 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)

admin.0 | 2018-08-20 13:50:56.798 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)
-- | -- | -- | --
admin.0 | 2018-08-20 13:50:46.801 | debug | system.adapter.admin.0: logging true
admin.0 | 2018-08-20 13:50:46.791 | debug | Subscribes: dummy
admin.0 | 2018-08-20 13:50:46.791 | debug | Change log subscriber state: true
admin.0 | 2018-08-20 13:50:46.791 | debug | Subscribe LOGS
admin.0 | 2018-08-20 13:50:46.690 | debug | Subscribes: system.host.*
admin.0 | 2018-08-20 13:50:46.690 | debug | Unsubscribe STATES: *.info.connection
admin.0 | 2018-08-20 13:50:46.690 | debug | Subscribes: system.host.*, *.info.connection
admin.0 | 2018-08-20 13:50:46.689 | debug | Unsubscribe STATES: system.adapter.*
admin.0 | 2018-08-20 13:50:46.467 | debug | Unsubscribe OBJECTS: system.adapter.*
admin.0 | 2018-08-20 13:50:46.191 | debug | system.adapter.admin.0: logging false
admin.0 | 2018-08-20 13:50:46.183 | debug | Change log subscriber state: FALSE
admin.0 | 2018-08-20 13:50:42.693 | info | Subscribe on all states again

`

Was sagt mir das, ausser, dass mehr als 200 events in der letzten Sekunde 0 ?? waren??

**Comment by GermanBluefox** [comment]
Das es nicht normal ist.

**Comment by Apollon77** [comment]
In der Instanz-Ansicht siehst Du wieviele Nachrichten welcher Adapter so generiert und so ... ist da was drin was so viel erzeugt?

**Comment by Ilovegym66** [comment]
Hmm also History und Javascript sind diejenigen die beide um die ⇥3316 / ↦8  erzeugen.. 
Wenn ich den Historyadapter deaktiviere, zeigt der Javascript immer noch soviel an.. Ich mach mal die History platt, vielleicht ist da ein Bock drin.. soviel logge ich doch garnicht.. sind vielleicht 50 Sensorwerte, mehr nicht...

**Comment by Apollon77** [comment]
Eingehend ist erstmal egal. Ausgehend wäre interessant. 

Beide (History und JavaScript) subscriben auf alle State changes. Ist also ok so ... wobei >3000 State changes in dem gemessenen Zeitraum ist recht viel. 

Musst nix platt machen!!!

**Comment by Ilovegym66** [comment]
war kein Problem.. Ausgehend hab ich so Kanditaten wie Alexa2 ->29, MQTT ->60, Sonoff ->57, alle anderen sind um die kleiner gleich 10.. 
Kann es sein, dass bei 5 Clients und der Host da irgendwie schnell was zuviel wird? 
Jeder Client produziert ausgehend meist zwischen 10-15 events... wenn ich das richtig verstehe..

**Comment by Apollon77** [comment]
Admin sollte aber nur das übertragen was auch aufgeklappt ist...

**Comment by GermanBluefox** [comment]
>  ->29
Das sind nur die STATES Anzeigen. Es geht aber um Objekte Update.

**Comment by GermanBluefox** [comment]
Gefunden?

**Comment by DanielWeeber** [comment]
Habe das identische Problem. Unter Instanzen ist selten 28 als maximaler Wert für ausgehende Ereignisse zu sehen.

Was kann ich tun beim debuggen zu unterstützen?

**Comment by GermanBluefox** [comment]
Das ist kein Bug.



пн, 31 дек. 2018 г., 10:56 DanielWeeber notifications@github.com:

**Comment by DanielWeeber** [comment]
Was generiert die Meldungen denn, wie kann ich das nachschauen?

**Comment by Apollon77** [comment]
Unter Instanzen Expertenmodus bekommst Du angezeigt wieviele State-Updates welcher Adapter macht

**Comment by DanielWeeber** [comment]
Ausgehend habe ich halt bei weitem nicht soviel, wie schon gesagt. Eingehend schon, aber laut dir ist das ja nicht das Problem. Eingehend habe ich bei javascript, mqtt, admin und history ca 150-200 eingehend. Das wars. Rest alles einstellig.

> > ->29
> 
> Das sind nur die STATES Anzeigen. Es geht aber um Objekte Update. Und das sieht man nicht.

**Comment by Apollon77** [comment]
Es geht um State updates ... wenn du mehr als 200 bei admin als Incoming hast dann wird unsubscribed weil die Gefahr besteht das vor lauter "State update traffic" der Rest von Admin zu langsam wird. Also wenn Du sagst Das Admin so viel eingehen hast ist das das Problem. Bringt mich aber zur Frage: Welche Admin version hast du? Bei Admin3 sollte das eigentlich nur vorkommen wenn Du wirklich alles haben willst (alles ausgeklappt, Ereignisse Tab o.ä.)

**Comment by DanielWeeber** [comment]
Bei Admin aktuell 18 incoming. Zum Zeitpunkt wo die Meldung kam kann ich natürlich jetzt nimmer nachschauen.
Version 3.6.0
Ereignisse Tab hatte ich mal probiert, aber bald wieder ausgeblendet, weil keine Chance das zu öffnen.
Vielleicht lags daran.

**Comment by passuff** [comment]
Habe hier das selbe Problem:


admin.0 | 2019-02-25 09:45:05.710 | info | Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)


Incomming states beim Admin variiert zwischen 100 und 300. Woran das liegt weiß ich nicht. Kann man den States flow irgendwo loggen?

**Comment by Apollon77** [comment]
Ok, Was genau hast Du angezeigt im Admin? Die normale Objektansicht oder welche?

**Comment by passuff** [comment]
Sorry, ich bin noch nicht so firm mit iobroker. Was genau meinst du mit: "angezeigt im admin"? Ist admin die Oberfläche?
Aktiviert habe ich: Adapter, Instanzen, Objekte, Log und Skripte.

**Comment by Apollon77** [comment]
Ja Admin ist die Web-Oberfläche. AUf welchem Tab bzw was lässt Du dir anzeigen wenn diese Meldung kommt. Die sollte nicht sofort da sein. Bzw: Admin v3 hoffe ich? Wenn nicht-> Update!

**Comment by passuff** [comment]
Was in diesem Moment geöffnet ist, weiß ich nicht. Ich sehe das immer erst später im Log. Admin ist V3.6

**Comment by Apollon77** [comment]
Dann finde es doch mal raus bitte. SOnst können wir nicht heflen.

An sich sollte nur bei der "State Werte ansicht" wo alle aktuellen Werte reinkommen" das überhaupt passierten

**Comment by AlexanderSch90** [comment]
Hänge mich leider mal dran. Habe auch ein Problem mit dem Admin-Adapter V. 3.6. 
IObroker ist sehr langsam seit ein paar Wochen: Anbei meine Daten: ⇥10005 / ↦8 im Adminadapter. Ähnliche Zahlen im Javascript-Adapter, SQL-Adapter und MQTT-Adapter. Alle weiteren Adapter sind im "einstelligem" Bereich. 

Iobroker läuft in einer Virtuellen Maschine auf einem J5005 - Board. Genug Ram und CPU ist also vorhanden. Ich denke jedoch durch die hohen Werte kommt iobroker trotzdem nichtmehr hinterher...

Was kann ich tun?

Der beschriebene Log kommt immer, egal in welchem Reiter ich mich befinde.

**Comment by Apollon77** [comment]
10k incoming events ... was macht denn da so einen Traffic? Nutzt Du Redis? WEnn nein bitte dringend umstellen

**Comment by AlexanderSch90** [comment]
ok habe ich. Ist schon alles schneller. Der Multihost will jetzt aber nicht mehr... 
Was habe ich gemacht am Master: apt install redis-server ; iobroker setup custom ; States in Redis rest auf default (Enter, Enter, r, Enter, Enter, Enter...)

Dann nano /etc/redis/redis.conf die Bind-Zeile auf bind 0.0.0.0 geändert. Neustart.

Jetzt kommt leider beim Slave folgender Fehler: 

`events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 10.4.4.13:9001
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at doListen (net.js:1510:7)
    at _combinedTickCallback (internal/process/next_tick.js:142:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
`

Beim Master folgendes:

`root@Debian-iobroker:~# sudo iobroker multihost status
Server accept connections for objects on all IP addresses.
Please check the binding of redis service. By default it is only local: http://download.redis.io/redis-stable/redis.conf
Change "bind 127.0.0.1" to "bind 0.0.0.0" or to others.
Please restart ioBroker: "iobroker restart"


Miltihost:      enabled
Authentication: enabled
Objects:        file on 0.0.0.0
States:         redis on 127.0.0.1
 Ready check failed: Connection forcefully ended and command aborted. It might have been processed.
 AbortError: Ready check failed: Connection forcefully ended and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/opt/iobroker/node_modules/redis/index.js:362:23)
    at RedisClient.end (/opt/iobroker/node_modules/redis/lib/extendedApi.js:52:14)
    at StateRedis.destroy (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:272:20)
    at processExit (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2820:44)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2695:33
    at showMHState (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:84:9)
    at Multihost.status (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupMultihost.js:160:9)
    at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:2694:32
    at Object.connected (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:3124:70)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInMemClient.js:120:68)
root@Debian-iobroker:~#
`

Hast du noch ne Idee? Danke!

**Comment by Apollon77** [comment]
On the slave you also need to use "setup custom" but as IP for redis the IP of the master.

For the error on master - which js.controller? In 1.4.2 there is a but with iobroker status showing such an error but anything works

**Comment by AlexanderSch90** [comment]
Sooo jetzt läuft es. Habe nochmal über alles ein Update laufen lassen (Master-Slave) apt-get upgrade und nochmal /.reinstall.sh laufen lassen. Jetzt finden sich die beiden und es gibt auch keinen Fehler mehr. Top!

Der Redis-Tipp war Goldwert! Noch eine letzte Frage: Wie schaffe ich es möglichst einfach die letztes "manuellen States" aus dem Javascript-Ordner auf den letzten Stand zu laden? Nach dem Umzug auf Redis sind die ja alle "NULL".

**Comment by AlexanderSch90** [comment]
das ist zwar nicht ganz das was ich suche, aber ok. Habe jetzt aus dem sql. Adapter die Werte rausgesucht (z.B. Zählerstände) und diese dann einmal manuell eingetippt unter Objekte...

Habe aber anscheinend noch ein Problem durch die Umstellung: 
Nach dem /.reinstall scheint das System aber ein paar Probleme zu haben. Unter anderem funktioneirt der BLE-Adapter nichtmehr. Der ist einfach nur "rot". Wenn ich den dann auf den Master schiebe, bleibt er auch "rot". Kann man den Adapter vielleicht komplett sauber entfernen und dann nochmal neu installieren?


Da ist leider aber auch noch mehr: mehrere Adapter (u.a. sql, Javascript, Text2Command, MQTT) werden nicht mehr unter den Instanzen angezeigt und haben auch keinen Reiter mehr (z.B. "Skripte", "Text2Command") Dennoch funktionieren die Skripte alle weiterhin und per Putty werden die Instanzen auch angezeigt... Im Hintergrund scheint es also zu laufen?!

Ehrlich gesagt habe ich keine Ahnung wie ich das wieder gerade biegen soll.

**Comment by Apollon77** [comment]
Support best in Forum!
