### ISSUE TITLE
remove don't work at clients 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#311]
Hi,
small problem with clients, in the Hosts Menu, if you want to delete it, iobroker says, you must stop iobroker, but if I'm stop iobroker, I can't use the admin-adapter :-)
And when I stop the iobroker on the client, the message is, that it can't be deleted, because iobroker is not running ...

**Comment by wendy2702** [comment]
@Ilovegym66 : Hi, can you please check if deletion is working now!

**Comment by Ilovegym66** [comment]
checked, nothing changed:
![grafik](https://user-images.githubusercontent.com/36229898/80522033-35d80e00-898c-11ea-956c-654f537a79d0.png)

**Comment by wendy2702** [comment]
Which JS-Controller Version at Host and Slave?

Did you try to stop iobroker at slave before deleting?

Are there Instances installed at Slave?

**Comment by DutchmanNL** [comment]
@wendy2702 latest version and controller confirmed

@Apollon77 @AlCalzone do we want this in the interface or should it be a command line exercise only ?

**Comment by AlCalzone** [comment]
I'm not 100% sure about the reasoning here, I don't have multihost. Some thoughts (and **my answers**):
1. Should it be possible to remove the current host while it is running? - **no**
2. Should it be possible to remove a slave while it is running? - **maybe**, it could be stopped first
3. Should it be possible to remove a slave while the master is running? - **no clue**, what's the difference? If not, the above will never work though.

**Comment by wendy2702** [comment]
I have done this some months ago and if i remember correct you always have to stop iobroker at slave, remove slave config at host via command line and the last step was delete the host via Admin.

This was documented at some old iobroker websites.

**Comment by Ilovegym66** [comment]
yes, that's it, wendy2702 ! So the fix is, to give by click on the symbol a guide how to delete it, like the js-controller-update-button.. :-)
or the Admin have to send a iobroker-stop to the slave, and delete the config .. ;-)

**Comment by Apollon77** [comment]
Please revalidate with Admin 5 React UI

**Comment by DutchmanNL** [comment]
@wendy2702 could you test this please ?

**Comment by Feuer-sturm** [comment]
Master: Admin 5.1.9 , js-controller 3.3.13
Slave: Admin 5.1.9 , js-controller 3.3.13

I have no Master Slave on Admin 4 available but under Admin 5 I see no icon how to delete a slave. Is this icon missing or was it removed? @GermanBluefox @Apollon77 


![grafik](https://user-images.githubusercontent.com/25422320/122690795-ca09d200-d22b-11eb-8ca4-2d5153b4218d.png)

**Comment by Apollon77** [comment]
I think in Admin4 it was just telling "only possible when iobroker is turned off" and so was never really working. Slave delete should be done on CLI only I think

**Comment by Ilovegym66** [comment]
Hi, I think we can close this issue, because in Admin5 the "problem" was solved, the icon to delete a host is dissappeared.. ;-)
Was for me the best solution anyway. Spend no time in that, please.
