### ISSUE TITLE
Admin 3.5.5

### ISSUE THREAD

**Issue by vauvau07** [ioBroker/ioBroker.admin#313]
bei Admin 3.5.3 und 3.5.5 sind
in den Instanzen die Funktionen
"Adapter-Webseite öffnen" ohne Ergebnis
bis Admin 3.5.1 noch alles i.O.

node 6.11.5
npm 3.10.10
js-controller 1.4.2

**Comment by Ilovegym66** [comment]
funktioniert hier mit 
node 8.11.4
npm 6.4
js-controller 1.4.2

**Comment by vauvau07** [comment]
funktioniert bei mir (Testsystem) auch mit
node 8.11.4
npm 4.6.1
nur mit node 8 habe ich dann noch andere Probleme , aber die können warten

**Comment by vauvau07** [comment]
mit admin 3.5.6 jetzt i.O.
