### ISSUE TITLE
Aufzählungen / Enums erzeugen im Cloudadapter Smartgerät  object-object-object

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#314]
Hi,
ich weiß nicht, ob das hier richtig ist, aber seit Admin 3.4.5 (oder so) werden bei Änderungen in den Aufzählungen ( egal ob im Tab Aufzählungen was ändere ) oder in den Objekten Räume und Funktionen zuweise, im Cloud Adapter Smartgeräte mit dem Namen Object-Object-Object-xxxx angelegt. 

Das ging heute sogar soweit, dass ich, da ich viele Änderungen in den Enums gemacht habe, meine ganzen alten Smartgeräte nicht mehr im Cloudadapter angezeigt wurden, und diese auch nicht mehr von Alexa aus erreichbar waren... :-1: 
Anscheinend verkraftet der Cloudadapter nur eine kleine begrenzte Anzahl an Smartgeräten??

Bitte dieses "Feature" schaltbar machen, dass man in Ruhe Änderungen vornehmen kann, aber die Cloud nicht gleich beeinflusst wird. Anschliessend ein "scan" und es werden auf Wunsch Smartgeräte angelegt.

**Comment by GermanBluefox** [comment]
Issue gehört zu Cloud Adapter.

Trotzdem die cloud-Version vom github ausprobieren.
