### ISSUE TITLE
Cloud Adapter mit Authentifizierung aktiviert

### ISSUE THREAD

**Issue by meicker** [ioBroker/ioBroker.admin#315]
Wenn die Authentifizierung aktiviert ist im Admin und man sich über den Cloud Adapter verbindet wird der Admin zwar geladen aber wenn man einen Tabwechsel macht bekommt man wieder eine Loginseite angezeigt. Nach erfolgreichem Login ist der Admin im Admin fenster geöffnet, praktisch 2x sichtbar. Das lässt sich unendlich fortsetzen.
![screenshot_2018-08-23 iobroker admin](https://user-images.githubusercontent.com/11345937/44532657-e986f600-a6f3-11e8-8211-3d2032c512b2.png)

**Comment by GermanBluefox** [comment]
Aktuell, sollte man für cloud extra admin ohne authentication verwenden.
Einfach gegen localhost binden und zu Cloud.instance zuweisen.

чт, 23 авг. 2018 г. в 16:45, meicker <notifications@github.com>:

**Comment by Apollon77** [comment]
Glaube die Idee hier ist da eine sinnvolle Fehlermeldung zu machen anstelle so einem komischen Verhalten ;-)

**Comment by GermanBluefox** [comment]
Lass issue hier hängen. Eigentlich soll es funktionieren. Muss suchen

Ingo Fischer <notifications@github.com> schrieb am Do., 23. Aug. 2018,
19:15:

**Comment by meicker** [comment]
Guten Morgen 😊

extra Admin ? - also für Cloud eine 2te Admin Instanz ? Oder den Admin einfach ohne Authentifizierung laufen lassen und Localhost wählen ? Ich würde nämlich sonst jetzt einfach den Admin auf Localhost setzen, aktuell hört er auf alle Verbindungen. 

Viele Grüsse,
Marc

**Comment by GermanBluefox** [comment]
Aber dann kannst du Admin nicht in deinem Netz verwenden. Nur auf dem Rechner.

Ich schlage 2te Instanz ohne Authentication.

**Comment by meicker** [comment]
schon gemerkt. Hatte mich eben mal kurz komplett ausgeschlossen. 

Also Du meinst 1. instanz mit 2. ohne für Cloud verbindung, richtig ?

Die für lokal auf die IP vom Raspberry oder auf alle hören
Die für die Cloud auf ? setzen ?

Viele Grüsse,
Marc

**Comment by wendy2702** [comment]
@meicker Hi, kann das geschlossen werden?

**Comment by meicker** [comment]
moin,

ja - kann geschlossen werden. 

Viele Grüsse,
Marc
