### ISSUE TITLE
[Feature Request] Adapter Update auslassen / überspringen

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.admin#316]
Ich habe gerade einen Fall, in dem eine aktuelle Adapterversion bei mir nicht störungfrei funktioniert, eine ältere Version hingegen schon.

Wie wäre es mit einer Funktion die es mir gestattet eine Version zu "ignorieren" damit diese mir nicht erneut angeboten wird.

Kommt jedoch eine neue Version, die womöglich das Problem bei mir löst, dann will ich wieder benachrichtig werden.

Vielleicht wäre ein Lösungsansatz die Expertenfunktion (Auswahl einer älteren Version) so zu erweitern, dass man jede dieser Adapter-Versionen optional mit einem "ignorieren" Kennzeichen (anhaken) versehen kann?

**Comment by GermanBluefox** [comment]
implemented in Admin5
