### ISSUE TITLE
Admin 3.5.6 - Einstellungen speichern

### ISSUE THREAD

**Issue by meicker** [ioBroker/ioBroker.admin#318]
Wenn man in den Einstellungen vom Admin etwas geändert hat und Speichern & Schließen drückt wird der Admin nicht geschlossen. Wenn man dann auf schließen drückt kommt eine Abfrage ob wirklich geschlossen werden soll da die Einstellungen noch nicht gespeichert sind.
Die Einstellungen werden gespeichert, aber auch richtig ?

**Comment by wendy2702** [comment]
Please reopen or open a new issue if still active with actual Version of Admin.
