### ISSUE TITLE
Upgrade socket.io to 2.1.1+

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#320]
In order to get rid of  several vulnerabilities we need to upgrade socket.io to 2.1.1 for Admin.

**Comment by Apollon77** [comment]
@GermanBluefox Soll ichs mal machen?

**Comment by GermanBluefox** [comment]
Da express und socket io zu probleme führen können. Habe ich natürlich
bedenken.

ср, 29 авг. 2018 г., 9:09 Ingo Fischer <notifications@github.com>:

**Comment by Apollon77** [comment]
Admin nutzt auch Express ... ok, dann ... aber würde das Ticket lassen damit wir es nicht aus dem Auge verlieren
