### ISSUE TITLE
Admin Einstellungen "Google Maps kann auf dieser Seite nicht richtig geladen werden"

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.admin#321]
Ist diese Meldung bei den Einstellungen im Admin Adapter OK, oder muss ich mir hier Gedanken machen? 
![grafik](https://user-images.githubusercontent.com/36501310/44897021-92d47a00-acfa-11e8-8529-a5fad1724da2.png)
Admin 3.5.7
JS Controller 1.4.2
node 8.11.14
nodejs 8.11.14
npm 4.6.1

**Comment by BuZZy1337** [comment]
Nein, du musst dir keine Gedanken machen. Der Fehler liegt nicht bei dir.
Wir kümmern uns drum. :relaxed:

**Comment by ihavenonick** [comment]
Alles klar und Danke für die schnelle Antwort. 
Hat das irgendwelche Auswirkungen auf andere Funktionen des IOBroker, oder ist das reine Kosmetik?

**Comment by BuZZy1337** [comment]
Nein,.. Ist nur "Kosmetik". :wink: 

Gruß

**Comment by GermanBluefox** [comment]
Fixed
