### ISSUE TITLE
setObject id missing!!

### ISSUE THREAD

**Issue by grritvrij** [ioBroker/ioBroker.admin#322]
Made a clean installation today on ubuntu 18.4 LTS with node 8 and npm 6.4.1
Using admin from latest repository i get the error setObject id missing!! after systeem boot.

![iobroker_admin_error](https://user-images.githubusercontent.com/32968632/44956536-c9122500-aec5-11e8-99d0-e125bb810b3c.JPG)

**Comment by Apollon77** [comment]
This is a know non critical issue in js-controller 1.4.2 and can be ignored. Will be fixed in next js-controller version

**Comment by GermanBluefox** [comment]
No. It cannot be fixed... User must manually fixed it.
stop iobroker
open objects.json file
and delete object with 
`_id:""`

**Comment by Apollon77** [comment]
No the issue comes from creating all instance objects on Adapter Start. Some Adapters have an instanceobject with an empty is in their io-package. A fix after 1.4.2 handled this correctly

**Comment by DutchmanNL** [comment]
@GermanBluefox 

thats the interesting part of this issue, the installation was fresh without any adapter configured or installed so i guess the behaviour is wrong that on a very clean install this issue already occurs

@Apollon77 
thank you

**Comment by Apollon77** [comment]
Will not happen with js-Controller >1.4.2 .. but as said uncritical!! Simply ignore

**Comment by GermanBluefox** [comment]
But if the object is created it will not disappear itself. User must delete them.

**Comment by Apollon77** [comment]
It got never created because this was the check before stating that he should create an objects with an empty id ... this is the error, so the object is not existing
