### ISSUE TITLE
Volvo On Call Adapter

### ISSUE THREAD

**Issue by meden01** [ioBroker/ioBroker.admin#323]
Hi all,
Volvo has, similar to BMW Connected Drive, his own cloud solution for controlling features of the cars with VOC enabled. Many important information is available on the Android and iOS App, like service demands, fuel, any kind of issues, controls for horn, door locks, head lights etc. Since the amount of hybrid cars is increasing, also the charging status is an important information, which could be used to control push messages (not included in the app) as well as controlling the charging cycle at home via homematic actors. Has anybody a chance to develop such an adapter?
kind regards

**Comment by Apollon77** [comment]
https://github.com/ioBroker/AdapterRequests/issues is the correct place for such a request
