### ISSUE TITLE
Feature idea: colorize log output differently per adapter

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#324]
This allows to easily distinguish between the logs of different adapters without setting a filter.
Quick'n'dirty example in Photoshop, the text should stay black of course.
![unbenannt-1](https://user-images.githubusercontent.com/17641229/45254762-b42e0980-b37d-11e8-8e57-a12ce743aab6.png)

**Comment by GermanBluefox** [comment]
Should be possible, because text colour is even now different. Just to
change background colour

сб, 8 сент. 2018 г., 15:42 AlCalzone <notifications@github.com>:

**Comment by GermanBluefox** [comment]
The Problem is, which color for which adapter?

**Comment by AlCalzone** [comment]
We could have a fixed set of colors and just assign them depending on the start order or something.

**Comment by GermanBluefox** [comment]
Implemented

**Comment by Feuer-sturm** [comment]
Admin 5.1.4
Coloured log is implemented:
![grafik](https://user-images.githubusercontent.com/25422320/120024122-05c7c800-bfef-11eb-9d97-6e66c350438b.png)
