### ISSUE TITLE
v.3.5.9 Disable logging, because no one socket connected

### ISSUE THREAD

**Issue by Mr-REM-Esq** [ioBroker/ioBroker.admin#325]
admin.0 | 2018-09-19 03:03:36.218 | warn | Disable logging, because no one socket connected
-- | -- | -- | --
admin.0 | 2018-09-19 02:45:51.199 | warn | Disable logging, because no one socket connected
admin.0 | 2018-09-19 02:45:51.194 | warn | Disable logging, because no one socket connected
admin.0 | 2018-09-19 02:44:52.688 | warn | Repository cannot be read. Invalid "system.config" object.
admin.0 | 2018-09-19 02:44:52.633 | info | Repository received successfully.
admin.0 | 2018-09-19 02:44:51.047 | info | Use link "http://localhost:8081" to configure.
admin.0 | 2018-09-19 02:44:51.047 | info | http server listening on port 8081
admin.0 | 2018-09-19 02:44:51.018 | warn | Repository cannot be read. Invalid "system.config" object.

**Comment by peer69** [comment]
Same here since update on 3.5.9

**Comment by foxriver76** [comment]
Still happening on 3.5.10?

**Comment by wendy2702** [comment]
Please reopen or open a new issue if problem occurs again.
