### ISSUE TITLE
backup only backs up vis.0

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#327]
I don't know where the best place is to post this .. but backup reliably only backs-up vis.0.
a) via sudo backup in /opt/iobroker
b) via backitup adapter (which .. as far as I know) uses the same command
br

**Comment by GermanBluefox** [comment]
What is the desired behavior ? 
There is no need to store other folders.

**Comment by daniel-lo** [comment]
You are confusing me. Vis.0 is only one adapter/instance but IMO backup should backup my complete ioBroker config .. so I'd expect all Instanzes to be in that archive - not only Vis.0. Am I misunderstanding something? How would I recover my configuration when my SD breaks .. with just Vis.0?

**Comment by Apollon77** [comment]
Modt config is stored as Object properties and there for it is part of the objects db json.

**Comment by daniel-lo** [comment]
So the json contains the config of all instances and the blockly scripts etc.? Then I was completely misled .. apologies.
