### ISSUE TITLE
States with blanks only updated after browser refresh in tab objects

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#329]
appeared at: https://forum.iobroker.net/viewtopic.php?f=20&t=17728&p=185668#p185668

Admin: 3.4.7
js-controller: 1.4.2

Can be reproduced by 

```javascript
let i = 0;

createState('javascript.0.test');
createState('javascript.0.test test');

setInterval(() => {
    setState('javascript.0.test', i, true);
    setState('javascript.0.test test', i, true);
    i++;
}, 5000);
```

Activating the script and switching to tab objects, you can observe that the state without blanks is updated every 5 seconds. The new value of the state with blanks only appears after Browser Refresh. Rebuild tree button doesn't help.

**Comment by wendy2702** [comment]
Please reopen or open a new issue if problem is still visible with actual versions of Admin and JS-Controller

**Comment by wendy2702** [comment]
Thanks for feedback.
