### ISSUE TITLE
[Feature Request] Adapter list add filter to show all installed adapters

### ISSUE THREAD

**Issue by Xyolyp** [ioBroker/ioBroker.admin#332]
I don't have any use for the filter "only show adapters with instances" but I searched for a "show all installed adapters" filter multiple times by now. 
Maybe even a filter like "display all installed adapters without instances" and a quick uninstall button to clean up an installation after trying out new adapters.

**Comment by wendy2702** [comment]
@GermanBluefox @Apollon77 Enhancement

**Comment by WLAN-Kabel** [comment]
Duplicate #281
