### ISSUE TITLE
[Feature Request] Add ServiceWorker to push notifications

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#333]
We could add a ServiceWorker to push notifications from Admin like errors or updates... (It works only with https).

See example in admin-neo:

https://github.com/ldittmar81/ioBroker.admin-neo/search?q=serviceWorker&unscoped_q=serviceWorker

**Comment by wendy2702** [comment]
@GermanBluefox @Apollon77 enhancement

**Comment by GermanBluefox** [comment]
Service worker works only with valid https pages. ioBroker has very seldom valid https certificates
