### ISSUE TITLE
Anmelden unter Firefox 

### ISSUE THREAD

**Issue by MathiasJZ** [ioBroker/ioBroker.admin#335]
Ich  melde mich bei Firefox als admin an. Dann kommt der Aufruf
192.1xx.x.xx:8081/%2F/
Danach arbeitet sich IObroker zu Tode.
Erst nachdem ich %2F/ gelöscht habe, ist Ruhe. Das Problem tritt nur bei Firefox auf. Bei meinen anderen Browsern Chrome, Opera und MS edge  habe ich das Problem nicht.
Gruß,
Mathias

**Comment by foxriver76** [comment]
Kannst du bitte genau beschreiben, was du meinst mit: 
``Du meldest dich bei Fritzbox an und dann kommt der Aufruf .. ?``

**Comment by MathiasJZ** [comment]
Entschuldige, ich habe mich falsch ausgedrückt.
Ich melde mich selbstverständlich bei der WebUI des IObrokers an.
Den Rest kennst Du ja.
Was mich aber stutzig macht, ich habe das nur beim Testsystem der piVCCU.
Auf der Installation der Beebox habe ich kein Problem.
Gruß,
Mathias

Am 2. Dezember 2018 11:16:14 schrieb Max Hauser <notifications@github.com>:

**Comment by foxriver76** [comment]
Kann das leider nicht nachstellen bei mir (mit FF v63).

**Comment by foxriver76** [comment]
Allerdings führt ein Aufruf von

`https://<ip>:8081/%2F/`

zum dem von dir beschriebenen Verhalten.

**Comment by wendy2702** [comment]
Please reopen or open a new issue if problem occurs again.
