### ISSUE TITLE
admin-tab Skripte wird nicht geladen

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.admin#336]
seit der Version 3.5.10 wird bei mir  in Edge und Chrome der Tab Skripte nicht volständig geladen.
![image](https://user-images.githubusercontent.com/24899637/49600281-244f2a00-f983-11e8-8f89-37f250e054af.png)

Ich habe keine blockly-Skripte, kann es daran liegen?

**Comment by Hypnos3** [comment]
Ich hab seit aktualisierung auf 4.0.3 gleiches Problem, allerdings ist der Fehler etwas anders:
![image](https://user-images.githubusercontent.com/12692680/49614118-a2bec280-f9a9-11e8-8035-cf1fceeaaa82.png)

```
GET http://192.168.178.221:8081/adapter/places/blockly.js net::ERR_ABORTED 404 (Not Found)
value @ BlocklyEditor.js:62
value @ BlocklyEditor.js:76
value @ BlocklyEditor.js:96
value @ App.js:194
onReady @ App.js:138
(anonymous) @ Connection.js:60
(anonymous) @ Connection.js:221
setTimeout (async)
(anonymous) @ Connection.js:204
n.onack @ socket.io.js:4
n.onpacket @ socket.io.js:4
(anonymous) @ socket.io.js:4
n.emit @ socket.io.js:3
n.ondecoded @ socket.io.js:2
(anonymous) @ socket.io.js:4
r.emit @ socket.io.js:2
s.add @ socket.io.js:2
n.ondata @ socket.io.js:2
(anonymous) @ socket.io.js:4
n.emit @ socket.io.js:3
n.onPacket @ socket.io.js:3
(anonymous) @ socket.io.js:3
n.emit @ socket.io.js:3
n.onPacket @ socket.io.js:3
n.onData @ socket.io.js:3
ws.onmessage @ socket.io.js:4
```

**Comment by GermanBluefox** [comment]
PLease test 4.0.5 And this is a wrong place for issue for ioBroker.javascript.
