### ISSUE TITLE
SelectID - Scrolling funktioniert nicht

### ISSUE THREAD

**Issue by jensweigele** [ioBroker/ioBroker.admin#337]
Scrolling im SelectID Fenster funktioniert nicht.
Zu sehen bei der Konfiguration von Yahka - bei der Auswahl eines Datenpunktes.

Der Grund ist wohl, das der Scroll-Bereich (Element "<div class="grid-main-wob-div">") die Höhe "calc(100% - 103px)" als Eigenschaft hat, wobei die 100% sich auf die komplette Page Höhe bezieht.

Siehe auch https://github.com/jensweigele/ioBroker.yahka/issues/50

**Comment by wendy2702** [comment]
@GermanBluefox @Apollon77 : i know that this problem still exists.

Is it Admin issue or Adapter issue ?

**Comment by Apollon77** [comment]
admin

**Comment by Jan-2005** [comment]
habe auch das Probleme das ich nicht Scrollen kann wenn ich einen State in der liste ID auswahl wählen will.

**Comment by Apollon77** [comment]
@jensweigele Please recheck with Admin5 React UI

**Comment by SidM01** [comment]
Hallo, ich habe ebenfalls das Problem mit dem Yahka Adapter dass ich nur mit den Cursortasten scrolle kann und nicht per Maus.
Auch über Touch z.b. am iPad ist das nicht möglich. Auch der aktuelle Admin Adapter in der v5.1.23 installiert, bringt keine Abhilfe.

Weitere Ideen?

Vielen Dank!

**Comment by Feuer-sturm** [comment]
I just made a simple check with Yahka and admin 5.3.7 (I have no Yahka in use).
Here it is possible to scroll. A scrollbar is available.
![grafik](https://user-images.githubusercontent.com/25422320/163049129-8e55fd51-51e7-48bc-9da7-396b5670e619.png)

Please open a new issue if there is still a problem. Issue closed.
