### ISSUE TITLE
BUG. Error objects are not deleted.

### ISSUE THREAD

**Issue by instalator** [ioBroker/ioBroker.admin#338]
![image](https://user-images.githubusercontent.com/11523624/49742496-428e9000-fccb-11e8-9da0-ce1d4b472dfb.png)
![image](https://user-images.githubusercontent.com/11523624/49742518-50441580-fccb-11e8-9a64-1ddf82a9afb3.png)

[mqtt.0.myhome.Boiler.zip](https://github.com/ioBroker/ioBroker.admin/files/2663719/mqtt.0.myhome.Boiler.zip)

**Comment by Apollon77** [comment]
I think the problem is more the characters like "!" and " " in the id ...

**Comment by instalator** [comment]
I can not remove it from the admin panel. writes an error: The object "mqtt.0.myhome.Boile0�myhome" does not exist. Refresh the page.

**Comment by DutchmanNL** [comment]
which admin and JS-controller version are u using

**Comment by instalator** [comment]
Admin - 3.5.10
JS-controller -  1.4.2

**Comment by DutchmanNL** [comment]
for me it looks like an illegal character has been used to create this state.
As the backend are linux based this illegal character causes an issue for the controller to find the real state.

Can you try to delete the whole tree instead of just this object, what happens than ?

**Comment by instalator** [comment]
This object created the mqtt driver. I can not delete, the error is the same
![image](https://user-images.githubusercontent.com/11523624/50726234-cd34a480-113c-11e9-8cf9-9b512036a756.png)

**Comment by DutchmanNL** [comment]
I understand, but did you try to delete the whole tree "boiler" so not an separate state but the folder ?
can you share a screenshot ? When hitting delete you should get the question delete ALL underlying states

**Comment by instalator** [comment]
The object "mqtt.0.myhome.Boile0���myhome" does not exist. Refresh the page.
![image](https://user-images.githubusercontent.com/11523624/50726356-75973880-113e-11e9-8512-3b99fee72122.png)
The second folder is deleted with all nested objects.

**Comment by Zwer2k** [comment]
I have the same problem.
The key is also created by mqtt adapter.
![image](https://user-images.githubusercontent.com/10438794/79805043-956b6380-8365-11ea-8294-85f4016de05d.png)

In Redis the entries look like this:
```
192.168.0.10:6379> keys *Gartenha*0*
1) cfg.o.mqtt.0.Gartenha0_.Gartenhaus.InnerP
...
3) io.mqtt.0.Gartenha0_.Gartenhaus.InnerP


```

**Comment by Apollon77** [comment]
It more seems that you have some completely damaged object IDs with invalid characers in it ... where are they from? I think they needs to be handled manually

**Comment by instalator** [comment]
It is impossible to delete them via WEB, I deleted only manually in the file ....\ioBroker\iobroker-data\objects.json. Be sure to backup the file.

**Comment by Zwer2k** [comment]
The errors come from the faulty MQTT communication.
I cannot delete the entries via object view and .\ioBroker\iobroker-data\objects.json I don't have because I use Redis.

**Comment by Coalado** [comment]
Same issue for me. Mqtt Adapter with ESPEasy.
![image](https://user-images.githubusercontent.com/21013026/80832351-cad94200-8bec-11ea-847b-acb09bfe2e69.png)

**Comment by instalator** [comment]
> Same issue for me. Mqtt Adapter with ESPEasy.
> ![image](https://user-images.githubusercontent.com/21013026/80832351-cad94200-8bec-11ea-847b-acb09bfe2e69.png)

Could you test this adapter to solve the problem?
https://github.com/instalator/ioBroker.reanimator

**Comment by Zwer2k** [comment]
Thank you for your work Instalator. I only find objects that were created before the activation of Redis. This means that the adapter cannot work with Redis. Can you possibly extend it?

**Comment by Coalado** [comment]
> > Same issue for me. Mqtt Adapter with ESPEasy.
> > ![image](https://user-images.githubusercontent.com/21013026/80832351-cad94200-8bec-11ea-847b-acb09bfe2e69.png)
> 
> Could you test this adapter to solve the problem?
> https://github.com/instalator/ioBroker.reanimator

Can you give me some information about what the adapter actually does?

**Comment by instalator** [comment]
> Thank you for your work Instalator. I only find objects that were created before the activation of Redis. This means that the adapter cannot work with Redis. Can you possibly extend it?

Maybe the community will finish it or when I start using Redis
