### ISSUE TITLE
[Enhancement] Show Changelog in a dialog befor each adapter update

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#339]
Most user do not know that they can see the update change log by going with mouse over the version number. 

We should add the following to the UI:
* When you klick on the update icon for one adapter then a dialog should open which shown the Changelog for this update and offer the use buttons "Cancel" and "Update"
* When useris doing bulk updates in Admin UI also a dialog should open which shows All the changelogs (maybe with a bild adaptername and paragraph or such to separate per adapter. The Dialog should also have "Cancel" and "Update "Buttons
* Updates using CLI stay untouched

**Comment by ldittmar81** [comment]
Give it to me 😎! I'll do it.

**Comment by Apollon77** [comment]
you are invited

**Comment by Seqway** [comment]
I want to push this request up because i miss the Changelog e.g. for the js-controller; there is no "?" like for the other adapters to see what has changed in the new Version. Thank you!
Hope this is the right issue, otherwise delete it and i open a new issue.

**Comment by Apollon77** [comment]
ALso make sure that major changes are displayed "highlighted"

**Comment by GermanBluefox** [comment]
Done
