### ISSUE TITLE
[Enhancement] Add Info for user when switching from default/stable to latest repo

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#342]
it is very easy for users to switch the repo without knowing what they are doing. or someone in forum told them.

The UI should show an Info message when a user switched from default/stable to latest repo. Text could say:

> Das "Latest" Repository enthält Adapterversionen, welche nicht vollständig getestet sind. Probleme mit diesen Versionen bitte beim Entwickler bzw in den relevanten Forum-Threads melden. Die Nutzung geschieht auf eigenes Risiko.

Das ganze könnte man als roten Text neben/unter der Selection anzeigen oder beim Speichern in einem extra Dialog. (denke ersteres reicht hier auch)

**Comment by Apollon77** [comment]
Maybe also an idea to change from a selection to two radio buttons whewre we can add crear descriptive texts to both that tell about options and consequences

**Comment by Apollon77** [comment]
maybe we could also add a "educational popup" on admin start once a month or such that is shown to people with latest repo selected and ask if it is still needed :-)

**Comment by GermanBluefox** [comment]
Done
