### ISSUE TITLE
ioBroker.admin undefined

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#344]
Hallo,

habe bei Pro folgende Fehler und komme nicht in den Admin:

ioBroker.admin undefined

![screenshot 1427 _li](https://user-images.githubusercontent.com/41079106/50367201-da6b6400-057e-11e9-85c0-a9b285568e7b.jpg)

Alle Adapter sind Grün.

Ich möchte den Pro Admin über einen Link von der Übersichtsseite aufrufen.
Sehe gerade komme auch nicht auf die VIS.

`Die Website ist nicht erreichbar iobroker.pro hat die Verbindung abgelehnt.`

LOG:

`admin.0	2018-12-21 23:41:01.197	info	Use link "http://localhost:8081" to configure.`

Sigi

**Comment by Apollon77** [comment]
Ppuuuhhhhhh ... ok ... würde ich nicht empfehlen. Admin per Cloud hat einige Einschränkungen. Keine live States Updates. Keine Logs bei adapter install/updates. Keine live Logs. Und noch ein paar Dinge. Von der ggf Performance mal abgesehen. 

Zur eigentlichen Frage: ich denke das issue hier ist eher das wohl alle Links der Übersicht Seite auf localhost zeigen und das ist falsch. Siemüsdten auch auf die relativen Cloud URLs umgebogen werden. 

Aber die Admin Kachel brauchst du halt nicht weil das was du siehst IST der Admin.

**Comment by sigi2345** [comment]
> Sie müssten auch auf die relativen Cloud URLs umgebogen werden.

Ja das ist es, ist das ein Bug oder ein Fehler von mir........

**Comment by wendy2702** [comment]
@sigi2345 : ist das noch offen oder kann das zu ?

**Comment by sigi2345** [comment]
> @sigi2345 : ist das noch offen oder kann das zu ?

zu
