### ISSUE TITLE
[Enhancement] Add a enum to an other enum

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#345]

**Comment by DutchmanNL** [comment]
hmm, why should that be done ?

I understand the usability but usecase is unclear. When an enum can be part of enum the visibility within ioBroker admin gets lost as you will only see the directly assigned part not the indirect assigned one.

So in relation to cons in usability, what is the benefit of having this ?

**Comment by Jey-Cee** [comment]
Situation: 1 House with 3 flats and 4 floors

Example for usecase: For the visualization i want to see only the things whats are in my flat. OK i can name the rooms like 'kitchen_1', 'kitchen_flat1' or something like this. It is ok when i create my own visualization, but that isnt a good way for automatic generated one. 
For managment and control of the hole object it is interesting to see the hole object or only a floor.

For now this means i have to add all my devices to a enum flat, floor and rooms separately. 
The easiest way is to add all devices to a room and add this room to the flat and the flat to the floor.

**Comment by DutchmanNL** [comment]
ok now i understand makes sence :+1: 

only thinking about how to visualize this. Looking at the object from admin perspective it must be clear if you add the device to room x on floor y the state is also in floor t (now you would only see room x)

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/308
