### ISSUE TITLE
HealthCheck funktion

### ISSUE THREAD

**Issue by OMCastle** [ioBroker/ioBroker.admin#346]
Hallo zusammen,

Ich befasse mich gerade mit der Performance meines OrangePi und halte eine Unterstützung in IOBroker für „Linux-Anfänger“ für sinnvoll. 

ich fände es super, wenn das Admin Tool um Health und Peformancechecks erweitert wird. 
1) TOP
2) ioWait
3) Nodejs Versionen
4) Watchdog für wichtige Prozesse mit aktiver Warnung, wenn die Sterben oder so..
5) Anzahl Datenpunkte
6)???
7) alles was ihr noch für sinnvoll und wichtig haltet 

Grüße
Oliver

**Comment by Apollon77** [comment]
Anzahl States gibt es heute schon unter “Objekte“. Rest ist Die frage ob das in Admin gehört oder nicht sinnvoller eigene Adapter sind mit eigenem Admin tab.

**Comment by OMCastle** [comment]
Gerne auch in Form eines neuen adapters. 
Eine Art Performance und HealthCheck Monitor mit einem möglichst standardisierten „Tech-Report“ würde ioBroker aus meiner Sicht gut zu Gesicht stehen.

**Comment by Apollon77** [comment]
Legst du das als Idee bitte bei den adapterRequsts mal an?! Danke

Und Idee gern auch im Forum vorstellen und um abstimmen bitten bei dem GitHub Adapter request ;-)

**Comment by OMCastle** [comment]
Danke. 
Ich Habe einen Adapterrequest erzeugt. 

https://github.com/ioBroker/AdapterRequests/issues/146

**Comment by Apollon77** [comment]
Danke!!
