### ISSUE TITLE
[Enhancement] Add more guidance on nodejs/npm versions and show ninfo if minimum version per LTS is not met

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#349]
We know that certain nodejs versions and also npm versions have problems.

e.g. npm between 5.0.0 and 5.7.1 or nodejs <8.12.0 have a memory leask and node < 10.13 (or such) have a bug in timeouts.

We should be able to tell such things to the users and inform them about problems and provide links for instructions (e.g. forum or website).
The basic infos should be loaded dynamically (no adapter update needed!) or be added to the repo file (maybe better idea).

A popup is shown with a text and link to inform user on any admin start till problem is fixed

**Comment by ldittmar81** [comment]
Sinse Admin 3.6.7 and info 1.5.3 you can show a message if node version is between x and y.

**Comment by ldittmar81** [comment]
{
        "title": {
            "en": "Your Node Version have a memory leask", "de" ....            
        },
        "content": {
            "en": "Bla, Bla.. install 10.x", "de"....
        },
        "id": "nodejs",
        "node-version": "between(8.0.0,8.12.0)",
        "class": "error",
        "fa-icon": "ban",
        "created": "2019-10-08T00:00:00.000Z",
        "conditions": { }
},
{
        "title": {
            "en": "Your Node Version have a bug in timeouts", "de" ....            
        },
        "content": {
            "en": "Bla, Bla.. install 10.x", "de"....
        },
        "id": "nodejs",
        "node-version": "between(10.0.0,10.13.0)",
        "class": "error",
        "fa-icon": "ban",
        "created": "2019-10-08T00:00:00.000Z",
        "conditions": { }
}

**Comment by Apollon77** [comment]
Cool. Can you also add "Npm" check?
And a "nodejs 12.x is not jet officially supported, use on your own risk"
And nodejs 7/9/11/13 is development version and not officially supported ..."

**Comment by ldittmar81** [comment]
If you tell me how to get the npm version then I'll add it.

For node 12.x you can use "node-version": "between(12.0.0,12.99.99)"

For node 7/9... you must copy the text for each one and set "node-version": "between(7.0.0,7.99.99)"

**Comment by Apollon77** [comment]
npm: https://github.com/ioBroker/ioBroker/blob/master/lib/checkVersions.js#L46

**Comment by ldittmar81** [comment]
https://github.com/ioBroker/ioBroker.admin/pull/440
