### ISSUE TITLE
Filter in Adapter list

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#350]
How come the filter never gives me any hits?

**Comment by Apollon77** [comment]
Please provide more details. Which filter is not working?

**Comment by daniel-lo** [comment]
The search field on top .. that filters the adapter list.

**Comment by daniel-lo** [comment]
Chances are it has to do with remote access via iobroker pro. Now - back at home - search works. Though I do think I experienced this at home too before.

**Comment by GermanBluefox** [comment]
Just checked via iobroker.pro and annot see any problems.  Is the Problem still exists?

**Comment by daniel-lo** [comment]
Just tried .. seems to bee good. Thx.
