### ISSUE TITLE
Add support for Compact mode

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#351]
Once js-controller 2.0-0 is on the way we also should support it in Admin.

It should be able to edit per instance if the instance runs in compact mode or not. I could imagine a new column in export mode at "Instances" where compact can be enabled or disabled

Also in Instances (also in non-expert mode) some visible info should be there if an instance is executed in compact mode (a small C in the green circle or something like this)

**Comment by Apollon77** [comment]
relates https://github.com/ioBroker/ioBroker.js-controller/issues/290

**Comment by GermanBluefox** [comment]
Done
