### ISSUE TITLE
Bug beim Hinzufügen /löschen von Adaptern

### ISSUE THREAD

**Issue by passuff** [ioBroker/ioBroker.admin#354]
Hat man mehr als eine Instanz eines Adapters, löscht die Instanz.0, kann man diese nicht wieder hinzufügen. Weder durch automatische noch manuelle Auswahl der Instanznummer.
zB.:

Adapter.0
Adapter.1
Adapter 0 wird gelöscht Adapter 1 bleibt bestehen. Es ist jetzt nicht möglich wieder einen Adapter.0 hinzuzufügen (weder manuell noch automatisch) ohne vorher Adapter.1 zu löschen.
Getestet mit aktuellen Adaptern und frisch aufgesetztem System.

**Comment by Apollon77** [comment]
Moved to Admin repo

**Comment by wendy2702** [comment]
@passuff : ist das mit den aktuellen Versionen immer noch so?

**Comment by DutchmanNL** [comment]
solved

![Schermafbeelding 2020-04-29 om 11 22 53](https://user-images.githubusercontent.com/7318445/80580450-d4f01a80-8a0b-11ea-93c6-d7ce054550a9.png)
