### ISSUE TITLE
[Feature Request] two factor authentication

### ISSUE THREAD

**Issue by mcdhrts** [ioBroker/ioBroker.admin#355]
Hey Zusammen,
da ioBroker im Normalfall Zugriff auf das komplette Smart Home hat und man auch gerne von außerhalb darauf zugreifen möchte finde ich wäre eine zwei Faktor Authentifizierung sehr gut.
Grüße
McD_HRTS

**Comment by Apollon77** [comment]
Ist das ein Feature Request für Admin odernicht für den pro-Cloud Zugriff?

Der Admin-Adapter ist aktuell nicht unbedingt dazu gedacht von Aussen erreichbar zu haben - 2FA hin oder her

**Comment by mcdhrts** [comment]
Das ist für den Admin gedacht. 
Der Pro-Cloud Zugriff ist ja dann wieder was das man nicht selber in der Hand hat (was jetzt nicht bedeuten soll dass das schlecht sein muss).

**Comment by Apollon77** [comment]
Aber gelwsen hast Du: Der Admin-Adapter ist aktuell nicht unbedingt dazu gedacht von Aussen erreichbar zu haben - 2FA hin oder her

**Comment by mcdhrts** [comment]
Ja das habe ich gelesen.

Pro-Cloud kommt für mich allerdings nicht in Frage und was anderes gibt es ja nicht oder täusche ich mich (Admin bzw. Web-Adapter halt)?

Daher ist das für mich eigentlich legitim darüber von außen zuzugreifen und die normale authentifizierung ist hier ja auch schon implementiert. Es hat ja mit Sicherheit nicht jeder Benutzer die Pro-Cloud eingerichtet für den Zugriff auf io.

Wenn das aber gegen eure Vorgehensweise stößt dann kannst du den Request schließen. Dann werde ich mir wohl was andere einfallen lassen müssen um hier eine gute Lösung hinzubekommen, dann baue ich die 2FA über den Reverse Proxy oder ähnliches ab.

**Comment by DutchmanNL** [comment]
in der Mitte gelassen ob der admin allgemein für externen zugriff geeignet ist finde ich eine Implementierung von 2FA durchaus interessant.

Ich kan mir mehrere scenario vorstellen wobei dies ein interessantes feature ist, man muss aber die requirements gut berücksichtigen.

z.b. :

- Welche vorm von 2FA stellen wir uns vor ? (facebook, google, local alternative ?)
- Sollte 2FA immer actief zijn oder nur bestimmte accounts (z.b. Privilege accounts wie admin)
- Wie sollte Integrierung verlaufen zwischen lokalen admin und cloud Lösung (auch hier wäre 2FA interessant)

So gibt es verschiedene Möglichkeiten, z.b. auch mit telegram.
User logon ==> Menu nach telegram bot für betreffende user, nach Bestätigung telegram ==> erfolgreicher login.

(mal als beispiel)

**Comment by Apollon77** [comment]
Es verstösst gegen keine Vorgehensweise, es ist nur fakt das Admin oder Web keine Security Audits haben und daher von Projektseite keine Empfehlung besteht diese (egal mit welchen Auth-Verfahren) ungesichert ins Netz zu stellen.
Es ist also zu 100% Dein eigenes Risiko.

**Comment by systemofapwne** [comment]
Auch wenn es keine 2FA ist, so kann ich alternativ empfehlen, mit Hilfe eines reverse-proxys (z.B. mit nginx) eine https Verbindung nach außen zu erlauben und darauf aufbauend z.B. einen HTTP Auth mit einzubauen. Man kann das dann so konfigurieren, dass zwei unabhängige benutzernamen/passwörter benötigt werden und auch erweitern, dass bei wiederholten Fehlschlägen der Zugriff gesperrt wird.

Damit der reverse-proxy allerdings auch funktioniert und die Bedienung von io-broker nicht unendlich langsam macht (weil sonst ein fallback auf non-persistent WebSockets geschieht), muss man den reverse proxy entsprechend konfigurieren ("Upgrade"). Dies hier ist ist ein Auszug meines nginx config files, mit dem ich https und HTTP auth über eine reverse-proxy ermögliche

```
server {
    listen 443;
    listen [::]:443;
    
    server_name www.deinedomain.com;
    
    #enable ssl
    ssl on;
    ssl_certificate /pfad/zum/cert;
    ssl_certificate_key /pfad/zum/key;
	
    location / {
        #iobroker internal address
        proxy_pass http://localhost:8081/;
        #BasicAuth
        auth_basic "Restricted";
        auth_basic_user_file /pfad/zum/.htpasswd;
        #"Upgrade" for WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
```
