### ISSUE TITLE
Update materializecss to 1.0.0

### ISSUE THREAD

**Issue by kirovilya** [ioBroker/ioBroker.admin#357]
When implementing the settings-page in adapter, I found a select-field problem in the **multiple** selection mode (can not select item by click on icons).
If use the select.js file with the latest changes from here https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js then everything works correctly.
```
<div class="input-field">
    <select id="groups" class="materialSelect" multiple>
        <option value="1">Item 1</option>
        <option value="2">Item 2</option>
        <option value="3">Item 3</option>
    </select>
    <label for="groups" class="translate">Groups</label>
</div>
```

**Comment by AlCalzone** [comment]
workaround:
```css
		li[id^="select-options"] > * {
			pointer-events: none;
		}
```

**Comment by wendy2702** [comment]
Please reopen if needed or open a new issue.
