### ISSUE TITLE
Adapter Cron defekt - Umgehung möglich?

### ISSUE THREAD

**Issue by micklafisch** [ioBroker/ioBroker.admin#360]
Hallo zusammen,
wo werden die cron Einstellungen der Adapter gespeichert bzw. wie komme ich an die Einstellungen ran?
Ich hatte am Handy am Adapter etwas einstellen wollen und hatte leider in der grafischen Maske für die Cronjobs scheinbar mich verdrückt und jetzt steht dort nichts gescheites mehr drin. Wenn ich die Maske wieder aufrufen will erscheint die folgende Meldung:
![hc_2088](https://user-images.githubusercontent.com/44931749/50968179-94008980-14da-11e9-9588-76be23828aaf.jpg)

Komme ich da irgendwie über die Dateiebene noch ran? Basis von iobroker ist Windows.

Besten Dank und Gruß
Michael

**Comment by Apollon77** [comment]
Gehe zu Objekte, Expertenmodus, dann sollte "system.adapter.XY.Z" als Ordner auftauchen. Ggf filter rausnehmen. Bei den Ordner-Objekt hinten rechts auf den Stift klicken, dann unter "Raw Experts only" siehst Du ein JSON und da steht das drin. Dort korrigieren, speichern, sollte behoben sein

**Comment by Apollon77** [comment]
But Admin should also allow editing with broken value

**Comment by micklafisch** [comment]
Super, vielen Dank für die Rückmeldung. Über den RAW Bereich konnte ich das ganze berichtigen. Läuft wieder alles.

**Comment by wendy2702** [comment]
@micklafisch can you please test once again with actual version of Admin adapter?

**Comment by WLAN-Kabel** [comment]
TODO: Verify cron input and prevent faulty saving

**Comment by GermanBluefox** [comment]
Admin 5 should work with it
