### ISSUE TITLE
[Feature Request] Add adapter GitHub link to Instances, actions column

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.admin#361]
Hi,

This is a simple feature request:
Can you please add an additional icon to the actions column in the adapter instances:
By clicking on the icon, it should open the GitHub page of the adapter in a new window.

This would really save time. To currently open the adapter’s GitHub website, we have to navigate to the Adapters tab, search for the adapter (where the name not necessarily matches with the Instance name - so needs time to search for the right adapter), click on the blue menu symbol (3 dots), click on the question mark “?” icon, and finally click on the “OPEN ON NEW TAB” button at the bottom.

I guess the use case is pretty clear: We regularly need to check GitHub, like for the documentation, check open issues, posting a new issue, etc. Also, this would support to have users using GitHub more frequently in raising issues if they experience any.

Thanks :-)

**Comment by ldittmar81** [comment]
Hi Mic-M,

you can also use this link to get the github pages from all officially released adapters: http://download.iobroker.net/list.html.

If you install the [info Adapter](https://github.com/ldittmar81/ioBroker.info) you can get also a list of all existing adapters on github (adapters who are not officially released)

**Comment by DutchmanNL** [comment]
I think in general we should be more clear wer information can be retrieved and how it will be reflected in the interface, my idea around this :

- readme (basics) are always on GitHub readme page
- the adapter should have a wiki with How-To and information specific for the adapter

If we keep this simple rule for all functionality its clear were you have to be.
I ageren with the topic starter that the current way to find the documentation is maybe not the best, questions would be what is more realistic and usable to do in our interfacing ?

**Comment by wendy2702** [comment]
@Mic-M : can this be closed?

**Comment by Mic-M** [comment]
@wendy2702 

Thanks for asking. Sure, please close this issue.

I think it would still be nice having a direct Github link within the admin interface in the instances list for the sake of ease of use. But looks like I am the only one asking for this enhancement :-)
