### ISSUE TITLE
No SQL-Datapoints selectable

### ISSUE THREAD

**Issue by IO-Link** [ioBroker/ioBroker.admin#362]
See also https://github.com/ioBroker/ioBroker.flot/issues/53

I cannot select SQL-Datapoints in the flot-instance, for some time now. Only one datapoint from the history-adapter is selectable - i added that datapoint only for testing.
The flot-adapter is working apart from that, the .vis shows the flot-diagrams from SQL-datapoints i made some time ago correct.
Latest admin, SQL and flot is installed (admin 3.5.10; SQL 1.9.2; flot 1.9.2)

The screenshot shows the history-datapoint - no SQL-datapoint is selectable.

![2019-01-17 20_47_01-window](https://user-images.githubusercontent.com/45272881/51495504-e1bfa080-1dbc-11e9-9fc6-bc8e5c767c62.png)

**Comment by IO-Link** [comment]
Any updates? 
I installed iobroker on a complete new VM in proxmox. I didn't used any restored iobroker and only installed a S7-adapter, SQL, web and flot-adapter.
But same issue....

**Comment by IO-Link** [comment]
I'm dumb and blind... I forgot to set the "Instanz" when adding a new line to "sql.0"
![2019-02-09 18_30_07-flot edit](https://user-images.githubusercontent.com/45272881/52524063-fa72f600-2c98-11e9-817d-a61359991ea0.png)

**Comment by Apollon77** [comment]
:-))
