### ISSUE TITLE
NodeRed geht auf die falsche IP

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.admin#363]
Hallo
Ich hab  folgendes System:
Master: RPI3B+  (192.168.1.22)
Slave1: RPI3B+  (192.168.1.23)
Slave2: RPI3B+  (192.168.1.24)

Hab auf dem Master und auf Slave2 den WEB-Adapter installiert.
Und auf Slave2 NodeRed Installiert.

Klicke ich bei Übersicht oder Unter Instanzen auf das Icon "Adapter-Website öffnen" geht automatisch eine Page auf meinen Master (192.168.1.22:1880) auf, da läuft aber kein NodeRed, sondern am Slave2 (192.168.1.24:1880). Ändert man die IP auf die richtige funktioniert es auch. Blöd ist natürlich, weil das ganze auf der Pro-Cloud scheinbar auch auf die falsche IP läuft und da passiert natürlich nichts.

lg

**Comment by wendy2702** [comment]
Duplicate to #51
