### ISSUE TITLE
Setting option on state should be configurable to show table yes or now

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#364]
We have the situation to have custom html implemented and using that for data logger adapter.
But new developments like telegram and SourceAnalytix also have their setting on the state but no need for a table with history

Current situation : Table is always shown for each adapter using custom html
Wanted situation : adjustable setting which tabs should be available in relation to the adapter or not.

<img width="1496" alt="schermafbeelding 2019-01-22 om 10 39 41" src="https://user-images.githubusercontent.com/7318445/51526469-baa3b600-1e32-11e9-9552-14eb01030c09.png">

**Comment by wendy2702** [comment]
Can this be closed?

**Comment by DutchmanNL** [comment]
> Can this be closed?

sorry, no enhancement still needed more adapter are using the custom tab (like logging adapter) and don't need history tables at all
