### ISSUE TITLE
Tab Enums and Objects uneven behavior

### ISSUE THREAD

**Issue by Jey-Cee** [ioBroker/ioBroker.admin#366]
If i want to add the adapter, 'xbox.0', on the enum tab to a enum it isnt possible. But when i do the same on the object tab it works.

**Comment by wendy2702** [comment]
Label as „Bug“ or „enhancement“ ?

**Comment by Jey-Cee** [comment]
Bug. It is already there.
This effect is for all adapter instance objects the same.

**Comment by GermanBluefox** [comment]
Actually only device, channel or state could belongs to enumerations. What is the use-case to place the instance into the room?

**Comment by Jey-Cee** [comment]
The whole instance is the device. I want to add the device to a enum.

**Comment by GermanBluefox** [comment]
> The whole instance is the device. I want to add the device to a enum.

Object type is "instance", xbox must have sub-object of type "device"

**Comment by GermanBluefox** [comment]
Sorry, but decline this request
