### ISSUE TITLE
[Bug] Problem with MaterializeCSS

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.admin#371]
https://forum.iobroker.net/viewtopic.php?f=24&t=21289

**Comment by ldittmar81** [comment]
https://forum.iobroker.net/topic/9041/adapter-iobroker-info/157

We should update MaterializeCSS.

**Comment by wendy2702** [comment]
Has this been done? Can we close the issue?

**Comment by Steiger04** [comment]
Multiselect funktioniert mittlerweile. Bei switches in tabs ist das Problem immer noch da, von daher ist das Thema nach wie vor offen.

**Comment by WLAN-Kabel** [comment]
@Steiger04 hast du einen Beispiel Adapter, an dem ich das testen kann? Mir ist das bis jetzt nicht aufgefallen.

**Comment by Steiger04** [comment]
@WLAN-Kabel Sorry für die späte Rückmeldung, ist mir durchgegangen. Du kannst mal meinen milight-smart-light Adapter installieren und dann im Admin unter dem Tab Zonen eine Zone anlegen (s.a. **[ZONEN](https://steiger04.github.io/milight-smart-light-doku/admin/#zonen)**). Wenn Du dann speicherst und erneut den Tab aufrufst und versuchst den SWITCH-Button zu ändern siehst Du den Effekt. Das ist aber kein spezifisches Adapter-Thema, sondern ein MaterializeCSS-Problem (s.a. ) **[hier](https://forum.iobroker.net/topic/19109/problem-mit-materializecss/4)**. Wie gesagt es ist nur noch ein SWITCH-Problem, multiselect funktioniert jetzt.

**Comment by WLAN-Kabel** [comment]
@Steiger04 ich habe das ganze mal debugt. Da liegt ein Problem mit Vue vor. Der Switch wird umgelegt, im Vue Skript aber wieder zurück gestellt. Bitte prüfe einmal dein Vue Skript.

**Comment by Steiger04** [comment]
@WLAN-Kabel verstehe nicht was Du meinst. Du kannst doch den Fehler komplett ohne vue.js reproduzieren (s.  **[hier](https://forum.iobroker.net/topic/19109/problem-mit-materializecss/4)**). Das vue-Skript erzeugt hinterher reinen HTML5-Code der im Browser dargestellt wird, dass siehst Du auch wenn Du die Admin-Seite meines Adapters debuggst.

**Comment by Steiger04** [comment]
@WLAN-Kabel Bist Du an dem Thema noch dran?

**Comment by ldittmar81** [comment]
> @Steiger04 hast du einen Beispiel Adapter, an dem ich das testen kann? Mir ist das bis jetzt nicht aufgefallen.

Beim Info Adapter, im Reiter Dokumentation -> Dokumentationssprachen: Um da eine Sprache auszuwählen, muss man vor dem Kästchen klicken.

**Comment by WLAN-Kabel** [comment]
@Steiger04 ja, ich bin da noch dran. Ich werde mir das nochmal genauer anschauen, wenn ich ein bisschen mehr Zeit habe.
