### ISSUE TITLE
[Enhancement] Vue neben React für die Adapterentwicklung

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/ioBroker.admin#372]
@all Auf Empfehlung von Apollon77 habe ich das Thema jetzt hier eingestellt.
Details dazu: https://github.com/ioBroker/create-adapter/issues/107

**Comment by ldittmar81** [comment]
Wenn es einfach möglich ist, warum denn nicht? Ob vue, react oder angular... Alles ist echt super und Geschmackssache. Bin dafür :)

**Comment by GermanBluefox** [comment]
Am Anfang, wurde ich erwarten, dass die Adapter vue/react Framework mit liefern. Danach (irgendwann) kann man überlegen, ob man manche common files nicht in admin integriert.

**Comment by Steiger04** [comment]
@GermanBluefox Du hast ja jetzt den scene-Adapter in react realisert und dazu auch den admin-Adapter angepasst. Ist denn auch noch die Integration von vue geplant? Das fände ich super, einfach weil man auch mit vue sehr sehr einfach starten kann und gerade am Anfang die Lernkurve extrem flach ist. Das würde glaube ich vielen Adapter-Entwicklern den Einstieg sehr einfach machen.

**Comment by GermanBluefox** [comment]
Leider habe ich für vue keine Kapazitäten. Und ich werde nicht das unterstützten. 
React kann alles, was vue kann und es gibt mehr React Entwickler, als vue.

**Comment by Apollon77** [comment]
@Steiger04 Wie oben geschrieben: Ein Adapter kann selbst "seine" Vue Deps mitbringen und laden. @frankjoke machthier auch aktuell etwas eigenes (siehe radar2 zB). Das wäre die option hier.
