### ISSUE TITLE
[Feature Request]Rename ioBroker Tabs possible

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.admin#373]
I would like to point out that i run a productivity system and als a test system.

If i open now both adapter pages (or other pages) from each ioBroker system then the name of each TAB in my browser looks the same.
It would be very helpful if for example the name of the machine can be used or whatever - so i can see better which Tab is from which ioBroker system:

![tabs](https://user-images.githubusercontent.com/40624961/52625241-db4eb100-2eb0-11e9-8f3e-b1218eedc5e6.png)

**Comment by Ilovegym66** [comment]
or login-username are displayed in the tab ??

**Comment by SebastianSchultz** [comment]
It would be great if this feature will be added to admin.
