### ISSUE TITLE
[Enhancement] option to lock an installed adapter (disable uninstall/update)

### ISSUE THREAD

**Issue by joergzdarsky** [ioBroker/ioBroker.admin#377]
**Request:** 
In the Adapter-Overview of ioBroker.Admin, please add an **option to lock an installed adapter** for unwanted deinstallation or adapter-update.
Sometimes you don't want to update a certain adapter to a newer version because of known issues (my example would be the "Script Engine" adapter). However it can happen when a lot of adapters have updates that you by mistake update that adapter.

**Behavior:**
Locking an instance should "disable" the deinstallation or update button, and these should remain disabled until you unlock the adapter again.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/316
