### ISSUE TITLE
SSL Zertifikate 2017 abgelaufen

### ISSUE THREAD

**Issue by markuskobe** [ioBroker/ioBroker.admin#378]
Hi, die beiligenden Zertifikate für eine HTTPS Verbindung sind 2017 abgelaufen...wenn man diesen vertraut, ist zwar die Verbindung möglich, aber socket.io und material in Verbindung mit socket.io laufen nicht sauber. Ich habe heute selbst signierte Zertifikate mit aktueller Gültigkeit verwendet und diesen auch vertraut...anschließend sind mit material und socket.io keine Fehler mehr aufgetreten...DANKE

**Comment by Apollon77** [comment]
Please create in js-controller repository
