### ISSUE TITLE
Last two rowes are missing in Objecte

### ISSUE THREAD

**Issue by heitec11** [ioBroker/ioBroker.admin#380]
Hi
I made a update to the lasted versions of the adapter.
Now the last two rowes are missing in Objecte are missing.
Any ideas?

**Comment by GermanBluefox** [comment]
Screenshot?

**Comment by cimba007** [comment]
pi@ioBroker-RasPi:~ $ iobroker version
1.5.11

pi@ioBroker-RasPi:~ $ uname -a
Linux ioBroker-RasPi 4.19.46-v7+ #1230 SMP Tue May 28 16:18:48 BST 2019 armv7l GNU/Linux

![image](https://user-images.githubusercontent.com/3453121/59152491-220a7d00-8a45-11e9-8d07-a254d550791d.png)

**Comment by cimba007** [comment]
workaround: add two dummy instances that are paused

![image](https://user-images.githubusercontent.com/3453121/59152527-2f743700-8a46-11e9-849b-eb1eeb1610c7.png)

**Comment by WLAN-Kabel** [comment]
Please comment or reopen if the problem is not resolved.
