### ISSUE TITLE
Show message when changing password, if auth is off

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#384]
~~Whenever I set a password, save it and check it again, it is set to "password_not_set" as before. I tried to create a new user with password, but there the password is not saved.~~

Please show an info, if user try to set a password and the authentication is off.

if I want to create a user, "admin 2" for example, that does not work, because the ID hangs on admin and even if I want to delete the name, the id admin stays and you have to cancel the build.

Admin 3.6.0, js-controller 1.4.2, Node.js 8.15.1, Browser: Chrome

**Comment by GermanBluefox** [comment]
I don't understand the requiremenst

**Comment by ldittmar81** [comment]
Hab es mit Admin 5.0.20 getestet und könnte das Problem nicht wieder nachstellen.
