### ISSUE TITLE
Wrong / undocumented handling of chain certificats in admin (3.5.10)

### ISSUE THREAD

**Issue by jaghatei** [ioBroker/ioBroker.admin#386]
Admin handles imported ca certificates (PEM string) simply as "public" certificates leaving the "chained" drop down list empty i.e. on mqtt ssl page.
CA certificates are only listed in "chained" list when not imported as PEM string, but configured as path to a file.

adapter-settings.js only differentiates between public and chained based on the count of line breaks (lines 303-309).
But when pasting ca certificate as PEM String with line breaks admin removes the line breaks on save to objects.json flipping it from ca to public level.

Either there should be a specific documentation to this behaviour or this needs to be fixed.
Maybe easier to provide a check box on certificate page to select public certificates beeing also used as ca certificates.

**Comment by Gosuwaldbear** [comment]
the problem is still there

**Comment by mcm1957** [comment]
Dod you notice that this issue is from 2019 and has been closed 2020???

If there still is a problem please open a new issuedescribing the problem, add version info of Adapter js-controller, node an OS and all relevant logs
