### ISSUE TITLE
Admin is showing null values when a unit is set

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#391]
js-controller : 1.5.7
code : this.setState(stateCreateName, { val: 20 ,ack: true, expire: (received_data.c["Interval"].v *3) + 2 });

current situation :
When state has a unit defined, after expire value = NULL
When state has not a unit defined, after expire value = ""

wanted situation :
always reset state value to NULL to clearly understand state is expired in all scenarios (with or without unit defined

**Comment by Apollon77** [comment]
Essence was that Admin seems to not display "null" values as soon as a unit is set. Without a unit a "null" is also shown as "Null"

**Comment by DutchmanNL** [comment]
> Without a unit a "null" is also shown as "Null"

the other way arround ;)

With unit ==> correctly shown as NULL
Without unit ==> empty 

![Schermafbeelding 2019-03-21 om 09 47 28](https://user-images.githubusercontent.com/7318445/54741356-7fb5c880-4bbe-11e9-940a-14a4752178b1.png)

**Comment by Apollon77** [comment]
But what is the best way? Show null or not? Please consider "Normal" users that also use Admin?
Maybe different in exprtmode (show null) vs non Experts (show nothing better then null) ?!

**Comment by DutchmanNL** [comment]
> But what is the best way? Show null or not? Please consider "Normal" users that also use Admin?

good point, look for us its a difference to have " 0 " or " NULL ", my personal opinion is that having NULL is different from 0 and should be visible to end-users.
One of the reasons is the setState expire function, so NULL indicates that there is really something wrong (no data received) I would prefer to have that visible

**Comment by wendy2702** [comment]
@DutchmanNL  can this be closed?

**Comment by DutchmanNL** [comment]
> @DutchmanNL can this be closed?

no still, admin still shows empty field for NULL values we should continue here or port the discussion to admin redesign as its a valid use case

**Comment by GermanBluefox** [comment]
Please retest with Admin5
