### ISSUE TITLE
Log-Tab is showing the wrong/previous day

### ISSUE THREAD

**Issue by Hambootje** [ioBroker/ioBroker.admin#392]
After midnight,the log-tab is showing the previous day. Logging itself is running fine. I can open the log of the current day under Download Log. It seems the link to the most recent log file is not updated at 00:00.
It seems not depending on the browser, tested chrome, firefox, edge on windows and android.
The only way to get the latest logging displayed is resetting the admin adapter.

Admin: 3.6.0
Js Controller (Hosts): 1.4.2
Node,Nodejs: v8.15.1 (master, freenas) v8.15.0 (slave, RPi)
*Npm: 6.4.1

**Comment by berndmr** [comment]
Same problem here. It is also a Freenas / Freebsd installation. 

But at my side, reseting Admin-Instance does not help, only restart js-controller. 

Admin: 3.6.4
js-controller:  1.5.14

**Comment by wendy2702** [comment]
Please retest with actual Version Of Admin and JS-Controller and reopen or open a new issue if needed.
