### ISSUE TITLE
caught error wifilight adapter

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#396]
with Version 3.6.2 the wifilight adapter chrash:

host.iobroker | 2019-05-06 09:28:52.060 | error | instance system.adapter.wifilight.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at bootstrap_node.js:625:3
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at startup (bootstrap_node.js:204:16)
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at Function.Module.runMain (module.js:694:10)
Caught | 2019-05-06 09:28:52.060 | error | by controller[0]:     at Function.Module._load (module.js:498:3)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at tryModuleLoad (module.js:506:12)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Module.load (module.js:566:32)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Module._compile (module.js:653:30)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:20:20)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1148:23)
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:                       ^
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]:     fns.adapter = fns.adapter(options);
Caught | 2019-05-06 09:28:52.059 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1148
host.iobroker | 2019-05-06 09:28:51.698 | info | object change system.adapter.wifilight.0
host.iobroker | 2019-05-06 09:28:50.892 | info | Restart adapter system.adapter.wifilight.0 because enabled

**Comment by Apollon77** [comment]
Please create in wifilight Repo :) it is an adapter issue
