### ISSUE TITLE
custom dialogs: showMessage not working

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#398]
Im custom dialog funktioniert 'showMessage' nicht.

siehe Beispiel:
https://github.com/Scrounger/ioBroker.linkeddevices/blob/210178b3e57c8beff00da229fa55d06d198ba441/admin/custom_m.html#L120

Admin: 3.6.2, Nodejs v8.16.0, NPM 6.4.1, JS controller 1.5.8

**Comment by ldittmar81** [comment]
Was genau passier da? Hast du schon mit gMain.showMessage(... probiert?

**Comment by Scrounger** [comment]
@ldittmar81 
mit gMain.showMessage(...) gehts, danke!
