### ISSUE TITLE
custom dialogs: customPostOnSave not working

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#399]
Die neue Funktion seit 3.6.2 customPostOnSave  scheint nicht zu funktionieren:

siehe Beispiel:
https://github.com/Scrounger/ioBroker.linkeddevices/blob/210178b3e57c8beff00da229fa55d06d198ba441/admin/custom_m.html#L142

Admin: 3.6.2, Nodejs v8.16.0, NPM 6.4.1, JS controller 1.5.8

**Comment by wendy2702** [comment]
@Scrounger can you please retest with actual version of Admin and JS-Controller

**Comment by Scrounger** [comment]
funktioniert leider nach wie vor nicht.

**Comment by GermanBluefox** [comment]
Es gibt keine customPostOnSave. Admin5 hat einen anderes Konzept dafür.
