### ISSUE TITLE
[Feature Request] custom dialogs: getObject

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#401]
Could you please implement in the custom dialog function 
`customPostInits[adapter] = function ($div, values, instanceObj, type, role) {...}`
the possibility to get the object, somthing like this:
`customPostInits[adapter] = function ($div, values, obj, instanceObj, type, role) {...}`

I need information e.g. if the object is read or write to implement some depending feature in my adapter.

Thanks in advanced!

**Comment by Scrounger** [comment]
Ok after reading the source i find the solution how to get the object of the custom dialog:
`	// Objekt holen für das der custom Dialog geöffnet wurde 
	var currentObj = gMain.objects[gMain.navigateGetParams()];`

I think a function to get the object would be more simple.
I also discovered if 'obj.common.custom[adapter].enabled = true', the obj in the 
`defaults.adapter= function (obj, instanceObj) {...}` 
is 'undefined'. [More details see here](https://forum.iobroker.net/topic/22186/adapter-entwicklung-custom-datapoint-specific-custom_m-html-abfrage-beim-speichern/10)

**Comment by wendy2702** [comment]
@Scrounger can you please retest with actual version of Admin and JS-Controller.

**Comment by Scrounger** [comment]
Wie wurde das implementiert, also wie lautet der Befehl dazu?

**Comment by GermanBluefox** [comment]
Admin5 works now in other way.
