### ISSUE TITLE
custom dialog: translation behavior

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#404]
Ich hab das Problem das die Übersetzung des custom dialogs nicht funktioniert, bzw. nur gelegentlich. Dieses Verhalten habe ich bei mehreren Adaptern festgestellt, die das template vom https://github.com/ioBroker/create-adapter für die Übersetzung verwenden:

```
<script type="text/javascript">
	$.get("adapter/linkeddevices/words.js", function (script) {
		let translation = script.substring(script.indexOf('{'), script.length);
		translation = translation.substring(0, translation.lastIndexOf(';'));
		$.extend(systemDictionary, JSON.parse(translation));
	});
</script>
```

Wenn ich jetzt den js-controller neustarte und den custom dialog aufrufe, sieht das ergebnis wie folgt aus:
![01](https://user-images.githubusercontent.com/6370451/58275918-6ab00e00-7d96-11e9-8f54-59e7a5086721.png)

Dann schließe ich den custom dialog und öffnen Ihn erneut. Jetzt geht die Übersetzung der Buttons verloren:
![02](https://user-images.githubusercontent.com/6370451/58275964-86b3af80-7d96-11e9-88b0-e531543f1eaa.png)

Wenn ich die Übersetzung sychron lade, dann ist sie nach einem neustart des js-controller sofort vorhanden
```
<script type="text/javascript">
	// $.get("adapter/linkeddevices/words.js", function (script) {
	// 	let translation = script.substring(script.indexOf('{'), script.length);
	// 	translation = translation.substring(0, translation.lastIndexOf(';'));
	// 	$.extend(systemDictionary, JSON.parse(translation));
	// });
	$.get({
		url: 'adapter/linkeddevices/words.js',
		success: function (result) {
			if (result.isOk) {
				let translation = script.substring(script.indexOf('{'), script.length);
				translation = translation.substring(0, translation.lastIndexOf(';'));
				$.extend(systemDictionary, translation);
			}
		},
		async: false
	})</script>
```
![03](https://user-images.githubusercontent.com/6370451/58276083-d5614980-7d96-11e9-96a4-27c5bb0c13a4.png)
Allerdings werden die hardcoded übersetzung dann nicht geladen (siehe roter kasten):
`Label.number_unit.text(_("change unit '%s' to", currentObj.common.unit));`
Und die Übersetzungen für z.B. Buttons ist auch nicht vorhanden

Wenn ich jetzt in customPostInits nochmal die translation lade
```
<script type="text/javascript">
	// $.get("adapter/linkeddevices/words.js", function (script) {
	// 	let translation = script.substring(script.indexOf('{'), script.length);
	// 	translation = translation.substring(0, translation.lastIndexOf(';'));
	// 	$.extend(systemDictionary, JSON.parse(translation));
	// });
	$.get({
		url: 'adapter/linkeddevices/words.js',
		success: function (result) {
			if (result.isOk) {
				let translation = script.substring(script.indexOf('{'), script.length);
				translation = translation.substring(0, translation.lastIndexOf(';'));
				$.extend(systemDictionary, translation);
			}
		},
		async: false
	})
	if (typeof customPostInits !== 'undefined') {
		customPostInits.linkeddevices = function ($div, values, instanceObj, type, role) {

			$.get("adapter/linkeddevices/words.js", function (script) {
				let translation = script.substring(script.indexOf('{'), script.length);
				translation = translation.substring(0, translation.lastIndexOf(';'));
				$.extend(systemDictionary, JSON.parse(translation));
			});
                }
          }
</script>
```

dann funktioniert auch die hardcoded Übersetzung, aber die Übersetzung der buttons geht wieder nicht.
![04](https://user-images.githubusercontent.com/6370451/58276279-4ef93780-7d97-11e9-89ba-5e7dbf8ac98b.png)

**Comment by ldittmar81** [comment]
Ich habe gemerkt, dass bei dir das steht:

`$.extend(systemDictionary, translation);`

Sollte aber das hier sein:

`$.extend(systemDictionary, JSON.parse(translation));`

Deswegen funktionieren bei dir nur die Buttons, denn diese kommen ja vom Admin-Adapter... hmm... was passiert, wenn du "save" und "cancel" in deine words.js hinzufügst?

**Comment by Scrounger** [comment]
Danke für den Hinweis, allerdings ist das Verhalten nach wie vor gleich.

"save, "cancel", etc. habe ich bereits meiner words.js hinzugefügt, dann funktioniert auch die Übersetzung der buttons. Aber das sollte doch eigentlich vom Admin Adapter kommen?

**Comment by wendy2702** [comment]
Ich weiß das du keine Frage auf deine Antwort bekommen hast aber ist das hier noch offen?

**Comment by Scrounger** [comment]
die obige Lösung funktioniert für mich von daher kann geschlossen werden
