### ISSUE TITLE
iobroker restart in log-tab

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.admin#406]
strange error :
node 10.15.3 npm 6.9 admin 3.62
If I delete the log in the log-tab - iobroker is doing a restart
with this error:

`host.raspberry3	2019-05-25 11:12:32.994	info	received SIGTERM
host.raspberry3	2019-05-25 11:12:27.987	info	received SIGTERM
host.raspberry3	2019-05-25 11:12:27.880	info	iobroker exit 0
host.raspberry3	2019-05-25 11:12:27.870	info	iobroker Starting node restart.js
host.raspberry3	2019-05-25 11:12:27.702	info	iobroker _restart
host.raspberry3	2019-05-25 11:12:27.702	error	TypeError [ERR_INVALID_CALLBACK]: Callback must be a function at maybeCallback (fs.js:128:9) at Object.writeFile (fs.js:1158:14) at processMessage (/opt/iobroker/node_modules/iobroker.js-c
host.raspberry3	2019-05-25 11:12:27.701	error	uncaught exception: Callback must be a function`

**Comment by Apollon77** [comment]
Which js-Controller Version? This error should be fixed  in 1.5.9 on latest channel which will come to stable very soon.

**Comment by liv-in-sky** [comment]
was the 1.4. version
the 1.5.9 version together with node 10 made some orther errors.

I have installed js-1.5.9 an node 8.16 - now it seems to be ok !
