### ISSUE TITLE
Host update instructions

### ISSUE THREAD

**Issue by kugelkopf123** [ioBroker/ioBroker.admin#407]
Hey.. 
As far as i know, this commands: 
`iobroker start, stop, restart, status`

are not working anymore. But if you click on the update button of the Host site from ioBroker you get the information to change into the Directory /opt/iobroker and run iobroker stop before updating. 

So.. perhaps this should be sudo systemctl stop iobroker.

**Comment by Apollon77** [comment]
From where you jave this info?

With the newest installation fixer and new installatuons these commands are working well. And the same as with systemctl.

There were some buggy versions in between, but current ones work well.

**Comment by kugelkopf123** [comment]
Sorry i was on vacation. 
When i write iobroker stop i get: 
`iobroker controller daemon is not running
`
So i have to stop via systemctl.

**Comment by Apollon77** [comment]
Did you used the installation fixer to make sure the installation basics are up to date?

**Comment by kugelkopf123** [comment]
> Did you used the installation fixer to make sure the installation basics are up to date?

No. Didnt knew that there is one.  So.. i guess i should try it?

**Comment by Apollon77** [comment]
maybe :-))

Read: https://forum.iobroker.net/topic/20211/iobroker-installation-fixer-beta-verf%C3%BCgbar for more info
