### ISSUE TITLE
Certificate Settings 

### ISSUE THREAD

**Issue by p33k** [ioBroker/ioBroker.admin#408]
Certificate Settings acting wierd. 
Sometimes there is only a blank screen, after couple of reloads a screen without save button.
only random after a lot of reloads the correct window with save button appears.
![Einstellungen Zertifikat](https://user-images.githubusercontent.com/6191925/59164555-d58b7400-8b0e-11e9-86cb-fb4067effc89.png)
![Einstellungen Zertifikat 1](https://user-images.githubusercontent.com/6191925/59164557-d6bca100-8b0e-11e9-9443-59806a5b2682.png)

**Comment by wendy2702** [comment]
Please retest with actual Version of Admin Adapter and reopen or open a new issue if needed.
