### ISSUE TITLE
Filter in history doesn't work correctly

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#410]
The history adapter offers a time filter in table sight of an object.

this doesn't work correctly.

Trying a lot the input of the filter like shown following image seems to work
![history_filter](https://user-images.githubusercontent.com/11257222/61173512-b2803400-a594-11e9-9bb8-c33fdf440ee7.png)

But this is not the way as indicated ;-)

**Comment by wendy2702** [comment]
Please retest with actual Version of Admin, History and JS-Controller and reopen or open a new issue if needed.
