### ISSUE TITLE
cron settings check

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#411]
i can edit the cron settings on Admin GUI and worst case is i can delete a asterisk manually.
default settings
![grafik](https://user-images.githubusercontent.com/6681528/61355926-9ec71d00-a875-11e9-9f15-5be4931f968c.png)

manually del 
![grafik](https://user-images.githubusercontent.com/6681528/61356026-c5855380-a875-11e9-8b54-ebe1e21c9222.png)

the problem is now.. the cron job is defect and restart the adapter in a loop

we need a check for right settings

**Comment by wendy2702** [comment]
Can you please check with actual Version of Admin?

**Comment by WLAN-Kabel** [comment]
TODO: Handle wrong cron input.

**Comment by WLAN-Kabel** [comment]
Duplicate #360
