### ISSUE TITLE
Autofill in chrome fills in the login-name on random places, if username/password is stored in browser

### ISSUE THREAD

**Issue by systemofapwne** [ioBroker/ioBroker.admin#414]
One thing, which drives me nuts now for many months is, that the username is automatically filled in to <input> forms, which have attributes like _placeholder="Name"_ in it.
This is especially annoying in the "Objects" tab: When I opened it up, it fills up the "Name" column with "admin", so the overall objects list is filtered for the word "admin". And it gets even more annoying, because from time to time, the Objects list dynamically refreshes, so chrome fills in "admin" again multiple times, such that the current view vanishes and I always need to clear that input-form manually. Using the "Objects" tab is therefore really, really annoying.

This bug is by the way not limited to "Objects" but also happens from time to time in "Logs" for the "Meldung" column and "enum" in the filter entry. I'm unsure, what exactly is triggering chrome to fill in the data there.

**Way to reproduce**
 * Open the iobroker admin site with chrome
 * Login with username/password and store the credentials in the browser
 * Click on objects tab -> The heading of the second column now will fill in the username

**Suggested fix**
I admit, that this is rather a bug with chrome's autofill heuristic. But I expect this behaviour to either vanish by not setting the _placeholder="Name"_ attribute (probably not wanted) or by adding the additional attribute _autocomplete="off"_ to every input form (but for the login page though).

**Edit**
I just tried to implement it on my own, but it seems like chrome ignores the autocomplete attribute. I will try to find a solution for a fix, which then should be implemented later.

**Comment by systemofapwne** [comment]
I found a way now to completely avoid chrome to fill an input form on its own.
The workaround consists of setting the the autocomplete attribute to "new-password"

**Example:**
`<input autocomplete="new-password" ... />`

This is the only way, how it seems, to stop chrome filling up the input field. I suggest, to add this to the table headlines of "objects" and "logs" and also to the "Filter" input of "adapter", "instances" and "enum".

**Comment by systemofapwne** [comment]
Any acknowledgement or similar observations? This issue is really, really annoying. It is so annoying, since it even "auto fills" when certain values within the object tab are updating, while you are browsing the state-tree. It is a not only a "minor inconveniece" but rather a major anoyance concerning usability - And with my suggested fix (see earlier) easily fixable.

**Comment by Apollon77** [comment]
Can you provide a PR?

**Comment by systemofapwne** [comment]
You mean a problem report? See the original post.

**Comment by Apollon77** [comment]
No PR is a pull request. If you know what and where to fix it edit that file here online on GitHub and create a PR to propose the code fix.

**Comment by systemofapwne** [comment]
Well, I hoped the main developers can take a look into this, since it is quite tedious for me to find the actual location in the source, where the input fields are getting defined. But I will give it a shot and provide a Pull Request, once I added the suggested changes.

**Comment by Apollon77** [comment]
This would be very helpful time wise. Thank you

**Comment by systemofapwne** [comment]
So far, I traced down one location in selectID.js. Yet, even when the correct js file is now provided via my webserver and the browser also is reading it correctly in the patched version, the <input>-form is not updated. I guess, there is another location, some kind of html template, which I have to fix. I will eventually figure it out - The code is rather complex so it might take some time. Yet, this issue annoys me a lot, so I want this to be fixed :D

**Comment by wendy2702** [comment]
@systemofapwne any news on this?

**Comment by systemofapwne** [comment]
I unfortunately ran out of time the past few months to fix this. To my last knowledge regarding the subject, it still is happening so I turned off "remember password/username", since it got very annoying. 
I hope I will find the time at some point in the near future to further debug this.

**Comment by wendy2702** [comment]
OK.

Is it OK for you if we close it for now and you can open a new issue if needed?

**Comment by systemofapwne** [comment]
I will close it with the state **Minor/Not yet fixed/Needs investigation**
