### ISSUE TITLE
Feature request: custom settings button for channels, devices, etc.

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#415]
@GermanBluefox 
Could you please implement a custom menu (button) for objects of type channel, devices, etc.
I need this for my linkeddevices adapter to auto create all linked objects of a channel, device, etc.

Here you find what i want to realize:
https://github.com/Scrounger/ioBroker.linkeddevices/issues/6

**Comment by wendy2702** [comment]
@Scrounger : even you never got a answer I’d like to ask if this is working now.

**Comment by Scrounger** [comment]
no not working, because not implemented.
I made a workaround in the adapter, but this feature would offer some others options, e.g. create linkeddevices for all obejcts of a channel.
