### ISSUE TITLE
Imported enums via object json is missing type enum

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.admin#416]
When I import a object which are enum members via an exportet json and the enums are not existing on the new machine the enums are created but not with type enum. This leads to invisible enum which prevent the creating of enums with this name.
You have to manually add the type enum to all new created enums.

**Comment by wendy2702** [comment]
Can you please retest with actual Version of Admin and JS-Controller.In case it is still NOK please provide some detailed information about your System and logfile.

**Comment by TA2k** [comment]
Still the same with actual admin and js controller..

import this json and take look at:
enum.rooms.ambiance_livingroom
you will see the type "enum" is missing.

`{
  "deconz.0.Lights.18": {
    "type": "device",
    "common": {
      "name": "Kugellampe",
      "role": "light",
      "enums": [
        {
          "_id": "enum.functions.backlight",
          "common": {
            "icon": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJDYXBhXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KCSB2aWV3Qm94PSIwIDAgNTExLjk5MSA1MTEuOTkxIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCA1MTEuOTkxIDUxMS45OTE7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxnPg0KCTxwYXRoIGQ9Ik05MS40OSwzMzYuNTcybC0yMS4zMzMsNDIuNjY3Yy0yLjYyNCw1LjI2OS0wLjQ5MSwxMS42NjksNC43NzksMTQuMzE1YzEuNTM2LDAuNzQ3LDMuMTU3LDEuMTA5LDQuNzU3LDEuMTA5DQoJCWMzLjkwNCwwLDcuNjU5LTIuMTc2LDkuNTM2LTUuODg4bDIxLjMzMy00Mi42NjdjMi42NDUtNS4yNjksMC41MTItMTEuNjY5LTQuNzU3LTE0LjMxNQ0KCQlDMTAwLjU1NywzMjkuMTY5LDk0LjE1NywzMzEuMzI0LDkxLjQ5LDMzNi41NzJ6Ii8+DQoJPHBhdGggZD0iTTUwNy41NTQsMTgzLjM1NmMtMi43NzMtMi4wMjctNi4zMzYtMi41MzktOS42LTEuNDkzbC00OS40MDgsMTYuNDY5Yy0xMy4wOTksNC4zNzMtMjEuODg4LDE2LjU3Ni0yMS44ODgsMzAuMzc5djM2Ljg4NQ0KCQljLTI0LjMyLTQuOTQ5LTQyLjY2Ny0yNi40OTYtNDIuNjY3LTUyLjI0NXYtODUuMzMzYzAtMzEuMjMyLTEyLjEzOS02MC43MTUtMzQuMzA0LTgzLjExNQ0KCQljLTIyLjMxNS0yMi4xMDEtNTEuNzk3LTM0LjI0LTgzLjAyOS0zNC4yNGMtNjQuNjgzLDAtMTE3LjMzMyw1Mi42NTEtMTE3LjMzMywxMTcuMzMzdjUzLjMzM2gtMzJjLTE3LjY0MywwLTMyLDE0LjM1Ny0zMiwzMg0KCQl2NDAuMTQ5TDEuMTIyLDQyMS45MDVjLTEuNjQzLDMuMzA3LTEuNDcyLDcuMjMyLDAuNDQ4LDEwLjM2OGMxLjk2MywzLjEzNiw1LjM5Nyw1LjA1Niw5LjA4OCw1LjA1Nmg3NS43NTUNCgkJYzUuMjI3LDM2LjA5NiwzNi4wNzUsNjQsNzMuNTc5LDY0czY4LjM1Mi0yNy45MDQsNzMuNTc5LTY0aDc1Ljc1NWMwLjE0OSwwLDAuMzIsMC4wMjEsMC40MjcsMA0KCQljNS44ODgsMCwxMC42NjctNC43NzksMTAuNjY3LTEwLjY2N2MwLTIuNzUyLTEuMDI0LTUuMjQ4LTIuNzMxLTcuMTI1bC04My4wMjktMTY2LjA1OXYtNDAuMTQ5YzAtMTcuNjQzLTE0LjM1Ny0zMi0zMi0zMmgtMzINCgkJdi01My4zMzNjMC01Mi45MjgsNDMuMDcyLTk2LDk2LTk2YzI1LjU1NywwLDQ5LjcyOCw5Ljk2Myw2Ny45NDcsMjcuOTg5YzE4LjA5MSwxOC4yODMsMjguMDUzLDQyLjQ1MywyOC4wNTMsNjguMDExdjg1LjMzMw0KCQljMCwzNy41MDQsMjcuOTA0LDY4LjM1Miw2NCw3My41Nzl2MzkuMDRjMCwxMy43ODEsOC43ODksMjYuMDA1LDIxLjg2NywzMC4zNTdsNDkuNDA4LDE2LjQ2OQ0KCQljMS4xMzEsMC4zNjMsMi4yNjEsMC41NTUsMy4zOTIsMC41NTVjMi4yMTksMCw0LjM5NS0wLjY4Myw2LjIyOS0yLjAyN2MyLjc5NS0xLjk4NCw0LjQzNy01LjIwNSw0LjQzNy04LjY0VjE5MS45OTYNCgkJQzUxMS45OTEsMTg4LjU2MSw1MTAuMzQ5LDE4NS4zNCw1MDcuNTU0LDE4My4zNTZ6IE0xNTkuOTkxLDQ3OS45OTZjLTI1Ljc0OSwwLTQ3LjMxNy0xOC4zNDctNTIuMjY3LTQyLjY2N2gxMDQuNTMzDQoJCUMyMDcuMzA5LDQ2MS42NDksMTg1Ljc0MSw0NzkuOTk2LDE1OS45OTEsNDc5Ljk5NnogTTI5Mi4wODcsNDE1Ljk5NmgtNjguMDk2aC0xMjhIMjcuOTE3bDc0LjY2Ny0xNDkuMzMzaDExNC44MzcNCgkJTDI5Mi4wODcsNDE1Ljk5NnogTTIwMi42NTgsMjAyLjY2MmM1Ljg2NywwLDEwLjY2Nyw0LjgsMTAuNjY3LDEwLjY2N3YzMkgxMDYuNjU4di0zMmMwLTUuODY3LDQuOC0xMC42NjcsMTAuNjY3LTEwLjY2N0gyMDIuNjU4eg0KCQkgTTQ5MC42NTgsMzQ3Ljg3OGwtMzUuMzcxLTExLjgxOWMtNC4zNzMtMS40MjktNy4yOTYtNS41MDQtNy4yOTYtMTAuMTEydi05Ny4yNTljMC00LjYwOCwyLjkyMy04LjY2MSw3LjI5Ni0xMC4xMTINCgkJbDM1LjM3MS0xMS43OTdWMzQ3Ljg3OHoiLz4NCjwvZz4NCjwvc3ZnPg0K",
            "name": {
              "en": "Backlight",
              "de": "Hintergrundbeleuchtung",
              "ru": "Подсветка",
              "pt": "Luz de fundo",
              "nl": "Backlight",
              "fr": "Rétro-éclairage",
              "it": "Controluce",
              "es": "Iluminar desde el fondo",
              "pl": "Podświetlenie",
              "zh-cn": "逆光"
            }
          }
        },
        {
          "_id": "enum.rooms.ambiance_livingroom",
          "common": {
            "name": "Ambiente - Wohnzimmer",
            "icon": "",
            "color": false
          },
          "native": {}
        }
      ]
    },
    "native": {
      "etag": "xxxxxx",
      "hascolor": true,
      "id": "18",
      "manufacturername": "Philips",
      "modelid": "LCT012",
      "swversion": "1.46.13_r26312",
      "type": "Extended color light",
      "uniqueid": "00:17"
    },
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564330,
    "_id": "deconz.0.Lights.18",
    "acl": {
      "object": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.action": {
    "type": "state",
    "common": {
      "name": "Kugellampe action",
      "role": "argument",
      "type": "string",
      "read": false,
      "write": true
    },
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.action",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.alert": {
    "type": "state",
    "common": {
      "name": "Kugellampe alert",
      "type": "string",
      "role": "state",
      "read": true,
      "write": true,
      "states": {
        "none": "none",
        "select": "select",
        "lselect": "lselect",
        "blink": "blink"
      },
      "def": "none"
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564330,
    "_id": "deconz.0.Lights.18.alert",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.bri": {
    "type": "state",
    "common": {
      "name": "Kugellampe bri",
      "type": "number",
      "role": "value.brightness",
      "read": true,
      "write": true,
      "min": 0,
      "max": 254,
      "def": 254
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564331,
    "_id": "deconz.0.Lights.18.bri",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.colormode": {
    "type": "state",
    "common": {
      "name": "Kugellampe colormode",
      "type": "string",
      "role": "state",
      "read": true,
      "write": true,
      "states": {
        "hs": "hs",
        "xy": "xy",
        "ct": "ct"
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564331,
    "_id": "deconz.0.Lights.18.colormode",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.colorspeed": {
    "type": "state",
    "common": {
      "name": "Kugellampe colorspeed",
      "type": "number",
      "role": "state",
      "read": true,
      "write": true,
      "min": 1,
      "max": 255,
      "def": 255
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564339,
    "_id": "deconz.0.Lights.18.colorspeed",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.ct": {
    "type": "state",
    "common": {
      "name": "Kugellampe ct",
      "type": "number",
      "role": "level.color.temperature",
      "read": true,
      "write": true,
      "min": 153,
      "max": 500,
      "def": 500
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564331,
    "_id": "deconz.0.Lights.18.ct",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.dimdown": {
    "type": "state",
    "common": {
      "name": "Kugellampe dimdown",
      "role": "button"
    },
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.dimdown",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.dimspeed": {
    "type": "state",
    "common": {
      "name": "Kugellampe dimspeed",
      "type": "number",
      "role": "level.dimspeed",
      "min": 0,
      "max": 254,
      "read": false,
      "write": true
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.dimspeed",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.dimup": {
    "type": "state",
    "common": {
      "name": "Kugellampe dimup",
      "role": "button"
    },
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.dimup",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.effect": {
    "type": "state",
    "common": {
      "name": "Kugellampe effect",
      "type": "string",
      "role": "state",
      "read": true,
      "write": true,
      "states": {
        "none": "none",
        "colorloop": "colorloop"
      }
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564339,
    "_id": "deconz.0.Lights.18.effect",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.hue": {
    "type": "state",
    "common": {
      "name": "Kugellampe hue",
      "type": "number",
      "role": "level.color.hue",
      "read": true,
      "write": true,
      "unit": "°",
      "min": 0,
      "max": 360,
      "def": 360
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564340,
    "_id": "deconz.0.Lights.18.hue",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.on": {
    "type": "state",
    "common": {
      "name": "Kugellampe on",
      "type": "boolean",
      "role": "switch",
      "read": true,
      "write": true
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564340,
    "_id": "deconz.0.Lights.18.on",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.reachable": {
    "type": "state",
    "common": {
      "name": "Kugellampe reachable",
      "type": "boolean",
      "role": "indicator.reachable",
      "read": true,
      "write": false
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564340,
    "_id": "deconz.0.Lights.18.reachable",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.sat": {
    "type": "state",
    "common": {
      "name": "Kugellampe sat",
      "type": "number",
      "role": "level.color.saturation",
      "read": true,
      "write": true,
      "min": 0,
      "max": 255,
      "def": 255
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.sat",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.transitiontime": {
    "type": "state",
    "common": {
      "name": "Kugellampe transitiontime",
      "type": "number",
      "role": "state",
      "read": true,
      "write": true,
      "def": 0
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.transitiontime",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  },
  "deconz.0.Lights.18.xy": {
    "type": "state",
    "common": {
      "name": "Kugellampe xy",
      "type": "array",
      "role": "color.CIE",
      "read": true,
      "write": true,
      "def": "0.10000, 0.10000"
    },
    "native": {},
    "from": "system.adapter.deconz.0",
    "user": "system.user.admin",
    "ts": 1581762564341,
    "_id": "deconz.0.Lights.18.xy",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}`

**Comment by Apollon77** [comment]
hm ... and why the enum objects in the json file not alao contain the type as needed? Because when you import that why the system should add it?

**Comment by TA2k** [comment]
good point maybe it is a bug in the export function
