### ISSUE TITLE
"localLink": false in common.welcomeScreen in io-package.json is not respected

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#417]
In io-package.json
under common.welcomeScreen
the statement
"localLink": false
is not respected. The local links is displayed in overview-tab.

Under welcomeScreenPro it is respected.

**Comment by wendy2702** [comment]
Can you please text / check with actual Version of Admin.

**Comment by sbormann** [comment]
Problem still exists.

**Comment by WLAN-Kabel** [comment]
@sbormann Do you have an example adapter?

**Comment by Apollon77** [comment]
I would assume hier tried in https://github.com/sbormann/ioBroker.iqontrol/blob/master/io-package.json#L215-L221

**Comment by sbormann** [comment]
Exactly, it works for welcomeSreenPro, but not for welcomeScreen.

**Comment by Apollon77** [comment]
@sbormann Still relevant with Admin5 react UI?
