### ISSUE TITLE
setting up adapter

### ISSUE THREAD

**Issue by ggraziotti** [ioBroker/ioBroker.admin#418]
I have iobroker on raspberry (ip address 192.168.0.xxx) connect to a router on another lan (192.168.1.xxx).
How to setting up the connection from another exsternal LAN outsite home ?
I have a web domain and static public IP.
How to configure let's encrypt (https)?
Is possible, for test only setting up and http unsecure connection from outside ?

Where can I find a step by step guide to configure the external access to iobroker ?

**Comment by Apollon77** [comment]
Best ask in the iobroker forum. The users there should be able to support. 

Short:
Use an iobroker.pro account with a remote access package and the cloud adapter to get secure access. 
Alternatively (and when you exactly know what you are doing and about the risks) open a port in your router and point it to a admin instance port. Enable ssl there with self signed certs or let’s encrypt. Let’s encrypt details please also check forum. But you also need to forward port 80 to one of the iobroker hosts depending on what you choose to setup let’s encrypt with.

**Comment by bratello** [comment]
> How to setting up the connection from another external LAN outside home ?

I would check the option to arrange the VPN between the home LAN and external LAN. Because you want to access your iobroker externally but secure it from WAN right? The VPN provides you such network between different offices. I hope that iobroker can work under VPN as other network application.

**Comment by wendy2702** [comment]
Please reopen or open a new issue if something is open but for configuration you better ask at forum.
