### ISSUE TITLE
Deleting and renaming files an folders via socket.emit does not work

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#423]
In index_m.htm socket.emit ignores the 'unlink' and 'rename' command, whereas 'writeFile' works well.

Has anyone any idea?

This is not working (deleting and renamig files and folders):

function deleteFile(path, callback) {
socket.emit('unlink', adapter, path, function (err) {
if (callback) callback(err);
});
}

function renameFile(oldPath, newPath, callback) {
socket.emit('rename', adapter, oldPath, newPath, function (err) {
if (callback) callback(err);
});
}
Whereas this works (Image-Upload):

function uploadFile(file, path, callback) {
if(typeof path == 'function') {
callback = path;
path = null;
}
var reader = new FileReader();
reader.onload = function(e) { // Closure to capture the file information.
socket.emit('writeFile', adapter, (path ? path + "/" : "") + file.name, e.target.result, function () {
if (callback) callback(file.name);
});
};
reader.readAsArrayBuffer(file);
}

Taken from https://github.com/sbormann/ioBroker.iqontrol

Many thanks!

**Comment by wendy2702** [comment]
Hi,

Do you still need support ?

**Comment by sbormann** [comment]
Yes please. I needed to add a socket.io-connection to get file operations working. Would be great to use the admin-built-in socket, as this would remove many connection-problems, espacialy reported for authenticated ssl-connections over iobroker.pro.

The socket.emit works - escept the unlink and rename command. 

I think this should not be so hard to fix.

Many thanks, Sebastian

**Comment by Apollon77** [comment]
* The integrated admin socketio do not have an unlink command, but "deleteFile" (which internally calls unlink)
* The integrated admin socketio do not have "rename" implemented

* The socketio adapter has "unlink" but not "deleteFile"
* The socketio adapter has "rename" implemented

**Comment by sbormann** [comment]
Ah, that helps! 
I could use deleteFile instead of unlink. But that would not resolve the problem with rename. Any chance to get that implemented?

**Comment by Apollon77** [comment]
Make a PR? ;-)) or wee need to see when someone finds time.

**Comment by sbormann** [comment]
PR - i wish i would have enough expertise to participate... but that beats me... So I hope, someone finds time ;)

**Comment by sbormann** [comment]
solved in #686
