### ISSUE TITLE
Make use of new getPort version

### ISSUE THREAD

**Issue by mc-0815** [ioBroker/ioBroker.admin#424]
Hi,

it would be gr8 to make use of the newest getPort version from js-controller that has the ability to check if configured port is available only for the configured IP. This makes the live for a setup with e.g. a reverse proxy much easier.

For further details see

https://github.com/ioBroker/ioBroker.js-controller/issues/351

**Comment by wendy2702** [comment]
Can you please check if this is working with actual Version of Admin and JS-Controller.
