### ISSUE TITLE
system.adapter.?.alive Datenpunkt wird mit NULL ausgegeben (admin 3.6.2)

### ISSUE THREAD

**Issue by LJSven** [ioBroker/ioBroker.admin#425]
Ich habe ein Javascript, was den ALIVE Datenpunkt überwacht. In unregelmäßigen Abständen werden "verschiedene" Adapter für eine ganz kurze Zeit mit "Null" befüllt und anschließend wieder auf "true" gesetzt. Woran kann das liegen?

2019-09-16 15:46:45.499  - info: javascript.0 script.js.common.Sonstige.ZZ_Batteriestatus_Mihome: Anzahl Geräte: 3 # davon LOWBAT erkannt: 0
--
2019-09-16 15:51:52.149  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Auslösender Aktor: system.adapter.enigma2.0.alive: null
2019-09-16 15:51:52.155  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Anzahl Geräte: 47 # davon ALIVE erkannt: 2
2019-09-16 15:51:52.170  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Auslösender Aktor: system.adapter.enigma2.0.alive: true
2019-09-16 15:51:52.177  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Anzahl Geräte: 47 # davon ALIVE erkannt: 2
2019-09-16 15:52:37.167  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Auslösender Aktor: system.adapter.enigma2.0.alive: null
2019-09-16 15:52:37.172  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Anzahl Geräte: 47 # davon ALIVE erkannt: 2
2019-09-16 15:52:38.176  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Auslösender Aktor: system.adapter.enigma2.0.alive: true
2019-09-16 15:52:38.180  - info: javascript.0 script.js.common.Sonstige.ZZ_Adapterstatus: Anzahl Geräte: 47 # davon ALIVE erkannt: 2

**Comment by Apollon77** [comment]
Wie ist die Last im System und beim js-Controller und den Adapter Prozessen?

An sich setzt der Adapter Prozess den alive Datenpunkt alle 15s mit einer expire Zeit von 30s. Bedeutet: nach 30s wird der Wert auf null gesetzt.

Das würde rein theoretisch bedeuten das das System sehr unter Last sein muss das hier Updates auf der Strecke bleiben. 

Siehst du im Admin die anderen System.adapter.xy.* States auch alle 15s aktualisieren?

**Comment by LJSven** [comment]
Die Datenpunkte werden regelmässig aktualiesert. Hier mal ein flot von meinem Tinkerboard - kannst du da was drauf erkennen?

![Bildschirmfoto 2019-09-16 um 20 41 16](https://user-images.githubusercontent.com/8560588/64984205-96fe1600-d8c2-11e9-816f-3fc9c349273e.png)

**Comment by Apollon77** [comment]
Die Skala der load fehlt. Was sagt denn ein einfaches "top" so?
Wie viele Objekte? Wieviele State Aktualisierungen so? Das wird im Admin angezeigt

**Comment by LJSven** [comment]
![Bildschirmfoto 2019-09-16 um 21 55 52](https://user-images.githubusercontent.com/8560588/64988935-cfa2ed00-d8cc-11e9-8946-0746761181e4.png)

![Bildschirmfoto 2019-09-16 um 21 55 14](https://user-images.githubusercontent.com/8560588/64988945-d598ce00-d8cc-11e9-9cd2-5d6f155c5ea2.png)

Ein einfaches Top sagt js-cron zwischen 5-15% / javascript das gleiche. 
Objekte: 6903, Zustände: 5784

![Bildschirmfoto 2019-09-16 um 21 58 55](https://user-images.githubusercontent.com/8560588/64989199-493adb00-d8cd-11e9-85cd-dcf7d71f619c.png)

**Comment by Apollon77** [comment]
Also ich habe nochmal code geschaut ... Im Standard kommen die Werte alls 15000ms (=15s) und der expire geht 10ms länger ... 

Zeig mal die Instanz ansicht

**Comment by LJSven** [comment]
Was meinst du genau? Diese?

![Bildschirmfoto 2019-09-17 um 07 44 03](https://user-images.githubusercontent.com/8560588/65014471-1c171880-d91f-11e9-80be-820b97927837.png)

![Bildschirmfoto 2019-09-17 um 07 44 13](https://user-images.githubusercontent.com/8560588/65014479-233e2680-d91f-11e9-9413-3be5d8b5f3ad.png)

![Bildschirmfoto 2019-09-17 um 07 44 23](https://user-images.githubusercontent.com/8560588/65014484-29340780-d91f-11e9-94b5-1e4f981a140e.png)

![Bildschirmfoto 2019-09-17 um 07 44 31](https://user-images.githubusercontent.com/8560588/65014495-2f29e880-d91f-11e9-8811-d7584d3626f7.png)

**Comment by Apollon77** [comment]
Ja,bitte nochmal mit aktiviertem expertenmodus. Dann wird angezeigt wieviele messages so fliessen

**Comment by LJSven** [comment]
![Bildschirmfoto 2019-09-18 um 07 30 01](https://user-images.githubusercontent.com/8560588/65114268-74651d80-d9e6-11e9-9948-ab974363f38b.png)

![Bildschirmfoto 2019-09-18 um 07 30 12](https://user-images.githubusercontent.com/8560588/65114274-7b8c2b80-d9e6-11e9-8583-d6752d7c27ea.png)

![Bildschirmfoto 2019-09-18 um 07 30 37](https://user-images.githubusercontent.com/8560588/65114278-8050df80-d9e6-11e9-9826-53a373534c4b.png)

![Bildschirmfoto 2019-09-18 um 07 30 57](https://user-images.githubusercontent.com/8560588/65114281-847cfd00-d9e6-11e9-8471-56e9f896971a.png)

**Comment by LJSven** [comment]
Ist das alles soweit korrekt?

**Comment by Apollon77** [comment]
sieht an sich ok aus. Ich finde die 1077 "ausgehenden" Events bei daswetter interessant :-) kann das was damit zu tun haben das es auftritt wenn der adapter kurz läuft?

**Comment by LJSven** [comment]
Es scheint als wenn der Ausgang immer so hoch ist. Im Moment steht er auf alle 45 Minuten. Wie würdest du ihn einstellen?

**Comment by LJSven** [comment]
Mir fällt aber gerade auf, daß wenn ich die Instanz auf dem Master laufen lassen, habe ich "8 ausgehende Events" - wenn ich die Instanz auf dem Slave laufen lasse kommen "769 ausgehende Events"

![Bildschirmfoto 2019-09-24 um 13 26 27](https://user-images.githubusercontent.com/8560588/65507907-447ab600-decf-11e9-9dc1-59777a417c0d.png)

![Bildschirmfoto 2019-09-24 um 13 28 37](https://user-images.githubusercontent.com/8560588/65507917-4ba1c400-decf-11e9-998b-8ded75da7ede.png)

**Comment by Apollon77** [comment]
DasWetter läuft nur in seinem Schedule ... jede Minute (macht das sinn?) ... keine Ahnung zu welchen Zeitpunkten er da ggf was an Daten lädt oder nicht ... War nur ne Frage ob die ALive Fehler immer kommen wenn der "losballert und 1000 Werte auf einmal setzt" oder ob das andere Zeitpunkte sind.

**Comment by wendy2702** [comment]
@LJSven : kann das hier geschlossen werden?
