### ISSUE TITLE
3.6.5 error ENOENT

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#426]
![grafik](https://user-images.githubusercontent.com/6681528/65130001-c5800c00-d9fc-11e9-9db2-e631c6a9bcc6.png)

**Comment by ldittmar81** [comment]
@arteck Wie oft kommt das vor? Welche Version hattest du vorher drauf?

**Comment by arteck** [comment]
zuvor war die 3.6.4
das kommt immer wenn ich das system neu starte.. der Pfad existiert bei mir auch nicht ...geschweige den die Datei

**Comment by Apollon77** [comment]
Da ist auch ein lib Zuviel im Pfad denke ich.

**Comment by ldittmar81** [comment]
https://github.com/ioBroker/ioBroker.admin/commit/0a0dc90596d3ab37764759ec019ba75b10f9d52d#diff-dbffe44e8e225d080405eaea4a578828

Da ist es rein gekommen

**Comment by Apollon77** [comment]
Ne denke ist eher dirname + ../www/...
