### ISSUE TITLE
Switch from http to https - but adapter navigation side bar not

### ISSUE THREAD

**Issue by crocri** [ioBroker/ioBroker.admin#428]
Hello!
Just switched to https with a certificate (admin.0). All custom admin tabs still working, but none of the adapter tabs are working. Node-Red and Terminal (for example) works with https too, but only if I open the link from the instance in another browser tab.

Reason is simple. Admin module is not changing the references in the buttons (src=):

<iframe class="iframe-in-tab" style="border: 0; solid #FFF; display: block; left: 0; top: 0; width: 100%; height: 100%" src="http://hostname:1880/?instance=0"></iframe>

has to be changed to

<iframe class="iframe-in-tab" style="border: 0; solid #FFF; display: block; left: 0; top: 0; width: 100%; height: 100%" src="https://hostname:1880/?instance=0"></iframe>

Then all adapters are working again (if it is possible to switch to https).

No reason not to do, because adapters do also not work with http because of a xml directive in the page set by admin module (iframes have to use the same protocol as the main page).

Best regards
Crocri

**Comment by wendy2702** [comment]
@crocri Is this still open?

**Comment by WLAN-Kabel** [comment]
I couldn't reproduce this behavior in the current version. If the problem still persists, please reopen the issue.
