### ISSUE TITLE
Input Textarea autoresize won't work

### ISSUE THREAD

**Issue by hacki11** [ioBroker/ioBroker.admin#436]
Adding a textarea input field will not autoresize due to a overridden css option.

Textarea does not resize:
![image](https://user-images.githubusercontent.com/15319906/66259989-c6fd5280-e7b8-11e9-9328-e1c27ac2ea84.png)

**Style**:
![image](https://user-images.githubusercontent.com/15319906/66260000-e8f6d500-e7b8-11e9-9648-071fe60639d0.png)

**Problem**:
hiddendiv is used to calculate the height of the textarea. adapter.less sets the hiddendiv display: none - therfor the height is always 0 => no updating of textarea.

**Workaround**:
Add to your adapter style.css:
```
.hiddendiv {
    visibility: hidden;
    display: block;
}
```
![image](https://user-images.githubusercontent.com/15319906/66260050-c3b69680-e7b9-11e9-82d3-46ca9bf5c505.png)

![image](https://user-images.githubusercontent.com/15319906/66260023-4428c780-e7b9-11e9-93e7-ad9731996b1f.png)

**Reference Style** of materializecss.com:
![image](https://user-images.githubusercontent.com/15319906/66260028-560a6a80-e7b9-11e9-8ad9-b12c226417cc.png)

**Comment by wendy2702** [comment]
@hacki11 Is this still open?
