### ISSUE TITLE
getState, getStates returns old values

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#438]
https://github.com/ioBroker/ioBroker.admin/blob/master/lib/socket.js#L695
https://github.com/ioBroker/ioBroker.admin/blob/master/lib/socket.js#L705

By onChange cache the value, and by unsubscribe clear whole cache

**Comment by ldittmar81** [comment]
Bad mistake that should be corrected urgently.

**Comment by AlCalzone** [comment]
The links lead to some unrelated lines. Please update them with permalinks:
![grafik](https://user-images.githubusercontent.com/17641229/66578079-bf53fa00-eb7a-11e9-90c4-51534508bae2.png)

**Comment by wendy2702** [comment]
@Apollon77 @AlCalzone : can this be closed?
