### ISSUE TITLE
After disabled events, subscribe only stored IDs

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#439]
https://github.com/ioBroker/ioBroker.admin/blob/master/lib/socket.js#L1185

**Comment by Apollon77** [comment]
this.subscribes.stateChange over all sockets

**Comment by wendy2702** [comment]
@Apollon77 : is this still open?

**Comment by GermanBluefox** [comment]
Sorry: what does this bug about?

**Comment by Apollon77** [comment]
is fixed in the meantime I think ... should be this https://github.com/ioBroker/ioBroker.admin/blob/7c09becdaee387df08edc1cfe03cb97a7549df27/lib/socket.js#L1541-L1542
