### ISSUE TITLE
Tab Scripte / Visual

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.admin#44]
Das Feld 'Aktiviert' im Tab 'Scripte' ist unübersichtlich. Man kann die 'true' und 'false' nur schlecht unterscheiden. Sinngemäss dem Tab 'Instanzen', wo das Feld 'Aktiviert' mit 'Ja' und 'Nein' einerseits übersetzt und andererseits auch noch farbig 'rot' und 'grün' unterschieden wird.

**Comment by GermanBluefox** [comment]
Sollte gefixt sein.
