### ISSUE TITLE
with 3.6.8 not able to select older versions on all adapters

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.admin#441]
after update to 3.6.8 it is not possible to select and install older versions  of all adapters

**Comment by ihavenonick** [comment]
Diskussion dazu unter:
[Forum](https://forum.iobroker.net/topic/25689/admin-v3-6-8-keine-alte-version-mehr-ausw%C3%A4hlbar/5)

**Comment by ldittmar81** [comment]
I found the error and will fix it.
https://github.com/ioBroker/ioBroker.admin/blob/0d6030847737b49c3e2bd6bfc41eaa379611981e/src/js/adminAdapters.js#L1625
