### ISSUE TITLE
Adapter Anleitung noch mit "SUDO"

### ISSUE THREAD

**Issue by andiling** [ioBroker/ioBroker.admin#443]
Hallo, sollten die Kommandos nicht ohne Sudo ausgeführt werden?
![Adapter Issue Anleitung](https://user-images.githubusercontent.com/20771598/66661640-a2392d00-ec47-11e9-9d75-0e5c588ac5ab.png)

**Comment by ldittmar81** [comment]
Kann man das inzwischen nicht automatisieren? Per Knopfdruck updaten? Jetzt wo Installationen per Skript und Installern gehen?

**Comment by ldittmar81** [comment]
Naja... Und geht es nicht kaputt, wenn man es manuell macht? Man müsste es halt gut loggen, vielleicht noch eine Methode es rückgängig zu machen, wenn es schief geht. Automatisch ein Backup vorher machen. Es wäre bestimmt möglich es ziemlich sicher zu machen.

**Comment by Apollon77** [comment]
Wie wäre s mit entfernen der Sudos und anfügen eines satzes der auf den fixer bei Problemen verweist? Sollten wir ggf angehen bevor wir controller 2.0 in stable machen!!

**Comment by Apollon77** [comment]
done in 3.6.12
