### ISSUE TITLE
Alle Adapter auf eine bestimmte Log Stufe stellen

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#445]
Hallo,
Interessant wäre eine Option das man Alle Adapter auf eine bestimmte Log Stufe stellen kann?
Ich möchte aber Alle Adapter auf zB. warn stellen. Das muss ich derzeit für jeden einzeln machen.
Oder gleich als Standard im Adapter warn, wie @paul53  es Vorgeschalgen hat?

https://forum.iobroker.net/topic/25692/js-controller-2-0-ab-sofort-im-latest-repo/201

**Comment by intruder7777** [comment]
dazu bitte noch den LogLevel für den Host einstellbar. Aktuell "Info" und nicht veränderbar

**Comment by Apollon77** [comment]
Loglevel vom Host ist änderbar in iobroker-Data/iobroker.json oder zur Laufzeit über system.host.name.loglevel. 

Ist es wirklich ein use case den man einigt braucht das man es irgendwie im Admin braucht alle Adapter auf einen loglevel zu setzen?

**Comment by Diginix** [comment]
Loglevel vom Host ist bei mir auch warn und von den meisten Adaptern, die mir zuviel zyklische Infozeilen generieren. Könnte also schon hilfreich sein alle Instanzen gesammelt auf warn stellen zu können und dann den kleineren Teil wieder zurück auf z.B. info. Oder man würde es in irgend einer Form selektiv machen. Aber alles nur nice2have. Steuerbar ist es jetzt schon, nur der Komfort fehlt. Aber wie viele den wirklich brauchen...

**Comment by intruder7777** [comment]
@Apollon77  Dieses Ändern ist aber nicht benutzerfreundlich. Besteht denn nicht die Möglichkeit dieses über den Admin einstellbar zu machen?

**Comment by DutchmanNL** [comment]
> @Apollon77 Dieses Ändern ist aber nicht benutzerfreundlich. Besteht denn nicht die Möglichkeit dieses über den Admin einstellbar zu machen?

stimme ich zu, wen dan auch mit Vorsicht genießen den das aendern auf loglevel Debug bzw silly von allen adapter gleichzeitig kan ein RIESEN problem verursachen.
Ich sag nur io-overload auf der SD karte usw

Wen überhaupt, stimme ich dem Vorschlag zu aber nur mass edit auf info / warn / error, debug und silly dürfen nicht in mass meiner Meinung nach.

Als Zusatz, die adapter welche viel info spammen sollte eventuell Überwegen das standard loglevel auf warn ein zu stellen anstatt log.



> @Apollon77 Dieses Ändern ist aber nicht benutzerfreundlich. Besteht denn nicht die Möglichkeit dieses über den Admin einstellbar zu machen?

Dafuer bitte ein neues issue sonst geht es unter.
Make log level of JS-Controller instance adjustable in admin

**Comment by sigi2345** [comment]
> auf loglevel Debug bzw silly

Die würde ich ausschließen. Also nur die Möglichkeit **Alle** Adapter auf Info oder warn.
