### ISSUE TITLE
Adapter list broken during upload

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#448]
![grafik](https://user-images.githubusercontent.com/17641229/66948503-20853d00-f055-11e9-8c76-08961e85ff33.png)

**Comment by wendy2702** [comment]
Hi,

Just did a test using IPAD Air with Safari and can‘t reproduce with Admin 4.1.1

Did a upload of i.e. RPI Adapter and „Icons“ are visible while upload is ongoing and after upload is finished.

Can you please test once again.

**Comment by AlCalzone** [comment]
I just reproduced with Firefox on Windows (Admin 4.0.9). Steps:
1. Start upload of an adapter that takes longer
2. Minimize the progress window
3. Switch to instances tab
4. Switch back to adapters tab

I'll try again with 4.1.1

**Comment by AlCalzone** [comment]
Still happens in 4.1.1

**Comment by wendy2702** [comment]
Which Adapter do you upload?

**Comment by AlCalzone** [comment]
see screenshot ;) iQontrol

**Comment by wendy2702** [comment]
OK. Can confirm that it‘s not working.

**Comment by wendy2702** [comment]
@GermanBluefox @Apollon77 you need to check.

**Comment by GermanBluefox** [comment]
Admin5 does not have this problem
