### ISSUE TITLE
Log-Einträge

### ISSUE THREAD

**Issue by ykuendig** [ioBroker/ioBroker.admin#45]
Im Tab 'Log' werden nur eine begrenzte Anzahl Einträge geladen. Offensichtlich passiert das unabhängig vom Filter. Wenn nun nämlich viele 'debug' Meldungen laufen, kann man im Log trotz filter 'info' nichts sehen.

**Comment by Apollon77** [comment]
Kannst DU das bitte nochmal mit einer aktuellen Admin Version testen?!
