### ISSUE TITLE
Menüeintrage automatisch anzeigen nach Installation

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#450]
Nach der Installation von Adaptern mit Menüeinträge, sollten diese automatisch im Admin Menü angezeigt werden. Es ist verwirrend dass ich was installiere und nichts passiert. 

<img width="182" alt="Screenshot_2" src="https://user-images.githubusercontent.com/9552828/67008690-54f70880-f0ea-11e9-9168-f7f9c5ee6d5b.png">

**Comment by GermanBluefox** [comment]
Done in Admin5
