### ISSUE TITLE
Verify Compact mode for your adapter

### ISSUE THREAD

**Issue by ioBrokerChecker** [ioBroker/ioBroker.admin#453]
We have detected that your adapter supports the compact mode. Please use the latest js-controller 2.0 and verify that everything works.

Some more information what is important to check can be found at https://github.com/ioBroker/ioBroker.js-controller/issues/512 

On questions please answer to the linked issue. Please close this issue after your test and add the version number that you have tested please as a comment.

Thank you for your support.

**Comment by wendy2702** [comment]
Done
