### ISSUE TITLE
Admin tab link does not work

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#454]
When opening iQontrol or node-red from the admin tabs the connection gets rejected:

![image](https://user-images.githubusercontent.com/49171332/67435303-1b436780-f5ec-11e9-8ac6-82ee346b7528.png)

Console shows:
![image](https://user-images.githubusercontent.com/49171332/67435314-23030c00-f5ec-11e9-9fd7-9eba310a65af.png)

Here is the definition of the admin tab of iQontrol:
````
"adminTab": {
 "singleton": true,
 "name": {
 "en": "iQontrol",
 "de": "iQontrol",
 "ru": "iQontrol",
 "pt": "iQontrol",
 "nl": "iQontrol",
 "fr": "iQontrol",
 "it": "iQontrol",
 "es": "iQontrol",
 "pl": "iQontrol",
 "zh-cn": "iQontrol"
 },
 "link": "%web_protocol%://%ip%:%web_port%/iqontrol/index.html?namespace=iqontrol.%instance%",
 "fa-icon": "blur_on"
 }
````

**Comment by Apollon77** [comment]
please retest with controller 2.0.39
