### ISSUE TITLE
Installed adapters only consider slave

### ISSUE THREAD

**Issue by cburghardt** [ioBroker/ioBroker.admin#455]
Admin: 3.6.10
js-controller: 2.0.35

The admin is running on my master and I have connected 2 slaves.
Since upgrading from js-controller 1.5 to 2.0 the list of installed adapters in the admin only shows the adapters from one slave as installed. When I switch to the list view all installed adapters are correctly listed. Also the list which is generated from the command line (iobroker update) is correct.
Sample attached, the ones which are shown as installed are from one slave. The ones on the master are missing.
![Bildschirmfoto 2019-10-24 um 14 28 09](https://user-images.githubusercontent.com/839480/67485541-8d5a9180-f66a-11e9-8b8b-7d321eaaa0d9.png)

**Comment by cburghardt** [comment]
One more aspect which seems related: also the log view only shows this slave. Is there somewhere a filter enabled?

**Comment by arteck** [comment]
You can switch the host on top .. You see..
