### ISSUE TITLE
Host-Update wird nicht angezeigt

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#463]
Mit aktuellem admin 3.6.12, wird im linken Menü kein Host Update angezeigt, obwohl es bereits verfügbar ist, nach Auswahl des Reiters Host, ist aber das Update, in dem Fall v.2.0.40, schon vorhanden.
Ebenfalls wurde auch bei jemanden das Host-Update unter Adapter angezeigt.
siehe
https://forum.iobroker.net/post/323176

**Comment by crunchip77** [comment]
![grafik](https://user-images.githubusercontent.com/41550245/68536289-c96f4100-0350-11ea-9ddb-bde701c5f7ba.png)

**Comment by wendy2702** [comment]
@crunchip77 : ist das auch mit den aktuellen Versionen noch der fall?

**Comment by crunchip77** [comment]
Nein,  aktuell funktioniert in der Hinsicht alles. Gab auch diesbezüglich in den letzten Versionen keine Probleme mehr.
