### ISSUE TITLE
SSL Zertifikat für Admin -> Keine Kette möglich

### ISSUE THREAD

**Issue by BeNeDeLuX** [ioBroker/ioBroker.admin#465]
Ich betreibe intern eine eigene Zertifikats Verwaltung (CA) und wollte jetzt ioBroker auf SSL umstellen. Leider habe ich im Webinterface unter der Admin Adapter in den Einstellungen nicht die Möglichkeit meine Zertifikatskette korrekt zusammen zu bauen, es ist nicht alles zur Auswahl.

Habe folgende Elemente importiert welche dafür nötig sind:

- Root CA
- Intermediate CA
- Wildcard Zertifikat
- Private Key für das Zertifikat

![all_certs](https://user-images.githubusercontent.com/1895086/68840456-13468700-06c3-11ea-97f4-6ba177756ec0.JPG)
Allerdings kann ich weder die RootCA noch das Intermediate CA auswählen:
![no_chain](https://user-images.githubusercontent.com/1895086/68840455-13468700-06c3-11ea-82ff-467bef9f201f.JPG)

Admin Adapter Version 3.6.12
Hier der Link zum Thread im Forum -> https://forum.iobroker.net/topic/26634/ssl-zertifikat-f%C3%BCr-admin-keine-kette-m%C3%B6glich

Plattform: linux
Die Architektur: x64
CPUs: 6
Geschwindigkeit: 3554 MHz
Modell: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
RAM: 62.8 GB
System-Betriebszeit: 15 T. 16:28:47
Node.js: v10.17.0
NPM: 6.11.3
Datenträgergröße: 39.2 GiB
Datenträger verfügbar: 8.8 GiB
Adapter-Anzahl: 259
Betriebszeit: 1 T. 12:26:34
Aktive Instanzen: 37

**Comment by wendy2702** [comment]
Ist das Problem noch offen?

**Comment by BeNeDeLuX** [comment]
Ich habe kein "Verkettetes Zertifikat" ausgewählt (da ja keines zur Auswahl steht) und ja SSL für die Adminoberfläche geht damit. Daher ist es für mich erledigt. Danke!

**Comment by dwm66** [comment]
Anscheinend existiert das Problem aber noch ... hab das grade auch nicht hingekriegt.
Ebenso scheint es nicht möglich zu sein, verkettete Zertifikate einzufügen, da landet immer nur das Erste ...

Einziger Workaround: Die volle Zertifikatskette als file abzuspeichern und zu referenzieren (als public), das klappt.

**Comment by BlackHawk3000** [comment]
> Anscheinend existiert das Problem aber noch ... hab das grade auch nicht hingekriegt. Ebenso scheint es nicht möglich zu sein, verkettete Zertifikate einzufügen, da landet immer nur das Erste ...
> 
> Einziger Workaround: Die volle Zertifikatskette als file abzuspeichern und zu referenzieren (als public), das klappt.

Hatte das Problem gerade auch und kann somit bestätigen, dass der "Fehler" noch in der aktuellen Version vorhanden ist.

**Comment by mcm1957** [comment]
> > Anscheinend existiert das Problem aber noch ... hab das grade auch nicht hingekriegt. Ebenso scheint es nicht möglich zu sein, verkettete Zertifikate einzufügen, da landet immer nur das Erste ...
> > Einziger Workaround: Die volle Zertifikatskette als file abzuspeichern und zu referenzieren (als public), das klappt.
> 
> Hatte das Problem gerade auch und kann somit bestätigen, dass der "Fehler" noch in der aktuellen Version vorhanden ist.
> 

Wenn ein Problem existiert dann eröffne dich ein neues Issue. Remarks in einem GECHLOSSENEN Issue werden sicher zu keiner Änderung führen.

**Comment by mhoster83** [comment]
> > Anscheinend existiert das Problem aber noch ... hab das grade auch nicht hingekriegt. Ebenso scheint es nicht möglich zu sein, verkettete Zertifikate einzufügen, da landet immer nur das Erste ...
> 
> > 
> 
> > Einziger Workaround: Die volle Zertifikatskette als file abzuspeichern und zu referenzieren (als public), das klappt.
> 
> 
> 
> Hatte das Problem gerade auch und kann somit bestätigen, dass der "Fehler" noch in der aktuellen Version vorhanden ist.
> 
> 
> 
> Mit deinem Workaround habe ich es aber jetzt "absichern" können, vielen lieben Dank, hast mir viele Std erspart :)

@BlackHawk3000 

Ich hänge genau an der gleichen Stelle, bekomme es aber irgendwie nicht hin. Kannst du nähere Details geben, wie du es eingerichtet hast? Vielen Dank

**Comment by mcm1957** [comment]
Das Issue ist seit 2020 GESCHLOSSEN.

Falls ein aktuelles Problem vorliegt bitte ein neues Issue öffnen.

**Comment by BlackHawk3000** [comment]
> > > Anscheinend existiert das Problem aber noch ... hab das grade auch nicht hingekriegt. Ebenso scheint es nicht möglich zu sein, verkettete Zertifikate einzufügen, da landet immer nur das Erste ...
> > 
> > 
> > > 
> > 
> > 
> > > Einziger Workaround: Die volle Zertifikatskette als file abzuspeichern und zu referenzieren (als public), das klappt.
> > 
> > 
> > Hatte das Problem gerade auch und kann somit bestätigen, dass der "Fehler" noch in der aktuellen Version vorhanden ist.
> > Mit deinem Workaround habe ich es aber jetzt "absichern" können, vielen lieben Dank, hast mir viele Std erspart :)
> 
> @BlackHawk3000
> 
> Ich hänge genau an der gleichen Stelle, bekomme es aber irgendwie nicht hin. Kannst du nähere Details geben, wie du es eingerichtet hast? Vielen Dank

Gerne versuche ich dir weiter zu helfen.
Es ist etwas missverständlich beschrieben in den Einstellungen. 

Als erstes generierst du dir deine zwei "Zertifikate" - einmal den Private und deinen Chain. 
Nun erstellst du dir über die Konsole den Ordner /opt/cersts und speicherst dort deine beiden Dateien. 
Danach in den EInstellungen die beiden "Zertifikate" verlinken. Wichtig hier den Chained musst du unter Public abspeichern und NICHT unter Chain. 

![Bildschirmfoto 2024-06-17 um 18 17 01](https://github.com/ioBroker/ioBroker.admin/assets/70750116/ac2c35af-f624-4515-ae12-6f3cfbd36438)

Und zum Schluss aktivierst du HTTPS und wählst deine Zertifikate in den EInstellungen der AdminInstanz aus. 

![Bildschirmfoto 2024-06-17 um 18 18 10](https://github.com/ioBroker/ioBroker.admin/assets/70750116/6e511fa2-e812-40f7-aa2c-36cbebc91d9d)

Hoffe dir hilft das weiter :)

**Comment by mhoster83** [comment]
@BlackHawk3000 Es hat endlich funktioniert. Vielen herzlichen Dank
