### ISSUE TITLE
Admin with "non-admin user" is not loading

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#466]
I have set up Admin with SSL and Auth. I created a User-Group and gave this group all rights like Admin group, I now created a user and put it into this group.

I now tried to login, worked, BUT Admin UI was not really loading. The "frame" was loading, but no left navigation and also no admon version number and no main frame content.just loadling bar.
Also with seeral reloads nothing loaded in the end.

I tried to debug and set some breakpoints .... after this it loaded with triggering those breakpoints ... I would assume some kind of timing issue?

**Comment by GermanBluefox** [comment]
Admin5 works
