### ISSUE TITLE
kein Login möglich mit aktivierter checkbox "angemeldet bleiben"

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.admin#467]
Der Login mit einem User (mit SSL and Auth, egal ob Admin oder anderer User) funktioniert solange man die Checkbox "angemeldet bleiben" **nicht** aktiviert. Mit aktivierter Checkbox wird man nicht eingeloggt und es gibt auch keine Meldung auf dem Loginschirm.

Log-File gibt auch nicht viel her:

_2019-11-19 07:13:33.149 - debug: admin.0 (3634) Unsubscribe STATES: info.0.newsfeed
2019-11-19 07:13:33.151 - debug: admin.0 (3634) Unsubscribe LOGS: dummy
2019-11-19 07:13:33.152 - debug: admin.0 (3634) Disable logging, because no one socket connected
2019-11-19 07:13:43.152 - debug: admin.0 (3634) Change log subscriber state: FALSE
2019-11-19 07:13:43.159 - debug: admin.0 (3634) system.adapter.admin.0: logging false_

![image](https://user-images.githubusercontent.com/54232526/69122128-524b5280-0a9e-11ea-987d-12883ee3bcfc.png)

Betriebssystem: linux, Ubuntu 18.04.3 
Architektur: x64
Node.js: v10.17.0
NPM: 6.11.3
js-controller: 2.1.0
iobroker.admin: 3.6.12

**Comment by LymanZerga** [comment]
Bei mir das gleiche. Mit der Checkbox eingeloggt bleiben aktiv komm ich nicht rein.

**Comment by CrEaK** [comment]
Kann ich bestätigen. Auch bei mir der Fall.

**Comment by Diginix** [comment]
Ist bei mir auch der Fall. Sowohl beim admin als auch beim web Adapter
Wenn ich als Login Timeout zB 864000 für 10 Tage hinterlegt habe, würde die Session dann durch den Haken dauerhaft am Leben bleiben? Mangels validem SSL Zert bei lokaler IP, merkt sich Chrome ja auch keine Logindaten für Websiten mehr. Ich muss also immer händisch die Logindaten eingeben.

nodejs 10.17.0
npm 6.9.0
JS-Controller 2.1.1
admin 3.7.2
web 2.4.10

**Comment by davincino** [comment]
Ich habe selbes Problem, was mir aber aufgefallen ist: obwohl der Haken "Angemeldet bleiben" nicht gesetzt ist, funktioniert es so als wäre er gesetzt.

Hatte in der Admin und Web Instanz noch die 3600s als default drin und musste mich regelmäßig neu anmelden. Seitdem ich gestern die Zeit auf 3600000s erhöht hatte muss ich mich nicht mehr seit gestern Abend anmelden.

Von mir aus müsste nun nur noch die Optik der Anmelde-Seite überarbeitet und der Haken für "Angemeldet bleiben" entfernt werden.
Dann wäre das Problem gelöst. Könnt ihr das bestätigen?

**Comment by HGlab01** [comment]
Wenn ich 3600000 eintrage, kann ich mich gar nicht mehr einloggen und musste ein weitere Instanz über CommandLine installieren um das wieder zu reparieren!

**Comment by davincino** [comment]
Hast du versucht eine etwas kürzere Zeit zu verwenden? Um zumindest den Fall zu reproduzieren, dass der Haken in "Angemeldet bleiben" nicht mehr notwendig ist?

**Comment by HGlab01** [comment]
Bin auch auf js-controller 2.1.1
Für mich sind das zwei unterschiedliche features. Den Timeout hoch zu drehen ist max. ein Workaround und gilt global für alle Geräte und alle User.
Das ist komplett was anderes wie einen spez. User für ein spez. Gerät angemeldet zu lassen.
Mit 999999 Sekunden funktioniert es bei mir - ist aber eben für mich keine gleichwertige Alternative und aus Security-Sicht ein NoGo.

**Comment by ymurawski** [comment]
Ich lese mal mit, wollte nach Monaten ohne Passwort gestern mal alles absichern... Jedoch ist das wirklich nervig das man sich immer neu anmelden muss, da ich bei mir im Flur alles über ein großes Tablet steuere

**Comment by dpomt** [comment]
> Kann ich bestätigen. Auch bei mir der Fall.

gleiches Problem hier

**Comment by pantau1962** [comment]
Es wäre schön, wenn der timeout im web.0-Adapter bei aktivierter Authentifizierung ausgeschaltet werden könnte, da ich Bereich des Dauerbetriebes im privaten Flur keine ständige neue Anmeldung erwünscht ist. Mit der VIS-Funktion "logout" kann man, wenn gewünscht, das logout manuell durchführen.
Hat einer eine Idee wie das umgesetzt werden könnte?

**Comment by Killi138** [comment]
Hier auch das selbe Problem. Nach Aktivieren der Checkbox und "erfolgreichem" Login erscheint die gleiche Login-Seite.

Aus dem Log:

`
/var/log/daemon.log <==
Jan 19 15:53:12 ioBroker bash[718]: (node:718) TimeoutOverflowWarning: 2592000000 does not fit into a 32-bit signed integer.
Jan 19 15:53:12 ioBroker bash[718]: Timeout duration was set to 1.

/var/log/syslog <==
Jan 19 15:53:12 ioBroker bash[718]: (node:718) TimeoutOverflowWarning: 2592000000 does not fit into a 32-bit signed integer.
Jan 19 15:53:12 ioBroker bash[718]: Timeout duration was set to 1
`

**Comment by Apollon77** [comment]
Kann es sein das Du den Timeout Wert auf 30 tage setzen wolltest? Das ist ein bissl viel. Nimm bitte einen kleineren Wert! Maximum wären grob 24 Tage (am besten nimm eher 23 Tage)

**Comment by Killi138** [comment]
> Kann es sein das Du den Timeout Wert auf 30 tage setzen wolltest? Das ist ein bissl viel. Nimm bitte einen kleineren Wert! Maximum wären grob 24 Tage (am besten nimm eher 23 Tage)

Ähm ich wollte gar nichts spezielles sondern die Funktion nutzen ;-) habe keinerlei Werte verstellt. Wo stellt man die denn ein?
Wollte mit meinen Logs nur helfen

**Comment by Apollon77** [comment]
Ok. Interessant ;-)

**Comment by HGlab01** [comment]
schaut ja fast so aus als würde man mit der Checkbox den Timeoutwert auf 2592000000  setzen versuchen ;-)
Dann wäre der Bug ja sehr einfach zu fixen

**Comment by Apollon77** [comment]
Ich glaube das ist es ... das war der fehlende Hinweis.
Wenn man "remember" macht werden 30 tage als maxage im cookie gesetzt ... diese Info aus dem Cookie wird im Sessionstore ebenso ausgelesen und für die Session genutzt - bei einer FileDB im controller ist das quasi ein "setTimeout" um die Session zu löschen ... daher ... interessant
@GermanBluefox

**Comment by Apollon77** [comment]
Ich glaube wir fixen es im js-controller ...

**Comment by Apollon77** [comment]
js-controller 2.2.8 ist raus. Bitte testen!
