### ISSUE TITLE
Scripte werden nicht angezeigt

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#474]
der Reiter Scripte ist leer, cache wurde geleert, downgrade auf admin 3.6.12 und javascript 4.3.0 hat nichts gebracht:
`

admin.0 | 2019-12-08 15:58:50.977 | debug | (7474) Unsubscribe OBJECTS: system.adapter.javascript.*
-- | -- | -- | --
admin.0 | 2019-12-08 15:58:50.977 | debug | (7474) Unsubscribe OBJECTS: script.*
admin.0 | 2019-12-08 15:58:50.976 | debug | (7474) Unsubscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2019-12-08 15:58:50.975 | debug | (7474) Unsubscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2019-12-08 15:57:09.065 | debug | (7474) Subscribes: system.adapter.javascript.*.alive, javascript.0.scriptProblem.*
admin.0 | 2019-12-08 15:57:09.064 | debug | (7474) Subscribe STATES: javascript.0.scriptProblem.*
admin.0 | 2019-12-08 15:57:07.796 | debug | (7474) Subscribes: system.adapter.javascript.*.alive
admin.0 | 2019-12-08 15:57:07.795 | debug | (7474) Subscribe STATES: system.adapter.javascript.*.alive
admin.0 | 2019-12-08 15:57:07.789 | debug | (7474) Subscribes: dummy

`Bin jetzt wieder auf beide Aktuellen Adapter gegangen

**Comment by BuZZy1337** [comment]
Was sagt die Browser Console dazu?

**Comment by guergen1** [comment]
Hier die Konsole von Firefox: 
![grafik](https://user-images.githubusercontent.com/34395245/70459190-f039a800-1ab3-11ea-90e0-85f1f7b55253.png)
![grafik](https://user-images.githubusercontent.com/34395245/70459226-047da500-1ab4-11ea-8487-836ccb454f95.png)
![grafik](https://user-images.githubusercontent.com/34395245/70459262-19f2cf00-1ab4-11ea-9ad8-272cb258cbe0.png)

**Comment by BuZZy1337** [comment]
Liegt am Enigma2 Adapter.

(Siehe auch hier: https://forum.iobroker.net/topic/27219/gel%C3%B6st-skripte-im-blockly-sind-ausgeblendet/26)

Bitte dort ein Issue öffnen.
https://github.com/Matten-Matten/ioBroker.enigma2/issues

Danke :)

**Comment by guergen1** [comment]
Ich habe bereits die neuste Version 1.2.8 installiert.
Issue wurde eröffnet!
Danke!

**Comment by BuZZy1337** [comment]
Has been fixed in iobroker.enigma2 with https://github.com/Matten-Matten/ioBroker.enigma2/commit/04816ca23a22306c8ed6999e7c85d3c90a24deef
