### ISSUE TITLE
Feature request: Add a way to push messages from the adapter code to its configuration dialog

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#475]
We currently have a one-way communication:
```
		sendTo(null, "commandName", args, ({ error, result }) => {
			// ...
		});
```
can be used to send a message from the config dialog to the adapter code. The adapter code can respond once, but it cannot actively push multiple messages to the config dialog, since it has no access to the embedded socket.io instance.

A possible workaround is polling from the frontend and storing the callbacks in the adapter code for later use - but this is pretty ugly.

I would really like if there was a way to easily push multiple messages to the frontend.

**Comment by GermanBluefox** [comment]
I use states for that: https://github.com/ioBroker/ioBroker.lovelace/blob/master/admin/index_m.html#L426

**Comment by GermanBluefox** [comment]
Just now I have no idea how to implement it other-ways.

**Comment by Apollon77** [comment]
But in fact the adapter needs to know when the admin page of the adapter or the tab is shown to only send those messages then. Else we have a log of irrelevant Traffic. And Thomson’s Bad when admin is used via cloud!!

So we would need some kind of enable/disable mechanism too. 

Maybe a default „push state“ per instance like system.adapter.name.instance.AdminPush or such and admin page subscribes to it and also unsubscribes ....

**Comment by AlCalzone** [comment]
> So we would need some kind of enable/disable mechanism too.

Since the admin pages already need to subscribe to objects and states if they need them, we could make them subscribe to messages too (similar to adapters) and unsubscribe when closing the page.

**Comment by Apollon77** [comment]
But exactly this is the topic ... messages are implemented on a "instance" level ... so "admin.0" subscribes to messages and then need to relay them and it needs to support decidning for which admin page they are. So it is an "admin specific message routing/subscription handling" needed

**Comment by AlCalzone** [comment]
The frontend knows which instance it is for (`adapter` and `instance` variables). So it could subscribe using that as a parameter: `socket.emit("subscribeMessages", `${adapter}.${instance}`, callback)`;
The admin instance would only relay the messages if they come from that instance.

By the way, how does the admin instance know which instance should receive the messages when the frontend does `sendTo(null, message, ...)`. Those are already relayed to the correct instance.

**Comment by GermanBluefox** [comment]
> By the way, how does the admin instance know which instance should receive the messages when the frontend does `sendTo(null, message, ...)`. Those are already relayed to the correct instance.

https://github.com/ioBroker/ioBroker.admin/blob/master/src/js/adapter-settings.js#L1072

**Comment by foxriver76** [comment]
Now possible - Example:

Backend: https://github.com/ioBroker/ioBroker.cameras/blob/master/main.js#L235 or with controller v5 https://github.com/ioBroker/ioBroker.cameras/blob/master/main.js#L235
Frontend: https://github.com/ioBroker/ioBroker.cameras/blob/master/src-widgets/src/RtspCamera.jsx#L247
