### ISSUE TITLE
3.7.3 Adapterliste wird nicht geladen

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#479]
Nach dem Update auf 3.7.3 wird die Adpaterliste nicht mehr geladen:
![grafik](https://user-images.githubusercontent.com/34395245/71554714-4353aa80-2a23-11ea-8d77-dd243a58426c.png)

**Comment by GermanBluefox** [comment]
Any browser console errors?

**Comment by garmatron** [comment]
I have the same Problem. 
"iobroker list adapters" is working. 

![image](https://user-images.githubusercontent.com/59332022/71555343-7732ce00-2a2b-11ea-94ff-6db87d18f862.png)

**Comment by DerDom2010** [comment]
Same problem here since Update.

I see no Error in Log on Debug Level

**Comment by Ilovegym66** [comment]
Works fine with js-controller 2.2.2 , nofaults.

**Comment by m0rph2k** [comment]
Das gleiche bei mir auch bei mehrern Iobrokern ioBroker.admin 3.7.3 ,js-controller 2.1.1 bzw auch 2.0.35

**Comment by gravidigit** [comment]
Selbes Thema hier. Gerade upgedatet bevor ich ins git geschaut habe :) 

Admin Version: 3.7.3

Node.js
    v10.18.0
NPM
    6.13.4

Restart und iobroker upgrade self hilft nicht.

**Comment by Colt89** [comment]
Selbes Problem hier

**Comment by Apollon77** [comment]
Bitte die Änderung bei getObjectList prüfen. Wenn nur zwei Params dann ist das der Grund. Im Controller 2.1 war der options nicht optional. Erst in controller 2.2.2 gefixt 

Kann das der Grund sein?

**Comment by m0rph2k** [comment]
Bitte die Änderung bei getObjectList prüfen --> wenn man mir sagt was genau mach ich das, fange leider damit nichts an. Ein Update des JS Controlers auf 2.2.2 wird im Iobroker nicht angezeigt vll mal manuell machen ?

**Comment by m0rph2k** [comment]
Ich hab mal iobroker auf einem raspberry neu Installiert dort läuft JS controller 2.1.1 dort funktioniert die 3.7.3 version :/

**Comment by JF62** [comment]
Sorry, aber auch der 3.7.4 lädt nicht die Adapterliste
Plattform: linux
RAM: 3.8 GB
Node.js: v10.15.2
NPM: 6.12.1
JS 2.1.1 (update wird nicht angeboten)

**Comment by m0rph2k** [comment]
Ja stimmt

**Comment by DerDom2010** [comment]
Update auf 3.7.4 weiterhin keine Adapterliste
Downgrade auf 3.7.2 gemacht, alles I.O.

js-controller 2.1.1

**Comment by JF62** [comment]
Ist ja kein Beinbruch, wir wissen ja, wie ein Downgrade funktioniert. Wenn wir irgendwelche weiteren Infos liefern sollen... Gerne

**Comment by Kampfratte** [comment]
Bei mir auch
Update auf 3.7.4 weiterhin keine Adapterliste
Downgrade auf 3.7.2 gemacht
auch js-Controller 2.1.1 und kein Update angezeigt auf 2.2.2

**Comment by Mr-REM-Esq** [comment]
> Downgrade auf 3.7.2 gemacht, alles I.O.
How to do it?

**Comment by JF62** [comment]
Via ssh/telnet:
_iobroker_ update admin3.7.2__

**Comment by Mr-REM-Esq** [comment]
Thank you. But now I have another problem.

"This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory."

**Comment by m0rph2k** [comment]
> 
> 
> Thank you. But now I have another problem.
> 
> "This adapter cannot be installed directly from github.
> You must install it from npm.
> Write for that "npm install iobroker.admin" in according directory."

Same problem

**Comment by m0rph2k** [comment]
3.7.5 gleiches Problem !?

**Comment by m0rph2k** [comment]
Bei mir ladet es wieder bei der 3.7.5 Version

**Comment by gravidigit** [comment]
Kann ich bestätigen. Läuft bei mir mit 3.7.5 auch wieder.

**Comment by Kampfratte** [comment]
3.7.5 läd bei mir auch wieder

**Comment by Mr-REM-Esq** [comment]
> > Thank you. But now I have another problem.
> > "This adapter cannot be installed directly from github.
> > You must install it from npm.
> > Write for that "npm install iobroker.admin" in according directory."
> 
> Same problem

Did you solve the problem?

**Comment by m0rph2k** [comment]
> 
> 
> > > Thank you. But now I have another problem.
> > > "This adapter cannot be installed directly from github.
> > > You must install it from npm.
> > > Write for that "npm install iobroker.admin" in according directory."
> > 
> > 
> > Same problem
> 
> Did you solve the problem?

Update to 3.7.5
