### ISSUE TITLE
Reiterbeschriftung hosts nicht grün bei neuer Version

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#48]
Die Beschriftung "Hosts" wir bei einem verfügbaren update nicht grün markiert.
Erst wenn der Reiter geöffnet wird.

**Comment by GermanBluefox** [comment]
Fixed in 0.5.10

**Comment by Homoran** [comment]
Nicht ganz.
Nach Starten des "Suche nach Updates"-Buttons wird die Beschriftung des Reiters Adapter grün, die des Reiters Hosts nicht. Selbst nach Öffnen dieses Tabs ist dort noch kein Update zu sehen, es ist nach wie vor 0.7.11 Installiert und verfügbar. Erst nach refresh (F5) ist die 0.7.12. zu sehen, dann ist auch die Beschriftung grün.

**Comment by GermanBluefox** [comment]
In Admin3 fixed
