### ISSUE TITLE
3.7.4 Adapterliste wird nicht geladen

### ISSUE THREAD

**Issue by JF62** [ioBroker/ioBroker.admin#480]
Sorry, aber auch der 3.7.4 lädt nicht die Adapterliste
Plattform: linux
RAM: 3.8 GB
Node.js: v10.15.2
NPM: 6.12.1
JS 2.1.1 (update wird nicht angeboten)

Nach downgrade auf 3.7.2 läuft alles wieder

**Comment by Mr-REM-Esq** [comment]
How do I downgrade?

**Comment by realwax** [comment]
+1 
njs 10.17
npm 6.14
js 2.1.1

**Comment by Moeinator** [comment]
So geht es mir leider auch :(

Plattform: linux
Die Architektur: x64
CPUs: 1
Geschwindigkeit: 3504 MHz
Modell: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
RAM: 1.9 GB
System-Betriebszeit: 00:13:52
Node.js: v10.18.0
NPM: 6.13.4
Adapter-Anzahl: 311
Datenträgergröße: 9.3 GiB
Datenträger verfügbar: 6.1 GiB

**Comment by Apollon77** [comment]
Duplicate #479

**Comment by JF62** [comment]
schließen ist ja ok, aber Problem besteht ja weiterhin auch in 3.7.4 und #479 ist als fixed markiert für 3.7.3

**Comment by FRYYYYYY** [comment]
> schließen ist ja ok, aber Problem besteht ja weiterhin auch in 3.7.4 und #479 ist als fixed markiert für 3.7.3

Ja, korrekt. Glaube, dass 3.7.5 gerade released wurde. Ggf ist es da gefixed, hatte aber noch keine Chance es zu testen.

**Comment by S401967** [comment]
In der Version admin@3.7.5 werden bei mir wieder die Adapter-liste angezeigt.

 
![image](https://user-images.githubusercontent.com/33559376/71564242-a8e47d00-2a9d-11ea-998e-3149a00597a3.png)
