### ISSUE TITLE
nach admin update 3.7.5 tab adapter lädt nicht mehr

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.admin#482]
Habe gerade admin auf 3.7.5 upgedatet, seitdem lädt der tab Adapter ewig

**Comment by Apollon77** [comment]
Shift reload? Anderer Browser tut oder auch nicht? Wirklich 3.7.5? 3.7.3 und 4 hatten dieses Problem. Adapter erstatten?

**Comment by lhoem** [comment]
Hatte das Gleiche nach dem Update auf 3.7.4 gestern. Habe gerade über den Info Tab auf 3.7.5 aktualisiert und nach der Installation beim Info und Adapter Tab mit Shift & Reload alles wieder sichtbar! Danke für Deine hervorragende Arbeit Apollon77!

**Comment by ajeder** [comment]
Hallo,
habe ebenfalls das Problem nach Update auf 3.7.5, jedoch wirkt bei mir der Tip mit Shift+Reload leider nicht. Ein anderer Browser nützt leider auch nichts.
Kann ich per bash den Admin wieder zu einer früheren Version downgraden?
Ich wäre Euch für einen Hinweis dankbar.

Gruß,
Axel

**Comment by Apollon77** [comment]
Und du bist sicher das es 3.7.5 ist?

**Comment by ajeder** [comment]
Hallo Apollon77,
danke für Deine Frage.
Ich habe gerade eine manuelle Installation der 3.7.5 durchgeführt und damit war mein Problem behoben. Daher kann ich Deine Frage jetzt nicht mehr nachträglich kontrollieren und beantworten.
Wie gesagt, die nachträgliche Installation hat das Problem jedoch gelöst.
Vielen Dank.
Ausserdem vielen Dank an das Engagement der vielen Leute hier im Forum.

Gruß,
Axel

**Comment by Farmer-cb** [comment]
Bei mir auch, 
Im iobroker rechts oben wird 3.7.5 angezeigt.
Shift reload bringt nix, aber wenn ich die seite im inkognito mod öffne gehts

**Comment by GermanBluefox** [comment]
> Bei mir auch,
> Im iobroker rechts oben wird 3.7.5 angezeigt.
> Shift reload bringt nix, aber wenn ich die seite im inkognito mod öffne gehts

js-controller version ?

**Comment by GermanBluefox** [comment]
Sollte gefixt sein

**Comment by Farmer-cb** [comment]
> > Bei mir auch,
> > Im iobroker rechts oben wird 3.7.5 angezeigt.
> > Shift reload bringt nix, aber wenn ich die seite im inkognito mod öffne gehts
> 
> js-controller version ?

ist die 2.1.1 am laufen
hab jetzt die admin version 3.7.7 installiert, leider ohne erfolg.

**Comment by Farmer-cb** [comment]
> > Bei mir auch,
> > Im iobroker rechts oben wird 3.7.5 angezeigt.
> > Shift reload bringt nix, aber wenn ich die seite im inkognito mod öffne gehts
> 
> js-controller version ?

ist die 2.1.1 am laufen
hab den admin jetzt auch auf 3.7.7, aber leider ohne verbesserung

**Comment by Farmer-cb** [comment]
> > Bei mir auch,
> > Im iobroker rechts oben wird 3.7.5 angezeigt.
> > Shift reload bringt nix, aber wenn ich die seite im inkognito mod öffne gehts
> 
> js-controller version ?

ist die 2.1.1 am laufen
hab den admin jetzt auf 3.7.7, leider ohne verbesserung

**Comment by Farmer-cb** [comment]
habe aus versehen geschlossen, kann man das wieder löschen

**Comment by wendy2702** [comment]
@Farmer-cb ist das noch ein Thema oder läuft es mittlerweile?

**Comment by Farmer-cb** [comment]
Ist immer noch ein Thema, hab mir zur zeit so geholfen, das ich die adminseite im inkognito-mode geöffnet habe

**Comment by wendy2702** [comment]
Welche Version vom Adapter läuft jetzt?

Welche Version JS-Controller?

iobroker -v
iobroker admin -v

Gibt es dazu einen Thread im iobroker Forum?

**Comment by Farmer-cb** [comment]
iobroker -v  **3.0.20**
iobroker admin -v **4.1.1**

Gibt es dazu einen Thread im iobroker Forum? 
[Welche Version vom Adapter läuft jetzt?

Welche Version JS-Controller?

iobroker -v
iobroker admin -v

[https://forum.iobroker.net/topic/30089/adapter-l%C3%A4dt-nicht-nach-host-%C3%A4nderung-bei-alter-ip-adresse](url)

**Comment by Apollon77** [comment]
Und du hast wirklich browser cache inklusive der "local storges" komplett mal gelöscht?

**Comment by Farmer-cb** [comment]
im chrome auf Einstellungen -> Browserdaten löschen -> Bilder und Dateien im Cache anklicken und dann auf Daten löschen.

"local storages" löschen hat geholfen, bis ich das ding gefunden habe.
iobroker öffnen strg+shift+i ->links auf Storages-> localstorages und dann clear
