### ISSUE TITLE
Eingabe Filter unter Objekte / Name führt zu Endlosschleife

### ISSUE THREAD

**Issue by Knallochse** [ioBroker/ioBroker.admin#486]
Leider führt ein setzen eines Filters unter Objekte / Name bei mir zu einer Dauerschleife
![image](https://user-images.githubusercontent.com/36857242/71762859-3fb59d00-2ed5-11ea-87bc-c16a0fdf3ab5.png)

Wäre es möglich den Admin Adapter zu erweitern, dass etwas ins Log geschrieben wird, um den Fehler ausfindig zu machen?

**Comment by Apollon77** [comment]
Steht irgendwas in der Browser console?
Welcher js-Controller ist im Einsatz?

**Comment by Knallochse** [comment]
Danke für deine Antwort: 
der  js-controller ist die 2.1.1
in der Console wird folgendes angezeigt

`selectID.js:2917 Uncaught TypeError: Cannot read property 'de' of null
    at K (selectID.js:2917)
    at jquery.fancytree-all.js:7881
    at F.visit (jquery.fancytree-all.js:2026)
    at F.visit (jquery.fancytree-all.js:2033)
    at F.visit (jquery.fancytree-all.js:2033)
    at F.visit (jquery.fancytree-all.js:2033)
    at D.visit (jquery.fancytree-all.js:3011)
    at D.e.ui.fancytree._FancytreeClass._applyFilterImpl (jquery.fancytree-all.js:7877)
    at D.e.ui.fancytree._FancytreeClass.filterNodes (jquery.fancytree-all.js:7946)
    at HTMLInputElement.<anonymous> (selectID.js:2986)
`

`jquery.fancytree-all.js:113 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.`

**Comment by Knallochse** [comment]
Kann ich noch etwas zur Fehlersuche beitragen, bzw. ist aus den Consolendaten des Browsers für euch der Fehler erkennbar?
Das Problem mit dem setzen des Filters habe ich mit allen Browsern (bei mir Edge, Chrome, Firefox und Safari) nachstellen können.

**Comment by Apollon77** [comment]
Ich tippe da bei dir irgendein Objekt kaputt ist und hier Admin aus dem Tritt bringt.

**Comment by Knallochse** [comment]
Hätten Sie einen Tip für mich, wie ich den fehlerhaften Datenpunkt finde. Aktuell befinden sich bei mir ca. 20.000 Datenpunkte unter Objekte. Im Logfile werden mir (auch unter Admin - debug) leider keine Fehler ausgegeben.

**Comment by wendy2702** [comment]
> selectID.js:2917 Uncaught TypeError: Cannot read property 'de' of null at K

Ist das noch aktuell? 

Wenn ja, ist die erste Zeile angeschnitten und kann eventuell mal vollständig gepostet werden?

**Comment by Knallochse** [comment]
Ja, Problem besteht noch.
Meinen Sie das mit erste Zeile?
![52924C27-8B09-4C06-B9F7-6D30930B5E6D](https://user-images.githubusercontent.com/36857242/80612528-5fe90900-8a3c-11ea-8af2-7beea8870497.jpeg)

**Comment by wendy2702** [comment]
ich meinte die erste Zeile aus dem Logfile.

Welche Version Admin und JS-Controller laufen aktuell?

**Comment by Knallochse** [comment]
Aktuell läuft mein System (Docker) mit folgenden Versionen
Node.js - v10.20.1 
NPM - 6.14.4
JS controller - 3.0.18
Admin - 4.0.9

Ich habe den Admin Adapter auf Debug gestellt. Bei setzen des Filters "Name" wird kein Fehler ausgegeben. In der Browser-Console (Chrome) erscheint bei Eingabe des Filters folgendes:

![image](https://user-images.githubusercontent.com/36857242/80622505-2e2a6f00-8a49-11ea-900d-e28040da5135.png)

Ich habe im Bild 2 wiederholende Meldungen, weil ich 2 verschiedene Filter eingegeben habe.

**Comment by Knallochse** [comment]
Fast vergessen: Danke, dass du mir versuchst zu helfen

**Comment by wendy2702** [comment]
Hm,

Gerade bei mir auf dem IPAD getestet mit JS-Controller 3.0.18 und Admin 4.1.1

Da geht das.

![1212FED4-282E-4980-9493-EE16F5654FB5](https://user-images.githubusercontent.com/33424168/80626207-5d8faa80-8a4e-11ea-9c61-298c8027a7a2.jpeg)

Kannst du mal auf der Konsole das machen und danach nochmal testen:

`iobroker upload all`

**Comment by wendy2702** [comment]
Hast du zufällig auch diesen „MoMA“ Adapter installiert?

**Comment by Knallochse** [comment]
Nein MoMA Adapter habe ich nicht installiert.
iobroker upload all läuft, aber das dauert noch eine ganze Weile

**Comment by Knallochse** [comment]
upload all ist durchgelaufen. Fehler bleibt
Iobroker neu gestartet. Fehler bleibt
Möchte noch ergänzen, dass das setzen des Filters unter ID funktioniert

**Comment by wendy2702** [comment]
Ist bestimmt wie im Forum beschrieben auch so ein Objekt mit falschem Namen.

Da es ja kein Bug in Admin ist, spricht etwas dagegen wenn wir das Issue schließen und im Forum weiter machen?

**Comment by Knallochse** [comment]
Hatte das Thema schon im Forum angesprochen, ohne Erfolg.
Ich würde mir wünschen, das IoBroker solche Proben selber abfängt.
Aber wenn es nur um das schließen Issues geht, dann halt zu.
Helfen konnte mir hier leider bisher niemand.
Trotzdem Danke für Ihre Bemühungen

**Comment by wendy2702** [comment]
Geht hier nicht nur um Schließen!

Ich habe keine Ahnung wie/ob der Admin das abfangen kann um entsprechend eine Meldung auszugeben oder ähnliches.

@GermanBluefox @Apollon77 @foxriver76 @ldittmar81 can somebody of you please check.

**Comment by Knallochse** [comment]
Fehler gefunden.
https://forum.iobroker.net/post/422286

**Comment by GermanBluefox** [comment]
Fixed in 5.0.17
