### ISSUE TITLE
update 3.7.6 (iobroker hängt sich auf)

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#487]
nach einem update von 3.7.5 auf 3.7.6 kommt es zu unerwünschten Fehlern, welche die Funktion beeinträchtigen, sei es die Darstellung im Browser( mit verschiedenen getestet) und auch die Funktion(Schraubenschlüssel)
![image](https://user-images.githubusercontent.com/41550245/71771011-cbaae180-2f34-11ea-9508-fb7df8568e31.png)ist funktionslos.
Forumsbeitrag https://forum.iobroker.net/post/351416

**Comment by Diginix** [comment]
Hilft dir nicht, aber bei mir ist alles ok mit admin 3.7.6 und JS-Controller 2.1.1
nodejs 10.18.0
npm 6.9.0
Xubuntu 19.10
Dürfte also kein generelles Problem sein.

**Comment by Apollon77** [comment]
Welcher js-Controller bei dir?

**Comment by crunchip77** [comment]
aktuell ist 2.2.4

**Comment by Apollon77** [comment]
versuch mal bitte mit 2.2.7

**Comment by crunchip77** [comment]
2.2.7 ist installiert, jedoch radar und dash-button problem, ich schreib im forum

**Comment by crunchip77** [comment]
läuft mit 2.2.7
