### ISSUE TITLE
aktualsierte Objekte werden angezeigt

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#488]
Obwohl ich in der Objekt-Ansicht alle Ordner zugeklappt habe, werden aktualisierte Werte und Datenpunkte angezeigt, die sich ändern.
Aber nur bis ich den Reload-Button drücke, danach bleibt die Liste ruhig. Ist etwas unvorteilhaft wenn man einen Dp sucht und die Liste sich ändert!

**Comment by GermanBluefox** [comment]
Hast du screenshots? Es ist nicht ganz klar was gemeint ist

**Comment by guergen1** [comment]
![grafik](https://user-images.githubusercontent.com/34395245/71784643-d1b4c700-2ff5-11ea-9ace-2ab1fa62553f.png)
 Der Wert Fritz Onlinestatus wurde grade aktualisiert, obwohl der Reiter javascript.0 geschlossen ist

**Comment by Apollon77** [comment]
Das kenne ich auch. Such dir nen ordner wo datenpunkte schnell/ oft aktualisiert werden. Dann klapp auf und kurz bevor ein state Change rein kommt Klappe Ordner zu. Dann kommen die sich aktualisierenden States des Ordners magisch wieder. 

Passiert vor allem wenn Adapter keine saubere Channel/devices Struktur haben und es damit nur einen subscribe auf oberster Ebene gibt. Passiert aber bei blödem timing bei sauberer Struktur. 

Also scheinbar wenn bei zugeklappten Ordner im Baum state Updates für States darunter kommen werden diese angezeigt und der „zugeklappt“ Status vom Baum ignoriert.

**Comment by GermanBluefox** [comment]
Admin5 ist anders
