### ISSUE TITLE
Funktion "Log Herunterladen" ist nicht kompatibel zu komprimierten Log-Dateien

### ISSUE THREAD

**Issue by Einstein67** [ioBroker/ioBroker.admin#489]
Die Schaltfläche "Log Herunterladen" im Log-Tab, ist nicht kompatibel zu den komprimierten (*.gz) Log-Dateien, die mit JS-Controller 2.2.x eingeführt wurden.

Es funktioniert beim Logfile des aktuellen Tages wie gewünscht, versucht man eine älteres (bereits komprimiertes) File zu öffnen, werden nur kryptische Zeichen angezeigt.

Die Archive sind in Ordnung. Manuelles downloaden, entpacken und öffnen funktioniert.

**Comment by Apollon77** [comment]
Ich denke der "application type" der Response muss korrekt gesetzt werden wenn die Endung ".gz" ist

**Comment by ToTXR4Y** [comment]
Es wird vermutlich an der Funktion liegen im Admin-Adapter wenn man auf Logfiles laden, das er dort auf "New Tab" anstelle auf "Save as" geht.

**Comment by GermanBluefox** [comment]
Please test with 3.7.8

**Comment by Mauflo** [comment]
> Please test with 3.7.8

There is no Button anymore ?! ;-)

**Comment by Diginix** [comment]
I have also no button in my log tab.
Nice try! ;-)

**Comment by Apollon77** [comment]
should be fixed in 3.7.9
