### ISSUE TITLE
Weboberfläche startet nach hostname Update nicht mehr

### ISSUE THREAD

**Issue by Schmidie64** [ioBroker/ioBroker.admin#490]
Hallo Zusammen,
ich habe gerade leider den Hostname meines Raspberry Pis verändert und den Pi neugestartet. Nun funktioniert das Webinterface leider nicht mehr. Ich habe den hostname wieder auf den Standart zurückgesetzt, was aber leider zu keine Besserung führte. 
Kann mir vielleicht jemand einen Tipp geben, was ich falsch mache?

P.S. Ich habe den Pi im Multihost-betrieb.
Grüße Schmidie

**Comment by Apollon77** [comment]
Am besten im Forum melden bei solchen Fragen. Ansonsten: was heißt das er nicht geht? Log? Generell tut ssh mit dem neuen Namen?
