### ISSUE TITLE
Storage-Schlüssel wird angezeigt, obwohl nicht aktiviert

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#491]
Bei einem meiner Dp wird hinten der Schraubenschlüssel angezeigt, obwohl KEINE Aktivierung vorliegt:
![grafik](https://user-images.githubusercontent.com/34395245/72210890-50ac7280-34c2-11ea-9d82-94f7aae98e73.png)
![grafik](https://user-images.githubusercontent.com/34395245/72210901-5efa8e80-34c2-11ea-9a8f-8615598792c2.png)

**Comment by Diginix** [comment]
Poste mal den Inhalt vom RAW des Objektes

**Comment by guergen1** [comment]
`{
  "from": "system.adapter.wiffi-wz.0",
  "user": "system.user.admin",
  "ts": 1566596960230,
  "common": {
    "name": 18,
    "desc": "w_power_4",
    "unit": "KW",
    "role": "value",
    "id": "Gasleistung",
    "type": "number",
    "read": true,
    "write": false,
    "custom": {
      "sql.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": "63072000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": "Gasleistung"
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "wiffi-wz.0.root.192_168_1_141.Gasleistung",
  "type": "state"
}`

**Comment by Apollon77** [comment]
Dann hattest Du wohl mal den sql Adapter installiert und dort Einstellungen gemacht .. und den dann deinstalliert ... ?! Die Einstellungen sind aber noch da

**Comment by guergen1** [comment]
Ja, das stimmt. Dann muss man erst alles ausschalten und dann den Adapter deinstallieren? Besser wäre es doch dass der Adapter das übernimmt :-)
Ich habe von sql auf influx umgestellt...
Grade den sql nochmal installiert und alles deaktiviert. jetzt diesen wieder runter!

**Comment by guergen1** [comment]
`{
  "type": "state",
  "common": {
    "read": true,
    "write": false,
    "desc": "w_power_4",
    "unit": "KW",
    "role": "value",
    "id": "Gasleistung",
    "name": "18",
    "type": "number"
  },
  "native": {},
  "from": "system.adapter.wiffi-wz.0",
  "user": "system.user.admin",
  "ts": 1566596960230,
  "_id": "wiffi-wz.0.root.192_168_1_141.Gasleistung",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`
