### ISSUE TITLE
Zeitfenster für Darstellung der mysql Daten stimmt nicht

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.admin#492]
Wenn man in den Objekten die Anzeige der mysql Daten nach Datum u. Uhrzeit eingrenzt,
dann stimmt die Anzeige nicht:
![grafik](https://user-images.githubusercontent.com/49147193/72255133-45625f80-3606-11ea-8312-dac7cfcf4a7b.png)

Wäre sehr schön, wenn das einmal jemand fixen könnte.
Vielen Dank

**Comment by Diginix** [comment]
Wie ist es denn wenn du das Datum in der Form eingibst wie es auch das System will.
Also "2020-01-13"?
So funktioniert es bei mir zumindest schon seit Jahren stabil, einschließlich neustem admin, js-controller usw.

Außerdem solltest du bei einem issue immer auch die VersionsNr der verwendeten Komponenten angeben. Hier also mind. JS-Controller und admin.

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Wie ist es denn wenn du das Datum in der Form eingibst wie es auch das System will.
> Also "2020-01-13"?
> So funktioniert es bei mir zumindest schon seit Jahren stabil, einschließlich neustem admin, js-controller usw.
> 
> Außerdem solltest du bei einem issue immer auch die VersionsNr der verwendeten Komponenten angeben. Hier also mind. JS-Controller und admin.

Also:
1.) Wenn eine Liste ausgegeben wird, dann sollte das Ergebnis mit den angezeigten Paramentern schon übereinstimmen.
2.) Das ist ja wohl selbstverständlich, dass ein aktuelles System verwendet wird. Woher soll ich denn wissen, welche Komponenten in Frage kommen?

**Comment by Diginix** [comment]
zu 1) Genau! Und du gibst dein Datum wissentlich in einem anderen Format ein als das was in der Ausgabe zu sehen ist.
zu 2) Definiere aktuelles System?
Es gibt nicht "ein aktuelles System" Es gibt latest oder stable und dazu noch verschiedene Platformen und nodejs/npm Versionen.

Welches Repo?
Welche JS-Controller Version?

ioBroker ist keine klickibunti plug&play noob Software. Wer dann keine Antworten auf Fragen liefert weil er es ggf nicht mal weiß, dem kann leider nicht wirklich geholfen werden.

**Comment by Hans-Zwiesel** [comment]
Auf diese Schlaumeierei-Hilfe kann man ja wirklich getrost verzichten.
Ein Tipp:
Versuche einfach, die Problemstellung nachzuvollziehen, dann können diese überflüssigen Fragen
leicht vermieden werden.

**Comment by Diginix** [comment]
Du postest einen Screenshot und auf Fragen antwortest du nicht. Also beziehe ich mich auf den Screenshot. Also komme ich dir mal entgegen: Was für ein "bis"-Datum soll 03:30 denn sein?

**Comment by Hans-Zwiesel** [comment]
Es gehört zum kleinen 1x1 eines jeden Programmierers:
Nach der Eingabe von Datum oder Uhrzeit **muß** eine Plausibilitäts-Prüfung erfolgen!
Diese geprüften Daten bilden dann die Grundlage für die Ausgabe einer Liste.
**Eine Liste, bei der die Parameter mit den Daten nicht übereinstimmen, darf es einfach nicht geben!**

**Comment by buanet** [comment]
Falls ich mich mal einmischen darf...
Ganz klar, für die Meldung des "Bugs" bekommt @Hans-Zwiesel sicher keinen Preis. Das ist deutlich ausbaufähig. Allein für die Anmerkung: 
> Wäre sehr schön, wenn das einmal jemand fixen könnte.

hätte ich den Issue sofort geschlossen...

Andererseits könnte man mal sachlich darüber diskutieren wie das Ergebnis aussehen sollte wenn die eingegebenen Daten für die Suche fehlerhaft sind.

Für mein Verständnis gibt es zwei Wege: 
1. Das Suchergebnis wird geleert und der Anwender kommt selbst darauf dass die Eingabe falsch sein muss
2. Das Suchergebnis der letzten Suche bleibt stehen (so wie es jetzt ist), es kommt aber eine Fehlermeldung "Suche konnte nicht ausgeführt werden. Bitte überprüfe deine Eingabe".

Ich würde den 2. Punkt bevorzugen. 

Zusätzlich könnte man die Suchfelder mit grauen Beispielwerten füllen, sodass sofort ersichtlich ist, in welchem Format die Daten eingegeben werden müssen...

MfG,
André

**Comment by Diginix** [comment]
Ach du hast gar kein Problem, weißt sogar wie alles besser wäre. Ich bin aber der Klugscheißer weil ich dir ernsthaft helfen wollte? Alles klar! Geh wo anders spielen oder commite ein fix!

**Comment by Ilovegym66** [comment]
@Hans-Zwiesel sorry, aber ... Da fehlen einem die Worte..
Wenn man fragt, um den Fehler eingrenzen zu können, dann antworte bitte sachgemäß und nicht mit so einem Unsinn wie "aktuelles System".. welches repo meinst du denn mit aktuell und welches System? Linux, Mac, Windows? Welches OS? 
Und wenn man unfähig ist, das Datum so einzugeben, wie es schon in der Liste steht. ... Da kann man sowieso nicht mehr helfen.. 
@Diginix schließ das hier wegen unzureichenden Informationen, ist ein Benutzer Fehler.

Ansonsten kann @Hans-Zwiesel  ja ein commit machen und das so fixen wie er das gerne hätte.

**Comment by Apollon77** [comment]
Ok, I checked a bit in debugger. It seems that the "Datepicker" is not working for the date parts and that why they simply stay empty in Code then (adminCustoms L388 und L390).

Because of this "start" and "end" are passed as NaN to the getHistory ....

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Ok, I checked a bit in debugger. It seems that the "Datepicker" is not working for the date parts and that why they simply stay empty in Code then (adminCustoms L388 und L390).
> 
> Because of this "start" and "end" are passed as NaN to the getHistory ....

Hallo Apollon77,
gut, dass es Leute wie Dich gibt, die tatsächlich etwas bewegen und nicht nur ihre
Besserwisserei hier verbreiten wollen.

**Comment by Apollon77** [comment]
@Hans-Zwiesel Der war unnötig! Jeder, und auch alle obigen versucht zu helfen wo er kann und wie er kann. Du tust Ihnen sehr unrecht mit diesen Worten

**Comment by Hans-Zwiesel** [comment]
> 
> 
> @Hans-Zwiesel Der war unnötig! Jeder, und auch alle obigen versucht zu helfen wo er kann und wie er kann. Du tust Ihnen sehr unrecht mit diesen Worten

Du hast ja recht. Aber mir geht immer der Hut hoch, wenn als Erstes auf Verdacht nach der Version nachgefragt wird bzw. Update empfohlen wird, obwohl der Frager gar nicht weiß, ob ein derartiger Fehler in einer aktuellen Version schon gefixt wurde.

**Comment by Diginix** [comment]
In qualifizierten Tickets gibt man immer alle relevanten Versionen, Plattformen usw. an. Erst recht wenn danach gefragt wird. Das ist das 1x1 eines Problemkindes. Es gibt TOs die haben uralt Systeme im Einsatz und melden Fehler, die längst behoben sind. Die Recherche kann man Entwicklern ersparen, wenn man gleich mit allem raus rückt. 
Da geht mir echt der Hut hoch.

**Comment by wendy2702** [comment]
Bei Eingabe vom Datum im richtigen Format funktioniert die Anzeige wie wir jetzt wissen. Deshalb bin ich so frei und schließe dieses Issue.
