### ISSUE TITLE
Session läuft ab trotz Aktivitäten

### ISSUE THREAD

**Issue by jpawlowski** [ioBroker/ioBroker.admin#493]
Ich werde leider ständig nach Ablauf eines Session Timeouts (30 Minuten?) ausgeloggt, obwohl ich aktiv in ioBroker hin und her navigiere. Ich würde erwarten, dass jede Aktivität die Session wieder auf die volle maximale Sessionlänge verlängert. Offenbar ist das aber nicht der Fall ;-(

Besonders ärgerlich ist das, weil sich der Timeout auch nur dadurch äußert, dass einige Aktivitäten nicht mehr richtig funktionieren oder man z.B. dann plötzlich ein Login Fenster innerhalb des Hauptframes bekommt. Bei einem Session Timeout hätte ich jedoch erwartet, dass dort entweder direkt ein Popup kommt oder gar ein Redirect auf die Loginseite stattfindet. So ist das Verhalten irgendwie unerwartet.

_Angemeldet bleiben_ ist übrigens auch keine Lösung, siehe #467

**Comment by Killi138** [comment]
Ich hänge mich hier mal dran, habe das selbe Problem - super nervig. 
Man loggt sich ein - gut.
Man klickt, man verwaltet, man tut - okay.
Irgendwann klickt man falsch - zack, login Fenster in einem iFrame. Okaaaayyyy?

=> Refreshe den Loginzeitpunkt nach einer Aktion und gut is....

**Comment by jpawlowski** [comment]
durch den fix in #467 ist das jetzt weniger wichtig. trotzdem wäre es cool, wenn das timeout bei nichtaktivität auch funktionieren würde ;-)

**Comment by wendy2702** [comment]
Hi,

Besteht das Problem noch mit der aktuellen Version Admin und JS-Controller?
