### ISSUE TITLE
New Feature: Log Files automatisch entpacken oder Download anbieten

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#495]
Wenn man "Log Files herunterladen" anklickt und dann ein älteres Log File auswählt, wird nur die gepackte Version im Browser angezeigt, die nicht lesbar ist.

Es wäre wünschenswert, wenn 
1. im Browser das log file entpackt würde, damit es lesbar ist
2.alternativ ein Download angeboten wird, der ein entpacktes Log File herunterlädt.

**Comment by Apollon77** [comment]
dulpicate #489
