### ISSUE TITLE
Versions-Anzeige in Instanzen Übersicht

### ISSUE THREAD

**Issue by ToTXR4Y** [ioBroker/ioBroker.admin#496]
Moin, es wäre toll wenn man als kleine zusätzliche Spalte die Version des verwendeten Adapters auch direkt in der Instanzenübersicht (z.B. neben dem LogLevel) sehen könnte. So kann man wirklich schnell nachschauen auf welcher Version man sich gerade befindet ;-)

**Comment by Apollon77** [comment]
Aus Platzgründen: ggf als mouseover über den Namen oder so auch eine Option?

**Comment by ToTXR4Y** [comment]
Von mir aus ja, alles einfacher und hilfreicher als erst über die Adapter Liste zu gucken ;-)
