### ISSUE TITLE
delObject leads to open and closing in Object overview

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.admin#497]
When I use delObject in an Adapter on a lot of items. All items are open clodes in the object tab like I'm deleting it manually. This is disturbing because this happens in the nina adapter every 5min.

**Comment by wendy2702** [comment]
Can you please update your description. At least to me it’s not clear what you are doing and what is the problem.

Thanks

**Comment by wendy2702** [comment]
May i ask why you are delete and recreate Objects? Wouldn’t it be better to have a fix structure on Objects. I.e. if somebody creates a script which is using one of your Objects it might be that the script today is working fine but not tomorrow because the Object is deleted.

**Comment by TA2k** [comment]
The structure is very complex and can change between each warning, device or update. With a fixed structure you have also to maintain when something is changed.

**Comment by TA2k** [comment]
Yes it would be nice if a createobject not let the object tree open up all new nodes

**Comment by DutchmanNL** [comment]
Hmm creating/Deleting object Alls time is very Bad i would sugges to change this in the Ninja adapter there are other ways how the can be archived without stressing the system that much

Happy to assist

**Comment by TA2k** [comment]
I will update this soon but anyway why is admin open new object automatically

**Comment by DutchmanNL** [comment]
> I will update this soon but anyway why is admin open new object automatically

interesting, I can reproduce when I do it with source analytix.
Here I created 100 states and about 5 channels but the sourceanalytix tree keeps closed.
Only when I open it, and than states are refreshing it happens.

So I would like to thread this issue in 3 ways : 

- Adapters should not create/delete objects in every one to prevent system load in generic
- Creation/deletion of objects and states should not open/close the folder structure
- same for states changes, as this is also very annoying and I assume in the same line of admin code

**Comment by GermanBluefox** [comment]
Please revalidater in Admin5
