### ISSUE TITLE
SAVE Button on wrench-icon behind a datapoint not working

### ISSUE THREAD

**Issue by Flashy-GER** [ioBroker/ioBroker.admin#498]
when I want change settings in this menu it is not possible to confirm the settings, because the SAVE Button is not working.
for Details, please have a look to these attached screenshots.

[Screenshot](https://www.directupload.net/file/d/5708/cm2sxv28_png.htm)

[console Output](https://www.directupload.net/file/d/5708/i7ll235z_png.htm)

[Code Part](https://www.directupload.net/file/d/5708/nd9ebyld_png.htm)

---

**System data:**

Platform: linux
Distribution: Raspbian GNU/Linux
Architecture: arm
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.81 GB
Node.js: v10.18.1
NPM: 6.13.6
JS-Controller (1): 2.1.1
Admin: 3.7.7
Admin: 3.7.7

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
Please check admin 3.7.8 and report back please.

**Comment by Flashy-GER** [comment]
Hi, I can confirm, the button is working again.
I was able to add and delete settings with admin 3.7.8. with JS 2.1.1
I update to JS 2.2.8 and the button is working in this combination as well.
