### ISSUE TITLE
[1] on hosts tab does not disappear after update

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#499]
I just updated my JS-Controller while I had the hosts tab in the Admin open in Firefox.
After upgrading, I pressed the reload button for the hosts tab. The tab content was correctly updated, but the tab still showed the `[1]`:
![grafik](https://user-images.githubusercontent.com/17641229/73204494-57341e80-413f-11ea-87dd-5ca8a4e8f0ab.png)

**Comment by AlCalzone** [comment]
Not stale

**Comment by AlCalzone** [comment]
Still not stale, shut up, bot!

**Comment by GermanBluefox** [comment]
Check Admin5
