### ISSUE TITLE
Button "Logfile Download" disapeared in 3.7.8

### ISSUE THREAD

**Issue by Mauflo** [ioBroker/ioBroker.admin#500]
The Button "Logfile Download" disapeared in the new Version 3.7.8! Is this a bug or a Feature? ;-)

**Comment by HGlab01** [comment]
Same here; I hope it is not a feature ;-)
JS-Controller: 2.2.8
Admin : 3.7.8
Node/Node.js: 10.18.1
OS: Linux Ubuntu 18.04.3 LTS

**Comment by WaJoWi** [comment]
Ditto! See also issue #501

**Comment by Steff42** [comment]
The same also here. In 3.7.7 everything was ok.
See also --> [https://forum.iobroker.net/topic/29441/log-button-nach-admin-update-verschwunden/3](url)

**Comment by HGlab01** [comment]
works again in v3.7.9 as expected
