### ISSUE TITLE
unpack the logfile when delivering via admin

### ISSUE THREAD

**Issue by WaJoWi** [ioBroker/ioBroker.admin#501]
Der Titel sagt eigentlich schon alles. ;-)

> *created by ioBroker.info*

**Comment by Baenker** [comment]
kann geschlossen werden. Ist mit der nächsten Version vom js-controller umgesetzt :-) Danke @Apollon77

**Comment by Apollon77** [comment]
No .... I changed a bit ... lets see if we can improve here

**Comment by wendy2702** [comment]
Can this be closed?
