### ISSUE TITLE
Admin Adapter update does not work

### ISSUE THREAD

**Issue by baeriwiliwonka** [ioBroker/ioBroker.admin#502]
Update via Webinterface is not working,
tried the manual way via ssh and sudo command and got following error message:

Update admin from @3.6.12 to @3.7.8

NPM version: 6.13.7

npm install iobroker.admin@3.7.8 --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! code EACCES

npm ERR! syscall access

npm ERR! path /opt/iobroker/node_modules/iobroker.admin

npm ERR! errno -13

npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.admin'

npm ERR! { [Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.admin']

npm ERR! stack:

npm ERR! 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.admin\'',

npm ERR! errno: -13,

npm ERR! code: 'EACCES',

npm ERR! syscall: 'access',

npm ERR! path: '/opt/iobroker/node_modules/iobroker.admin' }

npm ERR!

npm ERR! The operation was rejected by your operating system.

npm ERR! It is likely you do not have the permissions to access this file as the current user

npm ERR!

npm ERR! If you believe this might be a permissions issue, please double-check the

npm ERR! permissions of the file and its containing directories, or try running

npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:

npm ERR! /home/iobroker/.npm/_logs/2020-01-29T18_00_28_798Z-debug.log

host.iobroker Cannot install iobroker.admin@3.7.8: 243

What can be the root cause? Do I need to have special permissions and where can I set them.
Or is it a general problem with the update?

Thanks!

**Comment by Apollon77** [comment]
Please let the installation fixer tun and fix permissions.
