### ISSUE TITLE
Objekte Suche nach Name funktioniert nicht

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.admin#504]
Wenn ich im Reiter Objekte im Feld "Name" etwas eingeben, fängt nur der Kreisel an sich zu drehen, sonst passiert nichts. Den Fehler habe ich seit rund 5 Monaten. Im Forum findet man auch andere die das problem haben, aber eine  echte Lösung ist hier nicht 
[Forum](https://www.forum.iobroker.net/topic/22451/fehler-kein-filtern-im-admin-nach-name-mehr-m%C3%B6glich)

Wenn ich auf Expertenmodus umschalte oder F5 drücke wird die Suche einmalig ausgeführt, aber beim nächsten Tastendruck das gleiche.

Versionen:
Nodejs: v10.17.0
js-controller: 2.1.1
Admin: 3.7.9

Chrome Sagt im Debug bei jeder Tasteneingabe folgenden Fehler:

jquery.fancytree-all.js:113 Fancytree@2 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
v @ jquery.fancytree-all.js:113
warn @ jquery.fancytree-all.js:3019
e.ui.fancytree._FancytreeClass.filterNodes @ jquery.fancytree-all.js:7944
(anonymous) @ selectID.js:3041
dispatch @ jquery-3.2.1.min.js:3
m.handle @ jquery-3.2.1.min.js:3
selectID.js:2974 Uncaught TypeError: (n || "").toLowerCase is not a function
    at q (selectID.js:2974)
    at jquery.fancytree-all.js:7881
    at F.visit (jquery.fancytree-all.js:2026)
    at F.visit (jquery.fancytree-all.js:2033)
    at F.visit (jquery.fancytree-all.js:2033)
    at F.visit (jquery.fancytree-all.js:2033)
    at F.visit (jquery.fancytree-all.js:2033)
    at D.visit (jquery.fancytree-all.js:3011)
    at D.e.ui.fancytree._FancytreeClass._applyFilterImpl (jquery.fancytree-all.js:7877)
    at D.e.ui.fancytree._FancytreeClass.filterNodes (jquery.fancytree-all.js:7946)
q @ selectID.js:2974
(anonymous) @ jquery.fancytree-all.js:7881
visit @ jquery.fancytree-all.js:2026
visit @ jquery.fancytree-all.js:2033
visit @ jquery.fancytree-all.js:2033
visit @ jquery.fancytree-all.js:2033
visit @ jquery.fancytree-all.js:2033
visit @ jquery.fancytree-all.js:3011
e.ui.fancytree._FancytreeClass._applyFilterImpl @ jquery.fancytree-all.js:7877
e.ui.fancytree._FancytreeClass.filterNodes @ jquery.fancytree-all.js:7946
(anonymous) @ selectID.js:3041
dispatch @ jquery-3.2.1.min.js:3
m.handle @ jquery-3.2.1.min.js:3

**Comment by Omega236** [comment]
So ich habe nun rausgefunden wer schuld ist. (jetzt weiß ich zumindest auch wie man JS debugt)

Der Adapter Moma hat einige Kanäle/Geräte falsch erzeugt. Er hat den Namen nicht als string, sondern als Integer erzeugt. 

Es ist also kein fehler vom Admin-Adapter, aber es wäre schön wenn man es irgendwie mitbekommen würde was das Problem ist

`{
  "type": "channel",
  "common": {
    "name": 1
  },
  "native": {},
  "from": "system.adapter.moma.3",
  "user": "system.user.admin",
  "ts": 1580751546979,
  "_id": "moma.3.fsSize.1",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by wendy2702** [comment]
Duplicate to #486
