### ISSUE TITLE
Switch with push button functionality

### ISSUE THREAD

**Issue by drtp** [ioBroker/ioBroker.admin#505]
Hi,

some adapters like the yahka adapter are only based on switches. This leads to the problem that for e.g. TVs a respective button within the iOS Home App always toggles between on and off state, although it is only switched for a short time in order to set a respective TV channel or to change the volume. Hence, this is a somewhat unattractive look and feel. 

Therefore, I would like to have an option for switches that they automatically are set back to false after setting them to true. The switch back time should be something like 200 to 1000 ms. In addition, the switch should do nothing, when automatically switched back to false, in order to avoid a double switching behaviour. 

Of course, there already do exist buttons. However, the main drawback of them is that they do not give back any state information, which is mandatory for the yahka switches linked with them in order not to toggle their states between on and off.

**Comment by Apollon77** [comment]
Should not the respective adapter like yahka be responsible for this special behavior if needed? I do not see this a Basis feature of iobroker. 

Or better have yahka support buttons too ...

Or do understand the request wrong? Or do you need a general „button type state reset to false after being triggered with true“?

**Comment by drtp** [comment]
Well, in a certain way you are right. However, since datapoints can be created separately from adapters, it should give an option for not only defining them as buttons, switches and so on, but also to have the opportunity to define switches in the requested manner. Let's take the yahka adapter. I can understand, why it has not implemented the button functionality, because Apple does not support this directly. On the other hand, I already have filed a respective feature request for the yahka adapter as well. However, the yahka adapter used datapoints from other adapters. So the developer o the yahka adapter might argue that the developers of these adapters are responsible for the wished implementation. That's why I decided to position the feature request here. So to say on the highest level.

**Comment by Apollon77** [comment]
In fact from my point of view it is:

ioBroker supports buttons (triggers on any change - ideally with true, status is irrelevant because can not be read anyway) and switches (true/false = on/off). For Buttons there is no definition in "returning to false" or something  because they are only triggers.

If this is the way for own datapoints then you can create own JavaScripts that re-set your buttons to false after they got triggered with true, but in fact Yahka needs to make sure that based on the role the states are handled correctly. A button only triggers with "true" and read should always return false ... switches can be used like normal.

**Comment by drtp** [comment]
Okay. Thanks for explanation. Accordingly you can close this issue.

**Comment by BINARYADDlCT** [comment]
I would love to have a trigger feature, since there is no device or service type to trigger a KNX scene for example. These don't really have a reliable state to show if changed (whether it be in Homekit or elsewhere). Just to send a certain value to ioBroker, and go back to the initial state.

**Comment by Apollon77** [comment]
exists already. The role of the state needs to be "button".
