### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#506]
As discussed in the forum, I would appreciate to allow again creating own state structures in the root.

Maybe only in expert mode

**Comment by DutchmanNL** [comment]
suggest to only have this in Expert mode to provide a clean structure for regular end-users.

In "normal" circumstances its efficient enough to have 1 own data structure within Userdata.
(within that you are free to do all you want)
This also ensures "standardization" between systems and allows easier end-user support.

Main structure of root objects should remain reserved for adapters

**Comment by GermanBluefox** [comment]
No. Root is not allowed.
