### ISSUE TITLE
Tooltip notification  an improved versioning

### ISSUE THREAD

**Issue by calliou1234** [ioBroker/ioBroker.admin#507]
Hello,
it would be great when the tooltip notification could be improved including which version is beeing needed.
In my case the tooltip says only that the admin adapter has not the right version to update the javascript adapter, but not which version is needed.

Thanks
Calliou1234

**Comment by wendy2702** [comment]
Can you please test with actual Version of Admin Adapter and provide feedback.

**Comment by GermanBluefox** [comment]
Done in Admin5
