### ISSUE TITLE
Objekt Import Fehler ID

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.admin#508]
Hallo, bekomme beim Import einer json folgenden Fehler:

![Screenshot (1578)_LI](https://user-images.githubusercontent.com/41079106/73943201-a4a74d00-48f0-11ea-9b39-6a645ba44c47.jpg)

Siehe Beitrag im Forum:

https://forum.iobroker.net/topic/29801/gibt-es-einen-steuerungsbutton/20

Platform: Windows
Node.js: v10.16.3
JS : 2.2.8
NPM: 6.9.0
Admin: 3.7.9

**Comment by luft-post** [comment]
Bei mir genauso.

Platform: PI4
Node.js: v10.16.3
JS : 2.2.8
NPM: 6.9.0
Admin: 3.7.9

**Comment by Apollon77** [comment]
Wie sieht Euer JSON aus?

Wichtig!! Das JSON format sieht anders aus wenn man EIN Objekt hochlädt (dann ist es direkt das Object JSON) oder wenn man mehrere Objekte hochlädt (dann ist es ein Objekt mit den Objekt-IDs als Keys)

**Comment by sigi2345** [comment]
> Wie sieht Euer JSON aus?
> 
> Wichtig!! Das JSON format sieht anders aus wenn man EIN Objekt hochlädt (dann ist es direkt das Object JSON) oder wenn man mehrere Objekte hochlädt (dann ist es ein Objekt mit den Objekt-IDs als Keys)

`{
  "0_userdata.0.umschalten": {
    "_id": "0_userdata.0.umschalten",
    "type": "state",
    "common": {
      "name": "umschalten",
      "role": "",
      "type": "boolean",
      "read": true,
      "write": true,
      "desc": "Manuell erzeugt",
      "def": false
    },
    "native": {},
    "from": "system.adapter.admin.0",
    "user": "system.user.admin",
    "ts": 1580928582975,
    "acl": {
      "object": 1638,
      "state": 1638,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    }
  }
}`

**Comment by Apollon77** [comment]
And exactly this do not work!! One object means other format.

**Comment by sigi2345** [comment]
Danke, erledigt.
