### ISSUE TITLE
Link to instance on other Host

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.admin#51]
Node-Red läuft bei mir auf einem 2. Raspi (als slave oder client).
Wenn ich den Link unter Instanzen klicke, komm ich aber auf die IP von der Master-Installation.
Auch auf der Node-Red Lasche die nach der Installation erscheint kommt nichts.

**Comment by p33k** [comment]
Hatte erst eine funktionierende Single Host ioBroker Installation auf einem Raspberry mit node-red adapter (der im iobroker admin korrekt funktionierte) 192.168.1.10

Dann hab ich noch eine 2. iobroker installation als slave hinzugefügt, und die admin instanz dorthin "verschoben".
Jetzt funktioniert node-red im admin tab nichtmehr (Verbindung nicht gefunden).
Komischerweise aber auch nicht über 192.168.1.10:1880.
Das RF Funkmodul steuert node-red aber scheinbar noch korrekt an.

**Comment by wendy2702** [comment]
@GermanBluefox @Apollon77, has this been fixed?

**Comment by Apollon77** [comment]
I don't think so

**Comment by GermanBluefox** [comment]
Implemented in admin5
