### ISSUE TITLE
scripts.zip.zip not found

### ISSUE THREAD

**Issue by Pocky2507** [ioBroker/ioBroker.admin#510]
Der alte, schon behobene Fehler im Multihost:
`File 2020-02-07-scripts.zip.zip not found`
hat sich wieder eingeschlichen.

**Comment by Diginix** [comment]
Works for me with
javascript 4.3.4
admin 4.0
js-controller 2.2.8
nodejs 10.19.0
npm 6.9.0
Ubuntu 19.10
Testet with Chrome 79 on Windows 10.

**Comment by FredF63** [comment]
Ja, bei mir auch der Fehler
javascript 4.3.4
admin 4.0.0
js-controller 2.2.8
nodejs 10.18.1
npm 6.13.4
Mit Chrome 79, 80 und Firefox 72 probiert, Multihost, falls das wichtig ist

**Comment by Apollon77** [comment]
Was fixed in javascript 4.3.5 !! Really broken?

**Comment by Ilovegym66** [comment]
Ist fixed in 4.3.5 👍, funktioniert auch mit admin 4.x und neuem socketIo und web.

**Comment by Pocky2507** [comment]
Leute, ich schreibe das doch hier nicht aus Spass hin.
Ich weiss das es in 4.3.5 gefixt war.
Habe nun Java 4.3.8 und Admin 4.0.1 drauf und geht wieder.

**Comment by Apollon77** [comment]
Ok, also wieder gefixt ... hätte zwischendrin nie anders sein dürfen, wurde nix geändert.
