### ISSUE TITLE
Grössere Tasten im Adapter Menü

### ISSUE THREAD

**Issue by chefrocker** [ioBroker/ioBroker.admin#511]
Guten Tag
Ich bediene ioBroker teilweise auf meinem Tablet, das einzige problem was mich während meinen Bedienung am Tablet stört ist, dass die Buttons oben im Adaptermenü so klein sind. Könnte man da nicht eine Option machen, um die knöpfe zu vergrössern? Klar, einen kompletten Mobile Skin wäre noch besser, aber damit wäre mir schon erheblich geholfen🙂

**Comment by Apollon77** [comment]
Mit Admin 5 kommt eine Kachel-Ansicht an einigen Stellen dazu. Hier sollten wir checken das diese auf Mobile-Geräten gut bedienbar ist.
