### ISSUE TITLE
Safari (13.0.5) on MacOs doesn't opened the Adminpage

### ISSUE THREAD

**Issue by tugsi** [ioBroker/ioBroker.admin#512]
After installing Admin Version 4.0.0 or 4.0.1, I've got Problems on my MacBookPro with MacOs Mojave and the newest Safari (13.0.5).
Only the Header above is loaded, but nothing else. 
On Firefox it works.
Deleted Browser Cache und Local Storage, but no change.

After downgrading to 3.7.9, everything works again.

**Comment by EnnjiBennji** [comment]
Here is the same problem with chrome version 80.0.3987.87.
On Firefox it works!

**Comment by Apollon77** [comment]
Really deleted browser caches and local storage? And please use admin 4.0.1 in any case

**Comment by EnnjiBennji** [comment]
Yes, I deleted everything

**Comment by tugsi** [comment]
Same here, deleted Browser Cache, Local Storages like Cookies...
Tried with 4.0.0 and 4.0.1 , falling back to 3.7.9 everythings works, also without deleting cache etc

**Comment by Apollon77** [comment]
Are there errors in browser console? If yes which?

**Comment by tugsi** [comment]
Installed Latest Admin 4.0.1 again.
The JS-Konsole of Safari:
`Fancytree@1 – "Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead."`
Line 113 			fn.apply(window.console, args);
in jQuery.fancytree-all.js

Nothing more comes.

**Comment by Apollon77** [comment]
And now strange comes ... just updated and ma yAdmin 4.0.1 works on my Safari  13.0.5 also on Mojave.

So I need more details. Which port is used for admin? https or http?

**Comment by Apollon77** [comment]
Please also try „iobroker upload admin“ and a Full reload in your browser. And please show screenshot of browser console (text only can be misleading)

**Comment by tugsi** [comment]
And now my strange comes ...
Using the Night the Browser Console again and the Debugger too, it stopped with the Message how I wrote above.
But the I pressed the "Play"-Button in Debugger, the whole Adminpanel was loaded.
Ok, just give it a next try, I do the same, but again nothing happens, it stoke again.
Believe me, tried it most then ten times, every time it stoke and the Panel is not loaded.
In the meanwhile nothing changes, no cleaning, no restart or anything else.
I tried it again this morning and it works .... 
All Tabs in the left clicked, everything works.
Don't know what happened. No Browser Console, no Debugger.
Sorry I cannot tell you what happened over Night, how I tell, nothing changes. no Update or anything else.
Spooky...

**Comment by Apollon77** [comment]
sun flares? ;-) Feedback from the others?

**Comment by Apollon77** [comment]
Any news here?!

**Comment by Apollon77** [comment]
Is it now working or still broken?!

**Comment by tugsi** [comment]
From my side, everything alright now.

**Comment by Apollon77** [comment]
Please test with 4.0.5. and do Hard Reload in any case!!

**Comment by xxstasxx** [comment]
same problem there
Admin 4.1.1, Safari 13.1
At local Network works well and I have full access, but not via VPN
Google Chrome works...
