### ISSUE TITLE
log laden, Admin crasht

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#515]
Admin 4.0.1
wenn man versucht das log zu laden (gepackt) kommt die Meldung Seiten Ladefehler und der admin crasht
`

host.IoBroker | 2020-02-12 08:58:12.131 | info | instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
-- | -- | -- | --
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unzip.emit (/opt/iobroker/node_modules/minipass/index.js:307:25)
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unzip.emit (events.js:198:13)
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unzip.(anonymous function).on.chunk (/opt/iobroker/node_modules/tar/lib/parse.js:292:59)
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unpack.[consumeChunk] (/opt/iobroker/node_modules/tar/lib/parse.js:363:30)
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unpack.[consumeChunkSub] (/opt/iobroker/node_modules/tar/lib/parse.js:386:30)
host.IoBroker | 2020-02-12 08:58:12.131 | error | Caught by controller[1]:     at Unpack.[consumeHeader] (/opt/iobroker/node_modules/tar/lib/parse.js:105:20)
host.IoBroker | 2020-02-12 08:58:12.130 | error | Caught by controller[1]:     at new Header (/opt/iobroker/node_modules/tar/lib/header.js:39:12)
host.IoBroker | 2020-02-12 08:58:12.130 | error | Caught by controller[1]:     at Header.decode (/opt/iobroker/node_modules/tar/lib/header.js:54:16)
host.IoBroker | 2020-02-12 08:58:12.130 | error | Caught by controller[1]:     at decNumber (/opt/iobroker/node_modules/tar/lib/header.js:245:27)
host.IoBroker | 2020-02-12 08:58:12.130 | error | Caught by controller[1]:     at Object.exports.parse (/opt/iobroker/node_modules/tar/lib/large-numbers.js:53:11)
host.IoBroker | 2020-02-12 08:58:12.129 | error | Caught by controller[1]: TypeError: invalid base256 encoding
admin.0 | 2020-02-12 08:58:11.589 | info | (4809) Terminated (NO_ERROR): Without reason
admin.0 | 2020-02-12 08:58:11.587 | info | (4809) terminating
admin.0 | 2020-02-12 08:58:11.533 | info | (4809) terminating http server on port 8081
admin.0 | 2020-02-12 08:58:11.528 | error | at Unzip.emit (/opt/iobroker/node_modules/minipass/index.js:307:25)
admin.0 | 2020-02-12 08:58:11.528 | error | at Unzip.emit (events.js:198:13)
admin.0 | 2020-02-12 08:58:11.528 | error | at Unzip.(anonymous function).on.chunk (/opt/iobroker/node_modules/tar/lib/parse.js:292:59)
admin.0 | 2020-02-12 08:58:11.528 | error | at Unpack.[consumeChunk] (/opt/iobroker/node_modules/tar/lib/parse.js:363:30)
admin.0 | 2020-02-12 08:58:11.528 | error | at Unpack.[consumeChunkSub] (/opt/iobroker/node_modules/tar/lib/parse.js:386:30)
admin.0 | 2020-02-12 08:58:11.528 | error | at Unpack.[consumeHeader] (/opt/iobroker/node_modules/tar/lib/parse.js:105:20)
admin.0 | 2020-02-12 08:58:11.528 | error | at new Header (/opt/iobroker/node_modules/tar/lib/header.js:39:12)
admin.0 | 2020-02-12 08:58:11.528 | error | at Header.decode (/opt/iobroker/node_modules/tar/lib/header.js:54:16)
admin.0 | 2020-02-12 08:58:11.528 | error | at decNumber (/opt/iobroker/node_modules/tar/lib/header.js:245:27)
admin.0 | 2020-02-12 08:58:11.528 | error | at Object.exports.parse (/opt/iobroker/node_modules/tar/lib/large-numbers.js:53:11)
admin.0 | 2020-02-12 08:58:11.528 | error | (4809) TypeError: invalid base256 encoding
admin.0 | 2020-02-12 08:58:11.527 | error | (4809) uncaught exception: invalid base256 encoding

`
das selbe passiert auch, wenn man via VPN , das **aktuelle** Log aufrufen möchte, siehe
https://forum.iobroker.net/post/375734

**Comment by Apollon77** [comment]
@GermanBluefox It seems athat someting is broken with the unpack-tar stuff :-(

**Comment by wendy2702** [comment]
@crunchip77 : ich habe gerade mal mit Admin 4.1.1 getestet. Im Admin über den Button „Log Herunterladen“ das hat bei mir problemlos funktioniert.

Hast du das problem noch?

**Comment by crunchip77** [comment]
@wendy2702 nein es läuft. Problem bestand nur in v 4.0.1
