### ISSUE TITLE
Drag & Drop growing slower in enums edit

### ISSUE THREAD

**Issue by StrathCole** [ioBroker/ioBroker.admin#516]
When editing enums and dragging objects from the object list to the enums the process is growing slower with each element that is dragged and dropped.

Device: Firefox latest stable on Linux
Admin version: 4.0.1

Findings so far:
It must have to do with something that happens on drop event. When only dragging an element on the right and releasing it again (outside the enum list), the speed remains unchanged.

As soon as dropping an alement in an enum box (e. g. heating, light etc.) the next drag action has a slight delay (from mousedown to highlight of elements and helper appearing). This delay grows with each element that is dropped to the enum boxes.
A reload of the whole page resets the delay to zero again.

Attached you see the delay in the Firefox Developer Console (Runtime Profiling).
The delay not only grows before the drag starts but also on drop, so the interface is unresponsive for a growing amount of time after each drop, too (until you can click something again).

![Bildschirmfoto von 2020-02-13 10-47-54](https://user-images.githubusercontent.com/7449529/74426446-abd0dc80-4e55-11ea-908a-ed0023131cce.png)
![Bildschirmfoto von 2020-02-13 11-09-26](https://user-images.githubusercontent.com/7449529/74426448-ac697300-4e55-11ea-8eb9-b950931211c3.png)

**Comment by StrathCole** [comment]
Maybe this has to do with the updateCounters function:
![Bildschirmfoto von 2020-02-13 11-45-59](https://user-images.githubusercontent.com/7449529/74426888-7bd60900-4e56-11ea-98bf-0c222f0df708.png)

**Comment by wendy2702** [comment]
Is it the same with Admin 4.1.1 ?

**Comment by StrathCole** [comment]
> Is it the same with Admin 4.1.1 ?

Nope. Seems to be fixed in 4.1.1, no lagging anymore.

**Comment by wendy2702** [comment]
OK.

In case problem occurs again please reopen or open a new issue.
