### ISSUE TITLE
Admin page does not load, Error:  Server Error

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#517]
It happens that admin ist not loading at all, when if the situation occurs following error is visible in console log : 

![IMAGE 2020-02-15 13:21:27](https://user-images.githubusercontent.com/7318445/74587675-13be2900-4ff6-11ea-86fc-d410d3ac15e3.jpg)

Hitting the browser refresh button does mostly helps after 2-5 retry, I basically hit until the error is not visible in console and admin loads than within  seconds !

![IMAGE 2020-02-15 13:22:48](https://user-images.githubusercontent.com/7318445/74587689-436d3100-4ff6-11ea-8fc9-000a60a75485.jpg)
![IMAGE 2020-02-15 13:22:52](https://user-images.githubusercontent.com/7318445/74587692-45cf8b00-4ff6-11ea-80df-6c4a090852c6.jpg)
![IMAGE 2020-02-15 13:22:56](https://user-images.githubusercontent.com/7318445/74587693-4831e500-4ff6-11ea-9f29-19cbbbe61324.jpg)
![IMAGE 2020-02-15 13:23:01](https://user-images.githubusercontent.com/7318445/74587695-4b2cd580-4ff6-11ea-9858-f96263ec3351.jpg)
![IMAGE 2020-02-15 13:23:06](https://user-images.githubusercontent.com/7318445/74587697-4e27c600-4ff6-11ea-94d8-9b756d3e9d97.jpg)
![IMAGE 2020-02-15 13:23:11](https://user-images.githubusercontent.com/7318445/74587701-5122b680-4ff6-11ea-83e3-99c9d7284909.jpg)

admin config : 

<img width="1502" alt="Schermafbeelding 2020-02-15 om 13 24 18" src="https://user-images.githubusercontent.com/7318445/74587719-7a434700-4ff6-11ea-86db-b29ff93bb867.png">
<img width="1506" alt="Schermafbeelding 2020-02-15 om 13 24 50" src="https://user-images.githubusercontent.com/7318445/74587732-8d561700-4ff6-11ea-8af3-70b17c36da0c.png">

**Comment by Apollon77** [comment]
Which safari version? I used latest one and no problems on my mac :-(

**Comment by Apollon77** [comment]
ANd: do you use kaspersky? Antoi virus or such?

**Comment by Apollon77** [comment]
Please test with 4.0.5
