### ISSUE TITLE
Update Adapter via vis

### ISSUE THREAD

**Issue by Maja61** [ioBroker/ioBroker.admin#519]
Hi,

is it possible to get a function to update Adapters via the vis ? Just a button to "start update" or something similiar.

**Comment by ldittmar81** [comment]
Yes... It is possible and a good idea. If you open the info adapter you see a list of updatable adapters. Maybe I can create a widget for it.

**Comment by ldittmar81** [comment]
> Hi,
> 
> is it possible to get a function to update Adapters via the vis ? Just a button to "start update" or something similiar.

Something like this? https://forum.iobroker.net/topic/26533/view-adapter-status
