### ISSUE TITLE
Nach Update von admin 4.0.2-->4.0.3 keine Adapter sichtbar

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#520]
Habe grade das Update eingespielt, nach dem Update wird die Adapterliste nicht mehr geladen!

![grafik](https://user-images.githubusercontent.com/34395245/74961664-b6b7de00-540e-11ea-8752-a95b22d763e0.png)

**Comment by Apollon77** [comment]
Bitte Browser Cache und auch local Storage löschen. Dann Shift reload. Hilft das?

**Comment by DutchmanNL** [comment]
und sonst bitte Konsolen log mitgeben. vom browser, geht nicht ist ne sehr allgemeine Fehlermeldung :)

**Comment by guergen1** [comment]
Cache löschen hatte ich sonst immer direkt aus beim beenden vom Browser. Ein Update scheint das wieder eingeschaltet zu haben... läuft wieder
Danke!
