### ISSUE TITLE
Function "show log" cannot find log file

### ISSUE THREAD

**Issue by aleks-83** [ioBroker/ioBroker.admin#525]
Admin 3.7.8
Node.js 10.17.0
NPM 6.11.3
Windows 10

I tried to update admin to 3.7.9 but that crashed and i had much work to get ym iobroker back working, so i dont want to try that update again.

On the tab "Log" i click on "Download logfile" to show the complete log of the day.
The browser URL is:
`http://10.0.0.11:8081/log/file1/iobroker.2020-02-27.log`

On the HDD of the NUC the log file is:
`D:/ioBroker/NUC/log/iobroker.2020-02-27.log`

The error message in the browser window then is:
`File D:/ioBroker/NUC/node_modules/log/iobroker.2020-02-27.log not found`

So there seems to be an additional folder in the path named "node_modules".

Is this a known issue with 3.7.8?
As mentioned, i dont want to try install the 3.7.9 now.
I'd like to wait for the next release.

**Comment by wendy2702** [comment]
@aleks-83 : did you ask at iobroker Forum as well?
@AlCalzone @Stabilostick : i have no experience with iobroker at windows. Maybe you can comment?

**Comment by AlCalzone** [comment]
For me it is the following message:
```
File C:/iobroker/node_modules/log/iobroker.2020-04-29.log not found
```
which is complete nonsense since the log is in
```
C:/iobroker/log/
```

**Comment by wendy2702** [comment]
@AlCalzone i guess log download is working at your installation which is running on windows as well, am i right?

**Comment by AlCalzone** [comment]
This is whindows aswell, but the download is not working. Same problem, different (wrong) path
