### ISSUE TITLE
Aufzählungen: Javascript Neustart bei Änderungen notwendig

### ISSUE THREAD

**Issue by Hans-Zwiesel** [ioBroker/ioBroker.admin#526]
Hallo,

Wenn man bei den Aufzählungen eine Änderung vornimmt, dann muß der JS Adapter neu gestartet
werden, weil sonst die Änderungen im Script nicht berücksichtigt werden.
Manchmal auch, wenn bei den Objekten ein anderer Raum ausgewählt wurde.
Das hat mich schon Stunden an Fehlersuche gekostet.

- Raumnamen mit Umlauten werden nicht gefunden.

Meine Bitte an die Spezialisten: Bitte bei Gelegenheit diesen lästigen Fehler beseitigen.
Danke.

Node.js: v10.19.0, admin: v4.0.5

**Comment by Apollon77** [comment]
Please create this in javascript adapter :-)nThank you

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Please create this in javascript adapter :-)nThank you

Hallo Apollon77,
vielen Dank, aber ich verstehe nicht, was Du damit meinst.

**Comment by DutchmanNL** [comment]
Bug gehört nicht zum Admin sondern JavaScript Adapter.

also bitte das issue in iobroker.javascript anstatt iobroker.admin 😉
