### ISSUE TITLE
Error message after Github install does not help inexperienced users

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#527]
Currently we have this:
```
This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.
```

It should probably be like this:
```
This adapter cannot be installed directly from github.
You must install it from npm. To do so, execute the following commands on the console:
<pre>
cd /opt/iobroker
npm install iobroker.admin
</pre>
```
(where the path should be automatically determined)

**Comment by GermanBluefox** [comment]
It is issue of js.controller and not admin

**Comment by Apollon77** [comment]
really? This is a dialog in admin and no console output ... i think it comes if https://github.com/ioBroker/ioBroker.admin/blob/master/io-package.json#L233 "nogit" flag is set

**Comment by Apollon77** [comment]
How Admin5 is doing that?

**Comment by GermanBluefox** [comment]
It is changed now in Admin5. Please verify

**Comment by Feuer-sturm** [comment]
Admin 5.1.1
js-controller 3.3.11

With Admin 5.1.1 it looks like this:
![grafik](https://user-images.githubusercontent.com/25422320/119572825-a5007b80-bdb3-11eb-81ea-9cb7213ecdc6.png)
