### ISSUE TITLE
ENUM tab without content

### ISSUE THREAD

**Issue by olderbag** [ioBroker/ioBroker.admin#530]
Wenn ich im Admin-Screen auf "Aufzählungen" klicke, wird mir nur eine leere Seite mit den Überschriften angezeigt.
Außerdem bleibt der vorher gewählte Tab blau hinterlegt (hier "Instanzen"):
![Zwischenablage01](https://user-images.githubusercontent.com/39123738/76503139-95627480-6445-11ea-82b5-5a4b9e8436d6.jpg)
Versionen:
Admin: 4.0.5
js-controller: 2.2.10
Node.js: v10.19.0
NPM: 6.13.4

**Comment by Diginix** [comment]
Funktioniert bei mir im Chrome:

![image](https://user-images.githubusercontent.com/39678667/76505026-09524c00-6449-11ea-81b4-40e6ad3735a3.png)

Platform: Linux
admin: 4.0.5
js-controller: 2.2.9
nodejs: 10.19.0
npm: 6.13.7

**Comment by Apollon77** [comment]
Irgendein Fehler in der Browser Konsole?

**Comment by olderbag** [comment]
> Irgendein Fehler in der Browser Konsole?

Wenn die Frage heissen soll "Wird ein fehler angezeigt?":
Nein. Beim Klick auf "Aufzählungen erscheint das gezeigt Bild und fertig.

Wenn die Frage heissen soll "Hat der Browser vielleicht einen Fehler?":
Nein. Ist Chrome. Cache leeren bringt nichts. Auch andere Brwoser (Edge und Android-Chrome) zeigen das gleiche Verhalten.

Es muss also in der ioBroker Installation liegen. Die würde ich gerne reparieren - wenn ich nur wüsste wie, ohne eine Neuinstallation. :-(

**Comment by Diginix** [comment]
Browser Konsole heißt: 
- du öffnest diese mit F12 (in allen gängigen Browsern)
- führst den Klick auf "Aufzählungen" aus
- schaust im Bereich "Konsole" in dem zusätzlichen Fenster ob Fehler geworfen werden

**Comment by olderbag** [comment]
Aah - jetzt - ja:

`adminEnums.js:623 Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at l (adminEnums.js:623)
    at d (adminEnums.js:633)
    at c (adminEnums.js:682)
    at HTMLDivElement.<anonymous> (adminEnums.js:832)
    at Function.each (jquery-3.2.1.min.js:2)
    at e.fn.init.each (jquery-3.2.1.min.js:2)
    at u (adminEnums.js:831)
    at Enums._postInit (adminEnums.js:1666)
    at Enums.init (adminEnums.js:1689)
    at admin.js:1505`

**Comment by olderbag** [comment]
Hilft die Fehlermeldung nicht weiter?

**Comment by Apollon77** [comment]
Etwas ... kann es sein das du den Adapter openinghours (oder so ähnlich) nutzt? Der hat einen Bug und legt Objekte mit Zahlen als name an und genau hier scheint es kaputt zu sein. Also irgend ein Objekt in deinem System ist ungültig. Hast Du eine Idee was es sein könnte?

**Comment by olderbag** [comment]
Nein openighours nutze ich nicht.

Verstehe ich das richtig - wenn ein Objekt mit nur einer Zahl in der Spalte "Name" existiert, kann dieses Problem auftreten?

Ich habe jetzt mal alles aufgeklappt und durchgescrollt (gefühlt 100 Mio Objekte) - kein Objekt mit nur einer Zahl. Allerdings: im Adapter iCal gibt es Objekte, die lediglich ein "*" (Stern/Asterisk) beinhalten. Können die Probleme bereiten?

Falls ja: das ist doch dann eher als Bug im Admin Adapter zu sehen? Außer man definiert klare Restriktionen hinsichtlich Namensgebung.

Hier mal meine installierten Instanzen, weils einfacher ist Screenshot aus den Objekten. Ist da vielleicht ein Kandidat dabei der das Problem initiiert?:
![Zwischenablage01](https://user-images.githubusercontent.com/39123738/76642229-207d6080-6553-11ea-9ab3-16ef9d2a439b.jpg)

**Comment by olderbag** [comment]
Dank Snapshots von Proxmox konnte ich nun mal ein wenig Testen:

ALLE Instanzen mit Objekten gelöscht außer admin und web - ohne Erfolg.

Auf Konsolenebene web und admin gelöscht und neu installiert - ohne Erfolg.

Ich bin mit meiner Weisheit am Ende. Wenn ihr keine Idee mehr habt, bleibt nur eine Neuinstallation mit der Hoffnung, dass beim Restore der Fehler nicht wieder reinkommt.

**Comment by Apollon77** [comment]
Exportiere doch mal bitte im Admin alle Objekte und lade das json mal hier hoch

**Comment by olderbag** [comment]
Bitte sehr: 😀
[Objekte.zip](https://github.com/ioBroker/ioBroker.admin/files/4336386/Objekte.zip)

**Comment by DutchmanNL** [comment]
Ich glaube wir haben hier eine relation mit : https://github.com/ioBroker/ioBroker.admin/issues/533

in deinen Objekten finden ich den hier z.b. komisch : 

```
  "enum.rooms._object Object_": {
    "_id": "enum.rooms._object Object_",
    "type": "enum",
    "common": {
      "name": {
        "en": "Garden",
        "de": "Garten",
        "ru": "Сад",
        "fr": "Jardin",
        "nl": "Tuin"
      },
```

**Comment by olderbag** [comment]
Bitte sehr:
![Zwischenablage01](https://user-images.githubusercontent.com/39123738/77299576-f8c58f80-6cec-11ea-942b-7c25ae79eb76.jpg)

**Comment by olderbag** [comment]
Ich habe jetzt mal die - in meinen Augen dubiosen - "_object Object_" und "{roomGarden}" gelöscht und ioBroker neu gestartet.

Kein Erfolg. Gleiches Verhalten wie zuvor.

Ich verzweifle langsam, zumal ein Restore in ein neu aufgesetztes System auch nicht hilft.😥

**Comment by olderbag** [comment]
Ich habe die Ursache gefunden!

Nach dem ich folgendes Objekt gelöscht habe:
![image](https://user-images.githubusercontent.com/39123738/78226998-dee63280-74cc-11ea-80f6-d0ca60e8b3c6.png)
kann ich den Tab wieder anwählen und alle enthaltenen Aufzählungen werden angezeigt.

Das Objekt zeigt unter "Common":
`[
  "",
  "hm-rpc.2.JEQ0067477.1.STATE"
]`

...und unter "RAW":
`{
  "common": {
    "name": "controls",
    "members": [
      "",
      "hm-rpc.2.JEQ0067477.1.STATE"
    ]
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "enum.customs.controls",
  "type": "enum"
}`

Eine große Bitte habe ich aber an die/den Entwickler hier:
Bitte versuche die Ursache zu analysieren und teile sie mir hier mit. Es ist absolut unbefriedigend, einen Fehler auf diese Art (Löschen eines Objekts) zu beseitigen und nicht zu wissen, woran es wirklich lag. Und was noch schlimmer ist: ob nicht doch vielleicht noch eine Leiche im Keller liegt.

**Comment by GermanBluefox** [comment]
Fixed in 4.1.12

**Comment by Zwitsch** [comment]
Ich habe nun das gleiche Problem. Admin 4.2.1. Das Objekt enum.customs - controls gibt es bei mir allerdings nicht.
