### ISSUE TITLE
Make system_latitude & system_longitude (& other config values) available as objects?

### ISSUE THREAD

**Issue by raintonr** [ioBroker/ioBroker.admin#531]
I notice the ShutterControl module...

https://github.com/simatec/ioBroker.shuttercontrol

... requires it's own configuration options for system longitude & latitude. Ideally these should be removed and the system_latitude & system_longitude values entered on the admin setup screen should be used:

![image](https://user-images.githubusercontent.com/3794098/76877849-47e66d00-6874-11ea-9a9b-e302f79501f4.png)

Is there any way to access these? I can't tell, but think not and given the way ioBroker works imagine they are best exposed as objects under the admin adapter.

While working on this, perhaps also expose other values configured there (city, language, units, date format, etc).

**Comment by Apollon77** [comment]
The adapter can acces the system values ... so issue is for adsapter only

**Comment by raintonr** [comment]
No problem - but can you tell us how that is done? Where is this documented?

**Comment by Apollon77** [comment]
Read the object system.config and then look in common.latitude and common.longitude there

**Comment by raintonr** [comment]
Excellent, this works perfectly:

```JS
getObject('system.config', function(err, sysConfig){
    /* TODO: error handling */
    log(sysConfig.common.latitude);
    log(sysConfig.common.longitude);
});
```
