### ISSUE TITLE
[Bug] Prevent creation of ENUM with empty name

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#533]
Issue : Enum overview is not loading, javascript console indicates error "Cannot ready property typeof undefined"

RootCause : Enum with empty ID

How to reproduce : 
- create a "custom" defined enum and do not provide a name (leave empty)
- save the new enum
- the enum is created with empty id, example enum.functions.

```
{
  "_id": "enum.functions.",
  "common": {
    "name": "",
    "members": [],
    "icon": "",
    "color": false
  },
  "type": "enum",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1555503531344,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```

Expected behavior : 

A) Make it impossible to create enum with empty name by admin
B) Ensure proper error handling if object structure contains an error

**Comment by foxriver76** [comment]
We prevented this case in js-c 3, probably this is enough
