### ISSUE TITLE
Update instructions for JS-Controller still mention `sudo`

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#536]
![grafik](https://user-images.githubusercontent.com/17641229/78371065-c575e100-75c7-11ea-8965-f6d3354f4de7.png)

**Comment by Apollon77** [comment]
Yes, right. "manually installed iobroker without installer" was done using sudo earlier ...

**Comment by AlCalzone** [comment]
But that's not what we want the users to do. In the case of manual installation, the update procedure should be:
1. Backup
2. Fixer
3. Update without sudo.

**Comment by Feuer-sturm** [comment]
Admin 5.0.24

@AlCalzone This is how it looks like for a manually installed iobroker using Admin 5.0.24 if a new js-controller is available:
![grafik](https://user-images.githubusercontent.com/25422320/118313896-b1532180-b4f3-11eb-86e8-47f03ad62b05.png)

**Comment by AlCalzone** [comment]
The first sentence is wrong because it still mentions sudo. And iobroker fix is unnecessary unless someone messed up his permissions.

**Comment by Apollon77** [comment]
The content comes from here https://github.com/ioBroker/ioBroker.docs/tree/master/admin

**Comment by Apollon77** [comment]
We revamp the text in #844  ... I close here as duplicate
