### ISSUE TITLE
Respect common.globalDependency in UI

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#537]
see https://github.com/ioBroker/ioBroker.js-controller/issues/325

**Comment by Apollon77** [comment]
optional for controller 3.0 release

**Comment by Apollon77** [comment]
@GermanBluefox Is Admin5 checking  globalDependencies too?

**Comment by GermanBluefox** [comment]
I don't think so

**Comment by foxriver76** [comment]
afaik this is implemented
