### ISSUE TITLE
Adjust auto encryption to use encryptedNative rather then _enc idea

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#538]
see https://github.com/ioBroker/ioBroker.js-controller/issues/262 and https://github.com/ioBroker/ioBroker.js-controller/pull/766

ALso question is if we still want to decrypt automatically or never provide encrypted values to the admin page but just a "there is a value" flag and all fields shown as "Password" ... or split that topic out here?

**Comment by foxriver76** [comment]
I would split the second topic out for now and keep it consistent with current behavior.  But in the end, it's up to BF that he can decide when implementing.

**Comment by Apollon77** [comment]
@GermanBluefox And please introduce the new feature flag ADAPTER_AUTO_DECRYPT_NATIVE and best remove the old one

**Comment by Apollon77** [comment]
@GermanBluefox Relevant to fex before js-controller 3.0 release to latest
