### ISSUE TITLE
Adapterkonfigurationsseite nach Installation

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#541]
Ich habe im Browser immer in mehreren Tabs verschiedene Adminseiten offen. Wenn ich einen neuen Adapter installiere, dann springen alle Tabs auf die Seite der Adapterkonfiguration um.
Besser wäre wenn der Admin nur in dem geöffneten Tab auf die Seite weitergeleitet wird.

**Comment by GermanBluefox** [comment]
Comment for developer: check document.hidden

**Comment by santa81** [comment]
fixed in admin5
