### ISSUE TITLE
Auf dem Smartphone (Touch Bedienung) lassen sich die Host nicht umschalten

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.admin#543]
Ich betreibe zwei Host. Wenn ich per Smartphone mal nach dem Rechten sehen will, bekomme ich die Hosts über das Menu oben nicht angewählt. Es scheint so, dass der Klick auf den dahinterliegenden Layer aktiv wird. Denn wenn ich den zweiten Host anwähle, startet dann die darunterliegende Kachel.
Dieses Menu meine ich:
![grafik](https://user-images.githubusercontent.com/11903065/79024708-14051b80-7b84-11ea-8706-eae5254438e8.png)

**Comment by GermanBluefox** [comment]
Please retest Admin5
