### ISSUE TITLE
JS-Controller 3.0.x (Test) - Admin stürzt beim Versuch ein komprimiertes Log-File zu öffnen ab

### ISSUE THREAD

**Issue by Einstein67** [ioBroker/ioBroker.admin#546]
Admin Instanz (4.0,5) stürzt beim Versuch ein komprimiertes Log-File zu öffnen mit dem Fehler "uncaught exception: TAR_BAD_ARCHIVE: Unrecognized archive format" ab und startet neu.

`
admin.0 | 2020-04-12 07:33:27.683 | info | (18297) Use link "http://localhost:8081" to configure.
-- | -- | -- | --
admin.0 | 2020-04-12 07:33:27.683 | info | (18297) http server listening on port 8081
admin.0 | 2020-04-12 07:33:27.647 | info | (18297) received all objects
admin.0 | 2020-04-12 07:33:27.453 | info | (18297) requesting all objects
admin.0 | 2020-04-12 07:33:27.452 | info | (18297) requesting all states
admin.0 | 2020-04-12 07:33:27.442 | info | (18297) starting. Version 4.0.5 in /opt/iobroker/node_modules/iobroker.admin, node: v12.16.2, js-controller: 3.0.6
host.iob12b | 2020-04-12 07:33:26.715 | info | instance system.adapter.admin.0 started with pid 18297
host.iob12b | 2020-04-12 07:32:56.706 | info | Restart adapter system.adapter.admin.0 because enabled
host.iob12b | 2020-04-12 07:32:56.704 | info | instance system.adapter.admin.0 terminated with code 0 (NO_ERROR)
admin.0 | 2020-04-12 07:32:56.194 | info | (9409) Terminated (NO_ERROR): Without reason
admin.0 | 2020-04-12 07:32:56.194 | info | (9409) terminating
admin.0 | 2020-04-12 07:32:56.192 | info | (9409) terminating http server on port 8081
admin.0 | 2020-04-12 07:32:56.191 | error | at Unzip.emit (/opt/iobroker/node_modules/minipass/index.js:409:25)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unzip.emit (events.js:322:22)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unzip.<anonymous> (/opt/iobroker/node_modules/tar/lib/parse.js:352:29)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.[consumeChunk] (/opt/iobroker/node_modules/tar/lib/parse.js:434:21)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.[maybeEnd] (/opt/iobroker/node_modules/tar/lib/parse.js:402:17)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.[emit] (/opt/iobroker/node_modules/tar/lib/parse.js:286:12)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.emit (events.js:322:22)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.<anonymous> (/opt/iobroker/node_modules/tar/lib/parse.js:82:14)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.warn (/opt/iobroker/node_modules/tar/lib/unpack.js:188:18)
admin.0 | 2020-04-12 07:32:56.191 | error | at Unpack.warn (/opt/iobroker/node_modules/tar/lib/warn-mixin.js:19:40)
admin.0 | 2020-04-12 07:32:56.191 | error | (9409) Error: TAR_BAD_ARCHIVE: Unrecognized archive format
admin.0 | 2020-04-12 07:32:56.191 | error | (9409) uncaught exception: TAR_BAD_ARCHIVE: Unrecognized archive format

`

**Comment by Apollon77** [comment]
@GermanBluefox Relevant to fex before js-controller 3.0 release to latest

**Comment by GermanBluefox** [comment]
Please test with 4.0.6. It should not crash, but error cannot be fixed.

**Comment by Apollon77** [comment]
please retest 4-0-7

**Comment by Einstein67** [comment]
Funktioniert wieder perfekt.

(getestet mit JS-Controller 3.0.13 und Admin 4.0.7)
