### ISSUE TITLE
Feature Request: "Rebuild Button"

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.admin#547]
To make it more easy to rebuild Adapters with optional rebuild functionality (e.G. iot-Adapter) 
it would be helpfull to start the rebuild process via the admin-GUI.

May as an additional "Expert" function, similar to the "Upload"-functionality.

**Comment by DutchmanNL** [comment]
hmm ... i don't like this idea as the admin is not involved at all in adapter build.

My suggestion would be to hav this in the adapter creator, still I don't see added value as you can just "fork" every adapter of ioBroker an see the backend.
Copying an adapter is to risk full in my opinion, bad code or inefficient programming will be adapted, not thought about the really needed functionality 

( i am working in IAM-security and this are the main reasons we NEVER copy access rights)

As i am also working on a tutorial series (video introduction for adapter-dev) we agreed to have a new "template-adapter" with all mist common functions currently used in ioBroker.

This template adapter is in progress (and will stay in progress forever) but first version will be read this summer in combination with our Dev Tutorials

Cheers,

Dutch
