### ISSUE TITLE
"Activate history on all data points" button removes alias Ids

### ISSUE THREAD

**Issue by klassisch** [ioBroker/ioBroker.admin#549]
By pressing the "Activate history on all data points" button to subscribe all data points the alias Ids are removed.
Epected behavior: The alias Ids remains unchanged when the "Alias Id" field is left empty. 
relevant code snippet of history's debug log:
`2018-10-02 03:27:48.327 - debug: history.0 Removed Alias: rflink.0.channels.Prologue_6.TEMP !-> rflink.0.channels.Prologue_4.TEMP
2018-10-02 03:27:48.419 - debug: history.0 Removed Alias: rflink.0.channels.Prologue_6.HUM !-> rflink.0.channels.Prologue_4.HUM`

**Comment by wendy2702** [comment]
@klassisch : is this still open?

**Comment by klassisch** [comment]
@wendy2702 Thanks for taking care. Just checked again. In my current system the issue is still present.
js-controller:  1.5.14 
Admin: 3.6.12
History: 1.8.7 
Betriebssystem
    Windows
Architektur
    x64
CPUs
    4
Geschwindigkeit
    2295 MHz
Modell
    Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
RAM
    7.88 GB
System Betriebszeit
    00:01:14
Node.js
    v10.16.3 (Es gibt eine neuere Version: v10.20.1 - Empfohlene Version v12.16.3)
NPM
    6.9.0
Anzahl der Adapter
    283
Festplatte Größe
    464.25 GB
Festplatte frei
    398.52 GB

**Comment by wendy2702** [comment]
Hi,

Can you please update to actual  Version of JS-Controller and Admin and test again.

If you don‘t like to upgrade PLEASE close this issue as you are using old versions.

**Comment by klassisch** [comment]
@wendy2702 Unfortunately I failed to do so. I am still sticking at this version. Several I tried to update - all failed with a very strange behaviour, see  https://forum.iobroker.net/post/319374 and some following posts. First, all looks great but suddenly the parser seems to chop the input and to process it character by character - which of course makes no sense at all. Never saw this bahavior before, but it is repeatable. Just tried this two days ago. Same result. 
So, it seems that I have to wait until Stabiostick has finished the Windows installer V3. 
I also tried a clean install based on the V2 installer and a restore using the backitup adapter. This also failed and ended up in a non reacting system.  So I had to roll back to my current version, which easily could be done using Windows service manager.

**Comment by wendy2702** [comment]
OK.

Can we agree to close this issue and you reopen or create a new one if your system is running on actual versions?

For the hint i will answer at iobroker forum.

**Comment by klassisch** [comment]
Of course, I can agree. I will test again as soon as my system is updated.

**Comment by wendy2702** [comment]
Thank you Sir.

**Comment by klassisch** [comment]
Sorry, sirs, I have to reopen the issue. I apologize for not responding earlier. Today I update my system (Win 10) to 
	ioBroker.admin 3.6.12
	Node.js         v10.17.0
	NPM             6.11.3
	js-controller: 3.1.4
        History          1.9.6
and started a test. I created some test data
![aliastest-group-before-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368473-99fdf500-b52b-11ea-979b-0437b3474ffb.JPG)
Two of the tree test data got an alias
![aliastest-example1-before-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368559-b7cb5a00-b52b-11ea-8557-1641cf698969.JPG)
![aliastest-example2-before-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368564-bac64a80-b52b-11ea-8a45-0b550092a22f.JPG)
Then I prepared to start a "group subscription"
![aliastest-start-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368630-e5b09e80-b52b-11ea-8d8d-42b71ff53f9e.JPG)
and selected to subscibe
![aliastest-selecting-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368656-f3feba80-b52b-11ea-816e-fd5ceb43da25.JPG)
After the group subscription all three items have been subscribed which is correct
![aliastest-group-after-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368742-1c86b480-b52c-11ea-83ab-c21dc8c506e5.JPG)
But the alias has been deleted. My expectation was, that the alias would sustain.
![aliastest-example1-after-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368881-5952ab80-b52c-11ea-99bb-9d343f373985.JPG)

![aliastest-example2-after-group-subsscription-20200623](https://user-images.githubusercontent.com/35134055/85368893-5f488c80-b52c-11ea-9a49-ecf6f034b57e.JPG)

**Comment by GermanBluefox** [comment]
Admin5 hat neues Engine dafür. Also da bitte überprüfen.

**Comment by Apollon77** [comment]
@klassisch please recheck with Admin 5 ReactUI

**Comment by klassisch** [comment]
Thanks for the info. 
Sorry, I am still on Admin 4.2.1; jscontroller 3.2.16; Node.js v10.17.0; NPM 6.11.3
My light control depends on ioBroker and update on a Win 10 system may be a bit risky. So, I am a cautious late adopter and mostly in "stable".
