### ISSUE TITLE
"show tree view" in tab objects let admin get stuck

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#55]
Beim Anklicken des Buttons "show tree view" im Reiter "objects" bleibt der admin hängen

**Comment by GermanBluefox** [comment]
Das funktioniert. Nur dauert SEHR lange (bei mir ca 2-3 Minuten)

**Comment by Homoran** [comment]
könnte das <b>irgendwann</b> schneller werden, oder ist das nicht machbar?
Sonst kann der issue geschlossen werden

**Comment by GermanBluefox** [comment]
Leider es ist nicht machbar, aber
Man kann irgendeinen Meldung zeigen, dass es bis zu 2 Minuten dauern kann.

**Comment by Homoran** [comment]
>Man kann irgendeinen Meldung zeigen, dass es bis zu 2 Minuten dauern kann.

Das halte ich für sinnvoll.
