### ISSUE TITLE
Hintergrund schwarz

### ISSUE THREAD

**Issue by michihorni** [ioBroker/ioBroker.admin#550]
Hallo, ich habe die Version Admin 4.0.9 installiert. Alle Hintergründe im Editor sind schwarz. Siehe Anhang. Nur der "Fm light background"  wird auch der Hintergrund grau. Alle anderen Hintergründ bleiben Schwarz. Im Runtime Modus ist wieder alles OK.
![Unbenannt](https://user-images.githubusercontent.com/27429377/79986219-0026b700-84ac-11ea-9dff-d24be86d610e.JPG)

**Comment by WLAN-Kabel** [comment]
In deinem Problem geht es doch um die VIS und nicht um den Admin, oder doch?

**Comment by michihorni** [comment]
Hallöchen

der Hintergrund ist erst nach den Update das Admin schwarz geworden. Vis läuft seit einiger Zeit auf V 1.2.6.

Welcher Adapter letztlich jetzt entscheidend ist weiß ich natürlich nicht.
 

Mit freundlichen Grüßen
Michael Horn

 
 

Gesendet: Montag, 27. April 2020 um 16:17 Uhr
Von: "WLAN-Kabel" <notifications@github.com>
An: "ioBroker/ioBroker.admin" <ioBroker.admin@noreply.github.com>
Cc: "michihorni" <michaelhorn@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ioBroker/ioBroker.admin] Hintergrund schwarz (#550)


 

In deinem Problem geht es doch um die VIS und nicht um den Admin, oder doch?

**Comment by wendy2702** [comment]
Mal ein

`iobroker upload all`

Probiert ?

**Comment by michihorni** [comment]
Guten Morgen
ja hab ich gemacht, aber ohne Erfolg

Mit freundlichen Grüßen
Michael Horn

**Comment by novregen** [comment]
Hallo,
ich habe auch das gleiche Problem. Hintergrund wird als schwarz im Editor angezeigt, in der Runtime alles gut. Einige Hintergründe wie grau werden richtig angezeigt. Habe vis und web schon deinstalliert und neu installiert. Gibt es hierfür irgendeine Lösung ?

**Comment by Karlnappii** [comment]
This issue is still not solved!
