### ISSUE TITLE
Node.js version not recognized in proxmox vm

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#551]
Hi all, I need to switch from lxc container to vm (proxmox) and I have some issues with the vm installation. Node -v shows v12.16.2. Nevertheless ioBroker seems to reject that version (which it actually recommends. 

Info shows: "v11.15.0 (Diese Version von Node.js ist veraltet und wird nicht mehr unterstützt. Bitte installieren Sie Node.js v12.16.2"."

Additionally I get a popup at admin launch: "ioBroker unterstützt die LTS Versionen 6, 8, 10 oder neuer von Node.js. Bitte aktualisieren Sie die verwendete Node.js Version ("v11.15.0") auf dem Rechner "iobroker" auf eine unterstützte Version. Wir empfehlen die Verwendung von Node.js 6."

Please help me to get this tidied up.

the other most obvious problem is that I don't see the config page of the amazon dash adapter .. instead I get "File index.m.html not found" .. I did already install the adapter over via terminal command .. to no avail. A hint for getting this up and running again would be nice

**Comment by Apollon77** [comment]
Please tell Output from console for

node -v
nodejs -v

**Comment by Apollon77** [comment]
For second: try „iobroker upload amazon-dash“

**Comment by ldittmar81** [comment]
This line must be changed for the Admin adapter:

https://github.com/ioBroker/ioBroker.admin/blob/b4b08ce1e85e6526299445473ac487d4fa717189/src/i18n/de/translations.json#L558

**Comment by daniel-lo** [comment]
Oh .. ok ..
node -v v12.16.2
nodejs -v 11.15.0

I guess my bad .. I thought node is the version I need.
Now I need to find out how to update nodejs.

Amazon dash .. the command helped but the adapter stays red .. maybe this is related to nodejs. Libpcap driver is installed.

Thanx.

**Comment by daniel-lo** [comment]
nodejs is fixed .. now both show 12.16.2 :-)

Amazon Dash still red though.

**Comment by daniel-lo** [comment]
some log output (sorry .. for using this thread for dash now):

`amazon-dash.0	2020-04-26 19:20:14.555	info	(5007) Terminated (NO_ERROR): Without reason
amazon-dash.0	2020-04-26 19:20:14.554	info	(5007) terminating
amazon-dash.0	2020-04-26 19:20:14.521	info	(5007) cleaned everything up...
amazon-dash.0	2020-04-26 19:20:14.521	error	(5007) Error: socket: Operation not permitted at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39) at Object.exports.createSession (/opt/iobroke
amazon-dash.0	2020-04-26 19:20:14.512	error	(5007) uncaught exception: socket: Operation not permitted
amazon-dash.0	2020-04-26 19:20:14.510	info	(5007) starting pcap session on default interface
amazon-dash.0	2020-04-26 19:20:14.492	info	(5007) starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.amazon-dash, node: v12.16.2, js-controller: 3.0.18
--
amazon-dash.0	2020-04-26 17:19:11.279	info	(3755) Terminated (NO_ERROR): Without reason
amazon-dash.0	2020-04-26 17:19:11.279	info	(3755) terminating
amazon-dash.0	2020-04-26 17:19:11.237	info	(3755) cleaned everything up...
amazon-dash.0	2020-04-26 17:19:11.236	error	at processTicksAndRejections (internal/process/task_queues.js:97:5)
amazon-dash.0	2020-04-26 17:19:11.236	error	at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8067:34
amazon-dash.0	2020-04-26 17:19:11.236	error	at Adapter.emit (events.js:310:20)
amazon-dash.0	2020-04-26 17:19:11.236	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:53:9)
amazon-dash.0	2020-04-26 17:19:11.236	error	at main (/opt/iobroker/node_modules/iobroker.amazon-dash/main.js:90:29)
amazon-dash.0	2020-04-26 17:19:11.236	error	at Object.exports.createSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:131:12)
amazon-dash.0	2020-04-26 17:19:11.236	error	at new PcapSession (/opt/iobroker/node_modules/iobroker.amazon-dash/node_modules/pcap/pcap.js:60:39)
amazon-dash.0	2020-04-26 17:19:11.236	error	(3755) Error: socket: Operation not permitted
amazon-dash.0	2020-04-26 17:19:11.227	error	(3755) uncaught exception: socket: Operation not permitted`

**Comment by Apollon77** [comment]
run installation fixer (iobroker fix) ... comes from node update ad missing permissions

**Comment by daniel-lo** [comment]
installation fixer didn't help .. so amazon-dash is still red.

another thing I wonder about is .. while your command worked for the amazon-dash adapter .. why does your command from above not work for other adapters:
iobroker upload tr-064-community
iobroker upload network
These two also have the missing config-page problem.

**Comment by Apollon77** [comment]
Amazondash other topic please create issue there or in forum. Thank you.
