### ISSUE TITLE
Add FileEditor

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#555]
* basic Featureset like the vis file explorer (also the API calls can be checked from there)
  * Allow to edit all "user meta" folder (object type "meta" with common.type "meta.user"
  * show all forders in it
  * allow creating directories
  * allow file upload and download
  * allow file and directory deleting
  * view images (pot. also with background change ala vis editor)
* maybe also allow to view other "type meta" folders with without option to change it (only meta.user is allowed to be changed!)

**Comment by GermanBluefox** [comment]
Allow only folders and files with user.meta to delete or upload.

**Comment by GermanBluefox** [comment]
Done
