### ISSUE TITLE
Split out some "Instances" settings from overview into a settings page

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#556]
We could move settings like
* restart schedule
* compact settings
* ram limit
to an extra dialog to have less columns per instance, but maybe find ways where e.g. icons could be used to indicate e.g. "there is a restart schedule set" or "this runs in compact mode" to still have some visibility

**Comment by WLAN-Kabel** [comment]
The instances are currently created as an expansion panel in the React GUI. Should we integrate the settings in the unfolded panel or in a separate page / dialog?

**Comment by GermanBluefox** [comment]
No. Now is OK
