### ISSUE TITLE
Better display unmet dependencies

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#557]
Currently we already check the following deps from adapters:
* nodejs verison
* dependencies
* globalDependencies needas to be added

But it is displayed by slighgtly greying out the update button and only mouseover info shows the reason ... We should display that more promiment. e.g. greying out (yes) but also allow to click the button ad show the "problem" in a popup or such

**Comment by GermanBluefox** [comment]
Done
