### ISSUE TITLE
Add Basic Alias Settings editor to Object editor

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#558]
Comparable to the devices we should a basic editor for alias settings to the normal object creation/edit dialog.

**Comment by Berchemer** [comment]
Don't know how you want to implement this but...

In this context, I imagine a button for creating an ALIAS next to each data point in the object list, which you click on (e.g. as is already the case with the settings of the data point) and a mask appears in which name and role, etc. of the data point are preselected and thus mirror the data point in the ALIAS folder. Then all you need to do is click Create and an ALIAS is created and saved.
I think this would be very comfortable.

**Comment by GermanBluefox** [comment]
Done
