### ISSUE TITLE
Fehler "Einige Daten wurden nicht gespeichert. Verwerfen?"

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#559]
As postet here: https://forum.iobroker.net/topic/32243/fehler-einige-daten-wurden-nicht-gespeichert-verwerfen

Seit Update auf den js-controller 2.0 (aktuell nutze ich 2.2.9) habe ich beim Speichern von manchen Adapter-Einstellungen immer folgende Meldung, obwohl die Daten eigentlich korrekt gespeichert wurden. Die Meldung kommt bei "Speichern" und bei "Speichern und schließen".

![image](https://user-images.githubusercontent.com/49171332/80523822-f4952d80-898e-11ea-93b6-d006051b1fa5.png)

Ich konnte das ganze bislang zurückverfolgen auf die admin.js, Zeile 1396:

```
    main.navigateCheckDialog = function (callback) {
        if (main.currentDialog && main.dialogs[main.currentDialog] && typeof main.dialogs[main.currentDialog].allStored === 'function') {
            if (main.dialogs[main.currentDialog].allStored() === false) {
                return main.confirmMessage(_('Some data are not stored. Discard?'), _('Please confirm'), null, function (result) {
                    callback(!result);
                });
            }
        } else {
            if (configNotSaved) {
                return main.confirmMessage(_('Some data are not stored. Discard?'), _('Please confirm'), null, function (result) {
                    callback(!result);
                });
            }
        }
        callback(false);
    };
```

Ab hier komme ich aber leider nicht weiter. Betroffene Adapter sind u..a javascript, iQontrol, info etc., es scheint also eher ein admin-Problem zu sein... Bei hm-rega z.B. kommt die Meldung aber nicht...

Danke für die Hilfe!!

**Comment by WLAN-Kabel** [comment]
Couldn't recreate it in admin with react gui.

**Comment by WLAN-Kabel** [comment]
Please reopen, should it still occur in a future version.

**Comment by sbormann** [comment]
Hi, Problem still exists and is also reported to me by other users. Maybe it only occurrs when saving big configurations?

**Comment by Apollon77** [comment]
@sbormann Yes but please read what @WLAN-Kabel wrote ... We checked that bug for the next coming big admin update and there it is not reproducable. So please wait for Admin 5 and then we can check it again there :-)

**Comment by metaxa1** [comment]
Übersetze ich das richtig? "Bitte warten auf Admin 5, dann wird neu geprüft". Wenn ja, bis dahin kann ich keine funktionstüchtigen Änderungen in iQontrol machen. Nicht nur das Änderungen scheinbar nicht vollständig gespeichert werden, die geänderte Funktion (?) im iQontrol führt dazu, dass die betroffene Ansicht sich nicht mehr aufrufen läßt.

**Comment by Apollon77** [comment]
Ne Übersetzt heisst es: In Admin 5 konnten wir das Problem nicht reproduzieren.

**Comment by metaxa1** [comment]
@Apollon77 Danke Ingo :-) Sebastian versucht mir schon zu helfen, da es sich scheinbar "nur" um einen "optischen" Fehler handelt.
