### ISSUE TITLE
V 0.5.10, Reiter Objekte: "common.type" verschwindet / Name wird verkürzt

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.admin#56]
Reiter "Objekte":
1. Bei Wechsel zwischen den Reitern "allgemein" und "raw" verschwindet common.type, so wie es schon bei Version 0.5.9 mit dem Selektor "type" war. Ohne Selektor (String-Eingabe) passiert dies nicht.

2. Beim Erstellen eines neuen Objektes unter "javascript.0" und Eingabe des Namen "Test.irgendwas" ist anschließend der Name auf "irgendwas" verkürzt (auch in Version 0.5.9).

**Comment by GermanBluefox** [comment]
Fixed: https://github.com/ioBroker/ioBroker.admin/commit/7e583c8222426cfab4e3495501025119a35786a9
