### ISSUE TITLE
Tab für neu installierte Adapter automatisch sichtbar

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#562]
Es gibt einige Adapter die einem Tab integriert haben. Diese sind nach der Installation nicht aktiv und müssen extra im Menü freigeschaltet werden. Das ist nicht intuitiv! Wenn ich explizit was installiert habe, möchte ich den Tab auch haben. Wenn nicht, kann ich es dann selber ausschalten.

<img width="151" alt="Screenshot_4" src="https://user-images.githubusercontent.com/9552828/80603469-bfd9b280-8a30-11ea-9978-5c8506ed6c37.png">

Außerdem wäre eine eigene Sortierung der Tabs richtig cool.

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15

**Comment by Feuer-sturm** [comment]
Admin 5.0.15

Extramenü z.b. vom Backitup Adapter wird entfernt wenn der Adapter gelöscht ist und Extramenü wird hinzugefügt, wenn Backitup Adapter installiert wird.
Manuelle Sortierung ist per Drag&Drop ebenfalls möglich.

Issue kann geschlossen werden @GermanBluefox
