### ISSUE TITLE
Info tab crashes admin

### ISSUE THREAD

**Issue by WLAN-Kabel** [ioBroker/ioBroker.admin#566]
@GermanBluefox when loading the Info tab, the admin crashes.
![grafik](https://user-images.githubusercontent.com/53860633/80978749-c13b1e80-8e26-11ea-8cba-ebc835fa3e58.png)

**Comment by wendy2702** [comment]
Are you talking about this Tab:

![4C9D2689-1C20-476F-9D45-B99F4A9AFC15](https://user-images.githubusercontent.com/33424168/81103701-b90bdd80-8f11-11ea-82be-f7a9acf78458.jpeg)

For me it‘s working with Admin 4.1.1, JS 3.0.20 and Info 1.7.0

Which Versions of Admin, JS-Controller and Info you are using?

**Comment by WLAN-Kabel** [comment]
This was a bug in the development of the new React Admin, but it has been fixed.
