### ISSUE TITLE
Flot Ansicht häufig nicht sinnvoll - Add "open in Flot" Button/Link

### ISSUE THREAD

**Issue by Omega236** [ioBroker/ioBroker.admin#567]
ich habe das Problem dass ich bei fast jeden Datenpunkt den ich mir im "custom Settings"->Charts anschaue, flot nochmal öffnen muss und einige Parameter anpassen muss damit ich sinnvoll daten auslesen kann.
was mich am meisten stört:
Zusammenfassung auf 5 min und hier nur min-max werte -> komplett ungeeignet schnellere wechsel zu analysieren
keine Nachkommastellen -> gerade bei z.B. kWh Werte sehr ärgerlich
Datenpunkt visualisierung line statt steps: die Line Ansicht ist nicht geeignet um zu sehen zu welchem Zeitpunkt der Datenpunkt welchen wert hatte, sonder ist nur z.B. bei langsam aber kontinuierlich ändernden Datenpunkte wie Außentemperatur sinnvoll
TimeFormat hat kein Datum: Wenn man rauszoom hat man keine Ahnung an welchem tag man gerade ist

**Comment by wendy2702** [comment]
Ähm,

Warum ein Issue beim Admin wenn du Probleme mit FLOT hast?

**Comment by Omega236** [comment]
weil Flot alle möglichen Möglichkeit zum anzeigen gibt. Aber die wie die Ansicht auf der Admin-Seite ist, ist im Admin-Adapter hard-gecoded. habe auch einen Change-Request mit der Angepassten Code-Zeile gemacht.

**Comment by GermanBluefox** [comment]
Hm... Um die Werte anzuschauen, muss man trotzdem immer noch Flot benutzen.
minmax ist aggregate und sonst, kann man SEHR viele Daten laden.
Es wäre besser Knopf zu implementieren: "Open in flot"
Weil die geänderte Einstellungen passen gerade für deinen Fall...

**Comment by Apollon77** [comment]
Ich mag die "Open in Flot" Idee. Der Graph in Admin ist nur ne simple darstellung ... das wöre für mich die Idee.
@GermanBluefox Ich habs mal ins Admin 5 projekt geschoben

**Comment by GermanBluefox** [comment]
Please check the Admin5
