### ISSUE TITLE
V 0.5.10, Reiter Objekte: Multistate-Attribute

### ISSUE THREAD

**Issue by paul53** [ioBroker/ioBroker.admin#57]
Bei Erzeugung eines neuen Objektes vom Typ "Multistate" (Werteliste) wrden die Attribute "common.min", "common.max" und "common.states" nicht automatisch erzeugt.

**Comment by paul53** [comment]
Das funktioniert, wenn Du "index.html" in Zeile 407 änderst: value="enum" --> value = "multi"

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.admin/commit/a7898b0942282c52f383aeb36328c2cc52e80261
Fixed.
