### ISSUE TITLE
IOT Devices removed

### ISSUE THREAD

**Issue by n3roGit** [ioBroker/ioBroker.admin#570]
https://github.com/ioBroker/ioBroker.iot/issues/104

Hi guys,

I'm hoping someone can help here. For weeks I have had the problem that the devices of the IOT adapter disappear at irregular intervals. Sometimes just a few or even all of them.

The settings for iot disappear from the objects.

What I could reproduce now is that after activating influxdb on the objects the iot devices disappeared. I could not find any clues in the logs.
But before I used influxdb this already happened. I guess the iobroker "swallowed" some objects and destroyed the iot entries.

i really hope that someone can take care of this problem because i am really going crazy. i am also willing to give debugging access to my iobroker.

the system runs under docker on a ds918 and is installed in a current prod version.

node.js v10.19.0
NPM 6.13.4
js-controller 2.2.9

**Comment by Apollon77** [comment]
Then we need to check in Admin when doing "mass custom changes". maybe we forgot a place.

So: Do not do mass chsutom changes for now :-) With single changes the iot settings should stay, correct?

**Comment by n3roGit** [comment]
Yes it works for single DPs :)


BIG THX TO YOU!

**Comment by n3roGit** [comment]
Is there any news on this yet? I found out that the IOT devices themselves disappear when I adjust a small object area via mass processing that has nothing to do with the IOT devices.

If there are any problems to reproduce the problem, I am happy to provide my system.

**Comment by Apollon77** [comment]
I added it to be fixed in the current Admin Ui Rebuild. will still need to some time

**Comment by n3roGit** [comment]
Any news? Do You need some debug logs?

**Comment by n3roGit** [comment]
Any news?

**Comment by Apollon77** [comment]
As told above a fix will be part of Admin 5 and this is a bit away still because in active development. A workaround exists ...

**Comment by n3roGit** [comment]
Unfortunately the workaround works only partially. I could detect the deletion of IOT devices even when activating the history individually.

However, this does not happen so often.

**Comment by Apollon77** [comment]
Please recheck in Admin5 React UI!

**Comment by n3roGit** [comment]
Hello again,

today it was after a long time again so far. I have lost a whole part of my devices that come from the sonoff objects.


I still think that this has to do with the mass processing of objects. I had added several devices to the influxdb a good two weeks ago. yesterday then came after a long time a restart of iobroker. then the devices were gone.

**Comment by Apollon77** [comment]
WHich Admin version was used? Admin 5.1.11 with use of React UI or not?

**Comment by GermanBluefox** [comment]
> IOT

Some adapters recreate the objects by start. At least I know about hm-rpc. 
There is a workaround for that in hm-rpc.
![image](https://user-images.githubusercontent.com/4582016/125919866-ea22a9cc-0d75-46d3-a3f8-0f2ebafb5e1d.png)

**Comment by n3roGit** [comment]
> WHich Admin version was used? Admin 5.1.11 with use of React UI or not?

Whats todo to install it?

**Comment by n3roGit** [comment]
Tryed to install it via github and get this:

![image](https://user-images.githubusercontent.com/8565847/125927374-c0690f2a-7a32-47df-a895-dd4068a3aff5.png)

**Comment by Apollon77** [comment]
Admin 5.1.11 is in the latest repository, you can switch to it, install and switch back for the other udpates

**Comment by n3roGit** [comment]
what do i have to do to change this without admin adapter?

**Comment by n3roGit** [comment]
i fixed the adapter with 
iobroker upgrade admin http://download.iobroker.net/sources-dist.json

now i can chage repo via gui and update i

**Comment by n3roGit** [comment]
With the Admin version v5.1.25 I still have the problem that IOT devices disappear from time to time.

Can we maybe do a remote session about it?

**Comment by Apollon77** [comment]
When it is an issue, then with iot... but most likely with the relevant adapters. Which adapters are affected?

**Comment by n3roGit** [comment]
It's hard to say.
My devices are mostly controlled via the deconz and sonoff adapter.

What I notice is that the advanced attributes that the IOT adapter uses for the smart devices just disappear.
as a result, 20 devices are missing from my IOT device list.

I would still find it great as a workaround if I could export my IOT devices in the adapter. then I can simply restore them when I notice it.

**Comment by Apollon77** [comment]
When they "disapear" this normally means that the adapter deletes and recreates objects ... SOthis would be needed tocheck in the adapters

**Comment by Feuer-sturm** [comment]
@n3roGit Is this issue still open? Did you check the last comment of @Apollon77 ?

**Comment by n3roGit** [comment]
Is this commit new? Then I have to try it tomorrow

**Comment by Feuer-sturm** [comment]
@n3roGit I was talking about the last statement of Apollon https://github.com/ioBroker/ioBroker.admin/issues/570#issuecomment-964941027 and not about a commit ;-) Or which commit do you mean?
