### ISSUE TITLE
Make loglevel dropdown in instances tab update the loglevel on the fly

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#571]
JS-Controller supports changing the loglevel of adapters on the fly using the `system.adapter.<adaptername>.<instance>.logLevel` state. However the dropdown in the instances tab changes the adapter object, causing it to restart.

We should make this more intuitive:
1. Make the UI update the state only
2. Before the adapter is started (or after it is stopped?), synchronize the instance object with the state.

**Comment by Apollon77** [comment]
Important: Part #2 is more a js-controller  topic and this topic here needs to be done together with this js-controller feature

**Comment by WLAN-Kabel** [comment]
TODO: Option hinzufügen zum Auswählen der Dauer des Loglevel  (temporär oder persistent)
