### ISSUE TITLE
Object side / individual value table - missing lines at bottom / scrolling

### ISSUE THREAD

**Issue by Seqway** [ioBroker/ioBroker.admin#573]
Hello,
if i go to any value under objects and click on the "key / tool" at the end the individual setups for this value opens.
If i go to table of this value then the newest values are at the bottom but somehow partly hidden and scrolling not possible!
Example attached.
<img width="1472" alt="screenshot" src="https://user-images.githubusercontent.com/40624961/81828716-64341c80-953a-11ea-9281-6f24a176702a.png">

**Comment by GermanBluefox** [comment]
NO more actual in admin5
