### ISSUE TITLE
Also  add icons for dataSource and maybe also if "plugins->sentry" is there

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#575]
like #574 but for the other two ... 
* dataSource (see https://github.com/ioBroker/ioBroker.repositories/blob/master/README.md#connection-types)
* maybe also check system.adapter.name.instance in common.disableDataReporting (this disables data reporting like sentry)

**Comment by GermanBluefox** [comment]
Implemented in Admin5
