### ISSUE TITLE
Create folder on admin objects

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#577]
At the moment its not possible to create folders directly.
<img width="693" alt="Screenshot_10" src="https://user-images.githubusercontent.com/9552828/82417722-3c820e80-9a7c-11ea-8df7-4f8461007f31.png">

You must to use the device adapter to do this.

<img width="493" alt="Screenshot_11" src="https://user-images.githubusercontent.com/9552828/82417780-54599280-9a7c-11ea-83b4-74ea922f2ae3.png">

<img width="517" alt="Screenshot_12" src="https://user-images.githubusercontent.com/9552828/82417787-57548300-9a7c-11ea-81b8-fa844b9c92b3.png">

**Comment by ldittmar81** [comment]
Create folder makes only sense for "0_userdata.0" and "alias.0"

**Comment by Apollon77** [comment]
> Create folder makes only sense for "0_userdata.0" and "alias.0"
agreed ...

**Comment by GermanBluefox** [comment]
Implemented in Admin5
