### ISSUE TITLE
Datensicherung / einlesen klappt nicht.

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.admin#578]
Das Einlesen der Datensicherung (Pfeil) klappt nicht.
Genauer:
https://forum.iobroker.net/topic/33689/bug-sayit-speichert-config-nicht-korrekt

**Comment by WLAN-Kabel** [comment]
I found the error. The sayit adapter has a function with the same name that is normally responsible for uploading the config.

https://github.com/ioBroker/ioBroker.admin/blob/master/src/js/adapter-settings.js#L467

https://github.com/ioBroker/ioBroker.sayit/blob/master/admin/index_m.html#L310

**Comment by GermanBluefox** [comment]
This must be fixed in sayit
