### ISSUE TITLE
German Translation in Admin settings - "Aktiver Verwahrungsort"

### ISSUE THREAD

**Issue by tsvsj** [ioBroker/ioBroker.admin#579]
I would like to suggest to change the translation. I was looking for the repository setting, to use stable or latest repository. I didn't get the idea, that "Verwahrungsort" mentions the repository... 

It would be great to call it a repository, just what it is. This should be understandable to each user of ioBroker.

Thanks!

**Comment by GermanBluefox** [comment]
Rename to repository

**Comment by GermanBluefox** [comment]
Changed in 5.0.15

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
New wording is available.
![grafik](https://user-images.githubusercontent.com/25422320/117199152-20d95a80-adea-11eb-8b8b-de27ad6b2086.png)
