### ISSUE TITLE
Readonly states should not be writeable even in expert mode

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#583]
![grafik](https://user-images.githubusercontent.com/17641229/83335621-5c040d00-a2ae-11ea-980a-d000dd86ea18.png)

**Comment by Apollon77** [comment]
@WLAN-Kabel I think the interesting question to decide is "what is allowed in expert mode which normally isnt and why " :-)

**Comment by DutchmanNL** [comment]
as the write setting is just an indicator, the expert mode by design should allow modification.
Please keep in mind from a dev perspective, you should not use expert mode at all as user but for dev its very useful to switch to expert and have this kind of features.

@WLAN-Kabel if you have other reason to use the expert mode, not providing the same functionality as for a dev we could think about "Normal | Expert | Dev"

but for now I don't see an added value to implement a "dev" mode on top of expert

**Comment by AlCalzone** [comment]
@DutchmanNL however many users seem to have it enabled although they are clearly not experts. Question is: Does the override need to be enabled forever or can it be reset when closing admin? Or can we maybe make it clear that the state we are writing to should not be written to normally?

**Comment by WLAN-Kabel** [comment]
If the state is read only, written values from the user should not be taken into account by the corresponding adapter.

So I think writing in expert mode is not really necessary.

**Comment by ldittmar81** [comment]
What about to set expert mode ONLY for the current session? We should all work with the normal mode... only if you realy need something you shoud change.

**Comment by WLAN-Kabel** [comment]
@AlCalzone  currently it is part of the expert mode. We could try to reset the expert mode on exit or on startup, but this will probably confuse or even annoy some people if they have to activate it all the time.

**Comment by WLAN-Kabel** [comment]
@ldittmar81  if this is to be implemented in this way, there is still the question of whether it is necessary to write read-only states in expert mode.

**Comment by ldittmar81** [comment]
@WLAN-Kabel if an expert mode is something like "sudo" and it's not a normal mode, why not? But then we must to take a look on all expert mode features and discuss if it es a realy expert mode feature or not.

**Comment by AlCalzone** [comment]
@WLAN-Kabel I have never had the necessity to write a readonly state, so I'm with you on this. If we do agree that it might be necessary, I advocate strongly for not making this setting permanent. At least there should be a confirmation like "You are about to edit a readonly state. Continue?"

**Comment by ldittmar81** [comment]
It's the perfect oportunity to reset all " I have no idea, but I use expert mode" user to a normal mode. And then we can make the "expert mode" really powerfull. 😈

**Comment by ldittmar81** [comment]
@WLAN-Kabel We can discuss expert mode at the next meeting. Would you be there and prepare something?

**Comment by WLAN-Kabel** [comment]
@ldittmar81 I currently assume that I will be at the next appointment. I can also prepare something for it.

**Comment by GermanBluefox** [comment]
Will be implemented as: 
- User can activate expert mode, but it will be saved on session level
- If the user want to activate expertMode forever he must activate it in admin settings

**Comment by GermanBluefox** [comment]
Implemented in Admin5
