### ISSUE TITLE
Einstellung für einem Datenpunkt wenn Adapter gelöscht wurde

### ISSUE THREAD

**Issue by ldittmar81** [ioBroker/ioBroker.admin#585]
Wenn man für einem DP erweiterte Einstellungen macht...

![04-06-_2020_15-44-52](https://user-images.githubusercontent.com/9552828/83764689-8709aa80-a67a-11ea-8a44-58f00bf18d19.png)

... und dann zur Einstellung gebrauchten Adapter löscht, dann bleiben die Einstellungen da bzw. bleibt der Schraubenschlüssel blau und in der Filterung werden diese Adapter angezeigt, wenn man nach "mit Einstellungen" sortiert.

Man sollte da wenigstens die Möglichkeit bekommen, die Einstellungen wieder zu löschen... Selbst das Löschen im RAW-Modus ist nicht möglich. Bsp. oben -> da wurde eine Einstellung mit dem linkeddevices Adapter erstellt.

![04-06-_2020_15-52-02](https://user-images.githubusercontent.com/9552828/83765367-5d04b800-a67b-11ea-9ddc-78ec0fefdfc2.png)

Nach dem Löschen taucht Linkeddevices nicht mehr in der Übersicht auf... (klar.. logisch)

![04-06-_2020_15-53-12](https://user-images.githubusercontent.com/9552828/83765496-87ef0c00-a67b-11ea-8062-35c53cad2bbc.png)

Im RAW ist es immer noch da und ich kann es nicht löschen.

Vielleicht sollte Man in der eine Übersicht anzeigen, dass ein "Leiche" vorhanden ist und dort die Möglichkeit geben diese zu löschen... (Achtung!! Paint-Kunst)

![04-06-_2020_15-52-022](https://user-images.githubusercontent.com/9552828/83765953-15326080-a67c-11ea-8092-b408dece2833.png)

**Comment by Apollon77** [comment]
Und es verschwindet nicht wenn du die Custom seite neue speicherst?

**Comment by ldittmar81** [comment]
Nein... Es bleibt wie es ist. Ich kann es einfach nicht löschen...
