### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by Marty56** [ioBroker/ioBroker.admin#586]
Version 4.11 erzeugt folgenden Bug im syslog. Mit 4.0.10 kein Problem 

`
Jun  9 08:43:57 nuc bash[504]: (node:627) TimeoutOverflowWarning: 7781552818 does not fit into a 32-bit signed integer.
Jun  9 08:43:57 nuc bash[504]: Timeout duration was set to 1
`

**Comment by Apollon77** [comment]
Does it also happen in current admin version?

**Comment by Marty56** [comment]
I have move to a promox server and restored my iobroker.
After this I did not see the error.
