### ISSUE TITLE
Slave log on slave

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.admin#587]
it is not possible to download the log from slave systems.
![image](https://user-images.githubusercontent.com/37106885/84263777-c3308580-ab28-11ea-94fa-346d508694a6.png)
![image](https://user-images.githubusercontent.com/37106885/84263785-c75ca300-ab28-11ea-87c9-4f8586876663.png)

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v12.18.0
NPM: 6.14.4
Model: unknown
RAM: 987.98 MB
Node.js: v12.18.0
NPM: 6.14.5
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.6 MB
Node.js: v12.18.0
NPM: 6.14.5
JS-Controller (1): 3.1.4
Admin: 4.1.1
Admin: 4.1.1

> *created by ioBroker.info*

**Comment by Anzic23** [comment]
changes are planned?

**Comment by GermanBluefox** [comment]
Please test it in Admin5

**Comment by Apollon77** [comment]
You also tested with Admin5 and the enew React UI? Please check that

**Comment by Anzic23** [comment]
> You also tested with Admin5 and the enew React UI? Please check that

yes, of corse

**Comment by Feuer-sturm** [comment]
Master Admin 5.1.1, js-controller 3.3.11
Slave Admin 5.1.1, js-controller 3.3.11


With my configuration and active React-UI I can confirm that it is not possibe to download slave log file.

**Comment by GermanBluefox** [comment]
Should be fixed with admin 5.1.3 and js-controller 3.3.12

**Comment by Feuer-sturm** [comment]
Master: Admin 5.1.8 and js-controller 3.3.12
Slave:  Admin 5.1.8 and js-controller 3.3.12

Issue is fixed on my system. I can download the log of the iobroker slave
