### ISSUE TITLE
The problem with displaying cyrillic characters in the list of drivers. Question marks are displayed instead of letters.

### ISSUE THREAD

**Issue by OlegJktu** [ioBroker/ioBroker.admin#588]
![IoBroker глюк знаки вопроса](https://user-images.githubusercontent.com/34140076/84565882-30385b00-ad75-11ea-8062-7a0fa1fed557.PNG)
The problem with displaying cyrillic characters in the list of drivers. Question marks are displayed instead of letters. The problem is reproduced in browsers on Linux (KDE NEON) and Win10, chrome, firefox. The problem is reproduced with a clean new installation on raspberry pi and with a clean new installation in docker (buanet).
In other sections of the admin panel, I did not notice any problems.

Проблема с отображением кириличеких символов в списке драйверов. Отображаются знаки вопроса вместо букв. Проблема воспроизодится в браузерах на Linux (KDE NEON) и Win10, chrome, firefox. Проблема воспроизводится при чистой новой установки на raspberry pi и при чистой новой установки в докер (buanet).
В других разделах админки проблем не заметил.
Проблема воспроизводится при чистой новой установки на raspberry pi и при чистой новой установки в докер (buanet).

**Comment by WLAN-Kabel** [comment]
I cannot reproduce the behaviour (Chrome, Firefox)

Which browser do you use?

![grafik](https://user-images.githubusercontent.com/53860633/84763476-8ce18300-afcc-11ea-92f1-a513e321c470.png)

**Comment by OlegJktu** [comment]
> I cannot reproduce the behaviour (Chrome, Firefox)
> 
> Which browser do you use?
> 
> ![grafik](https://user-images.githubusercontent.com/53860633/84763476-8ce18300-afcc-11ea-92f1-a513e321c470.png)

![Screenshot_20200620_073612](https://user-images.githubusercontent.com/34140076/85191813-e695c600-b2c8-11ea-844b-87e936abf67b.png)
Mozzila Firefox for Ubuntu 77.0.1 (64-битный)

**Comment by OlegJktu** [comment]
> 
> 
> I cannot reproduce the behaviour (Chrome, Firefox)
> 
> Which browser do you use?
> 
> ![grafik](https://user-images.githubusercontent.com/53860633/84763476-8ce18300-afcc-11ea-92f1-a513e321c470.png)

win 10 chrome 
![Iobroker глюк 2](https://user-images.githubusercontent.com/34140076/85193252-6faffb80-b2cf-11ea-9ffe-b9f8825fbb05.PNG)
 83.0.4103.106

**Comment by OlegJktu** [comment]
I find how to fix.
Put the repo only latest
And made command iobroker upload all.
![Screenshot_2021-02-12 intro - ioBroker](https://user-images.githubusercontent.com/34140076/107781487-dd69d580-6d3f-11eb-8c0a-15c1781e1354.png)
![Screenshot_2021-02-12 Portainer local](https://user-images.githubusercontent.com/34140076/107781502-dfcc2f80-6d3f-11eb-86a6-4294c83846c9.png)
![Screenshot_2021-02-12 adapters - ioBroker](https://user-images.githubusercontent.com/34140076/107781690-15711880-6d40-11eb-97f3-a90cfbb39012.png)
