### ISSUE TITLE
Bulk-Action überschreibt Alias-IDs des SQL-Adapters

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.admin#592]
Ausgangslage (Beispiel) - SQL-Adapter:

- 50 Objekte mit SQL-Logging aktiv
- Die Objekte sind nicht einheitlich bzgl. "Nur Änderungen protokollieren"
- 20 Objekte haben Alias-IDs

Filtert man nun alle Objekte mit SQL und ändert dann im Bulk die Einstellungen bzgl. "Nur Änderungen protokollieren" (unter Alias-ID wird "unterschiedlich" angezeigt), sind im Anschluss alle eingetragenen Alias-IDs weg.

Ursprüngliches Issue beim SQL-Adapter ([#128](https://github.com/ioBroker/ioBroker.sql/issues/128)) entsprechend dokumentiert.

**Comment by Apollon77** [comment]
I think the main topic here is: How Admin should decide which fields to fill and which not?

**Comment by Apollon77** [comment]
duplocate to #549
