### ISSUE TITLE
Show somehow if a version was installed from Github/"not npm"

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#595]
We should show somehoe (maybe a small Github icon next to the version number in Admin?) that an adapter was installed from "not npm" (means GitHub basically).

To decide this it should be possible to use <instance-object>.common.installedFrom. The content is the Install URL (when Github) or "packagename@version" when from npm

**Comment by AlCalzone** [comment]
If an adapter was installed from github, the commit hash should be displayed as the version IMO. Otherwise, the information will just be "installed from master at some point in history" 99% of the time.

**Comment by Apollon77** [comment]
such a long thing will never have enough space to show there ... maybe as mouse over. but in fact the adapter shows a version number on start and not the hash ... maybe we should also show something like this in adapter log? So also logging different in controller?

And BTW: There are cases where no commit hash exists but only the URL! (especially when not master branch)

**Comment by AlCalzone** [comment]
The first 7 chars would be enough - like github does.

**Comment by ldittmar81** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/496 - we could show it on this new column. After the version number an octocat icon

**Comment by AlCalzone** [comment]
> There are cases where no commit hash exists but only the URL!

I've done a quick test (with a dependency, not adapter, but it should work the same):
```
npm i AlCalzone/node-zwave-js#cc-unit-tests
```
The containing package.json contains
```json
"dependencies": {
...
    "zwave-js": "github:AlCalzone/node-zwave-js#cc-unit-tests"
}
```
which doesn't help a lot (except we know its from github).

But the module's package.json has this:
```json
"_resolved": "github:AlCalzone/node-zwave-js#b92e01587e21f9c05bdd49d09799e70f02cdf497"
```

**Comment by Apollon77** [comment]
I experimented with that package.json parsing and it did not really worked for all cases, so this was not the option. But we could retry (would be a controller 3.2 topic then)

"iobroker install" will detect a GitHub install and then try to fetch the commit id from that (if master) ... bt depending on rate limiting and such there is a chance that this is not possible to retrieve

**Comment by ldittmar81** [comment]
And what about an user that download it and install it from the disc? Or maybe a installation from gitlab?

**Comment by WLAN-Kabel** [comment]
Maybe we should check if it was installed from npm. If not, then show something.

**Comment by Apollon77** [comment]
that was my initial idea ... When installed from file also the "InstalledFrom" should not contain "packagename@version" ... We only need to make sure not to show it when installedFrom is empty/not existing ... then the adapter was installed "pre controller 2.0" ... then we do not know it

**Comment by AlCalzone** [comment]
> that download it and install it from the disc? 

Then the path in the root package.json starts with `file://`

> Or maybe a installation from gitlab?

Not sure, wanna check?

> it did not really worked for all cases

IMO it would already be an improvement if we have that info sometimes. And especially since installing from Github is the main usecase.

> "iobroker install" will detect a GitHub install and then try to fetch the commit id from that (if master) 

Why not rely on the information npm already provides us with?

**Comment by WLAN-Kabel** [comment]
I just checked, the following information is already read out and can be used.
installedFrom: "iobroker.javascript@4.4.3"
installedFrom: "https://github.com/ioBroker/ioBroker.javascript/tarball/7118ff34ad97c44f193a14e3ee291ffc11886576"

**Comment by Apollon77** [comment]
> Why not rely on the information npm already provides us with?

If we can we should!
So we could enhance the logic that currently fills installedFrom and check if we can use _resolved from package.json ... sure ... But this is a controller issue ...

We need to have it in "installedFrom" because on automatic reinstallations (file deletion, move to other host or such) we need to know the location that we can use with npm install to reinstall the same version!

**Comment by WLAN-Kabel** [comment]
> `installedFrom: "iobroker.javascript@4.4.3"`
> or
> `installedFrom: "https://github.com/ioBroker/ioBroker.javascript/tarball/7118ff34ad97c44f193a14e3ee291ffc11886576"`

The information is in the common part of each instance.

**Comment by Apollon77** [comment]
> The information is in the common part of each instance.

Each instance that was created or adapter updated >jscontroller 2.0 :-) DSo very old instances will not have that!

**Comment by AlCalzone** [comment]
> created or adapter updated >jscontroller 2.0 :-) DSo very old instances will not have that!

Oh, I'm totally fine with that. If we need to know which github version a user has installed, it is most likely a very recent one. And for displaying the version we can still fall back to the instance version field.

**Comment by WLAN-Kabel** [comment]
This is the current implementation.

![grafik](https://user-images.githubusercontent.com/53860633/85165718-88d09200-b266-11ea-8009-02fccad84577.png)

**Comment by Apollon77** [comment]
maybe we find a better icon instead of a "warning"?

**Comment by Apollon77** [comment]
But else: great from my side!!

**Comment by WLAN-Kabel** [comment]
I actually think it's good that this is a warning, because the installed version will most likely not be supported by the developer.

But we can also take another icon.

**Comment by ldittmar81** [comment]
What about a yellow fa-github icon?

**Comment by WLAN-Kabel** [comment]
It is not necessarily installed from Github, but still a good alternative.

**Comment by Apollon77** [comment]
like too

**Comment by WLAN-Kabel** [comment]
Icon has been changed.
