### ISSUE TITLE
js-c 3.2: Implement AES192-cbc for encryption like js-controller > 3.2

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#598]
- https://github.com/ioBroker/ioBroker.js-controller/pull/887 this will need js-c 3.2, so still some time to go ;-)

**Comment by foxriver76** [comment]
Now with the launch of js-c 3.2 it would be nice to have the feature in admin too, please see the above linked pr for implementation details and how to detect the used encryption type

**Comment by Apollon77** [comment]
There is already a "Kidnof reference implementation" for also in browser  that we could CHECK and adopt maybe?!

https://github.com/ylabonte/ioBroker.procon-ip/blob/master/admin/crypto-helper.js

**Comment by Apollon77** [comment]
@GermanBluefox Should we implement it and add a js.controler 3.2 dep? (we need a 3.3.dep at the end anyway)

**Comment by GermanBluefox** [comment]
Yes we can implement it and we don't need any front-end libs for encoding/decoding

**Comment by Apollon77** [comment]
@GermanBluefox we missed that for admin5?

**Comment by GermanBluefox** [comment]
Implemented

**Comment by Apollon77** [comment]
@Feuer-sturm We need to test this very carefull ... in fact: setting a password and check that adapter starts correctly

**Comment by Feuer-sturm** [comment]
@Apollon77 Test done with Admin 6.2.3, Influx Adapter 3.1.7

Test steps:
In token field for influx adapter write wrong token value, store
In token field write correct value, start, start instance
Influx Adapter is ok and measurements are stored correctly


system.adapter.influxdb.0
"token": "$/aes-192-cbc:5de01......
