### ISSUE TITLE
Filter im History Tab funktioniert nicht

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#599]
History v1.9.9

Hallo, ich schaue mir grad die History Tabelle am Leistungsobjekt eines Messsensors an und sehe die Änderungen vom heutigen Tag. Nun hab ich versucht das Datum von gestern einzutragen .. und beim Betätigen des Refresh buttons passierte gar nichts .. die Werte von heute sind nicht mal verschwunden. Fenster verlassen und nochmal rein .. irgendwann stand da "no data". Beim schreiben dieses Textes purzeln Werte von heute ein obwohl im Filter noch immer das Datum von gestern eingetragen ist. Dies nur als Kontext .. wenn das Verhalten grundsätzlich normal ist .. ok.

ABER .. ich warum sehe ich keine Daten von gestern? Hatte das Problem auch schon beim FBpresence-Adapter .. dass dort immer behauptet wurde es gäbe keine historischen Daten. Retention Time steht alles auf Default .. 1 Year.

Später am Tag:

Keine Ahnung was da los ist .. jetzt sehe ich in besagter Tabelle nicht mal mehr die Daten von heute :-(
"no data"

https://github.com/ioBroker/ioBroker.history/issues/71

**Comment by MartinSchlender** [comment]
In the history of an object there is a way to filter. One can enter date from to and time from to. The result is unpredictable. With German date format it is not working at all. With american date format it works sometimes.
![image](https://user-images.githubusercontent.com/69381774/89717665-26b82180-d9b9-11ea-9768-9fc66de2111b.png)

**Comment by daniel-lo** [comment]
My foremost problem is that some adapter complain about non-existing data beyond today .. so no histrical data. This is what I would like to have fixed.

**Comment by MartinSchlender** [comment]
This problem is not solved at all. It´s still the same as described above

**Comment by daniel-lo** [comment]
correct .. not solved

**Comment by christianh17** [comment]
Are there any news about this issue?

**Comment by GermanBluefox** [comment]
Please retest with Admin5

**Comment by daniel-lo** [comment]
When I opened history on a sensor I saw yesterdays data but after a refresh I cannot go back and only see todays values dropping in.

**Comment by GermanBluefox** [comment]
> When I opened history on a sensor I saw yesterdays data but after a refresh I cannot go back and only see todays values dropping in.

Refresh of what? Admin4=>Admin5, Browser F5, something else?

**Comment by daniel-lo** [comment]
the refresh button on the history tab

**Comment by daniel-lo** [comment]
I checked
/opt/iobroker/iobroker-data/history/
and the directory is full of folders with data
one folder had a bad date - which I have now deleted.

Now when I go to the history tab of my adapter I see the history log from today.

BUT .. when I enter another date like

Date from/To 2021-05-06

I see values from 2021-05-01 (regardless of what date I enter - even if I use today 2021-05-08)

So whatever date I enter incorrect data is shown.

I will delete all data folders and maybe this fixes it .. but I thought you should knnow.

**Comment by daniel-lo** [comment]
After deleting all folders and restarting history I notice:

The folder for today is not immediately restored (could be held in RAM first)

And strange entries appear at the start of recording:

![grafik](https://user-images.githubusercontent.com/4311558/117529911-a885bb80-afda-11eb-8c95-c0ae917eba74.png)

**Comment by Apollon77** [comment]
That does noc ook like the Reach UI but the "old" UI ... please switch to React UI and check there

**Comment by daniel-lo** [comment]
oje .. ich hab im Admin Adapter auf die experimentelle UI umgestellt und kriege dies her (bin mir nicht sicher ob das vorher auch so war):

![grafik](https://user-images.githubusercontent.com/4311558/117531695-12ef2980-afe4-11eb-96ee-86a235952f68.png)

![grafik](https://user-images.githubusercontent.com/4311558/117531708-21d5dc00-afe4-11eb-88a5-4abde11ce3a7.png)

History weiter prüfen kann ich wohl am besten morgen .. wenn ein zweiter Tag angelaufen ist

**Comment by daniel-lo** [comment]
Auch interessant .. vorhin alle Verzeichnisse gelöscht .. jetzt gibt es:

![grafik](https://user-images.githubusercontent.com/4311558/117532675-ee498080-afe8-11eb-8e69-50e055e1d4de.png)

**Comment by Apollon77** [comment]
Akruell kann es bei der Erstinstallation von Admin5 dazu kommen das alle Adapter einmalig neu gestartet werden ... ich denke das war es. Sonst braucht es bitte mehr Logs

**Comment by daniel-lo** [comment]
OK .. erklärt aber die Geisterverzeichnisse nicht :-)
Ich hab ja grad mehrere Baustellen .. ich mach jetzt mal ein Neustart und speichere dann auch den Log.

**Comment by Apollon77** [comment]
Hm ... was ist den innden Verzeichnissen drin?

**Comment by daniel-lo** [comment]
history.hm-rega.0.950.json
history.hm-rega.0.1235.json

**Comment by daniel-lo** [comment]
dafür bin ich aber auch überrascht wieviele im Verzeichnis von heute auftauchen .. bin mir über max 2 Objekte bewusst wo ich das manuell aktiviert habe .. bestimmt ist das bei einigen Default?!

**Comment by Apollon77** [comment]
> bestimmt ist das bei einigen Default?!

wäre mit neu

**Comment by daniel-lo** [comment]
Also das war ich nicht .. sind aber im heutigen Verzeichnis auch nicht zu sehen:

![grafik](https://user-images.githubusercontent.com/4311558/117562048-455c5d80-b09c-11eb-938a-1508aa36548e.png)

**Comment by Apollon77** [comment]
Der Adapter legt nur was an wenn Daten da sind ... also irgendwie muss es aktiv gewesen sein ... bzw was ist denn in den File drin?

**Comment by daniel-lo** [comment]
bei den früheren Verzeichnissen von hm-rega:

[
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  },
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  },
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  },
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  },
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  },
  {
    "val": true,
    "ack": 1,
    "ts": 1619415918000,
    "q": 0,
    "from": "system.adapter.hm-rega.0",
    "user": "system.user.admin"
  }
]

**Comment by daniel-lo** [comment]
anderes beispiel history.alexa2.0.info.connection:

[
  {
    "val": null,
    "ts": 1620456562749,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620460532303,
    "lc": 1620460532303,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620460614504,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620461043580,
    "lc": 1620461043580,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620461108632,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620462187446,
    "lc": 1620462187446,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620462249153,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620463338204,
    "lc": 1620463338204,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620463409609,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620482106004,
    "lc": 1620482106004,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620482166633,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620488231581,
    "lc": 1620488231581,
    "q": 64,
    "from": "system.adapter.history.0"
  },
  {
    "val": null,
    "ts": 1620488313330,
    "ack": 1,
    "q": 64,
    "from": "system.adapter.history.0"
  }
]

**Comment by daniel-lo** [comment]
Leider noch immer buggy Admin 5.0.19:

![2021-05-10_065539 Filter 1](https://user-images.githubusercontent.com/4311558/117607797-093d0180-b15d-11eb-973f-090fc29e3908.png)

![2021-05-10_065646 Filter 2](https://user-images.githubusercontent.com/4311558/117607812-0d691f00-b15d-11eb-8b03-c81926c109df.png)

**Comment by daniel-lo** [comment]
5.0.24 .. noch genau das Gleiche

**Comment by GermanBluefox** [comment]
Please retest with Admin6 and if still exists => reopen

**Comment by MartinSchlender** [comment]
Hi,
I just installed the new Admin 6.1.8 and tried. There are still the same problems. The one that seems to work is the selection "last our". But if I try "the last 24 hours" it gives me crap - here is an example:
![image](https://user-images.githubusercontent.com/69381774/176994510-059827f1-62f5-461b-9a81-feb8bb06d43f.png)

there are only a hand full of values from today and then just a huge gap jumping to yesterday 15:05 ????
Please reopen

**Comment by Apollon77** [comment]
@MartinSchlender Which history version is installed? The list only works correctly with history 2.x from beta channel!

**Comment by MartinSchlender** [comment]
> @MartinSchlender Which history version is installed? The list only works correctly with history 2.x from beta channel!

Thanks - that solved the problem. After updating to the newest History everything works fine.
