### ISSUE TITLE
Admin-Seite wird nicht vollständig geladen, bei einer Netzwerkbandbreite von 700kBit/s

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.admin#600]
Leider kann die Admin-Seite nicht vollständig angezeigt werden, wenn zum Laden der Daten nur eine Bandbreite von 700kBit/s zur Verfügung steht. Bevor die Seite vollständig geladen ist, wird anscheinend ein Reconnect durchgeführt, das dazu führt, dass gar keine Daten mehr geladen werden!
![ioBroker admin - Google Chrome 05 07 2020 11_20_38](https://user-images.githubusercontent.com/43810083/86529543-aed67300-beb1-11ea-8044-a294710f5ac5.png)

**Comment by Apollon77** [comment]
Ich dneke das liegt am 20s socket.io ping/pong. Sollte sch mit Admin 5 lösen

**Comment by Apollon77** [comment]
Bitte mit 4.1.6 versuchen

**Comment by Hirsch-DE** [comment]
Hallo,
mit der Version 4.1.6 funktioniert es.
Danke
