### ISSUE TITLE
Eigener Datenpunkt nicht anlegbar

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#601]
Ich kann keinen eigenen Datenpunkt anlegen.

Ordner ".eigene" selektiert.
Plus aus dem Top-Menü
Name vergeben, Datenpunkt, Zahl -> hinzufügen
Name wird übernommen .. sonst ist das Fenster Allgemein leer.

**Comment by daniel-lo** [comment]
nach einem stop/start von iobroker ist der Datenpunkt da .. muss bei jeder Änderung am DP neu starten.

**Comment by Apollon77** [comment]
Ääähm .. wie lautet der Name? ".eigene"? SO ein name ist nicht unterstützt!!

Bitte lege eigene States in 0_userdata.0.* an!

Mit dem Namen wirst Du nie glücklich. "." als erstes Zeichen ist nicht unterstützt (und noch andere Dinge)

**Comment by daniel-lo** [comment]
Ging doch Ewigkeiten gut ...

![eigene](https://user-images.githubusercontent.com/4311558/86711437-3b04a980-c01c-11ea-8f63-2027dc58e6c2.png)

**Comment by Apollon77** [comment]
Ja, seid js.controller 2.0 haben wir solche nicht erlaubten Themen unterbunden

**Comment by daniel-lo** [comment]
Verstehe .. dann hab ich wohl so lange keinen neuen Datenpunkt gebraucht :-)
Danke für die Info .. ich lasse die alten jetzt aber mal da wo sie sind .. hoffe das ist kein Problem.

**Comment by Apollon77** [comment]
Am Ende wird JavaScript und andere Adapter nicht darauf subscriben können weil an vielen stellen solche IDs jetzt ignoriert werden.

**Comment by daniel-lo** [comment]
ups .. gibt es eine Möglichkeit die Datenpunkte zu verschieben .. ohne die Skripte danach anpassen zu müssen .. bzw. so, dass sie den geänderten Pfad automatisch übernehmen?

**Comment by Diginix** [comment]
Nicht dass ich wüsste. Du musst sie manuell am neuen Ort anlegen und könntest danach aber in den Skripten mit search/replace arbeiten. Bei Blockly müsstest du es entw. über das Skript-Spiegeln im Dateisystem lösen oder alle Skripte als ZIP (JSON) exportieren. Dann mit einem Editor deiner Wahl das search/replace in den JSON Dateien vornehmen und das Backup wieder einspielen.

**Comment by daniel-lo** [comment]
danke .. das heb ich mir mal für's WE auf :-)
