### ISSUE TITLE
Enhancement: Visible distinction between stable and latest repository updates

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.admin#606]
I usually have the repository set to latest to see which new features/bugfixes the adaper developers are working on. But I only update to stable versions unless there is a good reason to use the latest adapter version. Unfortunately, there is no indicator on the adapter page that marks if the update comes from the latest or the stable repository. I always have to change the repository and reload the page to see which update comes from the latest or stable repository. It would be great if some kind of indicator what show that on the adapter page - preferably in both view modes.

**Comment by Ilovegym66** [comment]
Additional for **all installed Adapters:**
selected in 3 stages with 3 colors, green - stable, yellow - latest, red - git. Same in the instances, please.

**Comment by Apollon77** [comment]
I think first stuff is already done (like github versions are shown with a special icon in Admin 5 ... @WLAN-Kabel what do you think? I would be more with the idea to have stble selected by default and allow to install once from latest without having to switch the repository
