### ISSUE TITLE
Admin 4.1.3 - Port 8082 hardcoded 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#607]
assigned with a issue in Phantomjs-Adapter, we found, that the port 8082 is hardcoded in the admin-adapter, see [Forum](https://forum.iobroker.net/post/466456)
In the [Line](https://github.com/ioBroker/ioBroker.admin/blob/master/src/lib/js/selectID.js#L2405) is the fault, the configured Port in the Web adapter is ignored here.

**Comment by Apollon77** [comment]
I think the mail question is which "web adapter" shuld be used? Or we also need to define a "default "One :-(

**Comment by Ilovegym66** [comment]
Yes, should be selected like  other adapters.. iot.. etc

**Comment by GermanBluefox** [comment]
I do not understand the problem

**Comment by Apollon77** [comment]
The correct linked line is https://github.com/ioBroker/ioBroker.admin/blob/master/src/lib/js/selectID.js#L2407 ... here port 80832 is hard coded - there might be no admin adapter on that port in the system. in fact we would need a syste,config setting for a "default web instance" (or if only one use the port from there. So in fact we need a more dynamic web-port lookup

**Comment by GermanBluefox** [comment]
Ist nicht möglich zu lösen in Admin4

**Comment by Ilovegym66** [comment]
kein Problem, lassen wir offen für Admin 5? oder dann neues Issue aufmachen?

**Comment by GermanBluefox** [comment]
Dann lieber neues.

**Comment by Ilovegym66** [comment]
:-)
