### ISSUE TITLE
"pushover" not shown in object-list

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.admin#610]
I have installed the pushover adapter, but it does not appear in the object lists. The screenshot shows that system.adapter.pushover exists. I have observed this on all systems. 

![image](https://user-images.githubusercontent.com/35403739/89631306-e82f4380-d8a0-11ea-898e-f97c86a5fa97.png)

**Comment by Apollon77** [comment]
And what is the problem? The pushoer Adapter is not having any states,or objects, so it do not need to be there,
