### ISSUE TITLE
update changelog please

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.admin#612]
Hi,
last update in changelog is V4.1.1, now we are on 4.1.7, no changes are made ? only the version number? :-)
update the changelog, please. :-)

**Comment by Apollon77** [comment]
I will sync it ... it is in https://github.com/ioBroker/ioBroker.admin/tree/4.0.x#changelog at the moment because the master is "Admin 5 dev" version

**Comment by Ilovegym66** [comment]
thank you, that solves my problem :-)

**Comment by Apollon77** [comment]
sync done
