### ISSUE TITLE
admin.0.info.updatesNumber and .updatesList are not updated after upgrading adapters

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#613]
Just a minor thing: After upgrading adapters, the blue bubble with the numbers of updates in the sidebar disappears - but the datapoints admin.0.info.updatesNumber and admin.0.info.updatesList keep the old values.

**Comment by Apollon77** [comment]
Is it updated when the repo is reloaded?

**Comment by Apollon77** [comment]
duplicate zu https://github.com/ioBroker/ioBroker.admin/issues/275?

**Comment by sbormann** [comment]
Yes, sorry, did not see the duplicate. Thanks!!

--
Von meinem iPhone aus gesendet

Am 26.08.2020 um 00:24 schrieb Ingo Fischer <notifications@github.com>:

﻿

duplicate zu #275<https://github.com/ioBroker/ioBroker.admin/issues/275>?
