### ISSUE TITLE
Mass actions under objects do not work as expected

### ISSUE THREAD

**Issue by Photographix** [ioBroker/ioBroker.admin#614]
**Describe the bug**  
Multiple changes of history options on multiple objects (all). E.g. activate all and hold time unlimited

**To Reproduce**  
1. Admin 4.1.7
2. Objects Register
3. Wrench
4. Activate check mark for all (Influx)
5. Save

**Expected behavior**  
Countdown to zero until all objects are set

Unfortunately nothing happens (DEV Console Chrome error)
Cancel is possible

**Screenshots & Logfiles**  
![Bildschirmfoto 2020-08-27 um 23 04 17](https://user-images.githubusercontent.com/16647382/91496130-eb27bd80-e8bb-11ea-9b8c-4da22e047e71.png)

**Versions:**  
 - Adapter version: 4.1.7
 - Node.js v12.18.3
 - NPM 6.14.6
 - Operating system: Docker Container

**Comment by Apollon77** [comment]
... but also seems to be a broken object somehow

**Comment by Apollon77** [comment]
duplicate of #615

**Comment by Photographix** [comment]
No with Admin 4.1.6 I have the same problem :-/

![image](https://user-images.githubusercontent.com/16647382/92081402-49c0d000-edc3-11ea-91f0-b1984c4a5211.png)

**Comment by Apollon77** [comment]
Ok, so this is not because of names :-) Good to know. Thank you

**Comment by Apollon77** [comment]
Please try 4.1.8

**Comment by Photographix** [comment]
Yes it works as expected again :-)
Thanks!
