### ISSUE TITLE
Admin 4.1.7 - Unable to select the properties of object if special chars in object-id

### ISSUE THREAD

**Issue by LevyKo** [ioBroker/ioBroker.admin#615]
In 4.1.7 you can't set or edit the properties of an object with special chars in the object-id (e.g. Shelly use "#" or Smartmeter use ":" and "_"). The settings window is displayed with the heading "Settings of 0" and no object is chosen. The same applies to history and/or database properties. If you want to edit, it does not select an object and shows "Settings of 0". This only applies 4.1.7. In 4.1.6 everything works as expected.

1. In Admin-Interface select Objects
2. Select a datapoint with a special-char in the path (e.g. shelly.0.SHSW-21#55A5A7#1.Shutter.Energy)
3. Click on Edit-Icon or Database-Settings-Icon
4. See "Einstellungen von 0" ("Settings of 0") in the heading and no object is selected

The expected behavior would be to edit the selected object.

 - Adapter version: 4.1.7
 - JS-Controller version: 3.6.1
 - Node version: 12.18.3
 - Operating system: debian 9.13

**Comment by JoschaMiddendorf** [comment]
I can confirm this misbehaviour in 4.1.7

**Comment by Diginix** [comment]
I have objects with IDs like: devices.RF:01234567.status_ex and it is not possible to edit any object details.
Even RAW is completely empty. And also already existing history data can't be viewed.
Rollback to 4.1.6 and all is ok.

JS-Controller 3.1.6
nodejs 12.18.3
npm 6.14.6

**Comment by Apollon77** [comment]
see also https://github.com/Apollon77/ioBroker.smartmeter/issues/149#issuecomment-685518484

**Comment by Diginix** [comment]
My problem is fixed with 4.1.8
