### ISSUE TITLE
Admin Info Panel verschluckt letzte Zeile

### ISSUE THREAD

**Issue by PLCHome** [ioBroker/ioBroker.admin#616]
In der Info Seite wird bei allen Adaptern die letzte Zeile der read.me nicht dargestellt.
Hier ein Beispiel vom Admin Adapter, es betrifft aber alle Adapter:

Bei Info fehlt die Toilette:
![image](https://user-images.githubusercontent.com/29116097/91812028-b788c280-ec30-11ea-81fb-73b65ca50f72.png)

![image](https://user-images.githubusercontent.com/29116097/91812076-ce2f1980-ec30-11ea-8792-8cffab86becb.png)

Bei Änderungsprotokoll fehlt "(Apollon77) Fix password encryption logics and make compatible to js-controller 3.x again":
![image](https://user-images.githubusercontent.com/29116097/91811629-17cb3480-ec30-11ea-9777-1551c18d8785.png)

![image](https://user-images.githubusercontent.com/29116097/91811916-8a3c1480-ec30-11ea-96f5-4f1dc76e7cdb.png)

Bei "Lizenz" scheint es zu funktionieren:
![image](https://user-images.githubusercontent.com/29116097/91812164-edc64200-ec30-11ea-8bf7-2cda7861b925.png)

![image](https://user-images.githubusercontent.com/29116097/91812106-da1adb80-ec30-11ea-8c9b-b9d4658f9fb3.png)

**Comment by WLAN-Kabel** [comment]
Ist in Admin 5 behoben.

#545
