### ISSUE TITLE
page with objects reload in the background

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.admin#618]
**Describe the bug**  
The situation is completely identical to that described in issue [45](https://github.com/ioBroker/ioBroker.web/issues/45) from web adapter.

**To Reproduce**  
1. Go to objects tab
2. Open another window in the background (scripts for example)
3. Go to new window tab with scripts
4. Wait 1-2 minute and go back to objects window
4. See error (objects tab reloads)

**Expected behavior**  
objects tab not reloadet

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/92568859-76c02780-f288-11ea-9e34-59b44aa32bfd.png)

**Versions:**  
 - Adapter version: 4.1.8
 - JS-Controller version: 3.1.6
 - Node version: v12.18.3
 - Operating system: Docker

**Additional context**  
By the way, the problem from issue [45 ](https://github.com/ioBroker/ioBroker.web/issues/45)is completely gone! Now scripts do not reload in the background, for which special thanks!

**Comment by Anzic23** [comment]
The same thing happens with - intro tab, info tab

**Comment by Apollon77** [comment]
Yes and this is kind of "as designed". Admin is using socket.io to communicate with the server side part. socket.io is making alive checks via Ping/Pong messages. When they are not coming the connection is re-established and this triggers this reload.

Modern browsers stop any javascript in background tabs, and so no Ping Pong happens anymore which leads to the reload.
This will be handled differently in Admin 5
