### ISSUE TITLE
Hide tables in Admin for non-data logger adapters

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#619]
We have the situation to have custom html implemented and using that for data logger adapter.
But new developments like telegram and SourceAnalytix also have their setting on the state but no need for a table with history

Current situation : Table is always shown for each adapter using custom html
Wanted situation : adjustable setting which tabs should be available in relation to the adapter or not.

<img width="1496" alt="schermafbeelding 2019-01-22 om 10 39 41" src="https://user-images.githubusercontent.com/7318445/51526469-baa3b600-1e32-11e9-9552-14eb01030c09.png">

**Comment by DutchmanNL** [comment]
new issue as previous closed by stale bot https://github.com/ioBroker/ioBroker.admin/issues/364

**Comment by Feuer-sturm** [comment]
@DutchmanNL Is this issue still open?

In Admin 5.3.1 it looks on my system like this (with active telegram adapter)
![grafik](https://user-images.githubusercontent.com/25422320/155861063-05961914-08ee-496e-8f10-eec069c86f7a.png)

**Comment by DutchmanNL** [comment]
Verified & confirmed thank you remindering @Feuer-sturm
