### ISSUE TITLE
Request Darkmode for ioBroker

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.admin#620]
Hello dear Devs,
I request the Darkmode for ioBroker. There is nothing more to say ;)

Thank you.

**Comment by GermanBluefox** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/4582016/93890485-a8a2a680-fcea-11ea-948d-3d4867a653bb.png)


It is part of Admin5.

**Comment by FlexerJR** [comment]
Yes!!!! Thank you!
