### ISSUE TITLE
[Enhancement] List instances and their start order

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#628]
**Is your feature request related to a problem? Please describe.**
several adapters and scripts are created to monitor system processes or act on changes/updates.
In several situation adapter they should handle the event of are starter earlier then the adapter itself, in a result of that unneeded error's occur of information is missing.

Practice Example : Seq adapter which is sending all logging information to a centralized environment. Its no starting almost at the end and by that I miss or logging of ioBroker start

**Describe the solution you'd like**
Capability to have a priority list defined which adapters should start first (all other can be as is, lets not overload configuration)

**Describe alternatives you've considered**
None, as for the use cases the start order of instances is important (same for scripting, trigger on change or update is missing the start values of adapter start)

Dependency with capability in JS-Controller : https://github.com/ioBroker/ioBroker.js-controller/issues/1054

**Comment by GermanBluefox** [comment]
Tiers are implemented with js-controller 3.3. and admin 5.0.10
