### ISSUE TITLE
different Icons for state with role button for false and true

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.admin#629]
**Is your feature request related to a problem? Please describe.**
it is not possible to see, the value of a state with role "button", addtional action needed like mouse over or edit

**Describe the solution you'd like**
different icons for the values true and false

**Comment by Apollon77** [comment]
A Button has by definiton no state ... A button can only be triggered (like the button on your wall). So what true/false  should mean?

**Comment by truegreyhound** [comment]
this is clear, but a filled icon for true and an empty one for false would be an option for visualization. Because this is too cumbersome for me in the admin, I'm starting again to replace the button role with value.

**Comment by Apollon77** [comment]
Ok, again: what is for you the difference on a button between true and false? e.g. homematic is setting the button to true ONCE after that it only triggers true again, it is never restored back to false ... so what does it then mean?

**Comment by truegreyhound** [comment]
Does the state have the role "state", in the admin view of the objects I can immediately see whether true or false, regardless of how the value is to be interpreted. If I assign the "button" role to the state in a functionally correct manner, the view does not show the value of this state. I have to use the mouse over function or edit the value.

**Comment by Apollon77** [comment]
in expert mode the real value is shown directly .. is this not sufficient?

**Comment by truegreyhound** [comment]
ok, I hadn't even noticed that, had only ever used it for other purposes. Yes I can work with it, but too much dangerous data in the ad in my opinion
Would a button be possible in normal mode that switches the interpretation of the role on or off?

**Comment by GermanBluefox** [comment]
Buttons are the states, that are write only and could accept only "true" with "ack": false.  All other usages are invalid and must be fixed in appropriate adapter.

**Comment by GermanBluefox** [comment]
It is implemented in Admin5 with opacity:
![image](https://user-images.githubusercontent.com/4582016/116322069-9a09f980-a7bb-11eb-9fa0-5f2df436e3ee.png)
![image](https://user-images.githubusercontent.com/4582016/116321978-6b8c1e80-a7bb-11eb-8a08-16cb3861174b.png)
