### ISSUE TITLE
Daten-Duplizierung bei mehreren Instanzen

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#63]
Hi,

ich habe eine Admin-Instanz für das Home-Netzwerk ohne Paswort und ohne SSL und eine für externen Zugriff mit Passwort und SSL.

Ich hatte jetzt schon mehrfach das Problem das beim beenden von iobroker (z.B. wegen Updates) ich es danach beim starten immer einer der beiden nicht hochkam weil der Port schon in Benutzung war. Irgendwie wurden wohl die Einstellungen beim beenden (oder neu starten?) auf beiden Adaptern die gleichen waren. Im objects.json war das dann auch so zu finden. Die eine laufende Instanz konnte das aber nicht editieren. Der Dialog bleibt leer. 

Wenn man es im objects.json wieder fixt geht danach alles ...

Irgendeine Idee?

**Comment by GermanBluefox** [comment]
Muss mit js-controller 0.9.0 gefixt sein.

**Comment by GermanBluefox** [comment]
?

**Comment by Apollon77** [comment]
dann machen wir mal zu, falls es nochmal passiert mach ich im Jira neu auf.
