### ISSUE TITLE
new copy button for state info

### ISSUE THREAD

**Issue by truegreyhound** [ioBroker/ioBroker.admin#630]
**Is your feature request related to a problem? Please describe.**
It is possible to get state info like value, ts, user and other when I pos the mouse cursor over the value.
For document or problem analysis is where helpfull, it would be helpful if this information could also be copied

**Describe the solution you'd like**
new button in the value field to copy the "mouse over" data to the clipboard

![image](https://user-images.githubusercontent.com/24899637/96177705-8c330c00-0f2e-11eb-9a89-93528c9ca9ea.png)

**Comment by truegreyhound** [comment]
finde ich eigentlich schade, dass das keinem fehlt, dürfte doch nicht so aufwändig sein oder?

**Comment by Diginix** [comment]
Für was brauchst du das in der Zwischenablage?
Im Skript kommst du an all diese Infos. Du könntest dir also ein Skript erstellen welches dir bei irgend einem Trigger die Infos per Telegram, Whatsapp, Email usw. sendet. Oder du speicherst dir die Infos in einem eigenen meta Objekt. Da kannst du sie sowohl in die Zwischenablage kopieren als auch in einer VIS anzeigen.  
Bleibt für mich aber immer noch die Frage wozu.

**Comment by truegreyhound** [comment]
Wenn ich im Admin einfach mal ein paar Werte prüfen will, ob sie sich geändert haben oder dito. beim debuggen. Außerdem werden bei längeren Zeichenketten die timestamps usw. nicht angezeigt.
Mit dem Copy2Clipboard kann ich mir dann die interessierenden Datenpunke "merken" und mit den aus einem Skript, Adapter bzw. Log erwarteten Werten vergleichen.
Bei dem Copy2Clipboard  wäre dann sicherlich auch sinnvoll die id mit auszugeben.
