### ISSUE TITLE
Log-Message: Unknown event: change

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#631]
When opening an adapter settings page, there are many messages in the console
````
change
Unknown event: change
````
They are fired from the onChange function:
![image](https://user-images.githubusercontent.com/49171332/97803989-35774300-1c4d-11eb-923c-79581c6ee935.png)

This sends a postMessage, but the message is unknown at the receiver's side:
![image](https://user-images.githubusercontent.com/49171332/97804006-5b044c80-1c4d-11eb-8ca2-97ab79808b39.png)

I don't see any issues here - but the many log-messages make debugging hard an should therefore be removed (just one line to ignore change and nochange messages).

**Comment by GermanBluefox** [comment]
Please ignore it
