### ISSUE TITLE
State dosn't refresh from time to time - clearing browser cache helps

### ISSUE THREAD

**Issue by oberstel** [ioBroker/ioBroker.admin#633]
**Describe the bug**  
From time-to-time, after using admin interface for several hours, object states won't refresh their states an longer. Old values seems to be static. 
Refreshing all entries within ioBroker dosn't help. 
Reloading the entire page within the brower (Safari) dosn't help.

I need to clear the browser cache to fix this issue.

**To Reproduce**  
Open admin Interface, work severel hours and check actuality of certain object states.

**Expected behavior**  
The object state should be actual every time. 

**Screenshots & Logfiles**  
none

**Versions:**  
 - Adapter version: 4.1.10
 - JS-Controller version: 3.1.6
 - Node version: 12.19.0
 - Operating system: Linux

**Additional context**  
none

**Comment by GermanBluefox** [comment]
Please re-validate in admin5
