### ISSUE TITLE
use maintenance flag for deletion of object and states to bypass validateId

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#634]
https://forum.iobroker.net/topic/38627/gel%C3%B6st-datenpunkt-l%C3%A4sst-sich-nicht-l%C3%B6schen-punkt-am-ende

**Comment by foxriver76** [comment]
Is it implemented? @GermanBluefox

**Comment by GermanBluefox** [comment]
Not yet

**Comment by GermanBluefox** [comment]
@foxriver76 Is this flag already implemented in js-controller? And if yes where?

**Comment by foxriver76** [comment]
it skips the `validateId` check in all adapter.js methods, we should use it to allow deleting legacy objects in admin so you can set it inside the options context of e. g. `deleteObject`

**Comment by GermanBluefox** [comment]
> it skips the `validateId` check in all adapter.js methods, we should use it to allow deleting legacy objects in admin so you can set it inside the options context of e. g. `deleteObject`

Thanks

**Comment by GermanBluefox** [comment]
Implemented in Admin5
