### ISSUE TITLE
Overview Tab / Links in Tiles

### ISSUE THREAD

**Issue by KoMa1978** [ioBroker/ioBroker.admin#637]
Hi all,

In the Overview Tab, there are links on each tile. It should be possible to manually overwrite them.

At the moment it uses the hostname I used to access iobroker, but in my case, the iobroker is behind a nginx web proxy and I access IOBROKER Admin interface via "iobroker.domain.local" while I access VIS via "vis.domain.local". Only this allows me to use only port 443 and have not to open different ports on my firewall. The nginx listening on port 443 distributes the request according to the used hostname.

nginx hat the advantag that it uses much less resources than apache but it doesn't allow to rewrite response traffic (AFAIK).

Thanks a lot,

**Comment by Apollon77** [comment]
How you would overwritethem? They are currently defined by the adapters and they utilize data from the config ... No idea how this should work in an "user understandable way" honestly. And the Links are the same ones as those on the instance tab

**Comment by KoMa1978** [comment]
These tiles are using the hostname, I use to connect to iobroker with an added port or (in case of homematic) the ip defined in the adapter.

Im not sure if it makes sense to overwrite these settings in the admin adapter for example with a regexp replacement functionality.

Or maybe it makes more sense to start a request for each single adapter like vis (which is the only one I use at the moment).

Of course this is mainly cosmetic ...

**Comment by GermanBluefox** [comment]
See https://github.com/ioBroker/ioBroker.admin/issues/647
