### ISSUE TITLE
set afterComma in objects-charts not to 0(zero) if float (use decimals for data with decimals/floats)

### ISSUE THREAD

**Issue by harvey637** [ioBroker/ioBroker.admin#643]
Hi,

using admin 4.1.11

when generating a history chart from an object that has decimals like a temperature (e.g. 3.2°C) the chart in the tab "objects-customs-history-chart" does not show the decimal.
So the graph itself is a bit of correct, but the displayed y-axis does not contain decimals, and the hover details also not:
![grafik](https://user-images.githubusercontent.com/10156426/100205103-f7e09f80-2f04-11eb-97b3-c44ad7d9dd01.png)

With graphs with small differences (change is with 2 or even 3 decimals) in the value the x-axis reveals no decimals at all:
![grafik](https://user-images.githubusercontent.com/10156426/100205562-93721000-2f05-11eb-8caf-26ddab09b9fe.png)

Now the y-axis is showing only 0 (Volt) and 1 (Volt), the value actually is 1.05 (Volt) = sometimes it is not even enough to use afterComma=2, so sad. 

But at least afterComma=1 would help with temperatures, which is a often used value.

Seems that the code for this is inside "src-rc-public-js-app.js", but I am not shure about how to change this into "afterComma=1" for the simple case, left alone how to correctly identify the neccessary number of decimals.

My whish: afterComma=1 should be easy for You :-)

Thank You
Harvey

**Comment by Apollon77** [comment]
we could take the relevant parts out of the PR https://github.com/ioBroker/ioBroker.admin/pull/568

* l%5B0%5D%5BafterComma%5D=2 : Show more info
* ?? l%5B0%5D%5BchartType%5D=steps : The "steps" view is better to see the Value at a specific time then "line"
* ?? timeFormat=%25H%3A%25M%3A%25S+%25d.%25m.%25y : TimeFormat with date, because when you zoom out you don't know the date

**Comment by GermanBluefox** [comment]
Please retest in admin5

**Comment by harvey637** [comment]
Hi Bluefox,
answered by mail, but sorry, not fixed.
It is not a major problem, but disturbing with a lot of temperatures, that normally have one decimal.
My case with 4 decimals (smartmeter reading of powerconsumption is in kWh with 4 decimals) really look sad.
Suggested fix from #568 looks easy and promising ....
cu
Harvey
