### ISSUE TITLE
User does not get permissions from assigned usergroup

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#644]
**Describe the bug**  
If a new user is created and then assigned to a group, the permissions (of the group) are not applied properly.

**To Reproduce**  
1. GoTo „Benutzer“ -> „neuen Benutzer erstellen“ (here user „test“)
![DE80FC19-581D-444D-98EE-3801357EF90A](https://user-images.githubusercontent.com/69053781/100417487-55016000-3081-11eb-9176-4fe9cb635c62.jpeg)

2. add this new user to group „Benutzer“
![1F5929A2-82C1-4AA0-8EB2-45AC3834DBA4](https://user-images.githubusercontent.com/69053781/100417567-82e6a480-3081-11eb-896f-56ba3dea2c3a.jpeg)

3. new user has no permissions
![4BD05067-C619-4972-A706-0D9812952B45](https://user-images.githubusercontent.com/69053781/100417627-a1e53680-3081-11eb-84a4-135c7eee496b.jpeg)

**Expected behavior**  
User has permissions from „Benutzergruppe“

**Versions:**  
 - Adapter version: admin 4.1.10
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0 (happens also also with 12.19.0)
 - Operating system: linux

**Additional context**  
Workaraound, which „may sometimes“ work can be found here: 
https://forum.iobroker.net/topic/20368/neuer-benutzer-keine-zugriffsrechte/8

**Comment by Apollon77** [comment]
Am i getting it right that you expect that the user kind of inherits the reights of the group directly? It is not working that way. The rights ate separated ... as on linux filesystem. The "rights combination" is then calculated dynamically when an object is tried to be accessed

**Comment by ice987987** [comment]
Then it was a misunderstanding on my part. How is then the simplest procedure that a user gets all rights of the group if:
a new user group is created with different rights. Afterwards a new user is created, this user gets the just created group. How does this user get the permissions? Logging in unfortunately results in an error as follows (f.ex. in vis):

![C69EC948-49A8-4742-9108-1F4372E352DA](https://user-images.githubusercontent.com/69053781/100496356-c01b6700-3153-11eb-8be7-acc4230d6df4.jpeg)

**Comment by GermanBluefox** [comment]
In admin5 you can see what the rights has every file. Can you check it?

**Comment by ice987987** [comment]
This is correct and it does also work in Admin v5.0.13 so far. The `Objekte` and its child's can also be changed: this works by clicking on the tree digit number on the right side.
Unter `Dateien`, the rights are also displayed, but they can't be changed by clicking on the number.

**Comment by GermanBluefox** [comment]
File access edit was fixed in 5.0.15
