### ISSUE TITLE
Receiving updates without an instance

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#645]
Eg .. I had Zigbee adapter installed but removed it at some point in time. I still receive updates for Zigbee though. Is this normal?

**Comment by Apollon77** [comment]
Depends ... if you only have removed the instance of zigbee then the adapter code is still installed and you see that in "Adapter tab". you can uninstall it there and then it is gone

**Comment by daniel-lo** [comment]
Ach so .. hatte angst ihn dann auch aus der Adapterübersicht zu löschen .. danke!
