### ISSUE TITLE
Interoperability of web and admin for chart not always working

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.admin#647]
**Describe the bug**  
Following setup:
- For web using https://sub1.domain.at
- For admin using https://sub2.domain.at
- Admin and Web are running without security/certificates as a reverse proxy takes care about the SSL

In this setup the Chart on states is always empty
![image](https://user-images.githubusercontent.com/35381530/101460152-7d1e7800-3939-11eb-8f61-0d3c7190b75a.png)

The console output shows 2 issues
![image](https://user-images.githubusercontent.com/35381530/101460201-93c4cf00-3939-11eb-99e5-2a59d12d8c78.png)

1. It seems that the chart is tried to load from sub2.domain.at with port from web
2. It seems that the chart is tried to load via http instead of https

**Expected behavior**  
Also in such setups the chart should loaded correct. As an idea, the url and security for the chart could either entered explicit on Admin as a additional parameter or it could be loaded from web adapters common.locallink parameter

**Versions:**  
 - Adapter version: 4.1.10
 - JS-Controller version: 3.1.6
 - Node version: 12.19.1
 - Operating system: Synology with docker image (linux)

Some prediscussions are done already here https://github.com/ioBroker/ioBroker.sql/issues/140

**Comment by GermanBluefox** [comment]
Impossible to solve. How should admin guess under which Domain is the web reachable?

**Comment by nkleber78** [comment]
@GermanBluefox The idea would either allow this to configure and keep this configuration also during update or let the user select the web instance which should be used. There are already some adapters that allow configuring/select the web instance during install. But I think the easiest way would be to add a configuration option which uses by default the URL like today, but if set then the configured URL is used. Would that an option?

**Comment by Apollon77** [comment]
locallink has an other purpose and so I would not use that. So the only config option would be to add kind of a "external service base-url" that also take e.g. reverse proxy stuff into account (like "https://sub1.domain/web/") and is then used for all links ... I could imagin that this also is benefitial for Docker usecases where internal ports can be mapped differently outside of the container. By default it is empty, but when filled is used.

**Comment by nkleber78** [comment]
@Apollon77 that makes sense for me and would fit for this usecases

**Comment by GermanBluefox** [comment]
Admin5 supports custom links in the intro. You can create a link there and click on it.
![image](https://user-images.githubusercontent.com/4582016/116446515-51a01980-a857-11eb-88ee-a48cb4d15b5c.png)

![image](https://user-images.githubusercontent.com/4582016/116446592-64b2e980-a857-11eb-977d-47235921680a.png)

**Comment by nkleber78** [comment]
@GermanBluefox does this helps for the issue with the chart inside the admin? If yes, this is a good option. At the end in such setups the chart in the objects view should going to work...
Anyway, thanks for your effort in driving the development...

**Comment by GermanBluefox** [comment]
Ok. I mixed up here intro page and chart page. Admin5 does not need web server to show chart.
