### ISSUE TITLE
Adapter view is not correct if upload is running

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.admin#649]
In case of a running adapter upload, or simply the value of system.admin.adapter.upload is not equal to 0, then the view or the specific adapter is not correct. Previous it was discussed here https://github.com/ioBroker/ioBroker.modbus/issues/83

![image](https://user-images.githubusercontent.com/35381530/102008070-24caea00-3d2e-11eb-9e2c-b523108bebdf.png)
![image](https://user-images.githubusercontent.com/35381530/102008073-2bf1f800-3d2e-11eb-85b5-e7395978817a.png)

**Expected behavior**  
Displaying is always correct even when an upload is running

**Versions:**  
 - Adapter version: 4.1.10
 - JS-Controller version: 3.1.6
 - Node version: 12.19.1
 - Operating system: Synology with docker image (linux)

**Comment by GermanBluefox** [comment]
Please verify in admin5
