### ISSUE TITLE
Wunsch: bessere Visualisierung, auf welchem Host man sich befindet

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.admin#65]
Ich habe tlw. bis zu drei ioBroker Admin Oberflächen auf (3 Hosts).

Leider passiert es mir zwischendurch, das ich im falschen Host arbeite.

Kann man deutlicher in der Admin-Oberfläche kennzeichnen, auf welchem Host man sich befindet?

Hostname / farblich / ...?

**Comment by Apollon77** [comment]
Farblich fänd ich cool ... Im "Host" Tab ne Farbe definieren können pro Host (und auto-vergabe irgendwie) und dann wird die navigationsleiste oder so in der Farbe passend zum Host eingefärbt

**Comment by Apollon77** [comment]
lternativ wenigstens Nachfrage bei wichtigen Aktionen (Installs und so) auf einem Slave

**Comment by GermanBluefox** [comment]
In Admin3 implementiert

**Comment by Apollon77** [comment]
Wie/wo editiere ich den farbwert?

**Comment by GermanBluefox** [comment]
Farblich nicht.
![image](https://user-images.githubusercontent.com/4582016/35652514-3f310902-06e4-11e8-8419-755966aad13f.png)
Aber mindestens schon zentral.
