### ISSUE TITLE
Adapter dependency not working (vis-google-fonts)

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.admin#651]
Some users reported the problem, that updating the Material Design Widgets adapter not working caused by the dependency to vis-google-fonts.

Admin Version: 4.1.12
more details: https://github.com/Scrounger/ioBroker.vis-materialdesign/issues/135#issuecomment-752032982

dependency in io-package.json: https://github.com/Scrounger/ioBroker.vis-materialdesign/blob/530ec6a4accc3c1d971ea5936df7cab02c329ac2/io-package.json#L304

I cant reproduce this issue.

**Comment by GermanBluefox** [comment]
If you install it via "github" button, the deps will not be installed.

**Comment by Apollon77** [comment]
@GermanBluefox maybe enhance the warning text below github installs and such by adding something like "Please note: Adapter dependencies are not checked when using this installation methid. Please check them yourself. Additionally you need to manually create an instance after installation if needed."

**Comment by Apollon77** [comment]
(because: it is not the first time that we have both of these questions)

**Comment by GermanBluefox** [comment]
So?
![image](https://user-images.githubusercontent.com/4582016/117283919-971ba280-ae66-11eb-9fdf-86fa64595714.png)

**Comment by Apollon77** [comment]
super. I adjustthe text via weblate later
