### ISSUE TITLE
Improved visibility of instance status

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.admin#652]
**Is your feature request related to a problem? Please describe.**
As almost 10% of all men I am suffering from impaired red-green vision (Röt-Grün-Farbschwäche).

It is hard for me to see which instance is running, disabled or has an error because the colored circle is really small. I do not have a problem seeing the colors in the button that starts or stops an instance as it is much larger.

**Describe the solution you'd like**
A possible solution could be using the whole cell like it is done in the the actions cell where you can start and stop an instance. For people with color blindness it would also be helpful to add an icon like the triangle for starting the instance and the two parallel lines for stopping the instance.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/58948938/103364856-0e0eec00-4abf-11eb-9ecf-7f408f73ccba.png)

**Comment by GermanBluefox** [comment]
Is it better now in Admin5?

**Comment by MC-1984** [comment]
Perfect, thank you!
