### ISSUE TITLE
Upgrade admin semver version to support "includePrereleases" to allow adapter upgrades for pre-release deps

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#655]
The current semver is kind of v3.x, includePrerelease is supported startng semver 6.x, but Iwas not able to find any minimized or "packaged" browser javascript

**Comment by AlCalzone** [comment]
Bundled from the latest semver version out there :)

[semver.zip](https://github.com/ioBroker/ioBroker.admin/files/6012625/semver.zip)

**Comment by AlCalzone** [comment]
And use the new property :)

**Comment by Apollon77** [comment]
What you mean?

**Comment by AlCalzone** [comment]
The comparing code in admin needs to actually use `includePrerelease`

**Comment by GermanBluefox** [comment]
I don't understand anything. Admin has 7.3.5 semver.

**Comment by Apollon77** [comment]
> Admin has 7.3.5 semver.

Also in Browser??? it is about the version checks in the browser part ...

**Comment by Apollon77** [comment]
> The comparing code in admin needs to actually use includePrerelease now that we can.

WHich is already done, but has no effect before we not update semver for browser part 

@GermanBluefox see https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/public/lib/js/semver.min.js (version 2.0.0 of semver!!) same as https://github.com/ioBroker/ioBroker.admin/blob/master/src/lib/js/semver.min.js ...

zip above should be a drop in replacement for thiése files
