### ISSUE TITLE
Update button in Gridview does not seem to check dependencies

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.admin#657]
**Describe the bug**  
As per issue #655 currently updates should not be possible using admin and js-controller beta. But if you switch adapter view to grid view, updates are possible and no notion of a unmet js-controller version is displayed.

**To Reproduce**  
1. Install js-controller beta (like 3.2.6-0, the - is important)
2. Go to adapters tab, switch to list view
3. Find an adapter with newer version and js-controller version requirement
4. See that update is not possible because of wrong js-controller version (see #655 )
5. Switch to gridview, see that error message is not visible and update can be startet

**Expected behavior**  
The misssing depencendy should be visible / checked in grid view, too and an update should not start.

**Screenshots & Logfiles**  
Gried view showing the (wrong) dependency mismatch:
![admin-can-not-update-from-listview - mouseover](https://user-images.githubusercontent.com/620860/104759412-268a3200-5760-11eb-8601-bc7a054e4fca.JPG)

Missing info about dependency mismatch:
![admin-can-not-update-from-gridview - mouseover](https://user-images.githubusercontent.com/620860/104759431-30ac3080-5760-11eb-9ea9-204d4bee1467.JPG)

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: 3.2.6-0
 - Node version: v12.19.0
 - Operating system: Ubuntu

**Comment by GermanBluefox** [comment]
Please recheck it with admin5
