### ISSUE TITLE
Dropdown in Adapter settings incorrect behavior again

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.admin#659]
**Bug was fixed with #638 but occurs in a little different type again**

**Describe the bug**  
I've integrated a Dropdown menu in a table in Adapter settings:

```
<table class="table-values">
  <thead>
    <tr>
      <th data-name="_index" style="width: 50px; background: #64b5f6; text-align: center" data-style="text-align: center">Nr</th>
      <th data-name="enabled"  style="width: 50px; background: #64b5f6" data-style="width: 70px" data-type="checkbox" class="translate">active</th>
      <th data-name="station_from" data-type="number" style="width: 15%; background: #64b5f6" class="translate">StationFrom</th>
      <th data-name="station_from_name" data-type="text" style="width: 15%; background: #64b5f6" class="translate">StationFromName</th>
      <th data-name="station_to" data-type="number" style="width: 15%; background: #64b5f6" class="translate">StationTo</th>
      <th data-name="station_to_name" data-type="text" style="width: 15%; background: #64b5f6" class="translate">StationToName</th>
      <th data-name="station_via" data-type="number"  style="width: 15%; background: #64b5f6">Via</th>
      <th data-name="traintype" data-type="select multiple" data-options="0/All"  style="width: 70px; background: #64b5f6" class="translate">TrainType</th>
      <th data-name="transfers"  style="width: 50px; background: #64b5f6" data-style="width: 70px" data-type="number" class="translate">Transfers</th>
      <th data-name="bicycle"  style="width: 50px; background: #64b5f6" data-style="width: 70px" data-type="checkbox" class="translate">Bycicle</th>
      <th data-buttons="delete" style="width: 100px; background: #64b5f6"></th>
    </tr>
  </thead>
</table>
```

Problem occurs with data-type "select multiple". In Chrome-Browser, the menu opens correct.

In the old bug, to enable or disable a option, I must click at the end of the text:

![image](https://user-images.githubusercontent.com/34286177/89231861-7f1ca700-d5e6-11ea-908f-e4144bad51a5.png)

Now, I can click anywhere, but the "selected" property isn't toggled in developer console, but in the view.

When clicking in the red marked area, the "selected" property is toggled correct.

**To Reproduce**  
Use an Adapter with table and dropdown, e.g. fahrplan, 

**Expected behavior**  
Click in complete line of element should enable or disable the element in the view and in the code

**Screenshots & Logfiles**  
See above.

**Versions:**  
 - Adapter version: ioBroker.fahrplan 1.0.2
 - JS-Controller version: 3.1.6 & 3.2.7
 - Node version: 12.20.0
 - Operating system: docker container

**Additional context**  

Thanks and regards,

Ralf

**Comment by GermanBluefox** [comment]
Can you try to move to Admin 5 and Json scheme?

**Comment by gaudes** [comment]
Hey @GermanBluefox,

not the solution I would like to hear :-)

Admin 5 is currently not productive and I have a search for stations integrated, so I'm not sure this would work with JSON schema.

If it is not possible to fix, I probably migrate to React for AdminUI.

Regards, Ralf
