### ISSUE TITLE
Object tree in Admin web site expands on changes

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.admin#661]
**Describe the bug**  
User has objects website in browser opened.
Adapter refreshs his objects including adding new objects and deleting unneeded objects
Subtree from Adapter expands under these circumstances
Problem is described currently from a few different users using my adapter "Fahrplan".

**To Reproduce**  
Use a adapter which works in the way described, for example fahrplan.

**Expected behavior**  
Closed subtrees should not be expanded on Adapter actions.

**Screenshots & Logfiles**  
-

**Versions:**  
 - Adapter version: For example fahrplan 1.0.2
 - JS-Controller version: current versions
 - Node version: unknown
 - Operating system: unknown

**Additional context**

**Comment by GermanBluefox** [comment]
Please use admin5
