### ISSUE TITLE
Accept common.states as array

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#662]
For eg loglevels it would be great if admin could use e.g. string  arrays and not only an object with key value pairs because often the key is redundant and makes handling in adapters harder.

**Comment by GermanBluefox** [comment]
IT must be changed too many places.

**Comment by GermanBluefox** [comment]
Admin 5.0.11 could handle it
![image](https://user-images.githubusercontent.com/4582016/116482541-a78bb600-a885-11eb-8e29-905895b25091.png)

**Comment by Apollon77** [comment]
@GermanBluefox  @foxriver76 but then we also need to enhance the Schema docs from state objects, beause till now not allowed ... and alle vidus also would pot. need to support it

**Comment by foxriver76** [comment]
adjusting schema.md isn't a big thing, but visualization adapters, yes..
