### ISSUE TITLE
Admin Password

### ISSUE THREAD

**Issue by detafun** [ioBroker/ioBroker.admin#663]
Hallo,
ich habe vor ein paar Tagen den Admin Login ein Password vergeben.
Jetzt wird immer als erstes nach dem Password gefragt. Das ist auch so richtig.

Was mir aufgefallen ist, das wenn ich in iobroker eingeloggt bin, und drinnen bleibe in einen Fenster, Dann aber nichts mehr eine weile mache, Das nicht komplett ausgeloggt wird. Ich habe weiterhin Zugriff auf bestimmte Seiten ohne das er mich wieder nach einen neuen Login fragt, da die Session ja abgelaufen ist.

Also Einloggen, stehen lassen und nach weis ich 30 Minuten mal die Info Seite aufrufen. Da kommt gleich die Abfrag zum Login neu. Andere Seiten werden zum Teil geladen. 

Denke das sollte nicht so sein. Sondern es sollte die Info kommen, Session abgelaufen, bitte neu Einloggen oder so..

cu Deta

**Comment by Apollon77** [comment]
Was hast DU denn als Session Laufzeit eingestellt? Welche Admin Version? Welcher js-controller?

**Comment by detafun** [comment]
Es ist alles Aktuell:
![grafik](https://user-images.githubusercontent.com/44980055/108666917-8b137c00-74d8-11eb-8e7f-601f6132d775.png)

![grafik](https://user-images.githubusercontent.com/44980055/108666965-aaaaa480-74d8-11eb-8361-b4510d6428d6.png)

Session, Standard, wo kann man das verstellen? Ich hab es noch nie verstellt, Standard so wie bei Installation

Das Passiert wenn man es einfach stehen lässt:

Ausgang Startseite.
Warten ca. 30 Minuten

Wenn man dann z.b. Info aufruft:
![grafik](https://user-images.githubusercontent.com/44980055/108672101-ca929600-74e1-11eb-8881-d6439a732198.png)

Hier sollte schon das auf dem ganzen Bildschirm erscheinen, das die Session abgelaufen ist.

Instanzen kann man komplett aufmachen. Ohne sich neu einzuloggen.

Objekte, hat er zum Teil geladen...

**Comment by Apollon77** [comment]
@detafun Please retest with Admin 5 and reopen if needed
