### ISSUE TITLE
Beim Installieren von Javascript werden Errors beim Serialport ausgegeben, die sind aber beim npm rebuild  nur Warnings

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.admin#666]
Bei der Installation von Javascript kommen Fehlermeldungen bezüglich Serial Port. Wenn ich ein rebuild mit npm mache sind die gleichen Fehlermeldungen allerdings Warnings und keine Errors

**Screenshots & Logfiles**  

`
pi@raspberrypi:~ $ cd /opt/iobroker/node_modules/serialport
pi@raspberrypi:/opt/iobroker/node_modules/serialport $ npm rebuild
> @serialport/bindings@8.0.8 install /opt/iobroker/node_modules/serialport/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
prebuild-install WARN install No prebuilt binaries found (target=12.21.0 runtime=node arch=arm libc= platform=linux)
make: Entering directory '/opt/iobroker/node_modules/serialport/node_modules/@serialport/bindings/build'
../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:409:70: **warning**: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);
   
`

Logfile 
`
**error**: javascript.0 (10472) ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/serialport.cpp:409:70: **warning**: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);

`

**Versions:**  
 - Adapter version: Admin 4.2.1
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Debian / PI

**Comment by Apollon77** [comment]
These are all just warnings and come from an adapter that still uses serialport 8 ... all will work. The reason is also not admin it is npm validating the whole tree. check all other adapters for updates
