### ISSUE TITLE
The representation of the adapter log differs whether the log is read from the file or sent directly to the Admin GUI 

### ISSUE THREAD

**Issue by Bannsaenger** [ioBroker/ioBroker.admin#667]
**Description**  
The representation of the adapter log differs whether the log is read from the file or sent directly to the Admin GUI 

**To Reproduce**  
1. log an error with e.g. adapter.log.error( ... ${err.stack} ... )
2. watch the log in tab-logs while the error is logged and mouse over the error
3. you see someting like this
![iobroker_error_log_01](https://user-images.githubusercontent.com/26897700/111280369-08479200-863c-11eb-8e91-600dd9b49241.png)
4. choose another tab an then go back to tab-logs
5. the presentation changed to a view with the error in multiple lines with the same timestamp
![iobroker_error_log_02](https://user-images.githubusercontent.com/26897700/111280372-08e02880-863c-11eb-85c3-62c27338380b.png)

**Versions:**  
 - JS-Controller version: 3.2.16
 - Node version: v10.17.0
 - Operating system: windows 
 - same on linux an other node and js-controller versions

**Comment by GermanBluefox** [comment]
Please retest with Admin5

**Comment by Bannsaenger** [comment]
Sorry, same behaviour in Admin5 (5.0.24) with Node v16.1.0

**Comment by Bannsaenger** [comment]
works in react ui, thanks
