### ISSUE TITLE
Add "Setup Authentication for Admin" as optional step to initial Wizard

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#669]
We should try to force users to setup Authentication for their Admin instance (skippable) as part of the initial setup steps.

We need to allow the user to configure:
* (strong) Password for user Admin
* Enable/Disable (defaults to enable) authentication for Admin

The page should have space for educational texts in general. Also when the user selects "disable" we should show a warning like textblock informing about the consequences.

I can provide texts when I see the screen-design

**Comment by Feuer-sturm** [comment]
Is this already released?
Yesterday evening I set up a new LXC container with Ubuntu and installed ioBroker by using this command 
`curl -sLf https://iobroker.net/install.sh | bash -` but I did not see the  possibility to setup authentication for Admin account.

**Comment by Apollon77** [comment]
This will be part of Admin5 ... Not the installer will ask for that but the first start with Admin ...
