### ISSUE TITLE
Add "Setup SSL" as optional step to initial Wizard

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#670]
We should allow the users to setup their system in a secure way. We have the self signed certificate auto-generated, so we could allow to enable that.

We should provide a page after #669 to inform the user and let him chose between:
* No SSL - including "warning style" text box if selected to inform about consequences
* Self signed certificate - including info box telling him that browser will bring message and he needs to accept it

We should also inform the user that he can use Let's encrypt to get better certificates, but I would not include that here (because needs some stuff to setup and would block the user progress here)

**Comment by buanet** [comment]
Yes, SSL is important, but more than this we should make sure the user is forced to give a username and a password for admin during the "first start wizard" (so there is no "admin" or other standard user which might be easily brute forced).

Regards,
André
