### ISSUE TITLE
Add info page about "port forwardsing and remote access to iobroker" at the end of install assistant

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#671]
We could have an educational page at the end of the install assistent which focusses on:
* Do not expose iobroker Admin or Web interfaces to the internet directly via port forwardings
* The Cloud services from iobroker  (veery short!!) can hel here to do that securely ...-> Link to Cloud Homepages
The content/texts could be different (harder, softer, info style vs Warning style) based on the decisions on ssl and authentication from the steps before (w.g. no ssl and no auth should tell it more hard to the user as when he enabled both)

**Comment by Feuer-sturm** [comment]
Is this already released?
Yesterday evening I set up a new LXC container with Ubuntu and installed ioBroker by using this command 
`curl -sLf https://iobroker.net/install.sh | bash -` but I did not see the mentioned information.

**Comment by Apollon77** [comment]
This will also be in Admin and will be available before we finalize Admin5 ( I think not yet done)
