### ISSUE TITLE
Make sure new tabs are shown directly after adapter install/reload

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#673]
Currently Admin remembers which tabs are to be displayed. This has as effect that new tabs are not displayed and so the user is not seeing it because it is unclear that an adapter provides a Tab.

Idea could be that Admin is not remembering which tabs to display, but which to hide. This would mean that new tabs are displayed directly and user can disable them and then they stay disabled.

Also changing this would enable all tabs on admin 5 update which would be ok and shows the user what tabs are there he maybe newer saw :-)

**Comment by GermanBluefox** [comment]
I think it is fixed in A5... should be checked
