### ISSUE TITLE
make localinks with only _default attribute work like localLink

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#674]
now where localLink is deprecated and we should change single local links to `_default: 'http://blabla'` it unfortunately looks pretty ugly in admin (I am not aware of the current look in admin 5, so maybe already fixed).

This is ugly:

![Bildschirmfoto von 2021-04-05 23-19-24](https://user-images.githubusercontent.com/25484431/113628872-dab39e80-9665-11eb-9d70-538919bb17e4.png)

If only `_default` given, make it look like this:

![Bildschirmfoto von 2021-04-05 23-20-22](https://user-images.githubusercontent.com/25484431/113628897-e4d59d00-9665-11eb-805f-fa268d8e369b.png)

**Comment by GermanBluefox** [comment]
Done in Admin5
