### ISSUE TITLE
[Admin 5 React] In Adapter View some Titels under Name are missing

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.admin#675]
Some of the adapter titels under Name are missing in Admin 5.0.2

Homematik ReGaHSS
Web
mydlink
wiffi wiffi-wz
proxmox
and some others

my browser: MS Edge
Node.js v12.22.0
NPM 6.14.11

![image](https://user-images.githubusercontent.com/22911084/114403594-3a99d000-9ba5-11eb-9998-dddccba0c0b8.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.3

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
In 5.0.4 problem in Admin Overview is still there

![grafik](https://user-images.githubusercontent.com/25422320/115286201-17e05c00-a14f-11eb-9913-831d9a255ce8.png)
![grafik](https://user-images.githubusercontent.com/25422320/115286244-2464b480-a14f-11eb-9ed9-62bbf87fb6f8.png)
![grafik](https://user-images.githubusercontent.com/25422320/115286293-33e3fd80-a14f-11eb-86a4-2d58ab1c05cc.png)
![grafik](https://user-images.githubusercontent.com/25422320/115286336-4100ec80-a14f-11eb-8ca9-f57d07cf993b.png)
....

**Comment by GermanBluefox** [comment]
It will be fixed with new js-controller 3.3

**Comment by Feuer-sturm** [comment]
Admin 5.0.13
js-controller 3.3.7

Issue is fixed :-)
