### ISSUE TITLE
[Admin 5 React] After change of "Darkmode" icons are very big 

### ISSUE THREAD

**Issue by MarkSau** [ioBroker/ioBroker.admin#676]
If I click to change the dark mode the icons of zigbee, backup etc. grows up to very big pictures

![Unbenannt](https://user-images.githubusercontent.com/22911084/114403349-00303300-9ba5-11eb-9c24-ac36cafba455.JPG)

**Comment by Apollon77** [comment]
which admin5 version?

**Comment by MarkSau** [comment]
5.0.2

**Comment by GermanBluefox** [comment]
Fixed in 5.03

**Comment by MarkSau** [comment]
@GermanBluefox I can confirm the fix
