### ISSUE TITLE
Adapter list parse error

### ISSUE THREAD

**Issue by Zentauer** [ioBroker/ioBroker.admin#677]
**Describe the bug**  
If the HomeMatic ReGaHSS adapter is installed, the Easy Admin page is empty.

**To Reproduce**  
1. Install the HomeMatic ReGaHSS Adapter
2. Go to Easy Admin

**Screenshots & Logfiles**  
[1618609281227.log](https://github.com/ioBroker/ioBroker.admin/files/6328236/1618609281227.log)
![Bildschirmfoto vom 2021-04-17 00-00-16](https://user-images.githubusercontent.com/35875079/115093366-5d681380-9f1a-11eb-9634-a33976671906.png)

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: linux

**Comment by GermanBluefox** [comment]
It is not yet implemented

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by Zentauer** [comment]
Error in 5.0.9:

![Bildschirmfoto vom 2021-04-27 16-09-08](https://user-images.githubusercontent.com/35875079/116255959-06143f80-a773-11eb-9183-c4f741a8a373.png)

**Comment by GermanBluefox** [comment]
> Error in 5.0.9:
> 
> ![Bildschirmfoto vom 2021-04-27 16-09-08](https://user-images.githubusercontent.com/35875079/116255959-06143f80-a773-11eb-9183-c4f741a8a373.png)

It is not possible. Do not call config.html directly. Call index.html

**Comment by Zentauer** [comment]
> > Error in 5.0.9:
> > ![Bildschirmfoto vom 2021-04-27 16-09-08](https://user-images.githubusercontent.com/35875079/116255959-06143f80-a773-11eb-9183-c4f741a8a373.png)
> 
> It is not possible. Do not call configs.html directly. Call index.html

![Bildschirmfoto vom 2021-04-28 00-26-28](https://user-images.githubusercontent.com/35875079/116320438-89a44f80-a7b8-11eb-983a-e2ebf780373c.png)

I clicked the icon in the top right corner.

**Comment by GermanBluefox** [comment]
It is does not work anymore in 5.0.x. It is work only in React UI
