### ISSUE TITLE
5.0.3 - titel missing

### ISSUE THREAD

**Issue by skvarel** [ioBroker/ioBroker.admin#678]
![grafik](https://user-images.githubusercontent.com/1114419/115121296-32c99980-9fb2-11eb-8554-b994a0328d0d.png)

**Comment by Apollon77** [comment]
Is that in the "old" UI or in the new one?

**Comment by skvarel** [comment]
In the 'old' UI

![grafik](https://user-images.githubusercontent.com/1114419/115134708-d0ed4c00-a012-11eb-837c-eefe6f2d4d57.png)

**Comment by skvarel** [comment]
'New' UI

Titel is Ok but description is missing

![grafik](https://user-images.githubusercontent.com/1114419/115134751-422cff00-a013-11eb-8555-7d29c38a4da0.png)

**Comment by GermanBluefox** [comment]
Could be fixed only with js-controller 3.3
