### ISSUE TITLE
Admin 5.0.2 -  Objekte Einstellungs Register öffnen sich nicht mehr

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#679]
Nach Admin Update von 4.1.2 auf 5.0.2 lassen sich die Einstellungsregister in den Objekten (siehe Screenshot) nicht mehr aufklappen.

Außerdem hat der Admin Update Prozess sich nicht wie angehakt selber neu gestartet. Nach 30 Minuten drehte immer noch der "Kreis". Ich habe dann dann die Webseite nochmal in einem anderen Browser Tab aufgemacht und da konnte man dann sehen, das dass Update durchgelaufen ist. Auf der Ursprünglichen Browser Seite wo das Update über das Adapter Menü angestoßen wurde ist der visuelle Prozess eingefroren.

![image](https://user-images.githubusercontent.com/44617472/115124724-03238d00-9fc4-11eb-9c67-a596791b7fb4.png)

![image](https://user-images.githubusercontent.com/44617472/115124707-e38c6480-9fc3-11eb-9e11-0a9a3cee91e8.png)

![image](https://user-images.githubusercontent.com/44617472/115124661-a031f600-9fc3-11eb-8114-ba2c0592fb1b.png)

**Comment by Feuer-sturm** [comment]
Mit Admin 5.0.3 kann ich die Einstellungsregister im Firefox und Chrome auf und zu klappen.

**Comment by JBSullivan** [comment]
NACHTRAG: Scheint ein Cache Problem von Chrome zu sein. Heute Morgen nach Neustart des Bedienrechner (ioB läuft headless auf einem NUC) funktioniert das Aufklappen der Register auch unter Chrome einwandfrei.
