### ISSUE TITLE
React, Log Seite weiss auf Smartphone

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.admin#680]
logs werden auf Smartphone nicht angezeigt (Weise Seite)..

MiMix2S
LinegeOS 18
edge Browser

**Comment by Feuer-sturm** [comment]
Die Protokoll Seite ist unabhängig vom Endgerät weiß unter Admin 5.0.3 mit React UI

**Comment by GermanBluefox** [comment]
Please provide browser logs. I cannot reproduce error: 
![image](https://user-images.githubusercontent.com/4582016/115144471-25152200-a04d-11eb-8bee-0c58ce3d19c9.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Does this help?
![grafik](https://user-images.githubusercontent.com/25422320/115146295-2ac33580-a056-11eb-8d14-1a977210aaa3.png)

![grafik](https://user-images.githubusercontent.com/25422320/115146311-48909a80-a056-11eb-8fc6-13f1277802a5.png)

**Comment by GermanBluefox** [comment]
Does your host have name "beeboxiobrokerMaster)" ?

**Comment by Feuer-sturm** [comment]
@GermanBluefox Hm, if i enter 
`hostname` in the console it shows:

```

proxmox@ioBrokerBETA:~$ hostname
ioBrokerBETA
```

Beebox would be a very old hostname. In my current productive ioBroker in the information menu beebox is shown as well but the real name of this host is different as well.

**Comment by Feuer-sturm** [comment]
@GermanBluefox I just changed the hostname of my proxmox container to "ioBrokerTestsystem".
After stopping iobroker I executed `sudo iobroker host this` to change the hostname for ioBroker.

Now I can see the "Protokoll" site
![grafik](https://user-images.githubusercontent.com/25422320/115150147-6d413e00-a067-11eb-81f7-7db6c88580aa.png)

**Comment by sigi2345** [comment]
Hallo, selbes Problem unter Windows:

![Screenshot (3670)](https://user-images.githubusercontent.com/41079106/115152690-5e13bd80-a072-11eb-9b72-ae9da1f5f254.png)

**Comment by Feuer-sturm** [comment]
@sigi2345 Is the host name of your system equal to the host name in ioBroker. In my case they were different.

**Comment by Schimi1983** [comment]
die neue version funktioniert... nur noch die "Objecte"-Seite ist weiss... der rest scheint zu funktioieren

**Comment by GermanBluefox** [comment]
> die neue version funktioniert... nur noch die "Objecte"-Seite ist weiss... der rest scheint zu funktioieren

Und was sieht man da in der Browser Konsole?

**Comment by Schimi1983** [comment]
nach dem Update heute morgen (5.0.4 glaube ich) geht's nun da auch...

Also, alles im Lot :-)
