### ISSUE TITLE
Admin 5.0.3 - Deleting of objects "Nur eins" and "Alle" is reversed

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#681]
Admin version 5.0.3
js-controller 3.2.16

Functionality of buttons "Nur eins" and "Alle" are reversed
If I want to delete a "folder" and all contained objects and I confirm with "Alle" only one object will be deleted
![image](https://user-images.githubusercontent.com/25422320/115127146-89e06600-9fd4-11eb-857b-d5fdb3105f48.png)

**Comment by GermanBluefox** [comment]
Is it Admin4 or Admin5 interface? If Admin4, please validate it in Admin5 (ReactUI)

**Comment by Feuer-sturm** [comment]
@GermanBluefox This issue is about admin4.

For admin5 I created the Ticket https://github.com/ioBroker/ioBroker.admin/issues/705

**Comment by Apollon77** [comment]
Then I wopuld close for admin4
