### ISSUE TITLE
Admin 5.0.3 - Deleting of subordinate objects if main object has no type

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#682]
Admin 5.0.3

If an object has no type and I want to delte this object I get the following screen:
![image](https://user-images.githubusercontent.com/25422320/115127283-9fa25b00-9fd5-11eb-822b-e7383ea10e4a.png)

![image](https://user-images.githubusercontent.com/25422320/115127301-c6f92800-9fd5-11eb-8ddb-33ee6dabe582.png)

If I press "OK" only one of the sub-objects will be deleted and not everything.

**Comment by GermanBluefox** [comment]
Interface is from Admin4... Can we concentrate to finish admin5? Admin4 will not be fixed any more

**Comment by Apollon77** [comment]
Then reopen please if admin5 too
