### ISSUE TITLE
Admin 5.0.3 - React UI - Menü Adapter Aktualisierungen stimmt nicht mit realer Anzahl überein

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#684]
Admin 5.0.3
js-controller 3.2.16

Die Anzahl der zu aktualisierenden Adapter links im Menü stimmt nicht mit der tatsächlichen Anzahl überein:

![grafik](https://user-images.githubusercontent.com/25422320/115129172-e9923d80-9fe3-11eb-9d07-9d608b0609cc.png)

**Comment by JBSullivan** [comment]
DITO, gleich mit Systemparametern

![image](https://user-images.githubusercontent.com/44617472/115136946-6bee2200-a023-11eb-9c4a-613004711469.png)

**Comment by GermanBluefox** [comment]
PLease retest 5.0.6

**Comment by Feuer-sturm** [comment]
With 5.0.6 bug is fixed :-)
