### ISSUE TITLE
Admin 5.0.3 - React UI - VIS Runtime Button fehlt in Übersicht und Icons nicht anklickbar

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#685]
Admin 5.0.3

In der Übersicht mit den Kacheln fehlt das Icon für die VIS Runtine, so dass man gleich zu seiner VIS kommt.
![grafik](https://user-images.githubusercontent.com/25422320/115129242-6b826680-9fe4-11eb-8ff9-8b87e958c587.png)

Ebenfalls hat es keinen Effekt, wenn man auf die großen Kacheln klickt. Man muss auf den kleinen Link klicken, damit man zum Inhalt der Kachel springt.

**Comment by JBSullivan** [comment]
Vielleicht auch ein Cache Problem (siehe Kommentar - https://github.com/ioBroker/ioBroker.admin/issues/679 )? Bei mir ist der Button HEUTE vorhanden und läßt sich auch anklicken. Gestern habe ich ehrlich gesagt nicht darauf geachtet.

**Comment by GermanBluefox** [comment]
Will be fixed with new vis version and admin 5.0.9

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
With Admin 5.0.11 and VIS 1.3.9 both problems (Missing VIS runtime and no reaction by clicking on the icons)  are still available.

**Comment by GermanBluefox** [comment]
By me works:
![image](https://user-images.githubusercontent.com/4582016/117219332-593a6200-ae05-11eb-918a-5fab7b8ce9fe.png)

**Comment by Feuer-sturm** [comment]
Admin 5.0.18

@GermanBluefox 
On my overview VIS runtime is still missing. Clearing of the browser cache after Admin 5.0.18 update did not have any effect.

Missing VIS runtime -> still missing
"no reaction by clicking on the icons" -> fixed
![image](https://user-images.githubusercontent.com/25422320/117515782-8ae33280-af97-11eb-9cc7-a8296146e40c.png)

**Comment by Matt77CHE** [comment]
Bei mir ist die Übersicht auch seit längerem leer - weder vis noch flot oder was ich sonst noch hatte wird angezeigt...

**Comment by GermanBluefox** [comment]
Please use the latest vis

**Comment by Feuer-sturm** [comment]
Admin 5.1.3
VIS 1.3.10

No change with current Admin and VIS version. VIS runtime icon is still missing

**Comment by Feuer-sturm** [comment]
Admin 6.2.16

VIS Runtime button is available -> ok

![grafik](https://user-images.githubusercontent.com/25422320/185492753-7f70bed8-5ae6-48bc-b4c0-4be071c6f862.png)


@GermanBluefox Is there a reason why the bar is not grey? (I know it was coloured in the past as well, but why?)
