### ISSUE TITLE
iQontrol ist broken since last update - Please help by fixing socket.js

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#686]
Hi @GermanBluefox 

since update to admin 5.0.3 iQontrol is broken. Something happend to socket.io.

I worked half the night on it. What i got so far, is that it is starting again, by using the inbuilt socket of admin (instead of serv.con from the web-adapter`s socket).

But there are two commands for my file-browser missing:
renameFile and mkDir.

Am i right that these two commands are missing here:
https://github.com/ioBroker/ioBroker.admin/blob/072da76e81271454ed8a819a7fdee0d2683ff9be/lib/socket.js#L948

Can you add these two commands or give me any hint how to archieve renaming files and adding dirs?

Many thanks,
  Sebastian

**Comment by GermanBluefox** [comment]
socket.io was replaced by pure socket communication.
I am a bit surprised about renameFile. Was it implemented?? It is not even in adapter.js

**Comment by Apollon77** [comment]
So an adjust the conn.js from iqontrol to switch to pure sockets should do the trick, or? ;-)

@sbormann sorry to not have communicated that earlier. I also scanned through all adapters, your one seems the only one which uses socketio directly in admin page

**Comment by sbormann** [comment]
Hi, 
That was, what i was doing this night :) I removed conn.js and switched to pure socket.
But the problem is, in pure socket these two functions are missing: rename and mkdir.
That was the reason i formerly used conn.js instead of pure socket.

The question is: Can you implement rename and mkdir in adapter.js and socket.js?

Many thanks

**Comment by Apollon77** [comment]
hm ... and how that was working before in socketio? https://github.com/ioBroker/ioBroker.admin/issues/423 is still open?

**Comment by sbormann** [comment]
#423 is of the same topic, yes. It is partially solved. With your hints i got deleteFile working.

Meanwhile i also got a workaround for mkDir (i create a temp-file, that also creates the folder-structure it is in and afterwards i delete the tempfile).

But rename is still not solved for pure adapter socket.

In socket.io rename was working fine with this syntax:
````servConn.renameFile(oldPath, newPath, function(err){ if (callback) callback(err); });````

**Comment by Apollon77** [comment]
@GermanBluefox has implemented renameFile in next update

**Comment by sbormann** [comment]
Great! Many thanks for that!!

**Comment by sbormann** [comment]
Confirmed, works with the latest commit. Closing this and again many thanks for the quick fix! :)
