### ISSUE TITLE
Admin 5.0.3 - React UI - Tooltip fehlt

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#687]
![grafik](https://user-images.githubusercontent.com/6681528/115137471-a0afa880-a026-11eb-97e1-8fd44a84aa5f.png)

![grafik](https://user-images.githubusercontent.com/6681528/115137751-2c760480-a028-11eb-92f2-36dee535229e.png)

![grafik](https://user-images.githubusercontent.com/6681528/115137765-52030e00-a028-11eb-9102-bd4f7b79a03d.png)

hier fehlt der Tooltip

**Comment by GermanBluefox** [comment]
Please check 5.0.6

**Comment by Feuer-sturm** [comment]
All marked icons have a tooltip in 5.0.6
