### ISSUE TITLE
Admin 5.0.3 - React UI - update der Version nach aktualisierung

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#688]
![grafik](https://user-images.githubusercontent.com/6681528/115137553-0bf97a80-a027-11eb-8b3d-c68edd1489fa.png)

nach der Aktualisierung wird die Version nicht aktualisiert.. ich muss F5 drücken dann seh ich dass es aktualisiert wurde

**Comment by Feuer-sturm** [comment]
Wenn man in der Ansicht "Adapter mit Aktualisierung" anzeigen ist, dann muss man nach einem erfolgreichen Adapter Update ebenfalls F5 drücken, damit der Adapter nicht mehr in dieser Ansicht auftaucht.

Erwartung wäre auch hier, dass der Adapter nach der Aktualisierung erfolgreich ausgeblendet wird.

![grafik](https://user-images.githubusercontent.com/25422320/115452839-3b72d780-a21f-11eb-8a0f-86ddf5d2d365.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.7 (not yet released)

**Comment by Feuer-sturm** [comment]
Both topics are fixed with 5.0.7
Can be closed @GermanBluefox @Apollon77
