### ISSUE TITLE
Admin 5.0.3 - React UI - Log-Stufe aktualisieren

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#690]
![grafik](https://user-images.githubusercontent.com/6681528/115138708-07849000-a02e-11eb-8c6e-f042da7e65d0.png)

nach Ändern der Log-Stufe wird diese nicht aktualisiert

**Comment by GermanBluefox** [comment]
Please check 5.0.6

**Comment by Feuer-sturm** [comment]
Looks good
![grafik](https://user-images.githubusercontent.com/25422320/115779153-e5856780-a3b7-11eb-8cfa-a9676421ec75.png)
