### ISSUE TITLE
Admin 5.0.3 - React UI - dark mode Text schlecht lesbar

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#691]
![grafik](https://user-images.githubusercontent.com/6681528/115138826-c476ec80-a02e-11eb-8798-df76bcf13bc5.png)

Text ist schlecht lesbar

**Comment by Apollon77** [comment]
Question is if the adapter UI explicitely writes black here??? SO is this an adapter issue or Admin?

**Comment by Apollon77** [comment]
@arteck please check what Zigbee contains here

**Comment by GermanBluefox** [comment]
Background will be always white in next version

**Comment by GermanBluefox** [comment]
Please verify
