### ISSUE TITLE
Admin 5.0.3 - React UI - error  "Cannot read property 'object' of undefined"

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#693]
https://user-images.githubusercontent.com/6681528/115139167-bcb84780-a030-11eb-93bf-e6b8913699df.mp4

Objectliste ist nicht mehr aufrufbar

doppelklick auf den Namen : hier alte sicht
![grafik](https://user-images.githubusercontent.com/6681528/115139283-5849b800-a031-11eb-9e66-35535e1efdef.png)

**Comment by GermanBluefox** [comment]
Please verify 5.0.5
