### ISSUE TITLE
Admin 5.0.3 - React UI - Update from git only add new Instance

### ISSUE THREAD

**Issue by MeisterTR** [ioBroker/ioBroker.admin#694]
![2021-04-18_10h58_49](https://user-images.githubusercontent.com/6328382/115140077-b7113080-a035-11eb-836e-00d5c0aa3a96.png)

**Comment by GermanBluefox** [comment]
Sorry. Problem is unclear. Does not run?

**Comment by MeisterTR** [comment]
When i want to install the Version from git and click on install it just add a New Instanz and dont install the latest Version from git, also with custom link it run in errors.

**Comment by GermanBluefox** [comment]
Please retest with 5.0.6
