### ISSUE TITLE
Admin 5.0.3 - React UI - Admin Übersicht nur zwei Kacheln am Smartphone sichtbar 

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#695]
Auf einem Samsung S9 werden nur zwei Kacheln in der Übersicht angezeigt. Man kann auch nicht scrollen um die restlichen Kacheln  welche am PC sichtbar sind zu erreichen. 

![Screenshot_20210418-112657_Samsung Internet](https://user-images.githubusercontent.com/25422320/115140807-7a473880-a039-11eb-9ec3-6e1dbedb32d1.jpg)

Admin 5.0.3 und react UI aktiv

**Comment by GermanBluefox** [comment]
Fixed in next version

**Comment by Feuer-sturm** [comment]
Checked with 5.0.4 - Everything is fine
@Apollon77 issue can be closed.

**Comment by GermanBluefox** [comment]
@Feuer-sturm I think, you can close the issue yourself in the future, because you are the issuer.
