### ISSUE TITLE
Admin 5.0.3 - React UI - Static column in objects overview cause visibility problems

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#698]
Admin 5.0.3
js-controller 3.2.16

The column width of the objects is now fixed and you can no longer enlarge it by dragging it. As a result, the names are cut off and the full name cannot be read at first glance. This causes as well that the icon for copy the path of the object lays over the name of the object.
Here I would like to be able to manually enlarge the individual columns again.

The new folder symbols look chic, but with more complex structures you have a lot of dead space on the left.

![grafik](https://user-images.githubusercontent.com/25422320/115145977-d23f6880-a054-11eb-9f70-1ecf58e72edf.png)

On the mobile phone it is even hard to guess what the name of the object could be. Here it looks like this:
![grafik](https://user-images.githubusercontent.com/25422320/115146150-91941f00-a055-11eb-89e9-0af8c540fe9a.png)

**Comment by GermanBluefox** [comment]
You can set the width yourself now. 
![image](https://user-images.githubusercontent.com/4582016/115148080-4af6f280-a05e-11eb-9ca8-9ba60d5e4b8c.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox Yes I found this feature. It would be great to resize the colum with the mouse :-)

If I activate 2 colums in the object overview on my mobile phone (e.g. ID and Name) it is not possible to slide horizontal to see both columns. Is this possible?

**Comment by sjfm-design** [comment]
title row will not corespond with data in FF and Chrome in personal settings.
![grafik](https://user-images.githubusercontent.com/30467409/115984685-b2ee9100-a5a8-11eb-9e01-4314266ef511.png)
![grafik](https://user-images.githubusercontent.com/30467409/115984691-bc77f900-a5a8-11eb-89fe-66c43de8c54d.png)

**Comment by Feuer-sturm** [comment]
Admin 5.0.12
js-controller 3.3.5

Folder structure is now better so that there is not so much white space.

Title row are the same in Firefox and Chrome by using individuel settings for the coloums.
![grafik](https://user-images.githubusercontent.com/25422320/116821872-0601ae80-ab7c-11eb-88db-0044ab69920f.png)

**Comment by GermanBluefox** [comment]
The layout was engineered a bit in 5.0.17. Please check

**Comment by Feuer-sturm** [comment]
@GermanBluefox Can you please give a little hint which part of the layout was updated a bit and shall be checked?

**Comment by GermanBluefox** [comment]
In smaller screens the auto layout was tuned up. Less 340, less 800, less 1200...

**Comment by Feuer-sturm** [comment]
From my point of view this issue is fixed. Checked   with admin 5.0.24
