### ISSUE TITLE
Only show "Expert mode" (and expert settings - the red wrench) on admon-own pages

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#700]
The header contains the "expert mode" icon and the "red wrench icon" on all pages in the header. This should only be shown on pages where it has an effect, and especially NOT on Admin Tabs from other adapters.

I noticed that while on "Javsscript" tab and trying to enable expert mode ... i clicked wrongly in the header ... but for Javsscript adapter it is somewhere else. That else confuses people

**Comment by GermanBluefox** [comment]
Adapters will not be able to control theme and expert mode. Because Admin4 had not this functionality it was temporary implemented in JS.

**Comment by Apollon77** [comment]
ahhh ok, so it will be used then also for the other adapters. good
