### ISSUE TITLE
Button data point is no longer displayed as a button

### ISSUE THREAD

**Issue by WaJoWi** [ioBroker/ioBroker.admin#701]
In devices, a button data point is no longer displayed as a button, but as logical. Even if one has deactivated the expert mode in the view.

Old:
![button](https://user-images.githubusercontent.com/24896600/115147200-239e2680-a05a-11eb-9a76-f1263c2cf43b.png)

New:
![button_neu](https://user-images.githubusercontent.com/24896600/115147202-26008080-a05a-11eb-9094-0bf1c728ed07.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.5

**Comment by Feuer-sturm** [comment]
@WaJoWi @Apollon77 
Button is available and it works :-)
