### ISSUE TITLE
Can not install from Github

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.admin#702]
When i try to install a Adapter from Github i get an Error:
`$ iobroker url https://github.com/xXBJXx/ioBroker.fully-tablet-control auto --host ioBroker

install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b

NPM version: 6.14.12

npm install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b --loglevel error --prefix "/opt/iobroker" (System call)

host.ioBroker Cannot install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b: 0

ERROR: Process exited with code 25`
I tried different writing and different Adapters with always the same result:
https://github.com/xXBJXx/ioBroker.fully-tablet-control
https://github.com/xXBJXx/ioBroker.fully-tablet-control.git (original Link form Git)
https://github.com/klein0r/ioBroker.birthdays.git
https://github.com/DrozmotiX/ioBroker.sourceanalytix.git

Log:
`

host.ioBroker |   | 2021-04-18 17:24:33.658 | info | iobroker exit 25
-- | -- | -- | -- | --
host.ioBroker |   | 2021-04-18 17:24:32.634 | error | iobroker host.ioBroker Cannot install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b: 0
host.ioBroker |   | 2021-04-18 17:23:13.839 | info | iobroker npm install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBroker |   | 2021-04-18 17:23:13.835 | info | iobroker NPM version: 6.14.12
host.ioBroker |   | 2021-04-18 17:23:13.293 | info | iobroker install xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b
host.ioBroker |   | 2021-04-18 17:23:10.915 | info | iobroker url https://github.com/xXBJXx/ioBroker.fully-tablet-control auto --host ioBroker

`

**Comment by Apollon77** [comment]
WHich js-controller ist installed?

Can you run `tall xXBJXx/ioBroker.fully-tablet-control#4f22742cc372acfae8875ead2808d57cf7b2663b --prefix "/opt/iobroker"` please on shell normally?

ANd PS: all locations with ".git" at the end are wrong, but https://github.com/xXBJXx/ioBroker.fully-tablet-control should work

**Comment by Apollon77** [comment]
For me manually on CLI also `iobroker url https://github.com/xXBJXx/ioBroker.fully-tablet-control auto --host ioBroker` works. Can you pelase try that too?

**Comment by Chaot1** [comment]
Sorry, geht in englisch jetzt zu schwer:
Installation über die Konsole hat funktioniert.

Ich weiß das die Endung ".git" eigentlich verkehrt ist. Aber wenn ich den Link aus Git in die Zwischenablage kopiere dann ist die Endung automatisch dran. Das hatte bisher auch immer funktioniert.

https://github.com/xXBJXx/ioBroker.fully-tablet-control habe ich mehrfach versucht - geht nicht.

**Comment by GermanBluefox** [comment]
Das hat mit admin nichts zu tun
