### ISSUE TITLE
Admin 5.0.2 - Zwei Admin Instanzen = kein Zugriff mehr auf die Instanz Verwaltung

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#703]
Ich weiß nicht ob ich es überlesen habe oder ob zu dem Issue noch keiner etwas auf gemacht hat.

Wenn man zwei Instanzen vom Admin 5.0.2 erstellt kommt man anschließen nicht mehr in die Instanzverwaltung hinein. Man landet dann genau wie beim LOG/Protokoll Button auf einer leeren Seite

![image](https://user-images.githubusercontent.com/44617472/115152761-c4004500-a072-11eb-81bc-dfa9ce2fa366.png)

![image](https://user-images.githubusercontent.com/44617472/115152768-d1b5ca80-a072-11eb-8535-798c4aa3702b.png)

![image](https://user-images.githubusercontent.com/44617472/115152784-e8f4b800-a072-11eb-8ca4-85e08ff81d06.png)

Sammlung im ioB Forum zu allem was mir so zum Admin 5.0.2  aufgefallen ist ;)
https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/10?_=1618762623199

**Comment by GermanBluefox** [comment]
Please install 5.0.5 tomorrow
