### ISSUE TITLE
Admin 5.0.3 - React UI - Deleting of one item from a channel does not work

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#705]
Admin 5.0.03

Create a channel with some datapoints and then press the delete button from the channel
![grafik](https://user-images.githubusercontent.com/25422320/115160571-38e67580-a099-11eb-8aba-7e6990563d10.png)

Confirm with "delete one item"
![grafik](https://user-images.githubusercontent.com/25422320/115160595-53205380-a099-11eb-94a4-2e3b3b3763ad.png)

What will happen:
Name and type of the channel will be deleted but no item
![grafik](https://user-images.githubusercontent.com/25422320/115160612-6af7d780-a099-11eb-91ca-46bdf6aa623a.png)

I had expected that a dialog will pop up and that I can select one of the datapoints of the channel

**Comment by GermanBluefox** [comment]
Works as designed. I don't understand what was expected.
Should the children then hang in the air???

**Comment by Feuer-sturm** [comment]
@GermanBluefox Perhaps there is a misunderstanding on my site of the feature "Delete on item". I had expected that a window will pop up where I can select (using my example from the screenshot) : aasdf, asdfasdf, tst1

If I press the button "Delete on item"  the name and the device of the channel "temp5" will be deleted and there is no pen any more avilable in the last coloum settings. 
What can I do from your point of view with "temp5" now?

**Comment by GermanBluefox** [comment]
Ich verstehe nicht. Deutsch?

**Comment by DocGame69** [comment]
Bei mir das selbe...
Seit dem Update kann ich in der Objekte-Übersicht nur noch einzelne States löschen. Wenn ich auf den Channel gehe und gesamt löschen will. geht das nicht (Admin 5.0.5 React UI nicht angewählt). Webb man Geräte mit mehr als 100 States löschen will (zb. WLED) wird man verrückt. Das löschen eines gesamten Channels war vorher kein Problem.

**Comment by Feuer-sturm** [comment]
Hallo @GermanBluefox, gerne auch auf Deutsch :-)
Wenn ich den channel "Temp5" auswählen und dann auf den Mülleimer klicke kommt das Popup in welchem ich "Delete one item" auswähle. 
Ich hätte jetzt erwartet, dass ich in  einem neuen Popup die Datenpunkte, welche unter "Temp5" zur Auswahl angeboten bekommen, von denen ich einen löschen kann.

Wenn man den Button drückt, dann wird kein Untergeordneter Datenpunkt von "Temp5" gelöscht sondern es verschwindet nur in der Zeile vom Channel "Temp5" der Inhalt von der Spalte "Name" und "Typ". Zeitgleich ist in der Zeile von "Temp5" auch der Stift rechts außen nicht mehr vorhanden.  Ich meine bis zur Version 5.0.4 konnte man dann auch keine neuen Datenpunkte unter "Temp5" über das [+] Symbol mehr hinzufügen.

Mit der Version 5.0.5 kann ich nach der Aktion "Delete one item" den Channel nicht mehr markieren bzw. den Kanal zuklappen. Das Icon vom Ordner bleibt dauerhaft geöffnet.
Man kann auch keine neuen Datenpunkte unterhalb des Kanals mehr hinzufügen, das das [+} ausgegraut ist.
![grafik](https://user-images.githubusercontent.com/25422320/115450013-b0441280-a21b-11eb-9a73-f6656ad172a7.png)

**Comment by Feuer-sturm** [comment]
@DocGame69 Passt das was du siehst zu diesem Ticket https://github.com/ioBroker/ioBroker.admin/issues/682?

**Comment by GermanBluefox** [comment]
Please test 5.0.11/12 together with js-controller 3.3.x

**Comment by Feuer-sturm** [comment]
Admin 5.0.11 (version 5.0.12 is not available yet if I call iobroker update on the console)
js-controller 3.3.5

@GermanBluefox 
I did the same steps which I described here https://github.com/ioBroker/ioBroker.admin/issues/705#issue-860763541
and it is the same result ( Name and type of the channel will be deleted but no item)

What shall happen from your point of view or what does it look like on your system if you select the channel and confirm  "delete on item"?


During testing of this issue it happens one time that the page "Objects" was complete white and this was in the browser console:
![grafik](https://user-images.githubusercontent.com/25422320/116791615-c96e7e00-aabb-11eb-98ec-f85a580d1d89.png)

**Comment by Apollon77** [comment]
These errors come from a browser plugin

**Comment by Feuer-sturm** [comment]
@Apollon77 Ok, Thanks. The mentioned IP is the adress from my proxmox server. I don't know what happend there.

@GermanBluefox With Admin 5.0.12 it is the same behavior as I described it here https://github.com/ioBroker/ioBroker.admin/issues/705#issuecomment-830676116

**Comment by GermanBluefox** [comment]
> @Apollon77 Ok, Thanks. The mentioned IP is the adress from my proxmox server. I don't know what happend there.
> 
> @GermanBluefox With Admin 5.0.12 it is the same behavior as I described it here [#705 (comment)](https://github.com/ioBroker/ioBroker.admin/issues/705#issuecomment-830676116)

The main ingredient is js-controller 3.3.x. Did you installed it?

**Comment by Feuer-sturm** [comment]
@GermanBluefox Yes. Currently I am using  js-controller 3.3.5

**Comment by GermanBluefox** [comment]
> @GermanBluefox Yes. Currently I am using js-controller 3.3.5

OK. So when you click on "Delete one item" only one selected item (e.g.  channel) will be deleted. If you click on "Delete with children" all sub item and the item itself will be deleted. 

> Ich hätte jetzt erwartet, dass ich in einem neuen Popup die Datenpunkte, welche unter "Temp5" zur Auswahl angeboten bekommen, von denen ich einen löschen kann.

Nein. Es wird nur das selektiertes Objekt gelöscht. So war auch in Admin4

**Comment by Apollon77** [comment]
Ok, dann sollten wir ggf den text der Buttons anpassen:
"Delete selected item"/"Nur ausgewählten Eintrag löschen" ist dann vllt besser

**Comment by Apollon77** [comment]
Or we prevent to delete a "non state" (folder, channel, device) as long as there is an other entry in it ... so only delete a channel/device/folder when empty OR delete with all items. Maybe this is more clear?

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 This posting https://github.com/ioBroker/ioBroker.admin/issues/705#issuecomment-830844725 from Apollon77 would fit to my expectation.

**Comment by GermanBluefox** [comment]
> Or we prevent to delete a "non state" (folder, channel, device) as long as there is an other entry in it ... so only delete a channel/device/folder when empty OR delete with all items. Maybe this is more clear?

No
