### ISSUE TITLE
Admin 5.0.4 - React UI - Adapter changelog display is not up to date

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#706]
![image](https://user-images.githubusercontent.com/19333515/115187953-76242500-a0e4-11eb-90cb-6b2cca720ef7.png)

**Comment by GermanBluefox** [comment]
The readme is taken from official web site. The information there could be up to 3 days old.

**Comment by o0shojo0o** [comment]
Ah thanks for the clarification!
