### ISSUE TITLE
Admin 5.0.4 - React UI - Installed instances, are always three

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#707]
With all adapters installed.

![image](https://user-images.githubusercontent.com/19333515/115200390-762c2100-a0f4-11eb-88c0-30ae3699dd6d.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.5

**Comment by o0shojo0o** [comment]
i have checked it, it works now :)
