### ISSUE TITLE
Admin 5.0.4 - React UI - Three updates are always displayed, but none is available

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#708]
![image](https://user-images.githubusercontent.com/19333515/115200662-bf7c7080-a0f4-11eb-81a8-b5cad0cca02d.png)

**Comment by Apollon77** [comment]
duplicate #684 ?! If yes please close

**Comment by o0shojo0o** [comment]
Oh sorry, I had overlooked!

**Comment by Apollon77** [comment]
np, thx for checking!
