### ISSUE TITLE
Admin 5.0.3 - React UI - Yahka crashes

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.admin#711]
Node 14.15.5

After Installing Admin 5.0.3, the instances tab is empty and the spinner keeps turning
Yahka shows no errors in log, but all yahka-devices in HomeKit are “not responding”

Downgrade Admin to v4 restored the instances tab, but yahka is not coming back (HomeKit still “not responding). Had to delete bridge from HomeKit and configure all again ….

**Comment by Apollon77** [comment]
The functionaliyt of yahka should not have anything to do with Admin ... Is iobroker log showing anything?
Browser konsole showign any errors?

**Comment by eric2905** [comment]
> The functionaliyt of yahka should not have anything to do with Admin ... Is iobroker log showing anything?
> Browser konsole showign any errors?

Yahia-Adapter is green, no error entries in log ... everything looks fine in ioBroker.
Only every State, etc. from ioBroker is "not responding" in HomeKit. Needed to delete the bridge in HomeKit and had to add it new (incl. complete new config in HomeKit).

Just testet it with admin 5.0.5 ... everything is working fine now.

**Comment by Apollon77** [comment]
Ok, so we close here?
