### ISSUE TITLE
v5.0.4. Can´t log in (using "name" and "password")

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.admin#712]
Not possible to log in while using name and password.
Comes an empty site with: 

`Diese Seite funktioniert nicht
192.168.178.149 hat keine Daten gesendet.
ERR_EMPTY_RESPONSE`

Unfortunately I do not have any logs because of restoring my system afterward.

**Comment by Apollon77** [comment]
Please check 5.0.5
