### ISSUE TITLE
reverse proxy don't work with 5.x.x

### ISSUE THREAD

**Issue by ManuelW77** [ioBroker/ioBroker.admin#713]
**Describe the bug**  
With iobBroker.admin 5.x i can't reach the web interface over nginx reverseproxy anymore. 
I downgradet to 4.1.1 and it works fine again.

**Comment by GermanBluefox** [comment]
Is it not the issue of nginx?

**Comment by Apollon77** [comment]
@ManuelW77 What exactly is not working? One bg change was that Admin4 used socket.io and Admin5 now use plain websockets ...maybe the reverse proxy needs special confoguration?

**Comment by GermanBluefox** [comment]
Please retest 5.0.6. It works by me:
![image](https://user-images.githubusercontent.com/4582016/115697878-47b47d00-a364-11eb-8020-016fd857b26d.png)

**Comment by ManuelW77** [comment]
Hmm, can you give me your nginx config for this? If i got directly to the server and port it works, but over reverse proxy it don't.

**Comment by darkiop** [comment]
HI. I have described a similar incident here in the forum. in my case via the reverse proxy of a Synology Disk Station.

https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/243?_=1619679225686#

**Comment by Apollon77** [comment]
Please show your reverse proxy config. re Upgrade headers and such set/passed through correctly?

I think socketio (Admin <5) had some fallbacks to "long polling approaches" included when no websocket connection was possible ... this fallback is now not existing any longer.

Like adding something like this to nginx config:

```
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
```

In Synology there are additional settings where you can also add them by selecing "websockets"

Could it that be?

**Comment by darkiop** [comment]
On the part of DSM, the following setting was sufficient: 

![grafik](https://user-images.githubusercontent.com/205119/116523631-b9497980-a8d6-11eb-8cfa-911596c29067.png)

Access now works via the RP

**Comment by Apollon77** [comment]
Then this is the main change required on the config of the proxy. Because the long polling from socket.io is no longer included.
@GermanBluefox maybe add it to the admin readme? (same later for web I expect and such)

**Comment by GermanBluefox** [comment]
Sorry, but I think it is self-evident, that people must threat web-sockets in reverse proxy?

**Comment by Apollon77** [comment]
Maybe we should add as a note to admin readme? :-) (because how people should know) ;-)

**Comment by GermanBluefox** [comment]
> Maybe we should add as a note to admin readme? :-) (because how people should know) ;-)

Because if you now how to setup reverse proxy, you must now what the websocket is and that admin and all modern dynamic GUIs use it today!

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.admin#reverse-proxy
