### ISSUE TITLE
Please added border-radius und box-shadow for Admin-Tabs without react

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#714]
Today I tried to adapt the css from Backitup to admin react and unfortunately could not implement everything.

box-shadow and border-radius are overwritten.
For the design of the admin tabs, which are currently not using react, it would be great if admin would set this directly.

Here is an example of what it could look like.

Original in the admin:
![image](https://user-images.githubusercontent.com/39792461/115254545-bcea3d00-a12d-11eb-8a57-d71714bb07c9.png)

Modified manually in the browser:
![image](https://user-images.githubusercontent.com/39792461/115254762-f327bc80-a12d-11eb-9b85-77e7a53c96a1.png)

**Comment by GermanBluefox** [comment]
What I see on these 2 pictures (find 10 differences) only border is added on the second picture.
Do you mean border and border-radius of iframe?

**Comment by simatec** [comment]
Exactly ... I mean the border with border-radius.  
Here it would be great if the AdminTab has the same style as the other tabs, even for adapters that are not yet written in react.

I also noticed that the AdminTab of the body does not use all colors when changing colors in the Admin.  I think it was with the color style "blue"

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by simatec** [comment]
In version 5.0.9, no border radius and no box shadow are set in the iframe.
However, with version 5.0.9 there was also the problem that the background is permanently white, even if the theme is changed in the admin. Here the fixed background appears to be highlighted in white in the iframe (see screenshot)

![image](https://user-images.githubusercontent.com/39792461/116280022-8e510f80-a788-11eb-819f-4cc8fc4e7f24.png)


The border radius and box shadow visible in the screenshot are currently set directly from the Backitup tab.
It would be nice to have a uniform style for all tabs.
So I could then also remove the border radius and no boxing shadow in the Backitup tab

**Comment by simatec** [comment]
In which file is the style for the AdminTab exactly defined? I would then test the whole live and create a PR. Just couldn't find it in the Github so far

**Comment by GermanBluefox** [comment]
The background is always white. If the config want to support dark/light it must overwrite the background itself.
The Problem was, that some configs are shown with invalid colors and it is easier to make a background white so the users could see at least all settings

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/116294263-11c62d00-a798-11eb-976e-5a22b0f773f5.png)
This is 5.0.9 (borderRadius is 3 in 5.0.10)

https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/tabs/Instances.js#L110

**Comment by simatec** [comment]
ahhh I think we had and galsch understood.  you thought it was about the configs in the instances and I was talking about the adminTab.  😉
But I've already found the place in the code and would do a PR there.

https://github.com/ioBroker/ioBroker.admin/blob/f02ef7dad77f2782efbd160caa5ea764b3ddae42/src-rx/src/tabs/CustomTab.js#L18

**Comment by GermanBluefox** [comment]
@simatec will you make a PR?

**Comment by GermanBluefox** [comment]
Added in 5.0.17
