### ISSUE TITLE
Make tiers configurable in expert mode

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.admin#715]
Power users should be able to change the Tiers. `common.tier` attribute of io-package.json. Tier has to be an integer between 1 and 3. If no value is set (e.g for most adapters by default right now) we should write "default" as placeholder

Read about it here: https://github.com/ioBroker/ioBroker.js-controller#tiers-start-instances-in-an-ordered-manner

**Comment by GermanBluefox** [comment]
What the f.. is tier???

**Comment by Apollon77** [comment]
Both Instances View:
Add tier selection as dialog with infotext: "Tiers define the order of adapters when the 
    system starts.". Tiers: "1: Logic adapters", "2: Data provider adapters", "3: Other adapters". If 
    common.tier is not 1 or 2 display as 3

**Comment by GermanBluefox** [comment]
Please retest 5.0.6. It must be fixed there

**Comment by Feuer-sturm** [comment]
Tier level is available:

![grafik](https://user-images.githubusercontent.com/25422320/115776558-8d009b00-a3b4-11eb-9122-6b42578962bb.png)

Currently all adapters have level 3

Will the most important adapters be pre-configured by the core developers to the specific level?

**Comment by foxriver76** [comment]
Admin is always first, no matter of tiers. For now, the behavior will stay the same as now until tiers are configured. And without new controller tiers won’t do anything ;-)

Von meinem iPhone gesendet

**Comment by Apollon77** [comment]
> Will the most important adapters be pre-configured by the core developers to the specific level?

Yes also this will happen with adapter updates
