### ISSUE TITLE
Admin 5.0.5 - React UI -Tab "Instanzen" lädt ewig

### ISSUE THREAD

**Issue by JohGrei** [ioBroker/ioBroker.admin#716]
Ubuntu VM unter Proxmox
Browser: EDGE
js-controller: 3.2.16
Node: 12.22.1
NPM: 6.14.12
Alle Adapter in Beta Zweig aktuell

Nach Klick auf Instanzen wird rechte Seite leer, der Ladebalken unterhalb des Headers läuft und lädt ewig. Leider auch keine Fehlermeldung in der Webconsole.

![image](https://user-images.githubusercontent.com/41279608/115339599-6587b380-a1a5-11eb-8dee-549d5d6b9ef8.png)

**Comment by amg666** [comment]
Bei mir gleiches Verhalten. alle anderen Menupunkte funktionieren, 
Debian10 unter Proxmox
Browser Firefox und Chrome getestet
Node.js: v14.16.1
NPM: 6.14.12

**Comment by muhagl** [comment]
Ebenfalls bei mir:
Debian 10
Browser Firefox//Edge/Chrome
Node.js: v12.22.1
NPM: 6.14.12
Alles aktuell

**Comment by Ilovegym66** [comment]
Hier mal ein Screenshot von der Browserkonsole, CentOS8, Frisch installierter Firefox. ( Konquerer geht gar nicht, aber das verlangt auch keiner :-))) 
Hier wird irgendwie ne alte Websocket 0.2.1 aufgerufen, liegts daran???
![grafik](https://user-images.githubusercontent.com/36229898/115962774-32368300-a51d-11eb-9715-72ab8710ed6c.png)

![grafik](https://user-images.githubusercontent.com/36229898/115962698-e7b50680-a51c-11eb-8765-22b124572fdb.png)

**Comment by GermanBluefox** [comment]
> Hier mal ein Screenshot von der Browserkonsole, CentOS8, Frisch installierter Firefox. ( Konquerer geht gar nicht, aber das verlangt auch keiner :-)))
> Hier wird irgendwie ne alte Websocket 0.2.1 aufgerufen, liegts daran???
> ![grafik](https://user-images.githubusercontent.com/36229898/115962774-32368300-a51d-11eb-9715-72ab8710ed6c.png)
> 
> ![grafik](https://user-images.githubusercontent.com/36229898/115962698-e7b50680-a51c-11eb-8765-22b124572fdb.png)

Any console outputs?

**Comment by GermanBluefox** [comment]
Please test 5.0.9
