### ISSUE TITLE
No title

### ISSUE THREAD

**Issue by bergjet** [ioBroker/ioBroker.admin#717]
V 5.0.5
js-controller 3.2.16

<img width="407" alt="Bildschirmfoto 2021-04-20 um 08 25 46" src="https://user-images.githubusercontent.com/4241968/115348177-96221a00-a1b2-11eb-81e7-9fe41f175453.png">

**Comment by Dirk-Peter-md** [comment]
Dies trat auch beim Update von anderen Adaptern unter der Vorgängerversion V 5.0.3 auf

![HomeMatic 2021-04-20 100537](https://user-images.githubusercontent.com/52133172/115361655-118ac800-a1c1-11eb-81c4-fa71fbb2572b.jpg)

**Comment by Apollon77** [comment]
Ja das liegt eher an den affected adaptern. Bitte dort isssues auf machen. bzw bei hm-rega ists bekannt

**Comment by GermanBluefox** [comment]
This will be fixed in js-controller 3.3
