### ISSUE TITLE
ReactUI - parent.gMain is missing - any alternative?

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#718]
Hi, when switching to react UI the object parent.gMain is missing. Is there anything smiliar provided?

**Comment by Apollon77** [comment]
what is "parent.gMail"? This is NO valid object name if you mean a real ioBroker object!

**Comment by sbormann** [comment]
Hi,
yes, i mean a javascript-object:
``parent.gMain`` = 
![image](https://user-images.githubusercontent.com/49171332/115370034-f6bc5180-a1c8-11eb-933f-678c56688aa7.png)

Best thing was:
``parent.gMain.objects`` contained all ioBroker-Objects - so it was much faster than fetching them by socket while loading the adapter (for example for selectID-Dialog).

Next thing:
How can i get the currentHost (that is needed for the socket function readDirAsZip)?

Again, many thanks

**Comment by sbormann** [comment]
...and: how can i get the running instances?
This is how i get historyInstances (like sql or influx..):
````
//History-Instances
var historyInstances = [];
function getHistoryInstances(callback){
	historyInstances = [];
	for(var id = 0; id < parent.gMain.instances.length; id++){
		if(parent.gMain.objects[parent.gMain.instances[id]].common.type === 'storage'){
			historyInstances.push(parent.gMain.instances[id].substring('system.adapter.'.length));
		}
	}
	callback && callback();
}
````

**Comment by sbormann** [comment]
...update: I switched to socket-method again to fetch ioBroker-Objects. Now that (and the history-instances) works again. A little bit slower than before. So if you have any information how to replace the old parent.gMain.objects it would be great.

The only thing that i can't get working: How can i get the current host?

I need it for this line of code:
````javascript
socket.emit('sendToHost', parent.gMain.currentHost, 'readDirAsZip', {id: namespace, name: pathWithoutSlashNamespace, options: {settings: false}}, function(data){
````

**Comment by GermanBluefox** [comment]
You must take the host where your adapter is running.
Or you can detect the next host, that is alive.
