### ISSUE TITLE
Hinweis auf verfügbare version(stable) Admin5

### ISSUE THREAD

**Issue by crunchip77** [ioBroker/ioBroker.admin#719]
Der Hinweis auf Stable Version ist unter Umständen nicht Zielführend für den ein oder anderen User, da es sich beim Admin5 doch eher auf eine Alpha Version bezieht.
![image](https://user-images.githubusercontent.com/41550245/115371413-3df71200-a1ca-11eb-9b57-b26802167916.png)

**Comment by Apollon77** [comment]
Ich denke hier muss "Verfgbare version: beta" stehen weil es Beta repo ist

**Comment by Apollon77** [comment]
(Was also that way in admin4 and I stumbled over it several times) ... maybe change that now?

**Comment by GermanBluefox** [comment]
I don't understand the problem here.

**Comment by Apollon77** [comment]
The problkem is that the text "Verfüggabe Versionen: stable" IMMER da ist ... egal was man installiert hat und egal welches Repo

**Comment by GermanBluefox** [comment]
THere is no such a text in Admin5. Please verify in Admin5. 
Admin4 will not be fixed any more.
