### ISSUE TITLE
Admin 5.0.5 - React-UI: Adapter-Tab lädt nicht  - "Cannot getRepository: timeout"

### ISSUE THREAD

**Issue by MarcelW85** [ioBroker/ioBroker.admin#720]
Der Adapter-Tab bleibt leider leer und zeigt nur die Meldung "Cannot getRepository: timeout".
Eine Umstellung von Beta auf Stable bringt leider keine Besserung.

Das Problem besteht nur beim React-UI.

**Comment by GermanBluefox** [comment]
Please test 5.0.9
