### ISSUE TITLE
React-UI - customs

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#722]
1. The link to custom-dialog has changed from ``http://<ip>:8081/#tab-objects/customs/dwd.0.warning.description`` (not-react) to ``http://<ip>:8081/#tab-objects/custom/dwd.0.warning.description`` (react-ui)

(s at customS is missing). Is that intentionally or a mistake?
How can i check, which link is valid (i am linking from iQontrol configuration to customs)

2. I found out that the old custom_m.html is not any longer supported. Instead it seems we have to use jsonCustom.json, right? But i am using a table and some scripts inside the custom_m.html. Any chance to implement that? Is there a description how to build the new cusom-dialog? Or a backward-compatibility for the old dialogs?

**Comment by Apollon77** [comment]
1.) @GermanBluefox ? I thinkit was intentionalbecause unknown that anyone uses such deep links :-)

2.) For this you wil get an Adapter issue soon, but yes the old custom(_m).html ios not longer supported. It was too big of a hack before and getting more worse with the react change, so we had no other chance then breaking here. For component types not supported by jsonConfig right now (see https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/src/components/JsonConfigComponent/SCHEMA.md) we need an admin issue that describes the component and required functionality (or a PR to add it on react side :-) )

**Comment by GermanBluefox** [comment]
We will change to customS

**Comment by sbormann** [comment]
Duplicate of #962

**Comment by sbormann** [comment]
Thanks for changing the link to customS.
But there is a new problem:
When there are spaces in the name of the datapoint (expressed as %20) you will only get a blank page. 

Example:
http://192.168.10.69:8081/#tab-objects/customs/alias.0.Fenster%20Arbeitszimmer.ACTUAL
This URL is displayed, when opening the custom dialog from objects tab. But if you try to open that url, you get the error.

Browser-Log:
![image](https://user-images.githubusercontent.com/49171332/116760962-b0f85800-aa16-11eb-802b-c1f7a6e858d9.png)
![image](https://user-images.githubusercontent.com/49171332/116761007-c8374580-aa16-11eb-8e38-2a26ec1b6a82.png)
![image](https://user-images.githubusercontent.com/49171332/116761025-d2594400-aa16-11eb-8d0d-8e485bf7d1e1.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.12
