### ISSUE TITLE
 Admin 5.0.5 - React UI: Benachrichtigungsmarke am Adapter

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.admin#723]
Der Reiter Adapter trägt dauerhaft eine Benachrichtigungsmarke mit der Ziffer 1. Es ist nicht erkennbar, dass diese durch einen aktualisierbaren Adapter ausgelöst würde. Ist der Grund u.U. ein Adapter, der aus einem Github-Repository installiert wurde und für den keine "verfügbare" Version besteht (s. Screenshot)? 

![Screenshot_2021-04-20 adapters - iobroker](https://user-images.githubusercontent.com/59287435/115413577-955ea780-a1f5-11eb-9ad6-c19c709b0a9a.png)

Im bisherigen UI gibt es keinen entsprechenden Hinweis.

**Comment by GermanBluefox** [comment]
Please retest with 5.0.6

**Comment by lonsimbt** [comment]
Is fixed in 5.0.6
