### ISSUE TITLE
Admin 5.0.5: Password encryption does not work properly with ReactUI

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#724]
**Describe the bug**  
Encyrption and decryption works fine using the classc UI in Admin 5.0.5.
But when using ReactUI the encrypted fields get messed up when saved and can't be properly decrypted anymore.
Btw: Decrypting a formerly saved password works. 
Seems that the bug happens during saving. Maybe double encryption? Or a wrong Key?

**To Reproduce**  
1. Open any adapter that stores encrypted credentials
2. type a password 
3. click save & close
4. login of adapter will crash due to a wrong password

**Versions:**  
 - Adapter version: Admin 5.0.5
 - JS-Controller version: 3.2.16
 - Node version: v14.16.1
 - Operating system: Windows

**Comment by afuerhoff** [comment]
I have the same problem and can reproduce this behaviour. 
After switching back to classic ui and saving the password again all is ok.

**Comment by GermanBluefox** [comment]
Which adapter for instance?

**Comment by afuerhoff** [comment]
From my side fb-checkpresence.

**Comment by Grizzelbee** [comment]
I realized it with MieleCloudService. As far as I know both adapters are using the broker (>3.0) build-in method to encrypt passwords.

**Comment by GermanBluefox** [comment]
Please retest 5.0.6. It must be fixed there

**Comment by Grizzelbee** [comment]
Fix is tested and confirmed! 5.0.6 solves this issue.
