### ISSUE TITLE
Admin 5.0.5 Instanzen werden nicht angezeigt

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#725]
Update: Fehler ist beim 5.0.6 noch vorhanden

Bei Klick auf "Instanzen" bleibt das Hauptfenster leer und der Ladebalken oben pulsiert, es passiert aber nichts.
Keine Einträge im Logfile zu sehen.
Ich hatte das Problem gestern mit der Version 5.0.4 und habe den wieder deinstalliert. Heute Versuch mit 5.0.5 gleiches Ergebnis
Getestet mit Firefox, Firefox Nightly und Opera, überall gleiches Verhalten.
Wenn ich in der Konsole iobroker set admin.0 --react false eingebe funktioniert die Anzeige der Instanzen wieder.

![grafik](https://user-images.githubusercontent.com/45561610/115426382-bc6ea680-a200-11eb-8244-69773d03f50f.png)

**Versions:**  
 - Adapter version: 5.0.5
 - JS-Controller version: v14.16.1
 - Node version: 6.14.12
 - Operating system: Debian10

**Additional context**  
VM auf Proxmox (Intel NUK), Multihost Umgebung mit 1 Pi3 als Slave

**Comment by amg666** [comment]
Der erste Teil der Konsole kommt, wenn ich auf "Objekte" gehe, wenn ich dann auf Instanzen gehe kommen die letzten 8 Zeilen 



`Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. 192.168.2.23:8081
iobroker.admin@5.0.5 index.js:16:8
[2021-04-21T06:46:06.306Z] Try to connect instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
alias.0 instrument.ts:129:35
alias.kg.arbeit.kontakte.fensterlinks.fensterlinks instrument.ts:129:35
alias-manager.admin instrument.ts:129:35
GEThttp://192.168.2.23:8081/adapter/simple-api/simple-api.png
[HTTP/1.1 404 Not Found 23ms]

GEThttp://192.168.2.23:8081/adapter/socketio/socketio.png
[HTTP/1.1 404 Not Found 32ms]

Leerer String an getElementById() übergeben. ObjectBrowser.js:3914:37
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35
Translate: dark instrument.ts:129:35
Translate: blue instrument.ts:129:35
Translate: colored instrument.ts:129:35
Translate: light instrument.ts:129:35

​

`

**Comment by eric2905** [comment]
Same problem

Node 14.15.5
js 3.2.16

**Comment by JohGrei** [comment]
das selbes Problem
[https://github.com/ioBroker/ioBroker.admin/issues/725](url)

**Comment by Ilovegym66** [comment]
Hier auch (seit 5.0.4, keine Besserung mit 5.0.5 und 5.0.6), vielleicht hilft das:
![grafik](https://user-images.githubusercontent.com/36229898/115689870-c86f7b00-a35c-11eb-9f80-54638712d596.png)

**Comment by Apollon77** [comment]
@Ilovegym66 Alle Fehlwr kommen von irgendwelchen Firefix Addons/Plugins ...strange

Wie sieht es bei den anderen aus?

**Comment by Ilovegym66** [comment]
Mit Chrome findet er das login-bng.png nicht.. ?? was ist das..?
![grafik](https://user-images.githubusercontent.com/36229898/115705362-ba295b00-a36c-11eb-8db3-14ed3a8ec8b0.png)

**Comment by Ilovegym66** [comment]
![grafik](https://user-images.githubusercontent.com/36229898/115705509-e8a73600-a36c-11eb-845d-9cb105121cca.png)

**Comment by Ilovegym66** [comment]
mit Microsoft EDGE, noch Fehler cannot read repo... 
![grafik](https://user-images.githubusercontent.com/36229898/115705658-1ab89800-a36d-11eb-91f1-64ee7767cd14.png)

**Comment by amg666** [comment]
> 
> 
> @Ilovegym66 Alle Fehlwr kommen von irgendwelchen Firefix Addons/Plugins ...strange
> 
> Wie sieht es bei den anderen aus?

Opera: Beim Klick auf Instanzen kommt nur die letzte Zeile "instrument.ts:129 GET INSTANCES", das Log davor hab ich mal mitgepostet, das passiert bei Klick auf andere Menueinträge, die funktionieren.
`GET INSTANCES
simple-api.png:1 GET http://192.168.2.23:8081/adapter/simple-api/simple-api.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ci @ react-dom.production.min.js:208
Cl @ react-dom.production.min.js:251
Vl @ react-dom.production.min.js:250
wl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
fl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$c @ react-dom.production.min.js:122
Gc @ react-dom.production.min.js:123
Uc @ react-dom.production.min.js:122
ul @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonymous) @ ObjectBrowser.js:1573
Promise.then (async)
s @ ObjectBrowser.js:1537
fa @ react-dom.production.min.js:135
No @ react-dom.production.min.js:181
Ui @ react-dom.production.min.js:269
Vl @ react-dom.production.min.js:250
wl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
fl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$c @ react-dom.production.min.js:122
Gc @ react-dom.production.min.js:123
Uc @ react-dom.production.min.js:122
Fe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
xr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Xt @ react-dom.production.min.js:73
r @ helpers.ts:87
socketio.png:1 GET http://192.168.2.23:8081/adapter/socketio/socketio.png 404 (Not Found)
Image (async)
y @ react-dom.production.min.js:23
ci @ react-dom.production.min.js:208
Cl @ react-dom.production.min.js:251
Vl @ react-dom.production.min.js:250
wl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
fl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$c @ react-dom.production.min.js:122
Gc @ react-dom.production.min.js:123
Uc @ react-dom.production.min.js:122
ul @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonymous) @ ObjectBrowser.js:1573
Promise.then (async)
s @ ObjectBrowser.js:1537
fa @ react-dom.production.min.js:135
No @ react-dom.production.min.js:181
Ui @ react-dom.production.min.js:269
Vl @ react-dom.production.min.js:250
wl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
fl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$c @ react-dom.production.min.js:122
Gc @ react-dom.production.min.js:123
Uc @ react-dom.production.min.js:122
Fe @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
xr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Xt @ react-dom.production.min.js:73
r @ helpers.ts:87
instrument.ts:129 GET INSTANCES`

Firefox Nightly:
Letzte Zeile vom Log bei Klick auf "Instanzen", die Einträge davor bei Klick auf Objekte

`GEThttp://192.168.2.23:8081/adapter/simple-api/simple-api.png
[HTTP/1.1 404 Not Found 6ms]

GEThttp://192.168.2.23:8081/adapter/socketio/socketio.png
[HTTP/1.1 404 Not Found 4ms]

Leerer String an getElementById() übergeben. ObjectBrowser.js:3946:37
GET INSTANCES`

**Comment by GermanBluefox** [comment]
Läuft das ganze auf RPI3?

**Comment by amg666** [comment]
Nein das ist Debian10 auf einem Intel NUK6, RPI3 Slave ist eingebunden aber nur mit 2 Adaptern (rpi2 und smartmeter)

**Comment by Ilovegym66** [comment]
Bei mir ist das ein lxc-containter unter proxmox mit Debian 10, Raspizero ist u.a. ein Slave mit smartmeter :-)

**Comment by amg666** [comment]
update auf 5.0.7 hat keine Besserung gebracht

**Comment by amg666** [comment]
5.0.8 Fehler ist immer noch da

**Comment by arteck** [comment]
@GermanBluefox übrigends hab ich auch.. im PROD system

**Comment by hilde0407** [comment]
Hier mein Log des Admin Adapters beim Aufruf der Instanzen bei Nutzung der React UI:

```
admin.1 | 2021-04-25 13:29:06.094 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
-- | -- | -- | --
admin.1 | 2021-04-25 13:29:06.081 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.080 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.079 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.078 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.078 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.078 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.077 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.076 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.075 | debug | (26027) No suitable Lua script, fallback to keys!: function(doc) { if (doc.type === 'state') emit(doc._id, doc) }
admin.1 | 2021-04-25 13:29:06.069 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount, system.host.*.diskFre
admin.1 | 2021-04-25 13:29:06.068 | debug | (26027) Subscribe STATES: *.info.connection
admin.1 | 2021-04-25 13:29:06.044 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount, system.host.*.diskFre
admin.1 | 2021-04-25 13:29:06.043 | debug | (26027) Subscribe STATES: system.host.*.freemem
admin.1 | 2021-04-25 13:29:06.043 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount, system.host.*.diskFre
admin.1 | 2021-04-25 13:29:06.043 | debug | (26027) Subscribe STATES: system.host.*.diskWarning
admin.1 | 2021-04-25 13:29:06.042 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount, system.host.*.diskFre
admin.1 | 2021-04-25 13:29:06.042 | debug | (26027) Subscribe STATES: system.host.*.diskSize
admin.1 | 2021-04-25 13:29:06.042 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount, system.host.*.diskFre
admin.1 | 2021-04-25 13:29:06.041 | debug | (26027) Subscribe STATES: system.host.*.diskFree
admin.1 | 2021-04-25 13:29:06.041 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss, system.adapter.*.outputCount
admin.1 | 2021-04-25 13:29:06.040 | debug | (26027) Subscribe STATES: system.adapter.*.outputCount
admin.1 | 2021-04-25 13:29:06.040 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount, system.adapter.*.memRss
admin.1 | 2021-04-25 13:29:06.039 | debug | (26027) Subscribe STATES: system.adapter.*.memRss
admin.1 | 2021-04-25 13:29:06.039 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected, system.adapter.*.inputCount
admin.1 | 2021-04-25 13:29:06.039 | debug | (26027) Subscribe STATES: system.adapter.*.inputCount
admin.1 | 2021-04-25 13:29:06.038 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive, system.adapter.*.connected
admin.1 | 2021-04-25 13:29:06.038 | debug | (26027) Subscribe STATES: system.adapter.*.connected
admin.1 | 2021-04-25 13:29:06.037 | debug | (26027) Subscribes: admin.0.info.newsFeed, system.adapter.*.alive
admin.1 | 2021-04-25 13:29:06.037 | debug | (26027) Subscribe STATES: system.adapter.*.alive

```

**Comment by Apollon77** [comment]
@GermanBluefox 10 times fallback to keys "in parallel" is a huge load on the controller. Do we maybe really need to find a way to optimize these queries? Also that subscribes log looks strange

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by eric2905** [comment]
> test

Now it works fine.
Testet on iPad with iiPadOS 14.6 beta (Safari)
Testing with macOS Big Sur 11.4 beta will follow later (Safari, Chrome, Edge)

**Comment by amg666** [comment]
I can't see 5.0.9, even if i click update icon

**Comment by amg666** [comment]
Update: Strange behaviour: admin settings -> Access to Instances -> I checked "Allow access to specific instances and than selected alexa2 (I selected only 1 instance)
After saving the settings, admin adapter again shows no instances....

**Comment by Apollon77** [comment]
Any error in log or in Browser Konsole?

**Comment by GermanBluefox** [comment]
> But, now the information about updateable adapters is missing

Please open another issue
