### ISSUE TITLE
Admin 5.0.5 Fehlermeldung wenn Menueinträge gelöscht werden

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#726]
**Describe the bug**  
Nach Installation des Adapters und Aktivierung von React(UI) zeigt er beim ersten Aufruf im linken Menu alle verfügbaren Einträge, auch den Adapter inventwo. Deaktivierung von inventwo führt zu Fehlermeldung

**To Reproduce**  
1. Menu links, unten den roten Edit Stift anklicken
2. Click auf Checkbox von inventwo VIS
3. Fehlermeldung erscheint

**Expected behavior**  
Checkbox sollte deaktiviert sein ohne Fehlermeldung

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/45561610/115427587-e1174e00-a201-11eb-82a5-006be43d17a6.png)

**Versions:**  
 - Adapter version: 5.0.5
 - JS-Controller version: v14.16.1
 - Node version: 6.14.12
 - Operating system: Debian10

**Additional context**  
VM unter proxmox

**Comment by GermanBluefox** [comment]
That is the error message of vis-inventwo and not of Admin5.
