### ISSUE TITLE
Admin 5.0.5 Objekte Tab lädt ohne Ergebnis

### ISSUE THREAD

**Issue by tobasium** [ioBroker/ioBroker.admin#727]
Nur bei React UI beim Aufruf des Objekte Tabs nur der Ladekreis keine anzeige der Objekte. Sobald React deaktiviert wird geht auch der Objekte Tab wieder.

Konsole Edge:

`Uncaught (in promise) TypeError: v.startsWith is not a function
    at u (ObjectBrowser.js:869)
    at we (ObjectBrowser.js:786)
    at ObjectBrowser.js:1545`
ObjectBrowser.js:869 

`Uncaught TypeError: v.startsWith is not a function
    at u (ObjectBrowser.js:869)
    at we (ObjectBrowser.js:786)
    at ObjectBrowser.js:2096
    at r (helpers.ts:87)`
helpers.ts:111

**Comment by tobasium** [comment]
Als kleinen Zusatz. Lade ich im Skripte Tab in einem Blockly die Objektliste ist sie nach wenigen Sekunden da.

**Comment by GermanBluefox** [comment]
Please retest 5.0.6

**Comment by tobasium** [comment]
testet 5.0.6 problem still exist:

`VM558 adapterIssues.js:6 Uncaught (in promise) TypeError: Cannot read property 'tabs' of undefined
    at getIssues (VM558 adapterIssues.js:6)
    at showIssues (VM558 adapterIssues.js:51)
    at VM563 info.js:169`

`chrome-extension://f…ontentscript.js:244 Uncaught TypeError: Cannot read property 'scrollHeight' of null
:8081/adapter/img/clock/clockface.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/img/clock/sechand.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/img/clock/hourhand.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/img/clock/minhand.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:8081/adapter/info/l…/adapterIssues.js:6 Uncaught (in promise) TypeError: Cannot read property 'tabs' of undefined`

**Comment by GermanBluefox** [comment]
the errors are from https://github.com/iobroker-community-adapters/ioBroker.info/blob/master/admin/lib/js/adapterIssues.js
and not from Admin5

**Comment by tobasium** [comment]
There are many more errors in console of browser:

`helpers.ts:111 Uncaught TypeError: v.startsWith is not a function
    at u (ObjectBrowser.js:880)
    at we (ObjectBrowser.js:798)
    at ObjectBrowser.js:2108
    at r (helpers.ts:87)`

`Uncaught (in promise) TypeError: v.startsWith is not a function
    at u (ObjectBrowser.js:880)
    at we (ObjectBrowser.js:798)
    at ObjectBrowser.js:1557`

`Uncaught TypeError: v.startsWith is not a function
    at u (ObjectBrowser.js:880)
    at we (ObjectBrowser.js:798)
    at ObjectBrowser.js:2108
    at r (helpers.ts:87)`

**Comment by GermanBluefox** [comment]
Kann es sein, dass role bei irgendeinem Objekt nicht "string" ist?

**Comment by tobasium** [comment]
Wie finde ich das jetzt raus?

[json.zip](https://github.com/ioBroker/ioBroker.admin/files/6359877/json.zip)

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/115753079-1014f780-a39b-11eb-9c20-97f218314a5c.png)

**Comment by GermanBluefox** [comment]
Deine role ist 1, das darf nicht sein.

**Comment by tobasium** [comment]
Ok. Tatsache das war die Ursache. Wie die 1 da rein kam ist eine andere Frage.
