### ISSUE TITLE
No Links in table of contents in adapter information

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#728]
Admin 5.0.5

If you press the (?) of an adapter the readme of the adapter will be shown.
In the right corner is a table of content. I had expected that hyperlinks are available to jump to the selected section. 
Currently you can only see the table of content.

![grafik](https://user-images.githubusercontent.com/25422320/115447596-f9df2e00-a218-11eb-942e-b3ab3460b8c6.png)
![grafik](https://user-images.githubusercontent.com/25422320/115447718-1bd8b080-a219-11eb-9c16-958d862e7e2d.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.13

**Comment by Feuer-sturm** [comment]
With 5.0.13 it works :-)
