### ISSUE TITLE
Admin 5.0.5 - React UI: Tabellendarstellung Objekte

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.admin#729]
Wenn man in den Objekten die Statusansicht umschaltet, ist die Darstellung des Tabellenkopfes für die Spalten "Geändert von" bsi "Wert" unschön. Ist die Überschrift "Qualitätscode" rechtsbündig ausgerichtet?

![grafik](https://user-images.githubusercontent.com/59287435/115452141-585adb00-a21e-11eb-8bbb-c9dae082ab8e.png)

**Comment by GermanBluefox** [comment]
Please check 5.0.8 (tomorrow)

**Comment by lonsimbt** [comment]
Fixed
