### ISSUE TITLE
Wunsch: Datenpunkte unter admin.0 mit Zusatzinfos

### ISSUE THREAD

**Issue by ruhr70** [ioBroker/ioBroker.admin#73]
Zusätzlich zu den bestehenden Datenpunkte (Anzahl Updates und Update List) wären u.a. folgende Datenpunkte wünschenswert:
- Anzahl aktivierter Adapter/Instanzen/Prozesse
- Gesamtspeicherverbrauch
- Anzahl installierter Instanzen
- ...

**Comment by GermanBluefox** [comment]
Ist erledigt
