### ISSUE TITLE
Admin 5.0.5 - React UI: Filtern von Objekten bzgl. influxdb funktioniert nicht

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.admin#730]
Setzt man in der Ansicht Objekte einen Filter auf "influxdb.0", der hier für die Aufzeichnung von Werten genutzt wird, erfolgt keine Einschränkung des Objektbaumes auf die Zweige, in denen tatsächlich Daten mittels influxdb aufgezeichnet werden. Es wird weiter der vollständige Objektbaum angezeigt.

![grafik](https://user-images.githubusercontent.com/59287435/115453600-1cc11080-a220-11eb-85af-f940234ef24c.png)

**Comment by GermanBluefox** [comment]
Please retest with 5.0.6

**Comment by lonsimbt** [comment]
Filtering is working in 5.0.6
