### ISSUE TITLE
5.0.5: Inputfields in react ui mode are empty in adapter configuration dialog 

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#732]
**Describe the bug**  
The content from input-fields are not shown in the fb-checkpresence adapter in the react ui view. But
the content is shown in the object view.
In the classic view all fields are shown correctly.

**To Reproduce**  
1. Go to configuration dialog of fb-checkpresence adapter
2. On the first tab you can see that the input fields are empty

**Expected behavior**  
-

**Screenshots & Logfiles**  
**React UI view:**
![image](https://user-images.githubusercontent.com/50245893/115457592-0e292800-a225-11eb-9da5-554781cabad6.png)
**Classic View**
![image](https://user-images.githubusercontent.com/50245893/115458944-ba1f4300-a226-11eb-9597-b1239d4bf552.png)

**Versions:**  
 - Adapter version: 5.0.5
 - JS-Controller version: 3.2.16
 - Node version: v12.22.0 
 - Operating system: Debian GNU/Linux

**Additional context**  
-

**Comment by Apollon77** [comment]
@afuerhoff but you should also state that you do big "dynamicadmin oage building logic" :-)) Is your browser console showing any error?

**Comment by afuerhoff** [comment]
I have no errors seen. In the classic view I have no problems. With the 5.0.3 I have not had the problem.

**Comment by Apollon77** [comment]
So issue is only in 5.0.4 or 5.0.5 (can you test 5.0.4 please to see when it was introduced) and only in react ui?

**Comment by afuerhoff** [comment]
5.0.4: I am wrong, same problem in 5.0.4 but you can see, the values are there but the color format seems wrong.
![image](https://user-images.githubusercontent.com/50245893/115600301-db426b00-a2dc-11eb-8ed7-692fff72b809.png)

5.0.3 It was the 5.0.3. with the correct behaviour. Here the background is black.
![image](https://user-images.githubusercontent.com/50245893/115601012-9539d700-a2dd-11eb-9bf8-35fb51a1da6c.png)

**Comment by Apollon77** [comment]
@afuerhoff You are sure that the color is not set static from your index_m?

**Comment by GermanBluefox** [comment]
Please retest with 5.0.6

**Comment by afuerhoff** [comment]
Same behaviour in 5.0.6
I am wondering that in the 5.0.3 the background is black and in the 5.0.5 / 5.0.6 is not.
![image](https://user-images.githubusercontent.com/50245893/115702281-06729c00-a369-11eb-9c67-234baf31a60c.png)

**Comment by Apollon77** [comment]
That was changed because of an other adapter dev that had issues with also setting colors hard and such :-(

**Comment by GermanBluefox** [comment]
> Same behaviour in 5.0.6
> I am wondering that in the 5.0.3 the background is black and in the 5.0.5 / 5.0.6 is not.
> ![image](https://user-images.githubusercontent.com/50245893/115702281-06729c00-a369-11eb-9c67-234baf31a60c.png)

Have you restart adapter?

**Comment by afuerhoff** [comment]
Yes, I have. 
With classic UI no problems. It seems that the font color is transparent with react UI.
![image](https://user-images.githubusercontent.com/50245893/115751920-e9a28c80-a399-11eb-9d54-0b3bd7b20396.png)

**Comment by GermanBluefox** [comment]
There are errors in browser console. Can you show them?

**Comment by afuerhoff** [comment]
It should be only a problem in the dark theme. The other 3 color themes are working well.
![image](https://user-images.githubusercontent.com/50245893/115776809-d7821780-a3b4-11eb-9d82-589f9c76ffa2.png)

**Comment by afuerhoff** [comment]
Hello, with 5.0.7 all themes are working well. From my side the issue is solved.
