### ISSUE TITLE
Admin 5.0.5 - React UI: Objekte löschen & Fehlende Übersetzungen

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.admin#733]
"Delete with Children" scheint noch ohne Funktion zu sein.

In der Sicherheitsabfrage beim Löschen von Objekten fehlen noch die deutschen Übersetzungen sowohl im Text als auch in den beiden Delete-Buttons.

![grafik](https://user-images.githubusercontent.com/59287435/115504413-32622480-a278-11eb-91ba-143aa3e6af09.png)

**Comment by Apollon77** [comment]
Translations in progress

**Comment by GermanBluefox** [comment]
Übersetzung ist in 5.0.6 fixed. Deletion wird mit js-controller 3.3 gefixt

**Comment by Feuer-sturm** [comment]
Übersetzung ist mit 5.0.6 vorhanden
![grafik](https://user-images.githubusercontent.com/25422320/115774425-d8fe1080-a3b1-11eb-9825-a866acafb16e.png)


Den Begriff "mit Kindern löschen" find ich persönlich im deutschen nicht ganz optimal.
Alternativen: "Alle Einträge löschen", "Alle Unterelemente löschen"

**Comment by Feuer-sturm** [comment]
Admin 5.0.10

Translation looks good :-)

![grafik](https://user-images.githubusercontent.com/25422320/116318993-03870980-a7b6-11eb-92ba-f6e757c22e08.png)
