### ISSUE TITLE
Admin 5.0.6 lädt nicht via VPN (ws connection error: CLOSED_NO_STATUS)

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#734]
Ich habe gestern im Büro festgestellt, dass ich seit dem Update auf admin 5 (ohne react) nicht mehr via VPN auf iobroker komme. Zu Hause im LAN komme ich ohne Probleme auf die Systeme.
Getestet wurden mehrere Systeme ..

![image](https://user-images.githubusercontent.com/39792461/115522434-647d8180-a28c-11eb-870d-a641e92855df.png)

Getestet wurde mit openVPN und shrewSoftVPN.
Beide VPN Clients lieferten das gleiche Ergebnis.

`Autofocus processing was blocked because a document's URL has a fragment '#tab-adapters'.
socket.io.js:59 [2021-04-21T08:12:17.422Z] Try to connect
socket.io.js:59 [2021-04-21T08:12:38.618Z] Start reconnect 0
socket.io.js:59 [2021-04-21T08:12:38.629Z] Try to connect
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8081/lib/js/vendor.js.map: Load canceled due to load timeout
socket.io.js:61 [2021-04-21T08:12:52.817Z] ws connection error: CLOSED_NO_STATUS
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
socket.io.js:59 [2021-04-21T08:12:52.820Z] Start reconnect 0
socket.io.js:59 [2021-04-21T08:12:52.822Z] Try to connect
socket.io.js:61 [2021-04-21T08:12:52.877Z] ws connection error: CLOSED_NO_STATUS
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
socket.io.js:329 WebSocket connection to 'ws://192.168.123.212:8081/?sid=1618992772823' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:329
socket.onclose @ socket.io.js:122
socket.io.js:59 [2021-04-21T08:12:52.878Z] Start reconnect 1
socket.io.js:61 [2021-04-21T08:12:52.879Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
SocketClient.close @ socket.io.js:329
socket.onclose @ socket.io.js:122
socket.io.js:59 [2021-04-21T08:12:52.879Z] Reconnect is already running 1
socket.io.js:59 [2021-04-21T08:12:52.880Z] Reconnect is already running 1
socket.io.js:59 [2021-04-21T08:12:53.879Z] Try to connect`

Auf Admin mit aktiven react komme ich via VPN teilweise drauf bekomme aber regelmäßig reconnect Fehler:

`[2021-04-21T08:21:44.943Z] Start reconnect 3
5.b003398b.chunk.js:2 [2021-04-21T08:21:44.944Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 5.b003398b.chunk.js:2
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
SocketClient.close @ socket.io.js:329
(anonymous) @ socket.io.js:92
r @ 5.b003398b.chunk.js:2
setTimeout (async)
(anonymous) @ 5.b003398b.chunk.js:2
SocketClient.connect @ socket.io.js:89
(anonymous) @ socket.io.js:354
r @ 5.b003398b.chunk.js:2
setTimeout (async)
(anonymous) @ 5.b003398b.chunk.js:2
SocketClient._reconnect @ socket.io.js:349
SocketClient.close @ socket.io.js:343
socket.onerror @ socket.io.js:132
SocketClient.close @ socket.io.js:329
(anonymous) @ socket.io.js:92
r @ 5.b003398b.chunk.js:2
error (async)
SocketClient.connect @ socket.io.js:125
(anonymous) @ socket.io.js:354
r @ 5.b003398b.chunk.js:2
setTimeout (async)
(anonymous) @ 5.b003398b.chunk.js:2
SocketClient._reconnect @ socket.io.js:349
SocketClient.close @ socket.io.js:343
socket.onerror @ socket.io.js:132
SocketClient.close @ socket.io.js:329
(anonymous) @ socket.io.js:92
r @ 5.b003398b.chunk.js:2
error (async)
SocketClient.connect @ socket.io.js:125
(anonymous) @ socket.io.js:354
r @ 5.b003398b.chunk.js:2
setTimeout (async)
(anonymous) @ 5.b003398b.chunk.js:2
SocketClient._reconnect @ socket.io.js:349
SocketClient.close @ socket.io.js:343
socket.onclose @ socket.io.js:122
`

Des Weiteren bekommt ich via VPN im react beim öffnen des Adapter Tabs folgenden Fehler und der Tab wird nicht geöffnet:

`TypeError: Cannot read property 'Node.js' of undefined
    at s.<anonymous> (Adapters.js:331)
    at u (5.b003398b.chunk.js:2)
    at Generator._invoke (5.b003398b.chunk.js:2)
    at Generator.next (5.b003398b.chunk.js:2)
    at r (5.b003398b.chunk.js:2)
    at c (5.b003398b.chunk.js:2)`

Getestet habe ich mit Chrome und Edge. Im lokalen LAN besteht diese Problem nicht und ich habe lokal auf alle genannten varianten Zugriff.

Ein Downgrade auf Admin 4.2.1 behebt das Problem

**Comment by simatec** [comment]
@GermanBluefox 
Eventuell helfen dir die weiteren Informationen etwas mehr.
Grundsätzlich habe ich das Gefühl, dass durch die VPN die Datenrate zu wenig ist und bis Ende eines Timeouts nicht alle map Dateien geladen werden können.

Hier ein Log mit Admin 5.0.6:

Instanz mit react = true

`iobroker.admin@5.0.6
4.dfa86905.chunk.js:2 [2021-04-22T08:26:52.557Z] Try to connect
4.dfa86905.chunk.js:2 Cannot getHostInfo for "system.host.iobroker-dev": timeout
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 Cannot getRepository: timeout
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 Cannot getInstalled: timeout
4.dfa86905.chunk.js:2 TypeError: Cannot read property 'Node.js' of undefined
    at a.<anonymous> (main.03db9e9b.chunk.js:2)
    at h (4.dfa86905.chunk.js:2)
    at Generator._invoke (4.dfa86905.chunk.js:2)
    at Generator.next (4.dfa86905.chunk.js:2)
    at r (4.dfa86905.chunk.js:2)
    at i (4.dfa86905.chunk.js:2)
(anonymous) @ 4.dfa86905.chunk.js:2
4.dfa86905.chunk.js:2 GET INSTANCES
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 Cannot read host information: timeout
4.dfa86905.chunk.js:2 Translate: Start/stop
4.dfa86905.chunk.js:2 Translate: Restart
4.dfa86905.chunk.js:2 [2021-04-22T08:27:52.836Z] Start reconnect 0
4.dfa86905.chunk.js:2 [2021-04-22T08:27:52.841Z] Try to connect
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 [2021-04-22T08:28:15.883Z] ws connection error: CLOSED_NO_STATUS
(anonymous) @ 4.dfa86905.chunk.js:2
4.dfa86905.chunk.js:2 [2021-04-22T08:28:15.928Z] Start reconnect 0
4.dfa86905.chunk.js:2 [2021-04-22T08:28:15.934Z] Try to connect
4.dfa86905.chunk.js:2 [2021-04-22T08:28:16.003Z] ws connection error: CLOSED_NO_STATUS
(anonymous) @ 4.dfa86905.chunk.js:2
socket.io.js:329 WebSocket connection to 'ws://192.168.123.212:8091/?sid=1619080095934&name=admin' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:329
4.dfa86905.chunk.js:2 [2021-04-22T08:28:16.003Z] Start reconnect 1
4.dfa86905.chunk.js:2 [2021-04-22T08:28:16.004Z] ws connection error: CLOSE_ABNORMAL
(anonymous) @ 4.dfa86905.chunk.js:2
24.dfa86905.chunk.js:2 [2021-04-22T08:28:16.004Z] Reconnect is already running 1
4.dfa86905.chunk.js:2 [2021-04-22T08:28:17.004Z] Try to connect
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 Translate: Show/hide PID
4.dfa86905.chunk.js:2 GET INSTANCES
4.dfa86905.chunk.js:2 Cannot read repo information: timeout
4.dfa86905.chunk.js:2 Cannot read host information: timeout
4.dfa86905.chunk.js:2 Translate: Start/stop
4.dfa86905.chunk.js:2 Translate: Restart
4.dfa86905.chunk.js:2 Cannot getHostInfo for "system.host.iobroker-dev": timeout
4.dfa86905.chunk.js:2 Cannot getRepository: timeout
4.dfa86905.chunk.js:2 Cannot getInstalled: timeout
4.dfa86905.chunk.js:2 TypeError: Cannot read property 'Node.js' of undefined
    at a.<anonymous> (main.03db9e9b.chunk.js:2)
    at h (4.dfa86905.chunk.js:2)
    at Generator._invoke (4.dfa86905.chunk.js:2)
    at Generator.next (4.dfa86905.chunk.js:2)
    at r (4.dfa86905.chunk.js:2)
    at i (4.dfa86905.chunk.js:2)
(anonymous) @ 4.dfa86905.chunk.js:2
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8091/static/js/4.dfa86905.chunk.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8091/static/js/main.03db9e9b.chunk.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8091/static/js/5.6e22f7c6.chunk.js.map: Load canceled due to load timeout`

Instanz mit react = false

`[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"tab-users-dialog-new-password" autocomplete=​"new-password">​
192.168.123.212/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"tab-users-dialog-new-password-repeat" autocomplete=​"new-password">​
socket.io.js:59 [2021-04-22T08:35:35.223Z] Try to connect
socket.io.js:59 [2021-04-22T08:35:51.335Z] Start reconnect 0
socket.io.js:59 [2021-04-22T08:35:51.337Z] Try to connect
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8081/lib/js/vendor.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://192.168.123.212:8081/js/app.js.map: Load canceled due to load timeout
socket.io.js:61 [2021-04-22T08:36:22.008Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
socket.io.js:59 [2021-04-22T08:36:22.009Z] Start reconnect 0
socket.io.js:59 [2021-04-22T08:36:22.011Z] Try to connect
socket.io.js:61 [2021-04-22T08:36:22.113Z] ws connection error: CLOSED_NO_STATUS
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
socket.io.js:329 WebSocket connection to 'ws://192.168.123.212:8081/?sid=1619080582011' failed: WebSocket is closed before the connection is established.
SocketClient.close @ socket.io.js:329
socket.onclose @ socket.io.js:122
socket.io.js:59 [2021-04-22T08:36:22.113Z] Start reconnect 1
socket.io.js:61 [2021-04-22T08:36:22.116Z] ws connection error: CLOSE_ABNORMAL
error @ socket.io.js:61
socket.onclose @ socket.io.js:120
SocketClient.close @ socket.io.js:329
socket.onclose @ socket.io.js:122
socket.io.js:59 [2021-04-22T08:36:22.116Z] Reconnect is already running 1
socket.io.js:59 [2021-04-22T08:36:22.116Z] Reconnect is already running 1
socket.io.js:59 [2021-04-22T08:36:23.327Z] Try to connect`

**Comment by simatec** [comment]
Ich habe zum Vergleich das ganze noch einmal mit Admin 4.2.1 durchgespielt.
Hier dauert zwar das laden recht lang, aber der Admin wird geladen.

Eventuell hilft auch hier der Log aus Admin 4.2.1

`[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"tab-users-dialog-new-password" autocomplete=​"new-password">​
192.168.123.214/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input type=​"password" id=​"tab-users-dialog-new-password-repeat" autocomplete=​"new-password">​
DevTools failed to load SourceMap: Could not load content for http://192.168.123.214:8081/lib/js/vendor.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://192.168.123.214:8081/js/app.js.map: Load canceled due to load timeout
app.js:2 [Violation] 'setTimeout' handler took 51ms
app.js:2 "ECharts": {"en": "ECharts", "de": "ECharts", "ru": "ECharts", "pt": "ECharts", "nl": "ECharts", "fr": "ECharts", "es": "ECharts", "pl": "ECharts", "it": "ECharts", "zh-cn": "ECharts"},
app.js:2 [Violation] 'setTimeout' handler took 52ms
app.js:2 "offline": {"en": "offline", "de": "offline", "ru": "offline", "pt": "offline", "nl": "offline", "fr": "offline", "es": "offline", "pl": "offline", "it": "offline", "zh-cn": "offline"},
app.js:2 Cannot compare "" and "0.0.5"
upToDate @ app.js:2
(anonymous) @ app.js:2
(anonymous) @ app.js:2
(anonymous) @ app.js:2
setTimeout (async)
(anonymous) @ app.js:2
r.onack @ index.js:83
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83`

**Comment by simatec** [comment]
@GermanBluefox  
Ich habe mir das Problem noch einmal in Ruhe angeschaut und intensiv getestet.
Mit dem Fix siehe PR ist der Fehler behoben und der Admin wird auch bei etwas langsameren Verbindungen via VPN geladen.

https://github.com/ioBroker/ioBroker.admin/pull/748

**Comment by GermanBluefox** [comment]
Thank you!

**Comment by simatec** [comment]
@GermanBluefox @Apollon77 
Auch wenn das Issue schon geschlossen wurde, muss ich hier noch einmal einhacken.
Gibt es eine Möglichkeit, die Datenmenge beim Aufruf von Admin zu verringern. 
Mit Admin 5.0.x habe ich extreme Probleme über VPN den Admin aufzurufen.

ich habe schon etliche male mit dem Timeout versucht was zu lösen, aber am Ende bekomme ich immer wieder Fehler Logs und der Admin wird nicht geladen oder einige Tabs können nicht geöffnet werden und geben errors raus.

Ich denke es müssen so ca. 10-15 MB geladen werden und bei einer VPN ist das schon recht viel. An meinem Standort habe ich aktuell nur 2,3 Mb im Upload.

Mein Produktivsystem läuft mit 4.2.1 und hier gibt es absolut keine Probleme.

Ich weiß, es ist noch Alpha. Ich möchte es bloß gerne in die Phase schon melden, da jetzt sicher noch einiges gemacht werden kann und noch schreien nicht zu viele User zu dem Problem.

Wenn ich irgendwo helfen kann zwecks Fehleranalyse, dann immer sehr gerne

**Comment by Apollon77** [comment]
Dann wäre ein neues Issue speziell zum thema "daten verringern" ggf ne idee ;-)) kannst du sehen was die haupt Traffic auslöser sind?

**Comment by simatec** [comment]
Da müsste ich mal schauen, wo man das eventuell in Chrome sehen kann ... 
Ich habe mal geschaut, was geladen wird. Und da sind einige js und einige map Dateien ...

Teileweise liegt eine Datei bei um die 5 MB.
Konntest du via VPN schon aus dem Büro testen?
Bei mir im Büro hab ich so ca. 20 MB synchron. 

Bei mir im Router habe ich die IOB Systeme schon versucht zu priorisieren aber leider erfolglos. Rufe ich den Admin auf, ist mein Upload bis zum TimeOut voll auf Anschlag

**Comment by Apollon77** [comment]
Naja die "statischen" FIles sollten nach einmal laden ja im Browser cache sein und damit "da" 

@GermanBluefox Vllt noch ETAG support oder sowas in den admin webserver einbauen/aktivieren für die statischen teile

Die Frage ist ja daher ob es die Statischen Teile sind oder die dynamische

**Comment by Apollon77** [comment]
ETAG seems to be easy in express:

https://stackoverflow.com/questions/24542959/how-does-a-etag-work-in-expressjs ... or maybe just  adding caching header for the static files is an better and enough solution?

**Comment by Apollon77** [comment]
PS: no was not yet in offcie ... but I have 25MBit in upload ... so :-))

**Comment by simatec** [comment]
> but I have 25MBit in upload ... so :-))

OK, dann hast du 10x soviel ... Bei mir auf dem Lande geht nicht mehr

**Comment by simatec** [comment]
> Naja die "statischen" FIles sollten nach einmal laden ja im Browser cache sein und damit "da"

@Apollon77 Davon würde ich auch ausgehen. Den gleichen Laptop wie hier im Büro nutze ich auch daheim.
Im Heimnetzwerk lädt der Admin wie er soll Sowohl mit als auch ohne react. 
Ich habe leider kein Remotezugang über die Cloud, sonst hätte ich den Weg mal getestet.

**Comment by Apollon77** [comment]
Naja müsste man im Browser schauen ob er aus dem cache lädt oder neu vom server

**Comment by simatec** [comment]
Er lädt die Admin Seite neu. 
Getestet hab ich mit Edge und Chrome

**Comment by simatec** [comment]
@GermanBluefox @Apollon77 
Eventuell helfen euch die Angaben aus der DEV-Konsole etwas weiter
![image](https://user-images.githubusercontent.com/39792461/116118801-fa1a7600-a6bd-11eb-88a6-c0915f542c31.png)

![image](https://user-images.githubusercontent.com/39792461/116118861-0a325580-a6be-11eb-8e26-9340fb91aed9.png)

![image](https://user-images.githubusercontent.com/39792461/116118934-246c3380-a6be-11eb-86ac-db1e1c7be742.png)

**Comment by simatec** [comment]
Hier noch die geladenen Dateien mit react

![image](https://user-images.githubusercontent.com/39792461/116119791-1a970000-a6bf-11eb-9696-8ffe1886e817.png)

**Comment by simatec** [comment]
Ich habe das ganze nochmal mit 4.2.1 gemacht 
![image](https://user-images.githubusercontent.com/39792461/116131246-6e5c1600-a6cc-11eb-90b6-45e052fa483d.png)

**Comment by simatec** [comment]
Hier sehe ich im Websocket ein paar Unterschiede.

Websocket 4.2.1
![image](https://user-images.githubusercontent.com/39792461/116132587-027aad00-a6ce-11eb-86b9-04809265b466.png)
![image](https://user-images.githubusercontent.com/39792461/116132677-19210400-a6ce-11eb-844b-d7c507c32b26.png)

Websocket 5.0.8
![image](https://user-images.githubusercontent.com/39792461/116132781-3c4bb380-a6ce-11eb-921e-c4c255a3f0a7.png)

**Comment by simatec** [comment]
@GermanBluefox Wenn du weitere Infos benötigst, können wir gerne ne direkte Verbindung herstellen und du kannst direkt Live bei mir testen, wo eventuell das Problem liegt ...
