### ISSUE TITLE
Admin 5.0.5 - White screen after selecting "Update all adapter"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#736]
Admin 5.0.5

If you press the button to "update all adapter" you will get a white screen with the below error. The update of the selected was done in the background. 

![grafik](https://user-images.githubusercontent.com/25422320/115606969-a6d2ad00-a2e4-11eb-80b4-a55e861adf7a.png)
![Animation](https://user-images.githubusercontent.com/25422320/115607635-7a6b6080-a2e5-11eb-888a-524696294f46.gif)

**Comment by GermanBluefox** [comment]
Please retest 5.0.6

**Comment by Feuer-sturm** [comment]
is fixed with 5.0.6  :-)
