### ISSUE TITLE
Admin 5.0.5. - Resync Android App friert ein.

### ISSUE THREAD

**Issue by JBSullivan** [ioBroker/ioBroker.admin#737]
Mit Admin 5.0.5. habe ich festgestellt, das bei einem ReSync der Android App (letzte verfügbare Version) diese einfriert und der Ladebalken bei "100%" in der vis-view.json stehen bleibt. 
Startet man die App neu, sieht man, das dass ReSync funktioniert hat, aber es gibt nicht wie früher einen automatischen Reload nach einem abgeschlossenen ReSync.

![image](https://user-images.githubusercontent.com/44617472/115610442-2793a800-a2e9-11eb-9011-1b65b6b9af9c.png)

**Comment by Apollon77** [comment]
Aber die ANdroid App hat doch mit Admin nix zu tun?! WIe kommst Du dazu das es connected ist?

**Comment by JBSullivan** [comment]
Ganz ehrlich, woher soll ich als Enduser wissen, was alles mit dem Admin zusammen hängt. War halt auffällig, das dass oben beschriebene Verhalten erst seit dem Update auf Admin 5.0.5 auftaucht. Von daher dachte ich - kannst es ja mal melden ;)

**Comment by amg666** [comment]
@JBSullivan Der Admin-Adapter ist für die Admin Oberfläche im Webbrowser da (und wenn du den Adapter updatest merkst du es daran, dass im Browser nix mehr geht bis das Update durch ist und der admin wieder läuft)
Zu deinem Problem mit der App: Hab ich grade bei mir versucht, lief ohne Probleme durch (Samsung Galaxy A5 mit Android 8.0.0), ich bin zwar schon beim Admin 5.0.6 aber beim 5.0.5 ging das auch ohne Probleme (weiß ich weil ich gestern an meiner "mobilen VIS" gebastelt habe  und da mehrere male re-synch machen musste.

**Comment by Apollon77** [comment]
@JBSullivan DIe Frage war genau so offen gemein t wie gestellt. Da war von meiner Seite nichts negatives drin. Es hätte ja sein können das Du einen grund gesehen hast
