### ISSUE TITLE
Admin 5.0.5 - React UI: Updateable Adapters - counter incorrect

### ISSUE THREAD

**Issue by eric2905** [ioBroker/ioBroker.admin#738]
The admin shows 5 adapters with updates, but there is only one update available

Info tab
![admin_01](https://user-images.githubusercontent.com/18639287/115611191-10a18580-a2ea-11eb-80c0-62bca78c200a.png)

--------------------------------------------------------------------------------------------------------------

Adapter tab
![admin_02](https://user-images.githubusercontent.com/18639287/115611217-15fed000-a2ea-11eb-9271-c55fc089fc4e.png)

**Comment by Feuer-sturm** [comment]
@eric2905 
Is duplicate with https://github.com/ioBroker/ioBroker.admin/issues/684
