### ISSUE TITLE
Admin 5.0.5 - React UI - Base settings Object and States Type Redis

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#739]
**Describe the bug**  
It cannot enter the IP/DNS of a remote server.
In my case a Docker host.

![image](https://user-images.githubusercontent.com/19333515/115618578-2ebfb380-a2f3-11eb-87c5-594a740cf202.png)
![image](https://user-images.githubusercontent.com/19333515/115618608-3717ee80-a2f3-11eb-9800-a4ab3ba067c6.png)

**Comment by Apollon77** [comment]
We need to enhance the option for IP dropdown to allow to specify an own IP or hostname - especially for redis that can be placed on a separate host!

**Comment by Apollon77** [comment]
(This is also needed for other adapters). Maybe we need two component types. One for "LocalIP" to just allow that selection or for "an ip"

**Comment by GermanBluefox** [comment]
Please test 5.0.6

**Comment by o0shojo0o** [comment]
Fix I can confirm.
Thanks for that!
