### ISSUE TITLE
Javascript UI mit Admin5: Änderung vom Scriptnamen und Verschieben führt zur Löschung vom Script 

### ISSUE THREAD

**Issue by testit2020** [ioBroker/ioBroker.admin#740]
Scriptname momentan: A_TEST1
![image](https://user-images.githubusercontent.com/68483974/115437186-29d40480-a20c-11eb-927a-e6cfe4ac32b6.png)
Ändern->
![image](https://user-images.githubusercontent.com/68483974/115437276-45d7a600-a20c-11eb-9fb9-00c6b4da107c.png)
OK klicken
![image](https://user-images.githubusercontent.com/68483974/115437374-6142b100-a20c-11eb-8f17-efc89889ee6d.png)

![image](https://user-images.githubusercontent.com/68483974/115437432-73bcea80-a20c-11eb-8adc-ac3afd83d7e9.png)

NPM
6.14.12
**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: linux

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by Feuer-sturm** [comment]
Admin 5.0.11

@GermanBluefox @Apollon77 
Renaming scripts and moving scripts to a different folder is working fine :-)
