### ISSUE TITLE
No progress or feedback in updatewindow after update of Admin adapter

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#742]
Update from Admin 5.0.5 to Admin 5.0.6

After starting the update of the admin adapter the update window will not change and no progress or final message will be shown.

Admin 5.0.6 was started successfull
`22 Apr 2021 21:03:15.597 admin.0 (15981) starting. Version 5.0.6 in /opt/iobroker/node_modules/iobroker.admin, node: v12.21.0, js-controller: 3.2.16 `

and 5 minutes later there is still the same window:
![grafik](https://user-images.githubusercontent.com/25422320/115788496-f5a34400-a3c3-11eb-903a-418571d43879.png)

Expectation is that a feedback is shown in the window after admin adapter update.

**Comment by Apollon77** [comment]
I also had that

**Comment by sigi2345** [comment]
Dito: Admin 5.0.6 to 5.0.7.

![Screenshot (3697)](https://user-images.githubusercontent.com/41079106/115955532-4ebfc480-a4f7-11eb-80ce-449f7d4a9454.png)

**Comment by GermanBluefox** [comment]
What exactly do you want to see from **stopped** instance???

**Comment by Feuer-sturm** [comment]
@GermanBluefox is it possible to give some feedback after admin started successfull after update?

**Comment by GermanBluefox** [comment]
Nope or hard to do.

**Comment by Feuer-sturm** [comment]
Ok, if there is no easy way then the topic can be closed from my point of view.

**Comment by Apollon77** [comment]
Admin4 behaves the same from the progress infos, BUT after admin restart the update window is closed!

**Comment by Apollon77** [comment]
We should have that as feedback of the successfull update or such

**Comment by Feuer-sturm** [comment]
@GermanBluefox 

Update from 5.0.20 to 5.0.21. 
Command window stays open after reconnection.

**Comment by Apollon77** [comment]
I think if fixed in 5.21 then it can only be tested when goind 5.0.21 -> 22 or ?!

**Comment by Feuer-sturm** [comment]
Update from 5.0.21 to 5.0.22.
Command window stays open after reconnection.

**Comment by Feuer-sturm** [comment]
Update from 5.0.24 to 5.0.26
 Command window closed after reconnection -> issue is fixed :-)

**Comment by Feuer-sturm** [comment]
Update from 5.0.26 to 5.0.27 on ioBroker Master
ioBroker slave 5.0.26

After admin update the command window stays open


![grafik](https://user-images.githubusercontent.com/25422320/118635045-768f0900-b7d3-11eb-8b17-5c7a122f10c6.png)

**Comment by GermanBluefox** [comment]
Fixed in 2.0.28

**Comment by Feuer-sturm** [comment]
Update from 5.0.27 to 5.0.28 on ioBroker Master
ioBroker slave 5.0.27
Browser: Chrome

After admin update the command window stays open.

@GermanBluefox Was your expectation that issue is fixed by making update from 5.0.27 to 5.0.28 or can it first work if I update from 5.0.28 to >=5.0.29 ?

**Comment by GermanBluefox** [comment]
> Was your expectation that issue is fixed by making update from 5.0.27 to 5.0.28 or can it first work if I update from 5.0.28 to >=5.0.29 ?

Yes. That was my expectation

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
After update Admin 5.0.28 to 5.0.29 the command window closed automatically :-)
