### ISSUE TITLE
Admin 5: fehlerhafte Instanz Übersicht auf mobile 

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#744]
iOS Safari, Column wird nich korrekt gerendert

![7251BB20-E034-471B-8B7D-6DBB98534080](https://user-images.githubusercontent.com/7318445/115819234-b80fdc80-a3fe-11eb-957a-f71291095167.png)

**Comment by GermanBluefox** [comment]
Fixed with 5.0.11
