### ISSUE TITLE
CSS and JS issues with Safari - (React UI 5.0.6)

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#746]
**Describe the bug**  

Some CSS and JS issues with Safari Version 14.0.3 (16610.4.3.1.7).

**To Reproduce**  

1. Use Safari
2. Open Tab "Instances"
3. Open Tab "Logs"

**Issue**  

1. Rows in instance view are to high (due to line breaks in RAM usage and other information)
2. Existing log entries cannot be parsed (NaN in timestamp)

**Screenshots & Logfiles**  

<img width="946" alt="Screenshot 2021-04-23 at 09 48 08" src="https://user-images.githubusercontent.com/1959049/115837639-18137c80-a419-11eb-9801-803e70c6e8bd.png">

<img width="1138" alt="Screenshot 2021-04-23 at 09 48 19" src="https://user-images.githubusercontent.com/1959049/115837620-12b63200-a419-11eb-9d68-4f2ef544590b.png">

**Versions:**  
 - Safari Browser: 14.0.3 (16610.4.3.1.7)
 - Adapter version: 5.0.6
 - JS-Controller version: 3.2.16
 - Node version: 12.20.1
 - Operating system: debian buster

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by klein0r** [comment]
- Log Date/Time issue is fixed
- Instance tab has still a line break

<img width="191" alt="Screenshot 2021-04-27 at 08 50 10" src="https://user-images.githubusercontent.com/1959049/116198733-a009c700-a736-11eb-8267-16c13b40b759.png">

**Comment by GermanBluefox** [comment]
Please test 5.0.11

**Comment by klein0r** [comment]
Fixed 👍 Thanks a lot
