### ISSUE TITLE
Admin 5.07 - im IOT Adapter können keine neuen Geräte mit Umlaut hinzugefügt werden

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.admin#749]
Beim Versuch über den IOT Adapter ein neues Gerät hinzuzufügen welches im Namen ein Umlaut enthält ("ä"), schlägt dies fehl.
![image](https://user-images.githubusercontent.com/30980239/115952279-59715e00-a4e5-11eb-9eb1-c8fef9acdda0.png)

Interessanterweise wird im RAW dennoch der Eintrag erstellt
 "smartName": {
      "de": "mähroboter"
    }

Die Gerätesuche über Alexa findet kein neues Geräte und in der Auflistung der Geräte im IOT Adapter erscheint der Eintrag nicht.

Das Hinzufügen eines Datenpunktes ohne Umlaut war hingegen in 5.0.7 erfolgreich
Das Hinzufügen des Datenpunktes mit dem Umlaut war mit Admin 4.x erfolgreich
Dann hat Alexa das/die Gerät/e auch gefunden und hinzugefügt.

Nachtrag:
Admin: 5.0.7
IOT Adapter: 1.8.16
Host. 3.2.16
node: 12.22.1
npm: 6.14.12

**Comment by GermanBluefox** [comment]
Das ist doch iobroker.iot bug und nicht Admin5 bug

**Comment by Apollon77** [comment]
@BramTown please create issue new in iot adapter
