### ISSUE TITLE
Admin 5.0.7: Objekt-Verzeichnisse können nicht komplett komplett gelöscht werden

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#750]
Funktion "löschen all" wird nicht richtig ausgeführt.

Ein Objekt-Ordner mit mehreren DP soll komplett gelöscht werden.
An dem zu löschenden Gruppenordner wird auf den Mülleimer geclickt.
Die Abfrage ob wirklich der gesamte Ordner gelöscht werden soll, wird mit "alle" bestätigt.
Jetzt klappt der Ornder auf und nur das letzte Objekt wird gelöscht.

Löschen einzelner Objekte funktioniert, jedoch nicht das "gruppenweise" löschen.

js-controller 3.2.16
node.js 12.22.1
npm 6.14.12

**Comment by GermanBluefox** [comment]
Wird im controller.js 3.3 gefixt
