### ISSUE TITLE
Admin 5.0.7: Cannot set property 'uuid' of undefined

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#751]
![grafik](https://user-images.githubusercontent.com/6681528/115966644-e12f8a80-a52e-11eb-9b0a-845c8ef3b868.png)

bei Aufruf der Adapter Liste

**Comment by GermanBluefox** [comment]
Fixed in 5.0.9. not yet released

**Comment by GermanBluefox** [comment]
Please test 5.0.9
