### ISSUE TITLE
Please added Feature for JsonConfigComponent

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#752]
PLease added this Features for JsonConfigComponent

* Link for Helptext (Hyperlink blank for readme or other)
* collapsible
* progress
* indeterminate
* title in h6
* more btn
* timepicker
* table-values

**Comment by GermanBluefox** [comment]
table-values - table
title in h6 - header
Link for helptext - staticLink

Where should progress get the value?
How the indeterminate checkbox should be coded? Value? Normally there are: true, false and ??

"more btn" for what? What more?

"collapsible " - does it meant accordion?

Only timepicker is clear and could be implemented together with dat picker

**Comment by Apollon77** [comment]
@foxriver76 maybe also for your monitoring pleasure

**Comment by foxriver76** [comment]
Would be great if after an issue is fixed the docs get updated by @GermanBluefox , then I could use the diff of the docs.

**Comment by simatec** [comment]
> table-values - table
> title in h6 - header
OK, I'll take a closer look at that

> Link for helptext - staticLink
I meant a link in the help text. Maybe that's already possible. Unfortunately I couldn't find it in the documentation. Here is an example
![image](https://user-images.githubusercontent.com/39792461/116237001-ff300180-a75f-11eb-9e3a-b74bcd2aeb24.png)

> Where should progress get the value?
> How the indeterminate checkbox should be coded? Value? Normally there are: true, false and ??
I mean a process bar that shows the progress
![image](https://user-images.githubusercontent.com/39792461/116237578-b3ca2300-a760-11eb-9306-8dc5d0c6f079.png)

> "more btn" for what? What more?
By that I meant more options for the size of the lettering, functions and icons of the buttons
> 
> "collapsible " - does it meant accordion?
Yes ... here the Example
![image](https://user-images.githubusercontent.com/39792461/116237354-6483f280-a760-11eb-8075-6a2c3ea0ec47.png)

> Only timepicker is clear and could be implemented together with date picker

**Comment by simatec** [comment]
@GermanBluefox I should absolutely not come across as a criticism. At your request in the dev meeting, I only tried to see what could possibly be included. I absolutely love JsonConfig

**Comment by GermanBluefox** [comment]
> Where should progress get the value?
?

> How the indeterminate checkbox should be coded? Value? Normally there are: true, false and ??
?

> More btn
Size could be controlled via "style" and "darkStyle". Icon is only possible as base64 or href to "admin/backitup/iconNAME.png".

What the function should have button? Now it can set state and send message via sendTo.

**Comment by simatec** [comment]
> > Where should progress get the value?
> 
> ?
> 
> > How the indeterminate checkbox should be coded? Value? Normally there are: true, false and ??
> 
> ?
> 
> > More btn
> 
> Size could be controlled via "style" and "darkStyle". Icon is only possible as base64 or href to "admin/backitup/iconNAME.png".
> 
> What the function should have 



> > Where should progress get the value?
> 
> ?

So far I have controlled the progress bar via script.  As an an example.  when backitup is called up for the restore from the cloud, the progress bar runs until the result is available.  WHEN THE PROCESS IS DONE, I'll hide them.  keep everything in the script


> > How the indeterminate checkbox should be coded? Value? Normally there are: true, false and ??

false and true is perfect


> > More btn
> 
> Size could be controlled via "style" and "darkStyle". Icon is only possible as base64 or href to "admin/backitup/iconNAME.png".

perfect 👍🏻
> What the function should have button? Now it can set state and send message via sendTo.

href for open a url was perfect. 

Certainly there are a lot more functions in the current version that are not yet so clear to me from the documentation.  Fronted is not the yellow of the egg for me yet 😀

**Comment by GermanBluefox** [comment]
@simatec It will not be possible to create the JsonConfig for backitup, because of dynamic list for "restores".

**Comment by GermanBluefox** [comment]
> false and true is perfect

But I need a value for "indeterminate". Which one should it be?

Progress bar, could be controlled via state. But you still does not answered the question.

**Comment by simatec** [comment]
> @simatec It will not be possible to create the JsonConfig for backitup, because of dynamic list for "restores".

Yes for dynamic list is this way not possible. 
Backitup would then have to be rewritten directly on react.  

For the suggestions here in the issue, I only looked through my adapters and wrote down all the options used by my adapters.  So far, the suggestions have no specific or planned use for me.  it was just suggestions from me.

**Comment by simatec** [comment]
> > false and true is perfect
> 
> But I need a value for "indeterminate". Which one should it be?
> 
> Progress bar, could be controlled via state. But you still does not answered the question.

Unfortunately I cannot answer the question for you.  I don't quite understand the class yet.  I use this here:

https://github.com/simatec/ioBroker.backitup/blob/070fa0a721dea029fa518276c4840691cdde6f8d/admin/tab_m.html#L420

**Comment by GermanBluefox** [comment]
> > > false and true is perfect
> > 
> > 
> > But I need a value for "indeterminate". Which one should it be?
> > Progress bar, could be controlled via state. But you still does not answered the question.
> 
> Unfortunately I cannot answer the question for you. I don't quite understand the class yet. I use this here:
> 
> https://github.com/simatec/ioBroker.backitup/blob/070fa0a721dea029fa518276c4840691cdde6f8d/admin/tab_m.html#L420

Ok. if not true and not false => indeterminate

**Comment by simatec** [comment]
helpLink is running ... many thanks
![image](https://user-images.githubusercontent.com/39792461/116396299-809d9780-a825-11eb-91e5-f42208645bc8.png)

**Comment by GermanBluefox** [comment]
Accordion is implemented too.

I still don't know where to get data for progress and how to use indeterminate. 

Do you have use case for indeterminate?

**Comment by simatec** [comment]
Unfortunately, I do not currently have a direct application.  
The idea is to show the progress as a graphic when a request, fetch or the same is heard via the GUI with a button or when opening the GUI.  
So far I've only heard this in js.  

With the adapter Pegelalarm I open the progress when starting the GUI with show() and this is hidden with hide() if the application belongs to the API and the selection is menus with data sequences

**Comment by GermanBluefox** [comment]
Ok. only timepicker left
