### ISSUE TITLE
Admin 5.0.7 : bubble im protokoll wird nicht aktualisiert

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#753]
![grafik](https://user-images.githubusercontent.com/6681528/115967307-3b7e1a80-a532-11eb-975c-6b5c55298d3d.png)

nachdem ich das Log gelöscht habe.. ist die bubble imer noch da

![grafik](https://user-images.githubusercontent.com/6681528/115967324-53ee3500-a532-11eb-8daf-919cf9e6af63.png)

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by Feuer-sturm** [comment]
Admin 5.0.10

@GermanBluefox What is your expectation for deleting the bubble with the number of warning.
I have a blockly which creates a warning. The bubble (1) will be shown. By clicking on the menu for logging the bubble will be deleted.
Is it how it should work?

![Animation1](https://user-images.githubusercontent.com/25422320/116322151-be65d600-a7bb-11eb-8bd7-7bd888f757c4.gif)

**Comment by GermanBluefox** [comment]
> Admin 5.0.10
> 
> @GermanBluefox What is your expectation for deleting the bubble with the number of warning.
> I have a blockly which creates a warning. The bubble (1) will be shown. By clicking on the menu for logging the bubble will be deleted.
> Is it how it should work?
> 
> ![Animation1](https://user-images.githubusercontent.com/25422320/116322151-be65d600-a7bb-11eb-8bd7-7bd888f757c4.gif)

Yes. If the user is in the log already, he must be not informed about errors as he is seeing them

**Comment by Feuer-sturm** [comment]
In Admin4 the Log item was colored red if there are errors in the shown log even in the case the users switched to the log menu item and switched back to another menu item

![grafik](https://user-images.githubusercontent.com/25422320/116476232-38a95f80-a87b-11eb-9e94-2baa384143d3.png)

From my point of view it would be helpful to have some indicator if there are some warnings / errors in the shown log and not just removing this indicator if the log menu is entered.

**Comment by Apollon77** [comment]
The indicator in Admin5 is a "Bubble" with yellow or red depending if warnings or error are there.

**Comment by Feuer-sturm** [comment]
@Apollon77 correct. I had expected that the bubble will stay if I enter and leave the log menu if there are warnings or errors. In Admin4 it works like this.

**Comment by GermanBluefox** [comment]
But now it works in other way

**Comment by Feuer-sturm** [comment]
Ok :-)
