### ISSUE TITLE
Admin 5.0.8 - Expert mode can not be entered

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#755]
Admin 5.0.8

After enabling expert mode (icon is green) the red wrench will not be shown. It is not possible to enter the expert mode settingss.

![grafik](https://user-images.githubusercontent.com/25422320/115971622-c7e80780-a549-11eb-8950-a8b3208bd0e5.png)

**Comment by Apollon77** [comment]
The host system settings got moved to the host tab. That is better then in main menu :-)

**Comment by Feuer-sturm** [comment]
Ahhh :-) I found it.
