### ISSUE TITLE
Admin 5 easy site

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#756]
If you click in the upper left corner on iobroker logo, a new blank site opens: iobroker:8081/#easy

i don´t know, maybe it´s not finished or it´s a bug

**Comment by Apollon77** [comment]
This should only come when you have enabled the easy admin ... Show your Admin settings please - there is an "Access to instances" tab

**Comment by Feuer-sturm** [comment]
@Apollon77 With Admin 5.0.8  I get the white screen as well by clicking in the left corner on the icon.

Browser console:
![grafik](https://user-images.githubusercontent.com/25422320/115973834-451a7900-a558-11eb-93ad-d08593a654ad.png)

"Access to instances" tab
![grafik](https://user-images.githubusercontent.com/25422320/115973837-52cffe80-a558-11eb-9e96-2d585e436f24.png)

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by amg666** [comment]
5.0.9 firefox/firefox nighlty, chrome, opera: It does NOT work (still empty screen)

**Comment by GermanBluefox** [comment]
> 5.0.9 firefox/firefox nighlty, chrome, opera: It does NOT work (still empty screen)

Browser console? Errors?

**Comment by zalash333** [comment]
Fixed in 5.0.10.
