### ISSUE TITLE
Admin 5 mobile Ansicht

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#758]
Auf meinem Smartphone nutze ich immer sehr kleine Schriftarten um alles auf einem Blick sehen zu können, in der mobilen Ansicht ist die Schrift sehr groß:
![Screenshot_20210424-223312](https://user-images.githubusercontent.com/18234371/115972520-25cb1e00-a54f-11eb-8340-fd10c7f32867.png)
wenn ich desktopwebseite in chrome aktivere, dann kann man es super lesen, wäre toll dies auch in der mobilen Ansicht so zu sehen:
![Screenshot_20210424-223235](https://user-images.githubusercontent.com/18234371/115972546-501cdb80-a54f-11eb-8c72-60c98ba8c2a2.png)

In Instanzen kann man überhaupt nichts erkennen:
![Screenshot_20210424-230109](https://user-images.githubusercontent.com/18234371/115972867-4d22ea80-a551-11eb-9e4f-bc63197b6618.png)

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by Feuer-sturm** [comment]
Admin 5.0.10

@GermanBluefox 
Instances
Is it possible to have some smaller icons and some more space between status lamp and the icon?

![grafik](https://user-images.githubusercontent.com/25422320/116318585-45fc1680-a7b5-11eb-8555-cd9a6c1db7fd.png)


Log looks better
![grafik](https://user-images.githubusercontent.com/25422320/116318293-d71ebd80-a7b4-11eb-809c-7c90231c67d9.png)

**Comment by santa81** [comment]
unter Objekte ist die Schrift auch zu groß. Name wird irgendwie nicht angezeigt egal ob aktiviert oder nicht. Manuell Breite angeben hat auf die schnelle auch nicht funktioniert. Kann man da auch % statt Pixel angeben?![Screenshot_20210428-233101.png](https://user-images.githubusercontent.com/18234371/116504050-c99e2c00-a8b7-11eb-9d6c-f6829ed7781a.png)

**Comment by Feuer-sturm** [comment]
Admin 5.0.12
@GermanBluefox @Apollon77 

Instances Menu is fixed. Icons of adapter has now a good size :-)
![grafik](https://user-images.githubusercontent.com/25422320/116813925-a349ec00-ab56-11eb-9c0b-363b86447d52.png)


Object View
Size is ok from my point of view and the correct value in coloum "Wert" is available
![grafik](https://user-images.githubusercontent.com/25422320/116813938-b492f880-ab56-11eb-9113-a3c40e8c3fcd.png)

It is possible to adapt the size of the coloums and the content of "Name" is available
![grafik](https://user-images.githubusercontent.com/25422320/116814105-6e8a6480-ab57-11eb-82b3-1a9b1ab4bcf9.png)
