### ISSUE TITLE
Admin 5 Instanzen

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#759]
Das Grün im Hintergrund finde ich im darkmode sehr unschön. Vorne der grüne Punkt reicht doch völlig aus. Wäre das möglich, so wirken die einzelnen Seiten von iobroker nicht einheitlich.

Zusätzlich wäre auch eine bessere Platzausnutzung der einzelnen Spalten möglich bei größeren Auflösungen. Dann wären auch alle Spalten gerade in jeder Zeile an der selben Stelle bei langen Namen.

![grafik](https://user-images.githubusercontent.com/18234371/115972903-88251e00-a551-11eb-8a93-d81a065b5516.png)

**Comment by GermanBluefox** [comment]
Ob das schön oder unschön ist, ist sehr subjektiv

**Comment by santa81** [comment]
das ist mir klar und ich scheine damit auch alleine zu sein. Alles andere finde ich auch sehr gelungen aber das passt meiner Meinung nach nicht rein. 
ich wollte damit auch niemanden beleidigen oder so, ich wenn sonst niemand so empfindet dann kann dies hier geschlossen werden.

**Comment by GermanBluefox** [comment]
Layout wurde angepasst
