### ISSUE TITLE
Objekte - Hinzufügen und Sichern von Objekten zum Teil nicht möglich

### ISSUE THREAD

**Issue by BramTown** [ioBroker/ioBroker.admin#761]
Im Objekte Tab sind bei der Auswahl eines Ordners in dem meisten Fällen weder das Hinzufügen eines neuen Objektes möglich ("+" ist ausgegraut), noch die Sicherung als json (Download Pfeil steht nicht zur Verfügung).

z.B.:
"**0_userdata**" - sichern **nicht** möglich / neues Objekt hinzufügen **nicht** möglich (+)
"**0_userdata.0**" - sichern **möglich** / neues Objekt hinzufügen **möglich** (+)
"**0_userdata.0.gewerke.lampen**" - sichern **nicht** möglich / neues Objekt hinzufügen **nicht** möglich (+)

und das zieht sich im Grunde durch alle Objektbäume - meistens ist weder sichern noch hinzufügen möglich

Ein json Upload scheint hingegen überall möglich zu sein.

**Comment by Apollon77** [comment]
Bitte genau prüfen ob da wirklich Objekte existieren!! Existierende haben eine Rolle ... sonst keine
* 0_userdata existier bei definition nicht
* 0_userdata.0 ist ein exitsierendes Objekt, daher geht alles
* 0_userdata.0.gewerke.lampen ... annahme: Du hast nur die Unterstrukturen angelegnt als objekte aber das "mutterobjekt" fehlt (kann channel sein oder folder).
Dann wäre es "as designed"

**Comment by BramTown** [comment]
Das war zuvor anders.
Ich konnte zuvor auch mehr Ebene einfügen
nun ist nach Gerät -> Kanal -> Datenpunkt schluss

Zuvor Konnte ich so viele Kanäle wie ich wollte ineinander verschachteln :-(

**Comment by Apollon77** [comment]
> Zuvor Konnte ich so viele Kanäle wie ich wollte ineinander verschachteln :-(

Was formal entgegen der Spezifikation ist. :-) Die definition isz device.channel.state (wenn man diese struktur nutzt) oder device.state/channel.state ... sonst gibt es "folder".
Aber ja Folder und sowas sollte gehen an sich immer ...

@GermanBluefox ? Do we really enforce that structure now?

**Comment by sjfm-design** [comment]
gestern selbes problem:
https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/272?_=1619643628936

**Comment by GermanBluefox** [comment]
Nur folgende Kombinationen sind erlaubt:

Folder=>state
Folder=>channel=>state
Folder=>device=>channel=>state
Channel =>state
device=>channel=>state

Nicht Experte dürfen nur in 0_userdata.0 oder alias.0 die Objekte erzeugen. 
Experte dürfen überall, aber ab zweite Ebene (z.B. vis.0 oder javascript.0) die Objekte erzeugen. 

Falls ihr irgendwas anders versucht zu machen, dann geht das nicht mehr

**Comment by Apollon77** [comment]
@GermanBluefox Vllt eine IDee einentoltip zu machen wenn button ausgegraut und irgendwie diese Info zur nötigen Struktur als "hilfetext" anzubieten?

**Comment by GermanBluefox** [comment]
Tooltip added

**Comment by Feuer-sturm** [comment]
5.0.18
Tooltip vorhanden:
![grafik](https://user-images.githubusercontent.com/25422320/117516779-4ad17f00-af9a-11eb-9851-20a2d2d9bf78.png)
