### ISSUE TITLE
Instanzen Icons Admin5

### ISSUE THREAD

**Issue by MCepheus** [ioBroker/ioBroker.admin#762]
Erst einmal danke für die tolle Arbeit. Die Auffrischung der Optik ist wirklich gut gelungen. Was noch neues "unter der Haube" steckt kann ich noch nicht beurteilen ;)
Nun eine kurze Anmerkung zu den Instanzen in Listenansicht. 
Ich benutze die Listenansicht sehr gerne, da man dort, meiner Meinung nach, eine schnellere Übersicht bekommt. Allerdings orientiere ich mich auch hier primär an den Icons um die Instanzen zu identifizieren und weniger an den Instanzennamen. Nun habt ihr die Icons in dieser Ansicht weggelassen. Die Ansicht wirkt nun zwar "cleaner", nur leidet für mich die Übersichtlichkeit dadurch.
Vielleicht besteht die Möglichkeit die Icons wieder einzusetzen?

**Comment by GermanBluefox** [comment]
Please test 5.0.9

**Comment by Feuer-sturm** [comment]
Admin 5.0.10
@GermanBluefox 
Icons are available
![grafik](https://user-images.githubusercontent.com/25422320/116317876-3defa700-a7b4-11eb-8ca1-a25eb0c81a30.png)
