### ISSUE TITLE
Object edit auf iPad 

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.admin#763]
Wenn ich auf dem iPad schaue, ist die oberste Übersichtszeile unter „Instanzen“ nicht korrekt dargestellt und unter „Objekten“ sind die „Objektdaten“ nicht sichtbar. 

![B8F731FC-B6EB-47D3-9DE2-78F8141C55D5](https://user-images.githubusercontent.com/56205459/116003389-1060fd00-a5fe-11eb-8b4b-628277df33a6.jpeg)
![A9127122-0769-41BD-BFE0-01F7479A16E5](https://user-images.githubusercontent.com/56205459/116003391-148d1a80-a5fe-11eb-845f-90631545b04a.jpeg)

Vielen Dank

EDIT: Das Problem mit der ersten Zeile ist auch auf der "Adapterseite" zu beobachten wenn Kachlen dargestellt werden. Bei der Listenansicht ist das Problem nicht vorhanden.

**Comment by GermanBluefox** [comment]
Was für einen Objekt-Type hat smartmeter.0.1xxx.value?

**Comment by Apollon77** [comment]
Normalerweise je nach inhalt number oder string - also "so sollte es sein" :-)

**Comment by MMeinhardt1** [comment]
Hier ein Bild der Objektdaten. Auf dem Notebook funktioniert es, nur eben auf den Apfelgeräten nicht.

![objektdaten](https://user-images.githubusercontent.com/56205459/117416875-18803d00-af1a-11eb-9f1c-5cf35fd374a0.PNG)

Danke

**Comment by GermanBluefox** [comment]
Dann muss da ein Fehler in der Browser console sein.

**Comment by MMeinhardt1** [comment]
Auf den iPads gibt es leider keine direkte Konsole. Man kann das nur "remote" von einem Safari Browser aus machen, so wie ich es gelesen habe. Einen Mac haben wir aber leider nicht. Ich schaue mal ob das auch irgendwie anders funktionieren kann.

**Comment by GermanBluefox** [comment]
Ich vermute iPad verschluck sich bei der Anzeige vom Ace-Editor

**Comment by Tagiwara** [comment]
Ich habe ein ähnliches Anzeigeproblem beim IMac... beim FF, Chrome und Safari überlagert das obere Banner die darunterliegenden Schaltflächen.
![1621361016654-bildschirmfoto-2021-05-18-um-20 00 26](https://user-images.githubusercontent.com/41060053/118757482-7f341d80-b86d-11eb-9cff-5b6854e06ddd.jpg)

**Comment by GermanBluefox** [comment]
> Ich habe ein ähnliches Anzeigeproblem beim IMac... beim FF, Chrome und Safari überlagert das obere Banner die darunterliegenden Schaltflächen.
> ![1621361016654-bildschirmfoto-2021-05-18-um-20 00 26](https://user-images.githubusercontent.com/41060053/118757482-7f341d80-b86d-11eb-9cff-5b6854e06ddd.jpg)

Bitte neue Issue anlegen
