### ISSUE TITLE
Admin 5.0.8: Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by chefkoch009** [ioBroker/ioBroker.admin#764]
Fehler beim Laden der Instanzen im Admin5:

Instances.js:353 Uncaught (in promise) TypeError: Cannot read property 'compact' of undefined
    at Instances.js:353

Instanzen werden nicht angezeigt.

**Comment by chefkoch009** [comment]
nach installation von Redis und umstellen von states und objects auf redis funktioniert es.

**Comment by Apollon77** [comment]
Kann an sich nichts miteinander zu tun haben

**Comment by GermanBluefox** [comment]
Please test 5.0.9
