### ISSUE TITLE
DarkMode autoChange 

### ISSUE THREAD

**Issue by chochb** [ioBroker/ioBroker.admin#767]
- Please install an automatic dark mode change. According to original time and / or the beginning of sunset

- Alternatively, an object (on / off) is sufficient for DarkMode. So that everyone could build it himself.

Or maybe booth (automatic and object)?

thx

Christoph

**Comment by GermanBluefox** [comment]
It takes system color theme by default if it is not set. But of course it does not check it every minute if it changed

**Comment by GermanBluefox** [comment]
I will close this request, as Admin5 selects automatically dark or light theme depends on system settings. But of course it does switch it if system changes the theme
