### ISSUE TITLE
Admin 5.0.8 - Unreadable comments in rating tab

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#772]
**Describe the bug**  

After submitting a new rating with comment, the comment is not readable (black text on dark blue background).

**To Reproduce**  

1. Rate an adapter and create a new rating with a comment
2. Close the rating popup
3. Click on the rating stars to see existing ratings

**Screenshots & Logfiles**  

<img width="622" alt="Screenshot 2021-04-27 at 09 00 11" src="https://user-images.githubusercontent.com/1959049/116199168-1ad2e200-a737-11eb-9fd3-7041ac8a729d.png">

**Versions:**  
 - Adapter version: 5.0.8

**Comment by Apollon77** [comment]
Background is a bit too dark with black writing color

**Comment by Feuer-sturm** [comment]
Admin 5.0.10

Both version are easy to read
Dark mode
![grafik](https://user-images.githubusercontent.com/25422320/116319692-44cbe900-a7b7-11eb-8415-bb7589d27f46.png)


Bright mode
![grafik](https://user-images.githubusercontent.com/25422320/116319770-65943e80-a7b7-11eb-98a5-3ae43f40a6d1.png)
