### ISSUE TITLE
Admin 5.0.10 - Adapter Version/Downgrade missing

### ISSUE THREAD

**Issue by skvarel** [ioBroker/ioBroker.admin#776]
Adapter Version-Info and Downgrade not possible

**Version 5.0.10**

![grafik](https://user-images.githubusercontent.com/1114419/116347081-cc334f80-a7eb-11eb-94a2-c2ff54fcc441.png)

![grafik](https://user-images.githubusercontent.com/1114419/116347147-f553e000-a7eb-11eb-885f-e9f674a56777.png)

**Comment by skvarel** [comment]
Version 5.0.8

![grafik](https://user-images.githubusercontent.com/1114419/116348284-1c131600-a7ee-11eb-8d0d-b23ea27de702.png)

**Comment by GermanBluefox** [comment]
Sorry no issues accepted for admin4

**Comment by Apollon77** [comment]
@skvarel Whyt is meaned here is: Please try theReact UI ... Admin5  prepares stuff for this and yes this feature is a difficult one because works different
