### ISSUE TITLE
Dropdown List does not work in React Mode

### ISSUE THREAD

**Issue by schmupu** [ioBroker/ioBroker.admin#778]
**Describe the bug**  
Im React Modus funktioniert das Dropdown Menü nicht mehr:

React Mode:
![1619242990292-989cd128-b481-43d0-81ce-d764984379ec-image](https://user-images.githubusercontent.com/38919572/116464657-87033200-a86c-11eb-958e-28da77dac2fe.png)

Old Mode:
![1619243094114-079252db-449a-49d2-a611-560b2944aac1-image](https://user-images.githubusercontent.com/38919572/116464826-b7e36700-a86c-11eb-9ba7-a23f5ea768ad.png)

**Additional Infos**
```
{
  "type": "state",
  "common": {
    "type": "number",
    "role": "value",
    "name": "Keypad Haustür (Tastern 4-6)",
    "read": true,
    "write": true,
    "states": "5:Einbruchalarm;6:Rauch;7:Medizinischer Alarm;8:Wasser;9:Stiller Alarm;10:Panic Alarm;11:Notfall Alarm;15:Notfall Alarm (Still);12:Feuer;13:CO Alarm;18:Gas Alarm;19:Hitze Alarm;100:Sensor-Event anwenden 1;101:Sensor-Event anwenden 2;102:Sensor-Event anwenden 3;103:Sensor-Event anwenden 4;104:Sensor-Event anwenden 5;105:Sensor-Event anwenden 6;106:Sensor-Event anwenden 7;107:Sensor-Event anwenden 8;108:Sensor-Event anwenden 9;109:Sensor-Event anwenden 10;110:Sensor-Event anwenden 11;111:Sensor-Event anwenden 12;112:Sensor-Event anwenden 13;113:Sensor-Event anwenden 14;114:Sensor-Event anwenden 15;115:Sensor-Event anwenden 16;150:Szene anwenden 1;151:Szene anwenden 2;152:Szene anwenden 3;153:Szene anwenden 4;154:Szene anwenden 5;155:Szene anwenden 6;156:Szene anwenden 7;157:Szene anwenden 8;158:Szene anwenden 9;159:Szene anwenden 10;160:Szene anwenden 11;161:Szene anwenden 12;162:Szene anwenden 13;163:Szene anwenden 14;164:Szene anwenden 15;165:Szene anwenden 16",
    "icon": "/icons/37.png"
  },
  "native": {},
  "from": "system.adapter.lupusec.0",
  "user": "system.user.admin",
  "ts": 1556480927321,
  "_id": "lupusec.0.devices.RF:00681870.sresp_button_456",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.user"
  }
}
```

**Versions:**  
 - Adapter version: 5.0.10
 - JS-Controller version: 3.2.16 
 - Node version: v12.22.1
 - Operating system: Linux (Ubuntu)

**Comment by Apollon77** [comment]
Hm ... this kind of states definition do not really match to the definition.

>     "states": "5:Einbruchalarm;6:Rauch;7:Medizinischer Alarm;8:Wasser;9:Stiller Alarm;10:Panic Alarm;11:Notfall Alarm;15:Notfall Alarm (Still);12:Feuer;13:CO Alarm;18:Gas Alarm;19:Hitze Alarm;100:Sensor-Event anwenden 1;101:Sensor-Event anwenden 2;102:Sensor-Event anwenden 3;103:Sensor-Event anwenden 4;104:Sensor-Event anwenden 5;105:Sensor-Event anwenden 6;106:Sensor-Event anwenden 7;107:Sensor-Event anwenden 8;108:Sensor-Event anwenden 9;109:Sensor-Event anwenden 10;110:Sensor-Event anwenden 11;111:Sensor-Event anwenden 12;112:Sensor-Event anwenden 13;113:Sensor-Event anwenden 14;114:Sensor-Event anwenden 15;115:Sensor-Event anwenden 16;150:Szene anwenden 1;151:Szene anwenden 2;152:Szene anwenden 3;153:Szene anwenden 4;154:Szene anwenden 5;155:Szene anwenden 6;156:Szene anwenden 7;157:Szene anwenden 8;158:Szene anwenden 9;159:Szene anwenden 10;160:Szene anwenden 11;161:Szene anwenden 12;162:Szene anwenden 13;163:Szene anwenden 14;164:Szene anwenden 15;165:Szene anwenden 16",

Definition is:
> common.states (optional) attribute of type number with the object of possible states {'value': 'valueName', 'value2': 'valueName2', 0: 'OFF', 1: 'ON'}

**Comment by GermanBluefox** [comment]
Admin 5.0.11 could handle it

**Comment by schmupu** [comment]
works fine! Thanks
