### ISSUE TITLE
Admin 5.0.10: File manager doesn't support blank in file name

### ISSUE THREAD

**Issue by FredF63** [ioBroker/ioBroker.admin#779]
Such files can't be up or down loaded
![1619633678808-2dcf10f6-a0c3-41d2-b028-5e8f31accd27-grafik](https://user-images.githubusercontent.com/43332106/116503511-98712c00-a8b6-11eb-94ed-76e9be37ed2f.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.12

**Comment by Feuer-sturm** [comment]
Admin 5.0.12

Folders with spaces - ok
Upload file with spaces  - ok 
download file with spaces - ok

![grafik](https://user-images.githubusercontent.com/25422320/116822967-069d4380-ab82-11eb-98b8-8b12d233562e.png)

**Comment by Feuer-sturm** [comment]
There are problems with deleting folders

A few minutes I created a folder temp und currently there is no content in this folder in the UI. If I click the delete button the following error will be prompted in the browser console
![grafik](https://user-images.githubusercontent.com/25422320/116823355-5715a080-ab84-11eb-89b3-f66d19946a3c.png)
![grafik](https://user-images.githubusercontent.com/25422320/116823311-000fcb80-ab84-11eb-93f8-694229e77b7b.png)

If I have a look in the folder structure in vis.0 my previous created tempmytemp and "temp ordner" folders are still there and in the "temp" folder which makes the problem in the UI there is a subfolder.
![grafik](https://user-images.githubusercontent.com/25422320/116823426-c25f7280-ab84-11eb-8a7b-8730ca9404fe.png)



![grafik](https://user-images.githubusercontent.com/25422320/116823503-3863d980-ab85-11eb-9d32-92ae49259242.png)



Steps to reproduce:
- create a folder "tempNew"
- upload an image in this new folder
- press delete icon of the folder
-- icon in the folder will be deleted
-- folder will stay but delete icon is not available any more
- press button "Dateien neue laden" in the React UI
- folder "tempNew" will not be shown in the UI but it is still there on the disc
