### ISSUE TITLE
Admin Adaptername fehlt

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#780]
Admin-Info: Bei Aktualisierungen wird beim Admin Adapter nicht der Adaptername (Admin) angezeigt sondern nur dass es eine Aktualisierung gibt
![grafik](https://user-images.githubusercontent.com/45561610/116513416-d6c41680-a8c9-11eb-94e3-9c4dad6560b4.png)

Das der Admin Adaptername nicht angezeigt wird, sehe ich auch in der Adapterübersicht, da ist der Name "Admin" nur in der Headline aber nicht in der Kachel mit den Infos:
![grafik](https://user-images.githubusercontent.com/45561610/116514192-fc055480-a8ca-11eb-98e0-dd44248304f6.png)

Admin Adapter 5.0.10 und 5.0.11
Getestet mit Firefox und Opera
Intel NUC mit VM Debian10
Node.js: v14.16.1
NPM: 6.14.12

**Comment by Apollon77** [comment]
Fix kommt mit js-controller 3.3
