### ISSUE TITLE
Admin 5 React: Provide color-scheme as css for materialize-adapters

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#782]
With the new ract-ui some design changes took place, so the old adapter config pages (index_m.html) do not fit to the new design, especialy if you switch the color scheme to dark mode.

I adjustet my css to best fit to the new design (standard color-scheme), but i have no idea how to figure out, if another color-scheme (dark mode) is used.

a) Question: How can i get the acutal color scheme? And if react-ui is active?

b) I think it makes sense to provide the design changes to all the old adapters by adjusting the used css.

If wanted, i can work out the needed css-modifications for the colour-schemes.

But i have no idea, where these need to be implementd in the admin-adapter, so you would have to do that or show me how to do it.

Greetings

**Comment by GermanBluefox** [comment]
I switched off the dark mode for older adapters, as the text was unreadable.
But I can activate it again.
The CSS must be updated here: https://github.com/ioBroker/ioBroker.admin/blob/master/src/less/adapter.less#L238

**Comment by sbormann** [comment]
OK, but how can i test it? Where is the path compiled css-file?

**Comment by GermanBluefox** [comment]
> OK, but how can i test it? Where is the path compiled css-file?

This must be reanimated and I will do that asap

**Comment by GermanBluefox** [comment]
@sbormann I added the build of less files into build pipeline. Now you can play with colors

**Comment by sbormann** [comment]
I think i need a little starting help. Can you provide me a screenshot or sth. where i can play with the colours?

**Comment by simatec** [comment]
The same goes for me.  I also need some help and a few tips to be able to adjust Backitup in the config and tab

**Comment by sbormann** [comment]
Following suggestion:

From inside the adatper iframe you can access ``windows.parent.adapterName`` (which is "admin" for react environments).

Maybe admin could provide another variable with the actual color-mode.

The adapter-settings.js could then look for changes there and set a corresponding class to the adapter html-tag
(for example ``<html class="color-mode-dark">...``)

Then the standard css-code could be enhanced to respect the colour-sceme depending on the class provided.

So changes in the colour-sceme could be brought dynamically to non-react adapters.

**Comment by simatec** [comment]
But that would mean that all of the more than 400 adapters would have to be adapted.
Since there are some adapters that are not maintained, I would consider adding the class automatically to make more sense

**Comment by sbormann** [comment]
No, i don't think that there is any adapter that has be updated, as all changes are made in the generic adapter-settings.js an the css that iobroker provides.

**Comment by Feuer-sturm** [comment]
@simatec @sbormann @GermanBluefox Is here a open todo in this issue?
