### ISSUE TITLE
Zeit im Protokoll falsch nach Update des Admin-Adapters

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.admin#783]
Hi,
nach einem Update des Admin-Adapters stimmen die Zeiteinträge nicht mehr. Das ganze war mir gestern schon aufgefallen, nach dem Update. Wenn man das Log herunterlädt sieht man den Unterschied denn dort stimmen die Uhrzeiten.

![6BBD4A5E-660F-43E9-9B37-972DF47D24F0](https://user-images.githubusercontent.com/56205459/116572976-b49fb800-a90c-11eb-93a3-5d65eee631ef.png)
![39A9CCA4-6052-408A-A7B1-34A3DA379059](https://user-images.githubusercontent.com/56205459/116573285-f4669f80-a90c-11eb-8b63-f5f4bb11db1b.png)

Danke

EDIT: die Uhr unter „Info“ zeigt die korrekte Uhrzeit an!

**Comment by Apollon77** [comment]
zeitzone auf dem Server ist auch korrekt? Zeitzone auf dem Rechner der Admin anzeigt?

**Comment by MMeinhardt1** [comment]
Unter „Info“ zeigt die dortige analoge Uhr die korrekte Zeit an. Auf den obigen Screenshots dürfte die Uhrzeit des Tablets zu sehen sein. Und auch in den Textauszug des Logs stehen ja die korrekten Uhrzeiten. Der raspi ist richtig konfiguriert.

**Comment by MMeinhardt1** [comment]
Ich habe soeben mal einen Adapter zum Spaß neugestartet, die angezeigten Uhrzeiten mach lustige Sprünge die bestimmt nicht gewollt sind.

![C57FDA0C-34FF-4309-A87C-5DC70C6B72C5](https://user-images.githubusercontent.com/56205459/116591725-795ab480-a91f-11eb-9cb8-424f5b4a953c.png)

**Comment by MMeinhardt1** [comment]
Ist mein Phänomen als Fehler eingestuft? Bin ich der einzige der dieses Problem hat? Kann ich sonst noch etwas testen bzw. kontrollieren um den eventuellen Fehler einzugrenzen?

Vielen Dank und ein schönes Wochenende!

**Comment by GermanBluefox** [comment]
Kann es sein, dass nur Apfel Geräte das haben?

**Comment by MMeinhardt1** [comment]
Das werde ich morgen mal kontrollieren und melde mich dann wieder.

**Comment by MMeinhardt1** [comment]
Hi @GermanBluefox,
auf dem Notebook mit Firefox sind die Zeiten in der Tat korrekt, scheint also ein apfeltechnisches Problem zu sein. Aber warum? Und warum erst nach letzten Updates? Vorher war es definitiv NICHT so.

Schönen 1. Mai

**Comment by MMeinhardt1** [comment]
Wenn das log offen ist und neue Ereignisse geschrieben werden stimmen die Uhrzeiten, hier ein Bild zur Info.

![0A3C5CF7-5947-4E68-BC1B-864772D67B9D](https://user-images.githubusercontent.com/56205459/118407600-c1990700-b681-11eb-9e63-767e51e9988e.png)

**Comment by Apollon77** [comment]
So fixed?

**Comment by MMeinhardt1** [comment]
Nein, leider nicht.

**Comment by GermanBluefox** [comment]
Fixed in 5.0.28

**Comment by MMeinhardt1** [comment]
Sobald verfügbar werde ich testen und berichten, vorab schon mal vielen Dank!

**Comment by MMeinhardt1** [comment]
V5.0.28 installiert und die Zeiten im Log sind jetzt korrekt.
@GermanBluefox, ich danke Dir vielmals für die tolle Arbeit!
