### ISSUE TITLE
Ovewview Screen no longer loadin in 5.0.11

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#784]
<img width="1657" alt="Bildschirmfoto 2021-04-30 um 00 02 31" src="https://user-images.githubusercontent.com/11976694/116623978-665bda80-a947-11eb-8ddd-477ff0ae020b.png">

**Comment by Matt77CHE** [comment]
bei mir auch, seit dem vorletzten update vom controller oder vom admin-adapter. auch mit dem neuesten controller immer noch so.

**Comment by GermanBluefox** [comment]
Fixed in 5.0.12

**Comment by GermanBluefox** [comment]
> bei mir auch, seit dem vorletzten update vom controller oder vom admin-adapter. auch mit dem neuesten controller immer noch so.

Auch gleicher Fehler im Browser log?

**Comment by Matt77CHE** [comment]
![Unbenannt](https://user-images.githubusercontent.com/73795309/116775257-67355f00-aa62-11eb-9de0-43bda403f48c.JPG)

**Comment by GermanBluefox** [comment]
Es ist ein anderen Fehler. Kannst du mit geöffnetem KonsoleFenster F5 drücken, dann sollten die map files geladen werden und ich kann besser sehen, wo der Fehler passiert ist.

**Comment by GermanBluefox** [comment]
@Matt77CHE kann es sein, dass du versuchst Admin4 mir zu zeigen?

**Comment by Matt77CHE** [comment]
ähhm, beim Admin4 weiss ich nicht was du meinst - was ist das?

**Comment by Matt77CHE** [comment]
so?

![Unbenannt](https://user-images.githubusercontent.com/73795309/116775941-31927500-aa66-11eb-8cf3-0d242585346c.JPG)

**Comment by Matt77CHE** [comment]
![Unbenannt](https://user-images.githubusercontent.com/73795309/116776009-afef1700-aa66-11eb-9469-9082bd263add.JPG)

**Comment by GermanBluefox** [comment]
> so?
> 
> ![Unbenannt](https://user-images.githubusercontent.com/73795309/116775941-31927500-aa66-11eb-8cf3-0d242585346c.JPG)

Viel besser!

**Comment by Matt77CHE** [comment]
@GermanBluefox das Problem besteht auch noch mit 5.0.12;
Habe soeben Host, Admin etc updated - immernoch kein Inhalt bei Übersicht....

![Unbenannt](https://user-images.githubusercontent.com/73795309/116807978-8998ac80-ab36-11eb-938e-afca9298d36a.JPG)
