### ISSUE TITLE
Admin 5.0.11 react ui Benutzer View ist weiß 

### ISSUE THREAD

**Issue by Cosmicbase** [ioBroker/ioBroker.admin#785]
Seit der Version admin 5.0.11 react ui funktioniert der "Instanzen" Reiter wieder. 
Einstellungen am "Benutzer" Reiter funktionieren leider noch nicht. Die Seite ist weiterhin weiß. 

![Screenshot_20210430_125815_com android chrome](https://user-images.githubusercontent.com/31271212/116686292-e586f800-a9b3-11eb-80ca-d1b25f7aba54.jpg)

 - js-controller 3.1.6 
 - nodejs v16
 - npm 7.10

**Comment by GermanBluefox** [comment]
Please report browse console error!

**Comment by Ilovegym66** [comment]
@Cosmicbase  don t use npm7x.. ! you have js-controller 3.1.6 and node 16 and npm 7.. very mixed and not verified setup..

@GermanBluefox I miss the group "Admin" where are there gone?? :-) how can I add a user to admin? or new users already admins?`hmm?
![grafik](https://user-images.githubusercontent.com/36229898/116703034-15d99100-a9ca-11eb-9605-6ef16f90fa14.png)

**Comment by GermanBluefox** [comment]
> @Cosmicbase don t use npm7x.. ! you have js-controller 3.1.6 and node 16 and npm 7.. very mixed and not verified setup..
> 
> @GermanBluefox I miss the group "Admin" where are there gone?? :-) how can I add a user to admin? or new users already admins?`hmm?
> ![grafik](https://user-images.githubusercontent.com/36229898/116703034-15d99100-a9ca-11eb-9605-6ef16f90fa14.png)

I have no idea, where you admin group is. 
Mine is on place:
![image](https://user-images.githubusercontent.com/4582016/116725914-e1260380-a9e2-11eb-8ab6-8c160a34d75d.png)

What about object `system.group.administrator` ? Does it exist?

**Comment by Ilovegym66** [comment]
yes, it exists.. 
![grafik](https://user-images.githubusercontent.com/36229898/116726389-7cb77400-a9e3-11eb-8e03-f3375326e192.png)

and now the group is shown...
![grafik](https://user-images.githubusercontent.com/36229898/116726529-b7211100-a9e3-11eb-9dbe-03896cd5f35d.png)

only thing what I'd done, was a reboot.. okay..

**Comment by Cosmicbase** [comment]
Ich habe jetzt nodejs 14.16.1 und die dazugehörige npm 6.14.12 installiert, Neustart und trotzdem ist der Benutzer View weiß. 
Also liegt es weder an Nodejs 16, noch an npm 7.10.

Für weitere Infos wäre ich sehr dankbar :)

**Comment by GermanBluefox** [comment]
> Users tab is not complete yet in Admin5

Completed in last version

**Comment by GermanBluefox** [comment]
> Ich habe jetzt nodejs 14.16.1 und die dazugehörige npm 6.14.12 installiert sowie Neustart. Trotzdem ist der Benutzer View weiß.
> Also liegt es weder an Nodejs 16, noch an npm 7.10.
> 
> Für weitere Infos wäre ich sehr dankbar :)

Ich brauche BROWSER CONSOLE output um weiter zu kommen
