### ISSUE TITLE
available version of adapters not up to date

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#786]
in the admin panel of adapters, the available version ist not really the actual one.
may be a refresh issue.
starting the update will install a newer version then indicated

https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/270?_=1619769188294

**Comment by Marty56** [comment]
This bug is also affection the stable version 4.2.1.
Although it indicates new updates correctly but it does not update "admin.0.info.newUpdates" when updates have been installed.
In other words the "admin.0.info.newUpdates" stays "true" forever.

**Comment by Marty56** [comment]
Thanks for the hint. It seems to be same issue.

**Comment by GermanBluefox** [comment]
Please retest with 5.0.21
