### ISSUE TITLE
File admin/index.html not found: {}

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.admin#788]
Iobroker admin 5.0.11. Browsercache gelöscht
JS- Controller 3.3.1
Web 3.4.0

Seit heute morgen kommt diese Meldung :

File admin/index.html not found: {}

nach Anklicken von Admin über Web-Interface der Ip : http://192.168.xxx.yyy:8082/
Alle anderen gehen. Auf die Istanzseite komme ich mit
http://192.168.xxx.yyy:8081/#tab-instances

**Comment by Apollon77** [comment]
@GermanBluefox or is this an "web" issue?

**Comment by GermanBluefox** [comment]
This is web issue

**Comment by GermanBluefox** [comment]
Fixed in Web Adapter
