### ISSUE TITLE
Update of js-controller is not displayed

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#789]
**Describe the bug**  
An update of js-controller is not shown in react ui mode.

**To Reproduce**  
Switch to react ui view and the update is not shown

**Expected behavior**  
An update of js-controller should be shown in react ui mode.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/50245893/116731500-0cf8b780-a9ea-11eb-85cc-deb6aa2c6511.png)

**Versions:**  
 - Adapter version: 5.0.11
 - JS-Controller version: 3.3.2
 - Node version: 12.22.1
 - Operating system: Debian GNU/Linux

**Comment by GermanBluefox** [comment]
Fixed in 5.0.12

**Comment by afuerhoff** [comment]
It works fine for me in 5.0.12 and issue could be closed. But see https://github.com/ioBroker/ioBroker.admin/issues/801
