### ISSUE TITLE
Log Überflutung

### ISSUE THREAD

**Issue by OlfrygtACAB** [ioBroker/ioBroker.admin#790]
Der Log meldet tausende Warnungen
bei verschiedenen Adaptern
was kann man dagegen tun

Sonoff

sonoff.0 | 2021-04-30 19:54:20.119 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.TempUnit" has wrong type "string" but has to be "number"
-- | -- | -- | --
sonoff.0 | 2021-04-30 19:54:20.057 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.DS18B20_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.956 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.934 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-04-30 19:54:19.926 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.Wifi_BSSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.858 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.Wifi_SSId" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.792 | warn | (1593) State value to set for "sonoff.0.Teich-Technik.SleepMode" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.537 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.TempUnit" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.528 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.DS18B20-2_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.520 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.DS18B20-1_Id" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.452 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_Downtime" has wrong type "string" but has to be "number"
sonoff.0 | 2021-04-30 19:54:19.432 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_Channel" has wrong type "number" but has to be "string"
sonoff.0 | 2021-04-30 19:54:19.426 | warn | (1593) State value to set for "sonoff.0.HKV_OG_Temperatur.Wifi_BSSId" has wrong type "string" but has to be "number"

Shelly

shelly.0 | 2021-04-30 19:53:34.677 | warn | (1575) State value to set for "shelly.0.SHDM-1#F3D1D5#1.temperatureF" has value "104.25" greater than max "100"
-- | -- | -- | --
shelly.0 | 2021-04-30 19:53:30.486 | warn | (1575) State value to set for "shelly.0.SHDM-1#F33473#1.temperatureF" has value "108.11" greater than max "100"
shelly.0 | 2021-04-30 19:53:21.602 | warn | (1575) State value to set for "shelly.0.SHDM-1#F3C0E3#1.temperatureF" has value "106.08" greater than max "100"
shelly.0 | 2021-04-30 19:53:19.672 | warn | (1575) State value to set for "shelly.0.SHDM-1#F3D1D5#1.temperatureF" has value "104.25" greater than max "100"
shelly.0 | 2021-04-30 19:53:15.487 | warn | (1575) State value to set for "shelly.0.SHDM-1#F33473#1.temperatureF" has value "108.36" greater than max "100"
shelly.0 | 2021-04-30 19:53:14.654 | warn | (1575) State value to set for "shelly.0.SHSW-25#68C63AF9142D#1.Shutter.Position" has value "-1" less than min "100"

Tankkoenig

tankerkoenig.0 | 2021-04-30 19:55:24.644 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.diesel.short" has been written without ack-flag with value "0"
-- | -- | -- | --
tankerkoenig.0 | 2021-04-30 19:55:24.596 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.diesel.feed" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-04-30 19:55:24.596 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.combined" has been written without ack-flag with value ""
tankerkoenig.0 | 2021-04-30 19:55:24.595 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.3rd" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-04-30 19:55:24.595 | warn | (1843) State value to set for "tankerkoenig.0.stations.9.e10.short" has wrong type "number" but has to be "string"
tankerkoenig.0 | 2021-04-30 19:55:24.594 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.short" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-04-30 19:55:24.594 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e10.feed" has been written without ack-flag with value "0"
tankerkoenig.0 | 2021-04-30 19:55:24.593 | warn | (1843) Read-only state "tankerkoenig.0.stations.9.e5.combined" has been written without ack-flag with value ""

WLED

wled.0 | 2021-04-30 19:54:53.740 | warn | (1781) State value to set for "wled.0.483fda49c0fd._info.mac" has wrong type "string" but has to be "number"
-- | -- | -- | --
wled.0 | 2021-04-30 19:54:32.339 | warn | (1781) State value to set for "wled.0.ecfabcc232d5._info.mac" has wrong type "string" but has to be "number"
wled.0 | 2021-04-30 19:54:28.968 | warn | (1781) State value to set for "wled.0.a4cf12de4a01._info.mac" has wrong type "string" but has to be "number"
wled.0 | 2021-04-30 19:53:49.573 | warn | (1781) State value to set for "wled.0.483fda49c0fd._info.mac" has wrong type "string" but has to be "number"
wled.0 | 2021-04-30 19:53:28.070 | warn | (1781) State value to set for "wled.0.ecfabcc232d5._info.mac" has wrong type "string" but has to be "number"
wled.0 | 2021-04-30 19:53:24.524 | warn | (1781) State value to set for "wled.0.a4cf12de4a01._info.mac" has wrong type "string" but has to be "number"

**Versions:**  
 - Adapter version: 5.0.11
 - JS-Controller version: 3.3.2
 - Node version: v12.22.1
 - Operating system: RasPi

**Comment by Feuer-sturm** [comment]
@OlfrygtACAB Hier findest du die Antwort: https://forum.iobroker.net/topic/44624/js-controller-3-3-jetzt-im-latest/26
Kommt mit js-controller 3.3.x

Da hilft nur Issues bei den jeweiligen Adaptern anlegen (falls es noch keine gibt)
