### ISSUE TITLE
Adaptername fehlt teilweise im Info tab wenn Update verfügbar 

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.admin#791]
Hallo,

im Info tab fehlen teilweise die Namen der Adapter für die ein Update verfügbar ist. 

![08B3B5D0-EC97-4C76-B9A6-8B5D2D3ED70B](https://user-images.githubusercontent.com/56205459/116743393-25240300-a9f9-11eb-986c-d201b591a333.png)

**Comment by simatec** [comment]
Bitte mache dazu ein Issue im Info Adapter auf.
