### ISSUE TITLE
State value

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.admin#792]
ich kann nicht genau nachvollziehen ob es durch das controller-update (beide) oder das admin-update ausgelösst wurde, aber seit den updates bekomme ich im Log von diversen adaptern warnmeldungen wegen state value - und nicht wenige....
vorher keine.

![Unbenannt](https://user-images.githubusercontent.com/73795309/116772658-e91c8c80-aa50-11eb-8d60-405988573cff.JPG)

**Comment by GermanBluefox** [comment]
It is because of js-controller

**Comment by Apollon77** [comment]
@Matt77CHE Please create issues with the respective adapters that generate the warning
