### ISSUE TITLE
Installation "von GITHUB" is different to "Beliebig" with errors

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#793]
**Describe the bug**  
Installation "von GITHUB" is different to "Beliebig".
With GITHUB an error is raised in the log.

**To Reproduce**  
Installation over GITHUB

**Expected behavior**  
Over both ways it should be the same behaviour without errors.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/50245893/116783968-f7d76380-aa91-11eb-8ca1-19cfb82e8d02.png)
![image](https://user-images.githubusercontent.com/50245893/116783983-06257f80-aa92-11eb-9e47-80fb523a431a.png)

**Versions:**  
 - Adapter version: 5.0.11
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: Debian GNU/Linux

**Comment by Apollon77** [comment]
@GermanBluefox that should not use url cli or needs to add iobroker

**Comment by GermanBluefox** [comment]
Fixed in 5.0.12

**Comment by afuerhoff** [comment]
From my side it works fine. Thanks for new feature npm.
