### ISSUE TITLE
Kein Anlegen eines Datenpunktes in den Virtuellen Devices

### ISSUE THREAD

**Issue by gelberlemmy** [ioBroker/ioBroker.admin#795]
Im Ordner für Virtuelle Devices unter Objekte  kann man über die neue Weboberfläche keinen neuen Datenpunkt mit dem + Symbol erstellen. Umschalten auf die alte Ansicht. Dort funktioniert es. 

Admin Adapter 5.0.11
JS Controller 3.2.16

**Comment by Apollon77** [comment]
Was genau möchtest DU erstellen? UND was ist die Struktur "oben drüber"?

**Comment by gelberlemmy** [comment]
Anbei ein Screenshot. Nutze diese um Dinge aus den Skripten darzustellen. Daher sind diese nicht im Alias platziert. Bei der alten Ansicht ist das + in Funktion

![2021-05-02 14_32_15-objects - raspberrypi](https://user-images.githubusercontent.com/20154913/116813383-d474ed00-ab53-11eb-82ca-60992855160d.png)

**Comment by Apollon77** [comment]
DU nbist in der "State change ansicht". Klick mal auf die normale Objektanlsicht (also auf dieses "1" icon ... geht es dort?

**Comment by gelberlemmy** [comment]
Nein auch nicht

**Comment by Apollon77** [comment]
Sber zeig mal bitte screenshot davon

**Comment by gelberlemmy** [comment]
![2021-05-02 14_59_28-Posteingang - lemke andre@me com - Outlook](https://user-images.githubusercontent.com/20154913/116814041-0dfb2780-ab57-11eb-98d3-7323ee2a0a8f.png)

**Comment by Apollon77** [comment]
Then I see the reason. Virtuelle_Devices.0 is a state ... inside a state no other objects are allowed. you need to correct this object first. In general: better migrate away from an own datastriucture and use 0_userdata.0 for own objects

**Comment by GermanBluefox** [comment]
It is not allowed to create children of objects with type "state". Only "folder", "device" or "channel" can have children.
