### ISSUE TITLE
logging with admin5 is very slow

### ISSUE THREAD

**Issue by rg-engineering** [ioBroker/ioBroker.admin#796]
with admin 5 (5.0.11) the logging (especially debug log) is very slow. I see only one log entry per second.
This influence the logging source as well (adapter). In my case it slows down a scheduled adapter in that way that adapter runs into a timeout and will be killed before end of the work.
In my opinion the log display in admin must be independent of the work in adapter and it should not influence the work of an adapter...

**Comment by Apollon77** [comment]
> This influence the logging source as well (adapter). In my case it slows down a scheduled adapter in that way that adapter runs into a timeout and will be killed before end of the work.

What you mean with this??
Normally technically there can not be any influence here - or at least I would not have any idea why and how

**Comment by afuerhoff** [comment]
I have the same problem when the info adapter log level is set to warn. When it is set to error I have no logging problems

**Comment by GermanBluefox** [comment]
![debug1](https://user-images.githubusercontent.com/4582016/116793870-b5ca1400-aac9-11eb-8334-f73ac55e2e0d.gif)

I cannot catch your problem. On video you can see 3 messages per second and it works smooth.

>This influence the logging source as well (adapter). 
Impossible. It is absolutely independent. Adapter fires and forget and the message will be delivered via redis.

**Comment by afuerhoff** [comment]
Please check with the info adapter. Now I have the problem with Loglevel info. Just js-controller updated. 
One message per second.

**Comment by rg-engineering** [comment]
When I run DasWetter with info log level it needs 55 seconds to complete the job. If I set it to debug level it needs more then 10 minutes on my machine. With admin 4 I haven't seen that much difference...

**Comment by Apollon77** [comment]
Ok wil massive logs the admin adapter and browser and all the visuel stuff will be the displaying bottleneck.

**Comment by GermanBluefox** [comment]
This all comes from js-controller 3.3 and from Admin5
