### ISSUE TITLE
Admin 5 / No host settings in instances

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#799]
ich vermisse die Host Anzeige unter Instanzen bei multihost im expertenmodus
![grafik](https://user-images.githubusercontent.com/6681528/116806797-a1206700-ab2f-11eb-8133-0aa4fd96e5f9.png)

**Comment by Apollon77** [comment]
5.0.12?? Das sollte das gefixt sein

**Comment by arteck** [comment]
ist aber nicht SRY

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/116883060-74e71200-ac25-11eb-9d41-d2f12af87ef3.png)

**Comment by arteck** [comment]
da muss ich jeden adapter aufklappen... um zu sehen wo der läuft.. platz ist nich da... warum zeigen wir es nicht wie früher

**Comment by GermanBluefox** [comment]
Mache ich.

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15
