### ISSUE TITLE
admin 5 objekte - Wert true/false

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#800]
bei schreiben von true/false in den Objekten ist die Übersetzung unglücklich gewählt...
![grafik](https://user-images.githubusercontent.com/6681528/116806826-e2187b80-ab2f-11eb-9520-64d915796cba.png)

im popup ist das Wort "Wert" ja aber was setzte ich damit.. nicht ersichtlich

**Comment by GermanBluefox** [comment]
Ich kann dropdown menü machen mit true/false. Sollte ich?

**Comment by Apollon77** [comment]
Oder machs als "Schiebe dings"/Switch/Slider ein/aus ... true/false?!

**Comment by GermanBluefox** [comment]
> Oder machs als "Schiebe dings"/Switch/Slider ein/aus ... true/false?!

Aber ich muss trotzdem noch irgendwo das Wort "Wert" platzieren. Switch ist schlecht dafür.

**Comment by Apollon77** [comment]
dann mach selection

**Comment by GermanBluefox** [comment]
> dann mach selection wenn du nicht
> 
> Wert: true <..> false
> 
> machen kannst

![image](https://user-images.githubusercontent.com/4582016/116822024-f46cd680-ab7c-11eb-9a6c-c6abc3fcf268.png)

Sieht irgendwie komisch aus.

**Comment by Apollon77** [comment]
Ich finds ok ... wenn selection besser aussieht dann nimm die und gut ;-)

**Comment by GermanBluefox** [comment]
Check 5.0.13

**Comment by arteck** [comment]
besser
