### ISSUE TITLE
No Host information in mobile view

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#802]
Admin 5.0.12

In the mobile view of Host no information of the current or a new Version are available. Clicking on the Host will Show the Hardware information but no js-controller version.

![Screenshot_20210502-120625_Samsung Internet](https://user-images.githubusercontent.com/25422320/116809680-83f39480-ab3f-11eb-96e1-76aecbac590d.jpg)

**Comment by GermanBluefox** [comment]
You are in "row view". Click on "tile view" and you will see some information 
![image](https://user-images.githubusercontent.com/4582016/116820503-c89a2280-ab75-11eb-9058-8647936bde8b.png)


or click on host row and it will show additional information.
![image](https://user-images.githubusercontent.com/4582016/116820491-bc15ca00-ab75-11eb-8f4d-7dbd13567612.png)

**Comment by Feuer-sturm** [comment]
Ahhh. Thanks :-)

I had expected to see some information because in the view in the browser there are some informations.

![grafik](https://user-images.githubusercontent.com/25422320/116821028-58d96700-ab78-11eb-8d5e-88b870514f17.png)

It sounds that it works as it is designed so I will close this issue.
