### ISSUE TITLE
system settings dialog - white page

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#803]
**Describe the bug**  
The system settings dialog is shortly visible and then a white page is shown in the browser.

**To Reproduce**  
Klick on and then the white page is shown.
![image](https://user-images.githubusercontent.com/50245893/116812170-9d9bd880-ab4d-11eb-9ec1-6324db730006.png)

**Expected behavior**  
The system settings dialog has to be displayed.

**Screenshots & Logfiles**  

**Versions:**  
- Adapter version: 5.0.12
- JS-Controller version: 3.3.5
- Node version: v12.22.1
- Operating system: linux

**Comment by GermanBluefox** [comment]
Please ALWAYS provide Browser console for GUI errors. I cannot do anything without it.

**Comment by afuerhoff** [comment]
![image](https://user-images.githubusercontent.com/50245893/116826722-bdef8580-ab95-11eb-91c6-5022574d740e.png)

**Comment by afuerhoff** [comment]
With filled fields Longitude and Latitude no more problems. The fields have to be checked if they were filled.
![image](https://user-images.githubusercontent.com/50245893/117051407-cc18df80-ad16-11eb-95c9-4c99697f720b.png)

**Comment by GermanBluefox** [comment]
Please test 5.0.15

**Comment by afuerhoff** [comment]
Test done. All is ok.
