### ISSUE TITLE
Script view is not shown

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#804]
**Describe the bug**  
The script view is not shown in react ui mode. It is shortly displayed but then a white page appears.

**To Reproduce**  
Switch to react mode and click on the scripts menue. 
![image](https://user-images.githubusercontent.com/50245893/116812579-b4432f00-ab4f-11eb-9bea-34251d106c68.png)

**Expected behavior**  
Scripts has to be displayed.

**Screenshots & Logfiles**  

**Versions:**  
- Adapter version: 5.0.12
- JS-Controller version: 3.2.16
- Node version: v12.22.1
- Operating system: linux

**Comment by Apollon77** [comment]
Are there any erorrs in Browser console?

**Comment by afuerhoff** [comment]
![image](https://user-images.githubusercontent.com/50245893/116812673-42b7b080-ab50-11eb-9d7d-7945f3afc598.png)

**Comment by afuerhoff** [comment]
Hi, it seems that it is a problem with sentry. No the view is displayed. But not always.

**Comment by Apollon77** [comment]
No, the setry error is never "Blocking". ignore it. Sentry in UI is disabled in Javascript adapter. so this is "expected"

**Comment by GermanBluefox** [comment]
I am not sure, that this error is Admin5 relevant. Does it work in Admin4 interface?

**Comment by afuerhoff** [comment]
The same behaviour in 5.0.12 classic ui.

**Comment by GermanBluefox** [comment]
I don't know what is that, as I cannot reproduce it

**Comment by afuerhoff** [comment]
Hi, I cannot reproduce this behaviour anymore. I don't no why. The only change was the update of the history adapter.
