### ISSUE TITLE
Admin 5 lists "js-controller" in "update all adapters" dialog

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.admin#805]
**To Reproduce**  

1. Go to adapter list
2. Click on filter to see adapters with updates
3. Click "update all adapters"
4. See list

**Expected behavior**  

Just list adapters (and not js-controller)

**Screenshots & Logfiles**  

<img width="505" alt="Screenshot 2021-05-02 at 16 21 48" src="https://user-images.githubusercontent.com/1959049/116816582-caa6b600-ab62-11eb-837b-29465a695417.png">

**Versions:**  
 - Adapter version: 5.0.12
 - JS-Controller version: 3.2.16

**Comment by klein0r** [comment]
Related to #789 and #801 ?

**Comment by GermanBluefox** [comment]
> Related to #789 and #801 ?

Nope

**Comment by GermanBluefox** [comment]
Fixed in 5.0.14 (not yet released

**Comment by Feuer-sturm** [comment]
Admin 5.0.14
js-controller 3.3.7

@GermanBluefox 
Is fixed in 5.0.14. js-controller update is available (3.3.8) and it is not shown in the list of updateable adapters

![grafik](https://user-images.githubusercontent.com/25422320/116938303-d7163600-ac6a-11eb-837d-92eb62f8dc11.png)
