### ISSUE TITLE
React UI - Number of updates not shown

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#806]
![image](https://user-images.githubusercontent.com/49171332/116819063-a650d680-ab6e-11eb-94b9-dfbf291fc73f.png)

**Comment by afuerhoff** [comment]
Evtl. haben die beiden Issues siehe hier https://github.com/ioBroker/ioBroker.admin/issues/801
die gleiche Ursache.

**Comment by Feuer-sturm** [comment]
Admin 5.0.14
js-controller 3.3.7

Anzahl der zu aktualisierenden Adapter und Host Update wird korrekt angezeigt

![grafik](https://user-images.githubusercontent.com/25422320/116937646-da5cf200-ac69-11eb-96b9-e72a430a67f0.png)
