### ISSUE TITLE
Adapter update not shown but under "Install a specific version"

### ISSUE THREAD

**Issue by afuerhoff** [ioBroker/ioBroker.admin#807]
**Describe the bug**  
Adapter is not shown in Info and adapter tab. Only under "Install a specific version".
But after install a bug is shown. The adaper version is the same as before installation.
See also here: https://github.com/ioBroker/ioBroker.admin/issues/793
It could be the same problem.
The failure is also in classic ui and also under admin 4.2.1.
https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/351

![image](https://user-images.githubusercontent.com/50245893/116819445-6e4a9300-ab70-11eb-9fb0-2285eaf19dc7.png)

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/50245893/116819343-06944800-ab70-11eb-8b9d-409f27de724e.png)

**Versions:**  
- Adapter version: 5.0.12
- JS-Controller version: 3.3.5
- Node version: v12.22.1
- Operating system: linux

**Comment by Apollon77** [comment]
yYes history 1.9.13 was not publsiehd correctly ... will be fixed with a new release. Admin was all ok
