### ISSUE TITLE
admin 5.x error ohne web instanz - express-session deprecated maxAge as Date

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#808]
![grafik](https://user-images.githubusercontent.com/6681528/116820475-aa342700-ab75-11eb-93d3-fd6e4df9dd4f.png)

das sind die Adapter die auf dem host laufen

![grafik](https://user-images.githubusercontent.com/6681528/116820486-b5875280-ab75-11eb-98f5-70e6b7b3ab10.png)

**Comment by Apollon77** [comment]
@GermanBluefox I would propose to fix it. It is just a "deprecation" ...

**Comment by GermanBluefox** [comment]
> @GermanBluefox I would propose to fix it. It is just a "deprecation" ...
Changed in 5.0.13
