### ISSUE TITLE
Backup Button in Admin Oberfläche

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.admin#81]
Ein Button mit dem man einfach ein Backupstarten lkönnte wäre hilfreich, vielleicht auch ein Automatismus, dass immer bevor eine neue Adapterinstanzerstellt wird ein Backup erstellt wird.

**Comment by Baenker** [comment]
das würde ich mir auch wünschen

**Comment by Breisgauer** [comment]
das wäre sehr hilfreich und passt zu https://github.com/ioBroker/ioBroker.admin/issues/132
Der Backup/Restore ist für viele User eine Herauforderung und führt besonders beim Wechsel von Systemen zu schwer zu beseitigenden Fehler.

**Comment by GermanBluefox** [comment]
There is backitup adapter for that
