### ISSUE TITLE
Text is bigger as the box - Admin mobile view

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#810]
Admin 5.0.12

In the following screens the text does not fit in the box or text area if you watch them on the mobile phone
![grafik](https://user-images.githubusercontent.com/25422320/116821944-84f6e700-ab7c-11eb-84b9-63584d1d342c.png)
![grafik](https://user-images.githubusercontent.com/25422320/116821957-917b3f80-ab7c-11eb-87d1-558af3658d93.png)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15

**Comment by Feuer-sturm** [comment]
Is fixed with 5.0.15
