### ISSUE TITLE
Admin5 - Anmeldung mit Firefox nicht möglich

### ISSUE THREAD

**Issue by MCepheus** [ioBroker/ioBroker.admin#814]
Hi, ich habe gerade versucht mich nach einem Update von Admin5 auf die ver. 5.0.13 per Firefox anzumelden.
Ich komme auf die Seite mit der Eingabemaske und kann auch User und PW eingeben. Danach geht es aber nicht weiter und der Ladekreis dreht sich endlos. Auch ein löschen des Cache bringt keinen Erfolg.
Mit z.B. Edge geht der Login ohne Probleme.
Über Putty konnte ich im Log folgendes auslesen:

2021-05-03 08:22:44.330  - warn: admin.0 (23370) Cannot parse "undefined"
2021-05-03 08:22:44.888  - error: admin.0 (23370) failed connection to socket.io from ::ffff:192.168.0.10:
2021-05-03 08:22:44.892  - error: admin.0 (23370) error
2021-05-03 08:22:44.916  - error: admin.0 (23370) failed connection to socket.io from ::ffff:192.168.0.10:
2021-05-03 08:22:44.918  - error: admin.0 (23370) error

/usr/bin/nodejs
v12.22.1
/usr/bin/node
v12.22.1
/usr/bin/npm
6.14.12

system.adapter.admin                   : admin          - v5.0.13
system.adapter.backitup                : backitup       - v2.1.5
system.adapter.cloud                   : cloud          - v4.0.10
system.adapter.coronavirus-statistics  : coronavirus-statistics - v0.7.0-4
system.adapter.daswetter               : daswetter      - v3.0.5
system.adapter.denon                   : denon          - v1.10.4
system.adapter.devices                 : devices        - v0.3.16
system.adapter.discovery               : discovery      - v2.6.2
system.adapter.doorbird                : doorbird       - v0.1.5
system.adapter.dwd                     : dwd            - v2.7.5
system.adapter.easee                   : easee          - v1.0.1
system.adapter.feiertage               : feiertage      - v1.0.19
system.adapter.heos                    : heos           - v1.8.0
system.adapter.ical                    : ical           - v1.9.3
system.adapter.icons-material-png      : icons-material-png - v0.1.0
system.adapter.icons-mfd-png           : icons-mfd-png  - v1.0.2
system.adapter.icons-mfd-svg           : icons-mfd-svg  - v1.0.2
system.adapter.icons-ultimate-png      : icons-ultimate-png - v1.0.1
system.adapter.influxdb                : influxdb       - v1.9.5
system.adapter.info                    : info           - v1.7.15
system.adapter.iqontrol                : iqontrol       - v1.8.0
system.adapter.javascript              : javascript     - v5.1.2
system.adapter.js2fs                   : js2fs          - v0.1.5
system.adapter.mercedesme              : mercedesme     - v0.0.51
system.adapter.mobile                  : mobile         - v1.0.1
system.adapter.mqtt                    : mqtt           - v2.3.5
system.adapter.ping                    : ping           - v1.4.12
system.adapter.plex                    : plex           - v0.9.1
system.adapter.pollenflug              : pollenflug     - v1.0.6
system.adapter.rpi2                    : rpi2           - v1.2.0
system.adapter.rtspstream              : rtspstream     - v0.0.4
system.adapter.samsung                 : samsung        - v0.2.9
system.adapter.sayit                   : sayit          - v1.12.2
system.adapter.shelly                  : shelly         - v4.0.7
system.adapter.simple-api              : simple-api     - v2.5.3
system.adapter.socketio                : socketio       - v3.1.4
system.adapter.sonoff                  : sonoff         - v2.4.0
system.adapter.stockmarket             : stockmarket    - v0.0.2
system.adapter.synology                : synology       - v1.0.0
system.adapter.telegram                : telegram       - v1.8.1
system.adapter.text2command            : text2command   - v2.0.7
system.adapter.tr-064                  : tr-064         - v4.2.12
system.adapter.trashschedule           : trashschedule  - v1.1.1
system.adapter.tvprogram               : tvprogram      - v1.0.0
system.adapter.tvspielfilm             : tvspielfilm    - v2.0.1
system.adapter.vis                     : vis            - v1.3.9
system.adapter.vis-canvas-gauges       : vis-canvas-gauges - v0.1.5
system.adapter.vis-fancyswitch         : vis-fancyswitch - v1.1.0
system.adapter.vis-hqwidgets           : vis-hqwidgets  - v1.1.7
system.adapter.vis-icontwo             : vis-icontwo    - v0.65.0
system.adapter.vis-inventwo            : vis-inventwo   - v2.9.5
system.adapter.vis-jqui-mfd            : vis-jqui-mfd   - v1.0.12
system.adapter.vis-map                 : vis-map        - v1.0.4
system.adapter.vis-material-advanced   : vis-material-advanced - v1.7.0
system.adapter.vis-materialdesign      : vis-materialdesign - v0.5.5
system.adapter.vis-plumb               : vis-plumb      - v1.0.2
system.adapter.vis-timeandweather      : vis-timeandweather - v1.1.7
system.adapter.vis-weather             : vis-weather    - v2.5.3
system.adapter.weatherunderground      : weatherunderground - v3.3.0
system.adapter.web                     : web            - v3.4.0
system.adapter.wolf                    : wolf           - v1.2.1
system.adapter.wolf-smartset           : wolf-smartset  - v0.2.2
system.adapter.zigbee                  : zigbee         - v1.5.3

Firefox in Version 88.0

**Comment by backfisch88** [comment]
IOS Safari auch so...
sobald man HTTPS ausschaltet gehts

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15 für Firefox. Safari keine Ahnung.

**Comment by MCepheus** [comment]
Du bist da jetzt definitiv einen Schritt weiter. Aber bei mir gibt es noch Probleme.
Ich komme jetzt nach eingabe des Users und des PW einen Schritt weiter zum Ladebildschirm mit dem großen ioBroker Logo. Das rotiert jetzt ca. 10 Sekunden ohne das etwas passiert. Ich wollte schon aufgeben bin dann aber plötzlich doch auf die "Startseite" weitergeleitet worden.
Dafür hatte ich 84 Logeinträge:
`

admin.0 | 2021-05-05 11:43:19.438 | error | error
-- | -- | -- | --
admin.0 | 2021-05-05 11:43:19.437 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.414 | error | error
admin.0 | 2021-05-05 11:43:19.413 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.398 | error | error
admin.0 | 2021-05-05 11:43:19.397 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.381 | error | error
admin.0 | 2021-05-05 11:43:19.380 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.363 | error | error
admin.0 | 2021-05-05 11:43:19.362 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.346 | error | error
admin.0 | 2021-05-05 11:43:19.345 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.331 | error | error
admin.0 | 2021-05-05 11:43:19.330 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.311 | error | error
admin.0 | 2021-05-05 11:43:19.310 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.294 | error | error
admin.0 | 2021-05-05 11:43:19.293 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.278 | error | error
admin.0 | 2021-05-05 11:43:19.277 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.261 | error | error
admin.0 | 2021-05-05 11:43:19.260 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.245 | error | error
admin.0 | 2021-05-05 11:43:19.244 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.229 | error | error
admin.0 | 2021-05-05 11:43:19.228 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.210 | error | error
admin.0 | 2021-05-05 11:43:19.209 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.194 | error | error
admin.0 | 2021-05-05 11:43:19.193 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.177 | error | error
admin.0 | 2021-05-05 11:43:19.177 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.161 | error | error
admin.0 | 2021-05-05 11:43:19.161 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.145 | error | error
admin.0 | 2021-05-05 11:43:19.144 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.128 | error | error
admin.0 | 2021-05-05 11:43:19.127 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.114 | error | error
admin.0 | 2021-05-05 11:43:19.113 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.094 | error | error
admin.0 | 2021-05-05 11:43:19.093 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.078 | error | error
admin.0 | 2021-05-05 11:43:19.077 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.062 | error | error
admin.0 | 2021-05-05 11:43:19.061 | error | failed connection to socket.io from ::ffff:192.168.0.10:
admin.0 | 2021-05-05 11:43:19.045 | error | error
admin.0 | 2021-05-05 11:43:19.044 | error | failed connection to socket.io from ::ffff:192.168.0.10:
`
Ein Auszug nur als Bsp.

**Comment by GermanBluefox** [comment]
Hast du browser in IP4 oder IP6?

Das `::ffff:192.168.0.10:` kann ich mir nicht erklären und bei mir geht FF

**Comment by MCepheus** [comment]
Eigentlich IP4, hab jetzt mal auf die neue 88.0.1 upgedatet und nun keine Fehlermeldung mehr. Entweder hat sich das nun eingespielt oder bei FF war auch irgendwo der Wurm drin.
Für mich erledigt. Danke!
