### ISSUE TITLE
checkbox 'close when finished' nor permanently checked

### ISSUE THREAD

**Issue by Homoran** [ioBroker/ioBroker.admin#815]
in the update dialog is the checkbox 'close when finished' not checked permanently anymore when checked once.
in earlier versions this option stayed permanently for future use.

**Comment by sjfm-design** [comment]
yes, would be nice!

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15

**Comment by Feuer-sturm** [comment]
Fix is working with 5.0.15
