### ISSUE TITLE
Admin 5.0.13: Adapter Traffic light shows green instead of yellow

### ISSUE THREAD

**Issue by Grizzelbee** [ioBroker/ioBroker.admin#816]
**Describe the bug**  
Adapter Traffic light shows green instead of yellow when Adapter is note connected.

**Expected behavior**  
Traffic light should show yellow, when not connected

**Screenshots & Logfiles**  
Admin 5.0.13:
![grafik](https://user-images.githubusercontent.com/5459426/116861679-caaac280-ac03-11eb-936b-1470aa570e41.png)

Admin 4.x:
![grafik](https://user-images.githubusercontent.com/5459426/116861712-dbf3cf00-ac03-11eb-98ea-c25f74248afa.png)

**Versions:**  
 - Adapter version: 5.0.13
 - JS-Controller version: 3.3.7
 - Node version: v14.15.4
 - Operating system: Windows 10 x64

**Comment by GermanBluefox** [comment]
Fixed in 5.0.15

**Comment by Grizzelbee** [comment]
Confirmed. Works now as expected.
