### ISSUE TITLE
Anzeige von verbundenen Clients unter Instanzen (Beispiel MQTT Adapter)

### ISSUE THREAD

**Issue by coyote1** [ioBroker/ioBroker.admin#817]
In Admin4 wurde unter Instanzen (Beispiel MQTT Adapter) angezeigt, welche Clients gerade mit MQTT verbunden sind, wenn man auf den farbigen Punkt vor der Instanz mit dem Mauszeiger klickte.
Bitte in Admin5 auch wieder einfügen, wenn man auf die Instanz klickt und den Status angezeigt bekommt.

**Comment by Apollon77** [comment]
Haste mal screenshot von Admin4?

**Comment by coyote1** [comment]
Sorry, hab ich gerade gemacht und wollte ihn einfügen.

Hier:

![iobroker](https://user-images.githubusercontent.com/19485543/116870971-cc7c8200-ac13-11eb-90c7-fe77e2e8364d.jpg)

**Comment by GermanBluefox** [comment]
implemented in 5.0.17

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/118035210-36f79580-b36b-11eb-8bc0-ec68abc08129.png)
