### ISSUE TITLE
admin 5.x multihost umschalten

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#819]
![grafik](https://user-images.githubusercontent.com/6681528/116874045-f08e9200-ac18-11eb-9980-b46cb426bbb1.png)

es erfolgt keine automatsche aktualiserung bei host wechsel 

früher wurde die Adapterliste automatisch nach umschalten aktualisert

**Comment by GermanBluefox** [comment]
Please validate in 5.0.16

**Comment by arteck** [comment]
nope.. nicht wirklich.. 

https://user-images.githubusercontent.com/6681528/117543027-5b760980-b01b-11eb-988b-8fdbba2eae43.mp4

**Comment by GermanBluefox** [comment]
Please try 5.0.23

**Comment by Feuer-sturm** [comment]
Admin 5.0.24 on Master and Slave
On my system it is working.

![Animation3](https://user-images.githubusercontent.com/25422320/118314937-21ae7280-b4f5-11eb-9e6d-8f6a57a7efb0.gif)

**Comment by arteck** [comment]
5.0.24 lädt die Seite jetzt wie es soll ... aber

nach adapter aktualisierung bleibt die anzeige des Adapter auf der alten version.. da müsste noch ein refresh erfolgen.

**Comment by GermanBluefox** [comment]
Kann nicht reproduzieren..... Auch mit Mutlihost

**Comment by Feuer-sturm** [comment]
Admin 5.0.26
Browser Chrome

Adapter zum Update verfügbar auf dem Slave:

![grafik](https://user-images.githubusercontent.com/25422320/118632732-0089a280-b7d1-11eb-97ad-1b18bb57656f.png)

Nach erfolgreichem update steht sofort die neue Version da ohne das ich auf einen weiteren Button für einen Refresh gedrückt habe:
![grafik](https://user-images.githubusercontent.com/25422320/118632862-2616ac00-b7d1-11eb-8ebd-aec223b751a5.png)

@arteck Bei dir ist das nicht so mit Admin 5.0.26?

**Comment by arteck** [comment]
ich schau mal im .28

**Comment by arteck** [comment]
ist immer noch

https://user-images.githubusercontent.com/6681528/118919721-5b3c0f00-b935-11eb-9d34-626916455890.mp4

auf dem Multihost.. auf dem Master.. wenn ich da einen Adapter aktualisere muss ich F5 drücken um nach dem update die neue Version zu sehen

**Comment by Feuer-sturm** [comment]
Ein Unterschied bei uns beiden ist, dass ich die checkbox zum automatischen schließen nicht aktiviert habe. 

@GermanBluefox kann das einen Unterschied machen?

**Comment by Feuer-sturm** [comment]
Master Admin 5.0.28 update to 5.0.29
Slave Admin 5.0.28

After successfull Admin update on Master from 5.0.28 to 5.0.29 I have the problem as well that not the new version will be shown automatically
![grafik](https://user-images.githubusercontent.com/25422320/119030645-739a4100-b9aa-11eb-94c2-b151bd9956ab.png)

After a refresh of the page Admin 5.0.29 will be shown

**Comment by GermanBluefox** [comment]
Please retest with 5.0.29

**Comment by Feuer-sturm** [comment]
Master: Admin 5.0.29
Slave Admin 5.0.28

Adapter page refreshed on master and then updated adapter on master where an update is available (BackItUp from 2.1.7 to 2.1.11).
Still the same problem. A refresh is necessary to see the current version.

**Comment by Feuer-sturm** [comment]
Master: Admin 5.0.30
Slave: Admin 5.0.30

@GermanBluefox @arteck 
Update to Admin 5.0.30
Adapter page refreshed on master and then updated adapter on master where an update is available.
Without any refresh the current version is displayed :-)

Issue fixed from my point of view

**Comment by GermanBluefox** [comment]
@arteck ?

**Comment by arteck** [comment]
geht
