### ISSUE TITLE
Versions Nummer bei Instanzen

### ISSUE THREAD

**Issue by lubeda** [ioBroker/ioBroker.admin#82]
Es wäre schön wenn man in der Ansicht der Instanzen bei der Konfigurtion die Versionsnummer des Adapters sehen könnte außerdem wäre ein Link zum dem Adapter Github an der stelle Hilfreich wenn man etwas nachlesen muss

**Comment by Apollon77** [comment]
Beides gibt es unter "Adapter". Welchen Mehrwert hätte es das unter "Instanzen" zu dupluizieren und sogar mehrfach darzustellen wenn es mehrere Instanzen eines Adapters gibt?

**Comment by lubeda** [comment]
Hallo,

ich dachte die Infos sind auch bei den Instanzen hilfreich, weil man manchmal bei den Instanzen etwas konfiguriert. Dann benötigt man schon mal die dazugehörige Github Seite als Dokumentation der möglichen Einstellungen/Parameter.

Auf der Adapterseite brauche ich diese Infos nicht so sehr, weil dort nur die Ensteidung ist: Brauche ich den Adapter ja oder nein. Also wäre die Doku damit näher an der Stelle an der man sie braucht.
Gruß Ludger.

**Comment by GermanBluefox** [comment]
In Admin3 implementiert
