### ISSUE TITLE
admin 5.x Anzahl installierter instanzen

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#822]
mir fehlt in der Übersicht die anzahl der installierten instanzen des adapter

![grafik](https://user-images.githubusercontent.com/6681528/116887374-8848ac00-ac2a-11eb-923a-3dc6db6408be.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Mit 5.0.15 werden die installierten Instanzen angezeigt
![grafik](https://user-images.githubusercontent.com/25422320/117198482-5df11d00-ade9-11eb-9594-8fbfbdd1faad.png)
