### ISSUE TITLE
Admin 5.0.13: es können keine eigenen Währungen angegeben werden

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#824]
Bei den Basiseinstellungen -> "Währungszeichen" sind vier Währungen vorgegeben, eigene können nicht eingegeben werden.

siehe auch: https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/375?_=1620064372534

Admin v5.0.13

**Comment by GermanBluefox** [comment]
Welche Währung willst du haben?
Momentan wird es noch nirgendwo verwendet,

**Comment by ice987987** [comment]
für mich ist die Währung CHF interessant.

**Comment by GermanBluefox** [comment]
CHF added in 5.0.15

**Comment by ice987987** [comment]
Funktioniert. Getestet mit Admin v5.0.15.
Vielen Dank.
