### ISSUE TITLE
Changing the schedule rule of an instance has no effect

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#825]
Admin 5.0.13
js-controller 3.3.7

Changing the schedule rule of an instance has no effect

![Animation](https://user-images.githubusercontent.com/25422320/116935996-76392e80-ac67-11eb-8c0b-7214a9687a6e.gif)

**Comment by Apollon77** [comment]
... and a loca issue with two missing texts it seems in the dialog

**Comment by Feuer-sturm** [comment]
Admin 5.0.15

- With Admin 5.0.15 it is now possible to change the scheduling time

- These arrows are very small
![grafik](https://user-images.githubusercontent.com/25422320/117102574-e4214b00-ad78-11eb-83da-67766b98c07b.png)

- Should be here a better text?

![grafik](https://user-images.githubusercontent.com/25422320/117102635-03b87380-ad79-11eb-9550-346107664ef1.png)

**Comment by GermanBluefox** [comment]
Arrows are depends on your browser and not configurable.

Texts are in other module "adapter-react" and will be fixed in next version
