### ISSUE TITLE
admin 5.x adapter aktualisierung

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#826]
![grafik](https://user-images.githubusercontent.com/6681528/116963507-4e6aba80-aca9-11eb-917b-c5cce23b61f7.png)

die Versionsnummer ist leer

**Comment by GermanBluefox** [comment]
Was hast du angeklickt?

**Comment by MichaelSchaaf999** [comment]
Ich schließ mich mal an: Der Name des Adapters wird nicht mehr angezeigt...
<img width="280" alt="image" src="https://user-images.githubusercontent.com/53481090/116973976-a1e70380-acbd-11eb-90e6-14f5e22ed39a.png">

**Comment by GermanBluefox** [comment]
> Ich schließ mich mal an: Der Name des Adapters wird nicht mehr angezeigt...
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/53481090/116973976-a1e70380-acbd-11eb-90e6-14f5e22ed39a.png">

Das ist komplett ein anderen Fehler. Bitte nicht anhängen. Und dein Problem wird mit js-controller 3.3 gelöst.

**Comment by GermanBluefox** [comment]
@arteck ??

**Comment by arteck** [comment]
aktualisiere von GIT..

**Comment by GermanBluefox** [comment]
Please retest with 5.0.21

**Comment by MichaelSchaaf999** [comment]
seems to work fine now
