### ISSUE TITLE
Admin5: Login stuck on spinning wheel with iOS mobile browsers

### ISSUE THREAD

**Issue by peer69** [ioBroker/ioBroker.admin#829]
**Describe the bug**  
Admin interface is stuck on the spinning wheel when opening from mobile browser using iOS (tested Safari, Chrome)

**To Reproduce**  
1. Open mobile browser on iOS
2. navigate to webinterface 
3. enter login information and login
4. See the spinning wheel forever

**Expected behavior**  
On desktop browsers (tested Safari 14.1 on MacOS as well as Chrome 83 on MacOS) the admin interface loads as expected after logging in.  

**Screenshots & Logfiles**  
![IMG_0817](https://user-images.githubusercontent.com/28559804/117118870-98c76680-ad91-11eb-8ba2-a179b3652c10.jpeg)
![IMG_0818](https://user-images.githubusercontent.com/28559804/117118880-9b29c080-ad91-11eb-82c2-3b3971cd4caf.jpeg)

Webconsole shows the following: 
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/28559804/117121216-9b778b00-ad94-11eb-85f2-22625d45cb63.png">

**Versions:**  
 - Adapter version: Admin 5.0.15
 - JS-Controller version: 3.3.8
 - Node version: 12.22.1
 - Operating system: Ubuntu 18.04.5

**Additional context**  
After rolling back to 4.1.1 Instances view is broken, does not show any instances on any browser. 
According to https://www.osstatus.com/search/results?platform=all&framework=all&search=-9807 this seems to be an error with an invalid certificate chain. I have changed my cert and key to ones issued by a local CA of mine and also imported the CA. After that, the interface loads fine. So this seems to be triggered by using SSL/TLS with the self signed certificates provided by ioBroker which are missing the corresponding CA and therefore are not trusted by iOS. Yet the login site did load up fine using SSL, the error only appeared after login.

**Comment by GermanBluefox** [comment]
According to Apple it is following error:
![image](https://user-images.githubusercontent.com/4582016/117172996-9df5d700-adcc-11eb-8e52-df56496dc2a9.png)

Can it be so, that without HTTPS it works?

**Comment by peer69** [comment]
Yes. I added my investigation and solution under "Additional context" in my original post above. Its still odd that the error only appears after login. Encrypted connection to the webinterface before login and therefore only showing the login prompt did not trigger the error.

**Comment by denzel1994** [comment]
Same issue here.

**Comment by GermanBluefox** [comment]
Sorry, what can I do against that apply does not like certificaes??

**Comment by peer69** [comment]
Not sure. Filing a radar at Apple will probably result into nothing. Maybe create a full chain at installation instead of a single key pair? For a less advanced user the only feasible solution would probably be disabling TLS which isn’t something you would want to suggest and might not even work with future browser versions.

**Comment by Apollon77** [comment]
@peer69 Hm ... I do not get why it is not working ... why a chain cert is needed? Could it be that the cert was just "too old"?

What "iobroker cert view" output?

**Comment by peer69** [comment]
I dont get it as well. In my case the cert was still valid. As i have already swapped the cert, @denzel1994 could you check what output "iobroker cert view" gives you? 
I might try to setup a new instance to check for this error but I wont be able to do so before the weekend. Another possible cause might have been a SHA1 signature. But in this case the error given by Apple would be misleading.
