### ISSUE TITLE
Adapter updates will only show up after a refresh by admin 5.0.x

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#830]
I'm not sure if it has already been reported.  

I noticed that I can press the Update button in the Adapter tab, but nothing happens afterwards.  

If updates are available, you will only see them after refreshing the admin page.  
Then I did the whole thing in parallel via the console and carried out iobroker update.

 Nothing appears in the admin here either until I refresh the page.

**Comment by Feuer-sturm** [comment]
And in addition after an Adapter update the number on the left side will not be updated. A refresh of th page is needed as well

![grafik](https://user-images.githubusercontent.com/25422320/117196321-9f33fd80-ade6-11eb-902a-42d01eed5d9f.png)

**Comment by sbormann** [comment]
Same for me:
![image](https://user-images.githubusercontent.com/49171332/117546048-bc580e80-b028-11eb-944a-41d1e71802d3.png)

**Comment by intruder7777** [comment]
5.0.21 Problem besteht immer noch. Aktualisierung unter Tab Adapter zeigt nichts an. Wechsel zu Info zeigt Adapter an die aktualisiert werden können. Im selben Moment erscheint auch die Anzahl am Namen "Adapter" aber unter Adapter werden immer noch keine Aktualisierungen angezeigt. Auch nach Aktualisierung des Adapter Tabs nicht. Erst nach einem Reload der Seite.

**Comment by Feuer-sturm** [comment]
Admin 5.0.21

I just updated one adapater over the adapter menu and after successfull update the correct number of available adapters in the menu on the left side is shown correctly.
