### ISSUE TITLE
Menu Dateien - Handling of folder "Benutzerdaten"

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#831]
Admin 5.0.15
js-controller 3.3.8

If you try to enter the folder "Benutzerdaten" in the menu "Dateien"  you will get an message that 0_userdata.0 does not exist and there will be an infity loop of the loading circle

Steps to reproduce:
- Enter Menu Dateien
- Klick on folder "Benutzerdaten"
- Message "Cannot read 0_userdata.0: Not exists" will be shown
- Click on button to create "new folder" and browser error will be shown

![grafik](https://user-images.githubusercontent.com/25422320/117179530-80783b80-add3-11eb-9e6e-11c905a6c966.png)

![grafik](https://user-images.githubusercontent.com/25422320/117179464-6c343e80-add3-11eb-969c-5f3e83ee98e9.png)

If you now press the button to create a folder the following error will be shown

![grafik](https://user-images.githubusercontent.com/25422320/117179903-ea90e080-add3-11eb-8d07-c9c498fa4ddd.png)

If you only select the folder "Benutzerdaten" and click on the button to create a new folder a name can not be entered
![grafik](https://user-images.githubusercontent.com/25422320/117193302-fa63f100-ade2-11eb-8f60-217a53d49f7a.png)
Translation: [...], verschwindet dieser nach ....

I was able to upload a file and after this I was able to create new folders as well

Expected behavior:
If you click on the folder "Benutzerdaten" and the folder is not available nothing shall happen. It should be possible to create new folder / upload data

**Comment by GermanBluefox** [comment]
IN Admin 5.0.17 the folder will be created by every admin restart and should always exist, as it is non-deletable.

**Comment by Feuer-sturm** [comment]
With Admin 5.0.18 it looks fine.
