### ISSUE TITLE
Admin5 Objekte alle Knoten aufklappen

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#832]
Alle Knoten aufklappen reagiert nicht, schließen und einzelne Ebenen öffnen und schließen ist ok.

**Comment by Feuer-sturm** [comment]
@santa81 Welche Admin Version verwendet du? Wo ist der Button für "alle Knoten aufklappen"?

Ich hab aktuell 5.0.15 im Einatz und sehe nur "Alle Knoten zuklappen", "Eine Ebene aufklappen", "Eine Ebene zuklappen". Diese drei Buttons funktionieren bei mir.
![grafik](https://user-images.githubusercontent.com/25422320/117197784-888ea600-ade8-11eb-983d-39ab968ebf95.png)

**Comment by santa81** [comment]
hehe, hab ich danach leider auch erst festgestellt. suche mal in irgendeiner Spalte nach etwas, also oben ein Name eingeben oder ein Raum...

**Comment by Feuer-sturm** [comment]
Ah, gefunden.
![grafik](https://user-images.githubusercontent.com/25422320/117201365-db6a5c80-adec-11eb-839d-c6398013c9bb.png)

Ich vermute, dass der Button in der allgemeinen Übersicht fehlt.
Den Button nur zu sehen, wenn man gefiltert hat um dann alle Knoten aufklappen zu können ist aus meiner Sicht kein typischer Anwendungsfall.

**Comment by santa81** [comment]
@Feuer-sturm ja klar ist das so. Ich hatte durch das js 3.3.x Update Probleme mit einigen DP von shelly, die falsch angelegt wurden.
Also habe ich nach Longpush gefiltert und dann braucht man genau den Button um alle Dp auf einmal überprüfen zu können.
Und da eben die Fehlerhaften zu löschen.

**Comment by GermanBluefox** [comment]
Fixed in 5.0.17

**Comment by Feuer-sturm** [comment]
@GermanBluefox @santa81 
Getestet mit Admin 5.0.18. Issue ist gefixt.
