### ISSUE TITLE
Admin5: Installation über Git fügt keine Instanz hinzu

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.admin#833]
**Describe the bug**  
Bei Installation eines Adapters über GIT (https://github.com/gaudes/ioBroker.slideshow.git) wird keine Instanz hinzugefügt

**To Reproduce**  
1. Installieren aus eigener URL
2. Beliebig
3. https://github.com/gaudes/ioBroker.slideshow.git
4. Installation erfolgt, keine Instanz vorhanden, keine Fehler im Log

**Expected behavior**  
Bei Installation wird instanz.0 mit installiert

**Versions:**  
Alles aktuell

**Comment by gaudes** [comment]
Hinweis: Adapter hat eine Dependency, welche nicht erfüllt wurde. Installation der Dependency ist auch nicht erfolgt

**Comment by GermanBluefox** [comment]
Das Verhalten war so, dass es keine Instanz angelegt wird.
Und dass man dann auf Adapter klicken muss und Instanz hinzufügen.
Vielleicht willst du nur eine spezifische Test-Version installieren und die Instanzen sind schon da??

**Comment by gaudes** [comment]
OK. Und die fehlenden Dependency ? In diesem Fall VIS ?

**Comment by GermanBluefox** [comment]
Git installs bzw ioBroker url macht das nicht weil eigentlich eher „dev/test Fälle“

**Comment by gaudes** [comment]
OK, dann ist es erledigt, der Rest hat geklappt. Danke.
