### ISSUE TITLE
Feature Request: iobroker Admin "Instanzen" for colorblinds

### ISSUE THREAD

**Issue by turtok187** [ioBroker/ioBroker.admin#834]
hi, in the iobroker admin "instanzen" are trafficlight symbols.
for me as a colorblind (red/green disability) can not see if the light is green or red.
could you please change the form of the symbol as it was for traffic lights:
green - square
yellow - triangle
red - round
or just change the color to something with more contrast!
https://wiki.selfhtml.org/wiki/Grafik/Farbkonzept/Farben_und_Kontraste#Farbenfehlsichtigkeit

many thanks!

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/117217858-66098680-ae02-11eb-9e7d-c8c1823bb45a.png)
![image](https://user-images.githubusercontent.com/4582016/117218023-ab2db880-ae02-11eb-822c-cbd42bc0ea80.png)
![image](https://user-images.githubusercontent.com/4582016/117218049-bc76c500-ae02-11eb-8b6d-1613070c67bd.png)

Like this?

**Comment by Apollon77** [comment]
I actually like that!!

**Comment by turtok187** [comment]
Yes, this samples are all readable and good recognizable for me!

**Comment by Feuer-sturm** [comment]
Admin 5.0.18

New icons are available
![grafik](https://user-images.githubusercontent.com/25422320/117514204-9fbdc700-af93-11eb-9e00-7adff8ac45f7.png)
