### ISSUE TITLE
Nach Änderung: "Speichern und Schließen" ist nicht übersetzt

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#836]
Nur eine Kleinigkeit: Bei deutscher Sprache wird nach Änderungen "Speichern" und "Schliessen" angeboten, "Speichern&Schliessen" Knopf ist nicht übersetzt ("Save&Close"), kann man mal bei Gelegenheit bereinigen.
![grafik](https://user-images.githubusercontent.com/45561610/117422193-9e52b700-af1f-11eb-8038-351d566d6485.png)

**Comment by Feuer-sturm** [comment]
Admin 5.0.21

@GermanBluefox @Apollon77 
Is fixed

![grafik](https://user-images.githubusercontent.com/25422320/118053196-5e0e9100-b384-11eb-974a-2fed57ff7db2.png)
