### ISSUE TITLE
React UI: Lots of info messages for non-installed adapters

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#839]
Fresh setup with dev-server, latest js-controller, latest admin. When I open the React Admin UI for the first time, I'm greeted with about 10-20 of these info messages which are mostly for adapters I don't even have installed.

![grafik](https://user-images.githubusercontent.com/17641229/117443127-f85f7680-af37-11eb-8620-1ec06114db49.png)

**Comment by Apollon77** [comment]
Seems so that some of the checks are not working as they should? like "Installed"?

**Comment by GermanBluefox** [comment]
The functionality will be moved from info into admin, as it is very important.

**Comment by AlCalzone** [comment]
Okay then it seems the checks are not working

**Comment by GermanBluefox** [comment]
Fixed in 5.0.19

**Comment by Feuer-sturm** [comment]
I just set up a fresh iobroker installation and updated admin to 5.0.21

With previous installations I saw the same behavior like @AlCalzone mentioned. With Admin 5.0.21 only the "Backitup" information is shown. No informations about adapters which are not installed.

Looks good :-)
