### ISSUE TITLE
React UI: Should the "Common" adapter group come first?

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.admin#840]
I currently see the following ordering of adapter groups in React UI. I believe the "Common/Allgemein" group should come first:
![grafik](https://user-images.githubusercontent.com/17641229/117443553-95221400-af38-11eb-9ef7-702538bb0b27.png)

**Comment by Feuer-sturm** [comment]
Admin 5.0.19

@GermanBluefox @AlCalzone 
Is fixed in 5.0.19
![grafik](https://user-images.githubusercontent.com/25422320/117725712-d9860c00-b1e5-11eb-8fe0-4d6cc1a6ef44.png)
