### ISSUE TITLE
Web Adapter has no title in adapter overview

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#841]
Admin 5.0.18
Web Adapter has no title in adapter overview

![grafik](https://user-images.githubusercontent.com/25422320/117514548-63d73180-af94-11eb-86c2-ce52315e1197.png)

**Comment by Apollon77** [comment]
js-controller 3.3?

**Comment by Feuer-sturm** [comment]
@Apollon77 yes 3.3.8 (your modified version https://github.com/ioBroker/ioBroker.admin/issues/754#issuecomment-834775937)

**Comment by GermanBluefox** [comment]
Fixed in 5.0.19
