### ISSUE TITLE
Object Menu incomplete in mobile view

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#843]
Admin 5.0.18

Object menu looks like this on the mobile phone 
![Screenshot_20210508-013654_Samsung Internet](https://user-images.githubusercontent.com/25422320/117517965-3c856200-af9e-11eb-9ad6-a1a8f96746a3.jpg)

**Comment by GermanBluefox** [comment]
Please switch ON auto columns.
![image](https://user-images.githubusercontent.com/4582016/117585216-83479900-b111-11eb-98c0-fa5eb0df77a4.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox Yes you were right. Auto coloums was not activated.
