### ISSUE TITLE
admin 5.x automatische Repo aktualisierung schlegt fehl

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#845]
meine beta repos werden nicht autoamisch aktualisiert..

eingestellt ist 
![grafik](https://user-images.githubusercontent.com/6681528/117530697-d967ef80-afde-11eb-9943-0966b7b6e222.png)

bekomme aber keine aktualisierung.. der adapter angezeigt

**Comment by Apollon77** [comment]
Bei mir wurde es ausgeführt laut log!!

> 2021-05-07 08:47:26.233  - info: admin.0 (12213) Request actual repository...
2021-05-07 08:47:26.379  - info: host.io-test2 Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"

Auch ein "reload" der adapterseite hat keinen effekt gehabt.

Es hatte nur scheinbar keinen echte neu-laden zur Folge (in 5.0.15 war das). erst nach einem "iobroker update" an der CLI und reload im browser kamen die aktuellen  adapter

**Comment by GermanBluefox** [comment]
Es wurde NICHTs diesbezüglich geändert.

**Comment by arteck** [comment]
bin inzwischen bei .26 .. ich muss immer noch manuell 
iobroker update 
ausführen... bei @Apollon77 ist es auch... ergo bin nicht alleine mit dem Problem

**Comment by Supermicha81** [comment]
I don't know if it is the same issue but even similar...

if i start the gui, no available update are shown. not in the menu in the left, not in the adapters-tap.
only if i manually click on "check for updates", the available updates are shown.

AND. after doing the update, the adapter even seems to be updateable and showing the update button since i press the "check for updates" button again.

**Comment by GermanBluefox** [comment]
>Ich hab auf Github gesehen, das es ein Update gibt...

Repo wird nur ein mal pro Tag vom Server abgeholt. Es kann sein, dass es bis zu 24 Stunden dauern kann, bis Update automatisch auftaucht.

**Comment by Supermicha81** [comment]
@GermanBluefox 

das ist schon klar soweit...

nur das das Update NACH der Installation auch weiterhin noch angezeigt wird, ist der eigentliche Bug.

Erst wenn ich nach dem Adapter-Update nochmal nach Updates suche, wird die neuinstallierte Version überhaupt angezeigt.

**Comment by Apollon77** [comment]
Das Problem hatte ich auch heute mit der 5.1.10 Habe 10 Adapter geupdatet und hosts geswitcht. Dann am Ende wieder auf den ersten Host geswitcht und plötzlich wurden alle Updates wieder angezeigt. dann repo neu geladen und ansicht wurde korrigiert

**Comment by Apollon77** [comment]
PS: Ich tippe da eher auf irgendein local cache thema

**Comment by arteck** [comment]
warum auch immer jetzt gehts
