### ISSUE TITLE
admin 5.x instanz einfärben 

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#846]
in der Adapterliste kann man bei multihost die Hosts sehen..
![grafik](https://user-images.githubusercontent.com/6681528/117530818-83477c00-afdf-11eb-82a4-3bda912474c7.png)
manchmal kan man diese nicht unterscheiden .. bitte den Host namen einfärben

als beispiel
host1 in rot
host2 in grün 
host3 in blau

**Comment by Apollon77** [comment]
... dann kommt als nächstes Feedback von den Usern mit Rot-Grün-Schwäche ;)

**Comment by arteck** [comment]
dann mach es konfigurierbar

**Comment by Apollon77** [comment]
naja Hosts haben ja farben

**Comment by GermanBluefox** [comment]
Bitte selbst auf Hosts Seite die Farben setzten. 
![image](https://user-images.githubusercontent.com/4582016/117585715-28fc0780-b114-11eb-84a9-75ca9e292514.png)

![image](https://user-images.githubusercontent.com/4582016/117585733-3addaa80-b114-11eb-81f9-617a6e8511ea.png)
