### ISSUE TITLE
Since 5.0.18 the iQontrol-Admin does not open

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#848]
Since update from 5.0.15 to 5.0.18 the iQontrol Admin page is unusable. It does not open and says "cannot read file: not exists". There is no error message. Here is the log:

![image](https://user-images.githubusercontent.com/49171332/117540868-82c7d900-b011-11eb-9a65-a0f68925288e.png)

I can't test 5.0.16 and 5.0.17 because the instances-tab is not opening.
5.0.15 works fine.

**Comment by GermanBluefox** [comment]
Why you have 2 socket connections? One to admin and one to web?

**Comment by sbormann** [comment]
This is historical: Before you added rename file to admin-socket a few weeks ago i used the web socket for file operations, because the web socket supported renaming files. But i thought i removed the old web socket completely after your update? Where have you found it?

**Comment by GermanBluefox** [comment]
Load socket.io from Admin: https://github.com/sbormann/ioBroker.iqontrol/blob/master/admin/index_m.html#L12
And here is connect to Admin socket: https://github.com/ioBroker/ioBroker.admin/blob/master/src-rx/public/js/adapter-settings.js#L10


Load of web conn.js: https://github.com/sbormann/ioBroker.iqontrol/blob/master/admin/index_m.html#L35
Connect to web socket: https://github.com/sbormann/ioBroker.iqontrol/blob/master/admin/conn.js#L231

Also 2 sockets....

**Comment by sbormann** [comment]
Oh yes, you are right, i forgot to remove conn.js (Line 35) from index_m.htm. Thans for the hint.
But removing it makes no difference, iQontrol is still not loading :(

**Comment by GermanBluefox** [comment]
Can you provide me you version of iQontrol as I cannot debug.
If I remove conn.js there are many calls to servConn 
![image](https://user-images.githubusercontent.com/4582016/117715336-6924be00-b1d8-11eb-93b9-fec31db98fe0.png)

**Comment by sbormann** [comment]
Github should be the actual version (in the moment i have uploaded the version without conn.js).
Thanks for your help!

**Comment by sbormann** [comment]
Works perfectly, many thanks.
