### ISSUE TITLE
Update instructions in hosts tab missing in react ui

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#849]
Hi .. I miss the host adapter update instructions in the new UI .. did I overlook?
For the old UI I could keep a text window open while doing the procedure.

**Comment by GermanBluefox** [comment]
Implemented in 5.0.19
![image](https://user-images.githubusercontent.com/4582016/117585677-f6520f00-b113-11eb-9ccc-3e00ed729e42.png)

**Comment by daniel-lo** [comment]
Super :-)
Wenn man das Fenster wie zuvor so ausrichten kann, dass man auch nach "iobroker stop" in ruhe weiter lesen kann ist das perfekt!

**Comment by daniel-lo** [comment]
Wie kommt man denn zu diesem Fenster? Erst wenn es ein Update gibt?

**Comment by Feuer-sturm** [comment]
@daniel-lo Ja du kommst zu der Ansicht nur, wenn es ein js-controller update gibt. Hier siehst du wie es dann aussieht: https://github.com/ioBroker/ioBroker.admin/issues/844#issuecomment-839147349

**Comment by GermanBluefox** [comment]
As I don't know what must be changed, I would close this issue

**Comment by daniel-lo** [comment]
Everything good .. can be closed.
