### ISSUE TITLE
React UI JSON Export all objects

### ISSUE THREAD

**Issue by theimo1221** [ioBroker/ioBroker.admin#850]
**Describe the bug**  
In the react UI it's not possible to download JSON object structur for all objects.
Reloading the page always results in preselction of previous selected. Deleting the respective cookie results in download button not beeing present.

**Expected behavior**  
A possibility to download all objects as a json through either:
a) Deselect current entry and allowing download for all objects
b) Multiselection for JSON Download (STRG + A, STRG+SHIFT+Click, Checkboxes, etc.)

**Versions:**  
 - Adapter version:  5.0.15
 - JS-Controller version: 3.3.8
 - Node version:  14
 - Operating system: Proxmox Debian

**Additional context**  
In classic admin you could reload page and press download, which resulted in all Objects beeing in the resulting JSON file.

**Comment by sbormann** [comment]
Multiselection would be also great for working with customs.

For the JSON-Download there could also be a dialog that asks if you want do download all objects or only the selected object.

**Comment by GermanBluefox** [comment]
Download all objects is too much. What is the use case for that?

**Comment by GermanBluefox** [comment]
> Multiselection would be also great for working with customs.
> 
> For the JSON-Download there could also be a dialog that asks if you want do download all objects or only the selected object.

It would be great to have some PRs.

**Comment by theimo1221** [comment]
> Download all objects is too much. What is the use case for that?

That higly depends on the user and their objects.
In addition some nodes are very big themselve which makes this argument in my opinion obsolete. Additionally it is performed on users manual request, so nothing regular or repeating.

In my case downloading that JSON gives me complete information about the objects, statetypes and ids which I can use as a config for my main logic.

**Comment by sbormann** [comment]
> > Multiselection would be also great for working with customs.
> > For the JSON-Download there could also be a dialog that asks if you want do download all objects or only the selected object.
> 
> It would be great to have some PRs.

I definitely would if I could. But that is simply beyond my knowledge. :)

**Comment by theimo1221** [comment]
> > > Multiselection would be also great for working with customs.
> 
> > > For the JSON-Download there could also be a dialog that asks if you want do download all objects or only the selected object.
> 
> > 
> 
> > It would be great to have some PRs.
> 
> 
> 
> I definitely would if I could. But that is simply beyond my knowledge. :)

I'll do it, but I'm not yet sure what would be the optimal solution here

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/117655910-f7c51b00-b197-11eb-8151-2cbce68907c0.png)
