### ISSUE TITLE
Admin5 Adapter updater mobile Ansicht 

### ISSUE THREAD

**Issue by santa81** [ioBroker/ioBroker.admin#851]
Das Installationslog  ist nicht sichtbar im updater.
![Screenshot_20210509-080117_Chrome Beta.jpg](https://user-images.githubusercontent.com/18234371/117562359-adac3e80-b09e-11eb-914b-0f5a76c3a4e6.jpg)

**Comment by GermanBluefox** [comment]
Question: how should I show all this on such a small display??

**Comment by santa81** [comment]
unten drunter scrollbar vielleicht. Mir ist es nur aufgefallen

**Comment by GermanBluefox** [comment]
Please try 5.0.23

**Comment by Feuer-sturm** [comment]
Admin 5.0.24

![grafik](https://user-images.githubusercontent.com/25422320/118316707-70f5a280-b4f7-11eb-9182-a8b1c3854481.png)

and with detailed informations:
![grafik](https://user-images.githubusercontent.com/25422320/118316763-810d8200-b4f7-11eb-8480-5616534b7fb9.png)

@GermanBluefox Is it possible not to clear the debug log after one adapter is updated? In this case I updated two adapters and I can only see the output from the last updated adapter.

**Comment by GermanBluefox** [comment]
It is complicated. The update will stop if some adapter fails. So you you see last error.
