### ISSUE TITLE
Admin 5.0.18: Loglevel lässt sich nicht ändern

### ISSUE THREAD

**Issue by lonsimbt** [ioBroker/ioBroker.admin#852]
Der Admin-Adapter übernimmt Änderungen des Loglevels nicht. Nur temporärer Wechsel des Loglevels über "Ohne Neustart" scheint zu funktionieren.

![grafik](https://user-images.githubusercontent.com/59287435/117564456-6cbb2680-b0ac-11eb-8cb7-0631a66df289.png)

Admin 5.0.18 
js-controller 3.3.8
Node.js  v14.16.1

**Comment by intruder7777** [comment]
5.00.21 -> Problem besteht immer noch mit der React Oberfläche. Nach Deaktivierung React und unter der "alten" Oberfläche funktioniert es

**Comment by lonsimbt** [comment]
@GermanBluefox: Die Beobachtung von @intruder7777 kann ich bestätigen. Auch unter 5.0.21 lässt sich unter der React Oberfläche der Loglevel nicht ändern (aber unter der "alten" Oberfläche).

**Comment by GermanBluefox** [comment]
Fixed in 5.0.22

**Comment by Feuer-sturm** [comment]
Admin 5.0.22

Loglevel kann dauerhaft geändert werden und das neue Loglevel bleibt auch nach einem Adapterneustart erhalten.
Temporäres ändern des Loglevels funktioniert ebenfalls.
