### ISSUE TITLE
Ungereimtheit bei Updateversuch (hier bei Conbee)

### ISSUE THREAD

**Issue by Michaelnorge** [ioBroker/ioBroker.admin#853]
Wenn ich in der alten Admin-Ui den Conbee updaten will (z.Z. auf die Version 1.13.15) startet einfach das Update.
Wenn ich dies allerdings mit der neuen Ui versuche, ist das aufkommende PopUp unschlüssig:

![image](https://user-images.githubusercontent.com/42386692/117569670-0d1e4480-b0c7-11eb-90e7-27679d77b981.png)

Die Version 2.xx wurde ja gestoppt, trotzdem wird sie hier angeboten.
Klicke ich auf "VERSION 2.05 IGNORIEREN" schließt sich einfach das Fenster.

Wenn ich nun auf "AKTUALISIEREN" klicken würde, wird dann auf die v1.13.15 oder die v2.05 geupdatet?

Der Hinweis ist verwirrend.

**Comment by Apollon77** [comment]
Dann bitte beim Adapter ein issue öffnen. Admin zeigt alle Versionen an die verfügbar sind bzw npm latest und so. Der Adapter Dev muss hier ggf die npm version "Latest" zurücksetzen auf die letzte 1.x, dannbietet Admin auch kein Update mehr an

**Comment by santa81** [comment]
@Apollon77 @Michaelnorge   
Auch wenn sicherlich deconz daran schuld ist, muss man sagen das nur das manuelle update unter Adapter diesen fehler macht.
Unter Info läuft das update ordnungsgemäß, auch wenn mehrere Adapter ein update anbieten, wird nicht auf 2.x.x aktualisiert im updater(also das automatische aktualisieren von mehreren Adaptern.

**Comment by Apollon77** [comment]
Ahh ok ... @GermanBluefox yes somethign is strange. Latest on npm for deconz is 1.13.15 (was reset to this). yes in the new and io-package.json on github most likely show 2.0.5 ... but admin should only care about repo verison, or!?
