### ISSUE TITLE
Admin Version not in top bar anymore

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#854]
Hallo .. in der alten UI war die Admin-Version immer gleich ersichtlich .. jetzt nur noch in der Adapter-Liste .. auch nicht in den Infos.

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/117648806-f8a57f00-b18e-11eb-9ae8-22f656ce277d.png)
![image](https://user-images.githubusercontent.com/4582016/117648866-0f4bd600-b18f-11eb-8f13-50fa3d01c0bd.png)

Really?

**Comment by GermanBluefox** [comment]
Welche Admin version?

**Comment by GermanBluefox** [comment]
Kann das jemand Bestätigen? @Apollon77 @Feuer-sturm

**Comment by daniel-lo** [comment]
Schaut bei mir in FF und Chrome gleich aus.

**Comment by Feuer-sturm** [comment]
Admin 5.0.18

@GermanBluefox 
Admin Version is only visible in both dark modes on the left side.
It looks like I am not logged in as well. I am not using certificates / https

![grafik](https://user-images.githubusercontent.com/25422320/117682701-a165d580-b1b3-11eb-9e81-1d325ce0f1c5.png)

If I swtich to the light mode no version is available
![grafik](https://user-images.githubusercontent.com/25422320/117682858-cb1efc80-b1b3-11eb-9114-0af9d06cc34e.png)

**Comment by daniel-lo** [comment]
Weiß nicht ob das schon vor 5.0.20 so war aber die Versionsnummer steht jetzt in der Menüzeile rechts neben dem Logo .. man sieht sie im hellen Design nur erst wenn man den Text markiert.

**Comment by daniel-lo** [comment]
links oben jetzt sichtbar

**Comment by Feuer-sturm** [comment]
Admin 5.0.21

@GermanBluefox 
If I reduce the size of the browser window the version is on the right side.
In both ligth modes it is ok
![grafik](https://user-images.githubusercontent.com/25422320/118028454-60142800-b363-11eb-94de-888ad011cad1.png)

In both dark mode you are not able to see the version number. You can see the number if you mark the text. -> not ok
![grafik](https://user-images.githubusercontent.com/25422320/118028736-b84b2a00-b363-11eb-81af-fabfb27dec29.png)

**Comment by daniel-lo** [comment]
Jetzt stoppt übrigens die Ladeanimation bei "Meine Adapter" nicht mehr.

![Uploading grafik.png…]()

**Comment by daniel-lo** [comment]
Oh .. grad 3 Adapter aktualisiert (backitup, hmrega, iot) .. und meine Menüleiste ist blank:


![grafik](https://user-images.githubusercontent.com/4311558/118348417-75977680-b54a-11eb-94cc-62e3e6305db4.png)

**Comment by daniel-lo** [comment]
Bin grad etwas ratlos .. auch ein drüberinstallieren des admin-adapters aus dem git hat nicht geholfen .. fix und neustart auch nicht.

Die alte GUI tut noch also hab ich erstmal auf die umgestellt. Jetzt nochmal auf die neue zurück zu stellen .. hilft auch nicht .. da ist was putt.

**Comment by daniel-lo** [comment]
@GermanBluefox bin nicht sicher ob hier noch reingeschaut wird .. aber ich habe noch zwei weitere Probleme (siehe oben)

**Comment by daniel-lo** [comment]
5.0.26 .. Menüpunkte wieder da .. Meine Adapter Animation läuft noch immer unendlich weiter

**Comment by daniel-lo** [comment]
Hab Menüpunkt "Info" in der Seitenleiste jetzt schon 2 mal nach oben geschoben .. leider nicht sticky.

**Comment by GermanBluefox** [comment]
@daniel-lo Warum schreibst du alles unter einem Issue???
Für jedes Problem ein neues Issue.

**Comment by daniel-lo** [comment]
ok .. merk ich mir .. das einzige was hier noch offen ist .. ist die Daueranmitation bei "Meine Adapter"
