### ISSUE TITLE
IOS Login

### ISSUE THREAD

**Issue by backfisch88** [ioBroker/ioBroker.admin#855]
Hallo

Kann mich mit HTTPS mich nicht einloggen IOS / Safari. Ohne HTTPS läufts
[https://i.ibb.co/zrdMh3L/IMG-8250.png](https://i.ibb.co/zrdMh3L/IMG-8250.png)

**Comment by GermanBluefox** [comment]
Nicht besonders hilfreich ist das Bild. Aber kann dein Problem das hier sein: https://github.com/ioBroker/ioBroker.admin/issues/829 ?

**Comment by backfisch88** [comment]
mit dem Admin 5.0.1 lief es noch, aber danke f[r den Hinweis! werde das mal Pruefen

**Comment by backfisch88** [comment]
also scheint wohl n Problem von Apple zu sein :/ somit /closed
