### ISSUE TITLE
"Files" tab still loads data for ALL directories also if expert mode is disabled

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#857]
**Describe the bug**  
When I have the expert mode disabled I only have two meta-user on my test system, but the Files tab still load all (roughly 80 in my case) directories that were returned by the initial meta search.

**To Reproduce**  
Open Files tab without expert mode

**Expected behavior**  
Only meta-user directories are really loaded when expert mode is off because only those are shown. I think it is completely ok to trigger a re-load of all directories when enabling expert mode!

**Versions:**  
 - Adapter version: 5.0.19

**Comment by GermanBluefox** [comment]
Et tu, Brute?
