### ISSUE TITLE
Lining up buttons in Adapter warning - mobile view

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#860]
Admin 5.0.19

Please add a little more space between these buttons and line them up. 
![grafik](https://user-images.githubusercontent.com/25422320/117724700-6cbe4200-b1e4-11eb-96ca-441c5825a3d3.png)

Is it a feature that the buttons "Bestätigen" and "OK" are highlighted?

**Comment by GermanBluefox** [comment]
Please try 5.0.23

**Comment by Feuer-sturm** [comment]
Is fixed with 5.0.24
![grafik](https://user-images.githubusercontent.com/25422320/118311692-84e9d600-b4f0-11eb-97b4-db8d14865d52.png)
