### ISSUE TITLE
Adapter Setup is not opening after adding Instance

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/ioBroker.admin#862]
Issue is happening with Admin version 5.0.18 and 5.0.20

Bevore Admin 5.0, when I installed my adapter "coutdown", after adding the instance, automatically the adapter settings opened. This is not happening any more with Admin 5.0. When I move to the sessions tab, and open the settings, it works fine.

**Comment by GermanBluefox** [comment]
The settings should be only opened if browser tab with admin is active. Is it so?

**Comment by jack-blackson** [comment]
@GermanBluefox  I don't really understand what you mean. Can you please clarify? What is meant with "admin is active"?

**Comment by GermanBluefox** [comment]
Can you just retry with 5.0.22?

**Comment by jack-blackson** [comment]
Works fine for me now :) I click on "add instance", and right away the setup opens. Perfect!
