### ISSUE TITLE
"Refresh view" -> "All elements are filtered out".

### ISSUE THREAD

**Issue by bluefish007** [ioBroker/ioBroker.admin#864]
When clicking on "Refresh view" all elements are filtered out, since Admin version 5.0.21.
Normally, this was used to check for new updates.

https://user-images.githubusercontent.com/72299469/117977396-0c88e680-b331-11eb-85be-00c415e4346a.mov

**Comment by Feuer-sturm** [comment]
Admin 5.0.22

With Admin 5.0.22 issue is fixed
