### ISSUE TITLE
admin 5.x expert add object

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#865]
in old admin 4 i can save the raw object under new _id and it will be created.. so i can fast genarate many same objects

plz make a function for "raw object add"

**Comment by Apollon77** [comment]
Admin4 way was I think never intended :-)

@arteck: Wen I now thingk about it is the json import not exactly the same as your "raw add"? maybe allow on "import" to have a textfield to paste json OR select a file for upload?

**Comment by arteck** [comment]
or simple copy - paste from - to object.. with new name.. and location

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/118196521-71396380-b44d-11eb-9647-55468f1e10b8.png)

In 5.0.23
