### ISSUE TITLE
Text for logout (Abmelden) does not disappear when folded

### ISSUE THREAD

**Issue by bluefish007** [ioBroker/ioBroker.admin#866]
Admin version 5.0.21.

Text for logout (Abmelden) does not disappear when folded:

<img width="93" alt="Bildschirmfoto 2021-05-12 um 15 42 26" src="https://user-images.githubusercontent.com/72299469/117985322-e36c5400-b338-11eb-9af3-a945018ef761.png">   <->  <img width="205" alt="Bildschirmfoto 2021-05-12 um 15 44 48" src="https://user-images.githubusercontent.com/72299469/117985443-fe3ec880-b338-11eb-9770-622f595eba2d.png">

**Comment by GermanBluefox** [comment]
Fixed in 5.0.22
