### ISSUE TITLE
Handling of themes for Admin5 React UI and javascript editor

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#868]
Admin 5.0.21

With Admin 5 it is possible to change the theme of the ReactUI (dark, light)

The Javascript Adapter supports in the editor as well the possibility to change the theme for the editor independently from Admin5 settings.

Is there still a need to have both possiblities to change the theme? Otherwise I would suggest that the javascript editor uses the same theme which is chosen in Admin5 UI.

**Comment by Apollon77** [comment]
I think this will be synced as soon as Admin5 becomes more stable

**Comment by GermanBluefox** [comment]
Themen and expert mode will be controllable only from admin

**Comment by GermanBluefox** [comment]
I will close here and we should monitor it in Javascript

**Comment by Feuer-sturm** [comment]
Ok. I created an issue for javascript adapter https://github.com/ioBroker/ioBroker.javascript/issues/841
