### ISSUE TITLE
Admin 5.0.22 - js-controller-updates shown in badge for adapter-updates

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#870]
2 Updates for adapters, 1 for js-controller. But Badge for hosts is not shown, badge for adapters shows 3:

![image](https://user-images.githubusercontent.com/49171332/118103188-eb300500-b3d9-11eb-9baf-7bebe8fea78d.png)

**Comment by GermanBluefox** [comment]
Please try 5.0.23

**Comment by sbormann** [comment]
Works with 5.0.24. Great job!
