### ISSUE TITLE
keine angezeigten Adapter Updates nach klick auf aktualisieren

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.admin#872]
**Describe the bug**  
Anscheinend wird das Repo beim Klick auf den Aktualisieungs-Button nicht eingelesen, da so keine anstehenden Adapter Updates angezeigt werden.

**Versions:**  
 - Adapter version: <5.0.22>
 - JS-Controller version: <3.3.9> 
 - Node version: <14.17.0> 
 - Operating system: <Buster>

**Comment by Apollon77** [comment]
In Admin4 the "reload" button also really requested the repo anew ... seems Admin5 is not doing that

**Comment by GermanBluefox** [comment]
Fixed in 5.0.25

**Comment by Feuer-sturm** [comment]
Admin 5.0.26

Pressing the icon "update view" in Adapter Overview will cause a log entry
`16 May 2021 20:19:16.024  host.ioBrokerTestsystem Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"`

Looks like it is fixed.

**Comment by ihavenonick** [comment]
Ja scheint zu laufen, da auch das Aktualisieren jetzt genau so lange dauert wie auf der alten UI.
Ich schließe deshalb hier mal.
