### ISSUE TITLE
Admin 5.0.22 no longer encrypts

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#874]
It seems that the admin variables given in the io-package.json with `encryptedNative` are not encrypted anymore.

**Comment by GermanBluefox** [comment]
> It seems that the admin variables given in the io-package.json with `encryptedNative` are not encrypted anymore.

For which adapter?

**Comment by o0shojo0o** [comment]
This for example https://github.com/o0shojo0o/ioBroker.matomo

**Comment by GermanBluefox** [comment]
Please update adapter-react to latest version

**Comment by o0shojo0o** [comment]
Also in the 5.0.27 the error is still present.

**Comment by Apollon77** [comment]
I think what Bluefox wanted to say is that the issue should be opened with the adapter and that the adapter dev needs to update  the adapter-react dependency to fix that issue!

**Comment by GermanBluefox** [comment]
@Apollon77 He is the adapter dev.

**Comment by GermanBluefox** [comment]
@o0shojo0o please Update it
https://github.com/o0shojo0o/ioBroker.matomo/blob/main/package.json#L30

To 1.6.20 or newer

**Comment by o0shojo0o** [comment]
oh man, sorry Dennis I have totally overlooked that you have referred to the adapter-react... 
I have now updated the adapter-react, but has also brought no improvement.

![image](https://user-images.githubusercontent.com/19333515/118598881-0e2e3080-b7af-11eb-99c9-5732cbbfc7de.png)
![image](https://user-images.githubusercontent.com/19333515/118598895-10908a80-b7af-11eb-82c9-fc184a76a2b1.png)

**Comment by GermanBluefox** [comment]
Please try 1.6.21 **adapter-react**

**Comment by o0shojo0o** [comment]
Thanks, now it works!
