### ISSUE TITLE
adminTab von Backitup öffnet seit Version 5.0.24 nicht mehr

### ISSUE THREAD

**Issue by simatec** [ioBroker/ioBroker.admin#876]
Seit Version 5.0.24 und react=true öffnet der adminTab von Backitup nicht mehr und gibt folgenden Fehler aus

![image](https://user-images.githubusercontent.com/39792461/118270031-b1d1c500-b4bf-11eb-8c1f-031f1460b315.png)
Die Instance kann nicht mehr ermittelt werden.

Ich habe mal ein paar Logs eingebaut und daraus konnte ich folgendes ermitteln:

window.loction: http://192.168.123.212:9081/adapter/backitup/tab_m.html?newReact=true
window.location.search.replace(/^?/, '').split('&'): newReact=true

Die Instance kann nicht ermittelt werden.

Mit react=false öffnet der adminTab von Backitup problemlos

**Comment by simatec** [comment]
Hier die settings für den adminTab von Backitup
https://github.com/simatec/ioBroker.backitup/blob/809ae58f15e8f337e9e0ff708c069785083df41f/admin/adapter-settings.js#L8

**Comment by GermanBluefox** [comment]
It is because singleton true:
https://github.com/simatec/ioBroker.backitup/blob/master/io-package.json#L211

Singleton means, your code does not need some specific instance and the GUI is responsible for all instances, like scenes/JS.

**Comment by simatec** [comment]
Ich muss es jetzt so lösen, um die Instance Nummer zu bekommen.
https://github.com/simatec/ioBroker.backitup/blob/d2dfcac2aa606746ff9e3a6dbb013660234c1a1d/admin/adapter-settings.js#L8 
Ohne ".split('=')[1]" bekommt man die Ausgabe instance=0

Eigentlich war die Idee von Backitup es "singleton true" zu haben
Das musste ich jetzt ändern auf singleton false

**Comment by GermanBluefox** [comment]
Please never use own adapter-settings.js!
Adapter specific changes could be done in adapter-settings, but your adapter will not get these changes as uses own version of adapter-settings.

If you wanted to create singleton, so you don't need an instance number. Singleton runs only once. But your adapter could be installed many times.

**Comment by simatec** [comment]
Die adapter-settings.js ist nur für den adminTab, da es mit der originalen bei mir Probleme gab.

**Comment by sbormann** [comment]
Ja, bei mir auch, habe für den Alias-Manger auch eine leicht abgewandelte adapter-settings.js genommen. Wenn gewünscht, kann ich in der originalen die Änderungen als PR zur Verfügung stellen?

**Comment by GermanBluefox** [comment]
> Ja, bei mir auch, habe für den Alias-Manger auch eine leicht abgewandelte adapter-settings.js genommen. Wenn gewünscht, kann ich in der originalen die Änderungen als PR zur Verfügung stellen?

Ist gewünscht

**Comment by GermanBluefox** [comment]
PLease retest with 2.0.25

**Comment by sbormann** [comment]
> > Ja, bei mir auch, habe für den Alias-Manger auch eine leicht abgewandelte adapter-settings.js genommen. Wenn gewünscht, kann ich in der originalen die Änderungen als PR zur Verfügung stellen?
> 
> Ist gewünscht

Here are the pull-requests (i edited it online on github - so i had to make two separate PRs for both files):

* For non-react:
    https://github.com/ioBroker/ioBroker.admin/pull/884

* For react:
    https://github.com/ioBroker/ioBroker.admin/pull/885

@simatec @arteck I think that should solve the problems with the tab-version of your admin-pages, if you use this new admin-settings.js from admin instead of your own modified one.

**Comment by simatec** [comment]
With version 5.0.26 it works fine

Many Thanks @GermanBluefox

**Comment by sbormann** [comment]
@simatec Wie machst Du das inzwischen? Nutzt Du auch noch Deine eigene adapter-settings.js?

**Comment by simatec** [comment]
Ja eine abgespeckte nutze ich für Backitup

**Comment by sbormann** [comment]
Habe inzwischen herausgefunden, dass man auch die von bluefox modifizierte Original-Datei nutzen kann, wenn man in der io-package.json den Link um ein ?0&noFooter ergänzt. Beispiel:
````
        "adminTab": {
            "name": {
                "en": "Alias-Manager",
                "de": "Alias-Manager",
                "ru": "Alias-Manager",
                "pt": "Alias-Manager",
                "nl": "Alias-Manager",
                "fr": "Alias-Manager",
                "it": "Alias-Manager",
                "es": "Alias-Manager",
                "pl": "Alias-Manager",
                "zh-cn": "Alias-Manager"
            },
            "singleton": true,
            "fa-icon": "control_point_duplicate",
            "link": "/adapter/alias-manager/index_m.html?0&noFooter"
        },
````
0 steht für Instanz 0, noFooter steht dafür, die untere Leiste mit den Buttons auszublenden.
