### ISSUE TITLE
Admin 5.0.24: Benutzergruppen können nicht angelegt werden & kein ändern der Rechte möglich

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#878]
**Describe the bug**  
- Es ist nicht möglich neue Benutzergruppen anzulegen
- Das Ändern der Rechte der bereits angelegten Standardgruppe "Benutzer" ist nicht möglich

**To Reproduce**  
unter "Benutzer"

**Expected behavior**  
- Neue Benutzergruppen sollen angelegt werden können
- Rechte können geändert werden und diese sollen den der Gruppe zugewiesenen Benutzer zugewiesen werden

**Screenshots & Logfiles**  
![7465EB67-E85A-4788-B78F-2E315B0179B2](https://user-images.githubusercontent.com/69053781/118322561-9dadb800-b4ff-11eb-89e6-6b8969e47377.jpeg)

**Versions:** 
Adapter version: admin v5.0.22 und 5.0.24
JS-Controller version: v3.3.8
Node version: v12.22.1

**Additional context**  
siehe https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/491?_=1621021819113

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 5.0.26
New usergroup can be created and permissions of defaultgroup "Benutzer" can be changed
