### ISSUE TITLE
Keine Geräte und Karte im Zigbee-Tab nach Update auf 5.0.24

### ISSUE THREAD

**Issue by MMeinhardt1** [ioBroker/ioBroker.admin#880]
Nach Update auf 5.0.24 funktioniert der Zigbee-Tab nicht mehr, nach downgrade auf 5.0.22 klappt es wieder. Version 5.0.23 kann leider nicht installiert werden!

pi@ioBroker:~ $ iob upgrade iobroker.admin@5.0.23

This downgrade of "admin" will remove the following changes:
==========================================================================
-> 5.0.24
Admin5: GUI fixes
==========================================================================

Would you like to downgrade admin from @5.0.24 to @5.0.23 now? [(y)es, (n)o]: y
Update admin from @5.0.24 to @5.0.23
host.ioBroker Adapter "system.adapter.admin.0" is stopped.
NPM version: 6.14.12
npm install iobroker.admin@5.0.23 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.admin@5.0.23.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-05-15T09_15_57_862Z-debug.log
upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/words.js words.js application/javascript
Update "system.adapter.admin.0"
upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json jsonConfig.json application/json
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index.html index.html text/html
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png
Adapter "admin" updated
host.ioBroker Adapter "system.adapter.admin.0" is started
pi@ioBroker:~ $ iob upgrade iobroker.admin@5.0.22

This downgrade of "admin" will remove the following changes:
==========================================================================
-> 5.0.24
Admin5: GUI fixes

-> 5.0.23
Admin5: GUI fixes
==========================================================================

Would you like to downgrade admin from @5.0.24 to @5.0.22 now? [(y)es, (n)o]: y
Update admin from @5.0.24 to @5.0.22
host.ioBroker Adapter "system.adapter.admin.0" is stopped.
NPM version: 6.14.12
npm install iobroker.admin@5.0.22 --loglevel error --prefix "/opt/iobroker" (System call)
upload [4] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/words.js words.js application/javascript
Update "system.adapter.admin.0"
upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json jsonConfig.json application/json
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index.html index.html text/html
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png
Adapter "admin" updated
host.ioBroker Adapter "system.adapter.admin.0" is started
pi@ioBroker:~ $

![86E8010F-059C-485B-9A2C-0E4BC5BB5D31](https://user-images.githubusercontent.com/56205459/118355625-3d575e80-b571-11eb-89c9-7ccabd5d86e9.png)

**Comment by bluefish007** [comment]
Wenn du über Instanzen -> Zigbee gehst, klappt es. Der Link in der Seitenleiste scheint defekt zu sein. 

Anstatt e (system.adapter.zigbee.e)  müsste da eine 0 stehen, denke ich mir...

**Comment by MMeinhardt1** [comment]
Die Aussage macht für mich wenig Sinn, denn bei 5.0.24 habe ich es über die Adresszeile mit IP:PORT/#tab-zigbee-0 getestet und auch dort der selbe Fehler. Dürfte somit kein falscher link aus dem Menü sein, oder hast du es bei Dir so nachvollziehen können?

**Comment by bluefish007** [comment]
IP:PORT/#tab-instances/config/system.adapter.zigbee.0 funktioniert unter 5.0.24!

**Comment by GermanBluefox** [comment]
please retest with 2.0.25

**Comment by MMeinhardt1** [comment]
Die Version 5.0.25 wird mir nicht angeboten und über die Katze geht auch nicht, siehe Screenshot 

![1DEB5662-94CF-4D83-9F5E-E34CE8810FB8](https://user-images.githubusercontent.com/56205459/118385623-d6898200-b610-11eb-8639-aeea89f8686f.png)

**Comment by skvarel** [comment]
> 
> 
> please retest with 2.0.25

It works .. thx!

![grafik](https://user-images.githubusercontent.com/1114419/118389708-6805ed80-b62b-11eb-99fe-d4363edd0358.png)

**Comment by MMeinhardt1** [comment]
> > please retest with 2.0.25
> 
> It works .. thx!
> 

Ist Dir das Update im iobroker angeboten worden? Oder wie hast du es installiert?

**Comment by bluefish007** [comment]
> > > please retest with 2.0.25
> > 
> > 
> > It works .. thx!
> 
> Ist Dir das Update im iobroker angeboten worden? Oder wie hast du es installiert?

Wer mit alpha Versionen rumspielt, sollte auch wenigstens ein bisschen mit den Grundlagen vertraut sein, meiner Meinung nach!

cd /opt/iobroker
npm install iobroker.admin@5.0.25


Und ja, das Problem ist mit 5.0.25 behoben!

**Comment by skvarel** [comment]
.. oder so:
(das klappt, weil die Versions-Infos direkt von npm geladen werden)
![grafik](https://user-images.githubusercontent.com/1114419/118393854-8b3b9780-b641-11eb-910c-791c7365a0d6.png)
