### ISSUE TITLE
tooltip for long device name

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#881]
![grafik](https://user-images.githubusercontent.com/6681528/118388466-f9259600-b624-11eb-8294-2dedcf0c6af6.png)

i cant see the full name.. and the col "Name" is fixed

**Comment by arteck** [comment]
![grafik](https://user-images.githubusercontent.com/6681528/118388547-849f2700-b625-11eb-82e3-b57f1ffdd8c6.png)

**Comment by GermanBluefox** [comment]
> ![grafik](https://user-images.githubusercontent.com/6681528/118388466-f9259600-b624-11eb-8294-2dedcf0c6af6.png)
> 
> i cant see the full name.. and the col "Name" is fixed

There is ALWAYS some name, that is longer than filed. ALWAYS.

**Comment by Feuer-sturm** [comment]
Admin 5.0.27

In 5.0.27 there is a tooltip. I am not sure if this was available in previous versions.
![grafik](https://user-images.githubusercontent.com/25422320/118636755-52342c00-b7d5-11eb-8183-7799fefe17c9.png)
