### ISSUE TITLE
Probleme nach Update auf 5.0.25

### ISSUE THREAD

**Issue by Matt77CHE** [ioBroker/ioBroker.admin#882]
Hallo
ich habe versucht den Admin Adapter auf 5.0.25 zu bringen via github.
Ich habe dann folgende Meldung erhalten:

This adapter cannot be installed directly from github.
You must install it from npm.
Write for that "npm install iobroker.admin" in according directory.

- ok; das habe ich anschliessend gemacht, js-controller etc auch updatet.

nun habe ich folgendes Problem;
Wenn ich wieder den iobroker öffnen will, kommt noch immer diese obengenannte "Fehlermeldung", obwohl das Update erfolgreich durchgeführt wurde. Vis und Vis Editor funktionieren - aber in den iobroker komme ich nicht mehr rein....

hat jemand eine Idee, wieso das so ist und wie ich das beheben kann?

**Comment by GermanBluefox** [comment]
`iob u admin` Ausführen

**Comment by Matt77CHE** [comment]
... entschuldigung - das verstehe ich jetzt nicht ganz was / wie du das meinst...

**Comment by Matt77CHE** [comment]
ok, mittlerweile habe ich glaube ich geschnallt, dass ich das so eingeben soll; habe och gemacht;
In der Konsole kommt dann folgendes:
`upload [3] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/jsonConfig.json jsonConfig.json application/json
upload [2] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index_m.html index_m.html text/html
upload [1] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/index.html index.html text/html
upload [0] admin.admin /opt/iobroker/node_modules/iobroker.admin/admin/admin.png admin.png image/png`

sonst keine Veränderung

**Comment by Matt77CHE** [comment]
Hier noch aus der Browser-Konsole:

> 13:54:53.301 GEThttps://192.168.1.245:8081/
[HTTP/1.1 304 Not Modified 55ms]

	
GET
	
scheme
	https
host
	192.168.1.245:8081
filename
	/
Adresse
	192.168.1.245:8081
Status304
Not Modified
VersionHTTP/1.1
Übertragen349 B (165 B Größe)
Referrer Policystrict-origin-when-cross-origin

    	
    Connection
    	keep-alive
    Date
    	Sun, 16 May 2021 11:54:52 GMT
    ETag
    	W/"a5-1FoCfmWdGYk4lbvgVxhpizrUOxw"
    Keep-Alive
    	timeout=5
    X-Frame-Options
    	SAMEORIGIN
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	de,en-US;q=0.7,en;q=0.3
    Cache-Control
    	max-age=0
    Connection
    	keep-alive
    Cookie
    	io=mXmmQpn988kESPkRAAAG
    DNT
    	1
    Host
    	192.168.1.245:8081
    If-None-Match
    	W/"a5-1FoCfmWdGYk4lbvgVxhpizrUOxw"
    Referer
    	http://192.168.1.245:8082/
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

13:54:53.364 Das Cookie “io” wird bald als Cross-Site-Cookie gegen “https://192.168.1.245:8081/” behandelt, da das Schema nicht übereinstimmt. 2 192.168.1.245:8081
13:54:53.376 GEThttps://192.168.1.245:8081/favicon.ico
[HTTP/1.1 200 OK 0ms]

	
GET
	
scheme
	https
host
	192.168.1.245:8081
filename
	/favicon.ico
Status200
OK
VersionHTTP/1.1
Übertragen165 B (165 B Größe)
Referrer Policystrict-origin-when-cross-origin

    	
    Connection
    	keep-alive
    Content-Length
    	165
    Content-Type
    	text/html; charset=utf-8
    Date
    	Sun, 16 May 2021 11:50:26 GMT
    ETag
    	W/"a5-1FoCfmWdGYk4lbvgVxhpizrUOxw"
    Keep-Alive
    	timeout=5
    X-Frame-Options
    	SAMEORIGIN
    	
    Accept
    	image/webp,*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	de,en-US;q=0.7,en;q=0.3
    Connection
    	keep-alive
    Cookie
    	io=mXmmQpn988kESPkRAAAG
    DNT
    	1
    Host
    	192.168.1.245:8081
    Referer
    	https://192.168.1.245:8081/
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

13:54:53.377 Das Cookie “io” wird bald als Cross-Site-Cookie gegen “https://192.168.1.245:8081/favicon.ico” behandelt, da das Schema nicht übereinstimmt. favicon.ico

**Comment by Matt77CHE** [comment]
Hallo;

kann mir jemand weiterhelfen? - Wäre sehr dankbar.

**Comment by GermanBluefox** [comment]
Ich verstehe nicht was du hier gepostet hast.
Das Kommando `npm install iobroker.admin` hast du vermutlich nicht in `/opt/iobroker` ausgeführt.

```
cd /opt/iobroker
npm install iobroker.admin
iob r admin
```
