### ISSUE TITLE
Installierte Adapter am Anfang, der Kachelansicht anzeigen.

### ISSUE THREAD

**Issue by senger1985** [ioBroker/ioBroker.admin#890]
Wäre es möglich, im Admin 5.2.26, in der Kachelansicht, die installierten Adapter, alphabetisch anzeigenzulassen?

**Comment by GermanBluefox** [comment]
Die sind alfabetisch sortiert:
![image](https://user-images.githubusercontent.com/4582016/118498663-91f00a80-b726-11eb-8d3c-b0695fa54bf5.png)

**Comment by senger1985** [comment]
![admin](https://user-images.githubusercontent.com/35745035/118501998-8fdb7b00-b729-11eb-9ec3-fb6acaccdef9.PNG)
Das ist richtig, aber im alten/weißen Admin, werden erst die installierten Adapter alphabetisch angezeigt und dann kommen die nicht installierten Adapter.
Ich fand das etwas übersichtlicher.

**Comment by GermanBluefox** [comment]
ok

**Comment by Feuer-sturm** [comment]
Admin 5.0.27

In der Adapterübersicht kommen jetzt zuerst die installierten Adapter sortiert von A-Z und danach die Adapter von A-Z ohne eine Instanz.

**Comment by senger1985** [comment]
Bei mir rasselt er ab, in der Adapterübersicht.
Siehe #893
