### ISSUE TITLE
Admin 5 GUI not loaded if domain name used

### ISSUE THREAD

**Issue by nkleber78** [ioBroker/ioBroker.admin#892]
**Describe the bug**  
After update to Admin 5 the GUI is no longer correctly loaded if a subdomain is used. I have a testinstance to verify this

**To Reproduce**  
1. Install Admin 4 -> GUI is correctly loaded with IP address on the used port without https
2. GUI is also correctly loaded if a domain with https and reverse proxy is used
3. Update Admin to 5.0.27
4. Now the GUI is only loaded with IP address, but no longer with the domain with https and reverse proxy

**Screenshots & Logfiles**  
<img width="551" alt="Screenshot 2021-05-17 at 21 37 31" src="https://user-images.githubusercontent.com/35381530/118546414-350d4800-b758-11eb-879c-eb825731d694.png">

**Versions:**  
 - Adapter version: 5.0.27
 - JS-Controller version: 3.2.16, auch update auf 3.3.10 hilft nicht...
 - Node version: 12.21.0
 - Operating system: Linux / Docker

**Comment by Apollon77** [comment]
Your revewrse proxy setup forwards and adds websocket headers? see https://github.com/ioBroker/ioBroker.admin#reverse-proxy

Admin 4 was not needing this because of a "long polling fallback of socketip" which is no longer used

**Comment by nkleber78** [comment]
Thanks @Apollon77 
that solved my issue
