### ISSUE TITLE
Adapteransicht stürzt ab, im Darkmode v5.0.27

### ISSUE THREAD

**Issue by senger1985** [ioBroker/ioBroker.admin#893]
**Describe the bug**  
Nach Aufruf, der Adapter, im Darkmode zeigt die Konsole folgende Fehler, im Microsoft Edge
![admin2](https://user-images.githubusercontent.com/35745035/118562709-85db6b80-b76d-11eb-9209-7ee9e65fa5ce.PNG)

**Versions:**  
 - Adapter version: 5.0.27
 - JS-Controller version: 3.3.10
 - Node version: 12.22.0
 - Operating system: Linux

**Comment by senger1985** [comment]
Kleiner Nachtrag:

Problem tritt "nur" beim Microsoft Edge Version 90.0.818.62 auf.
Unter Firefox ist die Adapteransicht aufrufbar.

**Comment by GermanBluefox** [comment]
SEHR komisch

**Comment by senger1985** [comment]
Ich kann es mir auch nicht erklären
