### ISSUE TITLE
Admin 5.0.27: Standard ACL werden nicht übernommen

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#898]
**Describe the bug**  
werden unter "Systemeinstellungen -> Standard ACL" Einstellungen vorgenommen, z.B.
![1621178946947-c3977d68-688b-4e6d-8001-f93ac7bf27a2-image](https://user-images.githubusercontent.com/69053781/118667342-3ab86b80-b7f4-11eb-8731-f28361f5e069.png)

werden diese beim Neuanlagen eines Ordners und/oder Datenpunktes nicht übernommen:
![1621179020482-5b571a64-a4e7-4d86-ad7e-3c7b066a7d86-image](https://user-images.githubusercontent.com/69053781/118667376-43a93d00-b7f4-11eb-815b-8cd026059b74.png)

**To Reproduce**  
unter "Objekte"

**Expected behavior**  
- Standart ACL werden beim Anlegen eines eines Ordners und/oder Datenpunktes übernommen (Besitzer-Anwender / Besitzer-Gruppe / Objektrechte / Zugriff auf Zustände)

**Versions:**  
Admin v5.0.26 / v5.0.27
Node.js: v12.22.1
js-controller: v3.3.10
Official Docker Image buanet/iobroker: v5.1.0

**Additional context**  
https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/568?_=1621347140165

**Comment by GermanBluefox** [comment]
Und falls man nach "default ACL Ändern", F5 drückt? 
Werden die ACLs dann übernommen?
Das wird mir helfen um Problem zu finden

**Comment by ice987987** [comment]
F5 hilft (bei mir) nicht (google chrome)
Folgend ein Screenshot: Der Standart-ACL wird geändert, nach dem Speichern kommt die Meldung, dann Anlegen eines Ordners und Datenpunktes ohne die Übernahme der zuvor angelegten ACL-Werte.

![Animation](https://user-images.githubusercontent.com/69053781/118698075-47e35380-b810-11eb-9552-6b56cb9ec28f.gif)

**Comment by GermanBluefox** [comment]
This is problem of other module. Issue created: https://github.com/ioBroker/db/issues/54

**Comment by Apollon77** [comment]
should then be fixed in js-controller 3.3.10

**Comment by Apollon77** [comment]
@ice987987 Can you please also retest with js-controller 3.3.11 and Admin 5.1?

**Comment by ice987987** [comment]
I have already tested it and there are still issues. Please see the screenshot [here](https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/707?_=1621881761698)

**Comment by Feuer-sturm** [comment]
Issue is fixed with Admin 5.1.9 and js-controller 3.3.12
See https://github.com/ioBroker/db/issues/54
