### ISSUE TITLE
Admin 5.0.27: "Besitzer-Gruppe" für mehrere Unterobjekte kann nicht geändert werden

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#899]
**Describe the bug**  
die "Besitzer-Gruppe" für mehrere Unterobjekte kann nicht geändert werden wenn diese unterschiedlich vorliegen:
![1621185199387-animation](https://user-images.githubusercontent.com/69053781/118669753-4e64d180-b7f6-11eb-8d24-0a491d65cacc.gif)

**To Reproduce**  
unter "Objekte"

**Expected behavior**  
die "Besitzer-Gruppe" für mehrere Unterobjekte kann geändert werden, auch wenn diese unterschiedlich vorliegen

**Versions:**  
Admin v5.0.26 / v5.0.27
Node.js: v12.22.1
js-controller: v3.3.10
Official Docker Image buanet/iobroker: v5.1.0

**Additional context**  
https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/568?_=1621347140165

**Comment by Feuer-sturm** [comment]
Admin 5.0.28

Is fixed with Admin 5.0.28
