### ISSUE TITLE
Menu Instances not possible to load

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#900]
Admin 5.0.27

Entering the menu "Instances" causes the following error:
![grafik](https://user-images.githubusercontent.com/25422320/118713821-b16c5d80-b822-11eb-9657-063c20e6f1fb.png)

**Comment by Feuer-sturm** [comment]
Error is only there if "Expert mode" is activated.
With deactivated "Expert mode" Instances menu can be opened.

**Comment by GermanBluefox** [comment]
Please retest with 5.0.29

**Comment by Feuer-sturm** [comment]
Master Admin 5.0.29
Slaver Admin 5.0.29

Steps to reproduce:
- ioBroker admin web interface
- enable expert mode
- Switch to menu "instances" will cause the error
![grafik](https://user-images.githubusercontent.com/25422320/119032106-1901e480-b9ac-11eb-836f-70c5b4981a88.png)

But this works:
Steps to reproduce:
- Go to Adapter overview
- Selecte ioBroker slave
- Enable Expert mode
- Switch to instances menu -> everything is fine
![grafik](https://user-images.githubusercontent.com/25422320/119032492-86157a00-b9ac-11eb-90e0-13f304e84886.png)

**Comment by Feuer-sturm** [comment]
Master Admin 5.0.30
Slaver Admin 5.0.30

Issue is fixed with 5.0.30

Steps to reproduce:
    Enter ioBroker admin web interface
    enable expert mode
    Switch to menu "instances" -> ok
