### ISSUE TITLE
No role requested when data point is manually created

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#901]
![grafik](https://user-images.githubusercontent.com/4311558/118722673-b6360f00-b82c-11eb-8e7d-cf634982780f.png)

**Comment by daniel-lo** [comment]
The bottom line is that I cannot add the data point to alexa devices.



iot.0 | 2021-05-18 13:32:25.763 | error | "0_userdata.0.lg_chromecast" not exists or no native part.
-- | -- | -- | --

**Comment by Apollon77** [comment]
The role is missing

**Comment by Apollon77** [comment]
We should add a role too

**Comment by daniel-lo** [comment]
If you write "should" it seems to be not mandatory. Brings me back to the point where I cannot add the data point to my Alexa Devices .. how can I handle this?

**Comment by GermanBluefox** [comment]
Please retest with 50.30

**Comment by daniel-lo** [comment]
5.0.31 .. no change .. (hab den datenpunkt auch neu gemacht .. boolean)

**Comment by GermanBluefox** [comment]
Was hat dieses issue mit Admin5 zu tun? Objekt kann doch erzeugt werden.

**Comment by Apollon77** [comment]
Naja, ein neues Pnbjekt ohne eine passende Rolle kann weder in Visus noch in iot sinnvoll genutzt werden ... daher war die Idee ob man nicht darüber sicherstellt das die Rolle da ist. Was ist die Alternative? Der User geht nach der Anlage nochmal auf "Edit" vom Objekt um die Rolle zu setzen?

Frage auch: Wollen wir das alle Objekte eine Rolle haben? Adapter-Devs "zwingen" wir dazu ...

**Comment by GermanBluefox** [comment]
Die Rolle ist da und nämlich "state"

**Comment by Apollon77** [comment]
Oohh ... blind me ... then ok the user nees to edit the onbject (because e.g. iot will not do anything with a "state "role from what I know (or I remember wrong) :)

**Comment by daniel-lo** [comment]
@Apollon77 tbh .. I am no fan of user guidance if it could/should be prevented .. adding objects to iot devices is a basic functionality that should just work. Maybe in IOT adapter ask for the role when adding the object/device?

**Comment by daniel-lo** [comment]
@Apollon77 tbh .. I am no fan of user guidance if it could/should be prevented .. adding objects to iot devices is a basic functionality that should just work. Maybe in IOT adapter ask for the role when adding the object/device?

**Comment by Apollon77** [comment]
In fact it is an iot topic ... admin needs to be generic and according to specificsation role:state ist the generic role ... so when we are on iot

**Comment by Apollon77** [comment]
@GermanBluefox can decide if an additional text is helpful in admin or not

**Comment by daniel-lo** [comment]
@Apollon77

Wo back to this?
https://github.com/ioBroker/ioBroker.iot/issues/287

**Comment by Apollon77** [comment]
yes
