### ISSUE TITLE
Top Banner überlagert die Schaltflächen darunter / IMac

### ISSUE THREAD

**Issue by Tagiwara** [ioBroker/ioBroker.admin#904]
Ich benutze einen IMac und habe ein Anzeigeproblem wie auf dem Bild dargestellt.
![118757482-7f341d80-b86d-11eb-9cff-5b6854e06ddd](https://user-images.githubusercontent.com/41060053/118864971-c60f2b00-b8e0-11eb-9979-45d1653a6388.jpg)
Das Banner oben überlagert die darunterliegenden Schaltflächen.

Identisch beim Safari, FF und Chrome.

Habe erstmalig den Admin 5.0.27 auf meinem Te

stsystem installiert, kann also nicht sagen, ob es bei den Versionen davor anders war.

 - Adapter version: 5.0.27
 - JS-Controller version: 3.3.10
 - Node version: 12.22.1
 - Operating system: Ubuntu 20.04

**Comment by GermanBluefox** [comment]
Früher war Internet Explorer das Problem, jetzt gibt es Apfel. :(

**Comment by Tagiwara** [comment]
Ich habe die Lösung. Es liegt am Benutzer der oben rechts angezeigt wird. Wenn der Name zu lang ist, mach der da eine Zeilenschaltung und das Banner wird um diese Zeilenschaltung größer. Bei einem kurzen Namen ist das nicht so.

![Bildschirmfoto 2021-05-21 um 19 13 08](https://user-images.githubusercontent.com/41060053/119174216-9a1eb180-ba68-11eb-83f6-c4b28025eb6d.jpg)

![Bildschirmfoto 2021-05-21 um 19 12 36](https://user-images.githubusercontent.com/41060053/119174229-9c810b80-ba68-11eb-8c86-c1445a9594eb.jpg)

**Comment by GermanBluefox** [comment]
Das ist schon besser

**Comment by Tagiwara** [comment]
kann man vielleicht noch anpassen. Beitrag kann also auf erledigt gesetzt werden

**Comment by GermanBluefox** [comment]
Das werde ich fixen. Danke fürs Forschen
