### ISSUE TITLE
Admin 5.0.28 (react mode): Adding room (enum) not possible

### ISSUE THREAD

**Issue by k3nz3l** [ioBroker/ioBroker.admin#905]
When hitting the + button to add an enum, the GUI crashes.

Error details attached as error.log
[error.log](https://github.com/ioBroker/ioBroker.admin/files/6511601/error.log)

**Comment by GermanBluefox** [comment]
Please retest with 5.0.29

**Comment by k3nz3l** [comment]
Hi,
i retested with 5.0.29, but it is still crashing with the same error. see attached.
Do you need any other information?
npm version = 7.11.2
nodejs version = 10.20.1
[5.0.29_error.log](https://github.com/ioBroker/ioBroker.admin/files/6518303/5.0.29_error.log)

**Comment by k3nz3l** [comment]
I installed 5.0.31 now and retested it.
Seems to work now.
Thx
