### ISSUE TITLE
admin 5.0.29 start or restart not visible

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#906]
adapter stop works but is not correct visible .. after F5 i see all is fine

https://user-images.githubusercontent.com/6681528/118920275-680d3280-b936-11eb-8325-2272f8fee438.mp4

**Comment by MarkSau** [comment]
i can reproduce it...only with F5 is see the correct state of instance

**Comment by GermanBluefox** [comment]
It is a global error in 5.0.29 with object update. Please wait with creation of new issues till 5.0.30.

**Comment by GermanBluefox** [comment]
Please retest with 5.0.29

**Comment by arteck** [comment]
.30

**Comment by Feuer-sturm** [comment]
@GermanBluefox @arteck 
On my system Master Admin 5.0.32 and Slave 5.0.32 there is a direct status change after stopping and starting an instance.
No page refresh is necessary.

On my system -> ok
