### ISSUE TITLE
5.0.29 Adapterliste nicht funktionsfähig

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#907]
Nach dem Update auf 5.0.29 sind laut Adapterliste keineAdapter installiert, auch die Versionen sind nicht sichtbar:
![grafik](https://user-images.githubusercontent.com/34395245/118952216-0bbd0980-b95c-11eb-8f6f-47100a28a201.png)

Ebenso kann ma die Icons hinten nicht nutzen.
Der Host wird als offline im Log gekennzeichnetIn der Systemübersicht ist der Slave aber da:
![grafik](https://user-images.githubusercontent.com/34395245/118952470-4757d380-b95c-11eb-99b6-8c72e8a89772.png)
![grafik](https://user-images.githubusercontent.com/34395245/118952524-5179d200-b95c-11eb-980f-d58aa617b77f.png)

**Comment by GermanBluefox** [comment]
No issues for old GUI are accepted any more. Please switch to react GUI or stay on version 4
