### ISSUE TITLE
Admin 5.0.29: Text auf Button verschoben

### ISSUE THREAD

**Issue by ice987987** [ioBroker/ioBroker.admin#908]
**Describe the bug**  
Beim Löschen eines Ordners unter Objekte ist die Anzeige der Icons auf den Buttons unschön verschoben

**To Reproduce**  
unter „Objekte“

**Expected behavior**  
Text und Icon innerhalb der Button

**Screenshots & Logfiles**  
![](https://forum.iobroker.net/assets/uploads/files/1621534402128-342e2c7d-4947-4047-a2b3-bcdf0a135367-image.png)

**Versions:**  
 Admin v5.0.29
Node.js: v12.22.1
js-controller: v3.3.10
Official Docker Image buanet/iobroker: v5.1.0
google chrome: v90.0.4430.212

**Additional context** 
siehe https://forum.iobroker.net/topic/44282/test-adapter-admin-5-0-x-alpha-der-neuen-ui/619?_=1621544653995

**Comment by Apollon77** [comment]
Yes, we will adjust the texts

**Comment by Apollon77** [comment]
Loca will be adjusted for next version
