### ISSUE TITLE
Admin 5.0.30 Darstellungsfehler im IOT Adapter

### ISSUE THREAD

**Issue by haselchen** [ioBroker/ioBroker.admin#912]
Kurz und schmerzlos,

beim Ändern eines Gerätes im IOT Adapter fiel mir auf, dass ich nicht bis nach ganz unten scrollen kann, dort überdeckt ein Banner das letzte Gerät. Klassische Ansicht, kein React.

Browser Firefox
Version 88.0.1

Refresh durchgeführt und Cache wurde mehrfach geleert.

![Unbenannt](https://user-images.githubusercontent.com/42101470/119148228-954c0480-ba4c-11eb-9e7d-c61c75bdd965.JPG)

**Comment by GermanBluefox** [comment]
Admin5 lässt alles wunderbar bis zu Ende scrollen:
![image](https://user-images.githubusercontent.com/4582016/119174360-c76b5f80-ba68-11eb-84fd-8564d296b4b8.png)
Please use Admin5

**Comment by haselchen** [comment]
Ich benutze Admin 5 , wie oben schon beschrieben.
In der klassischen Ansicht. Das es bei Dir funktioniert, hilft mir leider nicht weiter.

**Comment by GermanBluefox** [comment]
Es gibt kein klassischen Ansicht mehr.
