### ISSUE TITLE
Easy Admin tiles has wrong language

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#913]
Admin 5.0.30

Language is set to "Deutsch".
![grafik](https://user-images.githubusercontent.com/25422320/119189505-6c436800-ba7c-11eb-8d00-86a1f898777e.png)

But if Easy Admin is selected the text in the tiles is in english
![grafik](https://user-images.githubusercontent.com/25422320/119189571-811ffb80-ba7c-11eb-88c8-e1ae092bbbd9.png)

**Comment by Apollon77** [comment]
@Feuer-sturm maybe also missing translation keys? Can you please check and maybe add to the other issue?

**Comment by Feuer-sturm** [comment]
@Apollon77 There is nothing in the browser console. It is empty if I switch to Easy Admin

**Comment by GermanBluefox** [comment]
Fixed

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 5.0.32
