### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#914]
Admin 5.0.30

This issue shall collect and list up text elements which are not translated yet.

For example:
![grafik](https://user-images.githubusercontent.com/25422320/119195497-07d8d680-ba85-11eb-950b-44c69270a138.png)

In the browser console a message will be there which starts with "Translate: .............."
If you find this in your browser console please add the string here in a comment

```
Translate: API key
Translate: Restart works only if controller started as system service.
```

**Comment by Feuer-sturm** [comment]
`Translate: IP is domain or more than one address`

**Comment by Feuer-sturm** [comment]
```
Translate: controller
Translate: Collapse all
Translate: Expand all
Translate: Enum parameters
Translate: Debug instance
Translate: Filter
Translate: Instances
Translate: Start
Translate: easy
Translate: for programmers
Translate: for professionals
Translate: copy

Translate: Åland Islands
 Translate: Cocos (Keeling) Islands
 Translate: Congo, The Democratic Republic of the
 Translate: Cote D'Ivoire
 Translate: Heard Island and Mcdonald Islands
 Translate: Holy See (Vatican City State)
 Translate: Iran, Islamic Republic Of
 Translate: Korea, Democratic People'S Republic of
 Translate: Korea, Republic of
 Translate: Lao People'S Democratic Republic
 Translate: Macao
 Translate: Macedonia, The Former Yugoslav Republic of
 Translate: Micronesia, Federated States of
 Translate: Moldova, Republic of
 Translate: Palestinian Territory, Occupied
 Translate: RWANDA
 Translate: Saint Helena
 Translate: Saint Pierre and Miquelon
 Translate: Serbia and Montenegro
 Translate: South Georgia and the South Sandwich Islands
 Translate: Svalbard and Jan Mayen
 Translate: Taiwan, Province of China
 Translate: Tanzania, United Republic of
 Translate: Timor-Leste
 Translate: United States Minor Outlying Islands
 Translate: Viet Nam
 Translate: Virgin Islands, British
 Translate: Virgin Islands, U.S.
 Translate: Wallis and Futuna
```

**Comment by Feuer-sturm** [comment]
```
Translate: ra_Deselect all
Translate: ra_Select all
```

**Comment by GermanBluefox** [comment]
> Missing translations which are shown by using "Skripte" menu (Javascript Adapter 5.1.3)
> 
> ```
> Translate: ra_Deselect all
> Translate: ra_Select all
> Translate: ra_On weekdays
> Translate: debug_help
> Translate: debug
> Translate: verbose_help
> Translate: verbose
> Translate: Debug instance
> Translate: debug_help
> 
> Translate: Debug instance
> Translate: Resume execution
> Translate: Go to next line
> Translate: Step into function
> Translate: Step out from function
> Translate: Stop on exception
> Translate: Console
> Translate: Stack
> ```

It is issue for javascript adapter and not admin

**Comment by GermanBluefox** [comment]
> ```
> Translate: controller
> Translate: Collapse all
> Translate: Expand all
> Translate: Enum parameters
> Translate: Debug instance
> Translate: Filter
> Translate: Instances
> Translate: Start
> Translate: easy
> Translate: for programmers
> Translate: for professionals
> Translate: copy
> 
> Translate: Åland Islands
>  Translate: Cocos (Keeling) Islands
>  Translate: Congo, The Democratic Republic of the
>  Translate: Cote D'Ivoire
>  Translate: Heard Island and Mcdonald Islands
>  Translate: Holy See (Vatican City State)
>  Translate: Iran, Islamic Republic Of
>  Translate: Korea, Democratic People'S Republic of
>  Translate: Korea, Republic of
>  Translate: Lao People'S Democratic Republic
>  Translate: Macao
>  Translate: Macedonia, The Former Yugoslav Republic of
>  Translate: Micronesia, Federated States of
>  Translate: Moldova, Republic of
>  Translate: Palestinian Territory, Occupied
>  Translate: RWANDA
>  Translate: Saint Helena
>  Translate: Saint Pierre and Miquelon
>  Translate: Serbia and Montenegro
>  Translate: South Georgia and the South Sandwich Islands
>  Translate: Svalbard and Jan Mayen
>  Translate: Taiwan, Province of China
>  Translate: Tanzania, United Republic of
>  Translate: Timor-Leste
>  Translate: United States Minor Outlying Islands
>  Translate: Viet Nam
>  Translate: Virgin Islands, British
>  Translate: Virgin Islands, U.S.
>  Translate: Wallis and Futuna
> ```

I can't find many text in admin.... Where are they from? Javascript?

**Comment by Feuer-sturm** [comment]
> 
> 
> > Missing translations which are shown by using "Skripte" menu (Javascript Adapter 5.1.3)
> > ```
> > Translate: ra_Deselect all
> > Translate: ra_Select all
> > Translate: ra_On weekdays
> > Translate: debug_help
> > Translate: debug
> > Translate: verbose_help
> > Translate: verbose
> > Translate: Debug instance
> > Translate: debug_help
> > 
> > Translate: Debug instance
> > Translate: Resume execution
> > Translate: Go to next line
> > Translate: Step into function
> > Translate: Step out from function
> > Translate: Stop on exception
> > Translate: Console
> > Translate: Stack
> > ```
> 
> It is issue for javascript adapter and not admin

ok. https://github.com/ioBroker/ioBroker.javascript/issues/845

**Comment by Feuer-sturm** [comment]
> 
> 
> > ```
> > Translate: controller
> > Translate: Collapse all
....
> > ```
> 
> I can't find many text in admin.... Where are they from? Javascript?

Hello @GermanBluefox , I updated my comment https://github.com/ioBroker/ioBroker.admin/issues/914#issuecomment-846284662 with the menu where I saw the entry in the browser console

**Comment by GermanBluefox** [comment]
Many translations added. 
I don't want to translate the missing lands, as the RWANDA, imho, could live without translation.

"Scenes" belongs to scenes adapter and not admin

**Comment by Feuer-sturm** [comment]
With Admin 5.1.8 there are no message any more in the browser console -> fixed:
Host restart message 

Objects
Translate: Folder

Adapter
Translate: From npm

Instances
Translate: controller

Enumerations
Translate: Collapse all
Translate: Expand all
Translate: Enum parameters

**Comment by Feuer-sturm** [comment]
> "Scenes" belongs to scenes adapter and not admin

https://github.com/ioBroker/ioBroker.scenes/issues/109
