### ISSUE TITLE
Host basic settings - switching database type

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#917]
Admin 5.0.31
js-controller 3.3.10

What is the use case for switching from file to redis for database type for objects and states if no migration will be done?
![grafik](https://user-images.githubusercontent.com/25422320/119225713-bc1a4180-bb05-11eb-9ee2-8f36ce1c80a7.png)

A short explanation would be helpfull here.

**Comment by GermanBluefox** [comment]
No use. Just ignore it.

**Comment by Apollon77** [comment]
Or we simply do not allow to witch at all ... so leave "db type" as read only field? SO you can edit details ...  and we could add a quetionmark beside db type telling "to change it use iob setup custom"

**Comment by GermanBluefox** [comment]
People I am a bit tired of any suggestions and one more dialog texts. 
First people wanted to have edit of base settings. I have done it.
Then oooo I switched the DB and all my data lost .... What happened, OK I added dialog.
Now this.

**Comment by Apollon77** [comment]
Hm ... somewhen it is better in my eyes to prtect the user from errors very hard then allowing-but-warning.

Editing the host settings is a very grerat idea, but yes some field may be a bad idea to be changed that way - like this.

Honestly: If a user changes DB the system _will be_broken by 100% if he save and restart. There is no other chance then having a broken system, so I would protect user from risking that. Sorry that I was not seeng the "i broke my system with changeing db type" issue, else I would have broight that idea up earlier.

**Comment by GermanBluefox** [comment]
I can say the same about redis port, redis IP, redis password. The invalid setting in any of these options leads to "dead" host.

**Comment by GermanBluefox** [comment]
My suggestion:
![image](https://user-images.githubusercontent.com/4582016/119270507-3e396180-bbfd-11eb-9a21-9c0cc6bc875a.png)

**Comment by Apollon77** [comment]
Can we add one mor text on top "below" the "Danger zone? Stating:

"Changing these values can lead to a non-operational ioBroker system. Unless you knoww exactly what you do please better use "iob setup custom" to change the database type or basic database settings."

**Comment by Feuer-sturm** [comment]
Admin 5.1.7

Proposal from @Apollon77 is implemented in Admin 5.1.7
![grafik](https://user-images.githubusercontent.com/25422320/120903355-09d69400-c646-11eb-94df-926861264680.png)

I will close this issue.
