### ISSUE TITLE
Admin 5.0.31: _ID nicht editierbar

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.admin#919]
Neue GUI: Bei Datenpunkten kann die ID nicht editiert werden, es wird keine Option zum speichern angeboten. Werden weitere Zeilen editiert, wird speichern zwar angeboten, aber die Änderung der ID wird nicht übernommen:
![Aufnahme_2021_05_23_09_32_22_369](https://user-images.githubusercontent.com/34395245/119252017-02c17780-bbaa-11eb-9c57-f0676616c67a.gif)

Schalte ich auf die "alte Ansicht" zurück, ist der DP wieder komplett änderbar.

Node.js 12.22.1
NPM 6.14.12
js-controller: 3.3.10

**Comment by GermanBluefox** [comment]
_id darf man nicht ändern. Benutze Clone Funktion (unten rechts)
