### ISSUE TITLE
Log Message empty

### ISSUE THREAD

**Issue by fuchs-1978** [ioBroker/ioBroker.admin#920]
In der letzten Version von heute habe ich Log keine Einträge in der Spalte Nachrichten
![Screenshot_2021-05-23-22-25-25-057_com android chrome](https://user-images.githubusercontent.com/61315711/119275595-43ef7100-bc16-11eb-927c-5f1b3def027b.jpg)

**Comment by MMeinhardt1** [comment]
Ich kann diesen Fehler bestätigen 

![AD3AB0E2-AEAA-4E98-8628-7C668AB802B1](https://user-images.githubusercontent.com/56205459/119275936-3a670880-bc18-11eb-8059-266fe4ec34c8.png)

**Comment by GermanBluefox** [comment]
Should be fixed in v5.1.0

**Comment by Feuer-sturm** [comment]
@GermanBluefox Is fixed with 5.1.0 :-)
