### ISSUE TITLE
5.0.32 Instanzen -> Adapter -> Schraubschlüssel -> klick

### ISSUE THREAD

**Issue by Dirk-Peter-md** [ioBroker/ioBroker.admin#922]
In Instanzen -> Adapter -> Schraubschlüssel -> klick öffnen sich die Einstellungen nicht mehr

![Screenshot 2021-05-23 232218](https://user-images.githubusercontent.com/52133172/119277458-21625580-bc20-11eb-8481-ffd5547a0491.jpg)
---
Admin: 5.0.32
js-controller: 3.3.10
PLATTFORM: LINUX
BETRIEBSSYSTEM: LINUX
ARCHITEKTUR: ARM
CPUS: 4
GESCHWINDIGKEIT: 1800 MHZ
MODELL: ARMV7 PROCESSOR REV 1 (V7L)
RAM: 1.9 GB
SYSTEM-BETRIEBSZEIT: 22 T. 12:13:27
NODE.JS: V12.22.1
NPM: 6.14.12
DATENTRÄGERGRÖSS: 14.3 GB
FESTPLATTE FREI: 7.8 GB
ADAPTER-ANZAHL: 411
BETRIEBSZEIT: 8 T. 14:55:27
AKTIVE INSTANZEN: 14
PFAD: /OPT/IOBROKER/

**Comment by MMeinhardt1** [comment]
Hier das gleiche Problem, Admin 5.0.32 und JS-Controller 3.3.11

**Comment by Matt77CHE** [comment]
Bei mir auch das selbe Problem, Admin 5.0.32 und JS-Controller 3.3.11

**Comment by Michaelnorge** [comment]
Hier auch.

**Comment by solver4711** [comment]
Leider mir auch das selbe Problem, Admin 5.0.32 und JS-Controller 3.3.11

**Comment by fu-zhou** [comment]
Habe ich auch, zurück zu 5.0.31 funktioniert wieder

**Comment by breitenberger** [comment]
> Habe ich auch, zurück zu 5.0.31 funktioniert wieder

Frage: Wie funktioniert dies ??    please help me

LG Robert

**Comment by fu-zhou** [comment]
Du kannst eine bestimmte Version installieren:
![image](https://user-images.githubusercontent.com/11984960/119305285-d456a180-bc68-11eb-84d0-29dbe887ab3b.png)
Auf das "+" klicken (vorletztes Symbol in der Adapterzeile) und die 5.0.31 auswählen.

**Comment by breitenberger** [comment]
> Du kannst eine mögliche Version herunterladen: Auf das "+" klicken (vorletztes Symbol in der Adapterzeile) und sterben 5.0.31 finden.
> ![Bild](https://user-images.githubusercontent.com/11984960/119305285-d456a180-bc68-11eb-84d0-29dbe887ab3b.png)

Läuft wieder - DANKE

**Comment by JBSullivan** [comment]
DITO unter Windows als BS

![image](https://user-images.githubusercontent.com/44617472/119319327-96fb0f80-bc7a-11eb-9e03-b3b0e5bb481a.png)

**Comment by GermanBluefox** [comment]
Should be fixed in v5.1.0

**Comment by Feuer-sturm** [comment]
Is fixed with 5.1.0
