### ISSUE TITLE
5.0.32 - React UI standardmäßig an und lässt sich nicht deaktivieren

### ISSUE THREAD

**Issue by Speedbreaker12** [ioBroker/ioBroker.admin#923]
Wie schon im Titel beschrieben, ist nach dem Update von 5.0.31 auf 5.0.32 die React UI srandardmäßig aktiviert und lässt sich auch nicht mehr deaktivieren. Laut changelog sieht es nicht so aus, als ob das gewollt ist.

**Versions:**  
 - Adapter version: 5.0.32
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: linux

**Comment by solver4711** [comment]
Leider bei mir auch das selbe Problem, 
Admin 5.0.32 
JS-Controller 3.3.11
Platform linux
Node.js:v12.22.1
NPM:6.14.12

**Comment by GermanBluefox** [comment]
React UI kann jetzt deaktiviert werden, aber ja: React is standartmäßig AN.
Fixed in 5.1.0

**Comment by Feuer-sturm** [comment]
Admin 5.1.0

Alte Oberfläche kann wieder aktiviert werden und nach einem F5 der Seite wird die alte Oberfläche auch vollständig geladen.
