### ISSUE TITLE
5.0.32 Protokoll zeigt nach öffnen keine Nachrichten

### ISSUE THREAD

**Issue by Jogi2020** [ioBroker/ioBroker.admin#925]
Der Bereich Nachrichten bleibt beim öffnen der Protokolle zuerst leer. Angezeigt werden erst die Nachrichten die nach dem Öffnen der Protokolle generiert werden.
Der Fehler tritt seit der Installation des Admin Adapters 5.0.32 auf. gleichzeitig hatte ich auch den Host 3.3.11 installiert.

![image](https://user-images.githubusercontent.com/61438894/119278722-62aa3380-bc27-11eb-9965-5c65615c843c.png)

**Comment by JohGrei** [comment]
Das selbe bei mir, jedoch ohne Upgrade des js-controllers

**Comment by solver4711** [comment]
Leider bei mir auch das selbe Problem, Admin 5.0.32 und JS-Controller 3.3.11

**Comment by Feuer-sturm** [comment]
Dieses Ticket und https://github.com/ioBroker/ioBroker.admin/issues/920 zeigen das gleiche Problem. Eins kann als duplicate markiert und geschlossen werden.
