### ISSUE TITLE
5.0.32 Protokoll - Log Nachrichten werden nicht angezeigt

### ISSUE THREAD

**Issue by inbux** [ioBroker/ioBroker.admin#927]
Wenn man auf Protokoll klickt, werden bei den bestehende Logs der  Nachrichtentext in der Tabelle nicht angezeigt.

Bleibt man auf der Seite, so werden neue Logs die eintreffen, korrekt und vollständig mit Text hinzugefügt.
(die obersten 2 Zeilen)

```

host.iobroker | 2021-05-24 10:10:00.083 | info | instance system.adapter.dwd.0 started with pid 23336
javascript.0 | 2021-05-24 10:09:57.164 | info | script.js.Messungen.AussenTemperatur
javascript.0 | 2021-05-24 10:05:10.012 | info | 
deconz.0 | 2021-05-24 10:05:08.208 | info | 
javascript.0 | 2021-05-24 10:05:00.053 | warn
....
```

**Comment by inbux** [comment]
5.0.32 Protokoll zeigt nach öffnen keine Nachrichten #925

**Comment by Apollon77** [comment]
fixed in 5.1 from my knowledge
