### ISSUE TITLE
Kann keine Einstellungen in Instanzen anklicken

### ISSUE THREAD

**Issue by Schimi1983** [ioBroker/ioBroker.admin#928]
Hi,

bin nicht sicher ob es daran liegt (Admin Adapter 5.0.32)... kann aber unter Instanzen keine Einstellungen mehr betreten (leicht ausgegraut).

Da ich sonst nichts verändert habe, kann es nur nach einem Admin Update "passiert" sein... benutze ReactUI... kann aber im Admin Adapter nicht auf "die alte Ansicht" ändern....

**Comment by GermanBluefox** [comment]
Duplicate https://github.com/ioBroker/ioBroker.admin/issues/922
