### ISSUE TITLE
Daueranimation in "Meine Adapter" React 5.1.0

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.admin#929]
War aber auch schon vor 5.1.0 so

![daueranimat](https://user-images.githubusercontent.com/4311558/119327202-037a0c80-bc83-11eb-8bf0-972a09653f3e.png)

**Comment by GermanBluefox** [comment]
Ich kenne so ein Fenster im Admin5. Kann es sein, dass es info ist?

**Comment by daniel-lo** [comment]
Ja .. es ist der "Meine Adpater" Bereich auf der Info-Seite

**Comment by GermanBluefox** [comment]
Dann muss Issue für info Adapter erzeugt werden.
