### ISSUE TITLE
ChunkLoadError after updating Admin on slave and switching to Objects

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#930]
Master: Admin 5.1.0
Slave: Admin 5.1.0

The following ChunkLoadError is shown after updating Admin on slave and switching to Objects menu

Steps to reproduce
- Update Amin 5.1.0 on master -> Update was successfull, correct version number is show after using refreshing button on Adapter overview
- Update Admin 5.1.0 on slave -> Update was successfull, correct version number was shown
- Switch to menu "Objects"

![grafik](https://user-images.githubusercontent.com/25422320/119327913-ca8e6780-bc83-11eb-94f9-2323f44d6c03.png)

**Comment by GermanBluefox** [comment]
Das kann passieren. Sollte mit F5 weg sein und danach nie wieder sichtbar, bis weiterer Update

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
Nach einem F5 war alles ok.
Soll das Ticket offen bleiben oder ist es dem Update geschuldet, dass die Meldung kommt und kann nicht geändert werden?

**Comment by GermanBluefox** [comment]
Das kann ich nicht beheben. Es ist so, dass Browser hat alte Version geladen, aber nach dem Admin update existieren alte Dateien nicht mehr und diese Fehlermeldung sagt genau das
