### ISSUE TITLE
Cannot load jsonConfig of History bei states bei REACT

### ISSUE THREAD

**Issue by Hirsch-DE** [ioBroker/ioBroker.admin#931]
ich kann bei der neuen Oberfläche keine History-Einstellungen bei den States vornehmen, da die jsonConfig nicht geladen werden kann. Bei der alten Variante funktioniert es.

**Comment by GermanBluefox** [comment]
Welche History Version ist installiert?

**Comment by Hirsch-DE** [comment]
Version 1.9.13 ist installiert.

**Comment by Hirsch-DE** [comment]
Nur zur Info, der ioBroker läuft auf Windows.

**Comment by Hirsch-DE** [comment]
Bei React UI wird die Version 1.9.12 von history angezeigt, bei der alten UI wird Version 1.9.13 angezeigt!!!

**Comment by GermanBluefox** [comment]
Ich kann mit 1.9.13 das Problem nicht reproduzieren.
![image](https://user-images.githubusercontent.com/4582016/119383198-52479680-bcc3-11eb-9440-fc530f3c523d.png)


Vielleicht `iob u history` kann helfen?

**Comment by GermanBluefox** [comment]
Can anyone else check this?

**Comment by Feuer-sturm** [comment]
Admin 5.1.2
history 1.9.13

Ich habe history 1.9.13 installiert und kann einen Datenpunkt konfigurieren, dass er geloggt wird. Habe ein Logging alle 60s eingestellt.
Sieht i.O. aus bei mir.

![grafik](https://user-images.githubusercontent.com/25422320/119721820-e05e8100-be6b-11eb-8054-7ce6e60326e0.png)
![grafik](https://user-images.githubusercontent.com/25422320/119721849-e94f5280-be6b-11eb-9270-90c49fd302dd.png)

**Comment by GermanBluefox** [comment]
> 1.9.13

`iob u history`  should help
