### ISSUE TITLE
admin 5.1.0 error : cannot read property

### ISSUE THREAD

**Issue by arteck** [ioBroker/ioBroker.admin#932]
![grafik](https://user-images.githubusercontent.com/6681528/119351776-287d7800-bca1-11eb-8e6d-c1e10c3c390b.png)

![grafik](https://user-images.githubusercontent.com/6681528/119351791-2ddac280-bca1-11eb-86ae-f776e627c4ed.png)

das protokoll enthält keine nchrichten
![grafik](https://user-images.githubusercontent.com/6681528/119351868-45b24680-bca1-11eb-9315-b64fa86a5e4d.png)

**Comment by arteck** [comment]
ich kann auf dem Multihost nicht umschalten

**Comment by GermanBluefox** [comment]
Fix in 5.1.0
