### ISSUE TITLE
Crash at Tab instances

### ISSUE THREAD

**Issue by Archie-ndw** [ioBroker/ioBroker.admin#934]
instrument.ts:129 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at Hl (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at n.m.setState (react.production.min.js:12)
    at Instances.js:451
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonymous) @ instrument.ts:129
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
No @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
Hl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ Instances.js:451
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Instances.js:195
(anonymous) @ Instances.js:284
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 10.cc09ed55.chunk.js:1
pi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Sl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12

**Comment by GermanBluefox** [comment]
I cannot reproduce it. But it is because somewhere the translation is used, where it by default not set.
@Archie-ndw Any ideas what it could be?

**Comment by Archie-ndw** [comment]
Nein, leider nicht.
Das Problem ist: ich kann auch nicht wirklich die Instanzen einzeln abschalten weil der Tab sofort abstürzt.
Is es möglich in die Einstellungen des Admin-Adapters zu kommen ohne dem Tab Instanzen? Damit ich das react Guie wieder ausschalten kann? Oder ist unter 51.0 nur mehr React aktiv? IN der Vorgängerversion ohne React war alles ok.
Ich bin nicht sehr versiert - kann aber Anweisungen gut befolgen: Kann ich etwas liefern/abfrage was zur Fehlerermittlung beiträgt?

**Comment by Apollon77** [comment]
AUch ein "Hart reload" (Shift reload) hilft nicht?

**Comment by Archie-ndw** [comment]
Nein.
Es kommt dann zwar das Framework und man sieht ganz kurz dass versucht wird den Tab zu laden aber dann kommt geleich die GUI Fehler Seite.

**Comment by GermanBluefox** [comment]
> Nein, leider nicht.
> Das Problem ist: ich kann auch nicht wirklich die Instanzen einzeln abschalten weil der Tab sofort abstürzt.
> Is es möglich in die Einstellungen des Admin-Adapters zu kommen ohne dem Tab Instanzen? Damit ich das react Guie wieder ausschalten kann? Oder ist unter 51.0 nur mehr React aktiv? IN der Vorgängerversion ohne React war alles ok.
> Ich bin nicht sehr versiert - kann aber Anweisungen gut befolgen: Kann ich etwas liefern/abfrage was zur Fehlerermittlung beiträgt?

`iob set admin.0 --material true` über die Console schaltet React aus

**Comment by Archie-ndw** [comment]
Danke für den Tipp mit dem setzen der Option über die Console.

Unten nochmal zwei Logs aus der Chrome-Console und eines aus der FireFox Console
1: Erster Aufruf mit bereits geöffneter Console
2: Nochmaliger aufruf mit Shift-F5
3: Consoole Log aus dem Firefox


1)
instrument.ts:129 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at Hl (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at n.m.setState (react.production.min.js:12)
    at Instances.js:451
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonymous) @ instrument.ts:129
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
No @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
Hl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ Instances.js:451
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Instances.js:195
(anonymous) @ Instances.js:284
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 10.cc09ed55.chunk.js:1
pi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Sl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12


2)
getInstances: 347
2instrument.ts:129 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at Hl (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at n.m.setState (react.production.min.js:12)
    at Instances.js:451
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonymous) @ instrument.ts:129
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
No @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
Hl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ Instances.js:451
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Instances.js:195
(anonymous) @ Instances.js:284
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 10.cc09ed55.chunk.js:1
pi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Sl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
Ae @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
xr @ react-dom.production.min.js:105
Qt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
r @ helpers.ts:87


3)
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.100.139:8081
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.
192.168.100.139:8081
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 192.168.100.139:8081
iobroker.admin@5.1.0 index.js:18:8
[2021-05-24T18:53:58.288Z] Try to connect instrument.ts:129:35
getInstances: 444 instrument.ts:129:35
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        Wa
        Ga
        Ua
        hl
        enqueueSetState
        setState
    e Instances.js:451
    u runtime.js:63
    _invoke runtime.js:293
    w runtime.js:118
    Babel 2
        r
        i
instrument.ts:129:35
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%2C%20de%2C%20ru%2C%20pt%2C%20nl%2C%20fr%2C%20it%2C%20es%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    React 9
        Mc
        Oc
        Ro
        Ui
        Cl
        Hl
        El
        ml
        Ga
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
        Wa
        Ga
        Ua
        hl
        enqueueSetState
        setState
    e Instances.js:451
    u runtime.js:63
    _invoke runtime.js:293
    w runtime.js:118
    Babel 2
        r
        i
instrument.ts:129:35

​

**Comment by Archie-ndw** [comment]
![Tab-Error](https://user-images.githubusercontent.com/54120934/119395262-8aef6c00-bcd3-11eb-81b6-5bc5483123a5.png)

Ev. hilft dieser Screenshot: wenn ich zb die Admin-Settings mit dem Links aus dem Alten Guie direkt aufrufe funkt es auch unter React.
Scheinbar funkt "nur" die Root-Seite #tab-instances selbst  nicht.
Auffallend aber hier: Die Config Seite ist Sprachlich gemixt: oben Deutsch und dann Englisch

Wenn ich irgendwas beitragen kann, Logs odgl, einfach melden.

**Comment by vore** [comment]
Hello! 
Same here (Console open -> Error -> F5)

> instrument.ts:129 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Ben%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mc (react-dom.production.min.js:140)
    at react-dom.production.min.js:150
    at Ro (react-dom.production.min.js:176)
    at Ui (react-dom.production.min.js:271)
    at Cl (react-dom.production.min.js:250)
    at Hl (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at n.m.setState (react.production.min.js:12)
    at Instances.js:451
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonymous) @ instrument.ts:129
ii @ react-dom.production.min.js:216
n.payload @ react-dom.production.min.js:217
uc @ react-dom.production.min.js:130
No @ react-dom.production.min.js:184
Ui @ react-dom.production.min.js:269
Cl @ react-dom.production.min.js:250
Hl @ react-dom.production.min.js:250
El @ react-dom.production.min.js:250
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
Ua @ react-dom.production.min.js:122
hl @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
m.setState @ react.production.min.js:12
(anonymous) @ Instances.js:451
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ Instances.js:195
(anonymous) @ Instances.js:284
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
i @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ 10.cc09ed55.chunk.js:1
pi @ react-dom.production.min.js:219
jl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Sl @ react-dom.production.min.js:252
ml @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wa @ react-dom.production.min.js:122
Ga @ react-dom.production.min.js:123
F @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12

**Comment by GermanBluefox** [comment]
Please stop post such an error messages. It does not help me....And I need anyway only one first line

**Comment by GermanBluefox** [comment]
I guess it is because of some adapter. Can  you all posts here the installed instances? So I can find the overlap and detect the problem

**Comment by Archie-ndw** [comment]
> I guess it is because of some adapter. Can you all posts here the installed instances? So I can find the overlap and detect the problem

root@raspberrypi:/home/pi# iobroker list instances
+ system.adapter.admin.0                  : admin                 : raspberrypi                                                                                                                                                                                           -  enabled, port: 8081, bind: 0.0.0.0, run as: admi                                                                                                                                                             n
+ system.adapter.admin.1                  : admin                 : raspberrypi                                                                                                                                                                                           -  enabled, port: 9081, bind: 0.0.0.0, run as: admi                                                                                                                                                             n
  system.adapter.apple-find-me.0          : apple-find-me         : raspberrypi                                                                                                                                                                                           - disabled
+ system.adapter.backitup.0               : backitup              : raspberrypi                                                                                                                                                                                           -  enabled
  system.adapter.chromecast.0             : chromecast            : raspberrypi                                                                                                                                                                                           - disabled
+ system.adapter.cloud.0                  : cloud                 : raspberrypi                                                                                                                                                                                           -  enabled
  system.adapter.devices.0                : devices               : raspberrypi                                                                                                                                                                                           - disabled
  system.adapter.discovery.0              : discovery             : raspberrypi                                                                                                                                                                                           - disabled
+ system.adapter.hm-rega.0                : hm-rega               : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.hm-rpc.0                 : hm-rpc                : raspberrypi                                                                                                                                                                                           -  enabled, port: 18701
+ system.adapter.hm-rpc.1                 : hm-rpc                : raspberrypi                                                                                                                                                                                           -  enabled, port: 12001
+ system.adapter.hm-rpc.2                 : hm-rpc                : raspberrypi                                                                                                                                                                                           -  enabled, port: 12010
  system.adapter.hue.0                    : hue                   : raspberrypi                                                                                                                                                                                           - disabled, port: 80
  system.adapter.hyperion_ng.0            : hyperion_ng           : raspberrypi                                                                                                                                                                                           - disabled
  system.adapter.icons-ultimate-png.0     : icons-ultimate-png    : raspberrypi                                                                                                                                                                                           - disabled
+ system.adapter.info.0                   : info                  : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.intesishome.0            : intesishome           : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.iot.0                    : iot                   : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.javascript.0             : javascript            : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.lifx.0                   : lifx                  : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.mqtt.0                   : mqtt                  : raspberrypi                                                                                                                                                                                           -  enabled, port: 1883, bind: 192.168.100.139
+ system.adapter.nuki-extended.0          : nuki-extended         : raspberrypi                                                                                                                                                                                           -  enabled
  system.adapter.statistics.0             : statistics            : raspberrypi                                                                                                                                                                                           - disabled
+ system.adapter.telegram.0               : telegram              : raspberrypi                                                                                                                                                                                           -  enabled, port: 8443, bind: 0.0.0.0
  system.adapter.vis-fancyswitch.0        : vis-fancyswitch       : raspberrypi                                                                                                                                                                                           - disabled
  system.adapter.vis.0                    : vis                   : raspberrypi                                                                                                                                                                                           -  enabled
+ system.adapter.web.0                    : web                   : raspberrypi                                                                                                                                                                                           -  enabled, port: 8082, bind: 0.0.0.0, run as: admi                                                                                                                                                             n
  system.adapter.whatsapp-cmb.0           : whatsapp-cmb          : raspberrypi                                                                                                                                                                                           - disabled

+ instance is alive

**Comment by PaulchenPlump** [comment]
I have the same problems as the previous posters. Here is my instance list for better comparison:
```
+ system.adapter.admin.0         : admin         : raspberrypi - enabled, port: 8083, bind: 0.0.0.0, run as: admin
  system.adapter.alias-manager.0 : alias-manager : raspberrypi - enabled
  system.adapter.daswetter.0     : daswetter     : raspberrypi - enabled
  system.adapter.flot.0          : flot          : raspberrypi - enabled
+ system.adapter.javascript.0    : javascript    : raspberrypi - enabled
+ system.adapter.lovelace.0      : lovelace      : raspberrypi - enabled, port: 8091, bind: 0.0.0.0, run as: admin
  system.adapter.luftdaten.0     : luftdaten     : raspberrypi - enabled
+ system.adapter.netio.0         : netio         : raspberrypi - enabled
+ system.adapter.sonoff.0        : sonoff        : raspberrypi - enabled, port: 1883, bind: 0.0.0.0
+ system.adapter.sql.0           : sql           : raspberrypi - enabled, port: 0
+ system.adapter.web.0           : web           : raspberrypi - enabled, port: 8082, bind: 0.0.0.0, run as: admin
+ system.adapter.zigbee.0        : zigbee        : raspberrypi - enabled, port: /dev/tty????

+ instance is alive
```

What I noticed is the call via the IP address...

**Comment by msapogov** [comment]
I update to 5.1.1 and web gui work OK!

**Comment by Archie-ndw** [comment]
> I update to 5.1.1 and web gui work OK!

Same here :-)

**Comment by PaulchenPlump** [comment]
After the update everything is fine. Thanks a lot!
I think the bug can be closed.
