### ISSUE TITLE
Error in GUI

### ISSUE THREAD

**Issue by rsteinkuhl** [ioBroker/ioBroker.admin#935]
iobroker.admin@5.1.0
instrument.ts:129 [2021-05-24T18:13:48.020Z] Try to connect
instrument.ts:129 Cannot getRepositoryCompact: getCompactRepository timeout
instrument.ts:129 Translate: Detected slow connection!
instrument.ts:129 Translate: Seems that you have slow connection. Do you want to increase timeout interval?
instrument.ts:129 Translate: Read timeout
instrument.ts:129 Translate: in seconds
instrument.ts:129 Translate: Set timeout to 1 minute

TypeError: Cannot read property 'admin' of null
    at Drawer.js:213
    at Array.forEach (<anonymous>)
    at Function.value (Drawer.js:211)
    at new a (Drawer.js:174)
    at mc (react-dom.production.min.js:135)
    at No (react-dom.production.min.js:181)
    at Ui (react-dom.production.min.js:269)
    at Cl (react-dom.production.min.js:250)
    at Hl (react-dom.production.min.js:250)
    at El (react-dom.production.min.js:250)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at o.m.setState (react.production.min.js:12)
    at App.js:559
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at i (asyncToGenerator.js:25)
(anonym) @ instrument.ts:129

**Comment by GermanBluefox** [comment]
> Detected slow connection!

And how Adapter must read the data? What I can do against YOUR slow connection?

**Comment by rsteinkuhl** [comment]
The real problem was that the admin page wouldn't open after the update and I couldn't make any more settings. The other question is how do I find out which connection is slow?

 

Freundliche Grüße

 

Rainer Steinkuhl

Am Knick 2 a

44534 Lünen

Email: ***@***.***

 

Von: Bluefox ***@***.***> 
Gesendet: Dienstag, 25. Mai 2021 15:58
An: ioBroker/ioBroker.admin ***@***.***>
Cc: rsteinkuhl ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI (#935)

 

Detected slow connection!

And how Adapter must read the data? What I can do against YOUR slow connection?

**Comment by rsteinkuhl** [comment]
Error in GUI!

Please open the browser console (F12), copy error text from there and create the issue on github <https://github.com/ioBroker/ioBroker.admin/issues> 
Without this information it is not possible to analyse the error.
It should looks like 

If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.

t is null

***@***.***://10.50.6.108:8081/static/js/main.95e75f7d.chunk.js:2:882386function(e,t){return ***@***.***://10.50.6.108:8081/static/js/main.95e75f7d.chunk.js:2:882352function(e,t){return ***@***.***://10.50.6.108:8081/static/js/main.95e75f7d.chunk.js:2:874139function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5415152function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5434642function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5478333function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5464436function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5464364function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5464225function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5461191function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5410570function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5493961function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5410347function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5410517function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5410450function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5458560function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5414468function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5485472function(e,t){return ***@***.***://10.50.6.108:8081/static/js/main.95e75f7d.chunk.js:2:1067983function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5496449function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5496238function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:5496874function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:40824function(e,t){return ***@***.***://10.50.6.108:8081/static/js/5.acef7c19.chunk.js:2:41028function(e,t){return Object(Pe.jsxs)("div",{children:[e,Object(Pe.jsx)("br",{})]},t)}

 

Diese Fehlermeldung kommt seit dem Update auf Admin 5.1

 

Freundliche Grüße

 

Rainer Steinkuhl

Am Knick 2 a

44534 Lünen

Email: ***@***.***

 

Von: Bluefox ***@***.***> 
Gesendet: Dienstag, 25. Mai 2021 15:58
An: ioBroker/ioBroker.admin ***@***.***>
Cc: rsteinkuhl ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Error in GUI (#935)

 

Detected slow connection!

And how Adapter must read the data? What I can do against YOUR slow connection?

**Comment by GermanBluefox** [comment]
> If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.

???

**Comment by GermanBluefox** [comment]
Fixed in 5.1.3

**Comment by DonDimon85** [comment]
> Behoben in 5.1.3

Hallo 
wie haben sie das behoben?
