### ISSUE TITLE
Admin5: Release plan

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.admin#936]
Preparations:
[x] Release js-controller 3.3.11
[x] Release Admin 5.1 which enabled React-UI by default to get more user feedback
[ ] Fix all new issues and collect info for stable announcements - update Feature list eof Admin5 @GermanBluefox 
[ ] Adjust all custom-adapters to json-schema see below

When all is looking good for a week or such
[ ] Bring js-controller 3.3.12 into stable
[ ] Bring all relevant adapters into stable (see below)
[ ] Prepare Forum Thread and Info Adapter Message
[ ] Bring Admin 5.1 into stable with proper communication including info adapter

**Comment by Apollon77** [comment]
Collected adapter to update before Admin5:
* vis
* other react based adapter?
* all custom adapter
*

**Comment by Apollon77** [comment]
Adapter needs update:
* ioBroker.history/admin/custom_m.html (1.9.13 Stable missing)
* ioBroker.influxdb/admin/custom_m.html (1.9.5 Stable Done)
* ioBroker.lovelace/admin/custom_m.html (1.5.0+ In Progress)
* ioBroker.mqtt-client/admin/custom_m.html (1.3.2 Stable Todo)
* ioBroker.sql/admin/custom_m.html (1.15.7 Stable Done)
* ioBroker.telegram/admin/custom_m.html (>1.8.1 ... 1.8.2 Release open)
* https://github.com/Apollon77/ioBroker.homee/issues/137 (> 1.1.1 Merge and release outstanding)
* https://github.com/nisiode/ioBroker.iogo/issues/36 (0.7.0+ Release outstanding)
* https://github.com/sbormann/ioBroker.iqontrol/issues/181 (1.7.3+ Stable TODO)
* https://github.com/Scrounger/ioBroker.linkeddevices/issues/65 (TODO)
* https://github.com/rg-engineering/ioBroker.minmax/issues/22 (1.2.0+ Stable Todo?)
* https://github.com/DrozmotiX/ioBroker.sourceanalytix/issues/411 (0.4.9+ Stable Todo)
* https://github.com/iobroker-community-adapters/ioBroker.statistics/issues/61 (Release pending!) @GermanBluefox 
* https://github.com/iobroker-community-adapters/ioBroker.upnp/issues/70 (1.0.19+)

* https://github.com/Omega236/ioBroker.valuetrackerovertime/issues/17 (Open)
* https://github.com/Omega236/ioBroker.virtualpowermeter/issues/60 (PR Open)

After Stable-Release:
*  Add json-config to adapter creator: https://github.com/ioBroker/create-adapter/issues/723

**Comment by GermanBluefox** [comment]
Version iobroker.statistics@1.0.6 is in latest: https://www.npmjs.com/package/iobroker.statistics

**Comment by nisiode** [comment]
Version iobroker.iogo@0.7.0 is also in latest: https://www.npmjs.com/package/iobroker.iogo
