### ISSUE TITLE
Vis adapter setting button missing in react view 

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/ioBroker.admin#939]
Vis adapter setting button missing in react view.
admin version: 5.1.0
js-controler : 3.3.11
![Screenshot_271](https://user-images.githubusercontent.com/32600934/119416345-b5512180-bcf3-11eb-8a65-259e392f1346.png)

**Comment by GermanBluefox** [comment]
Fixed in vis 1.3.10

**Comment by xXBJXx** [comment]
I can confirm in v.1.3.10 the button is available again
