### ISSUE TITLE
Scripte startet auf Firefox nicht

### ISSUE THREAD

**Issue by tobst96** [ioBroker/ioBroker.admin#941]
ioBroker Admin: 5.1.0 auf dem Firefox Browser öffnet nicht. Die interne Seite lädt nicht. Allerdings in Chrome schon. Somit gehe ich vom GUI-Fehler aus.

Fehler:

Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt. tab.html
Detected custom blockly: iot instrument.ts:129:35
Detected custom blockly: telegram instrument.ts:129:35
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.2.25:8081/adapter/javascript/vs/editor/editor.main.js
Source-Map-Adresse: ../../../min-maps/vs/editor/editor.main.js.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.2.25:8081/adapter/javascript/vs/loader.js
Source-Map-Adresse: ../../min-maps/vs/loader.js.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.2.25:8081/adapter/javascript/vs/editor/editor.main.nls.de.js
Source-Map-Adresse: ../../../min-maps/vs/editor/editor.main.nls.de.js.map

**Comment by Apollon77** [comment]
please try "iobroker upload javascript". Fixed by this?

**Comment by GermanBluefox** [comment]
Cannot reproduce under FF:
![image](https://user-images.githubusercontent.com/4582016/119510925-3818c180-bd72-11eb-8ccd-7fce1bb22da8.png)
