### ISSUE TITLE
Admin 5 - React UI - Edit of "read only" Datapoints possible

### ISSUE THREAD

**Issue by nobl** [ioBroker/ioBroker.admin#942]
**Describe the bug**  
With Admin 5 and React UI it is possible to edit datapoints that are "read only".
Former UI didn't allow changing read-only values by just clicking on them.

**To Reproduce**  
1. Go to 'Objects'
2. Find any "read only" DP
3. Click on the value
4. Change Value and click save.

**Expected behavior**  
It shouldn't be possible to edit values that have a 'write' flag set as 'false' (just like in the former UI).

**Versions:**  
 - Adapter version: 5.1.0

**Comment by Apollon77** [comment]
Are you using expert mode? BEcause there you can do it - also in Admin4 and older versions. or is it without expert mode?

**Comment by nobl** [comment]
Ok - that explains it.
Without "Expert mode" editing isn't possible.

But: Old UI I also had in expert mode and edit didn't work by just clicking on the value (at least it didn't work before the forced React UI).

We can consider it solved then, if expert mode allows editing.
