### ISSUE TITLE
Admin 5 - React UI  - Scrolling not working in Safari (custom tab) works fine in chrome

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/ioBroker.admin#944]
no scroll balk visible in safari:

<img width="1678" alt="Schermafbeelding 2021-05-25 om 13 54 59" src="https://user-images.githubusercontent.com/7318445/119493736-cdab5580-bd60-11eb-8278-bcb6ab19fc97.png">

in chrome it works just fine : 

<img width="1654" alt="Schermafbeelding 2021-05-25 om 13 55 43" src="https://user-images.githubusercontent.com/7318445/119493837-e9166080-bd60-11eb-9aaa-9f6ba43457d6.png">

**Comment by GermanBluefox** [comment]
Don't use safari and best of all the whole apple stuff. Safari is a new Internet Explorer.

**Comment by DutchmanNL** [comment]
> Don't use safari and best of all the whole apple stuff. Safari is a new Internet Explorer.

eh yeah funny remark, should I use that as officiel message to the community ? ;)
As for all Mac and iOS users safari is the first browser they will use to get in touch with ioBroker I think this should not be an official statement :)

**Comment by GermanBluefox** [comment]
Is that a threat? Yes you can say, that Bluefox hates apple hardware and software.

**Comment by DutchmanNL** [comment]
> Is that a threat? Yes you can say, that Bluefox hates apple hardware and software.

A threat ? No dude lets keep it on the right level I am really looking for a solution and would like to avoid negative end-user feedback for ioBroker that's all sorry man :/ ....

**Comment by MMeinhardt1** [comment]
Hi guys,
on my iPad i habe the Same problem. Have you @GermanBluefox any ideas to solve the problems with (you said, „fucking“ apple) ios devices?

**Comment by GermanBluefox** [comment]
> fucking

You are sitting in front of such device or even hold in the hands and just report an error without any suggestion.
I must somehow find the device and fix an error.
And Apple does not provided the possibility to install safary somewhere except on Apple devices. 
And after that I must like apple?

**Comment by GermanBluefox** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/4582016/121222185-9a9bb280-c886-11eb-9ff7-975ff91c0bf1.png)

![image](https://user-images.githubusercontent.com/4582016/121222213-9f606680-c886-11eb-9279-7e639cecd9a1.png)

**Comment by MMeinhardt1** [comment]
Hi, you dont like apple. 
Sametimes i also dont like apple. I had seen some users have different problems with different apple devices. I.e. on my old iPad (iPad Air SW 12.5.3) i have the problems from this issue and with the problem i cant seen the object datas that i have discribed in an other issue. On my newer iPad (iPad Air 3rd Gen. SW 14.6) all the discribed problems from other users i dont have these. 
Apple devices are very strange.

**Comment by DutchmanNL** [comment]
> Cannot reproduce

its fixed, not sure in which update
