### ISSUE TITLE
Strange behaviour of Script Window

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.admin#947]
Node.js
v12.19.0
Admin 5.1.1.
Javascript 5.1.3.

Just look at the video. There you can see the Error!

https://user-images.githubusercontent.com/40354380/119615916-48777d80-be00-11eb-89c2-350ec3872839.MP4

**Comment by DutchmanNL** [comment]
Please add : 

**Describe the bug**  
A clear and concise description of what the bug is.

**Expected behavior**  
A clear and concise description of what you expected to happen.

**Comment by GermanBluefox** [comment]
What the browser is that? Anyway under Chrome and FF I cannot reproduce it
