### ISSUE TITLE
Admin Adapter 5.1.1 und Sourceanalytix Adapter

### ISSUE THREAD

**Issue by Semmy100** [ioBroker/ioBroker.admin#949]
Der Adapter Sourceanalytix lässt sich mit der Admin Version 5.1.1 nicht mehr konfigurieren, kommt immer Fehlermeldung: cannot load jsonconfig of sourceanalytix: not exists
Mit Version 5.3.1 hat es noch funktioniert.

**Comment by DutchmanNL** [comment]
work in progress : https://github.com/DrozmotiX/ioBroker.sourceanalytix/issues/411, abwarte auf admin 5.1.2 dan kan ich das issue beheben

**Comment by DutchmanNL** [comment]
@Semmy100 Please test with SourceAnalytix 0.4.9-0 (must be installed from git, not yet in admin available for install)
Requires at least admin 5.1.2 !

**Comment by Semmy100** [comment]
Ok, funktioniert jetzt wieder. Was bedeutet including basic rate?

**Comment by DutchmanNL** [comment]
> Ok, funktioniert jetzt wieder. Was bedeutet including basic rate?

Grund preis mitnehmen in den Berechnungen dazu ist noch ein issue offen beim SA adapter
