### ISSUE TITLE
Hinzufügen von Mitgliedern unter Aufzählungen nicht mehr möglich

### ISSUE THREAD

**Issue by dontobi** [ioBroker/ioBroker.admin#95]
Nach dem heutigen Update von 2.0.4 auf 2.0.6 klappt das hinzufügen von Mitgliedern unter dem Punkt Aufzählungen nicht mehr. Dies wurde mit mehreren Geräten und diversen Browsern ausprobiert.

**Comment by GermanBluefox** [comment]
Wird heute Abend gefixt.

**Comment by DutchmanNL** [comment]
wird der fix auch andere button probleme loesen sowie beim scenen adapter und cloud ? beispiel:

http://forum.iobroker.net/viewtopic.php?f=17&t=8442&p=89535#p89535

**Comment by DutchmanNL** [comment]
update, mit 2.0.7 ist diesen problem gefixed

**Comment by GermanBluefox** [comment]
Ja. Es werden alle solche Probleme gefixt.
