### ISSUE TITLE
Error in GUI #tab-instances: Minified React error #31

### ISSUE THREAD

**Issue by ronvlm** [ioBroker/ioBroker.admin#951]
[Error] Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Mc — react-dom.production.min.js:140
(anonyme Funktion) — react-dom.production.min.js:150:268
Ro — react-dom.production.min.js:176:174
Ui — react-dom.production.min.js:271:137
Cl — react-dom.production.min.js:250:350
Hl — react-dom.production.min.js:250:281
El — react-dom.production.min.js:250:138
ml — react-dom.production.min.js:243:166
ml
(anonyme Funktion) — react-dom.production.min.js:123:115
(anonyme Funktion) — scheduler.production.min.js:18:343
Ga — react-dom.production.min.js:123
Ua — react-dom.production.min.js:122:428
hl — react-dom.production.min.js:237:203
enqueueSetState — react-dom.production.min.js:133:214
(anonyme Funktion) — react.production.min.js:12:385
(anonyme Funktion) — Instances.js:451
u — runtime.js:63
(anonyme Funktion) — runtime.js:293
r — asyncToGenerator.js:3
i — asyncToGenerator.js:25
promiseReactionJob

	(anonyme Funktion) (5.acef7c19.chunk.js:2:6044918)
	ii (5.acef7c19.chunk.js:2:5448166)
	(anonyme Funktion) (5.acef7c19.chunk.js:2:5450426)
	uc (5.acef7c19.chunk.js:2:5413399)
	No (5.acef7c19.chunk.js:2:5436222)
	Cl (5.acef7c19.chunk.js:2:5464437)
	Hl (5.acef7c19.chunk.js:2:5464365)
	El (5.acef7c19.chunk.js:2:5464228)
	ml (5.acef7c19.chunk.js:2:5461194)
	ml
	(anonyme Funktion) (5.acef7c19.chunk.js:2:5410572)
	(anonyme Funktion) (5.acef7c19.chunk.js:2:5493963)
	Ga (5.acef7c19.chunk.js:2:5410518)
	Ua (5.acef7c19.chunk.js:2:5410453)
	hl (5.acef7c19.chunk.js:2:5458563)
	enqueueSetState (5.acef7c19.chunk.js:2:5414471)
	(anonyme Funktion) (5.acef7c19.chunk.js:2:5485488)
	(anonyme Funktion) (10.cc09ed55.chunk.js:1:64897)
	u (5.acef7c19.chunk.js:2:5496454)
	(anonyme Funktion) (5.acef7c19.chunk.js:2:5496239)
	r (5.acef7c19.chunk.js:2:40825)
	i (5.acef7c19.chunk.js:2:41029)
	promiseReactionJob

**Comment by GermanBluefox** [comment]
Welcher Tab? Dialog? Was wurde gemacht?

**Comment by ronvlm** [comment]
Betrifft bei mir immer nur #tab-instances, egal was man vorher gemacht hat.
Die anderen Tabs/Menüs gehen alle nur bei Instanzen kommt sofort der Fehler.
Alle installierten Versionen und  Module sind aktuell (läuft auf aktuellem Ubuntu):

Adapter    "admin"         : 4.2.1    , installed 5.1.0
Adapter    "backitup"      : 2.1.11   , installed 2.1.11
Adapter    "ble"           : 0.12.0   , installed 0.12.0
Adapter    "coronavirus-statistics": 0.6.3   , installed 0.7.0-4
Adapter    "devices"       : 0.3.16   , installed 0.3.16
Adapter    "discovery"     : 2.6.1    , installed 2.6.3
Adapter    "feiertage"     : 1.0.17   , installed 1.0.20
Adapter    "geofency"      : 1.0.3    , installed 1.0.3
Adapter    "ham"           : 4.0.2    , installed 4.0.2
Adapter    "hm-rpc"        : 1.14.37  , installed 1.14.38
Adapter    "homeconnect"   : 0.0.32   , installed 0.0.32
Adapter    "hue"           : 3.5.15   , installed 3.5.15
Adapter    "hue-extended"  : 2.0.0    , installed 2.0.0
Adapter    "influxdb"      : 1.9.5    , installed 1.9.5
Adapter    "info"          : 1.7.14   , installed 1.7.15
Adapter    "javascript"    : 5.1.3    , installed 5.1.3
Controller "js-controller" : 3.2.16   , installed 3.3.11
Adapter    "knx"           : 1.0.45   , installed 1.0.45
Adapter    "loxone"        : 2.1.0    , installed 2.2.1
Adapter    "luftdaten"     : 1.0.2    , installed 1.0.3
Adapter    "mqtt"          : 2.4.0    , installed 2.4.0
Adapter    "mqtt-client"   : 1.3.1    , installed 1.3.2
Adapter    "nanoleaf-lightpanels": 1.2.0   , installed 1.2.0
Adapter    "netatmo"       : 1.3.3    , installed 1.3.3
Adapter    "netatmo-crawler": 0.4.1   , installed 0.4.1
Adapter    "nina"          : 0.0.24   , installed 0.0.24
Adapter    "node-red"      : 2.3.0    , installed 2.3.0
Adapter    "nut"           : 1.5.0    , installed 1.5.0
Adapter    "odl"           : 1.1.4    , installed 1.1.4
Adapter    "openweathermap": 0.1.0    , installed 0.1.0
Adapter    "parser"        : 1.0.7    , installed 1.0.7
Adapter    "pollenflug"    : 1.0.6    , installed 1.0.6
Adapter    "proxmox"       : 1.3.3    , installed 1.3.4
Adapter    "sayit"         : 1.12.2   , installed 1.12.2
Adapter    "simple-api"    : 2.5.3    , installed 2.6.1
Adapter    "socketio"      : 3.1.4    , installed 3.1.4
Adapter    "sonos"         : 2.1.1    , installed 2.1.1
Adapter    "synology"      : 1.0.0    , installed 1.0.0
Adapter    "telegram"      : 1.8.1    , installed 1.8.1
Adapter    "tr-064"        : 4.2.12   , installed 4.2.12
Adapter    "unifi"         : 0.5.8    , installed 0.5.9
Adapter    "velux"         : 0.0.7    , installed 0.0.7
Adapter    "vis"           : 1.3.8    , installed 1.3.9
Adapter    "web"           : 3.4.0    , installed 3.4.1
Adapter    "yahka"         : 0.12.0   , installed 0.13.1
Adapter    "youtube"       : 1.0.3    , installed 1.1.0

**Comment by ronvlm** [comment]
Nachtrag:
mein System läuft mit 2 ioBroker-Instanzen.
Bist zum 5er Admin-Update funktionierte der Tab "Instanzen" reibungslos, danach wurden keine Adapterinstallationen mehr hinzugefügt.
Daten der 2 Host anbei


Host 1
-------
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 4570 MHz
Modell: Intel(R) Core(TM) i7-10710U CPU
RAM: 6 GB
System-Betriebszeit: 9 T. 22:21:46
Node.js: v12.22.1
NPM: 6.14.12
Festplatte frei: 16.3 GB
Adapter-Anzahl: 346
Betriebszeit: 7 T. 20:48:26
Aktive Instanzen: 17
Pfad: /opt/iobroker/


Host 2
------
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 3899 MHz
Modell: Intel(R) Core(TM) i7-7567U CPU
RAM: 6 GB
System-Betriebszeit: 9 T. 22:22:04
Node.js: v12.22.1
NPM: 6.14.12
Festplatte frei: 6.4 GB
Adapter-Anzahl: 346
Betriebszeit: 7 T. 20:49:31
Aktive Instanzen: 13
Pfad: /opt/iobroker/
