### ISSUE TITLE
Room name GUI Error

### ISSUE THREAD

**Issue by ChristianGrieger** [ioBroker/ioBroker.admin#952]
**Describe the bug**  

Newest beta version: 

When you try to create a new custom room and or edit a predefined room name it ends in GUI Error. I checked the folder and the file is there, so don't know what the problem is.

<img width="1041" alt="Bildschirmfoto 2021-05-26 um 18 04 15" src="https://user-images.githubusercontent.com/8712219/119693670-cb262a00-be4c-11eb-8285-ab4136537824.png">

**Comment by Feuer-sturm** [comment]
With Admin 5.1.2 I have this error as well

**Comment by GermanBluefox** [comment]
Step to reproduce?
- Create new room
-  Custom room.
- ?

**Comment by Feuer-sturm** [comment]
Steps to reproduce:
- Select Enum
- Edit a room by clicking on the pen
- try to change the "name" of the room -> here it will crash

![Animation11](https://user-images.githubusercontent.com/25422320/119724207-b8245180-be6e-11eb-8476-454c429c20e9.gif)

**Comment by GermanBluefox** [comment]
Please retest with 5.1.3

**Comment by Feuer-sturm** [comment]
Admin 5.1.3
If I now edit an existing room e.g. roomGarage (1) to roomGarage12 and save it
![grafik](https://user-images.githubusercontent.com/25422320/119897944-6b5d7b00-bf41-11eb-8f38-e3b70f1fb8f2.png)

a new room will be created -> not ok
![grafik](https://user-images.githubusercontent.com/25422320/119897973-77e1d380-bf41-11eb-8504-53b70c498c2d.png)

Expectation: The existing room will be updated

**Comment by GermanBluefox** [comment]
Fixed in 5.1.5

**Comment by Feuer-sturm** [comment]
Admin 5.1.5

Editing a room and creating a room is fixed with 5.1.5 on my system.

@ChristianGrieger Is it fixed with 5.1.5 on your system as well?
