### ISSUE TITLE
Instance - Sentry icon status does not change

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#953]
Admin 5.1.2

A lot of instances have the sentry icon. There is no feedback for the user if sentry is enabled or disabled.
By clicking on the sentry icon the instance will restart but no change is visable.

![Animation12](https://user-images.githubusercontent.com/25422320/119727372-7dbcb380-be72-11eb-8ce7-9b45bafb60c5.gif)

**Comment by Feuer-sturm** [comment]
Admin 5.1.3

In Admin 5.1.3 it is the same behavior than in 5.1.2

**Comment by GermanBluefox** [comment]
Cannot reproduce:
![sentry](https://user-images.githubusercontent.com/4582016/120011521-ab267000-bfde-11eb-842a-ea302cc50f5e.gif)

**Comment by Feuer-sturm** [comment]
Admin 5.1.4

With Admin 5.1.4 it is now ok on my system as well :-)
