### ISSUE TITLE
Icon for updating all adapters missing in adapter overview

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.admin#959]
Admin 5.1.3

The icon for updating all adapters is not visible in adpater overview
![grafik](https://user-images.githubusercontent.com/25422320/119872714-1101f180-bf24-11eb-8549-fa370d3fc1b3.png)

If the option "Filter adapter with updates" is activated the icon is visible 
![grafik](https://user-images.githubusercontent.com/25422320/119872773-1f500d80-bf24-11eb-9f0e-82212cef1942.png)

I would expect that the icon for update all adapters is visible in Adapter overview as well.

**Comment by GermanBluefox** [comment]
No. It works as designed
