### ISSUE TITLE
Issue with "<" and ">" in objects view

### ISSUE THREAD

**Issue by jack-blackson** [ioBroker/ioBroker.admin#960]
It seems that, in the object view, with admin 5.1 the symbols "<" and "> are not shown correctly. I saw this in the brings adapter, but also in my meteoalarm adapter:

<img width="1501" alt="grafik" src="https://user-images.githubusercontent.com/13975634/119874054-828e6f80-bf25-11eb-99ed-c17bffb1c349.png">

<img width="1503" alt="grafik" src="https://user-images.githubusercontent.com/13975634/119874130-9639d600-bf25-11eb-9220-6c753668766c.png">

This looks correct in Admin < 5.0

Browser: Firefox & Safari

**Versions:**  
 - Adapter version: 5.1.3
 - JS-Controller version: 3.3.9

**Comment by GermanBluefox** [comment]
Fixed in 5.1.5

**Comment by Feuer-sturm** [comment]
Admin 5.1.5

Is fixed with Admin 5.1.5

Old Admin 5.1.3
![grafik](https://user-images.githubusercontent.com/25422320/120099299-00779400-c13b-11eb-9d5b-c3eea6ba56b5.png)


New Admin 5.1.5
![grafik](https://user-images.githubusercontent.com/25422320/120099360-4e8c9780-c13b-11eb-865d-c0921d46d3ee.png)
