### ISSUE TITLE
How do I change the column width in the objects view?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [ioBroker/ioBroker.admin#962]
This was an old issue in '19 already and the last entry says: Implemented in admin5.
But I cannot see how to change column widths and could not find anything in the documentation about this.
My "name" column is to small to work with, after the last update of the admin adapter.

**Comment by GermanBluefox** [comment]
![name](https://user-images.githubusercontent.com/4582016/120012364-b1691c00-bfdf-11eb-8522-f22984d80e44.gif)

**Comment by MichaelSchaaf999** [comment]
Dankeschön!
Also, verstanden...  um die automatische Anordnung zu bewegen, bspw die Column Name breiter zu machen, muss man auf andere Columns verzichten, indem man sie abwählt. 
Okay, damit kann man leben, obwohl eine individuelle Spaltenbreiten-Einstellung netter wäre, beispielsweise dann mit horizontalem Scrollen. 
Aber: Es gibt bestimmt Wichtigeres.
Schöne WoEnde!

**Comment by Apollon77** [comment]
Die letzte Spalte im Screenshot wo Breite steht da kannst du eineZahl eingeben die die Spatenbreite in Pixeln ist. Da kannst du noch mehr tweaken. Aber horizontales Scrolling haben wir absichtlich nicht gemacht weil das nicht sinnvoll bedienbar ist auf allen Geräten

**Comment by MichaelSchaaf999** [comment]
Danke sehr, Ingo,
horizontales Scrolling braucht's auch nicht unbedingt, ja, kann ich bestätigen.
Aber das mit der Spaltenbreite hatte ich schon probiert, muss man sehr sinnig einsetzen, also eigentlich müsste man auf die ganze Fensterbreite hochrechnen mit automatischen Columns und mit Pixelbreite-gesteuerten Columns. Sonst wird's etwas durcheinander.
Aber: Alles gut, das sollte so m.E. für alle Ansprüche und jeden ausreichen.
Nochmals danke!
