### ISSUE TITLE
Benutzerdefinierte Einstellungen bei Objekten; Cannot load jsonConfig of sourceanalytix: Not exists

### ISSUE THREAD

**Issue by tugsi** [ioBroker/ioBroker.admin#965]
Benutze Admin 5.1.4
Wenn ich unter Objekten bei einem Datenpunkt hinten auf das Zahnradsymbol klicke (benutzerdefinierte Einstellungen; in alter GUI der Maulschlüssel), dann öffnen sich die Einstellungen von History und Co. 
Allerdings nicht mehr von Sourceanalytixs und es erscheint ein kleiner Hinweistext:
`Cannot load jsonConfig of sourceanalytix: Not exists`

Stelle ich um auf die alte Benutzeroberfläche, funktioniert alles wie gehabt und ich kann auch den Datenpunkt zu Sourceanalytix zuordnen.

**Comment by GermanBluefox** [comment]
Please update sourceanalytix

**Comment by tugsi** [comment]
Ok, but I have installed the 0.4.8
Seen on GitHub, the 0.4.9 is ready, but still not on npm yet, so I have to wait or?

**Comment by MMeinhardt1** [comment]
... you can download it over the GitHub link

**Comment by DutchmanNL** [comment]
> Ok, but I have installed the 0.4.8
> Seen on GitHub, the 0.4.9 is ready, but still not on npm yet, so I have to wait or?

Will release today on npm

**Comment by DutchmanNL** [comment]
0.4.9 released @GermanBluefox please close
