### ISSUE TITLE
manuelle Repo Aktualisierung über Button

### ISSUE THREAD

**Issue by Chaot1** [ioBroker/ioBroker.admin#968]
Ist es möglich/denkbar einen Button in der Admin Oberfläche einzubauen mit der man manuell das Repo abfragen kann. 

Derzeit aktualisiere ich indem ich auf den Info-Reiter umschalte. Funktioniert zwar, aber ist nach meiner Meinung ja so nicht optimal.

**Comment by Feuer-sturm** [comment]
@Chaot1 Dieser Button triggert doch ein Repo Update
![grafik](https://user-images.githubusercontent.com/25422320/120099070-c5c12c00-c139-11eb-81dd-a1a97f17c0f1.png)

```
30 May 2021 11:25:56.723
 host.ioBrokerTestsystem Updating repository "beta" under "http://download.iobroker.net/sources-dist-latest.json"
```

**Comment by Chaot1** [comment]
Dann ist die Beschriftung falsch oder zumindest extrem mißverständlich. Es kommt als Popup "Ansicht aktualisieren"

**Comment by GermanBluefox** [comment]
> Dann ist die Beschriftung falsch oder zumindest extrem mißverständlich. Es kommt als Popup "Ansicht aktualisieren"

Schlage deine Beschriftung vor.

**Comment by Chaot1** [comment]
Repo aktualisieren
Versionen aktualisieren
Repo erneut abfragen

Oder sowas. Mit "Ansicht aktualisieren" bringe ich landläufig nur eine Aktualisierung der Darstellung in Verbindung. Ähnlich dem F5 im Browser.

**Comment by Apollon77** [comment]
Bitte nicht "Repo" ... "Repository" ist der Begriff :-)

**Comment by GermanBluefox** [comment]
Repository aktualisieren ?

**Comment by Feuer-sturm** [comment]
Oder "Adapter auf Updates prüfen" / "Check adapter for updates".

Dann muss man nicht zwingend wissen was ein Repository ist ;-)

**Comment by Apollon77** [comment]
Ne das ist zu einseitig. Es können ja auch Adapter hinzukommen und wegfallen.

"Adapterinformationen aktualisieren"? oder sowas

**Comment by GermanBluefox** [comment]
"Check adapters for updates" implemented

**Comment by Chaot1** [comment]
Super gelöst - Danke!
