### ISSUE TITLE
It is not possible to create a data point in a folder structure that already existed before the update.

### ISSUE THREAD

**Issue by n3ucr0n** [ioBroker/ioBroker.admin#969]
I already have an existing folder structure under 0_userdata. After updating to Admin5, I can no longer create data points in this folder structure.

I only have the possibility to create another subfolder. Within this new folder I can create more data points. 
My wish would be that I can continue to use my existing folder structure. 

Is there a solution for this?

Thank you and best regards

![Unbenannt](https://user-images.githubusercontent.com/63336916/120164623-0df45300-c1fb-11eb-8b86-608d7c73f69a.JPG)

**Comment by GermanBluefox** [comment]
It is not a folder. It is "dummy folder"
Workaround is: create in "0_userdata.0" your "dummy" folder like "Alexa" and then (I hope) you can create inside it the new datapoints.

**Comment by n3ucr0n** [comment]
> It is not a folder. It is "dummy folder"
> Workaround is: create in "0_userdata.0" your "dummy" folder like "Alexa" and then (I hope) you can create inside it the new datapoints.

Thanks! The workaround worked. As you described, I only had to create the already existing dummy folders under "0_userdata.0" again with the exact same name. The existing folder structure remains, the dummy folders only get the type "Folder". after that it is also possible to create data points inside the folders
