### ISSUE TITLE
v5.1.5: certain dates are shown as "invalide" in object tab

### ISSUE THREAD

**Issue by HGlab01** [ioBroker/ioBroker.admin#972]
**Describe the bug**  
Certain dates, eg. 'Fri May 28 2021 04:23:41 GMT+0200' delivers in v5.1.5 'Invalide date' if using the role 'value.time' or 'date'. If using value some decimales are shown. In all cases 'number' was used as type.

**Repo**
```
let readDate = new Date ('Fri May 28 2021 04:23:41 GMT+0200');
this.log.info('readDate.getTime() ' + readDate.getTime());
await this.setStateAsync('aaa.test', readDate.getTime());
let getDate = await this.getStateAsync('aaa.test');
this.log.info('ReadState ' + getDate.val);
```

**Log**
```
2021-05-28 12:45:08.495 | info | readDate.getTime() 1622168621000
2021-05-28 12:45:08.510 | info | ReadState 1622168621000
```

State with role value.time:
![image](https://user-images.githubusercontent.com/54232526/119972657-c11e3b80-bfb2-11eb-9fa3-59ad600c7bf2.png)

State with role value:
![image](https://user-images.githubusercontent.com/54232526/119972772-e6ab4500-bfb2-11eb-8bd0-40a5eb9ded62.png)

With adapter version 4.2.1 no decimals are shown with role value and with role value.time a date is shown as expected.

**Versions:**  
 - Adapter version: 5.1.5
 - JS-Controller version: v3.3.11
 - Node version: v10.24.1
 - Operating system: Win10

**Comment by Apollon77** [comment]
Plese show the object definitions for the objects in question

**Comment by HGlab01** [comment]
```
{
  "common": {
    "name": "test",
    "desc": "Manually created",
    "role": "date",
    "type": "number",
    "read": true,
    "write": true,
    "def": 0
  },
  "type": "state",
  "_id": "test_jsonexplorer.0.aaa.test",
  "acl": {
    "object": 1632,
    "state": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1622524026461
}
```
