### ISSUE TITLE
Error when clicking on "Übersetzt von englisch"

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.admin#973]
**Describe the bug**  
When clicking on "Übersetzt von englisch":
![image](https://user-images.githubusercontent.com/69499563/120292392-8ffc7e80-c2c4-11eb-8bc6-5567c7eebdcb.png)

 ioBroker shows an Error Screen:
![image](https://user-images.githubusercontent.com/69499563/120292285-79eebe00-c2c4-11eb-88ad-f2df6a40f5e6.png)

**To Reproduce**  
1. Go to Z-Wave 2 Adapter in Adapter List
2. Click on "Übersetzt von englisch":
![image](https://user-images.githubusercontent.com/69499563/120292392-8ffc7e80-c2c4-11eb-8bc6-5567c7eebdcb.png)
3. See error

**Screenshots & Logfiles**  
Error Log from browser console:
`javascript: https://img.shields.io/lgtm/grade/javascript/g/AlCalzone/ioBroker.zwave2.svg?logo=lgtm&logoWidth=18 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
instrument.ts:129 Translate: english
instrument.ts:129 Translate: materialize
instrument.ts:129 Translate: compact
instrument.ts:129 TypeError: t.state.adapterNews[e].split is not a function
    at Markdown.js:628
    at Array.forEach (<anonymous>)
    at a.value (Markdown.js:626)
    at a.<anonymous> (Markdown.js:727)
    at hc (react-dom.production.min.js:131)
    at pi (react-dom.production.min.js:220)
    at jl (react-dom.production.min.js:259)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Sl (react-dom.production.min.js:252)
    at ml (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wa (react-dom.production.min.js:122)
    at Ga (react-dom.production.min.js:123)
    at Ua (react-dom.production.min.js:122)
    at hl (react-dom.production.min.js:237)
    at Object.enqueueSetState (react-dom.production.min.js:133)
    at a.m.setState (react.production.min.js:12)
    at Markdown.js:726`

**Versions:**  
 - Adapter version: 5.1.5
 - JS-Controller version: <js-controller-version> 
 - Node version: 12.22.1
 - Operating system: raspbian

**Comment by Feuer-sturm** [comment]
Admin 5.1.6

Reported bug is fixed with Admin 5.1.6 but "german" layout looks different than the english layout.
In addition there is no possibility to switch back from english to "german"

German:
![grafik](https://user-images.githubusercontent.com/25422320/120711710-fe596080-c4bf-11eb-90f0-9554208ef838.png)

English version:
![grafik](https://user-images.githubusercontent.com/25422320/120711929-424c6580-c4c0-11eb-8f59-8029523f7084.png)

**Comment by Feuer-sturm** [comment]
@GermanBluefox @Apollon77 Is my last comment a bug in admin as well or what is your expected behavior?

**Comment by GermanBluefox** [comment]
It is work as designed.

**Comment by Feuer-sturm** [comment]
Is not fixed yet (checked with admin 5.3.8)

**Comment by Feuer-sturm** [comment]
@GermanBluefox 
In the englisch version the sections "Information" and "Abzeichen" are still missing. The logo is differnt as well.
Admin 6.1.2

German
![grafik](https://user-images.githubusercontent.com/25422320/175369172-5c45f0f1-c022-4771-9e87-597af8c60f04.png)


English
![grafik](https://user-images.githubusercontent.com/25422320/175368965-8d9fe20d-228d-452a-9c37-88ad89184952.png)
