### ISSUE TITLE
keine Anzeige von History-Verlaufsdaten

### ISSUE THREAD

**Issue by ohle64** [ioBroker/ioBroker.admin#978]
In der neuen Oberfläche als auch in der alten werden unter Objekte - Datenpunkt xy - Zahnrad-Symbol keine Daten unter History-Verlaufsdaten angezeigt. Egal welchen Filter ich einstelle, die Verlaufsdaten bleiben leer. Daten sind im File aber vorhanden und werden auch im Diagramm-Reiter angezeigt.
Siehe: [https://forum.iobroker.net/topic/45569/history-keine-verlaufsdaten-anzeige?_=1622896442152](https://forum.iobroker.net/topic/45569/history-keine-verlaufsdaten-anzeige?_=1622896442152) 

**Versions:**  
 - Adapter version: <5.1.7>
 - JS-Controller version: <3.3.11>
 - Node version: <6.14.12>
 - Operating system: <ubuntu1804>

**Comment by thost96** [comment]
Hi, kann das nicht bestätigen. Bei mir werden im Admin sowohl in der neuen React UI als auch in der alten die Verlaufsdaten angezeigt. Meine Versionen: 

* Adapter version: 5.1.7 und 5.1.8
* JS-Controller version: 3.3.11
* Node version: 12.22.1 
* Operating system: debian / docker

Hast du den DP vielleicht mal gelöscht?

**Comment by ohle64** [comment]
Hallo,

 

bin jetzt auch auf Admin v5.1.8. Einige alte Datenpunkte haben keine Werte bei Verlaufsdaten – aber im Diagramm sind die Werte da. Ich habe jetzt mal bei einem anderen Datenpunkt die History eingeschaltet und da kamen auch gleich die Werte. Zur Not muss ich dann die History neu aktivieren bei den alten Datenpunkten. Ich beobachte das mal noch und melde mich dann. 

 

Gruß Frank

 

Von: Thorsten Reichelt ***@***.*** 
Gesendet: Montag, 7. Juni 2021 07:46
An: ioBroker/ioBroker.admin ***@***.***>
Cc: ohle64 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] keine Anzeige von History-Verlaufsdaten (#978)

 

Hi, kann das nicht bestätigen. Bei mir werden im Admin sowohl in der neuen React UI als auch in der alten die Verlaufsdaten angezeigt. Meine Versionen:

*	Adapter version: 5.1.7 und 5.1.8
*	JS-Controller version: 3.3.11
*	Node version: 12.22.1
*	Operating system: debian / docker

Hast du den DP vielleicht mal gelöscht?

**Comment by ohle64** [comment]
Hi,

 

ich habe gerade nochmal nachgesehen wegen der neu eingerichteten History-Abfrage – alle das gleiche Problem. Bei den neue Eingestellten steht jetzt ein Wert drin – mehr nicht. Etwas kurios: 16:49 Uhr steht da als Timestamp der Erfassung??? Sonst nur no data. Im Diagramm kann man mehrere Werte erkennen.

Sorry, ich versteh es nicht. Zugriffrechte können es nicht sein, sonst wäre im Diagramm auch nichts. Anzeigeproblem?

 

Das Löschen von einem Datenpunkt können wir ausschließen, es betriff alle eingestellten DP, also auch von den Adapter hue, deConz, Alexa2.0 usw.

Gruß Frank

 

Von: Thorsten Reichelt ***@***.*** 
Gesendet: Montag, 7. Juni 2021 07:46
An: ioBroker/ioBroker.admin ***@***.***>
Cc: ohle64 ***@***.***>; Author ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] keine Anzeige von History-Verlaufsdaten (#978)

 

Hi, kann das nicht bestätigen. Bei mir werden im Admin sowohl in der neuen React UI als auch in der alten die Verlaufsdaten angezeigt. Meine Versionen:

*	Adapter version: 5.1.7 und 5.1.8
*	JS-Controller version: 3.3.11
*	Node version: 12.22.1
*	Operating system: debian / docker

Hast du den DP vielleicht mal gelöscht?

**Comment by GermanBluefox** [comment]
Ich kann auch nicht reproduzieren.

**Comment by ohle64** [comment]
Hallo
Vielen Dank für eure Mithilfe und das Testen auf euren Systemen. 
Der Fehler war eine falsch datierte Datei im History Verzeichnis.
Besten Dank an alle Beteiligten

**Comment by nevermind2001** [comment]
> Hallo Vielen Dank für eure Mithilfe und das Testen auf euren Systemen. Der Fehler war eine falsch datierte Datei im History Verzeichnis. Besten Dank an alle Beteiligten

Hallo,

Danke für diesen Hinweis. Auch bei mir wurde bei "Verlaufsdaten" nichts angezeigt, obwohl Daten da waren. Ich habe dann im Verzeichnis /opt/iobroker/iobroker-data/history nachgesehen. Dort gab es einen Unterordner namens "133771211" (was ja keinen Sinn macht). Nachdem ich diesen Ordner gelöscht habe, waren die Verlaufsdaten im Admin wieder ersichtlich.
