### ISSUE TITLE
Question: How to find out, if admin runs with new react ui?

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.admin#979]
For some adjustments im my adapter if react ui is active, i used:
````javascript
socket.emit('getObject', 'system.adapter.admin.0', function(err, obj){
    if(!err && obj?.native?.react){
        isReact = true;
    }
}
````

But now, as far as i can see, the option native.react has changed to native.material. And over iobroker.pro the new react-ui doen't seem to work.

So what is the best practice to find out, if react-ui is active or not?

Many thanks

**Comment by sbormann** [comment]
Hi,
its for some design-adjustments, if react is active, inside admin_m.html


________________________________
Von: Bluefox ***@***.***>
Gesendet: Montag, 7. Juni 2021 09:02
An: ioBroker/ioBroker.admin ***@***.***>
Cc: Sebastian Bormann ***@***.***>; Mention ***@***.***>
Betreff: Re: [ioBroker/ioBroker.admin] Question: How to find out, if admin runs with new react ui? (#979)


@sbormann<https://github.com/sbormann> it is a wrong direction.
Why you need to know where is you config running?

**Comment by GermanBluefox** [comment]
`window.parent.adapterName === 'admin'`

**Comment by sbormann** [comment]
Perfect, thank you.

**Comment by Apollon77** [comment]
@sbormann DO you really want to strggle with two admin worlds? Admin 5 will become stable soon. Just make a new version and depend on Admin 5.1 and you can "just" be sure which admi version is there
