### ISSUE TITLE
Problem with Readme when Branch is main

### ISSUE THREAD

**Issue by gaudes** [ioBroker/ioBroker.admin#982]
**Describe the bug**  
See https://github.com/gaudes/ioBroker.slideshow/issues/85

**To Reproduce**  
Go to "Adapters" in Admin
Click the three points on Slideshow adapter
Click "open in new tab"
Wrong URL: https://github.com/gaudes/ioBroker.slideshow/main/README.md
Should be: https://github.com/gaudes/ioBroker.slideshow/blob/main/README.md

**Expected behavior**  
Correct link to readme should be opened.

**Screenshots & Logfiles**  
See issue See https://github.com/gaudes/ioBroker.slideshow/issues/85

**Versions:**  
 - Adapter version: 4.2.1
 - JS-Controller version: 3.2.16

**Additional context**

**Comment by GermanBluefox** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/4582016/121164580-f565e780-c84f-11eb-8c29-eac374f58728.png)

**Comment by jack-blackson** [comment]
@GermanBluefox  I have the same issue with one of my adapters - meteoalarm. Version is 2.0.4 ([Link](https://github.com/jack-blackson/ioBroker.meteoalarm/tarball/v2.0.4)) where I fixed the link, but still it uses the old one.

JS-Controller version: 3.3.15
Admin: 5.1.23

Shall I create a seperat issue for that?
