### ISSUE TITLE
Incorrect values for the number of adapters

### ISSUE THREAD

**Issue by DrBakterius** [ioBroker/ioBroker.admin#983]
If you are at the adapters and click on the circle to check for updates, then on the right side at 'Installed adapters' and 'Adapters updated in the last month' after each press a different value is displayed. With each update the original value is added.

See also: https://forum.iobroker.net/post/639945

**Comment by GermanBluefox** [comment]
Fixed in 5.1.9

**Comment by Feuer-sturm** [comment]
Admin 5.1.9

Issue is fixed on my system.
