### ISSUE TITLE
Aufruf #tab-users bricht ab

### ISSUE THREAD

**Issue by TbsBrggng** [ioBroker/ioBroker.admin#985]
Nach update auf Host 3.3.12 (admin 5.1.8) tritt der beigefügte Fehler bei dem Wechsel auf den Reiter "Benutzer" im iobroker-Admin auf.

[iobroker.local-1623139222951.log](https://github.com/ioBroker/ioBroker.admin/files/6614645/iobroker.local-1623139222951.log)

**Comment by GermanBluefox** [comment]
Will be fixed in 5.1.9
