### ISSUE TITLE
Checkboxen nicht sichtbar in Instanzen bei Auflösung von 1280x1024

### ISSUE THREAD

**Issue by SurfGargano** [ioBroker/ioBroker.admin#987]
In der React Version (admin 5.1.8)  sind Checkboxen nicht sichtbar in Instanzen bei Auflösung von 1280x1024
Die horizontal Scrollbar scrollt nicht nach links, so daß man nicht die Checkboxwn sieht.
![grafik](https://user-images.githubusercontent.com/70272783/121179769-61504c00-c860-11eb-906d-84de1101de2c.png)

Nur am Rande : für meinen Geschmack  finde ich die Icons in der Instanzenliste bei der React Version zu groß

**Comment by GermanBluefox** [comment]
Cannot reproduce.
![image](https://user-images.githubusercontent.com/4582016/121196015-6ae1b000-c870-11eb-92f2-c43db2e6a854.png)

What the device is that?

**Comment by SurfGargano** [comment]
Chrome , full screen
![grafik](https://user-images.githubusercontent.com/70272783/121199068-e80e2480-c872-11eb-82a2-3d1c263875a9.png)

![grafik](https://user-images.githubusercontent.com/70272783/121199384-2c99c000-c873-11eb-8b77-0ec318904c49.png)


if I change to not full screen, the checkboxes appeares.

![grafik](https://user-images.githubusercontent.com/70272783/121199544-50f59c80-c873-11eb-8a9a-2c928e9ecfcc.png)

**Comment by ice987987** [comment]
same issue on iPad:

![Animation](https://user-images.githubusercontent.com/69053781/121367389-9335e100-c93a-11eb-836b-ea70d9c32fe4.gif)

**Versions:**
Apple iPad Pro 12.9Zoll (iOS 14.6)
Admin: v5.1.9
JS-Controller version: v3.3.12
Node version: v12.22.1

**Comment by Apollon77** [comment]
And if you close the left menu bar?

**Comment by ice987987** [comment]
@Apollon77 
if I close the left menu bar, everything seems to be OK:

![Animation](https://user-images.githubusercontent.com/69053781/121376060-810b7100-c941-11eb-981d-7c31a0986f98.gif)

**Comment by MMeinhardt1** [comment]
@ice987987 hi, on my iPad Air 3rd Gen. all works fine. Very strange the apple devices.

**Comment by GermanBluefox** [comment]
Fixed in 5.1.10

**Comment by SurfGargano** [comment]
Still there in 5.1.9
![grafik](https://user-images.githubusercontent.com/70272783/125082834-f779cb00-e0c7-11eb-850c-e210e367f9ca.png)

**Comment by ice987987** [comment]
Error is fixed under following configurations:

**Versions:**
Apple iPad Pro 12.9Zoll (iOS 14.6)
Admin: v5.1.10
JS-Controller version: v3.3.12
Node version: v12.22.1

and

**Versions:**
Apple iPad Pro 12.9Zoll (iOS 14.6)
Admin: v5.1.10
JS-Controller version: v3.3.14
Node version: v12.22.2

Thanks!

**Comment by SurfGargano** [comment]
fixed in 5.1.10 desktop windows 10
Admin: v5.1.10
JS-Controller version: v3.3.14
