### ISSUE TITLE
WebSocket connection Error

### ISSUE THREAD

**Issue by MrDrache333** [ioBroker/ioBroker.admin#988]
**Describe the bug**  
When loading the UI-Tab Info, Adapters or Objects I got the following error and the Tab didn't load.

**To Reproduce**  
1. Install Admin 5.1.8
2. Open the Admin Interface
3. Click on Adapters, Info or Objects
4. Error

**Expected behavior**  
The clicked Tab should load normally

**Screenshots & Logfiles**  
`WebSocket connection to 'wss://192.168.178.122:8081/?sid=1623222968031&name=admin' failed: The operation couldn’t be completed. (kNWErrorDomainPOSIX error 40 - Message too long)
instrument.ts:129`
![Bildschirmfoto 2021-06-09 um 09 31 29](https://user-images.githubusercontent.com/22854641/121312270-82b74380-c905-11eb-9611-7744408640cd.jpg)
![Bildschirmfoto 2021-06-09 um 09 28 01](https://user-images.githubusercontent.com/22854641/121312280-83e87080-c905-11eb-986d-e7221d914ecf.jpg)

**Versions:**  
 - Adapter version: 5.1.8
 - JS-Controller version: 3.2.16
 - Node version: v12.22.1
 - Operating system: Raspberry Pi 4 Debian and Client to Connect macOS 12 Beta 1 with Safari 15.0

**Comment by GermanBluefox** [comment]
There is a bug about it, but from Apple no answer:
https://developer.apple.com/forums/thread/679576

**Comment by DutchmanNL** [comment]
Interesting I can’t reproduce this on my Mac and iOS devices

“ The web application sends a large amount of data (a database of items). If I make the database a lot smaller, it works without the error. Is it just that Safari's timeout is set extremely low so it won't work?”

@MrDrache333 do you have a lot of objects and states ? (I have 20k+ and 30 running adapters and all works)

**Comment by Apollon77** [comment]
This was an issue in ios 15 and new macOS Betas and solved since last udate of those ...

**Comment by backfisch88** [comment]
didn't work for me.... 
upgrade to node 14 was the answear for me

**Comment by Apollon77** [comment]
i do not understand how a nodejs update can fix a browser side issue? wft

**Comment by Leask** [comment]
The latest iOS 15 / macOS 12.0 beta fixed this issue.

**Comment by backfisch88** [comment]
> i do not understand how a nodejs update can fix a browser side issue? wft

Don’t get it but it works 😬😅

the new iOS update didn’t fix the problem for me. Just for fun i downgraded node. Did NOT work either
