### ISSUE TITLE
Multihost javascript update notification still shows after update

### ISSUE THREAD

**Issue by amg666** [ioBroker/ioBroker.admin#989]
My system showed a "2" at host menu (because an update is available for 2 systems, master and slave). After update of master system shows "1" (because of available update for slave).
After update of slave the "1" does not disappear, see picture. 
![grafik](https://user-images.githubusercontent.com/45561610/121317157-505c1500-c90a-11eb-9048-5e72a1034333.png)

After reload of admin adapter or refresh of browser the display is correct (no updates shown at host menu)

**Comment by Feuer-sturm** [comment]
Master Admin 5.1.8 and js-controller 3.3.12
Slave Admin 5.1.8  and js-controller 3.3.11 to 3.3.12
Same behavior on my sytstem as wel

**Comment by Apollon77** [comment]
I think the "badge" on the tab name needs to be recalculated as soon as new host infos are loaded

**Comment by Feuer-sturm** [comment]
Admin 5.3.1

Slave js-controller update was availalbe. Update was done
Swithcing from Host to a different menu and then back to host
Host overview is shown correctly. Master and Slave are up to date but the (1) is still there
After a page reload everything is fine and the number (1) is not there any more.

![grafik](https://user-images.githubusercontent.com/25422320/155861432-4846a9ba-1ca5-4579-bcb5-ba888d56eafe.png)

**Comment by Feuer-sturm** [comment]
Admin 6.1.5
Issue is still active with current admin version.

**Comment by GermanBluefox** [comment]
Please test with 6.1.7

**Comment by Feuer-sturm** [comment]
Is fixed with Admin 6.1.9
