### ISSUE TITLE
Object filter by name, does not display data points

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/ioBroker.admin#990]
When I filter the objects by name, only the folder is displayed and not the data points it contains.

Host: **3.3.11**
Admin: **5.1.8**

https://user-images.githubusercontent.com/19333515/121329716-c0bc6380-c915-11eb-9441-d0defd4b0d24.mp4

**Comment by Apollon77** [comment]
Does the sattes also contain the "name" ? If not they are not shown. "Filter "means really "FIltering"

**Comment by o0shojo0o** [comment]
Yes they don't of course, but in the old admin it worked like that.

**Comment by GermanBluefox** [comment]
Work as designed. Filter means hide all entries, that do not contain the given text

**Comment by o0shojo0o** [comment]
It's ok, I just wanted to point out that there is a difference here in the function to the old admin.
More I did not intend here...

**Comment by asgothian** [comment]
> Work as designed. Filter means hide all entries, that do not contain the given text

This interpretation of the filter feature does not match my expectation. If i filter on something which returns a device i am interested in seeing the states of the device, not just the device itself.

A.

**Comment by GermanBluefox** [comment]
Try 5.1.11
