### ISSUE TITLE
admin 5.1.9 can not create a datapoint

### ISSUE THREAD

**Issue by gitiegit** [ioBroker/ioBroker.admin#991]
cannot create a data point, it is only offered as a selection "create directory"
![image](https://user-images.githubusercontent.com/24435657/121399385-a9ea3100-c956-11eb-9133-9c92262c1c63.png)

my system:
iobroker-ubuntu
Platform
linux
Betriebssystem
linux
Architektur
x64
CPUs
4
Geschwindigkeit
1497 MHz
Modell
Common KVM processor
RAM
2.87 GB
System Betriebszeit
02:50:19
Node.js
v12.22.1
NPM
6.14.12
Festplatte Größe
31.37 GB
Festplatte frei
15.53 GB
Anzahl der Adapter
419
Betriebszeit
01:49:31
Aktive Instanzen
29
location
/opt/iobroker/
Hostname
iobroker-ubuntu

**Comment by Feuer-sturm** [comment]
@gitiegit 
Please try the following:

Goto 0_userdata.0 and then go with the mouse over the (+) and you can see what you can create:
![grafik](https://user-images.githubusercontent.com/25422320/121414190-b5ddef00-c966-11eb-984a-f3728c287501.png)


Deactivate the status
![grafik](https://user-images.githubusercontent.com/25422320/121415496-16b9f700-c968-11eb-8bae-c5c927ec0b35.png)

I think in your case in your selected entry "Stromzähler" there is nothing in the coloum "Typ" like here: 
![grafik](https://user-images.githubusercontent.com/25422320/121415673-4d900d00-c968-11eb-8905-574953549e51.png)

This is the reason why you can not create a datapoint or something else.
If the "Typ" is Device, channel, Folder than you can create new objects as mentioned in the image in the beginning.

**Comment by Feuer-sturm** [comment]
Here is a discussion with the same topi: https://github.com/ioBroker/ioBroker.admin/issues/980
