### ISSUE TITLE
admin5.x History not shown in 'Benutzerdefinierte Einstellungen' 

### ISSUE THREAD

**Issue by zokkai** [ioBroker/ioBroker.admin#994]
To set up history für objekts (like temperature) admin 5.x does not show history in 'Benutzerdefinierte Einstellungen'
works with admin.4x

in Admin5
Objekts -> Device -> Datapoint - Benutzerdefinierte Einstellungen

Error message:  Cannot load jsonConfig of history: Not exists

**Versions:**  
 - Adapter version: admin 5.19
 - JS-Controller version: 3.3.11
 - Node version: 14.17.0
 - Operating system: Raspbian buster

![image](https://user-images.githubusercontent.com/49320831/121481649-a09bab80-c9cc-11eb-87d1-a3af43f77260.png)

![image](https://user-images.githubusercontent.com/49320831/121481978-f40df980-c9cc-11eb-8601-d28c4f772c0a.png)

**Comment by Apollon77** [comment]
Upgrade history Adapter please, then it re-appears!

**Comment by zokkai** [comment]
Thanks for your reply. 
My problem seems to be more deeper.
reinstalling/upgrading adapters show following errors that might not related to admin or history adapter but any help woul be preciated 

------schnipp------
iob add history.0
NPM version: 6.14.13
npm install iobroker.history@1.9.12 --loglevel error --prefix "/opt/iobroker" (System call)
../authenticate_pam.cc: In function ‘void after_doing_auth(uv_work_t*, int)’:
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc:107:87: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(m->callback), 1, args);
                                                                                       ^
In file included from ../authenticate_pam.cc:23:
../../nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../authenticate_pam.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Authenticate(Nan::NAN_METHOD_ARGS_TYPE)’:
../authenticate_pam.cc:147:83: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’
   Local<Value> res = options->Get(Nan::New<String>("serviceName").ToLocalChecked());
                                                                                   ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
../authenticate_pam.cc:150:69: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    serviceName->WriteUtf8(m->serviceName, sizeof(m->serviceName) - 1);
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:152:69: error: no matching function for call to ‘v8::Array::Get(v8::Local<v8::String>)’
   res = options->Get(Nan::New<String>("remoteHost").ToLocalChecked());
                                                                     ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3717:43: note:   candidate expects 2 arguments, 1 provided
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                           ^~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3720:43: note:   candidate expects 2 arguments, 1 provided
../authenticate_pam.cc:155:66: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
    remoteHost->WriteUtf8(m->remoteHost, sizeof(m->remoteHost) - 1);
                                                                  ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:160:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  username->WriteUtf8(m->username, sizeof(m->username) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc:161:58: error: no matching function for call to ‘v8::String::WriteUtf8(char [128], unsigned int)’
  password->WriteUtf8(m->password, sizeof(m->password) - 1);
                                                          ^
In file included from /home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note: candidate: ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
       ^~~~~~~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/v8.h:3037:7: note:   no known conversion for argument 1 from ‘char [128]’ to ‘v8::Isolate*’
../authenticate_pam.cc: At global scope:
../authenticate_pam.cc:170:11: error: variable or field ‘init’ declared void
 void init(Handle<Object> exports) {
           ^~~~~~
../authenticate_pam.cc:170:11: error: ‘Handle’ was not declared in this scope
../authenticate_pam.cc:170:11: note: suggested alternative: ‘rand_r’
 void init(Handle<Object> exports) {
           ^~~~~~
           rand_r
../authenticate_pam.cc:170:24: error: expected primary-expression before ‘>’ token
 void init(Handle<Object> exports) {
                        ^
../authenticate_pam.cc:170:26: error: ‘exports’ was not declared in this scope
 void init(Handle<Object> exports) {
                          ^~~~~~~
In file included from ../../nan/nan.h:56,
                 from ../authenticate_pam.cc:23:
../authenticate_pam.cc:175:31: error: ‘init’ was not declared in this scope
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
../authenticate_pam.cc:175:31: note: suggested alternative: ‘int’
 NODE_MODULE(authenticate_pam, init);
                               ^~~~
/home/iobroker/.cache/node-gyp/14.17.0/include/node/node.h:758:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../authenticate_pam.cc:175:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(authenticate_pam, init);
 ^~~~~~~~~~~
make: *** [authenticate_pam.target.mk:109: Release/obj.target/authenticate_pam/authenticate_pam.o] Fehler 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.10.17-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/authenticate-pam
gyp ERR! node -v v14.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
----schnapp--------

any idea or hint? semms to be compiling. tried already reinstalling npm/node/nodejs with same result.

Adapter version: admin 5.19
JS-Controller version: 3.3.11
Node version: 14.17.0
Operating system: Raspbian buster

thanks

**Comment by Apollon77** [comment]
cutted too early. normally these are just warmings on optional dependencies and no real errors.

**Comment by zokkai** [comment]
if this is the case the problem with not showing history in 'Benutzerdefinierte Einstellungen' still exist.

steps i did so far:
- deinstalling history
- installing adapter again
- adding new instance to history adapter

**Comment by Apollon77** [comment]
which version you have installed of history? YOu need at least 1.9.13 (2021-04-19)

**Comment by zokkai** [comment]
arrgghh....
fixed!! 

thanks a lot!

might be worth to mention it somehow/somewhere

**Comment by Apollon77** [comment]
We will prepare a full list of connected adapter updates when we prepare stable release of admin 5-1
