### ISSUE TITLE
farben im log (protokoll)

### ISSUE THREAD

**Issue by sjfm-design** [ioBroker/ioBroker.admin#995]
die farben im log sollten nicht nach adapter, sondern nach info / debug / warn / error gestaltet werden.
weis, grün, orange, rot oder so.
bei adapter farbe übersieht man so leicht ein warn, oder error.

**Comment by Apollon77** [comment]
ich wäre auch dabei bestimmte farben wie gelb und rot und deren direkt abstufungen eher nicht zu nutzen als Hintergrundfarben

**Comment by Apollon77** [comment]
PS: Und für Warn/Error gibts oben die Auswahl nur Error u.a. anzuzeigen!

**Comment by sjfm-design** [comment]
ok, damit könnte ich auch leben. gelb und rot impliziert halt, aus macht der gewohnheit, warn und error bei mir. allerdings schränkt das die auswahl stark ein, da beide grundfarben in den farbsystemen sind.
@Apollon77 die auswahl oben ist mir bekannt.

**Comment by ihavenonick** [comment]
Die Identifizierung der Adapter ist mittlerweile schön mit Icon erledigt, somit macht eine weitere Zuordnung über die Farbe gar kein Sinn mehr und man sollte sich gerade im Log auf so wenig wie möglich Farben einigen, da es hier erst mal relevant ist zu erkennen, dass es ein Problem gibt und dann welcher Adapter das verursacht und das geht eben nur in dem man das Log **nicht** bunt wie Windows XP gestaltet.

**Comment by arteck** [comment]
ich würde vorschlagen macht es per Parameter... die die es bunt wollen können es so haben, für diejenigen die es nur schwarz weiss wollen.. checkbox an im admin und gut ist..

**Comment by sigi2345** [comment]
> ich würde vorschlagen macht es per Parameter... die die es bunt wollen können es so haben, für diejenigen die es nur schwarz weiss wollen.. checkbox an im admin und gut ist..

Jupp, in ein Log gehört keine Farbe. Meine persönliche Meinung.

**Comment by ihavenonick** [comment]
S/W ist gleich wieder zu viel zurück. Rot für Errors wäre schon OK ;)

**Comment by Feuer-sturm** [comment]
Mit Admin 5.1.10 gibt es jetzt die Möglichkeit die Farben im Log ein und auszuschalten.

![grafik](https://user-images.githubusercontent.com/25422320/125161430-a8dd3700-e182-11eb-82ed-49d1f8584fd9.png)
