### ISSUE TITLE
show full text in column "description" with hover

### ISSUE THREAD

**Issue by SabineTobi** [ioBroker/ioBroker.admin#996]
For most adapters, the description is truncated. It would be convenient if the full text were displayed e.g. by means of "hover".

auf Deutsch: bei den meisten Adaptern ist ja die Beschreibung abgeschnitten. Es wäre praktisch, wenn der volle Text zB. mittels "hover" angezeigt würde.

**Comment by GermanBluefox** [comment]
Do you mean "Name" column?

**Comment by SabineTobi** [comment]
I mean the column "Description" ("Beschreibung" in german). Here is a screenshot:
<img width="284" alt="Bildschirmfoto 2021-06-15 um 06 45 13" src="https://user-images.githubusercontent.com/20378476/121994379-74ee3c00-cda5-11eb-8c60-d16fe109a451.png">
You see the description for the Admin-Adapter truncated "**Die Konfiguration von ioBroker über das ...**"
I think, it would be a good idea to sow the full descruption in a "hover" window, as you do it with the cloud-symbol.

**Comment by SabineTobi** [comment]
sorry, I accidentally closed the issue

**Comment by GermanBluefox** [comment]
Fixed in 5.1.10

**Comment by Feuer-sturm** [comment]
Admin 5.1.11

Issue is fixed
![grafik](https://user-images.githubusercontent.com/25422320/125686657-266b738f-2b3c-4c0d-a0bf-38a811913221.png)
